EMil: TestSharedObjectAllocatorFixedSize.cpp File Reference
TestSharedObjectAllocatorFixedSize.cpp File Reference
Classes
class SharedObjectAllocatorFixedSizeTest
Typedefs
using AllocatorMySharedObject = infra::SharedObjectAllocator< infra::MonitoredConstructionObject, void(infra::ConstructionMonitorMock &)>
Functions
TEST_F (SharedObjectAllocatorFixedSizeTest, allocate_one_object)
TEST_F (SharedObjectAllocatorFixedSizeTest, when_allocation_fails_empty_SharedPtr_is_returned)
TEST_F (SharedObjectAllocatorFixedSizeTest, object_is_destructed_but_not_deallocated_while_WeakPtr_has_a_reference)
Typedef Documentation
AllocatorMySharedObject
using AllocatorMySharedObject = infra::SharedObjectAllocator<infra::MonitoredConstructionObject, void(infra::ConstructionMonitorMock&)>
Definition at line 6 of file TestSharedObjectAllocatorFixedSize.cpp.
Function Documentation
TEST_F() [1/3]
TEST_F (SharedObjectAllocatorFixedSizeTest , allocate_one_object)
Definition at line 15 of file TestSharedObjectAllocatorFixedSize.cpp.
References EXPECT_TRUE().
 {
     AllocatorMySharedObject::UsingAllocator<infra::SharedObjectAllocatorFixedSize>::WithStorage<2> allocator;
     void* savedObject;
     EXPECT_CALL(objectConstructionMock, Construct(testing::_)).WillOnce(testing::SaveArg<0>(&savedObject));
     infra::SharedPtr<infra::MonitoredConstructionObject> object = allocator.Allocate(objectConstructionMock);
     EXPECT_TRUE(static_cast<bool>(object));
     EXPECT_CALL(objectConstructionMock, Destruct(savedObject));
 }
TEST_F() [2/3]
TEST_F (SharedObjectAllocatorFixedSizeTest , when_allocation_fails_empty_SharedPtr_is_returned)
Definition at line 26 of file TestSharedObjectAllocatorFixedSize.cpp.
References EXPECT_FALSE().
 {
     infra::SharedObjectAllocatorFixedSize<infra::MonitoredConstructionObject, void(infra::ConstructionMonitorMock&)>::WithStorage<0> allocator;
     infra::SharedPtr<infra::MonitoredConstructionObject> object = allocator.Allocate(objectConstructionMock);
     EXPECT_FALSE(static_cast<bool>(object));
 }
TEST_F() [3/3]
TEST_F (SharedObjectAllocatorFixedSizeTest , object_is_destructed_but_not_deallocated_while_WeakPtr_has_a_reference)
Definition at line 34 of file TestSharedObjectAllocatorFixedSize.cpp.
References EXPECT_EQ().
 {
     infra::SharedObjectAllocatorFixedSize<infra::MonitoredConstructionObject, void(infra::ConstructionMonitorMock&)>::WithStorage<1> allocator;
     infra::WeakPtr<infra::MonitoredConstructionObject> weakObject;
     {
         EXPECT_CALL(objectConstructionMock, Construct(testing::_));
         infra::SharedPtr<infra::MonitoredConstructionObject> object = allocator.Allocate(objectConstructionMock);
         weakObject = object;
         EXPECT_CALL(objectConstructionMock, Destruct(testing::_));
     }
     testing::Mock::VerifyAndClearExpectations(&objectConstructionMock);
     EXPECT_EQ(nullptr, allocator.Allocate(objectConstructionMock));
 }