EMil: infra::MemoryRange< T > Class Template Reference
infra::MemoryRange< T > Class Template Reference
#include <MemoryRange.hpp>
Public Member Functions
MemoryRange ()
MemoryRange (T *begin, T *end)
template<class U >
MemoryRange (const MemoryRange< U > &other)
template<class T2 , std::size_t N>
constexpr MemoryRange (const std::array< T2, N > &array)
template<class T2 , std::size_t N>
MemoryRange (std::array< T2, N > &array)
template<class T2 >
MemoryRange (const std::vector< T2 > &vector)
template<class T2 >
MemoryRange (std::vector< T2 > &vector)
bool empty () const
std::size_t size () const
T * begin () const
const T * cbegin () const
T * end () const
const T * cend () const
T & operator[] (std::size_t index) const
template<class U >
bool operator== (const MemoryRange< U > &rhs) const
template<class U >
bool operator!= (const MemoryRange< U > &rhs) const
T & front () const
T & back () const
bool contains (const T *element) const
bool contains_or_end (const T *element) const
void clear ()
void pop_front (std::size_t num=1)
void pop_back (std::size_t num=1)
void shrink_from_front_to (std::size_t newSize)
void shrink_from_back_to (std::size_t newSize)
Private Attributes
T * beginElement
T * endElement
Detailed Description
template<class T>
class infra::MemoryRange< T >
Definition at line 15 of file MemoryRange.hpp.
Constructor & Destructor Documentation
MemoryRange() [1/7]
template<class T > infra::MemoryRange< T >::MemoryRange ()
Definition at line 122 of file MemoryRange.hpp.
         : beginElement(nullptr)
         , endElement(nullptr)
     {}
MemoryRange() [2/7]
template<class T> infra::MemoryRange< T >::MemoryRange (T * begin, T * end)
Definition at line 128 of file MemoryRange.hpp.
         : beginElement(begin)
         , endElement(end)
     {}
MemoryRange() [3/7]
template<class T > template<class U > infra::MemoryRange< T >::MemoryRange (const MemoryRange< U > & other)
Definition at line 135 of file MemoryRange.hpp.
         : beginElement(other.begin())
         , endElement(other.end())
     {}
MemoryRange() [4/7]
template<class T > template<class T2 , std::size_t N> constexpr infra::MemoryRange< T >::MemoryRange (const std::array< T2, N > & array)
Definition at line 142 of file MemoryRange.hpp.
         : beginElement(N != 0 ? &array.front() : nullptr)
         , endElement(N != 0 ? &array.front() + array.size() : nullptr)
     {}
MemoryRange() [5/7]
template<class T > template<class T2 , std::size_t N> infra::MemoryRange< T >::MemoryRange (std::array< T2, N > & array)
Definition at line 149 of file MemoryRange.hpp.
         : beginElement(array.data())
         , endElement(array.data() + array.size())
     {}
MemoryRange() [6/7]
template<class T > template<class T2 > infra::MemoryRange< T >::MemoryRange (const std::vector< T2 > & vector)
Definition at line 156 of file MemoryRange.hpp.
         : beginElement(vector.data())
         , endElement(vector.data() + vector.size())
     {}
MemoryRange() [7/7]
template<class T > template<class T2 > infra::MemoryRange< T >::MemoryRange (std::vector< T2 > & vector)
Definition at line 163 of file MemoryRange.hpp.
         : beginElement(vector.data())
         , endElement(vector.data() + vector.size())
     {}
Member Function Documentation
back()
template<class T > T & infra::MemoryRange< T >::back () const
Definition at line 232 of file MemoryRange.hpp.
Referenced by infra::Asn1Formatter::AddBigNumber().
     {
         return *(endElement - 1);
     }
begin()
template<class T > T * infra::MemoryRange< T >::begin () const
Definition at line 181 of file MemoryRange.hpp.
Referenced by services::CertificatesMbedTls::AddCertificateAuthority(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::AddFromInterrupt(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::assign(), infra::BoundedStringBase< char >::AssignToRange(), application::UpgradePackBuilder::AssignZeroFilled(), services::ConfigurationBlobImpl::BlobIsValid(), infra::BoundedStringBase< char >::BoundedStringBase(), infra::ByteRangeAsString(), application::ImageSignerEcDsa::CalculateSignature(), application::ImageSignerRsa::CalculateSignature(), application::ImageEncryptorXtea::CheckDecryption(), application::ImageEncryptorAes::CheckDecryption(), application::ImageSignerEcDsa::CheckSignature(), application::ImageSignerRsa::CheckSignature(), infra::ConstCastMemoryRange(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Consume(), infra::ContentsEqual(), infra::BoundedDeque< decltype(buffer)>::contiguous_range(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::ContiguousRange(), infra::Copy(), services::ConnectionMbedTls::DataReceived(), application::DecryptorAesMbedTls::DecryptorAesMbedTls(), application::DecryptorAesTiny::DecryptorAesTiny(), application::DecryptorXtea::DecryptorXtea(), infra::JsonInputStreamReader::Extract(), infra::StringInputStreamReader::Extract(), infra::StdStringInputStreamReader::Extract(), infra::StdVectorInputStreamReader::Extract(), infra::ByteInputStreamReader::Extract(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Full(), application::ImageAuthenticatorHmac::GenerateMac(), hal::SynchronousRandomDataGeneratorWin::GenerateRandomData(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Get(), infra::StdStringOutputStreamWriter::Insert(), infra::IoOutputStreamWriter::Insert(), infra::StringOutputStreamWriter::Insert(), infra::ByteOutputStreamWriter::Insert(), services::ConnectionMbedTls::StreamWriterMbedTls::Insert(), infra::IntersectingRange(), application::VerifierRsa::IsValid(), application::VerifierEcDsa::IsValid(), infra::MakeVector(), infra::MemoryRange< infra::StaticStorage< infra::detail::BoundedListNode< T > > >::operator==(), infra::operator==(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::operator[](), infra::ByteInputStreamReader::Peek(), services::ConfigurationBlobImpl::PrepareBlobForWriting(), infra::PrintTo(), infra::ByteInputStreamReader::Processed(), infra::ByteOutputStreamWriter::Processed(), infra::ReinterpretCastMemoryRange(), infra::ByteInputStreamReader::Remaining(), infra::ByteOutputStreamWriter::Remaining(), infra::ByteOutputStreamWriter::Reserve(), infra::StringOutputStreamWriter::RestoreState(), infra::ByteOutputStreamWriter::RestoreState(), infra::StringOutputStreamWriter::SaveState(), infra::ByteOutputStreamWriter::SaveState(), application::ImageEncryptorXtea::Secure(), application::ImageEncryptorAes::Secure(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Size(), services::ConnectionMbedTls::SslReceive(), services::ConnectionMbedTls::TrySend(), and infra::VolatileCastMemoryRange().
     {
         return beginElement;
     }
cbegin()
template<class T > const T * infra::MemoryRange< T >::cbegin () const
Definition at line 187 of file MemoryRange.hpp.
     {
         return beginElement;
     }
cend()
template<class T > const T * infra::MemoryRange< T >::cend () const
Definition at line 199 of file MemoryRange.hpp.
Referenced by services::CertificatesMbedTls::WriteOwnCertificate().
     {
         return endElement;
     }
clear()
template<class T > void infra::MemoryRange< T >::clear ()
Definition at line 250 of file MemoryRange.hpp.
Referenced by services::ConnectionSerial::StateConnected::Reset().
     {
         beginElement = nullptr;
         endElement = nullptr;
     }
contains()
template<class T> bool infra::MemoryRange< T >::contains (const T * element) const
Definition at line 238 of file MemoryRange.hpp.
     {
         return element >= beginElement && element < endElement;
     }
contains_or_end()
template<class T> bool infra::MemoryRange< T >::contains_or_end (const T * element) const
Definition at line 244 of file MemoryRange.hpp.
     {
         return element >= beginElement && element <= endElement;
     }
empty()
template<class T > bool infra::MemoryRange< T >::empty () const
Definition at line 169 of file MemoryRange.hpp.
Referenced by services::CyclicStore::Add(), infra::Asn1Formatter::AddBigNumber(), infra::BoundedDequeInputStreamReader::Extract(), infra::StreamWriterPrintF::Insert(), infra::Asn1SequenceIterator::operator++(), infra::operator>>(), services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent(), services::ConnectionMbedTls::SslReceive(), services::SynchronousFlashQuadSpi::WriteBuffer(), services::SynchronousFlashSpi::WriteBuffer(), services::FlashSpi::WriteBuffer(), and services::FlashQuadSpi::WriteBufferSequence().
     {
         return beginElement == endElement;
     }
end()
template<class T > T * infra::MemoryRange< T >::end () const
Definition at line 193 of file MemoryRange.hpp.
Referenced by infra::QueueForOneReaderOneIrqWriter< uint8_t >::AddFromInterrupt(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::assign(), application::ImageSignerEcDsa::CalculateSignature(), infra::ConstCastMemoryRange(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Consume(), infra::ContentsEqual(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::ContiguousRange(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Full(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Get(), infra::IoOutputStreamWriter::Insert(), services::ConnectionMbedTls::StreamWriterMbedTls::Insert(), infra::IntersectingRange(), infra::MakeVector(), infra::Asn1SequenceIterator::operator++(), infra::MemoryRange< infra::StaticStorage< infra::detail::BoundedListNode< T > > >::operator==(), infra::operator==(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::operator[](), infra::ReinterpretCastMemoryRange(), infra::ByteInputStreamReader::Remaining(), infra::ByteOutputStreamWriter::Remaining(), infra::StringOutputStreamWriter::RestoreState(), infra::ByteOutputStreamWriter::RestoreState(), infra::ByteOutputStreamWriter::SaveState(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Size(), services::ConnectionMbedTls::SslReceive(), and infra::VolatileCastMemoryRange().
     {
         return endElement;
     }
front()
template<class T > T & infra::MemoryRange< T >::front () const
Definition at line 226 of file MemoryRange.hpp.
Referenced by infra::Asn1SequenceIterator::MakeValue(), infra::operator>>(), and services::ConnectionSerial::StateConnectedSendingContent::SendEscapedContent().
     {
         return *beginElement;
     }
operator!=()
template<class T > template<class U > bool infra::MemoryRange< T >::operator!= (const MemoryRange< U > & rhs) const
Definition at line 220 of file MemoryRange.hpp.
     {
         return !(*this == rhs);
     }
operator==()
template<class T > template<class U > bool infra::MemoryRange< T >::operator== (const MemoryRange< U > & rhs) const
Definition at line 213 of file MemoryRange.hpp.
     {
         return begin() == rhs.begin() && end() == rhs.end();
     }
operator[]()
template<class T > T & infra::MemoryRange< T >::operator[] (std::size_t index) const
Definition at line 205 of file MemoryRange.hpp.
     {
         assert(index < size());
         return *(begin() + index);
     }
pop_back()
template<class T > void infra::MemoryRange< T >::pop_back (std::size_t num = 1)
Definition at line 264 of file MemoryRange.hpp.
Referenced by infra::Asn1Formatter::AddBigNumber(), and infra::DiscardTail().
     {
         assert(num <= size());
         endElement -= num;
     }
pop_front()
template<class T > void infra::MemoryRange< T >::pop_front (std::size_t num = 1)
Definition at line 257 of file MemoryRange.hpp.
Referenced by infra::DiscardHead(), infra::BoundedDequeInputStreamReader::Extract(), infra::ByteInputStreamReader::ExtractContiguousRange(), infra::StreamWriterPrintF::Insert(), infra::Asn1SequenceIterator::MakeValue(), infra::operator>>(), services::SynchronousFlashQuadSpi::PageProgram(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::SynchronousFlashSpi::PageProgram(), and services::FlashSpi::PageProgram().
     {
         assert(num <= size());
         beginElement += num;
     }
shrink_from_back_to()
template<class T > void infra::MemoryRange< T >::shrink_from_back_to (std::size_t newSize)
Definition at line 278 of file MemoryRange.hpp.
Referenced by infra::JsonInputStreamReader::Extract(), infra::LimitedStreamReader::Extract(), infra::StringInputStreamReader::Extract(), infra::StdStringInputStreamReader::Extract(), infra::StdVectorInputStreamReader::Extract(), infra::ByteInputStreamReader::Extract(), infra::StringInputStreamReader::ExtractContiguousRange(), infra::StdStringInputStreamReader::ExtractContiguousRange(), infra::StdVectorInputStreamReader::ExtractContiguousRange(), infra::ByteInputStreamReader::ExtractContiguousRange(), infra::Head(), infra::LimitedStreamWriter::Insert(), services::StreamWriterOnSerialCommunication::Insert(), infra::StringOutputStreamWriter::Insert(), infra::ByteOutputStreamWriter::Insert(), infra::StringOutputStreamWriter::Reserve(), infra::ByteOutputStreamWriter::Reserve(), and application::SecondStageToRamLoader::TryLoadImage().
     {
         if (newSize < size())
             endElement = beginElement + newSize;
     }
shrink_from_front_to()
template<class T > void infra::MemoryRange< T >::shrink_from_front_to (std::size_t newSize)
Definition at line 271 of file MemoryRange.hpp.
Referenced by infra::Tail().
     {
         if (newSize < size())
             beginElement = endElement - newSize;
     }
size()
template<class T > std::size_t infra::MemoryRange< T >::size () const
Definition at line 175 of file MemoryRange.hpp.
Referenced by services::CyclicStore::Add(), infra::Asn1Formatter::AddBigNumber(), services::CertificatesMbedTls::AddCertificateAuthority(), infra::Asn1Formatter::AddObjectId(), services::CyclicStore::AddPartial(), infra::Asn1Formatter::AddSerial(), infra::BoundedStringBase< char >::AssignToRange(), application::UpgradePackBuilder::AssignZeroFilled(), infra::ByteInputStreamReader::Available(), infra::ByteOutputStreamWriter::Available(), services::ConfigurationBlobImpl::BlobIsValid(), infra::ByteRangeAsString(), application::ImageSignerEcDsa::CalculateSignature(), application::ImageSignerRsa::CalculateSignature(), application::ImageSignerEcDsa::CheckSignature(), application::ImageSignerRsa::CheckSignature(), services::ConfigurationBlobImpl::ConfigurationBlobImpl(), services::ConnectionSerial::StateConnected::ContentReceived(), infra::ContentsEqual(), services::ConnectionSerial::StateConnected::ContentSizeToSend(), infra::BoundedDeque< decltype(buffer)>::contiguous_range(), infra::Copy(), services::ConnectionSerial::StateConnected::CopyEscapedContent(), services::ConnectionMbedTls::DataReceived(), application::DecryptorAesMbedTls::DecryptorAesMbedTls(), application::DecryptorXtea::DecryptorXtea(), infra::DiscardHead(), infra::DiscardTail(), infra::ByteInputStreamReader::Empty(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::EmptySize(), infra::JsonInputStreamReader::Extract(), infra::LimitedStreamReader::Extract(), infra::StringInputStreamReader::Extract(), infra::CountingStreamReader::Extract(), infra::StdStringInputStreamReader::Extract(), infra::StdVectorInputStreamReader::Extract(), infra::BoundedDequeInputStreamReader::Extract(), infra::ByteInputStreamReader::Extract(), services::ConnectionSerial::SerialConnectionStreamReader::Extract(), infra::LimitedStreamReader::ExtractContiguousRange(), infra::StringInputStreamReader::ExtractContiguousRange(), infra::StdStringInputStreamReader::ExtractContiguousRange(), infra::BoundedDequeInputStreamReader::ExtractContiguousRange(), infra::ByteInputStreamReader::ExtractContiguousRange(), services::ConnectionSerial::SerialConnectionStreamReader::ExtractContiguousRange(), infra::TextOutputStream::FormatArgs(), application::ImageAuthenticatorHmac::GenerateMac(), hal::SynchronousRandomDataGeneratorWin::GenerateRandomData(), infra::StreamWriterPrintF::Insert(), infra::LimitedStreamWriter::Insert(), infra::StdStringOutputStreamWriter::Insert(), infra::StringOutputStreamWriter::Insert(), infra::ByteOutputStreamWriter::Insert(), services::ConnectionMbedTls::StreamWriterMbedTls::Insert(), application::VerifierEcDsa::IsValid(), application::VerifierRsa::IsValid(), services::ConnectionSerial::MaxSendStreamSize(), infra::operator==(), services::SynchronousFlashQuadSpi::PageProgram(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::SynchronousFlashSpi::PageProgram(), services::FlashSpi::PageProgram(), infra::ByteInputStreamReader::Peek(), infra::PrintTo(), infra::ProtoFormatter::PutBytes(), infra::ProtoFormatter::PutLengthDelimitedField(), services::SynchronousFlashRegion::ReadBuffer(), services::FlashRegion::ReadBuffer(), infra::StringOutputStreamWriter::Reserve(), infra::ByteOutputStreamWriter::Reserve(), infra::StringOutputStreamWriter::RestoreState(), infra::EventDispatcherWorkerImpl::Schedule(), application::ImageEncryptorXtea::Secure(), application::ImageEncryptorAes::Secure(), services::ConnectionSerial::StateConnectedSendingContent::SendEscapedContent(), services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent(), services::StreamEchoConnection::SendStreamAvailable(), services::ConnectionMbedTls::SslReceive(), services::ConnectionMbedTls::SslSend(), infra::EventDispatcherWorkerImpl::TryExecuteAction(), application::SecondStageToRamLoader::TryLoadImage(), services::ConnectionMbedTls::TrySend(), application::PackUpgrader::TryUpgradeImage(), application::ImageUpgraderInternalFlash::Upgrade(), services::SynchronousFlashRegion::WriteBuffer(), services::FlashRegion::WriteBuffer(), and services::CyclicStore::WriteRange().
     {
         return endElement - beginElement;
     }
Member Data Documentation
beginElement
template<class T> T* infra::MemoryRange< T >::beginElement private
Definition at line 59 of file MemoryRange.hpp.
endElement
template<class T> T* infra::MemoryRange< T >::endElement private
Definition at line 60 of file MemoryRange.hpp.
The documentation for this class was generated from the following file:
MemoryRange.hpp