EMil: TestLlmnrResponder.cpp File Reference
TestLlmnrResponder.cpp File Reference
Classes
class LlmnrResponderTest
Functions
TEST_F (LlmnrResponderTest, request_record_a)
TEST_F (LlmnrResponderTest, query_for_someone_else_is_not_answered)
TEST_F (LlmnrResponderTest, short_header_is_not_answered)
TEST_F (LlmnrResponderTest, unknown_request_is_not_answered)
TEST_F (LlmnrResponderTest, unknown_class_is_not_answered)
TEST_F (LlmnrResponderTest, unknown_flags_are_not_answered)
TEST_F (LlmnrResponderTest, multiple_questions_are_not_answered)
TEST_F (LlmnrResponderTest, improper_string_is_not_answered)
TEST_F (LlmnrResponderTest, ignore_request_when_replying)
Function Documentation
TEST_F() [1/9]
TEST_F (LlmnrResponderTest , request_record_a)
Definition at line 38 of file TestLlmnrResponder.cpp.
References data, EXPECT_EQ(), infra::MakeRange(), and infra::UnOwnedSharedPtr().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 1, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     EXPECT_CALL(datagramExchange, RequestSendStream(38, services::UdpSocket{ services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 } }));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
     EXPECT_CALL(ipv4Info, GetIPv4Address()).WillOnce(testing::Return(services::IPv4Address{ 5, 6, 7, 8 }));
     infra::ByteOutputStreamWriter::WithStorage<512> response;
     responder.SendStreamAvailable(infra::UnOwnedSharedPtr(response));
     EXPECT_EQ((std::array<uint8_t, 38>{ 1, 2, 0x80, 0, 0, 1, 0, 1, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 1, 0, 1,
         0xc0, 0x0c, 0, 1, 0, 1, 0, 0, 0, 30, 0, 4, 5, 6, 7, 8 }), response.Processed());
 }
TEST_F() [2/9]
TEST_F (LlmnrResponderTest , query_for_someone_else_is_not_answered)
Definition at line 53 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'o', 'n', 'e', 0, 0, 1, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [3/9]
TEST_F (LlmnrResponderTest , short_header_is_not_answered)
Definition at line 61 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [4/9]
TEST_F (LlmnrResponderTest , unknown_request_is_not_answered)
Definition at line 69 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 2, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [5/9]
TEST_F (LlmnrResponderTest , unknown_class_is_not_answered)
Definition at line 77 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 1, 0, 2 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [6/9]
TEST_F (LlmnrResponderTest , unknown_flags_are_not_answered)
Definition at line 85 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 8, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 1, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [7/9]
TEST_F (LlmnrResponderTest , multiple_questions_are_not_answered)
Definition at line 93 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 1, 0, 8, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 1, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [8/9]
TEST_F (LlmnrResponderTest , improper_string_is_not_answered)
Definition at line 101 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0xa5, 0, 1, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }
TEST_F() [9/9]
TEST_F (LlmnrResponderTest , ignore_request_when_replying)
Definition at line 109 of file TestLlmnrResponder.cpp.
References data, and infra::MakeRange().
 {
     std::vector<uint8_t> data{ 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 'n', 'a', 'm', 'e', 0, 0, 1, 0, 1 };
     infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
     EXPECT_CALL(datagramExchange, RequestSendStream(38, services::UdpSocket{ services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 } }));
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
     responder.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 12 });
 }