EMil: infra::Asn1Sequence Class Reference
infra::Asn1Sequence Class Reference
#include <Asn1.hpp>
Public Member Functions
Asn1Sequence (infra::ConstByteRange range)
Asn1SequenceIterator begin () const
Asn1SequenceIterator end () const
Asn1Value front () const
Asn1Value operator[] (std::size_t index) const
bool operator== (const Asn1Sequence &other) const
bool operator!= (const Asn1Sequence &other) const
Private Attributes
infra::ConstByteRange range
Detailed Description
Definition at line 52 of file Asn1.hpp.
Constructor & Destructor Documentation
Asn1Sequence()
infra::Asn1Sequence::Asn1Sequence (infra::ConstByteRange range) explicit
Definition at line 110 of file Asn1.cpp.
         : range(range)
     {}
Member Function Documentation
begin()
Asn1SequenceIterator infra::Asn1Sequence::begin () const
Definition at line 114 of file Asn1.cpp.
References range.
Referenced by front(), and operator[]().
     {
         return Asn1SequenceIterator(range);
     }
end()
Asn1SequenceIterator infra::Asn1Sequence::end () const
Definition at line 119 of file Asn1.cpp.
     {
         return Asn1SequenceIterator();
     }
front()
Asn1Value infra::Asn1Sequence::front () const
Definition at line 124 of file Asn1.cpp.
References begin().
     {
         return *begin();
     }
operator!=()
bool infra::Asn1Sequence::operator!= (const Asn1Sequence & other) const
Definition at line 139 of file Asn1.cpp.
     {
         return !(*this == other);
     }
operator==()
bool infra::Asn1Sequence::operator== (const Asn1Sequence & other) const
Definition at line 134 of file Asn1.cpp.
References range.
     {
         return range == other.range;
     }
operator[]()
Asn1Value infra::Asn1Sequence::operator[] (std::size_t index) const
Definition at line 129 of file Asn1.cpp.
References begin().
     {
         return *std::next(begin(), index);
     }
Member Data Documentation
range
infra::ConstByteRange infra::Asn1Sequence::range private
Definition at line 67 of file Asn1.hpp.
Referenced by begin(), and operator==().
The documentation for this class was generated from the following files:
Asn1.hpp
Asn1.cpp