EMil: TestReferenceCountedSingleton.cpp File Reference
TestReferenceCountedSingleton.cpp File Reference
Classes
class ReferenceCountedSingletonTest
struct ReferenceCountedSingletonTest::X
Functions
TEST_F (ReferenceCountedSingletonTest, TestCreation)
TEST_F (ReferenceCountedSingletonTest, TestDestruction)
TEST_F (ReferenceCountedSingletonTest, TestMultipleAccess)
TEST_F (ReferenceCountedSingletonTest, TestDereference)
Function Documentation
TEST_F() [1/4]
TEST_F (ReferenceCountedSingletonTest , TestCreation)
Definition at line 35 of file TestReferenceCountedSingleton.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(numCreations, 0);
     X::Access access;
     EXPECT_EQ(numCreations, 1);
 }
TEST_F() [2/4]
TEST_F (ReferenceCountedSingletonTest , TestDestruction)
Definition at line 42 of file TestReferenceCountedSingleton.cpp.
References EXPECT_EQ().
 {
     {
         X::Access access;
         EXPECT_EQ(numCreations, 1);
     }
     EXPECT_EQ(numCreations, 0);
 }
TEST_F() [3/4]
TEST_F (ReferenceCountedSingletonTest , TestMultipleAccess)
Definition at line 51 of file TestReferenceCountedSingleton.cpp.
References EXPECT_EQ().
 {
     {
         X::Access access;
         {
             X::Access access2;
             EXPECT_EQ(numCreations, 1);
         }
         EXPECT_EQ(numCreations, 1);
     }
     EXPECT_EQ(numCreations, 0);
 }
TEST_F() [4/4]
TEST_F (ReferenceCountedSingletonTest , TestDereference)
Definition at line 64 of file TestReferenceCountedSingleton.cpp.
References EXPECT_TRUE().
 {
     X::Access access;
     EXPECT_TRUE(access->something);
     EXPECT_TRUE((*access).something);
     const X::Access constAccess;
     EXPECT_TRUE(constAccess->something);
     EXPECT_TRUE((*constAccess).something);
 }