EMil: TestJsonInputStream.cpp File Reference
TestJsonInputStream.cpp File Reference
Classes
class JsonInputStreamTest
Functions
TEST_F (JsonInputStreamTest, read_JsonString)
TEST_F (JsonInputStreamTest, Extract)
TEST_F (JsonInputStreamTest, Peek)
TEST_F (JsonInputStreamTest, Empty)
TEST_F (JsonInputStreamTest, Available)
Function Documentation
TEST_F() [1/5]
TEST_F (JsonInputStreamTest , read_JsonString)
Definition at line 19 of file TestJsonInputStream.cpp.
References EXPECT_EQ().
 {
     infra::JsonInputStream stream(string);
     char a;
     char b;
     char quote;
     stream >> a >> b >> quote;
     EXPECT_EQ('a', a);
     EXPECT_EQ('b', b);
     EXPECT_EQ('"', quote);
 }
TEST_F() [2/5]
TEST_F (JsonInputStreamTest , Extract)
Definition at line 33 of file TestJsonInputStream.cpp.
References EXPECT_EQ().
 {
     std::array<uint8_t, 3> result;
     reader.Extract(result, errorPolicy);
     EXPECT_EQ((std::array<uint8_t, 3>{ 'a', 'b', '"' }), result);
 }
TEST_F() [3/5]
TEST_F (JsonInputStreamTest , Peek)
Definition at line 40 of file TestJsonInputStream.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_EQ('a', reader.Peek(errorPolicy));
     EXPECT_FALSE(errorPolicy.Failed());
     std::array<uint8_t, 3> result;
     reader.Extract(result, errorPolicy);
     EXPECT_EQ(0, reader.Peek(errorPolicy));
     EXPECT_TRUE(errorPolicy.Failed());
 }
TEST_F() [4/5]
TEST_F (JsonInputStreamTest , Empty)
Definition at line 52 of file TestJsonInputStream.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_FALSE(reader.Empty());
     std::array<uint8_t, 3> result;
     reader.Extract(result, errorPolicy);
     EXPECT_TRUE(reader.Empty());
 }
TEST_F() [5/5]
TEST_F (JsonInputStreamTest , Available)
Definition at line 62 of file TestJsonInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(3, reader.Available());
     std::array<uint8_t, 3> result;
     reader.Extract(result, errorPolicy);
     EXPECT_EQ(0, reader.Available());
 }