EMil: infra::ProtoLengthDelimitedFormatter Class Reference
infra::ProtoLengthDelimitedFormatter Class Reference
#include <ProtoFormatter.hpp>
Public Member Functions
ProtoLengthDelimitedFormatter (ProtoFormatter &formatter, uint32_t fieldNumber)
ProtoLengthDelimitedFormatter (const ProtoLengthDelimitedFormatter &other)=delete
ProtoLengthDelimitedFormatter (ProtoLengthDelimitedFormatter &&other)
ProtoLengthDelimitedFormatter & operator= (const ProtoLengthDelimitedFormatter &other)=delete
~ProtoLengthDelimitedFormatter ()
Private Attributes
ProtoFormatter & formatter
std::size_t marker
Detailed Description
Definition at line 11 of file ProtoFormatter.hpp.
Constructor & Destructor Documentation
ProtoLengthDelimitedFormatter() [1/3]
infra::ProtoLengthDelimitedFormatter::ProtoLengthDelimitedFormatter (ProtoFormatter & formatter, uint32_t fieldNumber)
Definition at line 6 of file ProtoFormatter.cpp.
References formatter, marker, infra::ProtoFormatter::output, infra::ProtoFormatter::PutVarInt(), and infra::OutputStream::SaveMarker().
         : formatter(formatter)
     {
         formatter.PutVarInt((fieldNumber << 3) | 2);
         marker = formatter.output.SaveMarker();
     }
ProtoLengthDelimitedFormatter() [2/3]
infra::ProtoLengthDelimitedFormatter::ProtoLengthDelimitedFormatter (const ProtoLengthDelimitedFormatter & other) delete
ProtoLengthDelimitedFormatter() [3/3]
infra::ProtoLengthDelimitedFormatter::ProtoLengthDelimitedFormatter (ProtoLengthDelimitedFormatter && other)
Definition at line 13 of file ProtoFormatter.cpp.
         : formatter(other.formatter)
         , marker(other.marker)
     {
         other.marker = std::numeric_limits<std::size_t>::max();
     }
~ProtoLengthDelimitedFormatter()
infra::ProtoLengthDelimitedFormatter::~ProtoLengthDelimitedFormatter ()
Definition at line 20 of file ProtoFormatter.cpp.
References formatter, marker, infra::ProtoFormatter::output, infra::OutputStream::ProcessedBytesSince(), and infra::ProtoFormatter::PutVarInt().
     {
         if (marker != std::numeric_limits<std::size_t>::max())
         {
             uint32_t size = formatter.output.ProcessedBytesSince(marker);
             infra::SavedMarkerDataStream savedStream(formatter.output, marker);
             ProtoFormatter savedFormatter(savedStream);
             savedFormatter.PutVarInt(size);
         }
     }
Member Function Documentation
operator=()
ProtoLengthDelimitedFormatter& infra::ProtoLengthDelimitedFormatter::operator= (const ProtoLengthDelimitedFormatter & other) delete
Member Data Documentation
formatter
ProtoFormatter& infra::ProtoLengthDelimitedFormatter::formatter private
Definition at line 21 of file ProtoFormatter.hpp.
Referenced by ProtoLengthDelimitedFormatter(), and ~ProtoLengthDelimitedFormatter().
marker
std::size_t infra::ProtoLengthDelimitedFormatter::marker private
Definition at line 22 of file ProtoFormatter.hpp.
Referenced by ProtoLengthDelimitedFormatter(), and ~ProtoLengthDelimitedFormatter().
The documentation for this class was generated from the following files:
ProtoFormatter.hpp
ProtoFormatter.cpp