EMil: infra::StreamErrorPolicy Class Reference
infra::StreamErrorPolicy Class Reference
#include <StreamErrorPolicy.hpp>
Public Member Functions
StreamErrorPolicy ()=default
StreamErrorPolicy (SoftFail)
StreamErrorPolicy (NoFail)
~StreamErrorPolicy ()
virtual bool Failed () const
virtual void ReportResult (bool ok)
Private Types
enum FailureMode { FailureMode::assertion, FailureMode::soft, FailureMode::no }
Private Attributes
FailureMode failureMode = FailureMode::assertion
bool failed = false
bool checkedFail = true
Detailed Description
Definition at line 11 of file StreamErrorPolicy.hpp.
Member Enumeration Documentation
FailureMode
enum infra::StreamErrorPolicy::FailureMode strong private
Enumerator
assertion
soft
no
Definition at line 23 of file StreamErrorPolicy.hpp.
         {
             assertion,
             soft,
             no
         };
Constructor & Destructor Documentation
StreamErrorPolicy() [1/3]
infra::StreamErrorPolicy::StreamErrorPolicy () default
StreamErrorPolicy() [2/3]
infra::StreamErrorPolicy::StreamErrorPolicy (SoftFail) explicit
Definition at line 10 of file StreamErrorPolicy.cpp.
         : failureMode(FailureMode::soft)
     {}
StreamErrorPolicy() [3/3]
infra::StreamErrorPolicy::StreamErrorPolicy (NoFail) explicit
Definition at line 14 of file StreamErrorPolicy.cpp.
         : failureMode(FailureMode::no)
     {}
~StreamErrorPolicy()
infra::StreamErrorPolicy::~StreamErrorPolicy ()
Definition at line 18 of file StreamErrorPolicy.cpp.
References checkedFail.
     {
         assert(checkedFail);
     }
Member Function Documentation
Failed()
bool infra::StreamErrorPolicy::Failed () const virtual
Reimplemented in infra::CountingStreamReader.
Definition at line 23 of file StreamErrorPolicy.cpp.
References checkedFail, and failed.
Referenced by services::ConnectionSerial::SerialConnectionStreamReader::Extract(), infra::CountingStreamReader::Failed(), infra::OutputStream::Failed(), infra::InputStream::Failed(), and services::ConnectionSerial::SerialConnectionStreamReader::Peek().
     {
         checkedFail = true;
         return failed;
     }
ReportResult()
void infra::StreamErrorPolicy::ReportResult (bool ok) virtual
Reimplemented in infra::CountingStreamReader.
Definition at line 29 of file StreamErrorPolicy.cpp.
References assertion, checkedFail, failed, failureMode, and soft.
Referenced by infra::JsonInputStreamReader::Extract(), infra::LimitedStreamReader::Extract(), infra::StringInputStreamReader::Extract(), infra::StdStringInputStreamReader::Extract(), infra::StdVectorInputStreamReader::Extract(), infra::BoundedDequeInputStreamReader::Extract(), infra::ByteInputStreamReader::Extract(), services::ConnectionSerial::SerialConnectionStreamReader::Extract(), infra::LimitedStreamWriter::Insert(), infra::StringOutputStreamWriter::Insert(), infra::ByteOutputStreamWriter::Insert(), infra::TextInputStream::operator>>(), infra::operator>>(), infra::LimitedStreamReader::Peek(), infra::JsonInputStreamReader::Peek(), infra::StringInputStreamReader::Peek(), infra::StdStringInputStreamReader::Peek(), infra::StdVectorInputStreamReader::Peek(), infra::ByteInputStreamReader::Peek(), services::ConnectionSerial::SerialConnectionStreamReader::Peek(), infra::ProtoLengthDelimited::ProtoLengthDelimited(), infra::TextInputStream::ReadAsDecimal(), infra::TextInputStream::ReadAsHex(), infra::CountingStreamReader::ReportResult(), infra::StringOutputStreamWriter::Reserve(), and infra::ByteOutputStreamWriter::Reserve().
     {
         if (!ok)
         {
             failed = true;
             really_assert(failureMode != FailureMode::assertion);
         }
         checkedFail = failureMode != FailureMode::soft;
     }
Member Data Documentation
checkedFail
bool infra::StreamErrorPolicy::checkedFail = true mutable private
Definition at line 32 of file StreamErrorPolicy.hpp.
Referenced by Failed(), ReportResult(), and ~StreamErrorPolicy().
failed
bool infra::StreamErrorPolicy::failed = false private
Definition at line 31 of file StreamErrorPolicy.hpp.
Referenced by Failed(), and ReportResult().
failureMode
FailureMode infra::StreamErrorPolicy::failureMode = FailureMode::assertion private
Definition at line 30 of file StreamErrorPolicy.hpp.
Referenced by ReportResult().
The documentation for this class was generated from the following files:
StreamErrorPolicy.hpp
StreamErrorPolicy.cpp