EMil: hal::CleanFlashMock Class Reference
hal::CleanFlashMock Class Reference
#include <FlashMock.hpp>
Public Member Functions
CleanFlashMock ()=default
CleanFlashMock (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
MOCK_CONST_METHOD0 (NumberOfSectors, uint32_t())
MOCK_CONST_METHOD1 (SizeOfSector, uint32_t(uint32_t sectorIndex))
MOCK_CONST_METHOD1 (SectorOfAddress, uint32_t(uint32_t address))
MOCK_CONST_METHOD1 (AddressOfSector, uint32_t(uint32_t sectorIndex))
MOCK_METHOD3 (WriteBuffer, void(infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone))
MOCK_METHOD3 (ReadBuffer, void(infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone))
MOCK_METHOD3 (EraseSectors, void(uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone))
Public Member Functions inherited from hal::Flash
virtual uint32_t NumberOfSectors () const =0
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const =0
uint32_t TotalSize () const
virtual uint32_t SectorOfAddress (uint32_t address) const =0
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const =0
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone)=0
void EraseAll (infra::Function< void()> onDone)
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 36 of file FlashMock.hpp.
Constructor & Destructor Documentation
CleanFlashMock() [1/2]
hal::CleanFlashMock::CleanFlashMock () default
CleanFlashMock() [2/2]
hal::CleanFlashMock::CleanFlashMock (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
Definition at line 51 of file FlashMock.cpp.
References hal::Flash::AddressOfSector(), infra::Lambda(), hal::Flash::NumberOfSectors(), hal::Flash::SectorOfAddress(), and hal::Flash::SizeOfSector().
     {
         EXPECT_CALL(*this, NumberOfSectors()).WillRepeatedly(testing::Return(numberOfSectors));
         EXPECT_CALL(*this, SizeOfSector(testing::_)).WillRepeatedly(testing::Return(sizeOfEachSector));
         EXPECT_CALL(*this, SectorOfAddress(testing::_)).WillRepeatedly(infra::Lambda([sizeOfEachSector](uint32_t address) { return address % sizeOfEachSector; }));
         EXPECT_CALL(*this, AddressOfSector(testing::_)).WillRepeatedly(infra::Lambda([sizeOfEachSector](uint32_t sectorIndex) { return sectorIndex * sizeOfEachSector; }));
     }
Member Function Documentation
MOCK_CONST_METHOD0()
hal::CleanFlashMock::MOCK_CONST_METHOD0 (NumberOfSectors , uint32_t())
MOCK_CONST_METHOD1() [1/3]
hal::CleanFlashMock::MOCK_CONST_METHOD1 (SizeOfSector , uint32_t(uint32_t sectorIndex))
MOCK_CONST_METHOD1() [2/3]
hal::CleanFlashMock::MOCK_CONST_METHOD1 (SectorOfAddress , uint32_t(uint32_t address))
MOCK_CONST_METHOD1() [3/3]
hal::CleanFlashMock::MOCK_CONST_METHOD1 (AddressOfSector , uint32_t(uint32_t sectorIndex))
MOCK_METHOD3() [1/3]
hal::CleanFlashMock::MOCK_METHOD3 (WriteBuffer , void(infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone))
MOCK_METHOD3() [2/3]
hal::CleanFlashMock::MOCK_METHOD3 (ReadBuffer , void(infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone))
MOCK_METHOD3() [3/3]
hal::CleanFlashMock::MOCK_METHOD3 (EraseSectors , void(uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone))
The documentation for this class was generated from the following files:
FlashMock.hpp
FlashMock.cpp