EMil: services::SynchronousFlashRegion Class Reference
services::SynchronousFlashRegion Class Reference
#include <SynchronousFlashRegion.hpp>
Public Member Functions
SynchronousFlashRegion (hal::SynchronousFlash &master, uint32_t startSector, uint32_t numberOfSectors)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex) override
Public Member Functions inherited from hal::SynchronousFlash
SynchronousFlash ()=default
SynchronousFlash (const SynchronousFlash &other)=delete
SynchronousFlash & operator= (const SynchronousFlash &other)=delete
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex)
void EraseAll ()
Private Member Functions
uint32_t ToMasterAddress (uint32_t address) const
Private Attributes
hal::SynchronousFlash & master
uint32_t startSector
uint32_t numberOfSectors
uint32_t masterAddressOfStartSector
Additional Inherited Members
Public Types inherited from hal::SynchronousFlash
using Range = std::pair< uint32_t, uint32_t >
Protected Member Functions inherited from hal::SynchronousFlash
~SynchronousFlash ()=default
Detailed Description
Definition at line 8 of file SynchronousFlashRegion.hpp.
Constructor & Destructor Documentation
SynchronousFlashRegion()
services::SynchronousFlashRegion::SynchronousFlashRegion (hal::SynchronousFlash & master, uint32_t startSector, uint32_t numberOfSectors)
Definition at line 5 of file SynchronousFlashRegion.cpp.
References master, hal::SynchronousFlash::NumberOfSectors(), numberOfSectors, and startSector.
         : master(master)
         , startSector(startSector)
         , numberOfSectors(numberOfSectors)
         , masterAddressOfStartSector(master.AddressOfSector(startSector))
     {
         assert(startSector + numberOfSectors <= master.NumberOfSectors());
     }
Member Function Documentation
AddressOfSector()
uint32_t services::SynchronousFlashRegion::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::SynchronousFlash.
Definition at line 29 of file SynchronousFlashRegion.cpp.
References hal::SynchronousFlash::AddressOfSector(), master, masterAddressOfStartSector, and startSector.
     {
         return master.AddressOfSector(sectorIndex + startSector) - masterAddressOfStartSector;
     }
EraseSectors()
void services::SynchronousFlashRegion::EraseSectors (uint32_t beginIndex, uint32_t endIndex) override virtual
Implements hal::SynchronousFlash.
Definition at line 46 of file SynchronousFlashRegion.cpp.
References hal::SynchronousFlash::EraseSectors(), master, numberOfSectors, and startSector.
     {
         assert(beginIndex <= numberOfSectors && endIndex <= numberOfSectors);
         master.EraseSectors(beginIndex + startSector, endIndex + startSector);
     }
NumberOfSectors()
uint32_t services::SynchronousFlashRegion::NumberOfSectors () const override virtual
Implements hal::SynchronousFlash.
Definition at line 14 of file SynchronousFlashRegion.cpp.
References numberOfSectors.
     {
         return numberOfSectors;
     }
ReadBuffer()
void services::SynchronousFlashRegion::ReadBuffer (infra::ByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 40 of file SynchronousFlashRegion.cpp.
References master, masterAddressOfStartSector, numberOfSectors, hal::SynchronousFlash::ReadBuffer(), SectorOfAddress(), and infra::MemoryRange< T >::size().
     {
         assert(SectorOfAddress(address) <= numberOfSectors && SectorOfAddress(address + buffer.size()) <= numberOfSectors);
         master.ReadBuffer(buffer, address + masterAddressOfStartSector);
     }
SectorOfAddress()
uint32_t services::SynchronousFlashRegion::SectorOfAddress (uint32_t address) const override virtual
Implements hal::SynchronousFlash.
Definition at line 24 of file SynchronousFlashRegion.cpp.
References master, masterAddressOfStartSector, hal::SynchronousFlash::SectorOfAddress(), and startSector.
Referenced by ReadBuffer(), and WriteBuffer().
     {
         return master.SectorOfAddress(masterAddressOfStartSector + address) - startSector;
     }
SizeOfSector()
uint32_t services::SynchronousFlashRegion::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::SynchronousFlash.
Definition at line 19 of file SynchronousFlashRegion.cpp.
References master, hal::SynchronousFlash::SizeOfSector(), and startSector.
     {
         return master.SizeOfSector(startSector + sectorIndex);
     }
ToMasterAddress()
uint32_t services::SynchronousFlashRegion::ToMasterAddress (uint32_t address) const private
WriteBuffer()
void services::SynchronousFlashRegion::WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 34 of file SynchronousFlashRegion.cpp.
References master, masterAddressOfStartSector, numberOfSectors, SectorOfAddress(), infra::MemoryRange< T >::size(), and hal::SynchronousFlash::WriteBuffer().
     {
         assert(SectorOfAddress(address) <= numberOfSectors && SectorOfAddress(address + buffer.size()) <= numberOfSectors);
         master.WriteBuffer(buffer, address + masterAddressOfStartSector);
     }
Member Data Documentation
master
hal::SynchronousFlash& services::SynchronousFlashRegion::master private
Definition at line 29 of file SynchronousFlashRegion.hpp.
Referenced by AddressOfSector(), EraseSectors(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), SynchronousFlashRegion(), and WriteBuffer().
masterAddressOfStartSector
uint32_t services::SynchronousFlashRegion::masterAddressOfStartSector private
Definition at line 32 of file SynchronousFlashRegion.hpp.
Referenced by AddressOfSector(), ReadBuffer(), SectorOfAddress(), and WriteBuffer().
numberOfSectors
uint32_t services::SynchronousFlashRegion::numberOfSectors private
Definition at line 31 of file SynchronousFlashRegion.hpp.
Referenced by EraseSectors(), NumberOfSectors(), ReadBuffer(), SynchronousFlashRegion(), and WriteBuffer().
startSector
uint32_t services::SynchronousFlashRegion::startSector private
Definition at line 30 of file SynchronousFlashRegion.hpp.
Referenced by AddressOfSector(), EraseSectors(), SectorOfAddress(), SizeOfSector(), and SynchronousFlashRegion().
The documentation for this class was generated from the following files:
SynchronousFlashRegion.hpp
SynchronousFlashRegion.cpp