EMil: infra::JsonSubParser Class Reference
infra::JsonSubParser Class Reference abstract
#include <JsonStreamingParser.hpp>
Public Member Functions
JsonSubParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char &subObjects)
JsonSubParser (const JsonSubParser &other)=delete
JsonSubParser & operator= (const JsonSubParser &other)=delete
virtual ~JsonSubParser ()
virtual void Feed (infra::MemoryRange< const char > &data)=0
virtual JsonVisitor & Visitor ()=0
virtual void SetVisitor (JsonVisitor &visitor)=0
Protected Types
enum TokenState {
TokenState::open, TokenState::done, TokenState::stringOpen, TokenState::stringOpenAndEscaped,
TokenState::stringOverflowOpen, TokenState::unicodeValueOpen, TokenState::numberOpen, TokenState::numberFractionalOpen,
TokenState::numberExponentOpen, TokenState::identifierOpen
}
enum Token {
Token::error, Token::colon, Token::comma, Token::leftBrace,
Token::rightBrace, Token::leftBracket, Token::rightBracket, Token::string,
Token::stringOverflow, Token::number, Token::true_, Token::false_,
Token::null
}
Protected Member Functions
void FeedToken (infra::MemoryRange< const char > &data, bool saveValue)
void ReportParseError ()
void ReportSemanticError ()
infra::BoundedString CopyAndClear (infra::BoundedString &value) const
Protected Attributes
infra::BoundedString tagBuffer
infra::BoundedString valueBuffer
infra::BoundedVector< infra::PolymorphicVariant< JsonSubParser, JsonSubObjectParser, JsonSubArrayParser > > & subObjects
TokenState tokenState = TokenState::open
Token token = Token::error
int64_t tokenNumber
int8_t tokenSign
Private Member Functions
void FoundToken (Token found)
void ProcessEscapedData (char c, bool saveValue)
void AddToValueBuffer (char c, bool saveValue, bool inString)
Private Attributes
uint8_t unicodeIndex = 0
uint16_t unicode = 0
bool * destructedIndication = nullptr
Detailed Description
Definition at line 77 of file JsonStreamingParser.hpp.
Member Enumeration Documentation
Token
enum infra::JsonSubParser::Token strong protected
Enumerator
error
colon
comma
leftBrace
rightBrace
leftBracket
rightBracket
string
stringOverflow
number
true_
false_
null
Definition at line 107 of file JsonStreamingParser.hpp.
         {
             error,
             colon,
             comma,
             leftBrace,
             rightBrace,
             leftBracket,
             rightBracket,
             string,
             stringOverflow,
             number,
             true_,
             false_,
             null
         };
TokenState
enum infra::JsonSubParser::TokenState strong protected
Enumerator
open
done
stringOpen
stringOpenAndEscaped
stringOverflowOpen
unicodeValueOpen
numberOpen
numberFractionalOpen
numberExponentOpen
identifierOpen
Definition at line 93 of file JsonStreamingParser.hpp.
         {
             open,
             done,
             stringOpen,
             stringOpenAndEscaped,
             stringOverflowOpen,
             unicodeValueOpen,
             numberOpen,
             numberFractionalOpen,
             numberExponentOpen,
             identifierOpen
         };
Constructor & Destructor Documentation
JsonSubParser() [1/2]
infra::JsonSubParser::JsonSubParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char & subObjects)
Definition at line 75 of file JsonStreamingParser.cpp.
         : tagBuffer(tagBuffer)
         , valueBuffer(valueBuffer)
         , subObjects(reinterpret_cast<infra::BoundedVector<infra::PolymorphicVariant<JsonSubParser, JsonSubObjectParser, JsonSubArrayParser>>&>(subObjects))
     {}
JsonSubParser() [2/2]
infra::JsonSubParser::JsonSubParser (const JsonSubParser & other) delete
~JsonSubParser()
infra::JsonSubParser::~JsonSubParser () virtual
Definition at line 82 of file JsonStreamingParser.cpp.
References destructedIndication.
     {
         if (destructedIndication != nullptr)
             *destructedIndication = true;
     }
Member Function Documentation
AddToValueBuffer()
void infra::JsonSubParser::AddToValueBuffer (char c, bool saveValue, bool inString) private
Definition at line 323 of file JsonStreamingParser.cpp.
References error, FoundToken(), infra::BoundedStringBase< T >::full(), stringOverflowOpen, tokenState, and valueBuffer.
Referenced by FeedToken(), and ProcessEscapedData().
     {
         if (valueBuffer.full())
         {
             if (inString)
                 tokenState = TokenState::stringOverflowOpen;
             else
                 FoundToken(Token::error);
         }
         else if (saveValue)
             valueBuffer += c;
     }
CopyAndClear()
infra::BoundedString infra::JsonSubParser::CopyAndClear (infra::BoundedString & value) const protected
Definition at line 294 of file JsonStreamingParser.cpp.
References value.
Referenced by infra::JsonSubObjectParser::Feed().
     {
         infra::BoundedString result(value);
         value.clear();
         return result;
     }
Feed()
virtual void infra::JsonSubParser::Feed (infra::MemoryRange< const char > & data) pure virtual
Implemented in infra::JsonSubArrayParser, and infra::JsonSubObjectParser.
FeedToken()
void infra::JsonSubParser::FeedToken (infra::MemoryRange< const char > & data, bool saveValue) protected
Definition at line 88 of file JsonStreamingParser.cpp.
References AddToValueBuffer(), colon, comma, infra::data, done, error, false_, FoundToken(), infra::BoundedStringBase< T >::full(), identifierOpen, leftBrace, leftBracket, null, number, numberExponentOpen, numberFractionalOpen, numberOpen, open, ProcessEscapedData(), rightBrace, rightBracket, string, stringOpen, stringOpenAndEscaped, stringOverflow, stringOverflowOpen, tokenNumber, tokenSign, tokenState, true_, unicode, unicodeIndex, unicodeValueOpen, and valueBuffer.
Referenced by infra::JsonSubObjectParser::Feed(), and infra::JsonSubArrayParser::Feed().
     {
         while (!data.empty() && tokenState != TokenState::done)
         {
             auto c = data.front();
             if (tokenState == TokenState::numberOpen)
             {
                 if (std::isdigit(c))
                 {
                     tokenNumber = tokenNumber * 10 + c - '0';
                     data.pop_front();
                 }
                 else if (c == '.')
                 {
                     tokenState = TokenState::numberFractionalOpen;
                     data.pop_front();
                 }
                 else
                     FoundToken(Token::number);
             }
             else if (tokenState == TokenState::numberFractionalOpen)
             {
                 if (std::isdigit(c))
                     data.pop_front();
                 else if (c == 'e' || c == 'E')
                 {
                     tokenState = TokenState::numberExponentOpen;
                     data.pop_front();
                 }
                 else
                     FoundToken(Token::number);
             }
             else if (tokenState == TokenState::numberExponentOpen)
             {
                 if (std::isdigit(c) || c == '+' || c == '-')
                     data.pop_front();
                 else
                     FoundToken(Token::number);
             }
             else if (tokenState == TokenState::identifierOpen)
             {
                 if (std::isalpha(c))
                 {
                     AddToValueBuffer(c, saveValue, false);
                     data.pop_front();
                 }
                 else if (valueBuffer == "true")
                     FoundToken(Token::true_);
                 else if (valueBuffer == "false")
                     FoundToken(Token::false_);
                 else if (valueBuffer == "null")
                     FoundToken(Token::null);
                 else
                     FoundToken(Token::error);
             }
             else
             {
                 data.pop_front();
                 switch (tokenState)
                 {
                     case TokenState::open:
                         if (std::isspace(c))
{
                             while (!data.empty() && std::isspace(data.front()))
                                 data.pop_front();
                         }
                         else switch (c)
{
                             case ':':
                                 FoundToken(Token::colon);
                                 break;
                             case ',':
                                 FoundToken(Token::comma);
                                 break;
                             case '{':
                                 FoundToken(Token::leftBrace);
                                 break;
                             case '}':
                                 FoundToken(Token::rightBrace);
                                 break;
                             case '[':
                                 FoundToken(Token::leftBracket);
                                 break;
                             case ']':
                                 FoundToken(Token::rightBracket);
                                 break;
                             case '"':
                                 tokenState = TokenState::stringOpen;
                                 break;
                             case '-':
                                 tokenState = TokenState::numberOpen;
                                 tokenNumber = 0;
                                 tokenSign = -1;
                                 break;
                             default:
                                 if (std::isalpha(c))
{
                                     tokenState = TokenState::identifierOpen;
                                     valueBuffer = c;
                                 }
                                 else if (std::isdigit(c))
{
                                     tokenState = TokenState::numberOpen;
                                     tokenNumber = c - '0';
                                     tokenSign = 1;
                                 }
                                 else
                                     FoundToken(Token::error);
                         }
                         break;
                     case TokenState::stringOpen:
                     case TokenState::stringOverflowOpen:
                         while (true)
{
                             if (c == '\\')
                                 tokenState = TokenState::stringOpenAndEscaped;
                             else if (c == '"')
                                 FoundToken(tokenState == TokenState::stringOpen ? Token::string : Token::stringOverflow);
                             else
                                 AddToValueBuffer(c, saveValue, true);
                             if ((tokenState != TokenState::stringOpen && tokenState != TokenState::stringOverflowOpen) || data.empty())
                                 break;
                             c = data.front();
                             data.pop_front();
                         }
                         break;
                     case TokenState::stringOpenAndEscaped:
                         tokenState = TokenState::stringOpen;
                         ProcessEscapedData(c, saveValue);
                         break;
                     case TokenState::unicodeValueOpen:
                         if (c >= '0' && c <= '9')
{
                             ++unicodeIndex;
                             unicode = unicode * 16 + c - '0';
                         }
                         else if (c >= 'a' && c <= 'f')
{
                             ++unicodeIndex;
                             unicode = unicode * 16 + c - 'a' + 10;
                         }
                         else if (c >= 'A' && c <= 'F')
{
                             ++unicodeIndex;
                             unicode = unicode * 16 + c - 'A' + 10;
                         }
                         else
{
                             unicodeIndex = 0;
                             unicode = 0;
                             FoundToken(Token::error);
                         }
                         if (unicodeIndex == 4)
{
                             tokenState = TokenState::stringOpen;
                             if (valueBuffer.full())
                                 FoundToken(Token::error);
                             else
                                 AddToValueBuffer(static_cast<char>(unicode), saveValue, true);
                             unicodeIndex = 0;
                             unicode = 0;
                         }
                         break;
                     default:
                         std::abort();
                 }
             }
         }
     }
FoundToken()
void infra::JsonSubParser::FoundToken (Token found) private
Definition at line 301 of file JsonStreamingParser.cpp.
References done, token, and tokenState.
Referenced by AddToValueBuffer(), and FeedToken().
     {
         token = found;
         tokenState = TokenState::done;
     }
operator=()
JsonSubParser& infra::JsonSubParser::operator= (const JsonSubParser & other) delete
ProcessEscapedData()
void infra::JsonSubParser::ProcessEscapedData (char c, bool saveValue) private
Definition at line 307 of file JsonStreamingParser.cpp.
References AddToValueBuffer(), tokenState, and unicodeValueOpen.
Referenced by FeedToken().
     {
         switch (c)
         {
             case '"': AddToValueBuffer('"', saveValue, true); break;
             case '\\': AddToValueBuffer('\\', saveValue, true); break;
             case 'b': AddToValueBuffer('\b', saveValue, true); break;
             case 'f': AddToValueBuffer('\f', saveValue, true); break;
             case 'n': AddToValueBuffer('\n', saveValue, true); break;
             case 'r': AddToValueBuffer('\r', saveValue, true); break;
             case 't': AddToValueBuffer('\t', saveValue, true); break;
             case 'u': tokenState = TokenState::unicodeValueOpen; break;
             default: AddToValueBuffer(c, saveValue, true);
         }
     }
ReportParseError()
void infra::JsonSubParser::ReportParseError () protected
Definition at line 264 of file JsonStreamingParser.cpp.
References destructedIndication, and subObjects.
Referenced by infra::JsonSubObjectParser::Feed(), and infra::JsonSubArrayParser::Feed().
     {
         bool destructed = false;
         destructedIndication = &destructed;
         for (auto subObject = subObjects.rbegin(); !destructed && subObject != subObjects.rend(); ++subObject)
             (*subObject)->Visitor().ParseError();
         if (!destructed)
         {
             subObjects.clear();
             destructedIndication = nullptr;
         }
     }
ReportSemanticError()
void infra::JsonSubParser::ReportSemanticError () protected
Definition at line 279 of file JsonStreamingParser.cpp.
References destructedIndication, and subObjects.
Referenced by infra::JsonSubObjectParser::Feed(), and infra::JsonSubArrayParser::Feed().
     {
         bool destructed = false;
         destructedIndication = &destructed;
         for (auto subObject = std::next(subObjects.rbegin()); !destructed && subObject != subObjects.rend(); ++subObject)
             (*subObject)->Visitor().SemanticError();
         if (!destructed)
         {
             subObjects.clear();
             destructedIndication = nullptr;
         }
     }
SetVisitor()
virtual void infra::JsonSubParser::SetVisitor (JsonVisitor & visitor) pure virtual
Implemented in infra::JsonSubArrayParser, and infra::JsonSubObjectParser.
Visitor()
virtual JsonVisitor& infra::JsonSubParser::Visitor () pure virtual
Implemented in infra::JsonSubArrayParser, and infra::JsonSubObjectParser.
Member Data Documentation
destructedIndication
bool* infra::JsonSubParser::destructedIndication = nullptr private
Definition at line 148 of file JsonStreamingParser.hpp.
Referenced by ReportParseError(), ReportSemanticError(), and ~JsonSubParser().
subObjects
infra::BoundedVector<infra::PolymorphicVariant<JsonSubParser, JsonSubObjectParser, JsonSubArrayParser> >& infra::JsonSubParser::subObjects protected
Definition at line 138 of file JsonStreamingParser.hpp.
Referenced by infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), ReportParseError(), and ReportSemanticError().
tagBuffer
infra::BoundedString infra::JsonSubParser::tagBuffer protected
Definition at line 136 of file JsonStreamingParser.hpp.
Referenced by infra::JsonSubObjectParser::Feed(), and infra::JsonSubArrayParser::Feed().
token
Token infra::JsonSubParser::token = Token::error protected
Definition at line 141 of file JsonStreamingParser.hpp.
Referenced by infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), and FoundToken().
tokenNumber
int64_t infra::JsonSubParser::tokenNumber protected
Definition at line 142 of file JsonStreamingParser.hpp.
Referenced by infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), and FeedToken().
tokenSign
int8_t infra::JsonSubParser::tokenSign protected
Definition at line 143 of file JsonStreamingParser.hpp.
Referenced by infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), and FeedToken().
tokenState
TokenState infra::JsonSubParser::tokenState = TokenState::open protected
Definition at line 140 of file JsonStreamingParser.hpp.
Referenced by AddToValueBuffer(), infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), FeedToken(), FoundToken(), and ProcessEscapedData().
unicode
uint16_t infra::JsonSubParser::unicode = 0 private
Definition at line 147 of file JsonStreamingParser.hpp.
Referenced by FeedToken().
unicodeIndex
uint8_t infra::JsonSubParser::unicodeIndex = 0 private
Definition at line 146 of file JsonStreamingParser.hpp.
Referenced by FeedToken().
valueBuffer
infra::BoundedString infra::JsonSubParser::valueBuffer protected
Definition at line 137 of file JsonStreamingParser.hpp.
Referenced by AddToValueBuffer(), infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), and FeedToken().
The documentation for this class was generated from the following files:
JsonStreamingParser.hpp
JsonStreamingParser.cpp