EMil: TestFlashSpi.cpp File Reference
TestFlashSpi.cpp File Reference
Classes
class FlashSpiTest
Functions
TEST_F (FlashSpiTest, Construction)
TEST_F (FlashSpiTest, ReadData)
TEST_F (FlashSpiTest, ReadId)
TEST_F (FlashSpiTest, ReadDataAtNonZeroAddress)
TEST_F (FlashSpiTest, WriteData)
TEST_F (FlashSpiTest, WriteDataFinishesOnFlagPoll)
TEST_F (FlashSpiTest, WriteDataAtNonZeroAddress)
TEST_F (FlashSpiTest, WhenPageBoundaryIsCrossedFirstPartIsWritten)
TEST_F (FlashSpiTest, WhenPageBoundaryIsCrossedSecondPartIsWritten)
TEST_F (FlashSpiTest, EraseFirstSubSector)
TEST_F (FlashSpiTest, EraseFirstSubSectorFinishesOnFlagPoll)
TEST_F (FlashSpiTest, EraseSecondSubSector)
TEST_F (FlashSpiTest, EraseMultipleErasesOneSubSector)
TEST_F (FlashSpiTest, EraseMultipleErasesTwoSubSectors)
TEST_F (FlashSpiTest, EraseMultipleErasesSector)
TEST_F (FlashSpiTest, EraseMultipleErasesSubSectorsAndSector)
TEST_F (FlashSpiTest, EraseAllErasesBulk)
Function Documentation
TEST_F() [1/17]
TEST_F (FlashSpiTest , Construction)
Definition at line 39 of file TestFlashSpi.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(512, flash.NumberOfSectors());
     EXPECT_EQ(4096, flash.SizeOfSector(0));
 }
TEST_F() [2/17]
TEST_F (FlashSpiTest , ReadData)
Definition at line 45 of file TestFlashSpi.cpp.
References services::FlashSpi::commandReadData, hal::continueSession, EXPECT_EQ(), and hal::stop.
 {
     std::vector<uint8_t> receiveData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandReadData, 0), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop))
         .WillOnce(testing::Return(receiveData));
     EXPECT_CALL(finished, callback());
     std::vector<uint8_t> buffer(4, 0);
     flash.ReadBuffer(buffer, 0, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_EQ(receiveData, buffer);
 }
TEST_F() [3/17]
TEST_F (FlashSpiTest , ReadId)
Definition at line 60 of file TestFlashSpi.cpp.
References services::FlashSpi::commandReadId, hal::continueSession, EXPECT_EQ(), and hal::stop.
 {
     std::vector<uint8_t> receiveData = { 1, 2, 3 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadId), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(receiveData));
     EXPECT_CALL(finished, callback());
     std::vector<uint8_t> buffer(3, 0);
     flash.ReadFlashId(buffer, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_EQ(receiveData, buffer);
 }
TEST_F() [4/17]
TEST_F (FlashSpiTest , ReadDataAtNonZeroAddress)
Definition at line 74 of file TestFlashSpi.cpp.
References services::FlashSpi::commandReadData, hal::continueSession, EXPECT_EQ(), and hal::stop.
 {
     std::vector<uint8_t> receiveData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandReadData, 0x123456), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop))
         .WillOnce(testing::Return(receiveData));
     EXPECT_CALL(finished, callback());
     std::vector<uint8_t> buffer(4, 0);
     flash.ReadBuffer(buffer, 0 + 0x123456, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_EQ(receiveData, buffer);
 }
TEST_F() [5/17]
TEST_F (FlashSpiTest , WriteData)
Definition at line 89 of file TestFlashSpi.cpp.
References services::FlashSpi::commandPageProgram, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     const std::vector<uint8_t> sendData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandPageProgram, 0), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, SendDataMock(sendData, hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.WriteBuffer(sendData, 0, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [6/17]
TEST_F (FlashSpiTest , WriteDataFinishesOnFlagPoll)
Definition at line 102 of file TestFlashSpi.cpp.
References services::FlashSpi::commandPageProgram, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     const std::vector<uint8_t> sendData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandPageProgram, 0), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, SendDataMock(sendData, hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{0}));
     EXPECT_CALL(finished, callback());
     flash.WriteBuffer(sendData, 0, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [7/17]
TEST_F (FlashSpiTest , WriteDataAtNonZeroAddress)
Definition at line 116 of file TestFlashSpi.cpp.
References services::FlashSpi::commandPageProgram, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, infra::emptyFunction, and hal::stop.
 {
     const std::vector<uint8_t> sendData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandPageProgram, 0x123456), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, SendDataMock(sendData, hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.WriteBuffer(sendData, 0 + 0x123456, infra::emptyFunction);
     ExecuteAllActions();
 }
TEST_F() [8/17]
TEST_F (FlashSpiTest , WhenPageBoundaryIsCrossedFirstPartIsWritten)
Definition at line 129 of file TestFlashSpi.cpp.
References services::FlashSpi::commandPageProgram, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, infra::emptyFunction, and hal::stop.
 {
     const std::vector<uint8_t> sendData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandPageProgram, 254), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, SendDataMock(std::vector<uint8_t>{ 1, 2 }, hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.WriteBuffer(sendData, 0 + 254, infra::emptyFunction);
     ExecuteAllActions();
 }
TEST_F() [9/17]
TEST_F (FlashSpiTest , WhenPageBoundaryIsCrossedSecondPartIsWritten)
Definition at line 142 of file TestFlashSpi.cpp.
References services::FlashSpi::commandPageProgram, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, infra::emptyFunction, and hal::stop.
 {
     testing::InSequence s;
     const std::vector<uint8_t> sendData = { 1, 2, 3, 4, 5, 6 };
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandPageProgram, 254), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, SendDataMock(std::vector<uint8_t>{ 1, 2 }, hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{0}));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandPageProgram, 256), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, SendDataMock(std::vector<uint8_t>{ 3, 4, 5, 6 }, hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.WriteBuffer(sendData, 0 + 254, infra::emptyFunction);
     ExecuteAllActions();
 }
TEST_F() [10/17]
TEST_F (FlashSpiTest , EraseFirstSubSector)
Definition at line 162 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSubSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 0), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseSector(0, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [11/17]
TEST_F (FlashSpiTest , EraseFirstSubSectorFinishesOnFlagPoll)
Definition at line 173 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSubSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 0), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{0}));
     EXPECT_CALL(finished, callback());
     flash.EraseSector(0, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [12/17]
TEST_F (FlashSpiTest , EraseSecondSubSector)
Definition at line 185 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSubSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 4096), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseSector(1, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [13/17]
TEST_F (FlashSpiTest , EraseMultipleErasesOneSubSector)
Definition at line 196 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSubSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 0), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseSectors(0, 1, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [14/17]
TEST_F (FlashSpiTest , EraseMultipleErasesTwoSubSectors)
Definition at line 207 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSubSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     testing::InSequence s;
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 0), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{0}));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 4096), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseSectors(0, 2, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [15/17]
TEST_F (FlashSpiTest , EraseMultipleErasesSector)
Definition at line 224 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSector, 0), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseSectors(0, 16, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [16/17]
TEST_F (FlashSpiTest , EraseMultipleErasesSubSectorsAndSector)
Definition at line 235 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseSector, services::FlashSpi::commandEraseSubSector, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     testing::InSequence s;
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 61440), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{0}));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSector, 65536), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{0}));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstructionAndAddress(services::FlashSpi::commandEraseSubSector, 131072), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseSectors(15, 33, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [17/17]
TEST_F (FlashSpiTest , EraseAllErasesBulk)
Definition at line 256 of file TestFlashSpi.cpp.
References services::FlashSpi::commandEraseBulk, services::FlashSpi::commandReadStatusRegister, services::FlashSpi::commandWriteEnable, hal::continueSession, and hal::stop.
 {
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandWriteEnable), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandEraseBulk), hal::SpiAction::stop));
     EXPECT_CALL(spiMock, SendDataMock(CreateInstruction(services::FlashSpi::commandReadStatusRegister), hal::SpiAction::continueSession));
     EXPECT_CALL(spiMock, ReceiveDataMock(hal::SpiAction::stop)).WillOnce(testing::Return(std::vector<uint8_t>{1}));
     flash.EraseAll([this]() { finished.callback(); });
     ExecuteAllActions();
 }