EMil: services::ConnectionSerial::SerialConnectionStreamReader Class Reference
services::ConnectionSerial::SerialConnectionStreamReader Class Reference
Public Member Functions
SerialConnectionStreamReader (infra::BoundedDeque< uint8_t > &receivedDataQueue)
virtual void Extract (infra::ByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (infra::StreamErrorPolicy &errorPolicy) override
virtual infra::ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual infra::ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
virtual std::size_t ConstructSaveMarker () const override
virtual void Rewind (std::size_t marker) override
size_t ConsumeExtracted ()
Private Attributes
infra::BoundedDeque< uint8_t > & receivedDataQueue
size_t extractedAmount = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 291 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
SerialConnectionStreamReader()
services::ConnectionSerial::SerialConnectionStreamReader::SerialConnectionStreamReader (infra::BoundedDeque< uint8_t > & receivedDataQueue) explicit
Definition at line 703 of file ConnectionSerial.cpp.
         : receivedDataQueue(receivedDataQueue)
     {}
Member Function Documentation
Available()
size_t services::ConnectionSerial::SerialConnectionStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 766 of file ConnectionSerial.cpp.
References services::ConnectionSerial::receivedDataQueue, and infra::BoundedDeque< T >::size().
     {
         return receivedDataQueue.size() - extractedAmount;
     }
ConstructSaveMarker()
std::size_t services::ConnectionSerial::SerialConnectionStreamReader::ConstructSaveMarker () const override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 707 of file ConnectionSerial.cpp.
     {
         std::abort();
     }
ConsumeExtracted()
size_t services::ConnectionSerial::SerialConnectionStreamReader::ConsumeExtracted ()
Definition at line 771 of file ConnectionSerial.cpp.
References infra::BoundedDeque< T >::pop_front(), and services::ConnectionSerial::receivedDataQueue.
     {
         for (size_t i = 0; i < extractedAmount; i++)
             receivedDataQueue.pop_front();
         return extractedAmount;
     }
Empty()
bool services::ConnectionSerial::SerialConnectionStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 761 of file ConnectionSerial.cpp.
     {
         return Available() == 0;
     }
Extract()
void services::ConnectionSerial::SerialConnectionStreamReader::Extract (infra::ByteRange range, infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 717 of file ConnectionSerial.cpp.
References infra::Copy(), infra::StreamErrorPolicy::Failed(), infra::Head(), infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::size(), and infra::Tail().
     {
         errorPolicy.ReportResult(Available() >= range.size());
         if (errorPolicy.Failed())
             return;
         infra::ConstByteRange extractedRange1 = ExtractContiguousRange(range.size());
         infra::Copy(extractedRange1, infra::Head(range, extractedRange1.size()));
         if (extractedRange1.size() < range.size())
         {
             size_t diff = range.size() - extractedRange1.size();
             infra::ConstByteRange extractedRange2 = ExtractContiguousRange(diff);
             infra::Copy(extractedRange2, infra::Tail(range, diff));
         }
     }
ExtractContiguousRange()
infra::ConstByteRange services::ConnectionSerial::SerialConnectionStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 745 of file ConnectionSerial.cpp.
References infra::BoundedDeque< T >::begin(), infra::BoundedDeque< T >::contiguous_range(), infra::Head(), services::ConnectionSerial::receivedDataQueue, and infra::MemoryRange< T >::size().
     {
         infra::ByteRange range = infra::Head(receivedDataQueue.contiguous_range(receivedDataQueue.begin() + extractedAmount), max);
         extractedAmount += range.size();
         return range;
     }
Peek()
uint8_t services::ConnectionSerial::SerialConnectionStreamReader::Peek (infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 735 of file ConnectionSerial.cpp.
References infra::StreamErrorPolicy::Failed(), services::ConnectionSerial::receivedDataQueue, and infra::StreamErrorPolicy::ReportResult().
     {
         errorPolicy.ReportResult(Available() > 0);
         if (errorPolicy.Failed())
             return 0;
         return receivedDataQueue[extractedAmount];
     }
PeekContiguousRange()
infra::ConstByteRange services::ConnectionSerial::SerialConnectionStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 753 of file ConnectionSerial.cpp.
References infra::BoundedDeque< T >::begin(), infra::BoundedDeque< T >::contiguous_range(), services::ConnectionSerial::receivedDataQueue, and infra::BoundedDeque< T >::size().
     {
         if (start >= receivedDataQueue.size() - extractedAmount)
             return infra::ConstByteRange();
         return receivedDataQueue.contiguous_range(receivedDataQueue.begin() + extractedAmount + start);
     }
Rewind()
void services::ConnectionSerial::SerialConnectionStreamReader::Rewind (std::size_t marker) override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 712 of file ConnectionSerial.cpp.
     {
         std::abort();
     }
Member Data Documentation
extractedAmount
size_t services::ConnectionSerial::SerialConnectionStreamReader::extractedAmount = 0 private
Definition at line 310 of file ConnectionSerial.hpp.
receivedDataQueue
infra::BoundedDeque<uint8_t>& services::ConnectionSerial::SerialConnectionStreamReader::receivedDataQueue private
Definition at line 309 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp