EMil: infra::FixedPoint< T, Factor > Struct Template Reference
infra::FixedPoint< T, Factor > Struct Template Reference
#include <FixedPoint.hpp>
Public Member Functions
FixedPoint ()=default
FixedPoint (T integerPart, T fractionalPart)
FixedPoint (Scaled, T v)
FixedPoint (Unscaled, T v)
T AsUnscaled () const
T IntegerPart () const
T FractionalPart () const
T Rounded () const
FixedPoint & operator+= (const FixedPoint &x)
FixedPoint & operator-= (const FixedPoint &x)
FixedPoint & operator*= (const FixedPoint &x)
FixedPoint & operator/= (const FixedPoint &x)
FixedPoint & operator*= (T x)
FixedPoint & operator/= (T x)
FixedPoint operator- () const
Private Attributes
T value = 0
Detailed Description
template<class T, T Factor>
struct infra::FixedPoint< T, Factor >
Definition at line 12 of file FixedPoint.hpp.
Constructor & Destructor Documentation
FixedPoint() [1/4]
template<class T, T Factor> infra::FixedPoint< T, Factor >::FixedPoint () default
FixedPoint() [2/4]
template<class T , T Factor> infra::FixedPoint< T, Factor >::FixedPoint (T integerPart, T fractionalPart)
Definition at line 39 of file FixedPoint.hpp.
         : value(integerPart * Factor + fractionalPart)
     {}
FixedPoint() [3/4]
template<class T , T Factor> infra::FixedPoint< T, Factor >::FixedPoint (Scaled , T v)
Definition at line 44 of file FixedPoint.hpp.
         : value(v * Factor)
     {}
FixedPoint() [4/4]
template<class T , T Factor> infra::FixedPoint< T, Factor >::FixedPoint (Unscaled , T v)
Definition at line 49 of file FixedPoint.hpp.
         : value(v)
     {}
Member Function Documentation
AsUnscaled()
template<class T , T Factor> T infra::FixedPoint< T, Factor >::AsUnscaled () const
Definition at line 54 of file FixedPoint.hpp.
References value.
Referenced by infra::operator!=(), infra::operator<(), infra::operator==(), infra::operator>(), and infra::operator>=().
 { return value; }
FractionalPart()
template<class T , T Factor> T infra::FixedPoint< T, Factor >::FractionalPart () const
Definition at line 58 of file FixedPoint.hpp.
References value.
 { return value % Factor; }
IntegerPart()
template<class T , T Factor> T infra::FixedPoint< T, Factor >::IntegerPart () const
Definition at line 56 of file FixedPoint.hpp.
References value.
 { return value / Factor; }
operator*=() [1/2]
template<class T , T Factor> FixedPoint< T, Factor > & infra::FixedPoint< T, Factor >::operator*= (const FixedPoint< T, Factor > & x)
Definition at line 67 of file FixedPoint.hpp.
References value, and infra::FixedPoint< T, Factor >::value.
 { value *= x.value; value /= Factor; return *this; }
operator*=() [2/2]
template<class T , T Factor> FixedPoint< T, Factor > & infra::FixedPoint< T, Factor >::operator*= (T x)
Definition at line 71 of file FixedPoint.hpp.
References value.
 { value *= x; return *this; }
operator+=()
template<class T , T Factor> FixedPoint< T, Factor > & infra::FixedPoint< T, Factor >::operator+= (const FixedPoint< T, Factor > & x)
Definition at line 63 of file FixedPoint.hpp.
References value, and infra::FixedPoint< T, Factor >::value.
 { value += x.value; return *this; }
operator-()
template<class T , T Factor> FixedPoint< T, Factor > infra::FixedPoint< T, Factor >::operator- () const
Definition at line 75 of file FixedPoint.hpp.
References value, and infra::FixedPoint< T, Factor >::value.
 { FixedPoint result; result.value = -value; return result; }
operator-=()
template<class T , T Factor> FixedPoint< T, Factor > & infra::FixedPoint< T, Factor >::operator-= (const FixedPoint< T, Factor > & x)
Definition at line 65 of file FixedPoint.hpp.
References value, and infra::FixedPoint< T, Factor >::value.
 { value -= x.value; return *this; }
operator/=() [1/2]
template<class T , T Factor> FixedPoint< T, Factor > & infra::FixedPoint< T, Factor >::operator/= (const FixedPoint< T, Factor > & x)
Definition at line 69 of file FixedPoint.hpp.
References value, and infra::FixedPoint< T, Factor >::value.
 { value *= Factor; value /= x.value; return *this; }
operator/=() [2/2]
template<class T , T Factor> FixedPoint< T, Factor > & infra::FixedPoint< T, Factor >::operator/= (T x)
Definition at line 73 of file FixedPoint.hpp.
References value.
 { value /= x; return *this; }
Rounded()
template<class T , T Factor> T infra::FixedPoint< T, Factor >::Rounded () const
Definition at line 60 of file FixedPoint.hpp.
References value.
 { return value >= 0 ? (value + Factor / 2) / Factor : (value - Factor / 2) / Factor; }
Member Data Documentation
value
template<class T, T Factor> T infra::FixedPoint< T, Factor >::value = 0 private
Definition at line 33 of file FixedPoint.hpp.
Referenced by infra::FixedPoint< T, Factor >::operator*=(), infra::FixedPoint< T, Factor >::operator+=(), infra::FixedPoint< T, Factor >::operator-(), infra::FixedPoint< T, Factor >::operator-=(), and infra::FixedPoint< T, Factor >::operator/=().
The documentation for this struct was generated from the following file:
FixedPoint.hpp