EMil: TestCertificatesMbedTls.cpp File Reference
TestCertificatesMbedTls.cpp File Reference
Classes
class CertificatesMbedTlsWithVerify
class CertificatesMbedTlsTest
Functions
bool operator== (const mbedtls_x509_time &lhs, const mbedtls_x509_time &rhs)
bool CompareStringIgnoreNewline (const std::string &expected, const std::string &actual, std::string ignore="\")
TEST_F (CertificatesMbedTlsTest, write_private_key)
TEST_F (CertificatesMbedTlsTest, generate_new_key)
TEST_F (CertificatesMbedTlsTest, write_certificate)
TEST_F (CertificatesMbedTlsTest, update_valid_to_date)
TEST_F (CertificatesMbedTlsTest, sign_certificate_with_new_key)
Function Documentation
CompareStringIgnoreNewline()
bool CompareStringIgnoreNewline (const std::string & expected, const std::string & actual, std::string ignore = "\r\n")
Definition at line 45 of file TestCertificatesMbedTls.cpp.
Referenced by TEST_F().
 {
     size_t expectedIndex = 0;
     size_t actualIndex = 0;
     while (true)
     {
         while (expectedIndex < expected.size() && ignore.find_first_of(expected[expectedIndex]) != std::string::npos)
             expectedIndex++;
         while (actualIndex < actual.size() && ignore.find_first_of(actual[actualIndex]) != std::string::npos)
             actualIndex++;
         if (expectedIndex >= expected.size())
             return actualIndex >= actual.size();
         if (actualIndex >= actual.size())
             return false;
         if (expected[expectedIndex++] != actual[actualIndex++])
             return false;
     }
     return true;
 }
operator==()
bool operator== (const mbedtls_x509_time & lhs, const mbedtls_x509_time & rhs)
Definition at line 7 of file TestCertificatesMbedTls.cpp.
Referenced by TEST().
 {
     return lhs.year == rhs.year &&
         lhs.mon == rhs.mon &&
         lhs.day == rhs.day &&
         lhs.hour == rhs.hour &&
         lhs.min == rhs.min &&
         lhs.sec == rhs.sec;
 }
TEST_F() [1/5]
TEST_F (CertificatesMbedTlsTest , write_private_key)
Definition at line 83 of file TestCertificatesMbedTls.cpp.
References CompareStringIgnoreNewline(), and EXPECT_TRUE().
 {
     infra::BoundedString::WithStorage<2048> privateKey;
     certificates.WritePrivateKey(privateKey);
     EXPECT_TRUE(CompareStringIgnoreNewline(mbedtls_test_srv_key, privateKey.data()));
 }
TEST_F() [2/5]
TEST_F (CertificatesMbedTlsTest , generate_new_key)
Definition at line 91 of file TestCertificatesMbedTls.cpp.
References CompareStringIgnoreNewline(), and EXPECT_FALSE().
 {
     certificates.GenerateNewKey(randomDataGenerator);
     infra::BoundedString::WithStorage<2048> privateKey;
     certificates.WritePrivateKey(privateKey);
     EXPECT_FALSE(CompareStringIgnoreNewline(mbedtls_test_srv_key, privateKey.data()));
 }
TEST_F() [3/5]
TEST_F (CertificatesMbedTlsTest , write_certificate)
Definition at line 101 of file TestCertificatesMbedTls.cpp.
 {
     infra::BoundedString::WithStorage<2048> ownCertificate;
     certificates.WriteOwnCertificate(ownCertificate, randomDataGenerator);
     certificates.VerifyCertificate();
 }
TEST_F() [4/5]
TEST_F (CertificatesMbedTlsTest , update_valid_to_date)
Definition at line 109 of file TestCertificatesMbedTls.cpp.
 {
     certificates.UpdateValidToDate();
     infra::BoundedString::WithStorage<2048> ownCertificate;
     certificates.WriteOwnCertificate(ownCertificate, randomDataGenerator);
     certificates.CompareDate({ 9999, 12, 31, 23, 59, 59 });
 }
TEST_F() [5/5]
TEST_F (CertificatesMbedTlsTest , sign_certificate_with_new_key)
Definition at line 119 of file TestCertificatesMbedTls.cpp.
 {
     infra::BoundedString::WithStorage<2048> privateKey;
     certificates.GenerateNewKey(randomDataGenerator);
     certificates.WritePrivateKey(privateKey);
     infra::BoundedString::WithStorage<2048> ownCertificate;
     certificates.WriteOwnCertificate(ownCertificate, randomDataGenerator);
     certificates.VerifyCertificate();
 }