EMil: TestAsn1.cpp File Reference
TestAsn1.cpp File Reference
Functions
TEST (Asn1Test, get_integer)
TEST (Asn1Test, get_integer_1_byte_length)
TEST (Asn1Test, get_integer_2_byte_length)
TEST (Asn1Test, get_sequence)
TEST (Asn1Test, get_second_integer)
TEST (Asn1Test, iterator_end)
TEST (Asn1Test, dereference_iterator)
TEST (Asn1Test, increment_iterator)
Function Documentation
TEST() [1/8]
TEST (Asn1Test , get_integer)
Definition at line 4 of file TestAsn1.cpp.
References data, EXPECT_EQ(), infra::Asn1Sequence::front(), and infra::Asn1Value::Integer().
 {
     std::array<uint8_t, 3> data = { { 0x02, 0x01, 0xab } };
     infra::Asn1Sequence sequence(data);
     EXPECT_EQ(infra::ConstByteRange(data.data() + 2, data.data() + 3), sequence.front().Integer());
 }
TEST() [2/8]
TEST (Asn1Test , get_integer_1_byte_length)
Definition at line 12 of file TestAsn1.cpp.
References data, EXPECT_EQ(), infra::Asn1Sequence::front(), and infra::Asn1Value::Integer().
 {
     std::array<uint8_t, 4> data = { { 0x02, 0x81, 0x01, 0xab } };
     infra::Asn1Sequence sequence(data);
     EXPECT_EQ(infra::ConstByteRange(data.data() + 3, data.data() + 4), sequence.front().Integer());
 }
TEST() [3/8]
TEST (Asn1Test , get_integer_2_byte_length)
Definition at line 20 of file TestAsn1.cpp.
References data, EXPECT_EQ(), infra::Asn1Sequence::front(), and infra::Asn1Value::Integer().
 {
     std::array<uint8_t, 5> data = { { 0x02, 0x82, 0x00, 0x01, 0xab } };
     infra::Asn1Sequence sequence(data);
     EXPECT_EQ(infra::ConstByteRange(data.data() + 4, data.data() + 5), sequence.front().Integer());
 }
TEST() [4/8]
TEST (Asn1Test , get_sequence)
Definition at line 28 of file TestAsn1.cpp.
References infra::Asn1Sequence::begin(), data, EXPECT_EQ(), EXPECT_FALSE(), and infra::Asn1Value::Sequence().
 {
     std::array<uint8_t, 8> data = { { 0x30, 0x06, 0x02, 0x04, 0xFF, 0xFF, 0xFF, 0xFF } };
     infra::Asn1Sequence sequence(data);
     EXPECT_EQ(infra::Asn1Sequence(infra::ConstByteRange(data.data() + 2, data.data() + 8)), sequence.begin()->Sequence());
     EXPECT_FALSE(infra::Asn1Sequence(infra::ConstByteRange(data.data() + 2, data.data() + 8)) != sequence.begin()->Sequence());
 }
TEST() [5/8]
TEST (Asn1Test , get_second_integer)
Definition at line 37 of file TestAsn1.cpp.
References infra::Asn1Sequence::begin(), data, and EXPECT_EQ().
 {
     std::array<uint8_t, 6> data = { { 0x02, 0x01, 0xab, 0x02, 0x01, 0xcd } };
     infra::Asn1Sequence sequence(data);
     EXPECT_EQ(infra::ConstByteRange(data.data() + 5, data.data() + 6), std::next(sequence.begin())->Integer());
     EXPECT_EQ(infra::ConstByteRange(data.data() + 5, data.data() + 6), sequence[1].Integer());
 }
TEST() [6/8]
TEST (Asn1Test , iterator_end)
Definition at line 46 of file TestAsn1.cpp.
References data, infra::Asn1Sequence::end(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     std::array<uint8_t, 3> data = { { 0x02, 0x01, 0xab } };
     infra::Asn1Sequence sequence(data);
     EXPECT_TRUE(sequence.end() == infra::Asn1SequenceIterator());
     EXPECT_FALSE(sequence.end() != infra::Asn1SequenceIterator());
 }
TEST() [7/8]
TEST (Asn1Test , dereference_iterator)
Definition at line 55 of file TestAsn1.cpp.
References infra::Asn1Sequence::begin(), data, EXPECT_EQ(), and infra::Asn1Value::Integer().
 {
     std::array<uint8_t, 3> data = { { 0x02, 0x01, 0xab } };
     infra::Asn1Sequence sequence(data);
     EXPECT_EQ(infra::ConstByteRange(data.data() + 2, data.data() + 3), (*sequence.begin()).Integer());
     EXPECT_EQ(infra::ConstByteRange(data.data() + 2, data.data() + 3), (*static_cast<const infra::Asn1SequenceIterator&>(sequence.begin())).Integer());
     EXPECT_EQ(infra::ConstByteRange(data.data() + 2, data.data() + 3), sequence.begin().operator->()->Integer());
     EXPECT_EQ(infra::ConstByteRange(data.data() + 2, data.data() + 3), static_cast<const infra::Asn1SequenceIterator&>(sequence.begin()).operator->()->Integer());
 }
TEST() [8/8]
TEST (Asn1Test , increment_iterator)
Definition at line 66 of file TestAsn1.cpp.
References infra::Asn1Sequence::begin(), data, and EXPECT_EQ().
 {
     std::array<uint8_t, 6> data = { { 0x02, 0x01, 0xab, 0x02, 0x01, 0xcd } };
     infra::Asn1Sequence sequence(data);
     infra::Asn1SequenceIterator iterator = sequence.begin();
     EXPECT_EQ(sequence[1].Integer(), (++iterator)->Integer());
     infra::Asn1SequenceIterator iterator2 = sequence.begin();
     EXPECT_EQ(sequence[0].Integer(), (iterator2++)->Integer());
     EXPECT_EQ(sequence[1].Integer(), (iterator2++)->Integer());
 }