EMil: hal::QuadSpi::Lines Struct Reference
hal::QuadSpi::Lines Struct Reference
#include <QuadSpi.hpp>
Public Member Functions
bool operator== (const Lines &other) const
bool operator!= (const Lines &other) const
Static Public Member Functions
static Lines SingleSpeed ()
static Lines QuadSpeed ()
static Lines MixedSpeed (uint8_t instructionLines, uint8_t addressLines, uint8_t alternateLines, uint8_t dataLines)
static Lines MixedSpeed (uint8_t instructionLines, uint8_t addressLines, uint8_t dataLines)
Public Attributes
uint8_t instructionLines = 1
uint8_t addressLines = 1
uint8_t alternateLines = 1
uint8_t dataLines = 1
Private Member Functions
Lines (uint8_t instructionLines, uint8_t addressLines, uint8_t alternateLines, uint8_t dataLines)
Detailed Description
Definition at line 26 of file QuadSpi.hpp.
Constructor & Destructor Documentation
Lines()
hal::QuadSpi::Lines::Lines (uint8_t instructionLines, uint8_t addressLines, uint8_t alternateLines, uint8_t dataLines) private
Definition at line 6 of file QuadSpi.cpp.
         : instructionLines(instructionLines)
         , addressLines(addressLines)
         , alternateLines(alternateLines)
         , dataLines(dataLines)
     {}
Member Function Documentation
MixedSpeed() [1/2]
QuadSpi::Lines hal::QuadSpi::Lines::MixedSpeed (uint8_t instructionLines, uint8_t addressLines, uint8_t alternateLines, uint8_t dataLines) static
Definition at line 23 of file QuadSpi.cpp.
     {
         return Lines(instructionLines, addressLines, alternateLines, dataLines);
     }
MixedSpeed() [2/2]
QuadSpi::Lines hal::QuadSpi::Lines::MixedSpeed (uint8_t instructionLines, uint8_t addressLines, uint8_t dataLines) static
Definition at line 28 of file QuadSpi.cpp.
     {
         return Lines(instructionLines, addressLines, dataLines, dataLines);
     }
operator!=()
bool hal::QuadSpi::Lines::operator!= (const Lines & other) const
Definition at line 42 of file QuadSpi.cpp.
     {
         return !(*this == other);
     }
operator==()
bool hal::QuadSpi::Lines::operator== (const Lines & other) const
Definition at line 33 of file QuadSpi.cpp.
References addressLines, alternateLines, dataLines, and instructionLines.
     {
         return infra::Equals()
             (instructionLines, other.instructionLines)
             (addressLines, other.addressLines)
             (alternateLines, other.alternateLines)
             (dataLines, other.dataLines);
     }
QuadSpeed()
QuadSpi::Lines hal::QuadSpi::Lines::QuadSpeed () static
Definition at line 18 of file QuadSpi.cpp.
Referenced by services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress(), services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiCypressFll::ReadBuffer(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiMicronN25q::SendEraseBulk(), services::FlashQuadSpiCypressFll::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), services::FlashQuadSpiCypressFll::SwitchToSingleSpeed(), services::FlashQuadSpiMicronN25q::WriteEnable(), and services::FlashQuadSpiCypressFll::WriteEnable().
     {
         return Lines(4, 4, 4, 4);
     }
SingleSpeed()
QuadSpi::Lines hal::QuadSpi::Lines::SingleSpeed () static
Definition at line 13 of file QuadSpi.cpp.
Referenced by services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiSingleSpeed::SendEraseChip(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToQuadSpeed(), services::FlashQuadSpiSingleSpeed::WriteEnable(), and services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed().
     {
         return Lines(1, 1, 1, 1);
     }
Member Data Documentation
addressLines
uint8_t hal::QuadSpi::Lines::addressLines = 1
Definition at line 29 of file QuadSpi.hpp.
Referenced by operator==().
alternateLines
uint8_t hal::QuadSpi::Lines::alternateLines = 1
Definition at line 30 of file QuadSpi.hpp.
Referenced by operator==().
dataLines
uint8_t hal::QuadSpi::Lines::dataLines = 1
Definition at line 31 of file QuadSpi.hpp.
Referenced by operator==().
instructionLines
uint8_t hal::QuadSpi::Lines::instructionLines = 1
Definition at line 28 of file QuadSpi.hpp.
Referenced by operator==().
The documentation for this struct was generated from the following files:
QuadSpi.hpp
QuadSpi.cpp