EMil: infra::DataInputStream Class Reference
infra::DataInputStream Class Reference
#include <InputStream.hpp>
Classes
class WithErrorPolicy
class WithReader
Public Member Functions
TextInputStream operator>> (Text)
DataInputStream & operator>> (ByteRange range)
template<class Data >
DataInputStream & operator>> (Data &data)
template<class Data >
Data Extract ()
InputStream (StreamReader &reader, StreamErrorPolicy &errorPolicy)
Public Member Functions inherited from infra::InputStream
InputStream (StreamReader &reader, StreamErrorPolicy &errorPolicy)
bool Empty () const
std::size_t Available () const
ConstByteRange ContiguousRange (std::size_t max=std::numeric_limits< std::size_t >::max()) const
ConstByteRange PeekContiguousRange (std::size_t start=0) const
void Consume (std::size_t amount)
bool Failed () const
StreamReader & Reader () const
StreamErrorPolicy & ErrorPolicy () const
Additional Inherited Members
Protected Member Functions inherited from infra::InputStream
~InputStream ()=default
Detailed Description
Definition at line 66 of file InputStream.hpp.
Member Function Documentation
Extract()
template<class Data > Data infra::DataInputStream::Extract ()
Definition at line 223 of file InputStream.hpp.
     {
         Data result{};
         *this >> result;
         return result;
     }
InputStream()
infra::InputStream::InputStream
Definition at line 6 of file InputStream.cpp.
         : reader(reader)
         , errorPolicy(errorPolicy)
     {}
operator>>() [1/3]
TextInputStream infra::DataInputStream::operator>> (Text)
Definition at line 62 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), and infra::InputStream::Reader().
     {
         return TextInputStream(Reader(), ErrorPolicy());
     }
operator>>() [2/3]
DataInputStream & infra::DataInputStream::operator>> (ByteRange range)
Definition at line 67 of file InputStream.cpp.
References infra::data, infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), and infra::InputStream::Reader().
     {
         Reader().Extract(data, ErrorPolicy());
         return *this;
     }
operator>>() [3/3]
template<class Data > DataInputStream & infra::DataInputStream::operator>> (Data & data)
Definition at line 215 of file InputStream.hpp.
References infra::data, infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeRange(), infra::InputStream::Reader(), and infra::ReinterpretCastMemoryRange().
     {
         MemoryRange<typename std::remove_const<uint8_t>::type> dataRange(ReinterpretCastMemoryRange<typename std::remove_const<uint8_t>::type>(MakeRange(&data, &data + 1)));
         Reader().Extract(dataRange, ErrorPolicy());
         return *this;
     }
The documentation for this class was generated from the following files:
InputStream.hpp
InputStream.cpp