EMil: hal::SpiMaster Class Reference
hal::SpiMaster Class Reference abstract
#include <Spi.hpp>
Public Member Functions
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> &onDone)=0
virtual void SetChipSelectConfigurator (ChipSelectConfigurator &configurator)=0
virtual void SetCommunicationConfigurator (CommunicationConfigurator &configurator)=0
virtual void ResetCommunicationConfigurator ()=0
Protected Member Functions
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Detailed Description
Definition at line 31 of file Spi.hpp.
Constructor & Destructor Documentation
SpiMaster() [1/2]
hal::SpiMaster::SpiMaster () protected default
SpiMaster() [2/2]
hal::SpiMaster::SpiMaster (const SpiMaster & other) protected delete
~SpiMaster()
hal::SpiMaster::~SpiMaster () protected default
Member Function Documentation
operator=()
SpiMaster& hal::SpiMaster::operator= (const SpiMaster & other) protected delete
ReceiveData()
void hal::SpiMaster::ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> & onDone)
Definition at line 10 of file Spi.cpp.
References infra::data, and SendAndReceive().
Referenced by services::FlashSpi::ReadBuffer(), services::FlashSpi::ReadFlashId(), and services::FlashSpi::ReadStatusRegister().
     {
         SendAndReceive(infra::ConstByteRange(), data, nextAction, onDone);
     }
ResetCommunicationConfigurator()
virtual void hal::SpiMaster::ResetCommunicationConfigurator () pure virtual
Implemented in services::SpiMultipleAccess, hal::LowPowerSpiMaster, services::SpiMultipleAccessMaster, and services::SpiMasterWithChipSelect.
Referenced by services::SpiMasterWithChipSelect::ResetCommunicationConfigurator(), services::SpiMultipleAccessMaster::ResetCommunicationConfigurator(), and hal::LowPowerSpiMaster::ResetCommunicationConfigurator().
SendAndReceive()
virtual void hal::SpiMaster::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> & onDone) pure virtual
Implemented in services::SpiMultipleAccess, hal::LowPowerSpiMaster, services::SpiMultipleAccessMaster, and services::SpiMasterWithChipSelect.
Referenced by ReceiveData(), services::SpiMasterWithChipSelect::SendAndReceive(), services::SpiMultipleAccessMaster::SendAndReceive(), hal::LowPowerSpiMaster::SendAndReceive(), and SendData().
SendData()
void hal::SpiMaster::SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> & onDone)
Definition at line 5 of file Spi.cpp.
References infra::data, and SendAndReceive().
Referenced by services::FlashSpi::PageProgram(), services::FlashSpi::ReadBuffer(), services::FlashSpi::ReadFlashId(), services::FlashSpi::ReadStatusRegister(), services::FlashSpi::SendEraseBulk(), services::FlashSpi::SendEraseSector(), services::FlashSpi::SendEraseSubSector(), and services::FlashSpi::WriteEnable().
     {
         SendAndReceive(data, infra::ByteRange(), nextAction, onDone);
     }
SetChipSelectConfigurator()
virtual void hal::SpiMaster::SetChipSelectConfigurator (ChipSelectConfigurator & configurator) pure virtual
Implemented in services::SpiMultipleAccess, hal::LowPowerSpiMaster, services::SpiMultipleAccessMaster, and services::SpiMasterWithChipSelect.
Referenced by services::SpiMultipleAccessMaster::SetChipSelectConfigurator(), hal::LowPowerSpiMaster::SetChipSelectConfigurator(), and services::SpiMasterWithChipSelect::SpiMasterWithChipSelect().
SetCommunicationConfigurator()
virtual void hal::SpiMaster::SetCommunicationConfigurator (CommunicationConfigurator & configurator) pure virtual
Implemented in services::SpiMultipleAccess, hal::LowPowerSpiMaster, services::SpiMultipleAccessMaster, and services::SpiMasterWithChipSelect.
Referenced by services::SpiMasterWithChipSelect::SetCommunicationConfigurator(), services::SpiMultipleAccessMaster::SetCommunicationConfigurator(), and hal::LowPowerSpiMaster::SetCommunicationConfigurator().
The documentation for this class was generated from the following files:
Spi.hpp
Spi.cpp