EMil: infra::TimerService Class Reference
infra::TimerService Class Reference abstract
#include <TimerService.hpp>
Public Member Functions
uint32_t Id () const
void RegisterTimer (Timer &timer)
void UnregisterTimer (Timer &timer, TimePoint oldTriggerTime)
void UpdateTriggerTime (Timer &timer, TimePoint oldTriggerTime)
void Progressed (TimePoint time)
TimePoint NextTrigger () const
virtual void NextTriggerChanged ()
virtual TimePoint Now () const =0
virtual Duration Resolution () const =0
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
TimerService (uint32_t id)
TimerService (const TimerService &other)=delete
~TimerService ()
TimerService & operator= (const TimerService &other)=delete
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Member Functions
void ComputeNextTrigger ()
Private Attributes
uint32_t id
infra::IntrusiveForwardList< Timer > scheduledTimers
infra::IntrusiveForwardList< Timer >::iterator timerIterator
TimePoint nextTrigger = TimePoint::max()
bool holdUpdate = false
bool updateNeeded = false
Detailed Description
Definition at line 9 of file TimerService.hpp.
Constructor & Destructor Documentation
TimerService() [1/2]
infra::TimerService::TimerService (uint32_t id) explicit protected
Definition at line 6 of file TimerService.cpp.
References infra::InterfaceConnector< TimerServiceManager >::Instance(), and infra::TimerServiceManager::RegisterTimerService().
         : id(id)
     {
         TimerServiceManager::Instance().RegisterTimerService(*this);
     }
TimerService() [2/2]
infra::TimerService::TimerService (const TimerService & other) protected delete
~TimerService()
infra::TimerService::~TimerService () protected
Definition at line 12 of file TimerService.cpp.
References infra::InterfaceConnector< TimerServiceManager >::Instance(), and infra::TimerServiceManager::UnregisterTimerService().
     {
         TimerServiceManager::Instance().UnregisterTimerService(*this);
     }
Member Function Documentation
ComputeNextTrigger()
void infra::TimerService::ComputeNextTrigger () private
Definition at line 80 of file TimerService.cpp.
References holdUpdate, nextTrigger, NextTriggerChanged(), scheduledTimers, and updateNeeded.
Referenced by Progressed(), UnregisterTimer(), and UpdateTriggerTime().
     {
         if (!holdUpdate)
         {
             updateNeeded = false;
             TimePoint oldTrigger = nextTrigger;
             nextTrigger = TimePoint::max();
             for (auto& timer : scheduledTimers)
                 nextTrigger = std::min(nextTrigger, timer.NextTrigger());
             if (nextTrigger != oldTrigger)
                 NextTriggerChanged();
         }
         else
             updateNeeded = true;
     }
Id()
uint32_t infra::TimerService::Id () const
Definition at line 17 of file TimerService.cpp.
References id.
     {
         return id;
     }
NextTrigger()
TimePoint infra::TimerService::NextTrigger () const
Definition at line 72 of file TimerService.cpp.
References nextTrigger.
Referenced by infra::DerivedTimerService::NextTriggerChanged(), infra::ScalableDerivedTimerService::NextTriggerChanged(), infra::TickOnInterruptTimerService::NextTriggerChanged(), hal::TimerServiceBsd::NextTriggerChanged(), and hal::TimerServiceWin::NextTriggerChanged().
     {
         return nextTrigger;
     }
NextTriggerChanged()
void infra::TimerService::NextTriggerChanged () virtual
Reimplemented in hal::TimerServiceBsd, hal::TimerServiceWin, infra::DerivedTimerService, infra::ScalableDerivedTimerService, and infra::TickOnInterruptTimerService.
Definition at line 77 of file TimerService.cpp.
Referenced by ComputeNextTrigger(), and RegisterTimer().
     {}
Now()
virtual TimePoint infra::TimerService::Now () const pure virtual
Implemented in hal::TimerServiceBsd, hal::TimerServiceWin, infra::DerivedTimerService, infra::ScalableDerivedTimerService, and infra::TickOnInterruptTimerService.
Referenced by services::TracerWithDateTime::InsertHeader(), services::TracerWithTime::InsertHeader(), infra::Now(), infra::ScalableDerivedTimerService::Now(), infra::DerivedTimerService::Now(), and infra::Timer::Now().
operator=()
TimerService& infra::TimerService::operator= (const TimerService & other) protected delete
Progressed()
void infra::TimerService::Progressed (TimePoint time)
Definition at line 50 of file TimerService.cpp.
References ComputeNextTrigger(), holdUpdate, scheduledTimers, timerIterator, and updateNeeded.
Referenced by infra::DerivedTimerService::NextTriggerChanged(), infra::ScalableDerivedTimerService::NextTriggerChanged(), infra::TickOnInterruptTimerService::TimeProgressed(), hal::TimerServiceBsd::WaitForTrigger(), and hal::TimerServiceWin::WaitForTrigger().
     {
         holdUpdate = true;
         for (timerIterator = scheduledTimers.begin(); timerIterator != scheduledTimers.end(); )
         {
             infra::IntrusiveForwardList<Timer>::iterator currentIterator = timerIterator;
             ++timerIterator;
             if (currentIterator->NextTrigger() <= time)
             {
                 infra::Function<void()> action = currentIterator->Action();
                 currentIterator->ComputeNextTriggerTime();
                 action();
             }
         }
         holdUpdate = false;
         if (updateNeeded)
             ComputeNextTrigger();
     }
RegisterTimer()
void infra::TimerService::RegisterTimer (Timer & timer)
Definition at line 22 of file TimerService.cpp.
References nextTrigger, infra::Timer::NextTrigger(), NextTriggerChanged(), and scheduledTimers.
Referenced by infra::Timer::RegisterSelf().
     {
         scheduledTimers.push_front(timer);
         if (timer.NextTrigger() < nextTrigger)
         {
             nextTrigger = timer.NextTrigger();
             NextTriggerChanged();
         }
     }
Resolution()
virtual Duration infra::TimerService::Resolution () const pure virtual
Implemented in hal::TimerServiceBsd, hal::TimerServiceWin, infra::DerivedTimerService, infra::ScalableDerivedTimerService, and infra::TickOnInterruptTimerService.
Referenced by infra::DerivedTimerService::Resolution(), infra::ScalableDerivedTimerService::Resolution(), and infra::Timer::Resolution().
UnregisterTimer()
void infra::TimerService::UnregisterTimer (Timer & timer, TimePoint oldTriggerTime)
Definition at line 33 of file TimerService.cpp.
References ComputeNextTrigger(), nextTrigger, scheduledTimers, and timerIterator.
Referenced by infra::Timer::UnregisterSelf().
     {
         if (&*timerIterator == &timer)
             ++timerIterator;
         scheduledTimers.erase_slow(timer);
         if (oldTriggerTime == nextTrigger)
             ComputeNextTrigger();
     }
UpdateTriggerTime()
void infra::TimerService::UpdateTriggerTime (Timer & timer, TimePoint oldTriggerTime)
Definition at line 44 of file TimerService.cpp.
References ComputeNextTrigger(), and nextTrigger.
Referenced by infra::Timer::UpdateTriggerTime().
     {
         if (nextTrigger == oldTriggerTime)
             ComputeNextTrigger();
     }
Member Data Documentation
holdUpdate
bool infra::TimerService::holdUpdate = false private
Definition at line 41 of file TimerService.hpp.
Referenced by ComputeNextTrigger(), and Progressed().
id
uint32_t infra::TimerService::id private
Definition at line 36 of file TimerService.hpp.
Referenced by Id().
nextTrigger
TimePoint infra::TimerService::nextTrigger = TimePoint::max() private
Definition at line 40 of file TimerService.hpp.
Referenced by ComputeNextTrigger(), NextTrigger(), infra::TickOnInterruptTimerService::NextTriggerChanged(), RegisterTimer(), UnregisterTimer(), and UpdateTriggerTime().
scheduledTimers
infra::IntrusiveForwardList<Timer> infra::TimerService::scheduledTimers private
Definition at line 37 of file TimerService.hpp.
Referenced by ComputeNextTrigger(), Progressed(), RegisterTimer(), and UnregisterTimer().
timerIterator
infra::IntrusiveForwardList<Timer>::iterator infra::TimerService::timerIterator private
Definition at line 38 of file TimerService.hpp.
Referenced by Progressed(), and UnregisterTimer().
updateNeeded
bool infra::TimerService::updateNeeded = false private
Definition at line 42 of file TimerService.hpp.
Referenced by ComputeNextTrigger(), and Progressed().
The documentation for this class was generated from the following files:
TimerService.hpp
TimerService.cpp