EMil: services::ConnectionBsd Class Reference
services::ConnectionBsd Class Reference
#include <ConnectionBsd.hpp>
Classes
class StreamReaderBsd
class StreamWriterBsd
Public Member Functions
ConnectionBsd (EventDispatcherWithNetwork &network, int socket)
~ConnectionBsd ()
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
IPv4Address Ipv4Address () const
void SetObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
void Receive ()
void Send ()
void TrySend ()
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionBsd >
SharedPtr< ConnectionBsd > SharedFromThis ()
SharedPtr< const ConnectionBsd > SharedFromThis () const
WeakPtr< ConnectionBsd > WeakFromThis ()
WeakPtr< const ConnectionBsd > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionBsd > sharedPtr)
Private Member Functions
void TryAllocateSendStream ()
Private Attributes
EventDispatcherWithNetwork & network
int socket
infra::BoundedDeque< uint8_t >::WithMaxSize< 2048 > receiveBuffer
infra::BoundedDeque< uint8_t >::WithMaxSize< 2048 > sendBuffer
infra::SharedOptional< StreamWriterBsd > streamWriter
std::size_t requestedSendSize = 0
infra::SharedOptional< StreamReaderBsd > streamReader
bool trySend = false
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectionBsd >
using EnableSharedFromThisType = ConnectionBsd
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionBsd >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 17 of file ConnectionBsd.hpp.
Constructor & Destructor Documentation
ConnectionBsd()
services::ConnectionBsd::ConnectionBsd (EventDispatcherWithNetwork & network, int socket)
Definition at line 19 of file ConnectionBsd.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), Receive(), and infra::EventDispatcherWorker::Schedule().
         : network(network)
         , socket(socket)
     {
         infra::EventDispatcher::Instance().Schedule([this]() { Receive(); });
     }
~ConnectionBsd()
services::ConnectionBsd::~ConnectionBsd ()
Definition at line 26 of file ConnectionBsd.cpp.
References socket.
     {
         if (socket != 0)
         {
             int result = close(socket);
             if (result == -1)
                 std::abort();
         }
     }
Member Function Documentation
AbortAndDestroy()
void services::ConnectionBsd::AbortAndDestroy () override virtual
Implements services::Connection.
Definition at line 64 of file ConnectionBsd.cpp.
References services::Connection::ResetOwnership(), and socket.
Referenced by CloseAndDestroy().
     {
         int result = close(socket);
         assert(result != -1);
         socket = 0;
         ResetOwnership();
     }
AckReceived()
void services::ConnectionBsd::AckReceived () override virtual
Implements services::Connection.
Definition at line 54 of file ConnectionBsd.cpp.
References streamReader.
     {
         streamReader->ConsumeRead();
     }
CloseAndDestroy()
void services::ConnectionBsd::CloseAndDestroy () override virtual
Implements services::Connection.
Definition at line 59 of file ConnectionBsd.cpp.
References AbortAndDestroy().
     {
         AbortAndDestroy();
     }
Ipv4Address()
IPv4Address services::ConnectionBsd::Ipv4Address () const
Definition at line 72 of file ConnectionBsd.cpp.
References socket.
     {
         sockaddr_in address{};
         socklen_t addressLength = sizeof(address);
         getpeername(socket, reinterpret_cast<sockaddr*>(&address), &addressLength);
         return IPv4Address{
             static_cast<uint8_t>(address.sin_addr.s_addr >> 24),
             static_cast<uint8_t>(address.sin_addr.s_addr >> 16),
             static_cast<uint8_t>(address.sin_addr.s_addr >> 8),
             static_cast<uint8_t>(address.sin_addr.s_addr)
         };
     }
MaxSendStreamSize()
std::size_t services::ConnectionBsd::MaxSendStreamSize () const override virtual
Implements services::Connection.
Definition at line 44 of file ConnectionBsd.cpp.
References infra::BoundedDeque< T >::max_size(), and sendBuffer.
Referenced by RequestSendStream().
     {
         return sendBuffer.max_size();
     }
Receive()
void services::ConnectionBsd::Receive ()
Definition at line 94 of file ConnectionBsd.cpp.
References infra::BoundedDeque< T >::end(), infra::BoundedDeque< T >::full(), infra::BoundedDeque< T >::insert(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::BoundedDeque< T >::max_size(), receiveBuffer, services::Connection::ResetOwnership(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), infra::EnableSharedFromThis< ConnectionBsd >::SharedFromThis(), infra::BoundedDeque< T >::size(), and socket.
Referenced by ConnectionBsd().
     {
         while (!receiveBuffer.full())
         {
             std::array<uint8_t, 2048> buffer;
             int received = recv(socket, reinterpret_cast<char*>(buffer.data()), receiveBuffer.max_size() - receiveBuffer.size(), 0);
             if (received == -1)
             {
                 if (errno != EWOULDBLOCK)
                     ResetOwnership();
                 return;
             }
             else if (received != 0)
             {
                 receiveBuffer.insert(receiveBuffer.end(), buffer.data(), buffer.data() + received);
                 infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionBsd>& object)
                 {
                     object->GetObserver().DataReceived();
                 }, SharedFromThis());
             }
             else
             {
                 ResetOwnership();
                 return;
             }
         }
     }
ReceiveStream()
infra::SharedPtr< infra::StreamReaderWithRewinding > services::ConnectionBsd::ReceiveStream () override virtual
Implements services::Connection.
Definition at line 49 of file ConnectionBsd.cpp.
References streamReader.
     {
         return streamReader.Emplace(*this);
     }
RequestSendStream()
void services::ConnectionBsd::RequestSendStream (std::size_t sendSize) override virtual
Implements services::Connection.
Definition at line 36 of file ConnectionBsd.cpp.
References MaxSendStreamSize(), requestedSendSize, and TryAllocateSendStream().
     {
         assert(requestedSendSize == 0);
         assert(sendSize != 0 && sendSize <= MaxSendStreamSize());
         requestedSendSize = sendSize;
         TryAllocateSendStream();
     }
Send()
void services::ConnectionBsd::Send ()
Definition at line 123 of file ConnectionBsd.cpp.
References infra::detail::begin(), infra::BoundedDeque< T >::begin(), infra::BoundedDeque< T >::contiguous_range(), infra::BoundedDeque< T >::empty(), infra::BoundedDeque< T >::erase(), requestedSendSize, services::Connection::ResetOwnership(), sendBuffer, socket, and TryAllocateSendStream().
Referenced by TrySend().
     {
         int sent = 0;
         do
         {
             sent = send(socket, reinterpret_cast<char*>(sendBuffer.contiguous_range(sendBuffer.begin()).begin())
                 , sendBuffer.contiguous_range(sendBuffer.begin()).size(), 0);
             if (sent == -1)
             {
                 if (errno != EWOULDBLOCK)
                     ResetOwnership();
                 return;
             }
             sendBuffer.erase(sendBuffer.begin(), sendBuffer.begin() + sent);
         } while (sent != 0 && !sendBuffer.empty());
         if (requestedSendSize != 0)
             TryAllocateSendStream();
     }
SetObserver()
void services::ConnectionBsd::SetObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
Definition at line 86 of file ConnectionBsd.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), services::ConnectionObserver::Connected(), network, services::EventDispatcherWithNetwork::RegisterConnection(), services::Connection::SetOwnership(), and infra::EnableSharedFromThis< ConnectionBsd >::SharedFromThis().
     {
         connectionObserver->Attach(*this);
         SetOwnership(SharedFromThis(), connectionObserver);
         network.RegisterConnection(SharedFromThis());
         connectionObserver->Connected();
     }
TryAllocateSendStream()
void services::ConnectionBsd::TryAllocateSendStream () private
Definition at line 155 of file ConnectionBsd.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::BoundedDeque< T >::max_size(), requestedSendSize, infra::EventDispatcherWithWeakPtrWorker::Schedule(), sendBuffer, infra::EnableSharedFromThis< ConnectionBsd >::SharedFromThis(), infra::BoundedDeque< T >::size(), and streamWriter.
Referenced by RequestSendStream(), and Send().
     {
         assert(streamWriter.Allocatable());
         if (sendBuffer.max_size() - sendBuffer.size() >= requestedSendSize)
         {
             auto size = requestedSendSize;
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([size](const infra::SharedPtr<ConnectionBsd>& object)
             {
                 infra::SharedPtr<infra::StreamWriter> writer = object->streamWriter.Emplace(*object, size);
                 object->GetObserver().SendStreamAvailable(std::move(writer));
             }, SharedFromThis());
             requestedSendSize = 0;
         }
     }
TrySend()
void services::ConnectionBsd::TrySend ()
Definition at line 146 of file ConnectionBsd.cpp.
References Send(), and trySend.
     {
         if (trySend)
         {
             trySend = false;
             Send();
         }
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 68 of file ConnectionBsd.hpp.
Member Data Documentation
network
EventDispatcherWithNetwork& services::ConnectionBsd::network private
Definition at line 70 of file ConnectionBsd.hpp.
Referenced by SetObserver().
receiveBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<2048> services::ConnectionBsd::receiveBuffer private
Definition at line 73 of file ConnectionBsd.hpp.
Referenced by Receive().
requestedSendSize
std::size_t services::ConnectionBsd::requestedSendSize = 0 private
Definition at line 77 of file ConnectionBsd.hpp.
Referenced by RequestSendStream(), Send(), and TryAllocateSendStream().
sendBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<2048> services::ConnectionBsd::sendBuffer private
Definition at line 74 of file ConnectionBsd.hpp.
Referenced by MaxSendStreamSize(), Send(), and TryAllocateSendStream().
socket
int services::ConnectionBsd::socket private
Definition at line 71 of file ConnectionBsd.hpp.
Referenced by AbortAndDestroy(), Ipv4Address(), Receive(), Send(), and ~ConnectionBsd().
streamReader
infra::SharedOptional<StreamReaderBsd> services::ConnectionBsd::streamReader private
Definition at line 78 of file ConnectionBsd.hpp.
Referenced by AckReceived(), and ReceiveStream().
streamWriter
infra::SharedOptional<StreamWriterBsd> services::ConnectionBsd::streamWriter private
Definition at line 76 of file ConnectionBsd.hpp.
Referenced by TryAllocateSendStream().
trySend
bool services::ConnectionBsd::trySend = false private
Definition at line 79 of file ConnectionBsd.hpp.
Referenced by TrySend().
The documentation for this class was generated from the following files:
ConnectionBsd.hpp
ConnectionBsd.cpp