EMil: services::CyclicStore::Iterator Class Reference
services::CyclicStore::Iterator Class Reference
#include <CyclicStore.hpp>
Public Member Functions
Iterator (const CyclicStore &store)
Iterator (const Iterator &other)
~Iterator ()
Iterator & operator= (const Iterator &other)
void Read (infra::ByteRange buffer, infra::Function< void(infra::ByteRange result)> onDone)
void SectorIsErased (uint32_t sectorIndex)
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Private Member Functions
void ReadSectorStatusIfAtStart ()
Private Attributes
const CyclicStore & store
bool loadStartAddressDelayed
uint32_t address
infra::Sequencer sequencer
infra::ClaimableResource::Claimer::WithSize< SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE > claimer
SectorStatus sectorStatus = SectorStatus::used
bool firstSectorToRead = true
BlockHeader blockHeader
infra::ByteRange readBuffer
bool found = false
bool reachedEnd = false
Additional Inherited Members
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 110 of file CyclicStore.hpp.
Constructor & Destructor Documentation
Iterator() [1/2]
services::CyclicStore::Iterator::Iterator (const CyclicStore & store) explicit
Definition at line 347 of file CyclicStore.cpp.
References services::CyclicStore::iterators, and store.
         : store(store)
         , loadStartAddressDelayed(true)
         , address(0)
         , claimer(store.resource)
     {
         store.iterators.push_front(*this);
     }
Iterator() [2/2]
services::CyclicStore::Iterator::Iterator (const Iterator & other)
Definition at line 356 of file CyclicStore.cpp.
References services::CyclicStore::iterators, and store.
         : store(other.store)
         , loadStartAddressDelayed(other.loadStartAddressDelayed)
         , address(other.address)
         , claimer(store.resource)
     {
         store.iterators.push_front(*this);
     }
~Iterator()
services::CyclicStore::Iterator::~Iterator ()
Definition at line 365 of file CyclicStore.cpp.
     {
         store.iterators.erase_slow(*this);
     }
Member Function Documentation
operator=()
CyclicStore::Iterator & services::CyclicStore::Iterator::operator= (const Iterator & other)
Definition at line 370 of file CyclicStore.cpp.
References address, services::CyclicStore::blockHeader, blockHeader, firstSectorToRead, found, loadStartAddressDelayed, readBuffer, services::CyclicStore::sectorStatus, sectorStatus, and store.
     {
         assert(&store == &other.store);
         loadStartAddressDelayed = other.loadStartAddressDelayed;
         address = other.address;
         sectorStatus = other.sectorStatus;
         firstSectorToRead = other.firstSectorToRead;
         blockHeader = other.blockHeader;
         readBuffer = other.readBuffer;
         found = other.found;
         return *this;
     }
Read()
void services::CyclicStore::Iterator::Read (infra::ByteRange buffer, infra::Function< void(infra::ByteRange result)> onDone)
Definition at line 386 of file CyclicStore.cpp.
References services::CyclicStore::blockHeader, services::CyclicStore::BlockHeader::BlockLength(), infra::Sequencer::Continue(), services::CyclicStore::dataReady, infra::Sequencer::Else(), infra::Sequencer::ElseIf(), services::CyclicStore::empty, services::CyclicStore::emptyUntilEnd, infra::Sequencer::EndIf(), infra::Sequencer::EndWhile(), infra::Sequencer::Execute(), infra::Sequencer::Finished(), infra::Sequencer::If(), infra::Sequencer::Load(), infra::MakeByteRange(), services::CyclicStore::sectorStatus, services::CyclicStore::sequencer, services::CyclicStore::BlockHeader::status, infra::Sequencer::Step(), services::CyclicStore::used, infra::Sequencer::While(), services::CyclicStore::writingData, and services::CyclicStore::writingLength.
     {
         readBuffer = buffer;
         found = false;
         reachedEnd = false;
         claimer.Claim([this, onDone]()
         {
             if (loadStartAddressDelayed)
             {
                 loadStartAddressDelayed = false;
                 address = store.startAddress;
             }
             assert(sequencer.Finished());
             sequencer.Load([this, onDone]()
             {
                 ReadSectorStatusIfAtStart();
                 sequencer.While([this]() { return sectorStatus == SectorStatus::used && !found && !reachedEnd; });
                     sequencer.Step([this]()
                     {
                         store.flash.ReadBuffer(infra::MakeByteRange(blockHeader), address, [this]() { sequencer.Continue(); });
                         if (store.flash.SectorOfAddress(address + sizeof(blockHeader)) == store.flash.SectorOfAddress(address))
                             address += sizeof(blockHeader);
                         else
{
                             address = store.flash.StartOfNextSectorCyclical(address);
                         }
                     });
                     sequencer.If([this]() { return blockHeader.status == BlockStatus::dataReady; });
                         sequencer.If([this]() { return store.flash.AddressOffsetInSector(address) + blockHeader.BlockLength() <= store.flash.SizeOfSector(store.flash.SectorOfAddress(address)); });
                             sequencer.Step([this]()
{
                                 readBuffer.shrink_from_back_to(blockHeader.BlockLength());
                                 store.flash.ReadBuffer(readBuffer, address, [this]() { sequencer.Continue(); });
                                 address += blockHeader.BlockLength();
                                 if (address == store.flash.TotalSize())
                                     address = 0;
                                 found = true;
                             });
                         sequencer.Else();
                             sequencer.Execute([this]()
{
                                 address = store.flash.StartOfNextSectorCyclical(address);
                             });
                         sequencer.EndIf();
                     sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::emptyUntilEnd; });
                         sequencer.Execute([this]()
{
                             if (!store.flash.AtStartOfSector(address))
{
                                 address = store.flash.StartOfNextSectorCyclical(address);
                             }
                         });
                     sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::empty; });
                         sequencer.Execute([this]()
{
                             reachedEnd = true;
                             address -= sizeof(blockHeader);
                         });
                     sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::writingLength; });
                         // Do nothing
                     sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::writingData; });
                         sequencer.Execute([this]()
{
                             address += blockHeader.BlockLength();
                         });
                     sequencer.Else();
                         sequencer.Execute([this]()
{
                             address = store.flash.StartOfNextSectorCyclical(address);
                         });
                     sequencer.EndIf();
                     ReadSectorStatusIfAtStart();
                 sequencer.EndWhile();
                 sequencer.Execute([this, onDone]()
                 {
                     if (!found)
                         readBuffer.clear();
                     onDone(readBuffer);
                     claimer.Release();
                 });
             });
         });
     }
ReadSectorStatusIfAtStart()
void services::CyclicStore::Iterator::ReadSectorStatusIfAtStart () private
Definition at line 481 of file CyclicStore.cpp.
References infra::Sequencer::Continue(), services::CyclicStore::empty, infra::Sequencer::EndIf(), infra::Sequencer::Execute(), services::CyclicStore::firstInCycle, infra::Sequencer::If(), infra::MakeByteRange(), services::CyclicStore::sectorStatus, services::CyclicStore::sequencer, infra::Sequencer::Step(), and services::CyclicStore::used.
     {
         sequencer.If([this]() { return store.flash.AtStartOfSector(address); });
             sequencer.Step([this]()
             {
                 store.flash.ReadBuffer(infra::MakeByteRange(sectorStatus), address, [this]() { sequencer.Continue(); });
             });
             sequencer.Execute([this]()
             {
                 if (sectorStatus != SectorStatus::empty)
                     address += sizeof(sectorStatus);
                 if (sectorStatus == SectorStatus::firstInCycle)
                 {
                     if (firstSectorToRead)
                         sectorStatus = SectorStatus::used;
                     else
                         sectorStatus = SectorStatus::empty;
                 }
                 firstSectorToRead = false;
             });
         sequencer.EndIf();
     }
SectorIsErased()
void services::CyclicStore::Iterator::SectorIsErased (uint32_t sectorIndex)
Definition at line 472 of file CyclicStore.cpp.
References services::CyclicStore::sectorIndex.
     {
         if (store.flash.SectorOfAddress(address) == sectorIndex)
         {
             address = store.flash.StartOfNextSectorCyclical(address);
             firstSectorToRead = true;
         }
     }
Member Data Documentation
address
uint32_t services::CyclicStore::Iterator::address private
Definition at line 129 of file CyclicStore.hpp.
Referenced by operator=().
blockHeader
BlockHeader services::CyclicStore::Iterator::blockHeader private
Definition at line 135 of file CyclicStore.hpp.
Referenced by operator=().
claimer
infra::ClaimableResource::Claimer::WithSize<SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE> services::CyclicStore::Iterator::claimer private
Definition at line 131 of file CyclicStore.hpp.
firstSectorToRead
bool services::CyclicStore::Iterator::firstSectorToRead = true private
Definition at line 134 of file CyclicStore.hpp.
Referenced by operator=().
found
bool services::CyclicStore::Iterator::found = false private
Definition at line 138 of file CyclicStore.hpp.
Referenced by operator=().
loadStartAddressDelayed
bool services::CyclicStore::Iterator::loadStartAddressDelayed private
Definition at line 128 of file CyclicStore.hpp.
Referenced by operator=().
reachedEnd
bool services::CyclicStore::Iterator::reachedEnd = false private
Definition at line 139 of file CyclicStore.hpp.
readBuffer
infra::ByteRange services::CyclicStore::Iterator::readBuffer private
Definition at line 136 of file CyclicStore.hpp.
Referenced by operator=().
sectorStatus
SectorStatus services::CyclicStore::Iterator::sectorStatus = SectorStatus::used private
Definition at line 133 of file CyclicStore.hpp.
Referenced by operator=().
sequencer
infra::Sequencer services::CyclicStore::Iterator::sequencer private
Definition at line 130 of file CyclicStore.hpp.
store
const CyclicStore& services::CyclicStore::Iterator::store private
Definition at line 127 of file CyclicStore.hpp.
Referenced by Iterator(), and operator=().
The documentation for this class was generated from the following files:
CyclicStore.hpp
CyclicStore.cpp