EMil: services::FlashQuadSpiCypressFll Class Reference
services::FlashQuadSpiCypressFll Class Reference
#include <FlashQuadSpiCypressFll.hpp>
Public Member Functions
FlashQuadSpiCypressFll (hal::QuadSpi &spi, infra::Function< void()> onInitialized, uint32_t numberOfSectors=4096)
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
void SwitchToSingleSpeed (infra::Function< void()> onDone)
Public Member Functions inherited from services::FlashQuadSpi
FlashQuadSpi (hal::QuadSpi &spi, uint32_t numberOfSectors, uint8_t commandPageProgram)
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::FlashHomogeneous
FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Static Public Attributes
static const uint8_t commandPageProgram = 0x02
static const uint8_t commandReadData = 0xeb
static const uint8_t commandReadStatusRegister = 0x05
static const uint8_t commandWriteEnable = 0x06
static const uint8_t commandEraseSector = 0x20
static const uint8_t commandEraseHalfBlock = 0x52
static const uint8_t commandEraseBlock = 0xd8
static const uint8_t commandEraseChip = 0x60
static const uint8_t commandEnterQpi = 0x38
static const uint8_t commandExitQpi = 0xf5
static const uint32_t sizeHalfBlock = 32768
static const uint8_t statusFlagWriteInProgress = 1
Static Public Attributes inherited from services::FlashQuadSpi
static const uint32_t sizeBlock = 65536
static const uint32_t sizeSector = 4096
static const uint32_t sizePage = 256
Private Member Functions
void SwitchToQuadSpeed ()
virtual void WriteEnable () override
virtual void EraseSomeSectors (uint32_t endIndex) override
void SendEraseSector (uint32_t sectorIndex)
void SendEraseHalfBlock (uint32_t sectorIndex)
void SendEraseBlock (uint32_t sectorIndex)
void SendEraseChip ()
virtual void HoldWhileWriteInProgress () override
Private Attributes
infra::TimerSingleShot initDelayTimer
infra::Function< void()> onInitialized
Additional Inherited Members
Protected Member Functions inherited from services::FlashQuadSpi
void WriteBufferSequence ()
virtual void PageProgram ()
infra::BoundedVector< uint8_t >::WithMaxSize< 4 > ConvertAddress (uint32_t address) const
Protected Member Functions inherited from hal::FlashHomogeneous
~FlashHomogeneous ()=default
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Protected Attributes inherited from services::FlashQuadSpi
hal::QuadSpi & spi
infra::Sequencer sequencer
infra::AutoResetFunction< void()> onDone
infra::ConstByteRange buffer
uint32_t address = 0
uint32_t sectorIndex = 0
uint8_t commandPageProgram
Detailed Description
Definition at line 8 of file FlashQuadSpiCypressFll.hpp.
Constructor & Destructor Documentation
FlashQuadSpiCypressFll()
services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll (hal::QuadSpi & spi, infra::Function< void()> onInitialized, uint32_t numberOfSectors = 4096)
Definition at line 17 of file FlashQuadSpiCypressFll.cpp.
References infra::Sequencer::Continue(), initDelayTimer, infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::Sequencer::Load(), onInitialized, infra::EventDispatcherWorker::Schedule(), services::FlashQuadSpi::sequencer, infra::TimerSingleShot::Start(), infra::Sequencer::Step(), and SwitchToQuadSpeed().
         : FlashQuadSpi(spi, numberOfSectors, commandPageProgram)
         , onInitialized(onInitialized)
     {
         sequencer.Load([this]()
         {
             sequencer.Step([this]() { initDelayTimer.Start(std::chrono::milliseconds(100), [this]() { sequencer.Continue(); }); });
             sequencer.Step([this]() { SwitchToQuadSpeed(); });
             sequencer.Step([this]() { infra::EventDispatcher::Instance().Schedule([this]() { this->onInitialized(); }); });
         });
     }
Member Function Documentation
EraseSomeSectors()
void services::FlashQuadSpiCypressFll::EraseSomeSectors (uint32_t endIndex) override private virtual
Implements services::FlashQuadSpi.
Definition at line 54 of file FlashQuadSpiCypressFll.cpp.
References hal::FlashHomogeneous::NumberOfSectors(), services::FlashQuadSpi::sectorIndex, SendEraseBlock(), SendEraseChip(), SendEraseHalfBlock(), SendEraseSector(), services::FlashQuadSpi::sizeBlock, sizeHalfBlock, and services::FlashQuadSpi::sizeSector.
     {
         if (sectorIndex == 0 && endIndex == NumberOfSectors())
         {
             SendEraseChip();
             sectorIndex += NumberOfSectors();
         }
         else if (sectorIndex % (sizeBlock / sizeSector) == 0 && sectorIndex + sizeBlock / sizeSector <= endIndex)
         {
             SendEraseBlock(sectorIndex);
             sectorIndex += sizeBlock / sizeSector;
         }
         else if (sectorIndex % (sizeHalfBlock / sizeSector) == 0 && sectorIndex + sizeHalfBlock / sizeSector <= endIndex)
         {
             SendEraseHalfBlock(sectorIndex);
             sectorIndex += sizeHalfBlock / sizeSector;
         }
         else
         {
             SendEraseSector(sectorIndex);
             ++sectorIndex;
         }
     }
HoldWhileWriteInProgress()
void services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress () override private virtual
Implements services::FlashQuadSpi.
Definition at line 102 of file FlashQuadSpiCypressFll.cpp.
References commandReadStatusRegister, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::PollStatus(), hal::QuadSpi::Lines::QuadSpeed(), services::FlashQuadSpi::sequencer, services::FlashQuadSpi::spi, and statusFlagWriteInProgress.
     {
         static const hal::QuadSpi::Header pollWriteInProgressHeader{ infra::MakeOptional(commandReadStatusRegister), {}, {}, 0 };
         spi.PollStatus(pollWriteInProgressHeader, 1, 0, statusFlagWriteInProgress, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
ReadBuffer()
void services::FlashQuadSpiCypressFll::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 29 of file FlashQuadSpiCypressFll.cpp.
References services::FlashQuadSpi::address, hal::QuadSpi::AddressToVector(), services::FlashQuadSpi::buffer, commandReadData, infra::MakeOptional(), services::FlashQuadSpi::onDone, hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::ReceiveData(), and services::FlashQuadSpi::spi.
     {
         const hal::QuadSpi::Header header{ infra::MakeOptional(commandReadData), hal::QuadSpi::AddressToVector(address << 8, 4), {}, 8 };
         spi.ReceiveData(header, buffer, hal::QuadSpi::Lines::QuadSpeed(), onDone);
     }
SendEraseBlock()
void services::FlashQuadSpiCypressFll::SendEraseBlock (uint32_t sectorIndex) private
Definition at line 90 of file FlashQuadSpiCypressFll.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseBlock, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), services::FlashQuadSpi::sectorIndex, hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseBlockHeader{ infra::MakeOptional(commandEraseBlock), ConvertAddress(AddressOfSector(sectorIndex)), {}, 0 };
         spi.SendData(eraseBlockHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseChip()
void services::FlashQuadSpiCypressFll::SendEraseChip () private
Definition at line 96 of file FlashQuadSpiCypressFll.cpp.
References commandEraseChip, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         static const hal::QuadSpi::Header eraseChipHeader{ infra::MakeOptional(commandEraseChip), {}, {}, 0 };
         spi.SendData(eraseChipHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseHalfBlock()
void services::FlashQuadSpiCypressFll::SendEraseHalfBlock (uint32_t sectorIndex) private
Definition at line 84 of file FlashQuadSpiCypressFll.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseHalfBlock, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), services::FlashQuadSpi::sectorIndex, hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseHalfBlockHeader{ infra::MakeOptional(commandEraseHalfBlock), ConvertAddress(AddressOfSector(sectorIndex)), {}, 0 };
         spi.SendData(eraseHalfBlockHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseSector()
void services::FlashQuadSpiCypressFll::SendEraseSector (uint32_t sectorIndex) private
Definition at line 78 of file FlashQuadSpiCypressFll.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseSector, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), services::FlashQuadSpi::sectorIndex, hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseSectorHeader{ infra::MakeOptional(commandEraseSector), ConvertAddress(AddressOfSector(sectorIndex)), {}, 0 };
         spi.SendData(eraseSectorHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SwitchToQuadSpeed()
void services::FlashQuadSpiCypressFll::SwitchToQuadSpeed () private
Definition at line 42 of file FlashQuadSpiCypressFll.cpp.
References commandEnterQpi, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
Referenced by FlashQuadSpiCypressFll().
     {
         static const hal::QuadSpi::Header enterQpiHeader{ infra::MakeOptional(commandEnterQpi), {}, {}, 0 };
         spi.SendData(enterQpiHeader, {}, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
SwitchToSingleSpeed()
void services::FlashQuadSpiCypressFll::SwitchToSingleSpeed (infra::Function< void()> onDone)
Definition at line 36 of file FlashQuadSpiCypressFll.cpp.
References commandExitQpi, infra::MakeOptional(), services::FlashQuadSpi::onDone, hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), and services::FlashQuadSpi::spi.
     {
         static const hal::QuadSpi::Header exitQpiHeader{ infra::MakeOptional(commandExitQpi), {}, {}, 0 };
         spi.SendData(exitQpiHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), onDone);
     }
WriteEnable()
void services::FlashQuadSpiCypressFll::WriteEnable () override private virtual
Implements services::FlashQuadSpi.
Definition at line 48 of file FlashQuadSpiCypressFll.cpp.
References commandWriteEnable, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
     {
         static const hal::QuadSpi::Header writeEnableHeader{ infra::MakeOptional(commandWriteEnable), {}, {}, 0 };
         spi.SendData(writeEnableHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
Member Data Documentation
commandEnterQpi
const uint8_t services::FlashQuadSpiCypressFll::commandEnterQpi = 0x38 static
Definition at line 20 of file FlashQuadSpiCypressFll.hpp.
Referenced by SwitchToQuadSpeed().
commandEraseBlock
const uint8_t services::FlashQuadSpiCypressFll::commandEraseBlock = 0xd8 static
Definition at line 18 of file FlashQuadSpiCypressFll.hpp.
Referenced by SendEraseBlock().
commandEraseChip
const uint8_t services::FlashQuadSpiCypressFll::commandEraseChip = 0x60 static
Definition at line 19 of file FlashQuadSpiCypressFll.hpp.
Referenced by SendEraseChip().
commandEraseHalfBlock
const uint8_t services::FlashQuadSpiCypressFll::commandEraseHalfBlock = 0x52 static
Definition at line 17 of file FlashQuadSpiCypressFll.hpp.
Referenced by SendEraseHalfBlock().
commandEraseSector
const uint8_t services::FlashQuadSpiCypressFll::commandEraseSector = 0x20 static
Definition at line 16 of file FlashQuadSpiCypressFll.hpp.
Referenced by SendEraseSector().
commandExitQpi
const uint8_t services::FlashQuadSpiCypressFll::commandExitQpi = 0xf5 static
Definition at line 21 of file FlashQuadSpiCypressFll.hpp.
Referenced by SwitchToSingleSpeed().
commandPageProgram
const uint8_t services::FlashQuadSpiCypressFll::commandPageProgram = 0x02 static
Definition at line 12 of file FlashQuadSpiCypressFll.hpp.
commandReadData
const uint8_t services::FlashQuadSpiCypressFll::commandReadData = 0xeb static
Definition at line 13 of file FlashQuadSpiCypressFll.hpp.
Referenced by ReadBuffer().
commandReadStatusRegister
const uint8_t services::FlashQuadSpiCypressFll::commandReadStatusRegister = 0x05 static
Definition at line 14 of file FlashQuadSpiCypressFll.hpp.
Referenced by HoldWhileWriteInProgress().
commandWriteEnable
const uint8_t services::FlashQuadSpiCypressFll::commandWriteEnable = 0x06 static
Definition at line 15 of file FlashQuadSpiCypressFll.hpp.
Referenced by WriteEnable().
initDelayTimer
infra::TimerSingleShot services::FlashQuadSpiCypressFll::initDelayTimer private
Definition at line 45 of file FlashQuadSpiCypressFll.hpp.
Referenced by FlashQuadSpiCypressFll().
onInitialized
infra::Function<void()> services::FlashQuadSpiCypressFll::onInitialized private
Definition at line 46 of file FlashQuadSpiCypressFll.hpp.
Referenced by FlashQuadSpiCypressFll().
sizeHalfBlock
const uint32_t services::FlashQuadSpiCypressFll::sizeHalfBlock = 32768 static
Definition at line 23 of file FlashQuadSpiCypressFll.hpp.
Referenced by EraseSomeSectors().
statusFlagWriteInProgress
const uint8_t services::FlashQuadSpiCypressFll::statusFlagWriteInProgress = 1 static
Definition at line 25 of file FlashQuadSpiCypressFll.hpp.
Referenced by HoldWhileWriteInProgress().
The documentation for this class was generated from the following files:
FlashQuadSpiCypressFll.hpp
FlashQuadSpiCypressFll.cpp