EMil: application::UpgradePackBuilderFacade Class Reference
application::UpgradePackBuilderFacade Class Reference
#include <BuildUpgradePack.hpp>
Public Member Functions
UpgradePackBuilderFacade (const application::UpgradePackBuilder::HeaderInfo &headerInfo)
virtual ~UpgradePackBuilderFacade ()=default
void Build (const std::vector< std::string > &supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> &supportedBinaryTargets, std::string outputFilename, TargetAndFiles &targetAndFiles, BuildOptions &buildOptions, infra::JsonObject &configuration, infra::ConstByteRange aesKey, infra::ConstByteRange ecDsa224PublicKey, infra::ConstByteRange ecDsa224PrivateKey, const std::vector< NoFileInputFactory *> &otherTargets)
int Result () const
Protected Member Functions
virtual void PreBuilder (TargetAndFiles &targetAndFiles, const BuildOptions &buildOptions, infra::JsonObject &configuration)
virtual void PostBuilder (UpgradePackBuilder &builder, ImageSigner &signer, const BuildOptions &buildOptions)
Protected Attributes
UpgradePackBuilder::HeaderInfo headerInfo
Private Member Functions
void TryBuild (const std::vector< std::string > &supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> &supportedBinaryTargets, std::string outputFilename, TargetAndFiles &targetAndFiles, BuildOptions &buildOptions, infra::JsonObject &configuration, infra::ConstByteRange aesKey, infra::ConstByteRange ecDsa224PublicKey, infra::ConstByteRange ecDsa224PrivateKey, const std::vector< NoFileInputFactory *> &otherTargets)
void ShowUsage (int argc, const char *argv[], const std::vector< std::string > &supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> &supportedBinaryTargets, const std::vector< NoFileInputFactory *> &otherTargets) const
void ShowUsage (TargetAndFiles &targetAndFiles, BuildOptions &buildOptions, const std::vector< std::string > &supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> &supportedBinaryTargets, const std::vector< NoFileInputFactory *> &otherTargets) const
Private Attributes
int result = 0
Detailed Description
Definition at line 21 of file BuildUpgradePack.hpp.
Constructor & Destructor Documentation
UpgradePackBuilderFacade()
application::UpgradePackBuilderFacade::UpgradePackBuilderFacade (const application::UpgradePackBuilder::HeaderInfo & headerInfo) explicit
Definition at line 39 of file BuildUpgradePack.cpp.
         : headerInfo(headerInfo)
     {
         // Initialize the MbedTLS memory pool
         unsigned char memory_buf[100000];
         mbedtls_memory_buffer_alloc_init(memory_buf, sizeof(memory_buf));
     }
~UpgradePackBuilderFacade()
virtual application::UpgradePackBuilderFacade::~UpgradePackBuilderFacade () virtual default
Member Function Documentation
Build()
void application::UpgradePackBuilderFacade::Build (const std::vector< std::string > & supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> & supportedBinaryTargets, std::string outputFilename, TargetAndFiles & targetAndFiles, BuildOptions & buildOptions, infra::JsonObject & configuration, infra::ConstByteRange aesKey, infra::ConstByteRange ecDsa224PublicKey, infra::ConstByteRange ecDsa224PrivateKey, const std::vector< NoFileInputFactory *> & otherTargets)
Definition at line 47 of file BuildUpgradePack.cpp.
References infra::endl, application::LineException::file, infra::hex, application::LineException::line, application::OverwriteException::position, result, ShowUsage(), and TryBuild().
Referenced by application::BuildReferenceUpgradePack(), and application::BuildUpgradePack().
     {
         try
         {
             TryBuild(supportedHexTargets, supportedBinaryTargets, outputFilename, targetAndFiles, buildOptions, configuration, aesKey, ecDsa224PublicKey, ecDsa224PrivateKey, otherTargets);
         }
         catch (UsageException&)
         {
             ShowUsage(targetAndFiles, buildOptions, supportedHexTargets, supportedBinaryTargets, otherTargets);
             result = 1;
         }
         catch (application::IncorrectCrcException& exception)
         {
             std::cout << "Incorrect CRC in file " << exception.file << " at line " << exception.line << std::endl;
             result = 1;
         }
         catch (application::NoEndOfFileException& exception)
         {
             std::cout << "No end of file found in file " << exception.file << " at line " << exception.line << std::endl;
             result = 1;
         }
         catch (application::DataAfterEndOfFileException& exception)
         {
             std::cout << "Data found after end of file in file " << exception.file << " at line " << exception.line << std::endl;
             result = 1;
         }
         catch (application::UnknownRecordException& exception)
         {
             std::cout << "Unknown record in file " << exception.file << " at line " << exception.line << std::endl;
             result = 1;
         }
         catch (application::RecordTooShortException& exception)
         {
             std::cout << "Record too short in file " << exception.file << " at line " << exception.line << std::endl;
             result = 1;
         }
         catch (application::RecordTooLongException& exception)
         {
             std::cout << "Record too long in file " << exception.file << " at line " << exception.line << std::endl;
             result = 1;
         }
         catch (application::OverwriteException& exception)
         {
             std::cout << "Contents specified twice for memory location at address 0x" << std::hex << std::setw(8) << std::setfill('0') << exception.position << std::endl;
             result = 1;
         }
         catch (hal::CannotOpenFileException& exception)
         {
             std::cout << exception.what() << std::endl;
             result = 1;
         }
         catch (application::SignatureDoesNotVerifyException&)
         {
             std::cout << "Signature does not verify" << std::endl;
         }
         catch (std::exception& e)
         {
             std::cout << e.what() << std::endl;
             result = 1;
         }
     }
PostBuilder()
void application::UpgradePackBuilderFacade::PostBuilder (UpgradePackBuilder & builder, ImageSigner & signer, const BuildOptions & buildOptions) protected virtual
Definition at line 188 of file BuildUpgradePack.cpp.
Referenced by TryBuild().
     {}
PreBuilder()
void application::UpgradePackBuilderFacade::PreBuilder (TargetAndFiles & targetAndFiles, const BuildOptions & buildOptions, infra::JsonObject & configuration) protected virtual
Definition at line 185 of file BuildUpgradePack.cpp.
Referenced by TryBuild().
     {}
Result()
int application::UpgradePackBuilderFacade::Result () const
Definition at line 180 of file BuildUpgradePack.cpp.
References result.
Referenced by application::BuildReferenceUpgradePack(), and application::BuildUpgradePack().
     {
         return result;
     }
ShowUsage() [1/2]
void application::UpgradePackBuilderFacade::ShowUsage (int argc, const char * argv[], const std::vector< std::string > & supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> & supportedBinaryTargets, const std::vector< NoFileInputFactory *> & otherTargets) const private
Definition at line 133 of file BuildUpgradePack.cpp.
References infra::endl.
Referenced by Build().
     {
         std::cout << "Arguments: ";
         for (int i = 0; i != argc; ++i)
             std::cout << " " << argv[i];
         std::cout << std::endl;
         std::cout << "Invalid number of arguments" << std::endl;
         std::cout << argv[0] << " OutputFile [-Target1 InputFile1] [-Target2 InputFile2] [-Target3 InputFile3] [-Target4 InputFile4] ..." << std::endl;
         std::cout << "Targets: ";
         for (auto target : supportedHexTargets)
             std::cout << target << " ";
         for (auto targetAndAddress : supportedBinaryTargets)
             std::cout << targetAndAddress.first << " ";
         for (auto target : otherTargets)
             std::cout << target->TargetName() << " ";
         std::cout << std::endl;
     }
ShowUsage() [2/2]
void application::UpgradePackBuilderFacade::ShowUsage (TargetAndFiles & targetAndFiles, BuildOptions & buildOptions, const std::vector< std::string > & supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> & supportedBinaryTargets, const std::vector< NoFileInputFactory *> & otherTargets) const private
Definition at line 153 of file BuildUpgradePack.cpp.
References infra::endl.
     {
         std::cout << "Wrong usage" << std::endl;
         std::cout << "Given targets: ";
         for (auto target : targetAndFiles)
             std::cout << " " << target.first;
         std::cout << std::endl;
         std::cout << "Given options: ";
         for (auto option : buildOptions)
             std::cout << " " << option.first;
         std::cout << std::endl;
         std::cout << "Correct Usage" << std::endl;
         std::cout << "Available Targets: ";
         for (auto target : supportedHexTargets)
             std::cout << target << " ";
         for (auto targetAndAddress : supportedBinaryTargets)
             std::cout << targetAndAddress.first << " ";
         for (auto target : otherTargets)
             std::cout << target->TargetName() << " ";
         std::cout << std::endl;
     }
TryBuild()
void application::UpgradePackBuilderFacade::TryBuild (const std::vector< std::string > & supportedHexTargets, const std::vector< std::pair< std::string, uint32_t >> & supportedBinaryTargets, std::string outputFilename, TargetAndFiles & targetAndFiles, BuildOptions & buildOptions, infra::JsonObject & configuration, infra::ConstByteRange aesKey, infra::ConstByteRange ecDsa224PublicKey, infra::ConstByteRange ecDsa224PrivateKey, const std::vector< NoFileInputFactory *> & otherTargets) private
Definition at line 111 of file BuildUpgradePack.cpp.
References application::UpgradePackInputFactory::CreateInput(), headerInfo, PostBuilder(), PreBuilder(), and application::UpgradePackBuilder::WriteUpgradePack().
Referenced by Build().
     {
         application::SecureRandomNumberGenerator randomNumberGenerator;
         hal::FileSystemWin fileSystem;
         application::ImageEncryptorAes imageEncryptorAes(randomNumberGenerator, aesKey);
         application::UpgradePackInputFactory inputFactory(supportedHexTargets, supportedBinaryTargets, fileSystem, imageEncryptorAes, otherTargets);
         application::ImageSignerEcDsa signer(randomNumberGenerator, ecDsa224PublicKey, ecDsa224PrivateKey);
         PreBuilder(targetAndFiles, buildOptions, configuration);
         std::vector<std::unique_ptr<application::Input>> inputs;
         for (auto targetAndFile : targetAndFiles)
             inputs.push_back(inputFactory.CreateInput(targetAndFile.first, targetAndFile.second));
         application::UpgradePackBuilder builder(this->headerInfo, std::move(inputs), signer);
         PostBuilder(builder, signer, buildOptions);
         builder.WriteUpgradePack(outputFilename, fileSystem);
     }
Member Data Documentation
headerInfo
UpgradePackBuilder::HeaderInfo application::UpgradePackBuilderFacade::headerInfo protected
Definition at line 50 of file BuildUpgradePack.hpp.
Referenced by application::ReferenceUpgradePackBuilderFacade::PreBuilder(), and TryBuild().
result
int application::UpgradePackBuilderFacade::result = 0 private
Definition at line 53 of file BuildUpgradePack.hpp.
Referenced by Build(), and Result().
The documentation for this class was generated from the following files:
BuildUpgradePack.hpp
BuildUpgradePack.cpp