EMil: services::ConnectionMbedTls::StreamWriterMbedTls Class Reference
services::ConnectionMbedTls::StreamWriterMbedTls Class Reference
Public Member Functions
StreamWriterMbedTls (ConnectionMbedTls &connection)
~StreamWriterMbedTls ()
Public Member Functions inherited from infra::StreamWriter
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Private Member Functions
virtual void Insert (infra::ConstByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
Private Attributes
ConnectionMbedTls & connection
std::size_t sent = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 84 of file ConnectionMbedTls.hpp.
Constructor & Destructor Documentation
StreamWriterMbedTls()
services::ConnectionMbedTls::StreamWriterMbedTls::StreamWriterMbedTls (ConnectionMbedTls & connection) explicit
Definition at line 338 of file ConnectionMbedTls.cpp.
         : connection(connection)
     {}
~StreamWriterMbedTls()
services::ConnectionMbedTls::StreamWriterMbedTls::~StreamWriterMbedTls ()
Definition at line 342 of file ConnectionMbedTls.cpp.
     {
         if (sent != 0)
             connection.TrySend();
     }
Member Function Documentation
Available()
std::size_t services::ConnectionMbedTls::StreamWriterMbedTls::Available () const override private virtual
Implements infra::StreamWriter.
Definition at line 354 of file ConnectionMbedTls.cpp.
     {
         return connection.sendBuffer.max_size() - sent;
     }
Insert()
void services::ConnectionMbedTls::StreamWriterMbedTls::Insert (infra::ConstByteRange range, infra::StreamErrorPolicy & errorPolicy) override private virtual
Implements infra::StreamWriter.
Definition at line 348 of file ConnectionMbedTls.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         connection.sendBuffer.insert(connection.sendBuffer.end(), range.begin(), range.end());
         sent += range.size();
     }
Member Data Documentation
connection
ConnectionMbedTls& services::ConnectionMbedTls::StreamWriterMbedTls::connection private
Definition at line 96 of file ConnectionMbedTls.hpp.
sent
std::size_t services::ConnectionMbedTls::StreamWriterMbedTls::sent = 0 private
Definition at line 97 of file ConnectionMbedTls.hpp.
The documentation for this class was generated from the following files:
ConnectionMbedTls.hpp
ConnectionMbedTls.cpp