EMil: infra::ScalableDerivedTimerService Class Reference
infra::ScalableDerivedTimerService Class Reference
#include <ScalableDerivedTimerService.hpp>
Public Member Functions
ScalableDerivedTimerService (uint32_t id, TimerService &baseTimerService)
virtual void NextTriggerChanged () override
virtual TimePoint Now () const override
virtual Duration Resolution () const override
void Shift (Duration shift)
void Scale (uint32_t factor)
Duration GetCurrentShift () const
Public Member Functions inherited from infra::TimerService
uint32_t Id () const
void RegisterTimer (Timer &timer)
void UnregisterTimer (Timer &timer, TimePoint oldTriggerTime)
void UpdateTriggerTime (Timer &timer, TimePoint oldTriggerTime)
void Progressed (TimePoint time)
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Private Member Functions
TimePoint ScaleTime (TimePoint time) const
TimePoint UnscaleTime (TimePoint time) const
Private Attributes
TimerService & baseTimerService
TimerSingleShot timer
TimePoint nextTrigger
Duration shift = Duration()
uint32_t factor = 1
TimePoint startPointForFactor
Additional Inherited Members
Protected Member Functions inherited from infra::TimerService
TimerService (uint32_t id)
TimerService (const TimerService &other)=delete
~TimerService ()
TimerService & operator= (const TimerService &other)=delete
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 8 of file ScalableDerivedTimerService.hpp.
Constructor & Destructor Documentation
ScalableDerivedTimerService()
infra::ScalableDerivedTimerService::ScalableDerivedTimerService (uint32_t id, TimerService & baseTimerService)
Definition at line 5 of file ScalableDerivedTimerService.cpp.
         : TimerService(id)
         , baseTimerService(baseTimerService)
         , timer(baseTimerService.Id())
     {}
Member Function Documentation
GetCurrentShift()
Duration infra::ScalableDerivedTimerService::GetCurrentShift () const
Definition at line 45 of file ScalableDerivedTimerService.cpp.
References shift.
     {
         return shift;
     }
NextTriggerChanged()
void infra::ScalableDerivedTimerService::NextTriggerChanged () override virtual
Reimplemented from infra::TimerService.
Definition at line 11 of file ScalableDerivedTimerService.cpp.
References infra::Timer::Cancel(), infra::TimerService::NextTrigger(), nextTrigger, infra::TimerService::Progressed(), ScaleTime(), infra::TimerSingleShot::Start(), timer, and UnscaleTime().
Referenced by Scale(), and Shift().
     {
         nextTrigger = UnscaleTime(NextTrigger());
         if (NextTrigger() != TimePoint::max())
             timer.Start(nextTrigger, [this]() { Progressed(ScaleTime(nextTrigger)); });
         else
             timer.Cancel();
     }
Now()
TimePoint infra::ScalableDerivedTimerService::Now () const override virtual
Implements infra::TimerService.
Definition at line 21 of file ScalableDerivedTimerService.cpp.
References baseTimerService, infra::TimerService::Now(), and ScaleTime().
Referenced by Scale().
     {
         return ScaleTime(baseTimerService.Now());
     }
Resolution()
Duration infra::ScalableDerivedTimerService::Resolution () const override virtual
Implements infra::TimerService.
Definition at line 26 of file ScalableDerivedTimerService.cpp.
References baseTimerService, factor, and infra::TimerService::Resolution().
     {
         return baseTimerService.Resolution() * factor;
     }
Scale()
void infra::ScalableDerivedTimerService::Scale (uint32_t factor)
Definition at line 37 of file ScalableDerivedTimerService.cpp.
References factor, NextTriggerChanged(), Now(), shift, and startPointForFactor.
     {
         startPointForFactor = Now();
         this->factor = factor;
         shift += startPointForFactor - Now();
         NextTriggerChanged();
     }
ScaleTime()
TimePoint infra::ScalableDerivedTimerService::ScaleTime (TimePoint time) const private
Definition at line 50 of file ScalableDerivedTimerService.cpp.
References factor, shift, and startPointForFactor.
Referenced by NextTriggerChanged(), and Now().
     {
         return startPointForFactor + (time - startPointForFactor + shift) * factor;
     }
Shift()
void infra::ScalableDerivedTimerService::Shift (Duration shift)
Definition at line 31 of file ScalableDerivedTimerService.cpp.
References NextTriggerChanged(), and shift.
     {
         this->shift = shift;
         NextTriggerChanged();
     }
UnscaleTime()
TimePoint infra::ScalableDerivedTimerService::UnscaleTime (TimePoint time) const private
Definition at line 55 of file ScalableDerivedTimerService.cpp.
References factor, shift, and startPointForFactor.
Referenced by NextTriggerChanged().
     {
         return (time - startPointForFactor) / factor - shift + startPointForFactor;
     }
Member Data Documentation
baseTimerService
TimerService& infra::ScalableDerivedTimerService::baseTimerService private
Definition at line 28 of file ScalableDerivedTimerService.hpp.
Referenced by Now(), and Resolution().
factor
uint32_t infra::ScalableDerivedTimerService::factor = 1 private
Definition at line 33 of file ScalableDerivedTimerService.hpp.
Referenced by Resolution(), Scale(), ScaleTime(), and UnscaleTime().
nextTrigger
TimePoint infra::ScalableDerivedTimerService::nextTrigger private
Definition at line 30 of file ScalableDerivedTimerService.hpp.
Referenced by NextTriggerChanged().
shift
Duration infra::ScalableDerivedTimerService::shift = Duration() private
Definition at line 32 of file ScalableDerivedTimerService.hpp.
Referenced by GetCurrentShift(), Scale(), ScaleTime(), Shift(), and UnscaleTime().
startPointForFactor
TimePoint infra::ScalableDerivedTimerService::startPointForFactor private
Definition at line 34 of file ScalableDerivedTimerService.hpp.
Referenced by Scale(), ScaleTime(), and UnscaleTime().
timer
TimerSingleShot infra::ScalableDerivedTimerService::timer private
Definition at line 29 of file ScalableDerivedTimerService.hpp.
Referenced by NextTriggerChanged().
The documentation for this class was generated from the following files:
ScalableDerivedTimerService.hpp
ScalableDerivedTimerService.cpp