EMil: infra::JsonObjectIterator Class Reference
infra::JsonObjectIterator Class Reference
#include <Json.hpp>
Public Member Functions
bool operator== (const JsonObjectIterator &other) const
bool operator!= (const JsonObjectIterator &other) const
JsonKeyValue & operator* ()
const JsonKeyValue & operator* () const
JsonKeyValue * operator-> ()
const JsonKeyValue * operator-> () const
JsonObjectIterator & operator++ ()
JsonObjectIterator operator++ (int)
Private Types
enum {
readObjectStart, readKeyOrEnd, readKey, readColon,
readValue, readCommaOrObjectEnd, end
}
Private Member Functions
JsonObjectIterator ()
JsonObjectIterator (JsonObject &object)
void ParseNextToken ()
void SetError ()
void ReadObjectStart (JsonToken::Token token)
void ReadKeyOrEnd (JsonToken::Token token)
void ReadKey (JsonToken::Token token)
void ReadColon (JsonToken::Token token)
void ReadValue (JsonToken::Token token)
void ReadCommaOrObjectEnd (JsonToken::Token token)
Private Member Functions inherited from infra::JsonIterator
JsonIterator (infra::BoundedConstString objectString)
infra::Optional< JsonValue > ConvertValue (JsonToken::Token token)
Private Attributes
JsonObject * object = nullptr
JsonKeyValue keyValue
enum infra::JsonObjectIterator:: { ... } state = end
Private Attributes inherited from infra::JsonIterator
infra::BoundedConstString objectString
JsonTokenizer tokenizer
Friends
class JsonObject
Detailed Description
Definition at line 334 of file Json.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
readObjectStart
readKeyOrEnd
readKey
readColon
readValue
readCommaOrObjectEnd
end
Definition at line 371 of file Json.hpp.
         {
             readObjectStart,
             readKeyOrEnd,
             readKey,
             readColon,
             readValue,
             readCommaOrObjectEnd,
             end
         } state = end;
Constructor & Destructor Documentation
JsonObjectIterator() [1/2]
infra::JsonObjectIterator::JsonObjectIterator () private
Definition at line 855 of file Json.cpp.
         : JsonIterator("")
     {}
JsonObjectIterator() [2/2]
infra::JsonObjectIterator::JsonObjectIterator (JsonObject & object) private
Definition at line 859 of file Json.cpp.
         : JsonIterator(object.ObjectString())
         , object(&object)
         , state(readObjectStart)
     {
         ++*this;
     }
Member Function Documentation
operator!=()
bool infra::JsonObjectIterator::operator!= (const JsonObjectIterator & other) const
Definition at line 872 of file Json.cpp.
     {
         return !(*this == other);
     }
operator*() [1/2]
JsonKeyValue & infra::JsonObjectIterator::operator* ()
Definition at line 877 of file Json.cpp.
References end, keyValue, and state.
     {
         assert(state != end);
         return keyValue;
     }
operator*() [2/2]
const JsonKeyValue & infra::JsonObjectIterator::operator* () const
Definition at line 883 of file Json.cpp.
References end, keyValue, and state.
     {
         assert(state != end);
         return keyValue;
     }
operator++() [1/2]
JsonObjectIterator & infra::JsonObjectIterator::operator++ ()
Definition at line 901 of file Json.cpp.
References end, ParseNextToken(), readCommaOrObjectEnd, and state.
     {
         do
         {
             ParseNextToken();
         } while (state != readCommaOrObjectEnd && state != end);
         return *this;
     }
operator++() [2/2]
JsonObjectIterator infra::JsonObjectIterator::operator++ (int)
Definition at line 999 of file Json.cpp.
     {
         JsonObjectIterator result(*this);
         ++*this;
         return result;
     }
operator->() [1/2]
JsonKeyValue * infra::JsonObjectIterator::operator-> ()
Definition at line 889 of file Json.cpp.
References end, keyValue, and state.
     {
         assert(state != end);
         return &keyValue;
     }
operator->() [2/2]
const JsonKeyValue * infra::JsonObjectIterator::operator-> () const
Definition at line 895 of file Json.cpp.
References end, keyValue, and state.
     {
         assert(state != end);
         return &keyValue;
     }
operator==()
bool infra::JsonObjectIterator::operator== (const JsonObjectIterator & other) const
Definition at line 867 of file Json.cpp.
References end, state, and infra::JsonIterator::tokenizer.
     {
         return state == other.state && (state == end || tokenizer == other.tokenizer);
     }
ParseNextToken()
void infra::JsonObjectIterator::ParseNextToken () private
Definition at line 911 of file Json.cpp.
References end, ReadColon(), readColon, ReadCommaOrObjectEnd(), readCommaOrObjectEnd, ReadKey(), readKey, ReadKeyOrEnd(), readKeyOrEnd, ReadObjectStart(), readObjectStart, ReadValue(), readValue, state, infra::JsonTokenizer::Token(), and infra::JsonIterator::tokenizer.
Referenced by operator++().
     {
         JsonToken::Token token = tokenizer.Token();
         switch (state)
         {
             case readObjectStart:
                 ReadObjectStart(token);
                 break;
             case readKeyOrEnd:
                 ReadKeyOrEnd(token);
                 break;
             case readKey:
                 ReadKey(token);
                 break;
             case readColon:
                 ReadColon(token);
                 break;
             case readValue:
                 ReadValue(token);
                 break;
             case readCommaOrObjectEnd:
                 ReadCommaOrObjectEnd(token);
                 break;
             case end:
                 std::abort();
         }
     }
ReadColon()
void infra::JsonObjectIterator::ReadColon (JsonToken::Token token) private
Definition at line 966 of file Json.cpp.
References infra::Variant< T >::Is(), readValue, SetError(), and state.
Referenced by ParseNextToken().
     {
         state = readValue;
         if (!token.Is<JsonToken::Colon>())
             SetError();
     }
ReadCommaOrObjectEnd()
void infra::JsonObjectIterator::ReadCommaOrObjectEnd (JsonToken::Token token) private
Definition at line 983 of file Json.cpp.
References end, infra::Variant< T >::Is(), readKey, SetError(), and state.
Referenced by ParseNextToken().
     {
         if (token.Is<JsonToken::Comma>())
             state = readKey;
         else if (token.Is<JsonToken::RightBrace>())
             state = end;
         else
             SetError();
     }
ReadKey()
void infra::JsonObjectIterator::ReadKey (JsonToken::Token token) private
Definition at line 957 of file Json.cpp.
References infra::Variant< T >::Get(), infra::Variant< T >::Is(), infra::JsonKeyValue::key, keyValue, readColon, SetError(), and state.
Referenced by ParseNextToken().
     {
         state = readColon;
         if (token.Is<JsonToken::String>())
             keyValue.key = token.Get<JsonToken::String>().Value();
         else
             SetError();
     }
ReadKeyOrEnd()
void infra::JsonObjectIterator::ReadKeyOrEnd (JsonToken::Token token) private
Definition at line 946 of file Json.cpp.
References end, infra::Variant< T >::Get(), infra::Variant< T >::Is(), infra::JsonKeyValue::key, keyValue, readColon, SetError(), and state.
Referenced by ParseNextToken().
     {
         state = readColon;
         if (token.Is<JsonToken::RightBrace>())
             state = end;
         else if (token.Is<JsonToken::String>())
             keyValue.key = token.Get<JsonToken::String>().Value();
         else
             SetError();
     }
ReadObjectStart()
void infra::JsonObjectIterator::ReadObjectStart (JsonToken::Token token) private
Definition at line 939 of file Json.cpp.
References infra::Variant< T >::Is(), readKeyOrEnd, SetError(), and state.
Referenced by ParseNextToken().
     {
         state = readKeyOrEnd;
         if (!token.Is<JsonToken::LeftBrace>())
             SetError();
     }
ReadValue()
void infra::JsonObjectIterator::ReadValue (JsonToken::Token token) private
Definition at line 973 of file Json.cpp.
References infra::JsonIterator::ConvertValue(), keyValue, readCommaOrObjectEnd, readValue, SetError(), state, and infra::JsonKeyValue::value.
Referenced by ParseNextToken().
     {
         state = readCommaOrObjectEnd;
         infra::Optional<JsonValue> readValue = ConvertValue(token);
         if (readValue)
             keyValue.value = *readValue;
         else
             SetError();
     }
SetError()
void infra::JsonObjectIterator::SetError () private
Definition at line 993 of file Json.cpp.
References end, and state.
Referenced by ReadColon(), ReadCommaOrObjectEnd(), ReadKey(), ReadKeyOrEnd(), ReadObjectStart(), and ReadValue().
     {
         object->SetError();
         state = end;
     }
Friends And Related Function Documentation
JsonObject
friend class JsonObject friend
Definition at line 339 of file Json.hpp.
Member Data Documentation
keyValue
JsonKeyValue infra::JsonObjectIterator::keyValue private
Definition at line 369 of file Json.hpp.
Referenced by operator*(), operator->(), ReadKey(), ReadKeyOrEnd(), and ReadValue().
object
JsonObject* infra::JsonObjectIterator::object = nullptr private
Definition at line 368 of file Json.hpp.
state
enum { ... } infra::JsonObjectIterator::state
Referenced by operator*(), operator++(), operator->(), operator==(), ParseNextToken(), ReadColon(), ReadCommaOrObjectEnd(), ReadKey(), ReadKeyOrEnd(), ReadObjectStart(), ReadValue(), and SetError().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp