EMil: infra::TextOutputStream Class Reference
infra::TextOutputStream Class Reference
#include <OutputStream.hpp>
Classes
class Formatter
class FormatterBase
class WithErrorPolicy
class WithWriter
Public Member Functions
TextOutputStream (StreamWriter &writer, StreamErrorPolicy &errorPolicy)
TextOutputStream operator<< (Hex)
TextOutputStream operator<< (Bin)
TextOutputStream operator<< (Width width)
DataOutputStream operator<< (Data)
TextOutputStream & operator<< (Endl)
TextOutputStream & operator<< (const char *zeroTerminatedString)
TextOutputStream & operator<< (BoundedConstString string)
TextOutputStream & operator<< (const std::string &string)
TextOutputStream & operator<< (char c)
TextOutputStream & operator<< (uint8_t v)
TextOutputStream & operator<< (int32_t v)
TextOutputStream & operator<< (uint32_t v)
TextOutputStream & operator<< (int64_t v)
TextOutputStream & operator<< (uint64_t v)
TextOutputStream & operator<< (int v)
TextOutputStream & operator<< (unsigned int v)
TextOutputStream & operator<< (float v)
template<class... Args>
void Format (const char *format, Args &&... arguments)
Public Member Functions inherited from infra::OutputStream
OutputStream (StreamWriter &writer, StreamErrorPolicy &errorPolicy)
bool Failed () const
std::size_t SaveMarker () const
std::size_t ProcessedBytesSince (std::size_t marker) const
std::size_t Available () const
StreamWriter & Writer () const
StreamErrorPolicy & ErrorPolicy () const
Private Types
enum Radix { Radix::dec, Radix::bin, Radix::hex }
Private Member Functions
template<class T >
Formatter< T > MakeFormatter (T &&argument)
void OutputAsDecimal (uint64_t v, bool negative)
void OutputAsBinary (uint64_t v, bool negative)
void OutputAsHexadecimal (uint64_t v, bool negative)
template<class... Formatters>
void FormatHelper (const char *format, Formatters &&... formatters)
void FormatArgs (const char *format, infra::MemoryRange< FormatterBase *> formatters)
void OutputOptionalPadding (size_t paddingSize)
Private Attributes
Radix radix {Radix::dec}
Width width {0}
Additional Inherited Members
Protected Member Functions inherited from infra::OutputStream
~OutputStream ()=default
Detailed Description
Definition at line 84 of file OutputStream.hpp.
Member Enumeration Documentation
Radix
enum infra::TextOutputStream::Radix strong private
Enumerator
dec
bin
hex
Definition at line 163 of file OutputStream.hpp.
         {
             dec, bin, hex
         };
Constructor & Destructor Documentation
TextOutputStream()
infra::TextOutputStream::TextOutputStream (StreamWriter & writer, StreamErrorPolicy & errorPolicy)
Definition at line 110 of file OutputStream.cpp.
         : OutputStream(writer, errorPolicy)
     {}
Member Function Documentation
Format()
template<class... Args> void infra::TextOutputStream::Format (const char * format, Args &&... arguments)
Definition at line 396 of file OutputStream.hpp.
References FormatHelper(), and MakeFormatter().
     {
         FormatHelper(format, MakeFormatter(arguments)...);
     }
FormatArgs()
void infra::TextOutputStream::FormatArgs (const char * format, infra::MemoryRange< FormatterBase *> formatters) private
Definition at line 296 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeRange(), infra::ReinterpretCastByteRange(), infra::MemoryRange< T >::size(), and infra::OutputStream::Writer().
Referenced by FormatHelper().
     {
         while (*format != '\0')
         {
             const char* start = format;
             while (*format != '\0' && *format != '%')
                 ++format;
             Writer().Insert(ReinterpretCastByteRange(MakeRange(start, format)), ErrorPolicy());
             if (*format == '%')
             {
                 if (format[1] >= '1' && format[1] <= '9')
                 {
                     if (format[2] == '%')
                     {
                         uint8_t index = format[1] - '1';
                         if (index < formatters.size())
                             formatters[index]->Stream(*this);
                         ++format;
                     }
                     ++format;
                 }
                 ++format;
             }
         }
     }
FormatHelper()
template<class... Args> void infra::TextOutputStream::FormatHelper (const char * format, Args &&... formatters) private
Definition at line 402 of file OutputStream.hpp.
References FormatArgs().
Referenced by Format().
     {
         std::array<FormatterBase*, sizeof...(Args)> formatters = { &arguments... };
         FormatArgs(format, formatters);
     }
MakeFormatter()
template<class T > TextOutputStream::Formatter< T > infra::TextOutputStream::MakeFormatter (T && argument) private
Definition at line 390 of file OutputStream.hpp.
Referenced by Format().
     {
         return Formatter<T>(std::forward<T>(argument));
     }
operator<<() [1/17]
TextOutputStream infra::TextOutputStream::operator<< (Hex)
Definition at line 114 of file OutputStream.cpp.
References hex, and radix.
     {
         TextOutputStream result(*this);
         result.radix = Radix::hex;
         return result;
     }
operator<<() [2/17]
TextOutputStream infra::TextOutputStream::operator<< (Bin)
Definition at line 121 of file OutputStream.cpp.
References bin, and radix.
     {
         TextOutputStream result(*this);
         result.radix = Radix::bin;
         return result;
     }
operator<<() [3/17]
TextOutputStream infra::TextOutputStream::operator<< (Width width)
Definition at line 128 of file OutputStream.cpp.
References width.
     {
         TextOutputStream result(*this);
         result.width = width;
         return result;
     }
operator<<() [4/17]
DataOutputStream infra::TextOutputStream::operator<< (Data)
Definition at line 105 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), and infra::OutputStream::Writer().
     {
         return DataOutputStream(Writer(), ErrorPolicy());
     }
operator<<() [5/17]
TextOutputStream & infra::TextOutputStream::operator<< (Endl)
Definition at line 135 of file OutputStream.cpp.
     {
         *this << "\r\n";
         return *this;
     }
operator<<() [6/17]
TextOutputStream & infra::TextOutputStream::operator<< (const char * zeroTerminatedString)
Definition at line 83 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeRange(), OutputOptionalPadding(), infra::ReinterpretCastByteRange(), and infra::OutputStream::Writer().
     {
         const auto len = std::strlen(zeroTerminatedString);
         OutputOptionalPadding(len);
         Writer().Insert(ReinterpretCastByteRange(MakeRange(zeroTerminatedString, zeroTerminatedString + len)), ErrorPolicy());
         return *this;
     }
operator<<() [7/17]
TextOutputStream & infra::TextOutputStream::operator<< (BoundedConstString string)
Definition at line 91 of file OutputStream.cpp.
References infra::detail::begin(), infra::detail::end(), infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeRange(), infra::ReinterpretCastByteRange(), and infra::OutputStream::Writer().
     {
         Writer().Insert(ReinterpretCastByteRange(MakeRange(string.begin(), string.end())), ErrorPolicy());
         return *this;
     }
operator<<() [8/17]
TextOutputStream & infra::TextOutputStream::operator<< (const std::string & string)
Definition at line 98 of file OutputStream.cpp.
References infra::data, infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeRange(), infra::ReinterpretCastByteRange(), and infra::OutputStream::Writer().
     {
         Writer().Insert(ReinterpretCastByteRange(MakeRange(string.data(), string.data() + string.size())), ErrorPolicy());
         return *this;
     }
operator<<() [9/17]
TextOutputStream & infra::TextOutputStream::operator<< (char c)
Definition at line 141 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeByteRange(), and infra::OutputStream::Writer().
     {
         Writer().Insert(MakeByteRange(c), ErrorPolicy());
         return *this;
     }
operator<<() [10/17]
TextOutputStream & infra::TextOutputStream::operator<< (uint8_t v)
Definition at line 147 of file OutputStream.cpp.
     {
         return *this << static_cast<uint64_t>(v);
     }
operator<<() [11/17]
TextOutputStream & infra::TextOutputStream::operator<< (int32_t v)
Definition at line 152 of file OutputStream.cpp.
     {
         return *this << static_cast<int64_t>(v);
     }
operator<<() [12/17]
TextOutputStream & infra::TextOutputStream::operator<< (uint32_t v)
Definition at line 157 of file OutputStream.cpp.
     {
         return *this << static_cast<uint64_t>(v);
     }
operator<<() [13/17]
TextOutputStream & infra::TextOutputStream::operator<< (int64_t v)
Definition at line 162 of file OutputStream.cpp.
References bin, dec, hex, OutputAsBinary(), OutputAsDecimal(), OutputAsHexadecimal(), and radix.
     {
         const auto negative = v < 0;
         if (negative)
             v = -v;
         switch (radix)
         {
             case Radix::dec:
                 OutputAsDecimal(v, negative);
                 break;
             case Radix::bin:
                 OutputAsBinary(v, negative);
                 break;
             case Radix::hex:
                 OutputAsHexadecimal(v, negative);
                 break;
             default:
                 std::abort();
         }
         return *this;
     }
operator<<() [14/17]
TextOutputStream & infra::TextOutputStream::operator<< (uint64_t v)
Definition at line 185 of file OutputStream.cpp.
References bin, dec, hex, OutputAsBinary(), OutputAsDecimal(), OutputAsHexadecimal(), and radix.
     {
         switch (radix)
             {
             case Radix::dec:
                 OutputAsDecimal(v, false);
                 break;
             case Radix::bin:
                 OutputAsBinary(v, false);
                 break;
             case Radix::hex:
                 OutputAsHexadecimal(v, false);
                 break;
             default:
                 std::abort();
         }
         return *this;
     }
operator<<() [15/17]
TextOutputStream & infra::TextOutputStream::operator<< (int v)
Definition at line 206 of file OutputStream.cpp.
     {
         return *this << static_cast<int64_t>(v);
     }
operator<<() [16/17]
TextOutputStream & infra::TextOutputStream::operator<< (unsigned int v)
Definition at line 211 of file OutputStream.cpp.
     {
         return *this << static_cast<uint64_t>(v);
     }
operator<<() [17/17]
TextOutputStream & infra::TextOutputStream::operator<< (float v)
Definition at line 217 of file OutputStream.cpp.
     {
         if (v < 0)
             *this << "-";
         v = std::abs(v);
         *this << static_cast<uint32_t>(v);
         v -= static_cast<uint32_t>(v);
         *this << ".";
         *this << Width(3,'0') << static_cast<uint32_t>(v * 1000);
         return *this;
     }
OutputAsBinary()
void infra::TextOutputStream::OutputAsBinary (uint64_t v, bool negative) private
Definition at line 252 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeByteRange(), OutputOptionalPadding(), and infra::OutputStream::Writer().
Referenced by operator<<().
     {
         size_t nofDigits = negative ? 2 : 1;
         uint64_t mask = 1;
         while (v / mask >= 2)
         {
             mask *= 2;
             ++nofDigits;
         }
         OutputOptionalPadding(nofDigits);
         if (negative)
             Writer().Insert(MakeByteRange('-'), ErrorPolicy());
         while (mask != 0)
         {
             Writer().Insert(MakeByteRange(static_cast<char>('0' + ((v / mask) & 1))), ErrorPolicy());
             mask /= 2;
         }
     }
OutputAsDecimal()
void infra::TextOutputStream::OutputAsDecimal (uint64_t v, bool negative) private
Definition at line 231 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeByteRange(), OutputOptionalPadding(), and infra::OutputStream::Writer().
Referenced by operator<<().
     {
         size_t nofDigits = negative ? 2 : 1;
         uint64_t mask = 1;
         while (v / mask >= 10)
         {
             mask *= 10;
             ++nofDigits;
         }
         OutputOptionalPadding(nofDigits);
         if (negative)
             Writer().Insert(MakeByteRange('-'), ErrorPolicy());
         while (mask != 0)
         {
             Writer().Insert(MakeByteRange(static_cast<char>(((v / mask) % 10) + '0')), ErrorPolicy());
             mask /= 10;
         }
     }
OutputAsHexadecimal()
void infra::TextOutputStream::OutputAsHexadecimal (uint64_t v, bool negative) private
Definition at line 273 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeByteRange(), OutputOptionalPadding(), and infra::OutputStream::Writer().
Referenced by operator<<().
     {
         static const char hexChars[] = "0123456789abcdef";
         size_t nofDigits = negative ? 2 : 1;
         uint64_t mask = 1;
         while (v / mask >= 16)
         {
             mask *= 16;
             ++nofDigits;
         }
         OutputOptionalPadding(nofDigits);
         if (negative)
             Writer().Insert(MakeByteRange('-'), ErrorPolicy());
         while (mask != 0)
         {
             Writer().Insert(MakeByteRange(hexChars[(v / mask) % 16]), ErrorPolicy());
             mask /= 16;
         }
     }
OutputOptionalPadding()
void infra::TextOutputStream::OutputOptionalPadding (size_t paddingSize) private
Definition at line 327 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeByteRange(), infra::Width::padding, infra::Width::width, width, and infra::OutputStream::Writer().
Referenced by operator<<(), OutputAsBinary(), OutputAsDecimal(), and OutputAsHexadecimal().
     {
         for (auto i = size; i < width.width; ++i)
             Writer().Insert(MakeByteRange(width.padding), ErrorPolicy());
     }
Member Data Documentation
radix
Radix infra::TextOutputStream::radix {Radix::dec} private
Definition at line 168 of file OutputStream.hpp.
Referenced by operator<<().
width
Width infra::TextOutputStream::width {0} private
Definition at line 169 of file OutputStream.hpp.
Referenced by operator<<(), and OutputOptionalPadding().
The documentation for this class was generated from the following files:
OutputStream.hpp
OutputStream.cpp