EMil: TestAutoResetFunction.cpp File Reference
TestAutoResetFunction.cpp File Reference
Functions
TEST (AutoResetFunctionTest, IsInvokeable)
TEST (AutoResetFunctionTest, IsResetAfterInvoke)
TEST (AutoResetFunctionTest, ReAssignDuringInvoke)
TEST (AutoResetFunctionTest, TestConstructedEmpty)
TEST (AutoResetFunctionTest, TestConstructedEmptyByNullptr)
TEST (AutoResetFunctionTest, TestMoveAssign)
TEST (AutoResetFunctionTest, TestAssignNullptr)
TEST (AutoResetFunctionTest, TestInvoke0)
TEST (AutoResetFunctionTest, TestInvoke1)
TEST (AutoResetFunctionTest, TestClone)
TEST (AutoResetFunctionTest, TestSwap)
TEST (AutoResetFunctionTest, TestReturnValue)
TEST (AutoResetFunctionTest, TestParameter)
TEST (AutoResetFunctionTest, TestCompareToNullptr)
Function Documentation
TEST() [1/14]
TEST (AutoResetFunctionTest , IsInvokeable)
Definition at line 6 of file TestAutoResetFunction.cpp.
 {
     infra::MockCallback<void()> m;
     infra::AutoResetFunction<void()> f([&m]() { m.callback(); });
     EXPECT_CALL(m, callback());
     f();
 }
TEST() [2/14]
TEST (AutoResetFunctionTest , IsResetAfterInvoke)
Definition at line 15 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE().
 {
     infra::MockCallback<void()> m;
     infra::AutoResetFunction<void()> f([&m]() { m.callback(); });
     EXPECT_CALL(m, callback());
     f();
     EXPECT_FALSE(f);
 }
TEST() [3/14]
TEST (AutoResetFunctionTest , ReAssignDuringInvoke)
Definition at line 25 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE().
 {
     infra::MockCallback<void()> a;
     infra::MockCallback<void()> b;
     infra::AutoResetFunction<void(), 3 * sizeof(void*)> f;
     f = [&a, &b, &f]() { f = [&b]() { b.callback(); }; a.callback(); };
     EXPECT_CALL(a, callback());
     EXPECT_CALL(b, callback());
     f();
     f();
     EXPECT_FALSE(f);
 }
TEST() [4/14]
TEST (AutoResetFunctionTest , TestConstructedEmpty)
Definition at line 40 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE().
 {
     infra::AutoResetFunction<void()> f;
     EXPECT_FALSE(f);
 }
TEST() [5/14]
TEST (AutoResetFunctionTest , TestConstructedEmptyByNullptr)
Definition at line 46 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE().
 {
     infra::AutoResetFunction<void()> f(nullptr);
     EXPECT_FALSE(f);
 }
TEST() [6/14]
TEST (AutoResetFunctionTest , TestMoveAssign)
Definition at line 52 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE().
 {
     infra::MockCallback<void()> m;
     infra::AutoResetFunction<void()> f([&m]() { m.callback(); });
     infra::AutoResetFunction<void()> f2;
     f2 = std::move(f);
     EXPECT_FALSE(static_cast<bool>(f));
     EXPECT_CALL(m, callback());
     f2();
 }
TEST() [7/14]
TEST (AutoResetFunctionTest , TestAssignNullptr)
Definition at line 63 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE().
 {
     infra::MockCallback<void()> m;
     infra::AutoResetFunction<void()> f([&m]() { m.callback(); });
     f = nullptr;
     EXPECT_FALSE(f);
 }
TEST() [8/14]
TEST (AutoResetFunctionTest , TestInvoke0)
Definition at line 71 of file TestAutoResetFunction.cpp.
 {
     infra::MockCallback<void()> m;
     infra::AutoResetFunction<void()> f([&m]() { m.callback(); });
     EXPECT_CALL(m, callback());
     f.Invoke(std::make_tuple());
 }
TEST() [9/14]
TEST (AutoResetFunctionTest , TestInvoke1)
Definition at line 79 of file TestAutoResetFunction.cpp.
 {
     infra::MockCallback<void(int)> m;
     infra::AutoResetFunction<void(int)> f([&m](int x) { m.callback(x); });
     EXPECT_CALL(m, callback(1));
     f.Invoke(std::make_tuple(1));
 }
TEST() [10/14]
TEST (AutoResetFunctionTest , TestClone)
Definition at line 87 of file TestAutoResetFunction.cpp.
References EXPECT_TRUE().
 {
     infra::MockCallback<void(int)> m;
     infra::AutoResetFunction<void(int)> f([&m](int x) { m.callback(x); });
     EXPECT_CALL(m, callback(1));
     f.Clone().Invoke(1);
     EXPECT_TRUE(static_cast<bool>(f));
 }
TEST() [11/14]
TEST (AutoResetFunctionTest , TestSwap)
Definition at line 97 of file TestAutoResetFunction.cpp.
References EXPECT_FALSE(), and infra::swap().
 {
     infra::MockCallback<void()> m;
     infra::AutoResetFunction<void()> f([&m]() { m.callback(); });
     infra::AutoResetFunction<void()> f2;
     swap(f, f2);
     EXPECT_FALSE(f);
     EXPECT_CALL(m, callback());
     f2();
 }
TEST() [12/14]
TEST (AutoResetFunctionTest , TestReturnValue)
Definition at line 108 of file TestAutoResetFunction.cpp.
References EXPECT_EQ().
 {
     infra::AutoResetFunction<int()> f([]() { return 1; });
     EXPECT_EQ(1, f());
 }
TEST() [13/14]
TEST (AutoResetFunctionTest , TestParameter)
Definition at line 114 of file TestAutoResetFunction.cpp.
 {
     infra::MockCallback<void(int)> m;
     infra::AutoResetFunction<void(int)> f([&m](int x) { m.callback(x); });
     EXPECT_CALL(m, callback(1));
     f(1);
 }
TEST() [14/14]
TEST (AutoResetFunctionTest , TestCompareToNullptr)
Definition at line 122 of file TestAutoResetFunction.cpp.
References EXPECT_EQ().
 {
     infra::AutoResetFunction<void()> f;
     EXPECT_EQ(f, nullptr);
     EXPECT_EQ(nullptr, f);
     infra::AutoResetFunction<void()> g([]() {});
     EXPECT_NE(g, nullptr);
     EXPECT_NE(nullptr, g);
 }