EMil: TestClaimer Class Reference
TestClaimer Class Reference
Public Member Functions
TestClaimer (infra::ClaimableResource &resource)
void GrantedClaim ()
Public Member Functions inherited from infra::ClaimableResource::ClaimerWithSize< ExtraSize >
ClaimerWithSize (ClaimableResource &resource)
void Claim (const infra::Function< void(), ExtraSize > &claimedFunc)
virtual void Release () override
Public Member Functions inherited from infra::ClaimableResource::ClaimerBase
ClaimerBase (ClaimableResource &resource)
ClaimerBase (const ClaimerBase &other)=delete
ClaimerBase & operator= (const ClaimerBase &other)=delete
bool IsClaimed () const
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Public Attributes
uint32_t claimsGranted
Additional Inherited Members
Public Types inherited from infra::ClaimableResource::ClaimerWithSize< ExtraSize >
template<std::size_t NewExtraSize>
using WithSize = ClaimerWithSize< NewExtraSize >
Protected Member Functions inherited from infra::ClaimableResource::ClaimerBase
~ClaimerBase ()
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 5 of file TestClaimableResource.cpp.
Constructor & Destructor Documentation
TestClaimer()
TestClaimer::TestClaimer (infra::ClaimableResource & resource) inline
Definition at line 9 of file TestClaimableResource.cpp.
         : infra::ClaimableResource::Claimer(resource)
         , claimsGranted(0)
     {}
Member Function Documentation
GrantedClaim()
void TestClaimer::GrantedClaim () inline
Definition at line 16 of file TestClaimableResource.cpp.
References claimsGranted, EXPECT_TRUE(), and infra::ClaimableResource::ClaimerBase::IsClaimed().
Referenced by TEST_F().
     {
         EXPECT_TRUE(IsClaimed());
         ++claimsGranted;
     }
Member Data Documentation
claimsGranted
uint32_t TestClaimer::claimsGranted
Definition at line 14 of file TestClaimableResource.cpp.
Referenced by GrantedClaim().
The documentation for this class was generated from the following file:
TestClaimableResource.cpp