EMil: services::ConnectionSerial::StateInitSizeResponse Class Reference
services::ConnectionSerial::StateInitSizeResponse Class Reference
Public Member Functions
StateInitSizeResponse (ConnectionSerial &connection)
virtual void SizeRequestReceived () override
Public Member Functions inherited from services::ConnectionSerial::StateInit
StateInit (ConnectionSerial &connection)
virtual void EvaluatePendingSend () override
virtual void Reset () override
virtual void SizeResponseRequestReceived (size_t size) override
virtual void SizeResponseReceived (size_t size) override
virtual size_t ContentReceived (infra::ConstByteRange receivedRange) override
virtual void SizeUpdateReceived (size_t size) override
virtual void AccumulateWindowUpdateSize (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::State
State (ConnectionSerial &connection)
virtual ~State ()=default
virtual void AckReceived ()
Private Member Functions
void SendWindowSizeResponse ()
Private Attributes
MessageHeader windowSizeRespMsg = MessageHeader(MessageType::SizeResponse)
Additional Inherited Members
Protected Attributes inherited from services::ConnectionSerial::StateInit
bool sendInProgress = false
bool resetAfterSend = false
bool responseRequestAfterSend = false
Protected Attributes inherited from services::ConnectionSerial::State
ConnectionSerial & connection
hal::SerialCommunication & serialCommunication
Detailed Description
Definition at line 183 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
StateInitSizeResponse()
services::ConnectionSerial::StateInitSizeResponse::StateInitSizeResponse (ConnectionSerial & connection)
Definition at line 426 of file ConnectionSerial.cpp.
References SendWindowSizeResponse().
         : StateInit(connection)
     {
         SendWindowSizeResponse();
     }
Member Function Documentation
SendWindowSizeResponse()
void services::ConnectionSerial::StateInitSizeResponse::SendWindowSizeResponse () private
Definition at line 432 of file ConnectionSerial.cpp.
References hal::SerialCommunication::SendData(), and services::ConnectionSerial::serialCommunication.
Referenced by StateInitSizeResponse().
     {
         windowSizeRespMsg.SetSize(connection.ReceiveBufferSize());
         serialCommunication.SendData(windowSizeRespMsg.Range(), [this]()
         {
             if (responseRequestAfterSend)
                 connection.GoStateInitSizeResponseRequest();
             else
                 connection.GoStateConnectedIdle();
         });
     }
SizeRequestReceived()
void services::ConnectionSerial::StateInitSizeResponse::SizeRequestReceived () override virtual
Implements services::ConnectionSerial::State.
Definition at line 444 of file ConnectionSerial.cpp.
     {
         responseRequestAfterSend = true;
     }
Member Data Documentation
windowSizeRespMsg
MessageHeader services::ConnectionSerial::StateInitSizeResponse::windowSizeRespMsg = MessageHeader(MessageType::SizeResponse) private
Definition at line 195 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp