EMil: infra::Optional< T > Class Template Reference
infra::Optional< T > Class Template Reference
#include <Optional.hpp>
Public Member Functions
constexpr Optional ()=default
Optional (const Optional &other)
Optional (Optional &&other)
Optional (None)
template<class U >
Optional (const Optional< U > &other)
template<class... Args>
Optional (InPlace, Args &&... args)
~Optional ()
Optional & operator= (const Optional &other)
Optional & operator= (Optional &&other)
Optional & operator= (const None &)
Optional & operator= (const T &value)
Optional & operator= (T &&value)
template<class... Args>
void Emplace (Args &&... args)
template<class U , class... Args>
void Emplace (std::initializer_list< U > list, Args &&... args)
const T & operator* () const
T & operator* ()
const T * operator-> () const
T * operator-> ()
operator bool () const
bool operator! () const
bool operator== (const Optional &other) const
bool operator!= (const Optional &other) const
template<class U >
T ValueOr (U &&value) const
Private Member Functions
void Reset ()
Private Attributes
bool initialized = false
StaticStorage< T > data
Friends
bool operator== (const Optional &x, const None &y)
bool operator!= (const Optional &x, const None &y)
bool operator== (const None &x, const Optional &y)
bool operator!= (const None &x, const Optional &y)
bool operator== (const Optional &x, const T &y)
bool operator!= (const Optional &x, const T &y)
bool operator== (const T &x, const Optional &y)
bool operator!= (const T &x, const Optional &y)
Detailed Description
template<class T>
class infra::Optional< T >
Definition at line 32 of file Optional.hpp.
Constructor & Destructor Documentation
Optional() [1/6]
template<class T> constexpr infra::Optional< T >::Optional () default
Optional() [2/6]
template<class T > infra::Optional< T >::Optional (const Optional< T > & other)
Definition at line 147 of file Optional.hpp.
     {
         if (other)
             Emplace(*other);
     }
Optional() [3/6]
template<class T > infra::Optional< T >::Optional (Optional< T > && other)
Definition at line 154 of file Optional.hpp.
     {
         if (other)
         {
             Emplace(std::move(*other));
             other.Reset();
         }
     }
Optional() [4/6]
template<class T > infra::Optional< T >::Optional (None)
Definition at line 164 of file Optional.hpp.
     {}
Optional() [5/6]
template<class T > template<class U > infra::Optional< T >::Optional (const Optional< U > & other) explicit
Definition at line 169 of file Optional.hpp.
     {
         if (other)
             Emplace(*other);
     }
Optional() [6/6]
template<class T > template<class... Args> infra::Optional< T >::Optional (InPlace , Args &&... args) explicit
Definition at line 177 of file Optional.hpp.
     {
         Emplace(std::forward<Args>(args)...);
     }
~Optional()
template<class T > infra::Optional< T >::~Optional ()
Definition at line 183 of file Optional.hpp.
     {
         Reset();
     }
Member Function Documentation
Emplace() [1/2]
template<class T > template<class... Args> void infra::Optional< T >::Emplace (Args &&... args)
Definition at line 304 of file Optional.hpp.
Referenced by services::DatagramBsd::TryAllocateSendStream(), and services::DatagramWin::TryAllocateSendStream().
     {
         Reset();
         initialized = true;
         data.Construct(std::forward<Args>(args)...);
     }
Emplace() [2/2]
template<class T > template<class U, class... Args> void infra::Optional< T >::Emplace (std::initializer_list< U > list, Args &&... args)
Definition at line 313 of file Optional.hpp.
     {
         Reset();
         initialized = true;
         data.Construct(list, std::forward<Args>(args)...);
     }
operator bool()
template<class T > infra::Optional< T >::operator bool () const explicit
Definition at line 266 of file Optional.hpp.
     {
         return initialized;
     }
operator!()
template<class T > bool infra::Optional< T >::operator! () const
Definition at line 272 of file Optional.hpp.
     {
         return !initialized;
     }
operator!=()
template<class T > bool infra::Optional< T >::operator!= (const Optional< T > & other) const
Definition at line 287 of file Optional.hpp.
     {
         return !(*this == other);
     }
operator*() [1/2]
template<class T > const T & infra::Optional< T >::operator* () const
Definition at line 238 of file Optional.hpp.
     {
         assert(initialized);
         return *data;
     }
operator*() [2/2]
template<class T > T & infra::Optional< T >::operator* ()
Definition at line 245 of file Optional.hpp.
     {
         assert(initialized);
         return *data;
     }
operator->() [1/2]
template<class T > const T * infra::Optional< T >::operator-> () const
Definition at line 252 of file Optional.hpp.
     {
         assert(initialized);
         return &*data;
     }
operator->() [2/2]
template<class T > T * infra::Optional< T >::operator-> ()
Definition at line 259 of file Optional.hpp.
     {
         assert(initialized);
         return &*data;
     }
operator=() [1/5]
template<class T > Optional< T > & infra::Optional< T >::operator= (const Optional< T > & other)
Definition at line 189 of file Optional.hpp.
     {
         if (this != &other)
         {
             Reset();
             if (other)
                 Emplace(*other);
         }
         return *this;
     }
operator=() [2/5]
template<class T > Optional< T > & infra::Optional< T >::operator= (Optional< T > && other)
Definition at line 202 of file Optional.hpp.
     {
         Reset();
         if (other)
         {
             Emplace(std::move(*other));
             other.Reset();
         }
         return *this;
     }
operator=() [3/5]
template<class T > Optional< T > & infra::Optional< T >::operator= (const None &)
Definition at line 215 of file Optional.hpp.
     {
         Reset();
         return *this;
     }
operator=() [4/5]
template<class T> Optional< T > & infra::Optional< T >::operator= (const T & value)
Definition at line 222 of file Optional.hpp.
     {
         Reset();
         Emplace(value);
         return *this;
     }
operator=() [5/5]
template<class T> Optional< T > & infra::Optional< T >::operator= (T && value)
Definition at line 230 of file Optional.hpp.
     {
         Reset();
         Emplace(std::forward<T>(value));
         return *this;
     }
operator==()
template<class T > bool infra::Optional< T >::operator== (const Optional< T > & other) const
Definition at line 278 of file Optional.hpp.
     {
         if (initialized && other.initialized)
             return **this == *other;
         else
             return initialized == other.initialized;
     }
Reset()
template<class T > void infra::Optional< T >::Reset () private
Definition at line 321 of file Optional.hpp.
     {
         if (initialized)
         {
             data.Destruct();
             initialized = false;
         }
     }
ValueOr()
template<class T > template<class U > T infra::Optional< T >::ValueOr (U && value) const
Definition at line 294 of file Optional.hpp.
Referenced by infra::TextInputStream::ReadAsDecimal(), and infra::TextInputStream::ReadAsHex().
     {
         if (initialized)
             return **this;
         else
             return std::move(value);
     }
Friends And Related Function Documentation
operator!= [1/4]
template<class T> bool operator!= (const Optional< T > & x, const None & y) friend
Definition at line 69 of file Optional.hpp.
 { return !(x == y); }
operator!= [2/4]
template<class T> bool operator!= (const None & x, const Optional< T > & y) friend
Definition at line 71 of file Optional.hpp.
 { return y != x; }
operator!= [3/4]
template<class T> bool operator!= (const Optional< T > & x, const T & y) friend
Definition at line 73 of file Optional.hpp.
 { return !(x == y); }
operator!= [4/4]
template<class T> bool operator!= (const T & x, const Optional< T > & y) friend
Definition at line 75 of file Optional.hpp.
 { return y != x; }
operator== [1/4]
template<class T> bool operator== (const Optional< T > & x, const None & y) friend
Definition at line 68 of file Optional.hpp.
 { return !x; }
operator== [2/4]
template<class T> bool operator== (const None & x, const Optional< T > & y) friend
Definition at line 70 of file Optional.hpp.
 { return y == x; }
operator== [3/4]
template<class T> bool operator== (const Optional< T > & x, const T & y) friend
Definition at line 72 of file Optional.hpp.
 { return x && *x == y; }
operator== [4/4]
template<class T> bool operator== (const T & x, const Optional< T > & y) friend
Definition at line 74 of file Optional.hpp.
 { return y == x; }
Member Data Documentation
data
template<class T> StaticStorage<T> infra::Optional< T >::data private
Definition at line 85 of file Optional.hpp.
initialized
template<class T> bool infra::Optional< T >::initialized = false private
Definition at line 84 of file Optional.hpp.
Referenced by infra::Optional< services::DatagramWin::StreamWriterWin >::operator==().
The documentation for this class was generated from the following file:
Optional.hpp