EMil: infra::JsonArrayIterator Class Reference
infra::JsonArrayIterator Class Reference
#include <Json.hpp>
Public Member Functions
bool operator== (const JsonArrayIterator &other) const
bool operator!= (const JsonArrayIterator &other) const
JsonValue & operator* ()
const JsonValue & operator* () const
JsonValue * operator-> ()
const JsonValue * operator-> () const
JsonArrayIterator & operator++ ()
JsonArrayIterator operator++ (int)
Private Types
enum {
readArrayStart, readValueOrEnd, readValue, readCommaOrArrayEnd,
end
}
Private Member Functions
JsonArrayIterator ()
JsonArrayIterator (JsonArray &jsonArray)
void ReadValue (JsonToken::Token token)
void SetError ()
Private Member Functions inherited from infra::JsonIterator
JsonIterator (infra::BoundedConstString objectString)
infra::Optional< JsonValue > ConvertValue (JsonToken::Token token)
Private Attributes
JsonArray * jsonArray = nullptr
JsonValue value
enum infra::JsonArrayIterator:: { ... } state = end
Private Attributes inherited from infra::JsonIterator
infra::BoundedConstString objectString
JsonTokenizer tokenizer
Friends
class JsonArray
template<class T >
class JsonValueArrayIterator
Detailed Description
Definition at line 383 of file Json.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
readArrayStart
readValueOrEnd
readValue
readCommaOrArrayEnd
end
Definition at line 416 of file Json.hpp.
         {
             readArrayStart,
             readValueOrEnd,
             readValue,
             readCommaOrArrayEnd,
             end
         } state = end;
Constructor & Destructor Documentation
JsonArrayIterator() [1/2]
infra::JsonArrayIterator::JsonArrayIterator () private
Definition at line 1006 of file Json.cpp.
         : JsonIterator("")
     {}
JsonArrayIterator() [2/2]
infra::JsonArrayIterator::JsonArrayIterator (JsonArray & jsonArray) explicit private
Definition at line 1010 of file Json.cpp.
         : JsonIterator(jsonArray.ObjectString())
         , jsonArray(&jsonArray)
         , state(readArrayStart)
     {
         ++*this;
     }
Member Function Documentation
operator!=()
bool infra::JsonArrayIterator::operator!= (const JsonArrayIterator & other) const
Definition at line 1023 of file Json.cpp.
     {
         return !(*this == other);
     }
operator*() [1/2]
JsonValue & infra::JsonArrayIterator::operator* ()
Definition at line 1028 of file Json.cpp.
References end, state, and value.
     {
         assert(state != end);
         return value;
     }
operator*() [2/2]
const JsonValue & infra::JsonArrayIterator::operator* () const
Definition at line 1034 of file Json.cpp.
References end, state, and value.
     {
         assert(state != end);
         return value;
     }
operator++() [1/2]
JsonArrayIterator & infra::JsonArrayIterator::operator++ ()
Definition at line 1052 of file Json.cpp.
References end, infra::Variant< T >::Is(), readArrayStart, readCommaOrArrayEnd, ReadValue(), readValue, readValueOrEnd, SetError(), state, infra::JsonTokenizer::Token(), and infra::JsonIterator::tokenizer.
     {
         do
         {
             JsonToken::Token token = tokenizer.Token();
             switch (state)
             {
                 case readArrayStart:
                     state = readValueOrEnd;
                     if (!token.Is<JsonToken::LeftBracket>())
                         SetError();
                     break;
                 case readValueOrEnd:
                     state = readCommaOrArrayEnd;
                     if (token.Is<JsonToken::RightBracket>())
                         state = end;
                     else
                         ReadValue(token);
                     break;
                 case readValue:
                     state = readCommaOrArrayEnd;
                     ReadValue(token);
                     break;
                 case readCommaOrArrayEnd:
                     if (token.Is<JsonToken::Comma>())
                         state = readValue;
                     else if (token.Is<JsonToken::RightBracket>())
                         state = end;
                     else
                         SetError();
                     break;
                 case end:
                     std::abort();
             }
         } while (state != readCommaOrArrayEnd && state != end);
         return *this;
     }
operator++() [2/2]
JsonArrayIterator infra::JsonArrayIterator::operator++ (int)
Definition at line 1091 of file Json.cpp.
     {
         JsonArrayIterator result(*this);
         ++*this;
         return result;
     }
operator->() [1/2]
JsonValue * infra::JsonArrayIterator::operator-> ()
Definition at line 1040 of file Json.cpp.
References end, state, and value.
     {
         assert(state != end);
         return &value;
     }
operator->() [2/2]
const JsonValue * infra::JsonArrayIterator::operator-> () const
Definition at line 1046 of file Json.cpp.
References end, state, and value.
     {
         assert(state != end);
         return &value;
     }
operator==()
bool infra::JsonArrayIterator::operator== (const JsonArrayIterator & other) const
Definition at line 1018 of file Json.cpp.
References end, state, and infra::JsonIterator::tokenizer.
     {
         return state == other.state && (state == end || tokenizer == other.tokenizer);
     }
ReadValue()
void infra::JsonArrayIterator::ReadValue (JsonToken::Token token) private
Definition at line 1098 of file Json.cpp.
References infra::JsonIterator::ConvertValue(), readValue, SetError(), and value.
Referenced by operator++().
     {
         infra::Optional<JsonValue> readValue = ConvertValue(token);
         if (readValue)
             value = *readValue;
         else
             SetError();
     }
SetError()
void infra::JsonArrayIterator::SetError () private
Definition at line 1107 of file Json.cpp.
References end, jsonArray, infra::JsonArray::SetError(), and state.
Referenced by infra::JsonValueArrayIterator< T >::JsonValueArrayIterator(), operator++(), and ReadValue().
     {
         jsonArray->SetError();
         state = end;
     }
Friends And Related Function Documentation
JsonArray
friend class JsonArray friend
Definition at line 388 of file Json.hpp.
JsonValueArrayIterator
template<class T > friend class JsonValueArrayIterator friend
Definition at line 391 of file Json.hpp.
Member Data Documentation
jsonArray
JsonArray* infra::JsonArrayIterator::jsonArray = nullptr private
Definition at line 413 of file Json.hpp.
Referenced by SetError().
state
enum { ... } infra::JsonArrayIterator::state
Referenced by operator*(), operator++(), operator->(), operator==(), and SetError().
value
JsonValue infra::JsonArrayIterator::value private
Definition at line 414 of file Json.hpp.
Referenced by operator*(), operator->(), and ReadValue().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp