EMil: services::HttpClientImpl::HttpResponseParser Class Reference
services::HttpClientImpl::HttpResponseParser Class Reference
Public Member Functions
HttpResponseParser (HttpClientImpl &httpClient, infra::BoundedString &headerBuffer)
void DataReceived (infra::StreamReaderWithRewinding &reader)
bool Done () const
bool Error () const
uint32_t ContentLength () const
Private Member Functions
void ParseStatusLine (infra::StreamReaderWithRewinding &reader)
bool HttpVersionValid (infra::BoundedConstString httpVersion)
void ParseHeaders (infra::StreamReaderWithRewinding &reader)
HttpHeader HeaderFromString (infra::BoundedConstString header)
void SetError ()
Private Attributes
HttpClientImpl & httpClient
infra::BoundedString & headerBuffer
bool done = false
bool error = false
bool statusParsed = false
infra::Optional< uint32_t > contentLength
Detailed Description
Definition at line 86 of file HttpClientImpl.hpp.
Constructor & Destructor Documentation
HttpResponseParser()
services::HttpClientImpl::HttpResponseParser::HttpResponseParser (HttpClientImpl & httpClient, infra::BoundedString & headerBuffer)
Definition at line 311 of file HttpClientImpl.cpp.
         : httpClient(httpClient)
         , headerBuffer(headerBuffer)
     {}
Member Function Documentation
ContentLength()
uint32_t services::HttpClientImpl::HttpResponseParser::ContentLength () const
Definition at line 335 of file HttpClientImpl.cpp.
References services::HttpClientImpl::contentLength.
     {
         return *contentLength;
     }
DataReceived()
void services::HttpClientImpl::HttpResponseParser::DataReceived (infra::StreamReaderWithRewinding & reader)
Definition at line 316 of file HttpClientImpl.cpp.
     {
         if (!statusParsed)
             ParseStatusLine(reader);
         if (!Error())
             ParseHeaders(reader);
     }
Done()
bool services::HttpClientImpl::HttpResponseParser::Done () const
Definition at line 325 of file HttpClientImpl.cpp.
     {
         return done;
     }
Error()
bool services::HttpClientImpl::HttpResponseParser::Error () const
Definition at line 330 of file HttpClientImpl.cpp.
     {
         return error;
     }
HeaderFromString()
HttpHeader services::HttpClientImpl::HttpResponseParser::HeaderFromString (infra::BoundedConstString header) private
Definition at line 409 of file HttpClientImpl.cpp.
References infra::BoundedStringBase< char >::npos, infra::Tokenizer::Token(), infra::Tokenizer::TokenAndRest(), and value.
     {
         infra::Tokenizer tokenizer(header, ':');
         auto value = tokenizer.TokenAndRest(1);
         auto headerBegin = value.find_first_not_of(' ');
         return{ tokenizer.Token(0), headerBegin != infra::BoundedString::npos ? value.substr(headerBegin) : "" };
     }
HttpVersionValid()
bool services::HttpClientImpl::HttpResponseParser::HttpVersionValid (infra::BoundedConstString httpVersion) private
Definition at line 365 of file HttpClientImpl.cpp.
     {
         static const std::array<infra::BoundedConstString, 2> validVersions{ "HTTP/1.0",  "HTTP/1.1" };
         return std::any_of(validVersions.begin(), validVersions.end(), [&](infra::BoundedConstString validVersion) { return httpVersion == validVersion; });
     }
ParseHeaders()
void services::HttpClientImpl::HttpResponseParser::ParseHeaders (infra::StreamReaderWithRewinding & reader) private
Definition at line 371 of file HttpClientImpl.cpp.
References infra::InputStream::Available(), infra::StreamReaderWithRewinding::ConstructSaveMarker(), services::HttpClientImpl::contentLength, infra::InputStream::Empty(), infra::BoundedStringBase< T >::find_first_of(), infra::BoundedStringBase< T >::full(), services::HttpClientImpl::headerBuffer, infra::BoundedStringBase< T >::max_size(), infra::none, infra::BoundedStringBase< char >::npos, infra::BoundedStringBase< T >::resize(), infra::StreamReaderWithRewinding::Rewind(), infra::BoundedStringBase< T >::size(), and infra::BoundedStringBase< T >::substr().
     {
         infra::TextInputStream::WithErrorPolicy stream(reader);
         while (!done && !stream.Empty())
         {
             auto start = reader.ConstructSaveMarker();
             headerBuffer.resize(std::min(headerBuffer.max_size(), stream.Available()));
             stream >> headerBuffer;
             auto crlfPos = headerBuffer.find_first_of(crlf);
             if (crlfPos != infra::BoundedString::npos)
             {
                 auto headerLine = headerBuffer.substr(0, crlfPos);
                 reader.Rewind(start + headerLine.size() + crlf.size());
                 if (headerLine.empty() && headerBuffer.size() > crlfPos)
                 {
                     error = contentLength == infra::none;
                     done = true;
                     return;
                 }
                 auto header = HeaderFromString(headerLine);
                 if (header.Field() == "Content-Length")
                 {
                     contentLength = 0;
                     infra::StringInputStream contentLengthStream(header.Value());
                     contentLengthStream >> *contentLength;
                 }
                 else
                     httpClient.observer->HeaderAvailable(header);
             }
             else if (headerBuffer.full())
                 SetError();
         }
     }
ParseStatusLine()
void services::HttpClientImpl::HttpResponseParser::ParseStatusLine (infra::StreamReaderWithRewinding & reader) private
Definition at line 340 of file HttpClientImpl.cpp.
References infra::InputStream::Available(), infra::BoundedStringBase< T >::find_first_of(), services::HttpClientImpl::headerBuffer, services::HttpStatusCodeFromString(), infra::BoundedStringBase< T >::max_size(), infra::BoundedStringBase< char >::npos, infra::BoundedStringBase< T >::resize(), infra::StreamReaderWithRewinding::Rewind(), infra::BoundedStringBase< T >::substr(), and infra::Tokenizer::Token().
     {
         infra::TextInputStream::WithErrorPolicy stream(reader);
         headerBuffer.resize(std::min(headerBuffer.max_size(), stream.Available()));
         stream >> headerBuffer;
         auto crlfPos = headerBuffer.find_first_of(crlf);
         if (crlfPos != infra::BoundedString::npos)
         {
             auto statusLine = headerBuffer.substr(0, crlfPos);
             reader.Rewind(statusLine.size() + crlf.size());
             infra::Tokenizer tokenizer(statusLine, ' ');
             auto versionValid = HttpVersionValid(tokenizer.Token(0));
             auto statusCode = HttpStatusCodeFromString(tokenizer.Token(1));
             if (versionValid && statusCode)
                 httpClient.StatusAvailable(*statusCode, statusLine);
             else
                 SetError();
             statusParsed = true;
         }
     }
SetError()
void services::HttpClientImpl::HttpResponseParser::SetError () private
Definition at line 418 of file HttpClientImpl.cpp.
     {
         done = true;
         error = true;
     }
Member Data Documentation
contentLength
infra::Optional<uint32_t> services::HttpClientImpl::HttpResponseParser::contentLength private
Definition at line 111 of file HttpClientImpl.hpp.
done
bool services::HttpClientImpl::HttpResponseParser::done = false private
Definition at line 108 of file HttpClientImpl.hpp.
error
bool services::HttpClientImpl::HttpResponseParser::error = false private
Definition at line 109 of file HttpClientImpl.hpp.
headerBuffer
infra::BoundedString& services::HttpClientImpl::HttpResponseParser::headerBuffer private
Definition at line 107 of file HttpClientImpl.hpp.
httpClient
HttpClientImpl& services::HttpClientImpl::HttpResponseParser::httpClient private
Definition at line 106 of file HttpClientImpl.hpp.
statusParsed
bool services::HttpClientImpl::HttpResponseParser::statusParsed = false private
Definition at line 110 of file HttpClientImpl.hpp.
The documentation for this class was generated from the following files:
HttpClientImpl.hpp
HttpClientImpl.cpp