EMil: TestFlashRegion.cpp File Reference
TestFlashRegion.cpp File Reference
Classes
class FlashRegionTest
Functions
TEST_F (FlashRegionTest, Construct)
TEST_F (FlashRegionTest, WriteBuffer)
TEST_F (FlashRegionTest, WriteBufferAtEnd)
TEST_F (FlashRegionTest, ReadBuffer)
TEST_F (FlashRegionTest, ReadBufferAtEnd)
TEST_F (FlashRegionTest, EraseSector)
TEST_F (FlashRegionTest, EraseSectors)
Function Documentation
TEST_F() [1/7]
TEST_F (FlashRegionTest , Construct)
Definition at line 24 of file TestFlashRegion.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(2, region->NumberOfSectors());
     EXPECT_EQ(3, region->SizeOfSector(0));
     EXPECT_EQ(4, region->SizeOfSector(1));
 }
TEST_F() [2/7]
TEST_F (FlashRegionTest , WriteBuffer)
Definition at line 31 of file TestFlashRegion.cpp.
References infra::emptyFunction, and EXPECT_EQ().
 {
     region->WriteBuffer(std::vector<uint8_t>{ 0x01 }, region->AddressOfSector(0), infra::emptyFunction);
     EXPECT_EQ((std::vector<uint8_t>{ 0x01, 0xff, 0xff }), flashStub.sectors[2]);
 }
TEST_F() [3/7]
TEST_F (FlashRegionTest , WriteBufferAtEnd)
Definition at line 37 of file TestFlashRegion.cpp.
References infra::emptyFunction, and EXPECT_EQ().
 {
     region->WriteBuffer(std::vector<uint8_t>{ 0x01 }, region->AddressOfSector(1) + 3, infra::emptyFunction);
     EXPECT_EQ((std::vector<uint8_t>{ 0xff, 0xff, 0xff, 0x01 }), flashStub.sectors[3]);
 }
TEST_F() [4/7]
TEST_F (FlashRegionTest , ReadBuffer)
Definition at line 43 of file TestFlashRegion.cpp.
References infra::emptyFunction, EXPECT_EQ(), and infra::MakeByteRange().
 {
     flashStub.sectors[2] = std::vector<uint8_t>{ 0x01, 0xff, 0xff };
     uint8_t buffer{ 0xff };
     region->ReadBuffer(infra::MakeByteRange(buffer), region->AddressOfSector(0), infra::emptyFunction);
     EXPECT_EQ(0x01, buffer);
 }
TEST_F() [5/7]
TEST_F (FlashRegionTest , ReadBufferAtEnd)
Definition at line 51 of file TestFlashRegion.cpp.
References infra::emptyFunction, EXPECT_EQ(), and infra::MakeByteRange().
 {
     flashStub.sectors[3] = std::vector<uint8_t>{ 0xff, 0xff, 0xff, 0x01 };
     uint8_t buffer{ 0xff };
     region->ReadBuffer(infra::MakeByteRange(buffer), region->AddressOfSector(1) + 3, infra::emptyFunction);
     EXPECT_EQ(0x01, buffer);
 }
TEST_F() [6/7]
TEST_F (FlashRegionTest , EraseSector)
Definition at line 59 of file TestFlashRegion.cpp.
References infra::emptyFunction, and EXPECT_EQ().
 {
     flashStub.sectors[3] = std::vector<uint8_t>{ 0x01, 0x02, 0x03, 0x04 };
     region->EraseSector(1, infra::emptyFunction);
     EXPECT_EQ((std::vector<uint8_t>{ 0xff, 0xff, 0xff, 0xff }), flashStub.sectors[3]);
 }
TEST_F() [7/7]
TEST_F (FlashRegionTest , EraseSectors)
Definition at line 66 of file TestFlashRegion.cpp.
References infra::emptyFunction, and EXPECT_EQ().
 {
     flashStub.sectors[2] = std::vector<uint8_t>{ 0x01, 0x02, 0x03 };
     flashStub.sectors[3] = std::vector<uint8_t>{ 0x01, 0x02, 0x03, 0x04 };
     region->EraseSectors(0, 2, infra::emptyFunction);
     EXPECT_EQ((std::vector<uint8_t>{ 0xff, 0xff, 0xff }), flashStub.sectors[2]);
     EXPECT_EQ((std::vector<uint8_t>{ 0xff, 0xff, 0xff, 0xff }), flashStub.sectors[3]);
 }