EMil: services::FlashQuadSpi Class Reference
services::FlashQuadSpi Class Reference abstract
#include <FlashQuadSpi.hpp>
Public Member Functions
FlashQuadSpi (hal::QuadSpi &spi, uint32_t numberOfSectors, uint8_t commandPageProgram)
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::FlashHomogeneous
FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Static Public Attributes
static const uint32_t sizeBlock = 65536
static const uint32_t sizeSector = 4096
static const uint32_t sizePage = 256
Protected Member Functions
void WriteBufferSequence ()
virtual void PageProgram ()
infra::BoundedVector< uint8_t >::WithMaxSize< 4 > ConvertAddress (uint32_t address) const
virtual void WriteEnable ()=0
virtual void EraseSomeSectors (uint32_t endIndex)=0
virtual void HoldWhileWriteInProgress ()=0
Protected Member Functions inherited from hal::FlashHomogeneous
~FlashHomogeneous ()=default
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Protected Attributes
hal::QuadSpi & spi
infra::Sequencer sequencer
infra::AutoResetFunction< void()> onDone
infra::ConstByteRange buffer
uint32_t address = 0
uint32_t sectorIndex = 0
uint8_t commandPageProgram
Detailed Description
Definition at line 12 of file FlashQuadSpi.hpp.
Constructor & Destructor Documentation
FlashQuadSpi()
services::FlashQuadSpi::FlashQuadSpi (hal::QuadSpi & spi, uint32_t numberOfSectors, uint8_t commandPageProgram)
Definition at line 6 of file FlashQuadSpi.cpp.
         : hal::FlashHomogeneous(numberOfSectors, sizeSector)
         , spi(spi)
         , commandPageProgram(commandPageProgram)
     {}
Member Function Documentation
ConvertAddress()
infra::BoundedVector< uint8_t >::WithMaxSize< 4 > services::FlashQuadSpi::ConvertAddress (uint32_t address) const protected
Definition at line 60 of file FlashQuadSpi.cpp.
References address, and hal::QuadSpi::AddressToVector().
Referenced by PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), and services::FlashQuadSpiMicronN25q::SendEraseSubSector().
     {
         return hal::QuadSpi::AddressToVector(address, 3);
     }
EraseSectors()
void services::FlashQuadSpi::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 21 of file FlashQuadSpi.cpp.
References infra::Sequencer::EndWhile(), EraseSomeSectors(), infra::Sequencer::Execute(), HoldWhileWriteInProgress(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::Sequencer::Load(), onDone, infra::EventDispatcherWorker::Schedule(), sectorIndex, sequencer, infra::Sequencer::Step(), infra::Sequencer::While(), and WriteEnable().
     {
         this->onDone = onDone;
         sectorIndex = beginIndex;
         sequencer.Load([this, endIndex]()
         {
             sequencer.While([this, endIndex]() { return sectorIndex != endIndex; });
             sequencer.Step([this]() { WriteEnable(); });
             sequencer.Step([this, endIndex]() { EraseSomeSectors(endIndex); });
             sequencer.Step([this]() { HoldWhileWriteInProgress(); });
             sequencer.EndWhile();
             sequencer.Execute([this]() { infra::EventDispatcher::Instance().Schedule([this]() { this->onDone(); }); });
         });
     }
EraseSomeSectors()
virtual void services::FlashQuadSpi::EraseSomeSectors (uint32_t endIndex) protected pure virtual
Implemented in services::FlashQuadSpiCypressFll, services::FlashQuadSpiMicronN25q, and services::FlashQuadSpiSingleSpeed.
Referenced by EraseSectors().
HoldWhileWriteInProgress()
virtual void services::FlashQuadSpi::HoldWhileWriteInProgress () protected pure virtual
Implemented in services::FlashQuadSpiCypressFll, services::FlashQuadSpiMicronN25q, and services::FlashQuadSpiSingleSpeed.
Referenced by EraseSectors(), and WriteBufferSequence().
PageProgram()
void services::FlashQuadSpi::PageProgram () protected virtual
Reimplemented in services::FlashQuadSpiSingleSpeed.
Definition at line 49 of file FlashQuadSpi.cpp.
References address, hal::Flash::AddressOffsetInSector(), buffer, commandPageProgram, infra::Sequencer::Continue(), ConvertAddress(), infra::Head(), infra::MakeOptional(), infra::MemoryRange< T >::pop_front(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), sequencer, infra::MemoryRange< T >::size(), sizePage, and spi.
Referenced by WriteBufferSequence().
     {
         hal::QuadSpi::Header pageProgramHeader{ infra::MakeOptional(commandPageProgram), ConvertAddress(address), {}, 0 };
         infra::ConstByteRange currentBuffer = infra::Head(buffer, sizePage - AddressOffsetInSector(address) % sizePage);
         buffer.pop_front(currentBuffer.size());
         address += currentBuffer.size();
         spi.SendData(pageProgramHeader, currentBuffer, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
WriteBuffer()
void services::FlashQuadSpi::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 12 of file FlashQuadSpi.cpp.
References address, buffer, onDone, and WriteBufferSequence().
     {
         this->onDone = onDone;
         this->buffer = buffer;
         this->address = address;
         WriteBufferSequence();
     }
WriteBufferSequence()
void services::FlashQuadSpi::WriteBufferSequence () protected
Definition at line 36 of file FlashQuadSpi.cpp.
References infra::MemoryRange< T >::empty(), infra::Sequencer::EndWhile(), infra::Sequencer::Execute(), HoldWhileWriteInProgress(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::Sequencer::Load(), onDone, PageProgram(), infra::EventDispatcherWorker::Schedule(), sequencer, infra::Sequencer::Step(), infra::Sequencer::While(), and WriteEnable().
Referenced by WriteBuffer().
     {
         sequencer.Load([this]()
         {
             sequencer.While([this]() { return !this->buffer.empty(); });
             sequencer.Step([this]() { WriteEnable(); });
             sequencer.Step([this]() { PageProgram(); });
             sequencer.Step([this]() { HoldWhileWriteInProgress(); });
             sequencer.EndWhile();
             sequencer.Execute([this]() { infra::EventDispatcher::Instance().Schedule([this]() { this->onDone(); }); });
         });
     }
WriteEnable()
virtual void services::FlashQuadSpi::WriteEnable () protected pure virtual
Implemented in services::FlashQuadSpiCypressFll, services::FlashQuadSpiMicronN25q, and services::FlashQuadSpiSingleSpeed.
Referenced by EraseSectors(), and WriteBufferSequence().
Member Data Documentation
address
uint32_t services::FlashQuadSpi::address = 0 protected
Definition at line 40 of file FlashQuadSpi.hpp.
Referenced by ConvertAddress(), PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiCypressFll::ReadBuffer(), and WriteBuffer().
buffer
infra::ConstByteRange services::FlashQuadSpi::buffer protected
Definition at line 39 of file FlashQuadSpi.hpp.
Referenced by PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiCypressFll::ReadBuffer(), and WriteBuffer().
commandPageProgram
uint8_t services::FlashQuadSpi::commandPageProgram protected
Definition at line 42 of file FlashQuadSpi.hpp.
Referenced by PageProgram().
onDone
infra::AutoResetFunction<void()> services::FlashQuadSpi::onDone protected
Definition at line 38 of file FlashQuadSpi.hpp.
Referenced by EraseSectors(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiCypressFll::ReadBuffer(), services::FlashQuadSpiCypressFll::SwitchToSingleSpeed(), WriteBuffer(), and WriteBufferSequence().
sectorIndex
uint32_t services::FlashQuadSpi::sectorIndex = 0 protected
Definition at line 41 of file FlashQuadSpi.hpp.
Referenced by EraseSectors(), services::FlashQuadSpiSingleSpeed::EraseSomeSectors(), services::FlashQuadSpiMicronN25q::EraseSomeSectors(), services::FlashQuadSpiCypressFll::EraseSomeSectors(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), and services::FlashQuadSpiCypressFll::SendEraseSector().
sequencer
infra::Sequencer services::FlashQuadSpi::sequencer protected
Definition at line 37 of file FlashQuadSpi.hpp.
Referenced by EraseSectors(), services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll(), services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q(), services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress(), services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress(), services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress(), PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiMicronN25q::SendEraseBulk(), services::FlashQuadSpiSingleSpeed::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToQuadSpeed(), WriteBufferSequence(), services::FlashQuadSpiSingleSpeed::WriteEnable(), services::FlashQuadSpiMicronN25q::WriteEnable(), services::FlashQuadSpiCypressFll::WriteEnable(), and services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed().
sizeBlock
const uint32_t services::FlashQuadSpi::sizeBlock = 65536 static
Definition at line 16 of file FlashQuadSpi.hpp.
Referenced by services::FlashQuadSpiSingleSpeed::EraseSomeSectors(), services::FlashQuadSpiMicronN25q::EraseSomeSectors(), and services::FlashQuadSpiCypressFll::EraseSomeSectors().
sizePage
const uint32_t services::FlashQuadSpi::sizePage = 256 static
Definition at line 18 of file FlashQuadSpi.hpp.
Referenced by PageProgram(), and services::FlashQuadSpiSingleSpeed::PageProgram().
sizeSector
const uint32_t services::FlashQuadSpi::sizeSector = 4096 static
Definition at line 17 of file FlashQuadSpi.hpp.
Referenced by services::FlashQuadSpiSingleSpeed::EraseSomeSectors(), services::FlashQuadSpiMicronN25q::EraseSomeSectors(), and services::FlashQuadSpiCypressFll::EraseSomeSectors().
spi
hal::QuadSpi& services::FlashQuadSpi::spi protected
Definition at line 36 of file FlashQuadSpi.hpp.
Referenced by services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress(), services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress(), services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress(), PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiCypressFll::ReadBuffer(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiMicronN25q::SendEraseBulk(), services::FlashQuadSpiSingleSpeed::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToSingleSpeed(), services::FlashQuadSpiSingleSpeed::WriteEnable(), services::FlashQuadSpiMicronN25q::WriteEnable(), services::FlashQuadSpiCypressFll::WriteEnable(), and services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed().
The documentation for this class was generated from the following files:
FlashQuadSpi.hpp
FlashQuadSpi.cpp