EMil: services::ConnectionSerial::StateSendingUpdate Class Reference
services::ConnectionSerial::StateSendingUpdate Class Reference
Public Member Functions
StateSendingUpdate (ConnectionSerial &connection)
Public Member Functions inherited from services::ConnectionSerial::StateSending
StateSending (ConnectionSerial &connection)
virtual void EvaluatePendingSend () override
virtual void Reset () override
Public Member Functions inherited from services::ConnectionSerial::StateConnected
StateConnected (ConnectionSerial &connection)
virtual void AckReceived () override
virtual void SizeRequestReceived () override
virtual void SizeResponseRequestReceived (size_t size) override
virtual void SizeResponseReceived (size_t size) override
virtual size_t ContentReceived (infra::ConstByteRange receivedRange) override
virtual void SizeUpdateReceived (size_t size) override
virtual void AccumulateWindowUpdateSize (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::State
State (ConnectionSerial &connection)
virtual ~State ()=default
Private Member Functions
void SendUpdate ()
Private Attributes
MessageHeader updateMsg = MessageHeader(MessageType::SizeUpdate)
Additional Inherited Members
Protected Member Functions inherited from services::ConnectionSerial::StateSending
void GoIdle ()
Protected Member Functions inherited from services::ConnectionSerial::StateConnected
bool IsEscapedByte (uint8_t byte) const
Protected Attributes inherited from services::ConnectionSerial::StateSending
bool resetAfterSend = false
Protected Attributes inherited from services::ConnectionSerial::StateConnected
infra::ByteRange & sendBuffer
Protected Attributes inherited from services::ConnectionSerial::State
ConnectionSerial & connection
hal::SerialCommunication & serialCommunication
Detailed Description
Definition at line 250 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
StateSendingUpdate()
services::ConnectionSerial::StateSendingUpdate::StateSendingUpdate (ConnectionSerial & connection)
Definition at line 659 of file ConnectionSerial.cpp.
References SendUpdate().
         : StateSending(connection)
     {
         SendUpdate();
     }
Member Function Documentation
SendUpdate()
void services::ConnectionSerial::StateSendingUpdate::SendUpdate () private
Definition at line 665 of file ConnectionSerial.cpp.
References services::ConnectionSerial::MessageHeader::HeaderSize, infra::none, services::ConnectionSerial::StateConnected::Reset(), hal::SerialCommunication::SendData(), and services::ConnectionSerial::serialCommunication.
Referenced by StateSendingUpdate().
     {
         connection.updateInProgress = true;
         connection.peerBufferSize -= MessageHeader::HeaderSize;
         updateMsg.SetSize(*connection.accumulatedWindowSizeUpdate);
         *connection.accumulatedWindowSizeUpdate = 0;
         serialCommunication.SendData(updateMsg.Range(), [this]()
         {
             connection.updateInProgress = false;
             if (*connection.accumulatedWindowSizeUpdate == 0)
                 connection.accumulatedWindowSizeUpdate = infra::none;
             if (!resetAfterSend)
                 GoIdle();
             else
                 StateConnected::Reset();
         });
     }
Member Data Documentation
updateMsg
MessageHeader services::ConnectionSerial::StateSendingUpdate::updateMsg = MessageHeader(MessageType::SizeUpdate) private
Definition at line 260 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp