EMil: services::HttpClientJson Class Reference
services::HttpClientJson Class Reference abstract
#include <HttpClientJson.hpp>
Classes
struct ConnectionInfo
Public Types
using JsonParserCreatorBase = infra::CreatorBase< infra::JsonStreamingObjectParser, void(infra::JsonObjectVisitor &)>
template<std::size_t MaxTagLength, std::size_t MaxValueLength, std::size_t MaxObjectNesting>
using JsonParserCreator = JsonParserCreatorBase::WithCreator< infra::JsonStreamingObjectParser::WithBuffers< MaxTagLength, MaxValueLength, MaxObjectNesting > >
Public Member Functions
HttpClientJson (infra::BoundedString url, const ConnectionInfo &connectionInfo)
~HttpClientJson ()
void Cancel (const infra::Function< void()> &onDone)
Protected Member Functions
virtual infra::JsonObjectVisitor & TopJsonObjectVisitor ()=0
virtual void Connected () override
virtual void ClosingConnection () override
virtual void StatusAvailable (services::HttpStatusCode statusCode) override
virtual void HeaderAvailable (services::HttpHeader header) override
virtual void BodyAvailable (infra::SharedPtr< infra::StreamReader > &&reader) override
virtual void Established () override
Protected Member Functions inherited from services::HttpClientBasic
void Connect ()
void Connect (infra::BoundedString url)
void Close ()
void ContentError ()
infra::BoundedString Url () const
virtual infra::BoundedString Path () const
virtual services::HttpHeaders Headers () const
virtual void Done ()=0
virtual void Error (bool intermittentFailure)=0
virtual void BodyComplete () override
HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector &httpClientConnector)
HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector &httpClientConnector, infra::Duration timeoutDuration)
void Cancel (const infra::Function< void()> &onDone)
Protected Member Functions inherited from services::HttpClientObserver
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer)
Protected Member Functions inherited from infra::SingleObserver< HttpClientObserver, HttpClient >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Private Attributes
JsonParserCreatorBase & jsonParserCreator
infra::Optional< infra::ProxyCreator< JsonParserCreatorBase & > > jsonParser
infra::SharedPtr< infra::StreamReader > readerPtr
bool * destructedIndication = nullptr
Detailed Description
Definition at line 11 of file HttpClientJson.hpp.
Member Typedef Documentation
JsonParserCreator
template<std::size_t MaxTagLength, std::size_t MaxValueLength, std::size_t MaxObjectNesting> using services::HttpClientJson::JsonParserCreator = JsonParserCreatorBase::WithCreator<infra::JsonStreamingObjectParser::WithBuffers<MaxTagLength, MaxValueLength, MaxObjectNesting> >
Definition at line 18 of file HttpClientJson.hpp.
JsonParserCreatorBase
using services::HttpClientJson::JsonParserCreatorBase = infra::CreatorBase<infra::JsonStreamingObjectParser, void(infra::JsonObjectVisitor&)>
Definition at line 15 of file HttpClientJson.hpp.
Constructor & Destructor Documentation
HttpClientJson()
services::HttpClientJson::HttpClientJson (infra::BoundedString url, const ConnectionInfo & connectionInfo)
Definition at line 5 of file HttpClientJson.cpp.
         : services::HttpClientBasic(url, connectionInfo.port, connectionInfo.httpClientConnector)
         , jsonParserCreator(connectionInfo.jsonParserCreator)
     {}
~HttpClientJson()
services::HttpClientJson::~HttpClientJson ()
Definition at line 10 of file HttpClientJson.cpp.
References destructedIndication.
     {
         if (destructedIndication != nullptr)
             *destructedIndication = true;
     }
Member Function Documentation
BodyAvailable()
void services::HttpClientJson::BodyAvailable (infra::SharedPtr< infra::StreamReader > && reader) override protected virtual
Implements services::HttpClientObserver.
Definition at line 45 of file HttpClientJson.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), destructedIndication, infra::InputStream::Empty(), jsonParser, infra::noFail, infra::none, and readerPtr.
     {
         bool destructed = false;
         destructedIndication = &destructed;
         readerPtr = std::move(reader);
         infra::DataInputStream::WithErrorPolicy stream(*readerPtr, infra::noFail);
         while (!destructed && jsonParser != infra::none && !stream.Empty())
             (*jsonParser)->Feed(infra::ByteRangeAsString(stream.ContiguousRange()));
         if (!destructed)
         {
             readerPtr = nullptr;
             destructedIndication = nullptr;
         }
     }
Cancel()
void services::HttpClientJson::Cancel (const infra::Function< void()> & onDone)
Definition at line 16 of file HttpClientJson.cpp.
References services::HttpClientBasic::Cancel().
     {
         HttpClientBasic::Cancel(onDone);
     }
ClosingConnection()
void services::HttpClientJson::ClosingConnection () override protected virtual
Reimplemented from services::HttpClientBasic.
Definition at line 26 of file HttpClientJson.cpp.
References services::HttpClientBasic::ClosingConnection(), jsonParser, infra::none, and readerPtr.
     {
         readerPtr = nullptr;
         jsonParser = infra::none;
         services::HttpClientBasic::ClosingConnection();
     }
Connected()
void services::HttpClientJson::Connected () override protected virtual
Reimplemented from services::HttpClientObserver.
Definition at line 21 of file HttpClientJson.cpp.
References services::HttpClientBasic::Headers(), services::HttpClientBasic::Path(), and infra::SingleObserver< HttpClientObserver, HttpClient >::Subject().
     {
         HttpClientObserver::Subject().Get(Path(), Headers());
     }
Established()
void services::HttpClientJson::Established () override protected virtual
Reimplemented from services::HttpClientBasic.
Definition at line 64 of file HttpClientJson.cpp.
References jsonParser, jsonParserCreator, and TopJsonObjectVisitor().
     {
         jsonParser.Emplace(jsonParserCreator, TopJsonObjectVisitor());
     }
HeaderAvailable()
void services::HttpClientJson::HeaderAvailable (services::HttpHeader header) override protected virtual
Implements services::HttpClientObserver.
Definition at line 39 of file HttpClientJson.cpp.
References services::HttpClientBasic::ContentError(), services::HttpHeader::Field(), and services::HttpHeader::Value().
     {
         if (header.Field() == "content-type" && header.Value() != "application/json")
             ContentError();
     }
StatusAvailable()
void services::HttpClientJson::StatusAvailable (services::HttpStatusCode statusCode) override protected virtual
Implements services::HttpClientObserver.
Definition at line 33 of file HttpClientJson.cpp.
References services::HttpClientBasic::ContentError(), and services::OK.
     {
         if (statusCode != services::HttpStatusCode::OK)
             ContentError();
     }
TopJsonObjectVisitor()
virtual infra::JsonObjectVisitor& services::HttpClientJson::TopJsonObjectVisitor () protected pure virtual
Referenced by Established().
Member Data Documentation
destructedIndication
bool* services::HttpClientJson::destructedIndication = nullptr private
Definition at line 50 of file HttpClientJson.hpp.
Referenced by BodyAvailable(), and ~HttpClientJson().
jsonParser
infra::Optional<infra::ProxyCreator<JsonParserCreatorBase&> > services::HttpClientJson::jsonParser private
Definition at line 47 of file HttpClientJson.hpp.
Referenced by BodyAvailable(), ClosingConnection(), and Established().
jsonParserCreator
JsonParserCreatorBase& services::HttpClientJson::jsonParserCreator private
Definition at line 46 of file HttpClientJson.hpp.
Referenced by Established().
readerPtr
infra::SharedPtr<infra::StreamReader> services::HttpClientJson::readerPtr private
Definition at line 49 of file HttpClientJson.hpp.
Referenced by BodyAvailable(), and ClosingConnection().
The documentation for this class was generated from the following files:
HttpClientJson.hpp
HttpClientJson.cpp