EMil: HttpClientJsonTest Class Reference
HttpClientJsonTest Class Reference
Public Member Functions
HttpClientJsonTest ()
~HttpClientJsonTest ()
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< services::HttpClientMock > httpClient
testing::StrictMock< services::HttpClientConnectorMock > httpClientConnector
services::HttpClientObserverFactory * httpClientObserverFactory = nullptr
infra::Execute execute { [this]() { EXPECT_CALL(httpClientConnector, Connect(testing::_)).WillOnce(infra::SaveRef<0>(&httpClientObserverFactory)); } }
infra::BoundedString::WithStorage< 64 > url { "https://hostname/path" }
services::HttpClientJson::JsonParserCreator< 32, 64, 5 > jsonParserCreator
testing::StrictMock< HttpClientJsonMock > controller { url, services::HttpClientJson::ConnectionInfo{ jsonParserCreator, 443, httpClientConnector } }
testing::StrictMock< infra::MockCallback< void()> > onStopped
testing::StrictMock< infra::JsonObjectVisitorMock > jsonObjectVisitor
std::array< services::HttpHeader, 2 > headersIn { { { "api-version", "1" }, { "authorization", "Bearer xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx" } } }
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 26 of file TestHttpClientJson.cpp.
Constructor & Destructor Documentation
HttpClientJsonTest()
HttpClientJsonTest::HttpClientJsonTest () inline
Definition at line 31 of file TestHttpClientJson.cpp.
References EXPECT_EQ(), services::HttpClientObserverFactory::Hostname(), httpClientObserverFactory, and services::HttpClientObserverFactory::Port().
     {
         EXPECT_EQ("hostname", httpClientObserverFactory->Hostname());
         EXPECT_EQ(443, httpClientObserverFactory->Port());
     }
~HttpClientJsonTest()
HttpClientJsonTest::~HttpClientJsonTest () inline
Definition at line 37 of file TestHttpClientJson.cpp.
References httpClient.
     {
         httpClient.observer = nullptr;
     }
Member Data Documentation
controller
testing::StrictMock<HttpClientJsonMock> HttpClientJsonTest::controller { url, services::HttpClientJson::ConnectionInfo{ jsonParserCreator, 443, httpClientConnector } }
Definition at line 48 of file TestHttpClientJson.cpp.
execute
infra::Execute HttpClientJsonTest::execute { [this]() { EXPECT_CALL(httpClientConnector, Connect(testing::_)).WillOnce(infra::SaveRef<0>(&httpClientObserverFactory)); } }
Definition at line 45 of file TestHttpClientJson.cpp.
headersIn
std::array<services::HttpHeader, 2> HttpClientJsonTest::headersIn { { { "api-version", "1" }, { "authorization", "Bearer xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx" } } }
Definition at line 52 of file TestHttpClientJson.cpp.
httpClient
testing::StrictMock<services::HttpClientMock> HttpClientJsonTest::httpClient
Definition at line 42 of file TestHttpClientJson.cpp.
Referenced by ~HttpClientJsonTest().
httpClientConnector
testing::StrictMock<services::HttpClientConnectorMock> HttpClientJsonTest::httpClientConnector
Definition at line 43 of file TestHttpClientJson.cpp.
httpClientObserverFactory
services::HttpClientObserverFactory* HttpClientJsonTest::httpClientObserverFactory = nullptr
Definition at line 44 of file TestHttpClientJson.cpp.
Referenced by HttpClientJsonTest().
jsonObjectVisitor
testing::StrictMock<infra::JsonObjectVisitorMock> HttpClientJsonTest::jsonObjectVisitor
Definition at line 51 of file TestHttpClientJson.cpp.
jsonParserCreator
services::HttpClientJson::JsonParserCreator<32, 64, 5> HttpClientJsonTest::jsonParserCreator
Definition at line 47 of file TestHttpClientJson.cpp.
onStopped
testing::StrictMock<infra::MockCallback<void()> > HttpClientJsonTest::onStopped
Definition at line 49 of file TestHttpClientJson.cpp.
url
infra::BoundedString::WithStorage<64> HttpClientJsonTest::url { "https://hostname/path" }
Definition at line 46 of file TestHttpClientJson.cpp.
The documentation for this class was generated from the following file:
TestHttpClientJson.cpp