EMil: services::ConnectorWin Class Reference
services::ConnectorWin Class Reference
#include <ConnectionWin.hpp>
Public Member Functions
ConnectorWin (EventDispatcherWithNetwork &network, services::ClientConnectionObserverFactory &factory)
~ConnectorWin ()
void Connected ()
void Failed ()
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectorWin >
SharedPtr< ConnectorWin > SharedFromThis ()
SharedPtr< const ConnectorWin > SharedFromThis () const
WeakPtr< ConnectorWin > WeakFromThis ()
WeakPtr< const ConnectorWin > WeakFromThis () const
void MakeShared (SharedPtr< ConnectorWin > sharedPtr)
Private Attributes
EventDispatcherWithNetwork & network
services::ClientConnectionObserverFactory & factory
SOCKET connectSocket
WSAEVENT event = WSACreateEvent()
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectorWin >
using EnableSharedFromThisType = ConnectorWin
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectorWin >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 105 of file ConnectionWin.hpp.
Constructor & Destructor Documentation
ConnectorWin()
services::ConnectorWin::ConnectorWin (EventDispatcherWithNetwork & network, services::ClientConnectionObserverFactory & factory)
Definition at line 243 of file ConnectionWin.cpp.
References services::ClientConnectionObserverFactory::Address(), services::connect, connectSocket, event, factory, infra::Variant< T >::Get(), and services::ClientConnectionObserverFactory::Port().
         : network(network)
         , factory(factory)
     {
         auto address = factory.Address().Get<services::IPv4Address>();
         connectSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
         assert(connectSocket != INVALID_SOCKET);
         int result = WSAEventSelect(connectSocket, event, FD_CONNECT);
         assert(result == 0);
         ULONG nonBlock = 1;
         if (ioctlsocket(connectSocket, FIONBIO, &nonBlock) == SOCKET_ERROR)
             std::abort();
         sockaddr_in saddress = {};
         saddress.sin_family = AF_INET;
         saddress.sin_addr.s_net = address[0];
         saddress.sin_addr.s_host = address[1];
         saddress.sin_addr.s_lh = address[2];
         saddress.sin_addr.s_impno = address[3];
         saddress.sin_port = htons(factory.Port());
         if (connect(connectSocket, reinterpret_cast<sockaddr*>(&saddress), sizeof(saddress)) == SOCKET_ERROR)
         {
             if (GetLastError() != WSAEWOULDBLOCK)
                 std::abort();
         }
     }
~ConnectorWin()
services::ConnectorWin::~ConnectorWin ()
Definition at line 272 of file ConnectionWin.cpp.
References event.
     {
         BOOL result = WSACloseEvent(event);
         assert(result == TRUE);
     }
Member Function Documentation
Connected()
void services::ConnectorWin::Connected ()
Definition at line 278 of file ConnectionWin.cpp.
References services::ClientConnectionObserverFactory::ConnectionEstablished(), connectSocket, services::EventDispatcherWithNetwork::DeregisterConnector(), factory, network, and infra::EnableSharedFromThis< ConnectorWin >::SharedFromThis().
     {
         infra::WeakPtr<ConnectorWin> self = SharedFromThis();
         infra::SharedPtr<ConnectionWin> connection = infra::MakeSharedOnHeap<ConnectionWin>(network, connectSocket);
         factory.ConnectionEstablished([connection](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             if (connectionObserver)
                 connection->SetObserver(connectionObserver);
         });
         network.DeregisterConnector(*this);
     }
Failed()
void services::ConnectorWin::Failed ()
Definition at line 291 of file ConnectionWin.cpp.
References services::ClientConnectionObserverFactory::ConnectionFailed(), services::EventDispatcherWithNetwork::DeregisterConnector(), factory, network, and infra::EnableSharedFromThis< ConnectorWin >::SharedFromThis().
     {
         infra::WeakPtr<ConnectorWin> self = SharedFromThis();
         factory.ConnectionFailed(services::ClientConnectionObserverFactory::ConnectFailReason::refused);
         network.DeregisterConnector(*this);
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 117 of file ConnectionWin.hpp.
Member Data Documentation
connectSocket
SOCKET services::ConnectorWin::connectSocket private
Definition at line 121 of file ConnectionWin.hpp.
Referenced by Connected(), and ConnectorWin().
event
WSAEVENT services::ConnectorWin::event = WSACreateEvent() private
Definition at line 122 of file ConnectionWin.hpp.
Referenced by ConnectorWin(), and ~ConnectorWin().
factory
services::ClientConnectionObserverFactory& services::ConnectorWin::factory private
Definition at line 120 of file ConnectionWin.hpp.
Referenced by Connected(), ConnectorWin(), and Failed().
network
EventDispatcherWithNetwork& services::ConnectorWin::network private
Definition at line 119 of file ConnectionWin.hpp.
Referenced by Connected(), and Failed().
The documentation for this class was generated from the following files:
ConnectionWin.hpp
ConnectionWin.cpp