EMil: hal::OutputPin Class Reference
hal::OutputPin Class Reference
#include <Gpio.hpp>
Public Member Functions
OutputPin (GpioPin &pin, bool startState=false)
OutputPin (const OutputPin &other)=delete
OutputPin & operator= (const OutputPin &other)=delete
~OutputPin ()
void Set (bool value)
bool GetOutputLatch () const
Private Attributes
GpioPin & pin
Detailed Description
Definition at line 68 of file Gpio.hpp.
Constructor & Destructor Documentation
OutputPin() [1/2]
hal::OutputPin::OutputPin (GpioPin & pin, bool startState = false) explicit
Definition at line 33 of file Gpio.cpp.
References hal::GpioPin::Config(), hal::output, and pin.
         : pin(pin)
     {
         pin.Config(PinConfigType::output, startState);
     }
OutputPin() [2/2]
hal::OutputPin::OutputPin (const OutputPin & other) delete
~OutputPin()
hal::OutputPin::~OutputPin ()
Definition at line 39 of file Gpio.cpp.
References pin, and hal::GpioPin::ResetConfig().
     {
         pin.ResetConfig();
     }
Member Function Documentation
GetOutputLatch()
bool hal::OutputPin::GetOutputLatch () const
Definition at line 49 of file Gpio.cpp.
References hal::GpioPin::GetOutputLatch(), and pin.
     {
         return pin.GetOutputLatch();
     }
operator=()
OutputPin& hal::OutputPin::operator= (const OutputPin & other) delete
Set()
void hal::OutputPin::Set (bool value)
Definition at line 44 of file Gpio.cpp.
References pin, hal::GpioPin::Set(), and value.
Referenced by services::SpiMasterWithChipSelect::EndSession(), services::SignalLed::OnTimer(), hal::ScopedHigh::ScopedHigh(), hal::ScopedLow::ScopedLow(), services::SynchronousSpiMasterWithChipSelect::SendAndReceive(), services::SpiMasterWithChipSelect::StartSession(), services::SynchronousSpiMasterWithChipSelect::SynchronousSpiMasterWithChipSelect(), hal::ScopedHigh::~ScopedHigh(), and hal::ScopedLow::~ScopedLow().
     {
         pin.Set(value);
     }
Member Data Documentation
pin
GpioPin& hal::OutputPin::pin private
Definition at line 80 of file Gpio.hpp.
Referenced by GetOutputLatch(), OutputPin(), Set(), and ~OutputPin().
The documentation for this class was generated from the following files:
Gpio.hpp
Gpio.cpp