EMil: infra::BoundedList< T > Class Template Reference
infra::BoundedList< T > Class Template Reference
#include <BoundedList.hpp>
Public Types
template<std::size_t Max>
using WithMaxSize = infra::WithStorage< BoundedList< T >, std::array< StaticStorage< detail::BoundedListNode< T > >, Max > >
using value_type = T
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
using iterator = detail::BoundedListIterator< T, T >
using const_iterator = detail::BoundedListIterator< const T, T >
using difference_type = typename std::iterator_traits< iterator >::difference_type
using size_type = std::size_t
Public Member Functions
BoundedList (const BoundedList &other)=delete
BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage)
BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, size_type n, const value_type &value=value_type())
template<class InputIterator >
BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, InputIterator first, InputIterator last)
BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, std::initializer_list< T > initializerList)
BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, const BoundedList &other)
BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, BoundedList &&other)
~BoundedList ()
BoundedList & operator= (const BoundedList &other)
BoundedList & operator= (BoundedList &&other)
void AssignFromStorage (const BoundedList &other)
void AssignFromStorage (BoundedList &&other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
size_type size () const
size_type max_size () const
bool empty () const
bool full () const
value_type & front ()
const value_type & front () const
value_type & back ()
const value_type & back () const
void push_front (const value_type &value)
void push_front (value_type &&value)
void pop_front ()
void push_back (const value_type &value)
void push_back (value_type &&value)
void pop_back ()
void insert (iterator position, const value_type &value)
void insert (iterator position, value_type &&value)
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void assign (size_type n, const value_type &value)
template<class InputIterator >
void move_from_range (InputIterator first, InputIterator last)
void erase (iterator position)
void erase_all_after (iterator position)
void remove (reference value)
void swap (BoundedList &other)
void clear ()
template<class... Args>
void emplace_front (Args &&... args)
template<class... Args>
void emplace_back (Args &&... args)
bool operator== (const BoundedList &other) const
bool operator!= (const BoundedList &other) const
bool operator< (const BoundedList &other) const
bool operator<= (const BoundedList &other) const
bool operator> (const BoundedList &other) const
bool operator>= (const BoundedList &other) const
Private Types
using NodeType = detail::BoundedListNode< T >
Private Member Functions
NodeType * AllocateNode ()
Private Attributes
infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T > > > storage
size_type numAllocated = 0
size_type numInitialized = 0
NodeType * firstNode = nullptr
NodeType * lastNode = nullptr
NodeType * freeList = nullptr
Detailed Description
template<class T>
class infra::BoundedList< T >
Definition at line 36 of file BoundedList.hpp.
Member Typedef Documentation
const_iterator
template<class T> using infra::BoundedList< T >::const_iterator = detail::BoundedListIterator<const T, T>
Definition at line 48 of file BoundedList.hpp.
const_pointer
template<class T> using infra::BoundedList< T >::const_pointer = const T*
Definition at line 46 of file BoundedList.hpp.
const_reference
template<class T> using infra::BoundedList< T >::const_reference = const T&
Definition at line 44 of file BoundedList.hpp.
difference_type
template<class T> using infra::BoundedList< T >::difference_type = typename std::iterator_traits<iterator>::difference_type
Definition at line 49 of file BoundedList.hpp.
iterator
template<class T> using infra::BoundedList< T >::iterator = detail::BoundedListIterator<T, T>
Definition at line 47 of file BoundedList.hpp.
NodeType
template<class T> using infra::BoundedList< T >::NodeType = detail::BoundedListNode<T> private
Definition at line 129 of file BoundedList.hpp.
pointer
template<class T> using infra::BoundedList< T >::pointer = T*
Definition at line 45 of file BoundedList.hpp.
reference
template<class T> using infra::BoundedList< T >::reference = T&
Definition at line 43 of file BoundedList.hpp.
size_type
template<class T> using infra::BoundedList< T >::size_type = std::size_t
Definition at line 50 of file BoundedList.hpp.
value_type
template<class T> using infra::BoundedList< T >::value_type = T
Definition at line 42 of file BoundedList.hpp.
WithMaxSize
template<class T> template<std::size_t Max> using infra::BoundedList< T >::WithMaxSize = infra::WithStorage<BoundedList<T>, std::array<StaticStorage<detail::BoundedListNode<T> >, Max> >
Definition at line 40 of file BoundedList.hpp.
Constructor & Destructor Documentation
BoundedList() [1/7]
template<class T> infra::BoundedList< T >::BoundedList (const BoundedList< T > & other) delete
BoundedList() [2/7]
template<class T> infra::BoundedList< T >::BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage) explicit
Definition at line 185 of file BoundedList.hpp.
         : storage(storage)
     {}
BoundedList() [3/7]
template<class T> infra::BoundedList< T >::BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, size_type n, const value_type & value = value_type())
Definition at line 190 of file BoundedList.hpp.
         : storage(storage)
     {
         assign(n, value);
     }
BoundedList() [4/7]
template<class T> template<class InputIterator > infra::BoundedList< T >::BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, InputIterator first, InputIterator last)
Definition at line 198 of file BoundedList.hpp.
         : storage(storage)
     {
         assign(first, last);
     }
BoundedList() [5/7]
template<class T> infra::BoundedList< T >::BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, std::initializer_list< T > initializerList)
Definition at line 205 of file BoundedList.hpp.
         : storage(storage)
     {
         assign(initializerList.begin(), initializerList.end());
     }
BoundedList() [6/7]
template<class T> infra::BoundedList< T >::BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, const BoundedList< T > & other)
Definition at line 212 of file BoundedList.hpp.
         : storage(storage)
     {
         assign(other.begin(), other.end());
     }
BoundedList() [7/7]
template<class T> infra::BoundedList< T >::BoundedList (infra::MemoryRange< infra::StaticStorage< detail::BoundedListNode< T >>> storage, BoundedList< T > && other)
Definition at line 219 of file BoundedList.hpp.
         : storage(storage)
     {
         move_from_range(other.begin(), other.end());
         other.clear();
     }
~BoundedList()
template<class T > infra::BoundedList< T >::~BoundedList ()
Definition at line 227 of file BoundedList.hpp.
     {
         clear();
     }
Member Function Documentation
AllocateNode()
template<class T > BoundedList< T >::NodeType * infra::BoundedList< T >::AllocateNode () private
Definition at line 739 of file BoundedList.hpp.
     {
         NodeType* result;
         if (freeList != nullptr)
         {
             result = freeList;
             freeList = freeList->next;
             return result;
         }
         really_assert(numInitialized != storage.size());
         result = &*storage[numInitialized];
         ++numInitialized;
         return result;
     }
assign() [1/2]
template<class T > template<class InputIterator > void infra::BoundedList< T >::assign (InputIterator first, InputIterator last)
Definition at line 530 of file BoundedList.hpp.
     {
         clear();
         while (first != last)
         {
             push_back(*first);
             ++first;
         }
     }
assign() [2/2]
template<class T > void infra::BoundedList< T >::assign (size_type n, const value_type & value)
Definition at line 542 of file BoundedList.hpp.
     {
         clear();
         for (size_type i = 0; i != n; ++i)
             push_back(value);
     }
AssignFromStorage() [1/2]
template<class T > void infra::BoundedList< T >::AssignFromStorage (const BoundedList< T > & other)
Definition at line 255 of file BoundedList.hpp.
     {
         *this = other;
     }
AssignFromStorage() [2/2]
template<class T > void infra::BoundedList< T >::AssignFromStorage (BoundedList< T > && other)
Definition at line 261 of file BoundedList.hpp.
     {
         *this = std::move(other);
     }
back() [1/2]
template<class T > BoundedList< T >::value_type & infra::BoundedList< T >::back ()
Definition at line 339 of file BoundedList.hpp.
     {
         return *lastNode->storage;
     }
back() [2/2]
template<class T > const BoundedList< T >::value_type & infra::BoundedList< T >::back () const
Definition at line 345 of file BoundedList.hpp.
     {
         return *lastNode->storage;
     }
begin() [1/2]
template<class T > BoundedList< T >::iterator infra::BoundedList< T >::begin ()
Definition at line 267 of file BoundedList.hpp.
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::BoundedList(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator<(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator=(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator==(), and infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap().
     {
         return iterator(firstNode, this);
     }
begin() [2/2]
template<class T > BoundedList< T >::const_iterator infra::BoundedList< T >::begin () const
Definition at line 273 of file BoundedList.hpp.
     {
         return iterator(firstNode, this);
     }
cbegin()
template<class T > BoundedList< T >::const_iterator infra::BoundedList< T >::cbegin () const
Definition at line 291 of file BoundedList.hpp.
     {
         return const_iterator(firstNode, this);
     }
cend()
template<class T > BoundedList< T >::const_iterator infra::BoundedList< T >::cend () const
Definition at line 297 of file BoundedList.hpp.
     {
         return const_iterator(nullptr, this);
     }
clear()
template<class T > void infra::BoundedList< T >::clear ()
Definition at line 655 of file BoundedList.hpp.
     {
         while (!empty())
             pop_back();
     }
emplace_back()
template<class T > template<class... Args> void infra::BoundedList< T >::emplace_back (Args &&... args)
Definition at line 683 of file BoundedList.hpp.
     {
         NodeType* node = AllocateNode();
         static_cast<detail::BoundedListNode<T>*>(node)->storage.Construct(std::forward<Args>(args)...);
         node->previous = lastNode;
         node->next = nullptr;
         if (lastNode != nullptr)
             lastNode->next = node;
         else
             firstNode = node;
         lastNode = node;
         ++numAllocated;
     }
emplace_front()
template<class T > template<class... Args> void infra::BoundedList< T >::emplace_front (Args &&... args)
Definition at line 663 of file BoundedList.hpp.
     {
         NodeType* node = AllocateNode();
         static_cast<detail::BoundedListNode<T>*>(node)->storage.Construct(std::forward<Args>(args)...);
         node->next = firstNode;
         node->previous = nullptr;
         if (firstNode != nullptr)
             firstNode->previous = node;
         else
             lastNode = node;
         firstNode = node;
         ++numAllocated;
     }
empty()
template<class T > bool infra::BoundedList< T >::empty () const
Definition at line 315 of file BoundedList.hpp.
     {
         return numAllocated == 0;
     }
end() [1/2]
template<class T > BoundedList< T >::iterator infra::BoundedList< T >::end ()
Definition at line 279 of file BoundedList.hpp.
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::BoundedList(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator<(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator=(), and infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap().
     {
         return iterator(nullptr, this);
     }
end() [2/2]
template<class T > BoundedList< T >::const_iterator infra::BoundedList< T >::end () const
Definition at line 285 of file BoundedList.hpp.
     {
         return const_iterator(nullptr, this);
     }
erase()
template<class T > void infra::BoundedList< T >::erase (iterator position)
Definition at line 564 of file BoundedList.hpp.
     {
         NodeType* node = position.node;
         NodeType* next = node->next;
         NodeType* previous = node->previous;
         if (next != nullptr)
             next->previous = previous;
         else
             lastNode = previous;
         if (previous != nullptr)
             previous->next = next;
         else
             firstNode = next;
         node->storage.Destruct();
         node->next = freeList;
         freeList = node;
         --numAllocated;
     }
erase_all_after()
template<class T > void infra::BoundedList< T >::erase_all_after (iterator position)
Definition at line 588 of file BoundedList.hpp.
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap().
     {
         NodeType* node = position.node->next;
         position.node->next = nullptr;
         lastNode = position.node;
         while (node != nullptr)
         {
             node->storage.Destruct();
             NodeType* oldFreeList = freeList;
             freeList = node;
             node = node->next;
             freeList->next = oldFreeList;
             --numAllocated;
         }
     }
front() [1/2]
template<class T > BoundedList< T >::value_type & infra::BoundedList< T >::front ()
Definition at line 327 of file BoundedList.hpp.
     {
         return *firstNode->storage;
     }
front() [2/2]
template<class T > const BoundedList< T >::value_type & infra::BoundedList< T >::front () const
Definition at line 333 of file BoundedList.hpp.
     {
         return *firstNode->storage;
     }
full()
template<class T > bool infra::BoundedList< T >::full () const
Definition at line 321 of file BoundedList.hpp.
     {
         return numAllocated == storage.size();
     }
insert() [1/2]
template<class T > void infra::BoundedList< T >::insert (iterator position, const value_type & value)
Definition at line 465 of file BoundedList.hpp.
     {
         if (position != end())
         {
             NodeType* node = AllocateNode();
             node->storage.Construct(value);
             node->next = position.node;
             if (node->next != nullptr)
             {
                 node->previous = node->next->previous;
                 node->next->previous = node;
             }
             else
             {
                 node->previous = lastNode;
                 lastNode = node;
             }
             if (node->previous != nullptr)
                 node->previous->next = node;
             else
                 firstNode = node;
             ++numAllocated;
         }
         else
             push_back(value);
     }
insert() [2/2]
template<class T > void infra::BoundedList< T >::insert (iterator position, value_type && value)
Definition at line 497 of file BoundedList.hpp.
     {
         if (position != end())
         {
             NodeType* node = AllocateNode();
             node->storage.Construct(std::move(value));
             node->next = position.node;
             if (node->next != nullptr)
             {
                 node->previous = node->next->previous;
                 node->next->previous = node;
             }
             else
             {
                 node->previous = lastNode;
                 lastNode = node;
             }
             if (node->previous != nullptr)
                 node->previous->next = node;
             else
                 firstNode = node;
             ++numAllocated;
         }
         else
             push_back(std::move(value));
     }
max_size()
template<class T > BoundedList< T >::size_type infra::BoundedList< T >::max_size () const
Definition at line 309 of file BoundedList.hpp.
     {
         return storage.size();
     }
move_from_range()
template<class T > template<class InputIterator > void infra::BoundedList< T >::move_from_range (InputIterator first, InputIterator last)
Definition at line 552 of file BoundedList.hpp.
     {
         clear();
         while (first != last)
         {
             push_back(std::move(*first));
             ++first;
         }
     }
operator!=()
template<class T > bool infra::BoundedList< T >::operator!= (const BoundedList< T > & other) const
Definition at line 709 of file BoundedList.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T > bool infra::BoundedList< T >::operator< (const BoundedList< T > & other) const
Definition at line 715 of file BoundedList.hpp.
     {
         return std::lexicographical_compare(begin(), end(), other.begin(), other.end());
     }
operator<=()
template<class T > bool infra::BoundedList< T >::operator<= (const BoundedList< T > & other) const
Definition at line 721 of file BoundedList.hpp.
     {
         return !(other < *this);
     }
operator=() [1/2]
template<class T > BoundedList< T > & infra::BoundedList< T >::operator= (const BoundedList< T > & other)
Definition at line 233 of file BoundedList.hpp.
     {
         if (this != &other)
         {
             clear();
             assign(other.begin(), other.end());
         }
         return *this;
     }
operator=() [2/2]
template<class T > BoundedList< T > & infra::BoundedList< T >::operator= (BoundedList< T > && other)
Definition at line 246 of file BoundedList.hpp.
     {
         clear();
         move_from_range(other.begin(), other.end());
         return *this;
     }
operator==()
template<class T > bool infra::BoundedList< T >::operator== (const BoundedList< T > & other) const
Definition at line 702 of file BoundedList.hpp.
     {
         return size() == other.size()
             && std::equal(begin(), end(), other.begin());
     }
operator>()
template<class T > bool infra::BoundedList< T >::operator> (const BoundedList< T > & other) const
Definition at line 727 of file BoundedList.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T > bool infra::BoundedList< T >::operator>= (const BoundedList< T > & other) const
Definition at line 733 of file BoundedList.hpp.
     {
         return !(*this < other);
     }
pop_back()
template<class T > void infra::BoundedList< T >::pop_back ()
Definition at line 446 of file BoundedList.hpp.
     {
         lastNode->storage.Destruct();
         NodeType* oldEnd = lastNode;
         lastNode = lastNode->previous;
         if (lastNode != nullptr)
             lastNode->next = nullptr;
         else
             firstNode = nullptr;
         oldEnd->next = freeList;
         freeList = oldEnd;
         --numAllocated;
     }
pop_front()
template<class T > void infra::BoundedList< T >::pop_front ()
Definition at line 389 of file BoundedList.hpp.
     {
         firstNode->storage.Destruct();
         NodeType* oldStart = firstNode;
         firstNode = firstNode->next;
         if (firstNode != nullptr)
             firstNode->previous = nullptr;
         else
             lastNode = nullptr;
         oldStart->next = freeList;
         freeList = oldStart;
         --numAllocated;
     }
push_back() [1/2]
template<class T > void infra::BoundedList< T >::push_back (const value_type & value)
Definition at line 408 of file BoundedList.hpp.
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap().
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(value);
         node->previous = lastNode;
         node->next = nullptr;
         if (lastNode != nullptr)
             lastNode->next = node;
         else
             firstNode = node;
         lastNode = node;
         ++numAllocated;
     }
push_back() [2/2]
template<class T > void infra::BoundedList< T >::push_back (value_type && value)
Definition at line 427 of file BoundedList.hpp.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(std::move(value));
         node->previous = lastNode;
         node->next = nullptr;
         if (lastNode != nullptr)
             lastNode->next = node;
         else
             firstNode = node;
         lastNode = node;
         ++numAllocated;
     }
push_front() [1/2]
template<class T > void infra::BoundedList< T >::push_front (const value_type & value)
Definition at line 351 of file BoundedList.hpp.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(value);
         node->next = firstNode;
         node->previous = nullptr;
         if (firstNode != nullptr)
             firstNode->previous = node;
         else
             lastNode = node;
         firstNode = node;
         ++numAllocated;
     }
push_front() [2/2]
template<class T > void infra::BoundedList< T >::push_front (value_type && value)
Definition at line 370 of file BoundedList.hpp.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(std::move(value));
         node->next = firstNode;
         node->previous = nullptr;
         if (firstNode != nullptr)
             firstNode->previous = node;
         else
             lastNode = node;
         firstNode = node;
         ++numAllocated;
     }
remove()
template<class T > void infra::BoundedList< T >::remove (reference value)
Definition at line 607 of file BoundedList.hpp.
     {
         erase(iterator(reinterpret_cast<NodeType*>(&value), this));
     }
size()
template<class T > BoundedList< T >::size_type infra::BoundedList< T >::size () const
Definition at line 303 of file BoundedList.hpp.
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::full(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::max_size(), and infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator==().
     {
         return numAllocated;
     }
swap()
template<class T > void infra::BoundedList< T >::swap (BoundedList< T > & other)
Definition at line 613 of file BoundedList.hpp.
Referenced by infra::swap().
     {
         using std::swap;
         iterator i1 = begin();
         iterator i2 = other.begin();
         iterator i1old;
         iterator i2old;
         while (i1 != end() && i2 != other.end())
         {
             swap(*i1, *i2);
             i1old = i1;
             i2old = i2;
             ++i1;
             ++i2;
         }
         if (i1 != end())
         {
             while (i1 != end())
             {
                 other.push_back(std::move(*i1));
                 ++i1;
             }
             erase_all_after(i1old);
         }
         if (i2 != other.end())
         {
             while (i2 != other.end())
             {
                 push_back(std::move(*i2));
                 ++i2;
             }
             other.erase_all_after(i2old);
         }
     }
Member Data Documentation
firstNode
template<class T> NodeType* infra::BoundedList< T >::firstNode = nullptr private
Definition at line 138 of file BoundedList.hpp.
freeList
template<class T> NodeType* infra::BoundedList< T >::freeList = nullptr private
Definition at line 140 of file BoundedList.hpp.
lastNode
template<class T> NodeType* infra::BoundedList< T >::lastNode = nullptr private
Definition at line 139 of file BoundedList.hpp.
numAllocated
template<class T> size_type infra::BoundedList< T >::numAllocated = 0 private
Definition at line 136 of file BoundedList.hpp.
numInitialized
template<class T> size_type infra::BoundedList< T >::numInitialized = 0 private
Definition at line 137 of file BoundedList.hpp.
storage
template<class T> infra::MemoryRange<infra::StaticStorage<detail::BoundedListNode<T> > > infra::BoundedList< T >::storage private
Definition at line 135 of file BoundedList.hpp.
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::back(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::front(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::pop_back(), and infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::pop_front().
The documentation for this class was generated from the following file:
BoundedList.hpp