EMil: infra::XmlTagFormatter Class Reference
infra::XmlTagFormatter Class Reference
#include <XmlFormatter.hpp>
Public Member Functions
XmlTagFormatter (infra::TextOutputStream &stream, const char *tagName)
XmlTagFormatter (const XmlTagFormatter &other)=delete
XmlTagFormatter (XmlTagFormatter &&other)
XmlTagFormatter & operator= (const XmlTagFormatter &other)=delete
XmlTagFormatter & operator= (XmlTagFormatter &&other)
~XmlTagFormatter ()
void Attribute (const char *name, infra::BoundedConstString value)
void Content (infra::BoundedConstString string)
XmlTagFormatter Tag (const char *tagName)
void Element (const char *tagName, infra::BoundedConstString content)
Private Member Functions
void CloseBeginTag ()
Private Attributes
infra::Optional< infra::TextOutputStream::WithErrorPolicy > stream
const char * tagName = nullptr
bool empty = true
Detailed Description
Definition at line 29 of file XmlFormatter.hpp.
Constructor & Destructor Documentation
XmlTagFormatter() [1/3]
infra::XmlTagFormatter::XmlTagFormatter (infra::TextOutputStream & stream, const char * tagName)
Definition at line 71 of file XmlFormatter.cpp.
References tagName.
Referenced by Tag().
         : stream(infra::inPlace, stream.Writer(), infra::noFail)
         , tagName(tagName)
     {
         *this->stream << "<" << tagName;
     }
XmlTagFormatter() [2/3]
infra::XmlTagFormatter::XmlTagFormatter (const XmlTagFormatter & other) delete
XmlTagFormatter() [3/3]
infra::XmlTagFormatter::XmlTagFormatter (XmlTagFormatter && other)
Definition at line 87 of file XmlFormatter.cpp.
References infra::none.
         : stream(other.stream)
     {
         other.stream = infra::none;
     }
~XmlTagFormatter()
infra::XmlTagFormatter::~XmlTagFormatter ()
Definition at line 78 of file XmlFormatter.cpp.
References empty, infra::none, stream, and tagName.
     {
         if (stream != infra::none)
             if (empty)
                 *stream << " />";
             else
                 *stream << "</" << tagName << ">";
     }
Member Function Documentation
Attribute()
void infra::XmlTagFormatter::Attribute (const char * name, infra::BoundedConstString value)
Definition at line 101 of file XmlFormatter.cpp.
References stream, and value.
     {
         *stream << " " << name << R"(=")" << value << R"(")";
     }
CloseBeginTag()
void infra::XmlTagFormatter::CloseBeginTag () private
Definition at line 124 of file XmlFormatter.cpp.
References empty, and stream.
Referenced by Content(), and Tag().
     {
         if (empty)
         {
             empty = false;
             *stream << ">";
         }
     }
Content()
void infra::XmlTagFormatter::Content (infra::BoundedConstString string)
Definition at line 106 of file XmlFormatter.cpp.
References CloseBeginTag(), and stream.
     {
         CloseBeginTag();
         InsertEscapedContent(*stream, string);
     }
Element()
void infra::XmlTagFormatter::Element (const char * tagName, infra::BoundedConstString content)
Definition at line 118 of file XmlFormatter.cpp.
References Tag(), and tagName.
     {
         auto element = Tag(tagName);
         element.Content(content);
     }
operator=() [1/2]
XmlTagFormatter& infra::XmlTagFormatter::operator= (const XmlTagFormatter & other) delete
operator=() [2/2]
XmlTagFormatter & infra::XmlTagFormatter::operator= (XmlTagFormatter && other)
Definition at line 93 of file XmlFormatter.cpp.
References infra::none, and stream.
     {
         stream = other.stream;
         other.stream = infra::none;
         return *this;
     }
Tag()
XmlTagFormatter infra::XmlTagFormatter::Tag (const char * tagName)
Definition at line 112 of file XmlFormatter.cpp.
References CloseBeginTag(), stream, tagName, and XmlTagFormatter().
Referenced by Element().
     {
         CloseBeginTag();
         return XmlTagFormatter(*stream, tagName);
     }
Member Data Documentation
empty
bool infra::XmlTagFormatter::empty = true private
Definition at line 50 of file XmlFormatter.hpp.
Referenced by CloseBeginTag(), and ~XmlTagFormatter().
stream
infra::Optional<infra::TextOutputStream::WithErrorPolicy> infra::XmlTagFormatter::stream private
Definition at line 48 of file XmlFormatter.hpp.
Referenced by Attribute(), CloseBeginTag(), Content(), operator=(), Tag(), and ~XmlTagFormatter().
tagName
const char* infra::XmlTagFormatter::tagName = nullptr private
Definition at line 49 of file XmlFormatter.hpp.
Referenced by Element(), Tag(), XmlTagFormatter(), and ~XmlTagFormatter().
The documentation for this class was generated from the following files:
XmlFormatter.hpp
XmlFormatter.cpp