EMil: application::UpgradePackConfigParser Class Reference
application::UpgradePackConfigParser Class Reference
#include <UpgradePackConfigParser.hpp>
Classes
class ParseException
Public Member Functions
UpgradePackConfigParser (infra::JsonObject &json)
std::vector< std::pair< std::string, std::string > > GetComponents ()
std::vector< std::pair< std::string, std::string > > GetOptions ()
std::string GetOutputFilename ()
Private Member Functions
void CheckValidJson ()
void CheckMandatoryKeys ()
Private Attributes
infra::JsonObject & json
Detailed Description
Definition at line 8 of file UpgradePackConfigParser.hpp.
Constructor & Destructor Documentation
UpgradePackConfigParser()
application::UpgradePackConfigParser::UpgradePackConfigParser (infra::JsonObject & json)
Definition at line 14 of file UpgradePackConfigParser.cpp.
References CheckMandatoryKeys(), and CheckValidJson().
         : json(json)
     {
         CheckValidJson();
         CheckMandatoryKeys();
     }
Member Function Documentation
CheckMandatoryKeys()
void application::UpgradePackConfigParser::CheckMandatoryKeys () private
Definition at line 30 of file UpgradePackConfigParser.cpp.
References infra::BoundedStringBase< T >::data(), infra::JsonObject::HasKey(), and json.
Referenced by UpgradePackConfigParser().
     {
         std::vector<std::string> mandatoryKeys = { "components" };
         std::for_each(mandatoryKeys.begin(), mandatoryKeys.end(), [this](const std::string& key)
         {
             infra::BoundedConstString s = key.data();
             if (!json.HasKey(s))
                 throw ParseException("ConfigParser error: required key " + key + " missing");
         });
     }
CheckValidJson()
void application::UpgradePackConfigParser::CheckValidJson () private
Definition at line 21 of file UpgradePackConfigParser.cpp.
References infra::JsonObject::Error(), and json.
Referenced by UpgradePackConfigParser().
     {
         for (auto it : json)
         {}
         if (json.Error())
             throw ParseException("ConfigParser error: invalid JSON");
     }
GetComponents()
std::vector< std::pair< std::string, std::string > > application::UpgradePackConfigParser::GetComponents ()
Definition at line 41 of file UpgradePackConfigParser.cpp.
References infra::JsonObject::begin(), infra::JsonObject::end(), infra::JsonObject::GetOptionalObject(), json, and infra::none.
     {
         infra::Optional<infra::JsonObject> components = json.GetOptionalObject("components");
         if (components == infra::none)
             throw ParseException(std::string("ConfigParser error: components list should be an object"));
         std::vector<std::pair<std::string, std::string>> result;
         for (infra::JsonObjectIterator it = components->begin(); it != components->end() ; ++it)
         {
             if (it->value.Is<infra::JsonString>())
                 result.push_back(std::make_pair(it->key.ToStdString(), it->value.Get<infra::JsonString>().ToStdString()));
             else
                 throw ParseException("ConfigParser error: invalid value for component: " + it->key.ToStdString());
         }
         return result;
     }
GetOptions()
std::vector< std::pair< std::string, std::string > > application::UpgradePackConfigParser::GetOptions ()
Definition at line 61 of file UpgradePackConfigParser.cpp.
References infra::JsonObject::GetOptionalObject(), infra::JsonObject::HasKey(), json, and infra::none.
     {
         std::vector<std::pair<std::string, std::string>> result;
         if (!json.HasKey("options"))
             return result;
         infra::Optional<infra::JsonObject> options = json.GetOptionalObject("options");
         if (options == infra::none)
             throw ParseException(std::string("ConfigParser error: options list should be an object"));
         for (infra::JsonObjectIterator it = options->begin(); it != options->end(); ++it)
         {
             if (it->value.Is<infra::JsonString>())
                 result.push_back(std::make_pair(it->key.ToStdString(), it->value.Get<infra::JsonString>().ToStdString()));
             else if (it->value.Is<int32_t>())
                 result.push_back(std::pair<std::string, std::string>(it->key.ToStdString(), std::to_string(it->value.Get<int32_t>())));
             else
                 throw ParseException("ConfigParser error: invalid value for option: " + it->key.ToStdString());
         }
         return result;
     }
GetOutputFilename()
std::string application::UpgradePackConfigParser::GetOutputFilename ()
Definition at line 85 of file UpgradePackConfigParser.cpp.
References infra::JsonObject::GetOptionalString(), infra::JsonObject::GetString(), infra::JsonObject::HasKey(), json, infra::none, and infra::JsonString::ToStdString().
     {
         if (json.HasKey("output_filename"))
         {
             if (json.GetOptionalString("output_filename") == infra::none)
                 throw ParseException(std::string("ConfigParser error: output filename should be a string"));
             else
                 return json.GetString("output_filename").ToStdString();
         }
         return "";
     }
Member Data Documentation
json
infra::JsonObject& application::UpgradePackConfigParser::json private
Definition at line 31 of file UpgradePackConfigParser.hpp.
Referenced by CheckMandatoryKeys(), CheckValidJson(), GetComponents(), GetOptions(), and GetOutputFilename().
The documentation for this class was generated from the following files:
UpgradePackConfigParser.hpp
UpgradePackConfigParser.cpp