EMil: services::SpiMultipleAccess Class Reference
services::SpiMultipleAccess Class Reference
#include <SpiMultipleAccess.hpp>
Public Member Functions
SpiMultipleAccess (SpiMultipleAccessMaster &master)
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> &onDone) override
virtual void SetChipSelectConfigurator (hal::ChipSelectConfigurator &configurator) override
virtual void SetCommunicationConfigurator (hal::CommunicationConfigurator &configurator) override
virtual void ResetCommunicationConfigurator () override
Public Member Functions inherited from hal::SpiMaster
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
Private Member Functions
virtual void StartSession () override
virtual void EndSession () override
void SendAndReceiveOnClaimed (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> &onDone)
ChipSelectConfigurator ()=default
ChipSelectConfigurator (const ChipSelectConfigurator &other)=delete
ChipSelectConfigurator & operator= (const ChipSelectConfigurator &other)=delete
~ChipSelectConfigurator ()=default
Private Attributes
SpiMultipleAccessMaster & master
infra::ClaimableResource::Claimer::WithSize< SERVICES_SPI_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE > claimer
hal::ChipSelectConfigurator * chipSelectConfigurator = nullptr
hal::CommunicationConfigurator * communicationConfigurator = nullptr
Additional Inherited Members
Protected Member Functions inherited from hal::SpiMaster
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Detailed Description
Definition at line 31 of file SpiMultipleAccess.hpp.
Constructor & Destructor Documentation
SpiMultipleAccess()
services::SpiMultipleAccess::SpiMultipleAccess (SpiMultipleAccessMaster & master) explicit
Definition at line 37 of file SpiMultipleAccess.cpp.
         : master(master)
         , claimer(master)
     {}
Member Function Documentation
EndSession()
void services::SpiMultipleAccess::EndSession () override private virtual
Implements hal::ChipSelectConfigurator.
Definition at line 74 of file SpiMultipleAccess.cpp.
References chipSelectConfigurator, claimer, and hal::ChipSelectConfigurator::EndSession().
     {
         if (chipSelectConfigurator != nullptr)
             chipSelectConfigurator->EndSession();
         claimer.Release();
     }
ResetCommunicationConfigurator()
void services::SpiMultipleAccess::ResetCommunicationConfigurator () override virtual
Implements hal::SpiMaster.
Definition at line 63 of file SpiMultipleAccess.cpp.
References communicationConfigurator.
     {
         communicationConfigurator = nullptr;
     }
SendAndReceive()
void services::SpiMultipleAccess::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> & onDone) override virtual
Implements hal::SpiMaster.
Definition at line 42 of file SpiMultipleAccess.cpp.
References claimer, and SendAndReceiveOnClaimed().
     {
         if (!claimer.IsClaimed())
             claimer.Claim([this, sendData, receiveData, nextAction, onDone]()
             {
                 SendAndReceiveOnClaimed(sendData, receiveData, nextAction, onDone);
             });
         else
             SendAndReceiveOnClaimed(sendData, receiveData, nextAction, onDone);
     }
SendAndReceiveOnClaimed()
void services::SpiMultipleAccess::SendAndReceiveOnClaimed (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> & onDone) private
Definition at line 82 of file SpiMultipleAccess.cpp.
References communicationConfigurator, master, services::SpiMultipleAccessMaster::ResetCommunicationConfigurator(), services::SpiMultipleAccessMaster::SendAndReceive(), services::SpiMultipleAccessMaster::SetChipSelectConfigurator(), and services::SpiMultipleAccessMaster::SetCommunicationConfigurator().
Referenced by SendAndReceive().
     {
         if (communicationConfigurator != nullptr)
             master.SetCommunicationConfigurator(*communicationConfigurator);
         else
             master.ResetCommunicationConfigurator();
         master.SetChipSelectConfigurator(*this);
         master.SendAndReceive(sendData, receiveData, nextAction, onDone);
     }
SetChipSelectConfigurator()
void services::SpiMultipleAccess::SetChipSelectConfigurator (hal::ChipSelectConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 53 of file SpiMultipleAccess.cpp.
References chipSelectConfigurator.
     {
         chipSelectConfigurator = &configurator;
     }
SetCommunicationConfigurator()
void services::SpiMultipleAccess::SetCommunicationConfigurator (hal::CommunicationConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 58 of file SpiMultipleAccess.cpp.
References communicationConfigurator.
     {
         communicationConfigurator = &configurator;
     }
StartSession()
void services::SpiMultipleAccess::StartSession () override private virtual
Implements hal::ChipSelectConfigurator.
Definition at line 68 of file SpiMultipleAccess.cpp.
References chipSelectConfigurator, and hal::ChipSelectConfigurator::StartSession().
     {
         if (chipSelectConfigurator != nullptr)
             chipSelectConfigurator->StartSession();
     }
Member Data Documentation
chipSelectConfigurator
hal::ChipSelectConfigurator* services::SpiMultipleAccess::chipSelectConfigurator = nullptr private
Definition at line 51 of file SpiMultipleAccess.hpp.
Referenced by EndSession(), SetChipSelectConfigurator(), and StartSession().
claimer
infra::ClaimableResource::Claimer::WithSize<SERVICES_SPI_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE> services::SpiMultipleAccess::claimer private
Definition at line 50 of file SpiMultipleAccess.hpp.
Referenced by EndSession(), and SendAndReceive().
communicationConfigurator
hal::CommunicationConfigurator* services::SpiMultipleAccess::communicationConfigurator = nullptr private
Definition at line 52 of file SpiMultipleAccess.hpp.
Referenced by ResetCommunicationConfigurator(), SendAndReceiveOnClaimed(), and SetCommunicationConfigurator().
master
SpiMultipleAccessMaster& services::SpiMultipleAccess::master private
Definition at line 49 of file SpiMultipleAccess.hpp.
Referenced by SendAndReceiveOnClaimed().
The documentation for this class was generated from the following files:
SpiMultipleAccess.hpp
SpiMultipleAccess.cpp