EMil: FactoryDefaultConfigurationStoreIntegrationTest::Data Struct Reference
FactoryDefaultConfigurationStoreIntegrationTest::Data Struct Reference
Public Member Functions
void Serialize (infra::ProtoFormatter &formatter)
void Deserialize (infra::ProtoParser &parser)
Public Attributes
std::array< uint8_t, 8 > data = { 0, 1, 2, 3, 4, 5, 6, 7 }
Static Public Attributes
static const uint32_t maxMessageSize = 10
Detailed Description
Definition at line 586 of file TestConfigurationStore.cpp.
Member Function Documentation
Deserialize()
void FactoryDefaultConfigurationStoreIntegrationTest::Data::Deserialize (infra::ProtoParser & parser) inline
Definition at line 593 of file TestConfigurationStore.cpp.
References data, and infra::ProtoParser::GetField().
         {
             infra::ProtoParser::Field field = parser.GetField();
             assert(field.second == 1);
             infra::BoundedVector<uint8_t>::WithMaxSize<8> bytes;
             field.first.Get<infra::ProtoLengthDelimited>().GetBytes(bytes);
             assert(bytes.size() == data.size());
             std::copy(bytes.begin(), bytes.end(), data.begin());
         }
Serialize()
void FactoryDefaultConfigurationStoreIntegrationTest::Data::Serialize (infra::ProtoFormatter & formatter) inline
Definition at line 588 of file TestConfigurationStore.cpp.
References data, infra::MakeRange(), and infra::ProtoFormatter::PutBytesField().
         {
             formatter.PutBytesField(infra::MakeRange(data), 1);
         }
Member Data Documentation
data
std::array<uint8_t, 8> FactoryDefaultConfigurationStoreIntegrationTest::Data::data = { 0, 1, 2, 3, 4, 5, 6, 7 }
Definition at line 606 of file TestConfigurationStore.cpp.
Referenced by Deserialize(), and Serialize().
maxMessageSize
const uint32_t FactoryDefaultConfigurationStoreIntegrationTest::Data::maxMessageSize = 10 static
Definition at line 604 of file TestConfigurationStore.cpp.
The documentation for this struct was generated from the following file:
TestConfigurationStore.cpp