EMil: TestPolymorphicVariant.cpp File Reference
TestPolymorphicVariant.cpp File Reference
Functions
TEST (PolymorphicVariantTest, after_default_construction_State1_is_created)
TEST (PolymorphicVariantTest, create_State1)
TEST (PolymorphicVariantTest, create_State2)
TEST (PolymorphicVariantTest, assign_State2_after_construction)
TEST (PolymorphicVariantTest, Emplace_returns_reference_to_constructed_object)
TEST (PolymorphicVariantTest, create_State1_by_copy)
TEST (PolymorphicVariantTest, create_State2_by_copy)
TEST (PolymorphicVariantTest, copy_construct_variant)
TEST (PolymorphicVariantTest, copy_construct_from_narrower_variant)
TEST (PolymorphicVariantTest, copy_assign_variant)
TEST (PolymorphicVariantTest, copy_assign_from_narrower_variant)
TEST (PolymorphicVariantTest, compare_same_states)
TEST (PolymorphicVariantTest, compare_different_states)
TEST (PolymorphicVariantTest, compare_same_states_by_value)
TEST (PolymorphicVariantTest, compare_different_states_by_value)
Function Documentation
TEST() [1/15]
TEST (PolymorphicVariantTest , after_default_construction_State1_is_created)
Definition at line 124 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<State, State1, State2> v;
     EXPECT_EQ(1, v->Identifier());
 }
TEST() [2/15]
TEST (PolymorphicVariantTest , create_State1)
Definition at line 130 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<State, State1, State2> v((infra::InPlaceType<State1>()));
     EXPECT_EQ(1, v->Identifier());
 }
TEST() [3/15]
TEST (PolymorphicVariantTest , create_State2)
Definition at line 136 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<State, State1, State2> v((infra::InPlaceType<State2>()));
     EXPECT_EQ(2, v->Identifier());
 }
TEST() [4/15]
TEST (PolymorphicVariantTest , assign_State2_after_construction)
Definition at line 142 of file TestPolymorphicVariant.cpp.
References infra::PolymorphicVariant< Base, T >::Emplace(), and EXPECT_EQ().
 {
     infra::PolymorphicVariant<State, State1, State2> v;
     v.Emplace<State2>();
     EXPECT_EQ(2, v->Identifier());
 }
TEST() [5/15]
TEST (PolymorphicVariantTest , Emplace_returns_reference_to_constructed_object)
Definition at line 149 of file TestPolymorphicVariant.cpp.
References infra::PolymorphicVariant< Base, T >::Emplace(), and EXPECT_EQ().
 {
     infra::PolymorphicVariant<State, State1, State2> v;
     State1& state1 = v.Emplace<State1>();
     EXPECT_EQ(1, state1.Identifier());
 }
TEST() [6/15]
TEST (PolymorphicVariantTest , create_State1_by_copy)
Definition at line 157 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v((CopyableState1()));
     EXPECT_EQ(1, v->Identifier());
 }
TEST() [7/15]
TEST (PolymorphicVariantTest , create_State2_by_copy)
Definition at line 163 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v((CopyableState2()));
     EXPECT_EQ(2, v->Identifier());
 }
TEST() [8/15]
TEST (PolymorphicVariantTest , copy_construct_variant)
Definition at line 169 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v1((CopyableState2()));
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v2(v1);
     EXPECT_EQ(2, v2->Identifier());
 }
TEST() [9/15]
TEST (PolymorphicVariantTest , copy_construct_from_narrower_variant)
Definition at line 176 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<CopyableState, CopyableState2> v1((CopyableState2()));
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v2(v1);
     EXPECT_EQ(2, v2->Identifier());
 }
TEST() [10/15]
TEST (PolymorphicVariantTest , copy_assign_variant)
Definition at line 183 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v1;
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v2((CopyableState2()));
     v1 = v2;
     EXPECT_EQ(2, v1->Identifier());
 }
TEST() [11/15]
TEST (PolymorphicVariantTest , copy_assign_from_narrower_variant)
Definition at line 191 of file TestPolymorphicVariant.cpp.
References EXPECT_EQ().
 {
     infra::PolymorphicVariant<CopyableState, CopyableState1, CopyableState2> v1;
     infra::PolymorphicVariant<CopyableState, CopyableState2> v2((CopyableState2()));
     v1 = v2;
     EXPECT_EQ(2, v1->Identifier());
 }
TEST() [12/15]
TEST (PolymorphicVariantTest , compare_same_states)
Definition at line 199 of file TestPolymorphicVariant.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::PolymorphicVariant<State, ComparableState1, ComparableState2> v1((infra::InPlaceType<ComparableState1>()));
     infra::PolymorphicVariant<State, ComparableState1, ComparableState2> v2((infra::InPlaceType<ComparableState1>()));
     EXPECT_TRUE(v1 == v2);
     EXPECT_FALSE(v1 != v2);
     EXPECT_FALSE(v1 < v2);
     EXPECT_FALSE(v1 > v2);
     EXPECT_TRUE(v1 <= v2);
     EXPECT_TRUE(v1 >= v2);
 }
TEST() [13/15]
TEST (PolymorphicVariantTest , compare_different_states)
Definition at line 211 of file TestPolymorphicVariant.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::PolymorphicVariant<State, ComparableState1, ComparableState2> v1((infra::InPlaceType<ComparableState1>()));
     infra::PolymorphicVariant<State, ComparableState1, ComparableState2> v2((infra::InPlaceType<ComparableState2>()));
     EXPECT_FALSE(v1 == v2);
     EXPECT_TRUE(v1 != v2);
     EXPECT_TRUE(v1 < v2);
     EXPECT_FALSE(v1 > v2);
     EXPECT_TRUE(v1 <= v2);
     EXPECT_FALSE(v1 >= v2);
 }
TEST() [14/15]
TEST (PolymorphicVariantTest , compare_same_states_by_value)
Definition at line 223 of file TestPolymorphicVariant.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::PolymorphicVariant<State, ComparableState1, ComparableState2> v((infra::InPlaceType<ComparableState1>()));
     ComparableState1 c;
     EXPECT_TRUE(v == c);
     EXPECT_FALSE(v != c);
     EXPECT_FALSE(v < c);
     EXPECT_FALSE(v > c);
     EXPECT_TRUE(v <= c);
     EXPECT_TRUE(v >= c);
 }
TEST() [15/15]
TEST (PolymorphicVariantTest , compare_different_states_by_value)
Definition at line 235 of file TestPolymorphicVariant.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::PolymorphicVariant<State, ComparableState1, ComparableState2> v((infra::InPlaceType<ComparableState1>()));
     ComparableState2 c;
     EXPECT_FALSE(v == c);
     EXPECT_TRUE(v != c);
     EXPECT_TRUE(v < c);
     EXPECT_FALSE(v > c);
     EXPECT_TRUE(v <= c);
     EXPECT_FALSE(v >= c);
 }