EMil: infra::IntrusiveSet< T, Compare > Class Template Reference
infra::IntrusiveSet< T, Compare > Class Template Reference
#include <IntrusiveSet.hpp>
Public Types
typedef IntrusiveBinarySearchTree< T, Compare >::value_type value_type
typedef IntrusiveBinarySearchTree< T, Compare >::reference reference
typedef IntrusiveBinarySearchTree< T, Compare >::const_reference const_reference
typedef IntrusiveBinarySearchTree< T, Compare >::pointer pointer
typedef IntrusiveBinarySearchTree< T, Compare >::const_pointer const_pointer
typedef IntrusiveBinarySearchTree< T, Compare >::iterator iterator
typedef IntrusiveBinarySearchTree< T, Compare >::const_iterator const_iterator
typedef IntrusiveBinarySearchTree< T, Compare >::reverse_iterator reverse_iterator
typedef IntrusiveBinarySearchTree< T, Compare >::const_reverse_iterator const_reverse_iterator
typedef IntrusiveBinarySearchTree< T, Compare >::difference_type difference_type
typedef IntrusiveBinarySearchTree< T, Compare >::size_type size_type
typedef detail::IntrusiveSetNode< T > NodeType
typedef NodeType::Colour Colour
Public Types inherited from infra::IntrusiveBinarySearchTree< T, Compare >
typedef detail::IntrusiveBinarySearchTreeNode< T > NodeType
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef detail::IntrusiveBinarySearchTreeIterator< T, Compare > iterator
typedef detail::IntrusiveBinarySearchTreeIterator< const T, Compare > const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
IntrusiveSet (const Compare &compare=Compare())
template<class InputIterator >
IntrusiveSet (InputIterator first, InputIterator last, const Compare &comp=Compare())
IntrusiveSet (const IntrusiveSet &)=delete
IntrusiveSet (IntrusiveSet &&other)
IntrusiveSet & operator= (const IntrusiveSet &)=delete
IntrusiveSet & operator= (IntrusiveSet &&other)
~IntrusiveSet ()
bool invariant_holds () const
void insert (const_reference value)
void erase (const_reference value)
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void swap (IntrusiveSet &other)
Public Member Functions inherited from infra::IntrusiveBinarySearchTree< T, Compare >
IntrusiveBinarySearchTree (Compare compare=Compare())
IntrusiveBinarySearchTree (const IntrusiveBinarySearchTree &)=delete
IntrusiveBinarySearchTree (IntrusiveBinarySearchTree &&other)
IntrusiveBinarySearchTree & operator= (const IntrusiveBinarySearchTree &)=delete
IntrusiveBinarySearchTree & operator= (IntrusiveBinarySearchTree &&other)
~IntrusiveBinarySearchTree ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
size_type size () const
bool empty () const
iterator find (const_reference value)
const_iterator find (const_reference value) const
bool has_element (const_reference value) const
bool invariant_holds () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
reference root ()
const_reference root () const
void insert_in_tree (reference value)
std::tuple< T *, T *, T ** > remove_from_tree (reference value)
T * find_in_tree (const_reference value) const
T * sibling (const_reference node)
T *& parent_child_reference (reference node, const_reference child)
void right_rotate (reference top)
void left_rotate (reference top)
void clear ()
void swap (IntrusiveBinarySearchTree &other)
bool operator== (const IntrusiveBinarySearchTree &other) const
bool operator!= (const IntrusiveBinarySearchTree &other) const
bool operator< (const IntrusiveBinarySearchTree &other) const
bool operator<= (const IntrusiveBinarySearchTree &other) const
bool operator> (const IntrusiveBinarySearchTree &other) const
bool operator>= (const IntrusiveBinarySearchTree &other) const
Private Member Functions
bool invariant_holds_for_each_path (const_reference node, bool mustBeBlack, std::size_t blackLevels) const
Additional Inherited Members
Protected Member Functions inherited from infra::IntrusiveBinarySearchTree< T, Compare >
const T * RootNode () const
Detailed Description
template<class T, class Compare = std::less<T>>
class infra::IntrusiveSet< T, Compare >
Definition at line 40 of file IntrusiveSet.hpp.
Member Typedef Documentation
Colour
template<class T, class Compare = std::less<T>> typedef NodeType::Colour infra::IntrusiveSet< T, Compare >::Colour
Definition at line 57 of file IntrusiveSet.hpp.
const_iterator
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::const_iterator infra::IntrusiveSet< T, Compare >::const_iterator
Definition at line 50 of file IntrusiveSet.hpp.
const_pointer
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::const_pointer infra::IntrusiveSet< T, Compare >::const_pointer
Definition at line 48 of file IntrusiveSet.hpp.
const_reference
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::const_reference infra::IntrusiveSet< T, Compare >::const_reference
Definition at line 46 of file IntrusiveSet.hpp.
const_reverse_iterator
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::const_reverse_iterator infra::IntrusiveSet< T, Compare >::const_reverse_iterator
Definition at line 52 of file IntrusiveSet.hpp.
difference_type
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::difference_type infra::IntrusiveSet< T, Compare >::difference_type
Definition at line 53 of file IntrusiveSet.hpp.
iterator
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::iterator infra::IntrusiveSet< T, Compare >::iterator
Definition at line 49 of file IntrusiveSet.hpp.
NodeType
template<class T, class Compare = std::less<T>> typedef detail::IntrusiveSetNode<T> infra::IntrusiveSet< T, Compare >::NodeType
Definition at line 56 of file IntrusiveSet.hpp.
pointer
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::pointer infra::IntrusiveSet< T, Compare >::pointer
Definition at line 47 of file IntrusiveSet.hpp.
reference
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::reference infra::IntrusiveSet< T, Compare >::reference
Definition at line 45 of file IntrusiveSet.hpp.
reverse_iterator
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::reverse_iterator infra::IntrusiveSet< T, Compare >::reverse_iterator
Definition at line 51 of file IntrusiveSet.hpp.
size_type
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::size_type infra::IntrusiveSet< T, Compare >::size_type
Definition at line 54 of file IntrusiveSet.hpp.
value_type
template<class T, class Compare = std::less<T>> typedef IntrusiveBinarySearchTree<T, Compare>::value_type infra::IntrusiveSet< T, Compare >::value_type
Definition at line 44 of file IntrusiveSet.hpp.
Constructor & Destructor Documentation
IntrusiveSet() [1/4]
template<class T , class Compare > infra::IntrusiveSet< T, Compare >::IntrusiveSet (const Compare & compare = Compare()) explicit
Definition at line 92 of file IntrusiveSet.hpp.
         : IntrusiveBinarySearchTree<T, Compare>(compare)
     {}
IntrusiveSet() [2/4]
template<class T , class Compare > template<class InputIterator > infra::IntrusiveSet< T, Compare >::IntrusiveSet (InputIterator first, InputIterator last, const Compare & comp = Compare())
Definition at line 98 of file IntrusiveSet.hpp.
References infra::IntrusiveSet< T, Compare >::assign().
         : IntrusiveBinarySearchTree<T, Compare>(compare)
     {
         assign(first, last);
     }
IntrusiveSet() [3/4]
template<class T, class Compare = std::less<T>> infra::IntrusiveSet< T, Compare >::IntrusiveSet (const IntrusiveSet< T, Compare > &) delete
IntrusiveSet() [4/4]
template<class T , class Compare > infra::IntrusiveSet< T, Compare >::IntrusiveSet (IntrusiveSet< T, Compare > && other)
Definition at line 105 of file IntrusiveSet.hpp.
     {
         *this = std::move(other);
     }
~IntrusiveSet()
template<class T , class Compare > infra::IntrusiveSet< T, Compare >::~IntrusiveSet ()
Definition at line 119 of file IntrusiveSet.hpp.
     {}
Member Function Documentation
assign()
template<class T , class Compare > template<class InputIterator > void infra::IntrusiveSet< T, Compare >::assign (InputIterator first, InputIterator last)
Definition at line 389 of file IntrusiveSet.hpp.
Referenced by infra::IntrusiveSet< T, Compare >::IntrusiveSet().
     {
         this->clear();
         for (; first != last; ++first)                                                                                  //TICS !CFL#018
             insert(*first);
     }
erase()
template<class T , class Compare > void infra::IntrusiveSet< T, Compare >::erase (const_reference value)
Definition at line 231 of file IntrusiveSet.hpp.
References value.
     {
         // See http://www.geeksforgeeks.org/red-black-tree-set-3-delete-2/ for the algorithm
         T& node = const_cast<reference>(value);
         T* doubleBlackParent = nullptr;
         T** doubleBlack = nullptr;
         {
             // Step 1
             bool twoChildren = value.left && value.right;                                                               //TICS !OLC#006
             T* valueParent = value.parent;                                                                              //TICS !OLC#006
             T* replacement;
             T* oldReplacementParent;
             T** oldReplacement;
             std::tie(replacement, oldReplacementParent, oldReplacement) = remove_from_tree(const_cast<T&>(value));
             if (oldReplacementParent != nullptr)
             {
                 bool firstRed = replacement && replacement->colour == Colour::red;
                 bool secondRed = oldReplacementParent == &value
                                     ? twoChildren ? *oldReplacement && (*oldReplacement)->colour == Colour::red : value.colour == Colour::red
                                     : *oldReplacement && (*oldReplacement)->colour == Colour::red;
                 if (!firstRed && !secondRed)
                 {
                     if (oldReplacementParent != &value)
                     {
                         doubleBlackParent = oldReplacementParent;
                         doubleBlack = oldReplacement;
                     }
                     else if (twoChildren)
                     {
                         doubleBlackParent = replacement;
                         doubleBlack = oldReplacement == &value.left ? &replacement->left : &replacement->right;
                     }
                     else
                     {
                         doubleBlackParent = valueParent;
                         doubleBlack = oldReplacement == &valueParent->left ? &valueParent->left : &valueParent->right;
                     }
                 }
                 else
                 {
                     // Step 2, the simple case: either u or v is red (colour is copied below,
                     // a node being deleted with only one child is always black, since as red it cannot have a red child (two consecutive reds),
                     // nor a black child (one leaf and one black child is a violation of balance)
                 }
             }
             if (replacement != nullptr)
             {
                 if (oldReplacement != nullptr && *oldReplacement != nullptr)
                     (*oldReplacement)->colour = replacement->colour;
                 replacement->colour = value.colour;
             }
         }
         while (doubleBlackParent != nullptr)
         {
             T* doubleBlackSibling = &doubleBlackParent->left == doubleBlack ? doubleBlackParent->right : doubleBlackParent->left;
             if (doubleBlackSibling->colour == Colour::black
                 && ((doubleBlackSibling->left && doubleBlackSibling->left->colour == Colour::red) || (doubleBlackSibling->right && doubleBlackSibling->right->colour == Colour::red)))
             {
                 T** redNephew = (doubleBlackSibling->left && doubleBlackSibling->left->colour == Colour::red) ? &doubleBlackSibling->left : &doubleBlackSibling->right;
                 (*redNephew)->colour = Colour::black;
                 if (doubleBlackSibling == doubleBlackParent->left && redNephew == &doubleBlackSibling->left)
                 {
                     // Step 3.2 a i
                     right_rotate(*doubleBlackParent);
                     doubleBlackSibling->colour = doubleBlackParent->colour;
                     doubleBlackParent->colour = Colour::black;
                 }
                 else if (doubleBlackSibling == doubleBlackParent->left && redNephew == &doubleBlackSibling->right)
                 {
                     // Step 3.2 a ii
                     (*redNephew)->colour = doubleBlackParent->colour;
                     doubleBlackParent->colour = Colour::black;
                     doubleBlackSibling->colour = Colour::black;
                     left_rotate(*doubleBlackSibling);
                     right_rotate(*doubleBlackParent);
                 }
                 else if (doubleBlackSibling == doubleBlackParent->right && redNephew == &doubleBlackSibling->right)
                 {
                     // Step 3.2 a iii
                     left_rotate(*doubleBlackParent);
                     doubleBlackSibling->colour = doubleBlackParent->colour;
                     doubleBlackParent->colour = Colour::black;
                 }
                 else if (doubleBlackSibling == doubleBlackParent->right && redNephew == &doubleBlackSibling->left)
                 {
                     // Step 3.2 a iv
                     (*redNephew)->colour = doubleBlackParent->colour;
                     doubleBlackParent->colour = Colour::black;
                     doubleBlackSibling->colour = Colour::black;
                     right_rotate(*doubleBlackSibling);
                     left_rotate(*doubleBlackParent);
                 }
                 else
                     abort();
                 doubleBlackParent = nullptr;
             }
             else if (doubleBlackSibling->colour == Colour::black
                 && (!doubleBlackSibling->left || doubleBlackSibling->left->colour == Colour::black) && (!doubleBlackSibling->right || doubleBlackSibling->right->colour == Colour::black))
             {
                 // Step 3.2 b
                 doubleBlackSibling->colour = Colour::red;
                 if (doubleBlackParent->colour == Colour::red)
                 {
                     doubleBlackParent->colour = Colour::black;
                     doubleBlackParent = nullptr;
                 }
                 else
                 {
                     if (doubleBlackParent->parent != nullptr)
                         if (doubleBlackParent->parent->left == doubleBlackParent)
                             doubleBlack = &doubleBlackParent->parent->left;
                         else
                             doubleBlack = &doubleBlackParent->parent->right;
                     doubleBlackParent = doubleBlackParent->parent;
                 }
             }
             else if (doubleBlackSibling->colour == Colour::red)
             {
                 doubleBlackSibling->colour = Colour::black;
                 doubleBlackParent->colour = Colour::red;
                 if (doubleBlackSibling == doubleBlackParent->left)
                 {
                     // Step 3.2 c i
                     right_rotate(*doubleBlackParent);
                     doubleBlack = &doubleBlackParent->right;
                 }
                 else
                 {
                     // Step 3.2 c ii
                     left_rotate(*doubleBlackParent);
                     doubleBlack = &doubleBlackParent->left;
                 }
             }
             else
                 abort();
         }
         if (this->RootNode() != nullptr)
             const_cast<T*>(this->RootNode())->colour = Colour::black;
     }
insert()
template<class T , class Compare > void infra::IntrusiveSet< T, Compare >::insert (const_reference value)
Definition at line 167 of file IntrusiveSet.hpp.
References value.
     {
         assert(!value.parent);
         assert(!value.left);
         assert(!value.right);
         T* node = const_cast<pointer>(&value);
         insert_in_tree(*node);
         node->colour = Colour::red;
         while (node != this->RootNode() && node->parent->colour == Colour::red)
         {
             if (node->parent == node->parent->parent->left)
             {
                 T* uncle = node->parent->parent->right;
                 if (uncle && uncle->colour == Colour::red)
                 {
                     node->parent->colour = Colour::black;
                     uncle->colour = Colour::black;
                     node->parent->parent->colour = Colour::red;
                     node = node->parent->parent;
                 }
                 else
                 {
                     if (node == node->parent->right)
                     {
                         node = node->parent;
                         left_rotate(*node);
                     }
                     node->parent->colour = Colour::black;
                     node->parent->parent->colour = Colour::red;
                     right_rotate(*node->parent->parent);
                 }
             }
             else
             {
                 T* uncle = node->parent->parent->left;
                 if (uncle && uncle->colour == Colour::red)
                 {
                     node->parent->colour = Colour::black;
                     uncle->colour = Colour::black;
                     node->parent->parent->colour = Colour::red;
                     node = node->parent->parent;
                 }
                 else
                 {
                     if (node == node->parent->left)
                     {
                         node = node->parent;
                         right_rotate(*node);
                     }
                     node->parent->colour = Colour::black;
                     node->parent->parent->colour = Colour::red;
                     left_rotate(*node->parent->parent);
                 }
             }
         }
         const_cast<T*>(this->RootNode())->colour = Colour::black;
     }
invariant_holds()
template<class T , class Compare > bool infra::IntrusiveSet< T, Compare >::invariant_holds () const
Definition at line 123 of file IntrusiveSet.hpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), infra::detail::IntrusiveBinarySearchTreeNode< T >::left, and infra::detail::IntrusiveBinarySearchTreeNode< T >::right.
     {
         if (this->empty())
             return true;
         std::size_t blackLevels = 0;
         const NodeType* node = this->RootNode();
         while (node != nullptr)
         {
             if (node->colour != Colour::black && node->colour != Colour::red)
                 return false;
             if (node->colour == Colour::black)
                 ++blackLevels;
             if (!node->left)
                 node = node->right;
             else
                 node = node->left;
         }
         return (!this->RootNode() || invariant_holds_for_each_path(*this->RootNode(), true, blackLevels)) && IntrusiveBinarySearchTree<T, Compare>::invariant_holds();
     }
invariant_holds_for_each_path()
template<class T , class Compare > bool infra::IntrusiveSet< T, Compare >::invariant_holds_for_each_path (const_reference node, bool mustBeBlack, std::size_t blackLevels) const private
Definition at line 150 of file IntrusiveSet.hpp.
     {
         if (mustBeBlack && node.colour != Colour::black)
             return false;
         if (node.colour == Colour::black)
             --blackLevels;
         if (!node.left && !node.right)
             return blackLevels == 0;
         mustBeBlack = node.colour == Colour::red;
         return ((!node.left && blackLevels == 0) || (node.left && invariant_holds_for_each_path(*node.left, mustBeBlack, blackLevels)))
             && ((!node.right && blackLevels == 0) || (node.right && invariant_holds_for_each_path(*node.right, mustBeBlack, blackLevels)));
     }
operator=() [1/2]
template<class T, class Compare = std::less<T>> IntrusiveSet& infra::IntrusiveSet< T, Compare >::operator= (const IntrusiveSet< T, Compare > &) delete
operator=() [2/2]
template<class T , class Compare > IntrusiveSet< T, Compare > & infra::IntrusiveSet< T, Compare >::operator= (IntrusiveSet< T, Compare > && other)
Definition at line 111 of file IntrusiveSet.hpp.
     {
         static_cast<IntrusiveBinarySearchTree<T, Compare>&>(*this) = std::move(static_cast<IntrusiveBinarySearchTree<T, Compare>&>(other));
         return *this;
     }
swap()
template<class T , class Compare > void infra::IntrusiveSet< T, Compare >::swap (IntrusiveSet< T, Compare > & other)
Definition at line 397 of file IntrusiveSet.hpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::swap().
Referenced by infra::swap().
     {
         IntrusiveBinarySearchTree<T, Compare>::swap(other);
     }
The documentation for this class was generated from the following file:
IntrusiveSet.hpp