EMil: services::ConnectionLoopBackPeer Class Reference
services::ConnectionLoopBackPeer Class Reference
#include <ConnectionLoopBack.hpp>
Classes
class StreamReaderLoopBack
class StreamWriterLoopBack
Public Member Functions
ConnectionLoopBackPeer (ConnectionLoopBackPeer &peer, ConnectionLoopBack &loopBack)
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Private Member Functions
void TryAllocateSendStream ()
Private Attributes
ConnectionLoopBackPeer & peer
ConnectionLoopBack & loopBack
infra::BoundedDeque< uint8_t >::WithMaxSize< 1024 > sendBuffer
infra::SharedOptional< StreamWriterLoopBack > streamWriter
std::size_t requestedSendSize = 0
infra::SharedOptional< StreamReaderLoopBack > streamReader
Additional Inherited Members
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Detailed Description
Definition at line 14 of file ConnectionLoopBack.hpp.
Constructor & Destructor Documentation
ConnectionLoopBackPeer()
services::ConnectionLoopBackPeer::ConnectionLoopBackPeer (ConnectionLoopBackPeer & peer, ConnectionLoopBack & loopBack)
Definition at line 6 of file ConnectionLoopBack.cpp.
         : peer(peer)
         , loopBack(loopBack)
     {}
Member Function Documentation
AbortAndDestroy()
void services::ConnectionLoopBackPeer::AbortAndDestroy () override virtual
Implements services::Connection.
Definition at line 43 of file ConnectionLoopBack.cpp.
References peer, and services::Connection::ResetOwnership().
     {
         ResetOwnership();
         peer.ResetOwnership();
     }
AckReceived()
void services::ConnectionLoopBackPeer::AckReceived () override virtual
Implements services::Connection.
Definition at line 29 of file ConnectionLoopBack.cpp.
References peer, requestedSendSize, streamReader, and TryAllocateSendStream().
     {
         streamReader->ConsumeRead();
         if (peer.requestedSendSize != 0)
             peer.TryAllocateSendStream();
     }
CloseAndDestroy()
void services::ConnectionLoopBackPeer::CloseAndDestroy () override virtual
Implements services::Connection.
Definition at line 37 of file ConnectionLoopBack.cpp.
References peer, and services::Connection::ResetOwnership().
     {
         ResetOwnership();
         peer.ResetOwnership();
     }
MaxSendStreamSize()
std::size_t services::ConnectionLoopBackPeer::MaxSendStreamSize () const override virtual
Implements services::Connection.
Definition at line 19 of file ConnectionLoopBack.cpp.
References infra::BoundedDeque< T >::max_size(), and sendBuffer.
     {
         return sendBuffer.max_size();
     }
ReceiveStream()
infra::SharedPtr< infra::StreamReaderWithRewinding > services::ConnectionLoopBackPeer::ReceiveStream () override virtual
Implements services::Connection.
Definition at line 24 of file ConnectionLoopBack.cpp.
References peer, and streamReader.
     {
         return streamReader.Emplace(peer);
     }
RequestSendStream()
void services::ConnectionLoopBackPeer::RequestSendStream (std::size_t sendSize) override virtual
Implements services::Connection.
Definition at line 11 of file ConnectionLoopBack.cpp.
References requestedSendSize, streamWriter, and TryAllocateSendStream().
     {
         assert(requestedSendSize == 0);
         assert(streamWriter.Allocatable());
         requestedSendSize = sendSize;
         TryAllocateSendStream();
     }
TryAllocateSendStream()
void services::ConnectionLoopBackPeer::TryAllocateSendStream () private
Definition at line 49 of file ConnectionLoopBack.cpp.
References infra::Subject< ConnectionObserver >::GetObserver(), infra::Subject< ConnectionObserver >::HasObserver(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), loopBack, infra::BoundedDeque< T >::max_size(), requestedSendSize, infra::EventDispatcherWithWeakPtrWorker::Schedule(), sendBuffer, infra::EnableSharedFromThis< T >::SharedFromThis(), infra::BoundedDeque< T >::size(), and streamWriter.
Referenced by AckReceived(), and RequestSendStream().
     {
         assert(streamWriter.Allocatable());
         if (sendBuffer.max_size() - sendBuffer.size() >= requestedSendSize)
         {
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([this](const infra::SharedPtr<ConnectionLoopBack>& loopBack)
             {
                 if (HasObserver())
                 {
                     infra::SharedPtr<infra::StreamWriter> writer = streamWriter.Emplace(*this);
                     GetObserver().SendStreamAvailable(std::move(writer));
                 }
             }, loopBack.SharedFromThis());
             requestedSendSize = 0;
         }
     }
Member Data Documentation
loopBack
ConnectionLoopBack& services::ConnectionLoopBackPeer::loopBack private
Definition at line 61 of file ConnectionLoopBack.hpp.
Referenced by TryAllocateSendStream(), and services::ConnectionLoopBackPeer::StreamWriterLoopBack::~StreamWriterLoopBack().
peer
ConnectionLoopBackPeer& services::ConnectionLoopBackPeer::peer private
Definition at line 60 of file ConnectionLoopBack.hpp.
Referenced by AbortAndDestroy(), AckReceived(), CloseAndDestroy(), ReceiveStream(), and services::ConnectionLoopBackPeer::StreamWriterLoopBack::~StreamWriterLoopBack().
requestedSendSize
std::size_t services::ConnectionLoopBackPeer::requestedSendSize = 0 private
Definition at line 64 of file ConnectionLoopBack.hpp.
Referenced by AckReceived(), RequestSendStream(), and TryAllocateSendStream().
sendBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<1024> services::ConnectionLoopBackPeer::sendBuffer private
Definition at line 62 of file ConnectionLoopBack.hpp.
Referenced by MaxSendStreamSize(), and TryAllocateSendStream().
streamReader
infra::SharedOptional<StreamReaderLoopBack> services::ConnectionLoopBackPeer::streamReader private
Definition at line 65 of file ConnectionLoopBack.hpp.
Referenced by AckReceived(), and ReceiveStream().
streamWriter
infra::SharedOptional<StreamWriterLoopBack> services::ConnectionLoopBackPeer::streamWriter private
Definition at line 63 of file ConnectionLoopBack.hpp.
Referenced by RequestSendStream(), and TryAllocateSendStream().
The documentation for this class was generated from the following files:
ConnectionLoopBack.hpp
ConnectionLoopBack.cpp