EMil: infra::TextInputStream Class Reference
infra::TextInputStream Class Reference
#include <InputStream.hpp>
Classes
class WithErrorPolicy
class WithReader
Public Member Functions
DataInputStream operator>> (Data)
TextInputStream operator>> (Hex)
TextInputStream operator>> (Width width)
TextInputStream & operator>> (MemoryRange< char > text)
TextInputStream & operator>> (char &c)
TextInputStream & operator>> (int8_t &v)
TextInputStream & operator>> (int16_t &v)
TextInputStream & operator>> (int32_t &v)
TextInputStream & operator>> (int64_t &v)
TextInputStream & operator>> (uint8_t &v)
TextInputStream & operator>> (uint16_t &v)
TextInputStream & operator>> (uint32_t &v)
TextInputStream & operator>> (uint64_t &v)
TextInputStream & operator>> (float &v)
TextInputStream & operator>> (BoundedString &v)
TextInputStream & operator>> (const char *literal)
InputStream (StreamReader &reader, StreamErrorPolicy &errorPolicy)
Public Member Functions inherited from infra::InputStream
InputStream (StreamReader &reader, StreamErrorPolicy &errorPolicy)
bool Empty () const
std::size_t Available () const
ConstByteRange ContiguousRange (std::size_t max=std::numeric_limits< std::size_t >::max()) const
ConstByteRange PeekContiguousRange (std::size_t start=0) const
void Consume (std::size_t amount)
bool Failed () const
StreamReader & Reader () const
StreamErrorPolicy & ErrorPolicy () const
Private Member Functions
void SkipSpaces ()
void Read (int32_t &v)
void Read (int64_t &v)
void Read (uint32_t &v)
void Read (uint64_t &v)
void ReadAsDecimal (int32_t &v)
void ReadAsDecimal (int64_t &v)
void ReadAsDecimal (uint32_t &v)
void ReadAsDecimal (uint64_t &v)
void ReadAsHex (int32_t &v)
void ReadAsHex (int64_t &v)
void ReadAsHex (uint32_t &v)
void ReadAsHex (uint64_t &v)
Private Attributes
bool isDecimal = true
infra::Optional< std::size_t > width
Additional Inherited Members
Protected Member Functions inherited from infra::InputStream
~InputStream ()=default
Detailed Description
Definition at line 85 of file InputStream.hpp.
Member Function Documentation
InputStream()
infra::InputStream::InputStream
Definition at line 6 of file InputStream.cpp.
         : reader(reader)
         , errorPolicy(errorPolicy)
     {}
operator>>() [1/16]
DataInputStream infra::TextInputStream::operator>> (Data)
Definition at line 73 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), and infra::InputStream::Reader().
Referenced by operator>>().
     {
         return DataInputStream(Reader(), ErrorPolicy());
     }
operator>>() [2/16]
TextInputStream infra::TextInputStream::operator>> (Hex)
Definition at line 78 of file InputStream.cpp.
References isDecimal.
     {
         TextInputStream res(*this);
         res.isDecimal = false;
         return res;
     }
operator>>() [3/16]
TextInputStream infra::TextInputStream::operator>> (Width width)
Definition at line 85 of file InputStream.cpp.
References width.
     {
         TextInputStream res(*this);
         res.width = width.width;
         return res;
     }
operator>>() [4/16]
TextInputStream & infra::TextInputStream::operator>> (MemoryRange< char > text)
Definition at line 92 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::InputStream::Reader(), infra::ReinterpretCastByteRange(), and infra::text.
     {
         Reader().Extract(ReinterpretCastByteRange(text), ErrorPolicy());
         return *this;
     }
operator>>() [5/16]
TextInputStream & infra::TextInputStream::operator>> (char & c)
Definition at line 104 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), and infra::InputStream::Reader().
     {
         Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
         return *this;
     }
operator>>() [6/16]
TextInputStream & infra::TextInputStream::operator>> (int8_t & v)
Definition at line 110 of file InputStream.cpp.
References Read().
     {
         int32_t v32;
         Read(v32);
         v = static_cast<int8_t>(v32);
         return *this;
     }
operator>>() [7/16]
TextInputStream & infra::TextInputStream::operator>> (int16_t & v)
Definition at line 118 of file InputStream.cpp.
References Read().
     {
         int32_t v32;
         Read(v32);
         v = static_cast<int16_t>(v32);
         return *this;
     }
operator>>() [8/16]
TextInputStream & infra::TextInputStream::operator>> (int32_t & v)
Definition at line 126 of file InputStream.cpp.
References Read().
     {
         Read(v);
         return *this;
     }
operator>>() [9/16]
TextInputStream & infra::TextInputStream::operator>> (int64_t & v)
Definition at line 132 of file InputStream.cpp.
References Read().
     {
         Read(v);
         return *this;
     }
operator>>() [10/16]
TextInputStream & infra::TextInputStream::operator>> (uint8_t & v)
Definition at line 138 of file InputStream.cpp.
References Read().
     {
         uint32_t v32;
         Read(v32);
         v = static_cast<uint8_t>(v32);
         return *this;
     }
operator>>() [11/16]
TextInputStream & infra::TextInputStream::operator>> (uint16_t & v)
Definition at line 146 of file InputStream.cpp.
References Read().
     {
         uint32_t v32;
         Read(v32);
         v = static_cast<uint16_t>(v32);
         return *this;
     }
operator>>() [12/16]
TextInputStream & infra::TextInputStream::operator>> (uint32_t & v)
Definition at line 154 of file InputStream.cpp.
References Read().
     {
         Read(v);
         return *this;
     }
operator>>() [13/16]
TextInputStream & infra::TextInputStream::operator>> (uint64_t & v)
Definition at line 160 of file InputStream.cpp.
References Read().
     {
         Read(v);
         return *this;
     }
operator>>() [14/16]
TextInputStream & infra::TextInputStream::operator>> (float & v)
Definition at line 166 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), operator>>(), infra::StreamReader::Peek(), infra::InputStream::Reader(), and infra::InputStream::reader.
     {
         int32_t integer = 0;
         operator>>(integer);
         uint32_t frac = 0;
         int32_t div = (integer < 0) ? -1 : 1;
         infra::StreamReader& reader = Reader();
         char c = static_cast<char>(reader.Peek(ErrorPolicy()));
         if (c == '.')
         {
             reader.Extract(infra::MakeByteRange(c), ErrorPolicy());
             c = static_cast<char>(reader.Peek(ErrorPolicy()));
             while (c >= '0' && c <= '9')
             {
                 div *= 10;
                 frac = frac * 10 + static_cast<uint8_t>(c - '0');
                 reader.Extract(infra::MakeByteRange(c), ErrorPolicy());
                 c = static_cast<char>(reader.Peek(ErrorPolicy()));
             }
         }
         v = static_cast<float>(frac);
         v /= div;
         v += integer;
         return *this;
     }
operator>>() [15/16]
TextInputStream & infra::TextInputStream::operator>> (BoundedString & v)
Definition at line 98 of file InputStream.cpp.
References infra::BoundedStringBase< T >::begin(), and infra::BoundedStringBase< T >::end().
     {
         *this >> MemoryRange<char>(v.begin(), v.end());
         return *this;
     }
operator>>() [16/16]
TextInputStream & infra::TextInputStream::operator>> (const char * literal)
Definition at line 194 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::InputStream::Reader(), and infra::StreamErrorPolicy::ReportResult().
     {
         while (*literal != '\0')
         {
             char c;
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
             ErrorPolicy().ReportResult(c == *literal);
             ++literal;
         }
         return *this;
     }
Read() [1/4]
void infra::TextInputStream::Read (int32_t & v) private
Definition at line 217 of file InputStream.cpp.
References isDecimal, ReadAsDecimal(), and ReadAsHex().
Referenced by operator>>().
     {
         if (isDecimal)
             ReadAsDecimal(v);
         else
             ReadAsHex(v);
     }
Read() [2/4]
void infra::TextInputStream::Read (int64_t & v) private
Definition at line 225 of file InputStream.cpp.
References isDecimal, ReadAsDecimal(), and ReadAsHex().
     {
         if (isDecimal)
             ReadAsDecimal(v);
         else
             ReadAsHex(v);
     }
Read() [3/4]
void infra::TextInputStream::Read (uint32_t & v) private
Definition at line 233 of file InputStream.cpp.
References isDecimal, ReadAsDecimal(), and ReadAsHex().
     {
         if (isDecimal)
             ReadAsDecimal(v);
         else
             ReadAsHex(v);
     }
Read() [4/4]
void infra::TextInputStream::Read (uint64_t & v) private
Definition at line 241 of file InputStream.cpp.
References isDecimal, ReadAsDecimal(), and ReadAsHex().
     {
         if (isDecimal)
             ReadAsDecimal(v);
         else
             ReadAsHex(v);
     }
ReadAsDecimal() [1/4]
void infra::TextInputStream::ReadAsDecimal (int32_t & v) private
Definition at line 249 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), infra::InputStream::Reader(), and SkipSpaces().
Referenced by Read(), and ReadAsDecimal().
     {
         SkipSpaces();
         char c = Reader().Peek(ErrorPolicy());
         if (c == '-')
         {
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
             v = -1;
         }
         else
             v = 1;
         uint32_t vp = 0;
         ReadAsDecimal(vp);
         v *= vp;
     }
ReadAsDecimal() [2/4]
void infra::TextInputStream::ReadAsDecimal (int64_t & v) private
Definition at line 267 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), ReadAsDecimal(), infra::InputStream::Reader(), and SkipSpaces().
     {
         SkipSpaces();
         char c = Reader().Peek(ErrorPolicy());
         if (c == '-')
         {
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
             v = -1;
         }
         else
             v = 1;
         uint64_t vp = 0;
         ReadAsDecimal(vp);
         v *= vp;
     }
ReadAsDecimal() [3/4]
void infra::TextInputStream::ReadAsDecimal (uint32_t & v) private
Definition at line 285 of file InputStream.cpp.
References infra::StreamReader::Empty(), infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), infra::InputStream::Reader(), infra::StreamErrorPolicy::ReportResult(), SkipSpaces(), infra::Optional< T >::ValueOr(), and width.
     {
         SkipSpaces();
         v = 0;
         for (std::size_t i = 0; (i != width.ValueOr(std::numeric_limits<std::size_t>::max()) && !Reader().Empty()) || i == 0; ++i)
         {
             char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
             if (c >= '0' && c <= '9')
                 v = v * 10 + static_cast<uint32_t>(c - '0');
             else
             {
                 ErrorPolicy().ReportResult(i > 0);
                 break;
             }
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
         }
     }
ReadAsDecimal() [4/4]
void infra::TextInputStream::ReadAsDecimal (uint64_t & v) private
Definition at line 306 of file InputStream.cpp.
References infra::StreamReader::Empty(), infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), infra::InputStream::Reader(), infra::StreamErrorPolicy::ReportResult(), SkipSpaces(), infra::Optional< T >::ValueOr(), and width.
     {
         SkipSpaces();
         v = 0;
         for (std::size_t i = 0; (i != width.ValueOr(std::numeric_limits<std::size_t>::max()) && !Reader().Empty()) || i == 0; ++i)
         {
             char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
             if (c >= '0' && c <= '9')
                 v = v * 10 + static_cast<uint64_t>(c - '0');
             else
             {
                 ErrorPolicy().ReportResult(i > 0);
                 break;
             }
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
         }
     }
ReadAsHex() [1/4]
void infra::TextInputStream::ReadAsHex (int32_t & v) private
Definition at line 327 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), infra::InputStream::Reader(), and SkipSpaces().
Referenced by Read(), and ReadAsHex().
     {
         SkipSpaces();
         char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
         if (c == '-')
         {
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
             v = -1;
         }
         else
             v = 1;
         uint32_t vp = 0;
         ReadAsHex(vp);
         v *= vp;
     }
ReadAsHex() [2/4]
void infra::TextInputStream::ReadAsHex (int64_t & v) private
Definition at line 344 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), ReadAsHex(), infra::InputStream::Reader(), and SkipSpaces().
     {
         SkipSpaces();
         char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
         if (c == '-')
         {
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
             v = -1;
         }
         else
             v = 1;
         uint64_t vp = 0;
         ReadAsHex(vp);
         v *= vp;
     }
ReadAsHex() [3/4]
void infra::TextInputStream::ReadAsHex (uint32_t & v) private
Definition at line 361 of file InputStream.cpp.
References infra::StreamReader::Empty(), infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), infra::InputStream::Reader(), infra::StreamErrorPolicy::ReportResult(), SkipSpaces(), infra::Optional< T >::ValueOr(), and width.
     {
         SkipSpaces();
         v = 0;
         for (std::size_t i = 0; (i != width.ValueOr(std::numeric_limits<std::size_t>::max()) && !Reader().Empty()) || i == 0; ++i)
         {
             char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
             if (c >= '0' && c <= '9')
                 v = (v << 4) + static_cast<uint32_t>(c - '0');
             else if (c >= 'a' && c <= 'f')
                 v = (v << 4) + static_cast<uint32_t>(c - 'a') + 10;
             else if (c >= 'A' && c <= 'F')
                 v = (v << 4) + static_cast<uint32_t>(c - 'A') + 10;
             else
             {
                 ErrorPolicy().ReportResult(i > 0);
                 break;
             }
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
         }
     }
ReadAsHex() [4/4]
void infra::TextInputStream::ReadAsHex (uint64_t & v) private
Definition at line 387 of file InputStream.cpp.
References infra::StreamReader::Empty(), infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), infra::InputStream::Reader(), infra::StreamErrorPolicy::ReportResult(), SkipSpaces(), infra::Optional< T >::ValueOr(), and width.
     {
         SkipSpaces();
         v = 0;
         for (std::size_t i = 0; (i != width.ValueOr(std::numeric_limits<std::size_t>::max()) && !Reader().Empty()) || i == 0; ++i)
         {
             char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
             if (c >= '0' && c <= '9')
                 v = (v << 4) + static_cast<uint64_t>(c - '0');
             else if (c >= 'a' && c <= 'f')
                 v = (v << 4) + static_cast<uint64_t>(c - 'a') + 10;
             else if (c >= 'A' && c <= 'F')
                 v = (v << 4) + static_cast<uint64_t>(c - 'A') + 10;
             else
             {
                 ErrorPolicy().ReportResult(i > 0);
                 break;
             }
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
         }
     }
SkipSpaces()
void infra::TextInputStream::SkipSpaces () private
Definition at line 207 of file InputStream.cpp.
References infra::InputStream::ErrorPolicy(), infra::StreamReader::Extract(), infra::MakeByteRange(), infra::StreamReader::Peek(), and infra::InputStream::Reader().
Referenced by ReadAsDecimal(), and ReadAsHex().
     {
         char c = static_cast<char>(Reader().Peek(ErrorPolicy()));
         while (c == ' ')
         {
             Reader().Extract(infra::MakeByteRange(c), ErrorPolicy());
             c = static_cast<char>(Reader().Peek(ErrorPolicy()));
         }
     }
Member Data Documentation
isDecimal
bool infra::TextInputStream::isDecimal = true private
Definition at line 128 of file InputStream.hpp.
Referenced by operator>>(), and Read().
width
infra::Optional<std::size_t> infra::TextInputStream::width private
Definition at line 129 of file InputStream.hpp.
Referenced by operator>>(), ReadAsDecimal(), and ReadAsHex().
The documentation for this class was generated from the following files:
InputStream.hpp
InputStream.cpp