EMil: services::FlashDelayedInit Class Reference
services::FlashDelayedInit Class Reference
#include <FlashDelayedInit.hpp>
Public Member Functions
FlashDelayedInit (hal::Flash &master)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
void Initialized ()
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Private Attributes
hal::Flash & master
bool initialized = false
infra::AutoResetFunction< void(), SERVICES_FLASH_DELAYED_INIT_FUNCTION_EXTRA_SIZE > onInitialized
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 13 of file FlashDelayedInit.hpp.
Constructor & Destructor Documentation
FlashDelayedInit()
services::FlashDelayedInit::FlashDelayedInit (hal::Flash & master) explicit
Definition at line 5 of file FlashDelayedInit.cpp.
         : master(master)
     {}
Member Function Documentation
AddressOfSector()
uint32_t services::FlashDelayedInit::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 24 of file FlashDelayedInit.cpp.
References hal::Flash::AddressOfSector(), and master.
     {
         return master.AddressOfSector(sectorIndex);
     }
EraseSectors()
void services::FlashDelayedInit::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 45 of file FlashDelayedInit.cpp.
References hal::Flash::EraseSectors(), initialized, master, and onInitialized.
     {
         if (initialized)
             master.EraseSectors(beginIndex, endIndex, onDone);
         else
             onInitialized = [this, beginIndex, endIndex, onDone]() { master.EraseSectors(beginIndex, endIndex, onDone); };
     }
Initialized()
void services::FlashDelayedInit::Initialized ()
Definition at line 53 of file FlashDelayedInit.cpp.
References initialized, and onInitialized.
     {
         initialized = true;
         if (onInitialized)
             onInitialized();
     }
NumberOfSectors()
uint32_t services::FlashDelayedInit::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 9 of file FlashDelayedInit.cpp.
References master, and hal::Flash::NumberOfSectors().
     {
         return master.NumberOfSectors();
     }
ReadBuffer()
void services::FlashDelayedInit::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 37 of file FlashDelayedInit.cpp.
References initialized, master, onInitialized, and hal::Flash::ReadBuffer().
     {
         if (initialized)
             master.ReadBuffer(buffer, address, onDone);
         else
             onInitialized = [this, buffer, address, onDone]() { master.ReadBuffer(buffer, address, onDone); };
     }
SectorOfAddress()
uint32_t services::FlashDelayedInit::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 19 of file FlashDelayedInit.cpp.
References master, and hal::Flash::SectorOfAddress().
     {
         return master.SectorOfAddress(address);
     }
SizeOfSector()
uint32_t services::FlashDelayedInit::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 14 of file FlashDelayedInit.cpp.
References master, and hal::Flash::SizeOfSector().
     {
         return master.SizeOfSector(sectorIndex);
     }
WriteBuffer()
void services::FlashDelayedInit::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 29 of file FlashDelayedInit.cpp.
References initialized, master, onInitialized, and hal::Flash::WriteBuffer().
     {
         if (initialized)
             master.WriteBuffer(buffer, address, onDone);
         else
             onInitialized = [this, buffer, address, onDone]() { master.WriteBuffer(buffer, address, onDone); };
     }
Member Data Documentation
initialized
bool services::FlashDelayedInit::initialized = false private
Definition at line 34 of file FlashDelayedInit.hpp.
Referenced by EraseSectors(), Initialized(), ReadBuffer(), and WriteBuffer().
master
hal::Flash& services::FlashDelayedInit::master private
Definition at line 33 of file FlashDelayedInit.hpp.
Referenced by AddressOfSector(), EraseSectors(), NumberOfSectors(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), and WriteBuffer().
onInitialized
infra::AutoResetFunction<void(), SERVICES_FLASH_DELAYED_INIT_FUNCTION_EXTRA_SIZE> services::FlashDelayedInit::onInitialized private
Definition at line 36 of file FlashDelayedInit.hpp.
Referenced by EraseSectors(), Initialized(), ReadBuffer(), and WriteBuffer().
The documentation for this class was generated from the following files:
FlashDelayedInit.hpp
FlashDelayedInit.cpp