EMil: hal::SynchronousQuadSpi Class Reference
hal::SynchronousQuadSpi Class Reference abstract
#include <SynchronousQuadSpi.hpp>
Classes
struct Header
Public Member Functions
SynchronousQuadSpi ()=default
SynchronousQuadSpi (const SynchronousQuadSpi &other)=delete
SynchronousQuadSpi & operator= (const SynchronousQuadSpi &other)=delete
virtual void SendData (const Header &header, infra::ConstByteRange data)=0
virtual void SendDataQuad (const Header &header, infra::ConstByteRange data)=0
virtual void ReceiveData (const Header &header, infra::ByteRange data)=0
virtual void ReceiveDataQuad (const Header &header, infra::ByteRange data)=0
Protected Member Functions
~SynchronousQuadSpi ()=default
Detailed Description
Definition at line 9 of file SynchronousQuadSpi.hpp.
Constructor & Destructor Documentation
SynchronousQuadSpi() [1/2]
hal::SynchronousQuadSpi::SynchronousQuadSpi () default
SynchronousQuadSpi() [2/2]
hal::SynchronousQuadSpi::SynchronousQuadSpi (const SynchronousQuadSpi & other) delete
~SynchronousQuadSpi()
hal::SynchronousQuadSpi::~SynchronousQuadSpi () protected default
Member Function Documentation
operator=()
SynchronousQuadSpi& hal::SynchronousQuadSpi::operator= (const SynchronousQuadSpi & other) delete
ReceiveData()
virtual void hal::SynchronousQuadSpi::ReceiveData (const Header & header, infra::ByteRange data) pure virtual
ReceiveDataQuad()
virtual void hal::SynchronousQuadSpi::ReceiveDataQuad (const Header & header, infra::ByteRange data) pure virtual
Referenced by services::SynchronousFlashQuadSpi::ReadBuffer(), and services::SynchronousFlashQuadSpi::ReadStatusRegister().
SendData()
virtual void hal::SynchronousQuadSpi::SendData (const Header & header, infra::ConstByteRange data) pure virtual
Referenced by services::SynchronousFlashQuadSpi::SynchronousFlashQuadSpi().
SendDataQuad()
virtual void hal::SynchronousQuadSpi::SendDataQuad (const Header & header, infra::ConstByteRange data) pure virtual
Referenced by services::SynchronousFlashQuadSpi::PageProgram(), and services::SynchronousFlashQuadSpi::WriteEnable().
The documentation for this class was generated from the following file:
SynchronousQuadSpi.hpp