EMil: ConfigurationStoreTest Class Reference
ConfigurationStoreTest Class Reference
Public Member Functions
ConfigurationStoreTest ()
MOCK_METHOD1 (OnLoaded, void(bool success))
void DontRecover ()
Public Attributes
infra::Function< void(bool success)> onRecoverDone
infra::Function< void()> onEraseDone
testing::StrictMock< ConfigurationBlobMock > configurationBlob1
testing::StrictMock< ConfigurationBlobMock > configurationBlob2
testing::StrictMock< Data > dataInstance
services::ConfigurationStoreImpl< DataProxy > configurationStore
Detailed Description
Definition at line 176 of file TestConfigurationStore.cpp.
Constructor & Destructor Documentation
ConfigurationStoreTest()
ConfigurationStoreTest::ConfigurationStoreTest () inline
Definition at line 180 of file TestConfigurationStore.cpp.
         : configurationStore(configurationBlob1, configurationBlob2)
     {}
Member Function Documentation
DontRecover()
void ConfigurationStoreTest::DontRecover () inline
Definition at line 186 of file TestConfigurationStore.cpp.
References configurationBlob1, configurationBlob2, configurationStore, onEraseDone, onRecoverDone, and services::ConfigurationStoreBase::Recover().
     {
         EXPECT_CALL(configurationBlob1, Recover(testing::_)).WillOnce(testing::SaveArg<0>(&onRecoverDone));
         configurationStore.Recover([this](bool success) { OnLoaded(success); });
         EXPECT_CALL(configurationBlob2, Recover(testing::_)).WillOnce(testing::SaveArg<0>(&onRecoverDone));
         onRecoverDone(false);
         EXPECT_CALL(configurationBlob1, Erase(testing::_)).WillOnce(testing::SaveArg<0>(&onEraseDone));
         onRecoverDone(false);
         EXPECT_CALL(*this, OnLoaded(false));
         onEraseDone();
     }
MOCK_METHOD1()
ConfigurationStoreTest::MOCK_METHOD1 (OnLoaded , void(bool success))
Member Data Documentation
configurationBlob1
testing::StrictMock<ConfigurationBlobMock> ConfigurationStoreTest::configurationBlob1
Definition at line 204 of file TestConfigurationStore.cpp.
Referenced by DontRecover().
configurationBlob2
testing::StrictMock<ConfigurationBlobMock> ConfigurationStoreTest::configurationBlob2
Definition at line 205 of file TestConfigurationStore.cpp.
Referenced by DontRecover().
configurationStore
services::ConfigurationStoreImpl<DataProxy> ConfigurationStoreTest::configurationStore
Definition at line 207 of file TestConfigurationStore.cpp.
Referenced by DontRecover().
dataInstance
testing::StrictMock<Data> ConfigurationStoreTest::dataInstance
Definition at line 206 of file TestConfigurationStore.cpp.
onEraseDone
infra::Function<void()> ConfigurationStoreTest::onEraseDone
Definition at line 203 of file TestConfigurationStore.cpp.
Referenced by DontRecover().
onRecoverDone
infra::Function<void(bool success)> ConfigurationStoreTest::onRecoverDone
Definition at line 202 of file TestConfigurationStore.cpp.
Referenced by DontRecover().
The documentation for this class was generated from the following file:
TestConfigurationStore.cpp