EMil: application::BinaryObject Class Reference
application::BinaryObject Class Reference
#include <BinaryObject.hpp>
Classes
struct LineContents
Public Member Functions
void AddHex (const std::vector< std::string > &data, uint32_t offset, const std::string &fileName)
void AddBinary (const std::vector< uint8_t > &data, uint32_t offset, const std::string &fileName)
const SparseVector< uint8_t > & Memory () const
Private Member Functions
void AddLine (const std::string &line, const std::string &fileName, int lineNumber)
void VerifyNotEndOfFile (const std::string &fileName, int lineNumber) const
void InsertLineContents (const LineContents &lineContents)
Private Attributes
SparseVector< uint8_t > memory
bool endOfFile = false
uint32_t linearAddress = 0
uint32_t offset = 0
Detailed Description
Definition at line 53 of file BinaryObject.hpp.
Member Function Documentation
AddBinary()
void application::BinaryObject::AddBinary (const std::vector< uint8_t > & data, uint32_t offset, const std::string & fileName)
Definition at line 53 of file BinaryObject.cpp.
References infra::data, application::SparseVector< T >::Insert(), memory, and offset.
     {
         for (auto byte: data)
         {
             memory.Insert(byte, offset);
             ++offset;
         }
     }
AddHex()
void application::BinaryObject::AddHex (const std::vector< std::string > & data, uint32_t offset, const std::string & fileName)
Definition at line 35 of file BinaryObject.cpp.
References AddLine(), infra::data, endOfFile, linearAddress, and offset.
Referenced by application::InputHex::InputHex().
     {
         linearAddress = 0;
         endOfFile = false;
         this->offset = offset;
         int lineNumber = 0;
         for (auto line : data)
         {
             ++lineNumber;
             if (!line.empty())
                 AddLine(line, fileName, lineNumber);
         }
         if (!endOfFile)
             throw NoEndOfFileException(fileName, lineNumber);
     }
AddLine()
void application::BinaryObject::AddLine (const std::string & line, const std::string & fileName, int lineNumber) private
Definition at line 67 of file BinaryObject.cpp.
References application::BinaryObject::LineContents::data, endOfFile, InsertLineContents(), linearAddress, application::BinaryObject::LineContents::recordType, and VerifyNotEndOfFile().
Referenced by AddHex().
     {
         VerifyNotEndOfFile(fileName, lineNumber);
         LineContents lineContents(line, fileName, lineNumber);
         switch (lineContents.recordType)
         {
             case 0:
                 InsertLineContents(lineContents);
                 break;
             case 1:
                 endOfFile = true;
                 break;
             case 2:
                 linearAddress = (lineContents.data[0] * 256 + lineContents.data[1]) << 4;
                 break;
             case 3:
                 // Ignore Start Segment Address because in hex file, the entrypoint of the program is not interesting
                 break;
             case 4:
                 assert(lineContents.data.size() == 2);
                 linearAddress = (lineContents.data[0] * 256 + lineContents.data[1]) << 16;
                 break;
             case 5:
                 // Ignore Start Linear Address because in hex file, the entrypoint of the program is not interesting
                 break;
             default:
                 throw UnknownRecordException(fileName, lineNumber);
         }
     }
InsertLineContents()
void application::BinaryObject::InsertLineContents (const LineContents & lineContents) private
Definition at line 104 of file BinaryObject.cpp.
References application::BinaryObject::LineContents::address, application::BinaryObject::LineContents::data, application::SparseVector< T >::Insert(), linearAddress, memory, and offset.
Referenced by AddLine().
     {
         for (std::size_t i = 0; i != lineContents.data.size(); ++i)
             memory.Insert(lineContents.data[i], linearAddress + offset + lineContents.address + i);
     }
Memory()
const SparseVector< uint8_t > & application::BinaryObject::Memory () const
Definition at line 62 of file BinaryObject.cpp.
References memory.
Referenced by application::InputHex::Image().
     {
         return memory;
     }
VerifyNotEndOfFile()
void application::BinaryObject::VerifyNotEndOfFile (const std::string & fileName, int lineNumber) const private
Definition at line 98 of file BinaryObject.cpp.
References endOfFile.
Referenced by AddLine().
     {
         if (endOfFile)
             throw DataAfterEndOfFileException(fileName, lineNumber);
     }
Member Data Documentation
endOfFile
bool application::BinaryObject::endOfFile = false private
Definition at line 78 of file BinaryObject.hpp.
Referenced by AddHex(), AddLine(), and VerifyNotEndOfFile().
linearAddress
uint32_t application::BinaryObject::linearAddress = 0 private
Definition at line 79 of file BinaryObject.hpp.
Referenced by AddHex(), AddLine(), and InsertLineContents().
memory
SparseVector<uint8_t> application::BinaryObject::memory private
Definition at line 77 of file BinaryObject.hpp.
Referenced by AddBinary(), InsertLineContents(), and Memory().
offset
uint32_t application::BinaryObject::offset = 0 private
Definition at line 80 of file BinaryObject.hpp.
Referenced by AddBinary(), AddHex(), and InsertLineContents().
The documentation for this class was generated from the following files:
BinaryObject.hpp
BinaryObject.cpp