EMil: hal::QuadSpi Class Reference
hal::QuadSpi Class Reference abstract
#include <QuadSpi.hpp>
Classes
struct Header
struct Lines
Public Member Functions
QuadSpi ()=default
QuadSpi (const QuadSpi &other)=delete
QuadSpi & operator= (const QuadSpi &other)=delete
virtual void SendData (const Header &header, infra::ConstByteRange data, Lines lines, const infra::Function< void()> &actionOnCompletion)=0
virtual void ReceiveData (const Header &header, infra::ByteRange data, Lines lines, const infra::Function< void()> &actionOnCompletion)=0
virtual void PollStatus (const Header &header, uint8_t nofBytes, uint32_t match, uint32_t mask, Lines lines, const infra::Function< void()> &actionOnCompletion)=0
Static Public Member Functions
static infra::BoundedVector< uint8_t >::WithMaxSize< 4 > AddressToVector (uint32_t address, uint8_t numberOfBytes)
static uint32_t VectorToAddress (infra::BoundedVector< uint8_t >::WithMaxSize< 4 > vector)
Protected Member Functions
~QuadSpi ()=default
Detailed Description
Definition at line 12 of file QuadSpi.hpp.
Constructor & Destructor Documentation
QuadSpi() [1/2]
hal::QuadSpi::QuadSpi () default
QuadSpi() [2/2]
hal::QuadSpi::QuadSpi (const QuadSpi & other) delete
~QuadSpi()
hal::QuadSpi::~QuadSpi () protected default
Member Function Documentation
AddressToVector()
infra::BoundedVector< uint8_t >::WithMaxSize< 4 > hal::QuadSpi::AddressToVector (uint32_t address, uint8_t numberOfBytes) static
Definition at line 47 of file QuadSpi.cpp.
Referenced by services::FlashQuadSpi::ConvertAddress(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), and services::FlashQuadSpiCypressFll::ReadBuffer().
     {
         infra::BoundedVector<uint8_t>::WithMaxSize<4> result;
         for (uint8_t i = 0; i != numberOfBytes; ++i)
         {
             result.push_back(static_cast<uint8_t>(address));
             address >>= 8;
         }
         return result;
     }
operator=()
QuadSpi& hal::QuadSpi::operator= (const QuadSpi & other) delete
PollStatus()
virtual void hal::QuadSpi::PollStatus (const Header & header, uint8_t nofBytes, uint32_t match, uint32_t mask, Lines lines, const infra::Function< void()> & actionOnCompletion) pure virtual
Referenced by services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress(), services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress(), and services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress().
ReceiveData()
virtual void hal::QuadSpi::ReceiveData (const Header & header, infra::ByteRange data, Lines lines, const infra::Function< void()> & actionOnCompletion) pure virtual
Referenced by services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiMicronN25q::ReadBuffer(), and services::FlashQuadSpiCypressFll::ReadBuffer().
SendData()
virtual void hal::QuadSpi::SendData (const Header & header, infra::ConstByteRange data, Lines lines, const infra::Function< void()> & actionOnCompletion) pure virtual
Referenced by services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiMicronN25q::SendEraseBulk(), services::FlashQuadSpiSingleSpeed::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToSingleSpeed(), services::FlashQuadSpiSingleSpeed::WriteEnable(), services::FlashQuadSpiMicronN25q::WriteEnable(), services::FlashQuadSpiCypressFll::WriteEnable(), and services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed().
VectorToAddress()
uint32_t hal::QuadSpi::VectorToAddress (infra::BoundedVector< uint8_t >::WithMaxSize< 4 > vector) static
Definition at line 60 of file QuadSpi.cpp.
References infra::BoundedVector< T >::back(), infra::BoundedVector< T >::empty(), and infra::BoundedVector< T >::pop_back().
     {
         uint32_t result = 0;
         while (!vector.empty())
         {
             result = (result << 8) + vector.back();
             vector.pop_back();
         }
         return result;
     }
The documentation for this class was generated from the following files:
QuadSpi.hpp
QuadSpi.cpp