EMil: services::ConnectionFactoryWithNameResolverImpl::Action Class Reference
services::ConnectionFactoryWithNameResolverImpl::Action Class Reference
Public Member Functions
Action (ConnectionFactoryWithNameResolverImpl &connectionFactory, ClientConnectionObserverFactoryWithNameResolver &clientConnectionFactory)
bool Remove (ClientConnectionObserverFactoryWithNameResolver &clientConnectionFactory)
virtual infra::BoundedConstString Hostname () const override
virtual void NameLookupDone (IPAddress address, infra::TimePoint validUntil) override
virtual void NameLookupFailed () override
virtual IPAddress Address () const override
virtual uint16_t Port () const override
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver) override
virtual void ConnectionFailed (ConnectFailReason reason) override
Public Member Functions inherited from services::NameResolverResult
virtual IPVersions Versions () const
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Private Attributes
ConnectionFactoryWithNameResolverImpl & connectionFactory
ClientConnectionObserverFactoryWithNameResolver & clientConnectionFactory
IPAddress address
bool connecting = false
Additional Inherited Members
Public Types inherited from services::ClientConnectionObserverFactory
enum ConnectFailReason { refused, connectionAllocationFailed }
Protected Member Functions inherited from services::NameResolverResult
NameResolverResult ()=default
NameResolverResult (const NameResolverResult &other)=delete
NameResolverResult & operator= (const NameResolverResult &other)=delete
~NameResolverResult ()=default
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Protected Member Functions inherited from services::ClientConnectionObserverFactory
ClientConnectionObserverFactory ()=default
ClientConnectionObserverFactory (const ClientConnectionObserverFactory &other)=delete
ClientConnectionObserverFactory & operator= (const ClientConnectionObserverFactory &other)=delete
~ClientConnectionObserverFactory ()=default
Detailed Description
Definition at line 51 of file ConnectionFactoryWithNameResolver.hpp.
Constructor & Destructor Documentation
Action()
services::ConnectionFactoryWithNameResolverImpl::Action::Action (ConnectionFactoryWithNameResolverImpl & connectionFactory, ClientConnectionObserverFactoryWithNameResolver & clientConnectionFactory)
Definition at line 55 of file ConnectionFactoryWithNameResolver.cpp.
References connectionFactory, services::NameResolver::Lookup(), and services::ConnectionFactoryWithNameResolverImpl::nameLookup.
         : connectionFactory(connectionFactory)
         , clientConnectionFactory(clientConnectionFactory)
     {
         connectionFactory.nameLookup.Lookup(*this);
     }
Member Function Documentation
Address()
IPAddress services::ConnectionFactoryWithNameResolverImpl::Action::Address () const override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 95 of file ConnectionFactoryWithNameResolver.cpp.
     {
         return address;
     }
ConnectionEstablished()
void services::ConnectionFactoryWithNameResolverImpl::Action::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver) override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 105 of file ConnectionFactoryWithNameResolver.cpp.
References services::ConnectionFactoryWithNameResolverImpl::connectionFactory.
     {
         auto& clientConnectionFactory = this->clientConnectionFactory;
         connectionFactory.ActionIsDone(*this);
         clientConnectionFactory.ConnectionEstablished(std::move(createdObserver));
     }
ConnectionFailed()
void services::ConnectionFactoryWithNameResolverImpl::Action::ConnectionFailed (ConnectFailReason reason) override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 112 of file ConnectionFactoryWithNameResolver.cpp.
References services::ConnectionFactoryWithNameResolverImpl::connectionFactory, and services::Convert().
     {
         auto& clientConnectionFactory = this->clientConnectionFactory;
         connectionFactory.ActionIsDone(*this);
         clientConnectionFactory.ConnectionFailed(Convert(reason));
     }
Hostname()
infra::BoundedConstString services::ConnectionFactoryWithNameResolverImpl::Action::Hostname () const override virtual
Implements services::NameResolverResult.
Definition at line 76 of file ConnectionFactoryWithNameResolver.cpp.
     {
         return clientConnectionFactory.Hostname();
     }
NameLookupDone()
void services::ConnectionFactoryWithNameResolverImpl::Action::NameLookupDone (IPAddress address, infra::TimePoint validUntil) override virtual
Implements services::NameResolverResult.
Definition at line 81 of file ConnectionFactoryWithNameResolver.cpp.
References services::ConnectionFactory::Connect(), and services::ConnectionFactoryWithNameResolverImpl::connectionFactory.
     {
         this->address = address;
         connectionFactory.connectionFactory.Connect(*this);
         connecting = true;
     }
NameLookupFailed()
void services::ConnectionFactoryWithNameResolverImpl::Action::NameLookupFailed () override virtual
Implements services::NameResolverResult.
Definition at line 88 of file ConnectionFactoryWithNameResolver.cpp.
References services::ConnectionFactoryWithNameResolverImpl::connectionFactory.
     {
         auto& clientConnectionFactory = this->clientConnectionFactory;
         connectionFactory.ActionIsDone(*this);
         clientConnectionFactory.ConnectionFailed(ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::nameLookupFailed);
     }
Port()
uint16_t services::ConnectionFactoryWithNameResolverImpl::Action::Port () const override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 100 of file ConnectionFactoryWithNameResolver.cpp.
     {
         return clientConnectionFactory.Port();
     }
Remove()
bool services::ConnectionFactoryWithNameResolverImpl::Action::Remove (ClientConnectionObserverFactoryWithNameResolver & clientConnectionFactory)
Definition at line 62 of file ConnectionFactoryWithNameResolver.cpp.
References services::ConnectionFactory::CancelConnect(), and services::ConnectionFactoryWithNameResolverImpl::connectionFactory.
     {
         if (&clientConnectionFactory == &this->clientConnectionFactory)
         {
             if (connecting)
                 connectionFactory.connectionFactory.CancelConnect(*this);
             else
                 connectionFactory.nameLookup.CancelLookup(*this);
             return true;
         }
         else
             return false;
     }
Member Data Documentation
address
IPAddress services::ConnectionFactoryWithNameResolverImpl::Action::address private
Definition at line 74 of file ConnectionFactoryWithNameResolver.hpp.
clientConnectionFactory
ClientConnectionObserverFactoryWithNameResolver& services::ConnectionFactoryWithNameResolverImpl::Action::clientConnectionFactory private
Definition at line 73 of file ConnectionFactoryWithNameResolver.hpp.
connecting
bool services::ConnectionFactoryWithNameResolverImpl::Action::connecting = false private
Definition at line 75 of file ConnectionFactoryWithNameResolver.hpp.
connectionFactory
ConnectionFactoryWithNameResolverImpl& services::ConnectionFactoryWithNameResolverImpl::Action::connectionFactory private
Definition at line 72 of file ConnectionFactoryWithNameResolver.hpp.
Referenced by Action().
The documentation for this class was generated from the following files:
ConnectionFactoryWithNameResolver.hpp
ConnectionFactoryWithNameResolver.cpp