EMil: services::ConfigurationBlob Class Reference
services::ConfigurationBlob Class Reference abstract
#include <ConfigurationStore.hpp>
Public Member Functions
virtual infra::ByteRange CurrentBlob ()=0
virtual infra::ByteRange MaxBlob ()=0
virtual void Recover (const infra::Function< void(bool success)> &onRecovered)=0
virtual void Write (uint32_t size, const infra::Function< void()> &onDone)=0
virtual void Erase (const infra::Function< void()> &onDone)=0
Protected Member Functions
ConfigurationBlob ()=default
ConfigurationBlob (const ConfigurationBlob &other)=delete
ConfigurationBlob & operator= (const ConfigurationBlob &other)=delete
~ConfigurationBlob ()=default
Detailed Description
Definition at line 14 of file ConfigurationStore.hpp.
Constructor & Destructor Documentation
ConfigurationBlob() [1/2]
services::ConfigurationBlob::ConfigurationBlob () protected default
ConfigurationBlob() [2/2]
services::ConfigurationBlob::ConfigurationBlob (const ConfigurationBlob & other) protected delete
~ConfigurationBlob()
services::ConfigurationBlob::~ConfigurationBlob () protected default
Member Function Documentation
CurrentBlob()
virtual infra::ByteRange services::ConfigurationBlob::CurrentBlob () pure virtual
Implemented in services::ConfigurationBlobImpl.
Referenced by services::ConfigurationStoreImpl< T >::Deserialize().
Erase()
virtual void services::ConfigurationBlob::Erase (const infra::Function< void()> & onDone) pure virtual
Implemented in services::ConfigurationBlobImpl.
Referenced by services::ConfigurationStoreBase::Erase(), services::ConfigurationStoreBase::Recover(), services::FactoryDefaultConfigurationStoreBase::Recover(), and services::ConfigurationStoreBase::Write().
MaxBlob()
virtual infra::ByteRange services::ConfigurationBlob::MaxBlob () pure virtual
Implemented in services::ConfigurationBlobImpl.
Referenced by services::ConfigurationStoreImpl< T >::Serialize().
operator=()
ConfigurationBlob& services::ConfigurationBlob::operator= (const ConfigurationBlob & other) protected delete
Recover()
virtual void services::ConfigurationBlob::Recover (const infra::Function< void(bool success)> & onRecovered) pure virtual
Implemented in services::ConfigurationBlobImpl.
Referenced by services::ConfigurationStoreBase::Recover(), and services::FactoryDefaultConfigurationStoreBase::Recover().
Write()
virtual void services::ConfigurationBlob::Write (uint32_t size, const infra::Function< void()> & onDone) pure virtual
Implemented in services::ConfigurationBlobImpl.
Referenced by services::ConfigurationStoreImpl< T >::Serialize().
The documentation for this class was generated from the following file:
ConfigurationStore.hpp