EMil: infra::TickOnInterruptTimerService Class Reference
infra::TickOnInterruptTimerService Class Reference
#include <TickOnInterruptTimerService.hpp>
Public Member Functions
TickOnInterruptTimerService (uint32_t id, Duration resolution)
virtual void NextTriggerChanged () override
virtual TimePoint Now () const override
virtual Duration Resolution () const override
void SetResolution (Duration resolution)
void TimeProgressed (Duration amount)
void SystemTickInterrupt ()
Public Member Functions inherited from infra::TimerService
uint32_t Id () const
void RegisterTimer (Timer &timer)
void UnregisterTimer (Timer &timer, TimePoint oldTriggerTime)
void UpdateTriggerTime (Timer &timer, TimePoint oldTriggerTime)
void Progressed (TimePoint time)
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Private Member Functions
void ProcessTicks ()
Private Attributes
TimePoint systemTime = TimePoint()
Duration resolution
std::atomic< uint32_t > ticksNextNotification
std::atomic< uint32_t > ticksProgressed
std::atomic_bool notificationScheduled
Additional Inherited Members
Protected Member Functions inherited from infra::TimerService
TimerService (uint32_t id)
TimerService (const TimerService &other)=delete
~TimerService ()
TimerService & operator= (const TimerService &other)=delete
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 9 of file TickOnInterruptTimerService.hpp.
Constructor & Destructor Documentation
TickOnInterruptTimerService()
infra::TickOnInterruptTimerService::TickOnInterruptTimerService (uint32_t id, Duration resolution)
Definition at line 8 of file TickOnInterruptTimerService.cpp.
References NextTriggerChanged(), notificationScheduled, and ticksProgressed.
         : TimerService(id)
         , resolution(resolution)
     {
         ticksProgressed = 0;
         notificationScheduled = false;
         NextTriggerChanged();
     }
Member Function Documentation
NextTriggerChanged()
void infra::TickOnInterruptTimerService::NextTriggerChanged () override virtual
Reimplemented from infra::TimerService.
Definition at line 17 of file TickOnInterruptTimerService.cpp.
References infra::TimerService::NextTrigger(), infra::TimerService::nextTrigger, resolution, systemTime, and ticksNextNotification.
Referenced by ProcessTicks(), SetResolution(), and TickOnInterruptTimerService().
     {
         infra::TimePoint nextTrigger = NextTrigger();
         if (nextTrigger != infra::TimePoint::max())
         {
             infra::Duration durationToNextNotification = std::max(NextTrigger() - systemTime, Duration());
             ticksNextNotification = std::min(static_cast<uint32_t>((durationToNextNotification + resolution - Duration(1)) / resolution), std::numeric_limits<uint32_t>::max() / 2);
         }
         else
             ticksNextNotification = std::numeric_limits<uint32_t>::max() / 2;   // Once in a while, an update must be scheduled to avoid overflowing ticksNextNotification in the case no timers are scheduled
     }
Now()
TimePoint infra::TickOnInterruptTimerService::Now () const override virtual
Implements infra::TimerService.
Definition at line 29 of file TickOnInterruptTimerService.cpp.
References resolution, systemTime, and ticksProgressed.
     {
         return systemTime + ticksProgressed.load() * resolution;
     }
ProcessTicks()
void infra::TickOnInterruptTimerService::ProcessTicks () private
Definition at line 59 of file TickOnInterruptTimerService.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), NextTriggerChanged(), notificationScheduled, resolution, infra::EventDispatcherWorker::Schedule(), ticksNextNotification, ticksProgressed, and TimeProgressed().
Referenced by SystemTickInterrupt().
     {
         TimeProgressed(ticksProgressed.exchange(0) * resolution);
         NextTriggerChanged();
         // If in the meantime ticksProgressed has been increased beyond ticksNextNotification,
         // the event has not been scheduled by the interrupt, so schedule the event here.
         // Use the result of the assign to notificationScheduled, in order to avoid notificationScheduled
         // being set to false, then receiving an interrupt setting it to true, and not handling the newly scheduled
         // event immediately.
         bool reschedule = notificationScheduled = ticksProgressed >= ticksNextNotification;
         if (reschedule)
             infra::EventDispatcher::Instance().Schedule([this]() { ProcessTicks(); });
     }
Resolution()
Duration infra::TickOnInterruptTimerService::Resolution () const override virtual
Implements infra::TimerService.
Definition at line 34 of file TickOnInterruptTimerService.cpp.
References resolution.
     {
         return resolution;
     }
SetResolution()
void infra::TickOnInterruptTimerService::SetResolution (Duration resolution)
Definition at line 39 of file TickOnInterruptTimerService.cpp.
References NextTriggerChanged(), and resolution.
     {
         this->resolution = resolution;
         NextTriggerChanged();
     }
SystemTickInterrupt()
void infra::TickOnInterruptTimerService::SystemTickInterrupt ()
Definition at line 52 of file TickOnInterruptTimerService.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), notificationScheduled, ProcessTicks(), infra::EventDispatcherWorker::Schedule(), ticksNextNotification, and ticksProgressed.
     {
         ++ticksProgressed;
         if (ticksProgressed >= ticksNextNotification && !notificationScheduled.exchange(true))
             infra::EventDispatcher::Instance().Schedule([this]() { ProcessTicks(); });
     }
TimeProgressed()
void infra::TickOnInterruptTimerService::TimeProgressed (Duration amount)
Definition at line 45 of file TickOnInterruptTimerService.cpp.
References infra::TimerService::Progressed(), and systemTime.
Referenced by ProcessTicks().
     {
         systemTime += amount;
         Progressed(systemTime);
     }
Member Data Documentation
notificationScheduled
std::atomic_bool infra::TickOnInterruptTimerService::notificationScheduled private
Definition at line 33 of file TickOnInterruptTimerService.hpp.
Referenced by ProcessTicks(), SystemTickInterrupt(), and TickOnInterruptTimerService().
resolution
Duration infra::TickOnInterruptTimerService::resolution private
Definition at line 29 of file TickOnInterruptTimerService.hpp.
Referenced by NextTriggerChanged(), Now(), ProcessTicks(), Resolution(), and SetResolution().
systemTime
TimePoint infra::TickOnInterruptTimerService::systemTime = TimePoint() private
Definition at line 28 of file TickOnInterruptTimerService.hpp.
Referenced by NextTriggerChanged(), Now(), and TimeProgressed().
ticksNextNotification
std::atomic<uint32_t> infra::TickOnInterruptTimerService::ticksNextNotification private
Definition at line 31 of file TickOnInterruptTimerService.hpp.
Referenced by NextTriggerChanged(), ProcessTicks(), and SystemTickInterrupt().
ticksProgressed
std::atomic<uint32_t> infra::TickOnInterruptTimerService::ticksProgressed private
Definition at line 32 of file TickOnInterruptTimerService.hpp.
Referenced by Now(), ProcessTicks(), SystemTickInterrupt(), and TickOnInterruptTimerService().
The documentation for this class was generated from the following files:
TickOnInterruptTimerService.hpp
TickOnInterruptTimerService.cpp