EMil: TestHttpClient.cpp File Reference
TestHttpClient.cpp File Reference
Classes
struct HttpStatusCodeWithString
class HttpStatusMessageFormattingTest
class HttpClientTest
Functions
TEST (HttpTest, parse_components_from_url)
TEST (HttpTest, write_formatted_HttpHeader_to_stream)
TEST_P (HttpStatusMessageFormattingTest, write_formatted_HttpStatusCode_to_stream)
INSTANTIATE_TEST_CASE_P (HttpStatusMessageTest, HttpStatusMessageFormattingTest, testing::Values(HttpStatusCodeWithString{ services::HttpStatusCode::Continue, "Continue" }, HttpStatusCodeWithString{ services::HttpStatusCode::SwitchingProtocols, "SwitchingProtocols" }, HttpStatusCodeWithString{ services::HttpStatusCode::OK, "OK" }, HttpStatusCodeWithString{ services::HttpStatusCode::Created, "Created" }, HttpStatusCodeWithString{ services::HttpStatusCode::Accepted, "Accepted" }, HttpStatusCodeWithString{ services::HttpStatusCode::NonAuthorativeInformation, "NonAuthorativeInformation" }, HttpStatusCodeWithString{ services::HttpStatusCode::NoContent, "NoContent" }, HttpStatusCodeWithString{ services::HttpStatusCode::ResetContent, "ResetContent" }, HttpStatusCodeWithString{ services::HttpStatusCode::PartialContent, "PartialContent" }, HttpStatusCodeWithString{ services::HttpStatusCode::MultipleChoices, "MultipleChoices" }, HttpStatusCodeWithString{ services::HttpStatusCode::MovedPermanently, "MovedPermanently" }, HttpStatusCodeWithString{ services::HttpStatusCode::Found, "Found" }, HttpStatusCodeWithString{ services::HttpStatusCode::SeeOther, "SeeOther" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotModified, "NotModified" }, HttpStatusCodeWithString{ services::HttpStatusCode::UseProxy, "UseProxy" }, HttpStatusCodeWithString{ services::HttpStatusCode::TemporaryRedirect, "TemporaryRedirect" }, HttpStatusCodeWithString{ services::HttpStatusCode::BadRequest, "BadRequest" }, HttpStatusCodeWithString{ services::HttpStatusCode::Unauthorized, "Unauthorized" }, HttpStatusCodeWithString{ services::HttpStatusCode::PaymentRequired, "PaymentRequired" }, HttpStatusCodeWithString{ services::HttpStatusCode::Forbidden, "Forbidden" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotFound, "NotFound" }, HttpStatusCodeWithString{ services::HttpStatusCode::MethodNotAllowed, "MethodNotAllowed" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotAcceptable, "NotAcceptable" }, HttpStatusCodeWithString{ services::HttpStatusCode::ProxyAuthenticationRequired, "ProxyAuthenticationRequired" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestTimeOut, "RequestTimeOut" }, HttpStatusCodeWithString{ services::HttpStatusCode::Conflict, "Conflict" }, HttpStatusCodeWithString{ services::HttpStatusCode::Gone, "Gone" }, HttpStatusCodeWithString{ services::HttpStatusCode::LengthRequired, "LengthRequired" }, HttpStatusCodeWithString{ services::HttpStatusCode::PreconditionFailed, "PreconditionFailed" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestEntityTooLarge, "RequestEntityTooLarge" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestUriTooLarge, "RequestUriTooLarge" }, HttpStatusCodeWithString{ services::HttpStatusCode::UnsupportedMediaType, "UnsupportedMediaType" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestRangeNotSatisfiable, "RequestRangeNotSatisfiable" }, HttpStatusCodeWithString{ services::HttpStatusCode::ExpectationFailed, "ExpectationFailed" }, HttpStatusCodeWithString{ services::HttpStatusCode::InternalServerError, "InternalServerError" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotImplemented, "NotImplemented" }, HttpStatusCodeWithString{ services::HttpStatusCode::BadGateway, "BadGateway" }, HttpStatusCodeWithString{ services::HttpStatusCode::ServiceUnavailable, "ServiceUnavailable" }, HttpStatusCodeWithString{ services::HttpStatusCode::GatewayTimeOut, "GatewayTimeOut" }, HttpStatusCodeWithString{ services::HttpStatusCode::HttpVersionNotSupported, "HttpVersionNotSupported" }))
TEST_F (HttpClientTest, refused_connection_propagates_to_HttpClientFactory)
TEST_F (HttpClientTest, connection_failed_propagates_to_HttpClientFactory)
TEST_F (HttpClientTest, second_connection_is_tried_when_first_is_refused)
TEST_F (HttpClientTest, second_connection_is_tried_when_first_is_cancelled)
TEST_F (HttpClientTest, second_connection_is_removed_on_CancelConnect)
TEST_F (HttpClientTest, second_connection_is_tried_when_first_is_closed)
TEST_F (HttpClientTest, closed_connection_results_in_ClosingConnection)
TEST_F (HttpClientTest, Close_propagates_to_Connection)
TEST_F (HttpClientTest, AckReceived_propagates_to_Connection)
TEST_F (HttpClientTest, after_ConnectionEstablished_HttpClient_is_connected)
TEST_F (HttpClientTest, Get_request_is_executed)
TEST_F (HttpClientTest, Head_request_is_executed)
TEST_F (HttpClientTest, Connect_request_is_executed)
TEST_F (HttpClientTest, Options_request_is_executed)
TEST_F (HttpClientTest, Post_request_is_executed)
TEST_F (HttpClientTest, Put_request_is_executed)
TEST_F (HttpClientTest, Patch_request_is_executed)
TEST_F (HttpClientTest, Delete_request_is_executed)
TEST_F (HttpClientTest, request_contains_correct_headers)
TEST_F (HttpClientTest, incorrect_response_version_should_not_call_StatusAvailable)
TEST_F (HttpClientTest, incorrect_response_code_should_not_call_StatusAvailable)
TEST_F (HttpClientTest, response_with_supported_http_version_should_call_StatusAvailable)
TEST_F (HttpClientTest, ResponseAvailable_contains_correct_status_code)
TEST_F (HttpClientTest, ResponseAvailable_contains_response_headers)
TEST_F (HttpClientTest, too_long_header_is_rejected)
TEST_F (HttpClientTest, leading_spaces_are_stripped_from_header)
TEST_F (HttpClientTest, handle_headers_without_content)
TEST_F (HttpClientTest, ResponseAvailable_forwards_response_body_to_client)
TEST_F (HttpClientTest, ResponseAvailable_without_ContentLength_is_rejected)
TEST_F (HttpClientTest, response_in_parts_is_handled)
TEST_F (HttpClientTest, data_up_to_ContentLength_is_handled)
TEST_F (HttpClientTest, data_in_excess_of_ContentLength_is_ignored)
TEST_F (HttpClientTest, Close_while_DataAvailable_is_handled)
TEST_F (HttpClientTest, Close_while_BodyAvailable_is_handled)
TEST_F (HttpClientTest, when_reader_is_stored_body_available_sends_same_pointer)
TEST_F (HttpClientTest, closed_before_reader_is_reset)
TEST_F (HttpClientTest, Put_request_with_large_body_is_executed)
Function Documentation
INSTANTIATE_TEST_CASE_P()
INSTANTIATE_TEST_CASE_P (HttpStatusMessageTest , HttpStatusMessageFormattingTest , testing::Values(HttpStatusCodeWithString{ services::HttpStatusCode::Continue, "Continue" }, HttpStatusCodeWithString{ services::HttpStatusCode::SwitchingProtocols, "SwitchingProtocols" }, HttpStatusCodeWithString{ services::HttpStatusCode::OK, "OK" }, HttpStatusCodeWithString{ services::HttpStatusCode::Created, "Created" }, HttpStatusCodeWithString{ services::HttpStatusCode::Accepted, "Accepted" }, HttpStatusCodeWithString{ services::HttpStatusCode::NonAuthorativeInformation, "NonAuthorativeInformation" }, HttpStatusCodeWithString{ services::HttpStatusCode::NoContent, "NoContent" }, HttpStatusCodeWithString{ services::HttpStatusCode::ResetContent, "ResetContent" }, HttpStatusCodeWithString{ services::HttpStatusCode::PartialContent, "PartialContent" }, HttpStatusCodeWithString{ services::HttpStatusCode::MultipleChoices, "MultipleChoices" }, HttpStatusCodeWithString{ services::HttpStatusCode::MovedPermanently, "MovedPermanently" }, HttpStatusCodeWithString{ services::HttpStatusCode::Found, "Found" }, HttpStatusCodeWithString{ services::HttpStatusCode::SeeOther, "SeeOther" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotModified, "NotModified" }, HttpStatusCodeWithString{ services::HttpStatusCode::UseProxy, "UseProxy" }, HttpStatusCodeWithString{ services::HttpStatusCode::TemporaryRedirect, "TemporaryRedirect" }, HttpStatusCodeWithString{ services::HttpStatusCode::BadRequest, "BadRequest" }, HttpStatusCodeWithString{ services::HttpStatusCode::Unauthorized, "Unauthorized" }, HttpStatusCodeWithString{ services::HttpStatusCode::PaymentRequired, "PaymentRequired" }, HttpStatusCodeWithString{ services::HttpStatusCode::Forbidden, "Forbidden" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotFound, "NotFound" }, HttpStatusCodeWithString{ services::HttpStatusCode::MethodNotAllowed, "MethodNotAllowed" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotAcceptable, "NotAcceptable" }, HttpStatusCodeWithString{ services::HttpStatusCode::ProxyAuthenticationRequired, "ProxyAuthenticationRequired" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestTimeOut, "RequestTimeOut" }, HttpStatusCodeWithString{ services::HttpStatusCode::Conflict, "Conflict" }, HttpStatusCodeWithString{ services::HttpStatusCode::Gone, "Gone" }, HttpStatusCodeWithString{ services::HttpStatusCode::LengthRequired, "LengthRequired" }, HttpStatusCodeWithString{ services::HttpStatusCode::PreconditionFailed, "PreconditionFailed" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestEntityTooLarge, "RequestEntityTooLarge" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestUriTooLarge, "RequestUriTooLarge" }, HttpStatusCodeWithString{ services::HttpStatusCode::UnsupportedMediaType, "UnsupportedMediaType" }, HttpStatusCodeWithString{ services::HttpStatusCode::RequestRangeNotSatisfiable, "RequestRangeNotSatisfiable" }, HttpStatusCodeWithString{ services::HttpStatusCode::ExpectationFailed, "ExpectationFailed" }, HttpStatusCodeWithString{ services::HttpStatusCode::InternalServerError, "InternalServerError" }, HttpStatusCodeWithString{ services::HttpStatusCode::NotImplemented, "NotImplemented" }, HttpStatusCodeWithString{ services::HttpStatusCode::BadGateway, "BadGateway" }, HttpStatusCodeWithString{ services::HttpStatusCode::ServiceUnavailable, "ServiceUnavailable" }, HttpStatusCodeWithString{ services::HttpStatusCode::GatewayTimeOut, "GatewayTimeOut" }, HttpStatusCodeWithString{ services::HttpStatusCode::HttpVersionNotSupported, "HttpVersionNotSupported" }))
TEST() [1/2]
TEST (HttpTest , parse_components_from_url)
Definition at line 12 of file TestHttpClient.cpp.
References EXPECT_EQ(), services::HostFromUrl(), services::PathFromUrl(), and services::SchemeFromUrl().
 {
     EXPECT_EQ("http", services::SchemeFromUrl("http://host/path"));
     EXPECT_EQ("host", services::HostFromUrl("http://host/path"));
     EXPECT_EQ("/path", services::PathFromUrl("http://host/path"));
     EXPECT_EQ("/path/more", services::PathFromUrl("http://host/path/more"));
 }
TEST() [2/2]
TEST (HttpTest , write_formatted_HttpHeader_to_stream)
Definition at line 20 of file TestHttpClient.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     services::HttpHeader header{ "Key", "Value" };
     infra::StdStringOutputStream::WithStorage stream;
     stream << header;
     EXPECT_EQ("Key:Value", stream.Storage());
 }
TEST_F() [1/37]
TEST_F (HttpClientTest , refused_connection_propagates_to_HttpClientFactory)
Definition at line 138 of file TestHttpClient.cpp.
 {
     EXPECT_CALL(factory, ConnectionFailed(services::HttpClientObserverFactory::ConnectFailReason::refused));
     connector.ConnectionFailed(services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::refused);
 }
TEST_F() [2/37]
TEST_F (HttpClientTest , connection_failed_propagates_to_HttpClientFactory)
Definition at line 144 of file TestHttpClient.cpp.
 {
     EXPECT_CALL(factory, ConnectionFailed(services::HttpClientObserverFactory::ConnectFailReason::connectionAllocationFailed));
     connector.ConnectionFailed(services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::connectionAllocationFailed);
 }
TEST_F() [3/37]
TEST_F (HttpClientTest , second_connection_is_tried_when_first_is_refused)
Definition at line 150 of file TestHttpClient.cpp.
 {
     connector.Connect(factory2);
     EXPECT_CALL(factory, ConnectionFailed(services::HttpClientObserverFactory::ConnectFailReason::refused));
     EXPECT_CALL(connectionFactory, Connect(testing::Ref(connector)));
     connector.ConnectionFailed(services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::refused);
 }
TEST_F() [4/37]
TEST_F (HttpClientTest , second_connection_is_tried_when_first_is_cancelled)
Definition at line 159 of file TestHttpClient.cpp.
 {
     connector.Connect(factory2);
     EXPECT_CALL(connectionFactory, CancelConnect(testing::Ref(connector)));
     EXPECT_CALL(connectionFactory, Connect(testing::Ref(connector)));
     connector.CancelConnect(factory);
 }
TEST_F() [5/37]
TEST_F (HttpClientTest , second_connection_is_removed_on_CancelConnect)
Definition at line 168 of file TestHttpClient.cpp.
 {
     connector.Connect(factory2);
     connector.CancelConnect(factory2);
     EXPECT_CALL(factory, ConnectionFailed(services::HttpClientObserverFactory::ConnectFailReason::connectionAllocationFailed));
     connector.ConnectionFailed(services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::connectionAllocationFailed);
 }
TEST_F() [6/37]
TEST_F (HttpClientTest , second_connection_is_tried_when_first_is_closed)
Definition at line 177 of file TestHttpClient.cpp.
 {
     connector.Connect(factory2);
     Connect();
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     EXPECT_CALL(connectionFactory, Connect(testing::Ref(connector)));
     connection.AbortAndDestroy();
 }
TEST_F() [7/37]
TEST_F (HttpClientTest , closed_connection_results_in_ClosingConnection)
Definition at line 188 of file TestHttpClient.cpp.
 {
     Connect();
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     connection.AbortAndDestroy();
 }
TEST_F() [8/37]
TEST_F (HttpClientTest , Close_propagates_to_Connection)
Definition at line 197 of file TestHttpClient.cpp.
 {
     Connect();
     EXPECT_CALL(connection, CloseAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     client.Subject().Close();
 }
TEST_F() [9/37]
TEST_F (HttpClientTest , AckReceived_propagates_to_Connection)
Definition at line 206 of file TestHttpClient.cpp.
 {
     Connect();
     EXPECT_CALL(connection, AckReceivedMock());
     client.Subject().AckReceived();
 }
TEST_F() [10/37]
TEST_F (HttpClientTest , after_ConnectionEstablished_HttpClient_is_connected)
Definition at line 214 of file TestHttpClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), and services::ConnectionObserver::Connected().
 {
     EXPECT_CALL(factory, ConnectionEstablished(testing::_)).WillOnce(testing::Invoke([this](infra::AutoResetFunction<void(infra::SharedPtr<services::HttpClientObserver> client)>& createdClient)
     {
         EXPECT_CALL(client, Connected());
         createdClient(clientPtr);
     }));
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
 }
TEST_F() [11/37]
TEST_F (HttpClientTest , Get_request_is_executed)
Definition at line 230 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Get("/api/thing");
     ExecuteAllActions();
     EXPECT_EQ("GET /api/thing HTTP/1.1\r\nhost:localhost\r\n\r\n", connection.SentDataAsString());
 }
TEST_F() [12/37]
TEST_F (HttpClientTest , Head_request_is_executed)
Definition at line 240 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Head("/api/thing");
     ExecuteAllActions();
     EXPECT_EQ("HEAD /api/thing HTTP/1.1\r\nhost:localhost\r\n\r\n", connection.SentDataAsString());
 }
TEST_F() [13/37]
TEST_F (HttpClientTest , Connect_request_is_executed)
Definition at line 250 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Connect("/api/thing");
     ExecuteAllActions();
     EXPECT_EQ("CONNECT /api/thing HTTP/1.1\r\nhost:localhost\r\n\r\n", connection.SentDataAsString());
 }
TEST_F() [14/37]
TEST_F (HttpClientTest , Options_request_is_executed)
Definition at line 259 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Options("/api/thing");
     ExecuteAllActions();
     EXPECT_EQ("OPTIONS /api/thing HTTP/1.1\r\nhost:localhost\r\n\r\n", connection.SentDataAsString());
 }
TEST_F() [15/37]
TEST_F (HttpClientTest , Post_request_is_executed)
Definition at line 268 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Post("/api/thing", "body contents");
     ExecuteAllActions();
     EXPECT_EQ("POST /api/thing HTTP/1.1\r\nhost:localhost\r\ncontent-length:13\r\n\r\nbody contents", connection.SentDataAsString());
 }
TEST_F() [16/37]
TEST_F (HttpClientTest , Put_request_is_executed)
Definition at line 277 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Put("/api/thing", "body contents");
     ExecuteAllActions();
     EXPECT_EQ("PUT /api/thing HTTP/1.1\r\nhost:localhost\r\ncontent-length:13\r\n\r\nbody contents", connection.SentDataAsString());
 }
TEST_F() [17/37]
TEST_F (HttpClientTest , Patch_request_is_executed)
Definition at line 286 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Patch("/api/thing", "body contents");
     ExecuteAllActions();
     EXPECT_EQ("PATCH /api/thing HTTP/1.1\r\nhost:localhost\r\ncontent-length:13\r\n\r\nbody contents", connection.SentDataAsString());
 }
TEST_F() [18/37]
TEST_F (HttpClientTest , Delete_request_is_executed)
Definition at line 295 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Delete("/api/thing", {});
     ExecuteAllActions();
     EXPECT_EQ("DELETE /api/thing HTTP/1.1\r\nhost:localhost\r\n\r\n", connection.SentDataAsString());
 }
TEST_F() [19/37]
TEST_F (HttpClientTest , request_contains_correct_headers)
Definition at line 304 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     std::array<services::HttpHeader, 2> headers{ services::HttpHeader{ "authorization", "Basic Y29ubmVjdGl2aXR5OmlzY29vbA==" }, { "connection", "close" } };
     client.Subject().Get("/api/thing", headers);
     ExecuteAllActions();
     EXPECT_EQ("GET /api/thing HTTP/1.1\r\nauthorization:Basic Y29ubmVjdGl2aXR5OmlzY29vbA==\r\nconnection:close\r\nhost:localhost\r\n\r\n", connection.SentDataAsString());
 }
TEST_F() [20/37]
TEST_F (HttpClientTest , incorrect_response_version_should_not_call_StatusAvailable)
Definition at line 315 of file TestHttpClient.cpp.
References infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(testing::_)).Times(0);
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/X.Y 200 Success\r\n")));
     ExecuteAllActions();
 }
TEST_F() [21/37]
TEST_F (HttpClientTest , incorrect_response_code_should_not_call_StatusAvailable)
Definition at line 329 of file TestHttpClient.cpp.
References infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(testing::_)).Times(0);
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 900 Invalid\r\n")));
     ExecuteAllActions();
 }
TEST_F() [22/37]
TEST_F (HttpClientTest , response_with_supported_http_version_should_call_StatusAvailable)
Definition at line 343 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.0 200 Success\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
 }
TEST_F() [23/37]
TEST_F (HttpClientTest , ResponseAvailable_contains_correct_status_code)
Definition at line 362 of file TestHttpClient.cpp.
References services::BadRequest, services::Continue, services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::Continue));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 100 Continue\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::BadRequest));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 400 Bad Request\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
 }
TEST_F() [24/37]
TEST_F (HttpClientTest , ResponseAvailable_contains_response_headers)
Definition at line 388 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Date", "Sat, 28 Nov 2009 04:36:25 GMT")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Expires", "-1")));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nDate:Sat, 28 Nov 2009 04:36:25 GMT\r\nExpires:-1\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
 }
TEST_F() [25/37]
TEST_F (HttpClientTest , too_long_header_is_rejected)
Definition at line 404 of file TestHttpClient.cpp.
References infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(testing::_));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.0 200 Success\r\n012345678901234567890123456789012345678901234567890123456789\r\n")));
     ExecuteAllActions();
 }
TEST_F() [26/37]
TEST_F (HttpClientTest , leading_spaces_are_stripped_from_header)
Definition at line 418 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Header", "Header Data")));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nHeader:  Header Data\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
 }
TEST_F() [27/37]
TEST_F (HttpClientTest , handle_headers_without_content)
Definition at line 433 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Header", "")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("AnotherHeader", "")));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nHeader:  \r\nAnotherHeader:\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
 }
TEST_F() [28/37]
TEST_F (HttpClientTest , ResponseAvailable_forwards_response_body_to_client)
Definition at line 449 of file TestHttpClient.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), EXPECT_EQ(), infra::noFail, services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(connection, AckReceivedMock()).Times(2);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Date", "Sat, 28 Nov 2009 04:36:25 GMT")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Expires", "-1")));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader) {
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("body\r\ndata", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nDate:Sat, 28 Nov 2009 04:36:25 GMT\r\nExpires:-1\r\nContent-Length:10\r\n\r\nbody\r\ndata")));
     ExecuteAllActions();
 }
TEST_F() [29/37]
TEST_F (HttpClientTest , ResponseAvailable_without_ContentLength_is_rejected)
Definition at line 469 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n\r\nbody\r\ndata")));
     ExecuteAllActions();
 }
TEST_F() [30/37]
TEST_F (HttpClientTest , response_in_parts_is_handled)
Definition at line 484 of file TestHttpClient.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), EXPECT_EQ(), infra::noFail, services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Get("/");
     EXPECT_CALL(connection, AckReceivedMock()).Times(6);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n")));
     ExecuteAllActions();
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Date:Sat, 28 Nov 2009 04:36:25 GMT\r")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Date", "Sat, 28 Nov 2009 04:36:25 GMT")));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("\n")));
     ExecuteAllActions();
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Expires", "-1")));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader) {
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("body\r\ndat", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Expires:-1\r\nContent-Length:10\r\n\r\nbody\r\ndat")));
     ExecuteAllActions();
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader) {
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("a", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     EXPECT_CALL(client, BodyComplete());
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("a")));
     ExecuteAllActions();
 }
TEST_F() [31/37]
TEST_F (HttpClientTest , data_up_to_ContentLength_is_handled)
Definition at line 518 of file TestHttpClient.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), EXPECT_EQ(), infra::noFail, services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Get("/");
     EXPECT_CALL(connection, AckReceivedMock()).Times(3);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Date", "Sat, 28 Nov 2009 04:36:25 GMT")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Expires", "-1")));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader) {
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("body\r\nda", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     EXPECT_CALL(client, BodyComplete());
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n")));
     ExecuteAllActions();
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Date:Sat, 28 Nov 2009 04:36:25 GMT\r\nExpires:-1\r\nContent-Length:8\r\n\r\nbody\r\ndata")));
     ExecuteAllActions();
 }
TEST_F() [32/37]
TEST_F (HttpClientTest , data_in_excess_of_ContentLength_is_ignored)
Definition at line 540 of file TestHttpClient.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), EXPECT_EQ(), infra::noFail, services::OK, and infra::StringAsByteRange().
 {
     Connect();
     EXPECT_CALL(connection, AckReceivedMock()).Times(2);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Date", "Sat, 28 Nov 2009 04:36:25 GMT")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Expires", "-1")));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader) {
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("body\r\ndata", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\nDate:Sat, 28 Nov 2009 04:36:25 GMT\r\nExpires:-1\r\nContent-Length:10\r\n\r\nbody\r\ndata")));
     ExecuteAllActions();
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("extradata")));
     ExecuteAllActions();
 }
TEST_F() [33/37]
TEST_F (HttpClientTest , Close_while_DataAvailable_is_handled)
Definition at line 564 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Get("/");
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK)).WillOnce(testing::Invoke([this](services::HttpStatusCode result)
     {
         EXPECT_CALL(connection, CloseAndDestroyMock());
         EXPECT_CALL(client, ClosingConnection());
         client.Subject().Close();
     }));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n")));
     ExecuteAllActions();
 }
TEST_F() [34/37]
TEST_F (HttpClientTest , Close_while_BodyAvailable_is_handled)
Definition at line 581 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Get("/");
     EXPECT_CALL(connection, AckReceivedMock()).Times(3);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader)
     {
         reader = nullptr;
         EXPECT_CALL(connection, CloseAndDestroyMock());
         EXPECT_CALL(client, ClosingConnection());
         client.Subject().Close();
     }));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n")));
     ExecuteAllActions();
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Content-Length:8\r\n\r\nbody\r\ndata")));
     ExecuteAllActions();
 }
TEST_F() [35/37]
TEST_F (HttpClientTest , when_reader_is_stored_body_available_sends_same_pointer)
Definition at line 603 of file TestHttpClient.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), EXPECT_EQ(), infra::noFail, services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Get("/");
     EXPECT_CALL(connection, AckReceivedMock()).Times(5);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n")));
     ExecuteAllActions();
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Date:Sat, 28 Nov 2009 04:36:25 GMT\r")));
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Date", "Sat, 28 Nov 2009 04:36:25 GMT")));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("\n")));
     ExecuteAllActions();
     infra::SharedPtr<infra::StreamReader> readerPtr;
     EXPECT_CALL(client, HeaderAvailable(services::HttpHeader("Expires", "-1")));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this, &readerPtr](infra::SharedPtr<infra::StreamReader>& reader)
     {
         readerPtr = reader;
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("body\r\ndat", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Expires:-1\r\nContent-Length:10\r\n\r\nbody\r\ndat")));
     ExecuteAllActions();
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader)
     {
         infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
         EXPECT_EQ("a", infra::ByteRangeAsString(stream.ContiguousRange()));
     }));
     EXPECT_CALL(client, BodyComplete());
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("a")));
     ExecuteAllActions();
 }
TEST_F() [36/37]
TEST_F (HttpClientTest , closed_before_reader_is_reset)
Definition at line 641 of file TestHttpClient.cpp.
References services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Get("/");
     auto clientConnection = connection.Observer();  // Keep the client alive so that reader may be kept alive a little longer
     EXPECT_CALL(connection, AckReceivedMock()).Times(2);
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(client, BodyAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamReader>& reader)
     {
         EXPECT_CALL(connection, CloseAndDestroyMock());
         EXPECT_CALL(client, ClosingConnection());
         client.Subject().Close();
         reader = nullptr;
     }));
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.1 200 Success\r\n")));
     ExecuteAllActions();
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("Content-Length:8\r\n\r\nbody\r\ndata")));
     ExecuteAllActions();
 }
TEST_F() [37/37]
TEST_F (HttpClientTest , Put_request_with_large_body_is_executed)
Definition at line 665 of file TestHttpClient.cpp.
References infra::OutputStream::Available(), EXPECT_EQ(), services::OK, and infra::StringAsByteRange().
 {
     Connect();
     client.Subject().Put("/api/thing", 1024);
     EXPECT_CALL(client, SendStreamAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamWriter>& writer)
     {
         EXPECT_EQ("PUT /api/thing HTTP/1.1\r\nhost:localhost\r\ncontent-length:1024\r\n\r\n", connection.SentDataAsString());
         connection.sentData.clear();
         infra::TextOutputStream::WithErrorPolicy stream(*writer);
         stream << "data";
         EXPECT_CALL(client, SendStreamAvailable(testing::_)).WillOnce(testing::Invoke([this](infra::SharedPtr<infra::StreamWriter>& writer)
         {
             EXPECT_EQ("data", connection.SentDataAsString());
             connection.sentData.clear();
             infra::TextOutputStream::WithErrorPolicy stream(*writer);
             stream << std::string(stream.Available(), ' ');
             writer = nullptr;
         }));
     }));
     ExecuteAllActions();
     EXPECT_CALL(client, StatusAvailable(services::HttpStatusCode::OK));
     EXPECT_CALL(connection, AckReceivedMock());
     EXPECT_CALL(client, BodyComplete());
     client.Subject().Get("/");
     connection.SimulateDataReceived(infra::StringAsByteRange(infra::BoundedConstString("HTTP/1.0 200 Success\r\nContent-Length:0\r\n\r\n")));
     ExecuteAllActions();
 }
TEST_P()
TEST_P (HttpStatusMessageFormattingTest , write_formatted_HttpStatusCode_to_stream)
Definition at line 43 of file TestHttpClient.cpp.
References EXPECT_EQ().
 {
     auto parameter = GetParam();
     stream << parameter.code;
     EXPECT_EQ(parameter.string, stream.Storage());
 }