EMil: services::ConnectionMbedTlsConnector Class Reference
services::ConnectionMbedTlsConnector Class Reference
#include <ConnectionMbedTls.hpp>
Public Member Functions
ConnectionMbedTlsConnector (ConnectionFactoryMbedTls &factory, ConnectionFactory &networkFactory, ClientConnectionObserverFactory &clientFactory)
virtual IPAddress Address () const override
virtual uint16_t Port () const override
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver) override
virtual void ConnectionFailed (ConnectFailReason reason) override
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Private Attributes
ConnectionFactoryMbedTls & factory
ClientConnectionObserverFactory & clientFactory
Friends
class ConnectionFactoryMbedTls
Additional Inherited Members
Public Types inherited from services::ClientConnectionObserverFactory
enum ConnectFailReason { refused, connectionAllocationFailed }
Protected Member Functions inherited from services::ClientConnectionObserverFactory
ClientConnectionObserverFactory ()=default
ClientConnectionObserverFactory (const ClientConnectionObserverFactory &other)=delete
ClientConnectionObserverFactory & operator= (const ClientConnectionObserverFactory &other)=delete
~ClientConnectionObserverFactory ()=default
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 165 of file ConnectionMbedTls.hpp.
Constructor & Destructor Documentation
ConnectionMbedTlsConnector()
services::ConnectionMbedTlsConnector::ConnectionMbedTlsConnector (ConnectionFactoryMbedTls & factory, ConnectionFactory & networkFactory, ClientConnectionObserverFactory & clientFactory)
Definition at line 399 of file ConnectionMbedTls.cpp.
References services::ConnectionFactory::Connect().
         : factory(factory)
         , clientFactory(clientFactory)
     {
         networkFactory.Connect(*this);
     }
Member Function Documentation
Address()
IPAddress services::ConnectionMbedTlsConnector::Address () const override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 406 of file ConnectionMbedTls.cpp.
References services::ClientConnectionObserverFactory::Address(), and clientFactory.
     {
         return clientFactory.Address();
     }
ConnectionEstablished()
void services::ConnectionMbedTlsConnector::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver) override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 416 of file ConnectionMbedTls.cpp.
References services::ConnectionFactoryMbedTls::Allocate(), clientFactory, services::ClientConnectionObserverFactory::ConnectionEstablished(), ConnectionFailed(), factory, and services::ConnectionFactoryMbedTls::Remove().
     {
         infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> creationFailed = createdObserver.Clone();
         infra::SharedPtr<ConnectionMbedTls> connection = factory.Allocate(std::move(createdObserver));
         if (connection)
         {
             clientFactory.ConnectionEstablished([connection](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
             {
                 connection->CreatedObserver(connectionObserver);
             });
             factory.Remove(*this);
         }
         else
         {
             ConnectionFailed(ConnectFailReason::connectionAllocationFailed);
             creationFailed(nullptr);
         }
     }
ConnectionFailed()
void services::ConnectionMbedTlsConnector::ConnectionFailed (ConnectFailReason reason) override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 436 of file ConnectionMbedTls.cpp.
References clientFactory, services::ClientConnectionObserverFactory::ConnectionFailed(), factory, and services::ConnectionFactoryMbedTls::Remove().
Referenced by ConnectionEstablished().
     {
         clientFactory.ConnectionFailed(reason);
         factory.Remove(*this);
     }
Port()
uint16_t services::ConnectionMbedTlsConnector::Port () const override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 411 of file ConnectionMbedTls.cpp.
References clientFactory, and services::ClientConnectionObserverFactory::Port().
     {
         return clientFactory.Port();
     }
Friends And Related Function Documentation
ConnectionFactoryMbedTls
friend class ConnectionFactoryMbedTls friend
Definition at line 177 of file ConnectionMbedTls.hpp.
Member Data Documentation
clientFactory
ClientConnectionObserverFactory& services::ConnectionMbedTlsConnector::clientFactory private
Definition at line 180 of file ConnectionMbedTls.hpp.
Referenced by Address(), ConnectionEstablished(), ConnectionFailed(), and Port().
factory
ConnectionFactoryMbedTls& services::ConnectionMbedTlsConnector::factory private
Definition at line 179 of file ConnectionMbedTls.hpp.
Referenced by ConnectionEstablished(), and ConnectionFailed().
The documentation for this class was generated from the following files:
ConnectionMbedTls.hpp
ConnectionMbedTls.cpp