EMil: hal::QuadSpiStub Class Reference
hal::QuadSpiStub Class Reference
#include <QuadSpiStub.hpp>
Public Member Functions
virtual void SendData (const Header &header, infra::ConstByteRange data, Lines lines, const infra::Function< void()> &actionOnCompletion) override
virtual void ReceiveData (const Header &header, infra::ByteRange data, Lines lines, const infra::Function< void()> &actionOnCompletion) override
virtual void PollStatus (const Header &header, uint8_t nofBytes, uint32_t match, uint32_t mask, Lines lines, const infra::Function< void()> &actionOnCompletion) override
MOCK_METHOD3 (SendDataMock, void(const Header &, infra::ConstByteRange, Lines lines))
MOCK_METHOD2 (ReceiveDataMock, infra::ConstByteRange(const Header &, Lines lines))
MOCK_METHOD5 (PollStatusMock, void(const Header &, uint8_t nofBytes, uint32_t match, uint32_t mask, Lines lines))
Public Member Functions inherited from hal::QuadSpi
QuadSpi ()=default
QuadSpi (const QuadSpi &other)=delete
QuadSpi & operator= (const QuadSpi &other)=delete
Public Attributes
infra::AutoResetFunction< void()> onDone
Additional Inherited Members
Static Public Member Functions inherited from hal::QuadSpi
static infra::BoundedVector< uint8_t >::WithMaxSize< 4 > AddressToVector (uint32_t address, uint8_t numberOfBytes)
static uint32_t VectorToAddress (infra::BoundedVector< uint8_t >::WithMaxSize< 4 > vector)
Protected Member Functions inherited from hal::QuadSpi
~QuadSpi ()=default
Detailed Description
Definition at line 11 of file QuadSpiStub.hpp.
Member Function Documentation
MOCK_METHOD2()
hal::QuadSpiStub::MOCK_METHOD2 (ReceiveDataMock , infra::ConstByteRange(const Header &, Lines lines))
MOCK_METHOD3()
hal::QuadSpiStub::MOCK_METHOD3 (SendDataMock , void(const Header &, infra::ConstByteRange, Lines lines))
MOCK_METHOD5()
hal::QuadSpiStub::MOCK_METHOD5 (PollStatusMock , void(const Header &, uint8_t nofBytes, uint32_t match, uint32_t mask, Lines lines))
PollStatus()
void hal::QuadSpiStub::PollStatus (const Header & header, uint8_t nofBytes, uint32_t match, uint32_t mask, Lines lines, const infra::Function< void()> & actionOnCompletion) override virtual
Implements hal::QuadSpi.
Definition at line 23 of file QuadSpiStub.cpp.
References onDone.
     {
         assert(!onDone);
         onDone = actionOnCompletion;
         PollStatusMock(header, nofBytes, match, mask, lines);
     }
ReceiveData()
void hal::QuadSpiStub::ReceiveData (const Header & header, infra::ByteRange data, Lines lines, const infra::Function< void()> & actionOnCompletion) override virtual
Implements hal::QuadSpi.
Definition at line 14 of file QuadSpiStub.cpp.
References infra::MemoryRange< T >::begin(), data, infra::MemoryRange< T >::end(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), onDone, and infra::EventDispatcherWorker::Schedule().
     {
         assert(!onDone);
         onDone = actionOnCompletion;
         infra::ConstByteRange result = ReceiveDataMock(header, lines);
         std::copy(result.begin(), result.end(), data.begin());
         infra::EventDispatcher::Instance().Schedule([this]() { onDone(); });
     }
SendData()
void hal::QuadSpiStub::SendData (const Header & header, infra::ConstByteRange data, Lines lines, const infra::Function< void()> & actionOnCompletion) override virtual
Implements hal::QuadSpi.
Definition at line 6 of file QuadSpiStub.cpp.
References data, infra::InterfaceConnector< EventDispatcherWorker >::Instance(), onDone, and infra::EventDispatcherWorker::Schedule().
     {
         assert(!onDone);
         onDone = actionOnCompletion;
         SendDataMock(header, data, lines);
         infra::EventDispatcher::Instance().Schedule([this]() { onDone(); });
     }
Member Data Documentation
onDone
infra::AutoResetFunction<void()> hal::QuadSpiStub::onDone
Definition at line 23 of file QuadSpiStub.hpp.
Referenced by PollStatus(), ReceiveData(), and SendData().
The documentation for this class was generated from the following files:
QuadSpiStub.hpp
QuadSpiStub.cpp