EMil: infra::CountingStreamReader Class Reference
infra::CountingStreamReader Class Reference
#include <CountingInputStream.hpp>
Public Member Functions
CountingStreamReader (infra::StreamReader &reader)
uint32_t TotalRead () const
virtual void Extract (infra::ByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (infra::StreamErrorPolicy &errorPolicy) override
virtual infra::ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual infra::ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
virtual bool Failed () const override
virtual void ReportResult (bool ok) override
Private Attributes
infra::StreamReader & reader
infra::StreamErrorPolicy * otherErrorPolicy = nullptr
bool ok = true
uint32_t totalRead = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Private Member Functions inherited from infra::StreamErrorPolicy
StreamErrorPolicy ()=default
StreamErrorPolicy (SoftFail)
StreamErrorPolicy (NoFail)
~StreamErrorPolicy ()
Detailed Description
Definition at line 8 of file CountingInputStream.hpp.
Constructor & Destructor Documentation
CountingStreamReader()
infra::CountingStreamReader::CountingStreamReader (infra::StreamReader & reader)
Definition at line 5 of file CountingInputStream.cpp.
         : reader(reader)
     {}
Member Function Documentation
Available()
std::size_t infra::CountingStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 47 of file CountingInputStream.cpp.
References infra::StreamReader::Available(), and reader.
     {
         return reader.Available();
     }
Empty()
bool infra::CountingStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 42 of file CountingInputStream.cpp.
References infra::StreamReader::Empty(), and reader.
     {
         return reader.Empty();
     }
Extract()
void infra::CountingStreamReader::Extract (infra::ByteRange range, infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 14 of file CountingInputStream.cpp.
References infra::StreamReader::Extract(), ok, otherErrorPolicy, reader, infra::MemoryRange< T >::size(), and totalRead.
     {
         otherErrorPolicy = &errorPolicy;
         ok = true;
         reader.Extract(range, *this);
         if (ok)
             totalRead += range.size();
         otherErrorPolicy = nullptr;
     }
ExtractContiguousRange()
infra::ConstByteRange infra::CountingStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 30 of file CountingInputStream.cpp.
References infra::StreamReader::ExtractContiguousRange(), reader, and totalRead.
     {
         auto result = reader.ExtractContiguousRange(max);
         totalRead += result.size();
         return result;
     }
Failed()
bool infra::CountingStreamReader::Failed () const override virtual
Reimplemented from infra::StreamErrorPolicy.
Definition at line 52 of file CountingInputStream.cpp.
References infra::StreamErrorPolicy::Failed(), and otherErrorPolicy.
     {
         return otherErrorPolicy->Failed();
     }
Peek()
uint8_t infra::CountingStreamReader::Peek (infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 25 of file CountingInputStream.cpp.
References infra::StreamReader::Peek(), and reader.
     {
         return reader.Peek(errorPolicy);
     }
PeekContiguousRange()
infra::ConstByteRange infra::CountingStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 37 of file CountingInputStream.cpp.
References infra::StreamReader::PeekContiguousRange(), and reader.
     {
         return reader.PeekContiguousRange(start);
     }
ReportResult()
void infra::CountingStreamReader::ReportResult (bool ok) override virtual
Reimplemented from infra::StreamErrorPolicy.
Definition at line 57 of file CountingInputStream.cpp.
References ok, otherErrorPolicy, and infra::StreamErrorPolicy::ReportResult().
     {
         otherErrorPolicy->ReportResult(ok);
         this->ok = this->ok && ok;
     }
TotalRead()
uint32_t infra::CountingStreamReader::TotalRead () const
Definition at line 9 of file CountingInputStream.cpp.
References totalRead.
     {
         return totalRead;
     }
Member Data Documentation
ok
bool infra::CountingStreamReader::ok = true private
Definition at line 32 of file CountingInputStream.hpp.
Referenced by Extract(), and ReportResult().
otherErrorPolicy
infra::StreamErrorPolicy* infra::CountingStreamReader::otherErrorPolicy = nullptr private
Definition at line 31 of file CountingInputStream.hpp.
Referenced by Extract(), Failed(), and ReportResult().
reader
infra::StreamReader& infra::CountingStreamReader::reader private
Definition at line 30 of file CountingInputStream.hpp.
Referenced by Available(), Empty(), Extract(), ExtractContiguousRange(), Peek(), and PeekContiguousRange().
totalRead
uint32_t infra::CountingStreamReader::totalRead = 0 private
Definition at line 33 of file CountingInputStream.hpp.
Referenced by Extract(), ExtractContiguousRange(), and TotalRead().
The documentation for this class was generated from the following files:
CountingInputStream.hpp
CountingInputStream.cpp