EMil: services::HttpClientImpl Class Reference
services::HttpClientImpl Class Reference
#include <HttpClientImpl.hpp>
Classes
class BodyReader
class HttpResponseParser
Public Types
template<std::size_t MaxHeaderSize>
using WithMaxHeaderSize = infra::WithStorage< HttpClientImpl, infra::BoundedString::WithStorage< MaxHeaderSize > >
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Public Member Functions
HttpClientImpl (infra::BoundedString &headerBuffer, infra::BoundedConstString hostname)
void AttachObserver (const infra::SharedPtr< HttpClientObserver > &observer)
virtual void Get (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Head (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Connect (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Options (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Post (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers) override
virtual void Put (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers=noHeaders) override
virtual void Put (infra::BoundedConstString requestTarget, std::size_t contentSize, HttpHeaders headers=noHeaders) override
virtual void Patch (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers=noHeaders) override
virtual void Delete (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers=noHeaders) override
virtual void AckReceived () override
virtual void Close () override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
virtual void Connected () override
virtual void ClosingConnection () override
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Member Functions inherited from infra::Subject< HttpClientObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Protected Member Functions
virtual void StatusAvailable (HttpStatusCode code, infra::BoundedConstString statusLine)
virtual void WriteRequest (infra::SharedPtr< infra::StreamWriter > &&writer)
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Protected Member Functions inherited from infra::Subject< HttpClientObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< HttpClientObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< HttpClientObserver, ObserverSubjectType > *observer)
Protected Attributes
infra::SharedPtr< HttpClientObserver > observer
infra::Optional< HttpRequestFormatter > request
infra::Optional< HttpResponseParser > response
Private Member Functions
void ForwardStream (infra::SharedPtr< infra::StreamWriter > &&writer)
void RequestForwardStreamOrExpectResponse ()
void HandleData ()
void BodyReceived ()
void BodyReaderDestroyed ()
void BodyComplete ()
void ExecuteRequest (HttpVerb verb, infra::BoundedConstString requestTarget, const HttpHeaders headers)
void ExecuteRequestWithContent (HttpVerb verb, infra::BoundedConstString requestTarget, infra::BoundedConstString content, const HttpHeaders headers)
void ExecuteRequestWithContent (HttpVerb verb, infra::BoundedConstString requestTarget, std::size_t contentSize, const HttpHeaders headers)
void AbortAndDestroy ()
Private Attributes
infra::BoundedString & headerBuffer
infra::BoundedConstString hostname
infra::Optional< uint32_t > contentLength
infra::Optional< BodyReader > bodyReader
infra::AccessedBySharedPtr bodyReaderAccess
std::size_t streamingContentSize = 0
bool forwardingStream = false
infra::AccessedBySharedPtr forwardStreamAccess
infra::SharedPtr< infra::StreamWriter > forwardStreamPtr
Detailed Description
Definition at line 37 of file HttpClientImpl.hpp.
Member Typedef Documentation
WithMaxHeaderSize
template<std::size_t MaxHeaderSize> using services::HttpClientImpl::WithMaxHeaderSize = infra::WithStorage<HttpClientImpl, infra::BoundedString::WithStorage<MaxHeaderSize> >
Definition at line 43 of file HttpClientImpl.hpp.
Constructor & Destructor Documentation
HttpClientImpl()
services::HttpClientImpl::HttpClientImpl (infra::BoundedString & headerBuffer, infra::BoundedConstString hostname)
Definition at line 82 of file HttpClientImpl.cpp.
         : headerBuffer(headerBuffer)
         , hostname(hostname)
     {}
Member Function Documentation
AbortAndDestroy()
void services::HttpClientImpl::AbortAndDestroy () private
Definition at line 305 of file HttpClientImpl.cpp.
References bodyReaderAccess, infra::AccessedBySharedPtr::SetAction(), and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by DataReceived(), and HandleData().
     {
         bodyReaderAccess.SetAction([]() {});
         ConnectionObserver::Subject().AbortAndDestroy();
     }
AckReceived()
void services::HttpClientImpl::AckReceived () override virtual
Implements services::HttpClient.
Definition at line 138 of file HttpClientImpl.cpp.
References infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         ConnectionObserver::Subject().AckReceived();
     }
AttachObserver()
void services::HttpClientImpl::AttachObserver (const infra::SharedPtr< HttpClientObserver > & observer)
Definition at line 87 of file HttpClientImpl.cpp.
References observer.
     {
         this->observer = observer;
         observer->Attach(*this);
     }
BodyComplete()
void services::HttpClientImpl::BodyComplete () private
Definition at line 279 of file HttpClientImpl.cpp.
References contentLength, infra::none, observer, and response.
Referenced by BodyReaderDestroyed(), and BodyReceived().
     {
         contentLength = infra::none;
         response = infra::none;
         observer->BodyComplete();
     }
BodyReaderDestroyed()
void services::HttpClientImpl::BodyReaderDestroyed () private
Definition at line 269 of file HttpClientImpl.cpp.
References BodyComplete(), bodyReader, contentLength, infra::none, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         ConnectionObserver::Subject().AckReceived();
         *contentLength -= bodyReader->countingReader.TotalRead();
         bodyReader = infra::none;
         if (*contentLength == 0)
             BodyComplete();
     }
BodyReceived()
void services::HttpClientImpl::BodyReceived () private
Definition at line 254 of file HttpClientImpl.cpp.
References BodyComplete(), bodyReader, bodyReaderAccess, contentLength, infra::MakeContainedSharedObject(), infra::AccessedBySharedPtr::MakeShared(), observer, response, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by HandleData().
     {
         if (!contentLength)
             contentLength = response->ContentLength();
         if (contentLength == 0)
             BodyComplete();
         else
         {
             bodyReader.Emplace(ConnectionObserver::Subject().ReceiveStream(), *contentLength);
             observer->BodyAvailable(infra::MakeContainedSharedObject(bodyReader->countingReader, bodyReaderAccess.MakeShared(bodyReader)));
         }
     }
Close()
void services::HttpClientImpl::Close () override virtual
Implements services::HttpClient.
Definition at line 143 of file HttpClientImpl.cpp.
References bodyReaderAccess, infra::AccessedBySharedPtr::SetAction(), and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         bodyReaderAccess.SetAction([]() {});
         ConnectionObserver::Subject().CloseAndDestroy();
     }
ClosingConnection()
void services::HttpClientImpl::ClosingConnection () override virtual
Reimplemented from services::ConnectionObserver.
Reimplemented in services::TracingHttpClientImpl.
Definition at line 182 of file HttpClientImpl.cpp.
References infra::Subject< HttpClientObserver >::GetObserver(), and observer.
Referenced by services::TracingHttpClientImpl::ClosingConnection().
     {
         GetObserver().ClosingConnection();
         observer->Detach();
     }
Connect()
void services::HttpClientImpl::Connect (infra::BoundedConstString requestTarget, HttpHeaders headers) override virtual
Implements services::HttpClient.
Definition at line 103 of file HttpClientImpl.cpp.
References services::connect, and ExecuteRequest().
     {
         ExecuteRequest(HttpVerb::connect, requestTarget, headers);
     }
Connected()
void services::HttpClientImpl::Connected () override virtual
Reimplemented from services::ConnectionObserver.
Reimplemented in services::TracingHttpClientImpl.
Definition at line 170 of file HttpClientImpl.cpp.
References bodyReaderAccess, infra::Subject< HttpClientObserver >::GetObserver(), infra::AccessedBySharedPtr::SetAction(), and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by services::TracingHttpClientImpl::Connected().
     {
         infra::WeakPtr<services::HttpClientImpl> self = infra::StaticPointerCast<HttpClientImpl>(services::ConnectionObserver::Subject().Observer());
         bodyReaderAccess.SetAction([self]()
         {
             if (auto sharedSelf = self.lock())
                 sharedSelf->BodyReaderDestroyed();
         });
         GetObserver().Connected();
     }
DataReceived()
void services::HttpClientImpl::DataReceived () override virtual
Implements services::ConnectionObserver.
Reimplemented in services::TracingHttpClientImpl.
Definition at line 157 of file HttpClientImpl.cpp.
References AbortAndDestroy(), bodyReader, bodyReaderAccess, HandleData(), infra::MakeContainedSharedObject(), infra::AccessedBySharedPtr::MakeShared(), infra::none, observer, and response.
Referenced by services::TracingHttpClientImpl::DataReceived().
     {
         if (bodyReader != infra::none)
             observer->BodyAvailable(infra::MakeContainedSharedObject(bodyReader->countingReader, bodyReaderAccess.MakeShared(bodyReader)));
         else
         {
             if (response)
                 HandleData();
             else
                 AbortAndDestroy();
         }
     }
Delete()
void services::HttpClientImpl::Delete (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers = noHeaders) override virtual
Implements services::HttpClient.
Definition at line 133 of file HttpClientImpl.cpp.
References services::delete_, and ExecuteRequestWithContent().
     {
         ExecuteRequestWithContent(HttpVerb::delete_, requestTarget, content, headers);
     }
ExecuteRequest()
void services::HttpClientImpl::ExecuteRequest (HttpVerb verb, infra::BoundedConstString requestTarget, const HttpHeaders headers) private
Definition at line 286 of file HttpClientImpl.cpp.
References hostname, request, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by Connect(), Get(), Head(), and Options().
     {
         request.Emplace(verb, hostname, requestTarget, headers);
         ConnectionObserver::Subject().RequestSendStream(request->Size());
     }
ExecuteRequestWithContent() [1/2]
void services::HttpClientImpl::ExecuteRequestWithContent (HttpVerb verb, infra::BoundedConstString requestTarget, infra::BoundedConstString content, const HttpHeaders headers) private
Definition at line 292 of file HttpClientImpl.cpp.
References hostname, request, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by Delete(), Patch(), Post(), and Put().
     {
         request.Emplace(verb, hostname, requestTarget, content, headers);
         ConnectionObserver::Subject().RequestSendStream(request->Size());
     }
ExecuteRequestWithContent() [2/2]
void services::HttpClientImpl::ExecuteRequestWithContent (HttpVerb verb, infra::BoundedConstString requestTarget, std::size_t contentSize, const HttpHeaders headers) private
Definition at line 298 of file HttpClientImpl.cpp.
References hostname, request, streamingContentSize, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         request.Emplace(verb, hostname, requestTarget, contentSize, headers);
         streamingContentSize = contentSize;
         ConnectionObserver::Subject().RequestSendStream(request->Size());
     }
ForwardStream()
void services::HttpClientImpl::ForwardStream (infra::SharedPtr< infra::StreamWriter > && writer) private
Definition at line 203 of file HttpClientImpl.cpp.
References infra::StreamWriter::Available(), forwardStreamAccess, forwardStreamPtr, infra::AccessedBySharedPtr::MakeShared(), observer, RequestForwardStreamOrExpectResponse(), infra::AccessedBySharedPtr::SetAction(), and streamingContentSize.
Referenced by SendStreamAvailable().
     {
         forwardStreamPtr = std::move(writer);
         auto available = forwardStreamPtr->Available();
         forwardStreamAccess.SetAction([this, available]()
         {
             streamingContentSize -= available - forwardStreamPtr->Available();
             forwardStreamPtr = nullptr;
             RequestForwardStreamOrExpectResponse();
         });
         observer->SendStreamAvailable(forwardStreamAccess.MakeShared(*forwardStreamPtr));
     }
Get()
void services::HttpClientImpl::Get (infra::BoundedConstString requestTarget, HttpHeaders headers) override virtual
Implements services::HttpClient.
Definition at line 93 of file HttpClientImpl.cpp.
References ExecuteRequest(), and services::get.
     {
         ExecuteRequest(HttpVerb::get, requestTarget, headers);
     }
HandleData()
void services::HttpClientImpl::HandleData () private
Definition at line 229 of file HttpClientImpl.cpp.
References AbortAndDestroy(), BodyReceived(), response, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by DataReceived().
     {
         if (!response->Done())
         {
             auto reader = ConnectionObserver::Subject().ReceiveStream();
             infra::WeakPtr<services::ConnectionObserver> self = services::ConnectionObserver::Subject().Observer();
             response->DataReceived(*reader);
             if (!self.lock())   // DataReceived may close the connection
                 return;
             ConnectionObserver::Subject().AckReceived();
         }
         if (response->Done())
         {
             if (!response->Error())
                 BodyReceived();
             else
                 AbortAndDestroy();
         }
     }
Head()
void services::HttpClientImpl::Head (infra::BoundedConstString requestTarget, HttpHeaders headers) override virtual
Implements services::HttpClient.
Definition at line 98 of file HttpClientImpl.cpp.
References ExecuteRequest(), and services::head.
     {
         ExecuteRequest(HttpVerb::head, requestTarget, headers);
     }
Options()
void services::HttpClientImpl::Options (infra::BoundedConstString requestTarget, HttpHeaders headers) override virtual
Implements services::HttpClient.
Definition at line 108 of file HttpClientImpl.cpp.
References ExecuteRequest(), and services::options.
     {
         ExecuteRequest(HttpVerb::options, requestTarget, headers);
     }
Patch()
void services::HttpClientImpl::Patch (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers = noHeaders) override virtual
Implements services::HttpClient.
Definition at line 128 of file HttpClientImpl.cpp.
References ExecuteRequestWithContent(), and services::patch.
     {
         ExecuteRequestWithContent(HttpVerb::patch, requestTarget, content, headers);
     }
Post()
void services::HttpClientImpl::Post (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers) override virtual
Implements services::HttpClient.
Definition at line 113 of file HttpClientImpl.cpp.
References ExecuteRequestWithContent(), and services::post.
     {
         ExecuteRequestWithContent(HttpVerb::post, requestTarget, content, headers);
     }
Put() [1/2]
void services::HttpClientImpl::Put (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers = noHeaders) override virtual
Implements services::HttpClient.
Definition at line 118 of file HttpClientImpl.cpp.
References ExecuteRequestWithContent(), and services::put.
     {
         ExecuteRequestWithContent(HttpVerb::put, requestTarget, content, headers);
     }
Put() [2/2]
void services::HttpClientImpl::Put (infra::BoundedConstString requestTarget, std::size_t contentSize, HttpHeaders headers = noHeaders) override virtual
Implements services::HttpClient.
Definition at line 123 of file HttpClientImpl.cpp.
References ExecuteRequestWithContent(), and services::put.
     {
         ExecuteRequestWithContent(HttpVerb::put, requestTarget, contentSize, headers);
     }
RequestForwardStreamOrExpectResponse()
void services::HttpClientImpl::RequestForwardStreamOrExpectResponse () private
Definition at line 219 of file HttpClientImpl.cpp.
References forwardingStream, headerBuffer, response, streamingContentSize, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by ForwardStream(), and WriteRequest().
     {
         forwardingStream = streamingContentSize != 0;
         if (forwardingStream)
             ConnectionObserver::Subject().RequestSendStream(std::min(streamingContentSize, ConnectionObserver::Subject().MaxSendStreamSize()));
         else
             response.Emplace(*this, headerBuffer);
     }
SendStreamAvailable()
void services::HttpClientImpl::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::ConnectionObserver.
Definition at line 149 of file HttpClientImpl.cpp.
References forwardingStream, ForwardStream(), and WriteRequest().
     {
         if (forwardingStream)
             ForwardStream(std::move(writer));
         else
             WriteRequest(std::move(writer));
     }
StatusAvailable()
void services::HttpClientImpl::StatusAvailable (HttpStatusCode code, infra::BoundedConstString statusLine) protected virtual
Reimplemented in services::TracingStatusHttpClientImpl.
Definition at line 188 of file HttpClientImpl.cpp.
References observer.
Referenced by services::TracingStatusHttpClientImpl::StatusAvailable().
     {
         observer->StatusAvailable(code);
     }
WriteRequest()
void services::HttpClientImpl::WriteRequest (infra::SharedPtr< infra::StreamWriter > && writer) protected virtual
Reimplemented in services::TracingHttpClientImpl.
Definition at line 193 of file HttpClientImpl.cpp.
References infra::none, request, and RequestForwardStreamOrExpectResponse().
Referenced by SendStreamAvailable(), and services::TracingHttpClientImpl::WriteRequest().
     {
         infra::TextOutputStream::WithErrorPolicy stream(*writer);
         request->Write(stream);
         request = infra::none;
         writer = nullptr;
         RequestForwardStreamOrExpectResponse();
     }
Member Data Documentation
bodyReader
infra::Optional<BodyReader> services::HttpClientImpl::bodyReader private
Definition at line 133 of file HttpClientImpl.hpp.
Referenced by BodyReaderDestroyed(), BodyReceived(), and DataReceived().
bodyReaderAccess
infra::AccessedBySharedPtr services::HttpClientImpl::bodyReaderAccess private
Definition at line 134 of file HttpClientImpl.hpp.
Referenced by AbortAndDestroy(), BodyReceived(), Close(), Connected(), and DataReceived().
contentLength
infra::Optional<uint32_t> services::HttpClientImpl::contentLength private
Definition at line 132 of file HttpClientImpl.hpp.
Referenced by BodyComplete(), BodyReaderDestroyed(), BodyReceived(), services::HttpClientImpl::HttpResponseParser::ContentLength(), and services::HttpClientImpl::HttpResponseParser::ParseHeaders().
forwardingStream
bool services::HttpClientImpl::forwardingStream = false private
Definition at line 136 of file HttpClientImpl.hpp.
Referenced by RequestForwardStreamOrExpectResponse(), and SendStreamAvailable().
forwardStreamAccess
infra::AccessedBySharedPtr services::HttpClientImpl::forwardStreamAccess private
Definition at line 137 of file HttpClientImpl.hpp.
Referenced by ForwardStream().
forwardStreamPtr
infra::SharedPtr<infra::StreamWriter> services::HttpClientImpl::forwardStreamPtr private
Definition at line 138 of file HttpClientImpl.hpp.
Referenced by ForwardStream().
headerBuffer
infra::BoundedString& services::HttpClientImpl::headerBuffer private
Definition at line 130 of file HttpClientImpl.hpp.
Referenced by services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpClientImpl::HttpResponseParser::ParseStatusLine(), and RequestForwardStreamOrExpectResponse().
hostname
infra::BoundedConstString services::HttpClientImpl::hostname private
Definition at line 131 of file HttpClientImpl.hpp.
Referenced by ExecuteRequest(), and ExecuteRequestWithContent().
observer
infra::SharedPtr<HttpClientObserver> services::HttpClientImpl::observer protected
Definition at line 125 of file HttpClientImpl.hpp.
Referenced by AttachObserver(), BodyComplete(), BodyReceived(), ClosingConnection(), DataReceived(), ForwardStream(), and StatusAvailable().
request
infra::Optional<HttpRequestFormatter> services::HttpClientImpl::request protected
Definition at line 126 of file HttpClientImpl.hpp.
Referenced by ExecuteRequest(), ExecuteRequestWithContent(), services::TracingHttpClientImpl::WriteRequest(), and WriteRequest().
response
infra::Optional<HttpResponseParser> services::HttpClientImpl::response protected
Definition at line 127 of file HttpClientImpl.hpp.
Referenced by BodyComplete(), BodyReceived(), DataReceived(), HandleData(), and RequestForwardStreamOrExpectResponse().
streamingContentSize
std::size_t services::HttpClientImpl::streamingContentSize = 0 private
Definition at line 135 of file HttpClientImpl.hpp.
Referenced by ExecuteRequestWithContent(), ForwardStream(), and RequestForwardStreamOrExpectResponse().
The documentation for this class was generated from the following files:
HttpClientImpl.hpp
HttpClientImpl.cpp