EMil: services::SpiMasterWithChipSelect Class Reference
services::SpiMasterWithChipSelect Class Reference
#include <SpiMasterWithChipSelect.hpp>
Public Member Functions
SpiMasterWithChipSelect (hal::SpiMaster &aSpi, hal::GpioPin &aChipSelect)
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> &onDone) override
virtual void SetChipSelectConfigurator (hal::ChipSelectConfigurator &configurator) override
virtual void SetCommunicationConfigurator (hal::CommunicationConfigurator &configurator) override
virtual void ResetCommunicationConfigurator () override
virtual void StartSession () override
virtual void EndSession () override
Public Member Functions inherited from hal::SpiMaster
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
Private Attributes
hal::SpiMaster & spi
hal::OutputPin chipSelect
hal::ChipSelectConfigurator * chipSelectConfigurator = nullptr
Additional Inherited Members
Protected Member Functions inherited from hal::SpiMaster
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Protected Member Functions inherited from hal::ChipSelectConfigurator
ChipSelectConfigurator ()=default
ChipSelectConfigurator (const ChipSelectConfigurator &other)=delete
ChipSelectConfigurator & operator= (const ChipSelectConfigurator &other)=delete
~ChipSelectConfigurator ()=default
Detailed Description
Definition at line 9 of file SpiMasterWithChipSelect.hpp.
Constructor & Destructor Documentation
SpiMasterWithChipSelect()
services::SpiMasterWithChipSelect::SpiMasterWithChipSelect (hal::SpiMaster & aSpi, hal::GpioPin & aChipSelect)
Definition at line 5 of file SpiMasterWithChipSelect.cpp.
References hal::SpiMaster::SetChipSelectConfigurator(), and spi.
         : spi(spi)
         , chipSelect(chipSelect, true)
     {
         spi.SetChipSelectConfigurator(*this);
     }
Member Function Documentation
EndSession()
void services::SpiMasterWithChipSelect::EndSession () override virtual
Implements hal::ChipSelectConfigurator.
Definition at line 40 of file SpiMasterWithChipSelect.cpp.
References chipSelect, chipSelectConfigurator, hal::ChipSelectConfigurator::EndSession(), and hal::OutputPin::Set().
     {
         chipSelect.Set(true);
         if (chipSelectConfigurator != nullptr)
             chipSelectConfigurator->EndSession();
     }
ResetCommunicationConfigurator()
void services::SpiMasterWithChipSelect::ResetCommunicationConfigurator () override virtual
Implements hal::SpiMaster.
Definition at line 27 of file SpiMasterWithChipSelect.cpp.
References hal::SpiMaster::ResetCommunicationConfigurator(), and spi.
     {
         spi.ResetCommunicationConfigurator();
     }
SendAndReceive()
void services::SpiMasterWithChipSelect::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> & onDone) override virtual
Implements hal::SpiMaster.
Definition at line 12 of file SpiMasterWithChipSelect.cpp.
References hal::SpiMaster::SendAndReceive(), and spi.
     {
         spi.SendAndReceive(sendData, receiveData, nextAction, onDone);
     }
SetChipSelectConfigurator()
void services::SpiMasterWithChipSelect::SetChipSelectConfigurator (hal::ChipSelectConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 17 of file SpiMasterWithChipSelect.cpp.
References chipSelectConfigurator.
     {
         chipSelectConfigurator = &configurator;
     }
SetCommunicationConfigurator()
void services::SpiMasterWithChipSelect::SetCommunicationConfigurator (hal::CommunicationConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 22 of file SpiMasterWithChipSelect.cpp.
References hal::SpiMaster::SetCommunicationConfigurator(), and spi.
     {
         spi.SetCommunicationConfigurator(configurator);
     }
StartSession()
void services::SpiMasterWithChipSelect::StartSession () override virtual
Implements hal::ChipSelectConfigurator.
Definition at line 32 of file SpiMasterWithChipSelect.cpp.
References chipSelect, chipSelectConfigurator, hal::OutputPin::Set(), and hal::ChipSelectConfigurator::StartSession().
     {
         if (chipSelectConfigurator != nullptr)
             chipSelectConfigurator->StartSession();
         chipSelect.Set(false);
     }
Member Data Documentation
chipSelect
hal::OutputPin services::SpiMasterWithChipSelect::chipSelect private
Definition at line 27 of file SpiMasterWithChipSelect.hpp.
Referenced by EndSession(), and StartSession().
chipSelectConfigurator
hal::ChipSelectConfigurator* services::SpiMasterWithChipSelect::chipSelectConfigurator = nullptr private
Definition at line 28 of file SpiMasterWithChipSelect.hpp.
Referenced by EndSession(), SetChipSelectConfigurator(), and StartSession().
spi
hal::SpiMaster& services::SpiMasterWithChipSelect::spi private
Definition at line 26 of file SpiMasterWithChipSelect.hpp.
Referenced by ResetCommunicationConfigurator(), SendAndReceive(), SetCommunicationConfigurator(), and SpiMasterWithChipSelect().
The documentation for this class was generated from the following files:
SpiMasterWithChipSelect.hpp
SpiMasterWithChipSelect.cpp