EMil: infra::EventDispatcherWithWeakPtrWorker Class Reference
infra::EventDispatcherWithWeakPtrWorker Class Reference
#include <EventDispatcherWithWeakPtr.hpp>
Classes
class Action
class ActionFunction
class ActionWithWeakPtr
Public Types
using ActionStorage = StaticStorageForPolymorphicObjects< Action, INFRA_EVENT_DISPATCHER_WITH_WEAK_PTR_FUNCTION_EXTRA_SIZE >
template<std::size_t StorageSize, class T = EventDispatcherWithWeakPtrWorker>
using WithSize = infra::WithStorage< T, std::array< std::pair< ActionStorage, std::atomic< bool > >, StorageSize > >
Public Member Functions
EventDispatcherWithWeakPtrWorker (MemoryRange< std::pair< ActionStorage, std::atomic< bool >>> scheduledActionsStorage)
virtual void Schedule (const infra::Function< void()> &action) override
template<class T >
void Schedule (const typename std::decay< infra::Function< void(const infra::SharedPtr< T > &object)>>::type &action, const infra::SharedPtr< T > &object)
template<class T >
void Schedule (const typename std::decay< infra::Function< void(const infra::SharedPtr< T > &object)>>::type &action, const infra::WeakPtr< T > &object)
virtual std::size_t MinCapacity () const override
virtual bool IsIdle () const override
void Run ()
void ExecuteAllActions ()
Protected Member Functions
virtual void RequestExecution ()
virtual void Idle ()
virtual void ExecuteFirstAction () override
Protected Member Functions inherited from infra::EventDispatcherWorker
EventDispatcherWorker ()=default
EventDispatcherWorker (const EventDispatcherWorker &other)=delete
EventDispatcherWorker & operator= (const EventDispatcherWorker &other)=delete
~EventDispatcherWorker ()=default
Private Member Functions
bool TryExecuteAction ()
Private Attributes
infra::MemoryRange< std::pair< ActionStorage, std::atomic< bool > > > scheduledActions
std::atomic< uint32_t > scheduledActionsPushIndex
uint32_t scheduledActionsPopIndex
std::size_t minCapacity
Detailed Description
Definition at line 13 of file EventDispatcherWithWeakPtr.hpp.
Member Typedef Documentation
ActionStorage
using infra::EventDispatcherWithWeakPtrWorker::ActionStorage = StaticStorageForPolymorphicObjects<Action, INFRA_EVENT_DISPATCHER_WITH_WEAK_PTR_FUNCTION_EXTRA_SIZE>
Definition at line 52 of file EventDispatcherWithWeakPtr.hpp.
WithSize
template<std::size_t StorageSize, class T = EventDispatcherWithWeakPtrWorker> using infra::EventDispatcherWithWeakPtrWorker::WithSize = infra::WithStorage<T, std::array<std::pair<ActionStorage, std::atomic<bool> >, StorageSize> >
Definition at line 54 of file EventDispatcherWithWeakPtr.hpp.
Constructor & Destructor Documentation
EventDispatcherWithWeakPtrWorker()
infra::EventDispatcherWithWeakPtrWorker::EventDispatcherWithWeakPtrWorker (MemoryRange< std::pair< ActionStorage, std::atomic< bool >>> scheduledActionsStorage) explicit
Definition at line 6 of file EventDispatcherWithWeakPtr.cpp.
References scheduledActions.
         : scheduledActions(scheduledActionsStorage)
         , scheduledActionsPushIndex(0)
         , scheduledActionsPopIndex(0)
         , minCapacity(scheduledActions.size())
     {
         for (auto& action : scheduledActions)
             action.second = false;
     }
Member Function Documentation
ExecuteAllActions()
void infra::EventDispatcherWithWeakPtrWorker::ExecuteAllActions ()
Definition at line 45 of file EventDispatcherWithWeakPtr.cpp.
References TryExecuteAction().
Referenced by Run().
     {
         while (TryExecuteAction())
         {}
     }
ExecuteFirstAction()
void infra::EventDispatcherWithWeakPtrWorker::ExecuteFirstAction () override protected virtual
Implements infra::EventDispatcherWorker.
Definition at line 67 of file EventDispatcherWithWeakPtr.cpp.
References scheduledActions, and scheduledActionsPopIndex.
Referenced by TryExecuteAction().
     {
         scheduledActions[scheduledActionsPopIndex].first->Execute();
     }
Idle()
void infra::EventDispatcherWithWeakPtrWorker::Idle () protected virtual
Reimplemented in infra::LowPowerEventDispatcherWorker.
Definition at line 64 of file EventDispatcherWithWeakPtr.cpp.
Referenced by Run().
     {}
IsIdle()
bool infra::EventDispatcherWithWeakPtrWorker::IsIdle () const override virtual
Implements infra::EventDispatcherWorker.
Definition at line 51 of file EventDispatcherWithWeakPtr.cpp.
References scheduledActions, and scheduledActionsPopIndex.
     {
         return !scheduledActions[scheduledActionsPopIndex].second;
     }
MinCapacity()
std::size_t infra::EventDispatcherWithWeakPtrWorker::MinCapacity () const override virtual
Implements infra::EventDispatcherWorker.
Definition at line 56 of file EventDispatcherWithWeakPtr.cpp.
References minCapacity.
     {
         return minCapacity;
     }
RequestExecution()
void infra::EventDispatcherWithWeakPtrWorker::RequestExecution () protected virtual
Reimplemented in infra::LowPowerEventDispatcherWorker.
Definition at line 61 of file EventDispatcherWithWeakPtr.cpp.
Referenced by Schedule().
     {}
Run()
void infra::EventDispatcherWithWeakPtrWorker::Run ()
Definition at line 36 of file EventDispatcherWithWeakPtr.cpp.
References ExecuteAllActions(), and Idle().
     {
         while (true)                                                                                            //TICS !CPP4127
         {
             ExecuteAllActions();
             Idle();
         }
     }
Schedule() [1/3]
void infra::EventDispatcherWithWeakPtrWorker::Schedule (const infra::Function< void()> & action) override virtual
Implements infra::EventDispatcherWorker.
Definition at line 16 of file EventDispatcherWithWeakPtr.cpp.
References minCapacity, RequestExecution(), scheduledActions, scheduledActionsPopIndex, and scheduledActionsPushIndex.
Referenced by services::ConnectionMbedTls::DataReceived(), services::ConnectionBsd::Receive(), services::ConnectionWin::Receive(), Schedule(), services::ConnectionMbedTls::SslReceive(), services::ConnectionMbedTls::SslSend(), services::ConnectionBsd::TryAllocateSendStream(), services::DatagramBsd::TryAllocateSendStream(), services::DatagramWin::TryAllocateSendStream(), services::ConnectionWin::TryAllocateSendStream(), and services::ConnectionMbedTls::TryAllocateSendStream().
     {
         uint32_t pushIndex = scheduledActionsPushIndex;
         uint32_t newPushIndex;
         do
         {
             newPushIndex = (pushIndex + 1) % scheduledActions.size();
         } while (!scheduledActionsPushIndex.compare_exchange_weak(pushIndex, newPushIndex));
         scheduledActions[pushIndex].first.Construct<ActionFunction>(action);
         really_assert(!scheduledActions[pushIndex].second);
         scheduledActions[pushIndex].second = true;
         minCapacity = std::min<std::size_t>(minCapacity, (scheduledActions.size() + scheduledActionsPopIndex - pushIndex - 1) % scheduledActions.size() + 1);
         really_assert(minCapacity >= 1);
         RequestExecution();
     }
Schedule() [2/3]
template<class T > void infra::EventDispatcherWithWeakPtrWorker::Schedule (const typename std::decay< infra::Function< void(const infra::SharedPtr< T > &object)>>::type & action, const infra::SharedPtr< T > & object)
Definition at line 108 of file EventDispatcherWithWeakPtr.hpp.
References Schedule().
     {
         assert(object != nullptr);
         Schedule(action, infra::WeakPtr<T>(object));
     }
Schedule() [3/3]
template<class T > void infra::EventDispatcherWithWeakPtrWorker::Schedule (const typename std::decay< infra::Function< void(const infra::SharedPtr< T > &object)>>::type & action, const infra::WeakPtr< T > & object)
Definition at line 115 of file EventDispatcherWithWeakPtr.hpp.
References minCapacity, RequestExecution(), scheduledActions, scheduledActionsPopIndex, and scheduledActionsPushIndex.
     {
         uint32_t pushIndex = scheduledActionsPushIndex;
         uint32_t newPushIndex;
         do
         {
             newPushIndex = (pushIndex + 1) % scheduledActions.size();
         } while (!scheduledActionsPushIndex.compare_exchange_weak(pushIndex, newPushIndex));
         scheduledActions[pushIndex].first.Construct<ActionWithWeakPtr<T>>(action, object);
         assert(!scheduledActions[pushIndex].second);
         scheduledActions[pushIndex].second = true;
         minCapacity = std::min<std::size_t>(minCapacity, (scheduledActions.size() + scheduledActionsPopIndex - pushIndex - 1) % scheduledActions.size() + 1);
         assert(minCapacity >= 1);
         RequestExecution();
     }
TryExecuteAction()
bool infra::EventDispatcherWithWeakPtrWorker::TryExecuteAction () private
Definition at line 72 of file EventDispatcherWithWeakPtr.cpp.
References ExecuteFirstAction(), scheduledActions, and scheduledActionsPopIndex.
Referenced by ExecuteAllActions().
     {
         if (scheduledActions[scheduledActionsPopIndex].second)
         {
             ExecuteFirstAction();
             scheduledActions[scheduledActionsPopIndex].first.Destruct();
             scheduledActions[scheduledActionsPopIndex].second = false;
             scheduledActionsPopIndex = (scheduledActionsPopIndex + 1) % scheduledActions.size();
             return true;
         }
         else
             return false;
     }
Member Data Documentation
minCapacity
std::size_t infra::EventDispatcherWithWeakPtrWorker::minCapacity private
Definition at line 84 of file EventDispatcherWithWeakPtr.hpp.
Referenced by MinCapacity(), and Schedule().
scheduledActions
infra::MemoryRange<std::pair<ActionStorage, std::atomic<bool> > > infra::EventDispatcherWithWeakPtrWorker::scheduledActions private
Definition at line 81 of file EventDispatcherWithWeakPtr.hpp.
Referenced by EventDispatcherWithWeakPtrWorker(), ExecuteFirstAction(), IsIdle(), Schedule(), and TryExecuteAction().
scheduledActionsPopIndex
uint32_t infra::EventDispatcherWithWeakPtrWorker::scheduledActionsPopIndex private
Definition at line 83 of file EventDispatcherWithWeakPtr.hpp.
Referenced by ExecuteFirstAction(), IsIdle(), Schedule(), and TryExecuteAction().
scheduledActionsPushIndex
std::atomic<uint32_t> infra::EventDispatcherWithWeakPtrWorker::scheduledActionsPushIndex private
Definition at line 82 of file EventDispatcherWithWeakPtr.hpp.
Referenced by Schedule().
The documentation for this class was generated from the following files:
EventDispatcherWithWeakPtr.hpp
EventDispatcherWithWeakPtr.cpp