EMil: services::ConnectionFactoryMock Class Reference
services::ConnectionFactoryMock Class Reference
#include <ConnectionMock.hpp>
Public Member Functions
virtual infra::SharedPtr< void > Listen (uint16_t port, ServerConnectionObserverFactory &factory, IPVersions versions) override
MOCK_METHOD1 (Connect, void(ClientConnectionObserverFactory &factory))
MOCK_METHOD1 (CancelConnect, void(ClientConnectionObserverFactory &factory))
MOCK_METHOD2 (ListenMock, infra::SharedPtr< void >(uint16_t, IPVersions))
void NewConnection (Connection &connection, services::IPAddress address)
Public Member Functions inherited from services::ConnectionFactory
virtual void Connect (ClientConnectionObserverFactory &factory)=0
virtual void CancelConnect (ClientConnectionObserverFactory &factory)=0
Private Attributes
ServerConnectionObserverFactory * serverConnectionObserverFactory = nullptr
Additional Inherited Members
Protected Member Functions inherited from services::ConnectionFactory
ConnectionFactory ()=default
ConnectionFactory (const ConnectionFactory &other)=delete
ConnectionFactory & operator= (const ConnectionFactory &other)=delete
~ConnectionFactory ()=default
Detailed Description
Definition at line 41 of file ConnectionMock.hpp.
Member Function Documentation
Listen()
infra::SharedPtr< void > services::ConnectionFactoryMock::Listen (uint16_t port, ServerConnectionObserverFactory & factory, IPVersions versions) override virtual
Implements services::ConnectionFactory.
Definition at line 5 of file ConnectionMock.cpp.
References serverConnectionObserverFactory.
     {
         this->serverConnectionObserverFactory = &factory;
         return ListenMock(port, versions);
     }
MOCK_METHOD1() [1/2]
services::ConnectionFactoryMock::MOCK_METHOD1 (Connect , void(ClientConnectionObserverFactory &factory))
MOCK_METHOD1() [2/2]
services::ConnectionFactoryMock::MOCK_METHOD1 (CancelConnect , void(ClientConnectionObserverFactory &factory))
MOCK_METHOD2()
services::ConnectionFactoryMock::MOCK_METHOD2 (ListenMock , infra::SharedPtr< void > uint16_t, IPVersions)
NewConnection()
void services::ConnectionFactoryMock::NewConnection (Connection & connection, services::IPAddress address)
Definition at line 11 of file ConnectionMock.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), services::ConnectionObserver::Connected(), services::ServerConnectionObserverFactory::ConnectionAccepted(), serverConnectionObserverFactory, and services::Connection::SetOwnership().
     {
         serverConnectionObserverFactory->ConnectionAccepted([&connection](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             connectionObserver->Attach(connection);
             connection.SetOwnership(nullptr, connectionObserver);
             connectionObserver->Connected();
         }, address);
     }
Member Data Documentation
serverConnectionObserverFactory
ServerConnectionObserverFactory* services::ConnectionFactoryMock::serverConnectionObserverFactory = nullptr private
Definition at line 54 of file ConnectionMock.hpp.
Referenced by Listen(), and NewConnection().
The documentation for this class was generated from the following files:
ConnectionMock.hpp
ConnectionMock.cpp