EMil: services::FlashRegion Class Reference
services::FlashRegion Class Reference
#include <FlashRegion.hpp>
Public Member Functions
FlashRegion (hal::Flash &master, uint32_t startSector, uint32_t numberOfSectors)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Private Member Functions
uint32_t ToMasterAddress (uint32_t address) const
Private Attributes
hal::Flash & master
uint32_t startSector
uint32_t numberOfSectors
uint32_t masterAddressOfStartSector
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 8 of file FlashRegion.hpp.
Constructor & Destructor Documentation
FlashRegion()
services::FlashRegion::FlashRegion (hal::Flash & master, uint32_t startSector, uint32_t numberOfSectors)
Definition at line 6 of file FlashRegion.cpp.
References master, hal::Flash::NumberOfSectors(), numberOfSectors, and startSector.
         : master(master)
         , startSector(startSector)
         , numberOfSectors(numberOfSectors)
         , masterAddressOfStartSector(master.AddressOfSector(startSector))
     {
         really_assert(startSector + numberOfSectors <= master.NumberOfSectors());
     }
Member Function Documentation
AddressOfSector()
uint32_t services::FlashRegion::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 30 of file FlashRegion.cpp.
References hal::Flash::AddressOfSector(), master, masterAddressOfStartSector, and startSector.
     {
         return master.AddressOfSector(sectorIndex + startSector) - masterAddressOfStartSector;
     }
EraseSectors()
void services::FlashRegion::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 47 of file FlashRegion.cpp.
References hal::Flash::EraseSectors(), master, numberOfSectors, and startSector.
     {
         really_assert(beginIndex <= numberOfSectors && endIndex <= numberOfSectors);
         master.EraseSectors(beginIndex + startSector, endIndex + startSector, onDone);
     }
NumberOfSectors()
uint32_t services::FlashRegion::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 15 of file FlashRegion.cpp.
References numberOfSectors.
     {
         return numberOfSectors;
     }
ReadBuffer()
void services::FlashRegion::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 41 of file FlashRegion.cpp.
References master, masterAddressOfStartSector, numberOfSectors, hal::Flash::ReadBuffer(), SectorOfAddress(), and infra::MemoryRange< T >::size().
     {
         really_assert(SectorOfAddress(address) <= numberOfSectors && SectorOfAddress(address + buffer.size()) <= numberOfSectors);
         master.ReadBuffer(buffer, address + masterAddressOfStartSector, onDone);
     }
SectorOfAddress()
uint32_t services::FlashRegion::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 25 of file FlashRegion.cpp.
References master, masterAddressOfStartSector, hal::Flash::SectorOfAddress(), and startSector.
Referenced by ReadBuffer(), and WriteBuffer().
     {
         return master.SectorOfAddress(masterAddressOfStartSector + address) - startSector;
     }
SizeOfSector()
uint32_t services::FlashRegion::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 20 of file FlashRegion.cpp.
References master, hal::Flash::SizeOfSector(), and startSector.
     {
         return master.SizeOfSector(startSector + sectorIndex);
     }
ToMasterAddress()
uint32_t services::FlashRegion::ToMasterAddress (uint32_t address) const private
WriteBuffer()
void services::FlashRegion::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 35 of file FlashRegion.cpp.
References master, masterAddressOfStartSector, numberOfSectors, SectorOfAddress(), infra::MemoryRange< T >::size(), and hal::Flash::WriteBuffer().
     {
         really_assert(SectorOfAddress(address) <= numberOfSectors && SectorOfAddress(address + buffer.size()) <= numberOfSectors);
         master.WriteBuffer(buffer, address + masterAddressOfStartSector, onDone);
     }
Member Data Documentation
master
hal::Flash& services::FlashRegion::master private
Definition at line 29 of file FlashRegion.hpp.
Referenced by AddressOfSector(), EraseSectors(), FlashRegion(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), and WriteBuffer().
masterAddressOfStartSector
uint32_t services::FlashRegion::masterAddressOfStartSector private
Definition at line 32 of file FlashRegion.hpp.
Referenced by AddressOfSector(), ReadBuffer(), SectorOfAddress(), and WriteBuffer().
numberOfSectors
uint32_t services::FlashRegion::numberOfSectors private
Definition at line 31 of file FlashRegion.hpp.
Referenced by EraseSectors(), FlashRegion(), NumberOfSectors(), ReadBuffer(), and WriteBuffer().
startSector
uint32_t services::FlashRegion::startSector private
Definition at line 30 of file FlashRegion.hpp.
Referenced by AddressOfSector(), EraseSectors(), FlashRegion(), SectorOfAddress(), and SizeOfSector().
The documentation for this class was generated from the following files:
FlashRegion.hpp
FlashRegion.cpp