EMil: infra::StringInputStreamReader Class Reference
infra::StringInputStreamReader Class Reference
#include <StringInputStream.hpp>
Public Member Functions
StringInputStreamReader (BoundedConstString string)
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy) override
virtual ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
virtual std::size_t ConstructSaveMarker () const override
virtual void Rewind (std::size_t marker) override
Private Attributes
uint32_t offset = 0
BoundedConstString string
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 10 of file StringInputStream.hpp.
Constructor & Destructor Documentation
StringInputStreamReader()
infra::StringInputStreamReader::StringInputStreamReader (BoundedConstString string) explicit
Definition at line 5 of file StringInputStream.cpp.
         : string(string)
     {}
Member Function Documentation
Available()
std::size_t infra::StringInputStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 50 of file StringInputStream.cpp.
References offset.
     {
         return string.size() - offset;
     }
ConstructSaveMarker()
std::size_t infra::StringInputStreamReader::ConstructSaveMarker () const override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 55 of file StringInputStream.cpp.
References offset.
     {
         return offset;
     }
Empty()
bool infra::StringInputStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 45 of file StringInputStream.cpp.
References offset.
     {
         return offset == string.size();
     }
Extract()
void infra::StringInputStreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 9 of file StringInputStream.cpp.
References infra::detail::begin(), infra::MemoryRange< T >::begin(), offset, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         errorPolicy.ReportResult(offset + range.size() <= string.size());
         range.shrink_from_back_to(string.size() - offset);
         std::copy(string.begin() + offset, string.begin() + offset + range.size(), range.begin());
         offset += range.size();
     }
ExtractContiguousRange()
ConstByteRange infra::StringInputStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 31 of file StringInputStream.cpp.
References infra::data, offset, infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         ConstByteRange result(reinterpret_cast<const uint8_t*>(string.data()) + offset, reinterpret_cast<const uint8_t*>(string.data()) + string.size());
         result.shrink_from_back_to(max);
         offset += result.size();
         return result;
     }
Peek()
uint8_t infra::StringInputStreamReader::Peek (StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 17 of file StringInputStream.cpp.
References offset, and infra::StreamErrorPolicy::ReportResult().
     {
         if (offset == string.size())
         {
             errorPolicy.ReportResult(false);
             return 0;
         }
         else
         {
             errorPolicy.ReportResult(true);
             return static_cast<uint8_t>(string.begin()[offset]);
         }
     }
PeekContiguousRange()
ConstByteRange infra::StringInputStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 39 of file StringInputStream.cpp.
References infra::data.
     {
         ConstByteRange result(reinterpret_cast<const uint8_t*>(string.data()) + offset + start, reinterpret_cast<const uint8_t*>(string.data() + string.size()));
         return result;
     }
Rewind()
void infra::StringInputStreamReader::Rewind (std::size_t marker) override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 60 of file StringInputStream.cpp.
References offset.
     {
         offset = marker;
     }
Member Data Documentation
offset
uint32_t infra::StringInputStreamReader::offset = 0 private
Definition at line 28 of file StringInputStream.hpp.
Referenced by Available(), ConstructSaveMarker(), Empty(), Extract(), ExtractContiguousRange(), Peek(), and Rewind().
string
BoundedConstString infra::StringInputStreamReader::string private
Definition at line 29 of file StringInputStream.hpp.
The documentation for this class was generated from the following files:
StringInputStream.hpp
StringInputStream.cpp