EMil: TestStdStringOutputStream.cpp File Reference
TestStdStringOutputStream.cpp File Reference
Functions
TEST (StdStringOuputStreamTest, StdStringOutputStream)
TEST (StdStringOuputStreamTest, available_returns_max)
Function Documentation
TEST() [1/2]
TEST (StdStringOuputStreamTest , StdStringOutputStream)
Definition at line 5 of file TestStdStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StdStringOutputStream::WithStorage stream;
     stream << "abcd";
     EXPECT_EQ("abcd", stream.Storage());
 }
TEST() [2/2]
TEST (StdStringOuputStreamTest , available_returns_max)
Definition at line 14 of file TestStdStringOutputStream.cpp.
References infra::OutputStream::Available(), and EXPECT_EQ().
 {
     infra::StdStringOutputStream::WithStorage stream;
     EXPECT_EQ(std::numeric_limits<size_t>::max(), stream.Available());
 }