EMil: TestTracerAdapterPrintf.cpp File Reference
TestTracerAdapterPrintf.cpp File Reference
Classes
class TracerAdapterPrintfTest
Functions
void Print (const char *format,...)
TEST_F (TracerAdapterPrintfTest, print_format_string_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_escaped_percent_sign_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_unknown_format_string_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_character_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_string_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_null_string_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_int_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_long_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_long_with_width_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_long_long_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_float_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_int_in_hex_with_x_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_int_in_hex_with_width_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_int_in_hex_with_width_padding_0_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_int_in_hex_with_X_to_tracer)
TEST_F (TracerAdapterPrintfTest, print_multiple_values)
Variables
services::TracerAdapterPrintf * printfAdapter = nullptr
Function Documentation
Print()
void Print (const char * format, ...)
Definition at line 7 of file TestTracerAdapterPrintf.cpp.
References services::TracerAdapterPrintf::Print(), and printfAdapter.
Referenced by TEST_F().
 {
     ASSERT_TRUE(printfAdapter != nullptr);
     va_list args;
     va_start(args, format);
     printfAdapter->Print(format, &args);
     va_end(args);
 }
TEST_F() [1/16]
TEST_F (TracerAdapterPrintfTest , print_format_string_to_tracer)
Definition at line 34 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("Hello, Tracer!");
     EXPECT_EQ("Hello, Tracer!", stream.Storage());
 }
TEST_F() [2/16]
TEST_F (TracerAdapterPrintfTest , print_escaped_percent_sign_to_tracer)
Definition at line 40 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%%");
     EXPECT_EQ("%", stream.Storage());
 }
TEST_F() [3/16]
TEST_F (TracerAdapterPrintfTest , print_unknown_format_string_to_tracer)
Definition at line 46 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%llq");
     EXPECT_EQ("llq", stream.Storage());
 }
TEST_F() [4/16]
TEST_F (TracerAdapterPrintfTest , print_character_to_tracer)
Definition at line 52 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%c", 'A');
     EXPECT_EQ("A", stream.Storage());
 }
TEST_F() [5/16]
TEST_F (TracerAdapterPrintfTest , print_string_to_tracer)
Definition at line 58 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%s", "Hello, Tracer!");
     EXPECT_EQ("Hello, Tracer!", stream.Storage());
 }
TEST_F() [6/16]
TEST_F (TracerAdapterPrintfTest , print_null_string_to_tracer)
Definition at line 64 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%s", nullptr);
     EXPECT_EQ("(null)", stream.Storage());
 }
TEST_F() [7/16]
TEST_F (TracerAdapterPrintfTest , print_int_to_tracer)
Definition at line 70 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%d", -42);
     EXPECT_EQ("-42", stream.Storage());
 }
TEST_F() [8/16]
TEST_F (TracerAdapterPrintfTest , print_long_to_tracer)
Definition at line 76 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%ld", -42L);
     EXPECT_EQ("-42", stream.Storage());
 }
TEST_F() [9/16]
TEST_F (TracerAdapterPrintfTest , print_long_with_width_to_tracer)
Definition at line 82 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%08ld", -42L);
     EXPECT_EQ("-42", stream.Storage());
 }
TEST_F() [10/16]
TEST_F (TracerAdapterPrintfTest , print_long_long_to_tracer)
Definition at line 88 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%lld", -42LL);
     EXPECT_EQ("-42", stream.Storage());
 }
TEST_F() [11/16]
TEST_F (TracerAdapterPrintfTest , print_float_to_tracer)
Definition at line 94 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%f", 42.123f);
     EXPECT_EQ("42.123", stream.Storage());
 }
TEST_F() [12/16]
TEST_F (TracerAdapterPrintfTest , print_int_in_hex_with_x_to_tracer)
Definition at line 100 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%x", 0xABCD);
     EXPECT_EQ("abcd", stream.Storage());
 }
TEST_F() [13/16]
TEST_F (TracerAdapterPrintfTest , print_int_in_hex_with_width_to_tracer)
Definition at line 106 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%8x", 0xABCD);
     EXPECT_EQ("    abcd", stream.Storage());
 }
TEST_F() [14/16]
TEST_F (TracerAdapterPrintfTest , print_int_in_hex_with_width_padding_0_to_tracer)
Definition at line 112 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%08x", 0xABCD);
     EXPECT_EQ("0000abcd", stream.Storage());
 }
TEST_F() [15/16]
TEST_F (TracerAdapterPrintfTest , print_int_in_hex_with_X_to_tracer)
Definition at line 118 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%X", 0x123A);
     EXPECT_EQ("123a", stream.Storage());
 }
TEST_F() [16/16]
TEST_F (TracerAdapterPrintfTest , print_multiple_values)
Definition at line 124 of file TestTracerAdapterPrintf.cpp.
References EXPECT_EQ(), and Print().
 {
     Print("%u%u%u", 100, 200, 300);
     EXPECT_EQ("100200300", stream.Storage());
 }
Variable Documentation
printfAdapter
services::TracerAdapterPrintf* printfAdapter = nullptr
Definition at line 5 of file TestTracerAdapterPrintf.cpp.
Referenced by Print(), and TracerAdapterPrintfTest::TracerAdapterPrintfTest().