EMil: hal::TriStatePin Class Reference
hal::TriStatePin Class Reference
#include <Gpio.hpp>
Public Member Functions
TriStatePin (GpioPin &pin)
TriStatePin (GpioPin &pin, bool startOutputState)
TriStatePin (const TriStatePin &other)=delete
TriStatePin & operator= (const TriStatePin &other)=delete
~TriStatePin ()
bool Get () const
bool GetOutputLatch () const
void Set (bool value)
void SetAsInput ()
bool IsInput () const
void EnableInterrupt (const infra::Function< void()> &action, InterruptTrigger trigger)
void DisableInterrupt ()
Private Attributes
GpioPin & pin
Detailed Description
Definition at line 83 of file Gpio.hpp.
Constructor & Destructor Documentation
TriStatePin() [1/3]
hal::TriStatePin::TriStatePin (GpioPin & pin) explicit
Definition at line 54 of file Gpio.cpp.
References hal::GpioPin::Config(), pin, and hal::triState.
         : pin(pin)
     {
         pin.Config(PinConfigType::triState);
     }
TriStatePin() [2/3]
hal::TriStatePin::TriStatePin (GpioPin & pin, bool startOutputState)
Definition at line 60 of file Gpio.cpp.
References hal::GpioPin::Config(), pin, and hal::triState.
         : pin(pin)
     {
         pin.Config(PinConfigType::triState, startOutputState);
     }
TriStatePin() [3/3]
hal::TriStatePin::TriStatePin (const TriStatePin & other) delete
~TriStatePin()
hal::TriStatePin::~TriStatePin ()
Definition at line 66 of file Gpio.cpp.
References pin, and hal::GpioPin::ResetConfig().
     {
         pin.ResetConfig();
     }
Member Function Documentation
DisableInterrupt()
void hal::TriStatePin::DisableInterrupt ()
Definition at line 101 of file Gpio.cpp.
References hal::GpioPin::DisableInterrupt(), and pin.
     {
         pin.DisableInterrupt();
     }
EnableInterrupt()
void hal::TriStatePin::EnableInterrupt (const infra::Function< void()> & action, InterruptTrigger trigger)
Definition at line 96 of file Gpio.cpp.
References hal::GpioPin::EnableInterrupt(), and pin.
     {
         pin.EnableInterrupt(action, trigger);
     }
Get()
bool hal::TriStatePin::Get () const
Definition at line 71 of file Gpio.cpp.
References hal::GpioPin::Get(), and pin.
     {
         return pin.Get();
     }
GetOutputLatch()
bool hal::TriStatePin::GetOutputLatch () const
Definition at line 81 of file Gpio.cpp.
References hal::GpioPin::GetOutputLatch(), and pin.
     {
         return pin.GetOutputLatch();
     }
IsInput()
bool hal::TriStatePin::IsInput () const
Definition at line 91 of file Gpio.cpp.
References hal::GpioPin::IsInput(), and pin.
     {
         return pin.IsInput();
     }
operator=()
TriStatePin& hal::TriStatePin::operator= (const TriStatePin & other) delete
Set()
void hal::TriStatePin::Set (bool value)
Definition at line 76 of file Gpio.cpp.
References pin, hal::GpioPin::Set(), and value.
     {
         pin.Set(value);
     }
SetAsInput()
void hal::TriStatePin::SetAsInput ()
Definition at line 86 of file Gpio.cpp.
References pin, and hal::GpioPin::SetAsInput().
     {
         pin.SetAsInput();
     }
Member Data Documentation
pin
GpioPin& hal::TriStatePin::pin private
Definition at line 102 of file Gpio.hpp.
Referenced by DisableInterrupt(), EnableInterrupt(), Get(), GetOutputLatch(), IsInput(), Set(), SetAsInput(), TriStatePin(), and ~TriStatePin().
The documentation for this class was generated from the following files:
Gpio.hpp
Gpio.cpp