EMil: TestBoundedString.cpp File Reference
TestBoundedString.cpp File Reference
Functions
TEST (BoundedStringTest, TestConstructedEmpty)
TEST (BoundedStringTest, TestConstructFromMemoryRange)
TEST (BoundedStringTest, TestConstructFromNChars)
TEST (BoundedStringTest, TestConstructFromOtherString)
TEST (BoundedStringTest, TestConstructFromStdString)
TEST (BoundedStringTest, TestConstructFromStdStringAsStorage)
TEST (BoundedStringTest, TestConstructFromConstStdStringAsStorage)
TEST (BoundedStringTest, TestConstructFromCharP)
TEST (BoundedStringTest, TestConstructFromZeroTerminatedString)
TEST (BoundedStringTest, TestConstructFromRange)
TEST (BoundedStringTest, TestConstructFromInitializerList)
TEST (BoundedStringTest, TestCopyAssignFromString)
TEST (BoundedStringTest, TestCopyAssignFromStdString)
TEST (BoundedStringTest, TestCopyAssignFromZeroTerminated)
TEST (BoundedStringTest, TestCopyAssignFromChar)
TEST (BoundedStringTest, TestAssignFromString)
TEST (BoundedStringTest, TestAssignFromStdString)
TEST (BoundedStringTest, TestAssignFromZeroTerminated)
TEST (BoundedStringTest, TestAssignFromChar)
TEST (BoundedStringTest, TestFront)
TEST (BoundedStringTest, TestBack)
TEST (BoundedStringTest, TestData)
TEST (BoundedStringTest, TestBegin)
TEST (BoundedStringTest, TestEnd)
TEST (BoundedStringTest, TestRBegin)
TEST (BoundedStringTest, TestREnd)
TEST (BoundedStringTest, TestClear)
TEST (BoundedStringTest, TestAppendWithChars)
TEST (BoundedStringTest, TestAppendWithString)
TEST (BoundedStringTest, TestAppendWithSubString)
TEST (BoundedStringTest, TestAppendWithCharP)
TEST (BoundedStringTest, TestAppendWithZeroTerminated)
TEST (BoundedStringTest, TestAppendWithRange)
TEST (BoundedStringTest, TestInsertChars)
TEST (BoundedStringTest, TestInsertZeroTerminated)
TEST (BoundedStringTest, TestInsertCharP)
TEST (BoundedStringTest, TestInsertString)
TEST (BoundedStringTest, TestInsertCharAtIterator)
TEST (BoundedStringTest, TestInsertCharAtIteratorWithEndAsReturn)
TEST (BoundedStringTest, TestInsertCharsAtIterator)
TEST (BoundedStringTest, TestInsertCharsAtIteratorWithEndAsReturn)
TEST (BoundedStringTest, TestInsertRangeAtIterator)
TEST (BoundedStringTest, TestEraseCount)
TEST (BoundedStringTest, TestEraseChar)
TEST (BoundedStringTest, TestEraseRange)
TEST (BoundedStringTest, TestPushBack)
TEST (BoundedStringTest, TestPopBack)
TEST (BoundedStringTest, TestCompareEqual)
TEST (BoundedStringTest, TestCompareLess)
TEST (BoundedStringTest, TestCompareLessBySize)
TEST (BoundedStringTest, TestCompareGreater)
TEST (BoundedStringTest, TestCompareGreaterBySize)
TEST (BoundedStringTest, TestCompareOperators)
TEST (BoundedStringTest, TestConcatenateWithStdString)
TEST (BoundedStringTest, TestReplaceByString)
TEST (BoundedStringTest, TestReplaceByChars)
TEST (BoundedStringTest, TestSubstr)
TEST (BoundedStringTest, TestCopy)
TEST (BoundedStringTest, TestResize)
TEST (BoundedStringTest, TestShrink)
TEST (BoundedStringTest, TestSwap)
TEST (BoundedStringTest, TestTrimLeft)
TEST (BoundedStringTest, TestFind)
TEST (BoundedStringTest, TestFindNotFound)
TEST (BoundedStringTest, TestFindEmptyReturnsPos)
TEST (BoundedStringTest, TestRFind)
TEST (BoundedStringTest, TestRFindNotFound)
TEST (BoundedStringTest, TestRFindEmptyReturnsPos)
TEST (BoundedStringTest, TestFindFirstOf)
TEST (BoundedStringTest, TestFindFirstNotOf)
TEST (BoundedStringTest, TestFindLastOf)
TEST (BoundedStringTest, TestFindLastNotOf)
TEST (BoundedStringTest, TestStringAsByteRange)
TEST (BoundedStringTest, TestByteRangeAsString)
TEST (BoundedStringTest, TestPrintTo1)
TEST (BoundedStringTest, TestPrintTo2)
Function Documentation
TEST() [1/76]
TEST (BoundedStringTest , TestConstructedEmpty)
Definition at line 5 of file TestBoundedString.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::BoundedString::WithStorage<5> string;
     EXPECT_TRUE(string.empty());
     EXPECT_FALSE(string.full());
     EXPECT_EQ(0, string.size());
     EXPECT_EQ(5, string.max_size());
 }
TEST() [2/76]
TEST (BoundedStringTest , TestConstructFromMemoryRange)
Definition at line 15 of file TestBoundedString.cpp.
References data, EXPECT_EQ(), EXPECT_FALSE(), and infra::MakeRange().
 {
     std::array<char, 5> data = { 'a', 'b', 'c', 'd', 'e' };
     infra::BoundedString string(infra::MakeRange(data), 3);
     EXPECT_EQ('a', string[0]);
     EXPECT_EQ('b', string[1]);
     EXPECT_EQ('c', string[2]);
     EXPECT_EQ(3, string.size());
     EXPECT_EQ(5, string.max_size());
     EXPECT_FALSE(string.empty());
 }
TEST() [3/76]
TEST (BoundedStringTest , TestConstructFromNChars)
Definition at line 28 of file TestBoundedString.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     infra::BoundedString::WithStorage<5> string(3, 'a');
     EXPECT_EQ('a', string[0]);
     EXPECT_EQ('a', string[1]);
     EXPECT_EQ('a', static_cast<const infra::BoundedString&>(string)[2]);
     EXPECT_EQ(3, string.size());
     EXPECT_FALSE(string.empty());
 }
TEST() [4/76]
TEST (BoundedStringTest , TestConstructFromOtherString)
Definition at line 39 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string(3, 'a');
     infra::BoundedString::WithStorage<4> copy1(string);
     EXPECT_EQ('a', copy1[0]);
     EXPECT_EQ(3, copy1.size());
     infra::BoundedString::WithStorage<4> copy2(string, 0, 2);
     EXPECT_EQ('a', copy2[0]);
     EXPECT_EQ(2, copy2.size());
 }
TEST() [5/76]
TEST (BoundedStringTest , TestConstructFromStdString)
Definition at line 52 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     std::string string(3, 'a');
     infra::BoundedString::WithStorage<4> copy(string);
     EXPECT_EQ('a', copy[0]);
     EXPECT_EQ(3, copy.size());
 }
TEST() [6/76]
TEST (BoundedStringTest , TestConstructFromStdStringAsStorage)
Definition at line 61 of file TestBoundedString.cpp.
References EXPECT_EQ(), and infra::BoundedStringBase< T >::size().
 {
     std::string string(3, 'a');
     infra::BoundedString copy(string);
     EXPECT_EQ('a', copy[0]);
     EXPECT_EQ(3, copy.size());
 }
TEST() [7/76]
TEST (BoundedStringTest , TestConstructFromConstStdStringAsStorage)
Definition at line 70 of file TestBoundedString.cpp.
References EXPECT_EQ(), and infra::BoundedStringBase< T >::size().
 {
     const std::string string(3, 'a');
     infra::BoundedConstString copy(string);
     EXPECT_EQ('a', copy[0]);
     EXPECT_EQ(3, copy.size());
 }
TEST() [8/76]
TEST (BoundedStringTest , TestConstructFromCharP)
Definition at line 79 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char a[] = { 'a', '\0', 'a' };
     infra::BoundedString::WithStorage<3> string(a, 3);
     EXPECT_EQ('a', string[0]);
     EXPECT_EQ('\0', string[1]);
     EXPECT_EQ('a', string[2]);
     EXPECT_EQ(3, string.size());
 }
TEST() [9/76]
TEST (BoundedStringTest , TestConstructFromZeroTerminatedString)
Definition at line 90 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char a[] = { 'a', '\0', 'a' };
     infra::BoundedString::WithStorage<3> string(a);
     EXPECT_EQ('a', string[0]);
     EXPECT_EQ(1, string.size());
 }
TEST() [10/76]
TEST (BoundedStringTest , TestConstructFromRange)
Definition at line 99 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char a[] = { 'a', '\0', 'a' };
     infra::BoundedString::WithStorage<3> string(a, a + 3);
     EXPECT_EQ('a', string[0]);
     EXPECT_EQ('\0', string[1]);
     EXPECT_EQ('a', string[2]);
     EXPECT_EQ(3, string.size());
 }
TEST() [11/76]
TEST (BoundedStringTest , TestConstructFromInitializerList)
Definition at line 110 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<3> string({ 'a', '\0', 'a' });
     EXPECT_EQ('a', string[0]);
     EXPECT_EQ('\0', string[1]);
     EXPECT_EQ('a', string[2]);
     EXPECT_EQ(3, string.size());
 }
TEST() [12/76]
TEST (BoundedStringTest , TestCopyAssignFromString)
Definition at line 120 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string(3, 'a');
     infra::BoundedString::WithStorage<5> copy;
     copy = string;
     EXPECT_EQ(string, copy);
 }
TEST() [13/76]
TEST (BoundedStringTest , TestCopyAssignFromStdString)
Definition at line 130 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     std::string string(3, 'a');
     infra::BoundedString::WithStorage<5> copy;
     copy = string;
     EXPECT_EQ(string, copy);
 }
TEST() [14/76]
TEST (BoundedStringTest , TestCopyAssignFromZeroTerminated)
Definition at line 140 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string;
     string = "abc";
     EXPECT_EQ("abc", string);
     EXPECT_EQ(3, string.size());
 }
TEST() [15/76]
TEST (BoundedStringTest , TestCopyAssignFromChar)
Definition at line 149 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string;
     string = 'a';
     EXPECT_EQ("a", string);
 }
TEST() [16/76]
TEST (BoundedStringTest , TestAssignFromString)
Definition at line 157 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string(3, 'a');
     infra::BoundedString::WithStorage<5> copy;
     copy.assign(string);
     EXPECT_EQ(string, copy);
 }
TEST() [17/76]
TEST (BoundedStringTest , TestAssignFromStdString)
Definition at line 167 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     std::string string(3, 'a');
     infra::BoundedString::WithStorage<5> copy;
     copy.assign(string);
     EXPECT_EQ(string, copy);
 }
TEST() [18/76]
TEST (BoundedStringTest , TestAssignFromZeroTerminated)
Definition at line 177 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string;
     string.assign("abc");
     EXPECT_EQ("abc", string);
     EXPECT_EQ(3, string.size());
 }
TEST() [19/76]
TEST (BoundedStringTest , TestAssignFromChar)
Definition at line 186 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string;
     string.assign(1, 'a');
     EXPECT_EQ("a", string);
 }
TEST() [20/76]
TEST (BoundedStringTest , TestFront)
Definition at line 194 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('a', string.front());
     EXPECT_EQ('a', static_cast<const infra::BoundedString&>(string).front());
 }
TEST() [21/76]
TEST (BoundedStringTest , TestBack)
Definition at line 201 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('c', string.back());
     EXPECT_EQ('c', static_cast<const infra::BoundedString&>(string).back());
 }
TEST() [22/76]
TEST (BoundedStringTest , TestData)
Definition at line 208 of file TestBoundedString.cpp.
References data, and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('a', *string.data());
 }
TEST() [23/76]
TEST (BoundedStringTest , TestBegin)
Definition at line 214 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('a', *string.begin());
     EXPECT_EQ('a', *string.cbegin());
 }
TEST() [24/76]
TEST (BoundedStringTest , TestEnd)
Definition at line 221 of file TestBoundedString.cpp.
References infra::detail::end(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('c', *std::prev(string.end()));
     EXPECT_EQ('c', *std::prev(string.cend()));
 }
TEST() [25/76]
TEST (BoundedStringTest , TestRBegin)
Definition at line 228 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('c', *string.rbegin());
     EXPECT_EQ('c', *static_cast<const infra::BoundedString&>(string).rbegin());
     EXPECT_EQ('c', *string.crbegin());
 }
TEST() [26/76]
TEST (BoundedStringTest , TestREnd)
Definition at line 236 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     EXPECT_EQ('a', *std::prev(string.rend()));
     EXPECT_EQ('a', *std::prev(static_cast<const infra::BoundedString&>(string).rend()));
     EXPECT_EQ('a', *std::prev(string.crend()));
 }
TEST() [27/76]
TEST (BoundedStringTest , TestClear)
Definition at line 244 of file TestBoundedString.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     string.clear();
     EXPECT_EQ("", string);
     EXPECT_TRUE(string.empty());
 }
TEST() [28/76]
TEST (BoundedStringTest , TestAppendWithChars)
Definition at line 252 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string("abc");
     string.append(2, 'd');
     EXPECT_EQ("abcdd", string);
     EXPECT_EQ(5, string.size());
     string += 'e';
     EXPECT_EQ("abcdde", string);
 }
TEST() [29/76]
TEST (BoundedStringTest , TestAppendWithString)
Definition at line 262 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string("abc");
     string += infra::BoundedConstString("de");
     EXPECT_EQ("abcde", string);
     EXPECT_EQ(5, string.size());
     string += "fg";
     EXPECT_EQ("abcdefg", string);
     string += std::string("hi");
     EXPECT_EQ("abcdefghi", string);
 }
TEST() [30/76]
TEST (BoundedStringTest , TestAppendWithSubString)
Definition at line 274 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     string.append(infra::BoundedString::WithStorage<5>("defgh"), 1, 2);
     EXPECT_EQ("abcef", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [31/76]
TEST (BoundedStringTest , TestAppendWithCharP)
Definition at line 282 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<6> string("abc");
     string.append("d\0ef", 3);
     EXPECT_EQ(infra::BoundedString::WithStorage<6>("abcd\0e", 6), string);
     EXPECT_EQ(6, string.size());
 }
TEST() [32/76]
TEST (BoundedStringTest , TestAppendWithZeroTerminated)
Definition at line 290 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     string.append("d\0ef");
     EXPECT_EQ("abcd", string);
     EXPECT_EQ(4, string.size());
 }
TEST() [33/76]
TEST (BoundedStringTest , TestAppendWithRange)
Definition at line 298 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char a[] = "def";
     infra::BoundedString::WithStorage<5> string("abc");
     string.append(a, a + 3);
     EXPECT_EQ("abcde", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [34/76]
TEST (BoundedStringTest , TestInsertChars)
Definition at line 307 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     string.insert(1, 2, 'd');
     EXPECT_EQ("addbc", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [35/76]
TEST (BoundedStringTest , TestInsertZeroTerminated)
Definition at line 316 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     string.insert(1, "de");
     EXPECT_EQ("adebc", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [36/76]
TEST (BoundedStringTest , TestInsertCharP)
Definition at line 325 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<6> string("abc");
     string.insert(1, "d\0ef", 3);
     EXPECT_EQ(infra::BoundedString::WithStorage<6>("ad\0ebc", 6), string);
     EXPECT_EQ(6, string.size());
 }
TEST() [37/76]
TEST (BoundedStringTest , TestInsertString)
Definition at line 333 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<20> string("abc");
     infra::BoundedString::WithStorage<3> other("de");
     string.insert(1, other);
     EXPECT_EQ("adebc", string);
     EXPECT_EQ(5, string.size());
     string.insert(1, other, 0, 1);
     EXPECT_EQ("addebc", string);
     string.insert(1, std::string("x"));
     EXPECT_EQ("axddebc", string);
     string.insert(1, std::string("x"), 0, 1);
     EXPECT_EQ("axxddebc", string);
 }
TEST() [38/76]
TEST (BoundedStringTest , TestInsertCharAtIterator)
Definition at line 348 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.insert(string.begin() + 1, 'd');
     EXPECT_EQ(string.begin() + 2, i);
     EXPECT_EQ("adbc", string);
     EXPECT_EQ(4, string.size());
 }
TEST() [39/76]
TEST (BoundedStringTest , TestInsertCharAtIteratorWithEndAsReturn)
Definition at line 357 of file TestBoundedString.cpp.
References infra::detail::begin(), infra::detail::end(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.insert(string.begin() + 4, 'e');
     EXPECT_EQ(string.end(), i);
     EXPECT_EQ("abcde", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [40/76]
TEST (BoundedStringTest , TestInsertCharsAtIterator)
Definition at line 366 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.insert(string.begin() + 1, 2, 'd');
     EXPECT_EQ(string.begin() + 3, i);
     EXPECT_EQ("addbc", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [41/76]
TEST (BoundedStringTest , TestInsertCharsAtIteratorWithEndAsReturn)
Definition at line 375 of file TestBoundedString.cpp.
References infra::detail::begin(), infra::detail::end(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.insert(string.begin() + 3, 2, 'd');
     EXPECT_EQ(string.end(), i);
     EXPECT_EQ("abcdd", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [42/76]
TEST (BoundedStringTest , TestInsertRangeAtIterator)
Definition at line 384 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     char a[] = "de";
     infra::BoundedString::WithStorage<5> string("abc");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.insert(string.begin() + 1, a, a + sizeof(a));
     EXPECT_EQ(string.begin() + 3, i);
     EXPECT_EQ("adebc", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [43/76]
TEST (BoundedStringTest , TestEraseCount)
Definition at line 394 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     string.erase(1, 2);
     EXPECT_EQ("ad", string);
     EXPECT_EQ(2, string.size());
 }
TEST() [44/76]
TEST (BoundedStringTest , TestEraseChar)
Definition at line 402 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.erase(string.begin() + 1);
     EXPECT_EQ('c', *i);
     EXPECT_EQ("acd", string);
     EXPECT_EQ(3, string.size());
 }
TEST() [45/76]
TEST (BoundedStringTest , TestEraseRange)
Definition at line 411 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     infra::BoundedString::WithStorage<5>::const_iterator i = string.erase(string.begin() + 1, string.begin() + 3);
     EXPECT_EQ('d', *i);
     EXPECT_EQ("ad", string);
     EXPECT_EQ(2, string.size());
 }
TEST() [46/76]
TEST (BoundedStringTest , TestPushBack)
Definition at line 420 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     string.push_back('e');
     EXPECT_EQ("abcde", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [47/76]
TEST (BoundedStringTest , TestPopBack)
Definition at line 428 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     string.pop_back();
     EXPECT_EQ("abc", string);
     EXPECT_EQ(3, string.size());
 }
TEST() [48/76]
TEST (BoundedStringTest , TestCompareEqual)
Definition at line 436 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string1("abcd");
     infra::BoundedString::WithStorage<10> string2("abcd");
     EXPECT_EQ(0, string1.compare(string2));
     EXPECT_EQ(0, string1.compare(0, 4, string2));
     EXPECT_EQ(0, string1.compare(0, 4, string2, 0, 4));
     EXPECT_EQ(0, string1.compare("abcd"));
     EXPECT_EQ(0, string1.compare(0, 4, "abcd"));
     EXPECT_EQ(0, string1.compare(0, 4, "abcd", 4));
     EXPECT_EQ(0, string1.compare(std::string("abcd")));
     EXPECT_EQ(0, string1.compare(0, 4, std::string("abcd")));
     EXPECT_EQ(0, string1.compare(0, 4, std::string("abcd"), 4));
 }
TEST() [49/76]
TEST (BoundedStringTest , TestCompareLess)
Definition at line 451 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string1("abbb");
     infra::BoundedString::WithStorage<10> string2("abcd");
     EXPECT_EQ(-1, string1.compare(string2));
 }
TEST() [50/76]
TEST (BoundedStringTest , TestCompareLessBySize)
Definition at line 458 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string1("abc");
     infra::BoundedString::WithStorage<10> string2("abcd");
     EXPECT_EQ(-1, string1.compare(string2));
 }
TEST() [51/76]
TEST (BoundedStringTest , TestCompareGreater)
Definition at line 465 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string1("abde");
     infra::BoundedString::WithStorage<10> string2("abcd");
     EXPECT_EQ(1, string1.compare(string2));
 }
TEST() [52/76]
TEST (BoundedStringTest , TestCompareGreaterBySize)
Definition at line 472 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string1("abcde");
     infra::BoundedString::WithStorage<10> string2("abcd");
     EXPECT_EQ(1, string1.compare(string2));
 }
TEST() [53/76]
TEST (BoundedStringTest , TestCompareOperators)
Definition at line 479 of file TestBoundedString.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::BoundedConstString string("abc");
     char stringC[] = "abc";
     std::string stringStd = "abc";
     EXPECT_TRUE(string == string);
     EXPECT_TRUE(string == stringC);
     EXPECT_TRUE(stringC == string);
     EXPECT_TRUE(string == stringStd);
     EXPECT_TRUE(stringStd == string);
     EXPECT_FALSE(string != string);
     EXPECT_FALSE(string != stringC);
     EXPECT_FALSE(stringC != string);
     EXPECT_FALSE(string != stringStd);
     EXPECT_FALSE(stringStd != string);
     EXPECT_FALSE(string < string);
     EXPECT_FALSE(string < stringC);
     EXPECT_FALSE(stringC < string);
     EXPECT_FALSE(string < stringStd);
     EXPECT_FALSE(stringStd < string);
     EXPECT_TRUE(string <= string);
     EXPECT_TRUE(string <= stringC);
     EXPECT_TRUE(stringC <= string);
     EXPECT_TRUE(string <= stringStd);
     EXPECT_TRUE(stringStd <= string);
     EXPECT_FALSE(string > string);
     EXPECT_FALSE(string > stringC);
     EXPECT_FALSE(stringC > string);
     EXPECT_FALSE(string > stringStd);
     EXPECT_FALSE(stringStd > string);
     EXPECT_TRUE(string >= string);
     EXPECT_TRUE(string >= stringC);
     EXPECT_TRUE(stringC >= string);
     EXPECT_TRUE(string >= stringStd);
     EXPECT_TRUE(stringStd >= string);
 }
TEST() [54/76]
TEST (BoundedStringTest , TestConcatenateWithStdString)
Definition at line 522 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ("ab", std::string("a") + infra::BoundedConstString("b"));
 }
TEST() [55/76]
TEST (BoundedStringTest , TestReplaceByString)
Definition at line 527 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string1("abcde");
     infra::BoundedString::WithStorage<10> string2("kl");
     string1.replace(1, 3, string2);
     EXPECT_EQ("akle", string1);
     string1.replace(string1.begin() + 1, string1.begin() + 2, std::string("xx"));
     EXPECT_EQ("axxle", string1);
     string1.replace(1, 1, "z");
     EXPECT_EQ("azxle", string1);
     string1.replace(1, 1, "mmmm", 1);
     EXPECT_EQ("amxle", string1);
     string1.replace(string1.begin() + 1, string1.begin() + 2, "u");
     EXPECT_EQ("auxle", string1);
     string1.replace(string1.begin() + 1, string1.begin() + 2, "vvv", 1);
     EXPECT_EQ("avxle", string1);
     string1.replace(1, 1, std::string("y"));
     EXPECT_EQ("ayxle", string1);
     string1.replace(string1.begin() + 1, string1.begin() + 2, std::string("aaa"), 1);
     EXPECT_EQ("aaxle", string1);
     string1.replace(1, 1, std::string("bbb"), 1);
     EXPECT_EQ("abxle", string1);
     string1.replace(string1.begin() + 1, string1.begin() + 2, infra::BoundedConstString("c"));
     EXPECT_EQ("acxle", string1);
     string1.replace(1, 1, infra::BoundedConstString("d"), 0, 1);
     EXPECT_EQ("adxle", string1);
 }
TEST() [56/76]
TEST (BoundedStringTest , TestReplaceByChars)
Definition at line 555 of file TestBoundedString.cpp.
References infra::detail::begin(), and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcd");
     string.replace(1, 2, 3, 'k');
     EXPECT_EQ("akkkd", string);
     string.replace(string.begin() + 1, string.begin() + 2, 1, 'x');
     EXPECT_EQ("axkkd", string);
 }
TEST() [57/76]
TEST (BoundedStringTest , TestSubstr)
Definition at line 564 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ("bcd", string.substr(1, 3));
 }
TEST() [58/76]
TEST (BoundedStringTest , TestCopy)
Definition at line 570 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char buffer[3];
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ(3, string.copy(buffer, 3, 1));
     EXPECT_EQ('b', buffer[0]);
 }
TEST() [59/76]
TEST (BoundedStringTest , TestResize)
Definition at line 578 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<5> string("abc");
     string.resize(5, 'k');
     EXPECT_EQ("abckk", string);
     EXPECT_EQ(5, string.size());
 }
TEST() [60/76]
TEST (BoundedStringTest , TestShrink)
Definition at line 586 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedConstString::WithStorage<5> string("abc");
     string.shrink(2);
     EXPECT_EQ("ab", string);
     EXPECT_EQ(2, string.size());
 }
TEST() [61/76]
TEST (BoundedStringTest , TestSwap)
Definition at line 594 of file TestBoundedString.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     infra::BoundedString::WithStorage<4> string1("abc");
     infra::BoundedString::WithStorage<5> string2("defg");
     swap(string1, string2);
     EXPECT_EQ("defg", string1);
     EXPECT_EQ("abc", string2);
 }
TEST() [62/76]
TEST (BoundedStringTest , TestTrimLeft)
Definition at line 603 of file TestBoundedString.cpp.
References EXPECT_EQ(), and infra::TrimLeft().
 {
     EXPECT_EQ("abc ", infra::TrimLeft(infra::BoundedConstString("abc ")));
     EXPECT_EQ("abc ", infra::TrimLeft(infra::BoundedConstString("  abc ")));
     EXPECT_EQ("", infra::TrimLeft(infra::BoundedConstString("")));
     EXPECT_EQ("", infra::TrimLeft(infra::BoundedConstString(" ")));
 }
TEST() [63/76]
TEST (BoundedStringTest , TestFind)
Definition at line 611 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> searchString = "def";
     infra::BoundedString::WithStorage<10> string("abcdefgh");
     EXPECT_EQ(3, string.find("def"));
     EXPECT_EQ(3, string.find(searchString));
 }
TEST() [64/76]
TEST (BoundedStringTest , TestFindNotFound)
Definition at line 619 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string("abcdefgh");
     EXPECT_EQ(infra::BoundedString::WithStorage<10>::npos, string.find("fed"));
 }
TEST() [65/76]
TEST (BoundedStringTest , TestFindEmptyReturnsPos)
Definition at line 625 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string("abcdefgh");
     EXPECT_EQ(4, string.find("", 4));
 }
TEST() [66/76]
TEST (BoundedStringTest , TestRFind)
Definition at line 631 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> searchString("def");
     infra::BoundedString::WithStorage<10> string("abcdefgh");
     EXPECT_EQ(3, string.rfind("def"));
     EXPECT_EQ(3, string.rfind(searchString));
     EXPECT_EQ(3, string.rfind('d'));
 }
TEST() [67/76]
TEST (BoundedStringTest , TestRFindNotFound)
Definition at line 640 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string("abcdefgh");
     EXPECT_EQ(infra::BoundedString::WithStorage<10>::npos, string.rfind("fed"));
 }
TEST() [68/76]
TEST (BoundedStringTest , TestRFindEmptyReturnsPos)
Definition at line 646 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> string("abcdefgh");
     EXPECT_EQ(4, string.rfind("", 4));
 }
TEST() [69/76]
TEST (BoundedStringTest , TestFindFirstOf)
Definition at line 652 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char search[] = "dcb";
     infra::BoundedString::WithStorage<5> searchString = "dcb";
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ(1, string.find_first_of(search));
     EXPECT_EQ(1, string.find_first_of(searchString));
     EXPECT_EQ(1, string.find_first_of('b'));
 }
TEST() [70/76]
TEST (BoundedStringTest , TestFindFirstNotOf)
Definition at line 662 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char search[] = "dca";
     infra::BoundedString::WithStorage<5> searchString = "dca";
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ(1, string.find_first_not_of(search));
     EXPECT_EQ(1, string.find_first_not_of(searchString));
     EXPECT_EQ(1, string.find_first_not_of('a'));
 }
TEST() [71/76]
TEST (BoundedStringTest , TestFindLastOf)
Definition at line 672 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char search[] = "cdb";
     infra::BoundedString::WithStorage<5> searchString = "cdb";
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ(3, string.find_last_of(search));
     EXPECT_EQ(3, string.find_last_of(searchString));
 }
TEST() [72/76]
TEST (BoundedStringTest , TestFindLastNotOf)
Definition at line 681 of file TestBoundedString.cpp.
References EXPECT_EQ().
 {
     char search[] = "dce";
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ(1, string.find_last_not_of(search));
     EXPECT_EQ(3, string.find_last_not_of('e'));
 }
TEST() [73/76]
TEST (BoundedStringTest , TestStringAsByteRange)
Definition at line 689 of file TestBoundedString.cpp.
References infra::detail::begin(), infra::detail::end(), EXPECT_EQ(), and infra::StringAsByteRange().
 {
     infra::BoundedString::WithStorage<5> string("abcde");
     EXPECT_EQ(infra::MemoryRange<uint8_t>(reinterpret_cast<uint8_t*>(string.begin()), reinterpret_cast<uint8_t*>(string.end())),
         StringAsByteRange(string));
     EXPECT_EQ(infra::MemoryRange<const uint8_t>(reinterpret_cast<const uint8_t*>(string.begin()), reinterpret_cast<const uint8_t*>(string.end())),
         StringAsByteRange(const_cast<const infra::BoundedString&>(static_cast<const infra::BoundedString&>(string))));
 }
TEST() [74/76]
TEST (BoundedStringTest , TestByteRangeAsString)
Definition at line 699 of file TestBoundedString.cpp.
References infra::ByteRangeAsString(), data, and EXPECT_EQ().
 {
     std::array<uint8_t, 4> data = { "str" };
     infra::MemoryRange<uint8_t> byteRange(data);
     infra::MemoryRange<const uint8_t> byteRange2(data);
     const auto boudedString = ByteRangeAsString(byteRange);
     const auto boundedConstString = ByteRangeAsString(infra::ConstByteRange(byteRange));
     EXPECT_EQ(boudedString[0], 's');
     EXPECT_EQ(boudedString[1], 't');
     EXPECT_EQ(boudedString[2], 'r');
     EXPECT_EQ(boudedString[3], '\0');
     EXPECT_EQ(boundedConstString[0], 's');
     EXPECT_EQ(boundedConstString[1], 't');
     EXPECT_EQ(boundedConstString[2], 'r');
     EXPECT_EQ(boundedConstString[3], '\0');
 }
TEST() [75/76]
TEST (BoundedStringTest , TestPrintTo1)
Definition at line 719 of file TestBoundedString.cpp.
References EXPECT_EQ(), and infra::PrintTo().
 {
     std::ostringstream stream;
     infra::BoundedString::WithStorage<5> string = "abc";
     infra::PrintTo(static_cast<infra::BoundedString&>(string), &stream);
     EXPECT_EQ(R"("abc")", stream.str());
 }
TEST() [76/76]
TEST (BoundedStringTest , TestPrintTo2)
Definition at line 727 of file TestBoundedString.cpp.
References EXPECT_EQ(), and infra::PrintTo().
 {
     std::ostringstream stream;
     infra::BoundedString::WithStorage<5> string = "abc";
     infra::PrintTo(string, &stream);
     EXPECT_EQ(R"("abc")", stream.str());
 }