EMil: infra::TimerEvolving Class Reference
infra::TimerEvolving Class Reference
#include <TimerEvolving.hpp>
Public Member Functions
TimerEvolving (uint32_t timerServiceId=systemTimerServiceId)
TimerEvolving (const infra::Function< infra::Optional< infra::Duration >(uint32_t index)> &evolve, const infra::Function< void()> &action, uint32_t timerServiceId=systemTimerServiceId)
void Start (const infra::Function< infra::Optional< infra::Duration >(uint32_t index)> &evolve, const infra::Function< void()> &action)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
virtual const infra::Function< void()> & Action () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Member Functions
void Evolve (const infra::Function< void()> &action)
Private Attributes
infra::Function< infra::Optional< infra::Duration >uint32_t index)> evolve
std::size_t index = 0
infra::TimePoint triggerStart
Detailed Description
Definition at line 9 of file TimerEvolving.hpp.
Constructor & Destructor Documentation
TimerEvolving() [1/2]
infra::TimerEvolving::TimerEvolving (uint32_t timerServiceId = systemTimerServiceId) explicit
Definition at line 5 of file TimerEvolving.cpp.
         : Timer(timerServiceId)
         , index(0)
     {}
TimerEvolving() [2/2]
infra::TimerEvolving::TimerEvolving (const infra::Function< infra::Optional< infra::Duration >(uint32_t index)> & evolve, const infra::Function< void()> & action, uint32_t timerServiceId = systemTimerServiceId)
Definition at line 10 of file TimerEvolving.cpp.
References infra::Timer::action, evolve, and Start().
         : Timer(timerServiceId)
     {
         Start(evolve, action);
     }
Member Function Documentation
ComputeNextTriggerTime()
void infra::TimerEvolving::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 26 of file TimerEvolving.cpp.
References infra::Timer::Action(), and Evolve().
     {
         Evolve(Action());
     }
Evolve()
void infra::TimerEvolving::Evolve (const infra::Function< void()> & action) private
Definition at line 31 of file TimerEvolving.cpp.
References infra::Timer::action, infra::Timer::Cancel(), evolve, index, infra::Timer::SetNextTriggerTime(), and triggerStart.
Referenced by ComputeNextTriggerTime(), and Start().
     {
         auto nextDuration = evolve(index);
         ++index;
         if (nextDuration)
         {
             triggerStart += *nextDuration;
             SetNextTriggerTime(triggerStart, action);
         }
         else
             Cancel();
     }
Start()
void infra::TimerEvolving::Start (const infra::Function< infra::Optional< infra::Duration >(uint32_t index)> & evolve, const infra::Function< void()> & action)
Definition at line 16 of file TimerEvolving.cpp.
References infra::Timer::action, Evolve(), evolve, index, infra::Timer::Now(), infra::Timer::Resolution(), and triggerStart.
Referenced by TimerEvolving().
     {
         index = 0;
         this->evolve = evolve;
         triggerStart = Now() + Resolution();
         Evolve(action);
     }
Member Data Documentation
evolve
infra::Function<infra::Optional<infra::Duration>uint32_t index)> infra::TimerEvolving::evolve private
Definition at line 25 of file TimerEvolving.hpp.
Referenced by Evolve(), Start(), and TimerEvolving().
index
std::size_t infra::TimerEvolving::index = 0 private
Definition at line 26 of file TimerEvolving.hpp.
Referenced by Evolve(), and Start().
triggerStart
infra::TimePoint infra::TimerEvolving::triggerStart private
Definition at line 27 of file TimerEvolving.hpp.
Referenced by Evolve(), and Start().
The documentation for this class was generated from the following files:
TimerEvolving.hpp
TimerEvolving.cpp