EMil: TestObserver.cpp File Reference
TestObserver.cpp File Reference
Classes
class MyObserver
class MySubject
class MySingleObserver
class MySingleSubject
class MyAggregator
Functions
TEST (ObserverTest, default_constructed_observer_is_not_attached)
TEST (ObserverTest, construct_observer_with_subject)
TEST (ObserverTest, notify_one_observer)
TEST (ObserverTest, notify_two_observers)
TEST (ObserverTest, notify_two_observers_with_shortcut_call)
TEST (ObserverTest, notify_two_observers_without_shortcut_call)
TEST (ObserverTest, RegisterAfterConstruction)
TEST (ObserverTest, Detach)
TEST (SingleObserverTest, ConstructWithoutRegistration)
TEST (SingleObserverTest, ConstructWithRegistration)
TEST (SingleObserverTest, NotifyObserver)
TEST (SingleObserverTest, NotifyWithoutObserver)
TEST (SingleObserverTest, RegisterAfterConstruction)
TEST (SingleObserverTest, Detach)
Function Documentation
TEST() [1/14]
TEST (ObserverTest , default_constructed_observer_is_not_attached)
Definition at line 65 of file TestObserver.cpp.
References infra::Observer< Descendant, SubjectType_ >::Attached(), and EXPECT_FALSE().
 {
     MyObserver observer;
     EXPECT_FALSE(observer.Attached());
 }
TEST() [2/14]
TEST (ObserverTest , construct_observer_with_subject)
Definition at line 71 of file TestObserver.cpp.
References infra::Observer< Descendant, SubjectType_ >::Attached(), EXPECT_EQ(), EXPECT_TRUE(), and infra::Observer< Descendant, SubjectType_ >::Subject().
 {
     MySubject subject;
     MyObserver observer(subject);
     EXPECT_TRUE(observer.Attached());
     EXPECT_EQ(&subject, &observer.Subject());
 }
TEST() [3/14]
TEST (ObserverTest , notify_one_observer)
Definition at line 80 of file TestObserver.cpp.
References infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySubject subject;
     MyObserver observer(subject);
     EXPECT_CALL(observer, Callback());
     subject.NotifyObservers([](MyObserver& o) { o.Callback(); } );
 }
TEST() [4/14]
TEST (ObserverTest , notify_two_observers)
Definition at line 90 of file TestObserver.cpp.
References infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySubject subject;
     MyObserver observer1(subject);
     MyObserver observer2(subject);
     EXPECT_CALL(observer1, Callback());
     EXPECT_CALL(observer2, Callback());
     subject.NotifyObservers([](MyObserver& o) { o.Callback(); });
 }
TEST() [5/14]
TEST (ObserverTest , notify_two_observers_with_shortcut_call)
Definition at line 102 of file TestObserver.cpp.
References EXPECT_TRUE(), and infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySubject subject;
     MyObserver observer1(subject);
     MyObserver observer2(subject);
     EXPECT_CALL(observer1, Callback());
     EXPECT_TRUE(subject.NotifyObservers([](MyObserver& o) { o.Callback(); return true; }));
 }
TEST() [6/14]
TEST (ObserverTest , notify_two_observers_without_shortcut_call)
Definition at line 113 of file TestObserver.cpp.
References EXPECT_FALSE(), and infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySubject subject;
     MyObserver observer1(subject);
     MyObserver observer2(subject);
     EXPECT_CALL(observer1, Callback());
     EXPECT_CALL(observer2, Callback());
     EXPECT_FALSE(subject.NotifyObservers([](MyObserver& o) { o.Callback(); return false; }));
 }
TEST() [7/14]
TEST (ObserverTest , RegisterAfterConstruction)
Definition at line 125 of file TestObserver.cpp.
References infra::Observer< Descendant, SubjectType_ >::Attach(), infra::Observer< Descendant, SubjectType_ >::Attached(), EXPECT_TRUE(), and infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySubject subject;
     MyObserver observer;
     observer.Attach(subject);
     EXPECT_TRUE(observer.Attached());
     EXPECT_CALL(observer, Callback());
     subject.NotifyObservers([](const MyObserver& o) { const_cast<MyObserver&>(o).Callback(); });
 }
TEST() [8/14]
TEST (ObserverTest , Detach)
Definition at line 137 of file TestObserver.cpp.
References EXPECT_FALSE(), and infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySubject subject;
     testing::StrictMock<MyObserver> observer(subject);
     observer.Detach();
     EXPECT_FALSE(observer.Attached());
     subject.NotifyObservers([](MyObserver& o) { o.Callback(); });
 }
TEST() [9/14]
TEST (SingleObserverTest , ConstructWithoutRegistration)
Definition at line 148 of file TestObserver.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attached(), and EXPECT_FALSE().
 {
     MySingleObserver observer;
     EXPECT_FALSE(observer.Attached());
 }
TEST() [10/14]
TEST (SingleObserverTest , ConstructWithRegistration)
Definition at line 154 of file TestObserver.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attached(), EXPECT_TRUE(), and infra::Subject< ObserverType_, Helper >::HasObserver().
 {
     MySingleSubject subject;
     MySingleObserver observer(subject);
     EXPECT_TRUE(observer.Attached());
     EXPECT_TRUE(subject.HasObserver());
 }
TEST() [11/14]
TEST (SingleObserverTest , NotifyObserver)
Definition at line 163 of file TestObserver.cpp.
References infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySingleSubject subject;
     MySingleObserver observer(subject);
     EXPECT_CALL(observer, Callback());
     subject.NotifyObservers([](MySingleObserver &o) { o.Callback(); });
 }
TEST() [12/14]
TEST (SingleObserverTest , NotifyWithoutObserver)
Definition at line 172 of file TestObserver.cpp.
References infra::Subject< ObserverType_, Helper >::NotifyObservers().
 {
     MySingleSubject subject;
     subject.NotifyObservers([](MySingleObserver &o) { o.Callback(); });
 }
TEST() [13/14]
TEST (SingleObserverTest , RegisterAfterConstruction)
Definition at line 178 of file TestObserver.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), infra::SingleObserver< Descendant, SubjectType_ >::Attached(), EXPECT_TRUE(), infra::Subject< ObserverType_, Helper >::GetObserver(), and infra::Subject< ObserverType_, Helper >::HasObserver().
 {
     MySingleSubject subject;
     MySingleObserver observer;
     observer.Attach(subject);
     EXPECT_TRUE(observer.Attached());
     EXPECT_TRUE(subject.HasObserver());
     EXPECT_CALL(observer, Callback());
     subject.GetObserver().Callback();
 }
TEST() [14/14]
TEST (SingleObserverTest , Detach)
Definition at line 191 of file TestObserver.cpp.
References EXPECT_FALSE(), and infra::Subject< ObserverType_, Helper >::HasObserver().
 {
     MySingleSubject subject;
     testing::StrictMock<MySingleObserver> observer(subject);
     observer.Detach();
     EXPECT_FALSE(observer.Attached());
     EXPECT_FALSE(subject.HasObserver());
 }