EMil: services::ListenerWin Class Reference
services::ListenerWin Class Reference
#include <ConnectionWin.hpp>
Public Member Functions
ListenerWin (EventDispatcherWithNetwork &network, uint16_t port, services::ServerConnectionObserverFactory &factory)
~ListenerWin ()
void Accept ()
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Private Attributes
EventDispatcherWithNetwork & network
services::ServerConnectionObserverFactory & factory
SOCKET listenSocket
WSAEVENT event = WSACreateEvent()
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 87 of file ConnectionWin.hpp.
Constructor & Destructor Documentation
ListenerWin()
services::ListenerWin::ListenerWin (EventDispatcherWithNetwork & network, uint16_t port, services::ServerConnectionObserverFactory & factory)
Definition at line 197 of file ConnectionWin.cpp.
References event, listenSocket, network, and services::EventDispatcherWithNetwork::RegisterListener().
         : network(network)
         , factory(factory)
     {
         listenSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
         assert(listenSocket != INVALID_SOCKET);
         int result = WSAEventSelect(listenSocket, event, FD_ACCEPT);
         assert(result == 0);
         sockaddr_in address = {};
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = htonl(INADDR_ANY);
         address.sin_port = htons(port);
         if (bind(listenSocket, reinterpret_cast<SOCKADDR*>(&address), sizeof(SOCKADDR)) == SOCKET_ERROR)
             std::abort();
         if (listen(listenSocket, 1) == SOCKET_ERROR)
             std::abort();
         ULONG nonBlock = 1;
         if (ioctlsocket(listenSocket, FIONBIO, &nonBlock) == SOCKET_ERROR)
             std::abort();
         network.RegisterListener(*this);
     }
~ListenerWin()
services::ListenerWin::~ListenerWin ()
Definition at line 223 of file ConnectionWin.cpp.
References services::EventDispatcherWithNetwork::DeregisterListener(), event, and network.
     {
         BOOL result = WSACloseEvent(event);
         assert(result == TRUE);
         network.DeregisterListener(*this);
     }
Member Function Documentation
Accept()
void services::ListenerWin::Accept ()
Definition at line 230 of file ConnectionWin.cpp.
References services::ServerConnectionObserverFactory::ConnectionAccepted(), factory, listenSocket, and network.
     {
         SOCKET acceptedSocket = accept(listenSocket, NULL, NULL);
         assert(acceptedSocket != INVALID_SOCKET);
         infra::SharedPtr<ConnectionWin> connection = infra::MakeSharedOnHeap<ConnectionWin>(network, acceptedSocket);
         factory.ConnectionAccepted([connection](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             if (connectionObserver)
                 connection->SetObserver(connectionObserver);
         }, connection->Ipv4Address());
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 97 of file ConnectionWin.hpp.
Member Data Documentation
event
WSAEVENT services::ListenerWin::event = WSACreateEvent() private
Definition at line 102 of file ConnectionWin.hpp.
Referenced by ListenerWin(), and ~ListenerWin().
factory
services::ServerConnectionObserverFactory& services::ListenerWin::factory private
Definition at line 100 of file ConnectionWin.hpp.
Referenced by Accept().
listenSocket
SOCKET services::ListenerWin::listenSocket private
Definition at line 101 of file ConnectionWin.hpp.
Referenced by Accept(), and ListenerWin().
network
EventDispatcherWithNetwork& services::ListenerWin::network private
Definition at line 99 of file ConnectionWin.hpp.
Referenced by Accept(), ListenerWin(), and ~ListenerWin().
The documentation for this class was generated from the following files:
ConnectionWin.hpp
ConnectionWin.cpp