EMil: hal::GpioPinStub Class Reference
hal::GpioPinStub Class Reference
#include <GpioStub.hpp>
Public Member Functions
virtual ~GpioPinStub ()=default
virtual bool Get () const override
virtual void Set (bool value) override
virtual bool GetOutputLatch () const override
virtual void SetAsInput () override
virtual bool IsInput () const override
virtual void Config (PinConfigType config) override
virtual void Config (PinConfigType config, bool startOutputState) override
virtual void ResetConfig () override
virtual void EnableInterrupt (const infra::Function< void()> &action, InterruptTrigger trigger) override
virtual void DisableInterrupt () override
void SetStubState (bool value)
bool GetStubState () const
Public Member Functions inherited from hal::GpioPin
GpioPin ()=default
GpioPin (const GpioPin &other)=delete
GpioPin & operator= (const GpioPin &other)=delete
Private Attributes
bool state = false
bool input = true
infra::Optional< std::pair< infra::Function< void()>, InterruptTrigger > > triggerOnChange
Additional Inherited Members
Protected Member Functions inherited from hal::GpioPin
~GpioPin ()=default
Detailed Description
Definition at line 14 of file GpioStub.hpp.
Constructor & Destructor Documentation
~GpioPinStub()
virtual hal::GpioPinStub::~GpioPinStub () virtual default
Member Function Documentation
Config() [1/2]
void hal::GpioPinStub::Config (PinConfigType config) override virtual
Implements hal::GpioPin.
Definition at line 40 of file GpioStub.cpp.
References input.
     {
         input = true;
     }
Config() [2/2]
void hal::GpioPinStub::Config (PinConfigType config, bool startOutputState) override virtual
Implements hal::GpioPin.
Definition at line 45 of file GpioStub.cpp.
References input, and Set().
     {
         input = false;
         Set(startOutputState);
     }
DisableInterrupt()
void hal::GpioPinStub::DisableInterrupt () override virtual
Implements hal::GpioPin.
Definition at line 59 of file GpioStub.cpp.
References infra::none, and triggerOnChange.
     {
         triggerOnChange = infra::none;
     }
EnableInterrupt()
void hal::GpioPinStub::EnableInterrupt (const infra::Function< void()> & action, InterruptTrigger trigger) override virtual
Implements hal::GpioPin.
Definition at line 54 of file GpioStub.cpp.
References triggerOnChange.
     {
         triggerOnChange = std::make_pair(actionOnInterrupt, trigger);
     }
Get()
bool hal::GpioPinStub::Get () const override virtual
Implements hal::GpioPin.
Definition at line 6 of file GpioStub.cpp.
References state.
     {
         return state;
     }
GetOutputLatch()
bool hal::GpioPinStub::GetOutputLatch () const override virtual
Implements hal::GpioPin.
Definition at line 25 of file GpioStub.cpp.
References state.
Referenced by hal::GpioPinSpy::Set().
     {
         return state;
     }
GetStubState()
bool hal::GpioPinStub::GetStubState () const
Definition at line 78 of file GpioStub.cpp.
References state.
     {
         return state;
     }
IsInput()
bool hal::GpioPinStub::IsInput () const override virtual
Implements hal::GpioPin.
Definition at line 35 of file GpioStub.cpp.
References input.
     {
         return input;
     }
ResetConfig()
void hal::GpioPinStub::ResetConfig () override virtual
Implements hal::GpioPin.
Definition at line 51 of file GpioStub.cpp.
     {}
Set()
void hal::GpioPinStub::Set (bool value) override virtual
Implements hal::GpioPin.
Reimplemented in hal::GpioPinSpy.
Definition at line 11 of file GpioStub.cpp.
References hal::fallingEdge, input, hal::risingEdge, state, triggerOnChange, and value.
Referenced by Config(), and hal::GpioPinSpy::Set().
     {
         input = false;
         if (state != value)
         {
             state = value;
             if (triggerOnChange)
             if ((value && triggerOnChange->second != InterruptTrigger::fallingEdge)
                 || (!value && triggerOnChange->second != InterruptTrigger::risingEdge))
                 triggerOnChange->first();
         }
     }
SetAsInput()
void hal::GpioPinStub::SetAsInput () override virtual
Implements hal::GpioPin.
Definition at line 30 of file GpioStub.cpp.
References input.
     {
         input = true;
     }
SetStubState()
void hal::GpioPinStub::SetStubState (bool value)
Definition at line 64 of file GpioStub.cpp.
References hal::fallingEdge, input, hal::risingEdge, state, triggerOnChange, and value.
     {
         input = true;
         if (state != value)
         {
             state = value;
             if (triggerOnChange)
                 if ((value && triggerOnChange->second != InterruptTrigger::fallingEdge)
                     || (!value && triggerOnChange->second != InterruptTrigger::risingEdge))
                     triggerOnChange->first();
         }
     }
Member Data Documentation
input
bool hal::GpioPinStub::input = true private
Definition at line 36 of file GpioStub.hpp.
Referenced by Config(), IsInput(), Set(), SetAsInput(), and SetStubState().
state
bool hal::GpioPinStub::state = false private
Definition at line 35 of file GpioStub.hpp.
Referenced by Get(), GetOutputLatch(), GetStubState(), Set(), and SetStubState().
triggerOnChange
infra::Optional<std::pair<infra::Function<void()>, InterruptTrigger> > hal::GpioPinStub::triggerOnChange private
Definition at line 38 of file GpioStub.hpp.
Referenced by DisableInterrupt(), EnableInterrupt(), Set(), and SetStubState().
The documentation for this class was generated from the following files:
GpioStub.hpp
GpioStub.cpp