EMil: infra::JsonTokenizer Class Reference
infra::JsonTokenizer Class Reference
#include <Json.hpp>
Public Member Functions
JsonTokenizer (infra::BoundedConstString objectString)
JsonToken::Token Token ()
bool operator== (const JsonTokenizer &other) const
bool operator!= (const JsonTokenizer &other) const
Private Member Functions
void SkipWhitespace ()
JsonToken::Token TryCreateStringToken ()
JsonToken::Token TryCreateIntegerToken ()
JsonToken::Token TryCreateIdentifierToken ()
Private Attributes
infra::BoundedConstString objectString
std::size_t parseIndex = 0
Detailed Description
Definition at line 212 of file Json.hpp.
Constructor & Destructor Documentation
JsonTokenizer()
infra::JsonTokenizer::JsonTokenizer (infra::BoundedConstString objectString) explicit
Definition at line 456 of file Json.cpp.
         : objectString(objectString)
     {}
Member Function Documentation
operator!=()
bool infra::JsonTokenizer::operator!= (const JsonTokenizer & other) const
Definition at line 507 of file Json.cpp.
     {
         return !(*this == other);
     }
operator==()
bool infra::JsonTokenizer::operator== (const JsonTokenizer & other) const
Definition at line 502 of file Json.cpp.
References parseIndex.
     {
         return parseIndex == other.parseIndex;
     }
SkipWhitespace()
void infra::JsonTokenizer::SkipWhitespace () private
Definition at line 512 of file Json.cpp.
References objectString, parseIndex, and infra::BoundedStringBase< T >::size().
Referenced by Token().
     {
         while (parseIndex != objectString.size() && std::isspace(objectString[parseIndex]))                         //TICS !CON#007
             ++parseIndex;
     }
Token()
JsonToken::Token infra::JsonTokenizer::Token ()
Definition at line 460 of file Json.cpp.
References objectString, parseIndex, infra::BoundedStringBase< T >::size(), SkipWhitespace(), TryCreateIdentifierToken(), TryCreateIntegerToken(), and TryCreateStringToken().
Referenced by infra::CleanJsonContents(), infra::JsonArrayIterator::operator++(), infra::JsonObjectIterator::ParseNextToken(), infra::JsonIterator::SearchArrayEnd(), and infra::JsonIterator::SearchObjectEnd().
     {
         SkipWhitespace();
         if (parseIndex == objectString.size())
             return JsonToken::End();
         else
         {
             if (objectString[parseIndex] == '"')
                 return TryCreateStringToken();
             else if (objectString[parseIndex] == ':')
             {
                 ++parseIndex;
                 return JsonToken::Colon();
             }
             else if (objectString[parseIndex] == ',')
             {
                 ++parseIndex;
                 return JsonToken::Comma();
             }
             else if (objectString[parseIndex] == '.')
             {
                 ++parseIndex;
                 return JsonToken::Dot();
             }
             else if (objectString[parseIndex] == '{')
                 return JsonToken::LeftBrace(parseIndex++);
             else if (objectString[parseIndex] == '}')
                 return JsonToken::RightBrace(parseIndex++);
             else if (objectString[parseIndex] == '[')
                 return JsonToken::LeftBracket(parseIndex++);
             else if (objectString[parseIndex] == ']')
                 return JsonToken::RightBracket(parseIndex++);
             else if (std::isdigit(objectString[parseIndex]) != 0 || objectString[parseIndex] == '-')
                 return TryCreateIntegerToken();
             else if (std::isalpha(objectString[parseIndex]) != 0)
                 return TryCreateIdentifierToken();
             else
                 return JsonToken::Error();
         }
     }
TryCreateIdentifierToken()
JsonToken::Token infra::JsonTokenizer::TryCreateIdentifierToken () private
Definition at line 564 of file Json.cpp.
References objectString, parseIndex, infra::BoundedStringBase< T >::size(), and infra::BoundedStringBase< T >::substr().
Referenced by Token().
     {
         std::size_t tokenStart = parseIndex;
         while (parseIndex != objectString.size() && std::isalpha(objectString[parseIndex]))                         //TICS !CON#007
             ++parseIndex;
         infra::BoundedConstString identifier = objectString.substr(tokenStart, parseIndex - tokenStart);
         if (identifier == "true")
             return JsonToken::Boolean(true);
         else if (identifier == "false")
             return JsonToken::Boolean(false);
         else
             return JsonToken::Error();
     }
TryCreateIntegerToken()
JsonToken::Token infra::JsonTokenizer::TryCreateIntegerToken () private
Definition at line 538 of file Json.cpp.
References objectString, parseIndex, infra::BoundedStringBase< T >::size(), infra::BoundedStringBase< T >::substr(), and value.
Referenced by Token().
     {
         std::size_t tokenStart = parseIndex;
         bool sign = false;
         if (parseIndex != objectString.size() && objectString[parseIndex] == '-')                                       //TICS !CON#007
         {
             sign = true;
             ++parseIndex;
         }
         while (parseIndex != objectString.size() && std::isdigit(objectString[parseIndex]))                             //TICS !CON#007
             ++parseIndex;
         infra::BoundedConstString integer = objectString.substr(tokenStart, parseIndex - tokenStart);
         int32_t value = 0;
         for (std::size_t index = sign ? 1 : 0; index < integer.size(); ++index)
             value = value * 10 + integer[index] - '0';
         if (sign)
             value *= -1;
         return JsonToken::Integer(value);
     }
TryCreateStringToken()
JsonToken::Token infra::JsonTokenizer::TryCreateStringToken () private
Definition at line 518 of file Json.cpp.
References objectString, parseIndex, infra::BoundedStringBase< T >::size(), and infra::BoundedStringBase< T >::substr().
Referenced by Token().
     {
         ++parseIndex;
         std::size_t tokenStart = parseIndex;
         bool escape = false;
         while (escape || objectString[parseIndex] != '"')
         {
             escape = !escape && objectString[parseIndex] == '\\';
             ++parseIndex;
             if (parseIndex == objectString.size())
                 return JsonToken::Error();
         }
         ++parseIndex;
         return JsonToken::String(objectString.substr(tokenStart, parseIndex - tokenStart - 1));
     }
Member Data Documentation
objectString
infra::BoundedConstString infra::JsonTokenizer::objectString private
Definition at line 229 of file Json.hpp.
Referenced by SkipWhitespace(), Token(), TryCreateIdentifierToken(), TryCreateIntegerToken(), and TryCreateStringToken().
parseIndex
std::size_t infra::JsonTokenizer::parseIndex = 0 private
Definition at line 230 of file Json.hpp.
Referenced by operator==(), SkipWhitespace(), Token(), TryCreateIdentifierToken(), TryCreateIntegerToken(), and TryCreateStringToken().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp