EMil: infra::LimitedStreamWriter Class Reference
infra::LimitedStreamWriter Class Reference
#include <LimitedOutputStream.hpp>
Public Member Functions
LimitedStreamWriter (StreamWriter &output, uint32_t length)
LimitedStreamWriter (const LimitedStreamWriter &other)
virtual void Insert (ConstByteRange range, StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
Public Member Functions inherited from infra::StreamWriter
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Private Attributes
StreamWriter & output
uint32_t length
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 8 of file LimitedOutputStream.hpp.
Constructor & Destructor Documentation
LimitedStreamWriter() [1/2]
infra::LimitedStreamWriter::LimitedStreamWriter (StreamWriter & output, uint32_t length)
Definition at line 5 of file LimitedOutputStream.cpp.
         : output(output)
         , length(length)
     {}
LimitedStreamWriter() [2/2]
infra::LimitedStreamWriter::LimitedStreamWriter (const LimitedStreamWriter & other)
Definition at line 10 of file LimitedOutputStream.cpp.
         : output(other.output)
         , length(other.length)
     {}
Member Function Documentation
Available()
std::size_t infra::LimitedStreamWriter::Available () const override virtual
Implements infra::StreamWriter.
Definition at line 23 of file LimitedOutputStream.cpp.
References infra::StreamWriter::Available(), length, and output.
     {
         return std::min<std::size_t>(length, output.Available());
     }
Insert()
void infra::LimitedStreamWriter::Insert (ConstByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamWriter.
Definition at line 15 of file LimitedOutputStream.cpp.
References infra::StreamWriter::Insert(), length, output, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         errorPolicy.ReportResult(length >= range.size());
         range.shrink_from_back_to(length);
         length -= range.size();
         output.Insert(range, errorPolicy);
     }
Member Data Documentation
length
uint32_t infra::LimitedStreamWriter::length private
Definition at line 21 of file LimitedOutputStream.hpp.
Referenced by Available(), and Insert().
output
StreamWriter& infra::LimitedStreamWriter::output private
Definition at line 20 of file LimitedOutputStream.hpp.
Referenced by Available(), and Insert().
The documentation for this class was generated from the following files:
LimitedOutputStream.hpp
LimitedOutputStream.cpp