EMil: services::StreamEchoConnection Class Reference
services::StreamEchoConnection Class Reference
#include <StreamEcho.hpp>
Public Member Functions
StreamEchoConnection ()=default
void SendInitial ()
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
Public Member Functions inherited from services::ConnectionObserver
virtual void Connected ()
virtual void ClosingConnection ()
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Private Member Functions
void TryRequestSendStream ()
Private Attributes
std::size_t requestedSize = 0
Additional Inherited Members
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Detailed Description
Definition at line 9 of file StreamEcho.hpp.
Constructor & Destructor Documentation
StreamEchoConnection()
services::StreamEchoConnection::StreamEchoConnection () default
Member Function Documentation
DataReceived()
void services::StreamEchoConnection::DataReceived () override virtual
Implements services::ConnectionObserver.
Definition at line 29 of file StreamEcho.cpp.
References requestedSize, and TryRequestSendStream().
     {
         if (requestedSize == 0)
             TryRequestSendStream();
     }
SendInitial()
void services::StreamEchoConnection::SendInitial ()
Definition at line 5 of file StreamEcho.cpp.
     {}
SendStreamAvailable()
void services::StreamEchoConnection::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::ConnectionObserver.
Definition at line 8 of file StreamEcho.cpp.
References infra::InputStream::ContiguousRange(), requestedSize, infra::MemoryRange< T >::size(), infra::SingleObserver< ConnectionObserver, Connection >::Subject(), and TryRequestSendStream().
     {
         {
             infra::DataOutputStream::WithErrorPolicy stream(*writer);
             auto receiveStreamReader = Subject().ReceiveStream();
             infra::DataInputStream::WithErrorPolicy receiveStream(*receiveStreamReader);
             while (requestedSize != 0)
             {
                 infra::ConstByteRange range = receiveStream.ContiguousRange(requestedSize);
                 requestedSize -= range.size();
                 stream << range;
             }
             Subject().AckReceived();
             writer = nullptr;
         }
         TryRequestSendStream();
     }
TryRequestSendStream()
void services::StreamEchoConnection::TryRequestSendStream () private
Definition at line 35 of file StreamEcho.cpp.
References requestedSize, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by DataReceived(), and SendStreamAvailable().
     {
         auto receiveStreamReader = Subject().ReceiveStream();
         requestedSize = std::min<std::size_t>(receiveStreamReader->Available(), Subject().MaxSendStreamSize());
         if (requestedSize != 0)
             Subject().RequestSendStream(requestedSize);
     }
Member Data Documentation
requestedSize
std::size_t services::StreamEchoConnection::requestedSize = 0 private
Definition at line 24 of file StreamEcho.hpp.
Referenced by DataReceived(), SendStreamAvailable(), and TryRequestSendStream().
The documentation for this class was generated from the following files:
StreamEcho.hpp
StreamEcho.cpp