EMil: TestClaimableResource.cpp File Reference
TestClaimableResource.cpp File Reference
Classes
class TestClaimer
class TestClaimableResource
Functions
TEST_F (TestClaimableResource, ClaimIsGranted)
TEST_F (TestClaimableResource, ClaimWhileAlreadyClaimedIsGrantedAfterRelease)
TEST_F (TestClaimableResource, IfNoReleaseIsDoneSecondClaimIsNotGranted)
TEST_F (TestClaimableResource, ReleaseBeforeClaimGranted)
TEST_F (TestClaimableResource, AtDestructorTheClaimIsReleased)
TEST_F (TestClaimableResource, ClaimIsGrantedWhileProcessingReleaseEvent)
TEST_F (TestClaimableResource, TwoConsecutiveReleasesBeforeReleaseOfClaimIsProcessedResultsInNoAdditionalClaimsGranted)
Function Documentation
TEST_F() [1/7]
TEST_F (TestClaimableResource , ClaimIsGranted)
Definition at line 40 of file TestClaimableResource.cpp.
References EXPECT_EQ().
 {
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     EXPECT_EQ(1, claimerA.claimsGranted);
 }
TEST_F() [2/7]
TEST_F (TestClaimableResource , ClaimWhileAlreadyClaimedIsGrantedAfterRelease)
Definition at line 47 of file TestClaimableResource.cpp.
References EXPECT_EQ().
 {
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     EXPECT_EQ(1, claimerA.claimsGranted);
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     EXPECT_EQ(1, claimerA.claimsGranted);
     claimerA.Release();
     ExecuteAllActions();
     EXPECT_EQ(2, claimerA.claimsGranted);
 }
TEST_F() [3/7]
TEST_F (TestClaimableResource , IfNoReleaseIsDoneSecondClaimIsNotGranted)
Definition at line 60 of file TestClaimableResource.cpp.
 {
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     ASSERT_EQ(1, claimerA.claimsGranted);
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     ASSERT_EQ(1, claimerA.claimsGranted);
 }
TEST_F() [4/7]
TEST_F (TestClaimableResource , ReleaseBeforeClaimGranted)
Definition at line 70 of file TestClaimableResource.cpp.
References EXPECT_EQ().
 {
     claimerB.Claim([this]() { claimerB.GrantedClaim(); });
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     EXPECT_EQ(0, claimerA.claimsGranted);
     EXPECT_EQ(1, claimerB.claimsGranted);
     claimerA.Release();
     claimerB.Release();
     ExecuteAllActions();
     EXPECT_EQ(0, claimerA.claimsGranted);
     EXPECT_EQ(1, claimerB.claimsGranted);
 }
TEST_F() [5/7]
TEST_F (TestClaimableResource , AtDestructorTheClaimIsReleased)
Definition at line 84 of file TestClaimableResource.cpp.
References infra::ClaimableResource::ClaimerWithSize< ExtraSize >::Claim(), EXPECT_EQ(), and TestClaimer::GrantedClaim().
 {
     {
         TestClaimer localClaimer(resource);
         localClaimer.Claim([&localClaimer]() { localClaimer.GrantedClaim(); });
         claimerA.Claim([this]() { claimerA.GrantedClaim(); });
         ExecuteAllActions();
         EXPECT_EQ(0, claimerA.claimsGranted);
     }
     ExecuteAllActions();
     EXPECT_EQ(1, claimerA.claimsGranted);
 }
TEST_F() [6/7]
TEST_F (TestClaimableResource , ClaimIsGrantedWhileProcessingReleaseEvent)
Definition at line 97 of file TestClaimableResource.cpp.
References EXPECT_EQ().
 {
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     ExecuteAllActions();
     claimerB.Claim([this]() { claimerB.GrantedClaim(); });
     claimerA.Release();
     claimerC.Claim([this]() { claimerC.GrantedClaim(); });
     EXPECT_EQ(0, claimerB.claimsGranted);
     ExecuteAllActions();
     EXPECT_EQ(1, claimerB.claimsGranted);
 }
TEST_F() [7/7]
TEST_F (TestClaimableResource , TwoConsecutiveReleasesBeforeReleaseOfClaimIsProcessedResultsInNoAdditionalClaimsGranted)
Definition at line 109 of file TestClaimableResource.cpp.
References EXPECT_EQ().
 {
     claimerA.Claim([this]() { claimerA.GrantedClaim(); });
     claimerB.Claim([this]() { claimerB.GrantedClaim(); });
     claimerC.Claim([this]() { claimerC.GrantedClaim(); });
     ExecuteAllActions();
     ASSERT_EQ(1, claimerA.claimsGranted);
     claimerA.Release();
     claimerB.Release();
     claimerC.Release();
     ExecuteAllActions();
     EXPECT_EQ(1, claimerA.claimsGranted);
     EXPECT_EQ(0, claimerB.claimsGranted);
     EXPECT_EQ(0, claimerC.claimsGranted);
 }