EMil: IntrusiveSetTest Class Reference
IntrusiveSetTest Class Reference
Public Member Functions
std::string Representation (const infra::IntrusiveSet< SetInt > &tree)
void AddRepresentation (const SetInt &node, std::ostream &os)
Detailed Description
Definition at line 29 of file TestIntrusiveSet.cpp.
Member Function Documentation
AddRepresentation()
void IntrusiveSetTest::AddRepresentation (const SetInt & node, std::ostream & os) inline
Definition at line 44 of file TestIntrusiveSet.cpp.
Referenced by Representation().
     {
         if (node.colour == SetInt::Colour::black)
             os << "b";
         else
             os << "r";
         os << node.value;
         if (node.left || node.right)
         {
             os << "(";
             if (node.left)
                 AddRepresentation(*node.left, os);
             os << ",";
             if (node.right)
                 AddRepresentation(*node.right, os);
             os << ")";
         }
     }
Representation()
std::string IntrusiveSetTest::Representation (const infra::IntrusiveSet< SetInt > & tree) inline
Definition at line 33 of file TestIntrusiveSet.cpp.
References AddRepresentation(), infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_TRUE(), infra::IntrusiveSet< T, Compare >::invariant_holds(), and infra::IntrusiveBinarySearchTree< T, Compare >::root().
     {
         EXPECT_TRUE(tree.invariant_holds());
         std::ostringstream os;
         if (!tree.empty())
             AddRepresentation(tree.root(), os);
         return os.str();
     }
The documentation for this class was generated from the following file:
TestIntrusiveSet.cpp