EMil: infra::PerfectTimerService Class Reference
infra::PerfectTimerService Class Reference
#include <PerfectTimerService.hpp>
Public Member Functions
PerfectTimerService (uint32_t id)
virtual void NextTriggerChanged () override
virtual TimePoint Now () const override
virtual Duration Resolution () const override
void SetResolution (Duration resolution)
void TimeProgressed (Duration amount)
Public Member Functions inherited from infra::TimerService
uint32_t Id () const
void RegisterTimer (Timer &timer)
void UnregisterTimer (Timer &timer, TimePoint oldTriggerTime)
void UpdateTriggerTime (Timer &timer, TimePoint oldTriggerTime)
void Progressed (TimePoint time)
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Private Attributes
TimePoint systemTime = TimePoint()
Duration resolution
uint32_t nextNotification
infra::TimePoint previousTrigger
Additional Inherited Members
Protected Member Functions inherited from infra::TimerService
TimerService (uint32_t id)
TimerService (const TimerService &other)=delete
~TimerService ()
TimerService & operator= (const TimerService &other)=delete
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 8 of file PerfectTimerService.hpp.
Constructor & Destructor Documentation
PerfectTimerService()
infra::PerfectTimerService::PerfectTimerService (uint32_t id)
Definition at line 7 of file PerfectTimerService.cpp.
         : TimerService(id)
         , resolution(std::chrono::milliseconds(0))
         , systemTime(TimePoint())
     {}
Member Function Documentation
NextTriggerChanged()
void infra::PerfectTimerService::NextTriggerChanged () override virtual
Reimplemented from infra::TimerService.
Definition at line 13 of file PerfectTimerService.cpp.
References nextNotification, infra::TimerService::NextTrigger(), and previousTrigger.
     {
         nextNotification = static_cast<uint32_t>(std::max<std::chrono::milliseconds::rep>(
                         std::chrono::duration_cast<std::chrono::milliseconds>(NextTrigger() - previousTrigger).count(), 0));
     }
Now()
TimePoint infra::PerfectTimerService::Now () const override virtual
Implements infra::TimerService.
Definition at line 19 of file PerfectTimerService.cpp.
References systemTime.
Referenced by infra::ClockFixture::After(), and infra::ClockFixture::ForwardTime().
     {
         return systemTime;
     }
Resolution()
Duration infra::PerfectTimerService::Resolution () const override virtual
Implements infra::TimerService.
Definition at line 24 of file PerfectTimerService.cpp.
References resolution.
     {
         return resolution;
     }
SetResolution()
void infra::PerfectTimerService::SetResolution (Duration resolution)
Definition at line 29 of file PerfectTimerService.cpp.
References resolution.
     {
         this->resolution = resolution;
     }
TimeProgressed()
void infra::PerfectTimerService::TimeProgressed (Duration amount)
Definition at line 34 of file PerfectTimerService.cpp.
References infra::TimerService::Progressed(), and systemTime.
Referenced by infra::ClockFixture::ForwardTime().
     {
         systemTime += amount;
         Progressed(systemTime);
     }
Member Data Documentation
nextNotification
uint32_t infra::PerfectTimerService::nextNotification private
Definition at line 25 of file PerfectTimerService.hpp.
Referenced by NextTriggerChanged().
previousTrigger
infra::TimePoint infra::PerfectTimerService::previousTrigger private
Definition at line 26 of file PerfectTimerService.hpp.
Referenced by NextTriggerChanged().
resolution
Duration infra::PerfectTimerService::resolution private
Definition at line 23 of file PerfectTimerService.hpp.
Referenced by Resolution(), and SetResolution().
systemTime
TimePoint infra::PerfectTimerService::systemTime = TimePoint() private
Definition at line 22 of file PerfectTimerService.hpp.
Referenced by Now(), and TimeProgressed().
The documentation for this class was generated from the following files:
PerfectTimerService.hpp
PerfectTimerService.cpp