EMil: TestBoundedForwardList.cpp File Reference
TestBoundedForwardList.cpp File Reference
Functions
TEST (BoundedForwardListTest, TestConstructedEmpty)
TEST (BoundedForwardListTest, TestConstructionWith2Elements)
TEST (BoundedForwardListTest, TestConstructionWithRange)
TEST (BoundedForwardListTest, TestConstructionWithInitializerList)
TEST (BoundedForwardListTest, TestCopyConstruction)
TEST (BoundedForwardListTest, TestMoveConstruction)
TEST (BoundedForwardListTest, TestAssignment)
TEST (BoundedForwardListTest, TestSelfAssignment)
TEST (BoundedForwardListTest, TestMove)
TEST (BoundedForwardListTest, TestBeginAndEnd)
TEST (BoundedForwardListTest, TestFull)
TEST (BoundedForwardListTest, TestFront)
TEST (BoundedForwardListTest, TestAssignRange)
TEST (BoundedForwardListTest, TestAssignN)
TEST (BoundedForwardListTest, TestMoveFromRange)
TEST (BoundedForwardListTest, TestPushFront)
TEST (BoundedForwardListTest, TestPopFront)
TEST (BoundedForwardListTest, TestSwap)
TEST (BoundedForwardListTest, TestSwapDifferentSizes)
TEST (BoundedForwardListTest, TestClear)
TEST (BoundedForwardListTest, TestInsertAfter)
TEST (BoundedForwardList, TestErase)
TEST (BoundedForwardListTest, TestEraseAllAfter)
TEST (BoundedForwardListTest, TestEraseAllAfterNothing)
TEST (BoundedForwardListTest, CopyConstructIterator)
TEST (BoundedForwardListTest, Arrow)
TEST (BoundedForwardListTest, PostInc)
TEST (BoundedForwardListTest, TestEquals)
TEST (BoundedForwardListTest, TestUnequals)
TEST (BoundedForwardListTest, TestLessThan)
TEST (BoundedForwardListTest, TestGreaterThan)
TEST (BoundedForwardListTest, TestLessThanOrEqual)
TEST (BoundedForwardListTest, TestGreaterThanOrEqual)
Function Documentation
TEST() [1/33]
TEST (BoundedForwardListTest , TestConstructedEmpty)
Definition at line 7 of file TestBoundedForwardList.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list;
     EXPECT_TRUE(list.empty());
     EXPECT_FALSE(list.full());
     EXPECT_EQ(0, list.size());
     EXPECT_EQ(5, list.max_size());
 }
TEST() [2/33]
TEST (BoundedForwardListTest , TestConstructionWith2Elements)
Definition at line 17 of file TestBoundedForwardList.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     EXPECT_FALSE(list.empty());
     EXPECT_FALSE(list.full());
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(4, *list.begin());
     EXPECT_EQ(4, *std::next(list.begin()));
 }
TEST() [3/33]
TEST (BoundedForwardListTest , TestConstructionWithRange)
Definition at line 29 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(0, *list.begin());
     EXPECT_EQ(1, *std::next(list.begin()));
     EXPECT_EQ(2, *std::next(list.begin(), 2));
 }
TEST() [4/33]
TEST (BoundedForwardListTest , TestConstructionWithInitializerList)
Definition at line 41 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list({ 0, 1, 2 });
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(0, *list.begin());
     EXPECT_EQ(1, *std::next(list.begin()));
     EXPECT_EQ(2, *std::next(list.begin(), 2));
 }
TEST() [5/33]
TEST (BoundedForwardListTest , TestCopyConstruction)
Definition at line 52 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> original(std::size_t(2), 4);
     infra::BoundedForwardList<int>::WithMaxSize<5> copy(original);
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(4, copy.front());
 }
TEST() [6/33]
TEST (BoundedForwardListTest , TestMoveConstruction)
Definition at line 61 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_front(2);
     infra::BoundedForwardList<infra::MoveConstructible>::WithMaxSize<5> copy(std::move(original));
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy.front().x);
 }
TEST() [7/33]
TEST (BoundedForwardListTest , TestAssignment)
Definition at line 71 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> original(std::size_t(2), 4);
     infra::BoundedForwardList<int>::WithMaxSize<5> copy;
     copy = original;
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(4, copy.front());
 }
TEST() [8/33]
TEST (BoundedForwardListTest , TestSelfAssignment)
Definition at line 81 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> original(std::size_t(2), 4);
     original = original;
     EXPECT_EQ(2, original.size());
     EXPECT_EQ(4, original.front());
 }
TEST() [9/33]
TEST (BoundedForwardListTest , TestMove)
Definition at line 90 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_front(2);
     infra::BoundedForwardList<infra::MoveConstructible>::WithMaxSize<5> copy;
     copy = std::move(original);
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy.front().x);
 }
TEST() [10/33]
TEST (BoundedForwardListTest , TestBeginAndEnd)
Definition at line 101 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(list.end(), std::next(list.begin(), 3));
     EXPECT_EQ(list.cbegin(), list.begin());
     EXPECT_EQ(list.cend(), list.end());
     EXPECT_EQ(0, *list.begin());
 }
TEST() [11/33]
TEST (BoundedForwardListTest , TestFull)
Definition at line 113 of file TestBoundedForwardList.cpp.
References EXPECT_TRUE().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(5), 4);
     EXPECT_TRUE(list.full());
 }
TEST() [12/33]
TEST (BoundedForwardListTest , TestFront)
Definition at line 120 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(0, list.front());
 }
TEST() [13/33]
TEST (BoundedForwardListTest , TestAssignRange)
Definition at line 128 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list(range, range + 3);
     int otherRange[2] = { 4, 5 };
     list.assign(otherRange, otherRange + 2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(4, list.front());
     EXPECT_EQ(5, *std::next(list.begin()));
 }
TEST() [14/33]
TEST (BoundedForwardListTest , TestAssignN)
Definition at line 141 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list(range, range + 3);
     list.assign(std::size_t(2), 4);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(4, list.front());
     EXPECT_EQ(4, *std::next(list.begin()));
 }
TEST() [15/33]
TEST (BoundedForwardListTest , TestMoveFromRange)
Definition at line 153 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_front(2);
     infra::BoundedForwardList<infra::MoveConstructible>::WithMaxSize<5> copy;
     copy.move_from_range(original.begin(), original.end());
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy.front().x);
 }
TEST() [16/33]
TEST (BoundedForwardListTest , TestPushFront)
Definition at line 164 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.push_front(1);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(1, list.front());
 }
TEST() [17/33]
TEST (BoundedForwardListTest , TestPopFront)
Definition at line 173 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.pop_front();
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(4, list.front());
 }
TEST() [18/33]
TEST (BoundedForwardListTest , TestSwap)
Definition at line 182 of file TestBoundedForwardList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5};
     infra::BoundedForwardList<int>::WithMaxSize<5> list2(range2, range2 + 3);
     swap(list1, list2);
     infra::BoundedForwardList<int>::WithMaxSize<5> expectedList1(range2, range2 + 3);
     infra::BoundedForwardList<int>::WithMaxSize<5> expectedList2(range1, range1 + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [19/33]
TEST (BoundedForwardListTest , TestSwapDifferentSizes)
Definition at line 197 of file TestBoundedForwardList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2};
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[2] = { 3, 4};
     infra::BoundedForwardList<int>::WithMaxSize<5> list2(range2, range2 + 2);
     swap(list1, list2);
     infra::BoundedForwardList<int>::WithMaxSize<5> expectedList1(range2, range2 + 2);
     infra::BoundedForwardList<int>::WithMaxSize<5> expectedList2(range1, range1 + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [20/33]
TEST (BoundedForwardListTest , TestClear)
Definition at line 212 of file TestBoundedForwardList.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.clear();
     EXPECT_EQ(list.size(), 0);
     EXPECT_TRUE(list.empty());
     infra::BoundedForwardList<int>::WithMaxSize<5> expectedList;
     EXPECT_EQ(expectedList, list);
 }
TEST() [21/33]
TEST (BoundedForwardListTest , TestInsertAfter)
Definition at line 224 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     list.insert_after(list.begin(), 2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, *std::next(list.begin()));
 }
TEST() [22/33]
TEST (BoundedForwardList , TestErase)
Definition at line 233 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(3), 4);
     list.erase_slow(std::next(list.begin(), 2));
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, std::distance(list.begin(), list.end()));
     list.erase_slow(list.begin());
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
 }
TEST() [23/33]
TEST (BoundedForwardListTest , TestEraseAllAfter)
Definition at line 246 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(3), 4);
     list.erase_all_after(list.begin());
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
 }
TEST() [24/33]
TEST (BoundedForwardListTest , TestEraseAllAfterNothing)
Definition at line 255 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     list.erase_all_after(list.begin());
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
 }
TEST() [25/33]
TEST (BoundedForwardListTest , CopyConstructIterator)
Definition at line 264 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedForwardList<int>::iterator i(list.begin());
     EXPECT_EQ(4, *i);
 }
TEST() [26/33]
TEST (BoundedForwardListTest , Arrow)
Definition at line 272 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     EXPECT_EQ(4, *(list.begin().operator->()));
 }
TEST() [27/33]
TEST (BoundedForwardListTest , PostInc)
Definition at line 279 of file TestBoundedForwardList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedForwardList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedForwardList<int>::iterator i(list.begin());
     EXPECT_EQ(4, *i++);
 }
TEST() [28/33]
TEST (BoundedForwardListTest , TestEquals)
Definition at line 287 of file TestBoundedForwardList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list2(range2, range2 + 3);
     int range3[2] = { 0, 1 };
     infra::BoundedForwardList<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 == list1);
     EXPECT_FALSE(list1 == list2);
     EXPECT_FALSE(list1 == deque3);
     EXPECT_FALSE(deque3 == list1);
 }
TEST() [29/33]
TEST (BoundedForwardListTest , TestUnequals)
Definition at line 302 of file TestBoundedForwardList.cpp.
References EXPECT_FALSE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 != list1);
 }
TEST() [30/33]
TEST (BoundedForwardListTest , TestLessThan)
Definition at line 310 of file TestBoundedForwardList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[3] = { 0, 4, 5 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list2(range2, range2 + 3);
     int range3[2] = { 0, 1 };
     infra::BoundedForwardList<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 < list2);
     EXPECT_FALSE(list1 < deque3);
     EXPECT_FALSE(list1 < list1);
 }
TEST() [31/33]
TEST (BoundedForwardListTest , TestGreaterThan)
Definition at line 324 of file TestBoundedForwardList.cpp.
References EXPECT_FALSE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 > list1);
 }
TEST() [32/33]
TEST (BoundedForwardListTest , TestLessThanOrEqual)
Definition at line 332 of file TestBoundedForwardList.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 <= list1);
 }
TEST() [33/33]
TEST (BoundedForwardListTest , TestGreaterThanOrEqual)
Definition at line 340 of file TestBoundedForwardList.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedForwardList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 >= list1);
 }