EMil: services::I2cMultipleAccessMaster Class Reference
services::I2cMultipleAccessMaster Class Reference
#include <I2cMultipleAccess.hpp>
Public Member Functions
I2cMultipleAccessMaster (hal::I2cMaster &master)
virtual void SendData (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction, infra::Function< void(hal::Result, uint32_t numberOfBytesSent)> onSent) override
virtual void ReceiveData (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction, infra::Function< void(hal::Result)> onReceived) override
Public Member Functions inherited from hal::I2cMaster
I2cMaster ()=default
I2cMaster (const I2cMaster &other)=delete
I2cMaster & operator= (const I2cMaster &other)=delete
Public Member Functions inherited from infra::ClaimableResource
ClaimableResource ()=default
ClaimableResource (const ClaimableResource &other)=delete
ClaimableResource & operator= (const ClaimableResource &other)=delete
~ClaimableResource ()
Private Attributes
hal::I2cMaster & master
Additional Inherited Members
Public Types inherited from infra::ClaimableResource
using Claimer = ClaimerWithSize< INFRA_DEFAULT_FUNCTION_EXTRA_SIZE >
Protected Member Functions inherited from hal::I2cMaster
~I2cMaster ()=default
Detailed Description
Definition at line 14 of file I2cMultipleAccess.hpp.
Constructor & Destructor Documentation
I2cMultipleAccessMaster()
services::I2cMultipleAccessMaster::I2cMultipleAccessMaster (hal::I2cMaster & master) explicit
Definition at line 5 of file I2cMultipleAccess.cpp.
         : master(master)
     {}
Member Function Documentation
ReceiveData()
void services::I2cMultipleAccessMaster::ReceiveData (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction, infra::Function< void(hal::Result)> onReceived) override virtual
Implements hal::I2cMaster.
Definition at line 15 of file I2cMultipleAccess.cpp.
References infra::data, master, and hal::I2cMaster::ReceiveData().
Referenced by services::I2cMultipleAccess::ReceiveDataOnClaimed().
     {
         master.ReceiveData(address, data, nextAction, onReceived);
     }
SendData()
void services::I2cMultipleAccessMaster::SendData (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction, infra::Function< void(hal::Result, uint32_t numberOfBytesSent)> onSent) override virtual
Implements hal::I2cMaster.
Definition at line 9 of file I2cMultipleAccess.cpp.
References infra::data, master, and hal::I2cMaster::SendData().
Referenced by services::I2cMultipleAccess::SendDataOnClaimed().
     {
         master.SendData(address, data, nextAction, onSent);
     }
Member Data Documentation
master
hal::I2cMaster& services::I2cMultipleAccessMaster::master private
Definition at line 27 of file I2cMultipleAccess.hpp.
Referenced by ReceiveData(), and SendData().
The documentation for this class was generated from the following files:
I2cMultipleAccess.hpp
I2cMultipleAccess.cpp