EMil: infra::TimerLimitedRepeating Class Reference
infra::TimerLimitedRepeating Class Reference
#include <TimerLimitedRepeating.hpp>
Public Member Functions
TimerLimitedRepeating (uint32_t timerServiceId=systemTimerServiceId)
TimerLimitedRepeating (int aHowMany, Duration duration, const infra::Function< void()> &action, uint32_t timerServiceId=systemTimerServiceId)
void Start (int aHowMany, Duration duration, const infra::Function< void()> &action)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
virtual const infra::Function< void()> & Action () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Attributes
TimePoint triggerStart
Duration triggerPeriod
int howMany = 0
infra::Function< void()> action
Detailed Description
Definition at line 8 of file TimerLimitedRepeating.hpp.
Constructor & Destructor Documentation
TimerLimitedRepeating() [1/2]
infra::TimerLimitedRepeating::TimerLimitedRepeating (uint32_t timerServiceId = systemTimerServiceId) explicit
Definition at line 5 of file TimerLimitedRepeating.cpp.
         : Timer(timerServiceId)
         , triggerPeriod()
     {}
TimerLimitedRepeating() [2/2]
infra::TimerLimitedRepeating::TimerLimitedRepeating (int aHowMany, Duration duration, const infra::Function< void()> & action, uint32_t timerServiceId = systemTimerServiceId)
Definition at line 10 of file TimerLimitedRepeating.cpp.
References Start().
         : Timer(timerServiceId)
     {
         Start(aHowMany, duration, aAction);
     }
Member Function Documentation
ComputeNextTriggerTime()
void infra::TimerLimitedRepeating::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 27 of file TimerLimitedRepeating.cpp.
References action, infra::Timer::Cancel(), howMany, infra::Timer::Now(), infra::Timer::SetNextTriggerTime(), triggerPeriod, and triggerStart.
Referenced by Start().
     {
         if (howMany != 0)
         {
             --howMany;
             TimePoint now = Now();
             Duration diff = now - triggerStart;
             if (diff < Duration())
                 now += triggerPeriod;
             diff %= triggerPeriod;
             SetNextTriggerTime(now - diff + triggerPeriod, action);
         }
         else
             Cancel();
     }
Start()
void infra::TimerLimitedRepeating::Start (int aHowMany, Duration duration, const infra::Function< void()> & action)
Definition at line 16 of file TimerLimitedRepeating.cpp.
References action, ComputeNextTriggerTime(), howMany, infra::Timer::Now(), infra::Timer::Resolution(), triggerPeriod, and triggerStart.
Referenced by TimerLimitedRepeating().
     {
         action = aAction;
         triggerStart = Now() + Resolution();
         triggerPeriod = duration;
         howMany = aHowMany;
         ComputeNextTriggerTime();
     }
Member Data Documentation
action
infra::Function<void()> infra::TimerLimitedRepeating::action private
Definition at line 24 of file TimerLimitedRepeating.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
howMany
int infra::TimerLimitedRepeating::howMany = 0 private
Definition at line 23 of file TimerLimitedRepeating.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
triggerPeriod
Duration infra::TimerLimitedRepeating::triggerPeriod private
Definition at line 22 of file TimerLimitedRepeating.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
triggerStart
TimePoint infra::TimerLimitedRepeating::triggerStart private
Definition at line 21 of file TimerLimitedRepeating.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
The documentation for this class was generated from the following files:
TimerLimitedRepeating.hpp
TimerLimitedRepeating.cpp