EMil: services::MqttClientImpl::StateConnected Class Reference
services::MqttClientImpl::StateConnected Class Reference
Public Member Functions
virtual void ClosingConnection ()
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived (infra::StreamReader &reader) override
virtual void Publish (infra::BoundedConstString topic, infra::BoundedConstString payload) override
StateBase (MqttClientImpl &clientConnection)
StateBase (const StateBase &other)=delete
Public Member Functions inherited from services::MqttClientImpl::StateBase
StateBase (MqttClientImpl &clientConnection)
StateBase (const StateBase &other)=delete
StateBase & operator= (const StateBase &other)=delete
virtual ~StateBase ()=default
virtual void Connected ()
Private Attributes
infra::BoundedConstString topic
infra::BoundedConstString payload
infra::TimerSingleShot publishTimeout
Additional Inherited Members
Protected Attributes inherited from services::MqttClientImpl::StateBase
MqttClientImpl & clientConnection
Detailed Description
Definition at line 151 of file MqttClientImpl.hpp.
Member Function Documentation
ClosingConnection()
void services::MqttClientImpl::StateConnected::ClosingConnection () virtual
Implements services::MqttClientImpl::StateBase.
Definition at line 219 of file MqttClientImpl.cpp.
     {
         clientConnection.GetObserver().ClosingConnection();
         clientConnection.observer->Detach();
     }
DataReceived()
void services::MqttClientImpl::StateConnected::DataReceived (infra::StreamReader & reader) override virtual
Implements services::MqttClientImpl::StateBase.
Definition at line 235 of file MqttClientImpl.cpp.
References infra::InputStream::Failed(), services::MqttClientImpl::MqttParser::GetPacketType(), services::MqttClientImpl::packetTypePubAck, services::MqttClientImpl::publishTimeout, and infra::softFail.
     {
         infra::DataInputStream::WithErrorPolicy stream(reader, infra::softFail);
         MqttParser parser(stream);
         if (stream.Failed())
             return;
         if (parser.GetPacketType() == PacketType::packetTypePubAck)
         {
             uint16_t packetIdentifier;
             stream >> packetIdentifier;
             if (stream.Failed())
                 return;
             publishTimeout.Cancel();
             clientConnection.GetObserver().PublishDone();
             clientConnection.ConnectionObserver::Subject().AckReceived();
         }
     }
Publish()
void services::MqttClientImpl::StateConnected::Publish (infra::BoundedConstString topic, infra::BoundedConstString payload) override virtual
Reimplemented from services::MqttClientImpl::StateBase.
Definition at line 256 of file MqttClientImpl.cpp.
References services::MqttClientImpl::MqttFormatter::MessageSizePublish().
     {
         this->topic = topic;
         this->payload = payload;
         clientConnection.ConnectionObserver::Subject().RequestSendStream(MqttFormatter::MessageSizePublish(topic, payload));
     }
SendStreamAvailable()
void services::MqttClientImpl::StateConnected::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::MqttClientImpl::StateBase.
Definition at line 225 of file MqttClientImpl.cpp.
References services::MqttClientImpl::MqttFormatter::MessagePublish(), and services::MqttClientImpl::publishTimeout.
     {
         infra::DataOutputStream::WithErrorPolicy stream(*writer);
         MqttFormatter formatter(stream);
         formatter.MessagePublish(topic, payload);
         writer = nullptr;
         publishTimeout.Start(clientConnection.publishTimeout, [this]() { clientConnection.ConnectionObserver::Subject().AbortAndDestroy(); });
     }
StateBase() [1/2]
services::MqttClientImpl::StateBase::StateBase delete
StateBase() [2/2]
services::MqttClientImpl::StateBase::StateBase
Definition at line 129 of file MqttClientImpl.cpp.
         : clientConnection(clientConnection)
     {}
Member Data Documentation
payload
infra::BoundedConstString services::MqttClientImpl::StateConnected::payload private
Definition at line 165 of file MqttClientImpl.hpp.
publishTimeout
infra::TimerSingleShot services::MqttClientImpl::StateConnected::publishTimeout private
Definition at line 166 of file MqttClientImpl.hpp.
topic
infra::BoundedConstString services::MqttClientImpl::StateConnected::topic private
Definition at line 164 of file MqttClientImpl.hpp.
The documentation for this class was generated from the following files:
MqttClientImpl.hpp
MqttClientImpl.cpp