EMil: TestTokenizer.cpp File Reference
TestTokenizer.cpp File Reference
Functions
TEST (TokenizerTest, construction)
TEST (TokenizerTest, get_single_token)
TEST (TokenizerTest, get_token_out_of_many)
TEST (TokenizerTest, get_number_of_tokens)
TEST (TokenizerTest, nonexisting_token_is_empty)
TEST (TokenizerTest, skip_leading_tokens)
TEST (TokenizerTest, skip_middle_tokens)
TEST (TokenizerTest, skip_end_tokens)
TEST (TokenizerTest, token_from_colon_separated_string)
TEST (TokenizerTest, get_second_TokenAndRest)
Function Documentation
TEST() [1/10]
TEST (TokenizerTest , construction)
Definition at line 4 of file TestTokenizer.cpp.
 {
     infra::BoundedConstString string = "abcd efgh";
     infra::Tokenizer tokenizer(string, ' ');
 }
TEST() [2/10]
TEST (TokenizerTest , get_single_token)
Definition at line 10 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "abcd";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("abcd", tokenizer.Token(0));
 }
TEST() [3/10]
TEST (TokenizerTest , get_token_out_of_many)
Definition at line 18 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "abcd defg hijk";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("abcd", tokenizer.Token(0));
     EXPECT_EQ("defg", tokenizer.Token(1));
     EXPECT_EQ("hijk", tokenizer.Token(2));
 }
TEST() [4/10]
TEST (TokenizerTest , get_number_of_tokens)
Definition at line 28 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Size().
 {
     infra::BoundedConstString string = "abcd defg hijk";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ(3, tokenizer.Size());
 }
TEST() [5/10]
TEST (TokenizerTest , nonexisting_token_is_empty)
Definition at line 36 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "abcd defg hijk";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("", tokenizer.Token(3));
     EXPECT_EQ("", tokenizer.Token(4));
 }
TEST() [6/10]
TEST (TokenizerTest , skip_leading_tokens)
Definition at line 45 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "  abcd defg hijk";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("abcd", tokenizer.Token(0));
 }
TEST() [7/10]
TEST (TokenizerTest , skip_middle_tokens)
Definition at line 53 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "  abcd    defg hijk";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("defg", tokenizer.Token(1));
 }
TEST() [8/10]
TEST (TokenizerTest , skip_end_tokens)
Definition at line 61 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "abcd defg hijk  ";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("", tokenizer.Token(3));
 }
TEST() [9/10]
TEST (TokenizerTest , token_from_colon_separated_string)
Definition at line 69 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::Token().
 {
     infra::BoundedConstString string = "abcd:defg:hijk";
     infra::Tokenizer tokenizer(string, ':');
     EXPECT_EQ("defg", tokenizer.Token(1));
 }
TEST() [10/10]
TEST (TokenizerTest , get_second_TokenAndRest)
Definition at line 77 of file TestTokenizer.cpp.
References EXPECT_EQ(), and infra::Tokenizer::TokenAndRest().
 {
     infra::BoundedConstString string = "abcd defg hijk";
     infra::Tokenizer tokenizer(string, ' ');
     EXPECT_EQ("defg hijk", tokenizer.TokenAndRest(1));
     EXPECT_EQ("", tokenizer.TokenAndRest(3));
 }