EMil: infra::TimerSingleShot Class Reference
infra::TimerSingleShot Class Reference
#include <Timer.hpp>
Public Member Functions
TimerSingleShot (uint32_t timerServiceId=systemTimerServiceId)
TimerSingleShot (Duration duration, const infra::Function< void()> &action, uint32_t timerServiceId=systemTimerServiceId)
void Start (TimePoint time, const infra::Function< void()> &action)
void Start (Duration duration, const infra::Function< void()> &action)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
virtual const infra::Function< void()> & Action () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 74 of file Timer.hpp.
Constructor & Destructor Documentation
TimerSingleShot() [1/2]
infra::TimerSingleShot::TimerSingleShot (uint32_t timerServiceId = systemTimerServiceId) explicit
Definition at line 99 of file Timer.cpp.
         : Timer(timerServiceId)
     {}
TimerSingleShot() [2/2]
infra::TimerSingleShot::TimerSingleShot (Duration duration, const infra::Function< void()> & action, uint32_t timerServiceId = systemTimerServiceId)
Definition at line 103 of file Timer.cpp.
References Start().
         : Timer(timerServiceId)
     {
         Start(duration, aAction);
     }
Member Function Documentation
ComputeNextTriggerTime()
void infra::TimerSingleShot::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 119 of file Timer.cpp.
References infra::Timer::Cancel().
     {
         Cancel();
     }
Start() [1/2]
void infra::TimerSingleShot::Start (TimePoint time, const infra::Function< void()> & action)
Definition at line 109 of file Timer.cpp.
References infra::Timer::action, infra::Timer::Resolution(), and infra::Timer::SetNextTriggerTime().
Referenced by services::DebouncedButton::ButtonPressed(), services::RepeatingButton::ButtonPressed(), services::DebouncedButton::ButtonReleased(), services::NameResolverCache::Cleanup(), services::HttpClientBasic::ConnectionEstablished(), services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll(), services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q(), services::FlashSpi::HoldWhileWriteInProgress(), infra::ScalableDerivedTimerService::NextTriggerChanged(), infra::DerivedTimerService::NextTriggerChanged(), and TimerSingleShot().
     {
         SetNextTriggerTime(time + Resolution(), action);
     }
Start() [2/2]
void infra::TimerSingleShot::Start (Duration duration, const infra::Function< void()> & action)
Definition at line 114 of file Timer.cpp.
References infra::Timer::action, infra::Timer::Now(), infra::Timer::Resolution(), and infra::Timer::SetNextTriggerTime().
     {
         SetNextTriggerTime(Now() + duration + Resolution(), action);
     }
The documentation for this class was generated from the following files:
Timer.hpp
Timer.cpp