EMil: application::InputBinary Class Reference
application::InputBinary Class Reference
#include <InputBinary.hpp>
Public Member Functions
InputBinary (const std::string &targetName, const std::string &fileName, uint32_t destinationAddress, hal::FileSystem &fileSystem, const ImageSecurity &imageSecurity)
InputBinary (const std::string &targetName, const std::vector< uint8_t > &contents, uint32_t destinationAddress, const ImageSecurity &imageSecurity)
virtual std::vector< uint8_t > Image () const override
Public Member Functions inherited from application::Input
Input (const std::string &targetName)
virtual ~Input ()=default
std::string TargetName () const
Private Attributes
uint32_t destinationAddress
const ImageSecurity & imageSecurity
std::vector< uint8_t > image
Detailed Description
Definition at line 11 of file InputBinary.hpp.
Constructor & Destructor Documentation
InputBinary() [1/2]
application::InputBinary::InputBinary (const std::string & targetName, const std::string & fileName, uint32_t destinationAddress, hal::FileSystem & fileSystem, const ImageSecurity & imageSecurity)
Definition at line 6 of file InputBinary.cpp.
         : Input(targetName)
         , destinationAddress(destinationAddress)
         , imageSecurity(imageSecurity)
         , image(fileSystem.ReadBinaryFile(fileName))
     {}
InputBinary() [2/2]
application::InputBinary::InputBinary (const std::string & targetName, const std::vector< uint8_t > & contents, uint32_t destinationAddress, const ImageSecurity & imageSecurity)
Definition at line 14 of file InputBinary.cpp.
         : Input(targetName)
         , destinationAddress(destinationAddress)
         , imageSecurity(imageSecurity)
         , image(contents)
     {}
Member Function Documentation
Image()
std::vector< uint8_t > application::InputBinary::Image () const override virtual
Implements application::Input.
Definition at line 22 of file InputBinary.cpp.
References destinationAddress, application::ImageSecurity::EncryptionAndMacMethod(), image, imageSecurity, application::ImageSecurity::Secure(), application::Input::TargetName(), and application::Input::targetName.
     {
         std::string targetName(TargetName());
         std::vector<uint8_t> result;
         result.insert(result.end(), reinterpret_cast<const uint8_t*>(targetName.data()), reinterpret_cast<const uint8_t*>(targetName.data() + targetName.size()));
         result.insert(result.end(), 8 - targetName.size(), 0);
         uint32_t encryptionAndMacMethod = imageSecurity.EncryptionAndMacMethod();
         result.insert(result.end(), reinterpret_cast<const uint8_t*>(&encryptionAndMacMethod), reinterpret_cast<const uint8_t*>(&encryptionAndMacMethod + 1));
         std::vector<uint8_t> unencryptedImage;
         unencryptedImage.insert(unencryptedImage.end(), reinterpret_cast<const uint8_t*>(&destinationAddress), reinterpret_cast<const uint8_t*>(&destinationAddress + 1));
         uint32_t imageSize = image.size();
         unencryptedImage.insert(unencryptedImage.end(), reinterpret_cast<const uint8_t*>(&imageSize), reinterpret_cast<const uint8_t*>(&imageSize + 1));
         unencryptedImage.insert(unencryptedImage.end(), image.begin(), image.end());
         std::vector<uint8_t> encryptedImage = imageSecurity.Secure(unencryptedImage);
         result.insert(result.end(), encryptedImage.begin(), encryptedImage.end());
         uint32_t size = result.size() + sizeof(size);
         result.insert(result.begin(), reinterpret_cast<const uint8_t*>(&size), reinterpret_cast<const uint8_t*>(&size + 1));
         return result;
     }
Member Data Documentation
destinationAddress
uint32_t application::InputBinary::destinationAddress private
Definition at line 23 of file InputBinary.hpp.
Referenced by Image().
image
std::vector<uint8_t> application::InputBinary::image private
Definition at line 25 of file InputBinary.hpp.
Referenced by Image().
imageSecurity
const ImageSecurity& application::InputBinary::imageSecurity private
Definition at line 24 of file InputBinary.hpp.
Referenced by Image().
The documentation for this class was generated from the following files:
InputBinary.hpp
InputBinary.cpp