EMil: infra::TimerAlternating Class Reference
infra::TimerAlternating Class Reference
#include <TimerAlternating.hpp>
Public Member Functions
TimerAlternating (uint32_t timerServiceId=systemTimerServiceId)
TimerAlternating (Duration duration1, const infra::Function< void()> &aAction1, Duration duration2, const infra::Function< void()> &aAction2, uint32_t timerServiceId=systemTimerServiceId)
void Start (Duration duration1, const infra::Function< void()> &aAction1, Duration duration2, const infra::Function< void()> &aAction2)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual const infra::Function< void()> & Action () const override
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Attributes
std::array< Duration, 2 > durations = {}
std::array< infra::Function< void()>, 2 > scheduledTriggers
std::size_t index
TimePoint triggerStart
Detailed Description
Definition at line 11 of file TimerAlternating.hpp.
Constructor & Destructor Documentation
TimerAlternating() [1/2]
infra::TimerAlternating::TimerAlternating (uint32_t timerServiceId = systemTimerServiceId) explicit
Definition at line 5 of file TimerAlternating.cpp.
         : Timer(timerServiceId)
         , index(0)
     {}
TimerAlternating() [2/2]
infra::TimerAlternating::TimerAlternating (Duration duration1, const infra::Function< void()> & aAction1, Duration duration2, const infra::Function< void()> & aAction2, uint32_t timerServiceId = systemTimerServiceId)
Definition at line 10 of file TimerAlternating.cpp.
References Start().
         : Timer(timerServiceId)
     {
         Start(duration1, aAction1, duration2, aAction2);
     }
Member Function Documentation
Action()
const infra::Function< void()> & infra::TimerAlternating::Action () const override protected virtual
Reimplemented from infra::Timer.
Definition at line 29 of file TimerAlternating.cpp.
References index, and scheduledTriggers.
     {
         return scheduledTriggers[index];
     }
ComputeNextTriggerTime()
void infra::TimerAlternating::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 34 of file TimerAlternating.cpp.
References durations, infra::emptyFunction, index, infra::Timer::SetNextTriggerTime(), and triggerStart.
Referenced by Start().
     {
         index = (index + 1) & 1;
         triggerStart += durations[index];
         SetNextTriggerTime(triggerStart, infra::emptyFunction);     // Dummy function, this is overruled in Action()
     }
Start()
void infra::TimerAlternating::Start (Duration duration1, const infra::Function< void()> & aAction1, Duration duration2, const infra::Function< void()> & aAction2)
Definition at line 16 of file TimerAlternating.cpp.
References ComputeNextTriggerTime(), durations, index, infra::Timer::Now(), infra::Timer::Resolution(), scheduledTriggers, and triggerStart.
Referenced by TimerAlternating().
     {
         index = 1;
         triggerStart = Now() + Resolution();
         durations[0] = duration1;
         durations[1] = duration2;
         scheduledTriggers[0] = aAction1;
         scheduledTriggers[1] = aAction2;
         ComputeNextTriggerTime();
     }
Member Data Documentation
durations
std::array<Duration, 2> infra::TimerAlternating::durations = {} private
Definition at line 25 of file TimerAlternating.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
index
std::size_t infra::TimerAlternating::index private
Definition at line 27 of file TimerAlternating.hpp.
Referenced by Action(), ComputeNextTriggerTime(), and Start().
scheduledTriggers
std::array<infra::Function<void()>, 2> infra::TimerAlternating::scheduledTriggers private
Definition at line 26 of file TimerAlternating.hpp.
Referenced by Action(), and Start().
triggerStart
TimePoint infra::TimerAlternating::triggerStart private
Definition at line 29 of file TimerAlternating.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
The documentation for this class was generated from the following files:
TimerAlternating.hpp
TimerAlternating.cpp