EMil: services::RepeatingButton::FireTimer Class Reference
services::RepeatingButton::FireTimer Class Reference
#include <RepeatingButton.hpp>
Public Member Functions
FireTimer (uint32_t timerServiceId=infra::systemTimerServiceId)
void Start (infra::Duration initialDelay, infra::Duration successiveDelay, const infra::Function< void()> &action)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
virtual const infra::Function< void()> & Action () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Attributes
infra::Duration initialDelay = infra::Duration()
infra::Duration successiveDelay = infra::Duration()
infra::TimePoint triggerStart
Detailed Description
Definition at line 23 of file RepeatingButton.hpp.
Constructor & Destructor Documentation
FireTimer()
services::RepeatingButton::FireTimer::FireTimer (uint32_t timerServiceId = infra::systemTimerServiceId) explicit
Definition at line 51 of file RepeatingButton.cpp.
         : infra::Timer(timerServiceId)
     {}
Member Function Documentation
ComputeNextTriggerTime()
void services::RepeatingButton::FireTimer::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 63 of file RepeatingButton.cpp.
References infra::Now().
     {
         SetNextTriggerTime(Now() + successiveDelay, Action());
     }
Start()
void services::RepeatingButton::FireTimer::Start (infra::Duration initialDelay, infra::Duration successiveDelay, const infra::Function< void()> & action)
Definition at line 55 of file RepeatingButton.cpp.
References infra::Now().
Referenced by services::RepeatingButton::ButtonPressed().
     {
         this->initialDelay = initialDelay;
         this->successiveDelay = successiveDelay;
         SetNextTriggerTime(Now() + initialDelay, action);
         Action()();
     }
Member Data Documentation
initialDelay
infra::Duration services::RepeatingButton::FireTimer::initialDelay = infra::Duration() private
Definition at line 35 of file RepeatingButton.hpp.
successiveDelay
infra::Duration services::RepeatingButton::FireTimer::successiveDelay = infra::Duration() private
Definition at line 36 of file RepeatingButton.hpp.
triggerStart
infra::TimePoint services::RepeatingButton::FireTimer::triggerStart private
Definition at line 37 of file RepeatingButton.hpp.
The documentation for this class was generated from the following files:
RepeatingButton.hpp
RepeatingButton.cpp