EMil: TestBoundedDequeInputStream.cpp File Reference
TestBoundedDequeInputStream.cpp File Reference
Classes
class BoundedDequeInputStreamReaderTest
Functions
TEST_F (BoundedDequeInputStreamReaderTest, construction)
TEST_F (BoundedDequeInputStreamReaderTest, Extract)
TEST_F (BoundedDequeInputStreamReaderTest, Peek)
TEST_F (BoundedDequeInputStreamReaderTest, ExtractContiguousRange)
TEST_F (BoundedDequeInputStreamReaderTest, PeekContiguousRange)
TEST_F (BoundedDequeInputStreamReaderTest, ExtractContiguousRange_limited_by_max)
TEST_F (BoundedDequeInputStreamReaderTest, Rewind)
TEST (BoundedDequeInputStreamTest, construct_with_range)
TEST (BoundedDequeInputStreamTest, construct_softFail_with_range)
TEST (BoundedDequeInputStreamTest, construct_noFail_with_range)
Function Documentation
TEST() [1/3]
TEST (BoundedDequeInputStreamTest , construct_with_range)
Definition at line 73 of file TestBoundedDequeInputStream.cpp.
References infra::InputStream::ContiguousRange(), data, and EXPECT_EQ().
 {
     infra::BoundedDeque<uint8_t>::WithMaxSize<4> data{ std::initializer_list<uint8_t>{1, 2, 3, 4} };
     infra::BoundedDequeInputStream stream(data);
     EXPECT_EQ((std::array<uint8_t, 4>{{1, 2, 3, 4}}), stream.ContiguousRange(16));
 }
TEST() [2/3]
TEST (BoundedDequeInputStreamTest , construct_softFail_with_range)
Definition at line 80 of file TestBoundedDequeInputStream.cpp.
References infra::InputStream::ContiguousRange(), data, EXPECT_EQ(), and infra::softFail.
 {
     infra::BoundedDeque<uint8_t>::WithMaxSize<4> data{ std::initializer_list<uint8_t>{1, 2, 3, 4} };
     infra::BoundedDequeInputStream stream(data, infra::softFail);
     EXPECT_EQ((std::array<uint8_t, 4>{{1, 2, 3, 4}}), stream.ContiguousRange(16));
 }
TEST() [3/3]
TEST (BoundedDequeInputStreamTest , construct_noFail_with_range)
Definition at line 87 of file TestBoundedDequeInputStream.cpp.
References infra::InputStream::ContiguousRange(), data, EXPECT_EQ(), and infra::noFail.
 {
     infra::BoundedDeque<uint8_t>::WithMaxSize<4> data{ std::initializer_list<uint8_t>{ 1, 2, 3, 4 } };
     infra::BoundedDequeInputStream stream(data, infra::noFail);
     EXPECT_EQ((std::array<uint8_t, 4>{ {1, 2, 3, 4}}), stream.ContiguousRange(16));
 }
TEST_F() [1/7]
TEST_F (BoundedDequeInputStreamReaderTest , construction)
Definition at line 22 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     EXPECT_FALSE(reader.Empty());
     EXPECT_EQ(8, reader.Available());
 }
TEST_F() [2/7]
TEST_F (BoundedDequeInputStreamReaderTest , Extract)
Definition at line 28 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ().
 {
     std::array<uint8_t, 4> result;
     reader.Extract(result, errorPolicy);
     EXPECT_EQ((std::array<uint8_t, 4>{ {1, 2, 3, 4} }), result);
     reader.Extract(result, errorPolicy);
     EXPECT_EQ((std::array<uint8_t, 4>{ {5, 6, 7, 8} }), result);
 }
TEST_F() [3/7]
TEST_F (BoundedDequeInputStreamReaderTest , Peek)
Definition at line 38 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(1, reader.Peek(errorPolicy));
 }
TEST_F() [4/7]
TEST_F (BoundedDequeInputStreamReaderTest , ExtractContiguousRange)
Definition at line 43 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ((std::array<uint8_t, 6>{ {1, 2, 3, 4, 5, 6} }), reader.ExtractContiguousRange(16));
     EXPECT_EQ((std::array<uint8_t, 2>{ {7, 8} }), reader.ExtractContiguousRange(16));
 }
TEST_F() [5/7]
TEST_F (BoundedDequeInputStreamReaderTest , PeekContiguousRange)
Definition at line 49 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ((std::array<uint8_t, 6>{ {1, 2, 3, 4, 5, 6}}), reader.PeekContiguousRange(0));
     EXPECT_EQ((std::array<uint8_t, 2>{ {7, 8}}), reader.PeekContiguousRange(6));
     reader.ExtractContiguousRange(2);
     EXPECT_EQ((std::array<uint8_t, 4>{ {3, 4, 5, 6}}), reader.PeekContiguousRange(0));
 }
TEST_F() [6/7]
TEST_F (BoundedDequeInputStreamReaderTest , ExtractContiguousRange_limited_by_max)
Definition at line 58 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ((std::array<uint8_t, 2>{ {1, 2} }), reader.ExtractContiguousRange(2));
 }
TEST_F() [7/7]
TEST_F (BoundedDequeInputStreamReaderTest , Rewind)
Definition at line 63 of file TestBoundedDequeInputStream.cpp.
References EXPECT_EQ().
 {
     reader.ExtractContiguousRange(2);
     auto marker = reader.ConstructSaveMarker();
     reader.ExtractContiguousRange(2);
     reader.Rewind(marker);
     EXPECT_EQ((std::array<uint8_t, 2>{ {3, 4}}), reader.ExtractContiguousRange(2));
 }