EMil: infra::JsonArray Class Reference
infra::JsonArray Class Reference
#include <Json.hpp>
Public Member Functions
JsonArray ()=default
JsonArray (infra::BoundedConstString objectString)
infra::BoundedConstString ObjectString () const
JsonArrayIterator begin ()
JsonArrayIterator end ()
bool operator== (const JsonArray &other) const
bool operator!= (const JsonArray &other) const
void SetError ()
bool Error () const
Private Attributes
infra::BoundedConstString objectString
bool error = false
Detailed Description
Definition at line 284 of file Json.hpp.
Constructor & Destructor Documentation
JsonArray() [1/2]
infra::JsonArray::JsonArray () default
JsonArray() [2/2]
infra::JsonArray::JsonArray (infra::BoundedConstString objectString) explicit
Definition at line 721 of file Json.cpp.
         : objectString(objectString)
     {}
Member Function Documentation
begin()
JsonArrayIterator infra::JsonArray::begin ()
Definition at line 740 of file Json.cpp.
Referenced by infra::JsonArrayArray(), infra::JsonBooleanArray(), infra::JsonIntegerArray(), infra::JsonObjectArray(), infra::JsonStringArray(), and operator==().
     {
         return JsonArrayIterator(*this);
     }
end()
JsonArrayIterator infra::JsonArray::end ()
Definition at line 745 of file Json.cpp.
Referenced by infra::JsonArrayArray(), infra::JsonBooleanArray(), infra::JsonIntegerArray(), infra::JsonObjectArray(), infra::JsonStringArray(), and operator==().
     {
         return JsonArrayIterator();
     }
Error()
bool infra::JsonArray::Error () const
Definition at line 735 of file Json.cpp.
References error.
Referenced by operator==().
     {
         return error;
     }
ObjectString()
infra::BoundedConstString infra::JsonArray::ObjectString () const
Definition at line 725 of file Json.cpp.
References objectString.
     {
         return objectString;
     }
operator!=()
bool infra::JsonArray::operator!= (const JsonArray & other) const
Definition at line 759 of file Json.cpp.
     {
         return !(*this == other);
     }
operator==()
bool infra::JsonArray::operator== (const JsonArray & other) const
Definition at line 750 of file Json.cpp.
References begin(), end(), and Error().
     {
         JsonArray left(*this);
         JsonArray right(other);
         bool result = Equal(left.begin(), left.end(), right.begin(), right.end());
         return result && !left.Error() && !right.Error();
     }
SetError()
void infra::JsonArray::SetError ()
Definition at line 730 of file Json.cpp.
References error.
Referenced by infra::JsonArrayIterator::SetError().
     {
         error = true;
     }
Member Data Documentation
error
bool infra::JsonArray::error = false private
Definition at line 304 of file Json.hpp.
Referenced by Error(), and SetError().
objectString
infra::BoundedConstString infra::JsonArray::objectString private
Definition at line 303 of file Json.hpp.
Referenced by ObjectString().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp