EMil: services::RepeatingButton Class Reference
services::RepeatingButton Class Reference
#include <RepeatingButton.hpp>
Classes
struct Config
class FireTimer
Public Member Functions
RepeatingButton (hal::GpioPin &buttonPin, infra::Function< void()> aCallback, const Config &config=Config())
Private Member Functions
void ButtonChanged ()
void ButtonPressed ()
void ButtonReleased ()
void DebounceEnd ()
Private Attributes
hal::InputPin buttonPin
Config config
bool previousButtonState
FireTimer repeatingFireTimer
infra::TimerSingleShot debounceEnd
infra::Function< void()> callback
Detailed Description
Definition at line 9 of file RepeatingButton.hpp.
Constructor & Destructor Documentation
RepeatingButton()
services::RepeatingButton::RepeatingButton (hal::GpioPin & buttonPin, infra::Function< void()> aCallback, const Config & config = Config())
Definition at line 6 of file RepeatingButton.cpp.
References hal::bothEdges, ButtonChanged(), and hal::GpioPin::EnableInterrupt().
         : buttonPin(buttonPin)
         , config(config)
         , previousButtonState(false)
         , callback(aCallback)
     {
         this->buttonPin.EnableInterrupt([this]() { ButtonChanged(); }, hal::InterruptTrigger::bothEdges);
     }
Member Function Documentation
ButtonChanged()
void services::RepeatingButton::ButtonChanged () private
Definition at line 15 of file RepeatingButton.cpp.
References buttonPin, ButtonPressed(), ButtonReleased(), hal::InputPin::Get(), and previousButtonState.
Referenced by RepeatingButton().
     {
         bool buttonState = buttonPin.Get();
         if (previousButtonState != buttonState)
         {
             if (buttonState)
                 ButtonPressed();
             else
                 ButtonReleased();
         }
         previousButtonState = buttonState;
     }
ButtonPressed()
void services::RepeatingButton::ButtonPressed () private
Definition at line 30 of file RepeatingButton.cpp.
References infra::Timer::Armed(), config, services::RepeatingButton::Config::debounceDuration, debounceEnd, services::RepeatingButton::Config::initialDelay, repeatingFireTimer, services::RepeatingButton::FireTimer::Start(), infra::TimerSingleShot::Start(), and services::RepeatingButton::Config::successiveDelay.
Referenced by ButtonChanged().
     {
         if (!debounceEnd.Armed())
         {
             debounceEnd.Start(config.debounceDuration, [this]() { DebounceEnd(); });
             repeatingFireTimer.Start(config.initialDelay, config.successiveDelay, [this]() { callback(); });
         }
     }
ButtonReleased()
void services::RepeatingButton::ButtonReleased () private
Definition at line 39 of file RepeatingButton.cpp.
References infra::Timer::Armed(), infra::Timer::Cancel(), debounceEnd, and repeatingFireTimer.
Referenced by ButtonChanged().
     {
         if (!debounceEnd.Armed())
             repeatingFireTimer.Cancel();
     }
DebounceEnd()
void services::RepeatingButton::DebounceEnd () private
Definition at line 45 of file RepeatingButton.cpp.
References buttonPin, infra::Timer::Cancel(), hal::InputPin::Get(), and repeatingFireTimer.
     {
         if (!buttonPin.Get())
             repeatingFireTimer.Cancel();
     }
Member Data Documentation
buttonPin
hal::InputPin services::RepeatingButton::buttonPin private
Definition at line 47 of file RepeatingButton.hpp.
Referenced by ButtonChanged(), and DebounceEnd().
callback
infra::Function<void()> services::RepeatingButton::callback private
Definition at line 52 of file RepeatingButton.hpp.
config
Config services::RepeatingButton::config private
Definition at line 48 of file RepeatingButton.hpp.
Referenced by ButtonPressed().
debounceEnd
infra::TimerSingleShot services::RepeatingButton::debounceEnd private
Definition at line 51 of file RepeatingButton.hpp.
Referenced by ButtonPressed(), and ButtonReleased().
previousButtonState
bool services::RepeatingButton::previousButtonState private
Definition at line 49 of file RepeatingButton.hpp.
Referenced by ButtonChanged().
repeatingFireTimer
FireTimer services::RepeatingButton::repeatingFireTimer private
Definition at line 50 of file RepeatingButton.hpp.
Referenced by ButtonPressed(), ButtonReleased(), and DebounceEnd().
The documentation for this class was generated from the following files:
RepeatingButton.hpp
RepeatingButton.cpp