EMil: services::DnsResolver::HostnamePartsStream Class Reference
services::DnsResolver::HostnamePartsStream Class Reference
Public Member Functions
HostnamePartsStream (infra::StreamReaderWithRewinding &reader, uint32_t streamPosition)
virtual infra::BoundedConstString Current () const override
virtual void ConsumeCurrent () override
virtual bool Empty () const override
Private Member Functions
void ReadNext ()
Private Attributes
infra::StreamReaderWithRewinding & reader
uint32_t streamPosition
infra::DataInputStream::WithErrorPolicy stream
infra::BoundedString::WithStorage< 63 > label
Additional Inherited Members
Protected Member Functions inherited from services::DnsResolver::HostnameParts
HostnameParts ()=default
HostnameParts (const HostnameParts &other)=delete
HostnameParts & operator= (const HostnameParts &other)=delete
~HostnameParts ()=default
Detailed Description
Definition at line 117 of file DnsResolver.hpp.
Constructor & Destructor Documentation
HostnamePartsStream()
services::DnsResolver::HostnamePartsStream::HostnamePartsStream (infra::StreamReaderWithRewinding & reader, uint32_t streamPosition)
Definition at line 558 of file DnsResolver.cpp.
References ReadNext().
         : reader(reader)
         , streamPosition(streamPosition)
         , stream(reader, infra::noFail)
     {
         ReadNext();
     }
Member Function Documentation
ConsumeCurrent()
void services::DnsResolver::HostnamePartsStream::ConsumeCurrent () override virtual
Implements services::DnsResolver::HostnameParts.
Definition at line 571 of file DnsResolver.cpp.
     {
         ReadNext();
     }
Current()
infra::BoundedConstString services::DnsResolver::HostnamePartsStream::Current () const override virtual
Implements services::DnsResolver::HostnameParts.
Definition at line 566 of file DnsResolver.cpp.
     {
         return label;
     }
Empty()
bool services::DnsResolver::HostnamePartsStream::Empty () const override virtual
Implements services::DnsResolver::HostnameParts.
Definition at line 576 of file DnsResolver.cpp.
     {
         return label.empty();
     }
ReadNext()
void services::DnsResolver::HostnamePartsStream::ReadNext () private
Definition at line 581 of file DnsResolver.cpp.
References infra::StringAsByteRange().
Referenced by HostnamePartsStream().
     {
         label.clear();
         auto save = reader.ConstructSaveMarker();
         reader.Rewind(streamPosition);
         if (!stream.Empty())
         {
             auto size = stream.Extract<uint8_t>();
             while ((size & 0xc0) == 0xc0)
             {
                 uint8_t offsetHigh = size & 0x3f;
                 auto offsetLow = stream.Extract<uint8_t>();
                 uint16_t offset = offsetLow + (offsetHigh << 8);
                 size = 0;
                 auto currentPosition = reader.ConstructSaveMarker();
                 if (currentPosition <= offset)
                     break;
                 reader.Rewind(offset);
                 size = stream.Extract<uint8_t>();
             }
             if (size <= label.max_size())
             {
                 label.resize(size);
                 stream >> infra::StringAsByteRange(label);
             }
         }
         streamPosition = reader.ConstructSaveMarker();
         reader.Rewind(save);
     }
Member Data Documentation
label
infra::BoundedString::WithStorage<63> services::DnsResolver::HostnamePartsStream::label private
Definition at line 134 of file DnsResolver.hpp.
reader
infra::StreamReaderWithRewinding& services::DnsResolver::HostnamePartsStream::reader private
Definition at line 131 of file DnsResolver.hpp.
stream
infra::DataInputStream::WithErrorPolicy services::DnsResolver::HostnamePartsStream::stream private
Definition at line 133 of file DnsResolver.hpp.
streamPosition
uint32_t services::DnsResolver::HostnamePartsStream::streamPosition private
Definition at line 132 of file DnsResolver.hpp.
The documentation for this class was generated from the following files:
DnsResolver.hpp
DnsResolver.cpp