EMil: services::HttpPageServer Class Reference
services::HttpPageServer Class Reference
#include <HttpServer.hpp>
Public Member Functions
HttpPageServer ()=default
HttpPageServer (const HttpPageServer &other)=delete
HttpPageServer & operator= (const HttpPageServer &other)=delete
~HttpPageServer ()=default
virtual HttpPage * PageForRequest (const HttpRequestParser &request)
void AddPage (services::HttpPage &page)
Private Attributes
infra::IntrusiveForwardList< services::HttpPage > pages
Detailed Description
Definition at line 15 of file HttpServer.hpp.
Constructor & Destructor Documentation
HttpPageServer() [1/2]
services::HttpPageServer::HttpPageServer () default
HttpPageServer() [2/2]
services::HttpPageServer::HttpPageServer (const HttpPageServer & other) delete
~HttpPageServer()
services::HttpPageServer::~HttpPageServer () default
Member Function Documentation
AddPage()
void services::HttpPageServer::AddPage (services::HttpPage & page)
Definition at line 9 of file HttpServer.cpp.
References pages, and infra::IntrusiveForwardList< T >::push_front().
     {
         pages.push_front(page);
     }
operator=()
HttpPageServer& services::HttpPageServer::operator= (const HttpPageServer & other) delete
PageForRequest()
services::HttpPage * services::HttpPageServer::PageForRequest (const HttpRequestParser & request) virtual
Reimplemented in services::HttpServerConnectionObserver.
Definition at line 14 of file HttpServer.cpp.
References pages, and services::HttpRequestParser::PathTokens().
Referenced by services::HttpServerConnectionObserver::PageForRequest().
     {
         for (auto& page : pages)
             if (page.ServesRequest(request.PathTokens()))
                 return &page;
         return nullptr;
     }
Member Data Documentation
pages
infra::IntrusiveForwardList<services::HttpPage> services::HttpPageServer::pages private
Definition at line 28 of file HttpServer.hpp.
Referenced by AddPage(), and PageForRequest().
The documentation for this class was generated from the following files:
HttpServer.hpp
HttpServer.cpp