EMil: TestProtoParser.cpp File Reference
TestProtoParser.cpp File Reference
Functions
TEST (ProtoParserTest, GetVarInt_from_a_single_byte)
TEST (ProtoParserTest, GetVarInt_from_multiple_bytes)
TEST (ProtoParserTest, GetVarInt_largest)
TEST (ProtoParserTest, GetFixed32)
TEST (ProtoParserTest, GetFixed64)
TEST (ProtoParserTest, GetField_on_var_int_returns_uint64_t)
TEST (ProtoParserTest, GetField_on_fixed64_returns_uint64_t)
TEST (ProtoParserTest, GetField_on_fixed32_returns_uint32_t)
TEST (ProtoParserTest, GetField_returns_string)
TEST (ProtoParserTest, GetField_returns_bytes)
TEST (ProtoParserTest, GetField_returns_nested_object)
TEST (ProtoParserTest, SkipEverything_skips_LengthDelimited)
Function Documentation
TEST() [1/12]
TEST (ProtoParserTest , GetVarInt_from_a_single_byte)
Definition at line 5 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 1>{ 5 });
     infra::ProtoParser parser(stream);
     EXPECT_EQ(5, parser.GetVarInt());
 }
TEST() [2/12]
TEST (ProtoParserTest , GetVarInt_from_multiple_bytes)
Definition at line 13 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 2>{ 0x85, 3 });
     infra::ProtoParser parser(stream);
     EXPECT_EQ(389, parser.GetVarInt());
 }
TEST() [3/12]
TEST (ProtoParserTest , GetVarInt_largest)
Definition at line 21 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 10>{ 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 1 });
     infra::ProtoParser parser(stream);
     EXPECT_EQ(std::numeric_limits<uint64_t>::max(), parser.GetVarInt());
 }
TEST() [4/12]
TEST (ProtoParserTest , GetFixed32)
Definition at line 29 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 4>{ 1, 0, 0, 0 });
     infra::ProtoParser parser(stream);
     EXPECT_EQ(1, parser.GetFixed32());
 }
TEST() [5/12]
TEST (ProtoParserTest , GetFixed64)
Definition at line 37 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 8>{ 1, 0, 0, 0, 0, 0, 0, 0 });
     infra::ProtoParser parser(stream);
     EXPECT_EQ(1, parser.GetFixed64());
 }
TEST() [6/12]
TEST (ProtoParserTest , GetField_on_var_int_returns_uint64_t)
Definition at line 45 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 2>{ 1 << 3, 5 });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     EXPECT_EQ(5, field.first.Get<uint64_t>());
     EXPECT_EQ(1, field.second);
 }
TEST() [7/12]
TEST (ProtoParserTest , GetField_on_fixed64_returns_uint64_t)
Definition at line 55 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 9>{ (1 << 3) | 1, 5, 0, 0, 0, 0, 0, 0, 0 });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     EXPECT_EQ(5, field.first.Get<uint64_t>());
     EXPECT_EQ(1, field.second);
 }
TEST() [8/12]
TEST (ProtoParserTest , GetField_on_fixed32_returns_uint32_t)
Definition at line 65 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 5>{ (1 << 3) | 5, 5, 0, 0, 0 });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     EXPECT_EQ(5, field.first.Get<uint32_t>());
     EXPECT_EQ(1, field.second);
 }
TEST() [9/12]
TEST (ProtoParserTest , GetField_returns_string)
Definition at line 75 of file TestProtoParser.cpp.
References EXPECT_EQ(), and GetString().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 3>{ (1 << 3) | 2, 1, 'a' });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     infra::BoundedString::WithStorage<10> string;
     field.first.Get<infra::ProtoLengthDelimited>().GetString(string);
     EXPECT_EQ("a", string);
 }
TEST() [10/12]
TEST (ProtoParserTest , GetField_returns_bytes)
Definition at line 86 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 3>{ (1 << 3) | 2, 1, 5 });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     infra::BoundedVector<uint8_t>::WithMaxSize<10> bytes;
     field.first.Get<infra::ProtoLengthDelimited>().GetBytes(bytes);
     EXPECT_EQ(5, bytes.front());
 }
TEST() [11/12]
TEST (ProtoParserTest , GetField_returns_nested_object)
Definition at line 97 of file TestProtoParser.cpp.
References EXPECT_EQ(), and infra::ProtoParser::GetField().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 4>{ (1 << 3) | 2, 2, 1 << 3, 5 });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     infra::BoundedString::WithStorage<10> string;
     infra::ProtoParser nestedParser = field.first.Get<infra::ProtoLengthDelimited>().Parser();
     infra::ProtoParser::Field nestedField = nestedParser.GetField();
     EXPECT_EQ(5, nestedField.first.Get<uint64_t>());
     EXPECT_EQ(1, nestedField.second);
 }
TEST() [12/12]
TEST (ProtoParserTest , SkipEverything_skips_LengthDelimited)
Definition at line 110 of file TestProtoParser.cpp.
References EXPECT_EQ().
 {
     infra::ByteInputStream stream(std::array<uint8_t, 6>{ (1 << 3) | 2, 2, 1 << 3, 5, 1 << 3, 5 });
     infra::ProtoParser parser(stream);
     infra::ProtoParser::Field field = parser.GetField();
     infra::BoundedString::WithStorage<10> string;
     field.first.Get<infra::ProtoLengthDelimited>().SkipEverything();
     field = parser.GetField();
     EXPECT_EQ(5, field.first.Get<uint64_t>());
     EXPECT_EQ(1, field.second);
 }