EMil: services::MqttClientImpl::MqttFormatter Class Reference
services::MqttClientImpl::MqttFormatter Class Reference
Classes
struct InPlaceType
Public Member Functions
MqttFormatter (infra::DataOutputStream stream)
void MessageConnect (infra::BoundedConstString clientId, infra::BoundedConstString username, infra::BoundedConstString password)
void MessagePublish (infra::BoundedConstString topic, infra::BoundedConstString payload)
Static Public Member Functions
static std::size_t MessageSizeConnect (infra::BoundedConstString clientId, infra::BoundedConstString username, infra::BoundedConstString password)
static std::size_t MessageSizePublish (infra::BoundedConstString topic, infra::BoundedConstString payload)
Private Member Functions
void AddString (infra::BoundedConstString value)
void Header (PacketType packetType, std::size_t size, uint8_t flags=0)
uint8_t MakePacketType (PacketType packetType, uint8_t flags)
Static Private Member Functions
static std::size_t EncodedLength (infra::BoundedConstString value)
Private Attributes
infra::DataOutputStream stream
Detailed Description
Definition at line 46 of file MqttClientImpl.hpp.
Constructor & Destructor Documentation
MqttFormatter()
services::MqttClientImpl::MqttFormatter::MqttFormatter (infra::DataOutputStream stream)
Definition at line 5 of file MqttClientImpl.cpp.
         : stream(stream)
     {}
Member Function Documentation
AddString()
void services::MqttClientImpl::MqttFormatter::AddString (infra::BoundedConstString value) private
Definition at line 44 of file MqttClientImpl.cpp.
References infra::StringAsByteRange(), and value.
     {
         stream << BigEndianUint16(static_cast<uint16_t>(value.size())) << infra::StringAsByteRange(value);
     }
EncodedLength()
std::size_t services::MqttClientImpl::MqttFormatter::EncodedLength (infra::BoundedConstString value) static private
Definition at line 39 of file MqttClientImpl.cpp.
References value.
     {
         return 2 + value.size();
     }
Header()
void services::MqttClientImpl::MqttFormatter::Header (PacketType packetType, std::size_t size, uint8_t flags = 0) private
Definition at line 49 of file MqttClientImpl.cpp.
     {
         stream << MakePacketType(packetType, flags);
         while (size > 127)
         {
             stream << static_cast<uint8_t>((size & 0x7f) | 0x80);
             size >>= 7;
         }
         stream << static_cast<uint8_t>(size);
     }
MakePacketType()
uint8_t services::MqttClientImpl::MqttFormatter::MakePacketType (PacketType packetType, uint8_t flags) private
Definition at line 61 of file MqttClientImpl.cpp.
     {
         return static_cast<uint8_t>((static_cast<uint8_t>(packetType) << 4) | flags);
     }
MessageConnect()
void services::MqttClientImpl::MqttFormatter::MessageConnect (infra::BoundedConstString clientId, infra::BoundedConstString username, infra::BoundedConstString password)
Definition at line 9 of file MqttClientImpl.cpp.
References services::MqttClientImpl::packetTypeConnect.
Referenced by services::MqttClientImpl::StateConnecting::SendStreamAvailable().
     {
         PacketConnect packetHeader{};
         Header(PacketType::packetTypeConnect, sizeof(packetHeader) + EncodedLength(clientId) + EncodedLength(username) + EncodedLength(password));
         stream << packetHeader;
         AddString(clientId);
         AddString(username);
         AddString(password);
     }
MessagePublish()
void services::MqttClientImpl::MqttFormatter::MessagePublish (infra::BoundedConstString topic, infra::BoundedConstString payload)
Definition at line 24 of file MqttClientImpl.cpp.
References services::MqttClientImpl::packetTypePublish, infra::BoundedStringBase< T >::size(), and infra::StringAsByteRange().
Referenced by services::MqttClientImpl::StateConnected::SendStreamAvailable().
     {
         Header(PacketType::packetTypePublish, EncodedLength(topic) + payload.size() + 2, 2);
         AddString(topic);
         uint16_t packetIdentifier = 1;
         stream << BigEndianUint16(packetIdentifier);
         stream << infra::StringAsByteRange(payload);
     }
MessageSizeConnect()
std::size_t services::MqttClientImpl::MqttFormatter::MessageSizeConnect (infra::BoundedConstString clientId, infra::BoundedConstString username, infra::BoundedConstString password) static
Definition at line 19 of file MqttClientImpl.cpp.
Referenced by services::MqttClientImpl::StateConnecting::Connected().
     {
         return 5 + sizeof(PacketConnect) + EncodedLength(clientId) + EncodedLength(username) + EncodedLength(password);
     }
MessageSizePublish()
std::size_t services::MqttClientImpl::MqttFormatter::MessageSizePublish (infra::BoundedConstString topic, infra::BoundedConstString payload) static
Definition at line 34 of file MqttClientImpl.cpp.
References infra::BoundedStringBase< T >::size().
Referenced by services::MqttClientImpl::StateConnected::Publish().
     {
         return 5 + EncodedLength(topic) + payload.size();
     }
Member Data Documentation
stream
infra::DataOutputStream services::MqttClientImpl::MqttFormatter::stream private
Definition at line 67 of file MqttClientImpl.hpp.
The documentation for this class was generated from the following files:
MqttClientImpl.hpp
MqttClientImpl.cpp