EMil: services::MqttClientImpl::MqttParser Class Reference
services::MqttClientImpl::MqttParser Class Reference
Public Member Functions
MqttParser (infra::DataInputStream stream)
PacketType GetPacketType () const
Private Member Functions
void ExtractType ()
void ExtractSize ()
Private Attributes
infra::DataInputStream stream
PacketType packetType
uint32_t size = 0
Detailed Description
Definition at line 70 of file MqttClientImpl.hpp.
Constructor & Destructor Documentation
MqttParser()
services::MqttClientImpl::MqttParser::MqttParser (infra::DataInputStream stream)
Definition at line 66 of file MqttClientImpl.cpp.
References ExtractSize(), and ExtractType().
         : stream(stream)
     {
         ExtractType();
         ExtractSize();
     }
Member Function Documentation
ExtractSize()
void services::MqttClientImpl::MqttParser::ExtractSize () private
Definition at line 85 of file MqttClientImpl.cpp.
Referenced by MqttParser().
     {
         uint8_t sizeByte;
         uint8_t shift = 0;
         this->stream >> sizeByte;
         while (!stream.Failed() && sizeByte > 127)
         {
             size += sizeByte << shift;
             shift += 8;
             this->stream >> sizeByte;
         }
         size += sizeByte << shift;
     }
ExtractType()
void services::MqttClientImpl::MqttParser::ExtractType () private
Definition at line 78 of file MqttClientImpl.cpp.
Referenced by MqttParser().
     {
         uint8_t combinedPacketType;
         this->stream >> combinedPacketType;
         packetType = static_cast<PacketType>(combinedPacketType >> 4);
     }
GetPacketType()
MqttClientImpl::PacketType services::MqttClientImpl::MqttParser::GetPacketType () const
Definition at line 73 of file MqttClientImpl.cpp.
Referenced by services::MqttClientImpl::StateConnecting::DataReceived(), and services::MqttClientImpl::StateConnected::DataReceived().
     {
         return packetType;
     }
Member Data Documentation
packetType
PacketType services::MqttClientImpl::MqttParser::packetType private
Definition at line 83 of file MqttClientImpl.hpp.
size
uint32_t services::MqttClientImpl::MqttParser::size = 0 private
Definition at line 84 of file MqttClientImpl.hpp.
stream
infra::DataInputStream services::MqttClientImpl::MqttParser::stream private
Definition at line 82 of file MqttClientImpl.hpp.
The documentation for this class was generated from the following files:
MqttClientImpl.hpp
MqttClientImpl.cpp