EMil: hal::I2cMaster Class Reference
hal::I2cMaster Class Reference abstract
#include <I2c.hpp>
Public Member Functions
I2cMaster ()=default
I2cMaster (const I2cMaster &other)=delete
I2cMaster & operator= (const I2cMaster &other)=delete
virtual void SendData (I2cAddress address, infra::ConstByteRange data, Action nextAction, infra::Function< void(Result, uint32_t numberOfBytesSent)> onSent)=0
virtual void ReceiveData (I2cAddress address, infra::ByteRange data, Action nextAction, infra::Function< void(Result)> onReceived)=0
Protected Member Functions
~I2cMaster ()=default
Detailed Description
Definition at line 40 of file I2c.hpp.
Constructor & Destructor Documentation
I2cMaster() [1/2]
hal::I2cMaster::I2cMaster () default
I2cMaster() [2/2]
hal::I2cMaster::I2cMaster (const I2cMaster & other) delete
~I2cMaster()
hal::I2cMaster::~I2cMaster () protected default
Member Function Documentation
operator=()
I2cMaster& hal::I2cMaster::operator= (const I2cMaster & other) delete
ReceiveData()
virtual void hal::I2cMaster::ReceiveData (I2cAddress address, infra::ByteRange data, Action nextAction, infra::Function< void(Result)> onReceived) pure virtual
Implemented in services::I2cMultipleAccess, and services::I2cMultipleAccessMaster.
Referenced by hal::I2cMasterRegisterAccess::ReadRegister(), and services::I2cMultipleAccessMaster::ReceiveData().
SendData()
virtual void hal::I2cMaster::SendData (I2cAddress address, infra::ConstByteRange data, Action nextAction, infra::Function< void(Result, uint32_t numberOfBytesSent)> onSent) pure virtual
Implemented in services::I2cMultipleAccess, and services::I2cMultipleAccessMaster.
Referenced by hal::I2cMasterRegisterAccess::ReadRegister(), services::I2cMultipleAccessMaster::SendData(), and hal::I2cMasterRegisterAccess::WriteRegister().
The documentation for this class was generated from the following file:
I2c.hpp