EMil: TestMacAddress.cpp File Reference
TestMacAddress.cpp File Reference
Functions
TEST (MacAddressTest, toStream)
Function Documentation
TEST()
TEST (MacAddressTest , toStream)
Definition at line 5 of file TestMacAddress.cpp.
References infra::AsMacAddress(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     const hal::MacAddress mac = {0x12, 0x23, 0x34, 0x45, 0x56, 0x67};
     stream << infra::AsMacAddress(mac);
     EXPECT_EQ("12:23:34:45:56:67", stream.Storage());
 }