EMil: hal::SpiAsynchronousMock Class Reference
hal::SpiAsynchronousMock Class Reference
#include <SpiMock.hpp>
Public Member Functions
virtual void SetChipSelectConfigurator (ChipSelectConfigurator &configurator) override
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> &onDone) override
MOCK_METHOD4 (SendAndReceiveMock, void(std::vector< uint8_t > sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> &onDone))
MOCK_METHOD1 (SetChipSelectConfiguratorMock, void(ChipSelectConfigurator &configurator))
MOCK_METHOD1 (SetCommunicationConfigurator, void(CommunicationConfigurator &configurator))
MOCK_METHOD0 (ResetCommunicationConfigurator, void())
Public Member Functions inherited from hal::SpiMaster
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
virtual void SetCommunicationConfigurator (CommunicationConfigurator &configurator)=0
virtual void ResetCommunicationConfigurator ()=0
Public Attributes
infra::Function< void()> onDone
bool scheduleActionCompleteAutomatically = true
hal::ChipSelectConfigurator * chipSelectConfigurator = nullptr
Additional Inherited Members
Protected Member Functions inherited from hal::SpiMaster
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Detailed Description
Definition at line 28 of file SpiMock.hpp.
Member Function Documentation
MOCK_METHOD0()
hal::SpiAsynchronousMock::MOCK_METHOD0 (ResetCommunicationConfigurator , void())
MOCK_METHOD1() [1/2]
hal::SpiAsynchronousMock::MOCK_METHOD1 (SetChipSelectConfiguratorMock , void(ChipSelectConfigurator &configurator))
MOCK_METHOD1() [2/2]
hal::SpiAsynchronousMock::MOCK_METHOD1 (SetCommunicationConfigurator , void(CommunicationConfigurator &configurator))
MOCK_METHOD4()
hal::SpiAsynchronousMock::MOCK_METHOD4 (SendAndReceiveMock , void(std::vector< uint8_t > sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> &onDone))
SendAndReceive()
void hal::SpiAsynchronousMock::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> & onDone) override virtual
Implements hal::SpiMaster.
Definition at line 26 of file SpiMock.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and onDone.
     {
         this->onDone = onDone;
         SendAndReceiveMock(std::vector<uint8_t>(sendData.begin(), sendData.end()), receiveData, nextAction, onDone);
     }
SetChipSelectConfigurator()
void hal::SpiAsynchronousMock::SetChipSelectConfigurator (ChipSelectConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 20 of file SpiMock.cpp.
References chipSelectConfigurator.
     {
         chipSelectConfigurator = &configurator;
         SetChipSelectConfiguratorMock(configurator);
     }
Member Data Documentation
chipSelectConfigurator
hal::ChipSelectConfigurator* hal::SpiAsynchronousMock::chipSelectConfigurator = nullptr
Definition at line 42 of file SpiMock.hpp.
Referenced by SetChipSelectConfigurator().
onDone
infra::Function<void()> hal::SpiAsynchronousMock::onDone
Definition at line 32 of file SpiMock.hpp.
Referenced by SendAndReceive().
scheduleActionCompleteAutomatically
bool hal::SpiAsynchronousMock::scheduleActionCompleteAutomatically = true
Definition at line 41 of file SpiMock.hpp.
The documentation for this class was generated from the following files:
SpiMock.hpp
SpiMock.cpp