EMil: hal::FlashMock Class Reference
hal::FlashMock Class Reference
#include <FlashMock.hpp>
Public Member Functions
FlashMock (uint32_t numberOfSectors=4, uint32_t sizeOfSectors=16)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
MOCK_METHOD2 (writeBufferMock, void(std::vector< uint8_t >, uint32_t))
MOCK_METHOD1 (readBufferMock, std::vector< uint8_t >(uint32_t))
MOCK_METHOD2 (eraseSectorsMock, void(uint32_t, uint32_t))
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Public Attributes
uint32_t numberOfSectors
uint32_t sizeOfSectors
infra::Function< void()> done
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 10 of file FlashMock.hpp.
Constructor & Destructor Documentation
FlashMock()
hal::FlashMock::FlashMock (uint32_t numberOfSectors = 4, uint32_t sizeOfSectors = 16) explicit
Definition at line 6 of file FlashMock.cpp.
         : numberOfSectors(numberOfSectors)
         , sizeOfSectors(sizeOfSectors)
     {}
Member Function Documentation
AddressOfSector()
uint32_t hal::FlashMock::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 26 of file FlashMock.cpp.
References sizeOfSectors.
     {
         return sectorIndex * sizeOfSectors;
     }
EraseSectors()
void hal::FlashMock::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 45 of file FlashMock.cpp.
References done.
     {
         done = onDone;
         eraseSectorsMock(beginIndex, endIndex);
     }
MOCK_METHOD1()
hal::FlashMock::MOCK_METHOD1 (readBufferMock , std::vector< uint8_t > uint32_t)
MOCK_METHOD2() [1/2]
hal::FlashMock::MOCK_METHOD2 (writeBufferMock , void(std::vector< uint8_t >, uint32_t))
MOCK_METHOD2() [2/2]
hal::FlashMock::MOCK_METHOD2 (eraseSectorsMock , void(uint32_t, uint32_t))
NumberOfSectors()
uint32_t hal::FlashMock::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 11 of file FlashMock.cpp.
References numberOfSectors.
     {
         return numberOfSectors;
     }
ReadBuffer()
void hal::FlashMock::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 37 of file FlashMock.cpp.
References infra::MemoryRange< T >::begin(), done, and infra::MemoryRange< T >::size().
     {
         done = onDone;
         std::vector<uint8_t> result = readBufferMock(address);
         assert(result.size() == buffer.size());
         std::copy(result.begin(), result.end(), buffer.begin());
     }
SectorOfAddress()
uint32_t hal::FlashMock::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 21 of file FlashMock.cpp.
References sizeOfSectors.
     {
         return address / sizeOfSectors;
     }
SizeOfSector()
uint32_t hal::FlashMock::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 16 of file FlashMock.cpp.
References sizeOfSectors.
     {
         return sizeOfSectors;
     }
WriteBuffer()
void hal::FlashMock::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 31 of file FlashMock.cpp.
References infra::MemoryRange< T >::begin(), done, and infra::MemoryRange< T >::end().
     {
         done = onDone;
         writeBufferMock(std::vector<uint8_t>(buffer.begin(), buffer.end()), address);
     }
Member Data Documentation
done
infra::Function<void()> hal::FlashMock::done
Definition at line 33 of file FlashMock.hpp.
Referenced by EraseSectors(), ReadBuffer(), and WriteBuffer().
numberOfSectors
uint32_t hal::FlashMock::numberOfSectors
Definition at line 26 of file FlashMock.hpp.
Referenced by NumberOfSectors().
sizeOfSectors
uint32_t hal::FlashMock::sizeOfSectors
Definition at line 27 of file FlashMock.hpp.
Referenced by AddressOfSector(), SectorOfAddress(), and SizeOfSector().
The documentation for this class was generated from the following files:
FlashMock.hpp
FlashMock.cpp