EMil: services::ConfigurationStoreImpl< T > Class Template Reference
services::ConfigurationStoreImpl< T > Class Template Reference
#include <ConfigurationStore.hpp>
Classes
class WithBlobs
Public Member Functions
ConfigurationStoreImpl (ConfigurationBlob &blob1, ConfigurationBlob &blob2)
virtual const T & Configuration () const override
virtual T & Configuration () override
virtual void Write (infra::Function< void()> onDone=infra::Function< void()>()) override
virtual ConfigurationStoreBase::LockGuard Lock () override
virtual void Serialize (ConfigurationBlob &blob, const infra::Function< void()> &onDone) override
virtual void Deserialize (ConfigurationBlob &blob) override
Public Member Functions inherited from services::ConfigurationStoreBase
ConfigurationStoreBase (ConfigurationBlob &blob1, ConfigurationBlob &blob2)
void Recover (const infra::Function< void(bool success)> &onRecovered)
void Write (infra::Function< void()> onDone)
virtual void Write () override
void Erase (infra::Function< void()> onDone)
LockGuard Lock ()
Private Attributes
T configuration
Additional Inherited Members
Protected Member Functions inherited from services::ConfigurationStoreInterface
ConfigurationStoreInterface ()=default
ConfigurationStoreInterface (const ConfigurationStoreInterface &other)=delete
ConfigurationStoreInterface & operator= (const ConfigurationStoreInterface &other)=delete
~ConfigurationStoreInterface ()=default
Detailed Description
template<class T>
class services::ConfigurationStoreImpl< T >
Definition at line 132 of file ConfigurationStore.hpp.
Constructor & Destructor Documentation
ConfigurationStoreImpl()
template<class T > services::ConfigurationStoreImpl< T >::ConfigurationStoreImpl (ConfigurationBlob & blob1, ConfigurationBlob & blob2)
Definition at line 239 of file ConfigurationStore.hpp.
         : ConfigurationStoreBase(blob1, blob2)
     {}
Member Function Documentation
Configuration() [1/2]
template<class T > const T & services::ConfigurationStoreImpl< T >::Configuration () const override virtual
Implements services::ConfigurationStore< T >.
Definition at line 244 of file ConfigurationStore.hpp.
     {
         return configuration;
     }
Configuration() [2/2]
template<class T > T & services::ConfigurationStoreImpl< T >::Configuration () override virtual
Implements services::ConfigurationStore< T >.
Definition at line 250 of file ConfigurationStore.hpp.
     {
         return configuration;
     }
Deserialize()
template<class T > void services::ConfigurationStoreImpl< T >::Deserialize (ConfigurationBlob & blob) override virtual
Implements services::ConfigurationStoreBase.
Definition at line 277 of file ConfigurationStore.hpp.
References services::ConfigurationBlob::CurrentBlob().
     {
         infra::ByteInputStream stream(blob.CurrentBlob());
         infra::ProtoParser parser(stream);
         // Reset the configuration object by invoking the destructor, followed by the constructor
         // We do it this way instead of "configuration = T()", because T might be several kB in size, which overflows the stack
         configuration.~T();
         new (&configuration) T();
         configuration.Deserialize(parser);
     }
Lock()
template<class T > ConfigurationStoreBase::LockGuard services::ConfigurationStoreImpl< T >::Lock () override virtual
Implements services::ConfigurationStore< T >.
Definition at line 262 of file ConfigurationStore.hpp.
References services::ConfigurationStoreBase::Lock().
     {
         return ConfigurationStoreBase::Lock();
     }
Serialize()
template<class T > void services::ConfigurationStoreImpl< T >::Serialize (ConfigurationBlob & blob, const infra::Function< void()> & onDone) override virtual
Implements services::ConfigurationStoreBase.
Definition at line 268 of file ConfigurationStore.hpp.
References services::ConfigurationBlob::MaxBlob(), and services::ConfigurationBlob::Write().
     {
         infra::ByteOutputStream stream(blob.MaxBlob());
         infra::ProtoFormatter formatter(stream);
         configuration.Serialize(formatter);
         blob.Write(stream.Writer().Processed().size(), onDone);
     }
Write()
template<class T > void services::ConfigurationStoreImpl< T >::Write (infra::Function< void()> onDone = infra::Function<void()>()) override virtual
Implements services::ConfigurationStore< T >.
Definition at line 256 of file ConfigurationStore.hpp.
References services::ConfigurationStoreBase::Write().
     {
         ConfigurationStoreBase::Write(onDone);
     }
Member Data Documentation
configuration
template<class T> T services::ConfigurationStoreImpl< T >::configuration private
Definition at line 150 of file ConfigurationStore.hpp.
The documentation for this class was generated from the following file:
ConfigurationStore.hpp