EMil: services::ConnectionLoopBackConnector Class Reference
services::ConnectionLoopBackConnector Class Reference
#include <ConnectionLoopBack.hpp>
Public Member Functions
ConnectionLoopBackConnector (ConnectionLoopBackFactory &loopBackFactory, ClientConnectionObserverFactory &connectionObserverFactory)
void Connect ()
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionLoopBackConnector >
SharedPtr< ConnectionLoopBackConnector > SharedFromThis ()
SharedPtr< const ConnectionLoopBackConnector > SharedFromThis () const
WeakPtr< ConnectionLoopBackConnector > WeakFromThis ()
WeakPtr< const ConnectionLoopBackConnector > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionLoopBackConnector > sharedPtr)
Private Attributes
ConnectionLoopBackFactory & loopBackFactory
ClientConnectionObserverFactory & connectionObserverFactory
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectionLoopBackConnector >
using EnableSharedFromThisType = ConnectionLoopBackConnector
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionLoopBackConnector >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 98 of file ConnectionLoopBack.hpp.
Constructor & Destructor Documentation
ConnectionLoopBackConnector()
services::ConnectionLoopBackConnector::ConnectionLoopBackConnector (ConnectionLoopBackFactory & loopBackFactory, ClientConnectionObserverFactory & connectionObserverFactory)
Definition at line 144 of file ConnectionLoopBack.cpp.
         : loopBackFactory(loopBackFactory)
         , connectionObserverFactory(connectionObserverFactory)
     {}
Member Function Documentation
Connect()
void services::ConnectionLoopBackConnector::Connect ()
Definition at line 149 of file ConnectionLoopBack.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), and infra::EnableSharedFromThis< ConnectionLoopBackConnector >::SharedFromThis().
     {
         infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionLoopBackConnector>& object)
         {
             auto listener = object->loopBackFactory.listeners.find(object->connectionObserverFactory.Port());
             if (listener != object->loopBackFactory.listeners.end())
                 listener->second->Accept(object->connectionObserverFactory);
             else
                 object->connectionObserverFactory.ConnectionFailed(services::ClientConnectionObserverFactory::ConnectFailReason::refused);
         }, SharedFromThis());
     }
Member Data Documentation
connectionObserverFactory
ClientConnectionObserverFactory& services::ConnectionLoopBackConnector::connectionObserverFactory private
Definition at line 108 of file ConnectionLoopBack.hpp.
loopBackFactory
ConnectionLoopBackFactory& services::ConnectionLoopBackConnector::loopBackFactory private
Definition at line 107 of file ConnectionLoopBack.hpp.
The documentation for this class was generated from the following files:
ConnectionLoopBack.hpp
ConnectionLoopBack.cpp