EMil: TestWebSocketClient.cpp File Reference
TestWebSocketClient.cpp File Reference
Classes
class WebSocketClientTest
Functions
TEST_F (WebSocketClientTest, should_parse_valid_websocket_header)
TEST_F (WebSocketClientTest, should_parse_masking_key)
TEST_F (WebSocketClientTest, should_parse_payload_length)
TEST_F (WebSocketClientTest, should_parse_extended16_payload_length)
TEST_F (WebSocketClientTest, should_parse_extended64_payload_length)
Function Documentation
TEST_F() [1/5]
TEST_F (WebSocketClientTest , should_parse_valid_websocket_header)
Definition at line 9 of file TestWebSocketClient.cpp.
References data, and EXPECT_TRUE().
 {
     std::vector<uint8_t> data({ 0x80, 0x80, 0x00, 0x00, 0x00, 0x00 });
     infra::ByteInputStream stream(data);
     services::WebSocketFrameHeader header(stream.Reader());
     EXPECT_TRUE(header.IsValid());
     EXPECT_TRUE(header.IsComplete());
     EXPECT_TRUE(header.IsFinalFrame());
 }
TEST_F() [2/5]
TEST_F (WebSocketClientTest , should_parse_masking_key)
Definition at line 20 of file TestWebSocketClient.cpp.
References data, and EXPECT_EQ().
 {
     std::vector<uint8_t> data({ 0x80, 0x80, 0xAB, 0xCD, 0xEF, 0x01 });
     infra::ByteInputStream stream(data);
     services::WebSocketFrameHeader header(stream.Reader());
     std::array<uint8_t, 4> expected = { 0xAB, 0xCD, 0xEF, 0x01 };
     EXPECT_EQ(expected, header.MaskingKey());
 }
TEST_F() [3/5]
TEST_F (WebSocketClientTest , should_parse_payload_length)
Definition at line 30 of file TestWebSocketClient.cpp.
References data, and EXPECT_EQ().
 {
     std::vector<uint8_t> data({ 0x80, 0xFD, 0x00, 0x00, 0x00, 0x00 });
     infra::ByteInputStream stream(data);
     services::WebSocketFrameHeader header(stream.Reader());
     EXPECT_EQ(125, header.PayloadLength());
 }
TEST_F() [4/5]
TEST_F (WebSocketClientTest , should_parse_extended16_payload_length)
Definition at line 39 of file TestWebSocketClient.cpp.
References data, and EXPECT_EQ().
 {
     std::vector<uint8_t> data({ 0x80, 0xFE, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00 });
     infra::ByteInputStream stream(data);
     services::WebSocketFrameHeader header(stream.Reader());
     EXPECT_EQ(std::numeric_limits<uint16_t>::max(), header.PayloadLength());
 }
TEST_F() [5/5]
TEST_F (WebSocketClientTest , should_parse_extended64_payload_length)
Definition at line 48 of file TestWebSocketClient.cpp.
References data, and EXPECT_EQ().
 {
     std::vector<uint8_t> data({ 0x80, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00 });
     infra::ByteInputStream stream(data);
     services::WebSocketFrameHeader header(stream.Reader());
     EXPECT_EQ(std::numeric_limits<uint64_t>::max(), header.PayloadLength());
 }