EMil: services::DnsResolver::ActiveLookup Class Reference
services::DnsResolver::ActiveLookup Class Reference
Public Member Functions
ActiveLookup (DnsResolver &resolver, NameResolverResult &resolving)
bool IsResolving (NameResolverResult &resolving) const
Private Member Functions
virtual void DataReceived (infra::StreamReaderWithRewinding &reader, UdpSocket from) override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
void ResolveNextAttempt ()
void ResolveRecursion ()
void ResolveAttempt ()
void SelectNextNameServer ()
void TryFindAnswer (ReplyParser &replyParser)
void TryFindRecursiveNameServer (ReplyParser &replyParser)
void TryNewNameServers (ReplyParser &replyParser)
UdpSocket DnsUpdSocket () const
std::size_t QuerySize () const
void WriteHostname (infra::DataOutputStream &stream) const
Private Member Functions inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Private Attributes
DnsResolver & resolver
infra::SharedPtr< DatagramExchange > datagramExchange
uint16_t queryId
NameResolverResult & resolving
infra::TimerSingleShot timeoutTimer
uint8_t resolveAttempts = 0
uint8_t recursions = 0
infra::BoundedString::WithStorage< 253 > hostname
infra::BoundedVector< IPAddress >::WithMaxSize< maxAttempts > nameServers
const IPAddress * currentNameServer
Additional Inherited Members
Private Types inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
using SubjectType = DatagramExchange
using SingleHelper = DatagramExchange
Detailed Description
Definition at line 174 of file DnsResolver.hpp.
Constructor & Destructor Documentation
ActiveLookup()
services::DnsResolver::ActiveLookup::ActiveLookup (DnsResolver & resolver, NameResolverResult & resolving)
Definition at line 389 of file DnsResolver.cpp.
References ResolveNextAttempt().
         : resolver(resolver)
         , datagramExchange(resolver.datagramFactory.Listen(*this))
         , queryId(resolver.randomDataGenerator.GenerateRandomData<uint16_t>())
         , resolving(resolving)
         , hostname(resolving.Hostname())
         , nameServers(resolver.nameServers.begin(), resolver.nameServers.end())
         , currentNameServer(nameServers.begin() + resolver.currentNameServer)
     {
         ResolveNextAttempt();
     }
Member Function Documentation
DataReceived()
void services::DnsResolver::ActiveLookup::DataReceived (infra::StreamReaderWithRewinding & reader, UdpSocket from) override private virtual
Implements services::DatagramExchangeObserver.
Definition at line 406 of file DnsResolver.cpp.
References services::DnsResolver::ReplyParser::AnswerIsForCurrentQuery(), services::DnsResolver::ReplyParser::Error(), and services::GetAddress().
     {
         ReplyParser replyParser(reader, hostname);
         if (replyParser.AnswerIsForCurrentQuery(from, GetAddress(DnsUpdSocket()), queryId))
         {
             if (replyParser.Error())
                 ResolveNextAttempt();
             else
                 TryFindAnswer(replyParser);
         }
     }
DnsUpdSocket()
UdpSocket services::DnsResolver::ActiveLookup::DnsUpdSocket () const private
Definition at line 499 of file DnsResolver.cpp.
References services::DnsResolver::currentNameServer, and services::MakeUdpSocket().
     {
         return MakeUdpSocket(*currentNameServer, 53);
     }
IsResolving()
bool services::DnsResolver::ActiveLookup::IsResolving (NameResolverResult & resolving) const
Definition at line 401 of file DnsResolver.cpp.
     {
         return &resolving == &this->resolving;
     }
QuerySize()
std::size_t services::DnsResolver::ActiveLookup::QuerySize () const private
Definition at line 504 of file DnsResolver.cpp.
References infra::BoundedStringBase< T >::empty(), infra::BoundedStringBase< T >::find(), infra::BoundedStringBase< const char >::npos, infra::BoundedStringBase< T >::size(), and infra::BoundedStringBase< T >::substr().
     {
         infra::BoundedConstString hostnameCopy = hostname;
         std::size_t hostnameSize = 1;
         while (!hostnameCopy.empty())
         {
             auto dot = hostnameCopy.find('.');
             if (dot == infra::BoundedConstString::npos)
                 break;
             hostnameSize += dot + 1;
             hostnameCopy = hostnameCopy.substr(dot + 1);
         }
         return sizeof(QueryHeader) + hostnameSize + hostnameCopy.size() + 1 + sizeof(QuestionFooter);
     }
ResolveAttempt()
void services::DnsResolver::ActiveLookup::ResolveAttempt () private
Definition at line 456 of file DnsResolver.cpp.
     {
         datagramExchange->RequestSendStream(QuerySize(), DnsUpdSocket());
     }
ResolveNextAttempt()
void services::DnsResolver::ActiveLookup::ResolveNextAttempt () private
Definition at line 433 of file DnsResolver.cpp.
References services::DnsResolver::maxAttempts.
Referenced by ActiveLookup().
     {
         if (resolveAttempts == maxAttempts)
             resolver.NameLookupFailed(resolving);
         else
         {
             ++resolveAttempts;
             recursions = 0;
             SelectNextNameServer();
             ResolveAttempt();
         }
     }
ResolveRecursion()
void services::DnsResolver::ActiveLookup::ResolveRecursion () private
Definition at line 446 of file DnsResolver.cpp.
References services::DnsResolver::maxRecursions.
     {
         ++recursions;
         if (recursions == maxRecursions)
             resolver.NameLookupFailed(resolving);
         else
             ResolveAttempt();
     }
SelectNextNameServer()
void services::DnsResolver::ActiveLookup::SelectNextNameServer () private
Definition at line 461 of file DnsResolver.cpp.
References services::DnsResolver::currentNameServer, and services::DnsResolver::nameServers.
     {
         ++currentNameServer;
         if (currentNameServer == nameServers.end())
             currentNameServer = nameServers.begin();
     }
SendStreamAvailable()
void services::DnsResolver::ActiveLookup::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override private virtual
Implements services::DatagramExchangeObserver.
Definition at line 419 of file DnsResolver.cpp.
References services::DnsResolver::QuestionFooter::classIn, services::DnsResolver::QueryHeader::flagsRecursionDesired, services::DnsResolver::responseTimeout, and services::DnsResolver::QuestionFooter::typeA.
     {
         infra::DataOutputStream::WithErrorPolicy stream(*writer);
         QueryHeader header{ queryId, QueryHeader::flagsRecursionDesired, 1, 0, 0, 0 };
         stream << header;
         WriteHostname(stream);
         QuestionFooter footer{ QuestionFooter::typeA, QuestionFooter::classIn };
         stream << footer;
         timeoutTimer.Start(responseTimeout, [this]() { ResolveNextAttempt(); });
     }
TryFindAnswer()
void services::DnsResolver::ActiveLookup::TryFindAnswer (ReplyParser & replyParser) private
Definition at line 468 of file DnsResolver.cpp.
References infra::none, and services::DnsResolver::ReplyParser::ReadAnswerRecords().
     {
         auto answer = replyParser.ReadAnswerRecords();
         if (answer != infra::none)
             resolver.NameLookupSuccess(resolving, answer->first, answer->second);
         else
             TryFindRecursiveNameServer(replyParser);
     }
TryFindRecursiveNameServer()
void services::DnsResolver::ActiveLookup::TryFindRecursiveNameServer (ReplyParser & replyParser) private
Definition at line 477 of file DnsResolver.cpp.
References services::DnsResolver::ReplyParser::Recurse().
     {
         TryNewNameServers(replyParser);
         if (replyParser.Recurse())
             ResolveRecursion();
         else
             ResolveNextAttempt();
     }
TryNewNameServers()
void services::DnsResolver::ActiveLookup::TryNewNameServers (ReplyParser & replyParser) private
Definition at line 487 of file DnsResolver.cpp.
References services::DnsResolver::currentNameServer, services::DnsResolver::nameServers, and services::DnsResolver::ReplyParser::ReadNameServers().
     {
         decltype(nameServers) newRecursiveDnsServers;
         replyParser.ReadNameServers(newRecursiveDnsServers);
         if (!newRecursiveDnsServers.empty())
         {
             nameServers = newRecursiveDnsServers;
             currentNameServer = nameServers.begin();
         }
     }
WriteHostname()
void services::DnsResolver::ActiveLookup::WriteHostname (infra::DataOutputStream & stream) const private
Definition at line 522 of file DnsResolver.cpp.
References infra::data, infra::BoundedStringBase< T >::empty(), infra::BoundedStringBase< T >::find(), infra::BoundedStringBase< const char >::npos, infra::BoundedStringBase< T >::size(), infra::BoundedStringBase< T >::substr(), and infra::text.
     {
         infra::BoundedConstString hostnameCopy = hostname;
         while (!hostnameCopy.empty())
         {
             auto dot = hostnameCopy.find('.');
             if (dot == infra::BoundedConstString::npos)
                 break;
             stream << static_cast<uint8_t>(dot) << infra::text << hostnameCopy.substr(0, dot);
             hostnameCopy = hostnameCopy.substr(dot + 1);
         }
         stream << static_cast<uint8_t>(hostnameCopy.size()) << infra::text << hostnameCopy << infra::data << static_cast<uint8_t>(0);
     }
Member Data Documentation
currentNameServer
const IPAddress* services::DnsResolver::ActiveLookup::currentNameServer private
Definition at line 209 of file DnsResolver.hpp.
datagramExchange
infra::SharedPtr<DatagramExchange> services::DnsResolver::ActiveLookup::datagramExchange private
Definition at line 200 of file DnsResolver.hpp.
hostname
infra::BoundedString::WithStorage<253> services::DnsResolver::ActiveLookup::hostname private
Definition at line 207 of file DnsResolver.hpp.
nameServers
infra::BoundedVector<IPAddress>::WithMaxSize<maxAttempts> services::DnsResolver::ActiveLookup::nameServers private
Definition at line 208 of file DnsResolver.hpp.
queryId
uint16_t services::DnsResolver::ActiveLookup::queryId private
Definition at line 201 of file DnsResolver.hpp.
recursions
uint8_t services::DnsResolver::ActiveLookup::recursions = 0 private
Definition at line 205 of file DnsResolver.hpp.
resolveAttempts
uint8_t services::DnsResolver::ActiveLookup::resolveAttempts = 0 private
Definition at line 204 of file DnsResolver.hpp.
resolver
DnsResolver& services::DnsResolver::ActiveLookup::resolver private
Definition at line 199 of file DnsResolver.hpp.
resolving
NameResolverResult& services::DnsResolver::ActiveLookup::resolving private
Definition at line 202 of file DnsResolver.hpp.
timeoutTimer
infra::TimerSingleShot services::DnsResolver::ActiveLookup::timeoutTimer private
Definition at line 203 of file DnsResolver.hpp.
The documentation for this class was generated from the following files:
DnsResolver.hpp
DnsResolver.cpp