EMil: TestLowPowerSpiMaster.cpp File Reference
TestLowPowerSpiMaster.cpp File Reference
Classes
class LowPowerSpiMasterTest
Functions
TEST_F (LowPowerSpiMasterTest, construction)
TEST_F (LowPowerSpiMasterTest, SetChipSelectConfigurator_will_forward_call_downstream)
TEST_F (LowPowerSpiMasterTest, SetCommunicationConfigurator_will_forward_call_downstream)
TEST_F (LowPowerSpiMasterTest, ResetCommunicationConfigurator_will_forward_call_downstream)
TEST_F (LowPowerSpiMasterTest, SendAndReceive_will_refere_mainClock_and_release_onDone)
Function Documentation
TEST_F() [1/5]
TEST_F (LowPowerSpiMasterTest , construction)
Definition at line 24 of file TestLowPowerSpiMaster.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(mainClock.IsReferenced());
 }
TEST_F() [2/5]
TEST_F (LowPowerSpiMasterTest , SetChipSelectConfigurator_will_forward_call_downstream)
Definition at line 29 of file TestLowPowerSpiMaster.cpp.
 {
     hal::ChipSelectConfiguratorMock configurator;
     EXPECT_CALL(spiMock, SetChipSelectConfigurator(testing::Ref(configurator)));
     lowPowerSpiMaster.SetChipSelectConfigurator(configurator);
 }
TEST_F() [3/5]
TEST_F (LowPowerSpiMasterTest , SetCommunicationConfigurator_will_forward_call_downstream)
Definition at line 38 of file TestLowPowerSpiMaster.cpp.
 {
     hal::CommunicationConfiguratorMock configurator;
     EXPECT_CALL(spiMock, SetCommunicationConfigurator(testing::Ref(configurator)));
     lowPowerSpiMaster.SetCommunicationConfigurator(configurator);
 }
TEST_F() [4/5]
TEST_F (LowPowerSpiMasterTest , ResetCommunicationConfigurator_will_forward_call_downstream)
Definition at line 47 of file TestLowPowerSpiMaster.cpp.
 {
     EXPECT_CALL(spiMock, ResetCommunicationConfigurator());
     lowPowerSpiMaster.ResetCommunicationConfigurator();
 }
TEST_F() [5/5]
TEST_F (LowPowerSpiMasterTest , SendAndReceive_will_refere_mainClock_and_release_onDone)
Definition at line 54 of file TestLowPowerSpiMaster.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and hal::stop.
 {
     infra::MockCallback<void()> mockOnDone;
     std::vector<uint8_t> buffer = { 0 };
     EXPECT_CALL(spiMock, SendDataMock(testing::_, testing::_));
     EXPECT_CALL(spiMock, ReceiveDataMock(testing::_)).WillOnce(testing::Return(buffer));
     lowPowerSpiMaster.SendAndReceive(buffer, buffer, hal::SpiAction::stop, [&mockOnDone]() {mockOnDone.callback(); });
     EXPECT_TRUE(mainClock.IsReferenced());
     EXPECT_CALL(mockOnDone, callback());
     ExecuteAllActions();
     EXPECT_FALSE(mainClock.IsReferenced());
 }