EMil: infra::BoundedDequeInputStreamReader Class Reference
infra::BoundedDequeInputStreamReader Class Reference
#include <BoundedDequeInputStream.hpp>
Public Types
template<std::size_t Max>
using WithStorage = infra::WithStorage< BoundedDequeInputStreamReader, infra::BoundedDeque< uint8_t >::WithMaxSize< Max > >
Public Member Functions
BoundedDequeInputStreamReader (infra::BoundedDeque< uint8_t > &container)
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy) override
virtual ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
virtual std::size_t ConstructSaveMarker () const override
virtual void Rewind (std::size_t marker) override
Private Attributes
infra::BoundedDeque< uint8_t > & container
std::size_t offset = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 9 of file BoundedDequeInputStream.hpp.
Member Typedef Documentation
WithStorage
template<std::size_t Max> using infra::BoundedDequeInputStreamReader::WithStorage = infra::WithStorage<BoundedDequeInputStreamReader, infra::BoundedDeque<uint8_t>::WithMaxSize<Max> >
Definition at line 14 of file BoundedDequeInputStream.hpp.
Constructor & Destructor Documentation
BoundedDequeInputStreamReader()
infra::BoundedDequeInputStreamReader::BoundedDequeInputStreamReader (infra::BoundedDeque< uint8_t > & container) explicit
Definition at line 5 of file BoundedDequeInputStream.cpp.
         : container(container)
     {}
Member Function Documentation
Available()
std::size_t infra::BoundedDequeInputStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 45 of file BoundedDequeInputStream.cpp.
References container, offset, and infra::BoundedDeque< T >::size().
     {
         return container.size() - offset;
     }
ConstructSaveMarker()
std::size_t infra::BoundedDequeInputStreamReader::ConstructSaveMarker () const override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 50 of file BoundedDequeInputStream.cpp.
References offset.
     {
         return offset;
     }
Empty()
bool infra::BoundedDequeInputStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 40 of file BoundedDequeInputStream.cpp.
References container, offset, and infra::BoundedDeque< T >::size().
     {
         return offset == container.size();
     }
Extract()
void infra::BoundedDequeInputStreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 9 of file BoundedDequeInputStream.cpp.
References infra::BoundedDeque< T >::begin(), container, infra::BoundedDeque< T >::contiguous_range(), infra::Copy(), infra::MemoryRange< T >::empty(), infra::Head(), offset, infra::MemoryRange< T >::pop_front(), infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::size(), and infra::BoundedDeque< T >::size().
Referenced by Peek().
     {
         errorPolicy.ReportResult(dataRange.size() <= container.size() - offset);
         while (!dataRange.empty() && container.size() != offset)
         {
             ConstByteRange from = infra::Head(container.contiguous_range(container.begin() + offset), dataRange.size());
             infra::Copy(from, infra::Head(dataRange, from.size()));
             dataRange.pop_front(from.size());
             offset += from.size();
         }
     }
ExtractContiguousRange()
ConstByteRange infra::BoundedDequeInputStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 28 of file BoundedDequeInputStream.cpp.
References infra::BoundedDeque< T >::begin(), container, infra::BoundedDeque< T >::contiguous_range(), infra::Head(), offset, and infra::MemoryRange< T >::size().
     {
         ConstByteRange result = infra::Head(container.contiguous_range(container.begin() + offset), max);
         offset += result.size();
         return result;
     }
Peek()
uint8_t infra::BoundedDequeInputStreamReader::Peek (StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 21 of file BoundedDequeInputStream.cpp.
References Extract(), and infra::MakeByteRange().
     {
         uint8_t element = 0;
         Extract(MakeByteRange(element), errorPolicy);
         return element;
     }
PeekContiguousRange()
ConstByteRange infra::BoundedDequeInputStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 35 of file BoundedDequeInputStream.cpp.
     {
         return container.contiguous_range(container.begin() + offset + start);
     }
Rewind()
void infra::BoundedDequeInputStreamReader::Rewind (std::size_t marker) override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 55 of file BoundedDequeInputStream.cpp.
References offset.
     {
         offset = marker;
     }
Member Data Documentation
container
infra::BoundedDeque<uint8_t>& infra::BoundedDequeInputStreamReader::container private
Definition at line 29 of file BoundedDequeInputStream.hpp.
Referenced by Available(), Empty(), Extract(), and ExtractContiguousRange().
offset
std::size_t infra::BoundedDequeInputStreamReader::offset = 0 private
Definition at line 30 of file BoundedDequeInputStream.hpp.
Referenced by Available(), ConstructSaveMarker(), Empty(), Extract(), ExtractContiguousRange(), and Rewind().
The documentation for this class was generated from the following files:
BoundedDequeInputStream.hpp
BoundedDequeInputStream.cpp