EMil: services::WebSocket Class Reference
services::WebSocket Class Reference
#include <WebSocket.hpp>
Static Public Member Functions
static void UpgradeHeaders (infra::BoundedVector< const services::HttpHeader > &headers, infra::BoundedConstString protocol)
Detailed Description
Definition at line 56 of file WebSocket.hpp.
Member Function Documentation
UpgradeHeaders()
void services::WebSocket::UpgradeHeaders (infra::BoundedVector< const services::HttpHeader > & headers, infra::BoundedConstString protocol) static
Definition at line 91 of file WebSocket.cpp.
References infra::BoundedVector< T >::max_size(), infra::BoundedVector< T >::push_back(), and infra::BoundedVector< T >::size().
     {
         really_assert(headers.max_size() - headers.size() >= 5);
         headers.push_back(services::HttpHeader("Upgrade", "websocket"));
         headers.push_back(services::HttpHeader("Connection", "Upgrade"));
         headers.push_back(services::HttpHeader("Sec-Websocket-Key", "AQIDBAUGBbgJCgsMDQ4PEC=="));
         headers.push_back(services::HttpHeader("Sec-Websocket-Protocol", protocol));
         headers.push_back(services::HttpHeader("Sec-Websocket-Version", "13"));
     }
The documentation for this class was generated from the following files:
WebSocket.hpp
WebSocket.cpp