EMil: infra::BoundedForwardList< T > Class Template Reference
infra::BoundedForwardList< T > Class Template Reference
#include <BoundedForwardList.hpp>
Public Types
template<std::size_t Max>
using WithMaxSize = infra::WithStorage< BoundedForwardList< T >, std::array< StaticStorage< detail::BoundedForwardListNode< T > >, Max > >
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef detail::BoundedForwardListIterator< T > iterator
typedef detail::BoundedForwardListIterator< const T > const_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
BoundedForwardList (const BoundedForwardList &other)=delete
BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage)
BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, size_type n, const value_type &value=value_type())
template<class InputIterator >
BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, InputIterator first, InputIterator last)
BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, std::initializer_list< T > initializerList)
BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, const BoundedForwardList &other)
BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, BoundedForwardList &&other)
~BoundedForwardList ()
BoundedForwardList & operator= (const BoundedForwardList &other)
BoundedForwardList & operator= (BoundedForwardList &&other)
void AssignFromStorage (const BoundedForwardList &other)
void AssignFromStorage (BoundedForwardList &&other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
size_type size () const
size_type max_size () const
bool empty () const
bool full () const
value_type & front ()
const value_type & front () const
void push_front (const value_type &value)
void push_front (value_type &&value)
void pop_front ()
void insert_after (iterator position, const value_type &value)
void insert_after (iterator position, value_type &&value)
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void assign (size_type n, const value_type &value)
template<class InputIterator >
void move_from_range (InputIterator first, InputIterator last)
void erase_slow (iterator position)
void erase_all_after (iterator position)
void swap (BoundedForwardList &other)
void clear ()
template<class... Args>
void emplace_front (Args &&... args)
bool operator== (const BoundedForwardList &other) const
bool operator!= (const BoundedForwardList &other) const
bool operator< (const BoundedForwardList &other) const
bool operator<= (const BoundedForwardList &other) const
bool operator> (const BoundedForwardList &other) const
bool operator>= (const BoundedForwardList &other) const
Private Types
typedef detail::BoundedForwardListNode< typename std::remove_const< T >::type > NodeType
Private Member Functions
NodeType * AllocateNode ()
Private Attributes
infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T > > > storage
size_type numAllocated = 0
size_type numInitialized = 0
NodeType * firstNode = nullptr
NodeType * freeList = nullptr
Detailed Description
template<class T>
class infra::BoundedForwardList< T >
Definition at line 35 of file BoundedForwardList.hpp.
Member Typedef Documentation
const_iterator
template<class T> typedef detail::BoundedForwardListIterator<const T> infra::BoundedForwardList< T >::const_iterator
Definition at line 47 of file BoundedForwardList.hpp.
const_pointer
template<class T> typedef const T* infra::BoundedForwardList< T >::const_pointer
Definition at line 45 of file BoundedForwardList.hpp.
const_reference
template<class T> typedef const T& infra::BoundedForwardList< T >::const_reference
Definition at line 43 of file BoundedForwardList.hpp.
difference_type
template<class T> typedef std::iterator_traits<iterator>::difference_type infra::BoundedForwardList< T >::difference_type
Definition at line 48 of file BoundedForwardList.hpp.
iterator
template<class T> typedef detail::BoundedForwardListIterator<T> infra::BoundedForwardList< T >::iterator
Definition at line 46 of file BoundedForwardList.hpp.
NodeType
template<class T> typedef detail::BoundedForwardListNode<typename std::remove_const<T>::type> infra::BoundedForwardList< T >::NodeType private
Definition at line 119 of file BoundedForwardList.hpp.
pointer
template<class T> typedef T* infra::BoundedForwardList< T >::pointer
Definition at line 44 of file BoundedForwardList.hpp.
reference
template<class T> typedef T& infra::BoundedForwardList< T >::reference
Definition at line 42 of file BoundedForwardList.hpp.
size_type
template<class T> typedef std::size_t infra::BoundedForwardList< T >::size_type
Definition at line 49 of file BoundedForwardList.hpp.
value_type
template<class T> typedef T infra::BoundedForwardList< T >::value_type
Definition at line 41 of file BoundedForwardList.hpp.
WithMaxSize
template<class T> template<std::size_t Max> using infra::BoundedForwardList< T >::WithMaxSize = infra::WithStorage<BoundedForwardList<T>, std::array<StaticStorage<detail::BoundedForwardListNode<T> >, Max> >
Definition at line 39 of file BoundedForwardList.hpp.
Constructor & Destructor Documentation
BoundedForwardList() [1/7]
template<class T> infra::BoundedForwardList< T >::BoundedForwardList (const BoundedForwardList< T > & other) delete
BoundedForwardList() [2/7]
template<class T> infra::BoundedForwardList< T >::BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage) explicit
Definition at line 176 of file BoundedForwardList.hpp.
         : storage(storage)
     {}
BoundedForwardList() [3/7]
template<class T> infra::BoundedForwardList< T >::BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, size_type n, const value_type & value = value_type())
Definition at line 181 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::assign(), and value.
         : storage(storage)
     {
         assign(n, value);
     }
BoundedForwardList() [4/7]
template<class T> template<class InputIterator > infra::BoundedForwardList< T >::BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, InputIterator first, InputIterator last)
Definition at line 189 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::assign().
         : storage(storage)
     {
         assign(first, last);
     }
BoundedForwardList() [5/7]
template<class T> infra::BoundedForwardList< T >::BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, std::initializer_list< T > initializerList)
Definition at line 196 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::assign().
         : storage(storage)
     {
         assign(initializerList.begin(), initializerList.end());
     }
BoundedForwardList() [6/7]
template<class T> infra::BoundedForwardList< T >::BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, const BoundedForwardList< T > & other)
Definition at line 203 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::assign(), infra::BoundedForwardList< T >::begin(), and infra::BoundedForwardList< T >::end().
         : storage(storage)
     {
         assign(other.begin(), other.end());
     }
BoundedForwardList() [7/7]
template<class T> infra::BoundedForwardList< T >::BoundedForwardList (infra::MemoryRange< infra::StaticStorage< detail::BoundedForwardListNode< T >>> storage, BoundedForwardList< T > && other)
Definition at line 210 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::move_from_range().
         : storage(storage)
     {
         move_from_range(other.begin(), other.end());
         other.clear();
     }
~BoundedForwardList()
template<class T > infra::BoundedForwardList< T >::~BoundedForwardList ()
Definition at line 218 of file BoundedForwardList.hpp.
     {
         clear();
     }
Member Function Documentation
AllocateNode()
template<class T > BoundedForwardList< T >::NodeType * infra::BoundedForwardList< T >::AllocateNode () private
Definition at line 603 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next.
     {
         NodeType* result;
         if (freeList != nullptr)
         {
             result = freeList;
             freeList = freeList->next;
             return result;
         }
         really_assert(numInitialized != storage.size());
         result = &*storage[numInitialized];
         ++numInitialized;
         return result;
     }
assign() [1/2]
template<class T > template<class InputIterator > void infra::BoundedForwardList< T >::assign (InputIterator first, InputIterator last)
Definition at line 392 of file BoundedForwardList.hpp.
References infra::detail::begin().
Referenced by infra::BoundedForwardList< T >::BoundedForwardList().
     {
         clear();
         iterator current;
         while (first != last)
         {
             if (empty())
             {
                 push_front(*first);
                 current = begin();
             }
             else
             {
                 insert_after(current, *first);
                 ++current;
             }
             ++first;
         }
     }
assign() [2/2]
template<class T > void infra::BoundedForwardList< T >::assign (size_type n, const value_type & value)
Definition at line 414 of file BoundedForwardList.hpp.
References value.
     {
         clear();
         for (size_type i = 0; i != n; ++i)
             push_front(value);
     }
AssignFromStorage() [1/2]
template<class T > void infra::BoundedForwardList< T >::AssignFromStorage (const BoundedForwardList< T > & other)
Definition at line 246 of file BoundedForwardList.hpp.
     {
         *this = other;
     }
AssignFromStorage() [2/2]
template<class T > void infra::BoundedForwardList< T >::AssignFromStorage (BoundedForwardList< T > && other)
Definition at line 252 of file BoundedForwardList.hpp.
     {
         *this = std::move(other);
     }
begin() [1/2]
template<class T > BoundedForwardList< T >::iterator infra::BoundedForwardList< T >::begin ()
Definition at line 258 of file BoundedForwardList.hpp.
Referenced by infra::BoundedForwardList< T >::BoundedForwardList(), infra::BoundedForwardList< T >::operator<(), infra::BoundedForwardList< T >::operator=(), infra::BoundedForwardList< T >::operator==(), and infra::BoundedForwardList< T >::swap().
     {
         return iterator(firstNode);
     }
begin() [2/2]
template<class T > BoundedForwardList< T >::const_iterator infra::BoundedForwardList< T >::begin () const
Definition at line 264 of file BoundedForwardList.hpp.
     {
         return iterator(firstNode);
     }
cbegin()
template<class T > BoundedForwardList< T >::const_iterator infra::BoundedForwardList< T >::cbegin () const
Definition at line 282 of file BoundedForwardList.hpp.
     {
         return const_iterator(firstNode);
     }
cend()
template<class T > BoundedForwardList< T >::const_iterator infra::BoundedForwardList< T >::cend () const
Definition at line 288 of file BoundedForwardList.hpp.
     {
         return const_iterator();
     }
clear()
template<class T > void infra::BoundedForwardList< T >::clear ()
Definition at line 534 of file BoundedForwardList.hpp.
     {
         while (firstNode != nullptr)
             pop_front();
     }
emplace_front()
template<class T > template<class... Args> void infra::BoundedForwardList< T >::emplace_front (Args &&... args)
Definition at line 542 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, and infra::detail::BoundedForwardListNode< T >::storage.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(std::forward<Args>(args)...);
         node->next = firstNode;
         firstNode = node;
         ++numAllocated;
     }
empty()
template<class T > bool infra::BoundedForwardList< T >::empty () const
Definition at line 306 of file BoundedForwardList.hpp.
     {
         return numAllocated == 0;
     }
end() [1/2]
template<class T > BoundedForwardList< T >::iterator infra::BoundedForwardList< T >::end ()
Definition at line 270 of file BoundedForwardList.hpp.
Referenced by infra::BoundedForwardList< T >::BoundedForwardList(), infra::BoundedForwardList< T >::operator<(), infra::BoundedForwardList< T >::operator=(), and infra::BoundedForwardList< T >::swap().
     {
         return iterator();
     }
end() [2/2]
template<class T > BoundedForwardList< T >::const_iterator infra::BoundedForwardList< T >::end () const
Definition at line 276 of file BoundedForwardList.hpp.
     {
         return const_iterator();
     }
erase_all_after()
template<class T > void infra::BoundedForwardList< T >::erase_all_after (iterator position)
Definition at line 468 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, infra::detail::BoundedForwardListIterator< T >::node(), and infra::detail::BoundedForwardListNode< T >::storage.
Referenced by infra::BoundedForwardList< T >::swap().
     {
         NodeType* node = position.node().next;
         position.node().next = 0;
         while (node != nullptr)
         {
             node->storage.Destruct();
             NodeType* oldFreeList = freeList;
             freeList = node;
             node = node->next;
             freeList->next = oldFreeList;
             --numAllocated;
         }
     }
erase_slow()
template<class T > void infra::BoundedForwardList< T >::erase_slow (iterator position)
Definition at line 446 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, and infra::detail::BoundedForwardListIterator< T >::node().
     {
         NodeType* node = &position.node();
         if (firstNode == node)
             firstNode = node->next;
         else
         {
             NodeType* previous = firstNode;
             while (previous->next != node)
                 previous = previous->next;
             previous->next = node->next;
         }
         node->next = freeList;
         freeList = node;
         --numAllocated;
     }
front() [1/2]
template<class T > BoundedForwardList< T >::value_type & infra::BoundedForwardList< T >::front ()
Definition at line 318 of file BoundedForwardList.hpp.
     {
         return *firstNode->storage;
     }
front() [2/2]
template<class T > const BoundedForwardList< T >::value_type & infra::BoundedForwardList< T >::front () const
Definition at line 324 of file BoundedForwardList.hpp.
     {
         return *firstNode->storage;
     }
full()
template<class T > bool infra::BoundedForwardList< T >::full () const
Definition at line 312 of file BoundedForwardList.hpp.
     {
         return numAllocated == storage.size();
     }
insert_after() [1/2]
template<class T > void infra::BoundedForwardList< T >::insert_after (iterator position, const value_type & value)
Definition at line 367 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, infra::detail::BoundedForwardListIterator< T >::node(), infra::detail::BoundedForwardListNode< T >::storage, and value.
Referenced by infra::BoundedForwardList< T >::swap().
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(value);
         node->next = position.node().next;
         position.node().next = node;
         ++numAllocated;
     }
insert_after() [2/2]
template<class T > void infra::BoundedForwardList< T >::insert_after (iterator position, value_type && value)
Definition at line 379 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, infra::detail::BoundedForwardListIterator< T >::node(), infra::detail::BoundedForwardListNode< T >::storage, and value.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(std::move(value));
         node->next = position.node().next;
         position.node().next = node;
         ++numAllocated;
     }
max_size()
template<class T > BoundedForwardList< T >::size_type infra::BoundedForwardList< T >::max_size () const
Definition at line 300 of file BoundedForwardList.hpp.
     {
         return storage.size();
     }
move_from_range()
template<class T > template<class InputIterator > void infra::BoundedForwardList< T >::move_from_range (InputIterator first, InputIterator last)
Definition at line 424 of file BoundedForwardList.hpp.
References infra::detail::begin().
Referenced by infra::BoundedForwardList< T >::BoundedForwardList().
     {
         clear();
         iterator current;
         while (first != last)
         {
             if (empty())
             {
                 push_front(std::move(*first));
                 current = begin();
             }
             else
             {
                 insert_after(current, std::move(*first));
                 ++current;
             }
             ++first;
         }
     }
operator!=()
template<class T > bool infra::BoundedForwardList< T >::operator!= (const BoundedForwardList< T > & other) const
Definition at line 561 of file BoundedForwardList.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T > bool infra::BoundedForwardList< T >::operator< (const BoundedForwardList< T > & other) const
Definition at line 567 of file BoundedForwardList.hpp.
References infra::detail::begin(), infra::BoundedForwardList< T >::begin(), infra::detail::end(), infra::BoundedForwardList< T >::end(), and infra::BoundedForwardList< T >::size().
     {
         const_iterator i1 = begin();
         const_iterator i2 = other.begin();
         while (i1 != end() && i2 != other.end())
         {
             if (*i1 < *i2)
                 return true;
             ++i1;
             ++i2;
         }
         return size() < other.size();
     }
operator<=()
template<class T > bool infra::BoundedForwardList< T >::operator<= (const BoundedForwardList< T > & other) const
Definition at line 585 of file BoundedForwardList.hpp.
     {
         return !(other < *this);
     }
operator=() [1/2]
template<class T > BoundedForwardList< T > & infra::BoundedForwardList< T >::operator= (const BoundedForwardList< T > & other)
Definition at line 224 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::begin(), and infra::BoundedForwardList< T >::end().
     {
         if (this != &other)
         {
             clear();
             assign(other.begin(), other.end());
         }
         return *this;
     }
operator=() [2/2]
template<class T > BoundedForwardList< T > & infra::BoundedForwardList< T >::operator= (BoundedForwardList< T > && other)
Definition at line 237 of file BoundedForwardList.hpp.
     {
         clear();
         move_from_range(other.begin(), other.end());
         return *this;
     }
operator==()
template<class T > bool infra::BoundedForwardList< T >::operator== (const BoundedForwardList< T > & other) const
Definition at line 554 of file BoundedForwardList.hpp.
References infra::detail::begin(), infra::BoundedForwardList< T >::begin(), infra::detail::end(), and infra::BoundedForwardList< T >::size().
     {
         return size() == other.size()
             && std::equal(begin(), end(), other.begin());
     }
operator>()
template<class T > bool infra::BoundedForwardList< T >::operator> (const BoundedForwardList< T > & other) const
Definition at line 591 of file BoundedForwardList.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T > bool infra::BoundedForwardList< T >::operator>= (const BoundedForwardList< T > & other) const
Definition at line 597 of file BoundedForwardList.hpp.
     {
         return !(*this < other);
     }
pop_front()
template<class T > void infra::BoundedForwardList< T >::pop_front ()
Definition at line 354 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next.
     {
         firstNode->storage.Destruct();
         NodeType* oldStart = firstNode;
         firstNode = firstNode->next;
         oldStart->next = freeList;
         freeList = oldStart;
         --numAllocated;
     }
push_front() [1/2]
template<class T > void infra::BoundedForwardList< T >::push_front (const value_type & value)
Definition at line 330 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, infra::detail::BoundedForwardListNode< T >::storage, and value.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(value);
         node->next = firstNode;
         firstNode = node;
         ++numAllocated;
     }
push_front() [2/2]
template<class T > void infra::BoundedForwardList< T >::push_front (value_type && value)
Definition at line 342 of file BoundedForwardList.hpp.
References infra::detail::BoundedForwardListNode< T >::next, infra::detail::BoundedForwardListNode< T >::storage, and value.
     {
         NodeType* node = AllocateNode();
         node->storage.Construct(std::move(value));
         node->next = firstNode;
         firstNode = node;
         ++numAllocated;
     }
size()
template<class T > BoundedForwardList< T >::size_type infra::BoundedForwardList< T >::size () const
Definition at line 294 of file BoundedForwardList.hpp.
Referenced by infra::BoundedForwardList< T >::operator<(), and infra::BoundedForwardList< T >::operator==().
     {
         return numAllocated;
     }
swap()
template<class T > void infra::BoundedForwardList< T >::swap (BoundedForwardList< T > & other)
Definition at line 486 of file BoundedForwardList.hpp.
References infra::detail::begin(), infra::BoundedForwardList< T >::begin(), infra::detail::end(), infra::BoundedForwardList< T >::end(), infra::BoundedForwardList< T >::erase_all_after(), infra::BoundedForwardList< T >::insert_after(), and infra::swap().
Referenced by infra::swap().
     {
         using std::swap;
         iterator i1 = begin();
         iterator i2 = other.begin();
         iterator i1old;
         iterator i2old;
         while (i1 != end() && i2 != other.end())
         {
             swap(*i1, *i2);
             i1old = i1;
             i2old = i2;
             ++i1;
             ++i2;
         }
         if (i1 != end())
         {
             iterator cutOff1 = i1old;
             while (i1 != end())
             {
                 other.insert_after(i2old, std::move(*i1));
                 ++i2old;
                 ++i1;
             }
             erase_all_after(cutOff1);
         }
         if (i2 != other.end())
         {
             iterator cutOff2 = i2old;
             while (i2 != other.end())
             {
                 insert_after(i1old, std::move(*i2));
                 ++i1old;
                 ++i2;
             }
             other.erase_all_after(cutOff2);
         }
     }
Member Data Documentation
firstNode
template<class T> NodeType* infra::BoundedForwardList< T >::firstNode = nullptr private
Definition at line 128 of file BoundedForwardList.hpp.
freeList
template<class T> NodeType* infra::BoundedForwardList< T >::freeList = nullptr private
Definition at line 129 of file BoundedForwardList.hpp.
numAllocated
template<class T> size_type infra::BoundedForwardList< T >::numAllocated = 0 private
Definition at line 126 of file BoundedForwardList.hpp.
numInitialized
template<class T> size_type infra::BoundedForwardList< T >::numInitialized = 0 private
Definition at line 127 of file BoundedForwardList.hpp.
storage
template<class T> infra::MemoryRange<infra::StaticStorage<detail::BoundedForwardListNode<T> > > infra::BoundedForwardList< T >::storage private
Definition at line 125 of file BoundedForwardList.hpp.
The documentation for this class was generated from the following file:
BoundedForwardList.hpp