EMil: NameResolverCacheTest Class Reference
NameResolverCacheTest Class Reference
Public Member Functions
NameResolverCacheTest ()
void Lookup (services::NameResolverResultMock &result)
void CancelLookup (services::NameResolverResultMock &result)
void ExpectNameLookupDone (services::NameResolverResultMock &result, services::IPAddress address)
void NameLookupDone (services::NameResolverResultMock &result, services::IPAddress address)
void NameLookupFailed (services::NameResolverResultMock &result)
void AddToCache (infra::BoundedConstString hostname, services::IPAddress address)
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
infra::BoundedConstString hostname1 = "hostname1"
infra::BoundedConstString hostname2 = "hostname2"
infra::BoundedConstString hostname3 = "hostname3"
const services::IPAddress address1 { services::IPv4Address{ 1, 2, 3, 4 } }
testing::StrictMock< services::NameResolverMock > resolver
services::NameResolverCache::WithCacheSize< 2 > resolverCache { resolver }
testing::StrictMock< services::NameResolverResultMock > result1
testing::StrictMock< services::NameResolverResultMock > result2
services::NameResolverResult * lookupResult = nullptr
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 7 of file TestNameResolverCache.cpp.
Constructor & Destructor Documentation
NameResolverCacheTest()
NameResolverCacheTest::NameResolverCacheTest () inline
Definition at line 12 of file TestNameResolverCache.cpp.
References services::both, hostname1, hostname2, result1, and result2.
     {
         EXPECT_CALL(result1, Hostname()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(hostname1));
         EXPECT_CALL(result1, Versions()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(services::IPVersions::both));
         EXPECT_CALL(result2, Hostname()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(hostname2));
         EXPECT_CALL(result2, Versions()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(services::IPVersions::both));
     }
Member Function Documentation
AddToCache()
void NameResolverCacheTest::AddToCache (infra::BoundedConstString hostname, services::IPAddress address) inline
Definition at line 49 of file TestNameResolverCache.cpp.
References services::both, Lookup(), and NameLookupDone().
     {
         testing::StrictMock<services::NameResolverResultMock> result;
         EXPECT_CALL(result, Hostname()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(hostname));
         EXPECT_CALL(result, Versions()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(services::IPVersions::both));
         Lookup(result);
         NameLookupDone(result, address);
     }
CancelLookup()
void NameResolverCacheTest::CancelLookup (services::NameResolverResultMock & result) inline
Definition at line 26 of file TestNameResolverCache.cpp.
References resolver, and resolverCache.
     {
         EXPECT_CALL(resolver, CancelLookup(testing::_));
         resolverCache.CancelLookup(result);
     }
ExpectNameLookupDone()
void NameResolverCacheTest::ExpectNameLookupDone (services::NameResolverResultMock & result, services::IPAddress address) inline
Definition at line 32 of file TestNameResolverCache.cpp.
References NameLookupDone(), and infra::Now().
Referenced by NameLookupDone().
     {
         EXPECT_CALL(result, NameLookupDone(address, infra::Now() + std::chrono::hours(1)));
     }
Lookup()
void NameResolverCacheTest::Lookup (services::NameResolverResultMock & result) inline
Definition at line 20 of file TestNameResolverCache.cpp.
References lookupResult, resolver, and resolverCache.
Referenced by AddToCache().
     {
         EXPECT_CALL(resolver, Lookup(testing::_)).WillOnce(infra::SaveRef<0>(&lookupResult));
         resolverCache.Lookup(result);
     }
NameLookupDone()
void NameResolverCacheTest::NameLookupDone (services::NameResolverResultMock & result, services::IPAddress address) inline
Definition at line 37 of file TestNameResolverCache.cpp.
References ExpectNameLookupDone(), lookupResult, services::NameResolverResult::NameLookupDone(), and infra::Now().
Referenced by AddToCache(), and ExpectNameLookupDone().
     {
         ExpectNameLookupDone(result, address);
         lookupResult->NameLookupDone(address, infra::Now() + std::chrono::hours(1));
     }
NameLookupFailed()
void NameResolverCacheTest::NameLookupFailed (services::NameResolverResultMock & result) inline
Definition at line 43 of file TestNameResolverCache.cpp.
References lookupResult, and services::NameResolverResult::NameLookupFailed().
     {
         EXPECT_CALL(result, NameLookupFailed());
         lookupResult->NameLookupFailed();
     }
Member Data Documentation
address1
const services::IPAddress NameResolverCacheTest::address1 { services::IPv4Address{ 1, 2, 3, 4 } }
Definition at line 63 of file TestNameResolverCache.cpp.
hostname1
infra::BoundedConstString NameResolverCacheTest::hostname1 = "hostname1"
Definition at line 60 of file TestNameResolverCache.cpp.
Referenced by NameResolverCacheTest().
hostname2
infra::BoundedConstString NameResolverCacheTest::hostname2 = "hostname2"
Definition at line 61 of file TestNameResolverCache.cpp.
Referenced by NameResolverCacheTest().
hostname3
infra::BoundedConstString NameResolverCacheTest::hostname3 = "hostname3"
Definition at line 62 of file TestNameResolverCache.cpp.
lookupResult
services::NameResolverResult* NameResolverCacheTest::lookupResult = nullptr
Definition at line 69 of file TestNameResolverCache.cpp.
Referenced by Lookup(), NameLookupDone(), and NameLookupFailed().
resolver
testing::StrictMock<services::NameResolverMock> NameResolverCacheTest::resolver
Definition at line 65 of file TestNameResolverCache.cpp.
Referenced by CancelLookup(), and Lookup().
resolverCache
services::NameResolverCache::WithCacheSize<2> NameResolverCacheTest::resolverCache { resolver }
Definition at line 66 of file TestNameResolverCache.cpp.
Referenced by CancelLookup(), and Lookup().
result1
testing::StrictMock<services::NameResolverResultMock> NameResolverCacheTest::result1
Definition at line 67 of file TestNameResolverCache.cpp.
Referenced by NameResolverCacheTest().
result2
testing::StrictMock<services::NameResolverResultMock> NameResolverCacheTest::result2
Definition at line 68 of file TestNameResolverCache.cpp.
Referenced by NameResolverCacheTest().
The documentation for this class was generated from the following file:
TestNameResolverCache.cpp