EMil: services::ClientConnectionObserverFactory Class Reference
services::ClientConnectionObserverFactory Class Reference abstract
#include <Connection.hpp>
Public Types
enum ConnectFailReason { refused, connectionAllocationFailed }
Public Member Functions
virtual IPAddress Address () const =0
virtual uint16_t Port () const =0
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver)=0
virtual void ConnectionFailed (ConnectFailReason reason)=0
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Protected Member Functions
ClientConnectionObserverFactory ()=default
ClientConnectionObserverFactory (const ClientConnectionObserverFactory &other)=delete
ClientConnectionObserverFactory & operator= (const ClientConnectionObserverFactory &other)=delete
~ClientConnectionObserverFactory ()=default
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 70 of file Connection.hpp.
Member Enumeration Documentation
ConnectFailReason
enum services::ClientConnectionObserverFactory::ConnectFailReason
Enumerator
refused
connectionAllocationFailed
Definition at line 80 of file Connection.hpp.
         {
             refused,
             connectionAllocationFailed
         };
Constructor & Destructor Documentation
ClientConnectionObserverFactory() [1/2]
services::ClientConnectionObserverFactory::ClientConnectionObserverFactory () protected default
ClientConnectionObserverFactory() [2/2]
services::ClientConnectionObserverFactory::ClientConnectionObserverFactory (const ClientConnectionObserverFactory & other) protected delete
~ClientConnectionObserverFactory()
services::ClientConnectionObserverFactory::~ClientConnectionObserverFactory () protected default
Member Function Documentation
Address()
virtual IPAddress services::ClientConnectionObserverFactory::Address () const pure virtual
Implemented in services::MqttClientConnectorImpl, services::ConnectionMbedTlsConnector, and services::ConnectionFactoryWithNameResolverImpl::Action.
Referenced by services::ConnectionMbedTlsConnector::Address(), services::EventDispatcherWithNetwork::Connect(), services::ConnectorBsd::ConnectorBsd(), and services::ConnectorWin::ConnectorWin().
ConnectionEstablished()
virtual void services::ClientConnectionObserverFactory::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver) pure virtual
Implemented in services::MqttClientConnectorImpl, services::ConnectionMbedTlsConnector, and services::ConnectionFactoryWithNameResolverImpl::Action.
Referenced by services::ConnectorBsd::Connected(), services::ConnectorWin::Connected(), and services::ConnectionMbedTlsConnector::ConnectionEstablished().
ConnectionFailed()
virtual void services::ClientConnectionObserverFactory::ConnectionFailed (ConnectFailReason reason) pure virtual
Implemented in services::MqttClientConnectorImpl, services::ConnectionMbedTlsConnector, and services::ConnectionFactoryWithNameResolverImpl::Action.
Referenced by services::ConnectionMbedTlsConnector::ConnectionFailed(), services::ConnectorBsd::Failed(), and services::ConnectorWin::Failed().
operator=()
ClientConnectionObserverFactory& services::ClientConnectionObserverFactory::operator= (const ClientConnectionObserverFactory & other) protected delete
Port()
virtual uint16_t services::ClientConnectionObserverFactory::Port () const pure virtual
Implemented in services::MqttClientConnectorImpl, services::ConnectionMbedTlsConnector, and services::ConnectionFactoryWithNameResolverImpl::Action.
Referenced by services::ConnectorBsd::ConnectorBsd(), services::ConnectorWin::ConnectorWin(), and services::ConnectionMbedTlsConnector::Port().
The documentation for this class was generated from the following file:
Connection.hpp