EMil: TestBitLogic.cpp File Reference
TestBitLogic.cpp File Reference
Functions
TEST (BitLogicTest, Bit)
TEST (BitLogicTest, SetBit)
TEST (BitLogicTest, ClearBit)
TEST (BitLogicTest, ReplaceBit_bool)
TEST (BitLogicTest, ReplaceBit_value)
TEST (BitLogicTest, ReplaceBits)
TEST (BitLogicTest, IsBitSet)
TEST (BitLogicTest, GetBits)
Function Documentation
TEST() [1/8]
TEST (BitLogicTest , Bit)
Definition at line 4 of file TestBitLogic.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(32, infra::Bit<uint32_t>(5));
 }
TEST() [2/8]
TEST (BitLogicTest , SetBit)
Definition at line 9 of file TestBitLogic.cpp.
References EXPECT_EQ(), and infra::SetBit().
 {
     uint32_t x = 1;
     infra::SetBit(x, 5);
     EXPECT_EQ(33, x);
 }
TEST() [3/8]
TEST (BitLogicTest , ClearBit)
Definition at line 16 of file TestBitLogic.cpp.
References infra::ClearBit(), and EXPECT_EQ().
 {
     uint32_t x = 33;
     infra::ClearBit(x, 5);
     EXPECT_EQ(1, x);
 }
TEST() [4/8]
TEST (BitLogicTest , ReplaceBit_bool)
Definition at line 23 of file TestBitLogic.cpp.
References EXPECT_EQ(), and infra::ReplaceBit().
 {
     uint32_t x = 1;
     infra::ReplaceBit(x, true, 5);
     EXPECT_EQ(33, x);
 }
TEST() [5/8]
TEST (BitLogicTest , ReplaceBit_value)
Definition at line 30 of file TestBitLogic.cpp.
References EXPECT_EQ(), and infra::ReplaceBit().
 {
     uint32_t x = 1;
     infra::ReplaceBit(x, static_cast<uint32_t>(1), 5);
     EXPECT_EQ(33, x);
 }
TEST() [6/8]
TEST (BitLogicTest , ReplaceBits)
Definition at line 37 of file TestBitLogic.cpp.
References EXPECT_EQ(), and infra::ReplaceBits().
 {
     uint32_t x = 1;
     infra::ReplaceBits(x, 2, 2, 0);
     EXPECT_EQ(2, x);
 }
TEST() [7/8]
TEST (BitLogicTest , IsBitSet)
Definition at line 44 of file TestBitLogic.cpp.
References EXPECT_TRUE(), and infra::IsBitSet().
 {
     uint32_t x = 32;
     EXPECT_TRUE(infra::IsBitSet(x, 5));
 }
TEST() [8/8]
TEST (BitLogicTest , GetBits)
Definition at line 50 of file TestBitLogic.cpp.
References EXPECT_EQ(), and infra::GetBits().
 {
     uint32_t x = 2;
     EXPECT_EQ(2, infra::GetBits(x, 1, 1));
 }