EMil: services::Terminal Class Reference
services::Terminal Class Reference
#include <Terminal.hpp>
Classes
struct TerminalState
Public Member Functions
Terminal (hal::SerialCommunication &communication)
void Print (const char *message)
virtual void OnData (infra::BoundedString data)
Private Member Functions
void HandleInput ()
void HandleChar (char in)
void HandleNonEscapeChar (char c)
bool ProcessEscapeSequence (char in)
void ProcessEnter ()
void ProcessBackspace ()
void ProcessDelete ()
void EraseCharacterUnderCursor ()
void MoveCursorHome ()
void MoveCursorEnd ()
void MoveCursorLeft ()
void MoveCursorRight ()
void OverwriteBuffer (infra::BoundedConstString element)
void StoreHistory (infra::BoundedString element)
void HistoryForward ()
void HistoryBackward ()
void SendNonEscapeChar (char c)
void SendBell ()
Private Attributes
TerminalState state
hal::SerialCommunication & communication
infra::QueueForOneReaderOneIrqWriter< uint8_t >::WithStorage< 32 > queue
infra::BoundedString::WithStorage< 256 > buffer
infra::BoundedDeque< decltype(buffer)>::WithMaxSize< 4 > history
bool sendDone = true
Detailed Description
Definition at line 11 of file Terminal.hpp.
Constructor & Destructor Documentation
Terminal()
services::Terminal::Terminal (hal::SerialCommunication & communication) explicit
Definition at line 5 of file Terminal.cpp.
References HandleInput().
         : communication(communication)
         , queue([this] { HandleInput(); })
     {
         communication.ReceiveData([this](infra::ConstByteRange data) { for (uint8_t element : data) queue.AddFromInterrupt(element); });
         Print(state.prompt);
     }
Member Function Documentation
EraseCharacterUnderCursor()
void services::Terminal::EraseCharacterUnderCursor () private
Definition at line 146 of file Terminal.cpp.
References buffer, communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeByteRange(), infra::MakeRange(), Print(), hal::SerialCommunication::SendData(), and state.
Referenced by ProcessDelete().
     {
         assert(state.cursorPosition < buffer.size());
         if (buffer.size() == state.cursorPosition + 1)
             buffer.pop_back();
         else
         {
             std::rotate(std::next(buffer.begin(), state.cursorPosition), std::next(buffer.begin(), state.cursorPosition + 1), buffer.end());
             buffer = buffer.substr(0, buffer.size() - 1);
             communication.SendData(infra::MakeRange(reinterpret_cast<const uint8_t*>(std::next(buffer.begin(), state.cursorPosition)), reinterpret_cast<const uint8_t*>(buffer.end())), infra::emptyFunction);
         }
         Print(" \b");
         for (uint32_t i = buffer.size(); i > state.cursorPosition; --i)
             communication.SendData(infra::MakeByteRange('\b'), infra::emptyFunction);
     }
HandleChar()
void services::Terminal::HandleChar (char in) private
Definition at line 29 of file Terminal.cpp.
References HandleNonEscapeChar(), ProcessEscapeSequence(), services::Terminal::TerminalState::processingEscapeSequence, and state.
Referenced by HandleInput().
     {
         if (state.processingEscapeSequence)
             state.processingEscapeSequence = ProcessEscapeSequence(c);
         else
             HandleNonEscapeChar(c);
     }
HandleInput()
void services::Terminal::HandleInput () private
Definition at line 23 of file Terminal.cpp.
References infra::QueueForOneReaderOneIrqWriter< T >::Empty(), infra::QueueForOneReaderOneIrqWriter< T >::Get(), HandleChar(), and queue.
Referenced by Terminal().
     {
         while (!queue.Empty())
             HandleChar(static_cast<char>(queue.Get()));
     }
HandleNonEscapeChar()
void services::Terminal::HandleNonEscapeChar (char c) private
Definition at line 37 of file Terminal.cpp.
References HistoryBackward(), HistoryForward(), MoveCursorEnd(), MoveCursorHome(), MoveCursorLeft(), MoveCursorRight(), OverwriteBuffer(), ProcessBackspace(), ProcessDelete(), ProcessEnter(), services::Terminal::TerminalState::processingEscapeSequence, SendNonEscapeChar(), and state.
Referenced by HandleChar().
     {
         switch (c)
         {
             case '\n':
                 break;
             case '\r':
                 ProcessEnter();
                 break;
             case 27:
                 state.processingEscapeSequence = true;
                 break;
             case '\b':
             case '\x7F':
                 ProcessBackspace();
                 break;
             case 1: // ctrl-a
                 MoveCursorHome();
                 break;
             case 2: // ctrl-b
                 MoveCursorLeft();
                 break;
             case 3: // ctrl-c
                 OverwriteBuffer("");
                 break;
             case 4: // ctrl-d
                 ProcessDelete();
                 break;
             case 5: // ctrl-e
                 MoveCursorEnd();
                 break;
             case 6: // ctrl-f
                 MoveCursorRight();
                 break;
             case 14: // ctrl-n
                 HistoryForward();
                 break;
             case 16: // ctrl-p
                 HistoryBackward();
                 break;
             default:
                 SendNonEscapeChar(c);
                 break;
         }
     }
HistoryBackward()
void services::Terminal::HistoryBackward () private
Definition at line 239 of file Terminal.cpp.
References history, services::Terminal::TerminalState::historyIndex, OverwriteBuffer(), SendBell(), and state.
Referenced by HandleNonEscapeChar(), and ProcessEscapeSequence().
     {
         if (state.historyIndex > 0)
             OverwriteBuffer(history[--state.historyIndex]);
         else
             SendBell();
     }
HistoryForward()
void services::Terminal::HistoryForward () private
Definition at line 231 of file Terminal.cpp.
References infra::BoundedDeque< T >::empty(), history, services::Terminal::TerminalState::historyIndex, OverwriteBuffer(), infra::BoundedDeque< T >::size(), and state.
Referenced by HandleNonEscapeChar(), and ProcessEscapeSequence().
     {
         if (!history.empty() && state.historyIndex < history.size() - 1)
             OverwriteBuffer(history[++state.historyIndex]);
         else
             OverwriteBuffer("");
     }
MoveCursorEnd()
void services::Terminal::MoveCursorEnd () private
Definition at line 173 of file Terminal.cpp.
References buffer, communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeRange(), hal::SerialCommunication::SendData(), and state.
Referenced by HandleNonEscapeChar(), and ProcessEscapeSequence().
     {
         if (buffer.size() > 0 && state.cursorPosition < buffer.size())
             communication.SendData(infra::MakeRange(reinterpret_cast<const uint8_t*>(std::next(buffer.begin(), state.cursorPosition)), reinterpret_cast<const uint8_t*>(buffer.end())), infra::emptyFunction);
         state.cursorPosition = buffer.size();
     }
MoveCursorHome()
void services::Terminal::MoveCursorHome () private
Definition at line 166 of file Terminal.cpp.
References communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeByteRange(), Print(), services::Terminal::TerminalState::prompt, hal::SerialCommunication::SendData(), and state.
Referenced by HandleNonEscapeChar(), and ProcessEscapeSequence().
     {
         state.cursorPosition = 0;
         communication.SendData(infra::MakeByteRange('\r'), infra::emptyFunction);
         Print(state.prompt);
     }
MoveCursorLeft()
void services::Terminal::MoveCursorLeft () private
Definition at line 180 of file Terminal.cpp.
References communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeByteRange(), SendBell(), hal::SerialCommunication::SendData(), and state.
Referenced by HandleNonEscapeChar(), ProcessBackspace(), and ProcessEscapeSequence().
     {
         if (state.cursorPosition > 0)
         {
             communication.SendData(infra::MakeByteRange('\b'), infra::emptyFunction);
             --state.cursorPosition;
         }
         else
             SendBell();
     }
MoveCursorRight()
void services::Terminal::MoveCursorRight () private
Definition at line 191 of file Terminal.cpp.
References buffer, communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeByteRange(), SendBell(), hal::SerialCommunication::SendData(), and state.
Referenced by HandleNonEscapeChar(), and ProcessEscapeSequence().
     {
         if (state.cursorPosition < buffer.size())
         {
             communication.SendData(infra::MakeByteRange(buffer[state.cursorPosition]), infra::emptyFunction);
             ++state.cursorPosition;
         }
         else
             SendBell();
     }
OnData()
virtual void services::Terminal::OnData (infra::BoundedString data) inline virtual
Definition at line 17 of file Terminal.hpp.
Referenced by ProcessEnter().
 {}
OverwriteBuffer()
void services::Terminal::OverwriteBuffer (infra::BoundedConstString element) private
Definition at line 211 of file Terminal.cpp.
References buffer, communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeByteRange(), infra::MakeRange(), Print(), services::Terminal::TerminalState::prompt, hal::SerialCommunication::SendData(), and state.
Referenced by HandleNonEscapeChar(), HistoryBackward(), and HistoryForward().
     {
         std::size_t previousSize = buffer.size();
         buffer = element;
         communication.SendData(infra::MakeByteRange('\r'), infra::emptyFunction);
         Print(state.prompt);
         if (buffer.size() > 0)
             communication.SendData(infra::MakeRange(reinterpret_cast<const uint8_t*>(buffer.begin()), reinterpret_cast<const uint8_t*>(buffer.end())), infra::emptyFunction);
         for (std::size_t size = buffer.size(); size < previousSize; ++size)
             communication.SendData(infra::MakeByteRange(' '), infra::emptyFunction);
         for (std::size_t size = buffer.size(); size < previousSize; ++size)
             communication.SendData(infra::MakeByteRange('\b'), infra::emptyFunction);
         state.cursorPosition = buffer.size();
     }
Print()
void services::Terminal::Print (const char * message)
Definition at line 13 of file Terminal.cpp.
References communication, infra::data, infra::MakeRange(), infra::ReinterpretCastByteRange(), hal::SerialCommunication::SendData(), and sendDone.
Referenced by EraseCharacterUnderCursor(), MoveCursorHome(), OverwriteBuffer(), and ProcessEnter().
     {
         if (sendDone)
         {
             sendDone = false;
             infra::ConstByteRange data = infra::ReinterpretCastByteRange(infra::MakeRange(message, message + strlen(message)));
             communication.SendData(data, [this]() { sendDone = true; });
         }
     }
ProcessBackspace()
void services::Terminal::ProcessBackspace () private
Definition at line 132 of file Terminal.cpp.
References MoveCursorLeft(), and ProcessDelete().
Referenced by HandleNonEscapeChar().
     {
         MoveCursorLeft();
         ProcessDelete();
     }
ProcessDelete()
void services::Terminal::ProcessDelete () private
Definition at line 138 of file Terminal.cpp.
References buffer, services::Terminal::TerminalState::cursorPosition, EraseCharacterUnderCursor(), SendBell(), and state.
Referenced by HandleNonEscapeChar(), and ProcessBackspace().
     {
         if (state.cursorPosition < buffer.size())
             EraseCharacterUnderCursor();
         else
             SendBell();
     }
ProcessEnter()
void services::Terminal::ProcessEnter () private
Definition at line 117 of file Terminal.cpp.
References buffer, services::Terminal::TerminalState::cursorPosition, OnData(), Print(), services::Terminal::TerminalState::prompt, state, and StoreHistory().
Referenced by HandleNonEscapeChar().
     {
         Print("\r\n");
         if (buffer.size() > 0)
         {
             StoreHistory(buffer);
             OnData(buffer);
         }
         buffer.clear();
         state.cursorPosition = 0;
         Print(state.prompt);
     }
ProcessEscapeSequence()
bool services::Terminal::ProcessEscapeSequence (char in) private
Definition at line 83 of file Terminal.cpp.
References infra::BoundedStringBase< T >::find(), HistoryBackward(), HistoryForward(), MoveCursorEnd(), MoveCursorHome(), MoveCursorLeft(), MoveCursorRight(), infra::BoundedStringBase< const char >::npos, and SendBell().
Referenced by HandleChar().
     {
         static const infra::BoundedConstString ignoredEscapeCharacters = ";[O0123456789";
         if (ignoredEscapeCharacters.find(in) != infra::BoundedConstString::npos)
             return true;
         switch (in)
         {
             case 'A':
                 HistoryBackward();
                 break;
             case 'B':
                 HistoryForward();
                 break;
             case 'C':
                 MoveCursorRight();
                 break;
             case 'D':
                 MoveCursorLeft();
                 break;
             case 'F':
                 MoveCursorEnd();
                 break;
             case 'H':
                 MoveCursorHome();
                 break;
             default:
                 SendBell();
                 break;
         }
         return false;
     }
SendBell()
void services::Terminal::SendBell () private
Definition at line 259 of file Terminal.cpp.
References communication, infra::emptyFunction, infra::MakeByteRange(), and hal::SerialCommunication::SendData().
Referenced by HistoryBackward(), MoveCursorLeft(), MoveCursorRight(), ProcessDelete(), ProcessEscapeSequence(), and SendNonEscapeChar().
     {
         communication.SendData(infra::MakeByteRange('\a'), infra::emptyFunction);
     }
SendNonEscapeChar()
void services::Terminal::SendNonEscapeChar (char c) private
Definition at line 247 of file Terminal.cpp.
References buffer, communication, services::Terminal::TerminalState::cursorPosition, infra::emptyFunction, infra::MakeByteRange(), SendBell(), hal::SerialCommunication::SendData(), and state.
Referenced by HandleNonEscapeChar().
     {
         if (c > 31 && c < 127)
         {
             communication.SendData(infra::MakeByteRange(c), infra::emptyFunction);
             buffer.push_back(c);
             state.cursorPosition++;
         }
         else
             SendBell();
     }
StoreHistory()
void services::Terminal::StoreHistory (infra::BoundedString element) private
Definition at line 202 of file Terminal.cpp.
References buffer, infra::BoundedDeque< T >::full(), history, services::Terminal::TerminalState::historyIndex, infra::BoundedDeque< T >::pop_front(), infra::BoundedDeque< T >::push_back(), infra::BoundedDeque< T >::size(), and state.
Referenced by ProcessEnter().
     {
         if (history.full())
             history.pop_front();
         history.push_back(buffer);
         state.historyIndex = history.size();
     }
Member Data Documentation
buffer
infra::BoundedString::WithStorage<256> services::Terminal::buffer private
Definition at line 56 of file Terminal.hpp.
Referenced by EraseCharacterUnderCursor(), MoveCursorEnd(), MoveCursorRight(), OverwriteBuffer(), ProcessDelete(), ProcessEnter(), SendNonEscapeChar(), and StoreHistory().
communication
hal::SerialCommunication& services::Terminal::communication private
Definition at line 54 of file Terminal.hpp.
Referenced by EraseCharacterUnderCursor(), MoveCursorEnd(), MoveCursorHome(), MoveCursorLeft(), MoveCursorRight(), OverwriteBuffer(), Print(), SendBell(), and SendNonEscapeChar().
history
infra::BoundedDeque<decltype(buffer)>::WithMaxSize<4> services::Terminal::history private
Definition at line 57 of file Terminal.hpp.
Referenced by HistoryBackward(), HistoryForward(), and StoreHistory().
queue
infra::QueueForOneReaderOneIrqWriter<uint8_t>::WithStorage<32> services::Terminal::queue private
Definition at line 55 of file Terminal.hpp.
Referenced by HandleInput().
sendDone
bool services::Terminal::sendDone = true private
Definition at line 58 of file Terminal.hpp.
Referenced by Print().
state
TerminalState services::Terminal::state private
Definition at line 53 of file Terminal.hpp.
Referenced by EraseCharacterUnderCursor(), HandleChar(), HandleNonEscapeChar(), HistoryBackward(), HistoryForward(), MoveCursorEnd(), MoveCursorHome(), MoveCursorLeft(), MoveCursorRight(), OverwriteBuffer(), ProcessDelete(), ProcessEnter(), SendNonEscapeChar(), and StoreHistory().
The documentation for this class was generated from the following files:
Terminal.hpp
Terminal.cpp