EMil: hal::GpioPin Class Reference
hal::GpioPin Class Reference abstract
#include <Gpio.hpp>
Public Member Functions
GpioPin ()=default
GpioPin (const GpioPin &other)=delete
GpioPin & operator= (const GpioPin &other)=delete
virtual bool Get () const =0
virtual void Set (bool value)=0
virtual bool GetOutputLatch () const =0
virtual void SetAsInput ()=0
virtual bool IsInput () const =0
virtual void Config (PinConfigType config)=0
virtual void Config (PinConfigType config, bool startOutputState)=0
virtual void ResetConfig ()=0
virtual void EnableInterrupt (const infra::Function< void()> &action, InterruptTrigger trigger)=0
virtual void DisableInterrupt ()=0
Protected Member Functions
~GpioPin ()=default
Detailed Description
Definition at line 26 of file Gpio.hpp.
Constructor & Destructor Documentation
GpioPin() [1/2]
hal::GpioPin::GpioPin () default
GpioPin() [2/2]
hal::GpioPin::GpioPin (const GpioPin & other) delete
~GpioPin()
hal::GpioPin::~GpioPin () protected default
Member Function Documentation
Config() [1/2]
virtual void hal::GpioPin::Config (PinConfigType config) pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::Config(), hal::InputPin::InputPin(), hal::OutputPin::OutputPin(), and hal::TriStatePin::TriStatePin().
Config() [2/2]
virtual void hal::GpioPin::Config (PinConfigType config, bool startOutputState) pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
DisableInterrupt()
virtual void hal::GpioPin::DisableInterrupt () pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::DisableInterrupt(), hal::InputPin::DisableInterrupt(), and hal::TriStatePin::DisableInterrupt().
EnableInterrupt()
virtual void hal::GpioPin::EnableInterrupt (const infra::Function< void()> & action, InterruptTrigger trigger) pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::DebouncedButton::DebouncedButton(), services::GpioPinInverted::EnableInterrupt(), hal::InputPin::EnableInterrupt(), hal::TriStatePin::EnableInterrupt(), and services::RepeatingButton::RepeatingButton().
Get()
virtual bool hal::GpioPin::Get () const pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::Get(), hal::InputPin::Get(), and hal::TriStatePin::Get().
GetOutputLatch()
virtual bool hal::GpioPin::GetOutputLatch () const pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::GetOutputLatch(), hal::OutputPin::GetOutputLatch(), and hal::TriStatePin::GetOutputLatch().
IsInput()
virtual bool hal::GpioPin::IsInput () const pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::IsInput(), and hal::TriStatePin::IsInput().
operator=()
GpioPin& hal::GpioPin::operator= (const GpioPin & other) delete
ResetConfig()
virtual void hal::GpioPin::ResetConfig () pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::ResetConfig(), hal::InputPin::~InputPin(), hal::OutputPin::~OutputPin(), and hal::TriStatePin::~TriStatePin().
Set()
virtual void hal::GpioPin::Set (bool value) pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::DebugLed::DebugLed(), services::GpioPinInverted::Set(), hal::OutputPin::Set(), and hal::TriStatePin::Set().
SetAsInput()
virtual void hal::GpioPin::SetAsInput () pure virtual
Implemented in hal::DummyPin, and services::GpioPinInverted.
Referenced by services::GpioPinInverted::SetAsInput(), and hal::TriStatePin::SetAsInput().
The documentation for this class was generated from the following file:
Gpio.hpp