EMil: TestSntpClient.cpp File Reference
TestSntpClient.cpp File Reference
Classes
class SntpClientTest
Functions
TEST_F (SntpClientTest, connects_to_server)
TEST_F (SntpClientTest, sends_time_request)
TEST_F (SntpClientTest, calls_TimeUnavailable_on_empty_response)
TEST_F (SntpClientTest, calls_TimeUnavailable_on_too_small_response)
TEST_F (SntpClientTest, calls_TimeUnavailble_on_invalid_header_values)
TEST_F (SntpClientTest, calls_TimeUnavailable_on_invalid_stratum)
TEST_F (SntpClientTest, calls_TimeUnavailable_on_zero_transmit_timestamp)
TEST_F (SntpClientTest, calls_TimeUnavailable_on_mismatching_originate_timestamp)
TEST_F (SntpClientTest, calls_TimeAvailable_on_valid_response)
TEST_F (SntpClientTest, calls_KissOfDeath_on_stratum_0_response)
Function Documentation
TEST_F() [1/10]
TEST_F (SntpClientTest , connects_to_server)
Definition at line 60 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(factory, Connect(testing::Ref(sntpClient), services::UdpSocket{ services::Udpv4Socket{ { 127, 0, 0, 1}, 123 } })).WillOnce(testing::Return(datagramExchangePtr));
     EXPECT_CALL(datagramExchange, RequestSendStream(48));
     sntpClient.RequestTime(services::IPv4Address{ 127, 0, 0, 1 });
 }
TEST_F() [2/10]
TEST_F (SntpClientTest , sends_time_request)
Definition at line 68 of file TestSntpClient.cpp.
References EXPECT_EQ(), and infra::UnOwnedSharedPtr().
 {
     infra::ByteOutputStreamWriter::WithStorage<512> response;
     sntpClient.SendStreamAvailable(infra::UnOwnedSharedPtr(response));
     EXPECT_EQ((std::array<uint8_t, 48>{ 0x23, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                         0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00 }), response.Processed());
 }
TEST_F() [3/10]
TEST_F (SntpClientTest , calls_TimeUnavailable_on_empty_response)
Definition at line 80 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     DataReceived(std::vector<uint8_t>{});
 }
TEST_F() [4/10]
TEST_F (SntpClientTest , calls_TimeUnavailable_on_too_small_response)
Definition at line 86 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     DataReceived(std::vector<uint8_t>{ 0 });
 }
TEST_F() [5/10]
TEST_F (SntpClientTest , calls_TimeUnavailble_on_invalid_header_values)
Definition at line 92 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     HeaderReceived(0b11100100);
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     HeaderReceived(0b00111100);
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     HeaderReceived(0b00100111);
 }
TEST_F() [6/10]
TEST_F (SntpClientTest , calls_TimeUnavailable_on_invalid_stratum)
Definition at line 104 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     DataReceived(std::vector<uint8_t>{ 0x24, 0x10, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00 });
 }
TEST_F() [7/10]
TEST_F (SntpClientTest , calls_TimeUnavailable_on_zero_transmit_timestamp)
Definition at line 115 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     DataReceived(std::vector<uint8_t>{ 0x24, 0x02, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 });
 }
TEST_F() [8/10]
TEST_F (SntpClientTest , calls_TimeUnavailable_on_mismatching_originate_timestamp)
Definition at line 126 of file TestSntpClient.cpp.
 {
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     DataReceived(std::vector<uint8_t>{ 0x24, 0x02, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00 });
 }
TEST_F() [9/10]
TEST_F (SntpClientTest , calls_TimeAvailable_on_valid_response)
Definition at line 137 of file TestSntpClient.cpp.
References infra::UnOwnedSharedPtr().
 {
     EXPECT_CALL(sntpObserver, TimeAvailable(infra::Duration{ 0 }, infra::Duration{ 0 }));
     infra::ByteOutputStreamWriter::WithStorage<512> response;
     sntpClient.SendStreamAvailable(infra::UnOwnedSharedPtr(response));
     DataReceived(std::vector<uint8_t>{ 0x24, 0x02, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
                                        0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00 });
 }
TEST_F() [10/10]
TEST_F (SntpClientTest , calls_KissOfDeath_on_stratum_0_response)
Definition at line 151 of file TestSntpClient.cpp.
References services::SntpResultObserver::deny, services::SntpResultObserver::rateExceeded, and services::SntpResultObserver::restrict.
 {
     EXPECT_CALL(sntpObserver, KissOfDeath(services::SntpResultObserver::KissCode::deny));
     KissOfDeathReceived('D', 'E', 'N', 'Y');
     EXPECT_CALL(sntpObserver, KissOfDeath(services::SntpResultObserver::KissCode::restrict));
     KissOfDeathReceived('R', 'S', 'T', 'R');
     EXPECT_CALL(sntpObserver, KissOfDeath(services::SntpResultObserver::KissCode::rateExceeded));
     KissOfDeathReceived('R', 'A', 'T', 'E');
     EXPECT_CALL(sntpObserver, TimeUnavailable());
     KissOfDeathReceived('S', 'T', 'E', 'P');
 }