EMil: services::StreamWriterOnSerialCommunication Class Reference
services::StreamWriterOnSerialCommunication Class Reference
#include <StreamWriterOnSerialCommunication.hpp>
Public Types
template<std::size_t StorageSize>
using WithStorage = infra::WithStorage< StreamWriterOnSerialCommunication, std::array< uint8_t, StorageSize > >
Public Member Functions
StreamWriterOnSerialCommunication (infra::ByteRange bufferStorage, hal::SerialCommunication &communication)
virtual void Insert (infra::ConstByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
Public Member Functions inherited from infra::StreamWriter
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Private Member Functions
void TrySend ()
void CommunicationDone (uint32_t size)
Private Attributes
infra::CyclicByteBuffer buffer
hal::SerialCommunication & communication
bool communicating = false
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 10 of file StreamWriterOnSerialCommunication.hpp.
Member Typedef Documentation
WithStorage
template<std::size_t StorageSize> using services::StreamWriterOnSerialCommunication::WithStorage = infra::WithStorage<StreamWriterOnSerialCommunication, std::array<uint8_t, StorageSize> >
Definition at line 15 of file StreamWriterOnSerialCommunication.hpp.
Constructor & Destructor Documentation
StreamWriterOnSerialCommunication()
services::StreamWriterOnSerialCommunication::StreamWriterOnSerialCommunication (infra::ByteRange bufferStorage, hal::SerialCommunication & communication)
Definition at line 5 of file StreamWriterOnSerialCommunication.cpp.
         : buffer(bufferStorage)
         , communication(communication)
     {}
Member Function Documentation
Available()
std::size_t services::StreamWriterOnSerialCommunication::Available () const override virtual
Implements infra::StreamWriter.
Definition at line 17 of file StreamWriterOnSerialCommunication.cpp.
     {
         return std::numeric_limits<size_t>::max();
     }
CommunicationDone()
void services::StreamWriterOnSerialCommunication::CommunicationDone (uint32_t size) private
Definition at line 33 of file StreamWriterOnSerialCommunication.cpp.
References buffer, communicating, and TrySend().
Referenced by TrySend().
     {
         communicating = false;
         buffer.Pop(size);
         TrySend();
     }
Insert()
void services::StreamWriterOnSerialCommunication::Insert (infra::ConstByteRange range, infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamWriter.
Definition at line 10 of file StreamWriterOnSerialCommunication.cpp.
References buffer, infra::MemoryRange< T >::shrink_from_back_to(), and TrySend().
     {
         range.shrink_from_back_to(buffer.Available());
         buffer.Push(range);
         TrySend();
     }
TrySend()
void services::StreamWriterOnSerialCommunication::TrySend () private
Definition at line 22 of file StreamWriterOnSerialCommunication.cpp.
References buffer, communicating, communication, CommunicationDone(), and hal::SerialCommunication::SendData().
Referenced by CommunicationDone(), and Insert().
     {
         if (!buffer.Empty() && !communicating)
         {
             communicating = true;
             uint32_t size = buffer.ContiguousRange().size();
             communication.SendData(buffer.ContiguousRange(), [this, size]() { CommunicationDone(size); });
         }
     }
Member Data Documentation
buffer
infra::CyclicByteBuffer services::StreamWriterOnSerialCommunication::buffer private
Definition at line 27 of file StreamWriterOnSerialCommunication.hpp.
Referenced by CommunicationDone(), Insert(), and TrySend().
communicating
bool services::StreamWriterOnSerialCommunication::communicating = false private
Definition at line 29 of file StreamWriterOnSerialCommunication.hpp.
Referenced by CommunicationDone(), and TrySend().
communication
hal::SerialCommunication& services::StreamWriterOnSerialCommunication::communication private
Definition at line 28 of file StreamWriterOnSerialCommunication.hpp.
Referenced by TrySend().
The documentation for this class was generated from the following files:
StreamWriterOnSerialCommunication.hpp
StreamWriterOnSerialCommunication.cpp