EMil: TestIntrusiveForwardList.cpp File Reference
TestIntrusiveForwardList.cpp File Reference
Classes
struct ForwardListInt
Functions
TEST (IntrusiveForwardListTest, TestConstructedEmpty)
TEST (IntrusiveForwardListTest, TestConstructionWithRange)
TEST (IntrusiveForwardListTest, TestMoveConstruction)
TEST (IntrusiveForwardListTest, TestMoveAssignment)
TEST (IntrusiveForwardListTest, IterateAfterMoveAssignment)
TEST (IntrusiveForwardListTest, TestBeginAndEnd)
TEST (IntrusiveForwardListTest, TestFront)
TEST (IntrusiveForwardListTest, TestNotHasElement)
TEST (IntrusiveForwardListTest, TestHasElement)
TEST (IntrusiveForwardListTest, TestAssignRange)
TEST (IntrusiveForwardListTest, TestAssignN)
TEST (IntrusiveForwardListTest, TestPushFront)
TEST (IntrusiveForwardListTest, TestPopFront)
TEST (IntrusiveForwardListTest, TestSwap)
TEST (IntrusiveForwardListTest, TestSwapDifferentSizes)
TEST (IntrusiveForwardListTest, TestClear)
TEST (IntrusiveForwardListTest, TestInsert)
TEST (IntrusiveForwardListTest, TestEraseAfter)
TEST (IntrusiveListTest, TestEraseSlowAtFront)
TEST (IntrusiveListTest, TestEraseSlow)
TEST (IntrusiveForwardListTest, TestEquals)
TEST (IntrusiveForwardListTest, TestUnequals)
TEST (IntrusiveForwardListTest, TestLessThan)
TEST (IntrusiveForwardListTest, TestGreaterThan)
TEST (IntrusiveForwardListTest, TestLessThanOrEqual)
TEST (IntrusiveForwardListTest, TestGreaterThanOrEqual)
Function Documentation
TEST() [1/26]
TEST (IntrusiveForwardListTest , TestConstructedEmpty)
Definition at line 24 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::empty(), and EXPECT_TRUE().
 {
     infra::IntrusiveForwardList<ForwardListInt> list;
     EXPECT_TRUE(list.empty());
 }
TEST() [2/26]
TEST (IntrusiveForwardListTest , TestConstructionWithRange)
Definition at line 31 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), and EXPECT_EQ().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     EXPECT_EQ(ForwardListInt(0), *list.begin());
     EXPECT_EQ(ForwardListInt(1), *std::next(list.begin()));
     EXPECT_EQ(ForwardListInt(2), *std::next(list.begin(), 2));
 }
TEST() [3/26]
TEST (IntrusiveForwardListTest , TestMoveConstruction)
Definition at line 41 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), infra::IntrusiveForwardList< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> original(range, range + 3);
     infra::IntrusiveForwardList<ForwardListInt> copy(std::move(original));
     EXPECT_EQ(ForwardListInt(0), copy.front());
     EXPECT_EQ(ForwardListInt(1), *std::next(copy.begin()));
     EXPECT_EQ(ForwardListInt(2), *std::next(copy.begin(), 2));
     EXPECT_TRUE(original.empty());
 }
TEST() [4/26]
TEST (IntrusiveForwardListTest , TestMoveAssignment)
Definition at line 53 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), infra::IntrusiveForwardList< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> original(range, range + 3);
     infra::IntrusiveForwardList<ForwardListInt> copy;
     copy = std::move(original);
     EXPECT_EQ(ForwardListInt(0), copy.front());
     EXPECT_EQ(ForwardListInt(1), *std::next(copy.begin()));
     EXPECT_EQ(ForwardListInt(2), *std::next(copy.begin(), 2));
     EXPECT_TRUE(original.empty());
 }
TEST() [5/26]
TEST (IntrusiveForwardListTest , IterateAfterMoveAssignment)
Definition at line 66 of file TestIntrusiveForwardList.cpp.
 {
     ForwardListInt range[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> original(range, range + 3);
     infra::IntrusiveForwardList<ForwardListInt> copy;
     copy = std::move(original);
     for (ForwardListInt& i: copy)
     {}
 }
TEST() [6/26]
TEST (IntrusiveForwardListTest , TestBeginAndEnd)
Definition at line 77 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), infra::IntrusiveForwardList< T >::cbegin(), infra::IntrusiveForwardList< T >::cend(), infra::IntrusiveForwardList< T >::end(), and EXPECT_EQ().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     EXPECT_EQ(list.end(), std::next(list.begin(), 3));
     EXPECT_EQ(list.cbegin(), list.begin());
     EXPECT_EQ(list.cend(), list.end());
     EXPECT_EQ(ForwardListInt(0), *list.begin());
 }
TEST() [7/26]
TEST (IntrusiveForwardListTest , TestFront)
Definition at line 89 of file TestIntrusiveForwardList.cpp.
References EXPECT_EQ(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     EXPECT_EQ(ForwardListInt(0), list.front());
 }
TEST() [8/26]
TEST (IntrusiveForwardListTest , TestNotHasElement)
Definition at line 97 of file TestIntrusiveForwardList.cpp.
References EXPECT_FALSE(), and infra::IntrusiveForwardList< T >::has_element().
 {
     infra::IntrusiveForwardList<ForwardListInt> list;
     ForwardListInt x(3);
     EXPECT_FALSE(list.has_element(x));
 }
TEST() [9/26]
TEST (IntrusiveForwardListTest , TestHasElement)
Definition at line 105 of file TestIntrusiveForwardList.cpp.
References EXPECT_TRUE(), infra::IntrusiveForwardList< T >::has_element(), and infra::IntrusiveForwardList< T >::push_front().
 {
     infra::IntrusiveForwardList<ForwardListInt> list;
     ForwardListInt x(3);
     list.push_front(x);
     EXPECT_TRUE(list.has_element(x));
 }
TEST() [10/26]
TEST (IntrusiveForwardListTest , TestAssignRange)
Definition at line 114 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::assign(), infra::IntrusiveForwardList< T >::begin(), EXPECT_EQ(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     ForwardListInt otherRange[2] = { 4, 5 };
     list.assign(otherRange, otherRange + 2);
     EXPECT_EQ(ForwardListInt(4), list.front());
     EXPECT_EQ(ForwardListInt(5), *std::next(list.begin()));
 }
TEST() [11/26]
TEST (IntrusiveForwardListTest , TestAssignN)
Definition at line 126 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::assign(), infra::IntrusiveForwardList< T >::begin(), EXPECT_EQ(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     ForwardListInt range2[2] = { 3, 4 };
     list.assign(range2, range2 + 2);
     EXPECT_EQ(ForwardListInt(3), list.front());
     EXPECT_EQ(ForwardListInt(4), *std::next(list.begin()));
 }
TEST() [12/26]
TEST (IntrusiveForwardListTest , TestPushFront)
Definition at line 138 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), EXPECT_EQ(), infra::IntrusiveForwardList< T >::front(), and infra::IntrusiveForwardList< T >::push_front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     ForwardListInt i1(1);
     list.push_front(i1);
     EXPECT_EQ(i1, list.front());
     EXPECT_EQ(ForwardListInt(0), *std::next(list.begin()));
 }
TEST() [13/26]
TEST (IntrusiveForwardListTest , TestPopFront)
Definition at line 149 of file TestIntrusiveForwardList.cpp.
References EXPECT_EQ(), infra::IntrusiveForwardList< T >::front(), and infra::IntrusiveForwardList< T >::pop_front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     list.pop_front();
     EXPECT_EQ(ForwardListInt(1), list.front());
 }
TEST() [14/26]
TEST (IntrusiveForwardListTest , TestSwap)
Definition at line 158 of file TestIntrusiveForwardList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     ForwardListInt range1[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     ForwardListInt range2[3] = { 3, 4, 5};
     infra::IntrusiveForwardList<ForwardListInt> list2(range2, range2 + 3);
     swap(list1, list2);
     infra::IntrusiveForwardList<ForwardListInt> expectedList1(range2, range2 + 3);
     infra::IntrusiveForwardList<ForwardListInt> expectedList2(range1, range1 + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [15/26]
TEST (IntrusiveForwardListTest , TestSwapDifferentSizes)
Definition at line 173 of file TestIntrusiveForwardList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     ForwardListInt range1[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     ForwardListInt range2[2] = { 3, 4};
     infra::IntrusiveForwardList<ForwardListInt> list2(range2, range2 + 2);
     swap(list1, list2);
     infra::IntrusiveForwardList<ForwardListInt> expectedList1(range2, range2 + 2);
     infra::IntrusiveForwardList<ForwardListInt> expectedList2(range1, range1 + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [16/26]
TEST (IntrusiveForwardListTest , TestClear)
Definition at line 188 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::clear(), infra::IntrusiveForwardList< T >::empty(), EXPECT_EQ(), and EXPECT_TRUE().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     list.clear();
     EXPECT_TRUE(list.empty());
     infra::IntrusiveForwardList<ForwardListInt> expectedList;
     EXPECT_EQ(expectedList, list);
 }
TEST() [17/26]
TEST (IntrusiveForwardListTest , TestInsert)
Definition at line 200 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), EXPECT_EQ(), infra::IntrusiveForwardList< T >::front(), and infra::IntrusiveForwardList< T >::insert_after().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     ForwardListInt i2(2);
     list.insert_after(list.begin(), i2);
     EXPECT_EQ(ForwardListInt(0), list.front());
     EXPECT_EQ(ForwardListInt(2), *std::next(list.begin()));
 }
TEST() [18/26]
TEST (IntrusiveForwardListTest , TestEraseAfter)
Definition at line 211 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), infra::IntrusiveForwardList< T >::erase_after(), EXPECT_EQ(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2};
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     list.erase_after(range[0]);
     EXPECT_EQ(ForwardListInt(0), list.front());
     EXPECT_EQ(ForwardListInt(2), *std::next(list.begin()));
 }
TEST() [19/26]
TEST (IntrusiveListTest , TestEraseSlowAtFront)
Definition at line 221 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), infra::IntrusiveForwardList< T >::erase_slow(), EXPECT_EQ(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     list.erase_slow(range[0]);
     EXPECT_EQ(ForwardListInt(1), list.front());
     EXPECT_EQ(ForwardListInt(2), *std::next(list.begin()));
 }
TEST() [20/26]
TEST (IntrusiveListTest , TestEraseSlow)
Definition at line 231 of file TestIntrusiveForwardList.cpp.
References infra::IntrusiveForwardList< T >::begin(), infra::IntrusiveForwardList< T >::erase_slow(), EXPECT_EQ(), and infra::IntrusiveForwardList< T >::front().
 {
     ForwardListInt range[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list(range, range + 3);
     list.erase_slow(range[1]);
     EXPECT_EQ(ForwardListInt(0), list.front());
     EXPECT_EQ(ForwardListInt(2), *std::next(list.begin()));
 }
TEST() [21/26]
TEST (IntrusiveForwardListTest , TestEquals)
Definition at line 241 of file TestIntrusiveForwardList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     ForwardListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     ForwardListInt range2[3] = { 3, 4, 5 };
     infra::IntrusiveForwardList<ForwardListInt> list2(range2, range2 + 3);
     ForwardListInt range3[2] = { 0, 1 };
     infra::IntrusiveForwardList<ForwardListInt> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 == list1);
     EXPECT_FALSE(list1 == list2);
     EXPECT_FALSE(list1 == deque3);
     EXPECT_FALSE(deque3 == list1);
 }
TEST() [22/26]
TEST (IntrusiveForwardListTest , TestUnequals)
Definition at line 256 of file TestIntrusiveForwardList.cpp.
References EXPECT_FALSE().
 {
     ForwardListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 != list1);
 }
TEST() [23/26]
TEST (IntrusiveForwardListTest , TestLessThan)
Definition at line 264 of file TestIntrusiveForwardList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     ForwardListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     ForwardListInt range2[3] = { 0, 4, 5 };
     infra::IntrusiveForwardList<ForwardListInt> list2(range2, range2 + 3);
     ForwardListInt range3[2] = { 0, 1 };
     infra::IntrusiveForwardList<ForwardListInt> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 < list2);
     EXPECT_FALSE(list1 < deque3);
     EXPECT_FALSE(list1 < list1);
 }
TEST() [24/26]
TEST (IntrusiveForwardListTest , TestGreaterThan)
Definition at line 278 of file TestIntrusiveForwardList.cpp.
References EXPECT_FALSE().
 {
     ForwardListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 > list1);
 }
TEST() [25/26]
TEST (IntrusiveForwardListTest , TestLessThanOrEqual)
Definition at line 286 of file TestIntrusiveForwardList.cpp.
References EXPECT_TRUE().
 {
     ForwardListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 <= list1);
 }
TEST() [26/26]
TEST (IntrusiveForwardListTest , TestGreaterThanOrEqual)
Definition at line 294 of file TestIntrusiveForwardList.cpp.
References EXPECT_TRUE().
 {
     ForwardListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveForwardList<ForwardListInt> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 >= list1);
 }