EMil: TestCyclicStore.cpp File Reference
TestCyclicStore.cpp File Reference
Classes
class CyclicStoreBaseTest
class CyclicStoreTest
Functions
TEST_F (CyclicStoreTest, AddFirstItem)
TEST_F (CyclicStoreTest, AddPartialItem)
TEST_F (CyclicStoreTest, AddSecondItem)
TEST_F (CyclicStoreTest, FillSector)
TEST_F (CyclicStoreTest, AddItemInNewSector)
TEST_F (CyclicStoreTest, FillUnusedSpaceWhenAddingItem)
TEST_F (CyclicStoreTest, FillOneByteOfUnusedSpaceWhenAddingItem)
TEST_F (CyclicStoreTest, AddFirstItemWhenFlashStopsAfterNSteps)
TEST_F (CyclicStoreTest, AddItemWhichCausesSectorToBeErased)
TEST_F (CyclicStoreTest, AddItemOverflowingSectorWhichCausesSectorToBeErased)
TEST_F (CyclicStoreTest, ReadFirstItem)
TEST_F (CyclicStoreTest, ReadFirstItemTwice)
TEST_F (CyclicStoreTest, ReadItemWithInsufficientBufferSpace)
TEST_F (CyclicStoreTest, ReadSecondItem)
TEST_F (CyclicStoreTest, ReadSecondItemInNewSector)
TEST_F (CyclicStoreTest, ReadSecondItemAfterSkipSpace)
TEST_F (CyclicStoreTest, ReadSecondItemAfterSkipSpaceOfOneByte)
TEST_F (CyclicStoreTest, ReadSecondItemAfterSkipSpaceReallySkipsSector)
TEST_F (CyclicStoreTest, ReadInEmptyYieldsEmptyRange)
TEST_F (CyclicStoreTest, ReadPastEndYieldsEmptyRange)
TEST_F (CyclicStoreTest, ReadPastEndInAFullFlashYieldsEmptyRange)
TEST_F (CyclicStoreTest, ReadWhileAddWaitsForAddToFinish)
TEST_F (CyclicStoreTest, AddWhileClearWaitsforClearToFinish)
TEST_F (CyclicStoreTest, ReadItemAfterCyclicalLogging)
TEST_F (CyclicStoreBaseTest, ReadItemAfterCyclicalLogging2)
TEST_F (CyclicStoreBaseTest, RecoverAndReadFirstItem)
TEST_F (CyclicStoreBaseTest, RecoverFromAllDifferentGoodScenarios)
TEST_F (CyclicStoreBaseTest, InAllCorruptScenariosFlashIsErased)
TEST_F (CyclicStoreBaseTest, AfterRecoveryItemsAreInsertedAfterCurrentContents)
TEST_F (CyclicStoreBaseTest, RecoveryAfterPartialWriteContinuesAtTheCorrectPosition)
TEST_F (CyclicStoreBaseTest, RecoveryAfterCorruptionContinuesAtTheNextSector)
TEST_F (CyclicStoreBaseTest, ReadSkipsIncompleteData)
TEST_F (CyclicStoreBaseTest, OnCorruptDataReadSkipsToNextSector)
TEST_F (CyclicStoreTest, WhenSectorIsErasedIteratorIsMovedForward)
TEST_F (CyclicStoreTest, TestParallelAddAndClear)
TEST_F (CyclicStoreTest, when_iterator_is_at_start_of_an_empty_sector_newly_added_item_is_available_in_next_read)
TEST_F (CyclicStoreBaseTest, when_iterator_is_at_the_end_of_flash_newly_added_item_is_available_in_next_read)
Function Documentation
TEST_F() [1/37]
TEST_F (CyclicStoreTest , AddFirstItem)
Definition at line 30 of file TestCyclicStore.cpp.
References data, and EXPECT_EQ().
 {
     infra::MockCallback<void()> done;
     std::vector<uint8_t> data = { 11, 12 };
     cyclicStore.Add(data, [&done]() { done.callback(); });
     EXPECT_CALL(done, callback());
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 0xfc, 0xf8, 2, 0, 11, 12, 0xff, 0xff, 0xff, 0xff }), flash.sectors[0]);
 }
TEST_F() [2/37]
TEST_F (CyclicStoreTest , AddPartialItem)
Definition at line 43 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11 };
     cyclicStore.AddPartial(data, 3, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 12 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> thirdData = { 13 };
     cyclicStore.Add(thirdData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 0xfc, 0xf8, 3, 0, 11, 12, 13, 0xff, 0xff, 0xff }), flash.sectors[0]);
 }
TEST_F() [3/37]
TEST_F (CyclicStoreTest , AddSecondItem)
Definition at line 58 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 12 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 0xfc, 0xf8, 1, 0, 11, 0xf8, 1, 0, 12, 0xff }), flash.sectors[0]);
 }
TEST_F() [4/37]
TEST_F (CyclicStoreTest , FillSector)
Definition at line 70 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 6, 0, 11, 12, 13, 14, 15, 16 },
         { 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
 }
TEST_F() [5/37]
TEST_F (CyclicStoreTest , AddItemInNewSector)
Definition at line 82 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 6, 0, 11, 12, 13, 14, 15, 16 },
         { 0xfe, 0xf8, 1, 0, 21, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
 }
TEST_F() [6/37]
TEST_F (CyclicStoreTest , FillUnusedSpaceWhenAddingItem)
Definition at line 97 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11, 12, 13 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 3, 0, 11, 12, 13, 0x7f, 0xff, 0xff },
         { 0xfe, 0xf8, 1, 0, 21, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
 }
TEST_F() [7/37]
TEST_F (CyclicStoreTest , FillOneByteOfUnusedSpaceWhenAddingItem)
Definition at line 112 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 5, 0, 11, 12, 13, 14, 15, 0x7f, },
         { 0xfe, 0xf8, 1, 0, 21, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
 }
TEST_F() [8/37]
TEST_F (CyclicStoreTest , AddFirstItemWhenFlashStopsAfterNSteps)
Definition at line 127 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<std::vector<uint8_t>> flashAfterNSteps;
     for (uint8_t i = 1; i != 7; ++i)
     {
         cyclicStore.Clear(infra::emptyFunction);
         ExecuteAllActions();
         flash.stopAfterWriteSteps = i;
         std::vector<uint8_t> data = { 11, 12 };
         cyclicStore.Add(data, infra::emptyFunction);
         ExecuteAllActions();
         flashAfterNSteps.push_back(flash.sectors[0]);
     }
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xfe,    2,    0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xfc,    2,    0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xfc,    2,    0,   11,   12, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xf8,    2,    0,   11,   12, 0xff, 0xff, 0xff, 0xff }
     }), flashAfterNSteps);
 }
TEST_F() [9/37]
TEST_F (CyclicStoreTest , AddItemWhichCausesSectorToBeErased)
Definition at line 154 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21, 22, 23, 24, 25, 26 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> thirdData = { 31, 32, 33, 34, 35, 36 };
     cyclicStore.Add(thirdData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfe, 0xf8, 6, 0, 31, 32, 33, 34, 35, 36 },
         { 0xfc, 0xf8, 6, 0, 21, 22, 23, 24, 25, 26 },
     }), flash.sectors);
 }
TEST_F() [10/37]
TEST_F (CyclicStoreTest , AddItemOverflowingSectorWhichCausesSectorToBeErased)
Definition at line 172 of file TestCyclicStore.cpp.
References data, infra::emptyFunction, and EXPECT_EQ().
 {
     flash.sectors[0].resize(14);
     flash.sectors[1].resize(14);
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21, 22, 23, 24, 25, 26 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> thirdData = { 31, 32, 33, 34, 35, 36 };
     cyclicStore.Add(thirdData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfe, 0xf8, 6, 0, 31, 32, 33, 34, 35, 36, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xf8, 6, 0, 21, 22, 23, 24, 25, 26, 0x7f, 0xff, 0xff, 0xff },
     }), flash.sectors);
 }
TEST_F() [11/37]
TEST_F (CyclicStoreTest , ReadFirstItem)
Definition at line 192 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [12/37]
TEST_F (CyclicStoreTest , ReadFirstItemTwice)
Definition at line 208 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     // build
     std::vector<uint8_t> data = { 11, 12 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
     // operate/check
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12 }));
     iterator = cyclicStore.Begin();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [13/37]
TEST_F (CyclicStoreTest , ReadItemWithInsufficientBufferSpace)
Definition at line 233 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(1, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [14/37]
TEST_F (CyclicStoreTest , ReadSecondItem)
Definition at line 249 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(20, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [15/37]
TEST_F (CyclicStoreTest , ReadSecondItemInNewSector)
Definition at line 269 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     ASSERT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 6, 0, 11, 12, 13, 14, 15, 16 },
         { 0xfe, 0xf8, 1, 0, 21, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [16/37]
TEST_F (CyclicStoreTest , ReadSecondItemAfterSkipSpace)
Definition at line 294 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     ASSERT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 3, 0, 11, 12, 13, 0x7f, 0xff, 0xff },
         { 0xfe, 0xf8, 1, 0, 21, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [17/37]
TEST_F (CyclicStoreTest , ReadSecondItemAfterSkipSpaceOfOneByte)
Definition at line 319 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     ASSERT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 5, 0, 11, 12, 13, 14, 15, 0x7f, },
         { 0xfe, 0xf8, 1, 0, 21, 0xff, 0xff, 0xff, 0xff, 0xff },
     }), flash.sectors);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [18/37]
TEST_F (CyclicStoreTest , ReadSecondItemAfterSkipSpaceReallySkipsSector)
Definition at line 344 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     flash.sectors = std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 1, 0, 11, 0x7f, 0xf8, 1, 0, 21 },
         { 0xfe, 0xf8, 1, 0, 31 },
     };
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 31 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [19/37]
TEST_F (CyclicStoreTest , ReadInEmptyYieldsEmptyRange)
Definition at line 362 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::empty(), and services::CyclicStore::Iterator::Read().
 {
     infra::MockCallback<void(bool)> mock;
     EXPECT_CALL(mock, callback(true));
     std::vector<uint8_t> readDataBuffer(2, 0);
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(result.empty()); });
     ExecuteAllActions();
 }
TEST_F() [20/37]
TEST_F (CyclicStoreTest , ReadPastEndYieldsEmptyRange)
Definition at line 373 of file TestCyclicStore.cpp.
References data, infra::MemoryRange< T >::empty(), infra::emptyFunction, and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void(bool)> mock;
     EXPECT_CALL(mock, callback(true));
     std::vector<uint8_t> readDataBuffer(2, 0);
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(result.empty()); });
     ExecuteAllActions();
 }
TEST_F() [21/37]
TEST_F (CyclicStoreTest , ReadPastEndInAFullFlashYieldsEmptyRange)
Definition at line 390 of file TestCyclicStore.cpp.
References data, infra::MemoryRange< T >::empty(), infra::emptyFunction, and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void(bool)> mock;
     EXPECT_CALL(mock, callback(true));
     std::vector<uint8_t> readDataBuffer(6, 0);
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) {});
     ExecuteAllActions();
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(result.empty()); });
     ExecuteAllActions();
 }
TEST_F() [22/37]
TEST_F (CyclicStoreTest , ReadWhileAddWaitsForAddToFinish)
Definition at line 412 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12 };
     cyclicStore.Add(data, infra::emptyFunction);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [23/37]
TEST_F (CyclicStoreTest , AddWhileClearWaitsforClearToFinish)
Definition at line 427 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     infra::MockCallback<void()> done;
     flash.delaySignalEraseDone = true;
     cyclicStore.Clear([&done]() { done.callback(); });
     infra::Function<void()> onEraseDone = flash.onEraseDone;
     ExecuteAllActions();
     flash.delaySignalEraseDone = false;
     std::vector<uint8_t> secondData = { 21, 22 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_CALL(done, callback());
     onEraseDone();
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21, 22 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [24/37]
TEST_F (CyclicStoreTest , ReadItemAfterCyclicalLogging)
Definition at line 457 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21, 22, 23, 24, 25, 26 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> thirdData = { 31, 32, 33, 34, 35, 36 };
     cyclicStore.Add(thirdData, infra::emptyFunction);
     ExecuteAllActions();
     ASSERT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfe, 0xf8, 6, 0, 31, 32, 33, 34, 35, 36 },
         { 0xfc, 0xf8, 6, 0, 21, 22, 23, 24, 25, 26 },
     }), flash.sectors);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21, 22, 23, 24, 25, 26 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(10, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [25/37]
TEST_F (CyclicStoreBaseTest , ReadItemAfterCyclicalLogging2)
Definition at line 484 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), services::CyclicStore::Begin(), infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<std::vector<uint8_t>> sectors =
         { { 0xfc, 0xf8, 6, 0, 11, 12, 13, 14, 15, 16 },
           { 0xfe, 0xf8, 6, 0, 21, 22, 23, 24, 25, 26 } };
     flash.sectors = sectors;
     services::CyclicStore cyclicStore(flash);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12, 13, 14, 15, 16 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(10, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
     std::vector<uint8_t> data = { 31, 32, 33, 34, 35, 36 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     ASSERT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfe, 0xf8, 6, 0, 31, 32, 33, 34, 35, 36 },
         { 0xfc, 0xf8, 6, 0, 21, 22, 23, 24, 25, 26 }
     }), flash.sectors);
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21, 22, 23, 24, 25, 26 }));
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [26/37]
TEST_F (CyclicStoreBaseTest , RecoverAndReadFirstItem)
Definition at line 515 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), services::CyclicStore::Begin(), infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     {
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         std::vector<uint8_t> data = { 11, 12 };
         cyclicStore.Add(data, infra::emptyFunction);
         ExecuteAllActions();
     }
     services::CyclicStore cyclicStore(flash);
     ExecuteAllActions();
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(2, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [27/37]
TEST_F (CyclicStoreBaseTest , RecoverFromAllDifferentGoodScenarios)
Definition at line 539 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), services::CyclicStore::Begin(), infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), EXPECT_EQ(), and services::CyclicStore::Iterator::Read().
 {
     struct Scenario
     {
         std::vector<uint8_t> expected;
         std::vector<std::vector<uint8_t>> flashContents;
         std::vector<std::vector<uint8_t>> flashContentsAfterAddition;
     };
     const std::vector<uint8_t> first = { 0xfc, 0xf8, 1, 0, 55 };
     const std::vector<uint8_t> empty = { 0xff, 0xff, 0xff, 0xff, 0xff };
     const std::vector<uint8_t> used = { 0xfe, 0xf8, 1, 0, 44 };
     const std::vector<uint8_t> written = { 0xfe, 0xf8, 1, 0, 66 };
     const std::vector<uint8_t> usedAsFirst = { 0xfc, 0xf8, 1, 0, 44 };
     const std::array<Scenario, 10> scenarios = { {
         {
             std::vector<uint8_t>{ 55 },
             std::vector<std::vector<uint8_t>>{ first, empty },
             std::vector<std::vector<uint8_t>>{ first, written }
         },
         {
             std::vector<uint8_t>{ 55 },
             std::vector<std::vector<uint8_t>>{ first, used, empty },
             std::vector<std::vector<uint8_t>>{ first, used, written }
         },
         {
             std::vector<uint8_t>{ 55 },
             std::vector<std::vector<uint8_t>>{ first, used, empty, empty },
             std::vector<std::vector<uint8_t>>{ first, used, written, empty }
         },
         {
             std::vector<uint8_t>{ 55 },
             std::vector<std::vector<uint8_t>>{ first, used, used },
             std::vector<std::vector<uint8_t>>{ written, usedAsFirst, used }
         },
         {
             std::vector<uint8_t>{ 44 },
             std::vector<std::vector<uint8_t>>{ used, empty, used },
             std::vector<std::vector<uint8_t>>{ used, written, usedAsFirst }
         },
         {
             std::vector<uint8_t>{ 44 },
             std::vector<std::vector<uint8_t>>{ empty, used, used},
             std::vector<std::vector<uint8_t>>{ written, usedAsFirst, used }
         },
         {
             std::vector<uint8_t>{ 44 },
             std::vector<std::vector<uint8_t>>{ used, empty },
             std::vector<std::vector<uint8_t>>{ usedAsFirst, written }
         },
         {
             std::vector<uint8_t>{ 55 },
             std::vector<std::vector<uint8_t>>{ used, first, used },
             std::vector<std::vector<uint8_t>>{ used, written, usedAsFirst }
         },
         {
             std::vector<uint8_t>{ 55 },
             std::vector<std::vector<uint8_t>>{ used, used, first },
             std::vector<std::vector<uint8_t>>{ usedAsFirst, used, written }
         },
         {
             std::vector<uint8_t>{ 44 },
             std::vector<std::vector<uint8_t>>{ used, used, empty, used, used },
             std::vector<std::vector<uint8_t>>{ used, used, written, usedAsFirst, used }
         }
     } };
     for (std::size_t index = 0; index != scenarios.size(); ++index)
     {
         flash.sectors = scenarios[index].flashContents;
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         infra::MockCallback<void(std::vector<uint8_t>, std::size_t)> mock;
         EXPECT_CALL(mock, callback(scenarios[index].expected, index));
         services::CyclicStore::Iterator iterator = cyclicStore.Begin();
         std::vector<uint8_t> readDataBuffer(10, 0);
         iterator.Read(readDataBuffer, [&mock, index](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end()), index); });
         ExecuteAllActions();
         std::vector<uint8_t> data = { 66 };
         cyclicStore.Add(data, infra::emptyFunction);
         ExecuteAllActions();
         EXPECT_EQ(scenarios[index].flashContentsAfterAddition, flash.sectors);
     }
 }
TEST_F() [28/37]
TEST_F (CyclicStoreBaseTest , InAllCorruptScenariosFlashIsErased)
Definition at line 630 of file TestCyclicStore.cpp.
References EXPECT_EQ().
 {
     const std::vector<uint8_t> first = { 0xfc, 0xf8, 1, 0, 55 };
     const std::vector<uint8_t> empty = { 0xff, 0xff, 0xff, 0xff, 0xff };
     const std::vector<uint8_t> used = { 0xfe, 0xf8, 1, 0, 44 };
     const std::vector<uint8_t> corrupt = { 0xaa, 0xf8, 1, 0, 44 };
     const std::array<std::vector<std::vector<uint8_t>>, 8> scenarios = { {
         std::vector<std::vector<uint8_t>>{ empty, first, empty },
         std::vector<std::vector<uint8_t>>{ used, first, empty },
         std::vector<std::vector<uint8_t>>{ empty, first, used },
         std::vector<std::vector<uint8_t>>{ empty, used, used, empty },
         std::vector<std::vector<uint8_t>>{ empty, used, empty, used },
         std::vector<std::vector<uint8_t>>{ used, empty, used, empty },
         std::vector<std::vector<uint8_t>>{ used, used, used },
         std::vector<std::vector<uint8_t>>{ first, used, corrupt },
     } };
     for (std::size_t index = 0; index != scenarios.size(); ++index)
     {
         flash.sectors = scenarios[index];
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         std::vector<std::vector<uint8_t>> emptyFlash = flash.sectors;
         for (auto& sector : emptyFlash)
             sector = std::vector<uint8_t>(sector.size(), 0xff);
         EXPECT_EQ(emptyFlash, flash.sectors);
     }
 }
TEST_F() [29/37]
TEST_F (CyclicStoreBaseTest , AfterRecoveryItemsAreInsertedAfterCurrentContents)
Definition at line 664 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), data, infra::emptyFunction, and EXPECT_EQ().
 {
     flash.sectors = std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 1, 0, 16, 0xff, 0xff, 0xff, 0xff },
         { 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff }
     };
     services::CyclicStore cyclicStore(flash);
     ExecuteAllActions();
     std::vector<uint8_t> data = { 32 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     EXPECT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 1, 0, 16, 0xf8, 1, 0, 32 },
         { 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff }
     }), flash.sectors);
 }
TEST_F() [30/37]
TEST_F (CyclicStoreBaseTest , RecoveryAfterPartialWriteContinuesAtTheCorrectPosition)
Definition at line 684 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), data, infra::emptyFunction, and EXPECT_EQ().
 {
     struct Scenario
     {
         std::vector<uint8_t> flashContents;
         std::vector<uint8_t> flashContentsAfterAdd;
     };
     const std::array<Scenario, 5> scenarios =
     { {
         {
             { 0xfc, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
             { 0xfc, 0xf8, 1, 0, 22, 0xff, 0xff, 0xff, 0xff, 0xff },
         },
         {
             { 0xfc, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
             { 0xfc, 0xfe, 0xff, 0xff, 0xf8, 1, 0, 22, 0xff, 0xff },
         },
         {
             { 0xfc, 0xfe, 2, 0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
             { 0xfc, 0xfe, 2, 0, 0xf8, 1, 0, 22, 0xff, 0xff },
         },
         {
             { 0xfc, 0xfc, 2, 0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
             { 0xfc, 0xfc, 2, 0, 0xff, 0xff, 0xf8, 1, 0, 22 },
         },
         {
             { 0xfc, 0xfc, 2, 0, 11, 12, 0xff, 0xff, 0xff, 0xff },
             { 0xfc, 0xfc, 2, 0, 11, 12, 0xf8, 1, 0, 22 },
         }
     } };
     for (std::size_t index = 0; index != scenarios.size(); ++index)
     {
         flash.sectors[0] = scenarios[index].flashContents;
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         std::vector<uint8_t> data = { 22 };
         cyclicStore.Add(data, infra::emptyFunction);
         ExecuteAllActions();
         EXPECT_EQ(scenarios[index].flashContentsAfterAdd, flash.sectors[0]);
     }
 }
TEST_F() [31/37]
TEST_F (CyclicStoreBaseTest , RecoveryAfterCorruptionContinuesAtTheNextSector)
Definition at line 731 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), data, infra::emptyFunction, and EXPECT_EQ().
 {
     const std::array<std::vector<uint8_t>, 3> scenarios =
     { {
         { 0xfc, 0xaa, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xf8, 0xaa, 0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff },
         { 0xfc, 0xfc, 2, 0, 11, 12, 0xaa, 0xff, 0xff, 0xff }
     } };
     const std::vector<uint8_t> nextSector = { 0xfe, 0xf8, 1, 0, 22, 0xff, 0xff, 0xff, 0xff, 0xff };
     for (std::size_t index = 0; index != scenarios.size(); ++index)
     {
         flash.sectors[0] = scenarios[index];
         flash.sectors[1] = { 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff };
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         std::vector<uint8_t> data = { 22 };
         cyclicStore.Add(data, infra::emptyFunction);
         ExecuteAllActions();
         EXPECT_EQ(nextSector, flash.sectors[1]);
     }
 }
TEST_F() [32/37]
TEST_F (CyclicStoreBaseTest , ReadSkipsIncompleteData)
Definition at line 758 of file TestCyclicStore.cpp.
References services::CyclicStore::Begin(), infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     const std::array<std::vector<uint8_t>, 4> scenarios =
     { {
             { 0xfc, 0xfe, 0xff, 0xff, 0xf8, 1, 0, 22, 0xff, 0xff },
             { 0xfc, 0xfe, 2, 0, 0xf8, 1, 0, 22, 0xff, 0xff },
             { 0xfc, 0xfc, 2, 0, 0xff, 0xff, 0xf8, 1, 0, 22 },
             { 0xfc, 0xfc, 2, 0, 11, 12, 0xf8, 1, 0, 22 },
     } };
     for (std::size_t index = 0; index != scenarios.size(); ++index)
     {
         flash.sectors[0] = scenarios[index];
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         infra::MockCallback<void(std::vector<uint8_t>)> mock;
         EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 22 }));
         services::CyclicStore::Iterator iterator = cyclicStore.Begin();
         std::vector<uint8_t> readDataBuffer(2, 0);
         iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
         ExecuteAllActions();
     }
 }
TEST_F() [33/37]
TEST_F (CyclicStoreBaseTest , OnCorruptDataReadSkipsToNextSector)
Definition at line 785 of file TestCyclicStore.cpp.
References services::CyclicStore::Begin(), infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     const std::array<std::vector<uint8_t>, 3> scenarios =
     { {
         { 0xfc, 0xaa, 0xf8, 1, 0, 22 },
         { 0xfc, 0xf8, 0xaa, 0, 0xf8, 1, 0, 22 },
         { 0xfc, 0xfc, 2, 0, 11, 12, 0xaa, 0xf8, 1, 0, 22 }
     } };
     flash.sectors[1] = { 0xfe, 0xf8, 1, 0, 33 };
     for (std::size_t index = 0; index != scenarios.size(); ++index)
     {
         flash.sectors[0] = scenarios[index];
         services::CyclicStore cyclicStore(flash);
         ExecuteAllActions();
         infra::MockCallback<void(std::vector<uint8_t>)> mock;
         EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 33 }));
         services::CyclicStore::Iterator iterator = cyclicStore.Begin();
         std::vector<uint8_t> readDataBuffer(2, 0);
         iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
         ExecuteAllActions();
     }
 }
TEST_F() [34/37]
TEST_F (CyclicStoreTest , WhenSectorIsErasedIteratorIsMovedForward)
Definition at line 813 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> secondData = { 21, 22, 23, 24, 25, 26 };
     cyclicStore.Add(secondData, infra::emptyFunction);
     ExecuteAllActions();
     ASSERT_EQ((std::vector<std::vector<uint8_t>>{
         { 0xfc, 0xf8, 6, 0, 11, 12, 13, 14, 15, 16 },
         { 0xfe, 0xf8, 6, 0, 21, 22, 23, 24, 25, 26 },
     }), flash.sectors);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21, 22, 23, 24, 25, 26 }));
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> erasingSectorData = { 31 };
     cyclicStore.Add(erasingSectorData, infra::emptyFunction);
     ExecuteAllActions();
     std::vector<uint8_t> readDataBuffer(12, 0);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [35/37]
TEST_F (CyclicStoreTest , TestParallelAddAndClear)
Definition at line 841 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(6, 0);
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{}));
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     cyclicStore.Clear(infra::emptyFunction);
     ExecuteAllActions();
 }
TEST_F() [36/37]
TEST_F (CyclicStoreTest , when_iterator_is_at_start_of_an_empty_sector_newly_added_item_is_available_in_next_read)
Definition at line 858 of file TestCyclicStore.cpp.
References infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(6, 0);
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12, 13, 14, 15, 16 }));
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21, 22, 23, 24, 25, 26 }));
     std::vector<uint8_t> data2 = { 21, 22, 23, 24, 25, 26 };
     cyclicStore.Add(data2, infra::emptyFunction);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }
TEST_F() [37/37]
TEST_F (CyclicStoreBaseTest , when_iterator_is_at_the_end_of_flash_newly_added_item_is_available_in_next_read)
Definition at line 879 of file TestCyclicStore.cpp.
References services::CyclicStore::Add(), services::CyclicStore::Begin(), infra::MemoryRange< T >::begin(), data, infra::emptyFunction, infra::MemoryRange< T >::end(), and services::CyclicStore::Iterator::Read().
 {
     hal::FlashStub flash(2, 30);
     services::CyclicStore cyclicStore(flash);
     infra::MockCallback<void(std::vector<uint8_t>)> mock;
     services::CyclicStore::Iterator iterator = cyclicStore.Begin();
     std::vector<uint8_t> readDataBuffer(6, 0);
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 11, 12, 13, 14, 15, 16 }));
     std::vector<uint8_t> data = { 11, 12, 13, 14, 15, 16 };
     cyclicStore.Add(data, infra::emptyFunction);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
     EXPECT_CALL(mock, callback(std::vector<uint8_t>()));
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
     EXPECT_CALL(mock, callback(std::vector<uint8_t>{ 21, 22, 23, 24, 25, 26 }));
     std::vector<uint8_t> data2 = { 21, 22, 23, 24, 25, 26 };
     cyclicStore.Add(data2, infra::emptyFunction);
     iterator.Read(readDataBuffer, [&mock](infra::ByteRange result) { mock.callback(std::vector<uint8_t>(result.begin(), result.end())); });
     ExecuteAllActions();
 }