EMil: services::ConnectionSerial::StateConnected Class Reference
services::ConnectionSerial::StateConnected Class Reference
Public Member Functions
StateConnected (ConnectionSerial &connection)
virtual void EvaluatePendingSend () override
virtual void AckReceived () override
virtual void Reset () override
virtual void SizeRequestReceived () override
virtual void SizeResponseRequestReceived (size_t size) override
virtual void SizeResponseReceived (size_t size) override
virtual size_t ContentReceived (infra::ConstByteRange receivedRange) override
virtual void SizeUpdateReceived (size_t size) override
virtual void AccumulateWindowUpdateSize (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::State
State (ConnectionSerial &connection)
virtual ~State ()=default
Protected Member Functions
bool IsEscapedByte (uint8_t byte) const
Protected Attributes
infra::ByteRange & sendBuffer
Protected Attributes inherited from services::ConnectionSerial::State
ConnectionSerial & connection
hal::SerialCommunication & serialCommunication
Private Member Functions
bool UpdatePossible ()
size_t CopyEscapedContent (infra::ConstByteRange receivedRange)
size_t ContentSizeToSend () const
Detailed Description
Definition at line 198 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
StateConnected()
services::ConnectionSerial::StateConnected::StateConnected (ConnectionSerial & connection)
Definition at line 449 of file ConnectionSerial.cpp.
         : State(connection)
         , sendBuffer(connection.contentReadyForSend)
     {}
Member Function Documentation
AccumulateWindowUpdateSize()
void services::ConnectionSerial::StateConnected::AccumulateWindowUpdateSize (size_t size) override virtual
Implements services::ConnectionSerial::State.
Definition at line 561 of file ConnectionSerial.cpp.
     {
         if (connection.accumulatedWindowSizeUpdate)
             *connection.accumulatedWindowSizeUpdate += size;
         else
             connection.accumulatedWindowSizeUpdate.Emplace(size);
     }
AckReceived()
void services::ConnectionSerial::StateConnected::AckReceived () override virtual
Reimplemented from services::ConnectionSerial::State.
Definition at line 569 of file ConnectionSerial.cpp.
     {
         size_t bytesConsumed = connection.receivedDataReader->ConsumeExtracted();
         AccumulateWindowUpdateSize(bytesConsumed);
         EvaluatePendingSend();
     }
ContentReceived()
size_t services::ConnectionSerial::StateConnected::ContentReceived (infra::ConstByteRange receivedRange) override virtual
Implements services::ConnectionSerial::State.
Definition at line 613 of file ConnectionSerial.cpp.
References infra::MemoryRange< T >::size().
     {
         size_t copiedAmount = CopyEscapedContent(receivedRange);
         if (copiedAmount > 0) //What if we received only an escape byte?
             connection.NotifyObserverDataReceived();
         if (copiedAmount == receivedRange.size())
             connection.contentToReceive -= copiedAmount;
         else
         {
             connection.contentToReceive = 0;
             Reset();
         }
         return copiedAmount;
     }
ContentSizeToSend()
size_t services::ConnectionSerial::StateConnected::ContentSizeToSend () const private
Definition at line 465 of file ConnectionSerial.cpp.
References services::ConnectionSerial::MessageHeader::HeaderSize, services::ConnectionSerial::sendBuffer, and infra::MemoryRange< T >::size().
     {
         if (connection.totalContentSizeToSend != 0)
             return 0;
         size_t windowUpdateAndHeaderRoom = 2 * MessageHeader::HeaderSize;
         size_t maxContentSize = connection.peerBufferSize > windowUpdateAndHeaderRoom ? connection.peerBufferSize - windowUpdateAndHeaderRoom : 0;
         size_t contentSize = 0;
         for (size_t i=0; i<sendBuffer.size(); i++)
         {
             uint8_t incr = 0;
             if (IsEscapedByte(sendBuffer[i]))
                 ++incr;
             if (++incr + contentSize >= maxContentSize)
                 return maxContentSize;
             contentSize += incr;
         }
         return contentSize;
     }
CopyEscapedContent()
size_t services::ConnectionSerial::StateConnected::CopyEscapedContent (infra::ConstByteRange receivedRange) private
Definition at line 591 of file ConnectionSerial.cpp.
References services::ConnectionSerial::MessageHeader::IsEscapeByte(), services::ConnectionSerial::MessageHeader::IsHeaderByte(), and infra::MemoryRange< T >::size().
     {
         size_t copiedAmount = 0;
         for (; copiedAmount != receivedRange.size(); ++copiedAmount)
         {
             if (MessageHeader::IsEscapeByte(receivedRange[copiedAmount]) && !connection.isEscapeSeen)
             {
                 AccumulateWindowUpdateSize(1);
                 connection.isEscapeSeen = true;
             }
             else if (MessageHeader::IsHeaderByte(receivedRange[copiedAmount]) && !connection.isEscapeSeen)
                 break;
             else
             {
                 connection.receivedDataQueue.push_back(receivedRange[copiedAmount]);
                 connection.isEscapeSeen = false;
             }
         }
         return copiedAmount;
     }
EvaluatePendingSend()
void services::ConnectionSerial::StateConnected::EvaluatePendingSend () override virtual
Implements services::ConnectionSerial::State.
Reimplemented in services::ConnectionSerial::StateSending.
Definition at line 543 of file ConnectionSerial.cpp.
Referenced by services::ConnectionSerial::StateConnectedIdle::StateConnectedIdle().
     {
         if (UpdatePossible())
             connection.GoStateSendingUpdate();
         else
         {
             size_t contentSize = ContentSizeToSend();
             if (contentSize != 0)
                 connection.GoStateConnectedSendingContent(contentSize);
         }
     }
IsEscapedByte()
bool services::ConnectionSerial::StateConnected::IsEscapedByte (uint8_t byte) const protected
Definition at line 460 of file ConnectionSerial.cpp.
References services::ConnectionSerial::MessageHeader::IsEscapeByte(), and services::ConnectionSerial::MessageHeader::IsHeaderByte().
     {
         return MessageHeader::IsEscapeByte(byte) || MessageHeader::IsHeaderByte(byte);
     }
Reset()
void services::ConnectionSerial::StateConnected::Reset () override virtual
Implements services::ConnectionSerial::State.
Reimplemented in services::ConnectionSerial::StateSending.
Definition at line 454 of file ConnectionSerial.cpp.
References infra::MemoryRange< T >::clear(), and services::ConnectionSerial::sendBuffer.
Referenced by services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent(), and services::ConnectionSerial::StateSendingUpdate::SendUpdate().
     {
         sendBuffer.clear();
         connection.ResetConnection();
     }
SizeRequestReceived()
void services::ConnectionSerial::StateConnected::SizeRequestReceived () override virtual
Implements services::ConnectionSerial::State.
Definition at line 576 of file ConnectionSerial.cpp.
     {
         Reset();
     }
SizeResponseReceived()
void services::ConnectionSerial::StateConnected::SizeResponseReceived (size_t size) override virtual
Implements services::ConnectionSerial::State.
Definition at line 586 of file ConnectionSerial.cpp.
     {
         Reset();
     }
SizeResponseRequestReceived()
void services::ConnectionSerial::StateConnected::SizeResponseRequestReceived (size_t size) override virtual
Implements services::ConnectionSerial::State.
Definition at line 581 of file ConnectionSerial.cpp.
     {
         Reset();
     }
SizeUpdateReceived()
void services::ConnectionSerial::StateConnected::SizeUpdateReceived (size_t size) override virtual
Implements services::ConnectionSerial::State.
Definition at line 631 of file ConnectionSerial.cpp.
References services::ConnectionSerial::State::connection, and services::ConnectionSerial::peerBufferSize.
     {
         connection.peerBufferSize += size;
     }
UpdatePossible()
bool services::ConnectionSerial::StateConnected::UpdatePossible () private
Definition at line 555 of file ConnectionSerial.cpp.
References services::ConnectionSerial::MessageHeader::HeaderSize.
     {
         return connection.accumulatedWindowSizeUpdate.ValueOr(0) >= connection.minUpdateSize &&
                 !connection.updateInProgress && connection.peerBufferSize >= MessageHeader::HeaderSize;
     }
Member Data Documentation
sendBuffer
infra::ByteRange& services::ConnectionSerial::StateConnected::sendBuffer protected
Definition at line 224 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp