EMil: services::CyclicStore Class Reference
services::CyclicStore Class Reference
#include <CyclicStore.hpp>
Classes
struct BlockHeader
class Iterator
Public Member Functions
CyclicStore (hal::Flash &flash)
CyclicStore (const CyclicStore &other)=delete
CyclicStore & operator= (const CyclicStore &other)=delete
void Add (infra::ConstByteRange range, infra::Function< void()> onDone)
void AddPartial (infra::ConstByteRange range, uint32_t totalSize, infra::Function< void()> onDone)
void Clear (infra::Function< void()> onDone)
Iterator Begin () const
Private Types
enum BlockStatus : uint8_t {
BlockStatus::empty = 0xff, BlockStatus::emptyUntilEnd = 0x7f, BlockStatus::writingLength = 0xfe, BlockStatus::writingData = 0xfc,
BlockStatus::dataReady = 0xf8
}
enum SectorStatus : uint8_t { SectorStatus::empty = 0xff, SectorStatus::used = 0xfe, SectorStatus::firstInCycle = 0xfc }
enum RecoverPhase : uint8_t {
RecoverPhase::searchingStartOrEmpty, RecoverPhase::checkingAllUsed, RecoverPhase::checkingUsedFollowedByEmpty, RecoverPhase::checkingAllEmpty,
RecoverPhase::checkingAllUsedOrAllEmpty, RecoverPhase::corrupt, RecoverPhase::done
}
using Length = uint16_t
Private Member Functions
void Recover ()
void RecoverSector (uint32_t sectorIndex)
void RecoverEndAddress ()
void EraseSectorIfAtStart ()
void FillSectorIfDataDoesNotFit (std::size_t size)
void WriteSectorStatusIfAtStartOfSector ()
void WriteRange (infra::ConstByteRange range)
Private Attributes
hal::Flash & flash
uint32_t startAddress = 0
uint32_t endAddress = 0
infra::Sequencer sequencer
uint32_t sectorIndex = 0
infra::ClaimableResource resource
infra::ClaimableResource::Claimer::WithSize< SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE > claimerAdd
infra::ClaimableResource::Claimer::WithSize< SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE > claimerClear
infra::ClaimableResource::Claimer::WithSize< SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE > claimerRecover
infra::AutoResetFunction< void()> onAddDone
infra::AutoResetFunction< void()> onClearDone
uint32_t remainingPartialSize = 0
uint32_t partialSizeWritten = 0
bool partialAddStarted = false
SectorStatus sectorStatus = SectorStatus::empty
BlockHeader blockHeader
RecoverPhase recoverPhase = RecoverPhase::searchingStartOrEmpty
infra::IntrusiveForwardList< Iterator > iterators
Detailed Description
Definition at line 15 of file CyclicStore.hpp.
Member Typedef Documentation
Length
using services::CyclicStore::Length = uint16_t private
Definition at line 56 of file CyclicStore.hpp.
Member Enumeration Documentation
BlockStatus
enum services::CyclicStore::BlockStatus : uint8_t strong private
Enumerator
empty
emptyUntilEnd
writingLength
writingData
dataReady
Definition at line 58 of file CyclicStore.hpp.
                               : uint8_t
         {
             empty = 0xff,
             emptyUntilEnd = 0x7f,
             writingLength = 0xfe,
             writingData = 0xfc,
             dataReady = 0xf8
         };
RecoverPhase
enum services::CyclicStore::RecoverPhase : uint8_t strong private
Enumerator
searchingStartOrEmpty
checkingAllUsed
checkingUsedFollowedByEmpty
checkingAllEmpty
checkingAllUsedOrAllEmpty
corrupt
done
Definition at line 74 of file CyclicStore.hpp.
                                : uint8_t
         {
             searchingStartOrEmpty,
             checkingAllUsed,
             checkingUsedFollowedByEmpty,
             checkingAllEmpty,
             checkingAllUsedOrAllEmpty,
             corrupt,
             done
         };
SectorStatus
enum services::CyclicStore::SectorStatus : uint8_t strong private
Enumerator
empty
used
firstInCycle
Definition at line 67 of file CyclicStore.hpp.
                                : uint8_t
         {
             empty = 0xff,
             used = 0xfe,
             firstInCycle = 0xfc
         };
Constructor & Destructor Documentation
CyclicStore() [1/2]
services::CyclicStore::CyclicStore (hal::Flash & flash) explicit
Definition at line 6 of file CyclicStore.cpp.
References Recover().
         : flash(flash)
         , claimerAdd(resource)
         , claimerClear(resource)
         , claimerRecover(resource)
         , blockHeader()
     {
         Recover();
     }
CyclicStore() [2/2]
services::CyclicStore::CyclicStore (const CyclicStore & other) delete
Member Function Documentation
Add()
void services::CyclicStore::Add (infra::ConstByteRange range, infra::Function< void()> onDone)
Definition at line 16 of file CyclicStore.cpp.
References claimerAdd, infra::MemoryRange< T >::empty(), infra::Sequencer::EndIf(), EraseSectorIfAtStart(), infra::Sequencer::Execute(), FillSectorIfDataDoesNotFit(), infra::Sequencer::Finished(), infra::Sequencer::If(), infra::Sequencer::Load(), onAddDone, partialAddStarted, remainingPartialSize, sequencer, infra::MemoryRange< T >::size(), WriteRange(), and WriteSectorStatusIfAtStartOfSector().
Referenced by AddPartial().
     {
         assert(!range.empty());
         if (partialAddStarted)
             remainingPartialSize -= range.size();
         onAddDone = onDone;
         claimerAdd.Claim([this, range]()
         {
             assert(sequencer.Finished());
             sequencer.Load([this, range]()
             {
                 sequencer.If([this]() { return !partialAddStarted; });
                     FillSectorIfDataDoesNotFit(range.size() + remainingPartialSize);
                     EraseSectorIfAtStart();
                     WriteSectorStatusIfAtStartOfSector();
                 sequencer.EndIf();
                 WriteRange(range);
                 sequencer.Execute([this]()
                 {
                     claimerAdd.Release();
                     onAddDone();
                 });
             });
         });
     }
AddPartial()
void services::CyclicStore::AddPartial (infra::ConstByteRange range, uint32_t totalSize, infra::Function< void()> onDone)
Definition at line 44 of file CyclicStore.cpp.
References Add(), partialAddStarted, remainingPartialSize, and infra::MemoryRange< T >::size().
     {
         if (!partialAddStarted)
             remainingPartialSize = totalSize - range.size();
         Add(range, onDone);
     }
Begin()
CyclicStore::Iterator services::CyclicStore::Begin () const
Definition at line 76 of file CyclicStore.cpp.
     {
         return Iterator(*this);
     }
Clear()
void services::CyclicStore::Clear (infra::Function< void()> onDone)
Definition at line 52 of file CyclicStore.cpp.
References claimerClear, infra::Sequencer::Continue(), endAddress, hal::Flash::EraseAll(), infra::Sequencer::Execute(), infra::Sequencer::Finished(), flash, infra::Sequencer::Load(), onClearDone, sequencer, startAddress, and infra::Sequencer::Step().
     {
         onClearDone = onDone;
         claimerClear.Claim([this]()
         {
             endAddress = 0;
             startAddress = 0;
             assert(sequencer.Finished());
             sequencer.Load([this]()
             {
                 sequencer.Step([this]()
                 {
                     flash.EraseAll([this]() { sequencer.Continue(); });
                 });
                 sequencer.Execute([this]()
                 {
                     claimerClear.Release();
                     onClearDone();
                 });
             });
         });
     }
EraseSectorIfAtStart()
void services::CyclicStore::EraseSectorIfAtStart () private
Definition at line 240 of file CyclicStore.cpp.
References hal::Flash::AddressOffsetInSector(), infra::Sequencer::Continue(), endAddress, infra::Sequencer::EndIf(), hal::Flash::EraseSector(), firstInCycle, flash, infra::Sequencer::If(), iterators, infra::MakeByteRange(), hal::Flash::ReadBuffer(), hal::Flash::SectorOfAddress(), sectorStatus, sequencer, startAddress, hal::Flash::StartOfNextSectorCyclical(), infra::Sequencer::Step(), used, and hal::Flash::WriteBuffer().
Referenced by Add().
     {
         sequencer.If([this]() { return flash.AddressOffsetInSector(endAddress) == 0; });
             sequencer.Step([this]()
             {
                 flash.EraseSector(flash.SectorOfAddress(endAddress), [this]() { sequencer.Continue(); });
             });
             sequencer.Step([this]()
             {
                 flash.ReadBuffer(infra::MakeByteRange(sectorStatus), flash.StartOfNextSectorCyclical(endAddress), [this]() { sequencer.Continue(); });
             });
             sequencer.If([this]() { return sectorStatus == SectorStatus::used; });
                 sequencer.Step([this]()
                 {
                     for (auto& iterator: iterators)
                         iterator.SectorIsErased(flash.SectorOfAddress(startAddress));
                     sectorStatus = SectorStatus::firstInCycle;
                     startAddress = flash.StartOfNextSectorCyclical(endAddress);
                     flash.WriteBuffer(infra::MakeByteRange(sectorStatus), startAddress, [this]() { sequencer.Continue(); });
                 });
             sequencer.EndIf();
         sequencer.EndIf();
     }
FillSectorIfDataDoesNotFit()
void services::CyclicStore::FillSectorIfDataDoesNotFit (std::size_t size) private
Definition at line 265 of file CyclicStore.cpp.
References hal::Flash::AddressOffsetInSector(), blockHeader, emptyUntilEnd, endAddress, infra::Sequencer::EndIf(), flash, infra::Sequencer::If(), infra::MakeByteRange(), hal::Flash::SectorOfAddress(), sequencer, hal::Flash::SizeOfSector(), hal::Flash::StartOfNextSectorCyclical(), services::CyclicStore::BlockHeader::status, infra::Sequencer::Step(), and hal::Flash::WriteBuffer().
Referenced by Add().
     {
         sequencer.If([this, size]() { return flash.AddressOffsetInSector(endAddress) + sizeof(BlockHeader) + size > flash.SizeOfSector(flash.SectorOfAddress(endAddress)); });
             sequencer.Step([this]()
             {
                 blockHeader.status = BlockStatus::emptyUntilEnd;
                 flash.WriteBuffer(infra::MakeByteRange(blockHeader.status), endAddress, [this]() { sequencer.Continue(); });
                 endAddress = flash.StartOfNextSectorCyclical(endAddress);
             });
         sequencer.EndIf();
     }
operator=()
CyclicStore& services::CyclicStore::operator= (const CyclicStore & other) delete
Recover()
void services::CyclicStore::Recover () private
Definition at line 81 of file CyclicStore.cpp.
References claimerRecover, infra::Sequencer::Continue(), corrupt, done, infra::Sequencer::ElseIf(), endAddress, infra::Sequencer::EndForEach(), infra::Sequencer::EndIf(), hal::Flash::EraseAll(), infra::Sequencer::Execute(), infra::Sequencer::Finished(), flash, infra::Sequencer::ForEach(), infra::Sequencer::If(), infra::Sequencer::Load(), hal::Flash::NumberOfSectors(), RecoverEndAddress(), recoverPhase, RecoverSector(), searchingStartOrEmpty, sectorIndex, sequencer, startAddress, and infra::Sequencer::Step().
Referenced by CyclicStore().
     {
         claimerRecover.Claim([this]()
         {
             endAddress = 0;
             startAddress = 0;
             assert(sequencer.Finished());
             sequencer.Load([this]() {
                 sequencer.ForEach(sectorIndex, 0, flash.NumberOfSectors());
                     RecoverSector(sectorIndex);
                 sequencer.EndForEach(sectorIndex);
                 sequencer.If([this]() { return recoverPhase == RecoverPhase::corrupt || recoverPhase == RecoverPhase::searchingStartOrEmpty; });
                     sequencer.Step([this]()
                     {
                         startAddress = 0;
                         endAddress = startAddress;
                         flash.EraseAll([this]() { sequencer.Continue(); });
                     });
                 sequencer.ElseIf([this]() { return endAddress != startAddress; });
                     RecoverEndAddress();
                 sequencer.EndIf();
                 sequencer.Execute([this]()
                 {
                     claimerRecover.Release();
                     recoverPhase = RecoverPhase::done;
                 });
             });
         });
     }
RecoverEndAddress()
void services::CyclicStore::RecoverEndAddress () private
Definition at line 176 of file CyclicStore.cpp.
References hal::Flash::AddressOffsetInSector(), hal::Flash::AtStartOfSector(), blockHeader, services::CyclicStore::BlockHeader::BlockLength(), infra::Sequencer::Continue(), dataReady, infra::Sequencer::Else(), infra::Sequencer::ElseIf(), empty, emptyUntilEnd, endAddress, infra::Sequencer::EndIf(), infra::Sequencer::EndWhile(), infra::Sequencer::Execute(), flash, infra::Sequencer::If(), infra::MakeByteRange(), hal::Flash::ReadBuffer(), hal::Flash::SectorOfAddress(), sequencer, hal::Flash::SizeOfSector(), hal::Flash::StartOfNextSectorCyclical(), hal::Flash::StartOfPreviousSectorCyclical(), services::CyclicStore::BlockHeader::status, infra::Sequencer::Step(), hal::Flash::TotalSize(), infra::Sequencer::While(), writingData, and writingLength.
Referenced by Recover().
     {
         sequencer.Step([this]()
         {
             endAddress = flash.StartOfPreviousSectorCyclical(endAddress);
             ++endAddress;
             flash.ReadBuffer(infra::MakeByteRange(blockHeader), endAddress, [this]() { sequencer.Continue(); });
         });
         sequencer.While([this]() { return blockHeader.status != BlockStatus::empty && !flash.AtStartOfSector(endAddress); });
             sequencer.If([this]() { return blockHeader.status == BlockStatus::dataReady; });
                 sequencer.Execute([this]()
                 {
                     endAddress += sizeof(BlockHeader);
                 });
                 sequencer.If([this]() { return endAddress + blockHeader.BlockLength() <= flash.TotalSize() && flash.SectorOfAddress(endAddress) == flash.SectorOfAddress(endAddress + blockHeader.BlockLength()); });
                     sequencer.Step([this]()
                     {
                         endAddress += blockHeader.BlockLength();
                         flash.ReadBuffer(infra::MakeByteRange(blockHeader), endAddress, [this]() { sequencer.Continue(); });
                     });
                 sequencer.Else();
                     sequencer.Execute([this]()
                     {
                         endAddress = flash.StartOfNextSectorCyclical(endAddress);
                     });
                 sequencer.EndIf();
             sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::writingLength; });
                 sequencer.Step([this]()
                 {
                     endAddress += sizeof(BlockHeader);
                     flash.ReadBuffer(infra::MakeByteRange(blockHeader), endAddress, [this]() { sequencer.Continue(); });
                 });
             sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::writingData; });
                 sequencer.Execute([this]()
                 {
                     endAddress += sizeof(BlockHeader) + blockHeader.BlockLength();
                 });
                 sequencer.If([this]() { return flash.AddressOffsetInSector(endAddress) <= flash.SizeOfSector(flash.SectorOfAddress(endAddress)); });
                     sequencer.Step([this]()
                     {
                         flash.ReadBuffer(infra::MakeByteRange(blockHeader), endAddress, [this]() { sequencer.Continue(); });
                     });
                 sequencer.Else();
                     sequencer.Execute([this]()
                     {
                         // The BlockLength() field is corrupt, skip to next sector
                         endAddress = flash.StartOfNextSectorCyclical(endAddress);
                     });
                 sequencer.EndIf();
             sequencer.ElseIf([this]() { return blockHeader.status == BlockStatus::emptyUntilEnd; });
                 sequencer.Execute([this]()
                 {
                     endAddress = flash.StartOfNextSectorCyclical(endAddress);
                 });
             sequencer.Else();
                 sequencer.Execute([this]()
                 {
                     endAddress = flash.StartOfNextSectorCyclical(endAddress);
                 });
             sequencer.EndIf();
         sequencer.EndWhile();
     }
RecoverSector()
void services::CyclicStore::RecoverSector (uint32_t sectorIndex) private
Definition at line 112 of file CyclicStore.cpp.
References hal::Flash::AddressOfSector(), checkingAllEmpty, checkingAllUsed, checkingAllUsedOrAllEmpty, checkingUsedFollowedByEmpty, infra::Sequencer::Continue(), corrupt, empty, endAddress, infra::Sequencer::Execute(), firstInCycle, flash, infra::MakeByteRange(), hal::Flash::ReadBuffer(), recoverPhase, searchingStartOrEmpty, sectorIndex, sectorStatus, sequencer, startAddress, hal::Flash::StartOfNextSectorCyclical(), infra::Sequencer::Step(), and used.
Referenced by Recover().
     {
         sequencer.Step([this, sectorIndex]()
         {
             flash.ReadBuffer(infra::MakeByteRange(sectorStatus), flash.AddressOfSector(sectorIndex), [this]() { sequencer.Continue(); });
         });
         sequencer.Execute([this, sectorIndex]()
         {
             if (sectorStatus == SectorStatus::firstInCycle)
             {
                 if (recoverPhase == RecoverPhase::searchingStartOrEmpty)
                 {
                     startAddress = flash.AddressOfSector(sectorIndex);
                     endAddress = startAddress;
                     if (sectorIndex == 0)
                         recoverPhase = RecoverPhase::checkingUsedFollowedByEmpty;
                     else
                         recoverPhase = RecoverPhase::checkingAllUsed;
                 }
                 else
                     recoverPhase = RecoverPhase::corrupt;
             }
             else if (sectorStatus == SectorStatus::used)
             {
                 if (recoverPhase == RecoverPhase::checkingAllUsedOrAllEmpty)
                     recoverPhase = RecoverPhase::checkingAllUsed;
                 else if (recoverPhase == RecoverPhase::checkingUsedFollowedByEmpty
                     || recoverPhase == RecoverPhase::searchingStartOrEmpty
                     || recoverPhase == RecoverPhase::checkingAllUsed)
                 {}
                 else
                     recoverPhase = RecoverPhase::corrupt;
             }
             else if (sectorStatus == SectorStatus::empty)
             {
                 if (recoverPhase == RecoverPhase::searchingStartOrEmpty)
                 {
                     startAddress = flash.StartOfNextSectorCyclical(flash.AddressOfSector(sectorIndex));
                     endAddress = flash.AddressOfSector(sectorIndex);
                     recoverPhase = RecoverPhase::checkingAllUsedOrAllEmpty;
                 }
                 else if (recoverPhase == RecoverPhase::checkingAllUsedOrAllEmpty)
                 {
                     startAddress = 0;
                     endAddress = 0;
                     recoverPhase = RecoverPhase::checkingAllEmpty;
                 }
                 else if (recoverPhase == RecoverPhase::checkingUsedFollowedByEmpty)
                 {
                     endAddress = flash.AddressOfSector(sectorIndex);
                     recoverPhase = RecoverPhase::checkingAllEmpty;
                 }
                 else if (recoverPhase == RecoverPhase::checkingAllEmpty)
                 {}
                 else
                     recoverPhase = RecoverPhase::corrupt;
             }
             else
                 recoverPhase = RecoverPhase::corrupt;
         });
     }
WriteRange()
void services::CyclicStore::WriteRange (infra::ConstByteRange range) private
Definition at line 302 of file CyclicStore.cpp.
References blockHeader, infra::Sequencer::Continue(), dataReady, endAddress, infra::Sequencer::EndIf(), flash, infra::Sequencer::If(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), services::CyclicStore::BlockHeader::lengthLsb, services::CyclicStore::BlockHeader::lengthMsb, infra::MakeByteRange(), partialAddStarted, partialSizeWritten, remainingPartialSize, infra::EventDispatcherWorker::Schedule(), hal::Flash::SectorOfAddress(), sequencer, services::CyclicStore::BlockHeader::SetBlockLength(), infra::MemoryRange< T >::size(), hal::Flash::SizeOfSector(), services::CyclicStore::BlockHeader::status, infra::Sequencer::Step(), hal::Flash::TotalSize(), hal::Flash::WriteBuffer(), writingData, and writingLength.
Referenced by Add().
     {
         sequencer.If([this]() { return !partialAddStarted; });
             sequencer.Step([this, range]()  // Write status 'writing length'
             {
                 assert(sizeof(BlockHeader) + range.size() + remainingPartialSize + 1 <= flash.SizeOfSector(flash.SectorOfAddress(endAddress)));
                 blockHeader.status = BlockStatus::writingLength;
                 flash.WriteBuffer(infra::MakeByteRange(blockHeader.status), endAddress, [this]() { sequencer.Continue(); });
             });
             sequencer.Step([this, range]()  // Write length
             {
                 blockHeader.SetBlockLength(static_cast<Length>(range.size() + remainingPartialSize));
                 flash.WriteBuffer(infra::ByteRange(&blockHeader.lengthLsb, (&blockHeader.lengthMsb)+1), endAddress + 1, [this]() { sequencer.Continue(); });
             });
             sequencer.Step([this]()         // Write status 'writing data'
             {
                 blockHeader.status = BlockStatus::writingData;
                 flash.WriteBuffer(infra::MakeByteRange(blockHeader.status), endAddress + partialSizeWritten, [this]() { sequencer.Continue(); });
             });
         sequencer.EndIf();
         sequencer.Step([this, range]()  // Write data
         {
             flash.WriteBuffer(range, endAddress + partialSizeWritten + 3, [this]() { sequencer.Continue(); });
             partialSizeWritten += range.size();
         });
         sequencer.Step([this, range]()  // Write status 'ready'
         {
             if (remainingPartialSize == 0)
             {
                 blockHeader.status = BlockStatus::dataReady;
                 flash.WriteBuffer(infra::MakeByteRange(blockHeader.status), endAddress, [this]() { sequencer.Continue(); });
                 endAddress += partialSizeWritten + 3;
                 partialSizeWritten = 0;
                 partialAddStarted = false;
                 if (endAddress == flash.TotalSize())
                     endAddress = 0;
             }
             else
             {
                 partialAddStarted = true;
                 infra::EventDispatcher::Instance().Schedule([this]() { sequencer.Continue(); });
             }
         });
     }
WriteSectorStatusIfAtStartOfSector()
void services::CyclicStore::WriteSectorStatusIfAtStartOfSector () private
Definition at line 277 of file CyclicStore.cpp.
References hal::Flash::AtStartOfSector(), infra::Sequencer::Continue(), endAddress, infra::Sequencer::EndIf(), firstInCycle, flash, infra::Sequencer::If(), infra::MakeByteRange(), hal::Flash::ReadBuffer(), sectorStatus, sequencer, startAddress, hal::Flash::StartOfNextSectorCyclical(), infra::Sequencer::Step(), hal::Flash::TotalSize(), used, and hal::Flash::WriteBuffer().
Referenced by Add().
     {
         sequencer.If([this]() { return flash.AtStartOfSector(endAddress); });
             sequencer.Step([this]()
             {
                 flash.ReadBuffer(infra::MakeByteRange(sectorStatus), flash.StartOfNextSectorCyclical(endAddress), [this]() { sequencer.Continue(); });
             });
             sequencer.If([this]() { return sectorStatus == SectorStatus::used; });
                 sequencer.Step([this]()
                 {
                     sectorStatus = SectorStatus::firstInCycle;
                     flash.WriteBuffer(infra::MakeByteRange(sectorStatus), flash.StartOfNextSectorCyclical(endAddress), [this]() { sequencer.Continue(); });
                 });
             sequencer.EndIf(),
             sequencer.Step([this]()
             {
                 sectorStatus = endAddress == startAddress ? SectorStatus::firstInCycle : SectorStatus::used;
                 flash.WriteBuffer(infra::MakeByteRange(sectorStatus), endAddress, [this]() { sequencer.Continue(); });
                 ++endAddress;
                 if (endAddress == flash.TotalSize())
                     endAddress = 0;
             });
         sequencer.EndIf();
     }
Member Data Documentation
blockHeader
BlockHeader services::CyclicStore::blockHeader private
Definition at line 104 of file CyclicStore.hpp.
Referenced by FillSectorIfDataDoesNotFit(), services::CyclicStore::Iterator::operator=(), services::CyclicStore::Iterator::Read(), RecoverEndAddress(), and WriteRange().
claimerAdd
infra::ClaimableResource::Claimer::WithSize<SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE> services::CyclicStore::claimerAdd private
Definition at line 47 of file CyclicStore.hpp.
Referenced by Add().
claimerClear
infra::ClaimableResource::Claimer::WithSize<SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE> services::CyclicStore::claimerClear private
Definition at line 48 of file CyclicStore.hpp.
Referenced by Clear().
claimerRecover
infra::ClaimableResource::Claimer::WithSize<SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE> services::CyclicStore::claimerRecover private
Definition at line 49 of file CyclicStore.hpp.
Referenced by Recover().
endAddress
uint32_t services::CyclicStore::endAddress = 0 private
Definition at line 43 of file CyclicStore.hpp.
Referenced by Clear(), EraseSectorIfAtStart(), FillSectorIfDataDoesNotFit(), Recover(), RecoverEndAddress(), RecoverSector(), WriteRange(), and WriteSectorStatusIfAtStartOfSector().
flash
hal::Flash& services::CyclicStore::flash private
Definition at line 41 of file CyclicStore.hpp.
Referenced by Clear(), EraseSectorIfAtStart(), FillSectorIfDataDoesNotFit(), Recover(), RecoverEndAddress(), RecoverSector(), WriteRange(), and WriteSectorStatusIfAtStartOfSector().
iterators
infra::IntrusiveForwardList<Iterator> services::CyclicStore::iterators mutable private
Definition at line 107 of file CyclicStore.hpp.
Referenced by EraseSectorIfAtStart(), and services::CyclicStore::Iterator::Iterator().
onAddDone
infra::AutoResetFunction<void()> services::CyclicStore::onAddDone private
Definition at line 50 of file CyclicStore.hpp.
Referenced by Add().
onClearDone
infra::AutoResetFunction<void()> services::CyclicStore::onClearDone private
Definition at line 51 of file CyclicStore.hpp.
Referenced by Clear().
partialAddStarted
bool services::CyclicStore::partialAddStarted = false private
Definition at line 54 of file CyclicStore.hpp.
Referenced by Add(), AddPartial(), and WriteRange().
partialSizeWritten
uint32_t services::CyclicStore::partialSizeWritten = 0 private
Definition at line 53 of file CyclicStore.hpp.
Referenced by WriteRange().
recoverPhase
RecoverPhase services::CyclicStore::recoverPhase = RecoverPhase::searchingStartOrEmpty private
Definition at line 105 of file CyclicStore.hpp.
Referenced by Recover(), and RecoverSector().
remainingPartialSize
uint32_t services::CyclicStore::remainingPartialSize = 0 private
Definition at line 52 of file CyclicStore.hpp.
Referenced by Add(), AddPartial(), and WriteRange().
resource
infra::ClaimableResource services::CyclicStore::resource mutable private
Definition at line 46 of file CyclicStore.hpp.
sectorIndex
uint32_t services::CyclicStore::sectorIndex = 0 private
Definition at line 45 of file CyclicStore.hpp.
Referenced by Recover(), RecoverSector(), and services::CyclicStore::Iterator::SectorIsErased().
sectorStatus
SectorStatus services::CyclicStore::sectorStatus = SectorStatus::empty private
Definition at line 103 of file CyclicStore.hpp.
Referenced by EraseSectorIfAtStart(), services::CyclicStore::Iterator::operator=(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), RecoverSector(), and WriteSectorStatusIfAtStartOfSector().
sequencer
infra::Sequencer services::CyclicStore::sequencer private
Definition at line 44 of file CyclicStore.hpp.
Referenced by Add(), Clear(), EraseSectorIfAtStart(), FillSectorIfDataDoesNotFit(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), Recover(), RecoverEndAddress(), RecoverSector(), WriteRange(), and WriteSectorStatusIfAtStartOfSector().
startAddress
uint32_t services::CyclicStore::startAddress = 0 private
Definition at line 42 of file CyclicStore.hpp.
Referenced by Clear(), EraseSectorIfAtStart(), Recover(), RecoverSector(), and WriteSectorStatusIfAtStartOfSector().
The documentation for this class was generated from the following files:
CyclicStore.hpp
CyclicStore.cpp