EMil: services::DnsResolver::ReplyParser Class Reference
services::DnsResolver::ReplyParser Class Reference
Public Member Functions
ReplyParser (infra::StreamReaderWithRewinding &reader, infra::BoundedString &hostname)
bool AnswerIsForCurrentQuery (UdpSocket from, const IPAddress &currentNameServer, uint16_t queryId) const
bool Error () const
bool Recurse () const
infra::Optional< std::pair< IPAddress, infra::TimePoint > > ReadAnswerRecords ()
void ReadNameServers (infra::BoundedVector< IPAddress > &recursiveDnsServers)
Private Member Functions
void DiscardNameServerRecords ()
void ReadAdditionalRecords (infra::BoundedVector< IPAddress > &recursiveDnsServers, uint32_t nameServerPosition)
infra::Variant< Answer, CName, NoAnswer > ReadAnswer ()
void DiscardAnswer ()
infra::Optional< IPAddress > ReadNameServer (std::size_t nameServerPosition, std::size_t numNameServers)
bool ReadAndMatchHostname ()
bool ReadAndMatchHostnameParts (HostnameParts &hostnameParts)
bool ReadAndMatchReferenceHostname (uint8_t offsetHigh, HostnameParts &hostnameParts)
bool ReadAndMatchHostnameWithoutReference (uint8_t size, HostnameParts &hostnameParts)
bool ReadAndMatchHostnamePart (uint8_t size, const HostnameParts &hostnameParts)
void ReadCName (uint16_t resourceSize)
void ReadCNameReference (uint8_t offsetHigh)
bool ReadAndMatchNameServer (std::size_t nameServerPosition, std::size_t numNameServers)
bool IsNameServerForAdditionalRecord (std::size_t additionalRecordNameStart)
Private Attributes
infra::StreamReaderWithRewinding & reader
infra::DataInputStream::WithErrorPolicy stream { reader, infra::noFail }
infra::BoundedString & hostname
bool recurse = false
QueryHeader header {}
QuestionFooter footer {}
bool hostnameMatches
Detailed Description
Definition at line 137 of file DnsResolver.hpp.
Constructor & Destructor Documentation
ReplyParser()
services::DnsResolver::ReplyParser::ReplyParser (infra::StreamReaderWithRewinding & reader, infra::BoundedString & hostname)
Definition at line 90 of file DnsResolver.cpp.
References footer, header, hostnameMatches, ReadAndMatchHostname(), and stream.
         : reader(reader)
         , hostname(hostname)
     {
         stream >> header;
         hostnameMatches = ReadAndMatchHostname();
         stream >> footer;
     }
Member Function Documentation
AnswerIsForCurrentQuery()
bool services::DnsResolver::ReplyParser::AnswerIsForCurrentQuery (UdpSocket from, const IPAddress & currentNameServer, uint16_t queryId) const
Definition at line 99 of file DnsResolver.cpp.
References services::DnsResolver::currentNameServer, and services::GetAddress().
Referenced by services::DnsResolver::ActiveLookup::DataReceived().
     {
         // RFC 5452: Only accept responses from DNS server to which the query is sent
         if (GetAddress(from) != currentNameServer)
             return false;
         if ((header.flags & header.flagsResponse) == 0)
             return false;
         if (header.questionsCount != static_cast<uint16_t>(1))
             return false;
         if (header.id != queryId)
             return false;
         if (!hostnameMatches)
             return false;
         if (footer.type != footer.typeA)
             return false;
         if (footer.class_ != footer.classIn)
             return false;
         return true;
     }
DiscardAnswer()
void services::DnsResolver::ReplyParser::DiscardAnswer () private
Definition at line 203 of file DnsResolver.cpp.
     {
         ReadAndMatchHostname();
         auto resourceInner = stream.Extract<ResourceInner>();
         stream.Consume(resourceInner.resourceDataLength);
     }
DiscardNameServerRecords()
void services::DnsResolver::ReplyParser::DiscardNameServerRecords () private
Definition at line 153 of file DnsResolver.cpp.
     {
         for (uint16_t nameServerIndex = 0; nameServerIndex != header.nameServersCount; ++nameServerIndex)
             DiscardAnswer();
     }
Error()
bool services::DnsResolver::ReplyParser::Error () const
Definition at line 120 of file DnsResolver.cpp.
Referenced by services::DnsResolver::ActiveLookup::DataReceived().
     {
         return (header.flags & header.flagsErrorMask) != 0;
     }
IsNameServerForAdditionalRecord()
bool services::DnsResolver::ReplyParser::IsNameServerForAdditionalRecord (std::size_t additionalRecordNameStart) private
Definition at line 371 of file DnsResolver.cpp.
     {
         ReadAndMatchHostname();
         auto resourceInner = stream.Extract<ResourceInner>();
         if (resourceInner.IsNameServer())
         {
             HostnamePartsStream hostnameParts(reader, additionalRecordNameStart);
             if (ReadAndMatchHostnameParts(hostnameParts))
                 return true;
         }
         else
             stream.Consume(resourceInner.resourceDataLength);
         return false;
     }
ReadAdditionalRecords()
void services::DnsResolver::ReplyParser::ReadAdditionalRecords (infra::BoundedVector< IPAddress > & recursiveDnsServers, uint32_t nameServerPosition) private
Definition at line 159 of file DnsResolver.cpp.
References infra::BoundedVector< T >::full(), infra::none, and infra::BoundedVector< T >::push_back().
     {
         for (uint16_t additionalIndex = 0; additionalIndex != header.additionalRecordsCount; ++additionalIndex)
         {
             auto answer = ReadNameServer(nameServerPosition, header.nameServersCount);
             if (answer != infra::none && !recursiveDnsServers.full())
             {
                 recursiveDnsServers.push_back(*answer);
                 recurse = true;
             }
         }
     }
ReadAndMatchHostname()
bool services::DnsResolver::ReplyParser::ReadAndMatchHostname () private
Definition at line 229 of file DnsResolver.cpp.
Referenced by ReplyParser().
     {
         HostnamePartsString hostnameParts(hostname);
         return ReadAndMatchHostnameParts(hostnameParts);
     }
ReadAndMatchHostnamePart()
bool services::DnsResolver::ReplyParser::ReadAndMatchHostnamePart (uint8_t size, const HostnameParts & hostnameParts) private
Definition at line 283 of file DnsResolver.cpp.
References services::DnsResolver::HostnameParts::Current(), services::DnsResolver::HostnameParts::Empty(), and infra::BoundedStringBase< T >::size().
     {
         if (hostnameParts.Empty() || hostnameParts.Current().size() < size)
         {
             stream.Consume(size);
             return false;
         }
         for (uint8_t i = 0; i != size; ++i)
         {
             auto c = stream.Extract<char>();
             if (std::tolower(hostnameParts.Current()[i]) != std::tolower(c))
             {
                 stream.Consume(size - i - 1);
                 return false;
             }
         }
         return true;
     }
ReadAndMatchHostnameParts()
bool services::DnsResolver::ReplyParser::ReadAndMatchHostnameParts (HostnameParts & hostnameParts) private
Definition at line 235 of file DnsResolver.cpp.
     {
         auto size = stream.Extract<uint8_t>();
         if ((size & 0xc0) == 0xc0)
             return ReadAndMatchReferenceHostname(size & 0x3f, hostnameParts);
         else
             return ReadAndMatchHostnameWithoutReference(size, hostnameParts);
     }
ReadAndMatchHostnameWithoutReference()
bool services::DnsResolver::ReplyParser::ReadAndMatchHostnameWithoutReference (uint8_t size, HostnameParts & hostnameParts) private
Definition at line 263 of file DnsResolver.cpp.
References services::DnsResolver::HostnameParts::ConsumeCurrent(), and services::DnsResolver::HostnameParts::Empty().
     {
         bool result = true;
         while (size != 0)
         {
             if (!ReadAndMatchHostnamePart(size, hostnameParts))
                 result = false;
             if (result)
                 hostnameParts.ConsumeCurrent();
             size = stream.Extract<uint8_t>();
             if ((size & 0xc0) == 0xc0)
                 return ReadAndMatchReferenceHostname(size & 0x3f, hostnameParts) && result;
         }
         stream.Consume(size);
         return result && size == 0 && hostnameParts.Empty() && !stream.Failed();
     }
ReadAndMatchNameServer()
bool services::DnsResolver::ReplyParser::ReadAndMatchNameServer (std::size_t nameServerPosition, std::size_t numNameServers) private
Definition at line 356 of file DnsResolver.cpp.
     {
         auto additionalRecordNameStart = reader.ConstructSaveMarker();
         reader.Rewind(nameServerPosition);
         std::size_t i = 0;
         for (; i != numNameServers; ++i)
             if (IsNameServerForAdditionalRecord(additionalRecordNameStart))
                 break;
         reader.Rewind(additionalRecordNameStart);
         ReadAndMatchHostname();
         return i != numNameServers;
     }
ReadAndMatchReferenceHostname()
bool services::DnsResolver::ReplyParser::ReadAndMatchReferenceHostname (uint8_t offsetHigh, HostnameParts & hostnameParts) private
Definition at line 245 of file DnsResolver.cpp.
     {
         auto offsetLow = stream.Extract<uint8_t>();
         uint16_t offset = offsetLow + (offsetHigh << 8);
         auto currentPosition = reader.ConstructSaveMarker();
         if (currentPosition <= offset)
             return false;
         reader.Rewind(offset);
         auto size = stream.Extract<uint8_t>();
         bool result = ReadAndMatchHostnameWithoutReference(size, hostnameParts);
         reader.Rewind(currentPosition);
         return result;
     }
ReadAnswer()
infra::Variant< DnsResolver::Answer, DnsResolver::CName, DnsResolver::NoAnswer > services::DnsResolver::ReplyParser::ReadAnswer () private
Definition at line 172 of file DnsResolver.cpp.
References infra::Now().
     {
         bool hostnameMatches = ReadAndMatchHostname();
         auto resourceInner = stream.Extract<ResourceInner>();
         if (hostnameMatches)
         {
             if (resourceInner.IsCName())
             {
                 hostname.clear();
                 ReadCName(resourceInner.resourceDataLength);
                 if (!stream.Failed())
                     return CName{};
                 else
                     return NoAnswer{};
             }
             else if (resourceInner.IsIPv4Answer())
             {
                 auto address = stream.Extract<IPv4Address>();
                 if (!stream.Failed())
                     return Answer{ address, infra::Now() + std::chrono::seconds((resourceInner.ttl1 << 16) + resourceInner.ttl2) };
                 return NoAnswer{};
             }
         }
         stream.Consume(resourceInner.resourceDataLength);
         return NoAnswer{};
     }
ReadAnswerRecords()
infra::Optional< std::pair< IPAddress, infra::TimePoint > > services::DnsResolver::ReplyParser::ReadAnswerRecords ()
Definition at line 130 of file DnsResolver.cpp.
References services::DnsResolver::Answer::address, infra::Variant< T >::Get(), infra::MakeOptional(), infra::none, and services::DnsResolver::Answer::validUntil.
Referenced by services::DnsResolver::ActiveLookup::TryFindAnswer().
     {
         for (uint16_t answerIndex = 0; answerIndex != header.answersCount; ++answerIndex)
         {
             auto answer = ReadAnswer();
             if (answer.Is<Answer>())
                 return infra::MakeOptional(std::make_pair(answer.Get<Answer>().address, answer.Get<Answer>().validUntil));
             else if (answer.Is<CName>())
                 recurse = true;
         }
         return infra::none;
     }
ReadCName()
void services::DnsResolver::ReplyParser::ReadCName (uint16_t resourceSize) private
Definition at line 304 of file DnsResolver.cpp.
     {
         uint8_t partSize = 0;
         for (; resourceSize != 0 && !hostname.full(); --resourceSize)
         {
             if (partSize == 0)
             {
                 partSize = stream.Extract<uint8_t>();
                 if (partSize == 0)
                 {
                     stream.Consume(resourceSize - 1);
                     if (!hostname.empty())
                         hostname.pop_back();
                     return;
                 }
                 if ((partSize & 0xc0) == 0xc0)
                 {
                     ReadCNameReference(partSize & 0x3f);
                     return;
                 }
             }
             else
             {
                 auto c = stream.Extract<uint8_t>();
                 hostname.push_back(c);
                 --partSize;
                 if (partSize == 0)
                     hostname.push_back('.');
             }
         }
     }
ReadCNameReference()
void services::DnsResolver::ReplyParser::ReadCNameReference (uint8_t offsetHigh) private
Definition at line 340 of file DnsResolver.cpp.
     {
         auto offsetLow = stream.Extract<uint8_t>();
         uint16_t offset = offsetLow + (offsetHigh << 8);
         auto currentPosition = reader.ConstructSaveMarker();
         if (currentPosition > offset)
         {
             reader.Rewind(offset);
             ReadCName(static_cast<uint16_t>(currentPosition) - offset);
             reader.Rewind(currentPosition);
         }
     }
ReadNameServer()
infra::Optional< IPAddress > services::DnsResolver::ReplyParser::ReadNameServer (std::size_t nameServerPosition, std::size_t numNameServers) private
Definition at line 210 of file DnsResolver.cpp.
References infra::MakeOptional(), and infra::none.
     {
         bool nameServerMatches = ReadAndMatchNameServer(nameServerPosition, numNameServers);
         auto resourceInner = stream.Extract<ResourceInner>();
         if (nameServerMatches && resourceInner.IsIPv4Answer())
         {
             auto address = stream.Extract<IPv4Address>();
             if (!stream.Failed())
                 return infra::MakeOptional(IPAddress(address));
             else
                 return infra::none;
         }
         stream.Consume(resourceInner.resourceDataLength);
         return infra::none;
     }
ReadNameServers()
void services::DnsResolver::ReplyParser::ReadNameServers (infra::BoundedVector< IPAddress > & recursiveDnsServers)
Definition at line 145 of file DnsResolver.cpp.
Referenced by services::DnsResolver::ActiveLookup::TryNewNameServers().
     {
         auto nameServerPosition = reader.ConstructSaveMarker();
         DiscardNameServerRecords();
         ReadAdditionalRecords(recursiveDnsServers, nameServerPosition);
     }
Recurse()
bool services::DnsResolver::ReplyParser::Recurse () const
Definition at line 125 of file DnsResolver.cpp.
Referenced by services::DnsResolver::ActiveLookup::TryFindRecursiveNameServer().
     {
         return recurse;
     }
Member Data Documentation
footer
QuestionFooter services::DnsResolver::ReplyParser::footer {} private
Definition at line 170 of file DnsResolver.hpp.
Referenced by ReplyParser().
header
QueryHeader services::DnsResolver::ReplyParser::header {} private
Definition at line 169 of file DnsResolver.hpp.
Referenced by ReplyParser().
hostname
infra::BoundedString& services::DnsResolver::ReplyParser::hostname private
Definition at line 167 of file DnsResolver.hpp.
hostnameMatches
bool services::DnsResolver::ReplyParser::hostnameMatches private
Definition at line 171 of file DnsResolver.hpp.
Referenced by ReplyParser().
reader
infra::StreamReaderWithRewinding& services::DnsResolver::ReplyParser::reader private
Definition at line 165 of file DnsResolver.hpp.
recurse
bool services::DnsResolver::ReplyParser::recurse = false private
Definition at line 168 of file DnsResolver.hpp.
stream
infra::DataInputStream::WithErrorPolicy services::DnsResolver::ReplyParser::stream { reader, infra::noFail } private
Definition at line 166 of file DnsResolver.hpp.
Referenced by ReplyParser().
The documentation for this class was generated from the following files:
DnsResolver.hpp
DnsResolver.cpp