EMil: TestAsn1Formatter.cpp File Reference
TestAsn1Formatter.cpp File Reference
Functions
TEST (Asn1ObjectFormatter, construction_results_in_empty_object)
TEST (Asn1ObjectFormatter, add_uint8)
TEST (Asn1ObjectFormatter, add_uint32)
TEST (Asn1ObjectFormatter, add_int32)
TEST (Asn1ObjectFormatter, add_serial)
TEST (Asn1ObjectFormatter, add_bignum)
TEST (Asn1ObjectFormatter, add_bignum_zero)
TEST (Asn1ObjectFormatter, add_bignum_using_minumum_amount_of_bytes)
TEST (Asn1ObjectFormatter, add_bignum_zero_pad_when_high_bit_is_set)
TEST (Asn1ObjectFormatter, add_context_specific)
TEST (Asn1ObjectFormatter, add_object_id)
TEST (Asn1ObjectFormatter, add_bit_string)
TEST (Asn1ObjectFormatter, add_printable_string)
TEST (Asn1ObjectFormatter, add_utc_time_1950)
TEST (Asn1ObjectFormatter, add_utc_time)
TEST (Asn1ObjectFormatter, add_generalized_time)
TEST (Asn1ObjectFormatter, add_time)
TEST (Asn1ObjectFormatter, add_empty_optional)
TEST (Asn1ObjectFormatter, add_non_empty_optional)
TEST (Asn1ObjectFormatter, start_sequence)
TEST (Asn1ObjectFormatter, start_set)
TEST (Asn1ObjectFormatter, start_context_specific)
TEST (Asn1ObjectFormatter, start_bit_string)
TEST (Asn1ObjectFormatter, add_medium_sized_object)
TEST (Asn1ObjectFormatter, add_large_object)
Function Documentation
TEST() [1/25]
TEST (Asn1ObjectFormatter , construction_results_in_empty_object)
Definition at line 11 of file TestAsn1Formatter.cpp.
References EXPECT_EQ(), and infra::Asn1Formatter::Failed().
 {
     infra::ByteOutputStream::WithStorage<4> stream;
     auto marker = stream.SaveMarker();
     infra::Asn1Formatter formatter(stream);
     EXPECT_EQ(false, formatter.Failed());
     EXPECT_EQ(0, stream.ProcessedBytesSince(marker));
 }
TEST() [2/25]
TEST (Asn1ObjectFormatter , add_uint8)
Definition at line 22 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<3> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.Add(uint8_t(0xAB));
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x01, 0xAB));
 }
TEST() [3/25]
TEST (Asn1ObjectFormatter , add_uint32)
Definition at line 32 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<6> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.Add(uint32_t(0x01ABCDEF));
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x04, 0x01, 0xAB, 0xCD, 0xEF));
 }
TEST() [4/25]
TEST (Asn1ObjectFormatter , add_int32)
Definition at line 42 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<6> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.Add(int32_t(-1));
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x04, 0xFF, 0xFF, 0xFF, 0xFF));
 }
TEST() [5/25]
TEST (Asn1ObjectFormatter , add_serial)
Definition at line 52 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddSerial(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<6> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 4> serial = { 1, 2, 3, 4 };
     formatter.AddSerial(serial);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x04, 0x01, 0x02, 0x03, 0x04));
 }
TEST() [6/25]
TEST (Asn1ObjectFormatter , add_bignum)
Definition at line 64 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddBigNumber(), data, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<8> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 6> data = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06 };
     formatter.AddBigNumber(data);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x06, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01));
 }
TEST() [7/25]
TEST (Asn1ObjectFormatter , add_bignum_zero)
Definition at line 76 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddBigNumber(), data, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<2> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 1> data = { 0x00 };
     formatter.AddBigNumber(data);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x00));
 }
TEST() [8/25]
TEST (Asn1ObjectFormatter , add_bignum_using_minumum_amount_of_bytes)
Definition at line 88 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddBigNumber(), data, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<5> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 6> data = { 0x00, 0x01, 0x01, 0x00, 0x00, 0x00 };
     formatter.AddBigNumber(data);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x03, 0x01, 0x01, 0x00));
 }
TEST() [9/25]
TEST (Asn1ObjectFormatter , add_bignum_zero_pad_when_high_bit_is_set)
Definition at line 100 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddBigNumber(), data, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<5> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 2> data = { 0xFF, 0x80 };
     formatter.AddBigNumber(data);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x03, 0x00, 0x80, 0xFF));
 }
TEST() [10/25]
TEST (Asn1ObjectFormatter , add_context_specific)
Definition at line 112 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddContextSpecific(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     const uint8_t context = 1;
     infra::ByteOutputStream::WithStorage<4> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddContextSpecific(context, shortData);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x20 | 0x80 | context, 0x02, 0xAB, 0xBA));
 }
TEST() [11/25]
TEST (Asn1ObjectFormatter , add_object_id)
Definition at line 124 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddObjectId(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<4> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddObjectId(shortData);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x06, 0x02, 0xAB, 0xBA));
 }
TEST() [12/25]
TEST (Asn1ObjectFormatter , add_bit_string)
Definition at line 134 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddBitString(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<5> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddBitString(shortData);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x03, 0x03, 0x00, 0xAB, 0xBA));
 }
TEST() [13/25]
TEST (Asn1ObjectFormatter , add_printable_string)
Definition at line 144 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddPrintableString(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<4> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddPrintableString(shortData);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x13, 0x02, 0xAB, 0xBA));
 }
TEST() [14/25]
TEST (Asn1ObjectFormatter , add_utc_time_1950)
Definition at line 154 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddUtcTime(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<15> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddUtcTime(1950, 1, 1, 12, 15, 00);
     std::array<uint8_t, 15> expected = {0x17, 0x0D, '5', '0', '0', '1', '0', '1', '1', '2', '1', '5', '0', '0', 'Z'};
     EXPECT_EQ(expected, stream.Storage());
 }
TEST() [15/25]
TEST (Asn1ObjectFormatter , add_utc_time)
Definition at line 166 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddUtcTime(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<15> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddUtcTime(2017, 1, 1, 12, 15, 00);
     std::array<uint8_t, 15> expected = { 0x17, 0x0D, '1', '7', '0', '1', '0', '1', '1', '2', '1', '5', '0', '0', 'Z' };
     EXPECT_EQ(expected, stream.Storage());
 }
TEST() [16/25]
TEST (Asn1ObjectFormatter , add_generalized_time)
Definition at line 178 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddGeneralizedTime(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<17> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddGeneralizedTime(2050, 1, 1, 12, 15, 00);
     std::array<uint8_t, 17> expected = { 0x18, 0x0F, '2', '0', '5', '0', '0', '1', '0', '1', '1', '2', '1', '5', '0', '0', 'Z' };
     EXPECT_EQ(expected, stream.Storage());
 }
TEST() [17/25]
TEST (Asn1ObjectFormatter , add_time)
Definition at line 190 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddTime(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     {
         infra::ByteOutputStream::WithStorage<32> stream;
         infra::Asn1Formatter formatter(stream);
         formatter.AddTime(1950, 1, 1, 1, 1, 1);
         EXPECT_EQ(0x17, stream.Storage()[0]);
     }
     {
         infra::ByteOutputStream::WithStorage<32> stream;
         infra::Asn1Formatter formatter(stream);
         formatter.AddTime(2050, 1, 1, 1, 1, 1);
         EXPECT_EQ(0x18, stream.Storage()[0]);
     }
 }
TEST() [18/25]
TEST (Asn1ObjectFormatter , add_empty_optional)
Definition at line 207 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddOptional(), infra::none, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<2> stream;
     infra::Asn1Formatter formatter(stream);
     formatter.AddOptional<uint32_t>(infra::none);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x05, 0x00));
 }
TEST() [19/25]
TEST (Asn1ObjectFormatter , add_non_empty_optional)
Definition at line 217 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddOptional(), infra::inPlace, infra::WithStorage< Base, StorageType >::Storage(), and value.
 {
     infra::ByteOutputStream::WithStorage<3> stream;
     infra::Asn1Formatter formatter(stream);
     infra::Optional<uint8_t> value(infra::inPlace, 0xAB);
     formatter.AddOptional<uint8_t>(value);
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x02, 0x01, 0xAB));
 }
TEST() [20/25]
TEST (Asn1ObjectFormatter , start_sequence)
Definition at line 228 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), infra::Asn1Formatter::StartSequence(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<8> stream;
     infra::Asn1Formatter formatter(stream);
     {
         auto sequence = formatter.StartSequence();
         sequence.Add(0xFFFFFFFF);
     }
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x20 | 0x10, 0x06, 0x02, 0x04, 0xFF, 0xFF, 0xFF, 0xFF));
 }
TEST() [21/25]
TEST (Asn1ObjectFormatter , start_set)
Definition at line 240 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), infra::Asn1Formatter::StartSet(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<8> stream;
     infra::Asn1Formatter formatter(stream);
     {
         auto sequence = formatter.StartSet();
         sequence.Add(0xFFFFFFFF);
     }
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x20 | 0x11, 0x06, 0x02, 0x04, 0xFF, 0xFF, 0xFF, 0xFF));
 }
TEST() [22/25]
TEST (Asn1ObjectFormatter , start_context_specific)
Definition at line 252 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), infra::Asn1Formatter::StartContextSpecific(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     const uint8_t context = 3;
     infra::ByteOutputStream::WithStorage<8> stream;
     infra::Asn1Formatter formatter(stream);
     {
         auto sequence = formatter.StartContextSpecific(context);
         sequence.Add(0xFFFFFFFF);
     }
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x20 | 0x80 | context, 0x06, 0x02, 0x04, 0xFF, 0xFF, 0xFF, 0xFF));
 }
TEST() [23/25]
TEST (Asn1ObjectFormatter , start_bit_string)
Definition at line 266 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::Add(), infra::Asn1Formatter::StartBitString(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<9> stream;
     infra::Asn1Formatter formatter(stream);
     {
         auto sequence = formatter.StartBitString();
         sequence.Add(0xFFFFFFFF);
     }
     ASSERT_THAT(stream.Storage(), testing::ElementsAre(0x03, 0x07, 0x00, 0x02, 0x04, 0xFF, 0xFF, 0xFF, 0xFF));
 }
TEST() [24/25]
TEST (Asn1ObjectFormatter , add_medium_sized_object)
Definition at line 278 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddPrintableString(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<131> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 128> mediumSizedObject;
     formatter.AddPrintableString(mediumSizedObject);
     EXPECT_EQ(0x13, stream.Storage()[0]);
     EXPECT_EQ(0x81, stream.Storage()[1]);
     EXPECT_EQ(0x80, stream.Storage()[2]);
 }
TEST() [25/25]
TEST (Asn1ObjectFormatter , add_large_object)
Definition at line 291 of file TestAsn1Formatter.cpp.
References infra::Asn1Formatter::AddPrintableString(), EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::ByteOutputStream::WithStorage<260> stream;
     infra::Asn1Formatter formatter(stream);
     std::array<uint8_t, 256> largeObject;
     formatter.AddPrintableString(largeObject);
     EXPECT_EQ(0x13, stream.Storage()[0]);
     EXPECT_EQ(0x82, stream.Storage()[1]);
     EXPECT_EQ(0x01, stream.Storage()[2]);
     EXPECT_EQ(0x00, stream.Storage()[3]);
 }