EMil: services::ConfigurationStoreBase Class Reference
services::ConfigurationStoreBase Class Reference abstract
#include <ConfigurationStore.hpp>
Classes
class LockGuard
Public Member Functions
ConfigurationStoreBase (ConfigurationBlob &blob1, ConfigurationBlob &blob2)
void Recover (const infra::Function< void(bool success)> &onRecovered)
void Write (infra::Function< void()> onDone)
virtual void Write () override
void Erase (infra::Function< void()> onDone)
virtual void Serialize (ConfigurationBlob &blob, const infra::Function< void()> &onDone)=0
virtual void Deserialize (ConfigurationBlob &blob)=0
LockGuard Lock ()
Private Member Functions
void OnBlobLoaded (bool success)
void BlobWriteDone ()
void Unlocked ()
Private Attributes
ConfigurationBlob * activeBlob
ConfigurationBlob * inactiveBlob
infra::AutoResetFunction< void()> onWriteDone
infra::AutoResetFunction< void(bool success)> onRecovered
uint32_t lockCount = 0
bool writingBlob = false
bool writeRequested = false
Additional Inherited Members
Protected Member Functions inherited from services::ConfigurationStoreInterface
ConfigurationStoreInterface ()=default
ConfigurationStoreInterface (const ConfigurationStoreInterface &other)=delete
ConfigurationStoreInterface & operator= (const ConfigurationStoreInterface &other)=delete
~ConfigurationStoreInterface ()=default
Detailed Description
Definition at line 76 of file ConfigurationStore.hpp.
Constructor & Destructor Documentation
ConfigurationStoreBase()
services::ConfigurationStoreBase::ConfigurationStoreBase (ConfigurationBlob & blob1, ConfigurationBlob & blob2)
Definition at line 85 of file ConfigurationStore.cpp.
         : activeBlob(&blob1)
         , inactiveBlob(&blob2)
     {}
Member Function Documentation
BlobWriteDone()
void services::ConfigurationStoreBase::BlobWriteDone () private
Definition at line 151 of file ConfigurationStore.cpp.
References activeBlob, inactiveBlob, onWriteDone, infra::swap(), Write(), writeRequested, and writingBlob.
Referenced by Write().
     {
         std::swap(activeBlob, inactiveBlob);
         writingBlob = false;
         if (writeRequested)
             Write();
         else if (onWriteDone)
             onWriteDone();
     }
Deserialize()
virtual void services::ConfigurationStoreBase::Deserialize (ConfigurationBlob & blob) pure virtual
Implemented in services::ConfigurationStoreImpl< T >.
Referenced by OnBlobLoaded(), and services::FactoryDefaultConfigurationStoreBase::Recover().
Erase()
void services::ConfigurationStoreBase::Erase (infra::Function< void()> onDone)
Definition at line 109 of file ConfigurationStore.cpp.
References activeBlob, services::ConfigurationBlob::Erase(), inactiveBlob, and onWriteDone.
Referenced by services::FactoryDefaultConfigurationStoreBase::Recover().
     {
         onWriteDone = onDone;
         inactiveBlob->Erase([this]() { activeBlob->Erase([this]() { onWriteDone(); }); });
     }
Lock()
ConfigurationStoreBase::LockGuard services::ConfigurationStoreBase::Lock ()
Definition at line 115 of file ConfigurationStore.cpp.
Referenced by services::ConfigurationStoreImpl< T >::Lock().
     {
         return LockGuard(*this);
     }
OnBlobLoaded()
void services::ConfigurationStoreBase::OnBlobLoaded (bool success) private
Definition at line 141 of file ConfigurationStore.cpp.
References activeBlob, Deserialize(), inactiveBlob, onRecovered, and infra::swap().
Referenced by Recover().
     {
         std::swap(activeBlob, inactiveBlob);
         if (success)
             Deserialize(*inactiveBlob);
         onRecovered(success);
     }
Recover()
void services::ConfigurationStoreBase::Recover (const infra::Function< void(bool success)> & onRecovered)
Definition at line 120 of file ConfigurationStore.cpp.
References activeBlob, services::ConfigurationBlob::Erase(), inactiveBlob, OnBlobLoaded(), onRecovered, services::ConfigurationBlob::Recover(), and infra::swap().
Referenced by services::FactoryDefaultConfigurationStoreBase::Recover(), and services::ConfigurationStoreImpl< T >::WithBlobs::WithBlobs().
     {
         this->onRecovered = onRecovered;
         activeBlob->Recover([this](bool success)
         {
             if (success)
             {
                 inactiveBlob->Erase([this]() { OnBlobLoaded(true); });
             }
             else
             {
                 std::swap(activeBlob, inactiveBlob);
                 activeBlob->Recover([this](bool success)
                 {
                     inactiveBlob->Erase([this, success]() { OnBlobLoaded(success); });
                 });
             }
         });
     }
Serialize()
virtual void services::ConfigurationStoreBase::Serialize (ConfigurationBlob & blob, const infra::Function< void()> & onDone) pure virtual
Implemented in services::ConfigurationStoreImpl< T >.
Referenced by services::FactoryDefaultConfigurationStoreBase::Recover(), and Write().
Unlocked()
void services::ConfigurationStoreBase::Unlocked () private
Definition at line 161 of file ConfigurationStore.cpp.
References Write(), and writeRequested.
     {
         if (writeRequested)
             Write();
     }
Write() [1/2]
void services::ConfigurationStoreBase::Write (infra::Function< void()> onDone)
Definition at line 90 of file ConfigurationStore.cpp.
References activeBlob, BlobWriteDone(), services::ConfigurationBlob::Erase(), inactiveBlob, lockCount, onWriteDone, Serialize(), writeRequested, and writingBlob.
Referenced by services::FactoryDefaultConfigurationStoreBase::Write().
     {
         if (onDone)
             onWriteDone = onDone;
         writeRequested = true;
         if (!writingBlob && lockCount == 0)
         {
             writeRequested = false;
             writingBlob = true;
             Serialize(*activeBlob, [this]() { inactiveBlob->Erase([this]() { BlobWriteDone(); }); });
         }
     }
Write() [2/2]
void services::ConfigurationStoreBase::Write () override virtual
Implements services::ConfigurationStoreInterface.
Definition at line 104 of file ConfigurationStore.cpp.
Referenced by BlobWriteDone(), Unlocked(), and services::ConfigurationStoreImpl< T >::Write().
     {
         Write(infra::Function<void()>());
     }
Member Data Documentation
activeBlob
ConfigurationBlob* services::ConfigurationStoreBase::activeBlob private
Definition at line 111 of file ConfigurationStore.hpp.
Referenced by BlobWriteDone(), Erase(), OnBlobLoaded(), Recover(), and Write().
inactiveBlob
ConfigurationBlob* services::ConfigurationStoreBase::inactiveBlob private
Definition at line 112 of file ConfigurationStore.hpp.
Referenced by BlobWriteDone(), Erase(), OnBlobLoaded(), Recover(), and Write().
lockCount
uint32_t services::ConfigurationStoreBase::lockCount = 0 private
Definition at line 115 of file ConfigurationStore.hpp.
Referenced by services::ConfigurationStoreBase::LockGuard::LockGuard(), services::ConfigurationStoreBase::LockGuard::operator=(), and Write().
onRecovered
infra::AutoResetFunction<void(bool success)> services::ConfigurationStoreBase::onRecovered private
Definition at line 114 of file ConfigurationStore.hpp.
Referenced by OnBlobLoaded(), Recover(), and services::ConfigurationStoreImpl< T >::WithBlobs::WithBlobs().
onWriteDone
infra::AutoResetFunction<void()> services::ConfigurationStoreBase::onWriteDone private
Definition at line 113 of file ConfigurationStore.hpp.
Referenced by BlobWriteDone(), Erase(), and Write().
writeRequested
bool services::ConfigurationStoreBase::writeRequested = false private
Definition at line 117 of file ConfigurationStore.hpp.
Referenced by BlobWriteDone(), Unlocked(), and Write().
writingBlob
bool services::ConfigurationStoreBase::writingBlob = false private
Definition at line 116 of file ConfigurationStore.hpp.
Referenced by BlobWriteDone(), and Write().
The documentation for this class was generated from the following files:
ConfigurationStore.hpp
ConfigurationStore.cpp