EMil: infra::SingleObserver< Descendant, SubjectType_ > Class Template Reference
infra::SingleObserver< Descendant, SubjectType_ > Class Template Reference
#include <Observer.hpp>
Public Types
using SubjectType = SubjectType_
using SingleHelper = SubjectType_
Public Member Functions
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Protected Member Functions
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Private Attributes
SubjectType * subject = nullptr
Detailed Description
template<class Descendant, class SubjectType_>
class infra::SingleObserver< Descendant, SubjectType_ >
Definition at line 40 of file Observer.hpp.
Member Typedef Documentation
SingleHelper
template<class Descendant, class SubjectType_> using infra::SingleObserver< Descendant, SubjectType_ >::SingleHelper = SubjectType_
Definition at line 44 of file Observer.hpp.
SubjectType
template<class Descendant, class SubjectType_> using infra::SingleObserver< Descendant, SubjectType_ >::SubjectType = SubjectType_
Definition at line 43 of file Observer.hpp.
Constructor & Destructor Documentation
SingleObserver() [1/3]
template<class Descendant, class SubjectType_> infra::SingleObserver< Descendant, SubjectType_ >::SingleObserver () default
SingleObserver() [2/3]
template<class Descendant , class SubjectType_ > infra::SingleObserver< Descendant, SubjectType_ >::SingleObserver (SubjectType & subject)
Definition at line 169 of file Observer.hpp.
     {
         Attach(subject);
     }
SingleObserver() [3/3]
template<class Descendant, class SubjectType_> infra::SingleObserver< Descendant, SubjectType_ >::SingleObserver (const SingleObserver< Descendant, SubjectType_ > & other) protected delete
~SingleObserver()
template<class Descendant , class SubjectType_ > infra::SingleObserver< Descendant, SubjectType_ >::~SingleObserver () protected
Definition at line 175 of file Observer.hpp.
     {
         Detach();
     }
Member Function Documentation
Attach()
template<class Descendant , class SubjectType_ > void infra::SingleObserver< Descendant, SubjectType_ >::Attach (SubjectType & subject)
Definition at line 194 of file Observer.hpp.
Referenced by services::ConnectionMbedTls::CreatedObserver(), services::DatagramBsd::DatagramBsd(), services::DatagramWin::DatagramWin(), services::ConnectionBsd::SetObserver(), services::ConnectionWin::SetObserver(), and services::HttpServerConnectionObserver::TakeOverConnection().
     {
         Detach();
         this->subject = &subject;
         static_cast<infra::Subject<Descendant>*>(this->subject)->RegisterObserver(this);
     }
Attached()
template<class Descendant , class SubjectType_ > bool infra::SingleObserver< Descendant, SubjectType_ >::Attached () const
Definition at line 188 of file Observer.hpp.
     {
         return subject != nullptr;
     }
Detach()
template<class Descendant , class SubjectType_ > void infra::SingleObserver< Descendant, SubjectType_ >::Detach ()
Definition at line 202 of file Observer.hpp.
     {
         if (Attached())
             static_cast<infra::Subject<Descendant>*>(this->subject)->UnregisterObserver(this);
         subject = nullptr;
     }
operator=()
template<class Descendant, class SubjectType_> SingleObserver& infra::SingleObserver< Descendant, SubjectType_ >::operator= (const SingleObserver< Descendant, SubjectType_ > & other) protected delete
Subject()
template<class Descendant , class SubjectType_ > SingleObserver< Descendant, SubjectType_ >::SubjectType & infra::SingleObserver< Descendant, SubjectType_ >::Subject () const
Definition at line 181 of file Observer.hpp.
Referenced by services::ConnectionFactoryWithNameResolverForTls::ConnectionEstablished().
     {
         assert(subject != nullptr);
         return *subject;
     }
Member Data Documentation
subject
template<class Descendant, class SubjectType_> SubjectType* infra::SingleObserver< Descendant, SubjectType_ >::subject = nullptr private
Definition at line 63 of file Observer.hpp.
The documentation for this class was generated from the following file:
Observer.hpp