EMil: infra::Function< Result(Args...), ExtraSize > Class Template Reference
infra::Function< Result(Args...), ExtraSize > Class Template Reference
#include <Function.hpp>
Public Types
typedef Result ResultType
Public Member Functions
Function ()=default
Function (std::nullptr_t)
Function (const Function &other)
template<class F >
Function (F f)
~Function ()
Function & operator= (const Function &other)
Function & operator= (std::nullptr_t)
operator bool () const
ResultType operator() (Args... args) const
ResultType Invoke (const std::tuple< Args... > &args) const
void Swap (Function &other)
Private Types
typedef detail::InvokerFunctions< Result(Args...), ExtraSize > StorageType
Private Member Functions
template<class F >
void Assign (F f)
void Clear ()
bool Initialized () const
Static Private Member Functions
static void CopyConstruct (const StorageType &from, StorageType &to)
static void Destruct (StorageType &storage)
Private Attributes
StorageType invokerFunctions
Friends
template<class F , std::size_t ExtraSize2>
class Function
Detailed Description
template<std::size_t ExtraSize, class Result, class... Args>
class infra::Function< Result(Args...), ExtraSize >
Definition at line 91 of file Function.hpp.
Member Typedef Documentation
ResultType
template<std::size_t ExtraSize, class Result , class... Args> typedef Result infra::Function< Result(Args...), ExtraSize >::ResultType
Definition at line 94 of file Function.hpp.
StorageType
template<std::size_t ExtraSize, class Result , class... Args> typedef detail::InvokerFunctions<Result(Args...), ExtraSize> infra::Function< Result(Args...), ExtraSize >::StorageType private
Definition at line 124 of file Function.hpp.
Constructor & Destructor Documentation
Function() [1/4]
template<std::size_t ExtraSize, class Result , class... Args> infra::Function< Result(Args...), ExtraSize >::Function () default
Function() [2/4]
template<std::size_t ExtraSize, class Result , class... Args> infra::Function< Result(Args...), ExtraSize >::Function (std::nullptr_t)
Definition at line 285 of file Function.hpp.
     {}
Function() [3/4]
template<std::size_t ExtraSize, class Result , class... Args> infra::Function< Result(Args...), ExtraSize >::Function (const Function< Result(Args...), ExtraSize > & other)
Definition at line 289 of file Function.hpp.
     {
         if (other.Initialized())
             CopyConstruct(other.invokerFunctions, invokerFunctions);
     }
Function() [4/4]
template<std::size_t ExtraSize, class Result , class... Args> template<class F > infra::Function< Result(Args...), ExtraSize >::Function (F f)
Definition at line 297 of file Function.hpp.
     {
         Assign(std::forward<F>(f));
     }
~Function()
template<std::size_t ExtraSize, class Result , class... Args> infra::Function< Result(Args...), ExtraSize >::~Function ()
Definition at line 303 of file Function.hpp.
     {
         Clear();
     }
Member Function Documentation
Assign()
template<std::size_t ExtraSize, class Result , class... Args> template<class F > void infra::Function< Result(Args...), ExtraSize >::Assign (F f) private
Definition at line 372 of file Function.hpp.
     {
         Clear();
         StorageType::template Construct<F>(invokerFunctions, std::forward<F>(f));
     }
Clear()
template<std::size_t ExtraSize, class Result , class... Args> void infra::Function< Result(Args...), ExtraSize >::Clear () private
Definition at line 440 of file Function.hpp.
     {
         if (Initialized())
         {
             Destruct(invokerFunctions);
             invokerFunctions.virtualMethodTable = nullptr;
         }
     }
CopyConstruct()
template<std::size_t ExtraSize, class Result , class... Args> void infra::Function< Result(Args...), ExtraSize >::CopyConstruct (const StorageType & from, StorageType & to) static private
Definition at line 330 of file Function.hpp.
References infra::Copy(), infra::MakeByteRange(), and infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::virtualMethodTable.
     {
         if (from.virtualMethodTable->copyConstruct != nullptr)                                                      //TICS !CON#007
             from.virtualMethodTable->copyConstruct(from, to);
         else
             Copy(MakeByteRange(from), MakeByteRange(to));
     }
Destruct()
template<std::size_t ExtraSize, class Result , class... Args> void infra::Function< Result(Args...), ExtraSize >::Destruct (StorageType & storage) static private
Definition at line 339 of file Function.hpp.
References infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::virtualMethodTable.
     {
         if (storage.virtualMethodTable->destruct != nullptr)                                                        //TICS !CON#007
             storage.virtualMethodTable->destruct(storage);
     }
Initialized()
template<std::size_t ExtraSize, class Result , class... Args> bool infra::Function< Result(Args...), ExtraSize >::Initialized () const private
Definition at line 450 of file Function.hpp.
     {
         return invokerFunctions.virtualMethodTable != nullptr;                                                  //TICS !CON#007
     }
Invoke()
template<std::size_t ExtraSize, class Result , class... Args> Function< Result(Args...), ExtraSize >::ResultType infra::Function< Result(Args...), ExtraSize >::Invoke (const std::tuple< Args... > & args) const
Definition at line 434 of file Function.hpp.
     {
         return TupleInvokeHelper<sizeof...(Args), ResultType, Args...>::Invoke(invokerFunctions, invokerFunctions.virtualMethodTable->invoke, args);
     }
operator bool()
template<std::size_t ExtraSize, class Result , class... Args> infra::Function< Result(Args...), ExtraSize >::operator bool () const explicit
Definition at line 379 of file Function.hpp.
     {
         return Initialized();
     }
operator()()
template<std::size_t ExtraSize, class Result , class... Args> Function< Result(Args...), ExtraSize >::ResultType infra::Function< Result(Args...), ExtraSize >::operator() (Args... args) const
Definition at line 385 of file Function.hpp.
     {
         return invokerFunctions.virtualMethodTable->invoke(invokerFunctions, args...);
     }
operator=() [1/2]
template<std::size_t ExtraSize, class Result , class... Args> Function< Result(Args...), ExtraSize > & infra::Function< Result(Args...), ExtraSize >::operator= (const Function< Result(Args...), ExtraSize > & other)
Definition at line 309 of file Function.hpp.
     {
         if (this != &other)
         {
             Clear();
             if (other)
                 CopyConstruct(other.invokerFunctions, invokerFunctions);
         }
         return *this;
     }
operator=() [2/2]
template<std::size_t ExtraSize, class Result , class... Args> Function< Result(Args...), ExtraSize > & infra::Function< Result(Args...), ExtraSize >::operator= (std::nullptr_t)
Definition at line 323 of file Function.hpp.
     {
         Clear();
         return *this;
     }
Swap()
template<std::size_t ExtraSize, class Result , class... Args> void infra::Function< Result(Args...), ExtraSize >::Swap (Function< Result(Args...), ExtraSize > & other)
Definition at line 346 of file Function.hpp.
References infra::swap().
     {
         using std::swap;
         if (Initialized() && other.Initialized())
         {
             Function temp(std::move(*this));
             *this = std::move(other);
             other = std::move(temp);
         }
         else if (Initialized())
         {
             CopyConstruct(invokerFunctions, other.invokerFunctions);
             Destruct(invokerFunctions);
             invokerFunctions.virtualMethodTable = nullptr;
         }
         else if (other.Initialized())
         {
             CopyConstruct(other.invokerFunctions, invokerFunctions);
             Destruct(other.invokerFunctions);
             other.invokerFunctions.virtualMethodTable = nullptr;
         }
     }
Friends And Related Function Documentation
Function
template<std::size_t ExtraSize, class Result , class... Args> template<class F , std::size_t ExtraSize2> friend class Function friend
Definition at line 132 of file Function.hpp.
Member Data Documentation
invokerFunctions
template<std::size_t ExtraSize, class Result , class... Args> StorageType infra::Function< Result(Args...), ExtraSize >::invokerFunctions private
Definition at line 129 of file Function.hpp.
The documentation for this class was generated from the following file:
Function.hpp