EMil: TestMemoryRange.cpp File Reference
TestMemoryRange.cpp File Reference
Functions
TEST (MemoryRangeTest, TestConstructedEmpty)
TEST (MemoryRangeTest, TestConstructionWithPointers)
TEST (MemoryRangeTest, TestCopyConstruction)
TEST (MemoryRangeTest, TestConstructionWithArray)
TEST (MemoryRangeTest, TestConstructionWithEmptyArray)
TEST (MemoryRangeTest, TestConstructionWithVector)
TEST (MemoryRangeTest, TestEnd)
TEST (MemoryRangeTest, TestIndex)
TEST (MemoryRangeTest, TestFront)
TEST (MemoryRangeTest, TestBack)
TEST (MemoryRangeTest, TestContains)
TEST (MemoryRangeTest, TestContainsOrEnd)
TEST (MemoryRangeTest, TestClear)
TEST (MemoryRangeTest, TestPopFront)
TEST (MemoryRangeTest, TestPopBack)
TEST (MemoryRangeTest, TestShrinkFromFront)
TEST (MemoryRangeTest, TestShrinkFromFrontDoesNotShrink)
TEST (MemoryRangeTest, TestShrinkFromBack)
TEST (MemoryRangeTest, TestShrinkFromBackDoesNotShrink)
TEST (MemoryRangeTest, Copy)
TEST (MemoryRangeTest, ContentsEqual)
TEST (MemoryRangeTest, IntersectingRange)
TEST (MemoryRangeTest, Head)
TEST (MemoryRangeTest, Tail)
TEST (MemoryRangeTest, DiscardHead)
TEST (MemoryRangeTest, DiscardTail)
TEST (MemoryRangeTest, TestCompare)
TEST (MemoryRangeTest, TestMakeRangeFromArray)
TEST (MemoryRangeTest, TestMakeRangeFromContainer)
TEST (MemoryRangeTest, TestMakeVectorFromRange)
TEST (MemoryRangeTest, ConstCasts)
TEST (MemoryRangeTest, MakeStringByteRange)
Function Documentation
TEST() [1/32]
TEST (MemoryRangeTest , TestConstructedEmpty)
Definition at line 6 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::MemoryRange< T >::size().
 {
     infra::MemoryRange<int> range;
     EXPECT_TRUE(range.empty());
     EXPECT_EQ(0, range.size());
 }
TEST() [2/32]
TEST (MemoryRangeTest , TestConstructionWithPointers)
Definition at line 14 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::empty(), EXPECT_EQ(), EXPECT_FALSE(), and infra::MemoryRange< T >::size().
 {
     int array[] = { 0, 1, 2 };
     infra::MemoryRange<int> range(array, array + 3);
     EXPECT_FALSE(range.empty());
     EXPECT_EQ(3, range.size());
     EXPECT_EQ(&array[0], range.begin());
 }
TEST() [3/32]
TEST (MemoryRangeTest , TestCopyConstruction)
Definition at line 24 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::empty(), EXPECT_EQ(), EXPECT_FALSE(), and infra::MemoryRange< T >::size().
 {
     int array[] = { 0, 1, 2 };
     infra::MemoryRange<int> range(array, array + 3);
     infra::MemoryRange<const int> copy(range);
     EXPECT_FALSE(copy.empty());
     EXPECT_EQ(3, copy.size());
     EXPECT_EQ(&array[0], copy.begin());
 }
TEST() [4/32]
TEST (MemoryRangeTest , TestConstructionWithArray)
Definition at line 35 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::empty(), EXPECT_EQ(), EXPECT_FALSE(), and infra::MemoryRange< T >::size().
 {
     std::array<int, 3> array = { 0, 1, 2 };
     infra::MemoryRange<int> range(array);
     EXPECT_FALSE(range.empty());
     EXPECT_EQ(3, range.size());
     EXPECT_EQ(&array[0], range.begin());
 }
TEST() [5/32]
TEST (MemoryRangeTest , TestConstructionWithEmptyArray)
Definition at line 45 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::MemoryRange< T >::size().
 {
     std::array<int, 0> array;
     infra::MemoryRange<int> range(array);
     EXPECT_TRUE(range.empty());
     EXPECT_EQ(0, range.size());
 }
TEST() [6/32]
TEST (MemoryRangeTest , TestConstructionWithVector)
Definition at line 54 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::empty(), EXPECT_EQ(), EXPECT_FALSE(), and infra::MemoryRange< T >::size().
 {
     std::vector<int> vector = { 0, 1, 2 };
     infra::MemoryRange<int> range(vector);
     EXPECT_FALSE(range.empty());
     EXPECT_EQ(3, range.size());
     EXPECT_EQ(&vector[0], range.begin());
 }
TEST() [7/32]
TEST (MemoryRangeTest , TestEnd)
Definition at line 64 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::cbegin(), infra::MemoryRange< T >::cend(), infra::MemoryRange< T >::end(), and EXPECT_EQ().
 {
     std::array<int, 3> array = { 0, 1, 2 };
     infra::MemoryRange<int> range(array);
     EXPECT_EQ(range.begin() + 3, range.end());
     EXPECT_EQ(range.cbegin() + 3, range.cend());
 }
TEST() [8/32]
TEST (MemoryRangeTest , TestIndex)
Definition at line 73 of file TestMemoryRange.cpp.
References EXPECT_EQ().
 {
     std::array<int, 3> array = { 0, 1, 2 };
     infra::MemoryRange<int> range(array);
     EXPECT_EQ(0, range[0]);
     EXPECT_EQ(1, range[1]);
     EXPECT_EQ(2, range[2]);
 }
TEST() [9/32]
TEST (MemoryRangeTest , TestFront)
Definition at line 83 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MemoryRange< T >::front().
 {
     std::array<int, 3> array = { 0, 1, 2 };
     infra::MemoryRange<int> range(array);
     EXPECT_EQ(0, range.front());
 }
TEST() [10/32]
TEST (MemoryRangeTest , TestBack)
Definition at line 91 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::back(), and EXPECT_EQ().
 {
     std::array<int, 3> array = { 0, 1, 2 };
     infra::MemoryRange<int> range(array);
     EXPECT_EQ(2, range.back());
 }
TEST() [11/32]
TEST (MemoryRangeTest , TestContains)
Definition at line 99 of file TestMemoryRange.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     std::array<int, 5> array = { 0, 1, 2, 3, 4 };
     infra::MemoryRange<int> range(array.data() + 1, array.data() + 3);
     EXPECT_FALSE(range.contains(array.data()));
     EXPECT_TRUE(range.contains(array.data() + 1));
     EXPECT_TRUE(range.contains(array.data() + 2));
     EXPECT_FALSE(range.contains(array.data() + 3));
 }
TEST() [12/32]
TEST (MemoryRangeTest , TestContainsOrEnd)
Definition at line 110 of file TestMemoryRange.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     std::array<int, 5> array = { 0, 1, 2, 3, 4 };
     infra::MemoryRange<int> range(array.data() + 1, array.data() + 3);
     EXPECT_FALSE(range.contains_or_end(array.data()));
     EXPECT_TRUE(range.contains_or_end(array.data() + 1));
     EXPECT_TRUE(range.contains_or_end(array.data() + 2));
     EXPECT_TRUE(range.contains_or_end(array.data() + 3));
     EXPECT_FALSE(range.contains_or_end(array.data() + 4));
 }
TEST() [13/32]
TEST (MemoryRangeTest , TestClear)
Definition at line 122 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::clear(), infra::MemoryRange< T >::empty(), and EXPECT_TRUE().
 {
     std::array<int, 3> array = { 0, 1, 2 };
     infra::MemoryRange<int> range(array);
     range.clear();
     EXPECT_TRUE(range.empty());
 }
TEST() [14/32]
TEST (MemoryRangeTest , TestPopFront)
Definition at line 131 of file TestMemoryRange.cpp.
References EXPECT_EQ(), infra::MemoryRange< T >::front(), and infra::MemoryRange< T >::pop_front().
 {
     std::array<int, 4> array = { 0, 1, 2, 3 };
     infra::MemoryRange<int> range(array);
     range.pop_front();
     EXPECT_EQ(1, range.front());
 }
TEST() [15/32]
TEST (MemoryRangeTest , TestPopBack)
Definition at line 140 of file TestMemoryRange.cpp.
References infra::MemoryRange< T >::back(), EXPECT_EQ(), and infra::MemoryRange< T >::pop_back().
 {
     std::array<int, 4> array = { 0, 1, 2, 3 };
     infra::MemoryRange<int> range(array);
     range.pop_back();
     EXPECT_EQ(2, range.back());
 }
TEST() [16/32]
TEST (MemoryRangeTest , TestShrinkFromFront)
Definition at line 149 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MemoryRange< T >::shrink_from_front_to().
 {
     std::array<int, 4> array = { 0, 1, 2, 3 };
     infra::MemoryRange<int> range(array);
     range.shrink_from_front_to(3);
     EXPECT_EQ((std::array<int, 3>{ 1, 2, 3 }), range);
 }
TEST() [17/32]
TEST (MemoryRangeTest , TestShrinkFromFrontDoesNotShrink)
Definition at line 158 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MemoryRange< T >::shrink_from_front_to().
 {
     std::array<int, 4> array = { 0, 1, 2, 3 };
     infra::MemoryRange<int> range(array);
     range.shrink_from_front_to(6);
     EXPECT_EQ((std::array<int, 4>{ 0, 1, 2, 3 }), range);
 }
TEST() [18/32]
TEST (MemoryRangeTest , TestShrinkFromBack)
Definition at line 167 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MemoryRange< T >::shrink_from_back_to().
 {
     std::array<int, 4> array = { 0, 1, 2, 3 };
     infra::MemoryRange<int> range(array);
     range.shrink_from_back_to(3);
     EXPECT_EQ((std::array<int, 3>{ 0, 1, 2 }), range);
 }
TEST() [19/32]
TEST (MemoryRangeTest , TestShrinkFromBackDoesNotShrink)
Definition at line 176 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MemoryRange< T >::shrink_from_back_to().
 {
     std::array<int, 4> array = { 0, 1, 2, 3 };
     infra::MemoryRange<int> range(array);
     range.shrink_from_back_to(6);
     EXPECT_EQ((std::array<int, 4>{ 0, 1, 2, 3 }), range);
 }
TEST() [20/32]
TEST (MemoryRangeTest , Copy)
Definition at line 185 of file TestMemoryRange.cpp.
References infra::Copy(), EXPECT_EQ(), and infra::MakeByteRange().
 {
     int x = 0x12345678;
     int y;
     infra::Copy(infra::MakeByteRange(x), infra::MakeByteRange(y));
     EXPECT_EQ(0x12345678, y);
 }
TEST() [21/32]
TEST (MemoryRangeTest , ContentsEqual)
Definition at line 194 of file TestMemoryRange.cpp.
References infra::ContentsEqual(), EXPECT_FALSE(), EXPECT_TRUE(), and infra::MakeByteRange().
 {
     int a = 0x12;
     int x = 0x12345678;
     int y = x;
     int z = x - 1;
     EXPECT_TRUE(ContentsEqual(infra::MakeByteRange(x), infra::MakeByteRange(y)));
     EXPECT_FALSE(ContentsEqual(infra::MakeByteRange(x), infra::MakeByteRange(z)));
     EXPECT_FALSE(ContentsEqual(infra::MakeByteRange(x), infra::MakeByteRange(a)));
     std::array<int, 2> a1 = { 1, 2 };
     std::array<int, 3> a2 = { 1, 2, 3 };
     EXPECT_FALSE(infra::ContentsEqual(infra::MakeByteRange(a1), infra::MakeByteRange(a2)));
 }
TEST() [22/32]
TEST (MemoryRangeTest , IntersectingRange)
Definition at line 210 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::IntersectingRange().
 {
     std::array<uint8_t, 10> range;
     EXPECT_EQ(infra::ByteRange(range.data() + 2, range.data() + 4), infra::IntersectingRange(infra::ByteRange(range.data(), range.data() + 4), infra::ByteRange(range.data() + 2, range.data() + 6)));
     EXPECT_EQ(infra::ByteRange(range.data() + 2, range.data() + 2), infra::IntersectingRange(infra::ByteRange(range.data(), range.data() + 2), infra::ByteRange(range.data() + 2, range.data() + 6)));
     EXPECT_EQ(infra::ByteRange(), infra::IntersectingRange(infra::ByteRange(range.data(), range.data() + 2), infra::ByteRange(range.data() + 3, range.data() + 6)));
     EXPECT_EQ(infra::ByteRange(), infra::IntersectingRange(infra::ByteRange(range.data() + 3, range.data() + 6), infra::ByteRange(range.data(), range.data() + 2)));
 }
TEST() [23/32]
TEST (MemoryRangeTest , Head)
Definition at line 220 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::Head().
 {
     std::array<uint8_t, 10> range;
     EXPECT_EQ(infra::ByteRange(range.data(), range.data() + 4), infra::Head(infra::ByteRange(range), 4));
     EXPECT_EQ(infra::ByteRange(range.data(), range.data() + 10), infra::Head(infra::ByteRange(range), 14));
 }
TEST() [24/32]
TEST (MemoryRangeTest , Tail)
Definition at line 228 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::Tail().
 {
     std::array<uint8_t, 10> range;
     EXPECT_EQ(infra::ByteRange(range.data() + 6, range.data() + 10), infra::Tail(infra::ByteRange(range), 4));
     EXPECT_EQ(infra::ByteRange(range.data(), range.data() + 10), infra::Tail(infra::ByteRange(range), 14));
 }
TEST() [25/32]
TEST (MemoryRangeTest , DiscardHead)
Definition at line 236 of file TestMemoryRange.cpp.
References infra::DiscardHead(), and EXPECT_EQ().
 {
     std::array<uint8_t, 10> range;
     EXPECT_EQ(infra::ByteRange(range.data() + 4, range.data() + range.size()), infra::DiscardHead(infra::ByteRange(range), 4));
     EXPECT_EQ(infra::ByteRange(), infra::DiscardHead(infra::ByteRange(range), 14));
 }
TEST() [26/32]
TEST (MemoryRangeTest , DiscardTail)
Definition at line 244 of file TestMemoryRange.cpp.
References infra::DiscardTail(), and EXPECT_EQ().
 {
     std::array<uint8_t, 10> range;
     EXPECT_EQ(infra::ByteRange(range.data(), range.data() + 6), infra::DiscardTail(infra::ByteRange(range), 4));
     EXPECT_EQ(infra::ByteRange(), infra::DiscardTail(infra::ByteRange(range), 14));
 }
TEST() [27/32]
TEST (MemoryRangeTest , TestCompare)
Definition at line 252 of file TestMemoryRange.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     std::array<uint8_t, 3> range = { 1, 2, 3 };
     EXPECT_FALSE(infra::ByteRange(range.data(), range.data() + 2) == infra::ByteRange(range.data() + 1, range.data() + 2));
     EXPECT_FALSE(infra::ByteRange(range.data(), range.data() + 3) == infra::ByteRange(range.data(), range.data() + 2));
     EXPECT_TRUE(infra::ByteRange(range.data(), range.data() + 3) == infra::ByteRange(range.data(), range.data() + 3));
     EXPECT_FALSE(infra::ByteRange(range.data(), range.data() + 3) != infra::ByteRange(range.data(), range.data() + 3));
     EXPECT_TRUE(infra::ByteRange(range.data(), range.data() + 3) == range);
     EXPECT_TRUE(range == infra::ByteRange(range.data(), range.data() + 3));
     std::array<uint8_t, 3> otherRange = { 2, 3, 4 };
     EXPECT_FALSE(infra::ByteRange(range.data(), range.data() + 3) == otherRange);
     EXPECT_TRUE(infra::ByteRange(range.data(), range.data() + 3) != otherRange);
     EXPECT_TRUE(otherRange != infra::ByteRange(range.data(), range.data() + 3));
 }
TEST() [28/32]
TEST (MemoryRangeTest , TestMakeRangeFromArray)
Definition at line 270 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MakeRange().
 {
     uint8_t array[3] = { static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3) };
     const uint8_t constArray[3] = { static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3) };
     EXPECT_EQ(infra::ByteRange(reinterpret_cast<uint8_t*>(&array), reinterpret_cast<uint8_t*>(&array) + 3), infra::MakeRange(array));
     EXPECT_EQ(infra::ConstByteRange(reinterpret_cast<const uint8_t*>(&constArray), reinterpret_cast<const uint8_t*>(&constArray) + 3), infra::MakeRange(constArray));
 }
TEST() [29/32]
TEST (MemoryRangeTest , TestMakeRangeFromContainer)
Definition at line 279 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MakeRange().
 {
     infra::BoundedVector<uint8_t>::WithMaxSize<3> container({ static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3) });
     EXPECT_EQ(infra::ByteRange(&container.front(), &container.front() + 3), infra::MakeRange(container));
     EXPECT_EQ(infra::ByteRange(&container.front(), &container.front() + 3), infra::MakeRange(static_cast<const infra::BoundedVector<uint8_t>&>(container)));
 }
TEST() [30/32]
TEST (MemoryRangeTest , TestMakeVectorFromRange)
Definition at line 287 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MakeVector().
 {
     std::array<uint8_t, 3> array { 2, 3, 4 };
     EXPECT_EQ((std::vector<uint8_t>{ 2, 3, 4}), infra::MakeVector(infra::ConstByteRange(array)));
 }
TEST() [31/32]
TEST (MemoryRangeTest , ConstCasts)
Definition at line 293 of file TestMemoryRange.cpp.
References infra::ConstCastByteRange(), EXPECT_EQ(), infra::MakeConst(), and infra::MakeRange().
 {
     std::array<uint8_t, 3> array { 2, 3, 4 };
     EXPECT_EQ(array, infra::ConstCastByteRange(infra::MakeRange(array)));
     EXPECT_EQ(array, infra::ConstCastByteRange(infra::MakeConst(infra::MakeRange(array))));
 }
TEST() [32/32]
TEST (MemoryRangeTest , MakeStringByteRange)
Definition at line 301 of file TestMemoryRange.cpp.
References EXPECT_EQ(), and infra::MakeStringByteRange().
 {
     const char* string = "string";
     std::string stdString = "string";
     EXPECT_EQ(infra::MemoryRange<const char>(string, string + std::strlen(string)), infra::ReinterpretCastMemoryRange<const char>(infra::MakeStringByteRange(string)));
     EXPECT_EQ(infra::MemoryRange<const char>(stdString.data(), stdString.data() + stdString.size()), infra::ReinterpretCastMemoryRange<const char>(infra::MakeStringByteRange(stdString)));
 }