EMil: hal::FlashStub Class Reference
hal::FlashStub Class Reference
#include <FlashStub.hpp>
Public Member Functions
FlashStub (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Public Attributes
std::vector< std::vector< uint8_t > > sectors
infra::Optional< uint8_t > stopAfterWriteSteps
infra::Function< void()> onEraseDone
bool delaySignalEraseDone = false
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 10 of file FlashStub.hpp.
Constructor & Destructor Documentation
FlashStub()
hal::FlashStub::FlashStub (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
Definition at line 6 of file FlashStub.cpp.
         : sectors(numberOfSectors, std::vector<uint8_t>(sizeOfEachSector, 0xff))
     {}
Member Function Documentation
AddressOfSector()
uint32_t hal::FlashStub::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 34 of file FlashStub.cpp.
References sectors.
     {
         assert(sectorIndex <= sectors.size());
         uint32_t result = 0;
         for (uint32_t index = 0; index != sectorIndex; ++index)
             result += sectors[index].size();
         return result;
     }
EraseSectors()
void hal::FlashStub::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 82 of file FlashStub.cpp.
References infra::detail::begin(), delaySignalEraseDone, infra::detail::end(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), onEraseDone, infra::EventDispatcherWorker::Schedule(), and sectors.
     {
         for (uint32_t sectorIndex = beginIndex; sectorIndex != endIndex; ++sectorIndex)
             std::fill(sectors[sectorIndex].begin(), sectors[sectorIndex].end(), 0xff);
         onEraseDone = onDone;
         if (!delaySignalEraseDone)
             infra::EventDispatcher::Instance().Schedule(onDone);
     }
NumberOfSectors()
uint32_t hal::FlashStub::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 10 of file FlashStub.cpp.
References sectors.
     {
         return sectors.size();
     }
ReadBuffer()
void hal::FlashStub::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 68 of file FlashStub.cpp.
References hal::Flash::AddressOffsetInSector(), infra::detail::begin(), infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::empty(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::MemoryRange< T >::pop_front(), infra::EventDispatcherWorker::Schedule(), SectorOfAddress(), sectors, infra::MemoryRange< T >::size(), SizeOfSector(), and hal::Flash::StartOfNextSectorCyclical().
     {
         while (!buffer.empty())
         {
             std::size_t size = std::min<uint32_t>(buffer.size(), SizeOfSector(SectorOfAddress(address)) - AddressOffsetInSector(address));
             std::copy(sectors[SectorOfAddress(address)].begin() + AddressOffsetInSector(address), sectors[SectorOfAddress(address)].begin() + AddressOffsetInSector(address) + size, buffer.begin());
             buffer.pop_front(size);
             address = StartOfNextSectorCyclical(address);
         }
         infra::EventDispatcher::Instance().Schedule(onDone);
     }
SectorOfAddress()
uint32_t hal::FlashStub::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 20 of file FlashStub.cpp.
References sectors.
Referenced by ReadBuffer(), and WriteBuffer().
     {
         for (std::size_t index = 0; index != sectors.size(); ++index)
         {
             if (address < sectors[index].size())
                 return index;
             address -= sectors[index].size();
         }
         assert(address == 0);
         return sectors.size();
     }
SizeOfSector()
uint32_t hal::FlashStub::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 15 of file FlashStub.cpp.
References sectors.
Referenced by ReadBuffer(), and WriteBuffer().
     {
         return sectors[sectorIndex].size();
     }
WriteBuffer()
void hal::FlashStub::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 46 of file FlashStub.cpp.
References hal::Flash::AddressOffsetInSector(), infra::MemoryRange< T >::empty(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::MemoryRange< T >::pop_front(), infra::EventDispatcherWorker::Schedule(), SectorOfAddress(), sectors, infra::MemoryRange< T >::size(), SizeOfSector(), hal::Flash::StartOfNextSector(), and stopAfterWriteSteps.
     {
         infra::EventDispatcher::Instance().Schedule(onDone);
         if (stopAfterWriteSteps)
             if (*stopAfterWriteSteps > 0)
                 --*stopAfterWriteSteps;
             else
                 return;
         while (!buffer.empty())
         {
             std::size_t size = std::min<uint32_t>(buffer.size(), SizeOfSector(SectorOfAddress(address)) - AddressOffsetInSector(address));
             for (std::size_t i = 0; i != size; ++i)
                 sectors[SectorOfAddress(address)][AddressOffsetInSector(address) + i] &= buffer[i];
             buffer.pop_front(size);
             address = StartOfNextSector(address);
         }
     }
Member Data Documentation
delaySignalEraseDone
bool hal::FlashStub::delaySignalEraseDone = false
Definition at line 31 of file FlashStub.hpp.
Referenced by EraseSectors().
onEraseDone
infra::Function<void()> hal::FlashStub::onEraseDone
Definition at line 30 of file FlashStub.hpp.
Referenced by EraseSectors().
sectors
std::vector<std::vector<uint8_t> > hal::FlashStub::sectors
Definition at line 27 of file FlashStub.hpp.
Referenced by AddressOfSector(), EraseSectors(), FlashRegionTest::FlashRegionTest(), NumberOfSectors(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), and WriteBuffer().
stopAfterWriteSteps
infra::Optional<uint8_t> hal::FlashStub::stopAfterWriteSteps
Definition at line 28 of file FlashStub.hpp.
Referenced by WriteBuffer().
The documentation for this class was generated from the following files:
FlashStub.hpp
FlashStub.cpp