EMil: infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args > Class Template Reference
infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args > Class Template Reference
#include <ClockFixture.hpp>
Public Member Functions
TimeMatcher (infra::TimePoint expectedCallTime)
virtual bool MatchAndExplain (const std::tuple< Args... > &x, testing::MatchResultListener *listener) const override
virtual void DescribeTo (std::ostream *os) const override
Private Attributes
infra::TimePoint expectedCallTime
Detailed Description
template<class... Args>
class infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args >
Definition at line 50 of file ClockFixture.hpp.
Constructor & Destructor Documentation
TimeMatcher()
template<class... Args> infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args >::TimeMatcher (infra::TimePoint expectedCallTime)
Definition at line 70 of file ClockFixture.hpp.
         : expectedCallTime(expectedCallTime)
     {}
Member Function Documentation
DescribeTo()
template<class... Args> void infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args >::DescribeTo (std::ostream * os) const override virtual
Definition at line 81 of file ClockFixture.hpp.
References infra::endl, infra::ClockFixture::TimeMatcherHelper::expectedCallTime, infra::Now(), and infra::ClockFixture::TimeToString().
     {
         if (os)
         {
             *os << "To be called at " << TimeToString(expectedCallTime) << std::endl
                 << "                   It is now       " << TimeToString(infra::Now()) << std::endl;
         }
     }
MatchAndExplain()
template<class... Args> bool infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args >::MatchAndExplain (const std::tuple< Args... > & x, testing::MatchResultListener * listener) const override virtual
Definition at line 75 of file ClockFixture.hpp.
References infra::ClockFixture::TimeMatcherHelper::expectedCallTime, and infra::Now().
     {
         return expectedCallTime == infra::Now();
     }
Member Data Documentation
expectedCallTime
template<class... Args> infra::TimePoint infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args >::expectedCallTime private
Definition at line 60 of file ClockFixture.hpp.
The documentation for this class was generated from the following file:
ClockFixture.hpp