EMil: services::NameResolverResult Class Reference
services::NameResolverResult Class Reference abstract
#include <NameResolver.hpp>
Public Member Functions
virtual infra::BoundedConstString Hostname () const =0
virtual IPVersions Versions () const
virtual void NameLookupDone (IPAddress address, infra::TimePoint validUntil)=0
virtual void NameLookupFailed ()=0
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Protected Member Functions
NameResolverResult ()=default
NameResolverResult (const NameResolverResult &other)=delete
NameResolverResult & operator= (const NameResolverResult &other)=delete
~NameResolverResult ()=default
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 10 of file NameResolver.hpp.
Constructor & Destructor Documentation
NameResolverResult() [1/2]
services::NameResolverResult::NameResolverResult () protected default
NameResolverResult() [2/2]
services::NameResolverResult::NameResolverResult (const NameResolverResult & other) protected delete
~NameResolverResult()
services::NameResolverResult::~NameResolverResult () protected default
Member Function Documentation
Hostname()
virtual infra::BoundedConstString services::NameResolverResult::Hostname () const pure virtual
Implemented in services::ConnectionFactoryWithNameResolverImpl::Action, and services::NameResolverCache::ActiveLookup.
Referenced by services::NameLookupBsd::LookupIPv4(), services::NameLookupWin::LookupIPv4(), services::NameResolverCache::NameLookupSuccess(), and services::NameResolverCache::SearchCache().
NameLookupDone()
virtual void services::NameResolverResult::NameLookupDone (IPAddress address, infra::TimePoint validUntil) pure virtual
Implemented in services::ConnectionFactoryWithNameResolverImpl::Action, and services::NameResolverCache::ActiveLookup.
Referenced by services::NameResolverCache::Lookup(), services::NameLookupBsd::LookupIPv4(), services::NameLookupWin::LookupIPv4(), services::NameResolverCache::NameLookupSuccess(), and services::DnsResolver::NameLookupSuccess().
NameLookupFailed()
virtual void services::NameResolverResult::NameLookupFailed () pure virtual
Implemented in services::ConnectionFactoryWithNameResolverImpl::Action, and services::NameResolverCache::ActiveLookup.
Referenced by services::NameLookupBsd::LookupIPv4(), services::NameLookupWin::LookupIPv4(), services::NameResolverCache::NameLookupFailed(), and services::DnsResolver::NameLookupFailed().
operator=()
NameResolverResult& services::NameResolverResult::operator= (const NameResolverResult & other) protected delete
Versions()
virtual IPVersions services::NameResolverResult::Versions () const inline virtual
Reimplemented in services::NameResolverCache::ActiveLookup.
Definition at line 21 of file NameResolver.hpp.
References services::ipv4.
Referenced by services::NameLookupBsd::Lookup(), and services::NameLookupWin::Lookup().
 { return IPVersions::ipv4; }
The documentation for this class was generated from the following file:
NameResolver.hpp