EMil: hal::ChipSelectConfigurator Class Reference
hal::ChipSelectConfigurator Class Reference abstract
#include <Spi.hpp>
Public Member Functions
virtual void StartSession ()=0
virtual void EndSession ()=0
Protected Member Functions
ChipSelectConfigurator ()=default
ChipSelectConfigurator (const ChipSelectConfigurator &other)=delete
ChipSelectConfigurator & operator= (const ChipSelectConfigurator &other)=delete
~ChipSelectConfigurator ()=default
Detailed Description
Definition at line 18 of file Spi.hpp.
Constructor & Destructor Documentation
ChipSelectConfigurator() [1/2]
hal::ChipSelectConfigurator::ChipSelectConfigurator () protected default
ChipSelectConfigurator() [2/2]
hal::ChipSelectConfigurator::ChipSelectConfigurator (const ChipSelectConfigurator & other) protected delete
~ChipSelectConfigurator()
hal::ChipSelectConfigurator::~ChipSelectConfigurator () protected default
Member Function Documentation
EndSession()
virtual void hal::ChipSelectConfigurator::EndSession () pure virtual
Implemented in services::SpiMultipleAccess, and services::SpiMasterWithChipSelect.
Referenced by services::SpiMasterWithChipSelect::EndSession(), and services::SpiMultipleAccess::EndSession().
operator=()
ChipSelectConfigurator& hal::ChipSelectConfigurator::operator= (const ChipSelectConfigurator & other) protected delete
StartSession()
virtual void hal::ChipSelectConfigurator::StartSession () pure virtual
Implemented in services::SpiMultipleAccess, and services::SpiMasterWithChipSelect.
Referenced by services::SpiMasterWithChipSelect::StartSession(), and services::SpiMultipleAccess::StartSession().
The documentation for this class was generated from the following file:
Spi.hpp