EMil: application::ImageSignerEcDsa Class Reference
application::ImageSignerEcDsa Class Reference
#include <ImageSignerEcDsa.hpp>
Public Member Functions
ImageSignerEcDsa (RandomNumberGenerator &randomNumberGenerator, infra::ConstByteRange publicKey, infra::ConstByteRange privateKey)
virtual uint16_t SignatureMethod () const override
virtual uint16_t SignatureLength () const override
virtual std::vector< uint8_t > ImageSignature (const std::vector< uint8_t > &image) override
virtual bool CheckSignature (const std::vector< uint8_t > &signature, const std::vector< uint8_t > &image) override
Static Public Attributes
static const uint16_t signatureMethod = 1
static const size_t keyLength = 224
Private Member Functions
void CalculateSha256 (const std::vector< uint8_t > &image)
void CalculateSignature (const std::vector< uint8_t > &image)
Static Private Member Functions
static int MyRandom (uint8_t *dest, unsigned size)
Private Attributes
infra::ConstByteRange publicKey
infra::ConstByteRange privateKey
std::string keyFileName
std::array< uint8_t, 32 > hash
std::array< uint8_t, keyLength/8 *2 > signature
Static Private Attributes
static RandomNumberGenerator * randomNumberGenerator = nullptr
Additional Inherited Members
Protected Member Functions inherited from application::ImageSigner
~ImageSigner ()=default
Detailed Description
Definition at line 13 of file ImageSignerEcDsa.hpp.
Constructor & Destructor Documentation
ImageSignerEcDsa()
application::ImageSignerEcDsa::ImageSignerEcDsa (RandomNumberGenerator & randomNumberGenerator, infra::ConstByteRange publicKey, infra::ConstByteRange privateKey)
Definition at line 9 of file ImageSignerEcDsa.cpp.
References MyRandom(), and randomNumberGenerator.
         : publicKey(publicKey)
         , privateKey(privateKey)
     {
         ImageSignerEcDsa::randomNumberGenerator = &randomNumberGenerator;
         uECC_set_rng(MyRandom);
     }
Member Function Documentation
CalculateSha256()
void application::ImageSignerEcDsa::CalculateSha256 (const std::vector< uint8_t > & image) private
Definition at line 46 of file ImageSignerEcDsa.cpp.
References hash.
Referenced by CheckSignature(), and ImageSignature().
     {
         mbedtls_sha256_context ctx;
         mbedtls_sha256_init(&ctx);
         mbedtls_sha256_starts(&ctx, 0);
         mbedtls_sha256_update(&ctx, image.data(), image.size());
         mbedtls_sha256_finish(&ctx, hash.data());                                                                       //TICS !INT#030
         mbedtls_sha256_free(&ctx);
     }
CalculateSignature()
void application::ImageSignerEcDsa::CalculateSignature (const std::vector< uint8_t > & image) private
Definition at line 56 of file ImageSignerEcDsa.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), hash, keyLength, privateKey, publicKey, signature, and infra::MemoryRange< T >::size().
Referenced by ImageSignature().
     {
         if (privateKey.size() != signature.size())
             throw std::exception("Key length wrong");
         std::array<uint8_t, keyLength / 8 * 2> publicKeyForVerification;
         int result = uECC_compute_public_key(privateKey.begin(), publicKeyForVerification.data(), uECC_secp224r1());
         if (result != 1)
             throw std::exception("Failed to compute public key");
         if (!std::equal(publicKey.begin(), publicKey.end(), publicKeyForVerification.begin()))
             throw std::exception("Inconsistent private key pair");
         int ret = uECC_sign(privateKey.begin(), hash.data(), hash.size(), signature.data(), uECC_secp224r1());
         if (ret != 1)
             throw std::exception("Failed to calculate signature");
     }
CheckSignature()
bool application::ImageSignerEcDsa::CheckSignature (const std::vector< uint8_t > & signature, const std::vector< uint8_t > & image) override virtual
Implements application::ImageSigner.
Definition at line 35 of file ImageSignerEcDsa.cpp.
References infra::MemoryRange< T >::begin(), CalculateSha256(), hash, publicKey, signature, and infra::MemoryRange< T >::size().
     {
         std::copy(signature.begin(), signature.end(), this->signature.begin());
         CalculateSha256(image);
         if (publicKey.size() != signature.size())
             return false;
         return uECC_verify(publicKey.begin(), hash.data(), hash.size(), signature.data(), uECC_secp224r1()) == 1;
     }
ImageSignature()
std::vector< uint8_t > application::ImageSignerEcDsa::ImageSignature (const std::vector< uint8_t > & image) override virtual
Implements application::ImageSigner.
Definition at line 27 of file ImageSignerEcDsa.cpp.
References CalculateSha256(), CalculateSignature(), and signature.
     {
         CalculateSha256(image);
         CalculateSignature(image);
         return std::vector<uint8_t>(signature.begin(), signature.end());
     }
MyRandom()
int application::ImageSignerEcDsa::MyRandom (uint8_t * dest, unsigned size) static private
Definition at line 74 of file ImageSignerEcDsa.cpp.
References application::RandomNumberGenerator::Generate(), and randomNumberGenerator.
Referenced by ImageSignerEcDsa().
     {
         std::vector<uint8_t> entropy = randomNumberGenerator->Generate(size);
         std::copy(entropy.begin(), entropy.end(), dest);
         return 1;
     }
SignatureLength()
uint16_t application::ImageSignerEcDsa::SignatureLength () const override virtual
Implements application::ImageSigner.
Definition at line 22 of file ImageSignerEcDsa.cpp.
References signature.
     {
         return static_cast<uint16_t>(signature.size());
     }
SignatureMethod()
uint16_t application::ImageSignerEcDsa::SignatureMethod () const override virtual
Implements application::ImageSigner.
Definition at line 17 of file ImageSignerEcDsa.cpp.
References signatureMethod.
     {
         return signatureMethod;
     }
Member Data Documentation
hash
std::array<uint8_t, 32> application::ImageSignerEcDsa::hash private
Definition at line 38 of file ImageSignerEcDsa.hpp.
Referenced by CalculateSha256(), CalculateSignature(), and CheckSignature().
keyFileName
std::string application::ImageSignerEcDsa::keyFileName private
Definition at line 37 of file ImageSignerEcDsa.hpp.
keyLength
const size_t application::ImageSignerEcDsa::keyLength = 224 static
Definition at line 25 of file ImageSignerEcDsa.hpp.
Referenced by CalculateSignature().
privateKey
infra::ConstByteRange application::ImageSignerEcDsa::privateKey private
Definition at line 35 of file ImageSignerEcDsa.hpp.
Referenced by CalculateSignature().
publicKey
infra::ConstByteRange application::ImageSignerEcDsa::publicKey private
Definition at line 34 of file ImageSignerEcDsa.hpp.
Referenced by CalculateSignature(), and CheckSignature().
randomNumberGenerator
RandomNumberGenerator * application::ImageSignerEcDsa::randomNumberGenerator = nullptr static private
Definition at line 36 of file ImageSignerEcDsa.hpp.
Referenced by ImageSignerEcDsa(), and MyRandom().
signature
std::array<uint8_t, keyLength / 8 * 2> application::ImageSignerEcDsa::signature private
Definition at line 39 of file ImageSignerEcDsa.hpp.
Referenced by CalculateSignature(), CheckSignature(), ImageSignature(), and SignatureLength().
signatureMethod
const uint16_t application::ImageSignerEcDsa::signatureMethod = 1 static
Definition at line 24 of file ImageSignerEcDsa.hpp.
Referenced by SignatureMethod().
The documentation for this class was generated from the following files:
ImageSignerEcDsa.hpp
ImageSignerEcDsa.cpp