EMil: services::MqttClientImpl::StateConnecting Class Reference
services::MqttClientImpl::StateConnecting Class Reference
Public Member Functions
StateConnecting (MqttClientImpl &clientConnection, MqttClientObserverFactory &factory, infra::BoundedConstString clientId, infra::BoundedConstString username, infra::BoundedConstString password)
virtual void Connected () override
virtual void ClosingConnection () override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived (infra::StreamReader &reader) override
Public Member Functions inherited from services::MqttClientImpl::StateBase
StateBase (MqttClientImpl &clientConnection)
StateBase (const StateBase &other)=delete
StateBase & operator= (const StateBase &other)=delete
virtual ~StateBase ()=default
virtual void Publish (infra::BoundedConstString topic, infra::BoundedConstString payload)
Private Member Functions
void Timeout ()
Private Attributes
MqttClientObserverFactory & factory
infra::BoundedConstString clientId
infra::BoundedConstString username
infra::BoundedConstString password
infra::TimerSingleShot timeout
bool signaledFailure = false
Additional Inherited Members
Protected Attributes inherited from services::MqttClientImpl::StateBase
MqttClientImpl & clientConnection
Detailed Description
Definition at line 128 of file MqttClientImpl.hpp.
Constructor & Destructor Documentation
StateConnecting()
services::MqttClientImpl::StateConnecting::StateConnecting (MqttClientImpl & clientConnection, MqttClientObserverFactory & factory, infra::BoundedConstString clientId, infra::BoundedConstString username, infra::BoundedConstString password)
Definition at line 146 of file MqttClientImpl.cpp.
References Timeout().
         : StateBase(clientConnection)
         , factory(factory)
         , clientId(clientId)
         , username(username)
         , password(password)
         , timeout(std::chrono::minutes(1), [this]() { Timeout(); })
     {}
Member Function Documentation
ClosingConnection()
void services::MqttClientImpl::StateConnecting::ClosingConnection () override virtual
Implements services::MqttClientImpl::StateBase.
Definition at line 160 of file MqttClientImpl.cpp.
     {
         if (!signaledFailure)
             factory.ConnectionFailed(MqttClientObserverFactory::ConnectFailReason::initializationFailed);
     }
Connected()
void services::MqttClientImpl::StateConnecting::Connected () override virtual
Reimplemented from services::MqttClientImpl::StateBase.
Definition at line 155 of file MqttClientImpl.cpp.
References services::MqttClientImpl::MqttFormatter::MessageSizeConnect().
     {
         clientConnection.ConnectionObserver::Subject().RequestSendStream(MqttFormatter::MessageSizeConnect(clientId, username, password));
     }
DataReceived()
void services::MqttClientImpl::StateConnecting::DataReceived (infra::StreamReader & reader) override virtual
Implements services::MqttClientImpl::StateBase.
Definition at line 173 of file MqttClientImpl.cpp.
References infra::InputStream::Failed(), services::MqttClientImpl::MqttParser::GetPacketType(), services::MqttClientImpl::observer, services::MqttClientImpl::packetTypeConAck, and infra::softFail.
     {
         infra::DataInputStream::WithErrorPolicy stream(reader, infra::softFail);
         MqttParser parser(stream);
         if (stream.Failed())
             return;
         if (parser.GetPacketType() == PacketType::packetTypeConAck)
         {
             uint8_t connectAcknowledgeFlags;
             uint8_t connectReturnCode;
             stream >> connectAcknowledgeFlags >> connectReturnCode;
             if (stream.Failed())
                 return;
             clientConnection.ConnectionObserver::Subject().AckReceived();
             factory.ConnectionEstablished([this, &reader](infra::SharedPtr<MqttClientObserver> observer)
             {
                 if (observer)
                 {
                     observer->Attach(clientConnection);
                     clientConnection.observer = observer;
                     auto& newState = clientConnection.state.Emplace<StateConnected>(clientConnection);
                     observer->Connected();
                     newState.DataReceived(reader);
                 }
                 else
                 {
                     signaledFailure = true; // The factory already got a ConnectionEstablished, so it should not get a ConnectionFailed
                     clientConnection.ConnectionObserver::Subject().AbortAndDestroy();
                 }
             });
         }
         else
             clientConnection.ConnectionObserver::Subject().AbortAndDestroy();
     }
SendStreamAvailable()
void services::MqttClientImpl::StateConnecting::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::MqttClientImpl::StateBase.
Definition at line 166 of file MqttClientImpl.cpp.
References services::MqttClientImpl::MqttFormatter::MessageConnect().
     {
         infra::DataOutputStream::WithErrorPolicy stream(*writer);
         MqttFormatter formatter(stream);
         formatter.MessageConnect(clientId, username, password);
     }
Timeout()
void services::MqttClientImpl::StateConnecting::Timeout () private
Definition at line 212 of file MqttClientImpl.cpp.
Referenced by StateConnecting().
     {
         signaledFailure = true;
         factory.ConnectionFailed(MqttClientObserverFactory::ConnectFailReason::initializationTimedOut);
         clientConnection.ConnectionObserver::Subject().AbortAndDestroy();
     }
Member Data Documentation
clientId
infra::BoundedConstString services::MqttClientImpl::StateConnecting::clientId private
Definition at line 144 of file MqttClientImpl.hpp.
factory
MqttClientObserverFactory& services::MqttClientImpl::StateConnecting::factory private
Definition at line 143 of file MqttClientImpl.hpp.
password
infra::BoundedConstString services::MqttClientImpl::StateConnecting::password private
Definition at line 146 of file MqttClientImpl.hpp.
signaledFailure
bool services::MqttClientImpl::StateConnecting::signaledFailure = false private
Definition at line 148 of file MqttClientImpl.hpp.
timeout
infra::TimerSingleShot services::MqttClientImpl::StateConnecting::timeout private
Definition at line 147 of file MqttClientImpl.hpp.
username
infra::BoundedConstString services::MqttClientImpl::StateConnecting::username private
Definition at line 145 of file MqttClientImpl.hpp.
The documentation for this class was generated from the following files:
MqttClientImpl.hpp
MqttClientImpl.cpp