EMil: TestSignalLed.cpp File Reference
TestSignalLed.cpp File Reference
Classes
class SignalLedTest
Functions
TEST_F (SignalLedTest, StayOffWhenNoPatternIsLoaded)
TEST_F (SignalLedTest, TurnOnImmediatelyWhenPatternIsOn)
TEST_F (SignalLedTest, StayOffWhenPatternIsOff)
TEST_F (SignalLedTest, TurnOnAfterPeriod)
TEST_F (SignalLedTest, TurnOffAfterPeriod)
TEST_F (SignalLedTest, TurnOnAndOffPeriodically)
Function Documentation
TEST_F() [1/6]
TEST_F (SignalLedTest , StayOffWhenNoPatternIsLoaded)
Definition at line 19 of file TestSignalLed.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(led.GetOutputLatch());
 }
TEST_F() [2/6]
TEST_F (SignalLedTest , TurnOnImmediatelyWhenPatternIsOn)
Definition at line 24 of file TestSignalLed.cpp.
References EXPECT_TRUE().
 {
     signalLed.Set(1, 2);
     EXPECT_TRUE(led.GetOutputLatch());
 }
TEST_F() [3/6]
TEST_F (SignalLedTest , StayOffWhenPatternIsOff)
Definition at line 31 of file TestSignalLed.cpp.
References EXPECT_FALSE().
 {
     signalLed.Set(0, 2);
     EXPECT_FALSE(led.GetOutputLatch());
 }
TEST_F() [4/6]
TEST_F (SignalLedTest , TurnOnAfterPeriod)
Definition at line 38 of file TestSignalLed.cpp.
References EXPECT_EQ().
 {
     signalLed.Set(2, 2);
     ForwardTime(std::chrono::seconds(1));
     EXPECT_EQ((std::vector<hal::PinChange>{ { std::chrono::seconds(1), true } }), led.PinChanges());
 }
TEST_F() [5/6]
TEST_F (SignalLedTest , TurnOffAfterPeriod)
Definition at line 46 of file TestSignalLed.cpp.
References EXPECT_EQ().
 {
     signalLed.Set(1, 2);
     ForwardTime(std::chrono::seconds(1));
     EXPECT_EQ((std::vector<hal::PinChange>{ { std::chrono::seconds(0), true }, { std::chrono::seconds(1), false } }), led.PinChanges());
 }
TEST_F() [6/6]
TEST_F (SignalLedTest , TurnOnAndOffPeriodically)
Definition at line 54 of file TestSignalLed.cpp.
References EXPECT_EQ().
 {
     signalLed.Set(0xb, 4);  // binary: 1011
     ForwardTime(std::chrono::seconds(8));
     EXPECT_EQ((std::vector<hal::PinChange>{
         { std::chrono::seconds(0), true },
         { std::chrono::seconds(2), false },
         { std::chrono::seconds(3), true },
         { std::chrono::seconds(6), false },
         { std::chrono::seconds(7), true }
         }), led.PinChanges());
 }