EMil: application::PackUpgrader Class Reference
application::PackUpgrader Class Reference
#include <PackUpgrader.hpp>
Public Member Functions
PackUpgrader (hal::SynchronousFlash &upgradePackFlash)
void UpgradeFromImages (infra::MemoryRange< ImageUpgrader *> imageUpgraders)
bool HasImage (const char *imageName) const
void MarkAsError (uint32_t errorCode)
Private Member Functions
bool TryUpgradeImage (infra::MemoryRange< ImageUpgrader *> imageUpgraders)
bool IsImage (uint32_t &imageAddress, const char *imageName) const
void MarkAsDeployStarted ()
void MarkAsDeployed ()
Private Attributes
hal::SynchronousFlash & upgradePackFlash
uint32_t address = 0
Detailed Description
Definition at line 11 of file PackUpgrader.hpp.
Constructor & Destructor Documentation
PackUpgrader()
application::PackUpgrader::PackUpgrader (hal::SynchronousFlash & upgradePackFlash) explicit
Definition at line 6 of file PackUpgrader.cpp.
         : upgradePackFlash(upgradePackFlash)
     {}
Member Function Documentation
HasImage()
bool application::PackUpgrader::HasImage (const char * imageName) const
Definition at line 42 of file PackUpgrader.cpp.
References IsImage(), infra::MakeByteRange(), application::UpgradePackHeaderEpilogue::numberOfImages, hal::SynchronousFlash::ReadBuffer(), application::UpgradePackHeaderPrologue::signatureLength, and upgradePackFlash.
     {
         uint32_t imageAddress = 0;
         UpgradePackHeaderPrologue headerPrologue;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(headerPrologue), imageAddress);
         imageAddress += sizeof(UpgradePackHeaderPrologue);
         imageAddress += headerPrologue.signatureLength;
         UpgradePackHeaderEpilogue headerEpilogue;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(headerEpilogue), imageAddress);
         imageAddress += sizeof(UpgradePackHeaderEpilogue);
         for (std::size_t imageIndex = 0; imageIndex != headerEpilogue.numberOfImages; ++imageIndex)
         {
             if (IsImage(imageAddress, imageName))
                 return true;
         }
         return false;
     }
IsImage()
bool application::PackUpgrader::IsImage (uint32_t & imageAddress, const char * imageName) const private
Definition at line 103 of file PackUpgrader.cpp.
References application::ImageHeaderPrologue::lengthOfHeaderAndImage, infra::MakeByteRange(), hal::SynchronousFlash::ReadBuffer(), application::ImageHeaderPrologue::targetName, and upgradePackFlash.
Referenced by HasImage().
     {
         ImageHeaderPrologue imageHeader;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(imageHeader), imageAddress);
         imageAddress += imageHeader.lengthOfHeaderAndImage;
         return std::strncmp(imageHeader.targetName.data(), imageName, imageHeader.targetName.size()) == 0;
     }
MarkAsDeployed()
void application::PackUpgrader::MarkAsDeployed () private
Definition at line 118 of file PackUpgrader.cpp.
References application::deployed, infra::MakeByteRange(), upgradePackFlash, and hal::SynchronousFlash::WriteBuffer().
Referenced by UpgradeFromImages().
     {
         static const UpgradePackStatus statusDone = UpgradePackStatus::deployed;
         upgradePackFlash.WriteBuffer(infra::MakeByteRange(statusDone), 0);
     }
MarkAsDeployStarted()
void application::PackUpgrader::MarkAsDeployStarted () private
Definition at line 112 of file PackUpgrader.cpp.
References application::deployStarted, infra::MakeByteRange(), upgradePackFlash, and hal::SynchronousFlash::WriteBuffer().
Referenced by UpgradeFromImages().
     {
         static const UpgradePackStatus statusStarted = UpgradePackStatus::deployStarted;
         upgradePackFlash.WriteBuffer(infra::MakeByteRange(statusStarted), 0);
     }
MarkAsError()
void application::PackUpgrader::MarkAsError (uint32_t errorCode)
Definition at line 124 of file PackUpgrader.cpp.
References application::invalid, infra::MakeByteRange(), upgradePackFlash, and hal::SynchronousFlash::WriteBuffer().
Referenced by TryUpgradeImage(), and UpgradeFromImages().
     {
         static const UpgradePackStatus statusError = UpgradePackStatus::invalid;
         upgradePackFlash.WriteBuffer(infra::MakeByteRange(statusError), 0);
         upgradePackFlash.WriteBuffer(infra::MakeByteRange(errorCode), 4);
     }
TryUpgradeImage()
bool application::PackUpgrader::TryUpgradeImage (infra::MemoryRange< ImageUpgrader *> imageUpgraders) private
Definition at line 64 of file PackUpgrader.cpp.
References address, application::ImageHeaderEpilogue::destinationAddress, application::ImageHeaderEpilogue::imageSize, application::ImageHeaderPrologue::lengthOfHeaderAndImage, infra::MakeByteRange(), MarkAsError(), hal::SynchronousFlash::ReadBuffer(), infra::MemoryRange< T >::size(), application::ImageHeaderPrologue::targetName, application::upgradeErrorCodeNoSuitableImageUpgraderFound, and upgradePackFlash.
Referenced by UpgradeFromImages().
     {
         ImageHeaderPrologue imageHeader;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(imageHeader), address);
         uint32_t imageAddress = address;
         address += imageHeader.lengthOfHeaderAndImage;
         for (auto& imageUpgrader: imageUpgraders)
         {
             if (std::strncmp(imageHeader.targetName.data(), imageUpgrader->TargetName(), imageHeader.targetName.size()) == 0)
             {
                 imageAddress += sizeof(imageHeader);
                 infra::ByteRange decryptorState = imageUpgrader->ImageDecryptor().StateBuffer();
                 upgradePackFlash.ReadBuffer(decryptorState, imageAddress);
                 imageUpgrader->ImageDecryptor().Reset();
                 imageAddress += decryptorState.size();
                 ImageHeaderEpilogue imageHeaderEpilogue;
                 upgradePackFlash.ReadBuffer(infra::MakeByteRange(imageHeaderEpilogue), imageAddress);
                 imageAddress += sizeof(imageHeaderEpilogue);
                 imageUpgrader->ImageDecryptor().DecryptPart(infra::MakeByteRange(imageHeaderEpilogue));
                 uint32_t upgradeResult = imageUpgrader->Upgrade(upgradePackFlash, imageAddress, imageHeaderEpilogue.imageSize, imageHeaderEpilogue.destinationAddress);
                 if (upgradeResult != 0)
                 {
                     MarkAsError(upgradeResult);
                     return false;
                 }
                 return true;
             }
         }
         MarkAsError(upgradeErrorCodeNoSuitableImageUpgraderFound);
         return false;
     }
UpgradeFromImages()
void application::PackUpgrader::UpgradeFromImages (infra::MemoryRange< ImageUpgrader *> imageUpgraders)
Definition at line 10 of file PackUpgrader.cpp.
References address, application::UpgradePackHeaderEpilogue::headerVersion, application::UpgradePackHeaderPrologue::magic, infra::MakeByteRange(), MarkAsDeployed(), MarkAsDeployStarted(), MarkAsError(), application::UpgradePackHeaderEpilogue::numberOfImages, hal::SynchronousFlash::ReadBuffer(), application::UpgradePackHeaderPrologue::signatureLength, TryUpgradeImage(), application::upgradeErrorCodeUnknownHeaderVersion, upgradePackFlash, and application::upgradePackMagic.
     {
         UpgradePackHeaderPrologue headerPrologue;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(headerPrologue), address);
         address += sizeof(UpgradePackHeaderPrologue);
         bool sanity = headerPrologue.magic == upgradePackMagic;
         if (!sanity)
             return;
         MarkAsDeployStarted();
         address += headerPrologue.signatureLength;
         UpgradePackHeaderEpilogue headerEpilogue;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(headerEpilogue), address);
         address += sizeof(UpgradePackHeaderEpilogue);
         if (headerEpilogue.headerVersion != 1)
             MarkAsError(upgradeErrorCodeUnknownHeaderVersion);
         else
         {
             for (std::size_t imageIndex = 0; imageIndex != headerEpilogue.numberOfImages; ++imageIndex)
             {
                 if (!TryUpgradeImage(imageUpgraders))
                     return;
             }
             MarkAsDeployed();
         }
     }
Member Data Documentation
address
uint32_t application::PackUpgrader::address = 0 private
Definition at line 29 of file PackUpgrader.hpp.
Referenced by TryUpgradeImage(), and UpgradeFromImages().
upgradePackFlash
hal::SynchronousFlash& application::PackUpgrader::upgradePackFlash private
Definition at line 28 of file PackUpgrader.hpp.
Referenced by HasImage(), IsImage(), MarkAsDeployed(), MarkAsDeployStarted(), MarkAsError(), TryUpgradeImage(), and UpgradeFromImages().
The documentation for this class was generated from the following files:
PackUpgrader.hpp
PackUpgrader.cpp