EMil: infra::EventDispatcherWorker Class Reference
infra::EventDispatcherWorker Class Reference abstract
#include <EventDispatcher.hpp>
Public Member Functions
virtual void Schedule (const infra::Function< void()> &action)=0
virtual void ExecuteFirstAction ()=0
virtual std::size_t MinCapacity () const =0
virtual bool IsIdle () const =0
Protected Member Functions
EventDispatcherWorker ()=default
EventDispatcherWorker (const EventDispatcherWorker &other)=delete
EventDispatcherWorker & operator= (const EventDispatcherWorker &other)=delete
~EventDispatcherWorker ()=default
Detailed Description
Definition at line 11 of file EventDispatcher.hpp.
Constructor & Destructor Documentation
EventDispatcherWorker() [1/2]
infra::EventDispatcherWorker::EventDispatcherWorker () protected default
EventDispatcherWorker() [2/2]
infra::EventDispatcherWorker::EventDispatcherWorker (const EventDispatcherWorker & other) protected delete
~EventDispatcherWorker()
infra::EventDispatcherWorker::~EventDispatcherWorker () protected default
Member Function Documentation
ExecuteFirstAction()
virtual void infra::EventDispatcherWorker::ExecuteFirstAction () pure virtual
Implemented in infra::EventDispatcherWithWeakPtrWorker, and infra::EventDispatcherWorkerImpl.
IsIdle()
virtual bool infra::EventDispatcherWorker::IsIdle () const pure virtual
Implemented in infra::EventDispatcherWithWeakPtrWorker, and infra::EventDispatcherWorkerImpl.
MinCapacity()
virtual std::size_t infra::EventDispatcherWorker::MinCapacity () const pure virtual
Implemented in infra::EventDispatcherWithWeakPtrWorker, and infra::EventDispatcherWorkerImpl.
operator=()
EventDispatcherWorker& infra::EventDispatcherWorker::operator= (const EventDispatcherWorker & other) protected delete
Schedule()
virtual void infra::EventDispatcherWorker::Schedule (const infra::Function< void()> & action) pure virtual
Implemented in infra::EventDispatcherWithWeakPtrWorker, and infra::EventDispatcherWorkerImpl.
Referenced by infra::ClaimableResource::AddClaim(), services::ConnectionSerial::AllocatedSendStream(), services::ConnectionBsd::ConnectionBsd(), services::ConnectionWin::ConnectionWin(), services::FlashQuadSpi::EraseSectors(), services::FlashSpi::EraseSectors(), services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll(), services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q(), services::DatagramBsd::InitSocket(), services::DatagramWin::InitSocket(), services::NameLookupBsd::LookupIPv4(), services::NameLookupWin::LookupIPv4(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::NotifyDataAvailable(), infra::TickOnInterruptTimerService::ProcessTicks(), infra::SystemStateParticipant::ReachedState(), infra::ClaimableResource::RemoveClaim(), services::ConnectionSerial::SendStreamFilled(), infra::TickOnInterruptTimerService::SystemTickInterrupt(), hal::TimerServiceBsd::WaitForTrigger(), hal::TimerServiceWin::WaitForTrigger(), services::FlashSpi::WriteBuffer(), services::FlashQuadSpi::WriteBufferSequence(), and services::CyclicStore::WriteRange().
The documentation for this class was generated from the following file:
EventDispatcher.hpp