EMil: infra::Sequencer Class Reference
infra::Sequencer Class Reference
#include <Sequencer.hpp>
Public Types
using Function = infra::Function< void(), INFRA_SEQUENCER_FUNCTION_EXTRA_SIZE >
Public Member Functions
void Load (const Function &newSequence)
void Step (const Function &action)
void Execute (const Function &action)
void If (const infra::Function< bool()> &condition)
void ElseIf (const infra::Function< bool()> &condition)
void Else ()
void EndIf ()
void While (const infra::Function< bool()> &condition)
void EndWhile ()
void DoWhile ()
void EndDoWhile (const infra::Function< bool()> &condition)
void ForEach (uint32_t &variable, uint32_t from, uint32_t to)
void EndForEach (uint32_t &variable)
void Continue ()
bool Finished () const
Private Member Functions
void ExecuteWithoutContext (const Function &action)
void IncreaseCurrentStep ()
bool ExecuteCurrentStep () const
void ExecutePreviousStep ()
void ExecuteNextStep ()
void PushContext ()
void PopContext ()
Private Attributes
Function sequence
infra::BoundedVector< uint8_t >::WithMaxSize< 8 > execute
infra::BoundedVector< uint8_t >::WithMaxSize< 8 > examine
bool repeat = false
Detailed Description
Definition at line 13 of file Sequencer.hpp.
Member Typedef Documentation
Function
using infra::Sequencer::Function = infra::Function<void(), INFRA_SEQUENCER_FUNCTION_EXTRA_SIZE>
Definition at line 16 of file Sequencer.hpp.
Member Function Documentation
Continue()
void infra::Sequencer::Continue ()
Definition at line 12 of file Sequencer.cpp.
References infra::BoundedVector< T >::clear(), examine, ExecuteNextStep(), Finished(), PopContext(), PushContext(), repeat, and sequence.
Referenced by services::CyclicStore::Clear(), application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::EraseSectorIfAtStart(), services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll(), services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q(), services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress(), services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress(), services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress(), services::FlashSpi::HoldWhileWriteInProgress(), Load(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashSpi::PageProgram(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), services::FlashSpi::ReadStatusRegister(), services::CyclicStore::Recover(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::RecoverSector(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiMicronN25q::SendEraseBulk(), services::FlashQuadSpiSingleSpeed::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashSpi::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), services::FlashSpi::SendEraseSubSector(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToQuadSpeed(), services::FlashQuadSpiSingleSpeed::WriteEnable(), services::FlashQuadSpiMicronN25q::WriteEnable(), services::FlashQuadSpiCypressFll::WriteEnable(), services::FlashSpi::WriteEnable(), services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed(), services::CyclicStore::WriteRange(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         examine.clear();
         repeat = true;
         while (repeat)
         {
             repeat = false;
             PushContext();
             sequence();
             PopContext();
         }
         if (!Finished())
             ExecuteNextStep();
     }
DoWhile()
void infra::Sequencer::DoWhile ()
Definition at line 123 of file Sequencer.cpp.
References infra::emptyFunction, ExecuteWithoutContext(), and PushContext().
     {
         ExecuteWithoutContext(infra::emptyFunction);
         PushContext();
     }
Else()
void infra::Sequencer::Else ()
Definition at line 97 of file Sequencer.cpp.
References ExecuteNextStep(), ExecuteWithoutContext(), PopContext(), and PushContext().
Referenced by application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::Iterator::Read(), and services::CyclicStore::RecoverEndAddress().
     {
         PopContext();
         ExecuteWithoutContext([this]() { ExecuteNextStep(); });
         PushContext();
     }
ElseIf()
void infra::Sequencer::ElseIf (const infra::Function< bool()> & condition)
Definition at line 68 of file Sequencer.cpp.
References ExecuteNextStep(), ExecuteWithoutContext(), PopContext(), and PushContext().
Referenced by application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Recover(), and services::CyclicStore::RecoverEndAddress().
     {
         PopContext();
         ExecuteWithoutContext([this]()
         {
             ExecuteNextStep();
             ExecuteNextStep();
         });
         ExecuteWithoutContext([this, condition]()
         {
             if (!condition())
             {
                 ExecuteNextStep();
                 ExecuteNextStep();  // Immediately continue with the step after EndIf, Else, or EndWhile
             }
         });
         PushContext();
     }
EndDoWhile()
void infra::Sequencer::EndDoWhile (const infra::Function< bool()> & condition)
Definition at line 130 of file Sequencer.cpp.
References ExecutePreviousStep(), ExecuteWithoutContext(), and PopContext().
     {
         PopContext();
         ExecuteWithoutContext([this, condition]()
         {
             if (condition())
             {
                 ExecutePreviousStep();
                 ExecutePreviousStep();
                 ExecutePreviousStep();
             }
         });
     }
EndForEach()
void infra::Sequencer::EndForEach (uint32_t & variable)
Definition at line 177 of file Sequencer.cpp.
References ExecutePreviousStep(), ExecuteWithoutContext(), and PopContext().
Referenced by services::CyclicStore::Recover().
     {
         ExecuteWithoutContext([this, &variable]() { ++variable; });
         PopContext();
         ExecuteWithoutContext([this]()
         {
             ExecutePreviousStep();
             ExecutePreviousStep();
             ExecutePreviousStep();
         });
     }
EndIf()
void infra::Sequencer::EndIf ()
Definition at line 90 of file Sequencer.cpp.
References infra::emptyFunction, ExecuteWithoutContext(), and PopContext().
Referenced by services::CyclicStore::Add(), application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), services::CyclicStore::Recover(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::WriteRange(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         PopContext();
         ExecuteWithoutContext(infra::emptyFunction);
     }
EndWhile()
void infra::Sequencer::EndWhile ()
Definition at line 111 of file Sequencer.cpp.
References ExecutePreviousStep(), ExecuteWithoutContext(), and PopContext().
Referenced by application::DeployPackToExternal::DeployPackToExternal(), services::FlashQuadSpi::EraseSectors(), services::FlashSpi::EraseSectors(), services::FlashSpi::HoldWhileWriteInProgress(), services::CyclicStore::Iterator::Read(), services::CyclicStore::RecoverEndAddress(), services::FlashSpi::WriteBuffer(), and services::FlashQuadSpi::WriteBufferSequence().
     {
         PopContext();
         ExecuteWithoutContext([this]()
         {
             ExecutePreviousStep();
             ExecutePreviousStep();
             ExecutePreviousStep();
         });
     }
Execute()
void infra::Sequencer::Execute (const Function & action)
Definition at line 38 of file Sequencer.cpp.
References examine, execute, IncreaseCurrentStep(), PopContext(), PushContext(), infra::BoundedVector< T >::resize(), and infra::BoundedVector< T >::size().
Referenced by services::CyclicStore::Add(), services::CyclicStore::Clear(), application::DeployPackToExternal::DeployPackToExternal(), services::FlashQuadSpi::EraseSectors(), services::FlashSpi::EraseSectors(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), services::CyclicStore::Recover(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::RecoverSector(), services::FlashSpi::WriteBuffer(), and services::FlashQuadSpi::WriteBufferSequence().
     {
         decltype(execute) executeCopy = execute;
         if (executeCopy.size() > examine.size())
             executeCopy.resize(examine.size());
         if (executeCopy == examine)
         {
             PushContext();
             action();
             PopContext();
         }
         else
             IncreaseCurrentStep();
     }
ExecuteCurrentStep()
bool infra::Sequencer::ExecuteCurrentStep () const private
Definition at line 207 of file Sequencer.cpp.
References examine, and execute.
Referenced by ExecuteWithoutContext(), PopContext(), PushContext(), and Step().
     {
         return execute == examine;
     }
ExecuteNextStep()
void infra::Sequencer::ExecuteNextStep () private
Definition at line 212 of file Sequencer.cpp.
References infra::BoundedVector< T >::back(), and execute.
Referenced by Continue(), Else(), ElseIf(), ExecuteWithoutContext(), If(), and PopContext().
     {
         ++execute.back();
     }
ExecutePreviousStep()
void infra::Sequencer::ExecutePreviousStep () private
Definition at line 217 of file Sequencer.cpp.
References infra::BoundedVector< T >::back(), execute, and repeat.
Referenced by EndDoWhile(), EndForEach(), and EndWhile().
     {
         --execute.back();
         repeat = true;
     }
ExecuteWithoutContext()
void infra::Sequencer::ExecuteWithoutContext (const Function & action) private
Definition at line 191 of file Sequencer.cpp.
References ExecuteCurrentStep(), ExecuteNextStep(), and IncreaseCurrentStep().
Referenced by DoWhile(), Else(), ElseIf(), EndDoWhile(), EndForEach(), EndIf(), EndWhile(), ForEach(), and If().
     {
         if (ExecuteCurrentStep())
         {
             action();
             ExecuteNextStep();
         }
         IncreaseCurrentStep();
     }
Finished()
bool infra::Sequencer::Finished () const
Definition at line 246 of file Sequencer.cpp.
References infra::BoundedVector< T >::empty(), and execute.
Referenced by services::CyclicStore::Add(), services::CyclicStore::Clear(), Continue(), PopContext(), services::CyclicStore::Iterator::Read(), and services::CyclicStore::Recover().
     {
         return execute.empty();
     }
ForEach()
void infra::Sequencer::ForEach (uint32_t & variable, uint32_t from, uint32_t to)
Definition at line 145 of file Sequencer.cpp.
References ExecuteWithoutContext(), and PushContext().
Referenced by services::CyclicStore::Recover().
     {
         struct State
         {
             State(uint32_t& variable, uint32_t from, uint32_t to)
                 : variable(variable), from(from), to(to)
             {}
             uint32_t& variable;
             uint32_t from;
             uint32_t to;
         };
         State state(variable_, from_, to_);
         ExecuteWithoutContext([this, &state]()
         {
             state.variable = state.from;
         });
         ExecuteWithoutContext([this, &state]()
         {
             if (state.variable == state.to)
             {
                 ExecuteNextStep();
                 ExecuteNextStep();  // Immediately continue with the step after EndForEach
             }
         });
         PushContext();
     }
If()
void infra::Sequencer::If (const infra::Function< bool()> & condition)
Definition at line 54 of file Sequencer.cpp.
References ExecuteNextStep(), ExecuteWithoutContext(), and PushContext().
Referenced by services::CyclicStore::Add(), application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), services::CyclicStore::Recover(), services::CyclicStore::RecoverEndAddress(), While(), services::CyclicStore::WriteRange(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         ExecuteWithoutContext([this, condition]()
         {
             if (!condition())
             {
                 ExecuteNextStep();
                 ExecuteNextStep();  // Immediately continue with the step after EndIf, Else, or EndWhile
             }
         });
         PushContext();
     }
IncreaseCurrentStep()
void infra::Sequencer::IncreaseCurrentStep () private
Definition at line 202 of file Sequencer.cpp.
References infra::BoundedVector< T >::back(), and examine.
Referenced by Execute(), ExecuteWithoutContext(), PopContext(), and Step().
     {
         ++examine.back();
     }
Load()
void infra::Sequencer::Load (const Function & newSequence)
Definition at line 5 of file Sequencer.cpp.
References infra::BoundedVector< T >::clear(), Continue(), execute, and sequence.
Referenced by services::CyclicStore::Add(), services::CyclicStore::Clear(), application::DeployPackToExternal::DeployPackToExternal(), services::FlashQuadSpi::EraseSectors(), services::FlashSpi::EraseSectors(), services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll(), services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Recover(), services::FlashSpi::WriteBuffer(), and services::FlashQuadSpi::WriteBufferSequence().
     {
         sequence = newSequence;
         execute.clear();
         Continue();
     }
PopContext()
void infra::Sequencer::PopContext () private
Definition at line 231 of file Sequencer.cpp.
References infra::BoundedVector< T >::empty(), examine, execute, ExecuteCurrentStep(), ExecuteNextStep(), Finished(), IncreaseCurrentStep(), and infra::BoundedVector< T >::pop_back().
Referenced by Continue(), Else(), ElseIf(), EndDoWhile(), EndForEach(), EndIf(), EndWhile(), and Execute().
     {
         if (ExecuteCurrentStep())
         {
             execute.pop_back();
             if (!Finished())
                 ExecuteNextStep();
         }
         examine.pop_back();
         if (!examine.empty())
             IncreaseCurrentStep();
     }
PushContext()
void infra::Sequencer::PushContext () private
Definition at line 223 of file Sequencer.cpp.
References examine, execute, ExecuteCurrentStep(), and infra::BoundedVector< T >::push_back().
Referenced by Continue(), DoWhile(), Else(), ElseIf(), Execute(), ForEach(), and If().
     {
         if (ExecuteCurrentStep())
             execute.push_back(0);
         examine.push_back(0);
     }
Step()
void infra::Sequencer::Step (const Function & action)
Definition at line 30 of file Sequencer.cpp.
References ExecuteCurrentStep(), and IncreaseCurrentStep().
Referenced by services::CyclicStore::Clear(), application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::EraseSectorIfAtStart(), services::FlashQuadSpi::EraseSectors(), services::FlashSpi::EraseSectors(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::FlashQuadSpiCypressFll::FlashQuadSpiCypressFll(), services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q(), services::FlashSpi::HoldWhileWriteInProgress(), services::CyclicStore::Iterator::Read(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), services::CyclicStore::Recover(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::RecoverSector(), services::FlashSpi::WriteBuffer(), services::FlashQuadSpi::WriteBufferSequence(), services::CyclicStore::WriteRange(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         if (ExecuteCurrentStep())
             action();
         IncreaseCurrentStep();
     }
While()
void infra::Sequencer::While (const infra::Function< bool()> & condition)
Definition at line 106 of file Sequencer.cpp.
References If().
Referenced by application::DeployPackToExternal::DeployPackToExternal(), services::FlashQuadSpi::EraseSectors(), services::FlashSpi::EraseSectors(), services::FlashSpi::HoldWhileWriteInProgress(), services::CyclicStore::Iterator::Read(), services::CyclicStore::RecoverEndAddress(), services::FlashSpi::WriteBuffer(), and services::FlashQuadSpi::WriteBufferSequence().
     {
         If(condition);
     }
Member Data Documentation
examine
infra::BoundedVector<uint8_t>::WithMaxSize<8> infra::Sequencer::examine private
Definition at line 52 of file Sequencer.hpp.
Referenced by Continue(), Execute(), ExecuteCurrentStep(), IncreaseCurrentStep(), PopContext(), and PushContext().
execute
infra::BoundedVector<uint8_t>::WithMaxSize<8> infra::Sequencer::execute private
Definition at line 51 of file Sequencer.hpp.
Referenced by Execute(), ExecuteCurrentStep(), ExecuteNextStep(), ExecutePreviousStep(), Finished(), Load(), PopContext(), and PushContext().
repeat
bool infra::Sequencer::repeat = false private
Definition at line 53 of file Sequencer.hpp.
Referenced by Continue(), and ExecutePreviousStep().
sequence
Function infra::Sequencer::sequence private
Definition at line 49 of file Sequencer.hpp.
Referenced by Continue(), and Load().
The documentation for this class was generated from the following files:
Sequencer.hpp
Sequencer.cpp