EMil: services::SntpClient Class Reference
services::SntpClient Class Reference
#include <SntpClient.hpp>
Classes
struct NtpMessage
struct NtpTimestamp
Public Member Functions
SntpClient (services::DatagramFactory &factory, services::TimeWithLocalization &timeWithLocalization)
~SntpClient ()=default
void RequestTime (services::IPv4Address &address)
virtual void DataReceived (infra::StreamReaderWithRewinding &reader, services::UdpSocket from) override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
Public Member Functions inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Member Functions inherited from infra::Subject< SntpResultObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Private Types
enum NtpLeapIndicator : uint8_t { NtpLeapIndicator::noWarning, NtpLeapIndicator::lastMinuteHas61Seconds, NtpLeapIndicator::lastMinuteHas59Seconds, NtpLeapIndicator::alarmConditionClockNotSynchronized }
enum NtpMode : uint8_t {
NtpMode::reserved, NtpMode::symmetricActive, NtpMode::symmetricPassive, NtpMode::client,
NtpMode::server, NtpMode::broadcast
}
using NtpHeader = uint8_t
Private Member Functions
void NotifyTimeUnavailable ()
void NotifyKissOfDeath (NtpMessage &message)
void NotifyOffsetAndDelay (NtpMessage &message)
Static Private Member Functions
static NtpHeader CreateNtpHeader (NtpLeapIndicator leapIndicator, uint8_t versionNumber, NtpMode mode)
static SntpClient::NtpTimestamp Convert (infra::Duration time)
Private Attributes
services::DatagramFactory & factory
services::TimeWithLocalization & timeWithLocalization
infra::SharedPtr< services::DatagramExchange > datagramExchange
infra::Duration originRequestTime {}
Additional Inherited Members
Public Types inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
using SubjectType = DatagramExchange
using SingleHelper = DatagramExchange
Protected Member Functions inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Protected Member Functions inherited from infra::Subject< SntpResultObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< SntpResultObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< SntpResultObserver, ObserverSubjectType > *observer)
Detailed Description
Definition at line 33 of file SntpClient.hpp.
Member Typedef Documentation
NtpHeader
using services::SntpClient::NtpHeader = uint8_t private
Definition at line 66 of file SntpClient.hpp.
Member Enumeration Documentation
NtpLeapIndicator
enum services::SntpClient::NtpLeapIndicator : uint8_t strong private
Enumerator
noWarning
lastMinuteHas61Seconds
lastMinuteHas59Seconds
alarmConditionClockNotSynchronized
Definition at line 48 of file SntpClient.hpp.
                                     : uint8_t
         {
             noWarning,
             lastMinuteHas61Seconds,
             lastMinuteHas59Seconds,
             alarmConditionClockNotSynchronized
         };
NtpMode
enum services::SntpClient::NtpMode : uint8_t strong private
Enumerator
reserved
symmetricActive
symmetricPassive
client
server
broadcast
Definition at line 56 of file SntpClient.hpp.
                            : uint8_t
         {
             reserved,
             symmetricActive,
             symmetricPassive,
             client,
             server,
             broadcast
         };
Constructor & Destructor Documentation
SntpClient()
services::SntpClient::SntpClient (services::DatagramFactory & factory, services::TimeWithLocalization & timeWithLocalization)
Definition at line 62 of file SntpClient.cpp.
         : factory(factory)
         , timeWithLocalization(timeWithLocalization)
     {}
~SntpClient()
services::SntpClient::~SntpClient () default
Member Function Documentation
Convert()
SntpClient::NtpTimestamp services::SntpClient::Convert (infra::Duration time) static private
Definition at line 154 of file SntpClient.cpp.
References services::SntpClient::NtpTimestamp::fraction, and services::SntpClient::NtpTimestamp::seconds.
Referenced by SendStreamAvailable().
     {
         NtpTimestamp ntpTime = { 0 };
         ntpTime.seconds = static_cast<uint32_t>(std::chrono::duration_cast<std::chrono::seconds>(time + ntpEpochOffset).count());
         ntpTime.fraction = static_cast<uint32_t>(std::chrono::duration_cast<std::chrono::microseconds>(time).count() * ntpFractionFactor);
         return ntpTime;
     }
CreateNtpHeader()
SntpClient::NtpHeader services::SntpClient::CreateNtpHeader (NtpLeapIndicator leapIndicator, uint8_t versionNumber, NtpMode mode) static private
Definition at line 141 of file SntpClient.cpp.
References enum_cast().
Referenced by SendStreamAvailable().
     {
         uint8_t result = 0;
         really_assert(versionNumber == 3 || versionNumber == 4);
         result |= enum_cast(leapIndicator) << 6;
         result |= versionNumber << 3;
         result |= enum_cast(mode);
         return result;
     }
DataReceived()
void services::SntpClient::DataReceived (infra::StreamReaderWithRewinding & reader, services::UdpSocket from) override virtual
Implements services::DatagramExchangeObserver.
Definition at line 73 of file SntpClient.cpp.
References infra::StreamReader::Empty(), infra::InputStream::Failed(), NotifyKissOfDeath(), NotifyOffsetAndDelay(), NotifyTimeUnavailable(), originRequestTime, and infra::softFail.
     {
         if (reader.Empty())
         {
             NotifyTimeUnavailable();
             return;
         }
         infra::DataInputStream::WithErrorPolicy stream(reader, infra::softFail);
         NtpMessage message{ 0 };
         stream >> message;
         if (!stream.Failed() && message.Valid(originRequestTime))
         {
             if (message.stratum == 0)
                 NotifyKissOfDeath(message);
             else
                 NotifyOffsetAndDelay(message);
         }
         else
             NotifyTimeUnavailable();
     }
NotifyKissOfDeath()
void services::SntpClient::NotifyKissOfDeath (NtpMessage & message) private
Definition at line 113 of file SntpClient.cpp.
References infra::ByteRangeAsString(), services::SntpResultObserver::deny, infra::MakeByteRange(), infra::Subject< SntpResultObserver >::NotifyObservers(), NotifyTimeUnavailable(), infra::Subject< SntpResultObserver >::observer, services::SntpResultObserver::rateExceeded, services::SntpClient::NtpMessage::referenceIdentifier, and services::SntpResultObserver::restrict.
Referenced by DataReceived().
     {
         auto kissCode = infra::ByteRangeAsString(infra::MakeByteRange(message.referenceIdentifier));
         if (kissCode == "DENY")
             NotifyObservers([](SntpResultObserver& observer) { observer.KissOfDeath(SntpResultObserver::KissCode::deny); });
         else if (kissCode == "RSTR")
             NotifyObservers([](SntpResultObserver& observer) { observer.KissOfDeath(SntpResultObserver::KissCode::restrict); });
         else if (kissCode == "RATE")
             NotifyObservers([](SntpResultObserver& observer) { observer.KissOfDeath(SntpResultObserver::KissCode::rateExceeded); });
         else
             NotifyTimeUnavailable();
     }
NotifyOffsetAndDelay()
void services::SntpClient::NotifyOffsetAndDelay (NtpMessage & message) private
Definition at line 127 of file SntpClient.cpp.
References services::SntpClient::NtpTimestamp::Convert(), infra::Subject< SntpResultObserver >::NotifyObservers(), infra::DerivedTimerService::Now(), infra::Subject< SntpResultObserver >::observer, services::SntpClient::NtpMessage::originate, services::SntpClient::NtpMessage::receive, timeWithLocalization, services::SntpClient::NtpMessage::transmit, and services::TimeWithLocalization::Utc().
Referenced by DataReceived().
     {
         // 'Algorithm' according to section 5 of RFC5905
         auto t1 = message.originate.Convert();
         auto t2 = message.receive.Convert();
         auto t3 = message.transmit.Convert();
         auto t4 = timeWithLocalization.Utc().Now().time_since_epoch();
         auto roundTripDelay = (t4 - t1) - (t3 - t2);
         auto localClockOffset = ((t2 - t1) + (t3 - t4)) / 2;
         NotifyObservers([roundTripDelay, localClockOffset](SntpResultObserver& observer) { observer.TimeAvailable(roundTripDelay, localClockOffset); });
     }
NotifyTimeUnavailable()
void services::SntpClient::NotifyTimeUnavailable () private
Definition at line 108 of file SntpClient.cpp.
References infra::Subject< SntpResultObserver >::NotifyObservers(), and infra::Subject< SntpResultObserver >::observer.
Referenced by DataReceived(), and NotifyKissOfDeath().
     {
         NotifyObservers([](SntpResultObserver& observer) { observer.TimeUnavailable(); });
     }
RequestTime()
void services::SntpClient::RequestTime (services::IPv4Address & address)
Definition at line 67 of file SntpClient.cpp.
References services::DatagramFactory::Connect(), datagramExchange, factory, and services::DatagramExchange::RequestSendStream().
     {
         datagramExchange = factory.Connect(*this, Udpv4Socket{ address, ntpPort });
         datagramExchange->RequestSendStream(sizeof(NtpMessage));
     }
SendStreamAvailable()
void services::SntpClient::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::DatagramExchangeObserver.
Definition at line 96 of file SntpClient.cpp.
References client, Convert(), CreateNtpHeader(), infra::DerivedTimerService::Now(), noWarning, originRequestTime, timeWithLocalization, and services::TimeWithLocalization::Utc().
     {
         infra::DataOutputStream::WithErrorPolicy stream(*writer);
         NtpMessage message{ 0 };
         originRequestTime = timeWithLocalization.Utc().Now().time_since_epoch();
         message.header = CreateNtpHeader(NtpLeapIndicator::noWarning, ntpRequestVersion, NtpMode::client);
         message.transmit = Convert(originRequestTime);
         stream << message;
     }
Member Data Documentation
datagramExchange
infra::SharedPtr<services::DatagramExchange> services::SntpClient::datagramExchange private
Definition at line 107 of file SntpClient.hpp.
Referenced by RequestTime().
factory
services::DatagramFactory& services::SntpClient::factory private
Definition at line 105 of file SntpClient.hpp.
Referenced by RequestTime().
originRequestTime
infra::Duration services::SntpClient::originRequestTime {} private
Definition at line 108 of file SntpClient.hpp.
Referenced by DataReceived(), and SendStreamAvailable().
timeWithLocalization
services::TimeWithLocalization& services::SntpClient::timeWithLocalization private
Definition at line 106 of file SntpClient.hpp.
Referenced by NotifyOffsetAndDelay(), and SendStreamAvailable().
The documentation for this class was generated from the following files:
SntpClient.hpp
SntpClient.cpp