EMil: application::DecryptorAesMbedTls Class Reference
application::DecryptorAesMbedTls Class Reference
#include <DecryptorAesMbedTls.hpp>
Public Member Functions
DecryptorAesMbedTls (infra::ConstByteRange key)
virtual infra::ByteRange StateBuffer () override
virtual void Reset () override
virtual void DecryptPart (infra::ByteRange data) override
virtual bool DecryptAndAuthenticate (infra::ByteRange data) override
Static Public Attributes
static const std::size_t blockLength = 16
Private Attributes
mbedtls_aes_context ctx
size_t currentStreamBlockOffset = 0
std::array< uint8_t, blockLength > currentStreamBlock
std::array< uint8_t, blockLength > counter
Additional Inherited Members
Protected Member Functions inherited from application::Decryptor
~Decryptor ()=default
Detailed Description
Definition at line 9 of file DecryptorAesMbedTls.hpp.
Constructor & Destructor Documentation
DecryptorAesMbedTls()
application::DecryptorAesMbedTls::DecryptorAesMbedTls (infra::ConstByteRange key) explicit
Definition at line 5 of file DecryptorAesMbedTls.cpp.
References infra::MemoryRange< T >::begin(), ctx, and infra::MemoryRange< T >::size().
         : currentStreamBlock()
         , counter()
     {
         mbedtls_aes_init(&ctx);
         mbedtls_aes_setkey_enc(&ctx, key.begin(), key.size() * 8);
     }
Member Function Documentation
DecryptAndAuthenticate()
bool application::DecryptorAesMbedTls::DecryptAndAuthenticate (infra::ByteRange data) override virtual
Implements application::Decryptor.
Definition at line 28 of file DecryptorAesMbedTls.cpp.
References infra::data, and DecryptPart().
     {
         DecryptPart(data);
         return true;
     }
DecryptPart()
void application::DecryptorAesMbedTls::DecryptPart (infra::ByteRange data) override virtual
Implements application::Decryptor.
Definition at line 23 of file DecryptorAesMbedTls.cpp.
References counter, ctx, currentStreamBlock, currentStreamBlockOffset, and infra::data.
Referenced by DecryptAndAuthenticate().
     {
         mbedtls_aes_crypt_ctr(&ctx, data.size(), &currentStreamBlockOffset, counter.data(), currentStreamBlock.data(), data.begin(), data.begin());     //TICS !INT#030
     }
Reset()
void application::DecryptorAesMbedTls::Reset () override virtual
Implements application::Decryptor.
Definition at line 18 of file DecryptorAesMbedTls.cpp.
References currentStreamBlockOffset.
     {
         currentStreamBlockOffset = 0;
     }
StateBuffer()
infra::ByteRange application::DecryptorAesMbedTls::StateBuffer () override virtual
Implements application::Decryptor.
Definition at line 13 of file DecryptorAesMbedTls.cpp.
References counter, and infra::MakeByteRange().
     {
         return infra::MakeByteRange(counter);
     }
Member Data Documentation
blockLength
const std::size_t application::DecryptorAesMbedTls::blockLength = 16 static
Definition at line 13 of file DecryptorAesMbedTls.hpp.
counter
std::array<uint8_t, blockLength> application::DecryptorAesMbedTls::counter private
Definition at line 26 of file DecryptorAesMbedTls.hpp.
Referenced by DecryptPart(), and StateBuffer().
ctx
mbedtls_aes_context application::DecryptorAesMbedTls::ctx private
Definition at line 23 of file DecryptorAesMbedTls.hpp.
Referenced by DecryptorAesMbedTls(), and DecryptPart().
currentStreamBlock
std::array<uint8_t, blockLength> application::DecryptorAesMbedTls::currentStreamBlock private
Definition at line 25 of file DecryptorAesMbedTls.hpp.
Referenced by DecryptPart().
currentStreamBlockOffset
size_t application::DecryptorAesMbedTls::currentStreamBlockOffset = 0 private
Definition at line 24 of file DecryptorAesMbedTls.hpp.
Referenced by DecryptPart(), and Reset().
The documentation for this class was generated from the following files:
DecryptorAesMbedTls.hpp
DecryptorAesMbedTls.cpp