EMil: TestVariant.cpp File Reference
TestVariant.cpp File Reference
Classes
struct DoubleVisitor
struct EmptyVisitor
struct A
struct B
struct C
struct D
struct E
struct F
Functions
TEST (VariantTest, TestEmptyConstruction)
TEST (VariantTest, TestConstructionWithBool)
TEST (VariantTest, TestConstructionWithVariant)
TEST (VariantTest, TestConstructionWithNarrowVariant)
TEST (VariantTest, TestConstructionAtIndex)
TEST (VariantTest, TestGetBool)
TEST (VariantTest, TestAssignment)
TEST (VariantTest, TestInPlaceConstruction)
TEST (VariantTest, TestEmplace)
TEST (VariantTest, TestAssignmentFromVariant)
TEST (VariantTest, TestSelfAssignment)
TEST (VariantTest, TestAssignmentFromNarrowVariant)
TEST (VariantTest, TestVariantWithTwoTypes)
TEST (VariantTest, TestVisitor)
TEST (VariantTest, TestReturningVisitor)
TEST (VariantTest, TestEqual)
TEST (VariantTest, TestLessThan)
TEST (VariantTest, TestEqualValue)
TEST (VariantTest, TestLessThanValue)
TEST (VariantTest, TestDoubleVisitor)
TEST (VariantTest, TestRecursiveLoopUnrolling3_1)
TEST (VariantTest, TestRecursiveLoopUnrolling3_2)
TEST (VariantTest, TestRecursiveLoopUnrolling3_3)
TEST (VariantTest, TestRecursiveLoopUnrolling4_1)
TEST (VariantTest, TestRecursiveLoopUnrolling4_2)
TEST (VariantTest, TestRecursiveLoopUnrolling4_3)
TEST (VariantTest, TestRecursiveLoopUnrolling4_4)
TEST (VariantTest, TestRecursiveLoopUnrolling5_1)
TEST (VariantTest, TestRecursiveLoopUnrolling5_2)
TEST (VariantTest, TestRecursiveLoopUnrolling5_3)
TEST (VariantTest, TestRecursiveLoopUnrolling5_4)
TEST (VariantTest, TestRecursiveLoopUnrolling5_5)
TEST (VariantTest, TestRecursiveLoopUnrollingX)
Function Documentation
TEST() [1/33]
TEST (VariantTest , TestEmptyConstruction)
Definition at line 5 of file TestVariant.cpp.
 {
     infra::Variant<bool> v;
 }
TEST() [2/33]
TEST (VariantTest , TestConstructionWithBool)
Definition at line 10 of file TestVariant.cpp.
 {
     bool b;
     infra::Variant<bool> v(b);
 }
TEST() [3/33]
TEST (VariantTest , TestConstructionWithVariant)
Definition at line 16 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     infra::Variant<bool, int> i(5);
     infra::Variant<bool, int> v(i);
     EXPECT_EQ(5, v.Get<int>());
 }
TEST() [4/33]
TEST (VariantTest , TestConstructionWithNarrowVariant)
Definition at line 23 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     infra::Variant<int> i(5);
     infra::Variant<bool, int> v(i);
     EXPECT_EQ(5, v.Get<int>());
 }
TEST() [5/33]
TEST (VariantTest , TestConstructionAtIndex)
Definition at line 30 of file TestVariant.cpp.
References infra::atIndex, EXPECT_EQ(), infra::Variant< T >::Get(), and infra::Variant< T >::Which().
 {
     infra::Variant<uint8_t, uint16_t> v(infra::atIndex, 1, 3);
     EXPECT_EQ(1, v.Which());
     EXPECT_EQ(3, v.Get<uint16_t>());
 }
TEST() [6/33]
TEST (VariantTest , TestGetBool)
Definition at line 37 of file TestVariant.cpp.
References EXPECT_TRUE(), and infra::Variant< T >::Get().
 {
     bool b = true;
     infra::Variant<bool> v(b);
     EXPECT_TRUE(v.Get<bool>());
 }
TEST() [7/33]
TEST (VariantTest , TestAssignment)
Definition at line 44 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     infra::Variant<bool, int> v(true);
     v = 5;
     EXPECT_EQ(5, v.Get<int>());
 }
TEST() [8/33]
TEST (VariantTest , TestInPlaceConstruction)
Definition at line 51 of file TestVariant.cpp.
References EXPECT_EQ(), infra::Variant< T >::Get(), and infra::Variant< T >::Which().
 {
     struct MyStruct
     {
         MyStruct(int aX, int aY): x(aX), y(aY) {};
         int x;
         int y;
     };
     infra::Variant<MyStruct> v(infra::InPlaceType<MyStruct>(), 2, 3);
     EXPECT_EQ(0, v.Which());
     EXPECT_EQ(2, v.Get<MyStruct>().x);
     EXPECT_EQ(3, v.Get<MyStruct>().y);
 }
TEST() [9/33]
TEST (VariantTest , TestEmplace)
Definition at line 67 of file TestVariant.cpp.
References infra::Variant< T >::Emplace(), EXPECT_EQ(), infra::Variant< T >::Get(), operator==(), and infra::Variant< T >::Which().
 {
     struct MyStruct
     {
         MyStruct(int aX, int aY): x(aX), y(aY) {};
         bool operator==(const MyStruct& other) const
         {
             return x == other.x && y == other.y;
         }
         int x;
         int y;
     };
     infra::Variant<bool, MyStruct> v(true);
     EXPECT_EQ(MyStruct(2, 3), v.Emplace<MyStruct>(2, 3));
     EXPECT_EQ(1, v.Which());
     EXPECT_EQ(2, v.Get<MyStruct>().x);
     EXPECT_EQ(3, v.Get<MyStruct>().y);
 }
TEST() [10/33]
TEST (VariantTest , TestAssignmentFromVariant)
Definition at line 89 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     infra::Variant<bool, int> v(true);
     v = infra::Variant<bool, int>(5);
     EXPECT_EQ(5, v.Get<int>());
 }
TEST() [11/33]
TEST (VariantTest , TestSelfAssignment)
Definition at line 96 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     infra::Variant<bool, int> v(true);
     v = v;
     EXPECT_EQ(true, v.Get<bool>());
 }
TEST() [12/33]
TEST (VariantTest , TestAssignmentFromNarrowVariant)
Definition at line 103 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     infra::Variant<bool, int> v(true);
     v = infra::Variant<int>(5);
     EXPECT_EQ(5, v.Get<int>());
 }
TEST() [13/33]
TEST (VariantTest , TestVariantWithTwoTypes)
Definition at line 110 of file TestVariant.cpp.
References EXPECT_EQ(), and infra::Variant< T >::Get().
 {
     int i = 5;
     infra::Variant<bool, int> v(i);
     EXPECT_EQ(5, v.Get<int>());
 }
TEST() [14/33]
TEST (VariantTest , TestVisitor)
Definition at line 117 of file TestVariant.cpp.
References infra::ApplyVisitor(), and EXPECT_EQ().
 {
     struct Visitor
         : infra::StaticVisitor<void>
     {
         Visitor()
             : passed(0)
         {}
         void operator()(bool b)
         {}
         void operator()(int i)
         {
             ++passed;
         }
         int passed;
     };
     int i = 5;
     infra::Variant<bool, int> variant(i);
     Visitor visitor;
     infra::ApplyVisitor(visitor, variant);
     EXPECT_EQ(1, visitor.passed);
 }
TEST() [15/33]
TEST (VariantTest , TestReturningVisitor)
Definition at line 144 of file TestVariant.cpp.
References infra::ApplyVisitor(), and EXPECT_EQ().
 {
     struct Visitor
         : infra::StaticVisitor<bool>
     {
         bool operator()(bool b)
         {
             return false;
         }
         bool operator()(int i)
         {
             return true;
         }
     };
     int i = 5;
     infra::Variant<bool, int> variant(i);
     Visitor visitor;
     EXPECT_EQ(true, infra::ApplyVisitor(visitor, variant));
 }
TEST() [16/33]
TEST (VariantTest , TestEqual)
Definition at line 166 of file TestVariant.cpp.
References EXPECT_EQ().
 {
     int i = 1;
     int j = 2;
     bool k = true;
     const infra::Variant<bool, int> v1(i);
     const infra::Variant<bool, int> v2(i);
     const infra::Variant<bool, int> v3(j);
     const infra::Variant<bool, int> v4(k);
     EXPECT_EQ(v1, v2);
     EXPECT_NE(v1, v3);
     EXPECT_NE(v1, v4);
 }
TEST() [17/33]
TEST (VariantTest , TestLessThan)
Definition at line 181 of file TestVariant.cpp.
 {
     int i = 1;
     int j = 2;
     bool k = true;
     const infra::Variant<bool, int> v1(i);
     const infra::Variant<bool, int> v2(i);
     const infra::Variant<bool, int> v3(j);
     const infra::Variant<bool, int> v4(k);
     EXPECT_GE(v1, v2);
     EXPECT_LE(v1, v2);
     EXPECT_LT(v1, v3);
     EXPECT_GT(v1, v4);
 }
TEST() [18/33]
TEST (VariantTest , TestEqualValue)
Definition at line 197 of file TestVariant.cpp.
References EXPECT_EQ().
 {
     int i = 1;
     int j = 2;
     bool k = true;
     const infra::Variant<bool, int> v1(i);
     EXPECT_EQ(v1, i);
     EXPECT_NE(v1, j);
     EXPECT_NE(v1, k);
 }
TEST() [19/33]
TEST (VariantTest , TestLessThanValue)
Definition at line 209 of file TestVariant.cpp.
 {
     int i = 1;
     int j = 2;
     bool k = true;
     const infra::Variant<bool, int> v1(i);
     EXPECT_GE(v1, i);
     EXPECT_LE(v1, i);
     EXPECT_LT(v1, j);
     EXPECT_GT(v1, k);
 }
TEST() [20/33]
TEST (VariantTest , TestDoubleVisitor)
Definition at line 232 of file TestVariant.cpp.
References infra::ApplyVisitor(), and EXPECT_EQ().
 {
     infra::Variant<uint32_t, int> variant1(infra::InPlaceType<int>(), 5);
     infra::Variant<uint32_t, int> variant2(infra::InPlaceType<uint32_t>(), 1u);
     DoubleVisitor visitor;
     EXPECT_EQ(2, infra::ApplyVisitor(visitor, variant2, variant2));
     EXPECT_EQ(6, infra::ApplyVisitor(visitor, variant1, variant2));
     EXPECT_EQ(10, infra::ApplyVisitor(visitor, variant1, variant1));
 }
TEST() [21/33]
TEST (VariantTest , TestRecursiveLoopUnrolling3_1)
Definition at line 265 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C> v((A()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [22/33]
TEST (VariantTest , TestRecursiveLoopUnrolling3_2)
Definition at line 274 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C> v((B()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [23/33]
TEST (VariantTest , TestRecursiveLoopUnrolling3_3)
Definition at line 283 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C> v((C()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [24/33]
TEST (VariantTest , TestRecursiveLoopUnrolling4_1)
Definition at line 292 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D> v((A()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [25/33]
TEST (VariantTest , TestRecursiveLoopUnrolling4_2)
Definition at line 301 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D> v((B()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [26/33]
TEST (VariantTest , TestRecursiveLoopUnrolling4_3)
Definition at line 310 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D> v((C()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [27/33]
TEST (VariantTest , TestRecursiveLoopUnrolling4_4)
Definition at line 319 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D> v((D()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [28/33]
TEST (VariantTest , TestRecursiveLoopUnrolling5_1)
Definition at line 328 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D, E> v((A()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [29/33]
TEST (VariantTest , TestRecursiveLoopUnrolling5_2)
Definition at line 337 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D, E> v((B()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [30/33]
TEST (VariantTest , TestRecursiveLoopUnrolling5_3)
Definition at line 346 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D, E> v((C()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [31/33]
TEST (VariantTest , TestRecursiveLoopUnrolling5_4)
Definition at line 355 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D, E> v((D()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [32/33]
TEST (VariantTest , TestRecursiveLoopUnrolling5_5)
Definition at line 364 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D, E> v((E()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }
TEST() [33/33]
TEST (VariantTest , TestRecursiveLoopUnrollingX)
Definition at line 373 of file TestVariant.cpp.
References infra::ApplySameTypeVisitor(), and infra::ApplyVisitor().
 {
     infra::Variant<A, B, C, D, E, F> v((F()));
     EmptyVisitor visitor;
     infra::ApplyVisitor(visitor, v);
     infra::ApplyVisitor(visitor, v, v);
     infra::ApplySameTypeVisitor(visitor, v, v);
 }