EMil: infra::BoundedVector< T > Class Template Reference
infra::BoundedVector< T > Class Template Reference
#include <BoundedVector.hpp>
Public Types
template<std::size_t Max>
using WithMaxSize = infra::WithStorage< BoundedVector< T >, std::array< StaticStorage< T >, Max > >
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef T * iterator
typedef const T * const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
BoundedVector (const BoundedVector &other)=delete
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage)
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, size_type n, const value_type &value=value_type())
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, infra::MemoryRange< typename std::remove_const< T >::type > initData)
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, infra::MemoryRange< const T > initData)
template<class InputIterator >
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, InputIterator first, InputIterator last)
template<class U >
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, std::initializer_list< U > initializerList)
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, const BoundedVector &other)
BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, BoundedVector &&other)
~BoundedVector ()
BoundedVector & operator= (const BoundedVector &other)
BoundedVector & operator= (BoundedVector &&other)
void AssignFromStorage (const BoundedVector &other)
void AssignFromStorage (BoundedVector &&other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
size_type size () const
size_type max_size () const
void resize (size_type n, const value_type &value=value_type())
bool empty () const
bool full () const
infra::MemoryRange< T > range ()
infra::MemoryRange< const T > range () const
value_type & operator[] (size_type position)
const value_type & operator[] (size_type position) const
value_type & front ()
const value_type & front () const
value_type & back ()
const value_type & back () const
value_type * data ()
const value_type * data () const
void assign (infra::MemoryRange< typename std::remove_const< T >::type > initData)
void assign (infra::MemoryRange< const T > initData)
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void assign (size_type n, const value_type &value)
void push_back (const value_type &value)
void push_back (value_type &&value)
void pop_back ()
iterator insert (iterator position, const value_type &value)
void insert (iterator position, size_type n, const value_type &value)
template<class InputIterator >
void insert (iterator position, InputIterator first, InputIterator last)
iterator erase (iterator position)
iterator erase (iterator first, iterator last)
void swap (BoundedVector &other)
void clear ()
template<class... Args>
iterator emplace (const_iterator position, Args &&... args)
template<class... Args>
void emplace_back (Args &&... args)
bool operator== (const BoundedVector &other) const
bool operator!= (const BoundedVector &other) const
bool operator< (const BoundedVector &other) const
bool operator<= (const BoundedVector &other) const
bool operator> (const BoundedVector &other) const
bool operator>= (const BoundedVector &other) const
template<class RandomAccessIterator >
void insert (iterator position, RandomAccessIterator first, RandomAccessIterator last)
Private Member Functions
void move_up (const_iterator position, size_type n)
Private Attributes
infra::MemoryRange< infra::StaticStorage< T > > storage
size_type numAllocated = 0
Detailed Description
template<class T>
class infra::BoundedVector< T >
Definition at line 17 of file BoundedVector.hpp.
Member Typedef Documentation
const_iterator
template<class T> typedef const T* infra::BoundedVector< T >::const_iterator
Definition at line 29 of file BoundedVector.hpp.
const_pointer
template<class T> typedef const T* infra::BoundedVector< T >::const_pointer
Definition at line 27 of file BoundedVector.hpp.
const_reference
template<class T> typedef const T& infra::BoundedVector< T >::const_reference
Definition at line 25 of file BoundedVector.hpp.
const_reverse_iterator
template<class T> typedef std::reverse_iterator<const_iterator> infra::BoundedVector< T >::const_reverse_iterator
Definition at line 31 of file BoundedVector.hpp.
difference_type
template<class T> typedef std::iterator_traits<iterator>::difference_type infra::BoundedVector< T >::difference_type
Definition at line 32 of file BoundedVector.hpp.
iterator
template<class T> typedef T* infra::BoundedVector< T >::iterator
Definition at line 28 of file BoundedVector.hpp.
pointer
template<class T> typedef T* infra::BoundedVector< T >::pointer
Definition at line 26 of file BoundedVector.hpp.
reference
template<class T> typedef T& infra::BoundedVector< T >::reference
Definition at line 24 of file BoundedVector.hpp.
reverse_iterator
template<class T> typedef std::reverse_iterator<iterator> infra::BoundedVector< T >::reverse_iterator
Definition at line 30 of file BoundedVector.hpp.
size_type
template<class T> typedef std::size_t infra::BoundedVector< T >::size_type
Definition at line 33 of file BoundedVector.hpp.
value_type
template<class T> typedef T infra::BoundedVector< T >::value_type
Definition at line 23 of file BoundedVector.hpp.
WithMaxSize
template<class T> template<std::size_t Max> using infra::BoundedVector< T >::WithMaxSize = infra::WithStorage<BoundedVector<T>, std::array<StaticStorage<T>, Max> >
Definition at line 21 of file BoundedVector.hpp.
Constructor & Destructor Documentation
BoundedVector() [1/9]
template<class T> infra::BoundedVector< T >::BoundedVector (const BoundedVector< T > & other) delete
BoundedVector() [2/9]
template<class T> infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage) explicit
Definition at line 144 of file BoundedVector.hpp.
         : storage(storage)
     {}
BoundedVector() [3/9]
template<class T> infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, size_type n, const value_type & value = value_type())
Definition at line 149 of file BoundedVector.hpp.
         : storage(storage)
     {
         resize(n, value);
     }
BoundedVector() [4/9]
template<class T> infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, infra::MemoryRange< typename std::remove_const< T >::type > initData)
Definition at line 156 of file BoundedVector.hpp.
         : storage(storage)
     {
         assign(initData);
     }
BoundedVector() [5/9]
template<class T> infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, infra::MemoryRange< const T > initData)
Definition at line 163 of file BoundedVector.hpp.
         : storage(storage)
     {
         assign(initData);
     }
BoundedVector() [6/9]
template<class T> template<class InputIterator > infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, InputIterator first, InputIterator last)
Definition at line 171 of file BoundedVector.hpp.
         : storage(storage)
     {
         assign(first, last);
     }
BoundedVector() [7/9]
template<class T> template<class U > infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, std::initializer_list< U > initializerList)
Definition at line 179 of file BoundedVector.hpp.
         : storage(storage)
     {
         assign(initializerList.begin(), initializerList.end());
     }
BoundedVector() [8/9]
template<class T> infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, const BoundedVector< T > & other)
Definition at line 186 of file BoundedVector.hpp.
         : storage(storage)
     {
         assign(other.begin(), other.end());
     }
BoundedVector() [9/9]
template<class T> infra::BoundedVector< T >::BoundedVector (infra::MemoryRange< infra::StaticStorage< T >> storage, BoundedVector< T > && other)
Definition at line 193 of file BoundedVector.hpp.
         : storage(storage)
         , numAllocated(other.numAllocated)
     {
         for (size_type i = 0; i != size(); ++i)
             storage[i].Construct(std::move(other[i]));
     }
~BoundedVector()
template<class T > infra::BoundedVector< T >::~BoundedVector ()
Definition at line 236 of file BoundedVector.hpp.
     {
         clear();
     }
Member Function Documentation
assign() [1/4]
template<class T> void infra::BoundedVector< T >::assign (infra::MemoryRange< typename std::remove_const< T >::type > initData)
Definition at line 415 of file BoundedVector.hpp.
     {
         assign(initData.begin(), initData.end());
     }
assign() [2/4]
template<class T> void infra::BoundedVector< T >::assign (infra::MemoryRange< const T > initData)
Definition at line 421 of file BoundedVector.hpp.
     {
         assign(initData.begin(), initData.end());
     }
assign() [3/4]
template<class T > template<class InputIterator > void infra::BoundedVector< T >::assign (InputIterator first, InputIterator last)
Definition at line 428 of file BoundedVector.hpp.
     {
         clear();
         while (first != last)
         {
             emplace_back(*first);
             ++first;
         }
     }
assign() [4/4]
template<class T> void infra::BoundedVector< T >::assign (size_type n, const value_type & value)
Definition at line 440 of file BoundedVector.hpp.
     {
         clear();
         for (size_type i = 0; i != n; ++i)
             emplace_back(value);
     }
AssignFromStorage() [1/2]
template<class T > void infra::BoundedVector< T >::AssignFromStorage (const BoundedVector< T > & other)
Definition at line 224 of file BoundedVector.hpp.
     {
         *this = other;
     }
AssignFromStorage() [2/2]
template<class T > void infra::BoundedVector< T >::AssignFromStorage (BoundedVector< T > && other)
Definition at line 230 of file BoundedVector.hpp.
     {
         *this = std::move(other);
     }
back() [1/2]
template<class T > BoundedVector< T >::value_type & infra::BoundedVector< T >::back ()
Definition at line 389 of file BoundedVector.hpp.
Referenced by infra::Sequencer::ExecuteNextStep(), infra::Sequencer::ExecutePreviousStep(), infra::Sequencer::IncreaseCurrentStep(), and hal::QuadSpi::VectorToAddress().
     {
         really_assert(!empty());
         return *storage[size() - 1];
     }
back() [2/2]
template<class T > const BoundedVector< T >::value_type & infra::BoundedVector< T >::back () const
Definition at line 396 of file BoundedVector.hpp.
     {
         really_assert(!empty());
         return *storage[size() - 1];
     }
begin() [1/2]
template<class T > BoundedVector< T >::iterator infra::BoundedVector< T >::begin ()
Definition at line 242 of file BoundedVector.hpp.
Referenced by infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::BoundedVector(), infra::MakeRange(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator<(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator=(), and infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator==().
     {
         return &*storage[0];
     }
begin() [2/2]
template<class T > BoundedVector< T >::const_iterator infra::BoundedVector< T >::begin () const
Definition at line 248 of file BoundedVector.hpp.
     {
         return &*storage[0];
     }
cbegin()
template<class T > BoundedVector< T >::const_iterator infra::BoundedVector< T >::cbegin () const
Definition at line 291 of file BoundedVector.hpp.
     {
         return begin();
     }
cend()
template<class T > BoundedVector< T >::const_iterator infra::BoundedVector< T >::cend () const
Definition at line 297 of file BoundedVector.hpp.
     {
         return end();
     }
clear()
template<class T > void infra::BoundedVector< T >::clear ()
Definition at line 566 of file BoundedVector.hpp.
Referenced by infra::Sequencer::Continue(), and infra::Sequencer::Load().
     {
         while (!empty())
             pop_back();
     }
crbegin()
template<class T > BoundedVector< T >::const_reverse_iterator infra::BoundedVector< T >::crbegin () const
Definition at line 303 of file BoundedVector.hpp.
     {
         return rbegin();
     }
crend()
template<class T > BoundedVector< T >::const_reverse_iterator infra::BoundedVector< T >::crend () const
Definition at line 309 of file BoundedVector.hpp.
     {
         return rend();
     }
data() [1/2]
template<class T > BoundedVector< T >::value_type * infra::BoundedVector< T >::data ()
Definition at line 403 of file BoundedVector.hpp.
Referenced by services::DatagramWin::Send(), and services::DatagramBsd::Send().
     {
         return begin();
     }
data() [2/2]
template<class T > const BoundedVector< T >::value_type * infra::BoundedVector< T >::data () const
Definition at line 409 of file BoundedVector.hpp.
     {
         return begin();
     }
emplace()
template<class T > template<class... Args> BoundedVector< T >::iterator infra::BoundedVector< T >::emplace (const_iterator position, Args &&... args)
Definition at line 574 of file BoundedVector.hpp.
     {
         really_assert(size() != max_size());
         move_up(position, 1);
         storage[position - begin()].Construct(std::forward<Args>(args)...);
         return begin() + (position - begin());
     }
emplace_back()
template<class T > template<class... Args> void infra::BoundedVector< T >::emplace_back (Args &&... args)
Definition at line 584 of file BoundedVector.hpp.
     {
         really_assert(size() != max_size());
         storage[numAllocated].Construct(std::forward<Args>(args)...);
         ++numAllocated;
     }
empty()
template<class T > bool infra::BoundedVector< T >::empty () const
Definition at line 337 of file BoundedVector.hpp.
Referenced by infra::Sequencer::Finished(), infra::Sequencer::PopContext(), and hal::QuadSpi::VectorToAddress().
     {
         return numAllocated == 0;
     }
end() [1/2]
template<class T > BoundedVector< T >::iterator infra::BoundedVector< T >::end ()
Definition at line 254 of file BoundedVector.hpp.
Referenced by infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::BoundedVector(), infra::MakeRange(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator<(), and infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator=().
     {
         return begin() + size();
     }
end() [2/2]
template<class T > BoundedVector< T >::const_iterator infra::BoundedVector< T >::end () const
Definition at line 260 of file BoundedVector.hpp.
     {
         return begin() + size();
     }
erase() [1/2]
template<class T > BoundedVector< T >::iterator infra::BoundedVector< T >::erase (iterator position)
Definition at line 510 of file BoundedVector.hpp.
     {
         erase(position, position + 1);
         return position;
     }
erase() [2/2]
template<class T > BoundedVector< T >::iterator infra::BoundedVector< T >::erase (iterator first, iterator last)
Definition at line 517 of file BoundedVector.hpp.
     {
         iterator result = first;
         while (last != end())
         {
             *first = std::move(*last);
             ++first;
             ++last;
         }
         while (first != last)
         {
             storage[first - begin()].Destruct();
             ++first;
             --numAllocated;
         }
         return result;
     }
front() [1/2]
template<class T > BoundedVector< T >::value_type & infra::BoundedVector< T >::front ()
Definition at line 375 of file BoundedVector.hpp.
     {
         really_assert(!empty());
         return *storage[0];
     }
front() [2/2]
template<class T > const BoundedVector< T >::value_type & infra::BoundedVector< T >::front () const
Definition at line 382 of file BoundedVector.hpp.
     {
         really_assert(!empty());
         return *storage[0];
     }
full()
template<class T > bool infra::BoundedVector< T >::full () const
Definition at line 343 of file BoundedVector.hpp.
Referenced by services::DnsResolver::ReplyParser::ReadAdditionalRecords().
     {
         return numAllocated == max_size();
     }
insert() [1/4]
template<class T > BoundedVector< T >::iterator infra::BoundedVector< T >::insert (iterator position, const value_type & value)
Definition at line 473 of file BoundedVector.hpp.
     {
         insert(position, size_type(1), value);
         return position;
     }
insert() [2/4]
template<class T > void infra::BoundedVector< T >::insert (iterator position, size_type n, const value_type & value)
Definition at line 480 of file BoundedVector.hpp.
     {
         really_assert(size() + n <= max_size());
         move_up(position, n);
         for (size_type i = 0; i != n; ++i)
         {
             *position = value;
             ++position;
         }
     }
insert() [3/4]
template<class T> template<class InputIterator > void infra::BoundedVector< T >::insert (iterator position, InputIterator first, InputIterator last)
insert() [4/4]
template<class T> template<class RandomAccessIterator > void infra::BoundedVector< T >::insert (iterator position, RandomAccessIterator first, RandomAccessIterator last)
Definition at line 494 of file BoundedVector.hpp.
     {
         size_type n = last - first;
         really_assert(size() + n <= max_size());
         move_up(position, n);
         while (first != last)
         {
             *position = *first;
             ++position;
             ++first;
         }
     }
max_size()
template<class T > BoundedVector< T >::size_type infra::BoundedVector< T >::max_size () const
Definition at line 321 of file BoundedVector.hpp.
Referenced by infra::ProtoLengthDelimited::GetBytes(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::swap(), and services::WebSocket::UpgradeHeaders().
     {
         return storage.size();
     }
move_up()
template<class T > void infra::BoundedVector< T >::move_up (const_iterator position, size_type n) private
Definition at line 629 of file BoundedVector.hpp.
     {
         iterator copy_position = end();
         while (copy_position != position && copy_position + n != end())
         {
             storage[copy_position - begin() + n - 1].Construct(std::move(*(copy_position - 1)));
             --copy_position;
         }
         while (copy_position != position)
         {
             *storage[copy_position - begin() + n - 1] = std::move(*(copy_position - 1));
             --copy_position;
         }
         numAllocated += n;
     }
operator!=()
template<class T > bool infra::BoundedVector< T >::operator!= (const BoundedVector< T > & other) const
Definition at line 599 of file BoundedVector.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T > bool infra::BoundedVector< T >::operator< (const BoundedVector< T > & other) const
Definition at line 605 of file BoundedVector.hpp.
     {
         return std::lexicographical_compare(begin(), end(), other.begin(), other.end());
     }
operator<=()
template<class T > bool infra::BoundedVector< T >::operator<= (const BoundedVector< T > & other) const
Definition at line 611 of file BoundedVector.hpp.
     {
         return !(other < *this);
     }
operator=() [1/2]
template<class T > BoundedVector< T > & infra::BoundedVector< T >::operator= (const BoundedVector< T > & other)
Definition at line 202 of file BoundedVector.hpp.
     {
         if (this != &other)
             assign(other.begin(), other.end());
         return *this;
     }
operator=() [2/2]
template<class T > BoundedVector< T > & infra::BoundedVector< T >::operator= (BoundedVector< T > && other)
Definition at line 211 of file BoundedVector.hpp.
     {
         clear();
         numAllocated = other.size();
         for (size_type i = 0; i != size(); ++i)
             storage[i].Construct(std::move(other[i]));
         return *this;
     }
operator==()
template<class T > bool infra::BoundedVector< T >::operator== (const BoundedVector< T > & other) const
Definition at line 592 of file BoundedVector.hpp.
     {
         return size() == other.size()
             && std::equal(begin(), end(), other.begin());
     }
operator>()
template<class T > bool infra::BoundedVector< T >::operator> (const BoundedVector< T > & other) const
Definition at line 617 of file BoundedVector.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T > bool infra::BoundedVector< T >::operator>= (const BoundedVector< T > & other) const
Definition at line 623 of file BoundedVector.hpp.
     {
         return !(*this < other);
     }
operator[]() [1/2]
template<class T > BoundedVector< T >::value_type & infra::BoundedVector< T >::operator[] (size_type position)
Definition at line 361 of file BoundedVector.hpp.
     {
         really_assert(position >= 0 && position < size());
         return *storage[position];
     }
operator[]() [2/2]
template<class T > const BoundedVector< T >::value_type & infra::BoundedVector< T >::operator[] (size_type position) const
Definition at line 368 of file BoundedVector.hpp.
     {
         really_assert(position >= 0 && position < size());
         return *storage[position];
     }
pop_back()
template<class T > void infra::BoundedVector< T >::pop_back ()
Definition at line 465 of file BoundedVector.hpp.
Referenced by infra::Sequencer::PopContext(), and hal::QuadSpi::VectorToAddress().
     {
         really_assert(!empty());
         storage[numAllocated - 1].Destruct();
         --numAllocated;
     }
push_back() [1/2]
template<class T > void infra::BoundedVector< T >::push_back (const value_type & value)
Definition at line 449 of file BoundedVector.hpp.
Referenced by infra::Sequencer::PushContext(), services::DnsResolver::ReplyParser::ReadAdditionalRecords(), and services::WebSocket::UpgradeHeaders().
     {
         really_assert(!full());
         storage[numAllocated].Construct(value);
         ++numAllocated;
     }
push_back() [2/2]
template<class T > void infra::BoundedVector< T >::push_back (value_type && value)
Definition at line 457 of file BoundedVector.hpp.
     {
         really_assert(!full());
         storage[numAllocated].Construct(std::move(value));
         ++numAllocated;
     }
range() [1/2]
template<class T > infra::MemoryRange< T > infra::BoundedVector< T >::range ()
Definition at line 349 of file BoundedVector.hpp.
     {
         return infra::MemoryRange<T>(begin(), end());
     }
range() [2/2]
template<class T > infra::MemoryRange< const T > infra::BoundedVector< T >::range () const
Definition at line 355 of file BoundedVector.hpp.
     {
         return infra::MemoryRange<const T>(begin(), end());
     }
rbegin() [1/2]
template<class T > BoundedVector< T >::reverse_iterator infra::BoundedVector< T >::rbegin ()
Definition at line 266 of file BoundedVector.hpp.
     {
         return reverse_iterator(end());
     }
rbegin() [2/2]
template<class T > BoundedVector< T >::const_reverse_iterator infra::BoundedVector< T >::rbegin () const
Definition at line 272 of file BoundedVector.hpp.
     {
         return const_reverse_iterator(end());
     }
rend() [1/2]
template<class T > BoundedVector< T >::reverse_iterator infra::BoundedVector< T >::rend ()
Definition at line 278 of file BoundedVector.hpp.
     {
         return reverse_iterator(begin());
     }
rend() [2/2]
template<class T > BoundedVector< T >::const_reverse_iterator infra::BoundedVector< T >::rend () const
Definition at line 284 of file BoundedVector.hpp.
     {
         return const_reverse_iterator(begin());
     }
resize()
template<class T > void infra::BoundedVector< T >::resize (size_type n, const value_type & value = value_type())
Definition at line 327 of file BoundedVector.hpp.
Referenced by infra::Sequencer::Execute(), and infra::ProtoLengthDelimited::GetBytes().
     {
         while (n < size())
             pop_back();
         while (n > size())
             push_back(value);
     }
size()
template<class T > BoundedVector< T >::size_type infra::BoundedVector< T >::size () const
Definition at line 315 of file BoundedVector.hpp.
Referenced by infra::Sequencer::Execute(), infra::ProtoLengthDelimited::GetBytes(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::max_size(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator==(), services::DatagramWin::Send(), services::DatagramBsd::Send(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::swap(), and services::WebSocket::UpgradeHeaders().
     {
         return numAllocated;
     }
swap()
template<class T > void infra::BoundedVector< T >::swap (BoundedVector< T > & other)
Definition at line 539 of file BoundedVector.hpp.
Referenced by infra::swap().
     {
         using std::swap;
         assert(size() <= other.max_size() && other.size() < max_size());
         for (size_type i = 0; i < size() && i < other.size(); ++i)
         {
             swap(*storage[i], *other.storage[i]);
         }
         for (size_type i = size(); i < other.size(); ++i)
         {
             storage[i].Construct(std::move(*other.storage[i]));
             other.storage[i].Destruct();
         }
         for (size_type i = other.size(); i < size(); ++i)
         {
             other.storage[i].Construct(std::move(*storage[i]));
             storage[i].Destruct();
         }
         std::swap(numAllocated, other.numAllocated);
     }
Member Data Documentation
numAllocated
template<class T> size_type infra::BoundedVector< T >::numAllocated = 0 private
Definition at line 130 of file BoundedVector.hpp.
Referenced by infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::swap().
storage
template<class T> infra::MemoryRange<infra::StaticStorage<T> > infra::BoundedVector< T >::storage private
Definition at line 129 of file BoundedVector.hpp.
Referenced by infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::swap().
The documentation for this class was generated from the following file:
BoundedVector.hpp