EMil: infra::ProtoFormatter Class Reference
infra::ProtoFormatter Class Reference
#include <ProtoFormatter.hpp>
Public Member Functions
ProtoFormatter (infra::DataOutputStream output)
void PutVarInt (uint64_t value)
void PutSignedVarInt (uint64_t value)
void PutFixed32 (uint32_t value)
void PutFixed64 (uint64_t value)
void PutString (infra::BoundedConstString string)
void PutBytes (infra::ConstByteRange bytes)
void PutVarIntField (uint64_t value, uint32_t fieldNumber)
void PutSignedVarIntField (uint64_t value, uint32_t fieldNumber)
void PutFixed32Field (uint32_t value, uint32_t fieldNumber)
void PutFixed64Field (uint64_t value, uint32_t fieldNumber)
void PutLengthDelimitedField (infra::ConstByteRange range, uint32_t fieldNumber)
void PutStringField (infra::BoundedConstString string, uint32_t fieldNumber)
void PutBytesField (infra::ConstByteRange bytes, uint32_t fieldNumber)
ProtoLengthDelimitedFormatter LengthDelimitedFormatter (uint32_t fieldNumber)
Private Attributes
infra::DataOutputStream output
Friends
class ProtoLengthDelimitedFormatter
Detailed Description
Definition at line 25 of file ProtoFormatter.hpp.
Constructor & Destructor Documentation
ProtoFormatter()
infra::ProtoFormatter::ProtoFormatter (infra::DataOutputStream output) explicit
Definition at line 31 of file ProtoFormatter.cpp.
         : output(output.Writer(), output.ErrorPolicy())
     {}
Member Function Documentation
LengthDelimitedFormatter()
ProtoLengthDelimitedFormatter infra::ProtoFormatter::LengthDelimitedFormatter (uint32_t fieldNumber)
Definition at line 120 of file ProtoFormatter.cpp.
References ProtoLengthDelimitedFormatter.
     {
         return ProtoLengthDelimitedFormatter(*this, fieldNumber);
     }
PutBytes()
void infra::ProtoFormatter::PutBytes (infra::ConstByteRange bytes)
Definition at line 71 of file ProtoFormatter.cpp.
References output, PutVarInt(), and infra::MemoryRange< T >::size().
Referenced by PutBytesField().
     {
         PutVarInt(bytes.size());
         output << bytes;
     }
PutBytesField()
void infra::ProtoFormatter::PutBytesField (infra::ConstByteRange bytes, uint32_t fieldNumber)
Definition at line 114 of file ProtoFormatter.cpp.
References PutBytes(), and PutVarInt().
     {
         PutVarInt((fieldNumber << 3) | 2);
         PutBytes(bytes);
     }
PutFixed32()
void infra::ProtoFormatter::PutFixed32 (uint32_t value)
Definition at line 55 of file ProtoFormatter.cpp.
References output, and value.
Referenced by PutFixed32Field().
     {
         output << value;
     }
PutFixed32Field()
void infra::ProtoFormatter::PutFixed32Field (uint32_t value, uint32_t fieldNumber)
Definition at line 89 of file ProtoFormatter.cpp.
References PutFixed32(), PutVarInt(), and value.
     {
         PutVarInt((fieldNumber << 3) | 5);
         PutFixed32(value);
     }
PutFixed64()
void infra::ProtoFormatter::PutFixed64 (uint64_t value)
Definition at line 60 of file ProtoFormatter.cpp.
References output, and value.
Referenced by PutFixed64Field().
     {
         output << value;
     }
PutFixed64Field()
void infra::ProtoFormatter::PutFixed64Field (uint64_t value, uint32_t fieldNumber)
Definition at line 95 of file ProtoFormatter.cpp.
References PutFixed64(), PutVarInt(), and value.
     {
         PutVarInt((fieldNumber << 3) | 1);
         PutFixed64(value);
     }
PutLengthDelimitedField()
void infra::ProtoFormatter::PutLengthDelimitedField (infra::ConstByteRange range, uint32_t fieldNumber)
Definition at line 101 of file ProtoFormatter.cpp.
References output, PutVarInt(), and infra::MemoryRange< T >::size().
     {
         PutVarInt((fieldNumber << 3) | 2);
         PutVarInt(range.size());
         output << range;
     }
PutSignedVarInt()
void infra::ProtoFormatter::PutSignedVarInt (uint64_t value)
Definition at line 48 of file ProtoFormatter.cpp.
References PutVarInt(), and value.
Referenced by PutSignedVarIntField().
     {
         static const bool isArithmeticRightShift = (static_cast<signed int>(-1) >> 1) == static_cast<signed int>(-1);
         static_assert(isArithmeticRightShift, "");
         PutVarInt((value << 1) ^ (static_cast<int64_t>(value) >> 63));
     }
PutSignedVarIntField()
void infra::ProtoFormatter::PutSignedVarIntField (uint64_t value, uint32_t fieldNumber)
Definition at line 83 of file ProtoFormatter.cpp.
References PutSignedVarInt(), PutVarInt(), and value.
     {
         PutVarInt((fieldNumber << 3) | 0);
         PutSignedVarInt(value);
     }
PutString()
void infra::ProtoFormatter::PutString (infra::BoundedConstString string)
Definition at line 65 of file ProtoFormatter.cpp.
References output, PutVarInt(), and infra::StringAsByteRange().
Referenced by PutStringField().
     {
         PutVarInt(string.size());
         output << infra::StringAsByteRange(string);
     }
PutStringField()
void infra::ProtoFormatter::PutStringField (infra::BoundedConstString string, uint32_t fieldNumber)
Definition at line 108 of file ProtoFormatter.cpp.
References PutString(), and PutVarInt().
     {
         PutVarInt((fieldNumber << 3) | 2);
         PutString(string);
     }
PutVarInt()
void infra::ProtoFormatter::PutVarInt (uint64_t value)
Definition at line 35 of file ProtoFormatter.cpp.
References value.
Referenced by infra::ProtoLengthDelimitedFormatter::ProtoLengthDelimitedFormatter(), PutBytes(), PutBytesField(), PutFixed32Field(), PutFixed64Field(), PutLengthDelimitedField(), PutSignedVarInt(), PutSignedVarIntField(), PutString(), PutStringField(), PutVarIntField(), and infra::ProtoLengthDelimitedFormatter::~ProtoLengthDelimitedFormatter().
     {
         do
         {
             if (value > 127)
                 output << static_cast<uint8_t>(value & 0x7f | 0x80);
             else
                 output << static_cast<uint8_t>(value);
             value >>= 7;
         } while (value != 0);
     }
PutVarIntField()
void infra::ProtoFormatter::PutVarIntField (uint64_t value, uint32_t fieldNumber)
Definition at line 77 of file ProtoFormatter.cpp.
References PutVarInt(), and value.
     {
         PutVarInt((fieldNumber << 3) | 0);
         PutVarInt(value);
     }
Friends And Related Function Documentation
ProtoLengthDelimitedFormatter
friend class ProtoLengthDelimitedFormatter friend
Definition at line 47 of file ProtoFormatter.hpp.
Referenced by LengthDelimitedFormatter().
Member Data Documentation
output
infra::DataOutputStream infra::ProtoFormatter::output private
Definition at line 48 of file ProtoFormatter.hpp.
Referenced by infra::ProtoLengthDelimitedFormatter::ProtoLengthDelimitedFormatter(), PutBytes(), PutFixed32(), PutFixed64(), PutLengthDelimitedField(), PutString(), and infra::ProtoLengthDelimitedFormatter::~ProtoLengthDelimitedFormatter().
The documentation for this class was generated from the following files:
ProtoFormatter.hpp
ProtoFormatter.cpp