EMil: ConnectionSerialTest Class Reference
ConnectionSerialTest Class Reference
Public Member Functions
ConnectionSerialTest ()
void WindowSizeRequestReceived ()
void WindowSizeResponseReceived (size_t windowSize=2048)
void WindowSizeResponseRequestReceived (size_t windowSize=2048)
void ContentMessageReceived (std::vector< uint8_t > msg)
void ContentMessageReceivedAndObserverNotified (std::vector< uint8_t > msg)
void WindowSizeUpdateReceived (size_t windowSize)
void ExpectWindowSizeRequest (infra::Function< void()> actionOnCompletion)
void ExpectWindowSizeRequest ()
void ExpectWindowSizeResponse (size_t windowSize)
void ExpectWindowSizeResponseRequest (size_t windowSize)
void ExpectWindowSizeUpdate (size_t windowSize)
void ExpectWindowSizeUpdateWithComplete (size_t windowSize)
void ExpectAndCompleteWindowSizeRequest ()
void ExpectAndCompleteWindowSizeResponse (size_t windowSize)
void ExpectAndCompleteWindowSizeResponseRequest (size_t windowSize)
uint8_t ExpectSepearateContentHeaderAndContentMessages (std::vector< uint8_t > msg)
void ExpectAndCompleteSepearateContentHeaderAndContentMessage (std::vector< uint8_t > msg)
void ExpectSendStreamAvailable (std::vector< uint8_t > msg)
void GetAndWriteToSendStream (std::vector< uint8_t > msg)
void ExpectAndCompleteUpdate (size_t windowSize)
void AckReceivedAndExpectUpdate (size_t windowSize)
void Initialization (size_t peerWindowSize=2048)
void ReconstructConnection ()
void ReconstructConnectionWithMinUpdateSize (size_t minUpdateSize)
void ReconstructConnectionWithReceiveBufferSize (size_t size)
size_t ReceiveBufferSize () const
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< hal::SerialCommunicationMockWithAssert > serialCommunication
infra::Execute firstRequest1
uint8_t sendBuffer [4096]
std::vector< uint8_t > receiveBuffer
infra::Optional< infra::BoundedDeque< uint8_t > > receivedDataQueue
std::array< infra::StaticStorage< uint8_t >, 2048 > storage
infra::Optional< services::ConnectionSerial > connection
testing::StrictMock< services::ConnectionObserverMock > observer
infra::Execute firstRequest2
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 8 of file TestConnectionSerial.cpp.
Constructor & Destructor Documentation
ConnectionSerialTest()
ConnectionSerialTest::ConnectionSerialTest () inline
Definition at line 13 of file TestConnectionSerial.cpp.
References ExpectWindowSizeRequest(), and serialCommunication.
         : firstRequest1([this]() { ExpectWindowSizeRequest([this]() { serialCommunication.actionOnCompletion(); }); })
         , receiveBuffer(2048)
         , receivedDataQueue(infra::inPlace, storage)
         , connection(infra::inPlace, infra::MakeByteRange(sendBuffer), infra::MemoryRange<uint8_t>(receiveBuffer), *receivedDataQueue,  serialCommunication)
         , observer(*connection)
         , firstRequest2([this]() { ExecuteAllActions(); })
     {}
Member Function Documentation
AckReceivedAndExpectUpdate()
void ConnectionSerialTest::AckReceivedAndExpectUpdate (size_t windowSize) inline
Definition at line 205 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::AckReceived(), connection, and ExpectWindowSizeUpdateWithComplete().
     {
         ExpectWindowSizeUpdateWithComplete(windowSize);
         connection->AckReceived();
         ExecuteAllActions();
     }
ContentMessageReceived()
void ConnectionSerialTest::ContentMessageReceived (std::vector< uint8_t > msg) inline
Definition at line 54 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by ContentMessageReceivedAndObserverNotified().
     {
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfd });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(msg.size() >> 8) });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(msg.size()) });
         for (uint8_t element : msg)
             serialCommunication.dataReceived(std::vector<uint8_t>{ element });
     }
ContentMessageReceivedAndObserverNotified()
void ConnectionSerialTest::ContentMessageReceivedAndObserverNotified (std::vector< uint8_t > msg) inline
Definition at line 64 of file TestConnectionSerial.cpp.
References ContentMessageReceived(), and observer.
     {
         ContentMessageReceived(msg);
         EXPECT_CALL(observer, DataReceived());
         ExecuteAllActions();
     }
ExpectAndCompleteSepearateContentHeaderAndContentMessage()
void ConnectionSerialTest::ExpectAndCompleteSepearateContentHeaderAndContentMessage (std::vector< uint8_t > msg) inline
Definition at line 176 of file TestConnectionSerial.cpp.
References ExpectSepearateContentHeaderAndContentMessages(), and serialCommunication.
     {
         uint8_t serialCallCount = ExpectSepearateContentHeaderAndContentMessages(msg);
         ExecuteAllActions();
         for (int i=0; i<serialCallCount; i++)
             serialCommunication.actionOnCompletion();
     }
ExpectAndCompleteUpdate()
void ConnectionSerialTest::ExpectAndCompleteUpdate (size_t windowSize) inline
Definition at line 199 of file TestConnectionSerial.cpp.
References ExpectWindowSizeUpdateWithComplete().
     {
         ExpectWindowSizeUpdateWithComplete(windowSize);
         ExecuteAllActions();
     }
ExpectAndCompleteWindowSizeRequest()
void ConnectionSerialTest::ExpectAndCompleteWindowSizeRequest () inline
Definition at line 110 of file TestConnectionSerial.cpp.
References ExpectWindowSizeRequest(), and serialCommunication.
     {
         ExpectWindowSizeRequest();
         ExecuteAllActions();
         serialCommunication.actionOnCompletion();
     }
ExpectAndCompleteWindowSizeResponse()
void ConnectionSerialTest::ExpectAndCompleteWindowSizeResponse (size_t windowSize) inline
Definition at line 117 of file TestConnectionSerial.cpp.
References ExpectWindowSizeResponse(), and serialCommunication.
Referenced by Initialization().
     {
         ExpectWindowSizeResponse(windowSize);
         ExecuteAllActions();
         serialCommunication.actionOnCompletion();
     }
ExpectAndCompleteWindowSizeResponseRequest()
void ConnectionSerialTest::ExpectAndCompleteWindowSizeResponseRequest (size_t windowSize) inline
Definition at line 124 of file TestConnectionSerial.cpp.
References ExpectWindowSizeResponseRequest(), and serialCommunication.
     {
         ExpectWindowSizeResponseRequest(windowSize);
         ExecuteAllActions();
         serialCommunication.actionOnCompletion();
     }
ExpectSendStreamAvailable()
void ConnectionSerialTest::ExpectSendStreamAvailable (std::vector< uint8_t > msg) inline
Definition at line 184 of file TestConnectionSerial.cpp.
References observer.
Referenced by GetAndWriteToSendStream().
     {
         EXPECT_CALL(observer, SendStreamAvailableMock(testing::_)).WillOnce(testing::Invoke([msg](infra::SharedPtr<infra::StreamWriter> writer)
         {
             infra::ByteOutputStream::WithErrorPolicy stream(*writer);
             stream << infra::ConstByteRange(msg);
         }));
     }
ExpectSepearateContentHeaderAndContentMessages()
uint8_t ConnectionSerialTest::ExpectSepearateContentHeaderAndContentMessages (std::vector< uint8_t > msg) inline
Definition at line 132 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by ExpectAndCompleteSepearateContentHeaderAndContentMessage().
     {
         testing::InSequence sequential;
         int escapedMsgSize = 0;
         for (std::size_t i = 0; i < msg.size(); i++)
         {
             if (msg[i] >= 0xf9 && msg[i] <= 0xfe)
                 ++escapedMsgSize;
             ++escapedMsgSize;
         }
         uint8_t serialCallCount = 0;
         std::vector<uint8_t> contentMsgHeader = { 0xfd, static_cast<uint8_t>(escapedMsgSize >> 8), static_cast<uint8_t>(escapedMsgSize) };
         EXPECT_CALL(serialCommunication, SendDataMock(contentMsgHeader));
         ++serialCallCount;
         std::vector<uint8_t>::iterator it1 = msg.begin(), it2 = msg.begin();
         for (it2 = msg.begin(); it2 != msg.end(); ++it2)
         {
             if (*it2 >= 0xf9 && *it2 <= 0xfe)
             {
                 if (it1 != it2)
                 {
                     EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>(it1, it2)));
                     ++serialCallCount;
                 }
                 EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>({ 0xf9, *it2 })));
                 ++serialCallCount;
                 it1 = it2 + 1;
             }
         }
         if (it1 != it2)
         {
             EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>(it1, it2)));
             ++serialCallCount;
         }
         return serialCallCount;
     }
ExpectWindowSizeRequest() [1/2]
void ConnectionSerialTest::ExpectWindowSizeRequest (infra::Function< void()> actionOnCompletion) inline
Definition at line 78 of file TestConnectionSerial.cpp.
References serialCommunication.
     {
         EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>{ 0xfa, 0xfa, 0xfa }))
             .WillOnce(testing::InvokeWithoutArgs([actionOnCompletion]() { actionOnCompletion(); }));
     }
ExpectWindowSizeRequest() [2/2]
void ConnectionSerialTest::ExpectWindowSizeRequest () inline
Definition at line 84 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by ConnectionSerialTest(), ExpectAndCompleteWindowSizeRequest(), ReconstructConnectionWithMinUpdateSize(), and ReconstructConnectionWithReceiveBufferSize().
     {
         EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>{ 0xfa, 0xfa, 0xfa }));
     }
ExpectWindowSizeResponse()
void ConnectionSerialTest::ExpectWindowSizeResponse (size_t windowSize) inline
Definition at line 89 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by ExpectAndCompleteWindowSizeResponse().
     {
         EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>{ 0xfb, static_cast<uint8_t>(windowSize >> 8), static_cast<uint8_t>(windowSize) }));
     }
ExpectWindowSizeResponseRequest()
void ConnectionSerialTest::ExpectWindowSizeResponseRequest (size_t windowSize) inline
Definition at line 94 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by ExpectAndCompleteWindowSizeResponseRequest().
     {
         EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>{ 0xfc, static_cast<uint8_t>(windowSize >> 8), static_cast<uint8_t>(windowSize) }));
     }
ExpectWindowSizeUpdate()
void ConnectionSerialTest::ExpectWindowSizeUpdate (size_t windowSize) inline
Definition at line 99 of file TestConnectionSerial.cpp.
References serialCommunication.
     {
         EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>{ 0xfe, static_cast<uint8_t>(windowSize >> 8), static_cast<uint8_t>(windowSize) }));
     }
ExpectWindowSizeUpdateWithComplete()
void ConnectionSerialTest::ExpectWindowSizeUpdateWithComplete (size_t windowSize) inline
Definition at line 104 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by AckReceivedAndExpectUpdate(), and ExpectAndCompleteUpdate().
     {
         EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>{ 0xfe, static_cast<uint8_t>(windowSize >> 8), static_cast<uint8_t>(windowSize) }))
             .WillOnce(testing::InvokeWithoutArgs([this]() { serialCommunication.actionOnCompletion(); }));
     }
GetAndWriteToSendStream()
void ConnectionSerialTest::GetAndWriteToSendStream (std::vector< uint8_t > msg) inline
Definition at line 193 of file TestConnectionSerial.cpp.
References connection, ExpectSendStreamAvailable(), services::ConnectionSerial::MaxSendStreamSize(), and services::ConnectionSerial::RequestSendStream().
     {
         connection->RequestSendStream(connection->MaxSendStreamSize());
         ExpectSendStreamAvailable(msg);
     }
Initialization()
void ConnectionSerialTest::Initialization (size_t peerWindowSize = 2048) inline
Definition at line 212 of file TestConnectionSerial.cpp.
References ExpectAndCompleteWindowSizeResponse(), ReceiveBufferSize(), and WindowSizeResponseRequestReceived().
     {
         WindowSizeResponseRequestReceived(peerWindowSize);
         ExpectAndCompleteWindowSizeResponse(ReceiveBufferSize());
         ExecuteAllActions();
     }
ReceiveBufferSize()
size_t ConnectionSerialTest::ReceiveBufferSize () const inline
Definition at line 244 of file TestConnectionSerial.cpp.
References receiveBuffer.
Referenced by Initialization().
     {
         return static_cast<uint16_t>(receiveBuffer.size() - 1);
     }
ReconstructConnection()
void ConnectionSerialTest::ReconstructConnection () inline
Definition at line 219 of file TestConnectionSerial.cpp.
References connection, infra::Optional< T >::Emplace(), infra::MakeByteRange(), observer, receiveBuffer, receivedDataQueue, sendBuffer, and serialCommunication.
Referenced by ReconstructConnectionWithReceiveBufferSize().
     {
         observer.Detach();
         connection.Emplace(infra::MakeByteRange(sendBuffer), infra::MemoryRange<uint8_t>(receiveBuffer), *receivedDataQueue, serialCommunication);
         observer.Attach(*connection);
     }
ReconstructConnectionWithMinUpdateSize()
void ConnectionSerialTest::ReconstructConnectionWithMinUpdateSize (size_t minUpdateSize) inline
Definition at line 226 of file TestConnectionSerial.cpp.
References connection, infra::Optional< T >::Emplace(), ExpectWindowSizeRequest(), infra::MakeByteRange(), observer, receiveBuffer, receivedDataQueue, sendBuffer, and serialCommunication.
     {
         ExpectWindowSizeRequest([this]() { serialCommunication.actionOnCompletion(); });
         observer.Detach();
         connection.Emplace(infra::MakeByteRange(sendBuffer), infra::MemoryRange<uint8_t>(receiveBuffer), *receivedDataQueue, serialCommunication, minUpdateSize);
         observer.Attach(*connection);
         ExecuteAllActions();
     }
ReconstructConnectionWithReceiveBufferSize()
void ConnectionSerialTest::ReconstructConnectionWithReceiveBufferSize (size_t size) inline
Definition at line 235 of file TestConnectionSerial.cpp.
References infra::Optional< T >::Emplace(), ExpectWindowSizeRequest(), receiveBuffer, receivedDataQueue, ReconstructConnection(), serialCommunication, and storage.
     {
         ExpectWindowSizeRequest([this]() { serialCommunication.actionOnCompletion(); });
         receiveBuffer.resize(size);
         receivedDataQueue.Emplace(infra::MemoryRange<infra::StaticStorage<uint8_t>>(&storage[0], &storage[size]));
         ReconstructConnection();
         ExecuteAllActions();
     }
WindowSizeRequestReceived()
void ConnectionSerialTest::WindowSizeRequestReceived () inline
Definition at line 33 of file TestConnectionSerial.cpp.
References serialCommunication.
     {
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
     }
WindowSizeResponseReceived()
void ConnectionSerialTest::WindowSizeResponseReceived (size_t windowSize = 2048) inline
Definition at line 40 of file TestConnectionSerial.cpp.
References serialCommunication.
     {
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfb });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(windowSize >> 8) });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(windowSize) });
     }
WindowSizeResponseRequestReceived()
void ConnectionSerialTest::WindowSizeResponseRequestReceived (size_t windowSize = 2048) inline
Definition at line 47 of file TestConnectionSerial.cpp.
References serialCommunication.
Referenced by Initialization().
     {
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfc });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(windowSize >> 8) });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(windowSize) });
     }
WindowSizeUpdateReceived()
void ConnectionSerialTest::WindowSizeUpdateReceived (size_t windowSize) inline
Definition at line 71 of file TestConnectionSerial.cpp.
References serialCommunication.
     {
         serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfe });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(windowSize >> 8) });
         serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(windowSize) });
     }
Member Data Documentation
connection
infra::Optional<services::ConnectionSerial> ConnectionSerialTest::connection
Definition at line 28 of file TestConnectionSerial.cpp.
Referenced by AckReceivedAndExpectUpdate(), GetAndWriteToSendStream(), ReconstructConnection(), and ReconstructConnectionWithMinUpdateSize().
firstRequest1
infra::Execute ConnectionSerialTest::firstRequest1
Definition at line 23 of file TestConnectionSerial.cpp.
firstRequest2
infra::Execute ConnectionSerialTest::firstRequest2
Definition at line 30 of file TestConnectionSerial.cpp.
observer
testing::StrictMock<services::ConnectionObserverMock> ConnectionSerialTest::observer
Definition at line 29 of file TestConnectionSerial.cpp.
Referenced by ContentMessageReceivedAndObserverNotified(), ExpectSendStreamAvailable(), ReconstructConnection(), and ReconstructConnectionWithMinUpdateSize().
receiveBuffer
std::vector<uint8_t> ConnectionSerialTest::receiveBuffer
Definition at line 25 of file TestConnectionSerial.cpp.
Referenced by ReceiveBufferSize(), ReconstructConnection(), ReconstructConnectionWithMinUpdateSize(), and ReconstructConnectionWithReceiveBufferSize().
receivedDataQueue
infra::Optional<infra::BoundedDeque<uint8_t> > ConnectionSerialTest::receivedDataQueue
Definition at line 26 of file TestConnectionSerial.cpp.
Referenced by ReconstructConnection(), ReconstructConnectionWithMinUpdateSize(), and ReconstructConnectionWithReceiveBufferSize().
sendBuffer
uint8_t ConnectionSerialTest::sendBuffer[4096]
Definition at line 24 of file TestConnectionSerial.cpp.
Referenced by ReconstructConnection(), and ReconstructConnectionWithMinUpdateSize().
serialCommunication
testing::StrictMock<hal::SerialCommunicationMockWithAssert> ConnectionSerialTest::serialCommunication
Definition at line 22 of file TestConnectionSerial.cpp.
Referenced by ConnectionSerialTest(), ContentMessageReceived(), ExpectAndCompleteSepearateContentHeaderAndContentMessage(), ExpectAndCompleteWindowSizeRequest(), ExpectAndCompleteWindowSizeResponse(), ExpectAndCompleteWindowSizeResponseRequest(), ExpectSepearateContentHeaderAndContentMessages(), ExpectWindowSizeRequest(), ExpectWindowSizeResponse(), ExpectWindowSizeResponseRequest(), ExpectWindowSizeUpdate(), ExpectWindowSizeUpdateWithComplete(), ReconstructConnection(), ReconstructConnectionWithMinUpdateSize(), ReconstructConnectionWithReceiveBufferSize(), WindowSizeRequestReceived(), WindowSizeResponseReceived(), WindowSizeResponseRequestReceived(), and WindowSizeUpdateReceived().
storage
std::array<infra::StaticStorage<uint8_t>, 2048> ConnectionSerialTest::storage
Definition at line 27 of file TestConnectionSerial.cpp.
Referenced by ReconstructConnectionWithReceiveBufferSize().
The documentation for this class was generated from the following file:
TestConnectionSerial.cpp