EMil: infra::TimerLimitedRepeatingWithClosingAction Class Reference
infra::TimerLimitedRepeatingWithClosingAction Class Reference
#include <TimerLimitedRepeatingWithClosingAction.hpp>
Public Member Functions
TimerLimitedRepeatingWithClosingAction (uint32_t timerServiceId=systemTimerServiceId)
TimerLimitedRepeatingWithClosingAction (int aHowMany, Duration duration, const infra::Function< void()> &action, const infra::Function< void()> &aClosingAction, uint32_t timerServiceId=systemTimerServiceId)
void Start (int aHowMany, Duration duration, const infra::Function< void()> &action, const infra::Function< void()> &aClosingAction)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual const infra::Function< void()> & Action () const override
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Attributes
TimePoint triggerStart
Duration triggerPeriod
int howMany = 0
infra::Function< void()> action
infra::Function< void()> closingAction
Detailed Description
Definition at line 11 of file TimerLimitedRepeatingWithClosingAction.hpp.
Constructor & Destructor Documentation
TimerLimitedRepeatingWithClosingAction() [1/2]
infra::TimerLimitedRepeatingWithClosingAction::TimerLimitedRepeatingWithClosingAction (uint32_t timerServiceId = systemTimerServiceId) explicit
Definition at line 5 of file TimerLimitedRepeatingWithClosingAction.cpp.
         : Timer(timerServiceId)
         , triggerPeriod()
     {}
TimerLimitedRepeatingWithClosingAction() [2/2]
infra::TimerLimitedRepeatingWithClosingAction::TimerLimitedRepeatingWithClosingAction (int aHowMany, Duration duration, const infra::Function< void()> & action, const infra::Function< void()> & aClosingAction, uint32_t timerServiceId = systemTimerServiceId)
Definition at line 10 of file TimerLimitedRepeatingWithClosingAction.cpp.
References Start().
         : Timer(timerServiceId)
     {
         Start(aHowMany, duration, aAction, aClosingAction);
     }
Member Function Documentation
Action()
const infra::Function< void()> & infra::TimerLimitedRepeatingWithClosingAction::Action () const override protected virtual
Reimplemented from infra::Timer.
Definition at line 28 of file TimerLimitedRepeatingWithClosingAction.cpp.
References action, closingAction, and howMany.
     {
         if (howMany >= 0)
             return action;
         else
             return closingAction;
     }
ComputeNextTriggerTime()
void infra::TimerLimitedRepeatingWithClosingAction::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 36 of file TimerLimitedRepeatingWithClosingAction.cpp.
References infra::Timer::Cancel(), infra::emptyFunction, howMany, infra::Timer::Now(), infra::Timer::SetNextTriggerTime(), triggerPeriod, and triggerStart.
Referenced by Start().
     {
         if (howMany >= 0)
         {
             --howMany;
             TimePoint now = Now();
             Duration diff = now - triggerStart;
             if (diff < Duration())
                 now += triggerPeriod;
             diff %= triggerPeriod;
             SetNextTriggerTime(now - diff + triggerPeriod, infra::emptyFunction);
         }
         else
             Cancel();
     }
Start()
void infra::TimerLimitedRepeatingWithClosingAction::Start (int aHowMany, Duration duration, const infra::Function< void()> & action, const infra::Function< void()> & aClosingAction)
Definition at line 16 of file TimerLimitedRepeatingWithClosingAction.cpp.
References action, closingAction, ComputeNextTriggerTime(), howMany, infra::Timer::Now(), infra::Timer::Resolution(), triggerPeriod, and triggerStart.
Referenced by TimerLimitedRepeatingWithClosingAction().
     {
         closingAction = aClosingAction;
         action = aAction;
         triggerStart = Now() + Resolution();
         triggerPeriod = duration;
         howMany = aHowMany;
         ComputeNextTriggerTime();
     }
Member Data Documentation
action
infra::Function<void()> infra::TimerLimitedRepeatingWithClosingAction::action private
Definition at line 28 of file TimerLimitedRepeatingWithClosingAction.hpp.
Referenced by Action(), and Start().
closingAction
infra::Function<void()> infra::TimerLimitedRepeatingWithClosingAction::closingAction private
Definition at line 29 of file TimerLimitedRepeatingWithClosingAction.hpp.
Referenced by Action(), and Start().
howMany
int infra::TimerLimitedRepeatingWithClosingAction::howMany = 0 private
Definition at line 27 of file TimerLimitedRepeatingWithClosingAction.hpp.
Referenced by Action(), ComputeNextTriggerTime(), and Start().
triggerPeriod
Duration infra::TimerLimitedRepeatingWithClosingAction::triggerPeriod private
Definition at line 26 of file TimerLimitedRepeatingWithClosingAction.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
triggerStart
TimePoint infra::TimerLimitedRepeatingWithClosingAction::triggerStart private
Definition at line 25 of file TimerLimitedRepeatingWithClosingAction.hpp.
Referenced by ComputeNextTriggerTime(), and Start().
The documentation for this class was generated from the following files:
TimerLimitedRepeatingWithClosingAction.hpp
TimerLimitedRepeatingWithClosingAction.cpp