EMil: TestByteInputStream.cpp File Reference
TestByteInputStream.cpp File Reference
Classes
class ByteInputStreamReaderTest
Functions
TEST_F (ByteInputStreamReaderTest, construction)
TEST_F (ByteInputStreamReaderTest, Extract)
TEST_F (ByteInputStreamReaderTest, Peek)
TEST_F (ByteInputStreamReaderTest, ExtractContiguousRange)
TEST_F (ByteInputStreamReaderTest, PeekContiguousRange_from_start_position)
TEST_F (ByteInputStreamReaderTest, ExtractContiguousRange_limited_by_max)
TEST_F (ByteInputStreamReaderTest, Rewind)
TEST (ByteInputStreamTest, construct_with_range)
TEST (ByteInputStreamTest, construct_softFail_with_range)
TEST (ByteInputStreamTest, construct_noFail_with_range)
TEST (ByteInputStreamTest, StreamFromRange)
TEST (ByteInputStreamTest, StreamToMemoryRange)
Function Documentation
TEST() [1/5]
TEST (ByteInputStreamTest , construct_with_range)
Definition at line 63 of file TestByteInputStream.cpp.
References infra::InputStream::ContiguousRange(), data, and EXPECT_EQ().
 {
     std::array<uint8_t, 4> data{{1, 2, 3, 4}};
     infra::ByteInputStream stream(data);
     EXPECT_EQ((std::array<uint8_t, 4>{{1, 2, 3, 4}}), stream.ContiguousRange(16));
 }
TEST() [2/5]
TEST (ByteInputStreamTest , construct_softFail_with_range)
Definition at line 70 of file TestByteInputStream.cpp.
References infra::InputStream::ContiguousRange(), data, EXPECT_EQ(), and infra::softFail.
 {
     std::array<uint8_t, 4> data{{1, 2, 3, 4}};
     infra::ByteInputStream stream(data, infra::softFail);
     EXPECT_EQ((std::array<uint8_t, 4>{{1, 2, 3, 4}}), stream.ContiguousRange(16));
 }
TEST() [3/5]
TEST (ByteInputStreamTest , construct_noFail_with_range)
Definition at line 77 of file TestByteInputStream.cpp.
References infra::InputStream::ContiguousRange(), data, EXPECT_EQ(), and infra::noFail.
 {
     std::array<uint8_t, 4> data{ { 1, 2, 3, 4 } };
     infra::ByteInputStream stream(data, infra::noFail);
     EXPECT_EQ((std::array<uint8_t, 4>{ {1, 2, 3, 4}}), stream.ContiguousRange(16));
 }
TEST() [4/5]
TEST (ByteInputStreamTest , StreamFromRange)
Definition at line 84 of file TestByteInputStream.cpp.
References infra::InputStream::Empty(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), operator==(), infra::ByteInputStreamReader::Processed(), infra::DataInputStream::WithReader< TheReader >::Reader(), and infra::ByteInputStreamReader::Remaining().
 {
     std::array<uint8_t, 4> from = { 0, 1, 2, 3 };
     struct To
     {
         uint8_t a;
         uint8_t b;
         bool operator==(const To& other) const { return a == other.a && b == other.b; };
     } to = { 4, 5 };
     infra::ByteInputStream stream(from);
     EXPECT_EQ(from, stream.Reader().Remaining());
     stream >> to;
     EXPECT_EQ((To{ 0, 1 }), to);
     EXPECT_FALSE(stream.Empty());
     stream >> to;
     EXPECT_EQ((To{ 2, 3 }), to);
     EXPECT_TRUE(stream.Empty());
     EXPECT_EQ(from, stream.Reader().Processed());
 }
TEST() [5/5]
TEST (ByteInputStreamTest , StreamToMemoryRange)
Definition at line 110 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     std::array<uint8_t, 2> to = { 0, 1 };
     std::array<uint8_t, 4> buffer = { 2, 3, 4, 5 };
     infra::ByteInputStream stream(buffer);
     stream >> to;
     EXPECT_EQ((std::array<uint8_t, 2>{{ 2, 3 }}), to);
 }
TEST_F() [1/7]
TEST_F (ByteInputStreamReaderTest , construction)
Definition at line 18 of file TestByteInputStream.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     EXPECT_FALSE(reader.Empty());
     EXPECT_EQ(8, reader.Available());
 }
TEST_F() [2/7]
TEST_F (ByteInputStreamReaderTest , Extract)
Definition at line 24 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     std::array<uint8_t, 4> result;
     reader.Extract(result, errorPolicy);
     EXPECT_EQ((std::array<uint8_t, 4>{{1, 2, 3, 4}}), result);
 }
TEST_F() [3/7]
TEST_F (ByteInputStreamReaderTest , Peek)
Definition at line 31 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(1, reader.Peek(errorPolicy));
 }
TEST_F() [4/7]
TEST_F (ByteInputStreamReaderTest , ExtractContiguousRange)
Definition at line 36 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ((std::array<uint8_t, 8>{{1, 2, 3, 4, 5, 6, 7, 8}}), reader.ExtractContiguousRange(16));
 }
TEST_F() [5/7]
TEST_F (ByteInputStreamReaderTest , PeekContiguousRange_from_start_position)
Definition at line 41 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ((std::array<uint8_t, 8>{ {1, 2, 3, 4, 5, 6, 7, 8}}), reader.PeekContiguousRange(0));
     EXPECT_EQ((std::array<uint8_t, 2>{ {7, 8}}), reader.PeekContiguousRange(6));
 }
TEST_F() [6/7]
TEST_F (ByteInputStreamReaderTest , ExtractContiguousRange_limited_by_max)
Definition at line 48 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ((std::array<uint8_t, 2>{{1, 2}}), reader.ExtractContiguousRange(2));
 }
TEST_F() [7/7]
TEST_F (ByteInputStreamReaderTest , Rewind)
Definition at line 53 of file TestByteInputStream.cpp.
References EXPECT_EQ().
 {
     reader.ExtractContiguousRange(2);
     auto marker = reader.ConstructSaveMarker();
     reader.ExtractContiguousRange(2);
     reader.Rewind(marker);
     EXPECT_EQ((std::array<uint8_t, 2>{ {3, 4}}), reader.ExtractContiguousRange(2));
 }