EMil: services::TracerAdapterPrintf Class Reference
services::TracerAdapterPrintf Class Reference
#include <TracerAdapterPrintf.hpp>
Public Member Functions
TracerAdapterPrintf (services::Tracer &tracer)
void Print (const char *format, va_list *args)
Private Member Functions
void HandleFormat (const char *&format, va_list *args)
int ReadLength (const char *&format) const
infra::Width ReadSize (const char *&format) const
void ParseFormat (char format, int lengthSpecifier, const infra::Width &width, va_list *args)
Private Attributes
services::Tracer & tracer
Detailed Description
Definition at line 9 of file TracerAdapterPrintf.hpp.
Constructor & Destructor Documentation
TracerAdapterPrintf()
services::TracerAdapterPrintf::TracerAdapterPrintf (services::Tracer & tracer) explicit
Definition at line 5 of file TracerAdapterPrintf.cpp.
         : tracer(tracer)
     {}
Member Function Documentation
HandleFormat()
void services::TracerAdapterPrintf::HandleFormat (const char *& format, va_list * args) private
Definition at line 25 of file TracerAdapterPrintf.cpp.
References ParseFormat(), ReadLength(), and ReadSize().
Referenced by Print().
     {
         ++format;
         const auto width = ReadSize(format);
         const auto lengthSpecifier = ReadLength(format);
         ParseFormat(*format, lengthSpecifier, width, args);
     }
ParseFormat()
void services::TracerAdapterPrintf::ParseFormat (char format, int lengthSpecifier, const infra::Width & width, va_list * args) private
Definition at line 71 of file TracerAdapterPrintf.cpp.
References services::Tracer::Continue(), infra::hex, and tracer.
Referenced by HandleFormat().
     {
         switch (format)
         {
             case '\0': break;
             case '%':
                 tracer.Continue() << format;
                 break;
             case 'c':
                 tracer.Continue() << static_cast<const char>(va_arg(*args, int32_t));
                 break;
             case 's':
             {
                 auto* s = reinterpret_cast<const char*>(va_arg(*args, int32_t));
                 tracer.Continue() << (s != nullptr ? s : "(null)");
                 break;
             }
             case 'd':
             case 'i':
                 if (lengthSpecifier >= 2)
                     tracer.Continue() << va_arg(*args, int64_t);
                 else
                     tracer.Continue() << va_arg(*args, int32_t);
                 break;
             case 'u':
                 if (lengthSpecifier >= 2)
                     tracer.Continue() << va_arg(*args, uint64_t);
                 else
                     tracer.Continue() << va_arg(*args, uint32_t);
                 break;
             case 'p':                                                                                               //TICS !CFL#001
                 tracer.Continue() << "0x";
             case 'X':
             case 'x':
                 if (lengthSpecifier >= 2)
                     tracer.Continue() << infra::hex << width << va_arg(*args, uint64_t);
                 else
                     tracer.Continue() << infra::hex << width << va_arg(*args, uint32_t);
                 break;
             case 'f':
                 tracer.Continue() << static_cast<float>(va_arg(*args, double));
                 break;
             default:
                 while (lengthSpecifier-- > 0)
                     tracer.Continue() << 'l';
                 tracer.Continue() << format;
                 break;
         }
     }
Print()
void services::TracerAdapterPrintf::Print (const char * format, va_list * args)
Definition at line 9 of file TracerAdapterPrintf.cpp.
References services::Tracer::Continue(), HandleFormat(), services::Tracer::Trace(), and tracer.
     {
         assert(format != nullptr);
         assert(args != nullptr);
         for (; *format != 0; ++format)
         {
             if (*format == '%')
                 HandleFormat(format, args);
             else if (*format == '\n')
                 tracer.Trace();
             else
                 tracer.Continue() << *format;
         }
     }
ReadLength()
int services::TracerAdapterPrintf::ReadLength (const char *& format) const private
Definition at line 34 of file TracerAdapterPrintf.cpp.
Referenced by HandleFormat().
     {
         auto lengthSpecifier = 0;
         while (*format == 'l')
         {
             ++lengthSpecifier;
             ++format;
         }
         return lengthSpecifier;
     }
ReadSize()
infra::Width services::TracerAdapterPrintf::ReadSize (const char *& format) const private
Definition at line 47 of file TracerAdapterPrintf.cpp.
References infra::Width::padding, and infra::Width::width.
Referenced by HandleFormat().
     {
         infra::Width w(0);
         if (*format == '0')
         {
             w.padding = '0';
             format++;
         }
         while (*format > '0' && *format <= '9')
         {
             w.width = w.width*10 + *format - '0';
             ++format;
         }
         if (*format == '.')
         {
             ++format;
             while (*format > '0' && *format <= '9')
                 ++format;
         }
         return w;
     }
Member Data Documentation
tracer
services::Tracer& services::TracerAdapterPrintf::tracer private
Definition at line 23 of file TracerAdapterPrintf.hpp.
Referenced by ParseFormat(), and Print().
The documentation for this class was generated from the following files:
TracerAdapterPrintf.hpp
TracerAdapterPrintf.cpp