EMil: TestConnectionMbedTls.cpp File Reference
TestConnectionMbedTls.cpp File Reference
Classes
class ConnectionMbedTlsTest
Functions
TEST_F (ConnectionMbedTlsTest, when_allocation_on_network_fails_Listen_returns_nullptr)
TEST_F (ConnectionMbedTlsTest, when_listener_allocation_fails_Listen_returns_nullptr)
TEST_F (ConnectionMbedTlsTest, Listen_returns_listener)
TEST_F (ConnectionMbedTlsTest, create_connection)
TEST_F (ConnectionMbedTlsTest, send_and_receive_data)
TEST_F (ConnectionMbedTlsTest, reopen_connection)
Function Documentation
TEST_F() [1/6]
TEST_F (ConnectionMbedTlsTest , when_allocation_on_network_fails_Listen_returns_nullptr)
Definition at line 39 of file TestConnectionMbedTls.cpp.
References services::both, and EXPECT_EQ().
 {
     EXPECT_CALL(network, ListenMock(1234, services::IPVersions::both)).WillOnce(testing::Return(nullptr));
     infra::SharedPtr<void> listener = connectionFactory.Listen(1234, serverObserverFactory);
     EXPECT_EQ(nullptr, listener);
 }
TEST_F() [2/6]
TEST_F (ConnectionMbedTlsTest , when_listener_allocation_fails_Listen_returns_nullptr)
Definition at line 46 of file TestConnectionMbedTls.cpp.
References services::both, and EXPECT_EQ().
 {
     EXPECT_CALL(network, ListenMock(1234, services::IPVersions::both)).WillOnce(testing::Return(thisListener));
     infra::SharedPtr<void> listener1 = connectionFactory.Listen(1234, serverObserverFactory);
     infra::SharedPtr<void> listener2 = connectionFactory.Listen(1234, serverObserverFactory);
     EXPECT_EQ(nullptr, listener2);
 }
TEST_F() [3/6]
TEST_F (ConnectionMbedTlsTest , Listen_returns_listener)
Definition at line 54 of file TestConnectionMbedTls.cpp.
References services::both.
 {
     EXPECT_CALL(network, ListenMock(1234, services::IPVersions::both)).WillOnce(testing::Return(thisListener));
     infra::SharedPtr<void> listener = connectionFactory.Listen(1234, serverObserverFactory);
     EXPECT_NE(nullptr, listener);
 }
TEST_F() [4/6]
TEST_F (ConnectionMbedTlsTest , create_connection)
Definition at line 61 of file TestConnectionMbedTls.cpp.
References infra::SharedOptional< T >::Emplace(), infra::Lambda(), and infra::SingleObserver< Descendant, SubjectType_ >::Subject().
 {
     services::ConnectionFactoryMbedTls::WithMaxConnectionsListenersAndConnectors<2, 0, 1> tlsNetworkClient(loopBackNetwork, clientCertificates, randomDataGenerator);
     services::ConnectionFactoryMbedTls::WithMaxConnectionsListenersAndConnectors<2, 1, 0> tlsNetworkServer(loopBackNetwork, serverCertificates, randomDataGenerator);
     infra::SharedPtr<void> listener = tlsNetworkServer.Listen(1234, serverObserverFactory);
     EXPECT_CALL(clientObserverFactory, Port()).WillOnce(testing::Return(1234));
     tlsNetworkClient.Connect(clientObserverFactory);
     infra::SharedOptional<services::ConnectionObserverMock> observer1;
     infra::SharedOptional<services::ConnectionObserverMock> observer2;
     EXPECT_CALL(serverObserverFactory, ConnectionAcceptedMock(testing::_, testing::_))
         .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver, services::IPAddress address)
     {
         createdObserver(observer1.Emplace());
     }));
     EXPECT_CALL(clientObserverFactory, ConnectionEstablishedMock(testing::_))
         .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver)
     {
         createdObserver(observer2.Emplace());
     }));
     ExecuteAllActions();
     observer1->Subject().AbortAndDestroy();
 }
TEST_F() [5/6]
TEST_F (ConnectionMbedTlsTest , send_and_receive_data)
Definition at line 86 of file TestConnectionMbedTls.cpp.
References infra::SharedOptional< T >::Emplace(), EXPECT_EQ(), infra::Lambda(), services::ConnectionObserverStub::receivedData, services::ConnectionObserverStub::SendData(), and infra::SingleObserver< Descendant, SubjectType_ >::Subject().
 {
     services::ConnectionFactoryMbedTls::WithMaxConnectionsListenersAndConnectors<2, 1, 0> tlsNetworkServer(loopBackNetwork, serverCertificates, randomDataGenerator);
     services::ConnectionFactoryMbedTls::WithMaxConnectionsListenersAndConnectors<2, 0, 1> tlsNetworkClient(loopBackNetwork, clientCertificates, randomDataGenerator);
     infra::SharedPtr<void> listener = tlsNetworkServer.Listen(1234, serverObserverFactory);
     EXPECT_CALL(clientObserverFactory, Port()).WillOnce(testing::Return(1234));
     tlsNetworkClient.Connect(clientObserverFactory);
     infra::SharedOptional<services::ConnectionObserverStub> observer1;
     infra::SharedOptional<services::ConnectionObserverStub> observer2;
     EXPECT_CALL(serverObserverFactory, ConnectionAcceptedMock(testing::_, testing::_))
         .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver, services::IPAddress address)
     {
         createdObserver(observer1.Emplace());
     }));
     EXPECT_CALL(clientObserverFactory, ConnectionEstablishedMock(testing::_))
         .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver)
     {
         createdObserver(observer2.Emplace());
     }));
     ExecuteAllActions();
     observer2->SendData(std::vector<uint8_t>{ 1, 2, 3, 4 });
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 1, 2, 3, 4 }), observer1->receivedData);
     observer1->SendData(std::vector<uint8_t>{ 5, 6, 7, 8 });
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 5, 6, 7, 8 }), observer2->receivedData);
     observer1->Subject().AbortAndDestroy();
 }
TEST_F() [6/6]
TEST_F (ConnectionMbedTlsTest , reopen_connection)
Definition at line 121 of file TestConnectionMbedTls.cpp.
References infra::SharedOptional< T >::Emplace(), infra::Lambda(), and infra::SingleObserver< Descendant, SubjectType_ >::Subject().
 {
     services::ConnectionFactoryMbedTls::WithMaxConnectionsListenersAndConnectors<2, 1, 0> tlsNetworkServer(loopBackNetwork, serverCertificates, randomDataGenerator);
     services::ConnectionFactoryMbedTls::WithMaxConnectionsListenersAndConnectors<2, 0, 1> tlsNetworkClient(loopBackNetwork, clientCertificates, randomDataGenerator);
     infra::SharedPtr<void> listener = tlsNetworkServer.Listen(1234, serverObserverFactory);
     {
         EXPECT_CALL(clientObserverFactory, Port()).WillOnce(testing::Return(1234));
         tlsNetworkClient.Connect(clientObserverFactory);
         infra::SharedOptional<services::ConnectionObserverStub> observer1;
         infra::SharedOptional<services::ConnectionObserverStub> observer2;
         EXPECT_CALL(serverObserverFactory, ConnectionAcceptedMock(testing::_, testing::_))
             .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver, services::IPAddress address)
         {
             createdObserver(observer1.Emplace());
         }));
         EXPECT_CALL(clientObserverFactory, ConnectionEstablishedMock(testing::_))
             .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver)
         {
             createdObserver(observer2.Emplace());
         }));
         ExecuteAllActions();
         observer1->Subject().AbortAndDestroy();
     }
     {
         EXPECT_CALL(clientObserverFactory, Port()).WillOnce(testing::Return(1234));
         tlsNetworkClient.Connect(clientObserverFactory);
         infra::SharedOptional<services::ConnectionObserverStub> observer1;
         infra::SharedOptional<services::ConnectionObserverStub> observer2;
         EXPECT_CALL(serverObserverFactory, ConnectionAcceptedMock(testing::_, testing::_))
             .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver, services::IPAddress address)
         {
             createdObserver(observer1.Emplace());
         }));
         EXPECT_CALL(clientObserverFactory, ConnectionEstablishedMock(testing::_))
             .WillOnce(infra::Lambda([&](infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> createdObserver)
         {
             createdObserver(observer2.Emplace());
         }));
         ExecuteAllActions();
         observer1->Subject().AbortAndDestroy();
     }
 }