EMil: services::CertificatesMbedTls Class Reference
services::CertificatesMbedTls Class Reference
#include <CertificatesMbedTls.hpp>
Public Member Functions
CertificatesMbedTls ()
CertificatesMbedTls (const CertificatesMbedTls &other)=delete
CertificatesMbedTls & operator= (const CertificatesMbedTls &other)=delete
~CertificatesMbedTls ()
void AddCertificateAuthority (infra::ConstByteRange certificate)
void AddCertificateAuthority (const infra::BoundedConstString &certificate)
void AddOwnCertificate (const infra::BoundedConstString &certificate, const infra::BoundedConstString &privateKey)
void Config (mbedtls_ssl_config &sslConfig)
void GenerateNewKey (hal::SynchronousRandomDataGenerator &randomDataGenerator)
void WritePrivateKey (infra::BoundedString outputBuffer)
void WriteOwnCertificate (infra::BoundedString outputBuffer, hal::SynchronousRandomDataGenerator &randomDataGenerator)
void UpdateValidToDate ()
Protected Attributes
mbedtls_x509_crt caCertificates
mbedtls_x509_crt ownCertificate
mbedtls_pk_context privateKey
Private Member Functions
int32_t ExtractExponent (const mbedtls_rsa_context &rsaContext) const
void X509AddAlgorithm (infra::Asn1Formatter &root, const mbedtls_x509_buf &oid) const
void X509AddName (infra::Asn1Formatter &root, const mbedtls_x509_name &name) const
void X509AddTime (infra::Asn1Formatter &root, const mbedtls_x509_time &time) const
Private Attributes
const mbedtls_x509_time unlimitedExpirationDate = { 9999, 12, 31, 23, 59, 59 }
Detailed Description
Definition at line 12 of file CertificatesMbedTls.hpp.
Constructor & Destructor Documentation
CertificatesMbedTls() [1/2]
services::CertificatesMbedTls::CertificatesMbedTls ()
Definition at line 28 of file CertificatesMbedTls.cpp.
References caCertificates, ownCertificate, and privateKey.
     {
         mbedtls_x509_crt_init(&caCertificates);
         mbedtls_x509_crt_init(&ownCertificate);
         mbedtls_pk_init(&privateKey);
     }
CertificatesMbedTls() [2/2]
services::CertificatesMbedTls::CertificatesMbedTls (const CertificatesMbedTls & other) delete
~CertificatesMbedTls()
services::CertificatesMbedTls::~CertificatesMbedTls ()
Definition at line 35 of file CertificatesMbedTls.cpp.
References caCertificates, ownCertificate, and privateKey.
     {
         mbedtls_pk_free(&privateKey);
         mbedtls_x509_crt_free(&caCertificates);
         mbedtls_x509_crt_free(&ownCertificate);
     }
Member Function Documentation
AddCertificateAuthority() [1/2]
void services::CertificatesMbedTls::AddCertificateAuthority (infra::ConstByteRange certificate)
Definition at line 42 of file CertificatesMbedTls.cpp.
References infra::MemoryRange< T >::begin(), caCertificates, and infra::MemoryRange< T >::size().
Referenced by main().
     {
         int result = mbedtls_x509_crt_parse(&caCertificates, reinterpret_cast<const unsigned char*>(certificate.begin()), certificate.size());
         assert(result == 0);
     }
AddCertificateAuthority() [2/2]
void services::CertificatesMbedTls::AddCertificateAuthority (const infra::BoundedConstString & certificate)
Definition at line 48 of file CertificatesMbedTls.cpp.
References caCertificates, infra::BoundedStringBase< T >::data(), and infra::BoundedStringBase< T >::size().
     {
         int result = mbedtls_x509_crt_parse(&caCertificates, reinterpret_cast<const unsigned char*>(certificate.data()), certificate.size());
         assert(result == 0);
     }
AddOwnCertificate()
void services::CertificatesMbedTls::AddOwnCertificate (const infra::BoundedConstString & certificate, const infra::BoundedConstString & privateKey)
Definition at line 54 of file CertificatesMbedTls.cpp.
References infra::BoundedStringBase< T >::data(), ownCertificate, privateKey, and infra::BoundedStringBase< T >::size().
     {
         int result = mbedtls_x509_crt_parse(&ownCertificate, reinterpret_cast<const unsigned char*>(certificate.data()), certificate.size());
         assert(result == 0);
         result = mbedtls_pk_parse_key(&privateKey, reinterpret_cast<const unsigned char*>(key.data()), key.size(), NULL, 0);
         assert(result == 0);
     }
Config()
void services::CertificatesMbedTls::Config (mbedtls_ssl_config & sslConfig)
Definition at line 62 of file CertificatesMbedTls.cpp.
References caCertificates, ownCertificate, and privateKey.
Referenced by services::ConnectionMbedTls::ConnectionMbedTls().
     {
         mbedtls_ssl_conf_ca_chain(&sslConfig, &caCertificates, nullptr);
         int result = mbedtls_ssl_conf_own_cert(&sslConfig, &ownCertificate, &privateKey);
         assert(result == 0);
     }
ExtractExponent()
int32_t services::CertificatesMbedTls::ExtractExponent (const mbedtls_rsa_context & rsaContext) const private
Definition at line 216 of file CertificatesMbedTls.cpp.
Referenced by GenerateNewKey().
     {
         uint32_t exponent = 0;
         mbedtls_mpi_write_binary(&rsaContext.E, reinterpret_cast<unsigned char*>(&exponent), sizeof(uint32_t));
         exponent = (exponent << 16) | (exponent >> 16);
         exponent = ((exponent & 0x00ff00ff) << 8) | ((exponent & 0xff00ff00) >> 8);
         return exponent;
     }
GenerateNewKey()
void services::CertificatesMbedTls::GenerateNewKey (hal::SynchronousRandomDataGenerator & randomDataGenerator)
Definition at line 69 of file CertificatesMbedTls.cpp.
References ExtractExponent(), and privateKey.
     {
         if (mbedtls_pk_get_type(&privateKey) != MBEDTLS_PK_RSA)
             return;
         mbedtls_rsa_context* rsaContext = mbedtls_pk_rsa(privateKey);
         assert(rsaContext != nullptr);
         size_t keySizeInBits = mbedtls_pk_get_bitlen(&privateKey);
         int32_t exponent = ExtractExponent(*rsaContext);
         mbedtls_rsa_gen_key(rsaContext, &RandomDataGeneratorWrapper, &randomDataGenerator, keySizeInBits, exponent);
     }
operator=()
CertificatesMbedTls& services::CertificatesMbedTls::operator= (const CertificatesMbedTls & other) delete
UpdateValidToDate()
void services::CertificatesMbedTls::UpdateValidToDate ()
Definition at line 211 of file CertificatesMbedTls.cpp.
References ownCertificate, and unlimitedExpirationDate.
     {
         ownCertificate.valid_to = unlimitedExpirationDate;
     }
WriteOwnCertificate()
void services::CertificatesMbedTls::WriteOwnCertificate (infra::BoundedString outputBuffer, hal::SynchronousRandomDataGenerator & randomDataGenerator)
Definition at line 111 of file CertificatesMbedTls.cpp.
References infra::AsBase64(), infra::MemoryRange< T >::cend(), infra::BoundedStringBase< T >::clear(), infra::MakeByteRange(), infra::MakeConstByteRange(), ownCertificate, privateKey, infra::Asn1Formatter::StartSequence(), X509AddAlgorithm(), X509AddName(), and X509AddTime().
     {
         infra::ByteOutputStream::WithStorage<2048> contentsStream;
         infra::Asn1Formatter formatter(contentsStream);
         {
             infra::ByteRange tbsBegin;
             infra::ByteRange tbsEnd;
             auto certificateSequence = formatter.StartSequence();
             {
                 tbsBegin = contentsStream.Writer().Processed();
                 {
                     auto tbsSequence = certificateSequence.StartSequence();
                     // Version
                     {
                         auto versionContext = tbsSequence.StartContextSpecific();
                         versionContext.Add(uint8_t(ownCertificate.version - 1));
                     }
                     // Serial
                     tbsSequence.AddSerial(MakeConstByteRange(ownCertificate.serial));
                     // Signature Object ID
                     X509AddAlgorithm(tbsSequence, ownCertificate.sig_oid);
                     // Issuer Name
                     {
                         auto issuerSequence = tbsSequence.StartSequence();
                         X509AddName(issuerSequence, ownCertificate.issuer);
                     }
                     // Validity
                     {
                         auto timeSequence = tbsSequence.StartSequence();
                         X509AddTime(timeSequence, ownCertificate.valid_from);
                         X509AddTime(timeSequence, ownCertificate.valid_to);
                     }
                     // Subject Name
                     {
                         auto subjectSequence = tbsSequence.StartSequence();
                         X509AddName(subjectSequence, ownCertificate.subject);
                     }
                     // PublicKeyInfo
                     {
                         auto publicKeyInfoSequence = tbsSequence.StartSequence();
                         mbedtls_x509_buf pk_oid;
                         mbedtls_oid_get_oid_by_pk_alg(mbedtls_pk_get_type(&privateKey), const_cast<const char**>(reinterpret_cast<char**>(&pk_oid.p)), &pk_oid.len);
                         X509AddAlgorithm(publicKeyInfoSequence, pk_oid);
{
                             auto publicKeyBitString = publicKeyInfoSequence.StartBitString();
{
                                 auto rsaPublicKeySequence = publicKeyBitString.StartSequence();
                                 mbedtls_rsa_context* rsaContext = mbedtls_pk_rsa(privateKey);
                                 assert(rsaContext != nullptr);
                                 rsaPublicKeySequence.AddBigNumber(MakeByteRange(rsaContext->N));
                                 rsaPublicKeySequence.AddBigNumber(MakeByteRange(rsaContext->E));
                             }
                         }
                     }
                     //  v3 Extensions
                     if (ownCertificate.version == 3)
                         tbsSequence.AddContextSpecific(3, MakeConstByteRange(ownCertificate.v3_ext));
                 }
                 tbsEnd = contentsStream.Writer().Processed();
                 // Sign new certificate
                 unsigned char hash[64] = {};
                 if (mbedtls_md(mbedtls_md_info_from_type(ownCertificate.sig_md), tbsBegin.cend(), std::distance(tbsBegin.cend(), tbsEnd.cend()), hash) != 0)
                     std::abort();
                 unsigned char signature[MBEDTLS_MPI_MAX_SIZE];
                 size_t signatureLength = 0;
                 if (mbedtls_pk_sign(&privateKey, ownCertificate.sig_md, hash, 0, signature, &signatureLength, &RandomDataGeneratorWrapper, &randomDataGenerator) != 0)
                     std::abort();
                 X509AddAlgorithm(certificateSequence, ownCertificate.sig_oid);
                 certificateSequence.AddBitString(infra::ConstByteRange(signature, signature + signatureLength));
             }
         }
         outputBuffer.clear();
         infra::StringOutputStream stream(outputBuffer);
         stream << "-----BEGIN CERTIFICATE-----\r\n";
         stream << infra::AsBase64(contentsStream.Writer().Processed());
         stream << "-----END CERTIFICATE-----\r\n";
         stream << '\0';
     }
WritePrivateKey()
void services::CertificatesMbedTls::WritePrivateKey (infra::BoundedString outputBuffer)
Definition at line 83 of file CertificatesMbedTls.cpp.
References infra::AsBase64(), infra::BoundedStringBase< T >::clear(), infra::MakeByteRange(), privateKey, and infra::Asn1Formatter::StartSequence().
     {
         infra::ByteOutputStream::WithStorage<2048> contentsStream;
         infra::Asn1Formatter formatter(contentsStream);
         {
             auto sequence = formatter.StartSequence();
             mbedtls_rsa_context& rsaContext = *mbedtls_pk_rsa(privateKey);
             sequence.Add(uint8_t(rsaContext.ver));
             sequence.AddBigNumber(MakeByteRange(rsaContext.N));
             sequence.AddBigNumber(MakeByteRange(rsaContext.E));
             sequence.AddBigNumber(MakeByteRange(rsaContext.D));
             sequence.AddBigNumber(MakeByteRange(rsaContext.P));
             sequence.AddBigNumber(MakeByteRange(rsaContext.Q));
             sequence.AddBigNumber(MakeByteRange(rsaContext.DP));
             sequence.AddBigNumber(MakeByteRange(rsaContext.DQ));
             sequence.AddBigNumber(MakeByteRange(rsaContext.QP));
         }
         outputBuffer.clear();
         infra::StringOutputStream stream(outputBuffer);
         stream << "-----BEGIN RSA PRIVATE KEY-----\r\n";
         stream << infra::AsBase64(contentsStream.Writer().Processed());
         stream << "-----END RSA PRIVATE KEY-----\r\n";
         stream << '\0';
     }
X509AddAlgorithm()
void services::CertificatesMbedTls::X509AddAlgorithm (infra::Asn1Formatter & root, const mbedtls_x509_buf & oid) const private
Definition at line 226 of file CertificatesMbedTls.cpp.
References infra::Asn1Formatter::AddObjectId(), infra::MakeConstByteRange(), infra::none, and infra::Asn1Formatter::StartSequence().
Referenced by WriteOwnCertificate().
     {
         auto algorithmSequence = root.StartSequence();
         algorithmSequence.AddObjectId(MakeConstByteRange(oid));
         algorithmSequence.AddOptional<uint8_t>(infra::none);
     }
X509AddName()
void services::CertificatesMbedTls::X509AddName (infra::Asn1Formatter & root, const mbedtls_x509_name & name) const private
Definition at line 233 of file CertificatesMbedTls.cpp.
References infra::Asn1Formatter::AddObjectId(), infra::MakeConstByteRange(), infra::Asn1Formatter::StartSequence(), and infra::Asn1Formatter::StartSet().
Referenced by WriteOwnCertificate().
     {
         const mbedtls_x509_name* node = &name;
         while (node)
         {
             auto name = root.StartSet();
             {
                 auto attributeTypeAndValueSequence = name.StartSequence();
                 attributeTypeAndValueSequence.AddObjectId(MakeConstByteRange(node->oid));
                 attributeTypeAndValueSequence.AddPrintableString(MakeConstByteRange(node->val));
             }
             node = node->next;
         }
     }
X509AddTime()
void services::CertificatesMbedTls::X509AddTime (infra::Asn1Formatter & root, const mbedtls_x509_time & time) const private
Definition at line 250 of file CertificatesMbedTls.cpp.
References infra::Asn1Formatter::AddTime().
Referenced by WriteOwnCertificate().
     {
         root.AddTime(time.year, time.mon, time.day, time.hour, time.min, time.sec);
     }
Member Data Documentation
caCertificates
mbedtls_x509_crt services::CertificatesMbedTls::caCertificates protected
Definition at line 44 of file CertificatesMbedTls.hpp.
Referenced by AddCertificateAuthority(), CertificatesMbedTls(), Config(), and ~CertificatesMbedTls().
ownCertificate
mbedtls_x509_crt services::CertificatesMbedTls::ownCertificate protected
Definition at line 45 of file CertificatesMbedTls.hpp.
Referenced by AddOwnCertificate(), CertificatesMbedTls(), Config(), UpdateValidToDate(), WriteOwnCertificate(), and ~CertificatesMbedTls().
privateKey
mbedtls_pk_context services::CertificatesMbedTls::privateKey protected
Definition at line 46 of file CertificatesMbedTls.hpp.
Referenced by AddOwnCertificate(), CertificatesMbedTls(), Config(), GenerateNewKey(), WriteOwnCertificate(), WritePrivateKey(), and ~CertificatesMbedTls().
unlimitedExpirationDate
const mbedtls_x509_time services::CertificatesMbedTls::unlimitedExpirationDate = { 9999, 12, 31, 23, 59, 59 } private
Definition at line 41 of file CertificatesMbedTls.hpp.
Referenced by UpdateValidToDate().
The documentation for this class was generated from the following files:
CertificatesMbedTls.hpp
CertificatesMbedTls.cpp