EMil: TestJson.cpp File Reference
TestJson.cpp File Reference
Functions
TEST (BasicUsageTest, object_with_some_values)
TEST (BasicUsageTest, array_with_strings)
TEST (JsonTokenizerTest, get_end_token)
TEST (JsonTokenizerTest, get_empty_string_token)
TEST (JsonTokenizerTest, get_string_token)
TEST (JsonTokenizerTest, get_escaped_string_token)
TEST (JsonTokenizerTest, unclosed_string_results_in_error_token)
TEST (JsonObjectTest, JsonString_ToString_limits_to_destination)
object GetString ("key").ToString(data)
EXPECT_EQ ("\\", data)
TEST (JsonObjectTest, JsonString_ToStdString_unescapes)
EXPECT_EQ ("\\\\", object.GetString("key").ToStdString())
TEST (JsonObjectTest, JsonString_equality_unescapes)
EXPECT_TRUE ("\\\\"==object.GetString("key"))
EXPECT_TRUE (object.GetString("key")=="\\\\")
EXPECT_TRUE (infra::BoundedConstString("\\\\")==object.GetString("key"))
EXPECT_FALSE ("\\\\" !=object.GetString("key"))
EXPECT_FALSE (object.GetString("key") !="\\\\")
EXPECT_FALSE (infra::BoundedConstString("\\\\") !=object.GetString("key"))
TEST (JsonObjectTest, JsonString_size)
EXPECT_EQ (8, object.GetString("key").size())
EXPECT_FALSE (object.GetString("key").empty())
TEST (JsonObjectTest, JsonString_corner_case_escaping)
TEST (JsonObjectTest, iterator_equality)
TEST (JsonArrayIteratorTest, empty_array_iterator_compares_equal_to_end)
TEST (JsonArrayIteratorTest, nonempty_array_iterator_does_not_compare_equal_to_end)
TEST (JsonObjectIteratorTest, get_value_from_iterator)
TEST (JsonObjectIteratorTest, get_multiple_values_from_iterator)
TEST (JsonArrayTest, empty_array_construction)
TEST (JsonArrayTest, nonempty_array_construction)
TEST (JsonArrayTest, iterate_over_array)
TEST (JsonArrayTest, iterate_over_strings_in_array)
TEST (JsonArrayTest, iterate_over_strings_in_array_with_other_values_sets_error)
TEST (JsonArrayTest, iterate_over_booleans_in_array)
TEST (JsonArrayTest, iterate_over_integers_in_array)
TEST (JsonArrayTest, iterate_over_objects_in_array)
TEST (JsonArrayTest, iterate_over_arrays_in_array)
TEST (JsonArrayTest, incorrect_array_sets_error)
TEST (JsonArrayTest, nested_float_is_accepted)
Variables
infra::BoundedString::WithStorage< 4 > data
Function Documentation
EXPECT_EQ() [1/3]
EXPECT_EQ ("\ , data)
Referenced by HttpServerTest::CheckHttpResponse(), CertificatesMbedTlsWithVerify::CompareDate(), HttpServerTest::ExpectPageServerRequest(), HttpClientBasicTest::HttpClientBasicTest(), HttpClientJsonTest::HttpClientJsonTest(), services::HttpHeadersEquals(), hal::SpiMock::SendAndReceive(), TEST(), TEST_F(), TEST_P(), and CertificatesMbedTlsWithVerify::VerifyCertificate().
EXPECT_EQ() [2/3]
EXPECT_EQ ("\" , object. GetString"key").ToStdString()
EXPECT_EQ() [3/3]
EXPECT_EQ (8 , object. GetString"key").size()
EXPECT_FALSE() [1/4]
EXPECT_FALSE ("\" ! = object.GetString("key"))
Referenced by TEST(), and TEST_F().
EXPECT_FALSE() [2/4]
EXPECT_FALSE (object.GetString("key") ! = "\\\\")
EXPECT_FALSE() [3/4]
EXPECT_FALSE (infra::BoundedConstString("\") ! = object.GetString("key"))
EXPECT_FALSE() [4/4]
EXPECT_FALSE (object. GetString"key").empty()
EXPECT_TRUE() [1/3]
EXPECT_TRUE ("\" = =object.GetString("key"))
Referenced by TestClaimer::GrantedClaim(), IntrusiveSetTest::Representation(), TEST(), TEST_F(), and IntrusiveBinarySearchTreeTest::~IntrusiveBinarySearchTreeTest().
EXPECT_TRUE() [2/3]
EXPECT_TRUE (object. GetString"key" = ="\\\\")
EXPECT_TRUE() [3/3]
EXPECT_TRUE (infra::BoundedConstString("\\") = =object.GetString("key"))
GetString()
object GetString ("key")
Referenced by TEST().
TEST() [1/28]
TEST (BasicUsageTest , object_with_some_values)
Definition at line 4 of file TestJson.cpp.
References EXPECT_EQ(), and GetString().
 {
     infra::JsonObject object(R"({ "key" : "value", "enabled" : true, "subobject" : { "nested": true } })");
     EXPECT_EQ("value", object.GetString("key"));
     EXPECT_EQ(true, object.GetBoolean("enabled"));
     EXPECT_EQ(true, object.GetObject("subobject").GetBoolean("nested"));
 }
TEST() [2/28]
TEST (BasicUsageTest , array_with_strings)
Definition at line 13 of file TestJson.cpp.
References EXPECT_TRUE(), and infra::JsonStringArray().
 {
     infra::JsonArray array(R"([ "first", "second", "third" ])");
     for (auto string : JsonStringArray(array))
         EXPECT_TRUE(string == "first" || string == "second" || string == "third");
 }
TEST() [3/28]
TEST (JsonTokenizerTest , get_end_token)
Definition at line 21 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonTokenizer::Token().
 {
     infra::JsonTokenizer tokenizer(R"()");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::End()), tokenizer.Token());
 }
TEST() [4/28]
TEST (JsonTokenizerTest , get_empty_string_token)
Definition at line 28 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonTokenizer::Token().
 {
     infra::JsonTokenizer tokenizer(R"("")");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::String("")), tokenizer.Token());
 }
TEST() [5/28]
TEST (JsonTokenizerTest , get_string_token)
Definition at line 35 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonTokenizer::Token().
 {
     infra::JsonTokenizer tokenizer(R"("string")");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::String("string")), tokenizer.Token());
 }
TEST() [6/28]
TEST (JsonTokenizerTest , get_escaped_string_token)
Definition at line 42 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonTokenizer::Token().
 {
     infra::JsonTokenizer tokenizer(R"("str\"ing")");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::String(R"(str\"ing)")), tokenizer.Token());
 }
TEST() [7/28]
TEST (JsonTokenizerTest , unclosed_string_results_in_error_token)
Definition at line 49 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonTokenizer::Token().
 {
     infra::JsonTokenizer tokenizer(R"("str)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Error()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_end_token_after_string_token)
 {
     infra::JsonTokenizer tokenizer(R"("string")");
     ASSERT_EQ(infra::JsonToken::Token(infra::JsonToken::String("string")), tokenizer.Token());
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::End()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_int_token)
 {
     infra::JsonTokenizer tokenizer("42");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Integer(42)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_negative_int_token)
 {
     infra::JsonTokenizer tokenizer("-42");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Integer(-42)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, skip_whitespace_before_end)
 {
     infra::JsonTokenizer tokenizer(R"( )");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::End()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, skip_tab_whitespace_before_end)
 {
     infra::JsonTokenizer tokenizer("\t");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::End()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_true_token)
 {
     infra::JsonTokenizer tokenizer(R"(true)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Boolean(true)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_false_token)
 {
     infra::JsonTokenizer tokenizer(R"(false)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Boolean(false)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_colon_token)
 {
     infra::JsonTokenizer tokenizer(R"(:)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Colon()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_comma_token)
 {
     infra::JsonTokenizer tokenizer(R"(,)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Comma()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_left_brace_token)
 {
     infra::JsonTokenizer tokenizer(R"({)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::LeftBrace(0)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_right_brace_token)
 {
     infra::JsonTokenizer tokenizer(R"(})");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::RightBrace(0)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_left_bracket_token)
 {
     infra::JsonTokenizer tokenizer(R"([)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::LeftBracket(0)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_right_bracket_token)
 {
     infra::JsonTokenizer tokenizer(R"(])");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::RightBracket(0)), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, unknown_character_results_in_error_token)
 {
     infra::JsonTokenizer tokenizer(R"(~)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Error()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, unknown_identifier_results_in_error_token)
 {
     infra::JsonTokenizer tokenizer(R"(identifier)");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Error()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, get_multiple_tokens)
 {
     infra::JsonTokenizer tokenizer(R"({ "key" : "value" })");
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::LeftBrace(0)), tokenizer.Token());
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::String("key")), tokenizer.Token());
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::Colon()), tokenizer.Token());
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::String("value")), tokenizer.Token());
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::RightBrace(18)), tokenizer.Token());
     EXPECT_EQ(infra::JsonToken::Token(infra::JsonToken::End()), tokenizer.Token());
 }
 TEST(JsonTokenizerTest, clean_json)
 {
     infra::BoundedString::WithStorage<512> data(R"({ "key" : "value", "key2" : 1234, "key3" : true })");
     infra::CleanJsonContents(data);
     EXPECT_EQ(R"({"key":"value","key2":1234,"key3":true})", data);
 }
 TEST(JsonObjectIteratorTest, empty_object_iterator_compares_equal_to_end)
 {
     infra::JsonObject object(R"({ })");
     infra::JsonObjectIterator iterator(object.begin());
     infra::JsonObjectIterator endIterator(object.end());
     EXPECT_EQ(endIterator, iterator);
 }
 TEST(JsonObjectIteratorTest, nonempty_object_iterator_does_not_compare_equal_to_end)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     infra::JsonObjectIterator iterator(object.begin());
     infra::JsonObjectIterator endIterator(object.end());
     EXPECT_NE(endIterator, iterator);
 }
 TEST(JsonObjectIteratorTest, get_key_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ("key", iterator->key);
 }
 TEST(JsonObjectIteratorTest, after_next_iterator_is_end)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(object.end(), ++iterator);
 }
 TEST(JsonObjectIteratorTest, get_second_key_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : "value", "second_key" : "second_value" })");
     infra::JsonObjectIterator iterator(object.begin());
     ++iterator;
     EXPECT_EQ("second_key", iterator->key);
 }
 TEST(JsonObjectIteratorTest, get_second_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : "value", "second_key" : "second_value" })");
     infra::JsonObjectIterator iterator(object.begin());
     ++iterator;
     EXPECT_EQ("second_value", iterator->value.Get<infra::JsonString>());
 }
 TEST(JsonObjectIteratorTest, get_string_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ("value", iterator->value.Get<infra::JsonString>());
 }
 TEST(JsonObjectIteratorTest, get_integer_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : 42 })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(42, iterator->value.Get<int32_t>());
 }
 TEST(JsonObjectIteratorTest, get_true_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : true })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(true, iterator->value.Get<bool>());
 }
 TEST(JsonObjectIteratorTest, get_false_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : false })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(false, iterator->value.Get<bool>());
 }
 TEST(JsonObjectIteratorTest, get_object_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : { "bla" } })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(R"({ "bla" })", iterator->value.Get<infra::JsonObject>().ObjectString());
 }
 TEST(JsonObjectIteratorTest, get_object_value_with_nested_object_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : { "bla" : { } } })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(R"({ "bla" : { } })", iterator->value.Get<infra::JsonObject>().ObjectString());
 }
 TEST(JsonObjectIteratorTest, get_array_value_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : [ "bla" ] })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(R"([ "bla" ])", iterator->value.Get<infra::JsonArray>().ObjectString());
 }
 TEST(JsonObjectIteratorTest, get_object_value_from_iterator_with_error)
 {
     infra::JsonObject object(R"({ "key" : { "bla" : ~ } })");
     EXPECT_EQ(object.end(), object.begin());
 }
 TEST(JsonObjectIteratorTest, get_array_value_from_iterator_with_error)
 {
     infra::JsonObject object(R"({ "key" : [ "bla", ~ ] })");
     EXPECT_EQ(object.end(), object.begin());
 }
 TEST(JsonObjectIteratorTest, get_array_value_with_nested_array_from_iterator)
 {
     infra::JsonObject object(R"({ "key" : [ "bla", [ ] ] })");
     infra::JsonObjectIterator iterator(object.begin());
     EXPECT_EQ(R"([ "bla", [ ] ])", iterator->value.Get<infra::JsonArray>().ObjectString());
 }
 TEST(JsonObjectTest, empty_object_construction)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_EQ(object.end(), object.begin());
 }
 TEST(JsonObjectTest, nonempty_object_construction)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     EXPECT_NE(object.end(), object.begin());
 }
 TEST(JsonObjectTest, has_key_when_value_exists)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     EXPECT_TRUE(object.HasKey("key"));
 }
 TEST(JsonObjectTest, has_key_when_value_does_not_exist)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_FALSE(object.HasKey("key"));
 }
 TEST(JsonObjectTest, iterate_over_object)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     for (auto keyValue : object)
         EXPECT_EQ("value", keyValue.value.Get<infra::JsonString>());
 }
 TEST(JsonObjectTest, incorrect_object_sets_error)
 {
     std::vector<infra::BoundedConstString> errorObjects = { R"(~)", R"({~})", R"({ true })", R"({ "key" ~})", R"({ "key" : ~})", R"({ "key" : [})", R"({ "key" : true ~})" };
     for (auto errorObject : errorObjects)
     {
         infra::JsonObject object(errorObject);
         for (auto keyValue : object)
         {}
         EXPECT_TRUE(object.Error());
     }
 }
 TEST(JsonObjectTest, get_string)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     EXPECT_EQ("value", object.GetString("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_boolean)
 {
     infra::JsonObject object(R"({ "key" : true })");
     EXPECT_EQ(true, object.GetBoolean("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_integer)
 {
     infra::JsonObject object(R"({ "key" : 5 })");
     EXPECT_EQ(5, object.GetInteger("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_object)
 {
     infra::JsonObject object(R"({ "key" : { "bla" } })");
     EXPECT_EQ(R"({ "bla" })", object.GetObject("key").ObjectString());
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_array)
 {
     infra::JsonObject object(R"({ "key" : [ "bla" ] })");
     EXPECT_EQ(R"([ "bla" ])", object.GetArray("key").ObjectString());
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_optional_string)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     EXPECT_EQ("value", *object.GetOptionalString("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_none_when_optional_string_is_absent)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_EQ(infra::none, object.GetOptionalString("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_optional_boolean)
 {
     infra::JsonObject object(R"({ "key" : true })");
     EXPECT_EQ(true, *object.GetOptionalBoolean("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_none_when_optional_boolean_is_absent)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_EQ(infra::none, object.GetOptionalBoolean("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_none_when_optional_boolean_is_absent_but_key_is_present)
 {
     infra::JsonObject object(R"({ "key" : "value" })");
     EXPECT_EQ(infra::none, object.GetOptionalBoolean("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_optional_object)
 {
     infra::JsonObject object(R"({ "key" : { "bla" } })");
     EXPECT_EQ(R"({ "bla" })", object.GetOptionalObject("key")->ObjectString());
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_none_when_optional_object_is_absent)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_EQ(infra::none, object.GetOptionalObject("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_none_when_optional_array_is_absent)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_EQ(infra::none, object.GetOptionalArray("key"));
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, get_nonexistent_string_sets_error_on_object)
 {
     infra::JsonObject object(R"({ })");
     EXPECT_FALSE(object.Error());
     object.GetString("key");
     EXPECT_TRUE(object.Error());
 }
 TEST(JsonObjectTest, nested_float_is_accepted)
 {
     infra::JsonObject object(R"({ "key": { "nestedKey", 1.5 } })");
     for (auto x : object)
     {}
     EXPECT_FALSE(object.Error());
 }
 TEST(JsonObjectTest, JsonString_ToString_unescapes)
 {
     infra::JsonObject object(R"({ "key": "\"\\\n\t\r\b\f\u0020\u002a\u002A" })");
     infra::BoundedString::WithStorage<32> data;
     object.GetString("key").ToString(data);
     EXPECT_EQ("\"\\\n\t\r\b\f **", data);
     EXPECT_EQ("\\\"\\\\\\n\\t\\r\\b\\f\\u0020\\u002a\\u002A", object.GetString("key").Raw());
 }
TEST() [8/28]
TEST (JsonObjectTest , JsonString_ToString_limits_to_destination)
Definition at line 495 of file TestJson.cpp.
 {
     infra::JsonObject object(R"({ "key": "\"\\\n\t\r\b\f\u0020" })");
TEST() [9/28]
TEST (JsonObjectTest , JsonString_ToStdString_unescapes)
Definition at line 504 of file TestJson.cpp.
References EXPECT_EQ(), and GetString().
 {
     infra::JsonObject object(R"({ "key": "\"\\\n\t\r\b\f\u0020" })");
TEST() [10/28]
TEST (JsonObjectTest , JsonString_equality_unescapes)
Definition at line 511 of file TestJson.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and GetString().
 {
     infra::JsonObject object(R"({ "key": "\"\\\n\t\r\b\f\u0020" })");
TEST() [11/28]
TEST (JsonObjectTest , JsonString_size)
Definition at line 526 of file TestJson.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and GetString().
 {
     infra::JsonObject object(R"({ "key": "\"\\\n\t\r\b\f\u0020" })");
TEST() [12/28]
TEST (JsonObjectTest , JsonString_corner_case_escaping)
Definition at line 534 of file TestJson.cpp.
References EXPECT_EQ(), infra::JsonObject::GetString(), and GetString().
 {
     EXPECT_EQ("\1g", infra::JsonObject(R"({ "key": "\u1g" })").GetString("key"));
     infra::JsonObject object1(R"({ "key": "\k" })");
     EXPECT_EQ("k", object1.GetString("key"));
 }
TEST() [13/28]
TEST (JsonObjectTest , iterator_equality)
Definition at line 541 of file TestJson.cpp.
References EXPECT_EQ(), and GetString().
 {
     infra::JsonObject object(R"({ "key1": "bla", "key2": "bla", "key3": "bla3" })");
     EXPECT_EQ(object.GetString("key1"), object.GetString("key2"));
     EXPECT_NE(object.GetString("key1"), object.GetString("key3"));
 }
TEST() [14/28]
TEST (JsonArrayIteratorTest , empty_array_iterator_compares_equal_to_end)
Definition at line 549 of file TestJson.cpp.
References infra::JsonArray::begin(), infra::JsonArray::end(), and EXPECT_EQ().
 {
     infra::JsonArray jsonArray(R"([ ])");
     infra::JsonArrayIterator iterator(jsonArray.begin());
     infra::JsonArrayIterator endIterator(jsonArray.end());
     EXPECT_EQ(endIterator, iterator);
 }
TEST() [15/28]
TEST (JsonArrayIteratorTest , nonempty_array_iterator_does_not_compare_equal_to_end)
Definition at line 558 of file TestJson.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
 {
     infra::JsonArray jsonArray(R"([ "key" : "value" ])");
     infra::JsonArrayIterator iterator(jsonArray.begin());
     infra::JsonArrayIterator endIterator(jsonArray.end());
     EXPECT_NE(endIterator, iterator);
 }
TEST() [16/28]
TEST (JsonObjectIteratorTest , get_value_from_iterator)
Definition at line 567 of file TestJson.cpp.
References infra::JsonArray::begin(), and EXPECT_EQ().
 {
     infra::JsonArray jsonArray(R"([ "value" ])");
     infra::JsonArrayIterator iterator(jsonArray.begin());
     EXPECT_EQ("value", iterator->Get<infra::JsonString>());
 }
TEST() [17/28]
TEST (JsonObjectIteratorTest , get_multiple_values_from_iterator)
Definition at line 575 of file TestJson.cpp.
References infra::JsonArray::begin(), and EXPECT_EQ().
 {
     infra::JsonArray jsonArray(R"([ "value", true, { "subobject" } ])");
     infra::JsonArrayIterator iterator(jsonArray.begin());
     EXPECT_EQ("value", (iterator++)->Get<infra::JsonString>());
     EXPECT_EQ(true, (iterator++)->Get<bool>());
     EXPECT_EQ(R"({ "subobject" })", (*iterator++).Get<infra::JsonObject>().ObjectString());
 }
TEST() [18/28]
TEST (JsonArrayTest , empty_array_construction)
Definition at line 585 of file TestJson.cpp.
References infra::JsonArray::begin(), infra::JsonArray::end(), and EXPECT_EQ().
 {
     infra::JsonArray jsonArray(R"([ ])");
     EXPECT_EQ(jsonArray.end(), jsonArray.begin());
 }
TEST() [19/28]
TEST (JsonArrayTest , nonempty_array_construction)
Definition at line 592 of file TestJson.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
 {
     infra::JsonArray jsonArray(R"([ "value" ])");
     EXPECT_NE(jsonArray.end(), jsonArray.begin());
 }
TEST() [20/28]
TEST (JsonArrayTest , iterate_over_array)
Definition at line 599 of file TestJson.cpp.
References EXPECT_EQ(), and value.
 {
     infra::JsonArray jsonArray(R"([ "value" ])");
     for (auto value : jsonArray)
         EXPECT_EQ("value", value.Get<infra::JsonString>());
     EXPECT_EQ(1, std::distance(jsonArray.begin(), jsonArray.end()));
 }
TEST() [21/28]
TEST (JsonArrayTest , iterate_over_strings_in_array)
Definition at line 609 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonStringArray().
 {
     infra::JsonArray jsonArray(R"([ "value" ])");
     for (auto string : JsonStringArray(jsonArray))
         EXPECT_EQ("value", string);
     EXPECT_EQ(1, std::distance(JsonStringArray(jsonArray).first, JsonStringArray(jsonArray).second));
 }
TEST() [22/28]
TEST (JsonArrayTest , iterate_over_strings_in_array_with_other_values_sets_error)
Definition at line 619 of file TestJson.cpp.
References infra::JsonArray::Error(), EXPECT_TRUE(), and infra::JsonStringArray().
 {
     infra::JsonArray jsonArray(R"([ true, "value" ])");
     for (auto string : JsonStringArray(jsonArray))
     {}
     EXPECT_TRUE(jsonArray.Error());
 }
TEST() [23/28]
TEST (JsonArrayTest , iterate_over_booleans_in_array)
Definition at line 629 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonBooleanArray().
 {
     infra::JsonArray jsonArray(R"([ true ])");
     for (auto boolean : JsonBooleanArray(jsonArray))
         EXPECT_EQ(true, boolean);
     EXPECT_EQ(1, std::distance(JsonBooleanArray(jsonArray).first, JsonBooleanArray(jsonArray).second));
 }
TEST() [24/28]
TEST (JsonArrayTest , iterate_over_integers_in_array)
Definition at line 639 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonIntegerArray().
 {
     infra::JsonArray jsonArray(R"([ 5 ])");
     for (auto integer : JsonIntegerArray(jsonArray))
         EXPECT_EQ(5, integer);
     EXPECT_EQ(1, std::distance(JsonIntegerArray(jsonArray).first, JsonIntegerArray(jsonArray).second));
 }
TEST() [25/28]
TEST (JsonArrayTest , iterate_over_objects_in_array)
Definition at line 649 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonObjectArray().
 {
     infra::JsonArray jsonArray(R"([ { "name": "Richard" } ])");
     for (auto object : JsonObjectArray(jsonArray))
         EXPECT_EQ(R"({ "name": "Richard" })", object.ObjectString());
     EXPECT_EQ(1, std::distance(JsonObjectArray(jsonArray).first, JsonObjectArray(jsonArray).second));
 }
TEST() [26/28]
TEST (JsonArrayTest , iterate_over_arrays_in_array)
Definition at line 659 of file TestJson.cpp.
References EXPECT_EQ(), and infra::JsonArrayArray().
 {
     infra::JsonArray jsonArray(R"([ [ true ] ])");
     for (auto array : JsonArrayArray(jsonArray))
         EXPECT_EQ("[ true ]", array.ObjectString());
     EXPECT_EQ(1, std::distance(JsonArrayArray(jsonArray).first, JsonArrayArray(jsonArray).second));
 }
TEST() [27/28]
TEST (JsonArrayTest , incorrect_array_sets_error)
Definition at line 669 of file TestJson.cpp.
References EXPECT_TRUE(), and value.
 {
     std::vector<infra::BoundedConstString> errorArrays = { R"(~)", R"([~])", R"([ "value" ~])", R"([ "value" , ~])", R"([ { ])" };
     for (auto errorArray : errorArrays)
     {
         infra::JsonArray jsonArray(errorArray);
         for (auto value : jsonArray)
         {}
         EXPECT_TRUE(jsonArray.Error());
     }
 }
TEST() [28/28]
TEST (JsonArrayTest , nested_float_is_accepted)
Definition at line 684 of file TestJson.cpp.
References EXPECT_FALSE().
 {
     infra::JsonArray jsonArray(R"([ { 1.5 } ])");
     for (auto x : jsonArray)
     {}
     EXPECT_FALSE(jsonArray.Error());
 }
Variable Documentation
data
infra::BoundedString::WithStorage<4> data
Definition at line 497 of file TestJson.cpp.
Referenced by infra::QueueForOneReaderOneIrqWriter< uint8_t >::AddFromInterrupt(), services::HttpRequestParserImpl::CheckContentsLength(), infra::Variant< services::IPv4Address, services::IPv6Address >::ConstructInEmptyVariant(), FlashSpiTest::CreateInstructionAddressAndData(), SntpClientTest::DataReceived(), HttpServerTest::ExpectPageServerRequest(), services::HttpRequestParserImpl::FindHeadersAndBody(), services::ConnectionMbedTls::GenerateRandomData(), infra::Variant< services::IPv4Address, services::IPv6Address >::Get(), SntpClientTest::HeaderReceived(), services::HttpRequestParserImpl::HttpRequestParserImpl(), infra::MakeRange(), services::Terminal::Print(), infra::CyclicBuffer< uint8_t >::Push(), hal::FileSystemWin::ReadBinaryFile(), hal::I2cMasterRegisterAccess::ReadRegister(), hal::SynchronousSerialCommunicationMock::ReceiveData(), hal::I2cMasterRegisterAccessMock::ReceiveData(), hal::I2cMasterMock::ReceiveData(), hal::QuadSpiStub::ReceiveData(), services::I2cMultipleAccessMaster::ReceiveData(), hal::SynchronousSpi::ReceiveData(), hal::I2cMasterMockWithoutAutomaticDone::ReceiveData(), services::I2cMultipleAccess::ReceiveData(), hal::SpiMaster::ReceiveData(), services::I2cMultipleAccess::ReceiveDataOnClaimed(), ConfigurationBlobTest::RecoverFromFlash(), hal::SynchronousSerialCommunicationMock::SendData(), hal::I2cMasterRegisterAccessMock::SendData(), hal::I2cMasterMock::SendData(), hal::SerialCommunicationStub::SendData(), hal::QuadSpiStub::SendData(), hal::SerialCommunicationMock::SendData(), services::I2cMultipleAccessMaster::SendData(), hal::SynchronousSpi::SendData(), hal::I2cMasterMockWithoutAutomaticDone::SendData(), hal::SerialCommunicationMockWithAssert::SendData(), services::I2cMultipleAccess::SendData(), hal::SpiMaster::SendData(), services::ConnectionObserverStub::SendData(), services::I2cMultipleAccess::SendDataOnClaimed(), services::ConnectionObserverStub::SendStreamAvailable(), services::ConnectionSerial::SendStreamFilled(), services::ConnectionStub::SimulateDataReceived(), services::ConnectionMbedTls::StaticGenerateRandomData(), TEST(), TEST_F(), services::WebSocketFrameHeader::WebSocketFrameHeader(), and hal::I2cMasterRegisterAccess::WriteRegister().