EMil: services::HttpHeader Class Reference
services::HttpHeader Class Reference
#include <Http.hpp>
Public Member Functions
HttpHeader (infra::BoundedConstString field, infra::BoundedConstString value)
std::size_t Size () const
infra::BoundedConstString Field () const
infra::BoundedConstString Value () const
bool operator== (const HttpHeader &rhs) const
Private Attributes
infra::BoundedConstString field
infra::BoundedConstString value
Detailed Description
Definition at line 67 of file Http.hpp.
Constructor & Destructor Documentation
HttpHeader()
services::HttpHeader::HttpHeader (infra::BoundedConstString field, infra::BoundedConstString value)
Definition at line 21 of file Http.cpp.
         : field(field)
         , value(value)
     {}
Member Function Documentation
Field()
infra::BoundedConstString services::HttpHeader::Field () const
Definition at line 31 of file Http.cpp.
References field.
Referenced by services::HttpClientJson::HeaderAvailable(), and infra::operator<<().
     {
         return field;
     }
operator==()
bool services::HttpHeader::operator== (const HttpHeader & rhs) const
Definition at line 41 of file Http.cpp.
References field, and value.
     {
         return rhs.field == field &&
             rhs.value == value;
     }
Size()
std::size_t services::HttpHeader::Size () const
Definition at line 26 of file Http.cpp.
References field, infra::BoundedStringBase< T >::size(), and value.
Referenced by services::HttpRequestFormatter::HeadersSize().
     {
         return field.size() + value.size() + std::char_traits<char>::length(separator);
     }
Value()
infra::BoundedConstString services::HttpHeader::Value () const
Definition at line 36 of file Http.cpp.
References value.
Referenced by services::HttpClientJson::HeaderAvailable(), and infra::operator<<().
     {
         return value;
     }
Member Data Documentation
field
infra::BoundedConstString services::HttpHeader::field private
Definition at line 79 of file Http.hpp.
Referenced by Field(), operator==(), and Size().
value
infra::BoundedConstString services::HttpHeader::value private
Definition at line 80 of file Http.hpp.
Referenced by operator==(), Size(), and Value().
The documentation for this class was generated from the following files:
Http.hpp
Http.cpp