EMil: infra Namespace Reference
infra Namespace Reference
Namespaces
detail
JsonToken
Classes
class AccessedBySharedPtr
class Allocator
class Allocator< T, void(ConstructionArgs...)>
class AllocatorBase
class AllocatorFixedSpace
class AllocatorFixedSpace< T, NumberOfElements, void(ConstructionArgs...)>
class AllocatorHeap
class AllocatorHeap< T, void(ConstructionArgs...)>
class AsAsciiHelper
class AsBase64Helper
class AsHexHelper
class AsMacAddressHelper
class Asn1ContainerFormatter
class Asn1Formatter
class Asn1Sequence
class Asn1SequenceIterator
class Asn1Value
struct AtIndex
class AutoResetFunction
class AutoResetFunction< Result(Args...), ExtraSize >
struct BaseUnit
class BigEndian
struct Bin
class BoundedDeque
class BoundedDequeInputStream
class BoundedDequeInputStreamReader
class BoundedForwardList
class BoundedList
class BoundedPriorityQueue
class BoundedStringBase
class BoundedVector
struct Buffers
class ByteInputStream
class ByteInputStreamReader
class ByteOutputStream
class ByteOutputStreamWriter
struct CanCall
struct CanCall< ResultType(Args...)>
struct CanCallHelper
class ClaimableResource
class CountingDataInputStream
class CountingStreamReader
class CountingTextInputStream
class CrcCcittCalculator
class Creator
class Creator< T, U, void(ConstructionArgs...)>
class Creator< void, U, void(ConstructionArgs...)>
class CreatorBase
class CreatorBase< T, void(ConstructionArgs...)>
class CreatorBase< void, void(ConstructionArgs...)>
class CreatorExternal
class CreatorExternal< T, void(ConstructionArgs...)>
class CyclicBuffer
struct Data
class DataInputStream
class DataOutputStream
class Deallocator
class DelayedProxyCreator
class DelayedProxyCreator< T, void(ConstructionArgs...)>
class DerivedTimerService
struct enable_if<(Unit1First::identifier< Unit2First::identifier)>::type >
class EnableSharedFromThis
struct Endl
class Equals
class EventDispatcherConnector
class EventDispatcherWithWeakPtrConnector
class EventDispatcherWithWeakPtrWorker
class EventDispatcherWorker
class EventDispatcherWorkerImpl
class Execute
class ExecuteOnDestruction
struct ExistsInList
struct ExistsInList< List< Element, Tail... >, Element >
struct ExistsInList< List< Head, Tail... >, Element >
struct ExistsInList< List<>, Element >
struct ExistsInTypeList
struct ExistsInTypeList< U >
struct ExistsInTypeList< U, Front, Tail... >
struct ExistsInTypeList< U, U, Tail... >
struct FixedPoint
class FromBase64Helper
struct Front
class Function
class Function< Result(Args...), ExtraSize >
struct Hex
struct Identity
struct IndexInTypeList
struct IndexInTypeList< U, Front, Tail... >
struct IndexInTypeList< U, U, Tail... >
struct InPlace
struct InPlaceType
class InputStream
class InterfaceConnector
class IntrusiveBinarySearchTree
class IntrusiveForwardList
class IntrusiveList
class IntrusivePriorityQueue
class IntrusiveSet
struct InverseEachUnit
struct InverseEachUnit< List< Units... > >
class IoOutputStream
class IoOutputStreamWriter
class JsonArray
class JsonArrayFormatter
class JsonArrayIterator
class JsonArrayVisitor
class JsonInputStream
class JsonInputStreamReader
class JsonIterator
struct JsonKeyValue
class JsonObject
class JsonObjectFormatter
class JsonObjectIterator
class JsonObjectVisitor
class JsonStreamingObjectParser
class JsonString
class JsonStringIterator
class JsonStringStream
class JsonSubArrayParser
class JsonSubObjectParser
class JsonSubParser
class JsonTokenizer
class JsonValueArrayIterator
class JsonVisitor
class LessThan
class LimitedDataInputStream
class LimitedDataOutputStream
class LimitedStreamReader
class LimitedStreamWriter
class LimitedTextInputStream
class LimitedTextOutputStream
struct List
struct ListJoin
struct ListJoin< List< ListA... >, List< ListB... > >
struct ListPushBack
struct ListPushBack< List< ListElements... >, Elements... >
struct ListPushFront
struct ListPushFront< Element, List< ListElements... > >
class LowPowerEventDispatcherWorker
class LowPowerStrategy
class MainClockReference
struct MakePolymorphicVariantOver
struct MakePolymorphicVariantOver< Base, List< T... > >
struct MakeVariantOver
struct MakeVariantOver< List< T... > >
struct Max
struct MaxAlignmentOfTypes
struct MaxAlignmentOfTypes< Front >
struct MaxAlignmentOfTypes< Front, Tail... >
struct MaxAlignmentType
struct MaxAlignmentType< Front >
struct MaxAlignmentType< Front, Tail... >
struct MaxSizeOfTypes
struct MaxSizeOfTypes< Front >
struct MaxSizeOfTypes< Front, Tail... >
class MemoryRange
struct Min
struct MultiplyTwoUnitLists
struct MultiplyTwoUnitLists< List< Unit1First, Unit1Others... >, List< Unit2First, Unit2Others... >, typename std::enable_if<(Unit1First::identifier==Unit2First::identifier &&Unit1First::dimension+Unit2First::dimension !=0)>::type >
struct MultiplyTwoUnitLists< List< Unit1First, Unit1Others... >, List< Unit2First, Unit2Others... >, typename std::enable_if<(Unit1First::identifier==Unit2First::identifier &&Unit1First::dimension+Unit2First::dimension==0)>::type >
struct MultiplyTwoUnitLists< List< Units... >, List<> >
struct MultiplyTwoUnitLists< List<>, List< Units... > >
struct MultiplyTwoUnitLists< List<>, List<> >
struct MultiplyUnits
struct MultiplyUnits< Unit >
struct MultiplyUnits< Unit1, Unit2, OtherUnits... >
struct NoFail
struct None
class NotifyingSharedOptional
struct NullType
class Observer
class Optional
class OptionalForPolymorphicObjects
class OutputStream
class OverwriteDataStream
class OverwriteStreamWriter
class OverwriteTextStream
class PolymorphicVariant
struct PrintParameterNames
struct PrintParameterNames< Arg >
struct PrintParameterNames< Arg, Arg2, Args... >
struct PrintParameterNames<>
class ProtoFormatter
class ProtoLengthDelimited
class ProtoLengthDelimitedFormatter
class ProtoParser
class ProxyCreator
class ProxyCreator< CreatorBase< T, void(ConstructionArgs...)> & >
class ProxyCreator< T, void(ConstructionArgs...)>
class ProxyCreator< void, void(ConstructionArgs...)>
class Quantity
class QueueForOneReaderOneIrqWriter
class ReferenceCountedSingleton
class ReservedProxy
class SavedMarkerDataStream
class SavedMarkerStreamWriter
class SavedMarkerTextStream
class ScalableDerivedTimerService
struct Scaled
struct ScaleHelper
class Sequencer
class SharedObjectAllocator
class SharedObjectAllocator< T, void(ConstructionArgs...)>
class SharedObjectAllocatorFixedSize
class SharedObjectAllocatorFixedSize< T, void(ConstructionArgs...)>
class SharedObjectAllocatorHeap
class SharedObjectAllocatorHeap< T, void(ConstructionArgs...)>
class SharedObjectDeleter
class SharedOptional
class SharedPtr
class SingleObserver
struct SoftFail
struct StateInitializing
struct StateRunning
struct StaticGCD
struct StaticGCD< 0, Value2 >
struct StaticGCD< Value1, 0 >
struct StaticRationalBase
class StaticStorage
class StaticStorageForPolymorphicObjects
class StaticVisitor
class StdStringInputStream
class StdStringInputStreamReader
class StdStringOutputStream
class StdStringOutputStreamWriter
class StdVectorInputStream
class StdVectorInputStreamReader
class StreamErrorPolicy
class StreamReader
class StreamReaderWithRewinding
class StreamWriter
class StreamWriterDummy
class StreamWriterPrintF
class StringInputStream
class StringInputStreamReader
class StringOutputStream
class StringOutputStreamWriter
class Subject
class Subject< ObserverType_, void >
class SystemState
class SystemStateBase
class SystemStateManager
class SystemStateParticipant
struct Text
class TextInputStream
class TextOutputStream
class TickOnInterruptTimerService
class Timer
class TimerAlternating
class TimerEvolving
class TimerLimitedRepeating
class TimerLimitedRepeatingWithClosingAction
class TimerRepeating
class TimerService
class TimerServiceManager
class TimerSingleShot
class Tokenizer
struct TriggerImmediately
struct TupleInvokeHelper
struct TupleInvokeHelper< 0, ResultType, Args... >
struct TupleInvokeHelper< 1, ResultType, Args... >
struct TupleInvokeHelper< 2, ResultType, Args... >
struct TupleInvokeHelper< 3, ResultType, Args... >
struct TypeAtIndex
struct TypeAtIndex< 0, Front, Tail... >
struct TypeAtIndex< Index, Front, Tail... >
struct Unit
struct UnitBase
struct UnitListSame
struct UnitListSame< List< UnitListElements1... >, List< UnitListElements1... > >
struct UnitSame
struct Unscaled
class Variant
class WeakPtr
struct Width
class WithStorage
class XmlFormatter
class XmlTagFormatter
Typedefs
using EventDispatcher = EventDispatcherConnector< EventDispatcherWorkerImpl >
using EventDispatcherWithWeakPtr = EventDispatcherWithWeakPtrConnector< EventDispatcherWithWeakPtrWorker >
using LowPowerEventDispatcher = infra::EventDispatcherWithWeakPtrConnector< LowPowerEventDispatcherWorker >
using JsonValue = infra::Variant< bool, int32_t, JsonString, JsonObject, JsonArray >
using TimePoint = std::chrono::system_clock::time_point
using Duration = std::chrono::system_clock::duration
template<class T >
using UniquePtr = std::unique_ptr< T, Deallocator >
using BoundedString = BoundedStringBase< char >
using BoundedConstString = BoundedStringBase< const char >
typedef MemoryRange< uint8_t > ByteRange
typedef MemoryRange< const uint8_t > ConstByteRange
typedef CyclicBuffer< uint8_t > CyclicByteBuffer
template<class Base , class... Derived>
using StaticStorageForInheritanceTree = StaticStorageForPolymorphicObjects< Base, MaxSizeOfTypes< Derived... >::value - sizeof(Base), typename MaxAlignmentType< Derived... >::Type >
template<uint64_t N, uint64_t D>
using StaticRational = StaticRationalBase< N/StaticGCD< N, D >::value, D/StaticGCD< N, D >::value >
typedef BaseUnit< 1 > Meter
typedef Meter::Scale< StaticRational< 1, 1000 > > MilliMeter
typedef BaseUnit< 2 > Second
typedef Second::Scale< StaticRational< 60, 1 > > Minute
typedef Minute::Scale< StaticRational< 60, 1 > > Hour
typedef Hour::Scale< StaticRational< 24, 1 > > Day
typedef Second::Scale< StaticRational< 1, 1000 > > MilliSecond
typedef MilliSecond::Scale< StaticRational< 1, 1000 > > MicroSecond
typedef Second::Div< Meter >::Inverse MeterPerSecond
typedef BaseUnit< 3 > Ohm
typedef Ohm::Scale< StaticRational< 1000, 1 > > KiloOhm
typedef BaseUnit< 4 > Ampere
typedef Ampere::Scale< StaticRational< 1, 1000 > > MilliAmpere
typedef MilliAmpere::Scale< StaticRational< 1, 1000 > > MicroAmpere
typedef Ohm::Mul< Ampere > Volt
typedef Volt::Scale< StaticRational< 1, 1000 > > MilliVolt
typedef MilliVolt::Scale< StaticRational< 1, 1000 > > MicroVolt
typedef Ampere::Mul< Volt > Watt
typedef Watt::Mul< Second > Joule
typedef Joule::Scale< StaticRational< 3600, 1000 > > KiloWattHour
typedef BaseUnit< 4 > Celsius
Functions
AsMacAddressHelper AsMacAddress (hal::MacAddress macAddress)
TextOutputStream & operator<< (TextOutputStream &stream, const AsMacAddressHelper &asMacAddressHelper)
TextOutputStream & operator<< (TextOutputStream &&stream, const AsMacAddressHelper &asMacAddressHelper)
infra::TextInputStream & operator>> (infra::TextInputStream &stream, FromBase64Helper fromHexHelper)
infra::TextInputStream & operator>> (infra::TextInputStream &&stream, FromBase64Helper fromBase64Helper)
FromBase64Helper FromBase64 (infra::ByteRange data)
TextOutputStream & operator<< (TextOutputStream &stream, const AsAsciiHelper &asAsciiHelper)
TextOutputStream & operator<< (TextOutputStream &stream, const AsHexHelper &asHexHelper)
TextOutputStream & operator<< (TextOutputStream &stream, const AsBase64Helper &asHexHelper)
TextOutputStream & operator<< (TextOutputStream &&stream, const AsBase64Helper &asBase64Helper)
AsAsciiHelper AsAscii (ConstByteRange data)
AsHexHelper AsHex (ConstByteRange data)
AsBase64Helper AsBase64 (ConstByteRange data)
bool operator== (infra::BoundedConstString x, JsonString y)
bool operator!= (infra::BoundedConstString x, JsonString y)
bool operator== (const char *x, JsonString y)
bool operator!= (const char *x, JsonString y)
infra::TextOutputStream & operator<< (infra::TextOutputStream &stream, JsonString value)
infra::detail::DoublePair< JsonValueArrayIterator< bool > > JsonBooleanArray (JsonArray &array)
infra::detail::DoublePair< JsonValueArrayIterator< int32_t > > JsonIntegerArray (JsonArray &array)
infra::detail::DoublePair< JsonValueArrayIterator< JsonString > > JsonStringArray (JsonArray &array)
infra::detail::DoublePair< JsonValueArrayIterator< JsonObject > > JsonObjectArray (JsonArray &array)
infra::detail::DoublePair< JsonValueArrayIterator< JsonArray > > JsonArrayArray (JsonArray &array)
void CopyToken (infra::JsonToken::Token token, infra::TextOutputStream &stream)
void CleanJsonContents (infra::BoundedString &contents)
std::size_t JsonEscapedStringSize (infra::BoundedConstString string)
TextOutputStream & operator<< (TextOutputStream &stream, infra::TimePoint time)
TextOutputStream & operator<< (TextOutputStream &&stream, infra::TimePoint time)
TimePoint Now (uint32_t timerServiceId)
template<class T >
UniquePtr< T > MakeUnique (T *object, AllocatorBase &allocator)
template<std::size_t ExtraSize, class Result , class... Args>
void swap (AutoResetFunction< Result(Args...), ExtraSize > &x, AutoResetFunction< Result(Args...), ExtraSize > &y)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator== (const AutoResetFunction< Result(Args...), ExtraSize > &f, std::nullptr_t)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator== (std::nullptr_t, const AutoResetFunction< Result(Args...), ExtraSize > &f)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator!= (const AutoResetFunction< Result(Args...), ExtraSize > &f, std::nullptr_t)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator!= (std::nullptr_t, const AutoResetFunction< Result(Args...), ExtraSize > &f)
template<class T >
constexpr std::remove_cv< T >::type Bit (uint8_t index)
template<class T >
void SetBit (T &dataRegister, uint8_t index)
template<class T >
void ClearBit (T &dataRegister, uint8_t index)
template<class T >
void ReplaceBit (T &dataRegister, bool newValue, uint8_t position)
template<class T >
void ReplaceBit (T &dataRegister, typename std::remove_cv< T >::type newValue, uint8_t position)
template<class T >
void ReplaceBits (T &dataRegister, uint8_t size, typename std::remove_cv< T >::type newValue, uint8_t position)
template<class T >
bool IsBitSet (T dataRegister, uint8_t index)
template<class T >
T GetBits (T dataRegister, uint8_t size, uint8_t position)
template<class T >
void swap (BoundedDeque< T > &x, BoundedDeque< T > &y)
template<class T >
void swap (BoundedForwardList< T > &x, BoundedForwardList< T > &y)
template<class T >
void swap (BoundedList< T > &x, BoundedList< T > &y)
template<class RandomAccessIterator , class Compare >
void erase_heap (RandomAccessIterator begin, RandomAccessIterator end, RandomAccessIterator position, Compare compare)
BoundedString ByteRangeAsString (infra::MemoryRange< uint8_t > range)
template<class T , class U >
bool operator== (const BoundedStringBase< T > &lhs, const BoundedStringBase< U > &rhs)
template<class T , class U >
bool operator!= (const BoundedStringBase< T > &lhs, const BoundedStringBase< U > &rhs)
template<class T , class U >
bool operator< (const BoundedStringBase< T > &lhs, const BoundedStringBase< U > &rhs)
template<class T , class U >
bool operator<= (const BoundedStringBase< T > &lhs, const BoundedStringBase< U > &rhs)
template<class T , class U >
bool operator> (const BoundedStringBase< T > &lhs, const BoundedStringBase< U > &rhs)
template<class T , class U >
bool operator>= (const BoundedStringBase< T > &lhs, const BoundedStringBase< U > &rhs)
template<class T >
bool operator== (const char *lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator== (const BoundedStringBase< T > &lhs, const char *rhs)
template<class T >
bool operator== (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator== (const BoundedStringBase< T > &lhs, const std::string &rhs)
template<class T >
bool operator!= (const char *lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator!= (const BoundedStringBase< T > &lhs, const char *rhs)
template<class T >
bool operator!= (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator!= (const BoundedStringBase< T > &lhs, const std::string &rhs)
template<class T >
bool operator< (const char *lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator< (const BoundedStringBase< T > &lhs, const char *rhs)
template<class T >
bool operator< (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator< (const BoundedStringBase< T > &lhs, const std::string &rhs)
template<class T >
bool operator<= (const char *lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator<= (const BoundedStringBase< T > &lhs, const char *rhs)
template<class T >
bool operator<= (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator<= (const BoundedStringBase< T > &lhs, const std::string &rhs)
template<class T >
bool operator> (const char *lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator> (const BoundedStringBase< T > &lhs, const char *rhs)
template<class T >
bool operator> (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator> (const BoundedStringBase< T > &lhs, const std::string &rhs)
template<class T >
bool operator>= (const char *lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator>= (const BoundedStringBase< T > &lhs, const char *rhs)
template<class T >
bool operator>= (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
bool operator>= (const BoundedStringBase< T > &lhs, const std::string &rhs)
template<class T >
std::string operator+ (const std::string &lhs, const BoundedStringBase< T > &rhs)
template<class T >
void swap (BoundedStringBase< T > &lhs, BoundedStringBase< T > &rhs)
template<class T >
BoundedStringBase< T > TrimLeft (BoundedStringBase< T > string)
template<class T >
MemoryRange< T > MakeRange (infra::BoundedStringBase< T > &container)
template<class T >
MemoryRange< const T > MakeRange (const infra::BoundedStringBase< T > &container)
template<class T , class U >
MemoryRange< T > StringAsMemoryRange (const infra::BoundedStringBase< U > &string)
template<class T , class U >
MemoryRange< const T > StringAsMemoryRange (const infra::BoundedStringBase< const U > &string)
template<class U >
MemoryRange< uint8_t > StringAsByteRange (const infra::BoundedStringBase< U > &string)
template<class U >
MemoryRange< const uint8_t > StringAsByteRange (const infra::BoundedStringBase< const U > &string)
template<class T >
void PrintTo (const BoundedStringBase< T > &string, std::ostream *os)
template<class T , std::size_t Max>
void PrintTo (const typename BoundedStringBase< T >::template WithStorage< Max > &string, std::ostream *os)
template<class T >
void swap (BoundedVector< T > &x, BoundedVector< T > &y)
template<class T >
MemoryRange< T > MakeRange (infra::BoundedVector< T > &container)
template<class T >
MemoryRange< const T > MakeRange (const infra::BoundedVector< T > &container)
template<class U >
ByteRange ReinterpretCastByteRange (MemoryRange< U > memoryRange)
template<class U >
ConstByteRange ReinterpretCastByteRange (MemoryRange< const U > memoryRange)
ByteRange ConstCastByteRange (ConstByteRange byteRange)
template<class T >
ByteRange MakeByteRange (T &v)
template<class T >
ConstByteRange MakeConstByteRange (T &v)
template<class T >
ConstByteRange MakeByteRange (const T &v)
ConstByteRange MakeStringByteRange (const char *string)
ConstByteRange MakeStringByteRange (const std::string &string)
void PrintTo (ByteRange range, std::ostream *os)
void PrintTo (ConstByteRange range, std::ostream *os)
template<class T >
T SwapEndian (T value)
template<class T , T Factor>
FixedPoint< T, Factor > operator+ (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
FixedPoint< T, Factor > operator- (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
FixedPoint< T, Factor > operator* (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
FixedPoint< T, Factor > operator/ (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
FixedPoint< T, Factor > operator* (FixedPoint< T, Factor > x, T y)
template<class T , T Factor>
FixedPoint< T, Factor > operator* (T x, FixedPoint< T, Factor > y)
template<class T , T Factor>
FixedPoint< T, Factor > operator/ (FixedPoint< T, Factor > x, T y)
template<class T , T Factor>
FixedPoint< T, Factor > operator/ (T x, FixedPoint< T, Factor > y)
template<class T , T Factor>
bool operator== (const FixedPoint< T, Factor > &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator!= (const FixedPoint< T, Factor > &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator< (const FixedPoint< T, Factor > &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator> (const FixedPoint< T, Factor > &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator<= (const FixedPoint< T, Factor > &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator>= (const FixedPoint< T, Factor > &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator== (const FixedPoint< T, Factor > &x, const T &y)
template<class T , T Factor>
bool operator!= (const FixedPoint< T, Factor > &x, const T &y)
template<class T , T Factor>
bool operator< (const FixedPoint< T, Factor > &x, const T &y)
template<class T , T Factor>
bool operator> (const FixedPoint< T, Factor > &x, const T &y)
template<class T , T Factor>
bool operator<= (const FixedPoint< T, Factor > &x, const T &y)
template<class T , T Factor>
bool operator>= (const FixedPoint< T, Factor > &x, const T &y)
template<class T , T Factor>
bool operator== (const T &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator!= (const T &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator< (const T &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator> (const T &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator<= (const T &x, const FixedPoint< T, Factor > &y)
template<class T , T Factor>
bool operator>= (const T &x, const FixedPoint< T, Factor > &y)
template<std::size_t ExtraSize, class Result , class... Args>
void swap (Function< Result(Args...), ExtraSize > &x, Function< Result(Args...), ExtraSize > &y)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator== (const Function< Result(Args...), ExtraSize > &f, std::nullptr_t)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator== (std::nullptr_t, const Function< Result(Args...), ExtraSize > &f)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator!= (const Function< Result(Args...), ExtraSize > &f, std::nullptr_t)
template<std::size_t ExtraSize, class Result , class... Args>
bool operator!= (std::nullptr_t, const Function< Result(Args...), ExtraSize > &f)
template<class R , class... Args>
void PrintTo (Function< R(Args...)>, std::ostream *os)
template<class T , class Compare >
void swap (IntrusiveBinarySearchTree< T, Compare > &node, IntrusiveBinarySearchTree< T, Compare > &uncle)
template<class T >
void swap (IntrusiveForwardList< T > &x, IntrusiveForwardList< T > &y)
template<class T >
void swap (IntrusiveList< T > &x, IntrusiveList< T > &y)
template<class T , class Compare >
void swap (IntrusiveSet< T, Compare > &node, IntrusiveSet< T, Compare > &uncle)
template<class T >
MemoryRange< T > MakeRange (T *b, T *e)
template<class T , std::size_t N>
MemoryRange< T > MakeRange (std::array< T, N > &container)
template<class T , std::size_t N>
MemoryRange< const T > MakeRange (const std::array< T, N > &container)
template<class T >
std::vector< typename std::remove_const< T >::type > MakeVector (MemoryRange< T > range)
template<class T >
MemoryRange< T > MakeRange (std::vector< T > &range)
template<class T >
MemoryRange< const T > MakeRange (const std::vector< T > &range)
template<class T >
MemoryRange< const T > MakeConst (infra::MemoryRange< T > range)
template<class T , class U >
MemoryRange< T > ReinterpretCastMemoryRange (MemoryRange< U > memoryRange)
template<class T >
MemoryRange< T > ConstCastMemoryRange (MemoryRange< const T > memoryRange)
template<class T >
MemoryRange< T > VolatileCastMemoryRange (MemoryRange< volatile T > memoryRange)
template<class T >
void Copy (MemoryRange< const typename std::remove_const< T >::type > from, MemoryRange< T > to)
template<class T , class U >
bool ContentsEqual (MemoryRange< T > x, MemoryRange< U > y)
template<class T >
MemoryRange< T > IntersectingRange (MemoryRange< T > x, MemoryRange< T > y)
template<class T >
MemoryRange< T > Head (MemoryRange< T > range, std::size_t size)
template<class T >
MemoryRange< T > Tail (MemoryRange< T > range, std::size_t size)
template<class T >
MemoryRange< T > DiscardHead (MemoryRange< T > range, std::size_t size)
template<class T >
MemoryRange< T > DiscardTail (MemoryRange< T > range, std::size_t size)
template<class T , class U , std::size_t N>
bool operator== (MemoryRange< T > x, const std::array< U, N > &y)
template<class T , class U , std::size_t N>
bool operator== (const std::array< U, N > &x, MemoryRange< T > y)
template<class T , class U , std::size_t N>
bool operator!= (MemoryRange< T > x, const std::array< U, N > &y)
template<class T , class U , std::size_t N>
bool operator!= (const std::array< U, N > &x, MemoryRange< T > y)
template<class T , class U >
bool operator== (MemoryRange< T > x, const std::vector< U > &y)
template<class T , class U >
bool operator== (const std::vector< U > &x, MemoryRange< T > y)
template<class T , class U >
bool operator!= (MemoryRange< T > x, const std::vector< U > &y)
template<class T , class U >
bool operator!= (const std::vector< U > &x, MemoryRange< T > y)
template<class T , std::size_t N>
MemoryRange< T > MakeRange (T(&data)[N])
template<class T , std::size_t N>
MemoryRange< const T > MakeRange (const T(&data)[N])
void OptionalCoverageDummy ()
template<class T >
Optional< typename std::decay< T >::type > MakeOptional (T &&value)
template<class T , class F >
auto TransformOptional (const infra::Optional< T > &value, F transformation) -> infra::Optional< decltype(transformation(*value))>
template<class Range >
detail::DoublePair< typename Range::reverse_iterator > MakeReverseRange (Range &r)
template<class T >
SharedPtr< T > UnOwnedSharedPtr (T &object)
template<class T , class U >
SharedPtr< T > MakeContainedSharedObject (T &object, const SharedPtr< U > &container)
template<class T , class... Args>
SharedPtr< T > MakeSharedOnHeap (Args &&... args)
template<class U , class T >
SharedPtr< U > StaticPointerCast (const SharedPtr< T > &sharedPtr)
template<class U , class T >
SharedPtr< U > StaticPointerCast (SharedPtr< T > &&sharedPtr)
template<class T >
SharedPtr< typename std::remove_const< T >::type > ConstCast (const SharedPtr< T > &sharedPtr)
template<class T >
SharedPtr< typename std::remove_const< T >::type > ConstCast (SharedPtr< T > &&sharedPtr)
template<class T , class U >
SharedPtr< T > MakeContainedSharedObject (T &object, SharedPtr< U > &&container)
template<class UnitType , class StorageType >
Quantity< UnitType, StorageType > operator+ (Quantity< UnitType, StorageType > first, Quantity< UnitType, StorageType > second)
template<class UnitType , class StorageType >
Quantity< UnitType, StorageType > operator- (Quantity< UnitType, StorageType > first, Quantity< UnitType, StorageType > second)
template<class UnitType , class StorageType >
Quantity< UnitType, StorageType > operator* (Quantity< UnitType, StorageType > first, StorageType second)
template<class UnitType , class StorageType >
Quantity< UnitType, StorageType > operator* (StorageType first, Quantity< UnitType, StorageType > second)
template<class UnitType , class StorageType >
Quantity< typename UnitType::Inverse, StorageType > operator/ (StorageType value, Quantity< UnitType, StorageType > quantity)
template<class UnitType , class StorageType >
Quantity< UnitType, StorageType > operator/ (Quantity< UnitType, StorageType > quantity, StorageType value)
template<class Visitor , class Variant >
Visitor::ResultType ApplyVisitor (Visitor &visitor, Variant &variant)
template<class Visitor , class Variant >
Visitor::ResultType ApplyVisitor (Visitor &visitor, Variant &variant1, Variant &variant2)
template<class Visitor , class Variant >
Visitor::ResultType ApplySameTypeVisitor (Visitor &visitor, Variant &variant1, Variant &variant2)
infra::TextOutputStream & operator<< (infra::TextOutputStream &stream, const services::IPv4Address &address)
infra::TextOutputStream & operator<< (infra::TextOutputStream &stream, const services::IPv6Address &address)
infra::TextOutputStream & operator<< (infra::TextOutputStream &stream, const services::IPAddress &address)
TextOutputStream & operator<< (TextOutputStream &stream, const services::HttpHeader &header)
TextOutputStream & operator<< (TextOutputStream &stream, services::HttpVerb verb)
TextOutputStream & operator<< (TextOutputStream &stream, services::HttpStatusCode statusCode)
DataOutputStream & operator<< (DataOutputStream &stream, services::WebSocketOpCode opcode)
Variables
static const std::array< SystemStateBase, 2 > simpleStateSequence = { StateInitializing(), StateRunning() }
const SoftFail softFail
const NoFail noFail
const Text text
const Hex hex
const Bin bin
const Data data
const Endl endl
const Width resetWidth (0)
const TriggerImmediately triggerImmediately
const uint32_t systemTimerServiceId = 0
static const std::array< uint16_t, 256 > crcCcittTabe
const Scaled scaled
const Unscaled unscaled
const infra::Function< void()> emptyFunction = []() {}
const None none
const InPlace inPlace
const AtIndex atIndex
Typedef Documentation
Ampere
typedef BaseUnit<4> infra::Ampere
Definition at line 446 of file Unit.hpp.
BoundedConstString
using infra::BoundedConstString = typedef BoundedStringBase<const char>
Definition at line 19 of file BoundedString.hpp.
BoundedString
using infra::BoundedString = typedef BoundedStringBase<char>
Definition at line 18 of file BoundedString.hpp.
ByteRange
typedef MemoryRange<uint8_t> infra::ByteRange
Definition at line 13 of file ByteRange.hpp.
Celsius
typedef BaseUnit<4> infra::Celsius
Definition at line 456 of file Unit.hpp.
ConstByteRange
typedef MemoryRange<const uint8_t> infra::ConstByteRange
Definition at line 14 of file ByteRange.hpp.
CyclicByteBuffer
typedef CyclicBuffer<uint8_t> infra::CyclicByteBuffer
Definition at line 43 of file CyclicBuffer.hpp.
Day
typedef Hour::Scale<StaticRational<24, 1> > infra::Day
Definition at line 438 of file Unit.hpp.
Duration
using infra::Duration = typedef std::chrono::system_clock::duration
Definition at line 24 of file Timer.hpp.
EventDispatcher
using infra::EventDispatcher = typedef EventDispatcherConnector<EventDispatcherWorkerImpl>
Definition at line 71 of file EventDispatcher.hpp.
EventDispatcherWithWeakPtr
using infra::EventDispatcherWithWeakPtr = typedef EventDispatcherWithWeakPtrConnector<EventDispatcherWithWeakPtrWorker>
Definition at line 103 of file EventDispatcherWithWeakPtr.hpp.
Hour
typedef Minute::Scale<StaticRational<60, 1> > infra::Hour
Definition at line 437 of file Unit.hpp.
Joule
typedef Watt::Mul<Second> infra::Joule
Definition at line 453 of file Unit.hpp.
JsonValue
using infra::JsonValue = typedef infra::Variant<bool, int32_t, JsonString, JsonObject, JsonArray>
Definition at line 238 of file Json.hpp.
KiloOhm
typedef Ohm::Scale<StaticRational<1000, 1> > infra::KiloOhm
Definition at line 445 of file Unit.hpp.
KiloWattHour
typedef Joule::Scale<StaticRational<3600, 1000> > infra::KiloWattHour
Definition at line 454 of file Unit.hpp.
LowPowerEventDispatcher
using infra::LowPowerEventDispatcher = typedef infra::EventDispatcherWithWeakPtrConnector<LowPowerEventDispatcherWorker>
Definition at line 53 of file LowPowerEventDispatcher.hpp.
Meter
typedef BaseUnit<1> infra::Meter
Definition at line 432 of file Unit.hpp.
MeterPerSecond
typedef Second::Div<Meter>::Inverse infra::MeterPerSecond
Definition at line 442 of file Unit.hpp.
MicroAmpere
typedef MilliAmpere::Scale<StaticRational<1, 1000> > infra::MicroAmpere
Definition at line 448 of file Unit.hpp.
MicroSecond
typedef MilliSecond::Scale<StaticRational<1, 1000> > infra::MicroSecond
Definition at line 440 of file Unit.hpp.
MicroVolt
typedef MilliVolt::Scale<StaticRational<1, 1000> > infra::MicroVolt
Definition at line 451 of file Unit.hpp.
MilliAmpere
typedef Ampere::Scale<StaticRational<1, 1000> > infra::MilliAmpere
Definition at line 447 of file Unit.hpp.
MilliMeter
typedef Meter::Scale<StaticRational<1, 1000> > infra::MilliMeter
Definition at line 433 of file Unit.hpp.
MilliSecond
typedef Second::Scale<StaticRational<1, 1000> > infra::MilliSecond
Definition at line 439 of file Unit.hpp.
MilliVolt
typedef Volt::Scale<StaticRational<1, 1000> > infra::MilliVolt
Definition at line 450 of file Unit.hpp.
Minute
typedef Second::Scale<StaticRational<60, 1> > infra::Minute
Definition at line 436 of file Unit.hpp.
Ohm
typedef BaseUnit<3> infra::Ohm
Definition at line 444 of file Unit.hpp.
Second
typedef BaseUnit<2> infra::Second
Definition at line 435 of file Unit.hpp.
StaticRational
template<uint64_t N, uint64_t D> using infra::StaticRational = typedef StaticRationalBase<N / StaticGCD<N, D>::value, D / StaticGCD<N, D>::value>
Definition at line 46 of file Unit.hpp.
StaticStorageForInheritanceTree
template<class Base , class... Derived> using infra::StaticStorageForInheritanceTree = typedef StaticStorageForPolymorphicObjects<Base, MaxSizeOfTypes<Derived...>::value - sizeof(Base), typename MaxAlignmentType<Derived...>::Type>
Definition at line 74 of file StaticStorage.hpp.
TimePoint
using infra::TimePoint = typedef std::chrono::system_clock::time_point
Definition at line 23 of file Timer.hpp.
UniquePtr
template<class T > using infra::UniquePtr = typedef std::unique_ptr<T, Deallocator>
Definition at line 33 of file Allocator.hpp.
Volt
typedef Ohm::Mul<Ampere> infra::Volt
Definition at line 449 of file Unit.hpp.
Watt
typedef Ampere::Mul<Volt> infra::Watt
Definition at line 452 of file Unit.hpp.
Function Documentation
ApplySameTypeVisitor()
template<class Visitor , class Variant > Visitor::ResultType infra::ApplySameTypeVisitor (Visitor & visitor, Variant & variant1, Variant & variant2)
Definition at line 368 of file Variant.hpp.
References infra::Variant< T >::Which().
Referenced by infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::operator<(), infra::Variant< services::IPv4Address, services::IPv6Address >::operator<(), infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::operator==(), and infra::Variant< services::IPv4Address, services::IPv6Address >::operator==().
     {
         really_assert(variant1.Which() == variant2.Which());
         detail::ApplySameTypeVisitorHelper<0, Visitor, Variant> helper;
         return helper(visitor, variant1, variant2);                                                                     //TICS !CON#007
     }
ApplyVisitor() [1/2]
template<class Visitor , class Variant > Visitor::ResultType infra::ApplyVisitor (Visitor & visitor, Variant & variant)
Definition at line 354 of file Variant.hpp.
Referenced by CopyToken(), infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::operator=(), and infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::PolymorphicVariant().
     {
         detail::ApplyVisitorHelper<0, Visitor, Variant> helper;
         return helper(visitor, variant);
     }
ApplyVisitor() [2/2]
template<class Visitor , class Variant > Visitor::ResultType infra::ApplyVisitor (Visitor & visitor, Variant & variant1, Variant & variant2)
Definition at line 361 of file Variant.hpp.
Referenced by infra::Variant< services::IPv4Address, services::IPv6Address >::Destruct(), infra::Variant< services::IPv4Address, services::IPv6Address >::operator=(), and infra::Variant< services::IPv4Address, services::IPv6Address >::Variant().
     {
         detail::ApplyVisitorHelper2<0, Visitor, Variant> helper;
         return helper(visitor, variant1, variant2);
     }
AsAscii()
AsAsciiHelper infra::AsAscii (ConstByteRange data)
Definition at line 455 of file OutputStream.cpp.
References data.
     {
         return AsAsciiHelper(data);
     }
AsBase64()
AsBase64Helper infra::AsBase64 (ConstByteRange data)
Definition at line 465 of file OutputStream.cpp.
References data.
Referenced by services::CertificatesMbedTls::WriteOwnCertificate(), and services::CertificatesMbedTls::WritePrivateKey().
     {
         return AsBase64Helper(data);
     }
AsHex()
AsHexHelper infra::AsHex (ConstByteRange data)
Definition at line 460 of file OutputStream.cpp.
References data.
Referenced by services::TracingStreamReader::Extract(), services::TracingStreamReader::ExtractContiguousRange(), services::TracingStreamReader::PeekContiguousRange(), services::TracingFlash::ReadBuffer(), and services::TracingFlash::WriteBuffer().
     {
         return AsHexHelper(data);
     }
AsMacAddress()
AsMacAddressHelper infra::AsMacAddress (hal::MacAddress macAddress)
Definition at line 9 of file MacAddress.cpp.
     {
         return AsMacAddressHelper(macAddress);
     }
Bit()
template<class T > constexpr std::remove_cv<T>::type infra::Bit (uint8_t index)
Definition at line 11 of file BitLogic.hpp.
     {
         return static_cast<typename std::remove_cv<T>::type>(1) << index;
     }
ByteRangeAsString()
BoundedConstString infra::ByteRangeAsString (infra::MemoryRange< uint8_t > range)
Definition at line 5 of file BoundedString.cpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::size().
Referenced by services::HttpClientJson::BodyAvailable(), application::TracingHttpClient::BodyAvailable(), services::TracingHttpClientImpl::DataReceived(), and services::SntpClient::NotifyKissOfDeath().
     {
         return BoundedString(reinterpret_cast<char*>(range.begin()), range.size());
     }
CleanJsonContents()
void infra::CleanJsonContents (infra::BoundedString & contents)
Definition at line 1229 of file Json.cpp.
References infra::BoundedStringBase< T >::clear(), CopyToken(), infra::Variant< T >::Is(), and infra::JsonTokenizer::Token().
     {
         infra::JsonTokenizer tokenizer(contents);
         infra::BoundedString newContents(contents);
         newContents.clear();
         infra::StringOutputStream stream(newContents);
         for (infra::JsonToken::Token token = tokenizer.Token(); !token.Is<infra::JsonToken::End>() && !token.Is<infra::JsonToken::Error>(); token = tokenizer.Token())
             CopyToken(token, stream);
         contents = newContents;
     }
ClearBit()
template<class T > void infra::ClearBit (T & dataRegister, uint8_t index)
Definition at line 23 of file BitLogic.hpp.
     {
         dataRegister &= ~Bit<T>(index);
     }
ConstCast() [1/2]
template<class T > SharedPtr<typename std::remove_const<T>::type> infra::ConstCast (const SharedPtr< T > & sharedPtr)
Definition at line 396 of file SharedPtr.hpp.
References infra::SharedPtr< T >::control, and infra::SharedPtr< T >::object.
     {
         return SharedPtr<typename std::remove_const<T>::type>(sharedPtr.control, const_cast<typename std::remove_const<T>::type*>(sharedPtr.object));
     }
ConstCast() [2/2]
template<class T > SharedPtr<typename std::remove_const<T>::type> infra::ConstCast (SharedPtr< T > && sharedPtr)
Definition at line 402 of file SharedPtr.hpp.
     {
         SharedPtr<typename std::remove_const<T>::type> result(sharedPtr.control, const_cast<typename std::remove_const<T>::type*>(sharedPtr.object));
         sharedPtr.Reset(nullptr, nullptr);
         return result;
     }
ConstCastByteRange()
ByteRange infra::ConstCastByteRange (ConstByteRange byteRange) inline
Definition at line 76 of file ByteRange.hpp.
     {
         return ConstCastMemoryRange<uint8_t>(byteRange);
     }
ConstCastMemoryRange()
template<class T > MemoryRange< T > infra::ConstCastMemoryRange (MemoryRange< const T > memoryRange)
Definition at line 345 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::end().
     {
         return MemoryRange<T>(const_cast<T*>(memoryRange.begin()), const_cast<T*>(memoryRange.end()));
     }
ContentsEqual()
template<class T , class U > bool infra::ContentsEqual (MemoryRange< T > x, MemoryRange< U > y)
Definition at line 364 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         return x.size() == y.size()
             && std::equal(x.begin(), x.end(), y.begin());
     }
Copy()
template<class T > void infra::Copy (MemoryRange< const typename std::remove_const< T >::type > from, MemoryRange< T > to)
Definition at line 357 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::size().
Referenced by services::ConfigurationBlobImpl::BlobIsValid(), infra::Function< Result(Args...), ExtraSize >::CopyConstruct(), infra::BoundedDequeInputStreamReader::Extract(), services::ConnectionSerial::SerialConnectionStreamReader::Extract(), infra::StreamWriterPrintF::Insert(), infra::ReservedProxy< T >::operator=(), services::ConfigurationBlobImpl::PrepareBlobForWriting(), services::ConfigurationBlobImpl::RecoverCurrentSize(), and services::ConnectionSerial::MessageHeader::SetContent().
     {
         assert(from.size() == to.size());
         std::copy(from.begin(), from.begin() + from.size(), to.begin());
     }
CopyToken()
void infra::CopyToken (infra::JsonToken::Token token, infra::TextOutputStream & stream)
Definition at line 1148 of file Json.cpp.
References ApplyVisitor(), infra::JsonToken::String::RawValue(), infra::JsonToken::Integer::Value(), and infra::JsonToken::Boolean::Value().
Referenced by CleanJsonContents().
     {
         class CopyVisitor
             : public infra::StaticVisitor<void>
         {
         public:
             CopyVisitor(infra::TextOutputStream& stream)
                 : stream(stream)
             {}
             void operator()(infra::JsonToken::End) const
             {
                 std::abort();
             }
             void operator()(infra::JsonToken::Error) const
             {
                 std::abort();
             }
             void operator()(infra::JsonToken::Colon)
             {
                 stream << ':';
             }
             void operator()(infra::JsonToken::Comma)
             {
                 stream << ',';
             }
             void operator()(infra::JsonToken::Dot)
             {
                 stream << '.';
             }
             void operator()(infra::JsonToken::LeftBrace)
             {
                 stream << '{';
             }
             void operator()(infra::JsonToken::RightBrace)
             {
                 stream << '}';
             }
             void operator()(infra::JsonToken::LeftBracket)
             {
                 stream << '[';
             }
             void operator()(infra::JsonToken::RightBracket)
             {
                 stream << ']';
             }
             void operator()(infra::JsonToken::String token)
             {
                 stream << '"' << token.RawValue() << '"';
             }
             void operator()(infra::JsonToken::Integer token)
             {
                 stream << token.Value();
             }
             void operator()(infra::JsonToken::Boolean token)
             {
                 if (token.Value())
                     stream << "true";
                 else
                     stream << "false";
             }
         private:
             infra::TextOutputStream& stream;
         };
         CopyVisitor copyVisitor(stream);
         infra::ApplyVisitor(copyVisitor, token);
     }
DiscardHead()
template<class T > MemoryRange< T > infra::DiscardHead (MemoryRange< T > range, std::size_t size)
Definition at line 394 of file MemoryRange.hpp.
References infra::MemoryRange< T >::pop_front(), and infra::MemoryRange< T >::size().
Referenced by services::ConfigurationBlobImpl::CurrentBlob(), services::ConfigurationBlobImpl::MaxBlob(), infra::StringOutputStreamWriter::Overwrite(), and infra::ByteOutputStreamWriter::Overwrite().
     {
         if (range.size() <= size)
             return MemoryRange<T>();
         range.pop_front(size);
         return range;
     }
DiscardTail()
template<class T > MemoryRange< T > infra::DiscardTail (MemoryRange< T > range, std::size_t size)
Definition at line 404 of file MemoryRange.hpp.
References infra::MemoryRange< T >::pop_back(), and infra::MemoryRange< T >::size().
     {
         if (range.size() <= size)
             return MemoryRange<T>();
         range.pop_back(size);
         return range;
     }
erase_heap()
template<class RandomAccessIterator , class Compare > void infra::erase_heap (RandomAccessIterator begin, RandomAccessIterator end, RandomAccessIterator position, Compare compare)
Definition at line 78 of file BoundedPriorityQueue.hpp.
References infra::detail::begin(), and infra::detail::end().
Referenced by infra::BoundedPriorityQueue< T, Max, Compare >::erase().
     {
         std::size_t size = std::distance(begin, end);
         if (size > 1)
         {
             while (true)
             {
                 size_t index = std::distance(begin, position);
                 RandomAccessIterator parent = index > 0 ? begin + (index - 1) / 2 : end;
                 RandomAccessIterator child1 = index * 2 + 1 < size - 1 ? begin + index * 2 + 1 : end;
                 RandomAccessIterator child2 = index * 2 + 2 < size - 1 ? begin + index * 2 + 2 : end;
                 if (parent != end && compare(*parent, *std::prev(end)))
                 {
                     *position = std::move(*parent);
                     position = parent;
                 }
                 else if (child1 != end && compare(*std::prev(end), *child1))
                 {
                     if (child2 != end && compare(*child1, *child2))
                     {
                         *position = std::move(*child2);
                         position = child2;
                     }
                     else
                     {
                         *position = std::move(*child1);
                         position = child1;
                     }
                 }
                 else if (child2 != end && compare(*std::prev(end), *child2))
                 {
                     *position = std::move(*child2);
                     position = child2;
                 }
                 else
                 {
                     *position = std::move(*std::prev(end));
                     break;
                 }
             }
         }
     }
FromBase64()
FromBase64Helper infra::FromBase64 (infra::ByteRange data)
Definition at line 515 of file InputStream.cpp.
References data.
     {
         return FromBase64Helper(data);
     }
GetBits()
template<class T > T infra::GetBits (T dataRegister, uint8_t size, uint8_t position)
Definition at line 53 of file BitLogic.hpp.
     {
         return dataRegister & (~(std::numeric_limits<typename std::remove_cv<T>::type>::max() << size) << (position * size));
     }
Head()
template<class T > MemoryRange< T > infra::Head (MemoryRange< T > range, std::size_t size)
Definition at line 380 of file MemoryRange.hpp.
References infra::MemoryRange< T >::shrink_from_back_to().
Referenced by services::ConfigurationBlobImpl::BlobIsValid(), services::ConfigurationBlobImpl::CurrentBlob(), services::ConnectionSerial::DataReceived(), infra::BoundedDequeInputStreamReader::Extract(), services::ConnectionSerial::SerialConnectionStreamReader::Extract(), infra::BoundedDequeInputStreamReader::ExtractContiguousRange(), services::ConnectionSerial::SerialConnectionStreamReader::ExtractContiguousRange(), infra::StreamWriterPrintF::Insert(), infra::Asn1SequenceIterator::MakeValue(), services::SynchronousFlashQuadSpi::PageProgram(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::SynchronousFlashSpi::PageProgram(), services::FlashSpi::PageProgram(), services::ConfigurationBlobImpl::PrepareBlobForWriting(), PrintTo(), services::ConfigurationBlobImpl::RecoverCurrentSize(), services::ConnectionSerial::StateConnectedSendingContent::SendEscapedContent(), services::ConnectionMbedTls::SslSend(), and application::ImageUpgraderInternalFlash::Upgrade().
     {
         range.shrink_from_back_to(size);
         return range;
     }
IntersectingRange()
template<class T > MemoryRange< T > infra::IntersectingRange (MemoryRange< T > x, MemoryRange< T > y)
Definition at line 371 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::end().
     {
         if (x.begin() > y.end() || x.end() < y.begin())
             return MemoryRange<T>();
         return MemoryRange<T>(std::max(x.begin(), y.begin()), std::min(x.end(), y.end()));
     }
IsBitSet()
template<class T > bool infra::IsBitSet (T dataRegister, uint8_t index)
Definition at line 47 of file BitLogic.hpp.
     {
         return (dataRegister & Bit<T>(index)) != 0;
     }
JsonArrayArray()
infra::detail::DoublePair< JsonValueArrayIterator< JsonArray > > infra::JsonArrayArray (JsonArray & array)
Definition at line 1141 of file Json.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
     {
         return infra::detail::DoublePair<JsonValueArrayIterator<JsonArray>>(
             JsonValueArrayIterator<JsonArray>(array.begin(), array.end()),
             JsonValueArrayIterator<JsonArray>(array.end(), array.end()));
     }
JsonBooleanArray()
infra::detail::DoublePair< JsonValueArrayIterator< bool > > infra::JsonBooleanArray (JsonArray & array)
Definition at line 1113 of file Json.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
     {
         return infra::detail::DoublePair<JsonValueArrayIterator<bool>>(
             JsonValueArrayIterator<bool>(array.begin(), array.end()),
             JsonValueArrayIterator<bool>(array.end(), array.end()));
     }
JsonEscapedStringSize()
std::size_t infra::JsonEscapedStringSize (infra::BoundedConstString string)
Definition at line 70 of file JsonFormatter.cpp.
References infra::BoundedStringBase< T >::empty(), and infra::BoundedStringBase< T >::size().
     {
         std::size_t start = 0;
         std::size_t size = 0;
         while (start != string.size())
         {
             std::size_t escape;
             infra::BoundedConstString nonEscapedSubString;
             std::tie(escape, nonEscapedSubString) = NonEscapedSubString(string, start);
             start = escape;
             if (!nonEscapedSubString.empty())
                 size += nonEscapedSubString.size();
             if (start != string.size())
             {
                 size += EscapedCharacterSize(string[start]);
                 ++start;
             }
         }
         return size;
     }
JsonIntegerArray()
infra::detail::DoublePair< JsonValueArrayIterator< int32_t > > infra::JsonIntegerArray (JsonArray & array)
Definition at line 1120 of file Json.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
     {
         return infra::detail::DoublePair<JsonValueArrayIterator<int32_t>>(
             JsonValueArrayIterator<int32_t>(array.begin(), array.end()),
             JsonValueArrayIterator<int32_t>(array.end(), array.end()));
     }
JsonObjectArray()
infra::detail::DoublePair< JsonValueArrayIterator< JsonObject > > infra::JsonObjectArray (JsonArray & array)
Definition at line 1134 of file Json.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
     {
         return infra::detail::DoublePair<JsonValueArrayIterator<JsonObject>>(
             JsonValueArrayIterator<JsonObject>(array.begin(), array.end()),
             JsonValueArrayIterator<JsonObject>(array.end(), array.end()));
     }
JsonStringArray()
infra::detail::DoublePair< JsonValueArrayIterator< JsonString > > infra::JsonStringArray (JsonArray & array)
Definition at line 1127 of file Json.cpp.
References infra::JsonArray::begin(), and infra::JsonArray::end().
     {
         return infra::detail::DoublePair<JsonValueArrayIterator<JsonString>>(
             JsonValueArrayIterator<JsonString>(array.begin(), array.end()),
             JsonValueArrayIterator<JsonString>(array.end(), array.end()));
     }
MakeByteRange() [1/2]
template<class T > ByteRange infra::MakeByteRange (T & v)
Definition at line 82 of file ByteRange.hpp.
References MakeRange(), and ReinterpretCastByteRange().
Referenced by services::ConfigurationBlobImpl::BlobIsValid(), infra::Function< Result(Args...), ExtraSize >::CopyConstruct(), application::DeployPackToExternal::DeployPackToExternal(), services::Terminal::EraseCharacterUnderCursor(), services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), hal::SynchronousRandomDataGenerator::GenerateRandomData(), application::PackUpgrader::HasImage(), application::PackUpgrader::IsImage(), application::SecondStageToRamLoader::Load(), application::PackUpgrader::MarkAsDeployed(), application::PackUpgrader::MarkAsDeployStarted(), application::SecondStageToRamLoader::MarkAsError(), application::PackUpgrader::MarkAsError(), services::Terminal::MoveCursorHome(), services::Terminal::MoveCursorLeft(), services::Terminal::MoveCursorRight(), services::SntpClient::NotifyKissOfDeath(), infra::TextOutputStream::operator<<(), infra::ReservedProxy< T >::operator=(), infra::TextInputStream::operator>>(), infra::TextOutputStream::OutputAsBinary(), infra::TextOutputStream::OutputAsDecimal(), infra::TextOutputStream::OutputAsHexadecimal(), infra::TextOutputStream::OutputOptionalPadding(), services::Terminal::OverwriteBuffer(), services::SynchronousFlashSpi::PageProgram(), services::FlashSpi::PageProgram(), infra::BoundedDequeInputStreamReader::Peek(), infra::ByteInputStreamReader::Peek(), services::ConfigurationBlobImpl::PrepareBlobForWriting(), services::ConnectionSerial::MessageHeader::Range(), services::CyclicStore::Iterator::Read(), infra::TextInputStream::ReadAsDecimal(), infra::TextInputStream::ReadAsHex(), services::FlashSpi::ReadBuffer(), services::SynchronousFlashSpi::ReadBuffer(), services::FlashSpi::ReadFlashId(), hal::I2cMasterRegisterAccess::ReadRegister(), services::CyclicStore::Iterator::ReadSectorStatusIfAtStart(), services::SynchronousFlashQuadSpi::ReadStatusRegister(), services::SynchronousFlashSpi::ReadStatusRegister(), services::FlashSpi::ReadStatusRegister(), services::ConfigurationBlobImpl::RecoverCurrentSize(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::RecoverSector(), services::Terminal::SendBell(), services::SynchronousFlashSpi::SendEraseBulk(), services::FlashSpi::SendEraseBulk(), services::SynchronousFlashSpi::SendEraseSector(), services::FlashSpi::SendEraseSector(), services::SynchronousFlashSpi::SendEraseSubSector(), services::FlashSpi::SendEraseSubSector(), services::Terminal::SendNonEscapeChar(), services::LlmnrResponder::SendStreamAvailable(), services::ConnectionSerial::MessageHeader::SetContent(), infra::TextInputStream::SkipSpaces(), application::DecryptorAesTiny::StateBuffer(), application::DecryptorAesMbedTls::StateBuffer(), application::DecryptorXtea::StateBuffer(), SwapEndian(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::SynchronousFlashQuadSpi::SynchronousFlashQuadSpi(), application::SecondStageToRamLoader::TryLoadImage(), application::PackUpgrader::TryUpgradeImage(), application::PackUpgrader::UpgradeFromImages(), services::SynchronousFlashSpi::WriteEnable(), services::FlashSpi::WriteEnable(), services::CertificatesMbedTls::WriteOwnCertificate(), services::CertificatesMbedTls::WritePrivateKey(), services::CyclicStore::WriteRange(), hal::I2cMasterRegisterAccess::WriteRegister(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         return ReinterpretCastByteRange(MakeRange(&v, &v + 1));
     }
MakeByteRange() [2/2]
template<class T > ConstByteRange infra::MakeByteRange (const T & v)
Definition at line 94 of file ByteRange.hpp.
References MakeRange(), and ReinterpretCastByteRange().
     {
         return ReinterpretCastByteRange(MakeRange(&v, &v + 1));
     }
MakeConst()
template<class T > MemoryRange< const T > infra::MakeConst (infra::MemoryRange< T > range)
Definition at line 333 of file MemoryRange.hpp.
     {
         return MemoryRange<const T>(range);
     }
MakeConstByteRange()
template<class T > ConstByteRange infra::MakeConstByteRange (T & v)
Definition at line 88 of file ByteRange.hpp.
References MakeRange(), and ReinterpretCastByteRange().
Referenced by services::CertificatesMbedTls::WriteOwnCertificate(), services::CertificatesMbedTls::X509AddAlgorithm(), and services::CertificatesMbedTls::X509AddName().
     {
         return ReinterpretCastByteRange(MakeRange(&v, &v + 1));
     }
MakeContainedSharedObject() [1/2]
template<class T , class U > SharedPtr< T > infra::MakeContainedSharedObject (T & object, const SharedPtr< U > & container)
Definition at line 601 of file SharedPtr.hpp.
References infra::SharedPtr< T >::control.
Referenced by services::HttpClientImpl::BodyReceived(), services::HttpClientImpl::DataReceived(), and services::HttpServerConnectionObserver::TakeOverConnection().
     {
         return SharedPtr<T>(container.control, &object);
     }
MakeContainedSharedObject() [2/2]
template<class T , class U > SharedPtr<T> infra::MakeContainedSharedObject (T & object, SharedPtr< U > && container)
Definition at line 607 of file SharedPtr.hpp.
     {
         SharedPtr<T> result(container.control, &object);
         container = nullptr;
         return result;
     }
MakeOptional()
template<class T > Optional< typename std::decay< T >::type > infra::MakeOptional (T && value)
Definition at line 331 of file Optional.hpp.
References inPlace, and value.
Referenced by infra::JsonIterator::ConvertValue(), infra::JsonObject::GetOptionalValue(), services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress(), services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress(), services::FlashQuadSpiCypressFll::HoldWhileWriteInProgress(), services::HttpStatusCodeFromString(), services::HttpVerbFromString(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::DnsResolver::ReplyParser::ReadAnswerRecords(), infra::JsonIterator::ReadArrayValue(), services::FlashQuadSpiSingleSpeed::ReadBuffer(), services::FlashQuadSpiMicronN25q::ReadBuffer(), services::FlashQuadSpiCypressFll::ReadBuffer(), services::DnsResolver::ReplyParser::ReadNameServer(), infra::JsonIterator::ReadObjectValue(), infra::JsonIterator::SearchArrayEnd(), services::NameResolverCache::SearchCache(), infra::JsonIterator::SearchObjectEnd(), services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiMicronN25q::SendEraseBulk(), services::FlashQuadSpiSingleSpeed::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseChip(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToQuadSpeed(), services::FlashQuadSpiCypressFll::SwitchToSingleSpeed(), TransformOptional(), services::FlashQuadSpiSingleSpeed::WriteEnable(), services::FlashQuadSpiMicronN25q::WriteEnable(), services::FlashQuadSpiCypressFll::WriteEnable(), and services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed().
     {
         return Optional<typename std::decay<T>::type>(inPlace, std::forward<T>(value));
     }
MakeRange() [1/11]
template<class T > MemoryRange< T > infra::MakeRange (T * b, T * e)
Definition at line 285 of file MemoryRange.hpp.
     {
         return MemoryRange<T>(b, e);
     }
MakeRange() [2/11]
template<class T , std::size_t N> MemoryRange< T > infra::MakeRange (std::array< T, N > & container)
Definition at line 303 of file MemoryRange.hpp.
     {
         return MemoryRange<T>(container.data(), container.data() + container.size());
     }
MakeRange() [3/11]
template<class T , std::size_t N> MemoryRange< const T > infra::MakeRange (const std::array< T, N > & container)
Definition at line 309 of file MemoryRange.hpp.
     {
         return MemoryRange<const T>(container.data(), container.data() + container.size());
     }
MakeRange() [4/11]
template<class T > MemoryRange< T > infra::MakeRange (std::vector< T > & range)
Definition at line 321 of file MemoryRange.hpp.
     {
         return MemoryRange<T>(range);
     }
MakeRange() [5/11]
template<class T > MemoryRange< const T > infra::MakeRange (const std::vector< T > & range)
Definition at line 327 of file MemoryRange.hpp.
     {
         return MemoryRange<const T>(range);
     }
MakeRange() [6/11]
template<class T > MemoryRange< T > infra::MakeRange (infra::BoundedVector< T > & container)
Definition at line 654 of file BoundedVector.hpp.
References infra::BoundedVector< T >::begin(), and infra::BoundedVector< T >::end().
     {
         return MemoryRange<T>(container.begin(), container.end());
     }
MakeRange() [7/11]
template<class T > MemoryRange< const T > infra::MakeRange (const infra::BoundedVector< T > & container)
Definition at line 660 of file BoundedVector.hpp.
References infra::BoundedVector< T >::begin(), and infra::BoundedVector< T >::end().
     {
         return MemoryRange<const T>(container.begin(), container.end());
     }
MakeRange() [8/11]
template<class T , std::size_t N> MemoryRange<T> infra::MakeRange (T(&) data[N])
Definition at line 291 of file MemoryRange.hpp.
References data.
     {
         return MemoryRange<T>(&data[0], &data[0] + N);
     }
MakeRange() [9/11]
template<class T , std::size_t N> MemoryRange<const T> infra::MakeRange (const T(&) data[N])
Definition at line 297 of file MemoryRange.hpp.
References data.
     {
         return MemoryRange<const T>(&data[0], &data[0] + N);
     }
MakeRange() [10/11]
template<class T > MemoryRange< T > infra::MakeRange (infra::BoundedStringBase< T > & container)
Definition at line 1651 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), and infra::BoundedStringBase< T >::end().
Referenced by services::ConfigurationBlobImpl::BlobIsValid(), services::Terminal::EraseCharacterUnderCursor(), infra::JsonStreamingObjectParser::Feed(), infra::TextOutputStream::FormatArgs(), infra::ProtoLengthDelimited::GetBytes(), MakeByteRange(), MakeConstByteRange(), MakeStringByteRange(), services::Terminal::MoveCursorEnd(), infra::DataOutputStream::operator<<(), infra::TextOutputStream::operator<<(), infra::DataInputStream::operator>>(), infra::StringOutputStreamWriter::Overwrite(), services::Terminal::OverwriteBuffer(), services::HttpClientBasic::Path(), services::ConfigurationBlobImpl::PrepareBlobForWriting(), services::Terminal::Print(), infra::ByteInputStreamReader::Processed(), infra::ByteOutputStreamWriter::Processed(), services::DatagramWin::Receive(), services::DatagramBsd::Receive(), infra::ByteInputStreamReader::Remaining(), infra::ByteOutputStreamWriter::Remaining(), and services::ConnectionSerial::MessageHeader::SetContent().
     {
         return MemoryRange<T>(container.begin(), container.end());
     }
MakeRange() [11/11]
template<class T > MemoryRange< const T > infra::MakeRange (const infra::BoundedStringBase< T > & container)
Definition at line 1657 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), and infra::BoundedStringBase< T >::end().
     {
         return MemoryRange<const T>(container.begin(), container.end());
     }
MakeReverseRange()
template<class Range > detail::DoublePair<typename Range::reverse_iterator> infra::MakeReverseRange (Range & r)
Definition at line 41 of file ReverseRange.hpp.
     {
         return detail::DoublePair<typename Range::reverse_iterator>(r.rbegin(), r.rend());
     }
MakeSharedOnHeap()
template<class T , class... Args> SharedPtr< T > infra::MakeSharedOnHeap (Args &&... args)
Definition at line 651 of file SharedPtr.hpp.
     {
         return *new detail::SharedObjectOnHeap<T>(std::forward<Args>(args)...);
     }
MakeStringByteRange() [1/2]
ConstByteRange infra::MakeStringByteRange (const char * string) inline
Definition at line 99 of file ByteRange.hpp.
References MakeRange(), and ReinterpretCastByteRange().
     {
         return ReinterpretCastByteRange(MakeRange(string, string + std::strlen(string)));
     }
MakeStringByteRange() [2/2]
ConstByteRange infra::MakeStringByteRange (const std::string & string) inline
Definition at line 104 of file ByteRange.hpp.
References data, MakeRange(), and ReinterpretCastByteRange().
     {
         return ReinterpretCastByteRange(MakeRange(string.data(), string.data() + string.size()));
     }
MakeUnique()
template<class T > UniquePtr< T > infra::MakeUnique (T * object, AllocatorBase & allocator)
Definition at line 64 of file Allocator.hpp.
Referenced by infra::AllocatorHeap< T, void(ConstructionArgs...)>::Allocate().
     {
         return infra::UniquePtr<T>(object, Deallocator(allocator));
     }
MakeVector()
template<class T > std::vector< typename std::remove_const< T >::type > infra::MakeVector (MemoryRange< T > range)
Definition at line 315 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::end().
     {
         return std::vector<typename std::remove_const<T>::type>(range.begin(), range.end());
     }
Now()
TimePoint infra::Now (uint32_t timerServiceId)
Definition at line 7 of file Timer.cpp.
References infra::TimerServiceManager::GetTimerService(), infra::InterfaceConnector< TimerServiceManager >::Instance(), and infra::TimerService::Now().
Referenced by services::NameResolverCache::Cleanup(), services::RepeatingButton::FireTimer::ComputeNextTriggerTime(), services::NameLookupWin::LookupIPv4(), services::DnsResolver::ReplyParser::ReadAnswer(), and services::RepeatingButton::FireTimer::Start().
     {
         return TimerServiceManager::Instance().GetTimerService(timerServiceId).Now();
     }
operator!=() [1/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator!= (const AutoResetFunction< Result(Args...), ExtraSize > & f, std::nullptr_t)
Definition at line 143 of file AutoResetFunction.hpp.
     {
         return !(f == nullptr);
     }
operator!=() [2/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator!= (std::nullptr_t , const AutoResetFunction< Result(Args...), ExtraSize > & f)
Definition at line 149 of file AutoResetFunction.hpp.
     {
         return !(f == nullptr);
     }
operator!=() [3/18]
template<class T , T Factor> bool infra::operator!= (const FixedPoint< T, Factor > & x, const FixedPoint< T, Factor > & y)
Definition at line 97 of file FixedPoint.hpp.
 { return !(x == y); }
operator!=() [4/18]
template<class T , class U , std::size_t N> bool infra::operator!= (MemoryRange< T > x, const std::array< U, N > & y)
Definition at line 426 of file MemoryRange.hpp.
     {
         return !(x == y);
     }
operator!=() [5/18]
template<class T , class U , std::size_t N> bool infra::operator!= (const std::array< U, N > & x, MemoryRange< T > y)
Definition at line 432 of file MemoryRange.hpp.
     {
         return !(x == y);
     }
operator!=() [6/18]
template<class T , T Factor> bool infra::operator!= (const FixedPoint< T, Factor > & x, const T & y)
Definition at line 109 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x.AsUnscaled() != y * Factor; }
operator!=() [7/18]
template<class T , class U > bool infra::operator!= (MemoryRange< T > x, const std::vector< U > & y)
Definition at line 450 of file MemoryRange.hpp.
     {
         return !(x == y);
     }
operator!=() [8/18]
template<class T , class U > bool infra::operator!= (const std::vector< U > & x, MemoryRange< T > y)
Definition at line 456 of file MemoryRange.hpp.
     {
         return !(x == y);
     }
operator!=() [9/18]
template<class T , T Factor> bool infra::operator!= (const T & x, const FixedPoint< T, Factor > & y)
Definition at line 121 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x * Factor != y.AsUnscaled(); }
operator!=() [10/18]
bool infra::operator!= (infra::BoundedConstString x, JsonString y)
Definition at line 167 of file Json.cpp.
     {
         return y != x;
     }
operator!=() [11/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator!= (const Function< Result(Args...), ExtraSize > & f, std::nullptr_t)
Definition at line 474 of file Function.hpp.
     {
         return !(f == nullptr);
     }
operator!=() [12/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator!= (std::nullptr_t , const Function< Result(Args...), ExtraSize > & f)
Definition at line 480 of file Function.hpp.
     {
         return !(f == nullptr);
     }
operator!=() [13/18]
bool infra::operator!= (const char * x, JsonString y)
Definition at line 199 of file Json.cpp.
     {
         return y != x;
     }
operator!=() [14/18]
template<class T , class U > bool infra::operator!= (const BoundedStringBase< T > & lhs, const BoundedStringBase< U > & rhs)
Definition at line 1449 of file BoundedString.hpp.
     {
         return !(lhs == rhs);
     }
operator!=() [15/18]
template<class T > bool infra::operator!= (const char * lhs, const BoundedStringBase< T > & rhs)
Definition at line 1507 of file BoundedString.hpp.
     {
         return !(lhs == rhs);
     }
operator!=() [16/18]
template<class T > bool infra::operator!= (const BoundedStringBase< T > & lhs, const char * rhs)
Definition at line 1513 of file BoundedString.hpp.
     {
         return !(lhs == rhs);
     }
operator!=() [17/18]
template<class T > bool infra::operator!= (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1519 of file BoundedString.hpp.
     {
         return !(lhs == rhs);
     }
operator!=() [18/18]
template<class T > bool infra::operator!= (const BoundedStringBase< T > & lhs, const std::string & rhs)
Definition at line 1525 of file BoundedString.hpp.
     {
         return !(lhs == rhs);
     }
operator*() [1/5]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator* (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > & y)
Definition at line 82 of file FixedPoint.hpp.
 { return x *= y; }
operator*() [2/5]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator* (FixedPoint< T, Factor > x, T y)
Definition at line 86 of file FixedPoint.hpp.
 { return x *= y; }
operator*() [3/5]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator* (T x, FixedPoint< T, Factor > y)
Definition at line 88 of file FixedPoint.hpp.
 { return y *= x; }
operator*() [4/5]
template<class UnitType , class StorageType > Quantity<UnitType, StorageType> infra::operator* (Quantity< UnitType, StorageType > first, StorageType second)
Definition at line 360 of file Unit.hpp.
     {
         Quantity<UnitType, StorageType> result(first);
         result *= second;
         return result;
     }
operator*() [5/5]
template<class UnitType , class StorageType > Quantity<UnitType, StorageType> infra::operator* (StorageType first, Quantity< UnitType, StorageType > second)
Definition at line 368 of file Unit.hpp.
     {
         Quantity<UnitType, StorageType> result(second);
         result *= first;
         return result;
     }
operator+() [1/3]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator+ (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > & y)
Definition at line 78 of file FixedPoint.hpp.
 { return x += y; }
operator+() [2/3]
template<class T > std::string infra::operator+ (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1627 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), and infra::BoundedStringBase< T >::end().
     {
         std::string result(lhs);
         result.append(rhs.begin(), rhs.end());
         return result;
     }
operator+() [3/3]
template<class UnitType , class StorageType > Quantity<UnitType, StorageType> infra::operator+ (Quantity< UnitType, StorageType > first, Quantity< UnitType, StorageType > second)
Definition at line 337 of file Unit.hpp.
     {
         Quantity<UnitType, StorageType> result(first);
         result += second;
         return result;
     }
operator-() [1/2]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator- (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > & y)
Definition at line 80 of file FixedPoint.hpp.
 { return x -= y; }
operator-() [2/2]
template<class UnitType , class StorageType > Quantity<UnitType, StorageType> infra::operator- (Quantity< UnitType, StorageType > first, Quantity< UnitType, StorageType > second)
Definition at line 345 of file Unit.hpp.
     {
         Quantity<UnitType, StorageType> result(first);
         result -= second;
         return result;
     }
operator/() [1/5]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator/ (FixedPoint< T, Factor > x, const FixedPoint< T, Factor > & y)
Definition at line 84 of file FixedPoint.hpp.
 { return x /= y; }
operator/() [2/5]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator/ (FixedPoint< T, Factor > x, T y)
Definition at line 90 of file FixedPoint.hpp.
 { return x /= y; }
operator/() [3/5]
template<class T , T Factor> FixedPoint<T, Factor> infra::operator/ (T x, FixedPoint< T, Factor > y)
Definition at line 92 of file FixedPoint.hpp.
References scaled.
 { return FixedPoint<T, Factor>(scaled, x) /= y; }
operator/() [4/5]
template<class UnitType , class StorageType > Quantity<typename UnitType::Inverse, StorageType> infra::operator/ (StorageType value, Quantity< UnitType, StorageType > quantity)
Definition at line 383 of file Unit.hpp.
References infra::Quantity< UnitType, StorageType >::InverseDivide(), and value.
     {
         return quantity.InverseDivide(value);
     }
operator/() [5/5]
template<class UnitType , class StorageType > Quantity<UnitType, StorageType> infra::operator/ (Quantity< UnitType, StorageType > quantity, StorageType value)
Definition at line 389 of file Unit.hpp.
References value.
     {
         Quantity<UnitType, StorageType> result(quantity);
         result /= value;
         return result;
     }
operator<() [1/8]
template<class T , T Factor> bool infra::operator< (const FixedPoint< T, Factor > & x, const FixedPoint< T, Factor > & y)
Definition at line 99 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x.AsUnscaled() < y.AsUnscaled(); }
operator<() [2/8]
template<class T , T Factor> bool infra::operator< (const FixedPoint< T, Factor > & x, const T & y)
Definition at line 111 of file FixedPoint.hpp.
 { return x.AsUnscaled() < y * Factor; }
operator<() [3/8]
template<class T , T Factor> bool infra::operator< (const T & x, const FixedPoint< T, Factor > & y)
Definition at line 123 of file FixedPoint.hpp.
 { return x * Factor < y.AsUnscaled(); }
operator<() [4/8]
template<class T , class U > bool infra::operator< (const BoundedStringBase< T > & lhs, const BoundedStringBase< U > & rhs)
Definition at line 1455 of file BoundedString.hpp.
     {
         return std::lexicographical_compare(lhs.begin(), lhs.end(), rhs.begin(), rhs.end());
     }
operator<() [5/8]
template<class T > bool infra::operator< (const char * lhs, const BoundedStringBase< T > & rhs)
Definition at line 1531 of file BoundedString.hpp.
     {
         return std::lexicographical_compare(lhs, lhs + std::strlen(lhs), rhs.begin(), rhs.end());
     }
operator<() [6/8]
template<class T > bool infra::operator< (const BoundedStringBase< T > & lhs, const char * rhs)
Definition at line 1537 of file BoundedString.hpp.
     {
         return std::lexicographical_compare(lhs.begin(), lhs.end(), rhs, rhs + std::strlen(rhs));
     }
operator<() [7/8]
template<class T > bool infra::operator< (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1543 of file BoundedString.hpp.
     {
         return std::lexicographical_compare(lhs.data(), lhs.data() + lhs.size(), rhs.begin(), rhs.end());
     }
operator<() [8/8]
template<class T > bool infra::operator< (const BoundedStringBase< T > & lhs, const std::string & rhs)
Definition at line 1549 of file BoundedString.hpp.
     {
         return std::lexicographical_compare(lhs.begin(), lhs.end(), rhs.data(), rhs.data() + rhs.size());
     }
operator<<() [1/16]
TextOutputStream & infra::operator<< (TextOutputStream & stream, infra::TimePoint time)
Definition at line 5 of file StreamTime.cpp.
References resetWidth.
     {
         time_t now = std::chrono::system_clock::to_time_t(time);
         std::tm* utcTime = gmtime(&now);
         assert(utcTime != nullptr);
         const auto w02 = infra::Width(2, '0');
         stream << (utcTime->tm_year + 1900) << '-'
             << w02 << (utcTime->tm_mon + 1) << infra::resetWidth << '-'
             << w02 << utcTime->tm_mday << infra::resetWidth << ' '
             << w02 << utcTime->tm_hour << infra::resetWidth << ':'
             << w02 << utcTime->tm_min << infra::resetWidth << ':'
             << w02 << utcTime->tm_sec << infra::resetWidth << '.'
             << infra::Width(6, '0') << std::chrono::duration_cast<std::chrono::microseconds>(time.time_since_epoch()).count() % 1000000;
         return stream;
     }
operator<<() [2/16]
TextOutputStream& infra::operator<< (TextOutputStream & stream, const AsMacAddressHelper & asMacAddressHelper)
Definition at line 14 of file MacAddress.cpp.
References hex, infra::AsMacAddressHelper::macAddress, and resetWidth.
     {
         auto& mac = asMacAddressHelper.macAddress;
         const auto w02 = Width(2, '0');
         stream << hex
             << w02 << mac[0] << resetWidth << ':'
             << w02 << mac[1] << resetWidth << ':'
             << w02 << mac[2] << resetWidth << ':'
             << w02 << mac[3] << resetWidth << ':'
             << w02 << mac[4] << resetWidth << ':'
             << w02 << mac[5];
         return stream;
     }
operator<<() [3/16]
TextOutputStream & infra::operator<< (TextOutputStream && stream, infra::TimePoint time)
Definition at line 23 of file StreamTime.cpp.
     {
         return stream << time;
     }
operator<<() [4/16]
TextOutputStream& infra::operator<< (TextOutputStream && stream, const AsMacAddressHelper & asMacAddressHelper)
Definition at line 28 of file MacAddress.cpp.
     {
         return stream << asMacAddressHelper;
     }
operator<<() [5/16]
infra::TextOutputStream & infra::operator<< (infra::TextOutputStream & stream, const services::IPv4Address & address)
Definition at line 83 of file Address.cpp.
     {
         stream << address[0] << "." << address[1] << "." << address[2] << "." << address[3];
         return stream;
     }
operator<<() [6/16]
infra::TextOutputStream & infra::operator<< (infra::TextOutputStream & stream, const services::IPv6Address & address)
Definition at line 90 of file Address.cpp.
References hex.
     {
         stream << infra::hex << address[0] << ":" << address[1] << ":" << address[2] << ":" << address[3] << ":" << address[4] << ":" << address[5] << ":" << address[6] << ":" << address[7];
         return stream;
     }
operator<<() [7/16]
infra::TextOutputStream & infra::operator<< (infra::TextOutputStream & stream, const services::IPAddress & address)
Definition at line 97 of file Address.cpp.
References infra::Variant< T >::Get(), and infra::Variant< T >::Is().
     {
         if (address.Is<services::IPv4Address>())
             stream << address.Get<services::IPv4Address>();
         else
             stream << address.Get<services::IPv6Address>();
         return stream;
     }
operator<<() [8/16]
DataOutputStream & infra::operator<< (DataOutputStream & stream, services::WebSocketOpCode opcode)
Definition at line 105 of file WebSocket.cpp.
References enum_cast(), services::finMask, and services::opCodeMask.
     {
         stream << static_cast<uint8_t>(enum_cast(services::WebSocketMask::finMask) | (enum_cast(opcode) & enum_cast(services::WebSocketMask::opCodeMask)));
         return stream;
     }
operator<<() [9/16]
TextOutputStream & infra::operator<< (TextOutputStream & stream, const services::HttpHeader & header)
Definition at line 216 of file Http.cpp.
References services::HttpHeader::Field(), and services::HttpHeader::Value().
     {
         stream << header.Field() << services::separator << header.Value();
         return stream;
     }
operator<<() [10/16]
TextOutputStream & infra::operator<< (TextOutputStream & stream, services::HttpVerb verb)
Definition at line 223 of file Http.cpp.
References services::HttpVerbToString().
     {
         stream << services::HttpVerbToString(verb);
         return stream;
     }
operator<<() [11/16]
TextOutputStream & infra::operator<< (TextOutputStream & stream, services::HttpStatusCode statusCode)
Definition at line 230 of file Http.cpp.
References services::HttpStatusCodeToString().
     {
         stream << services::HttpStatusCodeToString(statusCode);
         return stream;
     }
operator<<() [12/16]
infra::TextOutputStream& infra::operator<< (infra::TextOutputStream & stream, JsonString value)
Definition at line 257 of file Json.cpp.
References value.
     {
         for (auto c : value)
             stream << c;
         return stream;
     }
operator<<() [13/16]
TextOutputStream& infra::operator<< (infra::TextOutputStream & stream, const AsAsciiHelper & asAsciiHelper)
Definition at line 375 of file OutputStream.cpp.
References infra::AsAsciiHelper::data.
     {
         for (uint8_t byte : asAsciiHelper.data)
             if (byte < 32 || byte >= 128)
                 stream << '.';
             else
                 stream << static_cast<char>(byte);
         return stream;
     }
operator<<() [14/16]
TextOutputStream& infra::operator<< (infra::TextOutputStream & stream, const AsHexHelper & asHexHelper)
Definition at line 390 of file OutputStream.cpp.
References infra::AsHexHelper::data, and hex.
     {
         TextOutputStream hexStream = stream << hex << Width(2, '0');
         for (uint8_t byte : asHexHelper.data)
             hexStream << byte;
         return stream;
     }
operator<<() [15/16]
TextOutputStream& infra::operator<< (infra::TextOutputStream & stream, const AsBase64Helper & asHexHelper)
Definition at line 404 of file OutputStream.cpp.
References infra::AsBase64Helper::data.
     {
         static const char* encodeTable = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
         uint8_t bitIndex = 2;                                                                                           //TICS !OLC#006
         uint8_t encodedByte = 0;
         uint32_t size = 0;
         for (uint8_t byte : asHexHelper.data)
         {
             encodedByte |= byte >> bitIndex;
             stream << encodeTable[encodedByte];
             ++size;
             encodedByte = static_cast<uint8_t>(byte << (8 - bitIndex)) >> 2;                                            //TICS !POR#006
             bitIndex += 2;
             if (bitIndex == 8)
             {
                 stream << encodeTable[encodedByte];
                 ++size;
                 encodedByte = 0;
                 bitIndex = 2;
             }
         }
         if ((size & 3) != 0)
         {
             stream << encodeTable[encodedByte];
             ++size;
         }
         if ((size & 3) != 0)
         {
             stream << '=';
             ++size;
         }
         if ((size & 3) != 0)
         {
             stream << '=';
             ++size;
         }
         return stream;
     }
operator<<() [16/16]
TextOutputStream& infra::operator<< (infra::TextOutputStream && stream, const AsBase64Helper & asBase64Helper)
Definition at line 450 of file OutputStream.cpp.
     {
         return stream << asBase64Helper;
     }
operator<=() [1/8]
template<class T , T Factor> bool infra::operator<= (const FixedPoint< T, Factor > & x, const FixedPoint< T, Factor > & y)
Definition at line 103 of file FixedPoint.hpp.
 { return !(y < x); }
operator<=() [2/8]
template<class T , T Factor> bool infra::operator<= (const FixedPoint< T, Factor > & x, const T & y)
Definition at line 115 of file FixedPoint.hpp.
 { return x.AsUnscaled() <= y * Factor; }
operator<=() [3/8]
template<class T , T Factor> bool infra::operator<= (const T & x, const FixedPoint< T, Factor > & y)
Definition at line 127 of file FixedPoint.hpp.
 { return x * Factor <= y.AsUnscaled(); }
operator<=() [4/8]
template<class T , class U > bool infra::operator<= (const BoundedStringBase< T > & lhs, const BoundedStringBase< U > & rhs)
Definition at line 1461 of file BoundedString.hpp.
     {
         return !(rhs < lhs);
     }
operator<=() [5/8]
template<class T > bool infra::operator<= (const char * lhs, const BoundedStringBase< T > & rhs)
Definition at line 1555 of file BoundedString.hpp.
     {
         return !(rhs < lhs);
     }
operator<=() [6/8]
template<class T > bool infra::operator<= (const BoundedStringBase< T > & lhs, const char * rhs)
Definition at line 1561 of file BoundedString.hpp.
     {
         return !(rhs < lhs);
     }
operator<=() [7/8]
template<class T > bool infra::operator<= (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1567 of file BoundedString.hpp.
     {
         return !(rhs < lhs);
     }
operator<=() [8/8]
template<class T > bool infra::operator<= (const BoundedStringBase< T > & lhs, const std::string & rhs)
Definition at line 1573 of file BoundedString.hpp.
     {
         return !(rhs < lhs);
     }
operator==() [1/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator== (const AutoResetFunction< Result(Args...), ExtraSize > & f, std::nullptr_t)
Definition at line 131 of file AutoResetFunction.hpp.
     {
         return !f;
     }
operator==() [2/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator== (std::nullptr_t , const AutoResetFunction< Result(Args...), ExtraSize > & f)
Definition at line 137 of file AutoResetFunction.hpp.
     {
         return !f;
     }
operator==() [3/18]
template<class T , T Factor> bool infra::operator== (const FixedPoint< T, Factor > & x, const FixedPoint< T, Factor > & y)
Definition at line 95 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x.AsUnscaled() == y.AsUnscaled(); }
operator==() [4/18]
template<class T , class U , std::size_t N> bool infra::operator== (MemoryRange< T > x, const std::array< U, N > & y)
Definition at line 414 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         return x.size() == y.size() && std::equal(x.begin(), x.end(), y.begin());
     }
operator==() [5/18]
template<class T , class U , std::size_t N> bool infra::operator== (const std::array< U, N > & x, MemoryRange< T > y)
Definition at line 420 of file MemoryRange.hpp.
     {
         return y == x;
     }
operator==() [6/18]
template<class T , T Factor> bool infra::operator== (const FixedPoint< T, Factor > & x, const T & y)
Definition at line 107 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x.AsUnscaled() == y * Factor; }
operator==() [7/18]
template<class T , class U > bool infra::operator== (MemoryRange< T > x, const std::vector< U > & y)
Definition at line 438 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         return x.size() == y.size() && std::equal(x.begin(), x.end(), y.begin());
     }
operator==() [8/18]
template<class T , class U > bool infra::operator== (const std::vector< U > & x, MemoryRange< T > y)
Definition at line 444 of file MemoryRange.hpp.
     {
         return y == x;
     }
operator==() [9/18]
template<class T , T Factor> bool infra::operator== (const T & x, const FixedPoint< T, Factor > & y)
Definition at line 119 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x * Factor == y.AsUnscaled(); }
operator==() [10/18]
bool infra::operator== (infra::BoundedConstString x, JsonString y)
Definition at line 162 of file Json.cpp.
     {
         return y == x;
     }
operator==() [11/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator== (const Function< Result(Args...), ExtraSize > & f, std::nullptr_t)
Definition at line 462 of file Function.hpp.
     {
         return !f;
     }
operator==() [12/18]
template<std::size_t ExtraSize, class Result , class... Args> bool infra::operator== (std::nullptr_t , const Function< Result(Args...), ExtraSize > & f)
Definition at line 468 of file Function.hpp.
     {
         return !f;
     }
operator==() [13/18]
bool infra::operator== (const char * x, JsonString y)
Definition at line 194 of file Json.cpp.
     {
         return y == x;
     }
operator==() [14/18]
template<class T , class U > bool infra::operator== (const BoundedStringBase< T > & lhs, const BoundedStringBase< U > & rhs)
Definition at line 1442 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), infra::BoundedStringBase< T >::end(), and infra::BoundedStringBase< T >::size().
     {
         return lhs.size() == rhs.size()
             && std::equal(lhs.begin(), lhs.end(), rhs.begin());
     }
operator==() [15/18]
template<class T > bool infra::operator== (const char * lhs, const BoundedStringBase< T > & rhs)
Definition at line 1479 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), infra::BoundedStringBase< T >::end(), and infra::BoundedStringBase< T >::size().
     {
         return std::strlen(lhs) == rhs.size()
             && std::equal(rhs.begin(), rhs.end(), lhs);
     }
operator==() [16/18]
template<class T > bool infra::operator== (const BoundedStringBase< T > & lhs, const char * rhs)
Definition at line 1486 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), infra::BoundedStringBase< T >::end(), and infra::BoundedStringBase< T >::size().
     {
         return lhs.size() == std::strlen(rhs)
             && std::equal(lhs.begin(), lhs.end(), rhs);
     }
operator==() [17/18]
template<class T > bool infra::operator== (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1493 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), infra::BoundedStringBase< T >::end(), and infra::BoundedStringBase< T >::size().
     {
         return lhs.size() == rhs.size()
             && std::equal(rhs.begin(), rhs.end(), lhs.begin());
     }
operator==() [18/18]
template<class T > bool infra::operator== (const BoundedStringBase< T > & lhs, const std::string & rhs)
Definition at line 1500 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::begin(), infra::BoundedStringBase< T >::end(), and infra::BoundedStringBase< T >::size().
     {
         return lhs.size() == rhs.size()
             && std::equal(lhs.begin(), lhs.end(), rhs.begin());
     }
operator>() [1/8]
template<class T , T Factor> bool infra::operator> (const FixedPoint< T, Factor > & x, const FixedPoint< T, Factor > & y)
Definition at line 101 of file FixedPoint.hpp.
 { return y < x; }
operator>() [2/8]
template<class T , T Factor> bool infra::operator> (const FixedPoint< T, Factor > & x, const T & y)
Definition at line 113 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x.AsUnscaled() > y * Factor; }
operator>() [3/8]
template<class T , T Factor> bool infra::operator> (const T & x, const FixedPoint< T, Factor > & y)
Definition at line 125 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x * Factor > y.AsUnscaled(); }
operator>() [4/8]
template<class T , class U > bool infra::operator> (const BoundedStringBase< T > & lhs, const BoundedStringBase< U > & rhs)
Definition at line 1467 of file BoundedString.hpp.
     {
         return rhs < lhs;
     }
operator>() [5/8]
template<class T > bool infra::operator> (const char * lhs, const BoundedStringBase< T > & rhs)
Definition at line 1579 of file BoundedString.hpp.
     {
         return rhs < lhs;
     }
operator>() [6/8]
template<class T > bool infra::operator> (const BoundedStringBase< T > & lhs, const char * rhs)
Definition at line 1585 of file BoundedString.hpp.
     {
         return rhs < lhs;
     }
operator>() [7/8]
template<class T > bool infra::operator> (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1591 of file BoundedString.hpp.
     {
         return rhs < lhs;
     }
operator>() [8/8]
template<class T > bool infra::operator> (const BoundedStringBase< T > & lhs, const std::string & rhs)
Definition at line 1597 of file BoundedString.hpp.
     {
         return rhs < lhs;
     }
operator>=() [1/8]
template<class T , T Factor> bool infra::operator>= (const FixedPoint< T, Factor > & x, const FixedPoint< T, Factor > & y)
Definition at line 105 of file FixedPoint.hpp.
 { return !(x < y); }
operator>=() [2/8]
template<class T , T Factor> bool infra::operator>= (const FixedPoint< T, Factor > & x, const T & y)
Definition at line 117 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x.AsUnscaled() >= y * Factor; }
operator>=() [3/8]
template<class T , T Factor> bool infra::operator>= (const T & x, const FixedPoint< T, Factor > & y)
Definition at line 129 of file FixedPoint.hpp.
References infra::FixedPoint< T, Factor >::AsUnscaled().
 { return x * Factor >= y.AsUnscaled(); }
operator>=() [4/8]
template<class T , class U > bool infra::operator>= (const BoundedStringBase< T > & lhs, const BoundedStringBase< U > & rhs)
Definition at line 1473 of file BoundedString.hpp.
     {
         return !(lhs < rhs);
     }
operator>=() [5/8]
template<class T > bool infra::operator>= (const char * lhs, const BoundedStringBase< T > & rhs)
Definition at line 1603 of file BoundedString.hpp.
     {
         return !(lhs < rhs);
     }
operator>=() [6/8]
template<class T > bool infra::operator>= (const BoundedStringBase< T > & lhs, const char * rhs)
Definition at line 1609 of file BoundedString.hpp.
     {
         return !(lhs < rhs);
     }
operator>=() [7/8]
template<class T > bool infra::operator>= (const std::string & lhs, const BoundedStringBase< T > & rhs)
Definition at line 1615 of file BoundedString.hpp.
     {
         return !(lhs < rhs);
     }
operator>=() [8/8]
template<class T > bool infra::operator>= (const BoundedStringBase< T > & lhs, const std::string & rhs)
Definition at line 1621 of file BoundedString.hpp.
     {
         return !(lhs < rhs);
     }
operator>>() [1/2]
infra::TextInputStream& infra::operator>> (infra::TextInputStream & stream, FromBase64Helper fromHexHelper)
Definition at line 465 of file InputStream.cpp.
References infra::FromBase64Helper::data, infra::MemoryRange< T >::empty(), infra::InputStream::Empty(), infra::InputStream::ErrorPolicy(), infra::MemoryRange< T >::front(), infra::MemoryRange< T >::pop_front(), and infra::StreamErrorPolicy::ReportResult().
     {
         uint8_t bitIndex = 0;
         uint16_t decodedWord = 0;
         while (!fromHexHelper.data.empty() && !stream.Empty())
         {
             char currentChar;
             stream >> currentChar;
             uint8_t decodedValue = DecodeByte(currentChar);
             ++currentChar;
             if (decodedValue < 64)
             {
                 decodedWord = (decodedWord << 6) | decodedValue;
                 bitIndex += 6;
                 if (bitIndex >= 8)
                 {
                     fromHexHelper.data.front() = static_cast<uint8_t>(decodedWord >> static_cast<uint8_t>(bitIndex - 8));
                     fromHexHelper.data.pop_front();
                     bitIndex -= 8;
                 }
             }
             else
             {
                 stream.ErrorPolicy().ReportResult(false);
                 return stream;
             }
         }
         while (bitIndex != 0 && !stream.Empty())
         {
             char currentChar;
             stream >> currentChar;
             stream.ErrorPolicy().ReportResult(currentChar == '=');
             bitIndex -= 2;
         }
         stream.ErrorPolicy().ReportResult(fromHexHelper.data.empty());
         return stream;
     }
operator>>() [2/2]
infra::TextInputStream& infra::operator>> (infra::TextInputStream && stream, FromBase64Helper fromBase64Helper)
Definition at line 510 of file InputStream.cpp.
     {
         return stream >> fromBase64Helper;
     }
OptionalCoverageDummy()
void infra::OptionalCoverageDummy ()
Definition at line 8 of file Optional.cpp.
     {}
PrintTo() [1/5]
void infra::PrintTo (ByteRange range, std::ostream * os) inline
Definition at line 33 of file ByteRange.hpp.
References infra::MemoryRange< T >::begin(), Head(), and infra::MemoryRange< T >::size().
     {
         *os << "ByteRange size " << range.size() << " contents [";
         for (uint8_t& e : infra::Head(range, 8))
         {
             *os << static_cast<int>(e);
             if (std::distance(range.begin(), &e) != range.size() - 1)
                 *os << ", ";
         }
         if (range.size() > 8)
             *os << "...";
         *os << "]";
     }
PrintTo() [2/5]
void infra::PrintTo (ConstByteRange range, std::ostream * os) inline
Definition at line 47 of file ByteRange.hpp.
References infra::MemoryRange< T >::begin(), Head(), and infra::MemoryRange< T >::size().
     {
         *os << "ConstByteRange size " << range.size() << " contents [";
         for (const uint8_t& e : infra::Head(range, 8))
         {
             *os << static_cast<int>(e);
             if (std::distance(range.begin(), &e) != range.size() - 1)
                 *os << ", ";
         }
         if (range.size() > 8)
             *os << "...";
         *os << "]";
     }
PrintTo() [3/5]
template<class R , class... Args> void infra::PrintTo (Function< R(Args...)> , std::ostream * os)
Definition at line 214 of file Function.hpp.
     {
         *os << "Function<" << typeid(R).name() << "(";
         PrintParameterNames<Args...> print(os);
         *os << ")>";
     }
PrintTo() [4/5]
template<class T > void infra::PrintTo (const BoundedStringBase< T > & string, std::ostream * os)
Definition at line 341 of file BoundedString.hpp.
     {
         *os << '"';
         for (char c : string)
             *os << c;
         *os << '"';
     }
PrintTo() [5/5]
template<class T , std::size_t Max> void infra::PrintTo (const typename BoundedStringBase< T >::template WithStorage< Max > & string, std::ostream * os)
Definition at line 350 of file BoundedString.hpp.
     {
         *os << '"';
         for (char c : string)
             *os << c;
         *os << '"';
     }
ReinterpretCastByteRange() [1/2]
template<class U > ByteRange infra::ReinterpretCastByteRange (MemoryRange< U > memoryRange)
Definition at line 65 of file ByteRange.hpp.
Referenced by infra::TextOutputStream::FormatArgs(), MakeByteRange(), MakeConstByteRange(), MakeStringByteRange(), infra::DataOutputStream::operator<<(), infra::TextOutputStream::operator<<(), infra::TextInputStream::operator>>(), infra::StringOutputStreamWriter::Overwrite(), services::Terminal::Print(), and infra::StringOutputStreamWriter::Reserve().
     {
         return ReinterpretCastMemoryRange<uint8_t>(memoryRange);
     }
ReinterpretCastByteRange() [2/2]
template<class U > ConstByteRange infra::ReinterpretCastByteRange (MemoryRange< const U > memoryRange)
Definition at line 71 of file ByteRange.hpp.
     {
         return ReinterpretCastMemoryRange<const uint8_t>(memoryRange);
     }
ReinterpretCastMemoryRange()
template<class T , class U > MemoryRange< T > infra::ReinterpretCastMemoryRange (MemoryRange< U > memoryRange)
Definition at line 339 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::end().
Referenced by infra::DataInputStream::operator>>().
     {
         return MemoryRange<T>(reinterpret_cast<T*>(memoryRange.begin()), reinterpret_cast<T*>(memoryRange.end()));
     }
ReplaceBit() [1/2]
template<class T > void infra::ReplaceBit (T & dataRegister, bool newValue, uint8_t position)
Definition at line 29 of file BitLogic.hpp.
     {
         dataRegister = (dataRegister & ~Bit<T>(position)) | (static_cast<T>(newValue) << position);
     }
ReplaceBit() [2/2]
template<class T > void infra::ReplaceBit (T & dataRegister, typename std::remove_cv< T >::type newValue, uint8_t position)
Definition at line 35 of file BitLogic.hpp.
     {
         dataRegister = (dataRegister & ~Bit<T>(position)) | (newValue << position);
     }
ReplaceBits()
template<class T > void infra::ReplaceBits (T & dataRegister, uint8_t size, typename std::remove_cv< T >::type newValue, uint8_t position)
Definition at line 41 of file BitLogic.hpp.
     {
         dataRegister = (dataRegister & ~(~(std::numeric_limits<typename std::remove_cv<T>::type>::max() << size) << (position * size))) | (newValue << (position * size));
     }
SetBit()
template<class T > void infra::SetBit (T & dataRegister, uint8_t index)
Definition at line 17 of file BitLogic.hpp.
     {
         dataRegister |= Bit<T>(index);
     }
StaticPointerCast() [1/2]
template<class U , class T > SharedPtr<U> infra::StaticPointerCast (const SharedPtr< T > & sharedPtr)
Definition at line 382 of file SharedPtr.hpp.
References infra::SharedPtr< T >::control, and infra::SharedPtr< T >::object.
     {
         return SharedPtr<U>(sharedPtr.control, static_cast<U*>(sharedPtr.object));
     }
StaticPointerCast() [2/2]
template<class U , class T > SharedPtr<U> infra::StaticPointerCast (SharedPtr< T > && sharedPtr)
Definition at line 388 of file SharedPtr.hpp.
     {
         SharedPtr<U> result(sharedPtr.control, static_cast<U*>(sharedPtr.object));
         sharedPtr.Reset(nullptr, nullptr);
         return result;
     }
StringAsByteRange() [1/2]
template<class U > MemoryRange< uint8_t > infra::StringAsByteRange (const infra::BoundedStringBase< U > & string)
Definition at line 1675 of file BoundedString.hpp.
Referenced by services::MqttClientImpl::MqttFormatter::AddString(), infra::ProtoLengthDelimited::GetString(), services::MqttClientImpl::MqttFormatter::MessagePublish(), infra::ProtoFormatter::PutString(), services::DnsResolver::HostnamePartsStream::ReadNext(), and services::LlmnrResponder::SendStreamAvailable().
     {
         return StringAsMemoryRange<uint8_t>(string);
     }
StringAsByteRange() [2/2]
template<class U > MemoryRange< const uint8_t > infra::StringAsByteRange (const infra::BoundedStringBase< const U > & string)
Definition at line 1681 of file BoundedString.hpp.
     {
         return StringAsMemoryRange<uint8_t>(string);
     }
StringAsMemoryRange() [1/2]
template<class T , class U > MemoryRange< T > infra::StringAsMemoryRange (const infra::BoundedStringBase< U > & string)
Definition at line 1663 of file BoundedString.hpp.
References infra::detail::end().
     {
         return MemoryRange<T>(reinterpret_cast<T*>(string.begin()), reinterpret_cast<T*>(string.end()));
     }
StringAsMemoryRange() [2/2]
template<class T , class U > MemoryRange< const T > infra::StringAsMemoryRange (const infra::BoundedStringBase< const U > & string)
Definition at line 1669 of file BoundedString.hpp.
References infra::detail::end().
     {
         return MemoryRange<const T>(reinterpret_cast<const T*>(string.begin()), reinterpret_cast<const T*>(string.end()));
     }
swap() [1/11]
template<std::size_t ExtraSize, class Result , class... Args> void infra::swap (AutoResetFunction< Result(Args...), ExtraSize > & x, AutoResetFunction< Result(Args...), ExtraSize > & y)
Definition at line 125 of file AutoResetFunction.hpp.
Referenced by services::ConfigurationStoreBase::BlobWriteDone(), services::ConfigurationStoreBase::OnBlobLoaded(), services::ConfigurationStoreBase::Recover(), infra::IntrusivePriorityQueue< T, Compare >::swap(), infra::BoundedPriorityQueue< T, Max, Compare >::swap(), and infra::BoundedForwardList< T >::swap().
     {
         x.Swap(y);
     }
swap() [2/11]
template<class T , class Compare > void infra::swap (IntrusiveSet< T, Compare > & node, IntrusiveSet< T, Compare > & uncle)
Definition at line 403 of file IntrusiveSet.hpp.
References infra::IntrusiveSet< T, Compare >::swap().
     {
         node.swap(uncle);
     }
swap() [3/11]
template<class T > void infra::swap (IntrusiveForwardList< T > & x, IntrusiveForwardList< T > & y)
Definition at line 385 of file IntrusiveForwardList.hpp.
References infra::IntrusiveForwardList< T >::swap().
Referenced by infra::IntrusiveForwardList< infra::Timer >::swap().
     {
         x.swap(y);
     }
swap() [4/11]
template<class T > void infra::swap (IntrusiveList< T > & x, IntrusiveList< T > & y)
Definition at line 488 of file IntrusiveList.hpp.
References infra::IntrusiveList< T >::swap().
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::swap().
     {
         x.swap(y);
     }
swap() [5/11]
template<class T > void infra::swap (BoundedForwardList< T > & x, BoundedForwardList< T > & y)
Definition at line 622 of file BoundedForwardList.hpp.
References infra::BoundedForwardList< T >::swap().
Referenced by infra::BoundedForwardList< T >::swap().
     {
         x.swap(y);
     }
swap() [6/11]
template<class T > void infra::swap (BoundedVector< T > & x, BoundedVector< T > & y)
Definition at line 648 of file BoundedVector.hpp.
References infra::BoundedVector< T >::swap().
Referenced by infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::swap().
     {
         x.swap(y);
     }
swap() [7/11]
template<class T , class Compare > void infra::swap (IntrusiveBinarySearchTree< T, Compare > & node, IntrusiveBinarySearchTree< T, Compare > & uncle)
Definition at line 746 of file IntrusiveBinarySearchTree.hpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::swap().
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::operator=(), and infra::IntrusiveBinarySearchTree< T, Compare >::swap().
     {
         node.swap(uncle);
     }
swap() [8/11]
template<class T > void infra::swap (BoundedDeque< T > & x, BoundedDeque< T > & y)
Definition at line 738 of file BoundedDeque.hpp.
References infra::BoundedDeque< T >::swap().
Referenced by infra::BoundedDeque< decltype(buffer)>::swap().
     {
         x.swap(y);
     }
swap() [9/11]
template<class T > void infra::swap (BoundedList< T > & x, BoundedList< T > & y)
Definition at line 758 of file BoundedList.hpp.
References infra::BoundedList< T >::swap().
Referenced by infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap().
     {
         x.swap(y);
     }
swap() [10/11]
template<std::size_t ExtraSize, class Result , class... Args> void infra::swap (Function< Result(Args...), ExtraSize > & x, Function< Result(Args...), ExtraSize > & y)
Definition at line 456 of file Function.hpp.
Referenced by infra::Function< Result(Args...), ExtraSize >::Swap().
     {
         x.Swap(y);
     }
swap() [11/11]
template<class T > void infra::swap (BoundedStringBase< T > & lhs, BoundedStringBase< T > & rhs)
Definition at line 1635 of file BoundedString.hpp.
References infra::BoundedStringBase< T >::swap().
Referenced by infra::BoundedStringBase< char >::swap().
     {
         lhs.swap(rhs);
     }
SwapEndian()
template<class T > T infra::SwapEndian (T value)
Definition at line 21 of file Endian.hpp.
References infra::detail::end(), infra::detail::make_reverse_iterator(), MakeByteRange(), and value.
Referenced by infra::BigEndian< uint32_t >::operator uint32_t(), and infra::BigEndian< uint16_t >::operator==().
     {
         static_assert(std::is_standard_layout<T>::value, "T should be standard layout");
         T result;
         auto valueRange = infra::MakeByteRange(value);
         std::copy(valueRange.begin(), valueRange.end(), detail::make_reverse_iterator(infra::MakeByteRange(result).end()));
         return result;
     }
Tail()
template<class T > MemoryRange< T > infra::Tail (MemoryRange< T > range, std::size_t size)
Definition at line 387 of file MemoryRange.hpp.
References infra::MemoryRange< T >::shrink_from_front_to().
Referenced by services::ConnectionSerial::SerialConnectionStreamReader::Extract(), services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent(), and services::ConnectionSerial::MessageHeader::SetContent().
     {
         range.shrink_from_front_to(size);
         return range;
     }
TransformOptional()
template<class T , class F > auto infra::TransformOptional (const infra::Optional< T > & value, F transformation) -> infra::Optional<decltype(transformation(*value))>
Definition at line 337 of file Optional.hpp.
References MakeOptional(), none, and value.
     {
         if (value != infra::none)
             return infra::MakeOptional(transformation(*value));
         else
             return infra::none;
     }
TrimLeft()
template<class T > BoundedStringBase< T > infra::TrimLeft (BoundedStringBase< T > string)
Definition at line 1641 of file BoundedString.hpp.
Referenced by services::HttpRequestParserImpl::EnumerateHeaders(), and services::HttpRequestParserImpl::Header().
     {
         for (auto i = 0; i != string.size(); ++i)
             if (string[i] != ' ')
                 return string.substr(i);
         return BoundedStringBase<T>();
     }
UnOwnedSharedPtr()
template<class T > SharedPtr< T > infra::UnOwnedSharedPtr (T & object)
Definition at line 593 of file SharedPtr.hpp.
Referenced by services::ConnectionSerial::ReceiveStream().
     {
         static detail::NullAllocator nullAllocator;
         static detail::SharedPtrControl control(nullptr, &nullAllocator);
         return SharedPtr<T>(&control, &object);
     }
VolatileCastMemoryRange()
template<class T > MemoryRange< T > infra::VolatileCastMemoryRange (MemoryRange< volatile T > memoryRange)
Definition at line 351 of file MemoryRange.hpp.
References infra::MemoryRange< T >::begin(), and infra::MemoryRange< T >::end().
     {
         return MemoryRange<T>(const_cast<T*>(memoryRange.begin()), const_cast<T*>(memoryRange.end()));
     }
Variable Documentation
atIndex
const AtIndex infra::atIndex
Definition at line 11 of file Variant.hpp.
bin
const struct infra::Bin infra::bin
Definition at line 8 of file StreamManipulators.cpp.
crcCcittTabe
const std::array<uint16_t, 256> infra::crcCcittTabe static
Definition at line 5 of file CrcCcittCalculator.cpp.
data
const struct infra::Data infra::data
Definition at line 9 of file StreamManipulators.cpp.
Referenced by application::BinaryObject::AddBinary(), infra::Asn1Formatter::AddContextSpecific(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::AddFromInterrupt(), application::BinaryObject::AddHex(), AsAscii(), AsBase64(), AsHex(), application::UpgradePackBuilder::AssignZeroFilled(), services::HttpRequestParserImpl::CheckContentsLength(), application::ImageEncryptorAes::CheckDecryption(), infra::StaticStorage< services::DatagramWin::StreamWriterWin >::Construct(), infra::StaticStorageForPolymorphicObjects< services::ConnectionSerial::State, T... >::Construct(), infra::Variant< services::IPv4Address, services::IPv6Address >::ConstructInEmptyVariant(), application::DecryptorAesTiny::DecryptAndAuthenticate(), application::DecryptorAesMbedTls::DecryptAndAuthenticate(), application::DecryptorXtea::DecryptAndAuthenticate(), application::DecryptorAesTiny::DecryptPart(), application::DecryptorAesMbedTls::DecryptPart(), application::DecryptorXtea::DecryptPart(), infra::StaticStorage< services::DatagramWin::StreamWriterWin >::Destruct(), infra::StaticStorageForPolymorphicObjects< services::ConnectionSerial::State, T... >::Destruct(), infra::Optional< services::DatagramWin::StreamWriterWin >::Emplace(), infra::OptionalForPolymorphicObjects< T, ExtraSize >::Emplace(), infra::StringInputStreamReader::ExtractContiguousRange(), infra::StdStringInputStreamReader::ExtractContiguousRange(), infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), infra::JsonStreamingObjectParser::Feed(), infra::JsonSubParser::FeedToken(), services::HttpRequestParserImpl::FindHeadersAndBody(), FromBase64(), application::ImageAuthenticatorHmac::GenerateMac(), services::ConnectionMbedTls::GenerateRandomData(), infra::Variant< services::IPv4Address, services::IPv6Address >::Get(), services::HttpRequestParserImpl::HttpRequestParserImpl(), application::VerifierEcDsa::IsValid(), application::VerifierRsa::IsValid(), application::InputHex::Linearize(), MakeRange(), MakeStringByteRange(), application::ImageSignerRsa::MyRandom(), infra::StaticStorage< services::DatagramWin::StreamWriterWin >::operator*(), infra::Optional< services::DatagramWin::StreamWriterWin >::operator*(), infra::OptionalForPolymorphicObjects< T, ExtraSize >::operator*(), infra::StaticStorage< services::DatagramWin::StreamWriterWin >::operator->(), infra::Optional< services::DatagramWin::StreamWriterWin >::operator->(), infra::OptionalForPolymorphicObjects< T, ExtraSize >::operator->(), infra::DataOutputStream::operator<<(), infra::TextOutputStream::operator<<(), infra::ReservedProxy< T >::operator=(), infra::DataInputStream::operator>>(), infra::StringInputStreamReader::PeekContiguousRange(), infra::StdStringInputStreamReader::PeekContiguousRange(), services::Terminal::Print(), infra::CyclicBuffer< T >::Push(), hal::FileSystemWin::ReadBinaryFile(), hal::I2cMasterRegisterAccess::ReadRegister(), services::I2cMultipleAccessMaster::ReceiveData(), hal::SynchronousSpi::ReceiveData(), services::I2cMultipleAccess::ReceiveData(), hal::SpiMaster::ReceiveData(), services::I2cMultipleAccess::ReceiveDataOnClaimed(), infra::Optional< services::DatagramWin::StreamWriterWin >::Reset(), infra::OptionalForPolymorphicObjects< T, ExtraSize >::Reset(), application::ImageEncryptorNone::Secure(), application::ImageEncryptorXtea::Secure(), application::ImageSecurityXteaHmac::Secure(), application::ImageEncryptorAes::Secure(), services::I2cMultipleAccessMaster::SendData(), hal::SynchronousSpi::SendData(), services::I2cMultipleAccess::SendData(), hal::SpiMaster::SendData(), services::I2cMultipleAccess::SendDataOnClaimed(), services::ConnectionSerial::SendStreamFilled(), services::ConnectionMbedTls::StaticGenerateRandomData(), services::WebSocketFrameHeader::WebSocketFrameHeader(), services::DnsResolver::ActiveLookup::WriteHostname(), and hal::I2cMasterRegisterAccess::WriteRegister().
emptyFunction
const infra::Function< void()> infra::emptyFunction = []() {}
Definition at line 5 of file Function.cpp.
Referenced by infra::TimerAlternating::ComputeNextTriggerTime(), infra::TimerLimitedRepeatingWithClosingAction::ComputeNextTriggerTime(), infra::Sequencer::DoWhile(), infra::Sequencer::EndIf(), services::Terminal::EraseCharacterUnderCursor(), services::Terminal::MoveCursorEnd(), services::Terminal::MoveCursorHome(), services::Terminal::MoveCursorLeft(), services::Terminal::MoveCursorRight(), services::Terminal::OverwriteBuffer(), services::Terminal::SendBell(), and services::Terminal::SendNonEscapeChar().
endl
const struct infra::Endl infra::endl
Definition at line 10 of file StreamManipulators.cpp.
Referenced by application::UpgradePackBuilderFacade::Build(), services::TracingHttpClientImpl::DataReceived(), main(), application::UpgradePackBuilderFacade::ShowUsage(), hal::FileSystemWin::WriteFile(), and services::TracingHttpClientImpl::WriteRequest().
hex
const struct infra::Hex infra::hex
Definition at line 7 of file StreamManipulators.cpp.
Referenced by application::UpgradePackBuilderFacade::Build(), services::TracingFlash::EraseSectors(), application::BinaryObject::LineContents::LineContents(), services::TracingConnectionMbedTls::LogFailure(), operator<<(), services::TracerAdapterPrintf::ParseFormat(), services::TracingFlash::ReadBuffer(), and services::TracingFlash::WriteBuffer().
inPlace
const struct infra::InPlace infra::inPlace
Definition at line 6 of file Optional.cpp.
Referenced by services::TimeWithLocalization::DurationFromString(), MakeOptional(), services::TimeWithLocalization::OffsetFromTimeString(), and services::TimeWithLocalization::TimePointFromString().
noFail
const struct infra::NoFail infra::noFail
Definition at line 8 of file StreamErrorPolicy.cpp.
Referenced by services::HttpClientJson::BodyAvailable(), application::TracingHttpClient::BodyAvailable(), and services::HttpRequestParserImpl::CheckContentsLength().
none
const struct infra::None infra::none
Definition at line 5 of file Optional.cpp.
Referenced by services::HttpClientJson::BodyAvailable(), services::HttpClientImpl::BodyComplete(), services::HttpClientImpl::BodyReaderDestroyed(), services::HttpClientJson::ClosingConnection(), infra::JsonIterator::ConvertValue(), services::HttpClientImpl::DataReceived(), infra::Creator< T, U, void(ConstructionArgs...)>::Destroy(), infra::Creator< void, U, void(ConstructionArgs...)>::Destroy(), infra::SharedOptional< services::DatagramWin::StreamWriterWin >::Destruct(), services::TimeWithLocalization::DurationFromString(), application::UpgradePackConfigParser::GetComponents(), infra::JsonObject::GetOptionalValue(), application::UpgradePackConfigParser::GetOptions(), application::UpgradePackConfigParser::GetOutputFilename(), services::HttpStatusCodeFromString(), services::HttpVerbFromString(), infra::JsonArrayFormatter::JsonArrayFormatter(), infra::JsonObjectFormatter::JsonObjectFormatter(), services::NameResolverCache::Lookup(), services::NameResolverCache::NameLookupDone(), services::DnsResolver::NameLookupDone(), services::TimeWithLocalization::OffsetFromTimeString(), infra::JsonObjectFormatter::operator=(), infra::XmlTagFormatter::operator=(), infra::JsonArrayFormatter::operator=(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::DnsResolver::ReplyParser::ReadAdditionalRecords(), services::DnsResolver::ReplyParser::ReadAnswerRecords(), infra::JsonIterator::ReadArrayValue(), services::DnsResolver::ReplyParser::ReadNameServer(), infra::JsonIterator::ReadObjectValue(), infra::JsonIterator::SearchArrayEnd(), services::NameResolverCache::SearchCache(), infra::JsonIterator::SearchObjectEnd(), services::DatagramWin::Send(), services::DatagramBsd::Send(), services::ConnectionSerial::StateSendingUpdate::SendUpdate(), services::TimeWithLocalization::TimePointFromString(), TransformOptional(), services::ConnectionSerial::TryConstructHeader(), services::DnsResolver::ActiveLookup::TryFindAnswer(), services::ConnectionSerial::TryProcessHeader(), services::NameResolverCache::TryResolveNext(), services::DnsResolver::TryResolveNext(), services::HttpClientImpl::WriteRequest(), services::CertificatesMbedTls::X509AddAlgorithm(), infra::XmlTagFormatter::XmlTagFormatter(), infra::JsonArrayFormatter::~JsonArrayFormatter(), infra::JsonObjectFormatter::~JsonObjectFormatter(), and infra::XmlTagFormatter::~XmlTagFormatter().
resetWidth
const Width infra::resetWidth
Definition at line 21 of file StreamManipulators.hpp.
Referenced by services::TracingConnectionMbedTls::LogFailure(), operator<<(), and operator<<().
scaled
const Scaled infra::scaled
Definition at line 7 of file FixedPoint.hpp.
Referenced by operator/().
simpleStateSequence
const std::array<SystemStateBase, 2> infra::simpleStateSequence = { StateInitializing(), StateRunning() } static
Definition at line 84 of file SystemStateManager.hpp.
softFail
const struct infra::SoftFail infra::softFail
Definition at line 7 of file StreamErrorPolicy.cpp.
Referenced by services::LlmnrResponder::DataReceived(), services::SntpClient::DataReceived(), services::MqttClientImpl::StateConnecting::DataReceived(), services::MqttClientImpl::StateConnected::DataReceived(), services::TimeWithLocalization::DurationFromString(), application::BinaryObject::LineContents::LineContents(), services::TimeWithLocalization::TimePointFromString(), and services::WebSocketFrameHeader::WebSocketFrameHeader().
systemTimerServiceId
const uint32_t infra::systemTimerServiceId = 0
Definition at line 31 of file Timer.hpp.
text
const struct infra::Text infra::text
Definition at line 6 of file StreamManipulators.cpp.
Referenced by infra::Asn1Formatter::AddGeneralizedTime(), infra::Asn1Formatter::AddUtcTime(), infra::TextInputStream::operator>>(), and services::DnsResolver::ActiveLookup::WriteHostname().
triggerImmediately
const TriggerImmediately infra::triggerImmediately
Definition at line 29 of file Timer.hpp.
Referenced by infra::TimerRepeating::TimerRepeating().
unscaled
const Unscaled infra::unscaled
Definition at line 9 of file FixedPoint.hpp.