var namespaceinfra =
[
    [ "detail", "d2/dc5/namespaceinfra_1_1detail.html", "d2/dc5/namespaceinfra_1_1detail" ],
    [ "JsonToken", "d0/d76/namespaceinfra_1_1_json_token.html", "d0/d76/namespaceinfra_1_1_json_token" ],
    [ "AccessedBySharedPtr", "da/d78/classinfra_1_1_accessed_by_shared_ptr.html", "da/d78/classinfra_1_1_accessed_by_shared_ptr" ],
    [ "Allocator", "dd/dc1/classinfra_1_1_allocator.html", null ],
    [ "Allocator< T, void(ConstructionArgs...)>", "dc/d81/classinfra_1_1_allocator_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "dc/d81/classinfra_1_1_allocator_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "AllocatorBase", "df/db7/classinfra_1_1_allocator_base.html", "df/db7/classinfra_1_1_allocator_base" ],
    [ "AllocatorFixedSpace", "dc/deb/classinfra_1_1_allocator_fixed_space.html", null ],
    [ "AllocatorFixedSpace< T, NumberOfElements, void(ConstructionArgs...)>", "dc/df0/classinfra_1_1_allocator_fixed_space_3_01_t_00_01_number_of_elements_00_01void_07_construction_args_8_8_8_08_4.html", "dc/df0/classinfra_1_1_allocator_fixed_space_3_01_t_00_01_number_of_elements_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "AllocatorHeap", "de/d99/classinfra_1_1_allocator_heap.html", null ],
    [ "AllocatorHeap< T, void(ConstructionArgs...)>", "d9/da5/classinfra_1_1_allocator_heap_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "d9/da5/classinfra_1_1_allocator_heap_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "AsAsciiHelper", "d9/dca/classinfra_1_1_as_ascii_helper.html", "d9/dca/classinfra_1_1_as_ascii_helper" ],
    [ "AsBase64Helper", "d9/d6b/classinfra_1_1_as_base64_helper.html", "d9/d6b/classinfra_1_1_as_base64_helper" ],
    [ "AsHexHelper", "d2/d2c/classinfra_1_1_as_hex_helper.html", "d2/d2c/classinfra_1_1_as_hex_helper" ],
    [ "AsMacAddressHelper", "da/d69/classinfra_1_1_as_mac_address_helper.html", "da/d69/classinfra_1_1_as_mac_address_helper" ],
    [ "Asn1ContainerFormatter", "db/d2d/classinfra_1_1_asn1_container_formatter.html", "db/d2d/classinfra_1_1_asn1_container_formatter" ],
    [ "Asn1Formatter", "db/dc0/classinfra_1_1_asn1_formatter.html", "db/dc0/classinfra_1_1_asn1_formatter" ],
    [ "Asn1Sequence", "df/dd8/classinfra_1_1_asn1_sequence.html", "df/dd8/classinfra_1_1_asn1_sequence" ],
    [ "Asn1SequenceIterator", "d6/d37/classinfra_1_1_asn1_sequence_iterator.html", "d6/d37/classinfra_1_1_asn1_sequence_iterator" ],
    [ "Asn1Value", "dd/d2b/classinfra_1_1_asn1_value.html", "dd/d2b/classinfra_1_1_asn1_value" ],
    [ "AtIndex", "db/dcc/structinfra_1_1_at_index.html", null ],
    [ "AutoResetFunction", "d5/d33/classinfra_1_1_auto_reset_function.html", null ],
    [ "AutoResetFunction< Result(Args...), ExtraSize >", "d6/d48/classinfra_1_1_auto_reset_function_3_01_result_07_args_8_8_8_08_00_01_extra_size_01_4.html", "d6/d48/classinfra_1_1_auto_reset_function_3_01_result_07_args_8_8_8_08_00_01_extra_size_01_4" ],
    [ "BaseUnit", "dd/d6f/structinfra_1_1_base_unit.html", null ],
    [ "BigEndian", "d9/d13/classinfra_1_1_big_endian.html", "d9/d13/classinfra_1_1_big_endian" ],
    [ "Bin", "d1/d1b/structinfra_1_1_bin.html", null ],
    [ "BoundedDeque", "d5/db7/classinfra_1_1_bounded_deque.html", "d5/db7/classinfra_1_1_bounded_deque" ],
    [ "BoundedDequeInputStream", "d4/d83/classinfra_1_1_bounded_deque_input_stream.html", "d4/d83/classinfra_1_1_bounded_deque_input_stream" ],
    [ "BoundedDequeInputStreamReader", "d7/dea/classinfra_1_1_bounded_deque_input_stream_reader.html", "d7/dea/classinfra_1_1_bounded_deque_input_stream_reader" ],
    [ "BoundedForwardList", "d4/d6c/classinfra_1_1_bounded_forward_list.html", "d4/d6c/classinfra_1_1_bounded_forward_list" ],
    [ "BoundedList", "d8/d38/classinfra_1_1_bounded_list.html", "d8/d38/classinfra_1_1_bounded_list" ],
    [ "BoundedPriorityQueue", "df/d12/classinfra_1_1_bounded_priority_queue.html", "df/d12/classinfra_1_1_bounded_priority_queue" ],
    [ "BoundedStringBase", "d1/d2a/classinfra_1_1_bounded_string_base.html", "d1/d2a/classinfra_1_1_bounded_string_base" ],
    [ "BoundedVector", "dc/de7/classinfra_1_1_bounded_vector.html", "dc/de7/classinfra_1_1_bounded_vector" ],
    [ "Buffers", "dd/def/structinfra_1_1_buffers.html", "dd/def/structinfra_1_1_buffers" ],
    [ "ByteInputStream", "d7/d19/classinfra_1_1_byte_input_stream.html", "d7/d19/classinfra_1_1_byte_input_stream" ],
    [ "ByteInputStreamReader", "db/d2a/classinfra_1_1_byte_input_stream_reader.html", "db/d2a/classinfra_1_1_byte_input_stream_reader" ],
    [ "ByteOutputStream", "df/d3a/classinfra_1_1_byte_output_stream.html", "df/d3a/classinfra_1_1_byte_output_stream" ],
    [ "ByteOutputStreamWriter", "df/d15/classinfra_1_1_byte_output_stream_writer.html", "df/d15/classinfra_1_1_byte_output_stream_writer" ],
    [ "CanCall", "dd/da8/structinfra_1_1_can_call.html", null ],
    [ "CanCall< ResultType(Args...)>", "d5/d15/structinfra_1_1_can_call_3_01_result_type_07_args_8_8_8_08_4.html", null ],
    [ "CanCallHelper", "d3/d32/structinfra_1_1_can_call_helper.html", "d3/d32/structinfra_1_1_can_call_helper" ],
    [ "ClaimableResource", "d0/d93/classinfra_1_1_claimable_resource.html", "d0/d93/classinfra_1_1_claimable_resource" ],
    [ "CountingDataInputStream", "df/db7/classinfra_1_1_counting_data_input_stream.html", null ],
    [ "CountingStreamReader", "d1/dc1/classinfra_1_1_counting_stream_reader.html", "d1/dc1/classinfra_1_1_counting_stream_reader" ],
    [ "CountingTextInputStream", "d8/d71/classinfra_1_1_counting_text_input_stream.html", null ],
    [ "CrcCcittCalculator", "dc/d3c/classinfra_1_1_crc_ccitt_calculator.html", "dc/d3c/classinfra_1_1_crc_ccitt_calculator" ],
    [ "Creator", "d6/d7c/classinfra_1_1_creator.html", null ],
    [ "Creator< T, U, void(ConstructionArgs...)>", "da/d5e/classinfra_1_1_creator_3_01_t_00_01_u_00_01void_07_construction_args_8_8_8_08_4.html", "da/d5e/classinfra_1_1_creator_3_01_t_00_01_u_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "Creator< void, U, void(ConstructionArgs...)>", "d5/daa/classinfra_1_1_creator_3_01void_00_01_u_00_01void_07_construction_args_8_8_8_08_4.html", "d5/daa/classinfra_1_1_creator_3_01void_00_01_u_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "CreatorBase", "de/de6/classinfra_1_1_creator_base.html", null ],
    [ "CreatorBase< T, void(ConstructionArgs...)>", "de/de2/classinfra_1_1_creator_base_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "de/de2/classinfra_1_1_creator_base_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "CreatorBase< void, void(ConstructionArgs...)>", "d9/dab/classinfra_1_1_creator_base_3_01void_00_01void_07_construction_args_8_8_8_08_4.html", "d9/dab/classinfra_1_1_creator_base_3_01void_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "CreatorExternal", "d3/df0/classinfra_1_1_creator_external.html", null ],
    [ "CreatorExternal< T, void(ConstructionArgs...)>", "d0/d4d/classinfra_1_1_creator_external_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "d0/d4d/classinfra_1_1_creator_external_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "CyclicBuffer", "d0/dd8/classinfra_1_1_cyclic_buffer.html", "d0/dd8/classinfra_1_1_cyclic_buffer" ],
    [ "Data", "d4/def/structinfra_1_1_data.html", null ],
    [ "DataInputStream", "d0/db4/classinfra_1_1_data_input_stream.html", "d0/db4/classinfra_1_1_data_input_stream" ],
    [ "DataOutputStream", "d6/d7d/classinfra_1_1_data_output_stream.html", "d6/d7d/classinfra_1_1_data_output_stream" ],
    [ "Deallocator", "d0/ddc/classinfra_1_1_deallocator.html", "d0/ddc/classinfra_1_1_deallocator" ],
    [ "DelayedProxyCreator", "dd/dfd/classinfra_1_1_delayed_proxy_creator.html", null ],
    [ "DelayedProxyCreator< T, void(ConstructionArgs...)>", "d7/d85/classinfra_1_1_delayed_proxy_creator_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "d7/d85/classinfra_1_1_delayed_proxy_creator_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "DerivedTimerService", "db/d9d/classinfra_1_1_derived_timer_service.html", "db/d9d/classinfra_1_1_derived_timer_service" ],
    [ "enable_if<(Unit1First::identifier< Unit2First::identifier)>::type >", "d5/d64/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_unit1_first_00_01_unit1_others_8_8_8_01_46298adc4ab4a29ef66ed793c9b540462.html", "d5/d64/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_unit1_first_00_01_unit1_others_8_8_8_01_46298adc4ab4a29ef66ed793c9b540462" ],
    [ "EnableSharedFromThis", "dd/df1/classinfra_1_1_enable_shared_from_this.html", "dd/df1/classinfra_1_1_enable_shared_from_this" ],
    [ "Endl", "de/d96/structinfra_1_1_endl.html", null ],
    [ "Equals", "dd/d99/classinfra_1_1_equals.html", "dd/d99/classinfra_1_1_equals" ],
    [ "EventDispatcherConnector", "d3/d09/classinfra_1_1_event_dispatcher_connector.html", "d3/d09/classinfra_1_1_event_dispatcher_connector" ],
    [ "EventDispatcherWithWeakPtrConnector", "d8/d3a/classinfra_1_1_event_dispatcher_with_weak_ptr_connector.html", "d8/d3a/classinfra_1_1_event_dispatcher_with_weak_ptr_connector" ],
    [ "EventDispatcherWithWeakPtrWorker", "de/d88/classinfra_1_1_event_dispatcher_with_weak_ptr_worker.html", "de/d88/classinfra_1_1_event_dispatcher_with_weak_ptr_worker" ],
    [ "EventDispatcherWorker", "d7/d34/classinfra_1_1_event_dispatcher_worker.html", "d7/d34/classinfra_1_1_event_dispatcher_worker" ],
    [ "EventDispatcherWorkerImpl", "da/d78/classinfra_1_1_event_dispatcher_worker_impl.html", "da/d78/classinfra_1_1_event_dispatcher_worker_impl" ],
    [ "Execute", "d1/dad/classinfra_1_1_execute.html", "d1/dad/classinfra_1_1_execute" ],
    [ "ExecuteOnDestruction", "d2/dae/classinfra_1_1_execute_on_destruction.html", "d2/dae/classinfra_1_1_execute_on_destruction" ],
    [ "ExistsInList", "da/de9/structinfra_1_1_exists_in_list.html", null ],
    [ "ExistsInList< List< Element, Tail... >, Element >", "d5/d03/structinfra_1_1_exists_in_list_3_01_list_3_01_element_00_01_tail_8_8_8_01_4_00_01_element_01_4.html", null ],
    [ "ExistsInList< List< Head, Tail... >, Element >", "de/d77/structinfra_1_1_exists_in_list_3_01_list_3_01_head_00_01_tail_8_8_8_01_4_00_01_element_01_4.html", null ],
    [ "ExistsInList< List<>, Element >", "d4/d8d/structinfra_1_1_exists_in_list_3_01_list_3_4_00_01_element_01_4.html", null ],
    [ "ExistsInTypeList", "dd/d24/structinfra_1_1_exists_in_type_list.html", null ],
    [ "ExistsInTypeList< U >", "d1/dc4/structinfra_1_1_exists_in_type_list_3_01_u_01_4.html", null ],
    [ "ExistsInTypeList< U, Front, Tail... >", "de/dab/structinfra_1_1_exists_in_type_list_3_01_u_00_01_front_00_01_tail_8_8_8_01_4.html", null ],
    [ "ExistsInTypeList< U, U, Tail... >", "d4/d06/structinfra_1_1_exists_in_type_list_3_01_u_00_01_u_00_01_tail_8_8_8_01_4.html", null ],
    [ "FixedPoint", "da/d82/structinfra_1_1_fixed_point.html", "da/d82/structinfra_1_1_fixed_point" ],
    [ "FromBase64Helper", "de/d5f/classinfra_1_1_from_base64_helper.html", "de/d5f/classinfra_1_1_from_base64_helper" ],
    [ "Front", "d8/ddb/structinfra_1_1_front.html", "d8/ddb/structinfra_1_1_front" ],
    [ "Function", "da/d07/classinfra_1_1_function.html", null ],
    [ "Function< Result(Args...), ExtraSize >", "d4/d2a/classinfra_1_1_function_3_01_result_07_args_8_8_8_08_00_01_extra_size_01_4.html", "d4/d2a/classinfra_1_1_function_3_01_result_07_args_8_8_8_08_00_01_extra_size_01_4" ],
    [ "Hex", "dc/dfa/structinfra_1_1_hex.html", null ],
    [ "Identity", "dc/d26/structinfra_1_1_identity.html", null ],
    [ "IndexInTypeList", "d0/dcd/structinfra_1_1_index_in_type_list.html", null ],
    [ "IndexInTypeList< U, Front, Tail... >", "dc/dba/structinfra_1_1_index_in_type_list_3_01_u_00_01_front_00_01_tail_8_8_8_01_4.html", null ],
    [ "IndexInTypeList< U, U, Tail... >", "d6/d18/structinfra_1_1_index_in_type_list_3_01_u_00_01_u_00_01_tail_8_8_8_01_4.html", null ],
    [ "InPlace", "da/de8/structinfra_1_1_in_place.html", null ],
    [ "InPlaceType", "df/d7d/structinfra_1_1_in_place_type.html", null ],
    [ "InputStream", "db/dda/classinfra_1_1_input_stream.html", "db/dda/classinfra_1_1_input_stream" ],
    [ "InterfaceConnector", "d3/d0e/classinfra_1_1_interface_connector.html", "d3/d0e/classinfra_1_1_interface_connector" ],
    [ "IntrusiveBinarySearchTree", "d4/dc7/classinfra_1_1_intrusive_binary_search_tree.html", "d4/dc7/classinfra_1_1_intrusive_binary_search_tree" ],
    [ "IntrusiveForwardList", "d3/d66/classinfra_1_1_intrusive_forward_list.html", "d3/d66/classinfra_1_1_intrusive_forward_list" ],
    [ "IntrusiveList", "df/da4/classinfra_1_1_intrusive_list.html", "df/da4/classinfra_1_1_intrusive_list" ],
    [ "IntrusivePriorityQueue", "de/d08/classinfra_1_1_intrusive_priority_queue.html", "de/d08/classinfra_1_1_intrusive_priority_queue" ],
    [ "IntrusiveSet", "df/d47/classinfra_1_1_intrusive_set.html", "df/d47/classinfra_1_1_intrusive_set" ],
    [ "InverseEachUnit", "d8/dc9/structinfra_1_1_inverse_each_unit.html", null ],
    [ "InverseEachUnit< List< Units... > >", "dc/de3/structinfra_1_1_inverse_each_unit_3_01_list_3_01_units_8_8_8_01_4_01_4.html", "dc/de3/structinfra_1_1_inverse_each_unit_3_01_list_3_01_units_8_8_8_01_4_01_4" ],
    [ "IoOutputStream", "dc/d1e/classinfra_1_1_io_output_stream.html", "dc/d1e/classinfra_1_1_io_output_stream" ],
    [ "IoOutputStreamWriter", "d3/dc1/classinfra_1_1_io_output_stream_writer.html", "d3/dc1/classinfra_1_1_io_output_stream_writer" ],
    [ "JsonArray", "d4/d83/classinfra_1_1_json_array.html", "d4/d83/classinfra_1_1_json_array" ],
    [ "JsonArrayFormatter", "df/d1e/classinfra_1_1_json_array_formatter.html", "df/d1e/classinfra_1_1_json_array_formatter" ],
    [ "JsonArrayIterator", "d8/ddc/classinfra_1_1_json_array_iterator.html", "d8/ddc/classinfra_1_1_json_array_iterator" ],
    [ "JsonArrayVisitor", "da/d3e/classinfra_1_1_json_array_visitor.html", "da/d3e/classinfra_1_1_json_array_visitor" ],
    [ "JsonInputStream", "d5/d79/classinfra_1_1_json_input_stream.html", "d5/d79/classinfra_1_1_json_input_stream" ],
    [ "JsonInputStreamReader", "d5/d11/classinfra_1_1_json_input_stream_reader.html", "d5/d11/classinfra_1_1_json_input_stream_reader" ],
    [ "JsonIterator", "df/dd0/classinfra_1_1_json_iterator.html", "df/dd0/classinfra_1_1_json_iterator" ],
    [ "JsonKeyValue", "d1/d53/structinfra_1_1_json_key_value.html", "d1/d53/structinfra_1_1_json_key_value" ],
    [ "JsonObject", "d1/dcf/classinfra_1_1_json_object.html", "d1/dcf/classinfra_1_1_json_object" ],
    [ "JsonObjectFormatter", "d5/d0c/classinfra_1_1_json_object_formatter.html", "d5/d0c/classinfra_1_1_json_object_formatter" ],
    [ "JsonObjectIterator", "dd/d2a/classinfra_1_1_json_object_iterator.html", "dd/d2a/classinfra_1_1_json_object_iterator" ],
    [ "JsonObjectVisitor", "d8/d16/classinfra_1_1_json_object_visitor.html", "d8/d16/classinfra_1_1_json_object_visitor" ],
    [ "JsonStreamingObjectParser", "d3/d88/classinfra_1_1_json_streaming_object_parser.html", "d3/d88/classinfra_1_1_json_streaming_object_parser" ],
    [ "JsonString", "d1/d16/classinfra_1_1_json_string.html", "d1/d16/classinfra_1_1_json_string" ],
    [ "JsonStringIterator", "d1/d67/classinfra_1_1_json_string_iterator.html", "d1/d67/classinfra_1_1_json_string_iterator" ],
    [ "JsonStringStream", "df/d64/classinfra_1_1_json_string_stream.html", "df/d64/classinfra_1_1_json_string_stream" ],
    [ "JsonSubArrayParser", "d2/d36/classinfra_1_1_json_sub_array_parser.html", "d2/d36/classinfra_1_1_json_sub_array_parser" ],
    [ "JsonSubObjectParser", "d2/d55/classinfra_1_1_json_sub_object_parser.html", "d2/d55/classinfra_1_1_json_sub_object_parser" ],
    [ "JsonSubParser", "dd/d09/classinfra_1_1_json_sub_parser.html", "dd/d09/classinfra_1_1_json_sub_parser" ],
    [ "JsonTokenizer", "d3/d5c/classinfra_1_1_json_tokenizer.html", "d3/d5c/classinfra_1_1_json_tokenizer" ],
    [ "JsonValueArrayIterator", "d8/d55/classinfra_1_1_json_value_array_iterator.html", "d8/d55/classinfra_1_1_json_value_array_iterator" ],
    [ "JsonVisitor", "df/d20/classinfra_1_1_json_visitor.html", "df/d20/classinfra_1_1_json_visitor" ],
    [ "LessThan", "da/da0/classinfra_1_1_less_than.html", "da/da0/classinfra_1_1_less_than" ],
    [ "LimitedDataInputStream", "dc/da9/classinfra_1_1_limited_data_input_stream.html", null ],
    [ "LimitedDataOutputStream", "d9/daf/classinfra_1_1_limited_data_output_stream.html", null ],
    [ "LimitedStreamReader", "d9/db6/classinfra_1_1_limited_stream_reader.html", "d9/db6/classinfra_1_1_limited_stream_reader" ],
    [ "LimitedStreamWriter", "dd/d12/classinfra_1_1_limited_stream_writer.html", "dd/d12/classinfra_1_1_limited_stream_writer" ],
    [ "LimitedTextInputStream", "d1/d4f/classinfra_1_1_limited_text_input_stream.html", null ],
    [ "LimitedTextOutputStream", "d7/d1d/classinfra_1_1_limited_text_output_stream.html", null ],
    [ "List", "df/dc1/structinfra_1_1_list.html", null ],
    [ "ListJoin", "d6/df1/structinfra_1_1_list_join.html", null ],
    [ "ListJoin< List< ListA... >, List< ListB... > >", "d8/dd1/structinfra_1_1_list_join_3_01_list_3_01_list_a_8_8_8_01_4_00_01_list_3_01_list_b_8_8_8_01_4_01_4.html", "d8/dd1/structinfra_1_1_list_join_3_01_list_3_01_list_a_8_8_8_01_4_00_01_list_3_01_list_b_8_8_8_01_4_01_4" ],
    [ "ListPushBack", "dc/daf/structinfra_1_1_list_push_back.html", null ],
    [ "ListPushBack< List< ListElements... >, Elements... >", "d3/d55/structinfra_1_1_list_push_back_3_01_list_3_01_list_elements_8_8_8_01_4_00_01_elements_8_8_8_01_4.html", "d3/d55/structinfra_1_1_list_push_back_3_01_list_3_01_list_elements_8_8_8_01_4_00_01_elements_8_8_8_01_4" ],
    [ "ListPushFront", "d8/d09/structinfra_1_1_list_push_front.html", null ],
    [ "ListPushFront< Element, List< ListElements... > >", "d5/d55/structinfra_1_1_list_push_front_3_01_element_00_01_list_3_01_list_elements_8_8_8_01_4_01_4.html", "d5/d55/structinfra_1_1_list_push_front_3_01_element_00_01_list_3_01_list_elements_8_8_8_01_4_01_4" ],
    [ "LowPowerEventDispatcherWorker", "dd/d44/classinfra_1_1_low_power_event_dispatcher_worker.html", "dd/d44/classinfra_1_1_low_power_event_dispatcher_worker" ],
    [ "LowPowerStrategy", "db/da4/classinfra_1_1_low_power_strategy.html", "db/da4/classinfra_1_1_low_power_strategy" ],
    [ "MainClockReference", "d3/d8e/classinfra_1_1_main_clock_reference.html", "d3/d8e/classinfra_1_1_main_clock_reference" ],
    [ "MakePolymorphicVariantOver", "d2/d89/structinfra_1_1_make_polymorphic_variant_over.html", null ],
    [ "MakePolymorphicVariantOver< Base, List< T... > >", "d1/d71/structinfra_1_1_make_polymorphic_variant_over_3_01_base_00_01_list_3_01_t_8_8_8_01_4_01_4.html", "d1/d71/structinfra_1_1_make_polymorphic_variant_over_3_01_base_00_01_list_3_01_t_8_8_8_01_4_01_4" ],
    [ "MakeVariantOver", "d3/d3b/structinfra_1_1_make_variant_over.html", null ],
    [ "MakeVariantOver< List< T... > >", "d5/d46/structinfra_1_1_make_variant_over_3_01_list_3_01_t_8_8_8_01_4_01_4.html", "d5/d46/structinfra_1_1_make_variant_over_3_01_list_3_01_t_8_8_8_01_4_01_4" ],
    [ "Max", "d2/d94/structinfra_1_1_max.html", null ],
    [ "MaxAlignmentOfTypes", "d5/dec/structinfra_1_1_max_alignment_of_types.html", null ],
    [ "MaxAlignmentOfTypes< Front >", "d9/ddf/structinfra_1_1_max_alignment_of_types_3_01_front_01_4.html", null ],
    [ "MaxAlignmentOfTypes< Front, Tail... >", "d6/d67/structinfra_1_1_max_alignment_of_types_3_01_front_00_01_tail_8_8_8_01_4.html", null ],
    [ "MaxAlignmentType", "da/df0/structinfra_1_1_max_alignment_type.html", null ],
    [ "MaxAlignmentType< Front >", "d6/d5e/structinfra_1_1_max_alignment_type_3_01_front_01_4.html", "d6/d5e/structinfra_1_1_max_alignment_type_3_01_front_01_4" ],
    [ "MaxAlignmentType< Front, Tail... >", "d1/dfd/structinfra_1_1_max_alignment_type_3_01_front_00_01_tail_8_8_8_01_4.html", "d1/dfd/structinfra_1_1_max_alignment_type_3_01_front_00_01_tail_8_8_8_01_4" ],
    [ "MaxSizeOfTypes", "df/dbf/structinfra_1_1_max_size_of_types.html", null ],
    [ "MaxSizeOfTypes< Front >", "dd/df0/structinfra_1_1_max_size_of_types_3_01_front_01_4.html", null ],
    [ "MaxSizeOfTypes< Front, Tail... >", "d8/d7d/structinfra_1_1_max_size_of_types_3_01_front_00_01_tail_8_8_8_01_4.html", null ],
    [ "MemoryRange", "d0/d6d/classinfra_1_1_memory_range.html", "d0/d6d/classinfra_1_1_memory_range" ],
    [ "Min", "dd/db2/structinfra_1_1_min.html", null ],
    [ "MultiplyTwoUnitLists", "de/da4/structinfra_1_1_multiply_two_unit_lists.html", [
      [ "type >", "d1/d59/structinfra_1_1_multiply_two_unit_lists_1_1type_01_4.html", "d1/d59/structinfra_1_1_multiply_two_unit_lists_1_1type_01_4" ]
    ] ],
    [ "MultiplyTwoUnitLists< List< Unit1First, Unit1Others... >, List< Unit2First, Unit2Others... >, typename std::enable_if<(Unit1First::identifier==Unit2First::identifier &&Unit1First::dimension+Unit2First::dimension !=0)>::type >", "db/d6a/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_unit1_first_00_01_unit1_others_8_8_8_01_4349e7e67cbc1d39731d522a6422d0c3b.html", "db/d6a/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_unit1_first_00_01_unit1_others_8_8_8_01_4349e7e67cbc1d39731d522a6422d0c3b" ],
    [ "MultiplyTwoUnitLists< List< Unit1First, Unit1Others... >, List< Unit2First, Unit2Others... >, typename std::enable_if<(Unit1First::identifier==Unit2First::identifier &&Unit1First::dimension+Unit2First::dimension==0)>::type >", "d7/d01/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_unit1_first_00_01_unit1_others_8_8_8_01_43a8790b346d10cf159008e01b27b05c9.html", "d7/d01/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_unit1_first_00_01_unit1_others_8_8_8_01_43a8790b346d10cf159008e01b27b05c9" ],
    [ "MultiplyTwoUnitLists< List< Units... >, List<> >", "d8/deb/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_units_8_8_8_01_4_00_01_list_3_4_01_4.html", "d8/deb/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_01_units_8_8_8_01_4_00_01_list_3_4_01_4" ],
    [ "MultiplyTwoUnitLists< List<>, List< Units... > >", "d1/dc4/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_4_00_01_list_3_01_units_8_8_8_01_4_01_4.html", "d1/dc4/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_4_00_01_list_3_01_units_8_8_8_01_4_01_4" ],
    [ "MultiplyTwoUnitLists< List<>, List<> >", "d8/d2e/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_4_00_01_list_3_4_01_4.html", "d8/d2e/structinfra_1_1_multiply_two_unit_lists_3_01_list_3_4_00_01_list_3_4_01_4" ],
    [ "MultiplyUnits", "d1/d23/structinfra_1_1_multiply_units.html", null ],
    [ "MultiplyUnits< Unit >", "d9/de9/structinfra_1_1_multiply_units_3_01_unit_01_4.html", "d9/de9/structinfra_1_1_multiply_units_3_01_unit_01_4" ],
    [ "MultiplyUnits< Unit1, Unit2, OtherUnits... >", "de/d2a/structinfra_1_1_multiply_units_3_01_unit1_00_01_unit2_00_01_other_units_8_8_8_01_4.html", "de/d2a/structinfra_1_1_multiply_units_3_01_unit1_00_01_unit2_00_01_other_units_8_8_8_01_4" ],
    [ "NoFail", "d0/db1/structinfra_1_1_no_fail.html", null ],
    [ "None", "d2/d4a/structinfra_1_1_none.html", null ],
    [ "NotifyingSharedOptional", "d4/d52/classinfra_1_1_notifying_shared_optional.html", "d4/d52/classinfra_1_1_notifying_shared_optional" ],
    [ "NullType", "d7/d75/structinfra_1_1_null_type.html", null ],
    [ "Observer", "d9/dd4/classinfra_1_1_observer.html", "d9/dd4/classinfra_1_1_observer" ],
    [ "Optional", "dc/df7/classinfra_1_1_optional.html", "dc/df7/classinfra_1_1_optional" ],
    [ "OptionalForPolymorphicObjects", "df/d2f/classinfra_1_1_optional_for_polymorphic_objects.html", "df/d2f/classinfra_1_1_optional_for_polymorphic_objects" ],
    [ "OutputStream", "d6/d97/classinfra_1_1_output_stream.html", "d6/d97/classinfra_1_1_output_stream" ],
    [ "OverwriteDataStream", "d1/df1/classinfra_1_1_overwrite_data_stream.html", null ],
    [ "OverwriteStreamWriter", "dc/dcc/classinfra_1_1_overwrite_stream_writer.html", "dc/dcc/classinfra_1_1_overwrite_stream_writer" ],
    [ "OverwriteTextStream", "d4/d59/classinfra_1_1_overwrite_text_stream.html", null ],
    [ "PolymorphicVariant", "de/dcd/classinfra_1_1_polymorphic_variant.html", "de/dcd/classinfra_1_1_polymorphic_variant" ],
    [ "PrintParameterNames", "d4/dfd/structinfra_1_1_print_parameter_names.html", null ],
    [ "PrintParameterNames< Arg >", "db/d32/structinfra_1_1_print_parameter_names_3_01_arg_01_4.html", "db/d32/structinfra_1_1_print_parameter_names_3_01_arg_01_4" ],
    [ "PrintParameterNames< Arg, Arg2, Args... >", "db/d7e/structinfra_1_1_print_parameter_names_3_01_arg_00_01_arg2_00_01_args_8_8_8_01_4.html", "db/d7e/structinfra_1_1_print_parameter_names_3_01_arg_00_01_arg2_00_01_args_8_8_8_01_4" ],
    [ "PrintParameterNames<>", "d8/d2b/structinfra_1_1_print_parameter_names_3_4.html", "d8/d2b/structinfra_1_1_print_parameter_names_3_4" ],
    [ "ProtoFormatter", "df/d59/classinfra_1_1_proto_formatter.html", "df/d59/classinfra_1_1_proto_formatter" ],
    [ "ProtoLengthDelimited", "d9/de8/classinfra_1_1_proto_length_delimited.html", "d9/de8/classinfra_1_1_proto_length_delimited" ],
    [ "ProtoLengthDelimitedFormatter", "d2/d1b/classinfra_1_1_proto_length_delimited_formatter.html", "d2/d1b/classinfra_1_1_proto_length_delimited_formatter" ],
    [ "ProtoParser", "de/db9/classinfra_1_1_proto_parser.html", "de/db9/classinfra_1_1_proto_parser" ],
    [ "ProxyCreator", "d9/d0a/classinfra_1_1_proxy_creator.html", null ],
    [ "ProxyCreator< CreatorBase< T, void(ConstructionArgs...)> & >", "d4/d20/classinfra_1_1_proxy_creator_3_01_creator_base_3_01_t_00_01void_07_construction_args_8_8_8_08_4_01_6_01_4.html", null ],
    [ "ProxyCreator< T, void(ConstructionArgs...)>", "dc/d83/classinfra_1_1_proxy_creator_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "dc/d83/classinfra_1_1_proxy_creator_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "ProxyCreator< void, void(ConstructionArgs...)>", "da/d71/classinfra_1_1_proxy_creator_3_01void_00_01void_07_construction_args_8_8_8_08_4.html", "da/d71/classinfra_1_1_proxy_creator_3_01void_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "Quantity", "d1/d3a/classinfra_1_1_quantity.html", "d1/d3a/classinfra_1_1_quantity" ],
    [ "QueueForOneReaderOneIrqWriter", "db/de0/classinfra_1_1_queue_for_one_reader_one_irq_writer.html", "db/de0/classinfra_1_1_queue_for_one_reader_one_irq_writer" ],
    [ "ReferenceCountedSingleton", "dc/d46/classinfra_1_1_reference_counted_singleton.html", "dc/d46/classinfra_1_1_reference_counted_singleton" ],
    [ "ReservedProxy", "d5/d83/classinfra_1_1_reserved_proxy.html", "d5/d83/classinfra_1_1_reserved_proxy" ],
    [ "SavedMarkerDataStream", "d5/db8/classinfra_1_1_saved_marker_data_stream.html", null ],
    [ "SavedMarkerStreamWriter", "d5/d41/classinfra_1_1_saved_marker_stream_writer.html", "d5/d41/classinfra_1_1_saved_marker_stream_writer" ],
    [ "SavedMarkerTextStream", "dc/dc2/classinfra_1_1_saved_marker_text_stream.html", null ],
    [ "ScalableDerivedTimerService", "da/dc4/classinfra_1_1_scalable_derived_timer_service.html", "da/dc4/classinfra_1_1_scalable_derived_timer_service" ],
    [ "Scaled", "d9/d77/structinfra_1_1_scaled.html", null ],
    [ "ScaleHelper", "dc/dc1/structinfra_1_1_scale_helper.html", "dc/dc1/structinfra_1_1_scale_helper" ],
    [ "Sequencer", "d8/dcc/classinfra_1_1_sequencer.html", "d8/dcc/classinfra_1_1_sequencer" ],
    [ "SharedObjectAllocator", "d9/d7e/classinfra_1_1_shared_object_allocator.html", null ],
    [ "SharedObjectAllocator< T, void(ConstructionArgs...)>", "dd/d4f/classinfra_1_1_shared_object_allocator_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "dd/d4f/classinfra_1_1_shared_object_allocator_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "SharedObjectAllocatorFixedSize", "dc/d5d/classinfra_1_1_shared_object_allocator_fixed_size.html", null ],
    [ "SharedObjectAllocatorFixedSize< T, void(ConstructionArgs...)>", "d4/d3d/classinfra_1_1_shared_object_allocator_fixed_size_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "d4/d3d/classinfra_1_1_shared_object_allocator_fixed_size_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "SharedObjectAllocatorHeap", "d0/dfc/classinfra_1_1_shared_object_allocator_heap.html", null ],
    [ "SharedObjectAllocatorHeap< T, void(ConstructionArgs...)>", "da/d93/classinfra_1_1_shared_object_allocator_heap_3_01_t_00_01void_07_construction_args_8_8_8_08_4.html", "da/d93/classinfra_1_1_shared_object_allocator_heap_3_01_t_00_01void_07_construction_args_8_8_8_08_4" ],
    [ "SharedObjectDeleter", "da/dcd/classinfra_1_1_shared_object_deleter.html", "da/dcd/classinfra_1_1_shared_object_deleter" ],
    [ "SharedOptional", "d1/d7f/classinfra_1_1_shared_optional.html", "d1/d7f/classinfra_1_1_shared_optional" ],
    [ "SharedPtr", "d1/d17/classinfra_1_1_shared_ptr.html", "d1/d17/classinfra_1_1_shared_ptr" ],
    [ "SingleObserver", "dc/d4c/classinfra_1_1_single_observer.html", "dc/d4c/classinfra_1_1_single_observer" ],
    [ "SoftFail", "d4/d11/structinfra_1_1_soft_fail.html", null ],
    [ "StateInitializing", "d1/de9/structinfra_1_1_state_initializing.html", null ],
    [ "StateRunning", "da/d1f/structinfra_1_1_state_running.html", null ],
    [ "StaticGCD", "d7/d91/structinfra_1_1_static_g_c_d.html", "d7/d91/structinfra_1_1_static_g_c_d" ],
    [ "StaticGCD< 0, Value2 >", "d3/dee/structinfra_1_1_static_g_c_d_3_010_00_01_value2_01_4.html", "d3/dee/structinfra_1_1_static_g_c_d_3_010_00_01_value2_01_4" ],
    [ "StaticGCD< Value1, 0 >", "df/d95/structinfra_1_1_static_g_c_d_3_01_value1_00_010_01_4.html", "df/d95/structinfra_1_1_static_g_c_d_3_01_value1_00_010_01_4" ],
    [ "StaticRationalBase", "d7/dbf/structinfra_1_1_static_rational_base.html", "d7/dbf/structinfra_1_1_static_rational_base" ],
    [ "StaticStorage", "d0/d8c/classinfra_1_1_static_storage.html", "d0/d8c/classinfra_1_1_static_storage" ],
    [ "StaticStorageForPolymorphicObjects", "d5/d39/classinfra_1_1_static_storage_for_polymorphic_objects.html", "d5/d39/classinfra_1_1_static_storage_for_polymorphic_objects" ],
    [ "StaticVisitor", "d2/dca/classinfra_1_1_static_visitor.html", "d2/dca/classinfra_1_1_static_visitor" ],
    [ "StdStringInputStream", "d1/da0/classinfra_1_1_std_string_input_stream.html", "d1/da0/classinfra_1_1_std_string_input_stream" ],
    [ "StdStringInputStreamReader", "dc/dc7/classinfra_1_1_std_string_input_stream_reader.html", "dc/dc7/classinfra_1_1_std_string_input_stream_reader" ],
    [ "StdStringOutputStream", "d8/d6a/classinfra_1_1_std_string_output_stream.html", "d8/d6a/classinfra_1_1_std_string_output_stream" ],
    [ "StdStringOutputStreamWriter", "db/d61/classinfra_1_1_std_string_output_stream_writer.html", "db/d61/classinfra_1_1_std_string_output_stream_writer" ],
    [ "StdVectorInputStream", "dd/d82/classinfra_1_1_std_vector_input_stream.html", "dd/d82/classinfra_1_1_std_vector_input_stream" ],
    [ "StdVectorInputStreamReader", "d7/def/classinfra_1_1_std_vector_input_stream_reader.html", "d7/def/classinfra_1_1_std_vector_input_stream_reader" ],
    [ "StreamErrorPolicy", "d5/d4a/classinfra_1_1_stream_error_policy.html", "d5/d4a/classinfra_1_1_stream_error_policy" ],
    [ "StreamReader", "d2/d90/classinfra_1_1_stream_reader.html", "d2/d90/classinfra_1_1_stream_reader" ],
    [ "StreamReaderWithRewinding", "d0/d1b/classinfra_1_1_stream_reader_with_rewinding.html", "d0/d1b/classinfra_1_1_stream_reader_with_rewinding" ],
    [ "StreamWriter", "de/dba/classinfra_1_1_stream_writer.html", "de/dba/classinfra_1_1_stream_writer" ],
    [ "StreamWriterDummy", "db/db2/classinfra_1_1_stream_writer_dummy.html", "db/db2/classinfra_1_1_stream_writer_dummy" ],
    [ "StreamWriterPrintF", "d1/d3d/classinfra_1_1_stream_writer_print_f.html", "d1/d3d/classinfra_1_1_stream_writer_print_f" ],
    [ "StringInputStream", "d7/d58/classinfra_1_1_string_input_stream.html", "d7/d58/classinfra_1_1_string_input_stream" ],
    [ "StringInputStreamReader", "d8/deb/classinfra_1_1_string_input_stream_reader.html", "d8/deb/classinfra_1_1_string_input_stream_reader" ],
    [ "StringOutputStream", "d7/d2a/classinfra_1_1_string_output_stream.html", "d7/d2a/classinfra_1_1_string_output_stream" ],
    [ "StringOutputStreamWriter", "df/d97/classinfra_1_1_string_output_stream_writer.html", "df/d97/classinfra_1_1_string_output_stream_writer" ],
    [ "Subject", "d1/db2/classinfra_1_1_subject.html", "d1/db2/classinfra_1_1_subject" ],
    [ "Subject< ObserverType_, void >", "df/d0b/classinfra_1_1_subject_3_01_observer_type___00_01void_01_4.html", "df/d0b/classinfra_1_1_subject_3_01_observer_type___00_01void_01_4" ],
    [ "SystemState", "d4/d87/classinfra_1_1_system_state.html", "d4/d87/classinfra_1_1_system_state" ],
    [ "SystemStateBase", "dc/da5/classinfra_1_1_system_state_base.html", "dc/da5/classinfra_1_1_system_state_base" ],
    [ "SystemStateManager", "df/d73/classinfra_1_1_system_state_manager.html", "df/d73/classinfra_1_1_system_state_manager" ],
    [ "SystemStateParticipant", "de/d21/classinfra_1_1_system_state_participant.html", "de/d21/classinfra_1_1_system_state_participant" ],
    [ "Text", "dd/d6b/structinfra_1_1_text.html", null ],
    [ "TextInputStream", "d7/d93/classinfra_1_1_text_input_stream.html", "d7/d93/classinfra_1_1_text_input_stream" ],
    [ "TextOutputStream", "de/dad/classinfra_1_1_text_output_stream.html", "de/dad/classinfra_1_1_text_output_stream" ],
    [ "TickOnInterruptTimerService", "df/d2e/classinfra_1_1_tick_on_interrupt_timer_service.html", "df/d2e/classinfra_1_1_tick_on_interrupt_timer_service" ],
    [ "Timer", "d5/da5/classinfra_1_1_timer.html", "d5/da5/classinfra_1_1_timer" ],
    [ "TimerAlternating", "d9/dec/classinfra_1_1_timer_alternating.html", "d9/dec/classinfra_1_1_timer_alternating" ],
    [ "TimerEvolving", "d0/d7e/classinfra_1_1_timer_evolving.html", "d0/d7e/classinfra_1_1_timer_evolving" ],
    [ "TimerLimitedRepeating", "db/d9e/classinfra_1_1_timer_limited_repeating.html", "db/d9e/classinfra_1_1_timer_limited_repeating" ],
    [ "TimerLimitedRepeatingWithClosingAction", "df/d93/classinfra_1_1_timer_limited_repeating_with_closing_action.html", "df/d93/classinfra_1_1_timer_limited_repeating_with_closing_action" ],
    [ "TimerRepeating", "d3/d9e/classinfra_1_1_timer_repeating.html", "d3/d9e/classinfra_1_1_timer_repeating" ],
    [ "TimerService", "da/def/classinfra_1_1_timer_service.html", "da/def/classinfra_1_1_timer_service" ],
    [ "TimerServiceManager", "db/d70/classinfra_1_1_timer_service_manager.html", "db/d70/classinfra_1_1_timer_service_manager" ],
    [ "TimerSingleShot", "d8/d87/classinfra_1_1_timer_single_shot.html", "d8/d87/classinfra_1_1_timer_single_shot" ],
    [ "Tokenizer", "d6/dbd/classinfra_1_1_tokenizer.html", "d6/dbd/classinfra_1_1_tokenizer" ],
    [ "TriggerImmediately", "dc/db5/structinfra_1_1_trigger_immediately.html", null ],
    [ "TupleInvokeHelper", "dc/d1e/structinfra_1_1_tuple_invoke_helper.html", null ],
    [ "TupleInvokeHelper< 0, ResultType, Args... >", "d8/dd0/structinfra_1_1_tuple_invoke_helper_3_010_00_01_result_type_00_01_args_8_8_8_01_4.html", "d8/dd0/structinfra_1_1_tuple_invoke_helper_3_010_00_01_result_type_00_01_args_8_8_8_01_4" ],
    [ "TupleInvokeHelper< 1, ResultType, Args... >", "d7/dbc/structinfra_1_1_tuple_invoke_helper_3_011_00_01_result_type_00_01_args_8_8_8_01_4.html", "d7/dbc/structinfra_1_1_tuple_invoke_helper_3_011_00_01_result_type_00_01_args_8_8_8_01_4" ],
    [ "TupleInvokeHelper< 2, ResultType, Args... >", "de/da3/structinfra_1_1_tuple_invoke_helper_3_012_00_01_result_type_00_01_args_8_8_8_01_4.html", "de/da3/structinfra_1_1_tuple_invoke_helper_3_012_00_01_result_type_00_01_args_8_8_8_01_4" ],
    [ "TupleInvokeHelper< 3, ResultType, Args... >", "dd/d74/structinfra_1_1_tuple_invoke_helper_3_013_00_01_result_type_00_01_args_8_8_8_01_4.html", "dd/d74/structinfra_1_1_tuple_invoke_helper_3_013_00_01_result_type_00_01_args_8_8_8_01_4" ],
    [ "TypeAtIndex", "db/da2/structinfra_1_1_type_at_index.html", null ],
    [ "TypeAtIndex< 0, Front, Tail... >", "da/d0c/structinfra_1_1_type_at_index_3_010_00_01_front_00_01_tail_8_8_8_01_4.html", "da/d0c/structinfra_1_1_type_at_index_3_010_00_01_front_00_01_tail_8_8_8_01_4" ],
    [ "TypeAtIndex< Index, Front, Tail... >", "da/d03/structinfra_1_1_type_at_index_3_01_index_00_01_front_00_01_tail_8_8_8_01_4.html", "da/d03/structinfra_1_1_type_at_index_3_01_index_00_01_front_00_01_tail_8_8_8_01_4" ],
    [ "Unit", "d3/ddf/structinfra_1_1_unit.html", "d3/ddf/structinfra_1_1_unit" ],
    [ "UnitBase", "d0/df9/structinfra_1_1_unit_base.html", "d0/df9/structinfra_1_1_unit_base" ],
    [ "UnitListSame", "df/dbc/structinfra_1_1_unit_list_same.html", "df/dbc/structinfra_1_1_unit_list_same" ],
    [ "UnitListSame< List< UnitListElements1... >, List< UnitListElements1... > >", "d3/d41/structinfra_1_1_unit_list_same_3_01_list_3_01_unit_list_elements1_8_8_8_01_4_00_01_list_3_01_uni38693b26daa8cead4131b7bf9a1eb53a.html", "d3/d41/structinfra_1_1_unit_list_same_3_01_list_3_01_unit_list_elements1_8_8_8_01_4_00_01_list_3_01_uni38693b26daa8cead4131b7bf9a1eb53a" ],
    [ "UnitSame", "d8/d2e/structinfra_1_1_unit_same.html", "d8/d2e/structinfra_1_1_unit_same" ],
    [ "Unscaled", "d2/dd8/structinfra_1_1_unscaled.html", null ],
    [ "Variant", "da/d2a/classinfra_1_1_variant.html", "da/d2a/classinfra_1_1_variant" ],
    [ "WeakPtr", "d3/daa/classinfra_1_1_weak_ptr.html", "d3/daa/classinfra_1_1_weak_ptr" ],
    [ "Width", "d4/daa/structinfra_1_1_width.html", "d4/daa/structinfra_1_1_width" ],
    [ "WithStorage", "d2/d40/classinfra_1_1_with_storage.html", "d2/d40/classinfra_1_1_with_storage" ],
    [ "XmlFormatter", "d7/d34/classinfra_1_1_xml_formatter.html", "d7/d34/classinfra_1_1_xml_formatter" ],
    [ "XmlTagFormatter", "d6/d00/classinfra_1_1_xml_tag_formatter.html", "d6/d00/classinfra_1_1_xml_tag_formatter" ]
];