EMil: infra::ByteInputStreamReader Class Reference
infra::ByteInputStreamReader Class Reference
#include <ByteInputStream.hpp>
Public Types
template<std::size_t Max>
using WithStorage = infra::WithStorage< ByteInputStreamReader, std::array< uint8_t, Max > >
Public Member Functions
ByteInputStreamReader (ConstByteRange range)
ConstByteRange Processed () const
ConstByteRange Remaining () const
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy) override
virtual ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
virtual std::size_t ConstructSaveMarker () const override
virtual void Rewind (std::size_t marker) override
Private Attributes
ConstByteRange range
std::size_t offset = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 9 of file ByteInputStream.hpp.
Member Typedef Documentation
WithStorage
template<std::size_t Max> using infra::ByteInputStreamReader::WithStorage = infra::WithStorage<ByteInputStreamReader, std::array<uint8_t, Max> >
Definition at line 14 of file ByteInputStream.hpp.
Constructor & Destructor Documentation
ByteInputStreamReader()
infra::ByteInputStreamReader::ByteInputStreamReader (ConstByteRange range) explicit
Definition at line 5 of file ByteInputStream.cpp.
         : range(range)
     {}
Member Function Documentation
Available()
std::size_t infra::ByteInputStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 57 of file ByteInputStream.cpp.
References offset, range, and infra::MemoryRange< T >::size().
     {
         return range.size() - offset;
     }
ConstructSaveMarker()
std::size_t infra::ByteInputStreamReader::ConstructSaveMarker () const override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 62 of file ByteInputStream.cpp.
References offset.
     {
         return offset;
     }
Empty()
bool infra::ByteInputStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 52 of file ByteInputStream.cpp.
References offset, range, and infra::MemoryRange< T >::size().
     {
         return offset == range.size();
     }
Extract()
void infra::ByteInputStreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 19 of file ByteInputStream.cpp.
References infra::MemoryRange< T >::begin(), offset, range, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         auto remaining = range.size() - offset;
         errorPolicy.ReportResult(dataRange.size() <= remaining);
         dataRange.shrink_from_back_to(remaining);
         std::copy(range.begin() + offset, range.begin() + offset + dataRange.size(), dataRange.begin());
         offset += dataRange.size();
     }
ExtractContiguousRange()
ConstByteRange infra::ByteInputStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 37 of file ByteInputStream.cpp.
References offset, infra::MemoryRange< T >::pop_front(), range, infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         ConstByteRange result = range;
         result.pop_front(offset);
         result.shrink_from_back_to(max);
         offset += result.size();
         return result;
     }
Peek()
uint8_t infra::ByteInputStreamReader::Peek (StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 28 of file ByteInputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MakeByteRange(), offset, range, infra::StreamErrorPolicy::ReportResult(), and infra::MemoryRange< T >::size().
     {
         uint8_t element;
         ByteRange dataRange(MakeByteRange(element));
         errorPolicy.ReportResult(dataRange.size() <= range.size() - offset);
         std::copy(range.begin() + offset, range.begin() + offset + dataRange.size(), dataRange.begin());
         return element;
     }
PeekContiguousRange()
ConstByteRange infra::ByteInputStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 46 of file ByteInputStream.cpp.
     {
         ConstByteRange result(range.begin() + offset + start, range.end());
         return result;
     }
Processed()
ConstByteRange infra::ByteInputStreamReader::Processed () const
Definition at line 9 of file ByteInputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MakeRange(), offset, and range.
     {
         return MakeRange(range.begin(), range.begin() + offset);
     }
Remaining()
ConstByteRange infra::ByteInputStreamReader::Remaining () const
Definition at line 14 of file ByteInputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), infra::MakeRange(), offset, and range.
     {
         return MakeRange(range.begin() + offset, range.end());
     }
Rewind()
void infra::ByteInputStreamReader::Rewind (std::size_t marker) override virtual
Implements infra::StreamReaderWithRewinding.
Definition at line 67 of file ByteInputStream.cpp.
References offset.
     {
         offset = marker;
     }
Member Data Documentation
offset
std::size_t infra::ByteInputStreamReader::offset = 0 private
Definition at line 33 of file ByteInputStream.hpp.
Referenced by Available(), ConstructSaveMarker(), Empty(), Extract(), ExtractContiguousRange(), Peek(), Processed(), Remaining(), and Rewind().
range
ConstByteRange infra::ByteInputStreamReader::range private
Definition at line 32 of file ByteInputStream.hpp.
Referenced by Available(), Empty(), Extract(), ExtractContiguousRange(), Peek(), Processed(), and Remaining().
The documentation for this class was generated from the following files:
ByteInputStream.hpp
ByteInputStream.cpp