EMil: infra::OutputStream Class Reference
infra::OutputStream Class Reference
#include <OutputStream.hpp>
Public Member Functions
OutputStream (StreamWriter &writer, StreamErrorPolicy &errorPolicy)
bool Failed () const
std::size_t SaveMarker () const
std::size_t ProcessedBytesSince (std::size_t marker) const
std::size_t Available () const
StreamWriter & Writer () const
StreamErrorPolicy & ErrorPolicy () const
Protected Member Functions
~OutputStream ()=default
Private Attributes
StreamWriter & writer
StreamErrorPolicy & errorPolicy
Detailed Description
Definition at line 44 of file OutputStream.hpp.
Constructor & Destructor Documentation
OutputStream()
infra::OutputStream::OutputStream (StreamWriter & writer, StreamErrorPolicy & errorPolicy)
Definition at line 43 of file OutputStream.cpp.
         : writer(writer)
         , errorPolicy(errorPolicy)
     {}
~OutputStream()
infra::OutputStream::~OutputStream () protected default
Member Function Documentation
Available()
std::size_t infra::OutputStream::Available () const
Definition at line 63 of file OutputStream.cpp.
References infra::StreamWriter::Available(), and writer.
     {
         return writer.Available();
     }
ErrorPolicy()
StreamErrorPolicy & infra::OutputStream::ErrorPolicy () const
Definition at line 73 of file OutputStream.cpp.
References errorPolicy.
Referenced by infra::TextOutputStream::FormatArgs(), infra::DataOutputStream::operator<<(), infra::TextOutputStream::operator<<(), infra::TextOutputStream::OutputAsBinary(), infra::TextOutputStream::OutputAsDecimal(), infra::TextOutputStream::OutputAsHexadecimal(), and infra::TextOutputStream::OutputOptionalPadding().
     {
         return errorPolicy;
     }
Failed()
bool infra::OutputStream::Failed () const
Definition at line 48 of file OutputStream.cpp.
References errorPolicy, and infra::StreamErrorPolicy::Failed().
Referenced by infra::Asn1Formatter::Failed(), infra::JsonObjectFormatter::Failed(), and infra::JsonArrayFormatter::Failed().
     {
         return errorPolicy.Failed();
     }
ProcessedBytesSince()
std::size_t infra::OutputStream::ProcessedBytesSince (std::size_t marker) const
Definition at line 58 of file OutputStream.cpp.
References infra::StreamWriter::GetProcessedBytesSince(), and writer.
Referenced by services::HttpResponse::WriteResponse(), and infra::ProtoLengthDelimitedFormatter::~ProtoLengthDelimitedFormatter().
     {
         return writer.GetProcessedBytesSince(marker);
     }
SaveMarker()
std::size_t infra::OutputStream::SaveMarker () const
Definition at line 53 of file OutputStream.cpp.
References infra::StreamWriter::ConstructSaveMarker(), and writer.
Referenced by infra::ProtoLengthDelimitedFormatter::ProtoLengthDelimitedFormatter(), infra::Asn1Formatter::StartBitString(), infra::Asn1Formatter::StartContextSpecific(), infra::Asn1Formatter::StartSequence(), infra::Asn1Formatter::StartSet(), and services::HttpResponse::WriteResponse().
     {
         return writer.ConstructSaveMarker();
     }
Writer()
StreamWriter & infra::OutputStream::Writer () const
Definition at line 68 of file OutputStream.cpp.
References writer.
Referenced by infra::TextOutputStream::FormatArgs(), infra::DataOutputStream::operator<<(), infra::TextOutputStream::operator<<(), infra::TextOutputStream::OutputAsBinary(), infra::TextOutputStream::OutputAsDecimal(), infra::TextOutputStream::OutputAsHexadecimal(), infra::TextOutputStream::OutputOptionalPadding(), services::HttpResponse::WriteResponse(), and infra::SavedMarkerStreamWriter::~SavedMarkerStreamWriter().
     {
         return writer;
     }
Member Data Documentation
errorPolicy
StreamErrorPolicy& infra::OutputStream::errorPolicy private
Definition at line 63 of file OutputStream.hpp.
Referenced by ErrorPolicy(), and Failed().
writer
StreamWriter& infra::OutputStream::writer private
Definition at line 62 of file OutputStream.hpp.
Referenced by Available(), ProcessedBytesSince(), SaveMarker(), and Writer().
The documentation for this class was generated from the following files:
OutputStream.hpp
OutputStream.cpp