EMil: TestQueueForOneReaderOneIrqWriter.cpp File Reference
TestQueueForOneReaderOneIrqWriter.cpp File Reference
Classes
class QueueForOneReaderOneIrqWriterTest
Functions
TEST_F (QueueForOneReaderOneIrqWriterTest, add_element)
TEST_F (QueueForOneReaderOneIrqWriterTest, add_range)
TEST_F (QueueForOneReaderOneIrqWriterTest, consume_1_before_get)
TEST_F (QueueForOneReaderOneIrqWriterTest, get_without_consume_using_array_operator)
TEST_F (QueueForOneReaderOneIrqWriterTest, get_ContiguousRange)
TEST_F (QueueForOneReaderOneIrqWriterTest, get_ContiguousRange_while_queue_is_wrapped)
TEST_F (QueueForOneReaderOneIrqWriterTest, get_ContiguousRange_with_offset)
TEST_F (QueueForOneReaderOneIrqWriterTest, get_ContiguousRange_with_offset_while_queue_is_wrapped)
TEST_F (QueueForOneReaderOneIrqWriterTest, Size)
TEST_F (QueueForOneReaderOneIrqWriterTest, EmptySize)
Function Documentation
TEST_F() [1/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , add_element)
Definition at line 17 of file TestQueueForOneReaderOneIrqWriter.cpp.
 {
     queue.Emplace(buffer, [this]() { queue->Get(); callback.callback(); });
     queue->AddFromInterrupt(0);
     EXPECT_CALL(callback, callback());
     ExecuteAllActions();
     queue->AddFromInterrupt(1);
     EXPECT_CALL(callback, callback());
     ExecuteAllActions();
 }
TEST_F() [2/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , add_range)
Definition at line 30 of file TestQueueForOneReaderOneIrqWriter.cpp.
References data.
 {
     queue.Emplace(buffer, [this]() { while (!queue->Empty()) queue->Get(); callback.callback(); });
     std::array<uint8_t, 2> data = {{ 0, 1 }};
     queue->AddFromInterrupt(data);
     EXPECT_CALL(callback, callback());
     ExecuteAllActions();
 }
TEST_F() [3/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , consume_1_before_get)
Definition at line 40 of file TestQueueForOneReaderOneIrqWriter.cpp.
References EXPECT_EQ().
 {
     queue.Emplace(buffer, [this]() { });
     queue->AddFromInterrupt(0);
     queue->AddFromInterrupt(1);
     queue->Consume(1);
     EXPECT_EQ(1, queue->Get());
 }
TEST_F() [4/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , get_without_consume_using_array_operator)
Definition at line 51 of file TestQueueForOneReaderOneIrqWriter.cpp.
References data, and EXPECT_EQ().
 {
     queue.Emplace(buffer, [this]() {});
     std::array<uint8_t, 4> data = { { 0, 1, 2, 3 } };
     queue->AddFromInterrupt(data);
     EXPECT_EQ(0, (*queue)[0]);
     EXPECT_EQ(3, (*queue)[3]);
     queue->Consume(4);
     queue->AddFromInterrupt(data);
     EXPECT_EQ(0, (*queue)[0]);
     EXPECT_EQ(3, (*queue)[3]);
 }
TEST_F() [5/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , get_ContiguousRange)
Definition at line 68 of file TestQueueForOneReaderOneIrqWriter.cpp.
References data, EXPECT_EQ(), and EXPECT_TRUE().
 {
     queue.Emplace(buffer, [this]() { });
     EXPECT_TRUE(queue->ContiguousRange().empty());
     std::array<uint8_t, 2> data = {{ 0, 1 }};
     queue->AddFromInterrupt(data);
     auto range = queue->ContiguousRange();
     EXPECT_EQ((std::vector<uint8_t>(data.begin(), data.end())), (std::vector<uint8_t>{ range.begin(), range.end() }));
 }
TEST_F() [6/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , get_ContiguousRange_while_queue_is_wrapped)
Definition at line 81 of file TestQueueForOneReaderOneIrqWriter.cpp.
References infra::MemoryRange< T >::begin(), data, infra::MemoryRange< T >::end(), EXPECT_EQ(), and infra::MemoryRange< T >::size().
 {
     queue.Emplace(buffer, [this]() {});
     std::array<uint8_t, 3> data = { { 0, 1, 2 } };
     queue->AddFromInterrupt(data);
     infra::ConstByteRange range = queue->ContiguousRange();
     EXPECT_EQ((std::vector<uint8_t>{0,1,2}), (std::vector<uint8_t>{ range.begin(), range.end() }));
     queue->Consume(3);
     queue->AddFromInterrupt(data);
     range = queue->ContiguousRange();
     EXPECT_EQ((std::vector<uint8_t>{0,1}), (std::vector<uint8_t>{ range.begin(), range.end() }));
     queue->Consume(range.size());
     range = queue->ContiguousRange();
     EXPECT_EQ((std::vector<uint8_t>{2}), (std::vector<uint8_t>{ range.begin(), range.end() }));
 }
TEST_F() [7/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , get_ContiguousRange_with_offset)
Definition at line 100 of file TestQueueForOneReaderOneIrqWriter.cpp.
References infra::MemoryRange< T >::begin(), data, infra::MemoryRange< T >::end(), and EXPECT_EQ().
 {
     queue.Emplace(buffer, [this]() {});
     std::array<uint8_t, 3> data = { { 0, 1, 2 } };
     queue->AddFromInterrupt(data);
     infra::ConstByteRange range = queue->ContiguousRange(1);
     EXPECT_EQ((std::vector<uint8_t>{1, 2}), (std::vector<uint8_t>{ range.begin(), range.end() }));
     queue->Consume(1);
     range = queue->ContiguousRange();
     EXPECT_EQ((std::vector<uint8_t>{1, 2}), (std::vector<uint8_t>{ range.begin(), range.end() }));
 }
TEST_F() [8/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , get_ContiguousRange_with_offset_while_queue_is_wrapped)
Definition at line 115 of file TestQueueForOneReaderOneIrqWriter.cpp.
References infra::MemoryRange< T >::begin(), data, infra::MemoryRange< T >::end(), and EXPECT_EQ().
 {
     queue.Emplace(buffer, [this]() {});
     std::array<uint8_t, 3> data = { { 0, 1, 2 } };
     queue->AddFromInterrupt(data);
     infra::ConstByteRange range = queue->ContiguousRange(2);
     EXPECT_EQ((std::vector<uint8_t>{ 2 }), (std::vector<uint8_t>{ range.begin(), range.end() }));
     queue->Consume(3);
     queue->AddFromInterrupt(data);
     range = queue->ContiguousRange(0);
     EXPECT_EQ((std::vector<uint8_t>{ 0, 1 }), (std::vector<uint8_t>{ range.begin(), range.end() }));
     range = queue->ContiguousRange(2);
     EXPECT_EQ((std::vector<uint8_t>{ 2 }), (std::vector<uint8_t>{ range.begin(), range.end() }));
 }
TEST_F() [9/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , Size)
Definition at line 134 of file TestQueueForOneReaderOneIrqWriter.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     queue.Emplace(buffer, [this]() {});
     std::array<uint8_t, 4> full = { { 3, 1, 2, 4 } };
     std::array<uint8_t, 1> data1 = { { 7 } };
     std::array<uint8_t, 2> data2 = { { 5, 1 } };
     EXPECT_TRUE(queue->Empty());
     EXPECT_FALSE(queue->Full());
     EXPECT_EQ(0, queue->Size());
     queue->AddFromInterrupt(full);
     EXPECT_FALSE(queue->Empty());
     EXPECT_TRUE(queue->Full());
     EXPECT_EQ(4, queue->Size());
     queue->Consume(2);
     EXPECT_EQ(2, queue->Size());
     queue->AddFromInterrupt(data1);
     EXPECT_EQ(3, queue->Size());
     queue->Consume(1);
     EXPECT_EQ(2, queue->Size());
     queue->AddFromInterrupt(data2);
     EXPECT_EQ(4, queue->Size());
 }
TEST_F() [10/10]
TEST_F (QueueForOneReaderOneIrqWriterTest , EmptySize)
Definition at line 161 of file TestQueueForOneReaderOneIrqWriter.cpp.
References EXPECT_EQ().
 {
     queue.Emplace(buffer, [this]() {});
     EXPECT_EQ(sizeof(buffer)-1, queue->EmptySize());
 }