EMil: infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable > Struct Template Reference
infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable > Struct Template Reference
#include <VariantDetail.hpp>
Public Member Functions
Visitor::ResultType operator() (Visitor &visitor, const Variant &variant1, const Variant &variant2)
template<class T >
Visitor::ResultType VisitSecond (Visitor &visitor, const T &v1, const Variant &variant2)
Detailed Description
template<std::size_t Index, class Visitor, class Variant, class Enable = void>
struct infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >
Definition at line 38 of file VariantDetail.hpp.
Member Function Documentation
operator()()
template<std::size_t Index, class Visitor , class Variant , class Enable > Visitor::ResultType infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >::operator() (Visitor & visitor, const Variant & variant1, const Variant & variant2)
Definition at line 274 of file VariantDetail.hpp.
References infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >::VisitSecond(), and infra::Variant< T >::Which().
         {
             if (variant1.Which() == Index)
                 return ApplyVisitorHelper2<0, Visitor, Variant>().VisitSecond(visitor, variant1.template GetAtIndex<Index>(), variant2);
             if (variant1.Which() == Index + 1)
                 return ApplyVisitorHelper2<0, Visitor, Variant>().VisitSecond(visitor, variant1.template GetAtIndex<Index + 1>(), variant2);
             if (variant1.Which() == Index + 2)
                 return ApplyVisitorHelper2<0, Visitor, Variant>().VisitSecond(visitor, variant1.template GetAtIndex<Index + 2>(), variant2);
             if (variant1.Which() == Index + 3)
                 return ApplyVisitorHelper2<0, Visitor, Variant>().VisitSecond(visitor, variant1.template GetAtIndex<Index + 3>(), variant2);
             if (variant1.Which() == Index + 4)
                 return ApplyVisitorHelper2<0, Visitor, Variant>().VisitSecond(visitor, variant1.template GetAtIndex<Index + 4>(), variant2);
             return ApplyVisitorHelper2<Index + 5, Visitor, Variant>()(visitor, variant1, variant2);
         }
VisitSecond()
template<std::size_t Index, class Visitor , class Variant , class Enable > template<class T > Visitor::ResultType infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >::VisitSecond (Visitor & visitor, const T & v1, const Variant & variant2)
Definition at line 292 of file VariantDetail.hpp.
References infra::Variant< T >::Which().
Referenced by infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >::operator()(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+1==Variant::size >::type >::operator()(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+2==Variant::size >::type >::operator()(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+3==Variant::size >::type >::operator()(), and infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+4==Variant::size >::type >::operator()().
         {
             if (variant2.Which() == Index)
                 return visitor(v1, variant2.template GetAtIndex<Index>());
             if (variant2.Which() == Index + 1)
                 return visitor(v1, variant2.template GetAtIndex<Index + 1>());
             if (variant2.Which() == Index + 2)
                 return visitor(v1, variant2.template GetAtIndex<Index + 2>());
             if (variant2.Which() == Index + 3)
                 return visitor(v1, variant2.template GetAtIndex<Index + 3>());
             if (variant2.Which() == Index + 4)
                 return visitor(v1, variant2.template GetAtIndex<Index + 4>());
             return ApplyVisitorHelper2<Index + 5, Visitor, Variant>().VisitSecond(visitor, v1, variant2);
         }
The documentation for this struct was generated from the following file:
VariantDetail.hpp