EMil: TestFixedPoint.cpp File Reference
TestFixedPoint.cpp File Reference
Functions
TEST (FixedPointTest, Construction)
TEST (FixedPointTest, IntegerPart)
TEST (FixedPointTest, FractionalPart)
TEST (FixedPointTest, Rounded)
TEST (FixedPointTest, Addition)
TEST (FixedPointTest, Subtraction)
TEST (FixedPointTest, Multiplication)
TEST (FixedPointTest, Division)
TEST (FixedPointTest, Negation)
TEST (FixedPointTest, Comparisons)
Function Documentation
TEST() [1/10]
TEST (FixedPointTest , Construction)
Definition at line 4 of file TestFixedPoint.cpp.
References EXPECT_EQ(), infra::scaled, and infra::unscaled.
 {
     EXPECT_EQ(0, (infra::FixedPoint<int, 10>().AsUnscaled()));
     EXPECT_EQ(34, (infra::FixedPoint<int, 10>(infra::unscaled, 34).AsUnscaled()));
     EXPECT_EQ(341, (infra::FixedPoint<int, 10>(34, 1).AsUnscaled()));
     EXPECT_EQ(340, (infra::FixedPoint<int, 10>(infra::scaled, 34).AsUnscaled()));
 }
TEST() [2/10]
TEST (FixedPointTest , IntegerPart)
Definition at line 12 of file TestFixedPoint.cpp.
References EXPECT_EQ(), infra::FixedPoint< T, Factor >::IntegerPart(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f(infra::unscaled, 34);
     EXPECT_EQ(3, f.IntegerPart());
 }
TEST() [3/10]
TEST (FixedPointTest , FractionalPart)
Definition at line 18 of file TestFixedPoint.cpp.
References EXPECT_EQ(), infra::FixedPoint< T, Factor >::FractionalPart(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f(infra::unscaled, 34);
     EXPECT_EQ(4, f.FractionalPart());
 }
TEST() [4/10]
TEST (FixedPointTest , Rounded)
Definition at line 24 of file TestFixedPoint.cpp.
References EXPECT_EQ(), and infra::unscaled.
 {
     EXPECT_EQ(3, (infra::FixedPoint<int, 10>(infra::unscaled, 34).Rounded()));
     EXPECT_EQ(4, (infra::FixedPoint<int, 10>(infra::unscaled, 35).Rounded()));
     EXPECT_EQ(-3, (infra::FixedPoint<int, 10>(infra::unscaled, -34).Rounded()));
     EXPECT_EQ(-4, (infra::FixedPoint<int, 10>(infra::unscaled, -35).Rounded()));
 }
TEST() [5/10]
TEST (FixedPointTest , Addition)
Definition at line 32 of file TestFixedPoint.cpp.
References infra::FixedPoint< T, Factor >::AsUnscaled(), EXPECT_EQ(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f1(infra::unscaled, 34);
     infra::FixedPoint<int, 10> f2(infra::unscaled, 15);
     EXPECT_EQ(49, (f1 + f2).AsUnscaled());
     f1 += f2;
     EXPECT_EQ(49, f1.AsUnscaled());
 }
TEST() [6/10]
TEST (FixedPointTest , Subtraction)
Definition at line 43 of file TestFixedPoint.cpp.
References infra::FixedPoint< T, Factor >::AsUnscaled(), EXPECT_EQ(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f1(infra::unscaled, 34);
     infra::FixedPoint<int, 10> f2(infra::unscaled, 15);
     EXPECT_EQ(19, (f1 - f2).AsUnscaled());
     f1 -= f2;
     EXPECT_EQ(19, f1.AsUnscaled());
 }
TEST() [7/10]
TEST (FixedPointTest , Multiplication)
Definition at line 54 of file TestFixedPoint.cpp.
References infra::FixedPoint< T, Factor >::AsUnscaled(), EXPECT_EQ(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f1(infra::unscaled, 34);
     infra::FixedPoint<int, 10> f2(infra::unscaled, 15);
     EXPECT_EQ(51, (f1 * f2).AsUnscaled());
     EXPECT_EQ(68, (f1 * 2).AsUnscaled());
     EXPECT_EQ(68, (2 * f1).AsUnscaled());
     f1 *= f2;
     EXPECT_EQ(51, f1.AsUnscaled());
     f1 *= 2;
     EXPECT_EQ(102, f1.AsUnscaled());
 }
TEST() [8/10]
TEST (FixedPointTest , Division)
Definition at line 69 of file TestFixedPoint.cpp.
References infra::FixedPoint< T, Factor >::AsUnscaled(), EXPECT_EQ(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f1(infra::unscaled, 34);
     infra::FixedPoint<int, 10> f2(infra::unscaled, 15);
     EXPECT_EQ(22, (f1 / f2).AsUnscaled());
     f1 /= f2;
     EXPECT_EQ(22, f1.AsUnscaled());
     EXPECT_EQ(11, (f1 / 2).AsUnscaled());
     EXPECT_EQ(9, (2 / f1).AsUnscaled());
 }
TEST() [9/10]
TEST (FixedPointTest , Negation)
Definition at line 82 of file TestFixedPoint.cpp.
References EXPECT_EQ(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f1(infra::unscaled, 34);
     EXPECT_EQ(-34, (-f1).AsUnscaled());
 }
TEST() [10/10]
TEST (FixedPointTest , Comparisons)
Definition at line 88 of file TestFixedPoint.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::unscaled.
 {
     infra::FixedPoint<int, 10> f1(infra::unscaled, 30);
     infra::FixedPoint<int, 10> f2(infra::unscaled, 15);
     EXPECT_TRUE(f1 == f1);
     EXPECT_FALSE(f1 == f2);
     EXPECT_TRUE(f2 < f1);
     EXPECT_FALSE(f1 < f2);
     EXPECT_FALSE(f1 < f1);
     EXPECT_TRUE(f1 == 3);
     EXPECT_FALSE(f2 == 1);
     EXPECT_FALSE(f2 == 2);
     EXPECT_TRUE(f1 < 4);
     EXPECT_FALSE(f1 < 3);
     EXPECT_TRUE(f2 < 2);
     EXPECT_FALSE(f2 < 1);
     EXPECT_TRUE(f1 > 2);
     EXPECT_FALSE(f1 > 3);
     EXPECT_TRUE(f2 > 1);
     EXPECT_FALSE(f2 > 2);
 }