EMil: application::SecondStageToRamLoader Class Reference
application::SecondStageToRamLoader Class Reference
#include <SecondStageToRamLoader.hpp>
Public Member Functions
SecondStageToRamLoader (hal::SynchronousFlash &upgradePackFlash, const char *product)
bool Load (infra::ByteRange ram, Decryptor &decryptor, const Verifier &verifier, bool override=false)
void MarkAsError (uint32_t errorCode)
Private Member Functions
bool TryLoadImage (infra::ByteRange ram, Decryptor &decryptor)
Private Attributes
hal::SynchronousFlash & upgradePackFlash
const char * product
uint32_t address = 0
Detailed Description
Definition at line 10 of file SecondStageToRamLoader.hpp.
Constructor & Destructor Documentation
SecondStageToRamLoader()
application::SecondStageToRamLoader::SecondStageToRamLoader (hal::SynchronousFlash & upgradePackFlash, const char * product)
Definition at line 7 of file SecondStageToRamLoader.cpp.
         : upgradePackFlash(upgradePackFlash)
         , product(product)
     {}
Member Function Documentation
Load()
bool application::SecondStageToRamLoader::Load (infra::ByteRange ram, Decryptor & decryptor, const Verifier & verifier, bool override = false)
Definition at line 12 of file SecondStageToRamLoader.cpp.
References address, application::deployStarted, application::UpgradePackHeaderEpilogue::headerVersion, application::Verifier::IsValid(), application::UpgradePackHeaderPrologue::magic, infra::MakeByteRange(), MarkAsError(), application::UpgradePackHeaderEpilogue::numberOfImages, product, application::UpgradePackHeaderEpilogue::productName, hal::SynchronousFlash::ReadBuffer(), application::readyToDeploy, application::UpgradePackHeaderPrologue::signatureLength, application::UpgradePackHeaderPrologue::signedContentsLength, application::UpgradePackHeaderPrologue::status, TryLoadImage(), application::upgradeErrorCodeInvalidSignature, application::upgradeErrorCodeNoOrIncorrectSecondStageFound, application::upgradeErrorCodeUnknownHeaderVersion, application::upgradeErrorCodeUnknownProductName, upgradePackFlash, and application::upgradePackMagic.
     {
         UpgradePackHeaderPrologue headerPrologue;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(headerPrologue), address);
         address += sizeof(UpgradePackHeaderPrologue);
         bool sanity = (override || headerPrologue.status == UpgradePackStatus::readyToDeploy || headerPrologue.status == UpgradePackStatus::deployStarted) && headerPrologue.magic == upgradePackMagic;
         if (!sanity)
             return false;
         hal::SynchronousFlash::Range signature(address, address + headerPrologue.signatureLength);
         address += headerPrologue.signatureLength;
         hal::SynchronousFlash::Range signedContents(address, address + headerPrologue.signedContentsLength);
         UpgradePackHeaderEpilogue headerEpilogue;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(headerEpilogue), address);
         address += sizeof(UpgradePackHeaderEpilogue);
         if (headerEpilogue.headerVersion != 1)
             MarkAsError(upgradeErrorCodeUnknownHeaderVersion);
         else if (std::strcmp(product, headerEpilogue.productName.data()) != 0)
             MarkAsError(upgradeErrorCodeUnknownProductName);
         else if (!verifier.IsValid(upgradePackFlash, signature, signedContents))
             MarkAsError(upgradeErrorCodeInvalidSignature);
         else
         {
             for (std::size_t imageIndex = 0; imageIndex != headerEpilogue.numberOfImages; ++imageIndex)
                 if (TryLoadImage(ram, decryptor))
                     return true;
             MarkAsError(upgradeErrorCodeNoOrIncorrectSecondStageFound);
         }
         return false;
     }
MarkAsError()
void application::SecondStageToRamLoader::MarkAsError (uint32_t errorCode)
Definition at line 84 of file SecondStageToRamLoader.cpp.
References application::invalid, infra::MakeByteRange(), upgradePackFlash, and hal::SynchronousFlash::WriteBuffer().
Referenced by Load().
     {
         static const UpgradePackStatus statusError = UpgradePackStatus::invalid;
         upgradePackFlash.WriteBuffer(infra::MakeByteRange(statusError), 0);
         upgradePackFlash.WriteBuffer(infra::MakeByteRange(errorCode), 4);
     }
TryLoadImage()
bool application::SecondStageToRamLoader::TryLoadImage (infra::ByteRange ram, Decryptor & decryptor) private
Definition at line 50 of file SecondStageToRamLoader.cpp.
References address, application::Decryptor::DecryptAndAuthenticate(), application::Decryptor::DecryptPart(), application::ImageHeaderPrologue::lengthOfHeaderAndImage, infra::MakeByteRange(), hal::SynchronousFlash::ReadBuffer(), application::Decryptor::Reset(), infra::MemoryRange< T >::shrink_from_back_to(), infra::MemoryRange< T >::size(), application::Decryptor::StateBuffer(), application::ImageHeaderPrologue::targetName, and upgradePackFlash.
Referenced by Load().
     {
         ImageHeaderPrologue imageHeader;
         upgradePackFlash.ReadBuffer(infra::MakeByteRange(imageHeader), address);
         if (std::strncmp(imageHeader.targetName.data(), "boot2nd", ImageHeaderPrologue().targetName.size()) == 0)
         {
             address += sizeof(imageHeader);
             infra::ByteRange decryptorState = decryptor.StateBuffer();
             upgradePackFlash.ReadBuffer(decryptorState, address);
             decryptor.Reset();
             address += decryptorState.size();
             ImageHeaderEpilogue imageHeaderEpilogue;
             upgradePackFlash.ReadBuffer(infra::MakeByteRange(imageHeaderEpilogue), address);
             address += sizeof(imageHeaderEpilogue);
             decryptor.DecryptPart(infra::MakeByteRange(imageHeaderEpilogue));
             uint32_t imageSize = imageHeader.lengthOfHeaderAndImage - sizeof(imageHeader) - decryptorState.size() - sizeof(imageHeaderEpilogue);
             if (imageSize > ram.size())
                 return false;
             ram.shrink_from_back_to(imageSize);
             upgradePackFlash.ReadBuffer(ram, address);
             return decryptor.DecryptAndAuthenticate(ram);
         }
         address += imageHeader.lengthOfHeaderAndImage;
         return false;
     }
Member Data Documentation
address
uint32_t application::SecondStageToRamLoader::address = 0 private
Definition at line 24 of file SecondStageToRamLoader.hpp.
Referenced by Load(), and TryLoadImage().
product
const char* application::SecondStageToRamLoader::product private
Definition at line 23 of file SecondStageToRamLoader.hpp.
Referenced by Load().
upgradePackFlash
hal::SynchronousFlash& application::SecondStageToRamLoader::upgradePackFlash private
Definition at line 22 of file SecondStageToRamLoader.hpp.
Referenced by Load(), MarkAsError(), and TryLoadImage().
The documentation for this class was generated from the following files:
SecondStageToRamLoader.hpp
SecondStageToRamLoader.cpp