EMil: TestUnit.cpp File Reference
TestUnit.cpp File Reference
Typedefs
typedef infra::Quantity< infra::Meter, int > Meter
typedef infra::Quantity< infra::MilliMeter, int > MilliMeter
typedef infra::Quantity< infra::Second, int > Second
typedef infra::Quantity< infra::Minute, int > Minute
typedef infra::Quantity< infra::Hour, int > Hour
typedef infra::Quantity< infra::Day, int > Day
typedef infra::Quantity< infra::MilliSecond, int > MilliSecond
typedef infra::Quantity< infra::MicroSecond, int > MicroSecond
typedef infra::Quantity< infra::MeterPerSecond, int > MeterPerSecond
typedef infra::Quantity< infra::MilliVolt, int > MilliVolt
typedef infra::Quantity< infra::MicroVolt, int > MicroVolt
typedef infra::Quantity< infra::MilliAmpere, int > MilliAmpere
typedef infra::Quantity< infra::MicroAmpere, int > MicroAmpere
typedef infra::Quantity< infra::KiloOhm, int > KiloOhm
Functions
TEST (UnitTest, ADCUseCase)
TEST (UnitTest, DefaultCreation)
TEST (UnitTest, CreationWithValue)
TEST (UnitTest, CopyConstruction)
TEST (UnitTest, CopyAssignment)
TEST (UnitTest, ConversionToSmallerUnit)
TEST (UnitTest, ConversionToLargerUnit)
TEST (UnitTest, Addition)
TEST (UnitTest, Subtraction)
TEST (UnitTest, Negation)
TEST (UnitTest, MultiplicationByScalar)
TEST (UnitTest, DivisionByScalar)
TEST (UnitTest, Multiplication)
TEST (UnitTest, Division)
Typedef Documentation
Day
typedef infra::Quantity<infra::Day, int> Day
Definition at line 10 of file TestUnit.cpp.
Hour
typedef infra::Quantity<infra::Hour, int> Hour
Definition at line 9 of file TestUnit.cpp.
KiloOhm
typedef infra::Quantity<infra::KiloOhm, int> KiloOhm
Definition at line 20 of file TestUnit.cpp.
Meter
typedef infra::Quantity<infra::Meter, int> Meter
Definition at line 4 of file TestUnit.cpp.
MeterPerSecond
typedef infra::Quantity<infra::MeterPerSecond, int> MeterPerSecond
Definition at line 14 of file TestUnit.cpp.
MicroAmpere
typedef infra::Quantity<infra::MicroAmpere, int> MicroAmpere
Definition at line 19 of file TestUnit.cpp.
MicroSecond
typedef infra::Quantity<infra::MicroSecond, int> MicroSecond
Definition at line 12 of file TestUnit.cpp.
MicroVolt
typedef infra::Quantity<infra::MicroVolt, int> MicroVolt
Definition at line 17 of file TestUnit.cpp.
MilliAmpere
typedef infra::Quantity<infra::MilliAmpere, int> MilliAmpere
Definition at line 18 of file TestUnit.cpp.
MilliMeter
typedef infra::Quantity<infra::MilliMeter, int> MilliMeter
Definition at line 5 of file TestUnit.cpp.
MilliSecond
typedef infra::Quantity<infra::MilliSecond, int> MilliSecond
Definition at line 11 of file TestUnit.cpp.
MilliVolt
typedef infra::Quantity<infra::MilliVolt, int> MilliVolt
Definition at line 16 of file TestUnit.cpp.
Minute
typedef infra::Quantity<infra::Minute, int> Minute
Definition at line 8 of file TestUnit.cpp.
Second
typedef infra::Quantity<infra::Second, int> Second
Definition at line 7 of file TestUnit.cpp.
Function Documentation
TEST() [1/14]
TEST (UnitTest , ADCUseCase)
Definition at line 22 of file TestUnit.cpp.
 {
     // ADC range is 0 - 65535, which corresponds to 0 - 1.023V
     MicroVolt adcToMicroVoltFactor(1024 * 1000 / 65536);
     int adcResult = 4096;   // 1/16 of the ADC range, so corresponds with 0.064V
     MilliVolt voltageAdc = adcResult * adcToMicroVoltFactor;
     // Assume a resistor of 5K from ADC to ground, and a resistor of 10K from ADC to the measured point.
     // In order to calculate the voltage of the measured point:
     KiloOhm resistorAdcToGround(5);
     KiloOhm resistorAdcToMeasured(10);
     MicroAmpere currentThroughResistorToGround = voltageAdc / resistorAdcToGround;
     MilliVolt voltageAcrossResistorToMeasured = currentThroughResistorToGround * resistorAdcToMeasured;
     MilliVolt voltageOfMeasured = voltageAcrossResistorToMeasured + voltageAdc;
 //    voltageOfMeasured = currentThroughResistorToGround * resistorAdcToMeasured + voltageAdc;
 }
TEST() [2/14]
TEST (UnitTest , DefaultCreation)
Definition at line 41 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance;
     EXPECT_EQ(0, distance.Value());
 }
TEST() [3/14]
TEST (UnitTest , CreationWithValue)
Definition at line 48 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(20);
     EXPECT_EQ(20, distance.Value());
 }
TEST() [4/14]
TEST (UnitTest , CopyConstruction)
Definition at line 55 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(20);
     Meter otherDistance(distance);
     EXPECT_EQ(20, otherDistance.Value());
 }
TEST() [5/14]
TEST (UnitTest , CopyAssignment)
Definition at line 63 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(20);
     Meter otherDistance;
     otherDistance = distance;
     EXPECT_EQ(20, otherDistance.Value());
 }
TEST() [6/14]
TEST (UnitTest , ConversionToSmallerUnit)
Definition at line 72 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(20);
     MilliMeter smallerUnit(distance);
     EXPECT_EQ(20000, smallerUnit.Value());
     Day duration(2);
     MicroSecond smallerDuration(duration);
     EXPECT_EQ(1001308160, smallerDuration.Value());
 }
TEST() [7/14]
TEST (UnitTest , ConversionToLargerUnit)
Definition at line 85 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     MilliMeter distance(20999);
     Meter largerDistance(distance);
     EXPECT_EQ(20, largerDistance.Value());
     MilliSecond duration(14400000);
     Hour largerDuration(duration);
     EXPECT_EQ(4, largerDuration.Value());
 }
TEST() [8/14]
TEST (UnitTest , Addition)
Definition at line 98 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance1(5);
     Meter distance2(3);
     Meter sum = distance1 + distance2;
     EXPECT_EQ(8, sum.Value());
     sum = distance1;
     sum += distance2;
     EXPECT_EQ(8, sum.Value());
 }
TEST() [9/14]
TEST (UnitTest , Subtraction)
Definition at line 113 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance1(5);
     Meter distance2(3);
     Meter difference = distance1 - distance2;
     EXPECT_EQ(2, difference.Value());
     difference = distance1;
     difference -= distance2;
     EXPECT_EQ(2, difference.Value());
 }
TEST() [10/14]
TEST (UnitTest , Negation)
Definition at line 128 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(4);
     Meter back = -distance;
     EXPECT_EQ(-4, back.Value());
 }
TEST() [11/14]
TEST (UnitTest , MultiplicationByScalar)
Definition at line 136 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(4);
     distance *= 2;
     EXPECT_EQ(8, distance.Value());
     Meter distance2 = distance * 3;
     EXPECT_EQ(24, distance2.Value());
     Meter distance3 = 3 * distance;
     EXPECT_EQ(24, distance3.Value());
 }
TEST() [12/14]
TEST (UnitTest , DivisionByScalar)
Definition at line 149 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(24);
     distance /= 2;
     EXPECT_EQ(12, distance.Value());
     Meter distance2 = distance / 3;
     EXPECT_EQ(4, distance2.Value());
     infra::Quantity<infra::Meter::Inverse, int> inverseDistance = 24 / distance;
     EXPECT_EQ(2, inverseDistance.Value());
 }
TEST() [13/14]
TEST (UnitTest , Multiplication)
Definition at line 162 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(4);
     Second time(2);
     infra::Quantity<infra::Meter::Mul<infra::Second>, int> distanceTime = distance * time;
     EXPECT_EQ(8, distanceTime.Value());
     distanceTime = time * distance;
     EXPECT_EQ(8, distanceTime.Value());
     MeterPerSecond speed(5);
     distance = speed * time;
     EXPECT_EQ(10, distance.Value());
     distance = time * speed;
     EXPECT_EQ(10, distance.Value());
 }
TEST() [14/14]
TEST (UnitTest , Division)
Definition at line 180 of file TestUnit.cpp.
References EXPECT_EQ(), and infra::Quantity< UnitType, StorageType >::Value().
 {
     Meter distance(24);
     Second time(6);
     MeterPerSecond speed = distance / time;
     EXPECT_EQ(4, speed.Value());
     distance = Meter(20);
     time = distance / speed;
     EXPECT_EQ(5, time.Value());
 }