EMil: hal::Flash Class Reference
hal::Flash Class Reference abstract
#include <Flash.hpp>
Public Member Functions
virtual uint32_t NumberOfSectors () const =0
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const =0
uint32_t TotalSize () const
virtual uint32_t SectorOfAddress (uint32_t address) const =0
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const =0
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone)=0
void EraseAll (infra::Function< void()> onDone)
Protected Member Functions
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 10 of file Flash.hpp.
Constructor & Destructor Documentation
Flash() [1/2]
hal::Flash::Flash () protected default
Flash() [2/2]
hal::Flash::Flash (const Flash & other) protected delete
~Flash()
hal::Flash::~Flash () protected default
Member Function Documentation
AddressOffsetInSector()
uint32_t hal::Flash::AddressOffsetInSector (uint32_t address) const
Definition at line 15 of file Flash.cpp.
References StartOfSector().
Referenced by services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::FlashQuadSpi::PageProgram(), services::FlashQuadSpiSingleSpeed::PageProgram(), services::FlashSpi::PageProgram(), and services::CyclicStore::RecoverEndAddress().
     {
         return address - StartOfSector(address);
     }
AddressOfSector()
virtual uint32_t hal::Flash::AddressOfSector (uint32_t sectorIndex) const pure virtual
Implemented in services::FlashMultipleAccess, services::FlashDelayedInit, services::FlashMultipleAccessMaster, hal::FlashHomogeneous, services::TracingFlash, and services::FlashRegion.
Referenced by services::FlashRegion::AddressOfSector(), services::TracingFlash::AddressOfSector(), services::FlashMultipleAccessMaster::AddressOfSector(), services::FlashDelayedInit::AddressOfSector(), services::CyclicStore::RecoverSector(), StartOfNextSector(), StartOfNextSectorCyclical(), StartOfPreviousSector(), StartOfPreviousSectorCyclical(), StartOfSector(), and TotalSize().
AtStartOfSector()
bool hal::Flash::AtStartOfSector (uint32_t address) const
Definition at line 46 of file Flash.cpp.
References StartOfSector().
Referenced by services::CyclicStore::RecoverEndAddress(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         return StartOfSector(address) == address;
     }
EraseAll()
void hal::Flash::EraseAll (infra::Function< void()> onDone)
Definition at line 56 of file Flash.cpp.
References EraseSectors(), and NumberOfSectors().
Referenced by services::CyclicStore::Clear(), application::DeployPackToExternal::DeployPackToExternal(), services::ConfigurationBlobImpl::Erase(), and services::CyclicStore::Recover().
     {
         EraseSectors(0, NumberOfSectors(), onDone);
     }
EraseSector()
void hal::Flash::EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
Definition at line 51 of file Flash.cpp.
References EraseSectors().
Referenced by services::CyclicStore::EraseSectorIfAtStart().
     {
         EraseSectors(sectorIndex, sectorIndex + 1, onDone);
     }
EraseSectors()
virtual void hal::Flash::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) pure virtual
Implemented in services::FlashMultipleAccess, services::FlashSpi, services::FlashDelayedInit, services::FlashMultipleAccessMaster, services::FlashQuadSpi, services::TracingFlash, and services::FlashRegion.
Referenced by EraseAll(), EraseSector(), services::FlashRegion::EraseSectors(), services::TracingFlash::EraseSectors(), services::FlashMultipleAccessMaster::EraseSectors(), and services::FlashDelayedInit::EraseSectors().
NumberOfSectors()
virtual uint32_t hal::Flash::NumberOfSectors () const pure virtual
Implemented in services::FlashMultipleAccess, services::FlashMultipleAccessMaster, services::FlashDelayedInit, hal::FlashHomogeneous, services::TracingFlash, and services::FlashRegion.
Referenced by EraseAll(), services::FlashRegion::FlashRegion(), services::TracingFlash::NumberOfSectors(), services::FlashDelayedInit::NumberOfSectors(), services::FlashMultipleAccessMaster::NumberOfSectors(), services::CyclicStore::Recover(), StartOfNextSectorCyclical(), StartOfPreviousSectorCyclical(), and TotalSize().
operator=()
Flash& hal::Flash::operator= (const Flash & other) protected delete
ReadBuffer()
virtual void hal::Flash::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) pure virtual
Implemented in services::FlashMultipleAccess, services::FlashSpi, services::FlashQuadSpiCypressFll, services::FlashQuadSpiMicronN25q, services::FlashDelayedInit, services::FlashMultipleAccessMaster, services::FlashQuadSpiSingleSpeed, services::TracingFlash, and services::FlashRegion.
Referenced by application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::EraseSectorIfAtStart(), services::FlashRegion::ReadBuffer(), services::TracingFlash::ReadBuffer(), services::FlashMultipleAccessMaster::ReadBuffer(), services::FlashDelayedInit::ReadBuffer(), services::ConfigurationBlobImpl::Recover(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::RecoverSector(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
SectorOfAddress()
virtual uint32_t hal::Flash::SectorOfAddress (uint32_t address) const pure virtual
Implemented in services::FlashMultipleAccess, services::FlashDelayedInit, services::FlashMultipleAccessMaster, hal::FlashHomogeneous, services::TracingFlash, and services::FlashRegion.
Referenced by services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::CyclicStore::RecoverEndAddress(), services::TracingFlash::SectorOfAddress(), services::FlashRegion::SectorOfAddress(), services::FlashDelayedInit::SectorOfAddress(), services::FlashMultipleAccessMaster::SectorOfAddress(), StartOfNextSector(), StartOfNextSectorCyclical(), StartOfPreviousSector(), StartOfPreviousSectorCyclical(), StartOfSector(), and services::CyclicStore::WriteRange().
SizeOfSector()
virtual uint32_t hal::Flash::SizeOfSector (uint32_t sectorIndex) const pure virtual
Implemented in services::FlashMultipleAccess, services::FlashMultipleAccessMaster, services::FlashDelayedInit, hal::FlashHomogeneous, services::TracingFlash, and services::FlashRegion.
Referenced by services::CyclicStore::FillSectorIfDataDoesNotFit(), services::CyclicStore::RecoverEndAddress(), services::FlashRegion::SizeOfSector(), services::TracingFlash::SizeOfSector(), services::FlashDelayedInit::SizeOfSector(), services::FlashMultipleAccessMaster::SizeOfSector(), TotalSize(), and services::CyclicStore::WriteRange().
StartOfNextSector()
uint32_t hal::Flash::StartOfNextSector (uint32_t address) const
Definition at line 20 of file Flash.cpp.
References AddressOfSector(), and SectorOfAddress().
     {
         return AddressOfSector(SectorOfAddress(address) + 1);
     }
StartOfNextSectorCyclical()
uint32_t hal::Flash::StartOfNextSectorCyclical (uint32_t address) const
Definition at line 30 of file Flash.cpp.
References AddressOfSector(), NumberOfSectors(), and SectorOfAddress().
Referenced by services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::RecoverSector(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         uint32_t sectorIndex = SectorOfAddress(address) + 1;
         if (sectorIndex == NumberOfSectors())
             sectorIndex = 0;
         return AddressOfSector(sectorIndex);
     }
StartOfPreviousSector()
uint32_t hal::Flash::StartOfPreviousSector (uint32_t address) const
Definition at line 25 of file Flash.cpp.
References AddressOfSector(), and SectorOfAddress().
     {
         return AddressOfSector(SectorOfAddress(address) - 1);
     }
StartOfPreviousSectorCyclical()
uint32_t hal::Flash::StartOfPreviousSectorCyclical (uint32_t address) const
Definition at line 38 of file Flash.cpp.
References AddressOfSector(), NumberOfSectors(), and SectorOfAddress().
Referenced by services::CyclicStore::RecoverEndAddress().
     {
         uint32_t sectorIndex = SectorOfAddress(address);
         if (sectorIndex == 0)
             sectorIndex = NumberOfSectors();
         return AddressOfSector(sectorIndex - 1);
     }
StartOfSector()
uint32_t hal::Flash::StartOfSector (uint32_t address) const
Definition at line 10 of file Flash.cpp.
References AddressOfSector(), and SectorOfAddress().
Referenced by AddressOffsetInSector(), and AtStartOfSector().
     {
         return AddressOfSector(SectorOfAddress(address));
     }
TotalSize()
uint32_t hal::Flash::TotalSize () const
Definition at line 5 of file Flash.cpp.
References AddressOfSector(), NumberOfSectors(), and SizeOfSector().
Referenced by services::ConfigurationBlobImpl::ConfigurationBlobImpl(), application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::RecoverEndAddress(), services::CyclicStore::WriteRange(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
     {
         return AddressOfSector(NumberOfSectors() - 1) + SizeOfSector(NumberOfSectors() - 1);
     }
WriteBuffer()
virtual void hal::Flash::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) pure virtual
Implemented in services::FlashMultipleAccess, services::FlashSpi, services::FlashDelayedInit, services::FlashMultipleAccessMaster, services::FlashQuadSpi, services::TracingFlash, and services::FlashRegion.
Referenced by application::DeployPackToExternal::DeployPackToExternal(), services::CyclicStore::EraseSectorIfAtStart(), services::CyclicStore::FillSectorIfDataDoesNotFit(), services::ConfigurationBlobImpl::Write(), services::FlashRegion::WriteBuffer(), services::TracingFlash::WriteBuffer(), services::FlashMultipleAccessMaster::WriteBuffer(), services::FlashDelayedInit::WriteBuffer(), services::CyclicStore::WriteRange(), and services::CyclicStore::WriteSectorStatusIfAtStartOfSector().
The documentation for this class was generated from the following files:
Flash.hpp
Flash.cpp