EMil: TestHttpClientJson.cpp File Reference
TestHttpClientJson.cpp File Reference
Classes
class HttpClientJsonMock
class HttpClientJsonTest
Functions
TEST_F (HttpClientJsonTest, should_do_Get_request_with_correct_headers_when_Connected)
TEST_F (HttpClientJsonTest, unsuccessful_status_is_reported)
TEST_F (HttpClientJsonTest, non_JSON_content_is_rejected)
TEST_F (HttpClientJsonTest, feed_json_data)
TEST_F (HttpClientJsonTest, ParseError_reports_Error)
TEST_F (HttpClientJsonTest, ContentError_during_parsing_closes_connection)
Function Documentation
TEST_F() [1/6]
TEST_F (HttpClientJsonTest , should_do_Get_request_with_correct_headers_when_Connected)
Definition at line 55 of file TestHttpClientJson.cpp.
References services::HttpClientObserver::Connected(), and services::HttpHeadersEquals().
 {
     services::HttpHeaders headers;
     EXPECT_CALL(httpClient, Get("/path", testing::_)).WillOnce(testing::SaveArg<1>(&headers));
     EXPECT_CALL(controller, Headers()).WillOnce(testing::Return(headersIn));
     EXPECT_CALL(controller, TopJsonObjectVisitor()).WillOnce(testing::ReturnRef(jsonObjectVisitor));
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     HttpHeadersEquals({ { "api-version", "1" }, { "authorization", "Bearer xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx" } }, headers);
     EXPECT_CALL(controller, Done());
 }
TEST_F() [2/6]
TEST_F (HttpClientJsonTest , unsuccessful_status_is_reported)
Definition at line 68 of file TestHttpClientJson.cpp.
References services::BadRequest, and services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(httpClient, Get("/path", testing::_));
     EXPECT_CALL(controller, Headers()).WillOnce(testing::Return(headersIn));
     EXPECT_CALL(controller, TopJsonObjectVisitor()).WillOnce(testing::ReturnRef(jsonObjectVisitor));
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(controller, Error(false));
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->StatusAvailable(services::HttpStatusCode::BadRequest);
 }
TEST_F() [3/6]
TEST_F (HttpClientJsonTest , non_JSON_content_is_rejected)
Definition at line 80 of file TestHttpClientJson.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(httpClient, Get("/path", testing::_));
     EXPECT_CALL(controller, Headers()).WillOnce(testing::Return(headersIn));
     EXPECT_CALL(controller, TopJsonObjectVisitor()).WillOnce(testing::ReturnRef(jsonObjectVisitor));
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(controller, Error(false));
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->HeaderAvailable(services::HttpHeader{ "content-type", "application/text" });
 }
TEST_F() [4/6]
TEST_F (HttpClientJsonTest , feed_json_data)
Definition at line 92 of file TestHttpClientJson.cpp.
References services::HttpClientObserver::Connected(), infra::MakeStringByteRange(), and infra::UnOwnedSharedPtr().
 {
     EXPECT_CALL(httpClient, Get("/path", testing::_));
     EXPECT_CALL(controller, Headers()).WillOnce(testing::Return(headersIn));
     EXPECT_CALL(controller, TopJsonObjectVisitor()).WillOnce(testing::ReturnRef(jsonObjectVisitor));
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     testing::StrictMock<infra::StreamReaderMock> reader;
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(false)).WillOnce(testing::Return(true));
     EXPECT_CALL(reader, ExtractContiguousRange(testing::_)).WillOnce(testing::Return(infra::MakeStringByteRange(R"({ "entry": "value" })")));
     EXPECT_CALL(jsonObjectVisitor, VisitString("entry", "value"));
     EXPECT_CALL(jsonObjectVisitor, Close());
     httpClient.observer->BodyAvailable(infra::UnOwnedSharedPtr(reader));
     EXPECT_CALL(controller, Done());
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->BodyComplete();
 }
TEST_F() [5/6]
TEST_F (HttpClientJsonTest , ParseError_reports_Error)
Definition at line 110 of file TestHttpClientJson.cpp.
References services::HttpClientObserver::Connected(), EXPECT_TRUE(), infra::Lambda(), infra::MakeStringByteRange(), and infra::UnOwnedSharedPtr().
 {
     EXPECT_CALL(httpClient, Get("/path", testing::_));
     EXPECT_CALL(controller, Headers()).WillOnce(testing::Return(headersIn));
     EXPECT_CALL(controller, TopJsonObjectVisitor()).WillOnce(testing::ReturnRef(jsonObjectVisitor));
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     testing::StrictMock<infra::StreamReaderMock> reader;
     auto readerPtr(infra::UnOwnedSharedPtr(reader));
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(false));
     EXPECT_CALL(reader, ExtractContiguousRange(testing::_)).WillOnce(testing::Return(infra::MakeStringByteRange(R"({ ] })")));
     EXPECT_CALL(jsonObjectVisitor, ParseError()).WillOnce(infra::Lambda([this]()
     {
         controller.ContentError();
     }));
     EXPECT_CALL(httpClient, Close()).WillOnce(infra::Lambda([this, &readerPtr]()
     {
         controller.ClosingConnection();
         EXPECT_TRUE(readerPtr == nullptr);
     }));
     EXPECT_CALL(controller, Error(false));
     httpClient.observer->BodyAvailable(std::move(readerPtr));
 }
TEST_F() [6/6]
TEST_F (HttpClientJsonTest , ContentError_during_parsing_closes_connection)
Definition at line 134 of file TestHttpClientJson.cpp.
References services::HttpClientObserver::Connected(), infra::MakeStringByteRange(), and infra::UnOwnedSharedPtr().
 {
     EXPECT_CALL(httpClient, Get("/path", testing::_));
     EXPECT_CALL(controller, Headers()).WillOnce(testing::Return(headersIn));
     EXPECT_CALL(controller, TopJsonObjectVisitor()).WillOnce(testing::ReturnRef(jsonObjectVisitor));
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     testing::StrictMock<infra::StreamReaderMock> reader;
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(false)).WillOnce(testing::Return(true));
     EXPECT_CALL(reader, ExtractContiguousRange(testing::_)).WillOnce(testing::Return(infra::MakeStringByteRange(R"({ "entry": "value")")));
     EXPECT_CALL(jsonObjectVisitor, VisitString("entry", "value")).WillOnce(testing::Invoke([this](infra::BoundedConstString, infra::BoundedConstString) { controller.ContentError(); }));
     EXPECT_CALL(controller, Error(false));
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->BodyAvailable(infra::UnOwnedSharedPtr(reader));
 }