EMil: services::NameLookupWin Class Reference
services::NameLookupWin Class Reference
#include <NameLookupWin.hpp>
Public Member Functions
NameLookupWin ()
~NameLookupWin ()
virtual void Lookup (NameResolverResult &result) override
virtual void CancelLookup (NameResolverResult &result) override
Private Member Functions
void Run ()
void LookupIPv4 ()
Private Attributes
std::mutex mutex
std::condition_variable condition
infra::IntrusiveList< NameResolverResult > nameLookup
bool run = true
std::thread lookupThread
NameResolverResult * currentLookup = nullptr
Additional Inherited Members
Protected Member Functions inherited from services::NameResolver
NameResolver ()=default
NameResolver (const NameResolver &other)=delete
NameResolver & operator= (const NameResolver &other)=delete
~NameResolver ()=default
Detailed Description
Definition at line 11 of file NameLookupWin.hpp.
Constructor & Destructor Documentation
NameLookupWin()
services::NameLookupWin::NameLookupWin ()
Definition at line 8 of file NameLookupWin.cpp.
References Run().
         : lookupThread([this]() { Run(); })
     {}
~NameLookupWin()
services::NameLookupWin::~NameLookupWin ()
Definition at line 12 of file NameLookupWin.cpp.
References condition, lookupThread, mutex, and run.
     {
         {
             std::lock_guard<std::mutex> lock(mutex);
             run = false;
             condition.notify_one();
         }
         lookupThread.join();
     }
Member Function Documentation
CancelLookup()
void services::NameLookupWin::CancelLookup (NameResolverResult & result) override virtual
Implements services::NameResolver.
Definition at line 32 of file NameLookupWin.cpp.
References mutex, and nameLookup.
     {
         std::lock_guard<std::mutex> lock(mutex);
         nameLookup.erase(result);
     }
Lookup()
void services::NameLookupWin::Lookup (NameResolverResult & result) override virtual
Implements services::NameResolver.
Definition at line 24 of file NameLookupWin.cpp.
References condition, services::ipv6, mutex, nameLookup, and services::NameResolverResult::Versions().
     {
         assert(result.Versions() != IPVersions::ipv6);
         std::lock_guard<std::mutex> lock(mutex);
         nameLookup.push_back(result);
         condition.notify_one();
     }
LookupIPv4()
void services::NameLookupWin::LookupIPv4 () private
Definition at line 58 of file NameLookupWin.cpp.
References infra::BoundedStringBase< T >::begin(), condition, currentLookup, infra::BoundedStringBase< T >::end(), services::NameResolverResult::Hostname(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), mutex, nameLookup, services::NameResolverResult::NameLookupDone(), services::NameResolverResult::NameLookupFailed(), infra::Now(), and infra::EventDispatcherWorker::Schedule().
Referenced by Run().
     {
         std::string terminatedHostname{ currentLookup->Hostname().begin(), currentLookup->Hostname().end() };
         terminatedHostname.push_back('\0');
         addrinfo* entry;
         int res = getaddrinfo(terminatedHostname.c_str(), nullptr, nullptr, &entry);
         if (res == 0)
             for (; entry != nullptr; entry = entry->ai_next)
                 if (entry->ai_family == AF_INET)
                 {
                     sockaddr_in* address = reinterpret_cast<sockaddr_in*>(entry->ai_addr);
                     auto ipv4Address = services::IPv4Address{ address->sin_addr.s_net, address->sin_addr.s_host, address->sin_addr.s_lh, address->sin_addr.s_impno };
                     infra::EventDispatcher::Instance().Schedule([this, ipv4Address]()
                     {
                         std::lock_guard<std::mutex> lock(mutex);
                         if (&nameLookup.front() == currentLookup)
{
                             nameLookup.pop_front();
                             currentLookup->NameLookupDone(ipv4Address, infra::Now() + std::chrono::minutes(5));
                         }
                         condition.notify_one();
                     });
                     return;
                 }
         infra::EventDispatcher::Instance().Schedule([this]()
         {
             std::unique_lock<std::mutex> lock(mutex);
             if (&nameLookup.front() == currentLookup)
             {
                 nameLookup.pop_front();
                 auto lookup = currentLookup;
                 lock.unlock();
                 lookup->NameLookupFailed();
             }
             condition.notify_one();
         });
     }
Run()
void services::NameLookupWin::Run () private
Definition at line 38 of file NameLookupWin.cpp.
References condition, currentLookup, LookupIPv4(), mutex, nameLookup, and run.
Referenced by NameLookupWin().
     {
         std::unique_lock<std::mutex> lock(mutex);
         while (run)
         {
             if (!nameLookup.empty())
             {
                 currentLookup = &nameLookup.front();
                 lock.unlock();
                 LookupIPv4();
                 lock.lock();
             }
             if (run)
                 condition.wait(lock);
         }
     }
Member Data Documentation
condition
std::condition_variable services::NameLookupWin::condition private
Definition at line 27 of file NameLookupWin.hpp.
Referenced by Lookup(), LookupIPv4(), Run(), and ~NameLookupWin().
currentLookup
NameResolverResult* services::NameLookupWin::currentLookup = nullptr private
Definition at line 31 of file NameLookupWin.hpp.
Referenced by LookupIPv4(), and Run().
lookupThread
std::thread services::NameLookupWin::lookupThread private
Definition at line 30 of file NameLookupWin.hpp.
Referenced by ~NameLookupWin().
mutex
std::mutex services::NameLookupWin::mutex private
Definition at line 26 of file NameLookupWin.hpp.
Referenced by CancelLookup(), Lookup(), LookupIPv4(), Run(), and ~NameLookupWin().
nameLookup
infra::IntrusiveList<NameResolverResult> services::NameLookupWin::nameLookup private
Definition at line 28 of file NameLookupWin.hpp.
Referenced by CancelLookup(), Lookup(), LookupIPv4(), and Run().
run
bool services::NameLookupWin::run = true private
Definition at line 29 of file NameLookupWin.hpp.
Referenced by Run(), and ~NameLookupWin().
The documentation for this class was generated from the following files:
NameLookupWin.hpp
NameLookupWin.cpp