EMil: application::Input Class Reference
application::Input Class Reference abstract
#include <Input.hpp>
Public Member Functions
Input (const std::string &targetName)
virtual ~Input ()=default
std::string TargetName () const
virtual std::vector< uint8_t > Image () const =0
Private Attributes
std::string targetName
Detailed Description
Definition at line 9 of file Input.hpp.
Constructor & Destructor Documentation
Input()
application::Input::Input (const std::string & targetName) explicit
Definition at line 5 of file Input.cpp.
         : targetName(targetName)
     {}
~Input()
virtual application::Input::~Input () virtual default
Member Function Documentation
Image()
virtual std::vector<uint8_t> application::Input::Image () const pure virtual
Implemented in application::InputBinary, application::InputHex, and application::NoFileInput.
TargetName()
std::string application::Input::TargetName () const
Definition at line 9 of file Input.cpp.
References targetName.
Referenced by application::NoFileInput::Image(), application::InputHex::Image(), and application::InputBinary::Image().
     {
         return targetName;
     }
Member Data Documentation
targetName
std::string application::Input::targetName private
Definition at line 19 of file Input.hpp.
Referenced by application::NoFileInput::Image(), application::InputBinary::Image(), and TargetName().
The documentation for this class was generated from the following files:
Input.hpp
Input.cpp