EMil: services::HttpRequestParserImpl Class Reference
services::HttpRequestParserImpl Class Reference
#include <HttpRequestParser.hpp>
Public Member Functions
HttpRequestParserImpl (infra::BoundedString data)
virtual bool Complete () const override
virtual bool Valid () const override
virtual HttpVerb Verb () const override
virtual const infra::Tokenizer & PathTokens () const override
virtual infra::BoundedString Body () override
virtual infra::BoundedConstString Body () const override
virtual infra::BoundedConstString Header (infra::BoundedConstString name) const override
virtual void EnumerateHeaders (const infra::Function< void(infra::BoundedConstString name, infra::BoundedConstString value)> &enumerator) const override
Private Member Functions
void FindVerb (infra::Tokenizer &tokenizer)
void FindPath (infra::Tokenizer &tokenizer)
void FindHeadersAndBody (infra::BoundedString data)
void CheckContentsLength (infra::BoundedString data)
Private Attributes
infra::BoundedString headers
infra::BoundedString body
HttpVerb verb
infra::BoundedConstString path
infra::Tokenizer pathTokens
bool complete = true
bool valid = true
Additional Inherited Members
Protected Member Functions inherited from services::HttpRequestParser
HttpRequestParser ()=default
HttpRequestParser (const HttpRequestParser &other)=delete
HttpRequestParser & operator= (const HttpRequestParser &other)=delete
~HttpRequestParser ()=default
Detailed Description
Definition at line 30 of file HttpRequestParser.hpp.
Constructor & Destructor Documentation
HttpRequestParserImpl()
services::HttpRequestParserImpl::HttpRequestParserImpl (infra::BoundedString data)
Definition at line 6 of file HttpRequestParser.cpp.
References infra::data, FindHeadersAndBody(), FindPath(), and FindVerb().
         : pathTokens("", '/')
     {
         infra::Tokenizer tokenizer(data, ' ');
         FindVerb(tokenizer);
         FindPath(tokenizer);
         FindHeadersAndBody(data);
     }
Member Function Documentation
Body() [1/2]
infra::BoundedString services::HttpRequestParserImpl::Body () override virtual
Implements services::HttpRequestParser.
Definition at line 53 of file HttpRequestParser.cpp.
References body.
     {
         return body;
     }
Body() [2/2]
infra::BoundedConstString services::HttpRequestParserImpl::Body () const override virtual
Implements services::HttpRequestParser.
Definition at line 58 of file HttpRequestParser.cpp.
References body.
     {
         return body;
     }
CheckContentsLength()
void services::HttpRequestParserImpl::CheckContentsLength (infra::BoundedString data) private
Definition at line 114 of file HttpRequestParser.cpp.
References body, complete, infra::data, infra::noFail, infra::BoundedStringBase< const char >::npos, and infra::BoundedStringBase< T >::size().
Referenced by FindHeadersAndBody().
     {
         static const char* contentLengthTag = "\r\nContent-Length:";
         std::size_t contentLengthHeaderStart = data.find(contentLengthTag);
         if (contentLengthHeaderStart != infra::BoundedConstString::npos)
         {
             auto contentLengthStart = contentLengthHeaderStart + std::strlen(contentLengthTag);
             auto contentLengthEnd = data.find("\r\n", contentLengthStart);
             infra::StringInputStream stream(data.substr(contentLengthStart, contentLengthEnd - contentLengthStart), infra::noFail);
             uint32_t size(0);
             stream >> size;
             if (body.size() < size)
                 complete = false;
         }
     }
Complete()
bool services::HttpRequestParserImpl::Complete () const override virtual
Implements services::HttpRequestParser.
Definition at line 33 of file HttpRequestParser.cpp.
References complete.
Referenced by services::HttpServerConnectionObserver::ReceivedRequest().
     {
         return complete;
     }
EnumerateHeaders()
void services::HttpRequestParserImpl::EnumerateHeaders (const infra::Function< void(infra::BoundedConstString name, infra::BoundedConstString value)> & enumerator) const override virtual
Implements services::HttpRequestParser.
Definition at line 82 of file HttpRequestParser.cpp.
References infra::BoundedStringBase< T >::find(), headers, infra::BoundedStringBase< char >::npos, and infra::TrimLeft().
     {
         auto headersTail = headers;
         while (!headersTail.empty())
         {
             auto nextHeaderStart = headersTail.find("\r\n");
             infra::Tokenizer tokenizer(headersTail.substr(0, nextHeaderStart), ':');
             enumerator(tokenizer.Token(0), infra::TrimLeft(tokenizer.TokenAndRest(1)));
             if (nextHeaderStart == infra::BoundedString::npos)
                 break;
             headersTail = headersTail.substr(nextHeaderStart + 2);
         }
     }
FindHeadersAndBody()
void services::HttpRequestParserImpl::FindHeadersAndBody (infra::BoundedString data) private
Definition at line 98 of file HttpRequestParser.cpp.
References body, CheckContentsLength(), complete, infra::data, headers, and infra::BoundedStringBase< char >::npos.
Referenced by HttpRequestParserImpl().
     {
         auto bodyStart = data.find("\r\n\r\n", 0, 4);
         if (bodyStart == infra::BoundedString::npos)
             complete = false;
         else
         {
             auto headersStart = data.find("\r\n");
             if (headersStart != bodyStart)
                 headers = data.substr(headersStart + 2, bodyStart);
             body = data.substr(bodyStart + 4);
         }
         CheckContentsLength(data);
     }
FindPath()
void services::HttpRequestParserImpl::FindPath (infra::Tokenizer & tokenizer) private
Definition at line 27 of file HttpRequestParser.cpp.
References path, pathTokens, and infra::Tokenizer::Token().
Referenced by HttpRequestParserImpl().
     {
         path = tokenizer.Token(1);
         pathTokens = infra::Tokenizer(path, '/');
     }
FindVerb()
void services::HttpRequestParserImpl::FindVerb (infra::Tokenizer & tokenizer) private
Definition at line 16 of file HttpRequestParser.cpp.
References services::HttpVerbFromString(), infra::Tokenizer::Token(), valid, and verb.
Referenced by HttpRequestParserImpl().
     {
         auto verbToken = tokenizer.Token(0);
         auto receivedVerb = HttpVerbFromString(verbToken);
         if (receivedVerb)
             verb = *receivedVerb;
         else
             valid = false;
     }
Header()
infra::BoundedConstString services::HttpRequestParserImpl::Header (infra::BoundedConstString name) const override virtual
Implements services::HttpRequestParser.
Definition at line 63 of file HttpRequestParser.cpp.
References infra::BoundedStringBase< T >::find(), headers, infra::BoundedStringBase< char >::npos, and infra::TrimLeft().
     {
         auto headersTail = headers;
         while (!headersTail.empty())
         {
             auto nextHeaderStart = headersTail.find("\r\n");
             infra::Tokenizer tokenizer(headersTail.substr(0, nextHeaderStart), ':');
             if (tokenizer.Token(0) == name)
                 return infra::TrimLeft(tokenizer.TokenAndRest(1));
             if (nextHeaderStart == infra::BoundedString::npos)
                 break;
             headersTail = headersTail.substr(nextHeaderStart + 2);
         }
         return infra::BoundedConstString();
     }
PathTokens()
const infra::Tokenizer & services::HttpRequestParserImpl::PathTokens () const override virtual
Implements services::HttpRequestParser.
Definition at line 48 of file HttpRequestParser.cpp.
References pathTokens.
     {
         return pathTokens;
     }
Valid()
bool services::HttpRequestParserImpl::Valid () const override virtual
Implements services::HttpRequestParser.
Definition at line 38 of file HttpRequestParser.cpp.
References valid.
     {
         return valid;
     }
Verb()
HttpVerb services::HttpRequestParserImpl::Verb () const override virtual
Implements services::HttpRequestParser.
Definition at line 43 of file HttpRequestParser.cpp.
References verb.
     {
         return verb;
     }
Member Data Documentation
body
infra::BoundedString services::HttpRequestParserImpl::body private
Definition at line 53 of file HttpRequestParser.hpp.
Referenced by Body(), CheckContentsLength(), and FindHeadersAndBody().
complete
bool services::HttpRequestParserImpl::complete = true private
Definition at line 57 of file HttpRequestParser.hpp.
Referenced by CheckContentsLength(), Complete(), and FindHeadersAndBody().
headers
infra::BoundedString services::HttpRequestParserImpl::headers private
Definition at line 52 of file HttpRequestParser.hpp.
Referenced by EnumerateHeaders(), FindHeadersAndBody(), and Header().
path
infra::BoundedConstString services::HttpRequestParserImpl::path private
Definition at line 55 of file HttpRequestParser.hpp.
Referenced by FindPath().
pathTokens
infra::Tokenizer services::HttpRequestParserImpl::pathTokens private
Definition at line 56 of file HttpRequestParser.hpp.
Referenced by FindPath(), and PathTokens().
valid
bool services::HttpRequestParserImpl::valid = true private
Definition at line 58 of file HttpRequestParser.hpp.
Referenced by FindVerb(), and Valid().
verb
HttpVerb services::HttpRequestParserImpl::verb private
Definition at line 54 of file HttpRequestParser.hpp.
Referenced by FindVerb(), and Verb().
The documentation for this class was generated from the following files:
HttpRequestParser.hpp
HttpRequestParser.cpp