EMil: services::ServerConnectionObserverFactory Class Reference
services::ServerConnectionObserverFactory Class Reference abstract
#include <Connection.hpp>
Public Member Functions
virtual void ConnectionAccepted (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver, IPAddress address)=0
Protected Member Functions
ServerConnectionObserverFactory ()=default
ServerConnectionObserverFactory (const ServerConnectionObserverFactory &other)=delete
ServerConnectionObserverFactory & operator= (const ServerConnectionObserverFactory &other)=delete
~ServerConnectionObserverFactory ()=default
Detailed Description
Definition at line 58 of file Connection.hpp.
Constructor & Destructor Documentation
ServerConnectionObserverFactory() [1/2]
services::ServerConnectionObserverFactory::ServerConnectionObserverFactory () protected default
ServerConnectionObserverFactory() [2/2]
services::ServerConnectionObserverFactory::ServerConnectionObserverFactory (const ServerConnectionObserverFactory & other) protected delete
~ServerConnectionObserverFactory()
services::ServerConnectionObserverFactory::~ServerConnectionObserverFactory () protected default
Member Function Documentation
ConnectionAccepted()
virtual void services::ServerConnectionObserverFactory::ConnectionAccepted (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver, IPAddress address) pure virtual
Implemented in services::SingleConnectionHttpServer< ConnectionCreationContext >, services::ConnectionMbedTlsListener, and services::StreamEchoServer.
Referenced by services::ListenerBsd::Accept(), services::ListenerWin::Accept(), and services::ConnectionMbedTlsListener::ConnectionAccepted().
operator=()
ServerConnectionObserverFactory& services::ServerConnectionObserverFactory::operator= (const ServerConnectionObserverFactory & other) protected delete
The documentation for this class was generated from the following file:
Connection.hpp