EMil: hal::GpioPinSpy Class Reference
hal::GpioPinSpy Class Reference
#include <GpioStub.hpp>
Public Member Functions
GpioPinSpy ()
virtual void Set (bool value) override
std::vector< PinChange > PinChanges () const
Public Member Functions inherited from hal::GpioPinStub
virtual ~GpioPinStub ()=default
virtual bool Get () const override
virtual bool GetOutputLatch () const override
virtual void SetAsInput () override
virtual bool IsInput () const override
virtual void Config (PinConfigType config) override
virtual void Config (PinConfigType config, bool startOutputState) override
virtual void ResetConfig () override
virtual void EnableInterrupt (const infra::Function< void()> &action, InterruptTrigger trigger) override
virtual void DisableInterrupt () override
void SetStubState (bool value)
bool GetStubState () const
Public Member Functions inherited from hal::GpioPin
GpioPin ()=default
GpioPin (const GpioPin &other)=delete
GpioPin & operator= (const GpioPin &other)=delete
Private Attributes
infra::TimePoint start
std::vector< PinChange > pinChanges
Additional Inherited Members
Protected Member Functions inherited from hal::GpioPin
~GpioPin ()=default
Detailed Description
Definition at line 53 of file GpioStub.hpp.
Constructor & Destructor Documentation
GpioPinSpy()
hal::GpioPinSpy::GpioPinSpy ()
Definition at line 101 of file GpioStub.cpp.
         : start(infra::Now())
     {}
Member Function Documentation
PinChanges()
std::vector< PinChange > hal::GpioPinSpy::PinChanges () const
Definition at line 113 of file GpioStub.cpp.
References pinChanges.
     {
         return pinChanges;
     }
Set()
void hal::GpioPinSpy::Set (bool value) override virtual
Reimplemented from hal::GpioPinStub.
Definition at line 105 of file GpioStub.cpp.
References hal::GpioPinStub::GetOutputLatch(), infra::Now(), pinChanges, hal::GpioPinStub::Set(), start, and value.
     {
         if (GetOutputLatch() != value)
             pinChanges.push_back({ infra::Now() - start, value });
         GpioPinStub::Set(value);
     }
Member Data Documentation
pinChanges
std::vector<PinChange> hal::GpioPinSpy::pinChanges private
Definition at line 65 of file GpioStub.hpp.
Referenced by PinChanges(), and Set().
start
infra::TimePoint hal::GpioPinSpy::start private
Definition at line 64 of file GpioStub.hpp.
Referenced by Set().
The documentation for this class was generated from the following files:
GpioStub.hpp
GpioStub.cpp