EMil: infra::ClockFixture Class Reference
infra::ClockFixture Class Reference
#include <ClockFixture.hpp>
Classes
class TimeMatcherHelper
Public Member Functions
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Static Public Member Functions
static std::string TimeToString (TimePoint time)
Public Attributes
PerfectTimerService systemTimerService
Detailed Description
Definition at line 11 of file ClockFixture.hpp.
Constructor & Destructor Documentation
ClockFixture() [1/2]
infra::ClockFixture::ClockFixture (uint32_t timerSericeId = systemTimerServiceId)
Definition at line 6 of file ClockFixture.cpp.
         : systemTimerService(timerSericeId)
     {}
ClockFixture() [2/2]
infra::ClockFixture::ClockFixture (const ClockFixture &) delete
~ClockFixture()
infra::ClockFixture::~ClockFixture ()
Definition at line 10 of file ClockFixture.cpp.
     {}
Member Function Documentation
After()
ClockFixture::TimeMatcherHelper infra::ClockFixture::After (infra::Duration duration) const
Definition at line 27 of file ClockFixture.cpp.
References infra::PerfectTimerService::Now(), and systemTimerService.
     {
         return TimeMatcherHelper(systemTimerService.Now() + duration);
     }
ForwardTime()
void infra::ClockFixture::ForwardTime (Duration time)
Definition at line 13 of file ClockFixture.cpp.
References infra::TimerService::NextTrigger(), infra::PerfectTimerService::Now(), systemTimerService, and infra::PerfectTimerService::TimeProgressed().
Referenced by FlashQuadSpiCypressFllTest::FlashQuadSpiCypressFllTest(), FlashQuadSpiMicronN25qTest::FlashQuadSpiMicronN25qTest(), FlashQuadSpiSingleSpeedTest::FlashQuadSpiSingleSpeedTest(), and DnsResolverTest::LookupIsRetried().
     {
         ExecuteAllActions();
         TimePoint newSystemTime = systemTimerService.Now() + amount;
         do
         {
             TimePoint minimumTriggerTime = std::min(newSystemTime, systemTimerService.NextTrigger());
             systemTimerService.TimeProgressed(minimumTriggerTime - systemTimerService.Now());
             ExecuteAllActions();
         } while (systemTimerService.Now() != newSystemTime);
     }
operator=()
ClockFixture& infra::ClockFixture::operator= (const ClockFixture &) delete
TimeToString()
std::string infra::ClockFixture::TimeToString (TimePoint time) static
Definition at line 32 of file ClockFixture.cpp.
References infra::PrintTo().
Referenced by infra::ClockFixture::TimeMatcherHelper::TimeMatcher< Args >::DescribeTo().
     {
         std::ostringstream os;
         PrintTo(time, &os);
         return os.str();
     }
Member Data Documentation
systemTimerService
PerfectTimerService infra::ClockFixture::systemTimerService
Definition at line 29 of file ClockFixture.hpp.
Referenced by After(), and ForwardTime().
The documentation for this class was generated from the following files:
ClockFixture.hpp
ClockFixture.cpp