EMil: infra::JsonString Class Reference
infra::JsonString Class Reference
#include <Json.hpp>
Public Member Functions
JsonString ()=default
JsonString (infra::BoundedConstString source)
JsonString (const char *source)
bool operator== (const JsonString &other) const
bool operator!= (const JsonString &other) const
bool operator== (infra::BoundedConstString other) const
bool operator!= (infra::BoundedConstString other) const
bool operator== (const char *other) const
bool operator!= (const char *other) const
bool empty () const
std::size_t size () const
JsonStringIterator begin () const
JsonStringIterator end () const
infra::BoundedConstString Raw () const
void ToString (infra::BoundedString &result) const
void AppendTo (infra::BoundedString &result) const
std::string ToStdString () const
Private Attributes
infra::BoundedConstString source
Friends
bool operator== (infra::BoundedConstString x, JsonString y)
bool operator!= (infra::BoundedConstString x, JsonString y)
bool operator== (const char *x, JsonString y)
bool operator!= (const char *x, JsonString y)
infra::TextOutputStream & operator<< (infra::TextOutputStream &stream, JsonString value)
Detailed Description
Definition at line 35 of file Json.hpp.
Constructor & Destructor Documentation
JsonString() [1/3]
infra::JsonString::JsonString () default
JsonString() [2/3]
infra::JsonString::JsonString (infra::BoundedConstString source)
Definition at line 122 of file Json.cpp.
         : source(source)
     {}
JsonString() [3/3]
infra::JsonString::JsonString (const char * source)
Definition at line 126 of file Json.cpp.
         : source(source)
     {}
Member Function Documentation
AppendTo()
void infra::JsonString::AppendTo (infra::BoundedString & result) const
Definition at line 235 of file Json.cpp.
References infra::BoundedStringBase< T >::full(), and infra::BoundedStringBase< T >::push_back().
Referenced by ToString().
     {
         for (auto c : *this)
         {
             result.push_back(c);
             if (result.full())
                 return;
         }
     }
begin()
JsonStringIterator infra::JsonString::begin () const
Definition at line 214 of file Json.cpp.
References infra::BoundedStringBase< T >::begin(), infra::BoundedStringBase< T >::end(), and source.
Referenced by operator==(), and size().
     {
         return JsonStringIterator(source.begin(), source.end());
     }
empty()
bool infra::JsonString::empty () const
Definition at line 204 of file Json.cpp.
References size().
     {
         return size() == 0;
     }
end()
JsonStringIterator infra::JsonString::end () const
Definition at line 219 of file Json.cpp.
References infra::BoundedStringBase< T >::end(), and source.
Referenced by operator==(), and size().
     {
         return JsonStringIterator(source.end(), source.end());
     }
operator!=() [1/3]
bool infra::JsonString::operator!= (const JsonString & other) const
Definition at line 135 of file Json.cpp.
     {
         return !(*this == other);
     }
operator!=() [2/3]
bool infra::JsonString::operator!= (infra::BoundedConstString other) const
Definition at line 157 of file Json.cpp.
     {
         return !(*this == other);
     }
operator!=() [3/3]
bool infra::JsonString::operator!= (const char * other) const
Definition at line 189 of file Json.cpp.
     {
         return !(*this == other);
     }
operator==() [1/3]
bool infra::JsonString::operator== (const JsonString & other) const
Definition at line 130 of file Json.cpp.
References source.
     {
         return source == other.source;
     }
operator==() [2/3]
bool infra::JsonString::operator== (infra::BoundedConstString other) const
Definition at line 140 of file Json.cpp.
References begin(), infra::BoundedStringBase< T >::begin(), end(), and infra::BoundedStringBase< T >::end().
     {
         auto x = begin();
         auto y = other.begin();
         while (x != end() && y != other.end())
         {
             if (*x != *y)
                 return false;
             ++x;
             ++y;
         }
         return x == end() && y == other.end();
     }
operator==() [3/3]
bool infra::JsonString::operator== (const char * other) const
Definition at line 172 of file Json.cpp.
References begin(), and end().
     {
         auto x = begin();
         auto y = other;
         while (x != end() && *y != 0)
         {
             if (*x != *y)
                 return false;
             ++x;
             ++y;
         }
         return x == end() && *y == 0;
     }
Raw()
infra::BoundedConstString infra::JsonString::Raw () const
Definition at line 224 of file Json.cpp.
References source.
Referenced by infra::JsonObjectFormatter::Add(), and infra::JsonToken::String::RawValue().
     {
         return source;
     }
size()
std::size_t infra::JsonString::size () const
Definition at line 209 of file Json.cpp.
References begin(), and end().
Referenced by empty().
     {
         return std::distance(begin(), end());
     }
ToStdString()
std::string infra::JsonString::ToStdString () const
Definition at line 246 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::GetOutputFilename().
     {
         std::string result;
         for (auto c : *this)
             result.push_back(c);
         return result;
     }
ToString()
void infra::JsonString::ToString (infra::BoundedString & result) const
Definition at line 229 of file Json.cpp.
References AppendTo(), and infra::BoundedStringBase< T >::clear().
     {
         result.clear();
         AppendTo(result);
     }
Friends And Related Function Documentation
operator!= [1/2]
bool operator!= (infra::BoundedConstString x, JsonString y) friend
Definition at line 167 of file Json.cpp.
     {
         return y != x;
     }
operator!= [2/2]
bool operator!= (const char * x, JsonString y) friend
Definition at line 199 of file Json.cpp.
     {
         return y != x;
     }
operator<<
infra::TextOutputStream& operator<< (infra::TextOutputStream & stream, JsonString value) friend
Definition at line 257 of file Json.cpp.
     {
         for (auto c : value)
             stream << c;
         return stream;
     }
operator== [1/2]
bool operator== (infra::BoundedConstString x, JsonString y) friend
Definition at line 162 of file Json.cpp.
     {
         return y == x;
     }
operator== [2/2]
bool operator== (const char * x, JsonString y) friend
Definition at line 194 of file Json.cpp.
     {
         return y == x;
     }
Member Data Documentation
source
infra::BoundedConstString infra::JsonString::source private
Definition at line 70 of file Json.hpp.
Referenced by begin(), end(), operator==(), and Raw().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp