EMil: services::FactoryDefaultConfigurationStoreBase Class Reference
services::FactoryDefaultConfigurationStoreBase Class Reference
#include <ConfigurationStore.hpp>
Public Member Functions
FactoryDefaultConfigurationStoreBase (ConfigurationStoreBase &configurationStore, ConfigurationBlob &factoryDefaultBlob)
void Recover (const infra::Function< void()> &onLoadFactoryDefault, const infra::Function< void(bool isFactoryDefault)> &onRecovered)
void Write (infra::Function< void()> onDone)
virtual void Write () override
Private Attributes
ConfigurationStoreBase & configurationStore
ConfigurationBlob & factoryDefaultBlob
infra::AutoResetFunction< void()> onLoadFactoryDefault
infra::AutoResetFunction< void(bool isFactoryDefault)> onRecovered
Additional Inherited Members
Protected Member Functions inherited from services::ConfigurationStoreInterface
ConfigurationStoreInterface ()=default
ConfigurationStoreInterface (const ConfigurationStoreInterface &other)=delete
ConfigurationStoreInterface & operator= (const ConfigurationStoreInterface &other)=delete
~ConfigurationStoreInterface ()=default
Detailed Description
Definition at line 186 of file ConfigurationStore.hpp.
Constructor & Destructor Documentation
FactoryDefaultConfigurationStoreBase()
services::FactoryDefaultConfigurationStoreBase::FactoryDefaultConfigurationStoreBase (ConfigurationStoreBase & configurationStore, ConfigurationBlob & factoryDefaultBlob)
Definition at line 201 of file ConfigurationStore.cpp.
         : configurationStore(configurationStore)
         , factoryDefaultBlob(factoryDefaultBlob)
     {}
Member Function Documentation
Recover()
void services::FactoryDefaultConfigurationStoreBase::Recover (const infra::Function< void()> & onLoadFactoryDefault, const infra::Function< void(bool isFactoryDefault)> & onRecovered)
Definition at line 206 of file ConfigurationStore.cpp.
References configurationStore, services::ConfigurationStoreBase::Deserialize(), services::ConfigurationBlob::Erase(), services::ConfigurationStoreBase::Erase(), factoryDefaultBlob, onLoadFactoryDefault, onRecovered, services::ConfigurationBlob::Recover(), services::ConfigurationStoreBase::Recover(), and services::ConfigurationStoreBase::Serialize().
Referenced by services::FactoryDefaultConfigurationStore< T >::WithBlobs::WithBlobs().
     {
         this->onLoadFactoryDefault = onLoadFactoryDefault;
         this->onRecovered = onRecovered;
         factoryDefaultBlob.Recover([this](bool success)
         {
             if (!success)
             {
                 this->onLoadFactoryDefault();
                 factoryDefaultBlob.Erase([this]()
                 {
                     configurationStore.Serialize(factoryDefaultBlob, [this]()
                     {
                         configurationStore.Recover([this](bool success)
{
                             if (success)
                                 this->onRecovered(false);
                             else
                                 configurationStore.Erase([this]() { this->onRecovered(true); });
                         });
                     });
                 });
             }
             else
             {
                 configurationStore.Deserialize(factoryDefaultBlob);
                 this->onLoadFactoryDefault = nullptr;
                 configurationStore.Recover([this](bool success)
                 {
                     this->onRecovered(!success);
                 });
             }
         });
     }
Write() [1/2]
void services::FactoryDefaultConfigurationStoreBase::Write (infra::Function< void()> onDone)
Definition at line 245 of file ConfigurationStore.cpp.
References configurationStore, and services::ConfigurationStoreBase::Write().
     {
         configurationStore.Write(onDone);
     }
Write() [2/2]
void services::FactoryDefaultConfigurationStoreBase::Write () override virtual
Implements services::ConfigurationStoreInterface.
Definition at line 250 of file ConfigurationStore.cpp.
Referenced by services::FactoryDefaultConfigurationStore< T >::Write().
     {
         Write(infra::Function<void()>());
     }
Member Data Documentation
configurationStore
ConfigurationStoreBase& services::FactoryDefaultConfigurationStoreBase::configurationStore private
Definition at line 197 of file ConfigurationStore.hpp.
Referenced by Recover(), and Write().
factoryDefaultBlob
ConfigurationBlob& services::FactoryDefaultConfigurationStoreBase::factoryDefaultBlob private
Definition at line 198 of file ConfigurationStore.hpp.
Referenced by Recover().
onLoadFactoryDefault
infra::AutoResetFunction<void()> services::FactoryDefaultConfigurationStoreBase::onLoadFactoryDefault private
Definition at line 199 of file ConfigurationStore.hpp.
Referenced by Recover(), and services::FactoryDefaultConfigurationStore< T >::WithBlobs::WithBlobs().
onRecovered
infra::AutoResetFunction<void(bool isFactoryDefault)> services::FactoryDefaultConfigurationStoreBase::onRecovered private
Definition at line 200 of file ConfigurationStore.hpp.
Referenced by Recover(), and services::FactoryDefaultConfigurationStore< T >::WithBlobs::WithBlobs().
The documentation for this class was generated from the following files:
ConfigurationStore.hpp
ConfigurationStore.cpp