EMil: TestI2cRegisterAccessMock.cpp File Reference
TestI2cRegisterAccessMock.cpp File Reference
Classes
class RegisterAccessMockTest
Functions
TEST_F (RegisterAccessMockTest, ReadRegisterInOneRead)
TEST_F (RegisterAccessMockTest, ReadRegisterInTwoReads)
TEST_F (RegisterAccessMockTest, WriteRegisterInOneWrite)
TEST_F (RegisterAccessMockTest, WriteRegisterInTwoWrites)
TEST_F (RegisterAccessMockTest, WriteRegisterInThreeWrites)
Function Documentation
TEST_F() [1/5]
TEST_F (RegisterAccessMockTest , ReadRegisterInOneRead)
Definition at line 19 of file TestI2cRegisterAccessMock.cpp.
References hal::complete, data, EXPECT_EQ(), infra::MakeByteRange(), hal::repeatedStart, and hal::stop.
 {
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDoneVerifier(hal::Result::complete, 1);
     infra::VerifyingFunctionMock<void(hal::Result)> receiveDataDoneVerifier(hal::Result::complete);
     EXPECT_CALL(masterMock, ReadRegisterMock(3)).WillOnce(testing::Return(std::vector<uint8_t>{ 1, 2, 3, 4 }));
     uint8_t dataRegister = 3;
     std::array<uint8_t, 4> data;
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(dataRegister), hal::Action::repeatedStart, sendDataDoneVerifier);
     master.ReceiveData(hal::I2cAddress(1), infra::MakeByteRange(data), hal::Action::stop, receiveDataDoneVerifier);
     EXPECT_EQ((std::array<uint8_t, 4>{ 1, 2, 3, 4 }), data);
 }
TEST_F() [2/5]
TEST_F (RegisterAccessMockTest , ReadRegisterInTwoReads)
Definition at line 33 of file TestI2cRegisterAccessMock.cpp.
References hal::complete, hal::continueSession, EXPECT_EQ(), infra::MakeByteRange(), hal::repeatedStart, and hal::stop.
 {
     infra::VerifyingFunctionMock<void(hal::Result)> receiveDataDone1Verifier(hal::Result::complete);
     infra::VerifyingFunctionMock<void(hal::Result)> receiveDataDone2Verifier(hal::Result::complete);
     EXPECT_CALL(masterMock, ReadRegisterMock(3)).WillOnce(testing::Return(std::vector<uint8_t>{ 1, 2, 3, 4 }));
     uint8_t dataRegister = 3;
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(dataRegister), hal::Action::repeatedStart, [](hal::Result, uint32_t numberOfBytesSent) {});
     std::array<uint8_t, 3> data1;
     std::array<uint8_t, 1> data2;
     master.ReceiveData(hal::I2cAddress(1), infra::MakeByteRange(data1), hal::Action::continueSession, receiveDataDone1Verifier);
     master.ReceiveData(hal::I2cAddress(1), infra::MakeByteRange(data2), hal::Action::stop, receiveDataDone2Verifier);
     EXPECT_EQ((std::array<uint8_t, 3>{ 1, 2, 3 }), data1);
     EXPECT_EQ((std::array<uint8_t, 1>{ 4 }), data2);
 }
TEST_F() [3/5]
TEST_F (RegisterAccessMockTest , WriteRegisterInOneWrite)
Definition at line 50 of file TestI2cRegisterAccessMock.cpp.
References hal::complete, data, infra::MakeByteRange(), and hal::stop.
 {
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDoneVerifier(hal::Result::complete, 5);
     EXPECT_CALL(masterMock, WriteRegisterMock(3, std::vector<uint8_t>{ 1, 2, 3, 4 }));
     std::array<uint8_t, 5> data = { 3, 1, 2, 3, 4 };
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(data), hal::Action::stop, sendDataDoneVerifier);
 }
TEST_F() [4/5]
TEST_F (RegisterAccessMockTest , WriteRegisterInTwoWrites)
Definition at line 59 of file TestI2cRegisterAccessMock.cpp.
References hal::complete, hal::continueSession, data, infra::MakeByteRange(), and hal::stop.
 {
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDone1Verifier(hal::Result::complete, 1);
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDone2Verifier(hal::Result::complete, 4);
     EXPECT_CALL(masterMock, WriteRegisterMock(3, std::vector<uint8_t>{ 1, 2, 3, 4 }));
     uint8_t dataRegister = 3;
     std::array<uint8_t, 4> data = { 1, 2, 3, 4 };
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(dataRegister), hal::Action::continueSession, sendDataDone1Verifier);
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(data), hal::Action::stop, sendDataDone2Verifier);
 }
TEST_F() [5/5]
TEST_F (RegisterAccessMockTest , WriteRegisterInThreeWrites)
Definition at line 71 of file TestI2cRegisterAccessMock.cpp.
References hal::complete, hal::continueSession, infra::MakeByteRange(), and hal::stop.
 {
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDone1Verifier(hal::Result::complete, 1);
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDone2Verifier(hal::Result::complete, 3);
     infra::VerifyingFunctionMock<void(hal::Result, uint32_t)> sendDataDone3Verifier(hal::Result::complete, 1);
     EXPECT_CALL(masterMock, WriteRegisterMock(3, std::vector<uint8_t>{ 1, 2, 3, 4 }));
     uint8_t dataRegister = 3;
     std::array<uint8_t, 3> data1 = { 1, 2, 3 };
     std::array<uint8_t, 1> data2 = { 4 };
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(dataRegister), hal::Action::continueSession, sendDataDone1Verifier);
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(data1), hal::Action::continueSession, sendDataDone2Verifier);
     master.SendData(hal::I2cAddress(1), infra::MakeByteRange(data2), hal::Action::stop, sendDataDone3Verifier);
 }