EMil: services::TracingConnectionMbedTls Class Reference
services::TracingConnectionMbedTls Class Reference
#include <TracingConnectionMbedTls.hpp>
Public Member Functions
TracingConnectionMbedTls (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver, CertificatesMbedTls &certificates, hal::SynchronousRandomDataGenerator &randomDataGenerator, const ConnectionMbedTls::ParametersWorkaround &parameters, Tracer &tracer)
virtual void TlsInitFailure (int reason) override
virtual void TlsReadFailure (int reason) override
virtual void TlsWriteFailure (int reason) override
virtual void TlsLog (int level, const char *file, int line, const char *message) override
Public Member Functions inherited from services::ConnectionMbedTls
ConnectionMbedTls (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver, CertificatesMbedTls &certificates, hal::SynchronousRandomDataGenerator &randomDataGenerator, const ParametersWorkaround &parameters)
ConnectionMbedTls (const ConnectionMbedTls &other)=delete
~ConnectionMbedTls ()
void CreatedObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
void SetHostname (infra::BoundedConstString hostname)
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
virtual void Connected () override
virtual void ClosingConnection () override
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionMbedTls >
SharedPtr< ConnectionMbedTls > SharedFromThis ()
SharedPtr< const ConnectionMbedTls > SharedFromThis () const
WeakPtr< ConnectionMbedTls > WeakFromThis ()
WeakPtr< const ConnectionMbedTls > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionMbedTls > sharedPtr)
Private Member Functions
void LogFailure (const char *what, int reason)
Private Attributes
Tracer & tracer
Additional Inherited Members
Public Types inherited from services::ConnectionMbedTls
using Parameters = infra::Variant< ServerParameters, ClientParameters >
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Public Types inherited from infra::EnableSharedFromThis< ConnectionMbedTls >
using EnableSharedFromThisType = ConnectionMbedTls
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionMbedTls >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 9 of file TracingConnectionMbedTls.hpp.
Constructor & Destructor Documentation
TracingConnectionMbedTls()
services::TracingConnectionMbedTls::TracingConnectionMbedTls (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver, CertificatesMbedTls & certificates, hal::SynchronousRandomDataGenerator & randomDataGenerator, const ConnectionMbedTls::ParametersWorkaround & parameters, Tracer & tracer)
Definition at line 7 of file TracingConnectionMbedTls.cpp.
         : ConnectionMbedTls(std::move(createdObserver), certificates, randomDataGenerator, parameters)
         , tracer(tracer)
     {}
Member Function Documentation
LogFailure()
void services::TracingConnectionMbedTls::LogFailure (const char * what, int reason) private
Definition at line 36 of file TracingConnectionMbedTls.cpp.
References services::Tracer::Continue(), infra::hex, infra::resetWidth, services::Tracer::Trace(), and tracer.
Referenced by TlsInitFailure(), TlsReadFailure(), and TlsWriteFailure().
     {
         tracer.Trace() << what << ": ";
 #if defined(MBEDTLS_ERROR_C)
         infra::BoundedString::WithStorage<128> description;
         mbedtls_strerror(reason, description.data(), description.max_size());
         tracer.Continue() << description;
 #endif
         tracer.Continue() << " (-0x" << infra::hex << infra::Width(4, '0') << std::abs(reason) << infra::resetWidth << ")";
     }
TlsInitFailure()
void services::TracingConnectionMbedTls::TlsInitFailure (int reason) override virtual
Reimplemented from services::ConnectionMbedTls.
Definition at line 13 of file TracingConnectionMbedTls.cpp.
References LogFailure().
     {
         LogFailure("ConnectionMbedTls::TlsInitFailure", reason);
     }
TlsLog()
void services::TracingConnectionMbedTls::TlsLog (int level, const char * file, int line, const char * message) override virtual
Reimplemented from services::ConnectionMbedTls.
Definition at line 28 of file TracingConnectionMbedTls.cpp.
References infra::BoundedStringBase< T >::find_last_of(), infra::BoundedStringBase< T >::substr(), services::Tracer::Trace(), and tracer.
     {
         infra::BoundedConstString fileCopy(file);
         tracer.Trace() << "[" << fileCopy.substr(fileCopy.find_last_of('\\') + 1) << ":" << line
                        << "] (" << level << "): " << message;
     }
TlsReadFailure()
void services::TracingConnectionMbedTls::TlsReadFailure (int reason) override virtual
Reimplemented from services::ConnectionMbedTls.
Definition at line 18 of file TracingConnectionMbedTls.cpp.
References LogFailure().
     {
         LogFailure("ConnectionMbedTls::TlsReadFailure", reason);
     }
TlsWriteFailure()
void services::TracingConnectionMbedTls::TlsWriteFailure (int reason) override virtual
Reimplemented from services::ConnectionMbedTls.
Definition at line 23 of file TracingConnectionMbedTls.cpp.
References LogFailure().
     {
         LogFailure("ConnectionMbedTls::TlsWriteFailure", reason);
     }
Member Data Documentation
tracer
Tracer& services::TracingConnectionMbedTls::tracer private
Definition at line 24 of file TracingConnectionMbedTls.hpp.
Referenced by LogFailure(), and TlsLog().
The documentation for this class was generated from the following files:
TracingConnectionMbedTls.hpp
TracingConnectionMbedTls.cpp