EMil: TestProxyCreator.cpp File Reference
TestProxyCreator.cpp File Reference
Classes
class PeripheralInterface
class Peripheral
class PeripheralWithTwoParameters
Functions
TEST (ProxyCreatorTest, CreatePeripheral)
TEST (ProxyCreatorTest, CreatePeripheralWithParameterGivenByProxy)
TEST (ProxyCreatorTest, CreatePeripheralWithParameterGivenByCreator)
TEST (ProxyCreatorTest, CreatePeripheralWithParameterGivenByProxyAndCreator)
TEST (ProxyCreatorTest, CreatePeripheralWithParameterGivenByCreatorAndProxy)
TEST (ProxyCreatorTest, AccessPeripheral)
TEST (ProxyCreatorTest, CreatePeripheralWithVoidAccess)
TEST (ProxyCreatorTest, CreatePeripheralByCreatorExternal)
TEST (DelayedProxyCreatorTest, CreatePeripheral)
TEST (DelayedProxyCreatorTest, CreatePeripheralWithParameterGivenByProxy)
TEST (DelayedProxyCreatorTest, CreatePeripheralWithParameterGivenByCreator)
TEST (DelayedProxyCreatorTest, CreatePeripheralWithParameterGivenByProxyAndCreator)
TEST (DelayedProxyCreatorTest, CreatePeripheralWithParameterGivenByCreatorAndProxy)
TEST (DelayedProxyCreatorTest, AccessPeripheral)
Function Documentation
TEST() [1/14]
TEST (ProxyCreatorTest , CreatePeripheral)
Definition at line 42 of file TestProxyCreator.cpp.
 {
     infra::Creator<PeripheralInterface, Peripheral, void()> creator;
     infra::ProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
 }
TEST() [2/14]
TEST (ProxyCreatorTest , CreatePeripheralWithParameterGivenByProxy)
Definition at line 49 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void(int, int)> creator;
     infra::ProxyCreator<PeripheralInterface, void(int, int)> creatorProxy(creator, 5, 6);
     EXPECT_EQ(5, creator->x);
 }
TEST() [3/14]
TEST (ProxyCreatorTest , CreatePeripheralWithParameterGivenByCreator)
Definition at line 57 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void()> creator([](infra::Optional<PeripheralWithTwoParameters>& object) { object.Emplace(5, 6); });
     infra::ProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
     EXPECT_EQ(5, creator->x);
 }
TEST() [4/14]
TEST (ProxyCreatorTest , CreatePeripheralWithParameterGivenByProxyAndCreator)
Definition at line 65 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void(int)> creator([](infra::Optional<PeripheralWithTwoParameters>& object, int x) { object.Emplace(x, 6); });
     infra::ProxyCreator<PeripheralInterface, void(int)> creatorProxy(creator, 5);
     EXPECT_EQ(5, creator->x);
     EXPECT_EQ(6, creator->y);
 }
TEST() [5/14]
TEST (ProxyCreatorTest , CreatePeripheralWithParameterGivenByCreatorAndProxy)
Definition at line 74 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void(int)> creator([](infra::Optional<PeripheralWithTwoParameters>& object, int y) { object.Emplace(5, y); });
     infra::ProxyCreator<PeripheralInterface, void(int)> creatorProxy(creator, 6);
     EXPECT_EQ(5, creator->x);
     EXPECT_EQ(6, creator->y);
 }
TEST() [6/14]
TEST (ProxyCreatorTest , AccessPeripheral)
Definition at line 83 of file TestProxyCreator.cpp.
 {
     infra::Creator<PeripheralInterface, Peripheral, void()> creator;
     infra::ProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
     EXPECT_CALL(*creator, SendMock());
     creatorProxy->Send();
 }
TEST() [7/14]
TEST (ProxyCreatorTest , CreatePeripheralWithVoidAccess)
Definition at line 93 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<void, PeripheralWithTwoParameters, void(int, int)> creator;
     infra::ProxyCreator<void, void(int, int)> creatorProxy(creator, 5, 6);
     EXPECT_EQ(5, creator->x);
 }
TEST() [8/14]
TEST (ProxyCreatorTest , CreatePeripheralByCreatorExternal)
Definition at line 101 of file TestProxyCreator.cpp.
 {
     infra::MockCallback<void()> construction;
     infra::MockCallback<void()> destruction;
     PeripheralWithTwoParameters peripheral(5, 6);
     infra::CreatorExternal<PeripheralInterface, void()> creator([&peripheral, &construction]() -> PeripheralWithTwoParameters& { construction.callback(); return peripheral; }, [&destruction]() { destruction.callback(); });
     EXPECT_CALL(construction, callback());
     infra::ProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
     EXPECT_CALL(peripheral, SendMock());
     creatorProxy->Send();
     EXPECT_CALL(destruction, callback());
 }
TEST() [9/14]
TEST (DelayedProxyCreatorTest , CreatePeripheral)
Definition at line 118 of file TestProxyCreator.cpp.
 {
     infra::Creator<PeripheralInterface, Peripheral, void()> creator;
     infra::DelayedProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
     creatorProxy.Emplace();
     creatorProxy.Destroy();
 }
TEST() [10/14]
TEST (DelayedProxyCreatorTest , CreatePeripheralWithParameterGivenByProxy)
Definition at line 127 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void(int, int)> creator;
     infra::DelayedProxyCreator<PeripheralInterface, void(int, int)> creatorProxy(creator);
     creatorProxy.Emplace(5, 6);
     EXPECT_EQ(5, creator->x);
 }
TEST() [11/14]
TEST (DelayedProxyCreatorTest , CreatePeripheralWithParameterGivenByCreator)
Definition at line 136 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void()> creator([](infra::Optional<PeripheralWithTwoParameters>& object) { object.Emplace(5, 6); });
     infra::DelayedProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
     creatorProxy.Emplace();
     EXPECT_EQ(5, creator->x);
 }
TEST() [12/14]
TEST (DelayedProxyCreatorTest , CreatePeripheralWithParameterGivenByProxyAndCreator)
Definition at line 145 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void(int)> creator([](infra::Optional<PeripheralWithTwoParameters>& object, int x) { object.Emplace(x, 6); });
     infra::DelayedProxyCreator<PeripheralInterface, void(int)> creatorProxy(creator);
     creatorProxy.Emplace(5);
     EXPECT_EQ(5, creator->x);
     EXPECT_EQ(6, creator->y);
 }
TEST() [13/14]
TEST (DelayedProxyCreatorTest , CreatePeripheralWithParameterGivenByCreatorAndProxy)
Definition at line 155 of file TestProxyCreator.cpp.
References EXPECT_EQ().
 {
     infra::Creator<PeripheralInterface, PeripheralWithTwoParameters, void(int)> creator([](infra::Optional<PeripheralWithTwoParameters>& object, int y) { object.Emplace(5, y); });
     infra::DelayedProxyCreator<PeripheralInterface, void(int)> creatorProxy(creator);
     creatorProxy.Emplace(6);
     EXPECT_EQ(5, creator->x);
     EXPECT_EQ(6, creator->y);
 }
TEST() [14/14]
TEST (DelayedProxyCreatorTest , AccessPeripheral)
Definition at line 165 of file TestProxyCreator.cpp.
 {
     infra::Creator<PeripheralInterface, Peripheral, void()> creator;
     infra::DelayedProxyCreator<PeripheralInterface, void()> creatorProxy(creator);
     creatorProxy.Emplace();
     EXPECT_CALL(*creator, SendMock());
     creatorProxy->Send();
 }