EMil: services::ConnectionFactory Class Reference
services::ConnectionFactory Class Reference abstract
#include <Connection.hpp>
Public Member Functions
virtual infra::SharedPtr< void > Listen (uint16_t port, ServerConnectionObserverFactory &factory, IPVersions versions=IPVersions::both)=0
virtual void Connect (ClientConnectionObserverFactory &factory)=0
virtual void CancelConnect (ClientConnectionObserverFactory &factory)=0
Protected Member Functions
ConnectionFactory ()=default
ConnectionFactory (const ConnectionFactory &other)=delete
ConnectionFactory & operator= (const ConnectionFactory &other)=delete
~ConnectionFactory ()=default
Detailed Description
Definition at line 93 of file Connection.hpp.
Constructor & Destructor Documentation
ConnectionFactory() [1/2]
services::ConnectionFactory::ConnectionFactory () protected default
ConnectionFactory() [2/2]
services::ConnectionFactory::ConnectionFactory (const ConnectionFactory & other) protected delete
~ConnectionFactory()
services::ConnectionFactory::~ConnectionFactory () protected default
Member Function Documentation
CancelConnect()
virtual void services::ConnectionFactory::CancelConnect (ClientConnectionObserverFactory & factory) pure virtual
Implemented in services::ConnectionFactoryMbedTls, services::EventDispatcherWithNetwork, and services::EventDispatcherWithNetwork.
Referenced by services::MqttClientConnectorImpl::CancelConnect(), and services::ConnectionFactoryWithNameResolverImpl::Action::Remove().
Connect()
virtual void services::ConnectionFactory::Connect (ClientConnectionObserverFactory & factory) pure virtual
Implemented in services::ConnectionFactoryMbedTls, services::EventDispatcherWithNetwork, and services::EventDispatcherWithNetwork.
Referenced by services::MqttClientConnectorImpl::Connect(), services::ConnectionMbedTlsConnector::ConnectionMbedTlsConnector(), and services::ConnectionFactoryWithNameResolverImpl::Action::NameLookupDone().
Listen()
virtual infra::SharedPtr<void> services::ConnectionFactory::Listen (uint16_t port, ServerConnectionObserverFactory & factory, IPVersions versions = IPVersions::both) pure virtual
Implemented in services::ConnectionFactoryMbedTls, services::EventDispatcherWithNetwork, and services::EventDispatcherWithNetwork.
Referenced by services::ConnectionFactoryMbedTls::Listen(), services::SingleConnectionHttpServer< ConnectionCreationContext >::SingleConnectionHttpServer(), and services::StreamEchoServer::StreamEchoServer().
operator=()
ConnectionFactory& services::ConnectionFactory::operator= (const ConnectionFactory & other) protected delete
The documentation for this class was generated from the following file:
Connection.hpp