EMil: services::SpiMultipleAccessMaster Class Reference
services::SpiMultipleAccessMaster Class Reference
#include <SpiMultipleAccess.hpp>
Public Member Functions
SpiMultipleAccessMaster (hal::SpiMaster &master)
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> &onDone) override
virtual void SetChipSelectConfigurator (hal::ChipSelectConfigurator &configurator) override
virtual void SetCommunicationConfigurator (hal::CommunicationConfigurator &configurator) override
virtual void ResetCommunicationConfigurator () override
Public Member Functions inherited from hal::SpiMaster
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
Public Member Functions inherited from infra::ClaimableResource
ClaimableResource ()=default
ClaimableResource (const ClaimableResource &other)=delete
ClaimableResource & operator= (const ClaimableResource &other)=delete
~ClaimableResource ()
Private Attributes
hal::SpiMaster & master
hal::CommunicationConfigurator * communicationConfigurator = nullptr
Additional Inherited Members
Public Types inherited from infra::ClaimableResource
using Claimer = ClaimerWithSize< INFRA_DEFAULT_FUNCTION_EXTRA_SIZE >
Protected Member Functions inherited from hal::SpiMaster
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Detailed Description
Definition at line 14 of file SpiMultipleAccess.hpp.
Constructor & Destructor Documentation
SpiMultipleAccessMaster()
services::SpiMultipleAccessMaster::SpiMultipleAccessMaster (hal::SpiMaster & master) explicit
Definition at line 5 of file SpiMultipleAccess.cpp.
         : master(master)
     {}
Member Function Documentation
ResetCommunicationConfigurator()
void services::SpiMultipleAccessMaster::ResetCommunicationConfigurator () override virtual
Implements hal::SpiMaster.
Definition at line 28 of file SpiMultipleAccess.cpp.
References communicationConfigurator, master, and hal::SpiMaster::ResetCommunicationConfigurator().
Referenced by services::SpiMultipleAccess::SendAndReceiveOnClaimed().
     {
         if (communicationConfigurator != nullptr)
         {
             master.ResetCommunicationConfigurator();
             communicationConfigurator = nullptr;
         }
     }
SendAndReceive()
void services::SpiMultipleAccessMaster::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, hal::SpiAction nextAction, const infra::Function< void()> & onDone) override virtual
Implements hal::SpiMaster.
Definition at line 9 of file SpiMultipleAccess.cpp.
References master, and hal::SpiMaster::SendAndReceive().
Referenced by services::SpiMultipleAccess::SendAndReceiveOnClaimed().
     {
         master.SendAndReceive(sendData, receiveData, nextAction, onDone);
     }
SetChipSelectConfigurator()
void services::SpiMultipleAccessMaster::SetChipSelectConfigurator (hal::ChipSelectConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 14 of file SpiMultipleAccess.cpp.
References master, and hal::SpiMaster::SetChipSelectConfigurator().
Referenced by services::SpiMultipleAccess::SendAndReceiveOnClaimed().
     {
         master.SetChipSelectConfigurator(configurator);
     }
SetCommunicationConfigurator()
void services::SpiMultipleAccessMaster::SetCommunicationConfigurator (hal::CommunicationConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 19 of file SpiMultipleAccess.cpp.
References communicationConfigurator, master, and hal::SpiMaster::SetCommunicationConfigurator().
Referenced by services::SpiMultipleAccess::SendAndReceiveOnClaimed().
     {
         if (communicationConfigurator != &configurator)
         {
             master.SetCommunicationConfigurator(configurator);
             communicationConfigurator = &configurator;
         }
     }
Member Data Documentation
communicationConfigurator
hal::CommunicationConfigurator* services::SpiMultipleAccessMaster::communicationConfigurator = nullptr private
Definition at line 28 of file SpiMultipleAccess.hpp.
Referenced by ResetCommunicationConfigurator(), and SetCommunicationConfigurator().
master
hal::SpiMaster& services::SpiMultipleAccessMaster::master private
Definition at line 27 of file SpiMultipleAccess.hpp.
Referenced by ResetCommunicationConfigurator(), SendAndReceive(), SetChipSelectConfigurator(), and SetCommunicationConfigurator().
The documentation for this class was generated from the following files:
SpiMultipleAccess.hpp
SpiMultipleAccess.cpp