EMil: hal::I2cMasterRegisterAccessMock Class Reference
hal::I2cMasterRegisterAccessMock Class Reference
#include <I2cRegisterAccessMock.hpp>
Public Member Functions
virtual void SendData (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction, infra::Function< void(hal::Result, uint32_t numberOfBytesSent)> onSent) override
virtual void ReceiveData (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction, infra::Function< void(hal::Result)> onReceived) override
MOCK_METHOD1 (ReadRegisterMock, std::vector< uint8_t >(uint8_t dataRegister))
MOCK_METHOD2 (WriteRegisterMock, void(uint8_t dataRegister, const std::vector< uint8_t > &data))
Public Member Functions inherited from hal::I2cMaster
I2cMaster ()=default
I2cMaster (const I2cMaster &other)=delete
I2cMaster & operator= (const I2cMaster &other)=delete
Private Attributes
bool sending = true
bool atStart = true
uint8_t dataRegister = 0
std::vector< uint8_t > currentSendData
std::vector< uint8_t > currentReceiveData
Additional Inherited Members
Protected Member Functions inherited from hal::I2cMaster
~I2cMaster ()=default
Detailed Description
Definition at line 10 of file I2cRegisterAccessMock.hpp.
Member Function Documentation
MOCK_METHOD1()
hal::I2cMasterRegisterAccessMock::MOCK_METHOD1 (ReadRegisterMock , std::vector< uint8_t > uint8_t dataRegister)
MOCK_METHOD2()
hal::I2cMasterRegisterAccessMock::MOCK_METHOD2 (WriteRegisterMock , void(uint8_t dataRegister, const std::vector< uint8_t > &data))
ReceiveData()
void hal::I2cMasterRegisterAccessMock::ReceiveData (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction, infra::Function< void(hal::Result)> onReceived) override virtual
Implements hal::I2cMaster.
Definition at line 31 of file I2cRegisterAccessMock.cpp.
References atStart, hal::complete, hal::continueSession, currentReceiveData, data, dataRegister, and sending.
     {
         assert(atStart || !sending);
         if (atStart)
             currentReceiveData = ReadRegisterMock(dataRegister);
         assert(currentReceiveData.size() >= data.size());
         std::copy(currentReceiveData.begin(), currentReceiveData.begin() + data.size(), data.begin());
         currentReceiveData.erase(currentReceiveData.begin(), currentReceiveData.begin() + data.size());
         atStart = nextAction != hal::Action::continueSession;
         sending = false;
         onReceived(hal::Result::complete);
     }
SendData()
void hal::I2cMasterRegisterAccessMock::SendData (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction, infra::Function< void(hal::Result, uint32_t numberOfBytesSent)> onSent) override virtual
Implements hal::I2cMaster.
Definition at line 7 of file I2cRegisterAccessMock.cpp.
References atStart, infra::MemoryRange< T >::begin(), hal::complete, hal::continueSession, currentSendData, data, dataRegister, infra::InputStream::Empty(), infra::MemoryRange< T >::end(), infra::DataInputStream::WithReader< TheReader >::Reader(), infra::ByteInputStreamReader::Remaining(), and sending.
     {
         assert(atStart || sending);
         infra::ByteInputStream stream(data);
         if (atStart)
             stream >> dataRegister;
         if (!stream.Empty())
             currentSendData.insert(currentSendData.end(), stream.Reader().Remaining().begin(), stream.Reader().Remaining().end());
         if (nextAction != hal::Action::continueSession && !currentSendData.empty())
         {
             WriteRegisterMock(dataRegister, currentSendData);
             currentSendData.clear();
         }
         atStart = nextAction != hal::Action::continueSession;
         sending = true;
         onSent(hal::Result::complete, data.size());
     }
Member Data Documentation
atStart
bool hal::I2cMasterRegisterAccessMock::atStart = true private
Definition at line 24 of file I2cRegisterAccessMock.hpp.
Referenced by ReceiveData(), and SendData().
currentReceiveData
std::vector<uint8_t> hal::I2cMasterRegisterAccessMock::currentReceiveData private
Definition at line 27 of file I2cRegisterAccessMock.hpp.
Referenced by ReceiveData().
currentSendData
std::vector<uint8_t> hal::I2cMasterRegisterAccessMock::currentSendData private
Definition at line 26 of file I2cRegisterAccessMock.hpp.
Referenced by SendData().
dataRegister
uint8_t hal::I2cMasterRegisterAccessMock::dataRegister = 0 private
Definition at line 25 of file I2cRegisterAccessMock.hpp.
Referenced by ReceiveData(), and SendData().
sending
bool hal::I2cMasterRegisterAccessMock::sending = true private
Definition at line 23 of file I2cRegisterAccessMock.hpp.
Referenced by ReceiveData(), and SendData().
The documentation for this class was generated from the following files:
I2cRegisterAccessMock.hpp
I2cRegisterAccessMock.cpp