EMil: services::HttpResponse Class Reference
services::HttpResponse Class Reference abstract
#include <HttpServer.hpp>
Public Member Functions
void WriteResponse (infra::TextOutputStream &stream) const
virtual infra::BoundedConstString Status () const =0
virtual void WriteBody (infra::TextOutputStream &stream) const =0
virtual infra::BoundedConstString ContentType () const =0
virtual void AddHeaders (HttpResponseHeaderBuilder &builder) const
Protected Member Functions
HttpResponse (std::size_t maxBodySize)
HttpResponse (const HttpResponse &other)=delete
HttpResponse & operator= (const HttpResponse &other)=delete
~HttpResponse ()=default
Private Attributes
std::size_t maxBodySize
Detailed Description
Definition at line 46 of file HttpServer.hpp.
Constructor & Destructor Documentation
HttpResponse() [1/2]
services::HttpResponse::HttpResponse (std::size_t maxBodySize) protected
Definition at line 55 of file HttpServer.cpp.
         : maxBodySize(maxBodySize)
     {}
HttpResponse() [2/2]
services::HttpResponse::HttpResponse (const HttpResponse & other) protected delete
~HttpResponse()
services::HttpResponse::~HttpResponse () protected default
Member Function Documentation
AddHeaders()
void services::HttpResponse::AddHeaders (HttpResponseHeaderBuilder & builder) const virtual
Reimplemented in application::TimeHttpPage::TimeResponse.
Definition at line 84 of file HttpServer.cpp.
Referenced by WriteResponse().
     {}
ContentType()
virtual infra::BoundedConstString services::HttpResponse::ContentType () const pure virtual
Implemented in application::TimeHttpPage::TimeResponse, and services::HttpErrorResponse.
Referenced by WriteResponse().
operator=()
HttpResponse& services::HttpResponse::operator= (const HttpResponse & other) protected delete
Status()
virtual infra::BoundedConstString services::HttpResponse::Status () const pure virtual
Implemented in application::TimeHttpPage::TimeResponse, and services::HttpErrorResponse.
Referenced by WriteResponse().
WriteBody()
virtual void services::HttpResponse::WriteBody (infra::TextOutputStream & stream) const pure virtual
Implemented in application::TimeHttpPage::TimeResponse, and services::HttpErrorResponse.
Referenced by WriteResponse().
WriteResponse()
void services::HttpResponse::WriteResponse (infra::TextOutputStream & stream) const
Definition at line 59 of file HttpServer.cpp.
References services::HttpResponseHeaderBuilder::AddHeader(), AddHeaders(), ContentType(), maxBodySize, infra::OutputStream::ProcessedBytesSince(), infra::OutputStream::SaveMarker(), services::HttpResponseHeaderBuilder::StartBody(), Status(), WriteBody(), and infra::OutputStream::Writer().
Referenced by services::HttpServerConnectionObserver::SendResponse().
     {
         HttpResponseHeaderBuilder builder(stream);
         std::size_t resultMarker = stream.SaveMarker();
         builder.AddHeader("Content-Length");
         std::size_t sizeMarker = stream.SaveMarker();
         builder.AddHeader("Content-Type", ContentType());
         AddHeaders(builder);
         builder.StartBody();
         uint32_t sizeBeforeGetResponse = stream.ProcessedBytesSince(sizeMarker);
         infra::LimitedTextOutputStream limitedResponse(stream.Writer(), maxBodySize);
         WriteBody(limitedResponse);
         uint32_t size = stream.ProcessedBytesSince(sizeMarker) - sizeBeforeGetResponse;
         {
             infra::SavedMarkerTextStream sizeStream(stream, sizeMarker);
             sizeStream << size;
         }
         {
             infra::SavedMarkerTextStream markerStream(stream, resultMarker);
             markerStream << Status();
         }
     }
Member Data Documentation
maxBodySize
std::size_t services::HttpResponse::maxBodySize private
Definition at line 64 of file HttpServer.hpp.
Referenced by WriteResponse().
The documentation for this class was generated from the following files:
HttpServer.hpp
HttpServer.cpp