EMil: infra::detail::BoundedForwardListIterator< T > Class Template Reference
infra::detail::BoundedForwardListIterator< T > Class Template Reference
#include <BoundedForwardList.hpp>
Public Member Functions
BoundedForwardListIterator ()
BoundedForwardListIterator (NodeType *node)
template<class T2 >
BoundedForwardListIterator (const BoundedForwardListIterator< T2 > &other)
template<class T2 >
BoundedForwardListIterator & operator= (const BoundedForwardListIterator< T2 > &other)
T & operator* () const
T * operator-> () const
NodeType & node ()
BoundedForwardListIterator & operator++ ()
BoundedForwardListIterator operator++ (int)
template<class T2 >
bool operator== (const BoundedForwardListIterator< T2 > &other) const
template<class T2 >
bool operator!= (const BoundedForwardListIterator< T2 > &other) const
template<class T2 >
BoundedForwardListIterator< T > & operator= (const BoundedForwardListIterator< T2 > &other)
Private Types
typedef detail::BoundedForwardListNode< typename std::remove_const< T >::type > NodeType
Private Attributes
NodeType * mNode
Friends
template<class >
class BoundedForwardListIterator
Detailed Description
template<class T>
class infra::detail::BoundedForwardListIterator< T >
Definition at line 31 of file BoundedForwardList.hpp.
Member Typedef Documentation
NodeType
template<class T > typedef detail::BoundedForwardListNode<typename std::remove_const<T>::type> infra::detail::BoundedForwardListIterator< T >::NodeType private
Definition at line 142 of file BoundedForwardList.hpp.
Constructor & Destructor Documentation
BoundedForwardListIterator() [1/3]
template<class T > infra::detail::BoundedForwardListIterator< T >::BoundedForwardListIterator ()
Definition at line 631 of file BoundedForwardList.hpp.
             : mNode(0)
         {}
BoundedForwardListIterator() [2/3]
template<class T > infra::detail::BoundedForwardListIterator< T >::BoundedForwardListIterator (NodeType * node) explicit
Definition at line 636 of file BoundedForwardList.hpp.
             : mNode(node)
         {}
BoundedForwardListIterator() [3/3]
template<class T > template<class T2 > infra::detail::BoundedForwardListIterator< T >::BoundedForwardListIterator (const BoundedForwardListIterator< T2 > & other)
Definition at line 642 of file BoundedForwardList.hpp.
             : mNode(other.mNode)
         {}
Member Function Documentation
node()
template<class T > BoundedForwardListIterator< T >::NodeType & infra::detail::BoundedForwardListIterator< T >::node ()
Definition at line 668 of file BoundedForwardList.hpp.
Referenced by infra::BoundedForwardList< T >::erase_all_after(), infra::BoundedForwardList< T >::erase_slow(), and infra::BoundedForwardList< T >::insert_after().
         {
             really_assert(mNode != 0);
             return *mNode;
         }
operator!=()
template<class T > template<class T2 > bool infra::detail::BoundedForwardListIterator< T >::operator!= (const BoundedForwardListIterator< T2 > & other) const
Definition at line 698 of file BoundedForwardList.hpp.
         {
             return !(*this == other);
         }
operator*()
template<class T > T & infra::detail::BoundedForwardListIterator< T >::operator* () const
Definition at line 656 of file BoundedForwardList.hpp.
         {
             return *mNode->storage;
         }
operator++() [1/2]
template<class T > BoundedForwardListIterator< T > & infra::detail::BoundedForwardListIterator< T >::operator++ ()
Definition at line 675 of file BoundedForwardList.hpp.
         {
             mNode = mNode->next;
             return *this;
         }
operator++() [2/2]
template<class T > BoundedForwardListIterator< T > infra::detail::BoundedForwardListIterator< T >::operator++ (int)
Definition at line 682 of file BoundedForwardList.hpp.
         {
             BoundedForwardListIterator copy(*this);
             mNode = mNode->next;
             return copy;
         }
operator->()
template<class T > T * infra::detail::BoundedForwardListIterator< T >::operator-> () const
Definition at line 662 of file BoundedForwardList.hpp.
         {
             return &*mNode->storage;
         }
operator=() [1/2]
template<class T > template<class T2 > BoundedForwardListIterator& infra::detail::BoundedForwardListIterator< T >::operator= (const BoundedForwardListIterator< T2 > & other)
operator=() [2/2]
template<class T > template<class T2 > BoundedForwardListIterator<T>& infra::detail::BoundedForwardListIterator< T >::operator= (const BoundedForwardListIterator< T2 > & other)
Definition at line 648 of file BoundedForwardList.hpp.
         {
             mNode = other.mNode;
             return *this;
         }
operator==()
template<class T > template<class T2 > bool infra::detail::BoundedForwardListIterator< T >::operator== (const BoundedForwardListIterator< T2 > & other) const
Definition at line 691 of file BoundedForwardList.hpp.
         {
             return mNode == other.mNode;
         }
Friends And Related Function Documentation
BoundedForwardListIterator
template<class T > template<class > friend class BoundedForwardListIterator friend
Definition at line 167 of file BoundedForwardList.hpp.
Member Data Documentation
mNode
template<class T > NodeType* infra::detail::BoundedForwardListIterator< T >::mNode private
Definition at line 169 of file BoundedForwardList.hpp.
The documentation for this class was generated from the following file:
BoundedForwardList.hpp