EMil: TestAllocatorHeap.cpp File Reference
TestAllocatorHeap.cpp File Reference
Classes
class HeapAllocatorTest
struct HeapAllocatorTest::TestObject
Functions
TEST_F (HeapAllocatorTest, allocate_one_object)
TEST_F (HeapAllocatorTest, after_object_goes_out_of_scope_object_is_released)
TEST_F (HeapAllocatorTest, when_allocating_more_than_capacity_nullptr_is_returned)
Function Documentation
TEST_F() [1/3]
TEST_F (HeapAllocatorTest , allocate_one_object)
Definition at line 35 of file TestAllocatorHeap.cpp.
References EXPECT_TRUE().
 {
     infra::UniquePtr<TestObject> object = allocator.Allocate();
     EXPECT_TRUE(TestObject::allocated);
 }
TEST_F() [2/3]
TEST_F (HeapAllocatorTest , after_object_goes_out_of_scope_object_is_released)
Definition at line 42 of file TestAllocatorHeap.cpp.
References EXPECT_FALSE().
 {
     {
         infra::UniquePtr<TestObject> object = allocator.Allocate();
     }
     EXPECT_FALSE(TestObject::allocated);
 }
TEST_F() [3/3]
TEST_F (HeapAllocatorTest , when_allocating_more_than_capacity_nullptr_is_returned)
Definition at line 51 of file TestAllocatorHeap.cpp.
References EXPECT_EQ().
 {
     infra::UniquePtr<TestObject> firstObject = allocator.Allocate();
     infra::UniquePtr<TestObject> secondObject = allocator.Allocate();
     EXPECT_EQ(nullptr, secondObject);
 }