EMil: services::ConnectorBsd Class Reference
services::ConnectorBsd Class Reference
#include <ConnectionBsd.hpp>
Public Member Functions
ConnectorBsd (EventDispatcherWithNetwork &network, services::ClientConnectionObserverFactory &factory)
~ConnectorBsd ()
void Connected ()
void Failed ()
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectorBsd >
SharedPtr< ConnectorBsd > SharedFromThis ()
SharedPtr< const ConnectorBsd > SharedFromThis () const
WeakPtr< ConnectorBsd > WeakFromThis ()
WeakPtr< const ConnectorBsd > WeakFromThis () const
void MakeShared (SharedPtr< ConnectorBsd > sharedPtr)
Private Attributes
EventDispatcherWithNetwork & network
services::ClientConnectionObserverFactory & factory
int connectSocket
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectorBsd >
using EnableSharedFromThisType = ConnectorBsd
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectorBsd >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 101 of file ConnectionBsd.hpp.
Constructor & Destructor Documentation
ConnectorBsd()
services::ConnectorBsd::ConnectorBsd (EventDispatcherWithNetwork & network, services::ClientConnectionObserverFactory & factory)
Definition at line 233 of file ConnectionBsd.cpp.
References services::ClientConnectionObserverFactory::Address(), services::connect, connectSocket, services::ConvertToUint32(), factory, infra::Variant< T >::Get(), and services::ClientConnectionObserverFactory::Port().
         : network(network)
         , factory(factory)
     {
         auto address = factory.Address().Get<services::IPv4Address>();
         connectSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
         assert(connectSocket != -1);
         SetNonBlocking(connectSocket);
         sockaddr_in saddress = {};
         saddress.sin_family = AF_INET;
         saddress.sin_addr.s_addr = htonl(services::ConvertToUint32(address));
         saddress.sin_port = htons(factory.Port());
         if (connect(connectSocket, reinterpret_cast<sockaddr*>(&saddress), sizeof(saddress)) == -1)
         {
             if (errno != EWOULDBLOCK)
                 std::abort();
         }
     }
~ConnectorBsd()
services::ConnectorBsd::~ConnectorBsd ()
Definition at line 254 of file ConnectionBsd.cpp.
References connectSocket.
     {
         close(connectSocket);
     }
Member Function Documentation
Connected()
void services::ConnectorBsd::Connected ()
Definition at line 259 of file ConnectionBsd.cpp.
References services::ClientConnectionObserverFactory::ConnectionEstablished(), connectSocket, services::EventDispatcherWithNetwork::DeregisterConnector(), factory, network, and infra::EnableSharedFromThis< ConnectorBsd >::SharedFromThis().
     {
         infra::WeakPtr<ConnectorBsd> self = SharedFromThis();
         infra::SharedPtr<ConnectionBsd> connection = infra::MakeSharedOnHeap<ConnectionBsd>(network, connectSocket);
         factory.ConnectionEstablished([connection](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             if (connectionObserver)
                 connection->SetObserver(connectionObserver);
         });
         network.DeregisterConnector(*this);
     }
Failed()
void services::ConnectorBsd::Failed ()
Definition at line 272 of file ConnectionBsd.cpp.
References services::ClientConnectionObserverFactory::ConnectionFailed(), services::EventDispatcherWithNetwork::DeregisterConnector(), factory, network, and infra::EnableSharedFromThis< ConnectorBsd >::SharedFromThis().
     {
         infra::WeakPtr<ConnectorBsd> self = SharedFromThis();
         factory.ConnectionFailed(services::ClientConnectionObserverFactory::ConnectFailReason::refused);
         network.DeregisterConnector(*this);
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 113 of file ConnectionBsd.hpp.
Member Data Documentation
connectSocket
int services::ConnectorBsd::connectSocket private
Definition at line 117 of file ConnectionBsd.hpp.
Referenced by Connected(), ConnectorBsd(), and ~ConnectorBsd().
factory
services::ClientConnectionObserverFactory& services::ConnectorBsd::factory private
Definition at line 116 of file ConnectionBsd.hpp.
Referenced by Connected(), ConnectorBsd(), and Failed().
network
EventDispatcherWithNetwork& services::ConnectorBsd::network private
Definition at line 115 of file ConnectionBsd.hpp.
Referenced by Connected(), and Failed().
The documentation for this class was generated from the following files:
ConnectionBsd.hpp
ConnectionBsd.cpp