EMil: TestLimitedInputStream.cpp File Reference
TestLimitedInputStream.cpp File Reference
Functions
TEST (LimitedInputStreamTest, Extract)
TEST (LimitedInputStreamTest, Peek_with_data_available)
TEST (LimitedInputStreamTest, Peek_with_no_data_available)
TEST (LimitedInputStreamTest, ExtractContiguousRange)
TEST (LimitedInputStreamTest, PeekContiguousRange)
TEST (LimitedInputStreamTest, Available)
TEST (LimitedInputStreamTest, Empty)
Function Documentation
TEST() [1/7]
TEST (LimitedInputStreamTest , Extract)
Definition at line 5 of file TestLimitedInputStream.cpp.
References data, EXPECT_TRUE(), infra::LimitedStreamReader::Extract(), infra::StreamErrorPolicy::Failed(), infra::Head(), infra::MakeRange(), and infra::softFail.
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 2);
     infra::StreamErrorPolicy errorPolicy(infra::softFail);
     std::array<uint8_t, 4> data;
     EXPECT_CALL(reader, Extract(infra::Head(infra::MakeRange(data), 2), testing::Ref(errorPolicy)));
     limitedReader.Extract(data, errorPolicy);
     EXPECT_TRUE(errorPolicy.Failed());
 }
TEST() [2/7]
TEST (LimitedInputStreamTest , Peek_with_data_available)
Definition at line 17 of file TestLimitedInputStream.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), infra::StreamErrorPolicy::Failed(), infra::LimitedStreamReader::Peek(), and infra::softFail.
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 1);
     infra::StreamErrorPolicy errorPolicy(infra::softFail);
     EXPECT_CALL(reader, Peek(testing::Ref(errorPolicy))).WillOnce(testing::Return(4));
     EXPECT_EQ(4, limitedReader.Peek(errorPolicy));
     EXPECT_FALSE(errorPolicy.Failed());
 }
TEST() [3/7]
TEST (LimitedInputStreamTest , Peek_with_no_data_available)
Definition at line 28 of file TestLimitedInputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::StreamErrorPolicy::Failed(), infra::LimitedStreamReader::Peek(), and infra::softFail.
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 0);
     infra::StreamErrorPolicy errorPolicy(infra::softFail);
     EXPECT_EQ(0, limitedReader.Peek(errorPolicy));
     EXPECT_TRUE(errorPolicy.Failed());
 }
TEST() [4/7]
TEST (LimitedInputStreamTest , ExtractContiguousRange)
Definition at line 38 of file TestLimitedInputStream.cpp.
References data, infra::LimitedStreamReader::Empty(), EXPECT_EQ(), EXPECT_TRUE(), infra::LimitedStreamReader::ExtractContiguousRange(), and infra::MakeRange().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 2);
     std::array<uint8_t, 2> data;
     EXPECT_CALL(reader, ExtractContiguousRange(2)).WillOnce(testing::Return(infra::MakeRange(data)));
     EXPECT_EQ(infra::MakeRange(data), limitedReader.ExtractContiguousRange(4));
     EXPECT_TRUE(limitedReader.Empty());
 }
TEST() [5/7]
TEST (LimitedInputStreamTest , PeekContiguousRange)
Definition at line 50 of file TestLimitedInputStream.cpp.
References data, infra::LimitedStreamReader::Empty(), EXPECT_EQ(), EXPECT_FALSE(), infra::MakeRange(), and infra::LimitedStreamReader::PeekContiguousRange().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 2);
     std::array<uint8_t, 2> data{{1, 2}};
     EXPECT_CALL(reader, PeekContiguousRange(0)).WillOnce(testing::Return(infra::MakeRange(data)));
     EXPECT_EQ(infra::MakeRange(data), limitedReader.PeekContiguousRange(0));
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(false));
     EXPECT_FALSE(limitedReader.Empty());
 }
TEST() [6/7]
TEST (LimitedInputStreamTest , Available)
Definition at line 64 of file TestLimitedInputStream.cpp.
References infra::LimitedStreamReader::Available(), and EXPECT_EQ().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 2);
     EXPECT_CALL(reader, Available()).WillOnce(testing::Return(4));
     EXPECT_EQ(2, limitedReader.Available());
     EXPECT_CALL(reader, Available()).WillOnce(testing::Return(1));
     EXPECT_EQ(1, limitedReader.Available());
 }
TEST() [7/7]
TEST (LimitedInputStreamTest , Empty)
Definition at line 76 of file TestLimitedInputStream.cpp.
References infra::LimitedStreamReader::Empty(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::LimitedStreamReader limitedReader(reader, 2);
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(false));
     EXPECT_FALSE(limitedReader.Empty());
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(true));
     EXPECT_TRUE(limitedReader.Empty());
 }