EMil: services::FlashQuadSpiMicronN25q Class Reference
services::FlashQuadSpiMicronN25q Class Reference
#include <FlashQuadSpiMicronN25q.hpp>
Public Member Functions
FlashQuadSpiMicronN25q (hal::QuadSpi &spi, infra::Function< void()> onInitialized, uint32_t numberOfSectors=4096)
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
Public Member Functions inherited from services::FlashQuadSpi
FlashQuadSpi (hal::QuadSpi &spi, uint32_t numberOfSectors, uint8_t commandPageProgram)
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::FlashHomogeneous
FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Static Public Attributes
static const uint8_t commandPageProgram = 0x32
static const uint8_t commandReadData = 0x0B
static const uint8_t commandReadStatusRegister = 0x05
static const uint8_t commandReadFlagStatusRegister = 0x70
static const uint8_t commandWriteEnable = 0x06
static const uint8_t commandEraseSubSector = 0x20
static const uint8_t commandEraseSector = 0xd8
static const uint8_t commandEraseBulk = 0xc7
static const uint8_t commandWriteEnhancedVolatileRegister = 0x61
static const uint8_t commandReadEnhancedVolatileRegister = 0x65
static const uint8_t statusFlagWriteInProgress = 1
static const uint8_t volatileRegisterForQuadSpeed = 0x5f
Static Public Attributes inherited from services::FlashQuadSpi
static const uint32_t sizeBlock = 65536
static const uint32_t sizeSector = 4096
static const uint32_t sizePage = 256
Private Member Functions
void WriteEnableSingleSpeed ()
void SwitchToQuadSpeed ()
virtual void WriteEnable () override
virtual void EraseSomeSectors (uint32_t endIndex) override
void SendEraseSubSector (uint32_t subSectorIndex)
void SendEraseSector (uint32_t subSectorIndex)
void SendEraseBulk ()
virtual void HoldWhileWriteInProgress () override
Private Attributes
infra::TimerSingleShot initDelayTimer
infra::Function< void()> onInitialized
Additional Inherited Members
Protected Member Functions inherited from services::FlashQuadSpi
void WriteBufferSequence ()
virtual void PageProgram ()
infra::BoundedVector< uint8_t >::WithMaxSize< 4 > ConvertAddress (uint32_t address) const
Protected Member Functions inherited from hal::FlashHomogeneous
~FlashHomogeneous ()=default
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Protected Attributes inherited from services::FlashQuadSpi
hal::QuadSpi & spi
infra::Sequencer sequencer
infra::AutoResetFunction< void()> onDone
infra::ConstByteRange buffer
uint32_t address = 0
uint32_t sectorIndex = 0
uint8_t commandPageProgram
Detailed Description
Definition at line 8 of file FlashQuadSpiMicronN25q.hpp.
Constructor & Destructor Documentation
FlashQuadSpiMicronN25q()
services::FlashQuadSpiMicronN25q::FlashQuadSpiMicronN25q (hal::QuadSpi & spi, infra::Function< void()> onInitialized, uint32_t numberOfSectors = 4096)
Definition at line 19 of file FlashQuadSpiMicronN25q.cpp.
References infra::Sequencer::Continue(), initDelayTimer, infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::Sequencer::Load(), onInitialized, infra::EventDispatcherWorker::Schedule(), services::FlashQuadSpi::sequencer, infra::TimerSingleShot::Start(), infra::Sequencer::Step(), SwitchToQuadSpeed(), and WriteEnableSingleSpeed().
         : FlashQuadSpi(spi, numberOfSectors, commandPageProgram)
         , onInitialized(onInitialized)
     {
         sequencer.Load([this]()
         {
             sequencer.Step([this]() { initDelayTimer.Start(std::chrono::milliseconds(1), [this]() { sequencer.Continue(); }); });
             sequencer.Step([this]() { WriteEnableSingleSpeed(); });
             sequencer.Step([this]() { SwitchToQuadSpeed(); });
             sequencer.Step([this]() { infra::EventDispatcher::Instance().Schedule([this]() { this->onInitialized(); }); });
         });
     }
Member Function Documentation
EraseSomeSectors()
void services::FlashQuadSpiMicronN25q::EraseSomeSectors (uint32_t endIndex) override private virtual
Implements services::FlashQuadSpi.
Definition at line 57 of file FlashQuadSpiMicronN25q.cpp.
References hal::FlashHomogeneous::NumberOfSectors(), services::FlashQuadSpi::sectorIndex, SendEraseBulk(), SendEraseSector(), SendEraseSubSector(), services::FlashQuadSpi::sizeBlock, and services::FlashQuadSpi::sizeSector.
     {
         if (sectorIndex == 0 && endIndex == NumberOfSectors())
         {
             SendEraseBulk();
             sectorIndex += NumberOfSectors();
         }
         else if (sectorIndex % (sizeBlock / sizeSector) == 0 && sectorIndex + sizeBlock / sizeSector <= endIndex)
         {
             SendEraseSector(sectorIndex);
             sectorIndex += sizeBlock / sizeSector;
         }
         else
         {
             SendEraseSubSector(sectorIndex);
             ++sectorIndex;
         }
     }
HoldWhileWriteInProgress()
void services::FlashQuadSpiMicronN25q::HoldWhileWriteInProgress () override private virtual
Implements services::FlashQuadSpi.
Definition at line 94 of file FlashQuadSpiMicronN25q.cpp.
References commandReadStatusRegister, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::PollStatus(), hal::QuadSpi::Lines::QuadSpeed(), services::FlashQuadSpi::sequencer, services::FlashQuadSpi::spi, and statusFlagWriteInProgress.
     {
         static const hal::QuadSpi::Header pollWriteInProgressHeader{ infra::MakeOptional(commandReadStatusRegister), {}, {}, 0 };
         spi.PollStatus(pollWriteInProgressHeader, 1, 0, statusFlagWriteInProgress, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
ReadBuffer()
void services::FlashQuadSpiMicronN25q::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 32 of file FlashQuadSpiMicronN25q.cpp.
References services::FlashQuadSpi::address, services::FlashQuadSpi::buffer, commandReadData, services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), services::FlashQuadSpi::onDone, hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::ReceiveData(), and services::FlashQuadSpi::spi.
     {
         const hal::QuadSpi::Header header{ infra::MakeOptional(commandReadData), ConvertAddress(address), {}, 10 };
         spi.ReceiveData(header, buffer, hal::QuadSpi::Lines::QuadSpeed(), onDone);
     }
SendEraseBulk()
void services::FlashQuadSpiMicronN25q::SendEraseBulk () private
Definition at line 88 of file FlashQuadSpiMicronN25q.cpp.
References commandEraseBulk, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         static const hal::QuadSpi::Header eraseBulkHeader{ infra::MakeOptional(commandEraseBulk), {}, {}, 0 };
         spi.SendData(eraseBulkHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseSector()
void services::FlashQuadSpiMicronN25q::SendEraseSector (uint32_t subSectorIndex) private
Definition at line 82 of file FlashQuadSpiMicronN25q.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseSector, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseSectorHeader{ infra::MakeOptional(commandEraseSector), ConvertAddress(AddressOfSector(subSectorIndex)), {}, 0 };
         spi.SendData(eraseSectorHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseSubSector()
void services::FlashQuadSpiMicronN25q::SendEraseSubSector (uint32_t subSectorIndex) private
Definition at line 76 of file FlashQuadSpiMicronN25q.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseSubSector, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseSubSectorHeader{ infra::MakeOptional(commandEraseSubSector), ConvertAddress(AddressOfSector(subSectorIndex)), {}, 0 };
         spi.SendData(eraseSubSectorHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
SwitchToQuadSpeed()
void services::FlashQuadSpiMicronN25q::SwitchToQuadSpeed () private
Definition at line 45 of file FlashQuadSpiMicronN25q.cpp.
References commandWriteEnhancedVolatileRegister, infra::Sequencer::Continue(), infra::MakeByteRange(), infra::MakeOptional(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), services::FlashQuadSpi::spi, and volatileRegisterForQuadSpeed.
Referenced by FlashQuadSpiMicronN25q().
     {
         static const hal::QuadSpi::Header writeVolatileRegisterHeader{ infra::MakeOptional(commandWriteEnhancedVolatileRegister), {}, {}, 0 };
         spi.SendData(writeVolatileRegisterHeader, infra::MakeByteRange(volatileRegisterForQuadSpeed), hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
WriteEnable()
void services::FlashQuadSpiMicronN25q::WriteEnable () override private virtual
Implements services::FlashQuadSpi.
Definition at line 51 of file FlashQuadSpiMicronN25q.cpp.
References commandWriteEnable, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::Lines::QuadSpeed(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, and services::FlashQuadSpi::spi.
     {
         static const hal::QuadSpi::Header writeEnableHeader{ infra::MakeOptional(commandWriteEnable), {}, {}, 0 };
         spi.SendData(writeEnableHeader, {}, hal::QuadSpi::Lines::QuadSpeed(), [this]() { sequencer.Continue(); });
     }
WriteEnableSingleSpeed()
void services::FlashQuadSpiMicronN25q::WriteEnableSingleSpeed () private
Definition at line 39 of file FlashQuadSpiMicronN25q.cpp.
References commandWriteEnable, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
Referenced by FlashQuadSpiMicronN25q().
     {
         static const hal::QuadSpi::Header writeEnableHeader{ infra::MakeOptional(commandWriteEnable), {}, {}, 0 };
         spi.SendData(writeEnableHeader, {}, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
Member Data Documentation
commandEraseBulk
const uint8_t services::FlashQuadSpiMicronN25q::commandEraseBulk = 0xc7 static
Definition at line 19 of file FlashQuadSpiMicronN25q.hpp.
Referenced by SendEraseBulk().
commandEraseSector
const uint8_t services::FlashQuadSpiMicronN25q::commandEraseSector = 0xd8 static
Definition at line 18 of file FlashQuadSpiMicronN25q.hpp.
Referenced by SendEraseSector().
commandEraseSubSector
const uint8_t services::FlashQuadSpiMicronN25q::commandEraseSubSector = 0x20 static
Definition at line 17 of file FlashQuadSpiMicronN25q.hpp.
Referenced by SendEraseSubSector().
commandPageProgram
const uint8_t services::FlashQuadSpiMicronN25q::commandPageProgram = 0x32 static
Definition at line 12 of file FlashQuadSpiMicronN25q.hpp.
commandReadData
const uint8_t services::FlashQuadSpiMicronN25q::commandReadData = 0x0B static
Definition at line 13 of file FlashQuadSpiMicronN25q.hpp.
Referenced by ReadBuffer().
commandReadEnhancedVolatileRegister
const uint8_t services::FlashQuadSpiMicronN25q::commandReadEnhancedVolatileRegister = 0x65 static
Definition at line 21 of file FlashQuadSpiMicronN25q.hpp.
commandReadFlagStatusRegister
const uint8_t services::FlashQuadSpiMicronN25q::commandReadFlagStatusRegister = 0x70 static
Definition at line 15 of file FlashQuadSpiMicronN25q.hpp.
commandReadStatusRegister
const uint8_t services::FlashQuadSpiMicronN25q::commandReadStatusRegister = 0x05 static
Definition at line 14 of file FlashQuadSpiMicronN25q.hpp.
Referenced by HoldWhileWriteInProgress().
commandWriteEnable
const uint8_t services::FlashQuadSpiMicronN25q::commandWriteEnable = 0x06 static
Definition at line 16 of file FlashQuadSpiMicronN25q.hpp.
Referenced by WriteEnable(), and WriteEnableSingleSpeed().
commandWriteEnhancedVolatileRegister
const uint8_t services::FlashQuadSpiMicronN25q::commandWriteEnhancedVolatileRegister = 0x61 static
Definition at line 20 of file FlashQuadSpiMicronN25q.hpp.
Referenced by SwitchToQuadSpeed().
initDelayTimer
infra::TimerSingleShot services::FlashQuadSpiMicronN25q::initDelayTimer private
Definition at line 42 of file FlashQuadSpiMicronN25q.hpp.
Referenced by FlashQuadSpiMicronN25q().
onInitialized
infra::Function<void()> services::FlashQuadSpiMicronN25q::onInitialized private
Definition at line 43 of file FlashQuadSpiMicronN25q.hpp.
Referenced by FlashQuadSpiMicronN25q().
statusFlagWriteInProgress
const uint8_t services::FlashQuadSpiMicronN25q::statusFlagWriteInProgress = 1 static
Definition at line 23 of file FlashQuadSpiMicronN25q.hpp.
Referenced by HoldWhileWriteInProgress().
volatileRegisterForQuadSpeed
const uint8_t services::FlashQuadSpiMicronN25q::volatileRegisterForQuadSpeed = 0x5f static
Definition at line 24 of file FlashQuadSpiMicronN25q.hpp.
Referenced by SwitchToQuadSpeed().
The documentation for this class was generated from the following files:
FlashQuadSpiMicronN25q.hpp
FlashQuadSpiMicronN25q.cpp