EMil: application::MaterialGenerator Class Reference
application::MaterialGenerator Class Reference
#include <MaterialGenerator.hpp>
Public Member Functions
MaterialGenerator (RandomNumberGenerator &randomNumberGenerator)
~MaterialGenerator ()
void WriteKeys (const std::string &fileName)
Static Public Attributes
static const std::size_t rsaKeyLength = 1024
static const std::size_t aesKeyLength = 128
static const std::size_t hmacKeyLength = 256
static const std::size_t xteaKeyLength = 128
static const std::size_t ecDsa224KeyLength = 224
Private Member Functions
void PrintMpi (std::ostream &output, const char *name, mbedtls_mpi number)
void PrintVector (std::ostream &output, const char *name, const std::vector< uint8_t > &vector)
Static Private Member Functions
static int RandomEntropy (void *data, unsigned char *output, size_t length, size_t *outputLength)
static int UccRandom (uint8_t *dest, unsigned size)
Private Attributes
mbedtls_pk_context pk
std::vector< uint8_t > aesKey
std::vector< uint8_t > xteaKey
std::vector< uint8_t > hmacKey
std::vector< uint8_t > ecDsa224PublicKey
std::vector< uint8_t > ecDsa224PrivateKey
Static Private Attributes
static RandomNumberGenerator * randomNumberGenerator = nullptr
Detailed Description
Definition at line 13 of file MaterialGenerator.hpp.
Constructor & Destructor Documentation
MaterialGenerator()
application::MaterialGenerator::MaterialGenerator (RandomNumberGenerator & randomNumberGenerator) explicit
Definition at line 14 of file MaterialGenerator.cpp.
References aesKey, aesKeyLength, ecDsa224KeyLength, ecDsa224PrivateKey, ecDsa224PublicKey, application::RandomNumberGenerator::Generate(), hmacKey, hmacKeyLength, pk, RandomEntropy(), randomNumberGenerator, rsaKeyLength, UccRandom(), xteaKey, and xteaKeyLength.
     {
         MaterialGenerator::randomNumberGenerator = &randomNumberGenerator;
         aesKey = randomNumberGenerator.Generate(aesKeyLength / 8);
         xteaKey = randomNumberGenerator.Generate(xteaKeyLength / 8);
         hmacKey = randomNumberGenerator.Generate(hmacKeyLength / 8);
         int ret;
         ecDsa224PublicKey.resize(ecDsa224KeyLength / 8 * 2);
         ecDsa224PrivateKey.resize(ecDsa224KeyLength / 8 * 2);
         uECC_set_rng(UccRandom);
         ret = uECC_make_key(ecDsa224PublicKey.data(), ecDsa224PrivateKey.data(), uECC_secp224r1());
         if (ret != 1)
             throw std::exception("uECC_make_key returned an error");
         mbedtls_entropy_context entropy;
         mbedtls_entropy_init(&entropy);
         ret = mbedtls_entropy_add_source(&entropy, RandomEntropy, NULL, 32, MBEDTLS_ENTROPY_SOURCE_STRONG);
         if (ret != 0)
             throw std::exception("mbedtls_entropy_add_source returned an error");
         mbedtls_ctr_drbg_context ctr_drbg;
         mbedtls_ctr_drbg_init(&ctr_drbg);
         ret = mbedtls_ctr_drbg_seed(&ctr_drbg, mbedtls_entropy_func, &entropy, nullptr, 0);
         if (ret != 0)
             throw std::exception("mbedtls_ctr_drbg_seed returned an error");
         mbedtls_pk_init(&pk);
         ret = mbedtls_pk_setup(&pk, mbedtls_pk_info_from_type(MBEDTLS_PK_RSA));
         if (ret != 0)
             throw std::exception("mbedtls_pk_setup returned an error");
         ret = mbedtls_rsa_gen_key(mbedtls_pk_rsa(pk), mbedtls_ctr_drbg_random, &ctr_drbg,
             rsaKeyLength, 65537);
         if (ret != 0)
             throw std::exception("mbedtls_rsa_gen_key returned an error");
         mbedtls_rsa_context* rsaContext = static_cast<mbedtls_rsa_context*>(pk.pk_ctx);
         mbedtls_rsa_set_padding(rsaContext, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
         ret = mbedtls_rsa_check_privkey(rsaContext);
         if (ret != 0)
             throw std::exception("Public key is invalid");
         mbedtls_ctr_drbg_free(&ctr_drbg);
         mbedtls_entropy_free(&entropy);
     }
~MaterialGenerator()
application::MaterialGenerator::~MaterialGenerator ()
Definition at line 67 of file MaterialGenerator.cpp.
References pk.
     {
         mbedtls_pk_free(&pk);
     }
Member Function Documentation
PrintMpi()
void application::MaterialGenerator::PrintMpi (std::ostream & output, const char * name, mbedtls_mpi number) private
Definition at line 128 of file MaterialGenerator.cpp.
References PrintVector().
Referenced by WriteKeys().
     {
         std::vector<uint32_t> n(number.p, number.p + number.n);
         std::vector<uint8_t> m;
         for (uint32_t word: n)
         {
             m.push_back(static_cast<uint8_t>(word));
             m.push_back(static_cast<uint8_t>(word >> 8));
             m.push_back(static_cast<uint8_t>(word >> 16));
             m.push_back(static_cast<uint8_t>(word >> 24));
         }
         PrintVector(output, name, m);
     }
PrintVector()
void application::MaterialGenerator::PrintVector (std::ostream & output, const char * name, const std::vector< uint8_t > & vector) private
Definition at line 143 of file MaterialGenerator.cpp.
Referenced by PrintMpi(), and WriteKeys().
     {
         std::ios oldState(nullptr);
         oldState.copyfmt(output);
         output << "const std::array<uint8_t, " << vector.size() << "> " << name << " = { {";
         for (std::size_t i = 0; i != vector.size(); i++)
         {
             if (i % 8 == 0)
                 output << "\n    ";
             output << "0x" << std::setw(2) << std::setfill('0') << std::hex << static_cast<int>(vector[i]) << std::dec;
             if (i != vector.size() - 1)
                 output << ", ";
         }
         output << "\n} };\n\n";
         output.copyfmt(oldState);
     }                                                                                                                   //TICS !COV_CPP_STREAM_FORMAT_STATE_01
RandomEntropy()
int application::MaterialGenerator::RandomEntropy (void * data, unsigned char * output, size_t length, size_t * outputLength) static private
Definition at line 112 of file MaterialGenerator.cpp.
References application::RandomNumberGenerator::Generate(), and randomNumberGenerator.
Referenced by MaterialGenerator().
     {
         std::vector<uint8_t> entropy = randomNumberGenerator->Generate(length);
         std::copy(entropy.begin(), entropy.end(), output);
         *outputLength = length;
         return 0;
     }
UccRandom()
int application::MaterialGenerator::UccRandom (uint8_t * dest, unsigned size) static private
Definition at line 121 of file MaterialGenerator.cpp.
References application::RandomNumberGenerator::Generate(), and randomNumberGenerator.
Referenced by MaterialGenerator().
     {
         std::vector<uint8_t> entropy = randomNumberGenerator->Generate(size);
         std::copy(entropy.begin(), entropy.end(), dest);
         return 1;
     }
WriteKeys()
void application::MaterialGenerator::WriteKeys (const std::string & fileName)
Definition at line 72 of file MaterialGenerator.cpp.
References aesKey, ecDsa224PrivateKey, ecDsa224PublicKey, hmacKey, pk, PrintMpi(), PrintVector(), and xteaKey.
Referenced by main().
     {
         std::ofstream file(fileName.c_str());
         if (!file)
             throw std::exception((std::string("Cannot open/create: ") + fileName).c_str());
         mbedtls_rsa_context* rsaContext = static_cast<mbedtls_rsa_context*>(pk.pk_ctx);
         file << R"(#include "upgrade_keys/Keys.hpp"
 )";
         PrintVector(file, "aesKey", aesKey);
         PrintVector(file, "xteaKey", xteaKey);
         PrintVector(file, "hmacKey", hmacKey);
         PrintVector(file, "ecDsa224PublicKey", ecDsa224PublicKey);
         PrintMpi(file, "rsaPrivateKeyN", rsaContext->N);
         PrintMpi(file, "rsaPrivateKeyE", rsaContext->E);
         file << R"(#ifdef CCOLA_HOST_BUILD
 // Private keys are only available in the upgrade builder, which is compiled only on the host.
 // So when compiling for any embedded platform, these keys are not included
 )";
         PrintVector(file, "ecDsa224PrivateKey", ecDsa224PrivateKey);
         PrintMpi(file, "rsaPrivateKeyD", rsaContext->D);
         PrintMpi(file, "rsaPrivateKeyP", rsaContext->P);
         PrintMpi(file, "rsaPrivateKeyQ", rsaContext->Q);
         PrintMpi(file, "rsaPrivateKeyDP", rsaContext->DP);
         PrintMpi(file, "rsaPrivateKeyDQ", rsaContext->DQ);
         PrintMpi(file, "rsaPrivateKeyQP", rsaContext->QP);
         file << R"(#endif
 )";
     }
Member Data Documentation
aesKey
std::vector<uint8_t> application::MaterialGenerator::aesKey private
Definition at line 38 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), and WriteKeys().
aesKeyLength
const std::size_t application::MaterialGenerator::aesKeyLength = 128 static
Definition at line 20 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator().
ecDsa224KeyLength
const std::size_t application::MaterialGenerator::ecDsa224KeyLength = 224 static
Definition at line 23 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator().
ecDsa224PrivateKey
std::vector<uint8_t> application::MaterialGenerator::ecDsa224PrivateKey private
Definition at line 42 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), and WriteKeys().
ecDsa224PublicKey
std::vector<uint8_t> application::MaterialGenerator::ecDsa224PublicKey private
Definition at line 41 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), and WriteKeys().
hmacKey
std::vector<uint8_t> application::MaterialGenerator::hmacKey private
Definition at line 40 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), and WriteKeys().
hmacKeyLength
const std::size_t application::MaterialGenerator::hmacKeyLength = 256 static
Definition at line 21 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator().
pk
mbedtls_pk_context application::MaterialGenerator::pk private
Definition at line 36 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), WriteKeys(), and ~MaterialGenerator().
randomNumberGenerator
RandomNumberGenerator * application::MaterialGenerator::randomNumberGenerator = nullptr static private
Definition at line 35 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), RandomEntropy(), and UccRandom().
rsaKeyLength
const std::size_t application::MaterialGenerator::rsaKeyLength = 1024 static
Definition at line 19 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator().
xteaKey
std::vector<uint8_t> application::MaterialGenerator::xteaKey private
Definition at line 39 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator(), and WriteKeys().
xteaKeyLength
const std::size_t application::MaterialGenerator::xteaKeyLength = 128 static
Definition at line 22 of file MaterialGenerator.hpp.
Referenced by MaterialGenerator().
The documentation for this class was generated from the following files:
MaterialGenerator.hpp
MaterialGenerator.cpp