EMil: hal::SerialCommunicationMock Class Reference
hal::SerialCommunicationMock Class Reference
#include <SerialCommunicationMock.hpp>
Public Member Functions
virtual void SendData (infra::ConstByteRange data, infra::Function< void()> actionOnCompletion) override
virtual void ReceiveData (infra::Function< void(infra::ConstByteRange data)> dataReceived) override
MOCK_METHOD1 (SendDataMock, void(std::vector< uint8_t >))
Public Attributes
infra::AutoResetFunction< void()> actionOnCompletion
infra::Function< void(infra::ConstByteRange data)> dataReceived
Additional Inherited Members
Protected Member Functions inherited from hal::SerialCommunication
SerialCommunication ()=default
~SerialCommunication ()=default
Detailed Description
Definition at line 11 of file SerialCommunicationMock.hpp.
Member Function Documentation
MOCK_METHOD1()
hal::SerialCommunicationMock::MOCK_METHOD1 (SendDataMock , void(std::vector< uint8_t >))
ReceiveData()
void hal::SerialCommunicationMock::ReceiveData (infra::Function< void(infra::ConstByteRange data)> dataReceived) override virtual
Implements hal::SerialCommunication.
Definition at line 12 of file SerialCommunicationMock.cpp.
References dataReceived.
     {
         this->dataReceived = dataReceived;
     }
SendData()
void hal::SerialCommunicationMock::SendData (infra::ConstByteRange data, infra::Function< void()> actionOnCompletion) override virtual
Implements hal::SerialCommunication.
Reimplemented in hal::SerialCommunicationMockWithAssert.
Definition at line 5 of file SerialCommunicationMock.cpp.
References actionOnCompletion, and data.
     {
         this->actionOnCompletion = actionOnCompletion;
         SendDataMock(std::vector<uint8_t>(data.begin(), data.end()));
     }
Member Data Documentation
actionOnCompletion
infra::AutoResetFunction<void()> hal::SerialCommunicationMock::actionOnCompletion
Definition at line 21 of file SerialCommunicationMock.hpp.
Referenced by SendData(), and hal::SerialCommunicationMockWithAssert::SendData().
dataReceived
infra::Function<void(infra::ConstByteRange data)> hal::SerialCommunicationMock::dataReceived
Definition at line 22 of file SerialCommunicationMock.hpp.
Referenced by ReceiveData().
The documentation for this class was generated from the following files:
SerialCommunicationMock.hpp
SerialCommunicationMock.cpp