EMil: TestStringInputStream.cpp File Reference
TestStringInputStream.cpp File Reference
Functions
TEST (StringInputStreamTest, ExtractDecimal)
TEST (StringInputStreamTest, ExtractHex)
TEST (StringInputStreamTest, ExtractSmallValue)
TEST (StringInputStreamTest, ExtractDelimitedValue)
TEST (StringInputStreamTest, ExtractPartialValue)
TEST (StringInputStreamTest, ExtractUint16)
TEST (StringInputStreamTest, ExtractUint32)
TEST (StringInputStreamTest, ExtractUint64)
TEST (StringInputStreamTest, ExtractHexWithOverflow)
TEST (StringInputStreamTest, ExtractHexWithoutGoodCharacters)
TEST (StringInputStreamTest, Consume)
TEST (StringInputStreamTest, FromBase64)
TEST (StringInputStreamTest, FromBase64_with_one_pad)
TEST (StringInputStreamTest, FromBase64_with_two_pads)
TEST (StringInputStreamTest, FromBase64_with_insufficient_input_reports_error)
TEST (StringInputStreamTest, Rewind)
Function Documentation
TEST() [1/16]
TEST (StringInputStreamTest , ExtractDecimal)
Definition at line 6 of file TestStringInputStream.cpp.
References EXPECT_EQ(), and value.
 {
     infra::BoundedString::WithStorage<10> string("12");
     infra::StringInputStream stream(string);
     uint8_t value;
     stream >> value;
     EXPECT_EQ(12, value);
 }
TEST() [2/16]
TEST (StringInputStreamTest , ExtractHex)
Definition at line 16 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<10> string("ab");
     infra::StringInputStream stream(string);
     uint8_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xab, value);
 }
TEST() [3/16]
TEST (StringInputStreamTest , ExtractSmallValue)
Definition at line 26 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<10> string("a");
     infra::StringInputStream stream(string);
     uint8_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xa, value);
 }
TEST() [4/16]
TEST (StringInputStreamTest , ExtractDelimitedValue)
Definition at line 36 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<10> string("a ");
     infra::StringInputStream stream(string);
     uint8_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xa, value);
 }
TEST() [5/16]
TEST (StringInputStreamTest , ExtractPartialValue)
Definition at line 46 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<10> string("abcd");
     infra::StringInputStream stream(string);
     uint8_t value;
     stream >> infra::hex >> infra::Width(1) >> value;
     EXPECT_EQ(0xa, value);
 }
TEST() [6/16]
TEST (StringInputStreamTest , ExtractUint16)
Definition at line 56 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<10> string("abcd");
     infra::StringInputStream stream(string);
     uint16_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xabcd, value);
 }
TEST() [7/16]
TEST (StringInputStreamTest , ExtractUint32)
Definition at line 66 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<10> string("abcd0123");
     infra::StringInputStream stream(string);
     uint32_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xabcd0123, value);
 }
TEST() [8/16]
TEST (StringInputStreamTest , ExtractUint64)
Definition at line 76 of file TestStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     infra::BoundedString::WithStorage<17> string("abcd0123abcd0123");
     infra::StringInputStream stream(string);
     uint64_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xabcd0123abcd0123, value);
 }
TEST() [9/16]
TEST (StringInputStreamTest , ExtractHexWithOverflow)
Definition at line 86 of file TestStringInputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::InputStream::Failed(), infra::hex, and infra::softFail.
 {
     infra::BoundedString::WithStorage<1> string("");
     infra::StringInputStream stream(string, infra::softFail);
     uint8_t v(1);
     stream >> infra::hex >> v;
     EXPECT_EQ(0, v);
     EXPECT_TRUE(stream.Failed());
 }
TEST() [10/16]
TEST (StringInputStreamTest , ExtractHexWithoutGoodCharacters)
Definition at line 97 of file TestStringInputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::InputStream::Failed(), infra::hex, and infra::softFail.
 {
     infra::StringInputStream stream(infra::BoundedConstString("k"), infra::softFail);
     uint8_t v(1);
     stream >> infra::hex >> v;
     EXPECT_EQ(0, v);
     EXPECT_TRUE(stream.Failed());
 }
TEST() [11/16]
TEST (StringInputStreamTest , Consume)
Definition at line 107 of file TestStringInputStream.cpp.
References infra::ByteRangeAsString(), infra::InputStream::Consume(), EXPECT_EQ(), infra::noFail, infra::InputStream::PeekContiguousRange(), and infra::MemoryRange< T >::size().
 {
     infra::BoundedConstString string("abcd");
     infra::StringInputStream stream(string, infra::noFail);
     EXPECT_EQ(string, infra::ByteRangeAsString(stream.PeekContiguousRange(0)));
     stream.Consume(stream.PeekContiguousRange().size());
     EXPECT_EQ("", infra::ByteRangeAsString(stream.PeekContiguousRange(0)));
 }
TEST() [12/16]
TEST (StringInputStreamTest , FromBase64)
Definition at line 117 of file TestStringInputStream.cpp.
References infra::InputStream::Empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::FromBase64().
 {
     infra::StringInputStream stream(infra::BoundedConstString("YWJj"));
     std::array<uint8_t, 3> output;
     stream >> infra::FromBase64(output);
     EXPECT_EQ((std::array<uint8_t, 3>{ 'a', 'b', 'c'}), output);
     EXPECT_TRUE(stream.Empty());
 }
TEST() [13/16]
TEST (StringInputStreamTest , FromBase64_with_one_pad)
Definition at line 128 of file TestStringInputStream.cpp.
References infra::InputStream::Empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::FromBase64().
 {
     infra::StringInputStream stream(infra::BoundedConstString("YWI="));
     std::array<uint8_t, 2> output;
     stream >> infra::FromBase64(output);
     EXPECT_EQ((std::array<uint8_t, 2>{ 'a', 'b' }), output);
     EXPECT_TRUE(stream.Empty());
 }
TEST() [14/16]
TEST (StringInputStreamTest , FromBase64_with_two_pads)
Definition at line 139 of file TestStringInputStream.cpp.
References infra::InputStream::Empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::FromBase64().
 {
     infra::StringInputStream stream(infra::BoundedConstString("YQ=="));
     std::array<uint8_t, 1> output;
     stream >> infra::FromBase64(output);
     EXPECT_EQ((std::array<uint8_t, 1>{ 'a' }), output);
     EXPECT_TRUE(stream.Empty());
 }
TEST() [15/16]
TEST (StringInputStreamTest , FromBase64_with_insufficient_input_reports_error)
Definition at line 150 of file TestStringInputStream.cpp.
References infra::InputStream::ErrorPolicy(), EXPECT_TRUE(), infra::StreamErrorPolicy::Failed(), infra::FromBase64(), and infra::softFail.
 {
     infra::StringInputStream stream(infra::BoundedConstString("YWJ"), infra::softFail);
     std::array<uint8_t, 3> output;
     stream >> infra::FromBase64(output);
     EXPECT_TRUE(stream.ErrorPolicy().Failed());
 }
TEST() [16/16]
TEST (StringInputStreamTest , Rewind)
Definition at line 160 of file TestStringInputStream.cpp.
References infra::StringInputStreamReader::ConstructSaveMarker(), EXPECT_EQ(), infra::hex, infra::TextInputStream::WithReader< TheReader >::Reader(), infra::StringInputStreamReader::Rewind(), and value.
 {
     infra::BoundedString::WithStorage<10> string("abcd");
     infra::StringInputStream stream(string);
     auto marker = stream.Reader().ConstructSaveMarker();
     uint8_t value;
     stream >> infra::hex >> infra::Width(2) >> value;
     EXPECT_EQ(0xab, value);
     stream.Reader().Rewind(marker);
     stream >> infra::hex >> infra::Width(2) >> value;
     EXPECT_EQ(0xab, value);
 }