EMil: services::DatagramBsd Class Reference
services::DatagramBsd Class Reference
#include <DatagramBsd.hpp>
Classes
class StreamWriterBsd
Public Member Functions
DatagramBsd (EventDispatcherWithNetwork &network, uint16_t port, DatagramExchangeObserver &observer)
DatagramBsd (EventDispatcherWithNetwork &network, DatagramExchangeObserver &observer)
DatagramBsd (EventDispatcherWithNetwork &network, UdpSocket remote, DatagramExchangeObserver &observer)
DatagramBsd (EventDispatcherWithNetwork &network, uint16_t localPort, UdpSocket remote, DatagramExchangeObserver &observer)
~DatagramBsd ()
virtual void RequestSendStream (std::size_t sendSize) override
virtual void RequestSendStream (std::size_t sendSize, UdpSocket to) override
void Receive ()
void Send ()
void TrySend ()
Public Member Functions inherited from infra::Subject< DatagramExchangeObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::EnableSharedFromThis< DatagramBsd >
SharedPtr< DatagramBsd > SharedFromThis ()
SharedPtr< const DatagramBsd > SharedFromThis () const
WeakPtr< DatagramBsd > WeakFromThis ()
WeakPtr< const DatagramBsd > WeakFromThis () const
void MakeShared (SharedPtr< DatagramBsd > sharedPtr)
Private Member Functions
void InitSocket ()
void BindLocal (uint16_t port)
void BindRemote (UdpSocket remote)
void TryAllocateSendStream ()
Private Attributes
EventDispatcherWithNetwork & network
int socket = ::socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)
infra::Optional< UdpSocket > connectedTo
infra::Optional< infra::BoundedVector< uint8_t >::WithMaxSize< 508 > > sendBuffer
infra::SharedOptional< StreamWriterBsd > streamWriter
std::size_t requestedSendSize = 0
UdpSocket requestedTo
bool trySend = false
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< DatagramBsd >
using EnableSharedFromThisType = DatagramBsd
Protected Member Functions inherited from infra::Subject< DatagramExchangeObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< DatagramExchangeObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< DatagramExchangeObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::EnableSharedFromThis< DatagramBsd >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 19 of file DatagramBsd.hpp.
Constructor & Destructor Documentation
DatagramBsd() [1/4]
services::DatagramBsd::DatagramBsd (EventDispatcherWithNetwork & network, uint16_t port, DatagramExchangeObserver & observer)
Definition at line 11 of file DatagramBsd.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(port);
     }
DatagramBsd() [2/4]
services::DatagramBsd::DatagramBsd (EventDispatcherWithNetwork & network, DatagramExchangeObserver & observer)
Definition at line 19 of file DatagramBsd.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(0);
     }
DatagramBsd() [3/4]
services::DatagramBsd::DatagramBsd (EventDispatcherWithNetwork & network, UdpSocket remote, DatagramExchangeObserver & observer)
Definition at line 27 of file DatagramBsd.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), BindRemote(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(0);
         BindRemote(remote);
     }
DatagramBsd() [4/4]
services::DatagramBsd::DatagramBsd (EventDispatcherWithNetwork & network, uint16_t localPort, UdpSocket remote, DatagramExchangeObserver & observer)
Definition at line 36 of file DatagramBsd.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), BindRemote(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(localPort);
         BindRemote(remote);
     }
~DatagramBsd()
services::DatagramBsd::~DatagramBsd ()
Definition at line 45 of file DatagramBsd.cpp.
References infra::Subject< DatagramExchangeObserver >::GetObserver(), and socket.
     {
         GetObserver().Detach();
         int result = close(socket);
         if (result == -1)
             std::abort();
     }
Member Function Documentation
BindLocal()
void services::DatagramBsd::BindLocal (uint16_t port) private
Definition at line 130 of file DatagramBsd.cpp.
References socket.
Referenced by DatagramBsd().
     {
         sockaddr_in address{};
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = INADDR_ANY;
         address.sin_port = htons(port);
         auto result = bind(socket, reinterpret_cast<sockaddr*>(&address), sizeof(address));
         assert(result == 0);
     }
BindRemote()
void services::DatagramBsd::BindRemote (UdpSocket remote) private
Definition at line 140 of file DatagramBsd.cpp.
References services::connect, connectedTo, services::ConvertToUint32(), infra::Variant< T >::Get(), and socket.
Referenced by DatagramBsd().
     {
         sockaddr_in address{};
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = htonl(services::ConvertToUint32(remote.Get<Udpv4Socket>().first));
         address.sin_port = htons(remote.Get<Udpv4Socket>().second);
         auto result = connect(socket, reinterpret_cast<sockaddr*>(&address), sizeof(address));
         assert(result == 0);
         connectedTo = remote;
     }
InitSocket()
void services::DatagramBsd::InitSocket () private
Definition at line 120 of file DatagramBsd.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), Receive(), infra::EventDispatcherWorker::Schedule(), and socket.
Referenced by DatagramBsd().
     {
         assert(socket != -1);
         if (fcntl(socket, F_SETFL, fcntl(socket, F_GETFL, 0) | O_NONBLOCK) == -1)
             std::abort();
         infra::EventDispatcher::Instance().Schedule([this]() { Receive(); });
     }
Receive()
void services::DatagramBsd::Receive ()
Definition at line 67 of file DatagramBsd.cpp.
References services::ConvertFromUint32(), infra::Subject< DatagramExchangeObserver >::GetObserver(), infra::MakeRange(), and socket.
Referenced by InitSocket().
     {
         infra::BoundedVector<uint8_t>::WithMaxSize<508> receiveBuffer;
         receiveBuffer.resize(receiveBuffer.max_size());
         sockaddr_in fromAddress{};
         socklen_t fromAddressSize = sizeof(fromAddress);
         auto received = recvfrom(socket, reinterpret_cast<char*>(receiveBuffer.data()), receiveBuffer.size(), 0, reinterpret_cast<sockaddr*>(&fromAddress), &fromAddressSize);
         if (received == -1)
         {
             if (errno != EWOULDBLOCK && errno != EMSGSIZE)
                 std::abort();
             return;
         }
         else if (fromAddressSize == sizeof(fromAddress) && fromAddress.sin_family == AF_INET)
         {
             receiveBuffer.resize(received);
             infra::ByteInputStreamReader reader(infra::MakeRange(receiveBuffer));
             auto from = Udpv4Socket{ services::ConvertFromUint32(ntohl(fromAddress.sin_addr.s_addr)), fromAddress.sin_port };
             GetObserver().DataReceived(reader, from);
         }
     }
RequestSendStream() [1/2]
void services::DatagramBsd::RequestSendStream (std::size_t sendSize) override virtual
Implements services::DatagramExchange.
Definition at line 54 of file DatagramBsd.cpp.
References connectedTo.
     {
         RequestSendStream(sendSize, *connectedTo);
     }
RequestSendStream() [2/2]
void services::DatagramBsd::RequestSendStream (std::size_t sendSize, UdpSocket to) override virtual
Implements services::DatagramExchange.
Definition at line 59 of file DatagramBsd.cpp.
References requestedSendSize, requestedTo, streamWriter, and TryAllocateSendStream().
     {
         assert(streamWriter.Allocatable());
         requestedSendSize = sendSize;
         requestedTo = to;
         TryAllocateSendStream();
     }
Send()
void services::DatagramBsd::Send ()
Definition at line 93 of file DatagramBsd.cpp.
References services::ConvertToUint32(), infra::BoundedVector< T >::data(), infra::Variant< T >::Get(), infra::none, requestedTo, sendBuffer, infra::BoundedVector< T >::size(), and socket.
Referenced by TrySend().
     {
         sockaddr_in address{};
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = htonl(services::ConvertToUint32(requestedTo.Get<Udpv4Socket>().first));
         address.sin_port = htons(requestedTo.Get<Udpv4Socket>().second);
         int sent = sendto(socket, reinterpret_cast<char*>(sendBuffer->data()), sendBuffer->size(), 0, reinterpret_cast<sockaddr*>(&address), sizeof(address));
         if (sent == -1)
         {
             if (errno != EWOULDBLOCK)
                 std::abort();
             return;
         }
         sendBuffer = infra::none;
     }
TryAllocateSendStream()
void services::DatagramBsd::TryAllocateSendStream () private
Definition at line 152 of file DatagramBsd.cpp.
References infra::Optional< T >::Emplace(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), requestedSendSize, infra::EventDispatcherWithWeakPtrWorker::Schedule(), sendBuffer, infra::EnableSharedFromThis< DatagramBsd >::SharedFromThis(), and streamWriter.
Referenced by RequestSendStream().
     {
         assert(streamWriter.Allocatable());
         if (!sendBuffer)
         {
             sendBuffer.Emplace(requestedSendSize, 0);
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<DatagramBsd>& object)
             {
                 infra::SharedPtr<infra::StreamWriter> writer = object->streamWriter.Emplace(*object);
                 object->GetObserver().SendStreamAvailable(std::move(writer));
             }, SharedFromThis());
         }
     }
TrySend()
void services::DatagramBsd::TrySend ()
Definition at line 111 of file DatagramBsd.cpp.
References Send(), and trySend.
     {
         if (trySend)
         {
             trySend = false;
             Send();
         }
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 56 of file DatagramBsd.hpp.
Member Data Documentation
connectedTo
infra::Optional<UdpSocket> services::DatagramBsd::connectedTo private
Definition at line 60 of file DatagramBsd.hpp.
Referenced by BindRemote(), and RequestSendStream().
network
EventDispatcherWithNetwork& services::DatagramBsd::network private
Definition at line 58 of file DatagramBsd.hpp.
requestedSendSize
std::size_t services::DatagramBsd::requestedSendSize = 0 private
Definition at line 65 of file DatagramBsd.hpp.
Referenced by RequestSendStream(), and TryAllocateSendStream().
requestedTo
UdpSocket services::DatagramBsd::requestedTo private
Definition at line 66 of file DatagramBsd.hpp.
Referenced by RequestSendStream(), and Send().
sendBuffer
infra::Optional<infra::BoundedVector<uint8_t>::WithMaxSize<508> > services::DatagramBsd::sendBuffer private
Definition at line 62 of file DatagramBsd.hpp.
Referenced by Send(), and TryAllocateSendStream().
socket
int services::DatagramBsd::socket = ::socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) private
Definition at line 59 of file DatagramBsd.hpp.
Referenced by BindLocal(), BindRemote(), InitSocket(), Receive(), Send(), and ~DatagramBsd().
streamWriter
infra::SharedOptional<StreamWriterBsd> services::DatagramBsd::streamWriter private
Definition at line 64 of file DatagramBsd.hpp.
Referenced by RequestSendStream(), and TryAllocateSendStream().
trySend
bool services::DatagramBsd::trySend = false private
Definition at line 67 of file DatagramBsd.hpp.
Referenced by TrySend().
The documentation for this class was generated from the following files:
DatagramBsd.hpp
DatagramBsd.cpp