EMil: infra::ProtoLengthDelimited Class Reference
infra::ProtoLengthDelimited Class Reference
#include <ProtoParser.hpp>
Public Member Functions
ProtoLengthDelimited (infra::DataInputStream inputStream, uint32_t length)
ProtoLengthDelimited (const ProtoLengthDelimited &other)
void SkipEverything ()
ProtoParser Parser ()
void GetString (infra::BoundedString &string)
void GetBytes (infra::BoundedVector< uint8_t > &bytes)
Private Attributes
infra::LimitedStreamReader limitedReader
infra::DataInputStream input
Detailed Description
Definition at line 14 of file ProtoParser.hpp.
Constructor & Destructor Documentation
ProtoLengthDelimited() [1/2]
infra::ProtoLengthDelimited::ProtoLengthDelimited (infra::DataInputStream inputStream, uint32_t length)
Definition at line 7 of file ProtoParser.cpp.
References infra::InputStream::Available(), infra::InputStream::ErrorPolicy(), and infra::StreamErrorPolicy::ReportResult().
         : limitedReader(inputStream.Reader(), length)
         , input(limitedReader, inputStream.ErrorPolicy())
     {
         inputStream.ErrorPolicy().ReportResult(inputStream.Available() >= length);
     }
ProtoLengthDelimited() [2/2]
infra::ProtoLengthDelimited::ProtoLengthDelimited (const ProtoLengthDelimited & other)
Definition at line 14 of file ProtoParser.cpp.
         : limitedReader(other.limitedReader)
         , input(limitedReader, other.input.ErrorPolicy())
     {}
Member Function Documentation
GetBytes()
void infra::ProtoLengthDelimited::GetBytes (infra::BoundedVector< uint8_t > & bytes)
Definition at line 37 of file ProtoParser.cpp.
References infra::InputStream::Available(), input, infra::MakeRange(), infra::BoundedVector< T >::max_size(), infra::BoundedVector< T >::resize(), and infra::BoundedVector< T >::size().
     {
         bytes.resize(std::min(input.Available(), bytes.max_size()));
         assert(bytes.size() == input.Available());
         input >> infra::MakeRange(bytes);
     }
GetString()
void infra::ProtoLengthDelimited::GetString (infra::BoundedString & string)
Definition at line 30 of file ProtoParser.cpp.
References infra::InputStream::Available(), input, and infra::StringAsByteRange().
     {
         string.resize(std::min(input.Available(), string.max_size()));
         assert(string.size() == input.Available());
         input >> infra::StringAsByteRange(string);
     }
Parser()
ProtoParser infra::ProtoLengthDelimited::Parser ()
Definition at line 25 of file ProtoParser.cpp.
References input.
     {
         return ProtoParser(input);
     }
SkipEverything()
void infra::ProtoLengthDelimited::SkipEverything ()
Definition at line 19 of file ProtoParser.cpp.
References infra::InputStream::ContiguousRange(), infra::InputStream::Empty(), and input.
     {
         while (!input.Empty())
             input.ContiguousRange();
     }
Member Data Documentation
input
infra::DataInputStream infra::ProtoLengthDelimited::input private
Definition at line 28 of file ProtoParser.hpp.
Referenced by GetBytes(), GetString(), Parser(), and SkipEverything().
limitedReader
infra::LimitedStreamReader infra::ProtoLengthDelimited::limitedReader private
Definition at line 27 of file ProtoParser.hpp.
The documentation for this class was generated from the following files:
ProtoParser.hpp
ProtoParser.cpp