EMil: services::ConnectionObserverStub Class Reference
services::ConnectionObserverStub Class Reference
#include <ConnectionStub.hpp>
Public Member Functions
ConnectionObserverStub ()=default
ConnectionObserverStub (services::Connection &connection)
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
void SendData (const std::vector< uint8_t > &data)
Public Member Functions inherited from services::ConnectionObserver
virtual void Connected ()
virtual void ClosingConnection ()
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Attributes
std::vector< uint8_t > receivedData
Private Member Functions
void TryRequestSendStream ()
Private Attributes
std::size_t requestedSendStreamSize = 0
std::vector< uint8_t > sendData
Additional Inherited Members
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Detailed Description
Definition at line 86 of file ConnectionStub.hpp.
Constructor & Destructor Documentation
ConnectionObserverStub() [1/2]
services::ConnectionObserverStub::ConnectionObserverStub () default
ConnectionObserverStub() [2/2]
services::ConnectionObserverStub::ConnectionObserverStub (services::Connection & connection) inline
Definition at line 91 of file ConnectionStub.hpp.
             : services::ConnectionObserver(connection)
         {}
Member Function Documentation
DataReceived()
void services::ConnectionObserverStub::DataReceived () override virtual
Implements services::ConnectionObserver.
Definition at line 119 of file ConnectionStub.cpp.
References infra::InputStream::ContiguousRange(), infra::MemoryRange< T >::empty(), and infra::Subject< ConnectionObserver >::Subject().
     {
         infra::SharedPtr<infra::StreamReader> reader = Subject().ReceiveStream();
         infra::DataInputStream::WithErrorPolicy stream(*reader);
         for (infra::ConstByteRange received = stream.ContiguousRange(); !received.empty(); received = stream.ContiguousRange())
             receivedData.insert(receivedData.end(), received.begin(), received.end());
         Subject().AckReceived();
     }
SendData()
void services::ConnectionObserverStub::SendData (const std::vector< uint8_t > & data)
Definition at line 130 of file ConnectionStub.cpp.
References data.
Referenced by TEST_F().
     {
         sendData.insert(sendData.end(), data.begin(), data.end());
         TryRequestSendStream();
     }
SendStreamAvailable()
void services::ConnectionObserverStub::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::ConnectionObserver.
Definition at line 108 of file ConnectionStub.cpp.
References data.
     {
         infra::DataOutputStream::WithErrorPolicy stream(*writer);
         infra::ConstByteRange data(sendData.data(), sendData.data() + requestedSendStreamSize);
         stream << data;
         writer = nullptr;
         sendData.erase(sendData.begin(), sendData.begin() + requestedSendStreamSize);
         requestedSendStreamSize = 0;
         TryRequestSendStream();
     }
TryRequestSendStream()
void services::ConnectionObserverStub::TryRequestSendStream () private
Definition at line 137 of file ConnectionStub.cpp.
References infra::Subject< ConnectionObserver >::Subject().
     {
         if (requestedSendStreamSize == 0 && !sendData.empty())
         {
             requestedSendStreamSize = std::min(sendData.size(), Subject().MaxSendStreamSize());
             Subject().RequestSendStream(requestedSendStreamSize);
         }
     }
Member Data Documentation
receivedData
std::vector<uint8_t> services::ConnectionObserverStub::receivedData
Definition at line 100 of file ConnectionStub.hpp.
Referenced by TEST_F().
requestedSendStreamSize
std::size_t services::ConnectionObserverStub::requestedSendStreamSize = 0 private
Definition at line 108 of file ConnectionStub.hpp.
sendData
std::vector<uint8_t> services::ConnectionObserverStub::sendData private
Definition at line 109 of file ConnectionStub.hpp.
The documentation for this class was generated from the following files:
ConnectionStub.hpp
ConnectionStub.cpp