EMil: infra::JsonToken::String Class Reference
infra::JsonToken::String Class Reference
#include <Json.hpp>
Public Member Functions
String (infra::BoundedConstString value)
bool operator== (const String &other) const
bool operator!= (const String &other) const
JsonString Value () const
BoundedConstString RawValue () const
Private Attributes
JsonString value
Detailed Description
Definition at line 166 of file Json.hpp.
Constructor & Destructor Documentation
String()
infra::JsonToken::String::String (infra::BoundedConstString value) explicit
Definition at line 393 of file Json.cpp.
             : value(value)
         {}
Member Function Documentation
operator!=()
bool infra::JsonToken::String::operator!= (const String & other) const
Definition at line 402 of file Json.cpp.
References value.
         {
             return value != other.value;
         }
operator==()
bool infra::JsonToken::String::operator== (const String & other) const
Definition at line 397 of file Json.cpp.
References value.
         {
             return value == other.value;
         }
RawValue()
BoundedConstString infra::JsonToken::String::RawValue () const
Definition at line 412 of file Json.cpp.
References infra::JsonString::Raw(), and value.
Referenced by infra::CopyToken().
         {
             return value.Raw();
         }
Value()
JsonString infra::JsonToken::String::Value () const
Definition at line 407 of file Json.cpp.
References value.
Referenced by infra::JsonIterator::ConvertValue().
         {
             return value;
         }
Member Data Documentation
value
JsonString infra::JsonToken::String::value private
Definition at line 178 of file Json.hpp.
Referenced by operator!=(), operator==(), RawValue(), and Value().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp