EMil: infra::DataOutputStream Class Reference
infra::DataOutputStream Class Reference
#include <OutputStream.hpp>
Classes
class WithErrorPolicy
class WithWriter
Public Member Functions
TextOutputStream operator<< (Text)
template<class Data >
DataOutputStream & operator<< (const Data &data)
template<class Data >
DataOutputStream & operator<< (MemoryRange< Data > data)
OutputStream (StreamWriter &writer, StreamErrorPolicy &errorPolicy)
Public Member Functions inherited from infra::OutputStream
OutputStream (StreamWriter &writer, StreamErrorPolicy &errorPolicy)
bool Failed () const
std::size_t SaveMarker () const
std::size_t ProcessedBytesSince (std::size_t marker) const
std::size_t Available () const
StreamWriter & Writer () const
StreamErrorPolicy & ErrorPolicy () const
Additional Inherited Members
Protected Member Functions inherited from infra::OutputStream
~OutputStream ()=default
Detailed Description
Definition at line 66 of file OutputStream.hpp.
Member Function Documentation
operator<<() [1/3]
TextOutputStream infra::DataOutputStream::operator<< (Text)
Definition at line 78 of file OutputStream.cpp.
References infra::OutputStream::ErrorPolicy(), and infra::OutputStream::Writer().
     {
         return TextOutputStream(Writer(), ErrorPolicy());
     }
operator<<() [2/3]
template<class Data > DataOutputStream & infra::DataOutputStream::operator<< (const Data & data)
Definition at line 291 of file OutputStream.hpp.
References infra::data, infra::OutputStream::ErrorPolicy(), infra::StreamWriter::Insert(), infra::MakeRange(), infra::ReinterpretCastByteRange(), and infra::OutputStream::Writer().
     {
         ConstByteRange dataRange(ReinterpretCastByteRange(MakeRange(&data, &data + 1)));
         Writer().Insert(dataRange, ErrorPolicy());
         return *this;
     }
operator<<() [3/3]
template<class Data > DataOutputStream & infra::DataOutputStream::operator<< (MemoryRange< Data > data)
Definition at line 299 of file OutputStream.hpp.
References infra::data, and infra::ReinterpretCastByteRange().
     {
         ConstByteRange dataRange(ReinterpretCastByteRange(data));
         Writer().Insert(dataRange, ErrorPolicy());
         return *this;
     }
OutputStream()
infra::OutputStream::OutputStream
Definition at line 43 of file OutputStream.cpp.
         : writer(writer)
         , errorPolicy(errorPolicy)
     {}
The documentation for this class was generated from the following files:
OutputStream.hpp
OutputStream.cpp