EMil: services Namespace Reference
services Namespace Reference
Classes
class AllocatorTracingConnectionMbedTlsAdapter
class CertificatesMbedTls
class ClientConnectionObserverFactory
class ClientConnectionObserverFactoryWithNameResolver
class ConfigurationBlob
class ConfigurationBlobImpl
class ConfigurationStore
class ConfigurationStoreAccess
class ConfigurationStoreBase
class ConfigurationStoreImpl
class ConfigurationStoreInterface
class Connection
class ConnectionBsd
class ConnectionFactory
class ConnectionFactoryMbedTls
class ConnectionFactoryWithNameResolver
class ConnectionFactoryWithNameResolverForTls
class ConnectionFactoryWithNameResolverImpl
class ConnectionMbedTls
class ConnectionMbedTlsConnector
class ConnectionMbedTlsListener
class ConnectionObserver
class ConnectionSerial
class ConnectionWin
class ConnectorBsd
class ConnectorWin
class CyclicStore
class DatagramBsd
class DatagramExchange
class DatagramExchangeObserver
class DatagramFactory
class DatagramWin
class DebouncedButton
class DebugLed
struct DefaultConnectionCreationContext
class DefaultHttpServer
class DnsResolver
class EventDispatcherWithNetwork
class FactoryDefaultConfigurationStore
class FactoryDefaultConfigurationStoreBase
class FlashDelayedInit
class FlashMultipleAccess
class FlashMultipleAccessMaster
class FlashQuadSpi
class FlashQuadSpiCypressFll
class FlashQuadSpiMicronN25q
class FlashQuadSpiSingleSpeed
class FlashRegion
class FlashSpi
class GpioPinInverted
class HttpClient
class HttpClientBasic
class HttpClientConnector
class HttpClientConnectorImpl
class HttpClientImpl
class HttpClientJson
class HttpClientObserver
class HttpClientObserverFactory
class HttpErrorResponse
class HttpHeader
class HttpPage
class HttpPageServer
class HttpRequestFormatter
class HttpRequestParser
class HttpRequestParserImpl
class HttpResponse
class HttpResponseBadRequest
class HttpResponseHeaderBuilder
class HttpResponseMethodNotAllowed
class HttpResponseNotFound
class HttpResponseOutOfMemory
class HttpServerConnection
class HttpServerConnectionObserver
class HttpServerConnectionObserverFactory
class HttpServerConnectionObserverFactoryImpl
class I2cMultipleAccess
class I2cMultipleAccessMaster
struct IPAddresses
struct IpConfig
class IPInfo
struct Ipv4Config
class IPv4Info
struct IPv4InterfaceAddresses
class IPv6Info
class ListenerBsd
class ListenerWin
class LlmnrResponder
class MqttClient
class MqttClientConnector
class MqttClientConnectorImpl
class MqttClientImpl
class MqttClientObserver
class MqttClientObserverFactory
class Multicast
class NameLookupBsd
class NameLookupWin
class NameResolver
class NameResolverCache
class NameResolverResult
class NetworkPing
class NetworkPingResultsObserver
class RepeatingButton
class ServerConnectionObserverFactory
class SignalLed
class SingleConnectionHttpServer
class SntpClient
class SntpResultObserver
class SpiMasterWithChipSelect
class SpiMultipleAccess
class SpiMultipleAccessMaster
class StreamEchoConnection
class StreamEchoServer
class StreamWriterOnSerialCommunication
class StreamWriterOnSynchronousSerialCommunication
class SynchronousFlashQuadSpi
class SynchronousFlashRegion
class SynchronousFlashSpi
struct SynchronousFlashSpiConfig
class SynchronousSpiMasterWithChipSelect
class Terminal
class TimeWithLocalization
class Tracer
class TracerAdapterPrintf
class TracerWithDateTime
class TracerWithTime
class TracingConnectionFactoryMbedTls
class TracingConnectionMbedTls
class TracingFlash
class TracingHttpClientImpl
class TracingInputStream
class TracingStatusHttpClientImpl
class TracingStreamReader
class WebSocket
class WebSocketFrameHeader
class WiFiNetwork
class WiFiNetworkAccessPointObserver
class WiFiNetworkJoinResultObserver
class WiFiNetworkScanner
class WiFiNetworkScanNetworkForDetailsResultObserver
class WiFiNetworkScanNetworksResultObserver
class WiFiNetworkStationObserver
struct WiFiSecurity
Typedefs
using IPv4Address = std::array< uint8_t, 4 >
using IPv6Address = std::array< uint16_t, 8 >
using IPAddress = infra::Variant< services::IPv4Address, services::IPv6Address >
using Udpv4Socket = std::pair< IPv4Address, uint16_t >
using Udpv6Socket = std::pair< IPv6Address, uint16_t >
using UdpSocket = infra::Variant< Udpv4Socket, Udpv6Socket >
using AllocatorConnectionMbedTls = infra::SharedObjectAllocator< ConnectionMbedTls, void(infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver, CertificatesMbedTls &certificates, hal::SynchronousRandomDataGenerator &randomDataGenerator, const ConnectionMbedTls::ParametersWorkaround &parameters)>
using AllocatorConnectionMbedTlsListener = infra::SharedObjectAllocator< ConnectionMbedTlsListener, void(AllocatorConnectionMbedTls &allocator, ServerConnectionObserverFactory &factory, CertificatesMbedTls &certificates, hal::SynchronousRandomDataGenerator &randomDataGenerator, mbedtls_ssl_cache_context &serverCache, bool clientAuthenticationNeeded)>
using HttpHeaders = infra::MemoryRange< const HttpHeader >
using AllocatorStreamEchoConnection = infra::SharedObjectAllocator< StreamEchoConnection, void()>
using AllocatorTracingConnectionMbedTls = infra::SharedObjectAllocator< TracingConnectionMbedTls, void(infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver, CertificatesMbedTls &certificates, hal::SynchronousRandomDataGenerator &randomDataGenerator, const ConnectionMbedTls::ParametersWorkaround &parameters, Tracer &tracer)>
using WebSocketMaskingKey = std::array< uint8_t, 4 >
using SsidString = infra::BoundedString::WithStorage< 32 >
using AllocatorConnectionBsd = infra::SharedObjectAllocator< ConnectionBsd, void(EventDispatcherWithNetwork &, int)>
using AllocatorDatagramBsd = infra::SharedObjectAllocator< DatagramBsd, void(EventDispatcherWithNetwork &, int)>
using AllocatorConnectionWin = infra::SharedObjectAllocator< ConnectionWin, void(EventDispatcherWithNetwork &, SOCKET)>
using AllocatorDatagramWin = infra::SharedObjectAllocator< DatagramWin, void(EventDispatcherWithNetwork &, SOCKET)>
Enumerations
enum IPVersions { IPVersions::ipv4, IPVersions::ipv6, IPVersions::both }
enum HttpVerb : uint8_t {
HttpVerb::get, HttpVerb::head, HttpVerb::connect, HttpVerb::options,
HttpVerb::patch, HttpVerb::put, HttpVerb::post, HttpVerb::delete_
}
enum HttpStatusCode : uint16_t {
HttpStatusCode::Continue = 100, HttpStatusCode::SwitchingProtocols = 101, HttpStatusCode::OK = 200, HttpStatusCode::Created = 201,
HttpStatusCode::Accepted = 202, HttpStatusCode::NonAuthorativeInformation = 203, HttpStatusCode::NoContent = 204, HttpStatusCode::ResetContent = 205,
HttpStatusCode::PartialContent = 206, HttpStatusCode::MultipleChoices = 300, HttpStatusCode::MovedPermanently = 301, HttpStatusCode::Found = 302,
HttpStatusCode::SeeOther = 303, HttpStatusCode::NotModified = 304, HttpStatusCode::UseProxy = 305, HttpStatusCode::TemporaryRedirect = 307,
HttpStatusCode::BadRequest = 400, HttpStatusCode::Unauthorized = 401, HttpStatusCode::PaymentRequired = 402, HttpStatusCode::Forbidden = 403,
HttpStatusCode::NotFound = 404, HttpStatusCode::MethodNotAllowed = 405, HttpStatusCode::NotAcceptable = 406, HttpStatusCode::ProxyAuthenticationRequired = 407,
HttpStatusCode::RequestTimeOut = 408, HttpStatusCode::Conflict = 409, HttpStatusCode::Gone = 410, HttpStatusCode::LengthRequired = 411,
HttpStatusCode::PreconditionFailed = 412, HttpStatusCode::RequestEntityTooLarge = 413, HttpStatusCode::RequestUriTooLarge = 414, HttpStatusCode::UnsupportedMediaType = 415,
HttpStatusCode::RequestRangeNotSatisfiable = 416, HttpStatusCode::ExpectationFailed = 417, HttpStatusCode::InternalServerError = 500, HttpStatusCode::NotImplemented = 501,
HttpStatusCode::BadGateway = 502, HttpStatusCode::ServiceUnavailable = 503, HttpStatusCode::GatewayTimeOut = 504, HttpStatusCode::HttpVersionNotSupported = 505
}
enum WebSocketMask : uint8_t {
WebSocketMask::finMask = 0x80, WebSocketMask::rsvMask = 0x70, WebSocketMask::opCodeMask = 0x0F, WebSocketMask::payloadMask = 0x80,
WebSocketMask::payloadLengthMask = 0x7F
}
enum WebSocketOpCode : uint8_t {
WebSocketOpCode::opCodeContinue = 0x00, WebSocketOpCode::opCodeText = 0x01, WebSocketOpCode::opCodeBin = 0x02, WebSocketOpCode::opCodeClose = 0x08,
WebSocketOpCode::opCodePing = 0x09, WebSocketOpCode::opCodePong = 0x0A
}
enum WiFiJoiningStatus {
WiFiJoiningStatus::noError, WiFiJoiningStatus::unknownError, WiFiJoiningStatus::timeout, WiFiJoiningStatus::authenticationError,
WiFiJoiningStatus::networkNotFound
}
Functions
UdpSocket MakeUdpSocket (IPAddress address, uint16_t port)
IPAddress GetAddress (UdpSocket socket)
uint16_t GetPort (UdpSocket socket)
IPv4Address IPv4AddressLocalHost ()
IPv6Address IPv6AddressLocalHost ()
uint32_t ConvertToUint32 (IPv4Address address)
IPv4Address ConvertFromUint32 (uint32_t address)
ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason Convert (ClientConnectionObserverFactory::ConnectFailReason reason)
infra::BoundedConstString SchemeFromUrl (infra::BoundedConstString url)
infra::BoundedConstString HostFromUrl (infra::BoundedConstString url)
infra::BoundedConstString PathFromUrl (infra::BoundedConstString url)
infra::BoundedConstString HttpVerbToString (HttpVerb verb)
infra::Optional< HttpVerb > HttpVerbFromString (infra::BoundedConstString verb)
infra::Optional< HttpStatusCode > HttpStatusCodeFromString (infra::BoundedConstString statusCode)
infra::BoundedConstString HttpStatusCodeToString (services::HttpStatusCode statusCode)
void SetGlobalTracerInstance (Tracer &tracer)
Tracer & GlobalTracer ()
Variables
static const uint32_t ethernetMtu = 1500
static const uint32_t tcpPacketOverhead = 54
static const uint32_t maxPacketPayload = ethernetMtu - tcpPacketOverhead
static const HttpHeaders noHeaders {}
Typedef Documentation
AllocatorConnectionBsd
using services::AllocatorConnectionBsd = typedef infra::SharedObjectAllocator<ConnectionBsd, void(EventDispatcherWithNetwork&, int)>
Definition at line 82 of file ConnectionBsd.hpp.
AllocatorConnectionMbedTls
using services::AllocatorConnectionMbedTls = typedef infra::SharedObjectAllocator<ConnectionMbedTls, void(infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)>&& createdObserver, CertificatesMbedTls& certificates, hal::SynchronousRandomDataGenerator& randomDataGenerator, const ConnectionMbedTls::ParametersWorkaround& parameters)>
Definition at line 137 of file ConnectionMbedTls.hpp.
AllocatorConnectionMbedTlsListener
using services::AllocatorConnectionMbedTlsListener = typedef infra::SharedObjectAllocator<ConnectionMbedTlsListener, void(AllocatorConnectionMbedTls& allocator, ServerConnectionObserverFactory& factory, CertificatesMbedTls& certificates, hal::SynchronousRandomDataGenerator& randomDataGenerator, mbedtls_ssl_cache_context& serverCache, bool clientAuthenticationNeeded)>
Definition at line 161 of file ConnectionMbedTls.hpp.
AllocatorConnectionWin
using services::AllocatorConnectionWin = typedef infra::SharedObjectAllocator<ConnectionWin, void(EventDispatcherWithNetwork&, SOCKET)>
Definition at line 85 of file ConnectionWin.hpp.
AllocatorDatagramBsd
using services::AllocatorDatagramBsd = typedef infra::SharedObjectAllocator<DatagramBsd, void(EventDispatcherWithNetwork&, int)>
Definition at line 70 of file DatagramBsd.hpp.
AllocatorDatagramWin
using services::AllocatorDatagramWin = typedef infra::SharedObjectAllocator<DatagramWin, void(EventDispatcherWithNetwork&, SOCKET)>
Definition at line 71 of file DatagramWin.hpp.
AllocatorStreamEchoConnection
using services::AllocatorStreamEchoConnection = typedef infra::SharedObjectAllocator<StreamEchoConnection, void()>
Definition at line 27 of file StreamEcho.hpp.
AllocatorTracingConnectionMbedTls
using services::AllocatorTracingConnectionMbedTls = typedef infra::SharedObjectAllocator<TracingConnectionMbedTls, void(infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)>&& createdObserver, CertificatesMbedTls& certificates, hal::SynchronousRandomDataGenerator& randomDataGenerator, const ConnectionMbedTls::ParametersWorkaround& parameters, Tracer& tracer)>
Definition at line 28 of file TracingConnectionMbedTls.hpp.
HttpHeaders
using services::HttpHeaders = typedef infra::MemoryRange<const HttpHeader>
Definition at line 83 of file Http.hpp.
IPAddress
using services::IPAddress = typedef infra::Variant<services::IPv4Address, services::IPv6Address>
Definition at line 13 of file Address.hpp.
IPv4Address
using services::IPv4Address = typedef std::array<uint8_t, 4>
Definition at line 11 of file Address.hpp.
IPv6Address
using services::IPv6Address = typedef std::array<uint16_t, 8>
Definition at line 12 of file Address.hpp.
SsidString
using services::SsidString = typedef infra::BoundedString::WithStorage<32>
Definition at line 39 of file WiFiNetwork.hpp.
UdpSocket
using services::UdpSocket = typedef infra::Variant<Udpv4Socket, Udpv6Socket>
Definition at line 24 of file Address.hpp.
Udpv4Socket
using services::Udpv4Socket = typedef std::pair<IPv4Address, uint16_t>
Definition at line 22 of file Address.hpp.
Udpv6Socket
using services::Udpv6Socket = typedef std::pair<IPv6Address, uint16_t>
Definition at line 23 of file Address.hpp.
WebSocketMaskingKey
using services::WebSocketMaskingKey = typedef std::array<uint8_t, 4>
Definition at line 30 of file WebSocket.hpp.
Enumeration Type Documentation
HttpStatusCode
enum services::HttpStatusCode : uint16_t strong
Enumerator
Continue
SwitchingProtocols
OK
Created
Accepted
NonAuthorativeInformation
NoContent
ResetContent
PartialContent
MultipleChoices
MovedPermanently
Found
SeeOther
NotModified
UseProxy
TemporaryRedirect
BadRequest
Unauthorized
PaymentRequired
Forbidden
NotFound
MethodNotAllowed
NotAcceptable
ProxyAuthenticationRequired
RequestTimeOut
Conflict
Gone
LengthRequired
PreconditionFailed
RequestEntityTooLarge
RequestUriTooLarge
UnsupportedMediaType
RequestRangeNotSatisfiable
ExpectationFailed
InternalServerError
NotImplemented
BadGateway
ServiceUnavailable
GatewayTimeOut
HttpVersionNotSupported
Definition at line 23 of file Http.hpp.
                               : uint16_t
     {
         Continue = 100,
         SwitchingProtocols = 101,
         OK = 200,
         Created = 201,
         Accepted = 202,
         NonAuthorativeInformation = 203,
         NoContent = 204,
         ResetContent = 205,
         PartialContent = 206,
         MultipleChoices = 300,
         MovedPermanently = 301,
         Found = 302,
         SeeOther = 303,
         NotModified = 304,
         UseProxy = 305,
         TemporaryRedirect = 307,
         BadRequest = 400,
         Unauthorized = 401,
         PaymentRequired = 402,
         Forbidden = 403,
         NotFound = 404,
         MethodNotAllowed = 405,
         NotAcceptable = 406,
         ProxyAuthenticationRequired = 407,
         RequestTimeOut = 408,
         Conflict = 409,
         Gone = 410,
         LengthRequired = 411,
         PreconditionFailed = 412,
         RequestEntityTooLarge = 413,
         RequestUriTooLarge = 414,
         UnsupportedMediaType = 415,
         RequestRangeNotSatisfiable = 416,
         ExpectationFailed = 417,
         InternalServerError = 500,
         NotImplemented = 501,
         BadGateway = 502,
         ServiceUnavailable = 503,
         GatewayTimeOut = 504,
         HttpVersionNotSupported = 505
     };
HttpVerb
enum services::HttpVerb : uint8_t strong
Enumerator
get
head
connect
options
patch
put
post
delete_
Definition at line 11 of file Http.hpp.
                         : uint8_t
     {
         get,
         head,
         connect,
         options,
         patch,
         put,
         post,
         delete_
     };
IPVersions
enum services::IPVersions strong
Enumerator
ipv4
ipv6
both
Definition at line 15 of file Address.hpp.
     {
         ipv4,
         ipv6,
         both
     };
WebSocketMask
enum services::WebSocketMask : uint8_t strong
Enumerator
finMask
rsvMask
opCodeMask
payloadMask
payloadLengthMask
Definition at line 11 of file WebSocket.hpp.
                              : uint8_t
     {
         finMask = 0x80,
         rsvMask = 0x70,
         opCodeMask = 0x0F,
         payloadMask = 0x80,
         payloadLengthMask = 0x7F
     };
WebSocketOpCode
enum services::WebSocketOpCode : uint8_t strong
Enumerator
opCodeContinue
opCodeText
opCodeBin
opCodeClose
opCodePing
opCodePong
Definition at line 20 of file WebSocket.hpp.
                                : uint8_t
     {
         opCodeContinue = 0x00,
         opCodeText = 0x01,
         opCodeBin = 0x02,
         opCodeClose = 0x08,
         opCodePing = 0x09,
         opCodePong = 0x0A
     };
WiFiJoiningStatus
enum services::WiFiJoiningStatus strong
Enumerator
noError
unknownError
timeout
authenticationError
networkNotFound
Definition at line 60 of file WiFiNetwork.hpp.
     {
         noError,
         unknownError,
         timeout,
         authenticationError,
         networkNotFound
     };
Function Documentation
Convert()
ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason services::Convert (ClientConnectionObserverFactory::ConnectFailReason reason)
Definition at line 5 of file ConnectionFactoryWithNameResolver.cpp.
Referenced by services::ConnectionFactoryWithNameResolverImpl::Action::ConnectionFailed().
     {
         switch (reason)
         {
             case ClientConnectionObserverFactory::ConnectFailReason::refused:
                 return ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::refused;
             case ClientConnectionObserverFactory::ConnectFailReason::connectionAllocationFailed:
                 return ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::connectionAllocationFailed;
             default:
                 std::abort();
         }
     }
ConvertFromUint32()
IPv4Address services::ConvertFromUint32 (uint32_t address)
Definition at line 45 of file Address.cpp.
Referenced by services::NameLookupBsd::LookupIPv4(), and services::DatagramBsd::Receive().
     {
         return services::IPv4Address{
             static_cast<uint8_t>(address >> 24),
             static_cast<uint8_t>(address >> 16),
             static_cast<uint8_t>(address >> 8),
             static_cast<uint8_t>(address)
         };
     }
ConvertToUint32()
uint32_t services::ConvertToUint32 (IPv4Address address)
Definition at line 40 of file Address.cpp.
Referenced by services::DatagramBsd::BindRemote(), services::ConnectorBsd::ConnectorBsd(), and services::DatagramBsd::Send().
     {
         return address[3] | (address[2] << 8) | (address[1] << 16) | (address[0] << 24);
     }
GetAddress()
IPAddress services::GetAddress (UdpSocket socket)
Definition at line 14 of file Address.cpp.
References infra::Variant< T >::Get(), and infra::Variant< T >::Is().
Referenced by services::DnsResolver::ReplyParser::AnswerIsForCurrentQuery(), and services::DnsResolver::ActiveLookup::DataReceived().
     {
         if (socket.Is<Udpv4Socket>())
             return socket.Get<Udpv4Socket>().first;
         else
             return socket.Get<Udpv6Socket>().first;
     }
GetPort()
uint16_t services::GetPort (UdpSocket socket)
Definition at line 22 of file Address.cpp.
References infra::Variant< T >::Get(), and infra::Variant< T >::Is().
     {
         if (socket.Is<Udpv4Socket>())
             return socket.Get<Udpv4Socket>().second;
         else
             return socket.Get<Udpv6Socket>().second;
     }
GlobalTracer()
Tracer & services::GlobalTracer ()
Definition at line 25 of file GlobalTracer.cpp.
     {
 #ifdef CCOLA_HOST_BUILD
         if (globalTracerInstance == nullptr)
             return tracerDummy;
 #endif
         assert(globalTracerInstance != nullptr);
         return *globalTracerInstance;
     }
HostFromUrl()
infra::BoundedConstString services::HostFromUrl (infra::BoundedConstString url)
Definition at line 56 of file Http.cpp.
References infra::BoundedStringBase< T >::find(), and infra::BoundedStringBase< T >::substr().
Referenced by services::HttpClientBasic::Hostname().
     {
         auto schemeEnd = SchemeEndPositionFromUrl(url);
         return url.substr(schemeEnd, url.find('/', schemeEnd) - schemeEnd);
     }
HttpStatusCodeFromString()
infra::Optional< HttpStatusCode > services::HttpStatusCodeFromString (infra::BoundedConstString statusCode)
Definition at line 110 of file Http.cpp.
References Accepted, BadGateway, BadRequest, Conflict, Continue, Created, ExpectationFailed, Forbidden, Found, GatewayTimeOut, Gone, HttpVersionNotSupported, InternalServerError, LengthRequired, infra::MakeOptional(), MethodNotAllowed, MovedPermanently, MultipleChoices, NoContent, NonAuthorativeInformation, infra::none, NotAcceptable, NotFound, NotImplemented, NotModified, OK, PartialContent, PaymentRequired, PreconditionFailed, ProxyAuthenticationRequired, RequestEntityTooLarge, RequestRangeNotSatisfiable, RequestTimeOut, RequestUriTooLarge, ResetContent, SeeOther, ServiceUnavailable, infra::BoundedStringBase< T >::size(), SwitchingProtocols, TemporaryRedirect, Unauthorized, UnsupportedMediaType, UseProxy, and value.
Referenced by services::HttpClientImpl::HttpResponseParser::ParseStatusLine().
     {
         std::underlying_type<services::HttpStatusCode>::type value = 0;
         for (std::size_t index = 0; index < statusCode.size(); ++index)
             value = value * 10 + statusCode[index] - '0';
         switch (value)
         {
         case 100: return infra::MakeOptional(HttpStatusCode::Continue);
         case 101: return infra::MakeOptional(HttpStatusCode::SwitchingProtocols);
         case 200: return infra::MakeOptional(HttpStatusCode::OK);
         case 201: return infra::MakeOptional(HttpStatusCode::Created);
         case 202: return infra::MakeOptional(HttpStatusCode::Accepted);
         case 203: return infra::MakeOptional(HttpStatusCode::NonAuthorativeInformation);
         case 204: return infra::MakeOptional(HttpStatusCode::NoContent);
         case 205: return infra::MakeOptional(HttpStatusCode::ResetContent);
         case 206: return infra::MakeOptional(HttpStatusCode::PartialContent);
         case 300: return infra::MakeOptional(HttpStatusCode::MultipleChoices);
         case 301: return infra::MakeOptional(HttpStatusCode::MovedPermanently);
         case 302: return infra::MakeOptional(HttpStatusCode::Found);
         case 303: return infra::MakeOptional(HttpStatusCode::SeeOther);
         case 304: return infra::MakeOptional(HttpStatusCode::NotModified);
         case 305: return infra::MakeOptional(HttpStatusCode::UseProxy);
         case 307: return infra::MakeOptional(HttpStatusCode::TemporaryRedirect);
         case 400: return infra::MakeOptional(HttpStatusCode::BadRequest);
         case 401: return infra::MakeOptional(HttpStatusCode::Unauthorized);
         case 402: return infra::MakeOptional(HttpStatusCode::PaymentRequired);
         case 403: return infra::MakeOptional(HttpStatusCode::Forbidden);
         case 404: return infra::MakeOptional(HttpStatusCode::NotFound);
         case 405: return infra::MakeOptional(HttpStatusCode::MethodNotAllowed);
         case 406: return infra::MakeOptional(HttpStatusCode::NotAcceptable);
         case 407: return infra::MakeOptional(HttpStatusCode::ProxyAuthenticationRequired);
         case 408: return infra::MakeOptional(HttpStatusCode::RequestTimeOut);
         case 409: return infra::MakeOptional(HttpStatusCode::Conflict);
         case 410: return infra::MakeOptional(HttpStatusCode::Gone);
         case 411: return infra::MakeOptional(HttpStatusCode::LengthRequired);
         case 412: return infra::MakeOptional(HttpStatusCode::PreconditionFailed);
         case 413: return infra::MakeOptional(HttpStatusCode::RequestEntityTooLarge);
         case 414: return infra::MakeOptional(HttpStatusCode::RequestUriTooLarge);
         case 415: return infra::MakeOptional(HttpStatusCode::UnsupportedMediaType);
         case 416: return infra::MakeOptional(HttpStatusCode::RequestRangeNotSatisfiable);
         case 417: return infra::MakeOptional(HttpStatusCode::ExpectationFailed);
         case 500: return infra::MakeOptional(HttpStatusCode::InternalServerError);
         case 501: return infra::MakeOptional(HttpStatusCode::NotImplemented);
         case 502: return infra::MakeOptional(HttpStatusCode::BadGateway);
         case 503: return infra::MakeOptional(HttpStatusCode::ServiceUnavailable);
         case 504: return infra::MakeOptional(HttpStatusCode::GatewayTimeOut);
         case 505: return infra::MakeOptional(HttpStatusCode::HttpVersionNotSupported);
         }
         return infra::none;
     }
HttpStatusCodeToString()
infra::BoundedConstString services::HttpStatusCodeToString (services::HttpStatusCode statusCode)
Definition at line 164 of file Http.cpp.
References Accepted, BadGateway, BadRequest, Conflict, Continue, Created, ExpectationFailed, Forbidden, Found, GatewayTimeOut, Gone, HttpVersionNotSupported, InternalServerError, LengthRequired, MethodNotAllowed, MovedPermanently, MultipleChoices, NoContent, NonAuthorativeInformation, NotAcceptable, NotFound, NotImplemented, NotModified, OK, PartialContent, PaymentRequired, PreconditionFailed, ProxyAuthenticationRequired, RequestEntityTooLarge, RequestRangeNotSatisfiable, RequestTimeOut, RequestUriTooLarge, ResetContent, SeeOther, ServiceUnavailable, SwitchingProtocols, TemporaryRedirect, Unauthorized, UnsupportedMediaType, and UseProxy.
Referenced by infra::operator<<().
     {
         switch (statusCode)
         {
         case services::HttpStatusCode::Continue: return "Continue";
         case services::HttpStatusCode::SwitchingProtocols: return "SwitchingProtocols";
         case services::HttpStatusCode::OK: return "OK";
         case services::HttpStatusCode::Created: return "Created";
         case services::HttpStatusCode::Accepted: return "Accepted";
         case services::HttpStatusCode::NonAuthorativeInformation: return "NonAuthorativeInformation";
         case services::HttpStatusCode::NoContent: return "NoContent";
         case services::HttpStatusCode::ResetContent: return "ResetContent";
         case services::HttpStatusCode::PartialContent: return "PartialContent";
         case services::HttpStatusCode::MultipleChoices: return "MultipleChoices";
         case services::HttpStatusCode::MovedPermanently: return "MovedPermanently";
         case services::HttpStatusCode::Found: return "Found";
         case services::HttpStatusCode::SeeOther: return "SeeOther";
         case services::HttpStatusCode::NotModified: return "NotModified";
         case services::HttpStatusCode::UseProxy: return "UseProxy";
         case services::HttpStatusCode::TemporaryRedirect: return "TemporaryRedirect";
         case services::HttpStatusCode::BadRequest: return "BadRequest";
         case services::HttpStatusCode::Unauthorized: return "Unauthorized";
         case services::HttpStatusCode::PaymentRequired: return "PaymentRequired";
         case services::HttpStatusCode::Forbidden: return "Forbidden";
         case services::HttpStatusCode::NotFound: return "NotFound";
         case services::HttpStatusCode::MethodNotAllowed: return "MethodNotAllowed";
         case services::HttpStatusCode::NotAcceptable: return "NotAcceptable";
         case services::HttpStatusCode::ProxyAuthenticationRequired: return "ProxyAuthenticationRequired";
         case services::HttpStatusCode::RequestTimeOut: return "RequestTimeOut";
         case services::HttpStatusCode::Conflict: return "Conflict";
         case services::HttpStatusCode::Gone: return "Gone";
         case services::HttpStatusCode::LengthRequired: return "LengthRequired";
         case services::HttpStatusCode::PreconditionFailed: return "PreconditionFailed";
         case services::HttpStatusCode::RequestEntityTooLarge: return "RequestEntityTooLarge";
         case services::HttpStatusCode::RequestUriTooLarge: return "RequestUriTooLarge";
         case services::HttpStatusCode::UnsupportedMediaType: return "UnsupportedMediaType";
         case services::HttpStatusCode::RequestRangeNotSatisfiable: return "RequestRangeNotSatisfiable";
         case services::HttpStatusCode::ExpectationFailed: return "ExpectationFailed";
         case services::HttpStatusCode::InternalServerError: return "InternalServerError";
         case services::HttpStatusCode::NotImplemented: return "NotImplemented";
         case services::HttpStatusCode::BadGateway: return "BadGateway";
         case services::HttpStatusCode::ServiceUnavailable: return "ServiceUnavailable";
         case services::HttpStatusCode::GatewayTimeOut: return "GatewayTimeOut";
         case services::HttpStatusCode::HttpVersionNotSupported: return "HttpVersionNotSupported";
         }
         std::abort();
     }
HttpVerbFromString()
infra::Optional< HttpVerb > services::HttpVerbFromString (infra::BoundedConstString verb)
Definition at line 88 of file Http.cpp.
References connect, delete_, get, head, infra::MakeOptional(), infra::none, options, patch, post, and put.
Referenced by services::HttpRequestParserImpl::FindVerb().
     {
         if (verb == "GET")
             return infra::MakeOptional(HttpVerb::get);
         else if (verb == "HEAD")
             return infra::MakeOptional(HttpVerb::head);
         else if (verb == "CONNECT")
             return infra::MakeOptional(HttpVerb::connect);
         else if (verb == "OPTIONS")
             return infra::MakeOptional(HttpVerb::options);
         else if (verb == "PATCH")
             return infra::MakeOptional(HttpVerb::patch);
         else if (verb == "PUT")
             return infra::MakeOptional(HttpVerb::put);
         else if (verb == "POST")
             return infra::MakeOptional(HttpVerb::post);
         else if (verb == "DELETE")
             return infra::MakeOptional(HttpVerb::delete_);
         return infra::none;
     }
HttpVerbToString()
infra::BoundedConstString services::HttpVerbToString (HttpVerb verb)
Definition at line 71 of file Http.cpp.
References connect, delete_, get, head, options, patch, post, and put.
Referenced by infra::operator<<(), and services::HttpRequestFormatter::Size().
     {
         switch (verb)
         {
         case HttpVerb::get: return "GET";
         case HttpVerb::head: return "HEAD";
         case HttpVerb::connect: return "CONNECT";
         case HttpVerb::options: return "OPTIONS";
         case HttpVerb::patch: return "PATCH";
         case HttpVerb::put: return "PUT";
         case HttpVerb::post: return "POST";
         case HttpVerb::delete_: return "DELETE";
         }
         std::abort();
     }
IPv4AddressLocalHost()
IPv4Address services::IPv4AddressLocalHost ()
Definition at line 30 of file Address.cpp.
     {
         return IPv4Address{ 127, 0, 0, 1 };
     }
IPv6AddressLocalHost()
IPv6Address services::IPv6AddressLocalHost ()
Definition at line 35 of file Address.cpp.
     {
         return IPv6Address{ 0, 0, 0, 0, 0, 0, 0, 1 };
     }
MakeUdpSocket()
UdpSocket services::MakeUdpSocket (IPAddress address, uint16_t port)
Definition at line 6 of file Address.cpp.
References infra::Variant< T >::Get(), and infra::Variant< T >::Is().
Referenced by services::DnsResolver::ActiveLookup::DnsUpdSocket().
     {
         if (address.Is<services::IPv4Address>())
             return Udpv4Socket{ address.Get<services::IPv4Address>(), port };
         else
             return Udpv6Socket{ address.Get<services::IPv6Address>(), port };
     }
PathFromUrl()
infra::BoundedConstString services::PathFromUrl (infra::BoundedConstString url)
Definition at line 62 of file Http.cpp.
References infra::BoundedStringBase< T >::find(), infra::BoundedStringBase< char >::npos, and infra::BoundedStringBase< T >::substr().
Referenced by services::HttpClientBasic::Path().
     {
         auto separator = url.find('/', SchemeEndPositionFromUrl(url));
         if (separator == infra::BoundedString::npos)
             return infra::BoundedConstString();
         else
             return url.substr(separator);
     }
SchemeFromUrl()
infra::BoundedConstString services::SchemeFromUrl (infra::BoundedConstString url)
Definition at line 47 of file Http.cpp.
References infra::BoundedStringBase< T >::find(), infra::BoundedStringBase< char >::npos, and infra::BoundedStringBase< T >::substr().
     {
         auto schemeEnd = url.find("://");
         if (schemeEnd == infra::BoundedString::npos)
             return infra::BoundedConstString();
         else
             return url.substr(0, schemeEnd);
     }
SetGlobalTracerInstance()
void services::SetGlobalTracerInstance (Tracer & tracer)
Definition at line 18 of file GlobalTracer.cpp.
Referenced by main().
     {
         assert(globalTracerInstance == nullptr);
         globalTracerInstance = &tracer;
     }
Variable Documentation
ethernetMtu
const uint32_t services::ethernetMtu = 1500 static
Definition at line 107 of file Connection.hpp.
maxPacketPayload
const uint32_t services::maxPacketPayload = ethernetMtu - tcpPacketOverhead static
Definition at line 109 of file Connection.hpp.
noHeaders
const HttpHeaders services::noHeaders {} static
Definition at line 84 of file Http.hpp.
Referenced by services::HttpClientBasic::Headers().
tcpPacketOverhead
const uint32_t services::tcpPacketOverhead = 54 static
Definition at line 108 of file Connection.hpp.