EMil: TestSharedOptional.cpp File Reference
TestSharedOptional.cpp File Reference
Functions
TEST (SharedOptionalTest, Emplace_returns_SharedPtr)
TEST (SharedOptionalTest, after_Emplace_SharedOptional_is_not_allocatable)
TEST (SharedOptionalTest, after_Emplace_SharedOptional_is_deferenceable)
TEST (SharedOptionalTest, after_SharedPtr_destruction_SharedOptional_is_not_dereferenceable)
TEST (SharedOptionalTest, only_after_WeakPtr_destruction_SharedOptional_is_allocatable)
TEST (SharedOptionalTest, NotifyingSharedPtr_notifies_after_becoming_allocatable)
TEST (SharedOptionalTest, change_callback_on_NotifyingSharedPtr)
Function Documentation
TEST() [1/7]
TEST (SharedOptionalTest , Emplace_returns_SharedPtr)
Definition at line 5 of file TestSharedOptional.cpp.
References infra::SharedOptional< T >::Emplace(), EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::SharedOptional<int> s;
     EXPECT_FALSE(static_cast<bool>(s));
     EXPECT_TRUE(!s);
     infra::SharedPtr<int> p = s.Emplace(5);
     EXPECT_EQ(5, *p);
     EXPECT_TRUE(static_cast<bool>(s));
     EXPECT_FALSE(!s);
 }
TEST() [2/7]
TEST (SharedOptionalTest , after_Emplace_SharedOptional_is_not_allocatable)
Definition at line 16 of file TestSharedOptional.cpp.
References infra::SharedOptional< T >::Allocatable(), infra::SharedOptional< T >::Emplace(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::SharedOptional<int> s;
     EXPECT_TRUE(s.Allocatable());
     infra::SharedPtr<int> p = s.Emplace(5);
     EXPECT_FALSE(s.Allocatable());
 }
TEST() [3/7]
TEST (SharedOptionalTest , after_Emplace_SharedOptional_is_deferenceable)
Definition at line 24 of file TestSharedOptional.cpp.
References infra::SharedOptional< T >::Emplace(), and EXPECT_EQ().
 {
     infra::SharedOptional<int> s;
     const infra::SharedOptional<int>& cs = s;
     infra::SharedPtr<int> p = s.Emplace(5);
     EXPECT_EQ(5, *s);
     EXPECT_EQ(5, *cs);
     EXPECT_EQ(5, *(s.operator->()));
     EXPECT_EQ(5, *(cs.operator->()));
 }
TEST() [4/7]
TEST (SharedOptionalTest , after_SharedPtr_destruction_SharedOptional_is_not_dereferenceable)
Definition at line 35 of file TestSharedOptional.cpp.
References infra::SharedOptional< T >::Emplace(), and EXPECT_FALSE().
 {
     infra::SharedOptional<int> s;
     infra::SharedPtr<int> p = s.Emplace(5);
     p = nullptr;
     EXPECT_FALSE(static_cast<bool>(s));
 }
TEST() [5/7]
TEST (SharedOptionalTest , only_after_WeakPtr_destruction_SharedOptional_is_allocatable)
Definition at line 43 of file TestSharedOptional.cpp.
References infra::SharedOptional< T >::Allocatable(), infra::SharedOptional< T >::Emplace(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::SharedOptional<int> s;
     infra::SharedPtr<int> p = s.Emplace(5);
     infra::WeakPtr<int> wp = p;
     p = nullptr;
     EXPECT_FALSE(s.Allocatable());
     wp = nullptr;
     EXPECT_TRUE(s.Allocatable());
 }
TEST() [6/7]
TEST (SharedOptionalTest , NotifyingSharedPtr_notifies_after_becoming_allocatable)
Definition at line 54 of file TestSharedOptional.cpp.
 {
     infra::MockCallback<void()> callback;
     infra::NotifyingSharedOptional<int> s([&callback]() { callback.callback(); });
     infra::SharedPtr<int> p = s.Emplace(5);
     infra::WeakPtr<int> wp = p;
     p = nullptr;
     EXPECT_CALL(callback, callback());
     wp = nullptr;
 }
TEST() [7/7]
TEST (SharedOptionalTest , change_callback_on_NotifyingSharedPtr)
Definition at line 67 of file TestSharedOptional.cpp.
References infra::SharedOptional< T >::Emplace(), and infra::NotifyingSharedOptional< T >::OnAllocatable().
 {
     infra::MockCallback<void()> callback;
     infra::NotifyingSharedOptional<int> s;
     s.OnAllocatable([&callback]() { callback.callback(); });
     infra::SharedPtr<int> p = s.Emplace(5);
     EXPECT_CALL(callback, callback());
     p = nullptr;
 }