EMil: TestStdStringInputStream.cpp File Reference
TestStdStringInputStream.cpp File Reference
Functions
TEST (StdStringInputStreamTest, ExtractHex)
TEST (StdStringInputStreamTest, StdStringInputStream)
TEST (StdStringInputStreamTest, ExtractHexFrowStdStringInputStreamWithOverflow)
TEST (StdStringInputStreamTest, ExtractStringLiteral)
TEST (StdStringInputStreamTest, PeekLiteral)
Function Documentation
TEST() [1/5]
TEST (StdStringInputStreamTest , ExtractHex)
Definition at line 5 of file TestStdStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     std::string string("ab");
     infra::StdStringInputStream stream(string);
     uint8_t value;
     stream >> infra::hex >> value;
     EXPECT_EQ(0xab, value);
 }
TEST() [2/5]
TEST (StdStringInputStreamTest , StdStringInputStream)
Definition at line 15 of file TestStdStringInputStream.cpp.
References EXPECT_EQ(), infra::hex, and value.
 {
     std::string string("abcd");
     infra::StdStringInputStream stream(string);
     uint8_t value;
     stream >> infra::hex >> infra::Width(1) >> value;
     EXPECT_EQ(0xa, value);
 }
TEST() [3/5]
TEST (StdStringInputStreamTest , ExtractHexFrowStdStringInputStreamWithOverflow)
Definition at line 25 of file TestStdStringInputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::hex, infra::inPlace, and infra::softFail.
 {
     infra::StdStringInputStream::WithStorage stream(infra::inPlace, "", infra::softFail);
     uint8_t v(1);
     stream >> infra::hex >> v;
     EXPECT_EQ(0, v);
     EXPECT_TRUE(stream.Failed());
 }
TEST() [4/5]
TEST (StdStringInputStreamTest , ExtractStringLiteral)
Definition at line 35 of file TestStdStringInputStream.cpp.
References EXPECT_TRUE(), and infra::inPlace.
 {
     infra::StdStringInputStream::WithStorage stream(infra::inPlace, "abcd");
     stream >> "abcd";
     EXPECT_TRUE(stream.Empty());
 }
TEST() [5/5]
TEST (StdStringInputStreamTest , PeekLiteral)
Definition at line 43 of file TestStdStringInputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::inPlace, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StdStringInputStream::WithStorage stream(infra::inPlace, "a");
     EXPECT_EQ('a', stream.PeekContiguousRange(0).front());
     EXPECT_EQ("a", stream.Storage());
     stream.Consume(1);
     EXPECT_TRUE(stream.Empty());
 }