EMil: infra::detail Namespace Reference
infra::detail Namespace Reference
Classes
struct ApplySameTypeVisitorHelper
struct ApplySameTypeVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+1==Variant::size >::type >
struct ApplySameTypeVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+2==Variant::size >::type >
struct ApplySameTypeVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+3==Variant::size >::type >
struct ApplySameTypeVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+4==Variant::size >::type >
struct ApplySameTypeVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index==Variant::size >::type >
struct ApplyVisitorHelper
struct ApplyVisitorHelper2
struct ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+1==Variant::size >::type >
struct ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+2==Variant::size >::type >
struct ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+3==Variant::size >::type >
struct ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+4==Variant::size >::type >
struct ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index==Variant::size >::type >
struct ApplyVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+1==Variant::size >::type >
struct ApplyVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+2==Variant::size >::type >
struct ApplyVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+3==Variant::size >::type >
struct ApplyVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index+4==Variant::size >::type >
struct ApplyVisitorHelper< Index, Visitor, Variant, typename std::enable_if< Index==Variant::size >::type >
class BoundedDequeIterator
class BoundedForwardListIterator
struct BoundedForwardListNode
class BoundedListIterator
struct BoundedListNode
struct ConstructAtIndexHelper
struct ConstructAtIndexHelper< ArgHead, ArgTail... >
struct ConstructAtIndexHelper<>
struct ConstructPolymorphicVisitor
struct ConstructVisitor
struct CopyPolymorphicVisitor
struct CopyVisitor
struct DestroyVisitor
struct DoublePair
struct EqualVisitor
class IntrusiveBinarySearchTreeIterator
class IntrusiveBinarySearchTreeNode
class IntrusiveForwardListIterator
class IntrusiveForwardListNode
class IntrusiveListIterator
class IntrusiveListNode
class IntrusivePriorityQueueNode
struct IntrusiveSetNode
struct InvokerFunctions
struct InvokerFunctions< Result(Args...), ExtraSize >
struct LessThanVisitor
class NullAllocator
class SharedObjectOnHeap
class SharedPtrControl
class StorageHolder
Functions
template<class Iterator >
std::reverse_iterator< Iterator > make_reverse_iterator (Iterator i)
template<class T >
T begin (const DoublePair< T > &p)
template<class T >
T end (const DoublePair< T > &p)
template<class T >
void MakeSharedFromThis (SharedPtr< T > *object, typename T::EnableSharedFromThisType *=nullptr)
void MakeSharedFromThis (void *object)
Function Documentation
begin()
template<class T > T infra::detail::begin (const DoublePair< T > & p)
Definition at line 28 of file ReverseRange.hpp.
Referenced by infra::QueueForOneReaderOneIrqWriter< uint8_t >::AddFromInterrupt(), infra::IntrusiveForwardList< infra::Timer >::assign(), infra::BoundedForwardList< T >::assign(), infra::IntrusiveForwardList< infra::Timer >::cbegin(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::cbegin(), infra::BoundedDeque< decltype(buffer)>::cbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::cbegin(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::cbegin(), infra::BoundedStringBase< char >::compare(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::ContiguousRange(), infra::BoundedStringBase< char >::copy(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::data(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::emplace(), infra::BoundedDeque< decltype(buffer)>::emplace(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::end(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::erase(), infra::BoundedDeque< decltype(buffer)>::erase(), infra::BoundedStringBase< char >::erase(), infra::erase_heap(), infra::IntrusiveForwardList< infra::Timer >::erase_slow(), infra::StringInputStreamReader::Extract(), infra::StdStringInputStreamReader::Extract(), infra::BoundedStringBase< char >::find(), infra::BoundedStringBase< char >::find_first_not_of(), infra::BoundedStringBase< char >::find_first_of(), infra::BoundedStringBase< char >::find_last_not_of(), infra::BoundedStringBase< char >::find_last_of(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Full(), infra::BoundedDeque< decltype(buffer)>::insert(), infra::BoundedStringBase< char >::insert(), infra::BoundedForwardList< T >::move_from_range(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::move_up(), infra::IntrusiveForwardList< infra::Timer >::operator<(), infra::BoundedForwardList< T >::operator<(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator<(), infra::IntrusiveBinarySearchTree< T, Compare >::operator<(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator<(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator<(), infra::BoundedDeque< decltype(buffer)>::operator<(), infra::TextOutputStream::operator<<(), infra::MemoryRange< infra::StaticStorage< infra::detail::BoundedListNode< T > > >::operator==(), infra::BoundedForwardList< T >::operator==(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator==(), infra::IntrusiveBinarySearchTree< T, Compare >::operator==(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator==(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator==(), infra::BoundedDeque< decltype(buffer)>::operator==(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::operator[](), infra::MemoryRange< infra::StaticStorage< infra::detail::BoundedListNode< T > > >::operator[](), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::range(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::rend(), infra::BoundedDeque< decltype(buffer)>::rend(), infra::IntrusiveBinarySearchTree< T, Compare >::rend(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::rend(), infra::BoundedStringBase< char >::replace(), infra::BoundedStringBase< char >::ReplaceImpl(), infra::BoundedStringBase< char >::resize(), infra::BoundedStringBase< char >::rfind(), services::ConnectionBsd::Send(), services::ConnectionWin::Send(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Size(), infra::BoundedStringBase< char >::substr(), infra::BoundedForwardList< T >::swap(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap(), and infra::Tokenizer::TokenAndRest().
         {
             return p.first;
         }
end()
template<class T > T infra::detail::end (const DoublePair< T > & p)
Definition at line 34 of file ReverseRange.hpp.
Referenced by infra::JsonInputStreamReader::Available(), infra::IntrusiveForwardList< infra::Timer >::cend(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::cend(), infra::BoundedDeque< decltype(buffer)>::cend(), infra::IntrusiveBinarySearchTree< T, Compare >::cend(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::cend(), infra::BoundedStringBase< char >::compare(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::ContiguousRange(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::erase(), infra::erase_heap(), infra::IntrusiveForwardList< infra::Timer >::erase_slow(), infra::BoundedStringBase< char >::find(), infra::BoundedStringBase< char >::find_first_not_of(), infra::BoundedStringBase< char >::find_first_of(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Full(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::insert(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::move_up(), infra::IntrusiveForwardList< infra::Timer >::operator<(), infra::BoundedForwardList< T >::operator<(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator<(), infra::IntrusiveBinarySearchTree< T, Compare >::operator<(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator<(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator<(), infra::BoundedDeque< decltype(buffer)>::operator<(), infra::TextOutputStream::operator<<(), infra::MemoryRange< infra::StaticStorage< infra::detail::BoundedListNode< T > > >::operator==(), infra::BoundedForwardList< T >::operator==(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator==(), infra::IntrusiveBinarySearchTree< T, Compare >::operator==(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::operator==(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::operator==(), infra::BoundedDeque< decltype(buffer)>::operator==(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::range(), infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::rbegin(), infra::BoundedDeque< decltype(buffer)>::rbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::rbegin(), infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::rbegin(), infra::StringOutputStreamWriter::Reserve(), infra::BoundedStringBase< char >::resize(), infra::StringOutputStreamWriter::RestoreState(), infra::BoundedStringBase< char >::rfind(), infra::StringOutputStreamWriter::SaveState(), infra::QueueForOneReaderOneIrqWriter< uint8_t >::Size(), infra::StringAsMemoryRange(), infra::BoundedForwardList< T >::swap(), infra::BoundedList< services::ConnectionFactoryWithNameResolverImpl::Action >::swap(), and infra::SwapEndian().
         {
             return p.second;
         }
make_reverse_iterator()
template<class Iterator > std::reverse_iterator<Iterator> infra::detail::make_reverse_iterator (Iterator i)
Definition at line 14 of file Endian.hpp.
Referenced by infra::SwapEndian().
         {
             return std::reverse_iterator<Iterator>(i);
         }
MakeSharedFromThis() [1/2]
template<class T > void infra::detail::MakeSharedFromThis (SharedPtr< T > * object, typename T::EnableSharedFromThisType * = nullptr)
Definition at line 536 of file SharedPtr.hpp.
References infra::EnableSharedFromThis< T >::MakeShared().
Referenced by infra::SharedPtr< services::ConnectionObserver >::SharedPtr().
         {
             static_cast<EnableSharedFromThis<typename T::EnableSharedFromThisType>&>(**object).MakeShared(*object);
         }
MakeSharedFromThis() [2/2]
void infra::detail::MakeSharedFromThis (void * object) inline
Definition at line 541 of file SharedPtr.hpp.
         {}