EMil: TestCompareMembers.cpp File Reference
TestCompareMembers.cpp File Reference
Functions
TEST (EqualsTest, TestConstructedEmpty)
TEST (EqualsTest, TestEqual1Bool)
TEST (EqualsTest, TestEqual1Bool1Int)
TEST (EqualsTest, TestNotEqual1Bool)
TEST (EqualsTest, TestNotEqual1Bool1Int)
TEST (EqualsTest, TestNotEqual1Bool1Int2)
TEST (LessThanTest, TestConstructedEmpty)
TEST (LessThanTest, TestLessThanBool)
TEST (LessThanTest, TestLessThanInt)
TEST (LessThanTest, TestEqualsIsNotLessThanBool)
TEST (LessThanTest, TestEQualsIsNotLessThanInt)
TEST (LessThanTest, TestLexicalOrder1)
TEST (LessThanTest, TestLexicalOrder2)
TEST (LessThanTest, TestLexicalOrder3)
Function Documentation
TEST() [1/14]
TEST (EqualsTest , TestConstructedEmpty)
Definition at line 4 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::Equals());
 }
TEST() [2/14]
TEST (EqualsTest , TestEqual1Bool)
Definition at line 9 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::Equals()
         (true, true));
 }
TEST() [3/14]
TEST (EqualsTest , TestEqual1Bool1Int)
Definition at line 15 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::Equals()
         (true, true)
         (5, 5));
 }
TEST() [4/14]
TEST (EqualsTest , TestNotEqual1Bool)
Definition at line 22 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::Equals()
         (true, false));
 }
TEST() [5/14]
TEST (EqualsTest , TestNotEqual1Bool1Int)
Definition at line 28 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::Equals()
         (true, true)
         (5, 4));
 }
TEST() [6/14]
TEST (EqualsTest , TestNotEqual1Bool1Int2)
Definition at line 35 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::Equals()
         (true, false)
         (5, 5));
 }
TEST() [7/14]
TEST (LessThanTest , TestConstructedEmpty)
Definition at line 42 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::LessThan());
 }
TEST() [8/14]
TEST (LessThanTest , TestLessThanBool)
Definition at line 47 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::LessThan()
         (false, true));
 }
TEST() [9/14]
TEST (LessThanTest , TestLessThanInt)
Definition at line 53 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::LessThan()
         (4, 5));
 }
TEST() [10/14]
TEST (LessThanTest , TestEqualsIsNotLessThanBool)
Definition at line 59 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::LessThan()
         (true, true));
 }
TEST() [11/14]
TEST (LessThanTest , TestEQualsIsNotLessThanInt)
Definition at line 65 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::LessThan()
         (4, 4));
 }
TEST() [12/14]
TEST (LessThanTest , TestLexicalOrder1)
Definition at line 71 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::LessThan()
         (2, 3)
         (3, 2));
 }
TEST() [13/14]
TEST (LessThanTest , TestLexicalOrder2)
Definition at line 78 of file TestCompareMembers.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(infra::LessThan()
         (2, 2)
         (2, 3));
 }
TEST() [14/14]
TEST (LessThanTest , TestLexicalOrder3)
Definition at line 85 of file TestCompareMembers.cpp.
References EXPECT_FALSE().
 {
     EXPECT_FALSE(infra::LessThan()
         (2, 2)
         (3, 2));
 }