EMil: services::NameResolverCache Class Reference
services::NameResolverCache Class Reference
#include <NameResolverCache.hpp>
Classes
class ActiveLookup
struct CacheEntry
Public Types
template<std::size_t Size>
using WithCacheSize = infra::WithStorage< NameResolverCache, infra::BoundedVector< CacheEntry >::WithMaxSize< Size > >
Public Member Functions
NameResolverCache (infra::BoundedVector< CacheEntry > &cache, NameResolver &resolver)
virtual void Lookup (NameResolverResult &result) override
virtual void CancelLookup (NameResolverResult &result) override
Protected Member Functions
virtual void RemoveOneCacheEntry (infra::BoundedVector< CacheEntry > &cache)
Protected Member Functions inherited from services::NameResolver
NameResolver ()=default
NameResolver (const NameResolver &other)=delete
NameResolver & operator= (const NameResolver &other)=delete
~NameResolver ()=default
Private Member Functions
infra::Optional< CacheEntry > SearchCache (NameResolverResult &result) const
std::array< uint8_t, 16 > Hash (infra::BoundedConstString name) const
void TryResolveNext ()
void NameLookupSuccess (NameResolverResult &result, IPAddress address, infra::TimePoint validUntil)
void NameLookupFailed (NameResolverResult &result)
void NameLookupCancelled ()
void NameLookupDone (const infra::Function< void(), 3 *sizeof(void *)> &observerCallback)
void TryAddToCache (infra::BoundedConstString name, IPAddress address, infra::TimePoint validUntil)
void AddToCache (infra::BoundedConstString name, IPAddress address, infra::TimePoint validUntil)
void Cleanup ()
Private Attributes
infra::BoundedVector< CacheEntry > & cache
NameResolver & resolver
infra::IntrusiveList< NameResolverResult > waiting
infra::Optional< ActiveLookup > activeLookup
infra::TimerSingleShot cleanupTimer
Detailed Description
Definition at line 11 of file NameResolverCache.hpp.
Member Typedef Documentation
WithCacheSize
template<std::size_t Size> using services::NameResolverCache::WithCacheSize = infra::WithStorage<NameResolverCache, infra::BoundedVector<CacheEntry>::WithMaxSize<Size> >
Definition at line 23 of file NameResolverCache.hpp.
Constructor & Destructor Documentation
NameResolverCache()
services::NameResolverCache::NameResolverCache (infra::BoundedVector< CacheEntry > & cache, NameResolver & resolver)
Definition at line 6 of file NameResolverCache.cpp.
         : cache(cache)
         , resolver(resolver)
     {}
Member Function Documentation
AddToCache()
void services::NameResolverCache::AddToCache (infra::BoundedConstString name, IPAddress address, infra::TimePoint validUntil) private
Definition at line 115 of file NameResolverCache.cpp.
References cache, Cleanup(), and Hash().
Referenced by TryAddToCache().
     {
         cache.emplace_back(CacheEntry{ address, validUntil, Hash(name) });
         Cleanup();
     }
CancelLookup()
void services::NameResolverCache::CancelLookup (NameResolverResult & result) override virtual
Implements services::NameResolver.
Definition at line 23 of file NameResolverCache.cpp.
References activeLookup, and waiting.
     {
         if (!activeLookup->IsResolving(result))
         {
             assert(waiting.has_element(result));
             waiting.erase(result);
         }
         else
             activeLookup->CancelLookup();
     }
Cleanup()
void services::NameResolverCache::Cleanup () private
Definition at line 121 of file NameResolverCache.cpp.
References cache, cleanupTimer, infra::Now(), and infra::TimerSingleShot::Start().
Referenced by AddToCache().
     {
         infra::TimePoint now = infra::Now();
         infra::TimePoint cleanupTime = infra::TimePoint::max();
         for (auto entry = cache.begin(); entry != cache.end(); )
         {
             if (entry->validUntil <= now)
                 entry = cache.erase(entry);
             else
             {
                 cleanupTime = std::min(cleanupTime, entry->validUntil);
                 ++entry;
             }
         }
         cleanupTimer.Start(cleanupTime, [this]() { Cleanup(); });
     }
Hash()
std::array< uint8_t, 16 > services::NameResolverCache::Hash (infra::BoundedConstString name) const private
Definition at line 60 of file NameResolverCache.cpp.
References infra::BoundedStringBase< T >::begin(), and infra::BoundedStringBase< T >::size().
Referenced by AddToCache(), and SearchCache().
     {
         struct
         {
             std::array<uint8_t, 16> first;
             std::array<uint8_t, 16> second;
         } result;
         auto res = mbedtls_sha256_ret(reinterpret_cast<const unsigned char*>(name.begin()), name.size(), result.first.data(), 0);
         assert(res == 0);
         return result.first;
     }
Lookup()
void services::NameResolverCache::Lookup (NameResolverResult & result) override virtual
Implements services::NameResolver.
Definition at line 11 of file NameResolverCache.cpp.
References services::NameResolverResult::NameLookupDone(), infra::none, SearchCache(), TryResolveNext(), and waiting.
     {
         auto cacheEntry = SearchCache(result);
         if (cacheEntry != infra::none)
             result.NameLookupDone(cacheEntry->address, cacheEntry->validUntil);
         else
         {
             waiting.push_back(result);
             TryResolveNext();
         }
     }
NameLookupCancelled()
void services::NameResolverCache::NameLookupCancelled () private
Definition at line 94 of file NameResolverCache.cpp.
References NameLookupDone().
     {
         NameLookupDone([]() {});
     }
NameLookupDone()
void services::NameResolverCache::NameLookupDone (const infra::Function< void(), 3 *sizeof(void *)> & observerCallback) private
Definition at line 99 of file NameResolverCache.cpp.
References activeLookup, infra::none, and TryResolveNext().
Referenced by NameLookupCancelled(), NameLookupFailed(), and NameLookupSuccess().
     {
         activeLookup = infra::none;
         observerCallback();
         TryResolveNext();
     }
NameLookupFailed()
void services::NameResolverCache::NameLookupFailed (NameResolverResult & result) private
Definition at line 89 of file NameResolverCache.cpp.
References NameLookupDone(), and services::NameResolverResult::NameLookupFailed().
     {
         NameLookupDone([&result]() { result.NameLookupFailed(); });
     }
NameLookupSuccess()
void services::NameResolverCache::NameLookupSuccess (NameResolverResult & result, IPAddress address, infra::TimePoint validUntil) private
Definition at line 83 of file NameResolverCache.cpp.
References services::NameResolverResult::Hostname(), services::NameResolverResult::NameLookupDone(), NameLookupDone(), and TryAddToCache().
     {
         TryAddToCache(result.Hostname(), address, validUntil);
         NameLookupDone([&result, &address, &validUntil]() { result.NameLookupDone(address, validUntil); });
     }
RemoveOneCacheEntry()
void services::NameResolverCache::RemoveOneCacheEntry (infra::BoundedVector< CacheEntry > & cache) protected virtual
Definition at line 34 of file NameResolverCache.cpp.
References cache.
Referenced by TryAddToCache().
     {
         infra::TimePoint firstToExpire = cache.front().validUntil;
         for (auto& entry : cache)
             firstToExpire = std::min(firstToExpire, entry.validUntil);
         for (auto& entry : cache)
             if (entry.validUntil == firstToExpire)
             {
                 cache.erase(&entry);
                 break;
             }
     }
SearchCache()
infra::Optional< NameResolverCache::CacheEntry > services::NameResolverCache::SearchCache (NameResolverResult & result) const private
Definition at line 49 of file NameResolverCache.cpp.
References cache, Hash(), services::NameResolverResult::Hostname(), infra::MakeOptional(), and infra::none.
Referenced by Lookup().
     {
         auto nameHash = Hash(result.Hostname());
         for (auto& entry : cache)
             if (entry.nameHash == nameHash)
                 return infra::MakeOptional(entry);
         return infra::none;
     }
TryAddToCache()
void services::NameResolverCache::TryAddToCache (infra::BoundedConstString name, IPAddress address, infra::TimePoint validUntil) private
Definition at line 106 of file NameResolverCache.cpp.
References AddToCache(), cache, and RemoveOneCacheEntry().
Referenced by NameLookupSuccess().
     {
         if (cache.full())
             RemoveOneCacheEntry(cache);
         if (!cache.full())
             AddToCache(name, address, validUntil);
     }
TryResolveNext()
void services::NameResolverCache::TryResolveNext () private
Definition at line 74 of file NameResolverCache.cpp.
References activeLookup, infra::none, and waiting.
Referenced by Lookup(), and NameLookupDone().
     {
         if (activeLookup == infra::none && !waiting.empty())
         {
             activeLookup.Emplace(*this, waiting.front());
             waiting.pop_front();
         }
     }
Member Data Documentation
activeLookup
infra::Optional<ActiveLookup> services::NameResolverCache::activeLookup private
Definition at line 72 of file NameResolverCache.hpp.
Referenced by CancelLookup(), NameLookupDone(), and TryResolveNext().
cache
infra::BoundedVector<CacheEntry>& services::NameResolverCache::cache private
Definition at line 68 of file NameResolverCache.hpp.
Referenced by AddToCache(), Cleanup(), RemoveOneCacheEntry(), SearchCache(), and TryAddToCache().
cleanupTimer
infra::TimerSingleShot services::NameResolverCache::cleanupTimer private
Definition at line 74 of file NameResolverCache.hpp.
Referenced by Cleanup().
resolver
NameResolver& services::NameResolverCache::resolver private
Definition at line 69 of file NameResolverCache.hpp.
Referenced by services::NameResolverCache::ActiveLookup::ActiveLookup().
waiting
infra::IntrusiveList<NameResolverResult> services::NameResolverCache::waiting private
Definition at line 71 of file NameResolverCache.hpp.
Referenced by CancelLookup(), Lookup(), and TryResolveNext().
The documentation for this class was generated from the following files:
NameResolverCache.hpp
NameResolverCache.cpp