EMil: application::DeployPackToExternal Class Reference
application::DeployPackToExternal Class Reference
#include <DeployPackToExternal.hpp>
Public Member Functions
DeployPackToExternal (hal::Flash &from, hal::Flash &to)
Public Member Functions inherited from infra::Subject< DeployPackToExternalObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Private Attributes
hal::Flash & from
hal::Flash & to
infra::Sequencer sequencer
UpgradePackHeaderPrologue header
std::array< uint8_t, 256 > buffer
std::size_t sizeToDo = 0
std::size_t currentSize = 0
uint32_t currentReadAddress = 0
uint32_t currentWriteAddress = 0
Additional Inherited Members
Protected Member Functions inherited from infra::Subject< DeployPackToExternalObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< DeployPackToExternalObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< DeployPackToExternalObserver, ObserverSubjectType > *observer)
Detailed Description
Definition at line 26 of file DeployPackToExternal.hpp.
Constructor & Destructor Documentation
DeployPackToExternal()
application::DeployPackToExternal::DeployPackToExternal (hal::Flash & from, hal::Flash & to)
Definition at line 5 of file DeployPackToExternal.cpp.
References buffer, infra::Sequencer::Continue(), currentReadAddress, currentSize, currentWriteAddress, application::deployed, infra::Sequencer::Else(), infra::Sequencer::ElseIf(), infra::Sequencer::EndIf(), infra::Sequencer::EndWhile(), hal::Flash::EraseAll(), infra::Sequencer::Execute(), from, infra::Subject< DeployPackToExternalObserver >::GetObserver(), header, infra::Sequencer::If(), infra::Sequencer::Load(), infra::MakeByteRange(), hal::Flash::ReadBuffer(), application::readyToDeploy, sequencer, application::UpgradePackHeaderPrologue::signatureLength, application::UpgradePackHeaderPrologue::signedContentsLength, sizeToDo, application::UpgradePackHeaderPrologue::status, infra::Sequencer::Step(), to, hal::Flash::TotalSize(), infra::Sequencer::While(), and hal::Flash::WriteBuffer().
         : from(from_)
         , to(to_)
         , header()
     {
         sequencer.Load([this]() {
             sequencer.Step([this]() { from.ReadBuffer(infra::MakeByteRange(header), 0, [this]() { sequencer.Continue(); }); });
             sequencer.Execute([this]() { sizeToDo = header.signedContentsLength + sizeof(UpgradePackHeaderPrologue) + header.signatureLength; });
             sequencer.If([this]() { return header.status != UpgradePackStatus::readyToDeploy; });
                 sequencer.Execute([this]() { GetObserver().NotDeployable(); });
             sequencer.ElseIf([this]() { return sizeToDo <= from.TotalSize(); });
                 sequencer.Step([this]() { to.EraseAll([this]() { sequencer.Continue(); }); });
                 sequencer.While([this]() { return sizeToDo != 0; });
                     sequencer.Step([this]()
                     {
                         currentSize = std::min(buffer.size(), sizeToDo);
                         from.ReadBuffer(buffer, currentReadAddress, [this]() { sequencer.Continue(); });
                     });
                     sequencer.Step([this]()
                     {
                         to.WriteBuffer(buffer, currentWriteAddress, [this]() { sequencer.Continue(); });
                     });
                     sequencer.Execute([this]()
                     {
                         currentReadAddress += currentSize;
                         currentWriteAddress += currentSize;
                         sizeToDo -= currentSize;
                     });
                 sequencer.EndWhile();
                 sequencer.Step([this]()
                 {
                     static const UpgradePackStatus statusDeployed = UpgradePackStatus::deployed;
                     from.WriteBuffer(infra::MakeByteRange(statusDeployed), 0, [this]() { sequencer.Continue(); });
                 });
                 sequencer.Execute([this]() { GetObserver().Done(); });
             sequencer.Else();
                 sequencer.Execute([this]() { GetObserver().DoesntFit(); });
             sequencer.EndIf();
         });
     }
Member Data Documentation
buffer
std::array<uint8_t, 256> application::DeployPackToExternal::buffer private
Definition at line 39 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
currentReadAddress
uint32_t application::DeployPackToExternal::currentReadAddress = 0 private
Definition at line 42 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
currentSize
std::size_t application::DeployPackToExternal::currentSize = 0 private
Definition at line 41 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
currentWriteAddress
uint32_t application::DeployPackToExternal::currentWriteAddress = 0 private
Definition at line 43 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
from
hal::Flash& application::DeployPackToExternal::from private
Definition at line 33 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
header
UpgradePackHeaderPrologue application::DeployPackToExternal::header private
Definition at line 38 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
sequencer
infra::Sequencer application::DeployPackToExternal::sequencer private
Definition at line 36 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
sizeToDo
std::size_t application::DeployPackToExternal::sizeToDo = 0 private
Definition at line 40 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
to
hal::Flash& application::DeployPackToExternal::to private
Definition at line 34 of file DeployPackToExternal.hpp.
Referenced by DeployPackToExternal().
The documentation for this class was generated from the following files:
DeployPackToExternal.hpp
DeployPackToExternal.cpp