EMil: TestFunction.cpp File Reference
TestFunction.cpp File Reference
Functions
TEST (FunctionTest, TestConstructedEmpty)
TEST (FunctionTest, TestConstructedEmptyByNullptr)
TEST (FunctionTest, TestConstructedNotEmpty)
void function ()
TEST (FunctionTest, TestConstructedWithFunctionPointer)
TEST (FunctionTest, TestConstructedWithTheEmptyFunction)
TEST (FunctionTest, TestCall)
TEST (FunctionTest, TestInvoke0)
TEST (FunctionTest, TestInvoke1)
TEST (FunctionTest, TestInvoke2)
TEST (FunctionTest, TestInvoke3)
TEST (FunctionTest, TestCopyConstructedFromEmptyFunction)
TEST (FunctionTest, TestCopyConstruct)
TEST (FunctionTest, TestCopyConstructTwice)
TEST (FunctionTest, TestCopyAssignFromEmptyFunction)
TEST (FunctionTest, TestCopyAssign)
TEST (FunctionTest, TestAssignNullptr)
TEST (FunctionTest, TestAssign)
TEST (FunctionTest, TestSwapFilledEmpty)
TEST (FunctionTest, TestSwapFilledFilled)
TEST (FunctionTest, TestSwapEmptyFilled)
TEST (FunctionTest, TestSwapEmptyEmpty)
TEST (FunctionTest, TestReturnValue)
TEST (FunctionTest, TestParameter)
TEST (FunctionProxyTest, TestProxy)
TEST (FunctionTest, TestCompareToNullptr)
TEST (FunctionTest, Execute)
TEST (FunctionTest, ExecuteWithSize)
TEST (FunctionTest, ExecuteOnDestruction)
TEST (FunctionTest, ExecuteOnDestructionWithSize)
Function Documentation
function()
void function ()
Definition at line 24 of file TestFunction.cpp.
 {}
TEST() [1/29]
TEST (FunctionTest , TestConstructedEmpty)
Definition at line 6 of file TestFunction.cpp.
References EXPECT_FALSE().
 {
     infra::Function<void()> f;
     EXPECT_FALSE(f);
 }
TEST() [2/29]
TEST (FunctionTest , TestConstructedEmptyByNullptr)
Definition at line 12 of file TestFunction.cpp.
References EXPECT_FALSE().
 {
     infra::Function<void()> f(nullptr);
     EXPECT_FALSE(f);
 }
TEST() [3/29]
TEST (FunctionTest , TestConstructedNotEmpty)
Definition at line 18 of file TestFunction.cpp.
References EXPECT_TRUE().
 {
     infra::Function<void()> f([]() {} );
     EXPECT_TRUE(static_cast<bool>(f));
 }
TEST() [4/29]
TEST (FunctionTest , TestConstructedWithFunctionPointer)
Definition at line 27 of file TestFunction.cpp.
References EXPECT_TRUE().
 {
     infra::Function<void()> f(function);
     EXPECT_TRUE(static_cast<bool>(f));
     infra::Function<void()> g(f);
 }
TEST() [5/29]
TEST (FunctionTest , TestConstructedWithTheEmptyFunction)
Definition at line 34 of file TestFunction.cpp.
References infra::emptyFunction, and EXPECT_TRUE().
 {
     infra::Function<void()> f(infra::emptyFunction);
     EXPECT_TRUE(static_cast<bool>(f));
     f();
 }
TEST() [6/29]
TEST (FunctionTest , TestCall)
Definition at line 41 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); } );
     EXPECT_CALL(m, callback());
     f();
 }
TEST() [7/29]
TEST (FunctionTest , TestInvoke0)
Definition at line 49 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); });
     EXPECT_CALL(m, callback());
     f.Invoke(std::make_tuple());
 }
TEST() [8/29]
TEST (FunctionTest , TestInvoke1)
Definition at line 57 of file TestFunction.cpp.
 {
     infra::MockCallback<void(int)> m;
     infra::Function<void(int)> f([&m](int x) { m.callback(x); });
     EXPECT_CALL(m, callback(1));
     f.Invoke(std::make_tuple(1));
 }
TEST() [9/29]
TEST (FunctionTest , TestInvoke2)
Definition at line 65 of file TestFunction.cpp.
 {
     infra::MockCallback<void(int, int)> m;
     infra::Function<void(int, int)> f([&m](int x, int y) { m.callback(x, y); });
     EXPECT_CALL(m, callback(1, 2));
     f.Invoke(std::make_tuple(1, 2));
 }
TEST() [10/29]
TEST (FunctionTest , TestInvoke3)
Definition at line 73 of file TestFunction.cpp.
 {
     infra::MockCallback<void(int, int, int)> m;
     infra::Function<void(int, int, int)> f([&m](int x, int y, int z) { m.callback(x, y, z); });
     EXPECT_CALL(m, callback(1, 2, 3));
     f.Invoke(std::make_tuple(1, 2, 3));
 }
TEST() [11/29]
TEST (FunctionTest , TestCopyConstructedFromEmptyFunction)
Definition at line 81 of file TestFunction.cpp.
References EXPECT_FALSE().
 {
     infra::Function<void()> f;
     infra::Function<void()> copy(f);
     EXPECT_FALSE(static_cast<bool>(copy));
 }
TEST() [12/29]
TEST (FunctionTest , TestCopyConstruct)
Definition at line 88 of file TestFunction.cpp.
References EXPECT_TRUE().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); } );
     infra::Function<void()> f2(f);
     EXPECT_TRUE(static_cast<bool>(f));
     EXPECT_CALL(m, callback());
     f2();
 }
TEST() [13/29]
TEST (FunctionTest , TestCopyConstructTwice)
Definition at line 98 of file TestFunction.cpp.
References EXPECT_TRUE().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); });
     infra::Function<void()> f2(f);
     infra::Function<void()> f3(f2);
     EXPECT_TRUE(static_cast<bool>(f));
     EXPECT_CALL(m, callback());
     f3();
 }
TEST() [14/29]
TEST (FunctionTest , TestCopyAssignFromEmptyFunction)
Definition at line 109 of file TestFunction.cpp.
References EXPECT_FALSE().
 {
     infra::Function<void()> f;
     infra::Function<void()> copy;
     copy = f;
     EXPECT_FALSE(static_cast<bool>(copy));
 }
TEST() [15/29]
TEST (FunctionTest , TestCopyAssign)
Definition at line 117 of file TestFunction.cpp.
References EXPECT_TRUE().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); } );
     infra::Function<void()> f2;
     f2 = f;
     EXPECT_TRUE(static_cast<bool>(f));
     EXPECT_CALL(m, callback());
     f2();
 }
TEST() [16/29]
TEST (FunctionTest , TestAssignNullptr)
Definition at line 128 of file TestFunction.cpp.
References EXPECT_FALSE().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); } );
     f = nullptr;
     EXPECT_FALSE(static_cast<bool>(f));
 }
TEST() [17/29]
TEST (FunctionTest , TestAssign)
Definition at line 136 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f;
     f = [&m]() { m.callback(); };
     EXPECT_CALL(m, callback());
     f();
 }
TEST() [18/29]
TEST (FunctionTest , TestSwapFilledEmpty)
Definition at line 145 of file TestFunction.cpp.
References EXPECT_FALSE(), and infra::swap().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); } );
     infra::Function<void()> f2;
     swap(f, f2);
     EXPECT_FALSE(static_cast<bool>(f));
     EXPECT_CALL(m, callback());
     f2();
 }
TEST() [19/29]
TEST (FunctionTest , TestSwapFilledFilled)
Definition at line 156 of file TestFunction.cpp.
References infra::emptyFunction, EXPECT_TRUE(), and infra::swap().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f([&m]() { m.callback(); });
     infra::Function<void()> f2(infra::emptyFunction);
     swap(f, f2);
     EXPECT_TRUE(static_cast<bool>(f));
     EXPECT_CALL(m, callback());
     f2();
 }
TEST() [20/29]
TEST (FunctionTest , TestSwapEmptyFilled)
Definition at line 167 of file TestFunction.cpp.
References EXPECT_FALSE(), and infra::swap().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f;
     infra::Function<void()> f2([&m]() { m.callback(); });
     swap(f, f2);
     EXPECT_FALSE(static_cast<bool>(f2));
     EXPECT_CALL(m, callback());
     f();
 }
TEST() [21/29]
TEST (FunctionTest , TestSwapEmptyEmpty)
Definition at line 178 of file TestFunction.cpp.
References EXPECT_FALSE(), and infra::swap().
 {
     infra::MockCallback<void()> m;
     infra::Function<void()> f;
     infra::Function<void()> f2;
     swap(f, f2);
     EXPECT_FALSE(static_cast<bool>(f));
     EXPECT_FALSE(static_cast<bool>(f2));
 }
TEST() [22/29]
TEST (FunctionTest , TestReturnValue)
Definition at line 188 of file TestFunction.cpp.
References EXPECT_EQ().
 {
     infra::Function<int()> f([]() { return 1; } );
     EXPECT_EQ(1, f());
 }
TEST() [23/29]
TEST (FunctionTest , TestParameter)
Definition at line 194 of file TestFunction.cpp.
 {
     infra::MockCallback<void(int)> m;
     infra::Function<void(int)> f([&m](int x) { m.callback(x); } );
     EXPECT_CALL(m, callback(1));
     f(1);
 }
TEST() [24/29]
TEST (FunctionProxyTest , TestProxy)
Definition at line 202 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     infra::Function<void(), 40> p([&m]() { m.callback(); } );
     EXPECT_CALL(m, callback());
     infra::Function<void(), sizeof(void*)> f([&p]() { p(); });
     f();
 }
TEST() [25/29]
TEST (FunctionTest , TestCompareToNullptr)
Definition at line 212 of file TestFunction.cpp.
References EXPECT_EQ().
 {
     infra::Function<void()> f;
     EXPECT_EQ(f, nullptr);
     EXPECT_EQ(nullptr, f);
     infra::Function<void()> g([]() {});
     EXPECT_NE(g, nullptr);
     EXPECT_NE(nullptr, g);
 }
TEST() [26/29]
TEST (FunctionTest , Execute)
Definition at line 225 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     EXPECT_CALL(m, callback());
     infra::Execute execute([&m]() { m.callback(); });
 }
TEST() [27/29]
TEST (FunctionTest , ExecuteWithSize)
Definition at line 232 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     EXPECT_CALL(m, callback());
     int a, b, c;
     infra::Execute::WithExtraSize<4 * sizeof(void*)> execute([&m, a, b, c]() { m.callback(); });
 }
TEST() [28/29]
TEST (FunctionTest , ExecuteOnDestruction)
Definition at line 240 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     {
         infra::ExecuteOnDestruction execute([&m]() { m.callback(); });
         EXPECT_CALL(m, callback());
     }
 }
TEST() [29/29]
TEST (FunctionTest , ExecuteOnDestructionWithSize)
Definition at line 251 of file TestFunction.cpp.
 {
     infra::MockCallback<void()> m;
     int a, b, c;
     {
         infra::ExecuteOnDestruction::WithExtraSize<4 * sizeof(void*)> execute([&m, a, b, c]() { m.callback(); });
         EXPECT_CALL(m, callback());
     }
 }