EMil: TestStringOutputStream.cpp File Reference
TestStringOutputStream.cpp File Reference
Functions
TEST (StringOutputStreamTest, stream_byte)
TEST (StringOutputStreamTest, stream_from_bounded_string)
TEST (StringOutputStreamTest, stream_literal)
TEST (StringOutputStreamTest, stream_literal_in_hex_stream)
TEST (StringOutputStreamTest, stream_literal_in_bin_stream)
TEST (StringOutputStreamTest, stream_character)
TEST (StringOutputStreamTest, stream_uint8)
TEST (StringOutputStreamTest, stream_int8)
TEST (StringOutputStreamTest, stream_negative_int8)
TEST (StringOutputStreamTest, stream_int8_with_leading_zeroes)
TEST (StringOutputStreamTest, stream_int8_with_smaller_width)
TEST (StringOutputStreamTest, stream_negative_int8_with_width)
TEST (StringOutputStreamTest, stream_uint64_max)
TEST (StringOutputStreamTest, stream_int64_max)
TEST (StringOutputStreamTest, stream_int64_min)
TEST (StringOutputStreamTest, stream_float)
TEST (StringOutputStreamTest, stream_negative_float)
TEST (StringOutputStreamTest, stream_short_hex)
TEST (StringOutputStreamTest, stream_longer_hex)
TEST (StringOutputStreamTest, stream_negative_hex)
TEST (StringOutputStreamTest, stream_hex_with_leading_zeroes)
TEST (StringOutputStreamTest, stream_short_bin)
TEST (StringOutputStreamTest, stream_longer_bin)
TEST (StringOutputStreamTest, stream_negative_bin)
TEST (StringOutputStreamTest, stream_bin_with_leading_zeroes)
TEST (StringOutputStreamTest, overflow)
TEST (StringOutputStreamTest, overflow_with_noFail)
TEST (StringOutputStreamTest, overflow_twice)
TEST (StringOutputStreamTest, format_simple_string)
TEST (StringOutputStreamTest, format_simple_string_width)
TEST (StringOutputStreamTest, format_string_with_one_parameter)
TEST (StringOutputStreamTest, format_string_with_two_parameters)
TEST (StringOutputStreamTest, format_string_with_string)
TEST (StringOutputStreamTest, format_string_with_invalid_param_specifier)
TEST (StringOutputStreamTest, format_string_with_incomplete_param_specifier)
TEST (StringOutputStreamTest, format_string_with_out_of_range_index)
TEST (StringOutputStreamTest, format_custom_parameter)
TEST (StringOutputStreamTest, stream_byte_range_as_ascii)
TEST (StringOutputStreamTest, stream_byte_range_as_hex)
TEST (StringOutputStreamTest, stream_byte_range_as_base64)
TEST (StringOutputStreamTest, reserve_type)
TEST (StringOutputStreamTest, reserve_type_without_space)
TEST (StringOutputStreamTest, stream_to_saved_point)
TEST (StringOutputStreamTest, stream_to_nested_saved_point)
TEST (StringOutputStreamTest, overwrite_on_saved_point)
TEST (StringOutputStreamTest, available_retuns_remaining_space)
Function Documentation
TEST() [1/46]
TEST (StringOutputStreamTest , stream_byte)
Definition at line 25 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<2> stream;
     stream << uint8_t(12);
     EXPECT_EQ("12", stream.Storage());
 }
TEST() [2/46]
TEST (StringOutputStreamTest , stream_from_bounded_string)
Definition at line 33 of file TestStringOutputStream.cpp.
References infra::data, and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> s = "abcd";
     infra::StringOutputStream stream(s);
     stream << uint8_t(12) << infra::data << uint8_t('a');
     EXPECT_EQ("abcd12a", s);
 }
TEST() [3/46]
TEST (StringOutputStreamTest , stream_literal)
Definition at line 43 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << "abcd";
     EXPECT_EQ("abcd", stream.Storage());
 }
TEST() [4/46]
TEST (StringOutputStreamTest , stream_literal_in_hex_stream)
Definition at line 52 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::hex, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::hex << "abcd";
     EXPECT_EQ("abcd", stream.Storage());
 }
TEST() [5/46]
TEST (StringOutputStreamTest , stream_literal_in_bin_stream)
Definition at line 61 of file TestStringOutputStream.cpp.
References infra::bin, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::bin << "abcd";
     EXPECT_EQ("abcd", stream.Storage());
 }
TEST() [6/46]
TEST (StringOutputStreamTest , stream_character)
Definition at line 70 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << 'a';
     EXPECT_EQ("a", stream.Storage());
 }
TEST() [7/46]
TEST (StringOutputStreamTest , stream_uint8)
Definition at line 79 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << uint8_t(255);
     EXPECT_EQ("255", stream.Storage());
 }
TEST() [8/46]
TEST (StringOutputStreamTest , stream_int8)
Definition at line 88 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << int8_t(127);
     EXPECT_EQ("127", stream.Storage());
 }
TEST() [9/46]
TEST (StringOutputStreamTest , stream_negative_int8)
Definition at line 97 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << int8_t(-128);
     EXPECT_EQ("-128", stream.Storage());
 }
TEST() [10/46]
TEST (StringOutputStreamTest , stream_int8_with_leading_zeroes)
Definition at line 106 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::Width(5,'0') << int8_t(127);
     EXPECT_EQ("00127", stream.Storage());
 }
TEST() [11/46]
TEST (StringOutputStreamTest , stream_int8_with_smaller_width)
Definition at line 115 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::Width(2) << int8_t(127);
     EXPECT_EQ("127", stream.Storage());
 }
TEST() [12/46]
TEST (StringOutputStreamTest , stream_negative_int8_with_width)
Definition at line 124 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::Width(7) << int8_t(-127);
     EXPECT_EQ("   -127", stream.Storage());
 }
TEST() [13/46]
TEST (StringOutputStreamTest , stream_uint64_max)
Definition at line 133 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<20> stream;
     stream << std::numeric_limits<uint64_t>::max();
     EXPECT_EQ("18446744073709551615", stream.Storage());
 }
TEST() [14/46]
TEST (StringOutputStreamTest , stream_int64_max)
Definition at line 142 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<20> stream;
     stream << std::numeric_limits<int64_t>::max();
     EXPECT_EQ("9223372036854775807", stream.Storage());
 }
TEST() [15/46]
TEST (StringOutputStreamTest , stream_int64_min)
Definition at line 151 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<20> stream;
     stream << std::numeric_limits<int64_t>::min();
     EXPECT_EQ("-9223372036854775808", stream.Storage());
 }
TEST() [16/46]
TEST (StringOutputStreamTest , stream_float)
Definition at line 160 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<20> stream;
     stream << float(42.123);
     EXPECT_EQ("42.123", stream.Storage());
 }
TEST() [17/46]
TEST (StringOutputStreamTest , stream_negative_float)
Definition at line 169 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<20> stream;
     stream << float(-42.123);
     EXPECT_EQ("-42.123", stream.Storage());
 }
TEST() [18/46]
TEST (StringOutputStreamTest , stream_short_hex)
Definition at line 178 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::hex, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::hex << uint8_t(10);
     EXPECT_EQ("a", stream.Storage());
 }
TEST() [19/46]
TEST (StringOutputStreamTest , stream_longer_hex)
Definition at line 187 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::hex, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::hex << uint8_t(0x1A);
     EXPECT_EQ("1a", stream.Storage());
 }
TEST() [20/46]
TEST (StringOutputStreamTest , stream_negative_hex)
Definition at line 195 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::hex, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::hex << int8_t(-0x1A);
     EXPECT_EQ("-1a", stream.Storage());
 }
TEST() [21/46]
TEST (StringOutputStreamTest , stream_hex_with_leading_zeroes)
Definition at line 203 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::hex, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::hex << infra::Width(4,'0') << uint8_t(0x1A);
     EXPECT_EQ("001a", stream.Storage());
 }
TEST() [22/46]
TEST (StringOutputStreamTest , stream_short_bin)
Definition at line 211 of file TestStringOutputStream.cpp.
References infra::bin, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::bin << uint8_t(1);
     EXPECT_EQ("1", stream.Storage());
 }
TEST() [23/46]
TEST (StringOutputStreamTest , stream_longer_bin)
Definition at line 220 of file TestStringOutputStream.cpp.
References infra::bin, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::bin << uint8_t(0x1A);
     EXPECT_EQ("11010", stream.Storage());
 }
TEST() [24/46]
TEST (StringOutputStreamTest , stream_negative_bin)
Definition at line 228 of file TestStringOutputStream.cpp.
References infra::bin, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::bin << int8_t(-0x1A);
     EXPECT_EQ("-11010", stream.Storage());
 }
TEST() [25/46]
TEST (StringOutputStreamTest , stream_bin_with_leading_zeroes)
Definition at line 236 of file TestStringOutputStream.cpp.
References infra::bin, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<10> stream;
     stream << infra::bin << infra::Width(8, '0') << uint8_t(0x1A);
     EXPECT_EQ("00011010", stream.Storage());
 }
TEST() [26/46]
TEST (StringOutputStreamTest , overflow)
Definition at line 244 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::softFail, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<2> stream(infra::softFail);
     stream << "abc";
     EXPECT_EQ("ab", stream.Storage());
     EXPECT_TRUE(stream.Failed());
 }
TEST() [27/46]
TEST (StringOutputStreamTest , overflow_with_noFail)
Definition at line 253 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::noFail, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<2> stream(infra::noFail);
     stream << "abc";
     EXPECT_EQ("ab", stream.Storage());
 }
TEST() [28/46]
TEST (StringOutputStreamTest , overflow_twice)
Definition at line 261 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::softFail, and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<2> stream(infra::softFail);
     stream << "abc" << "def";
     EXPECT_EQ("ab", stream.Storage());
     EXPECT_TRUE(stream.Failed());
 }
TEST() [29/46]
TEST (StringOutputStreamTest , format_simple_string)
Definition at line 270 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("simple");
     EXPECT_EQ("simple", stream.Storage());
 }
TEST() [30/46]
TEST (StringOutputStreamTest , format_simple_string_width)
Definition at line 278 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream << infra::Width(10) << "simple";
     EXPECT_EQ("    simple", stream.Storage());
 }
TEST() [31/46]
TEST (StringOutputStreamTest , format_string_with_one_parameter)
Definition at line 286 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("%1%", 1);
     EXPECT_EQ("1", stream.Storage());
 }
TEST() [32/46]
TEST (StringOutputStreamTest , format_string_with_two_parameters)
Definition at line 294 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("%1% %2%", 5, 'a');
     EXPECT_EQ("5 a", stream.Storage());
 }
TEST() [33/46]
TEST (StringOutputStreamTest , format_string_with_string)
Definition at line 302 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("%1%", "bla");
     EXPECT_EQ("bla", stream.Storage());
 }
TEST() [34/46]
TEST (StringOutputStreamTest , format_string_with_invalid_param_specifier)
Definition at line 310 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("%bla");
     EXPECT_EQ("bla", stream.Storage());
 }
TEST() [35/46]
TEST (StringOutputStreamTest , format_string_with_incomplete_param_specifier)
Definition at line 318 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("%1", "bla");
     EXPECT_EQ("", stream.Storage());
 }
TEST() [36/46]
TEST (StringOutputStreamTest , format_string_with_out_of_range_index)
Definition at line 326 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream.Format("%3%", 1, 2);
     EXPECT_EQ("", stream.Storage());
 }
TEST() [37/46]
TEST (StringOutputStreamTest , format_custom_parameter)
Definition at line 334 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     MyObject myObject(5);
     stream.Format("%1%", myObject);
     EXPECT_EQ("MyObject!", stream.Storage());
 }
TEST() [38/46]
TEST (StringOutputStreamTest , stream_byte_range_as_ascii)
Definition at line 343 of file TestStringOutputStream.cpp.
References infra::AsAscii(), data, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     std::array<uint8_t, 4> data = { 1, 2, 'a', 'b' };
     stream << infra::AsAscii(infra::ByteRange(data));
     EXPECT_EQ("..ab", stream.Storage());
 }
TEST() [39/46]
TEST (StringOutputStreamTest , stream_byte_range_as_hex)
Definition at line 352 of file TestStringOutputStream.cpp.
References infra::AsHex(), data, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     std::array<uint8_t, 4> data = { 1, 2, 0x30, 0x40 };
     stream << infra::AsHex(infra::ByteRange(data));
     EXPECT_EQ("01023040", stream.Storage());
 }
TEST() [40/46]
TEST (StringOutputStreamTest , stream_byte_range_as_base64)
Definition at line 361 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream1;
     stream1 << infra::AsBase64(std::array<uint8_t, 1>{ 'a' });
     EXPECT_EQ("YQ==", stream1.Storage());
     infra::StringOutputStream::WithStorage<64> stream2;
     stream2 << infra::AsBase64(std::array<uint8_t, 2>{ 'a', 'b' });
     EXPECT_EQ("YWI=", stream2.Storage());
     infra::StringOutputStream::WithStorage<64> stream3;
     stream3 << infra::AsBase64(std::array<uint8_t, 3>{ 'a', 'b', 'c' });
     EXPECT_EQ("YWJj", stream3.Storage());
     infra::StringOutputStream::WithStorage<64> stream4;
     stream4 << infra::AsBase64(std::array<uint8_t, 4>{ 'a', 'b', 'c', 'd' });
     EXPECT_EQ("YWJjZA==", stream4.Storage());
     infra::StringOutputStream::WithStorage<64> stream5;
     stream5 << infra::data << infra::text << infra::AsBase64(std::array<uint8_t, 1>{ 'a' });
     EXPECT_EQ("YQ==", stream5.Storage());
 }
TEST() [41/46]
TEST (StringOutputStreamTest , reserve_type)
Definition at line 384 of file TestStringOutputStream.cpp.
References EXPECT_EQ().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream << "a";
     auto reservedSpace = stream.Writer().Reserve<uint8_t>(stream.ErrorPolicy());
     stream << "c";
     reservedSpace = 'b';
     EXPECT_EQ("abc", stream.Storage());
 }
TEST() [42/46]
TEST (StringOutputStreamTest , reserve_type_without_space)
Definition at line 395 of file TestStringOutputStream.cpp.
References EXPECT_TRUE(), and infra::softFail.
 {
     infra::StringOutputStream::WithStorage<2> stream(infra::softFail);
     stream << "a";
     auto reservedSpace = stream.Writer().Reserve<uint32_t>(stream.ErrorPolicy());
     reservedSpace = uint32_t(32);
     EXPECT_TRUE(stream.Failed());
 }
TEST() [43/46]
TEST (StringOutputStreamTest , stream_to_saved_point)
Definition at line 405 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream << "a";
     auto marker = stream.SaveMarker();
     stream << "c";
     {
         EXPECT_EQ(1, stream.ProcessedBytesSince(marker));
         infra::SavedMarkerTextStream savedStream(stream, marker);
         savedStream << 12345;
     }
     EXPECT_EQ("a12345c", stream.Storage());
 }
TEST() [44/46]
TEST (StringOutputStreamTest , stream_to_nested_saved_point)
Definition at line 421 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), infra::OutputStream::ProcessedBytesSince(), infra::OutputStream::SaveMarker(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream << "a";
     auto marker = stream.SaveMarker();
     stream << "c";
     {
         infra::SavedMarkerTextStream savedStream(stream, marker);
         savedStream << 1;
         auto nestedMarker = savedStream.SaveMarker();
         savedStream << 56;
         {
             EXPECT_EQ(2, savedStream.ProcessedBytesSince(nestedMarker));
             infra::SavedMarkerTextStream nestedSavedStream(savedStream, nestedMarker);
             nestedSavedStream << 234;
         }
     }
     EXPECT_EQ("a123456c", stream.Storage());
 }
TEST() [45/46]
TEST (StringOutputStreamTest , overwrite_on_saved_point)
Definition at line 444 of file TestStringOutputStream.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<64> stream;
     stream << "a";
     auto marker = stream.SaveMarker();
     stream << "b";
     stream << "c";
     {
         EXPECT_EQ(2, stream.ProcessedBytesSince(marker));
         infra::OverwriteTextStream overwriteStream(stream, marker);
         overwriteStream << "d";
     }
     EXPECT_EQ("adc", stream.Storage());
 }
TEST() [46/46]
TEST (StringOutputStreamTest , available_retuns_remaining_space)
Definition at line 461 of file TestStringOutputStream.cpp.
References EXPECT_EQ().
 {
     infra::StringOutputStream::WithStorage<4> sos;
     EXPECT_EQ(4, sos.Available());
     sos << 1234;
     EXPECT_EQ(0, sos.Available());
 }