EMil: TestMqttClient.cpp File Reference
TestMqttClient.cpp File Reference
Classes
class MqttClientTest
Functions
TEST_F (MqttClientTest, refused_connection_propagates_to_MqttClientFactory)
TEST_F (MqttClientTest, connection_failed_propagates_to_MqttClientFactory)
TEST_F (MqttClientTest, after_connected_connect_message_is_sent)
TEST_F (MqttClientTest, after_conack_MqttClient_is_connected)
TEST_F (MqttClientTest, partial_conack_is_ignored)
TEST_F (MqttClientTest, invalid_response_results_in_ConnectionFailed)
TEST_F (MqttClientTest, timeout_results_in_ConnectionFailed)
TEST_F (MqttClientTest, client_observer_allocation_failure_results_in_connection_aborted)
TEST_F (MqttClientTest, Publish_some_data)
TEST_F (MqttClientTest, partial_puback_is_ignored)
TEST_F (MqttClientTest, closed_connection_results_in_ClosingConnection)
Function Documentation
TEST_F() [1/11]
TEST_F (MqttClientTest , refused_connection_propagates_to_MqttClientFactory)
Definition at line 54 of file TestMqttClient.cpp.
 {
     EXPECT_CALL(factory, ConnectionFailed(services::MqttClientObserverFactory::ConnectFailReason::refused));
     connector.ConnectionFailed(services::ClientConnectionObserverFactory::ConnectFailReason::refused);
 }
TEST_F() [2/11]
TEST_F (MqttClientTest , connection_failed_propagates_to_MqttClientFactory)
Definition at line 60 of file TestMqttClient.cpp.
 {
     EXPECT_CALL(factory, ConnectionFailed(services::MqttClientObserverFactory::ConnectFailReason::connectionAllocationFailed));
     connector.ConnectionFailed(services::ClientConnectionObserverFactory::ConnectFailReason::connectionAllocationFailed);
 }
TEST_F() [3/11]
TEST_F (MqttClientTest , after_connected_connect_message_is_sent)
Definition at line 66 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), services::ConnectionObserver::Connected(), and EXPECT_EQ().
 {
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 0x10, 0x28, 0x00, 0x04, 'M' , 'Q' , 'T' , 'T' , 0x04, 0xc2, 0x00, 0x00, 0x00, 0x08, 'c' , 'l' ,
         'i' , 'e' , 'n' , 't' , 'I' , 'd' , 0x00, 0x08, 'u' , 's' , 'e' , 'r' , 'n' , 'a' , 'm' , 'e' ,
         0x00, 0x08, 'p' , 'a' , 's' , 's' , 'w' , 'o' , 'r' , 'd' }), connection.sentData);
 }
TEST_F() [4/11]
TEST_F (MqttClientTest , after_conack_MqttClient_is_connected)
Definition at line 82 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), services::ConnectionObserver::Connected(), and infra::Lambda().
 {
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
     ExecuteAllActions();
     EXPECT_CALL(factory, ConnectionEstablished(testing::_)).WillOnce(infra::Lambda([this](infra::AutoResetFunction<void(infra::SharedPtr<services::MqttClientObserver> client)>& createdClient)
     {
         EXPECT_CALL(client, Connected());
         createdClient(clientPtr);
     }));
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x20, 0x00, 0x00, 0x00 });
     ExecuteAllActions();
 }
TEST_F() [5/11]
TEST_F (MqttClientTest , partial_conack_is_ignored)
Definition at line 102 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), and services::ConnectionObserver::Connected().
 {
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
     ExecuteAllActions();
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x20 });
     ExecuteAllActions();
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x00, 0x00 });
     ExecuteAllActions();
 }
TEST_F() [6/11]
TEST_F (MqttClientTest , invalid_response_results_in_ConnectionFailed)
Definition at line 120 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), and services::ConnectionObserver::Connected().
 {
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
     ExecuteAllActions();
     EXPECT_CALL(factory, ConnectionFailed(services::MqttClientObserverFactory::ConnectFailReason::initializationFailed));
     EXPECT_CALL(connection, AbortAndDestroyMock());
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x30, 0 });
     ExecuteAllActions();
 }
TEST_F() [7/11]
TEST_F (MqttClientTest , timeout_results_in_ConnectionFailed)
Definition at line 137 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), and services::ConnectionObserver::Connected().
 {
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
     ExecuteAllActions();
     EXPECT_CALL(factory, ConnectionFailed(services::MqttClientObserverFactory::ConnectFailReason::initializationTimedOut));
     EXPECT_CALL(connection, AbortAndDestroyMock());
     ForwardTime(std::chrono::minutes(1));
 }
TEST_F() [8/11]
TEST_F (MqttClientTest , client_observer_allocation_failure_results_in_connection_aborted)
Definition at line 153 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), services::ConnectionObserver::Connected(), and infra::Lambda().
 {
     connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
     {
         connectionObserver->Attach(connection);
         connection.SetOwnership(nullptr, connectionObserver);
         connectionObserver->Connected();
     });
     ExecuteAllActions();
     EXPECT_CALL(factory, ConnectionEstablished(testing::_)).WillOnce(infra::Lambda([this](infra::AutoResetFunction<void(infra::SharedPtr<services::MqttClientObserver> client)>& createdClient)
     {
         createdClient(nullptr);
     }));
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x20, 0x00, 0x00, 0x00 });
     EXPECT_CALL(connection, AbortAndDestroyMock());
     ExecuteAllActions();
 }
TEST_F() [9/11]
TEST_F (MqttClientTest , Publish_some_data)
Definition at line 173 of file TestMqttClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Publish("topic", "payload");
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 0x32, 0x10, 0x00, 0x05, 't', 'o', 'p', 'i', 'c', 0, 1, 'p', 'a', 'y', 'l', 'o', 'a', 'd' }), connection.sentData);
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x40, 0x00, 0x01, 0x00 });
     EXPECT_CALL(client, PublishDone());
     ExecuteAllActions();
 }
TEST_F() [10/11]
TEST_F (MqttClientTest , partial_puback_is_ignored)
Definition at line 187 of file TestMqttClient.cpp.
References EXPECT_EQ().
 {
     Connect();
     client.Subject().Publish("topic", "payload");
     ExecuteAllActions();
     EXPECT_EQ((std::vector<uint8_t>{ 0x32, 0x10, 0x00, 0x05, 't', 'o', 'p', 'i', 'c', 0, 1, 'p', 'a', 'y', 'l', 'o', 'a', 'd' }), connection.sentData);
     connection.SimulateDataReceived(std::vector<uint8_t>{ 0x40, 0x00, 0x01 });
     ExecuteAllActions();
 }
TEST_F() [11/11]
TEST_F (MqttClientTest , closed_connection_results_in_ClosingConnection)
Definition at line 200 of file TestMqttClient.cpp.
 {
     Connect();
     EXPECT_CALL(connection, AbortAndDestroyMock());
     EXPECT_CALL(client, ClosingConnection());
     connection.AbortAndDestroy();
 }