EMil: infra::JsonObject Class Reference
infra::JsonObject Class Reference
#include <Json.hpp>
Public Member Functions
JsonObject ()=default
JsonObject (infra::BoundedConstString objectString)
infra::BoundedConstString ObjectString () const
JsonObjectIterator begin ()
JsonObjectIterator end ()
bool HasKey (infra::BoundedConstString key)
JsonString GetString (infra::BoundedConstString key)
bool GetBoolean (infra::BoundedConstString key)
int32_t GetInteger (infra::BoundedConstString key)
JsonObject GetObject (infra::BoundedConstString key)
JsonArray GetArray (infra::BoundedConstString key)
JsonValue GetValue (infra::BoundedConstString key)
infra::Optional< JsonString > GetOptionalString (infra::BoundedConstString key)
infra::Optional< bool > GetOptionalBoolean (infra::BoundedConstString key)
infra::Optional< int32_t > GetOptionalInteger (infra::BoundedConstString key)
infra::Optional< JsonObject > GetOptionalObject (infra::BoundedConstString key)
infra::Optional< JsonArray > GetOptionalArray (infra::BoundedConstString key)
bool operator== (const JsonObject &other) const
bool operator!= (const JsonObject &other) const
void SetError ()
bool Error () const
Private Member Functions
template<class T >
T GetValue (infra::BoundedConstString key)
template<class T >
infra::Optional< T > GetOptionalValue (infra::BoundedConstString key)
Private Attributes
infra::BoundedConstString objectString
bool error = false
Detailed Description
Definition at line 240 of file Json.hpp.
Constructor & Destructor Documentation
JsonObject() [1/2]
infra::JsonObject::JsonObject () default
JsonObject() [2/2]
infra::JsonObject::JsonObject (infra::BoundedConstString objectString) explicit
Definition at line 580 of file Json.cpp.
         : objectString(objectString)
     {}
Member Function Documentation
begin()
JsonObjectIterator infra::JsonObject::begin ()
Definition at line 589 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::GetComponents(), and operator==().
     {
         return JsonObjectIterator(*this);
     }
end()
JsonObjectIterator infra::JsonObject::end ()
Definition at line 594 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::GetComponents(), and operator==().
     {
         return JsonObjectIterator();
     }
Error()
bool infra::JsonObject::Error () const
Definition at line 691 of file Json.cpp.
References error.
Referenced by application::UpgradePackConfigParser::CheckValidJson(), and operator==().
     {
         return error;
     }
GetArray()
JsonArray infra::JsonObject::GetArray (infra::BoundedConstString key)
Definition at line 630 of file Json.cpp.
     {
         return GetValue<JsonArray>(key);
     }
GetBoolean()
bool infra::JsonObject::GetBoolean (infra::BoundedConstString key)
Definition at line 615 of file Json.cpp.
     {
         return GetValue<bool>(key);
     }
GetInteger()
int32_t infra::JsonObject::GetInteger (infra::BoundedConstString key)
Definition at line 620 of file Json.cpp.
     {
         return GetValue<int32_t>(key);
     }
GetObject()
JsonObject infra::JsonObject::GetObject (infra::BoundedConstString key)
Definition at line 625 of file Json.cpp.
     {
         return GetValue<JsonObject>(key);
     }
GetOptionalArray()
infra::Optional< JsonArray > infra::JsonObject::GetOptionalArray (infra::BoundedConstString key)
Definition at line 667 of file Json.cpp.
     {
         return GetOptionalValue<JsonArray>(key);
     }
GetOptionalBoolean()
infra::Optional< bool > infra::JsonObject::GetOptionalBoolean (infra::BoundedConstString key)
Definition at line 652 of file Json.cpp.
     {
         return GetOptionalValue<bool>(key);
     }
GetOptionalInteger()
infra::Optional< int32_t > infra::JsonObject::GetOptionalInteger (infra::BoundedConstString key)
Definition at line 657 of file Json.cpp.
     {
         return GetOptionalValue<int32_t>(key);
     }
GetOptionalObject()
infra::Optional< JsonObject > infra::JsonObject::GetOptionalObject (infra::BoundedConstString key)
Definition at line 662 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::GetComponents(), and application::UpgradePackConfigParser::GetOptions().
     {
         return GetOptionalValue<JsonObject>(key);
     }
GetOptionalString()
infra::Optional< JsonString > infra::JsonObject::GetOptionalString (infra::BoundedConstString key)
Definition at line 647 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::GetOutputFilename().
     {
         return GetOptionalValue<JsonString>(key);
     }
GetOptionalValue()
template<class T > infra::Optional< T > infra::JsonObject::GetOptionalValue (infra::BoundedConstString key) private
Definition at line 710 of file Json.cpp.
References infra::MakeOptional(), and infra::none.
     {
         for (auto& keyValue : *this)
         {
             if (keyValue.key == key && keyValue.value.Is<T>())
                 return infra::MakeOptional(keyValue.value.Get<T>());
         }
         return infra::none;
     }
GetString()
JsonString infra::JsonObject::GetString (infra::BoundedConstString key)
Definition at line 610 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::GetOutputFilename().
     {
         return GetValue<JsonString>(key);
     }
GetValue() [1/2]
JsonValue infra::JsonObject::GetValue (infra::BoundedConstString key)
Definition at line 635 of file Json.cpp.
References SetError().
     {
         for (auto& keyValue : *this)
         {
             if (keyValue.key == key)
                 return keyValue.value;
         }
         SetError();
         return JsonValue();
     }
GetValue() [2/2]
template<class T > T infra::JsonObject::GetValue (infra::BoundedConstString key) private
Definition at line 697 of file Json.cpp.
References infra::Variant< T >::Get(), and SetError().
     {
         for (auto& keyValue : *this)
         {
             if (keyValue.key == key && keyValue.value.Is<T>())
                 return keyValue.value.Get<T>();
         }
         SetError();
         return T();
     }
HasKey()
bool infra::JsonObject::HasKey (infra::BoundedConstString key)
Definition at line 599 of file Json.cpp.
Referenced by application::UpgradePackConfigParser::CheckMandatoryKeys(), application::UpgradePackConfigParser::GetOptions(), and application::UpgradePackConfigParser::GetOutputFilename().
     {
         for (auto& keyValue : *this)
         {
             if (keyValue.key == key)
                 return true;
         }
         return false;
     }
ObjectString()
infra::BoundedConstString infra::JsonObject::ObjectString () const
Definition at line 584 of file Json.cpp.
References objectString.
Referenced by infra::JsonObjectFormatter::Add().
     {
         return objectString;
     }
operator!=()
bool infra::JsonObject::operator!= (const JsonObject & other) const
Definition at line 681 of file Json.cpp.
     {
         return !(*this == other);
     }
operator==()
bool infra::JsonObject::operator== (const JsonObject & other) const
Definition at line 672 of file Json.cpp.
References begin(), end(), and Error().
     {
         JsonObject left(*this);
         JsonObject right(other);
         bool result = Equal(left.begin(), left.end(), right.begin(), right.end());
         return result && !left.Error() && !right.Error();
     }
SetError()
void infra::JsonObject::SetError ()
Definition at line 686 of file Json.cpp.
References error.
Referenced by GetValue().
     {
         error = true;
     }
Member Data Documentation
error
bool infra::JsonObject::error = false private
Definition at line 281 of file Json.hpp.
Referenced by Error(), and SetError().
objectString
infra::BoundedConstString infra::JsonObject::objectString private
Definition at line 280 of file Json.hpp.
Referenced by ObjectString().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp