EMil: TestJsonFormatter.cpp File Reference
TestJsonFormatter.cpp File Reference
Functions
TEST (BasicUsageTest, format_json_object)
TEST (JsonObjectFormatter, construction_results_in_empty_object)
TEST (JsonObjectFormatter, add_bool)
TEST (JsonObjectFormatter, add_int)
TEST (JsonObjectFormatter, add_const_char_ptr)
TEST (JsonObjectFormatter, add_BoundedConstString)
TEST (JsonObjectFormatter, add_milli_float)
TEST (JsonObjectFormatter, add_sting_as_sub_object)
TEST (JsonObjectFormatter, add_sub_object)
TEST (JsonObjectFormatter, add_sub_array)
TEST (JsonObjectFormatter, add_string_via_stream)
TEST (JsonObjectFormatter, add_json_value_bool)
TEST (JsonObjectFormatter, add_json_value_int)
TEST (JsonObjectFormatter, add_json_value_string)
TEST (JsonObjectFormatter, add_json_value_object)
TEST (JsonObjectFormatter, add_json_value_array)
TEST (JsonObjectFormatter, output_is_truncated_on_small_output_string)
TEST (JsonObjectFormatter, move_object_formatter)
TEST (JsonObjectFormatter, move_array_formatter)
TEST (JsonObjectFormatter, escape_strings)
TEST (JsonObjectFormatter, JsonEscapedStringSize_results_in_size_of_escaped_string)
TEST (JsonArrayFormatter, construction_results_in_empty_object)
TEST (JsonArrayFormatter, add_bool)
TEST (JsonArrayFormatter, add_int)
TEST (JsonArrayFormatter, add_const_char_ptr)
TEST (JsonArrayFormatter, add_BoundedConstString)
TEST (JsonArrayFormatter, add_sub_object)
TEST (JsonArrayFormatter, add_sub_array)
TEST (JsonArrayFormatter, output_is_truncated_on_small_output_string)
Function Documentation
TEST() [1/29]
TEST (BasicUsageTest , format_json_object)
Definition at line 4 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<100> response;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, response);
         formatter.Add("name", "Upgrade 19.2");
         formatter.Add("version", "19.2");
         formatter.Add("canupgrade", true);
     }
     EXPECT_EQ(R"({ "name":"Upgrade 19.2", "version":"19.2", "canupgrade":true })", response);
 }
TEST() [2/29]
TEST (JsonObjectFormatter , construction_results_in_empty_object)
Definition at line 17 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
     }
     EXPECT_EQ("{  }", string);
 }
TEST() [3/29]
TEST (JsonObjectFormatter , add_bool)
Definition at line 28 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add("trueTag", true);
         formatter.Add("falseTag", false);
     }
     EXPECT_EQ(R"({ "trueTag":true, "falseTag":false })", string);
 }
TEST() [4/29]
TEST (JsonObjectFormatter , add_int)
Definition at line 41 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add("intTag", 0);
         formatter.Add("uint32Tag", static_cast<uint32_t>(5));
         formatter.Add("int64Tag", static_cast<int64_t>(-10));
     }
     EXPECT_EQ(R"({ "intTag":0, "uint32Tag":5, "int64Tag":-10 })", string);
 }
TEST() [5/29]
TEST (JsonObjectFormatter , add_const_char_ptr)
Definition at line 55 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         const char* s = "test";
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add("tag", s);
     }
     EXPECT_EQ(R"({ "tag":"test" })", string);
 }
TEST() [6/29]
TEST (JsonObjectFormatter , add_BoundedConstString)
Definition at line 68 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::BoundedConstString s("test");
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add("tag", s);
     }
     EXPECT_EQ(R"({ "tag":"test" })", string);
 }
TEST() [7/29]
TEST (JsonObjectFormatter , add_milli_float)
Definition at line 81 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.AddMilliFloat("tag", 12, 34);
     }
     EXPECT_EQ(R"({ "tag":12.034 })", string);
 }
TEST() [8/29]
TEST (JsonObjectFormatter , add_sting_as_sub_object)
Definition at line 93 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::BoundedConstString s(R"({ "test": 123 })");
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.AddSubObject("tag", s);
     }
     EXPECT_EQ(R"({ "tag":{ "test": 123 } })", string);
 }
TEST() [9/29]
TEST (JsonObjectFormatter , add_sub_object)
Definition at line 106 of file TestJsonFormatter.cpp.
References infra::JsonObjectFormatter::Add(), EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         {
             infra::JsonObjectFormatter subObject(formatter.SubObject("tag"));
             subObject.Add("subTagName", "value");
         }
     }
     EXPECT_EQ(R"({ "tag":{ "subTagName":"value" } })", string);
 }
TEST() [10/29]
TEST (JsonObjectFormatter , add_sub_array)
Definition at line 121 of file TestJsonFormatter.cpp.
References infra::JsonArrayFormatter::Add(), EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         {
             infra::JsonArrayFormatter subArray(formatter.SubArray("tag"));
             subArray.Add("value");
         }
     }
     EXPECT_EQ(R"({ "tag":[ "value" ] })", string);
 }
TEST() [11/29]
TEST (JsonObjectFormatter , add_string_via_stream)
Definition at line 136 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::BoundedConstString s("test");
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         auto stream = formatter.AddString("tag");
         stream << s;
     }
     EXPECT_EQ(R"({ "tag":"test" })", string);
 }
TEST() [12/29]
TEST (JsonObjectFormatter , add_json_value_bool)
Definition at line 150 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(infra::JsonKeyValue{ "tag", infra::JsonValue(infra::InPlaceType<bool>(), true) });
     }
     EXPECT_EQ(R"({ "tag":true })", string);
 }
TEST() [13/29]
TEST (JsonObjectFormatter , add_json_value_int)
Definition at line 162 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(infra::JsonKeyValue{ "tag", infra::JsonValue(infra::InPlaceType<int32_t>(), 5) });
     }
     EXPECT_EQ(R"({ "tag":5 })", string);
 }
TEST() [14/29]
TEST (JsonObjectFormatter , add_json_value_string)
Definition at line 174 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(infra::JsonKeyValue{ "tag\\\"", infra::JsonValue(infra::InPlaceType<infra::JsonString>(), R"(ab\"cd)") });
     }
     EXPECT_EQ("{ \"tag\\\"\":\"ab\\\"cd\" }", string);
 }
TEST() [15/29]
TEST (JsonObjectFormatter , add_json_value_object)
Definition at line 186 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(infra::JsonKeyValue{ "tag", infra::JsonValue(infra::InPlaceType<infra::JsonObject>(), infra::JsonObject("{}")) });
     }
     EXPECT_EQ(R"({ "tag":{} })", string);
 }
TEST() [16/29]
TEST (JsonObjectFormatter , add_json_value_array)
Definition at line 198 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(infra::JsonKeyValue{ "tag", infra::JsonValue(infra::InPlaceType<infra::JsonArray>(), infra::JsonArray("[]")) });
     }
     EXPECT_EQ(R"({ "tag":[] })", string);
 }
TEST() [17/29]
TEST (JsonObjectFormatter , output_is_truncated_on_small_output_string)
Definition at line 210 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<1> string;
     {
         infra::BoundedConstString s("test");
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add("tag", s);
     }
     EXPECT_EQ(R"({)", string);
 }
TEST() [18/29]
TEST (JsonObjectFormatter , move_object_formatter)
Definition at line 223 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<100> string;
     {
         auto formatter = infra::JsonObjectFormatter::WithStringStream(infra::inPlace, string);
         auto subObject = std::move(formatter.SubObject("tag"));
     }
     EXPECT_EQ(R"({ "tag":{  } })", string);
 }
TEST() [19/29]
TEST (JsonObjectFormatter , move_array_formatter)
Definition at line 235 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<100> string;
     {
         auto formatter = infra::JsonObjectFormatter::WithStringStream(infra::inPlace, string);
         auto subArray = std::move(formatter.SubArray("tag"));
     }
     EXPECT_EQ(R"({ "tag":[  ] })", string);
 }
TEST() [20/29]
TEST (JsonObjectFormatter , escape_strings)
Definition at line 247 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonObjectFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add("tag", "\"\b\f\n\r\t\x11");
     }
     EXPECT_EQ("{ \"tag\":\"\\\"\\b\\f\\n\\r\\t\\u0011\" }", string);
 }
TEST() [21/29]
TEST (JsonObjectFormatter , JsonEscapedStringSize_results_in_size_of_escaped_string)
Definition at line 259 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::JsonEscapedStringSize().
 {
     EXPECT_EQ(0, infra::JsonEscapedStringSize(""));
     EXPECT_EQ(2, infra::JsonEscapedStringSize("{}"));
     EXPECT_EQ(2, infra::JsonEscapedStringSize("\""));
     EXPECT_EQ(4, infra::JsonEscapedStringSize("\r\n"));
     EXPECT_EQ(12, infra::JsonEscapedStringSize("\x11\x11"));
 }
TEST() [22/29]
TEST (JsonArrayFormatter , construction_results_in_empty_object)
Definition at line 268 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
     }
     EXPECT_EQ("[  ]", string);
 }
TEST() [23/29]
TEST (JsonArrayFormatter , add_bool)
Definition at line 279 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(true);
         formatter.Add(false);
     }
     EXPECT_EQ(R"([ true, false ])", string);
 }
TEST() [24/29]
TEST (JsonArrayFormatter , add_int)
Definition at line 292 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(0);
         formatter.Add(static_cast<uint32_t>(5));
         formatter.Add(static_cast<int64_t>(-10));
     }
     EXPECT_EQ(R"([ 0, 5, -10 ])", string);
 }
TEST() [25/29]
TEST (JsonArrayFormatter , add_const_char_ptr)
Definition at line 306 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         const char* s = "test";
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(s);
     }
     EXPECT_EQ(R"([ "test" ])", string);
 }
TEST() [26/29]
TEST (JsonArrayFormatter , add_BoundedConstString)
Definition at line 319 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::BoundedConstString s("test");
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(s);
     }
     EXPECT_EQ(R"([ "test" ])", string);
 }
TEST() [27/29]
TEST (JsonArrayFormatter , add_sub_object)
Definition at line 332 of file TestJsonFormatter.cpp.
References infra::JsonObjectFormatter::Add(), EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         {
             infra::JsonObjectFormatter subObject(formatter.SubObject());
             subObject.Add("subTagName", "value");
         }
     }
     EXPECT_EQ(R"([ { "subTagName":"value" } ])", string);
 }
TEST() [28/29]
TEST (JsonArrayFormatter , add_sub_array)
Definition at line 347 of file TestJsonFormatter.cpp.
References infra::JsonArrayFormatter::Add(), EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<64> string;
     {
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         {
             infra::JsonArrayFormatter subArray(formatter.SubArray());
             subArray.Add("value");
         }
     }
     EXPECT_EQ(R"([ [ "value" ] ])", string);
 }
TEST() [29/29]
TEST (JsonArrayFormatter , output_is_truncated_on_small_output_string)
Definition at line 362 of file TestJsonFormatter.cpp.
References EXPECT_EQ(), and infra::inPlace.
 {
     infra::BoundedString::WithStorage<1> string;
     {
         infra::BoundedConstString s("test");
         infra::JsonArrayFormatter::WithStringStream formatter(infra::inPlace, string);
         formatter.Add(s);
     }
     EXPECT_EQ(R"([)", string);
 }