EMil: FlashQuadSpiCypressFllTest Class Reference
FlashQuadSpiCypressFllTest Class Reference
Public Member Functions
FlashQuadSpiCypressFllTest ()
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< hal::QuadSpiStub > spiStub
infra::VerifyingFunctionMock< void()> onInitialized
services::FlashQuadSpiCypressFll flash
testing::StrictMock< infra::MockCallback< void()> > finished
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 7 of file TestFlashQuadSpiCypressFll.cpp.
Constructor & Destructor Documentation
FlashQuadSpiCypressFllTest()
FlashQuadSpiCypressFllTest::FlashQuadSpiCypressFllTest () inline
Definition at line 12 of file TestFlashQuadSpiCypressFll.cpp.
References services::FlashQuadSpiCypressFll::commandEnterQpi, infra::ClockFixture::ForwardTime(), infra::MakeOptional(), onInitialized, hal::QuadSpi::Lines::SingleSpeed(), and spiStub.
         : flash(spiStub, onInitialized)
     {
         EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiCypressFll::commandEnterQpi), {}, {}, 0 },
             infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
         ForwardTime(std::chrono::milliseconds(100));
         testing::Mock::VerifyAndClear(&spiStub);
         testing::Mock::VerifyAndClear(&onInitialized);
     }
Member Data Documentation
finished
testing::StrictMock<infra::MockCallback<void()> > FlashQuadSpiCypressFllTest::finished
Definition at line 27 of file TestFlashQuadSpiCypressFll.cpp.
flash
services::FlashQuadSpiCypressFll FlashQuadSpiCypressFllTest::flash
Definition at line 25 of file TestFlashQuadSpiCypressFll.cpp.
onInitialized
infra::VerifyingFunctionMock<void()> FlashQuadSpiCypressFllTest::onInitialized
Definition at line 24 of file TestFlashQuadSpiCypressFll.cpp.
Referenced by FlashQuadSpiCypressFllTest().
spiStub
testing::StrictMock<hal::QuadSpiStub> FlashQuadSpiCypressFllTest::spiStub
Definition at line 23 of file TestFlashQuadSpiCypressFll.cpp.
Referenced by FlashQuadSpiCypressFllTest().
The documentation for this class was generated from the following file:
TestFlashQuadSpiCypressFll.cpp