EMil: infra::EventDispatcherWorkerImpl Class Reference
infra::EventDispatcherWorkerImpl Class Reference
#include <EventDispatcher.hpp>
Public Types
template<std::size_t StorageSize, class T = EventDispatcherWorkerImpl>
using WithSize = infra::WithStorage< T, std::array< std::pair< infra::Function< void()>, std::atomic< bool > >, StorageSize > >
Public Member Functions
EventDispatcherWorkerImpl (MemoryRange< std::pair< infra::Function< void()>, std::atomic< bool >>> scheduledActionsStorage)
virtual void Schedule (const infra::Function< void()> &action) override
virtual std::size_t MinCapacity () const override
virtual bool IsIdle () const override
void Run ()
void ExecuteAllActions ()
Protected Member Functions
virtual void RequestExecution ()
virtual void Idle ()
virtual void ExecuteFirstAction () override
Protected Member Functions inherited from infra::EventDispatcherWorker
EventDispatcherWorker ()=default
EventDispatcherWorker (const EventDispatcherWorker &other)=delete
EventDispatcherWorker & operator= (const EventDispatcherWorker &other)=delete
~EventDispatcherWorker ()=default
Private Member Functions
bool TryExecuteAction ()
Private Attributes
infra::MemoryRange< std::pair< infra::Function< void()>, std::atomic< bool > > > scheduledActions
std::atomic< uint32_t > scheduledActionsPushIndex
uint32_t scheduledActionsPopIndex
std::size_t minCapacity
Detailed Description
Definition at line 26 of file EventDispatcher.hpp.
Member Typedef Documentation
WithSize
template<std::size_t StorageSize, class T = EventDispatcherWorkerImpl> using infra::EventDispatcherWorkerImpl::WithSize = infra::WithStorage<T, std::array<std::pair<infra::Function<void()>, std::atomic<bool> >, StorageSize> >
Definition at line 31 of file EventDispatcher.hpp.
Constructor & Destructor Documentation
EventDispatcherWorkerImpl()
infra::EventDispatcherWorkerImpl::EventDispatcherWorkerImpl (MemoryRange< std::pair< infra::Function< void()>, std::atomic< bool >>> scheduledActionsStorage) explicit
Definition at line 6 of file EventDispatcher.cpp.
References scheduledActions.
         : scheduledActions(scheduledActionsStorage)
         , scheduledActionsPushIndex(0)
         , scheduledActionsPopIndex(0)
         , minCapacity(scheduledActions.size())
     {
         for (auto& action : scheduledActions)
             action.second = false;
     }
Member Function Documentation
ExecuteAllActions()
void infra::EventDispatcherWorkerImpl::ExecuteAllActions ()
Definition at line 45 of file EventDispatcher.cpp.
References TryExecuteAction().
Referenced by Run().
     {
         while (TryExecuteAction())
         {}
     }
ExecuteFirstAction()
void infra::EventDispatcherWorkerImpl::ExecuteFirstAction () override protected virtual
Implements infra::EventDispatcherWorker.
Definition at line 67 of file EventDispatcher.cpp.
References scheduledActions, and scheduledActionsPopIndex.
Referenced by TryExecuteAction().
     {
         scheduledActions[scheduledActionsPopIndex].first();
     }
Idle()
void infra::EventDispatcherWorkerImpl::Idle () protected virtual
Definition at line 64 of file EventDispatcher.cpp.
Referenced by Run().
     {}
IsIdle()
bool infra::EventDispatcherWorkerImpl::IsIdle () const override virtual
Implements infra::EventDispatcherWorker.
Definition at line 51 of file EventDispatcher.cpp.
References scheduledActions, and scheduledActionsPopIndex.
     {
         return !scheduledActions[scheduledActionsPopIndex].second;
     }
MinCapacity()
std::size_t infra::EventDispatcherWorkerImpl::MinCapacity () const override virtual
Implements infra::EventDispatcherWorker.
Definition at line 56 of file EventDispatcher.cpp.
References minCapacity.
     {
         return minCapacity;
     }
RequestExecution()
void infra::EventDispatcherWorkerImpl::RequestExecution () protected virtual
Definition at line 61 of file EventDispatcher.cpp.
Referenced by Schedule().
     {}
Run()
void infra::EventDispatcherWorkerImpl::Run ()
Definition at line 36 of file EventDispatcher.cpp.
References ExecuteAllActions(), and Idle().
     {
         while (true)                                                                                            //TICS !CPP4127
         {
             ExecuteAllActions();
             Idle();
         }
     }
Schedule()
void infra::EventDispatcherWorkerImpl::Schedule (const infra::Function< void()> & action) override virtual
Implements infra::EventDispatcherWorker.
Definition at line 16 of file EventDispatcher.cpp.
References minCapacity, RequestExecution(), scheduledActions, scheduledActionsPopIndex, scheduledActionsPushIndex, and infra::MemoryRange< T >::size().
     {
         uint32_t pushIndex = scheduledActionsPushIndex;
         uint32_t newPushIndex;
         do
         {
             newPushIndex = (pushIndex + 1) % scheduledActions.size();
         } while (!scheduledActionsPushIndex.compare_exchange_weak(pushIndex, newPushIndex));
         scheduledActions[pushIndex].first = action;
         really_assert(!scheduledActions[pushIndex].second);
         scheduledActions[pushIndex].second = true;
         minCapacity = std::min<std::size_t>(minCapacity, (scheduledActions.size() + scheduledActionsPopIndex - pushIndex - 1) % scheduledActions.size() + 1);
         really_assert(minCapacity >= 1);
         RequestExecution();
     }
TryExecuteAction()
bool infra::EventDispatcherWorkerImpl::TryExecuteAction () private
Definition at line 72 of file EventDispatcher.cpp.
References ExecuteFirstAction(), scheduledActions, scheduledActionsPopIndex, and infra::MemoryRange< T >::size().
Referenced by ExecuteAllActions().
     {
         if (scheduledActions[scheduledActionsPopIndex].second)
         {
             ExecuteFirstAction();
             scheduledActions[scheduledActionsPopIndex].first = nullptr;
             scheduledActions[scheduledActionsPopIndex].second = false;
             scheduledActionsPopIndex = (scheduledActionsPopIndex + 1) % scheduledActions.size();
             return true;
         }
         else
             return false;
     }
Member Data Documentation
minCapacity
std::size_t infra::EventDispatcherWorkerImpl::minCapacity private
Definition at line 55 of file EventDispatcher.hpp.
Referenced by MinCapacity(), and Schedule().
scheduledActions
infra::MemoryRange<std::pair<infra::Function<void()>, std::atomic<bool> > > infra::EventDispatcherWorkerImpl::scheduledActions private
Definition at line 52 of file EventDispatcher.hpp.
Referenced by EventDispatcherWorkerImpl(), ExecuteFirstAction(), IsIdle(), Schedule(), and TryExecuteAction().
scheduledActionsPopIndex
uint32_t infra::EventDispatcherWorkerImpl::scheduledActionsPopIndex private
Definition at line 54 of file EventDispatcher.hpp.
Referenced by ExecuteFirstAction(), IsIdle(), Schedule(), and TryExecuteAction().
scheduledActionsPushIndex
std::atomic<uint32_t> infra::EventDispatcherWorkerImpl::scheduledActionsPushIndex private
Definition at line 53 of file EventDispatcher.hpp.
Referenced by Schedule().
The documentation for this class was generated from the following files:
EventDispatcher.hpp
EventDispatcher.cpp