EMil: infra::AccessedBySharedPtr Class Reference
infra::AccessedBySharedPtr Class Reference
#include <SharedPtr.hpp>
Public Member Functions
AccessedBySharedPtr ()=default
AccessedBySharedPtr (const infra::Function< void()> &onUnReferenced)
~AccessedBySharedPtr ()
template<class T >
SharedPtr< T > MakeShared (T &value)
void SetAction (const infra::Function< void()> &newOnUnReferenced)
Private Member Functions
virtual void Destruct (const void *object) override
virtual void Deallocate (void *control) override
SharedObjectDeleter ()=default
SharedObjectDeleter (const SharedObjectDeleter &other)=delete
SharedObjectDeleter & operator= (const SharedObjectDeleter &other)=delete
~SharedObjectDeleter ()=default
Private Attributes
detail::SharedPtrControl control { this, this }
infra::Function< void()> onUnReferenced
Detailed Description
Definition at line 201 of file SharedPtr.hpp.
Constructor & Destructor Documentation
AccessedBySharedPtr() [1/2]
infra::AccessedBySharedPtr::AccessedBySharedPtr () default
AccessedBySharedPtr() [2/2]
infra::AccessedBySharedPtr::AccessedBySharedPtr (const infra::Function< void()> & onUnReferenced)
Definition at line 62 of file SharedPtr.cpp.
         : onUnReferenced(onUnReferenced)
     {}
~AccessedBySharedPtr()
infra::AccessedBySharedPtr::~AccessedBySharedPtr ()
Definition at line 66 of file SharedPtr.cpp.
References control, and infra::detail::SharedPtrControl::UnReferenced().
     {
         assert(control.UnReferenced());
     }
Member Function Documentation
Deallocate()
void infra::AccessedBySharedPtr::Deallocate (void * control) override private virtual
Implements infra::SharedObjectDeleter.
Definition at line 79 of file SharedPtr.cpp.
References onUnReferenced.
     {
         onUnReferenced();
     }
Destruct()
void infra::AccessedBySharedPtr::Destruct (const void * object) override private virtual
Implements infra::SharedObjectDeleter.
Definition at line 76 of file SharedPtr.cpp.
     {}
MakeShared()
template<class T > SharedPtr< T > infra::AccessedBySharedPtr::MakeShared (T & value)
Definition at line 587 of file SharedPtr.hpp.
References control, and value.
Referenced by services::HttpClientImpl::BodyReceived(), services::HttpClientBasic::ConnectionEstablished(), services::HttpClientImpl::DataReceived(), and services::HttpClientImpl::ForwardStream().
     {
         return SharedPtr<T>(&control, &value);
     }
SetAction()
void infra::AccessedBySharedPtr::SetAction (const infra::Function< void()> & newOnUnReferenced)
Definition at line 71 of file SharedPtr.cpp.
References onUnReferenced.
Referenced by services::HttpClientImpl::AbortAndDestroy(), services::HttpClientBasic::Cancel(), services::HttpClientImpl::Close(), services::HttpClientBasic::ClosingConnection(), services::HttpClientImpl::Connected(), services::HttpClientImpl::ForwardStream(), and services::HttpClientBasic::Timeout().
     {
         onUnReferenced = newOnUnReferenced;
     }
Member Data Documentation
control
detail::SharedPtrControl infra::AccessedBySharedPtr::control { this, this } private
Definition at line 219 of file SharedPtr.hpp.
Referenced by MakeShared(), and ~AccessedBySharedPtr().
onUnReferenced
infra::Function<void()> infra::AccessedBySharedPtr::onUnReferenced private
Definition at line 220 of file SharedPtr.hpp.
Referenced by Deallocate(), and SetAction().
The documentation for this class was generated from the following files:
SharedPtr.hpp
SharedPtr.cpp