EMil: application::DecryptorXtea Class Reference
application::DecryptorXtea Class Reference
#include <DecryptorXtea.hpp>
Public Member Functions
DecryptorXtea (infra::ConstByteRange key)
virtual infra::ByteRange StateBuffer () override
virtual void Reset () override
virtual void DecryptPart (infra::ByteRange data) override
virtual bool DecryptAndAuthenticate (infra::ByteRange data) override
Static Public Attributes
static const std::size_t blockLength = 8
Private Attributes
mbedtls_xtea_context ctx
std::array< uint8_t, blockLength > iv
Additional Inherited Members
Protected Member Functions inherited from application::Decryptor
~Decryptor ()=default
Detailed Description
Definition at line 9 of file DecryptorXtea.hpp.
Constructor & Destructor Documentation
DecryptorXtea()
application::DecryptorXtea::DecryptorXtea (infra::ConstByteRange key) explicit
Definition at line 5 of file DecryptorXtea.cpp.
References infra::MemoryRange< T >::begin(), ctx, and infra::MemoryRange< T >::size().
     {
         mbedtls_xtea_init(&ctx);
         assert(key.size() == 16);
         mbedtls_xtea_setup(&ctx, key.begin());                                                                  //TICS !INT#030
     }
Member Function Documentation
DecryptAndAuthenticate()
bool application::DecryptorXtea::DecryptAndAuthenticate (infra::ByteRange data) override virtual
Implements application::Decryptor.
Definition at line 25 of file DecryptorXtea.cpp.
References infra::data, and DecryptPart().
     {
         DecryptPart(data);
         return true;
     }
DecryptPart()
void application::DecryptorXtea::DecryptPart (infra::ByteRange data) override virtual
Implements application::Decryptor.
Definition at line 20 of file DecryptorXtea.cpp.
References ctx, infra::data, and iv.
Referenced by DecryptAndAuthenticate().
     {
         mbedtls_xtea_crypt_cbc(&ctx, MBEDTLS_XTEA_DECRYPT, data.size(), iv.data(), data.begin(), data.begin()); //TICS !INT#030
     }
Reset()
void application::DecryptorXtea::Reset () override virtual
Implements application::Decryptor.
Definition at line 17 of file DecryptorXtea.cpp.
     {}
StateBuffer()
infra::ByteRange application::DecryptorXtea::StateBuffer () override virtual
Implements application::Decryptor.
Definition at line 12 of file DecryptorXtea.cpp.
References iv, and infra::MakeByteRange().
     {
         return infra::MakeByteRange(iv);
     }
Member Data Documentation
blockLength
const std::size_t application::DecryptorXtea::blockLength = 8 static
Definition at line 13 of file DecryptorXtea.hpp.
ctx
mbedtls_xtea_context application::DecryptorXtea::ctx private
Definition at line 23 of file DecryptorXtea.hpp.
Referenced by DecryptorXtea(), and DecryptPart().
iv
std::array<uint8_t, blockLength> application::DecryptorXtea::iv private
Definition at line 24 of file DecryptorXtea.hpp.
Referenced by DecryptPart(), and StateBuffer().
The documentation for this class was generated from the following files:
DecryptorXtea.hpp
DecryptorXtea.cpp