EMil: TestOptional.cpp File Reference
TestOptional.cpp File Reference
Classes
struct PolymorphicBool
struct PolymorphicBoolDescendant
Namespaces
infra
Functions
void infra::OptionalCoverageDummy ()
TEST (OptionalTest, OptionalCoverageDummy)
TEST (OptionalTest, TestConstructedEmpty)
TEST (OptionalTest, TestConstructedEmptyWithNone)
TEST (OptionalTest, TestConstructedWithValue)
TEST (OptionalTest, TestConstructedWithMovedValue)
TEST (OptionalTest, TestConstructedWithConvertibleValue)
TEST (OptionalTest, TestCopyConstruction)
TEST (OptionalTest, TestMoveConstruction)
TEST (OptionalTest, TestMoveConstructedWithEmptyOptional)
TEST (OptionalTest, TestCopyAssign)
TEST (OptionalTest, TestCopyAssignWithSelf)
TEST (OptionalTest, TestCopyAssignWithEmptyOptional)
TEST (OptionalTest, TestMoveAssign)
TEST (OptionalTest, TestMoveAssignWithEmpty)
TEST (OptionalTest, TestAssignValue)
TEST (OptionalTest, TestAssignNone)
TEST (OptionalTest, TestCompareToNone)
TEST (OptionalTest, TestCompare)
TEST (OptionalTest, TestCompareToValue)
TEST (OptionalTest, TestConstruct)
TEST (OptionalTest, TestConstructWithInitializerList)
TEST (OptionalTest, TestIndirect)
TEST (OptionalTest, TestMakeOptional)
TEST (OptionalTest, TestTransformOptional)
TEST (OptionalTest, ValueOrGivesStoredWhenAvailable)
TEST (OptionalTest, ValueOrGivesParameterWhenNothingIsStored)
TEST (OptionalForPolymorphicObjectsTest, TestConstructedEmpty)
TEST (OptionalForPolymorphicObjectsTest, TestConstructedEmptyWithNone)
TEST (OptionalForPolymorphicObjectsTest, TestConstructedWithValue)
TEST (OptionalForPolymorphicObjectsTest, TestConstructedWithMovedValue)
TEST (OptionalForPolymorphicObjectsTest, TestConstructedWithDescendant)
TEST (OptionalForPolymorphicObjectsTest, TestAssignLValue)
TEST (OptionalForPolymorphicObjectsTest, TestAssignRValue)
TEST (OptionalForPolymorphicObjectsTest, TestAssignNone)
TEST (OptionalForPolymorphicObjectsTest, TestAssignDescendant)
TEST (OptionalForPolymorphicObjectsTest, TestCompareToNone)
TEST (OptionalForPolymorphicObjectsTest, TestCompare)
TEST (OptionalForPolymorphicObjectsTest, TestCompareToValue)
TEST (OptionalForPolymorphicObjectsTest, TestConstruct)
TEST (OptionalForPolymorphicObjectsTest, TestIndirect)
TEST (OptionalForPolymorphicObjectsTest, ConstructDescendant)
Function Documentation
TEST() [1/41]
TEST (OptionalTest , OptionalCoverageDummy)
Definition at line 9 of file TestOptional.cpp.
References infra::OptionalCoverageDummy().
 {
     infra::OptionalCoverageDummy();
 }
TEST() [2/41]
TEST (OptionalTest , TestConstructedEmpty)
Definition at line 14 of file TestOptional.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::Optional<bool> o;
     EXPECT_FALSE(o);
     EXPECT_TRUE(!o);
 }
TEST() [3/41]
TEST (OptionalTest , TestConstructedEmptyWithNone)
Definition at line 21 of file TestOptional.cpp.
References EXPECT_FALSE(), and infra::none.
 {
     infra::Optional<bool> o(infra::none);
     EXPECT_FALSE(o);
 }
TEST() [4/41]
TEST (OptionalTest , TestConstructedWithValue)
Definition at line 27 of file TestOptional.cpp.
References EXPECT_TRUE(), infra::inPlace, and value.
 {
     bool value(true);
     infra::Optional<bool> o(infra::inPlace, value);
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
     EXPECT_TRUE(*(o.operator->()));
 }
TEST() [5/41]
TEST (OptionalTest , TestConstructedWithMovedValue)
Definition at line 36 of file TestOptional.cpp.
References EXPECT_TRUE(), infra::inPlace, and value.
 {
     bool value(true);
     infra::Optional<bool> o(infra::inPlace, std::move(value));
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [6/41]
TEST (OptionalTest , TestConstructedWithConvertibleValue)
Definition at line 44 of file TestOptional.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<short int> x(infra::inPlace, 1);
     infra::Optional<int> y(x);
     EXPECT_TRUE(static_cast<bool>(y));
     EXPECT_EQ(1, *y);
     EXPECT_FALSE(infra::Optional<int>(infra::Optional<short int>()));
 }
TEST() [7/41]
TEST (OptionalTest , TestCopyConstruction)
Definition at line 54 of file TestOptional.cpp.
References EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> o1(infra::inPlace, true);
     infra::Optional<bool> o2(o1);
     EXPECT_TRUE(static_cast<bool>(o1));
     EXPECT_TRUE(static_cast<bool>(o2));
     EXPECT_TRUE(*o2);
 }
TEST() [8/41]
TEST (OptionalTest , TestMoveConstruction)
Definition at line 63 of file TestOptional.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> o1(infra::inPlace, true);
     infra::Optional<bool> o2(std::move(o1));
     EXPECT_FALSE(o1);
     EXPECT_TRUE(static_cast<bool>(o2));
     EXPECT_TRUE(*o2);
 }
TEST() [9/41]
TEST (OptionalTest , TestMoveConstructedWithEmptyOptional)
Definition at line 72 of file TestOptional.cpp.
References EXPECT_FALSE().
 {
     infra::Optional<bool> e;
     infra::Optional<bool> o(std::move(e));
     EXPECT_FALSE(static_cast<bool>(o));
 }
TEST() [10/41]
TEST (OptionalTest , TestCopyAssign)
Definition at line 79 of file TestOptional.cpp.
References EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> o1(infra::inPlace, true);
     infra::Optional<bool> o2;
     o2 = o1;
     EXPECT_TRUE(static_cast<bool>(o1));
     EXPECT_TRUE(static_cast<bool>(o2));
     EXPECT_TRUE(*o2);
 }
TEST() [11/41]
TEST (OptionalTest , TestCopyAssignWithSelf)
Definition at line 89 of file TestOptional.cpp.
References EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> o1(infra::inPlace, true);
     o1 = o1;
     EXPECT_TRUE(static_cast<bool>(o1));
     EXPECT_TRUE(*o1);
 }
TEST() [12/41]
TEST (OptionalTest , TestCopyAssignWithEmptyOptional)
Definition at line 97 of file TestOptional.cpp.
References EXPECT_FALSE().
 {
     infra::Optional<bool> o1;
     infra::Optional<bool> o2;
     o2 = o1;
     EXPECT_FALSE(static_cast<bool>(o2));
 }
TEST() [13/41]
TEST (OptionalTest , TestMoveAssign)
Definition at line 105 of file TestOptional.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> o1(infra::inPlace, true);
     infra::Optional<bool> o2;
     o2 = std::move(o1);
     EXPECT_FALSE(static_cast<bool>(o1));
     EXPECT_TRUE(static_cast<bool>(o2));
     EXPECT_TRUE(*o2);
 }
TEST() [14/41]
TEST (OptionalTest , TestMoveAssignWithEmpty)
Definition at line 115 of file TestOptional.cpp.
References EXPECT_FALSE().
 {
     infra::Optional<bool> o1;
     infra::Optional<bool> o2;
     o2 = std::move(o1);
     EXPECT_FALSE(static_cast<bool>(o1));
     EXPECT_FALSE(static_cast<bool>(o2));
 }
TEST() [15/41]
TEST (OptionalTest , TestAssignValue)
Definition at line 124 of file TestOptional.cpp.
References EXPECT_TRUE().
 {
     infra::Optional<bool> o;
     o = true;
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [16/41]
TEST (OptionalTest , TestAssignNone)
Definition at line 132 of file TestOptional.cpp.
References EXPECT_FALSE(), infra::inPlace, and infra::none.
 {
     infra::Optional<bool> o(infra::inPlace, true);
     o = infra::none;
     EXPECT_FALSE(o);
 }
TEST() [17/41]
TEST (OptionalTest , TestCompareToNone)
Definition at line 139 of file TestOptional.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::none.
 {
     infra::Optional<bool> o;
     EXPECT_TRUE(o == infra::none);
     EXPECT_FALSE(o != infra::none);
     EXPECT_TRUE(infra::none == o);
     EXPECT_FALSE(infra::none != o);
 }
TEST() [18/41]
TEST (OptionalTest , TestCompare)
Definition at line 148 of file TestOptional.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> t(infra::inPlace, true);
     infra::Optional<bool> f(infra::inPlace, false);
     infra::Optional<bool> u;
     EXPECT_TRUE(t == t);
     EXPECT_TRUE(f == f);
     EXPECT_TRUE(u == u);
     EXPECT_FALSE(t == f);
     EXPECT_FALSE(t == u);
     EXPECT_FALSE(f == u);
     EXPECT_FALSE(t != t);
 }
TEST() [19/41]
TEST (OptionalTest , TestCompareToValue)
Definition at line 166 of file TestOptional.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::inPlace.
 {
     infra::Optional<bool> t(infra::inPlace, true);
     infra::Optional<bool> u;
     EXPECT_TRUE(t == true);
     EXPECT_TRUE(true == t);
     EXPECT_FALSE(t == false);
     EXPECT_FALSE(t != true);
     EXPECT_FALSE(true != t);
     EXPECT_FALSE(u == true);
 }
TEST() [20/41]
TEST (OptionalTest , TestConstruct)
Definition at line 181 of file TestOptional.cpp.
References infra::Optional< T >::Emplace(), and EXPECT_TRUE().
 {
     bool b(true);
     infra::Optional<bool> o;
     o.Emplace(std::move(b));
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [21/41]
TEST (OptionalTest , TestConstructWithInitializerList)
Definition at line 190 of file TestOptional.cpp.
References infra::Optional< T >::Emplace(), and EXPECT_TRUE().
 {
     struct X
     {
         X(std::initializer_list<bool>)
         {}
     };
     infra::Optional<X> o;
     o.Emplace({ true });
     EXPECT_TRUE(static_cast<bool>(o));
 }
TEST() [22/41]
TEST (OptionalTest , TestIndirect)
Definition at line 202 of file TestOptional.cpp.
References EXPECT_TRUE(), and infra::inPlace.
 {
     struct X
     {
         X(): x(true) {}
         bool x;
     };
     infra::Optional<X> o(infra::inPlace, X());
     EXPECT_TRUE(o->x);
     EXPECT_TRUE(const_cast<infra::Optional<X>&>(o)->x);
 }
TEST() [23/41]
TEST (OptionalTest , TestMakeOptional)
Definition at line 215 of file TestOptional.cpp.
References EXPECT_TRUE(), and infra::MakeOptional().
 {
     infra::Optional<bool> o = infra::MakeOptional(true);
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [24/41]
TEST (OptionalTest , TestTransformOptional)
Definition at line 222 of file TestOptional.cpp.
References EXPECT_EQ(), infra::MakeOptional(), infra::none, infra::TransformOptional(), and value.
 {
     infra::Optional<bool> o = infra::MakeOptional(true);
     infra::Optional<bool> empty;
     EXPECT_EQ(infra::MakeOptional(5), infra::TransformOptional(infra::MakeOptional(true), [](bool value) { return 5; }));
     EXPECT_EQ(infra::none, infra::TransformOptional(empty, [](bool value) { return 5; }));
 }
TEST() [25/41]
TEST (OptionalTest , ValueOrGivesStoredWhenAvailable)
Definition at line 230 of file TestOptional.cpp.
References EXPECT_EQ(), infra::inPlace, and infra::Optional< T >::ValueOr().
 {
     infra::Optional<int> i(infra::inPlace, 5);
     EXPECT_EQ(5, i.ValueOr(2));
 }
TEST() [26/41]
TEST (OptionalTest , ValueOrGivesParameterWhenNothingIsStored)
Definition at line 236 of file TestOptional.cpp.
References EXPECT_EQ(), and infra::Optional< T >::ValueOr().
 {
     infra::Optional<int> i;
     EXPECT_EQ(2, i.ValueOr(2));
 }
TEST() [27/41]
TEST (OptionalForPolymorphicObjectsTest , TestConstructedEmpty)
Definition at line 266 of file TestOptional.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o;
     EXPECT_FALSE(o);
     EXPECT_TRUE(!o);
 }
TEST() [28/41]
TEST (OptionalForPolymorphicObjectsTest , TestConstructedEmptyWithNone)
Definition at line 273 of file TestOptional.cpp.
References EXPECT_FALSE(), and infra::none.
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o(infra::none);
     EXPECT_FALSE(static_cast<bool>(o));
 }
TEST() [29/41]
TEST (OptionalForPolymorphicObjectsTest , TestConstructedWithValue)
Definition at line 279 of file TestOptional.cpp.
References EXPECT_TRUE(), and value.
 {
     bool value(true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o(infra::InPlaceType<PolymorphicBool>(), value);
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [30/41]
TEST (OptionalForPolymorphicObjectsTest , TestConstructedWithMovedValue)
Definition at line 287 of file TestOptional.cpp.
References EXPECT_TRUE(), and value.
 {
     bool value(true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o(infra::InPlaceType<PolymorphicBool>(), std::move(value));
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [31/41]
TEST (OptionalForPolymorphicObjectsTest , TestConstructedWithDescendant)
Definition at line 295 of file TestOptional.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBoolDescendant, 0> descendant(infra::InPlaceType<PolymorphicBoolDescendant>(), true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o(descendant);
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
     infra::OptionalForPolymorphicObjects<PolymorphicBoolDescendant, 0> emptyDescendant;
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> x(emptyDescendant);
     EXPECT_FALSE(static_cast<bool>(x));
 }
TEST() [32/41]
TEST (OptionalForPolymorphicObjectsTest , TestAssignLValue)
Definition at line 307 of file TestOptional.cpp.
References EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o;
     bool b = true;
     o = b;
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [33/41]
TEST (OptionalForPolymorphicObjectsTest , TestAssignRValue)
Definition at line 316 of file TestOptional.cpp.
References EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o;
     o = true;
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [34/41]
TEST (OptionalForPolymorphicObjectsTest , TestAssignNone)
Definition at line 324 of file TestOptional.cpp.
References EXPECT_FALSE(), and infra::none.
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o(infra::InPlaceType<PolymorphicBool>(), true);
     o = infra::none;
     EXPECT_FALSE(static_cast<bool>(o));
 }
TEST() [35/41]
TEST (OptionalForPolymorphicObjectsTest , TestAssignDescendant)
Definition at line 331 of file TestOptional.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBoolDescendant, 0> descendant(infra::InPlaceType<PolymorphicBoolDescendant>(), true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o;
     o = descendant;
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
     infra::OptionalForPolymorphicObjects<PolymorphicBoolDescendant, 0> emptyDescendant;
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> x;
     x = emptyDescendant;
     EXPECT_FALSE(static_cast<bool>(x));
 }
TEST() [36/41]
TEST (OptionalForPolymorphicObjectsTest , TestCompareToNone)
Definition at line 345 of file TestOptional.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and infra::none.
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o;
     EXPECT_TRUE(o == infra::none);
     EXPECT_FALSE(o != infra::none);
     EXPECT_TRUE(infra::none == o);
     EXPECT_FALSE(infra::none != o);
 }
TEST() [37/41]
TEST (OptionalForPolymorphicObjectsTest , TestCompare)
Definition at line 354 of file TestOptional.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> t(infra::InPlaceType<PolymorphicBool>(), true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> f(infra::InPlaceType<PolymorphicBool>(), false);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> u;
     EXPECT_TRUE(t == t);
     EXPECT_TRUE(f == f);
     EXPECT_TRUE(u == u);
     EXPECT_FALSE(t == f);
     EXPECT_FALSE(t == u);
     EXPECT_FALSE(f == u);
     EXPECT_TRUE(f != u);
 }
TEST() [38/41]
TEST (OptionalForPolymorphicObjectsTest , TestCompareToValue)
Definition at line 371 of file TestOptional.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> t(infra::InPlaceType<PolymorphicBool>(), true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> u;
     EXPECT_TRUE(t == true);
     EXPECT_TRUE(true == t);
     EXPECT_FALSE(t == false);
     EXPECT_FALSE(t != true);
     EXPECT_FALSE(true != t);
     EXPECT_FALSE(u == true);
 }
TEST() [39/41]
TEST (OptionalForPolymorphicObjectsTest , TestConstruct)
Definition at line 386 of file TestOptional.cpp.
References infra::OptionalForPolymorphicObjects< T, ExtraSize >::Emplace(), and EXPECT_TRUE().
 {
     PolymorphicBool b(true);
     infra::OptionalForPolymorphicObjects<PolymorphicBool, sizeof(void*)> o;
     o.Emplace<PolymorphicBool>(std::move(b));
     EXPECT_TRUE(static_cast<bool>(o));
     EXPECT_TRUE(*o);
 }
TEST() [40/41]
TEST (OptionalForPolymorphicObjectsTest , TestIndirect)
Definition at line 395 of file TestOptional.cpp.
References EXPECT_TRUE().
 {
     struct X
     {
         X()
             : x(true)
         {}
         virtual ~X() = default;
         bool x;
     };
     infra::OptionalForPolymorphicObjects<X, sizeof(void*)> o{ infra::InPlaceType<X>(), X() };
     EXPECT_TRUE(o->x);
     EXPECT_TRUE((const_cast<const infra::OptionalForPolymorphicObjects<X, sizeof(void*)>&>(o)->x));
 }
TEST() [41/41]
TEST (OptionalForPolymorphicObjectsTest , ConstructDescendant)
Definition at line 413 of file TestOptional.cpp.
References infra::OptionalForPolymorphicObjects< T, ExtraSize >::Emplace().
 {
     struct Base
     {
         virtual ~Base() = default;
     };
     struct Derived
         : Base
     {
         int ExtraStorage;
     };
     infra::OptionalForPolymorphicObjects<Base, sizeof(void*)> optionalBase((infra::InPlaceType<Derived>()));
     optionalBase.Emplace<Derived>();
 }