EMil: testing::Matcher< infra::BoundedStringBase< T > > Class Template Reference
testing::Matcher< infra::BoundedStringBase< T > > Class Template Reference
#include <BoundedStringMatcher.hpp>
Public Member Functions
Matcher ()=default
Matcher (const MatcherInterface< const infra::BoundedStringBase< T > &> *impl)
Matcher (const MatcherInterface< infra::BoundedStringBase< T >> *impl)
Matcher (infra::BoundedStringBase< T > s)
Matcher (const char *s)
Matcher ()=default
Matcher (const MatcherInterface< infra::BoundedStringBase< T >> *impl)
Matcher (infra::BoundedStringBase< T > s)
Matcher (const char *s)
Detailed Description
template<class T>
class testing::Matcher< infra::BoundedStringBase< T > >
Definition at line 10 of file BoundedStringMatcher.hpp.
Constructor & Destructor Documentation
Matcher() [1/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher () default
Matcher() [2/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (const MatcherInterface< const infra::BoundedStringBase< T > &> * impl) inline explicit
Definition at line 16 of file BoundedStringMatcher.hpp.
             : internal::MatcherBase<infra::BoundedStringBase<T>>(impl)
         {}
Matcher() [3/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (const MatcherInterface< infra::BoundedStringBase< T >> * impl) inline explicit
Definition at line 20 of file BoundedStringMatcher.hpp.
             : internal::MatcherBase<infra::BoundedStringBase<T>>(impl)
         {}
Matcher() [4/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (infra::BoundedStringBase< T > s) inline
Definition at line 24 of file BoundedStringMatcher.hpp.
References infra::BoundedStringBase< T >::data(), and infra::BoundedStringBase< T >::size().
 { *this = Eq(std::string(s.data(), s.size())); }
Matcher() [5/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (const char * s) inline
Definition at line 25 of file BoundedStringMatcher.hpp.
 { *this = Eq(std::string(s)); }
Matcher() [6/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher () default
Matcher() [7/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (const MatcherInterface< infra::BoundedStringBase< T >> * impl) inline explicit
Definition at line 16 of file OptionalMatcher.hpp.
             : internal::MatcherBase<infra::BoundedStringBase<T>>(impl)
         {}
Matcher() [8/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (infra::BoundedStringBase< T > s) inline
Definition at line 20 of file OptionalMatcher.hpp.
References infra::BoundedStringBase< T >::data(), and infra::BoundedStringBase< T >::size().
 { *this = Eq(std::string(s.data(), s.size())); }
Matcher() [9/9]
template<class T > testing::Matcher< infra::BoundedStringBase< T > >::Matcher (const char * s) inline
Definition at line 21 of file OptionalMatcher.hpp.
 { *this = Eq(std::string(s)); }
The documentation for this class was generated from the following files:
BoundedStringMatcher.hpp
OptionalMatcher.hpp