EMil: services::ConnectionSerial::StateInitSizeRequest Class Reference
services::ConnectionSerial::StateInitSizeRequest Class Reference
Public Member Functions
StateInitSizeRequest (ConnectionSerial &connection)
virtual void Reset () override
virtual void SizeRequestReceived () override
virtual void SizeResponseRequestReceived (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::StateInit
StateInit (ConnectionSerial &connection)
virtual void EvaluatePendingSend () override
virtual void SizeResponseReceived (size_t size) override
virtual size_t ContentReceived (infra::ConstByteRange receivedRange) override
virtual void SizeUpdateReceived (size_t size) override
virtual void AccumulateWindowUpdateSize (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::State
State (ConnectionSerial &connection)
virtual ~State ()=default
virtual void AckReceived ()
Private Member Functions
void SendWindowSizeRequest ()
Private Attributes
bool responseAfterSend = false
infra::TimerSingleShot windowRequestTimer
MessageHeader windowSizeReqMsg = MessageHeader(MessageType::SizeRequest)
Additional Inherited Members
Protected Attributes inherited from services::ConnectionSerial::StateInit
bool sendInProgress = false
bool resetAfterSend = false
bool responseRequestAfterSend = false
Protected Attributes inherited from services::ConnectionSerial::State
ConnectionSerial & connection
hal::SerialCommunication & serialCommunication
Detailed Description
Definition at line 149 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
StateInitSizeRequest()
services::ConnectionSerial::StateInitSizeRequest::StateInitSizeRequest (ConnectionSerial & connection)
Definition at line 366 of file ConnectionSerial.cpp.
References SendWindowSizeRequest().
         : StateInit(connection)
     {
         SendWindowSizeRequest();
     }
Member Function Documentation
Reset()
void services::ConnectionSerial::StateInitSizeRequest::Reset () override virtual
Reimplemented from services::ConnectionSerial::StateInit.
Definition at line 382 of file ConnectionSerial.cpp.
     {}
SendWindowSizeRequest()
void services::ConnectionSerial::StateInitSizeRequest::SendWindowSizeRequest () private
Definition at line 347 of file ConnectionSerial.cpp.
References hal::SerialCommunication::SendData(), and services::ConnectionSerial::serialCommunication.
Referenced by StateInitSizeRequest().
     {
         sendInProgress = true;
         serialCommunication.SendData(windowSizeReqMsg.Range(), [this]()
         {
             sendInProgress = false;
             if (!responseRequestAfterSend && !responseAfterSend)
                 windowRequestTimer.Start(std::chrono::seconds(1), [this]() { SendWindowSizeRequest(); });
             else if (responseRequestAfterSend)
                 connection.GoStateInitSizeResponseRequest();
             else
                 connection.GoStateInitSizeResponse();
         });
     }
SizeRequestReceived()
void services::ConnectionSerial::StateInitSizeRequest::SizeRequestReceived () override virtual
Implements services::ConnectionSerial::State.
Definition at line 385 of file ConnectionSerial.cpp.
     {
         if (sendInProgress)
             responseRequestAfterSend = true;
         else
             connection.GoStateInitSizeResponseRequest();
     }
SizeResponseRequestReceived()
void services::ConnectionSerial::StateInitSizeRequest::SizeResponseRequestReceived (size_t size) override virtual
Reimplemented from services::ConnectionSerial::StateInit.
Definition at line 372 of file ConnectionSerial.cpp.
     {
         connection.peerBufferSize = size;
         if (sendInProgress)
             responseAfterSend = true;
         else
             connection.GoStateInitSizeResponse();
     }
Member Data Documentation
responseAfterSend
bool services::ConnectionSerial::StateInitSizeRequest::responseAfterSend = false private
Definition at line 163 of file ConnectionSerial.hpp.
windowRequestTimer
infra::TimerSingleShot services::ConnectionSerial::StateInitSizeRequest::windowRequestTimer private
Definition at line 164 of file ConnectionSerial.hpp.
windowSizeReqMsg
MessageHeader services::ConnectionSerial::StateInitSizeRequest::windowSizeReqMsg = MessageHeader(MessageType::SizeRequest) private
Definition at line 165 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp