EMil: TestIntrusiveBinarySearchTree.cpp File Reference
TestIntrusiveBinarySearchTree.cpp File Reference
Classes
class IntrusiveBinarySearchTreeTest
Functions
TEST_F (IntrusiveBinarySearchTreeTest, ConstructEmptyTree)
TEST_F (IntrusiveBinarySearchTreeTest, MoveConstructEmptyTree)
TEST_F (IntrusiveBinarySearchTreeTest, MoveAssignEmptyTree)
TEST_F (IntrusiveBinarySearchTreeTest, InsertNode)
TEST_F (IntrusiveBinarySearchTreeTest, InsertSecondNodeLeft)
TEST_F (IntrusiveBinarySearchTreeTest, InsertSecondNodeRight)
TEST_F (IntrusiveBinarySearchTreeTest, InsertThirdNodeLeft)
TEST_F (IntrusiveBinarySearchTreeTest, InsertThirdNodeRight)
TEST_F (IntrusiveBinarySearchTreeTest, InsertThirdNodeLeftInBetween)
TEST_F (IntrusiveBinarySearchTreeTest, InsertThirdNodeRightInBetween)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveSingleNode)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveRootNodeWithLeftChild)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveRootNodeWithRightChild)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveRootNodeWithTwoChildren)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveRootNodeWithTwoChildrenAndGrandChildren)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootLeftLeafNode)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootRightLeafNode)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootLeftChildWithLeftGrandChild)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootLeftChildWithRightGrandChild)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootRightChildWithLeftGrandChild)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootRightChildWithRightGrandChild)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNodeWithTwoChildren)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNodeWithTwoChildrenAndGrandChildren)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNodeWithTwoChildrenAndMoreGrandChildren)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveNonRootNodeWithTwoChildrenAndMoreGrandChildren)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveFrontWithReplacementNotBeingTheNewFront)
TEST_F (IntrusiveBinarySearchTreeTest, RemoveBackWithReplacementNotBeingTheNewBack)
TEST_F (IntrusiveBinarySearchTreeTest, Accessors)
TEST_F (IntrusiveBinarySearchTreeTest, SwapEmptyWithEmpty)
TEST_F (IntrusiveBinarySearchTreeTest, SwapFilledWithEmpty)
TEST_F (IntrusiveBinarySearchTreeTest, SwapEmptyWithFilled)
TEST_F (IntrusiveBinarySearchTreeTest, SwapFilledWithFilled)
TEST_F (IntrusiveBinarySearchTreeTest, FindRootNode)
TEST_F (IntrusiveBinarySearchTreeTest, FindLeftNode)
TEST_F (IntrusiveBinarySearchTreeTest, FindRightNode)
TEST_F (IntrusiveBinarySearchTreeTest, DontFindNode)
TEST_F (IntrusiveBinarySearchTreeTest, RotateRootLeft)
TEST_F (IntrusiveBinarySearchTreeTest, RotateLeftChildLeft)
TEST_F (IntrusiveBinarySearchTreeTest, RotateRightChildLeft)
TEST_F (IntrusiveBinarySearchTreeTest, RotateRootRight)
TEST_F (IntrusiveBinarySearchTreeTest, RotateLeftChildRight)
TEST_F (IntrusiveBinarySearchTreeTest, RotateRightChildRight)
TEST_F (IntrusiveBinarySearchTreeTest, Sibling)
TEST_F (IntrusiveBinarySearchTreeTest, ParentChildReference)
TEST_F (IntrusiveBinarySearchTreeTest, TestManyInsertionsAndDeletions)
Function Documentation
TEST_F() [1/45]
TEST_F (IntrusiveBinarySearchTreeTest , ConstructEmptyTree)
Definition at line 79 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     EXPECT_TRUE(tree.invariant_holds());
     EXPECT_TRUE(tree.empty());
     EXPECT_EQ(0, tree.size());
     EXPECT_EQ(tree.begin(), tree.end());
     EXPECT_EQ(tree.rbegin(), tree.rend());
     EXPECT_EQ(tree.cbegin(), tree.cend());
     EXPECT_EQ(tree.crbegin(), tree.crend());
     EXPECT_EQ(tree.begin(), tree.cend());
     EXPECT_EQ(tree.rbegin(), tree.crend());
 }
TEST_F() [2/45]
TEST_F (IntrusiveBinarySearchTreeTest , MoveConstructEmptyTree)
Definition at line 92 of file TestIntrusiveBinarySearchTree.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::begin(), infra::IntrusiveBinarySearchTree< T, Compare >::cbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::cend(), infra::IntrusiveBinarySearchTree< T, Compare >::crbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::crend(), infra::IntrusiveBinarySearchTree< T, Compare >::empty(), infra::IntrusiveBinarySearchTree< T, Compare >::end(), EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), infra::IntrusiveBinarySearchTree< T, Compare >::rbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::rend(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
 {
     infra::IntrusiveBinarySearchTree<TestNode> moved(std::move(tree));
     EXPECT_TRUE(moved.invariant_holds());
     EXPECT_TRUE(moved.empty());
     EXPECT_EQ(0, moved.size());
     EXPECT_EQ(moved.begin(), moved.end());
     EXPECT_EQ(moved.rbegin(), moved.rend());
     EXPECT_EQ(moved.cbegin(), moved.cend());
     EXPECT_EQ(moved.crbegin(), moved.crend());
     EXPECT_EQ(moved.begin(), moved.cend());
     EXPECT_EQ(moved.rbegin(), moved.crend());
     EXPECT_TRUE(tree.invariant_holds());
     EXPECT_TRUE(tree.empty());
     EXPECT_EQ(0, tree.size());
     EXPECT_EQ(tree.begin(), tree.end());
     EXPECT_EQ(tree.rbegin(), tree.rend());
     EXPECT_EQ(tree.cbegin(), tree.cend());
     EXPECT_EQ(tree.crbegin(), tree.crend());
     EXPECT_EQ(tree.begin(), tree.cend());
     EXPECT_EQ(tree.rbegin(), tree.crend());
 }
TEST_F() [3/45]
TEST_F (IntrusiveBinarySearchTreeTest , MoveAssignEmptyTree)
Definition at line 117 of file TestIntrusiveBinarySearchTree.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::begin(), infra::IntrusiveBinarySearchTree< T, Compare >::cbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::cend(), infra::IntrusiveBinarySearchTree< T, Compare >::crbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::crend(), infra::IntrusiveBinarySearchTree< T, Compare >::empty(), infra::IntrusiveBinarySearchTree< T, Compare >::end(), EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), infra::IntrusiveBinarySearchTree< T, Compare >::rbegin(), infra::IntrusiveBinarySearchTree< T, Compare >::rend(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
 {
     infra::IntrusiveBinarySearchTree<TestNode> moved;
     moved = std::move(tree);
     EXPECT_TRUE(moved.invariant_holds());
     EXPECT_TRUE(moved.empty());
     EXPECT_EQ(0, moved.size());
     EXPECT_EQ(moved.begin(), moved.end());
     EXPECT_EQ(moved.rbegin(), moved.rend());
     EXPECT_EQ(moved.cbegin(), moved.cend());
     EXPECT_EQ(moved.crbegin(), moved.crend());
     EXPECT_EQ(moved.begin(), moved.cend());
     EXPECT_EQ(moved.rbegin(), moved.crend());
     EXPECT_TRUE(tree.invariant_holds());
     EXPECT_TRUE(tree.empty());
     EXPECT_EQ(0, tree.size());
     EXPECT_EQ(tree.begin(), tree.end());
     EXPECT_EQ(tree.rbegin(), tree.rend());
     EXPECT_EQ(tree.cbegin(), tree.cend());
     EXPECT_EQ(tree.crbegin(), tree.crend());
     EXPECT_EQ(tree.begin(), tree.cend());
     EXPECT_EQ(tree.rbegin(), tree.crend());
 }
TEST_F() [4/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertNode)
Definition at line 143 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     tree.insert_in_tree(node0);
     EXPECT_FALSE(tree.empty());
     EXPECT_EQ(1, tree.size());
     EXPECT_EQ("0", Representation(tree));
 }
TEST_F() [5/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertSecondNodeLeft)
Definition at line 152 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     EXPECT_EQ("1(0,)", Representation(tree));
 }
TEST_F() [6/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertSecondNodeRight)
Definition at line 161 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node2);
     EXPECT_EQ("1(,2)", Representation(tree));
 }
TEST_F() [7/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertThirdNodeLeft)
Definition at line 169 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node0);
     EXPECT_EQ("1(0,2)", Representation(tree));
 }
TEST_F() [8/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertThirdNodeRight)
Definition at line 178 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     EXPECT_EQ("1(0,2)", Representation(tree));
 }
TEST_F() [9/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertThirdNodeLeftInBetween)
Definition at line 187 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node1);
     EXPECT_EQ("2(0(,1),)", Representation(tree));
 }
TEST_F() [10/45]
TEST_F (IntrusiveBinarySearchTreeTest , InsertThirdNodeRightInBetween)
Definition at line 196 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     EXPECT_EQ("0(,2(1,))", Representation(tree));
 }
TEST_F() [11/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveSingleNode)
Definition at line 205 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     ASSERT_EQ("0", Representation(tree));
     EXPECT_EQ(std::make_tuple(nullptr, nullptr, nullptr), tree.remove_from_tree(node0));
     EXPECT_EQ("", Representation(tree));
 }
TEST_F() [12/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveRootNodeWithLeftChild)
Definition at line 214 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     ASSERT_EQ("2(1,)", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node1, &node2, &node2.left), tree.remove_from_tree(node2));
     EXPECT_EQ("1", Representation(tree));
 }
TEST_F() [13/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveRootNodeWithRightChild)
Definition at line 224 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node1);
     ASSERT_EQ("0(,1)", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node1, &node0, &node0.right), tree.remove_from_tree(node0));
     EXPECT_EQ("1", Representation(tree));
 }
TEST_F() [14/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveRootNodeWithTwoChildren)
Definition at line 234 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     ASSERT_EQ("1(0,2)", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node2, &node1, &node1.right), tree.remove_from_tree(node1));
     EXPECT_EQ("2(0,)", Representation(tree));
 }
TEST_F() [15/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveRootNodeWithTwoChildrenAndGrandChildren)
Definition at line 245 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node2);
     ASSERT_EQ("1(0,3(2,))", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node2, &node3, &node3.left), tree.remove_from_tree(node1));
     EXPECT_EQ("2(0,3)", Representation(tree));
 }
TEST_F() [16/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootLeftLeafNode)
Definition at line 257 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     ASSERT_EQ("1(0,)", Representation(tree));
     EXPECT_EQ(std::make_tuple(nullptr, &node0, &node1.left), tree.remove_from_tree(node0));
     EXPECT_EQ("1", Representation(tree));
 }
TEST_F() [17/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootRightLeafNode)
Definition at line 267 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node2);
     ASSERT_EQ("1(,2)", Representation(tree));
     EXPECT_EQ(std::make_tuple(nullptr, &node2, &node1.right), tree.remove_from_tree(node2));
     EXPECT_EQ("1", Representation(tree));
 }
TEST_F() [18/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootLeftChildWithLeftGrandChild)
Definition at line 277 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     ASSERT_EQ("2(1(0,),)", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node0, &node1, &node1.left), tree.remove_from_tree(node1));
     EXPECT_EQ("2(0,)", Representation(tree));
 }
TEST_F() [19/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootLeftChildWithRightGrandChild)
Definition at line 288 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node1);
     ASSERT_EQ("2(0(,1),)", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node1, &node0, &node0.right), tree.remove_from_tree(node0));
     EXPECT_EQ("2(1,)", Representation(tree));
 }
TEST_F() [20/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootRightChildWithLeftGrandChild)
Definition at line 299 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     ASSERT_EQ("0(,2(1,))", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node1, &node2, &node2.left), tree.remove_from_tree(node2));
     EXPECT_EQ("0(,1)", Representation(tree));
 }
TEST_F() [21/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootRightChildWithRightGrandChild)
Definition at line 310 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node2);
     ASSERT_EQ("0(,1(,2))", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node2, &node1, &node1.right), tree.remove_from_tree(node1));
     EXPECT_EQ("0(,2)", Representation(tree));
 }
TEST_F() [22/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNodeWithTwoChildren)
Definition at line 321 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node4);
     ASSERT_EQ("1(0,3(2,4))", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node4, &node3, &node3.right), tree.remove_from_tree(node3));
     EXPECT_EQ("1(0,4(2,))", Representation(tree));
 }
TEST_F() [23/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNodeWithTwoChildrenAndGrandChildren)
Definition at line 334 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node2);
     ASSERT_EQ("1(0,3(2,))", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node2, &node3, &node3.left), tree.remove_from_tree(node1));
     EXPECT_EQ("2(0,3)", Representation(tree));
 }
TEST_F() [24/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNodeWithTwoChildrenAndMoreGrandChildren)
Definition at line 346 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node4);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node3);
     ASSERT_EQ("1(0,4(2(,3),))", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node2, &node4, &node4.left), tree.remove_from_tree(node1));
     EXPECT_EQ("2(0,4(3,))", Representation(tree));
 }
TEST_F() [25/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveNonRootNodeWithTwoChildrenAndMoreGrandChildren)
Definition at line 359 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node5);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node4);
     ASSERT_EQ("5(1(0,3(2,4)),)", Representation(tree));
     EXPECT_EQ(std::make_tuple(&node2, &node3, &node3.left), tree.remove_from_tree(node1));
     EXPECT_EQ("5(2(0,3(,4)),)", Representation(tree));
 }
TEST_F() [26/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveFrontWithReplacementNotBeingTheNewFront)
Definition at line 373 of file TestIntrusiveBinarySearchTree.cpp.
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     ASSERT_EQ("0(,2(1,))", Representation(tree));
     tree.remove_from_tree(node0);
 }
TEST_F() [27/45]
TEST_F (IntrusiveBinarySearchTreeTest , RemoveBackWithReplacementNotBeingTheNewBack)
Definition at line 383 of file TestIntrusiveBinarySearchTree.cpp.
 {
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node1);
     ASSERT_EQ("2(0(,1),)", Representation(tree));
     tree.remove_from_tree(node2);
 }
TEST_F() [28/45]
TEST_F (IntrusiveBinarySearchTreeTest , Accessors)
Definition at line 393 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     EXPECT_EQ(&node1, &tree.root());
     EXPECT_EQ(&node0, &tree.front());
     EXPECT_EQ(&node2, &tree.back());
 }
TEST_F() [29/45]
TEST_F (IntrusiveBinarySearchTreeTest , SwapEmptyWithEmpty)
Definition at line 404 of file TestIntrusiveBinarySearchTree.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), and infra::swap().
 {
     infra::IntrusiveBinarySearchTree<TestNode> other;
     swap(tree, other);
     EXPECT_TRUE(tree.empty());
     EXPECT_TRUE(other.empty());
     EXPECT_TRUE(other.invariant_holds());
 }
TEST_F() [30/45]
TEST_F (IntrusiveBinarySearchTreeTest , SwapFilledWithEmpty)
Definition at line 415 of file TestIntrusiveBinarySearchTree.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::insert_in_tree(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), infra::IntrusiveBinarySearchTree< T, Compare >::root(), infra::IntrusiveBinarySearchTree< T, Compare >::size(), and infra::swap().
 {
     infra::IntrusiveBinarySearchTree<TestNode> other;
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     swap(tree, other);
     EXPECT_TRUE(tree.empty());
     EXPECT_FALSE(other.empty());
     EXPECT_EQ(3, other.size());
     EXPECT_EQ(&node1, &other.root());
     EXPECT_TRUE(other.invariant_holds());
 }
TEST_F() [31/45]
TEST_F (IntrusiveBinarySearchTreeTest , SwapEmptyWithFilled)
Definition at line 431 of file TestIntrusiveBinarySearchTree.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::insert_in_tree(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), and infra::swap().
 {
     infra::IntrusiveBinarySearchTree<TestNode> other;
     other.insert_in_tree(node1);
     other.insert_in_tree(node0);
     other.insert_in_tree(node2);
     swap(tree, other);
     EXPECT_FALSE(tree.empty());
     EXPECT_TRUE(other.empty());
     EXPECT_EQ(3, tree.size());
     EXPECT_EQ(&node1, &tree.root());
     EXPECT_TRUE(other.invariant_holds());
 }
TEST_F() [32/45]
TEST_F (IntrusiveBinarySearchTreeTest , SwapFilledWithFilled)
Definition at line 447 of file TestIntrusiveBinarySearchTree.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::insert_in_tree(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), infra::IntrusiveBinarySearchTree< T, Compare >::root(), infra::IntrusiveBinarySearchTree< T, Compare >::size(), and infra::swap().
 {
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node4);
     infra::IntrusiveBinarySearchTree<TestNode> other;
     other.insert_in_tree(node1);
     other.insert_in_tree(node0);
     other.insert_in_tree(node2);
     swap(tree, other);
     EXPECT_FALSE(tree.empty());
     EXPECT_EQ(3, tree.size());
     EXPECT_EQ(&node1, &tree.root());
     EXPECT_FALSE(other.empty());
     EXPECT_EQ(2, other.size());
     EXPECT_EQ(&node3, &other.root());
     EXPECT_TRUE(other.invariant_holds());
 }
TEST_F() [33/45]
TEST_F (IntrusiveBinarySearchTreeTest , FindRootNode)
Definition at line 467 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     EXPECT_EQ(0, tree.find(node0)->value);
 }
TEST_F() [34/45]
TEST_F (IntrusiveBinarySearchTreeTest , FindLeftNode)
Definition at line 476 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     EXPECT_EQ(1, tree.find(node1)->value);
 }
TEST_F() [35/45]
TEST_F (IntrusiveBinarySearchTreeTest , FindRightNode)
Definition at line 485 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     EXPECT_EQ(2, tree.find(node2)->value);
 }
TEST_F() [36/45]
TEST_F (IntrusiveBinarySearchTreeTest , DontFindNode)
Definition at line 494 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     EXPECT_EQ(tree.end(), tree.find(node3));
 }
TEST_F() [37/45]
TEST_F (IntrusiveBinarySearchTreeTest , RotateRootLeft)
Definition at line 503 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node4);
     ASSERT_EQ("1(0,3(2,4))", Representation(tree));
     tree.left_rotate(node1);
     EXPECT_EQ("3(1(0,2),4)", Representation(tree));
 }
TEST_F() [38/45]
TEST_F (IntrusiveBinarySearchTreeTest , RotateLeftChildLeft)
Definition at line 516 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node5);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node4);
     ASSERT_EQ("5(1(0,3(2,4)),)", Representation(tree));
     tree.left_rotate(node1);
     EXPECT_EQ("5(3(1(0,2),4),)", Representation(tree));
 }
TEST_F() [39/45]
TEST_F (IntrusiveBinarySearchTreeTest , RotateRightChildLeft)
Definition at line 530 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node4);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node5);
     ASSERT_EQ("0(,2(1,4(3,5)))", Representation(tree));
     tree.left_rotate(node2);
     EXPECT_EQ("0(,4(2(1,3),5))", Representation(tree));
 }
TEST_F() [40/45]
TEST_F (IntrusiveBinarySearchTreeTest , RotateRootRight)
Definition at line 544 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node4);
     ASSERT_EQ("3(1(0,2),4)", Representation(tree));
     tree.right_rotate(node3);
     EXPECT_EQ("1(0,3(2,4))", Representation(tree));
 }
TEST_F() [41/45]
TEST_F (IntrusiveBinarySearchTreeTest , RotateLeftChildRight)
Definition at line 557 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node5);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node4);
     EXPECT_EQ("5(3(1(0,2),4),)", Representation(tree));
     tree.right_rotate(node3);
     ASSERT_EQ("5(1(0,3(2,4)),)", Representation(tree));
 }
TEST_F() [42/45]
TEST_F (IntrusiveBinarySearchTreeTest , RotateRightChildRight)
Definition at line 571 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node4);
     tree.insert_in_tree(node2);
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node3);
     tree.insert_in_tree(node5);
     ASSERT_EQ("0(,4(2(1,3),5))", Representation(tree));
     tree.right_rotate(node4);
     EXPECT_EQ("0(,2(1,4(3,5)))", Representation(tree));
 }
TEST_F() [43/45]
TEST_F (IntrusiveBinarySearchTreeTest , Sibling)
Definition at line 585 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     ASSERT_EQ("1(0,2)", Representation(tree));
     EXPECT_EQ(&node0, tree.sibling(node2));
     EXPECT_EQ(&node2, tree.sibling(node0));
 }
TEST_F() [44/45]
TEST_F (IntrusiveBinarySearchTreeTest , ParentChildReference)
Definition at line 596 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_EQ().
 {
     tree.insert_in_tree(node1);
     tree.insert_in_tree(node0);
     tree.insert_in_tree(node2);
     ASSERT_EQ("1(0,2)", Representation(tree));
     EXPECT_EQ(&node1.left, &tree.parent_child_reference(node1, node0));
     EXPECT_EQ(&node1.right, &tree.parent_child_reference(node1, node2));
 }
TEST_F() [45/45]
TEST_F (IntrusiveBinarySearchTreeTest , TestManyInsertionsAndDeletions)
Definition at line 607 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_TRUE(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
 {
     for (int size = 1; size != 20; ++size)
     {
         for (int step = 3; step != 6; ++step)
         {
             std::vector<TestNode> elements;
             int n = 0;
             std::generate_n(std::back_inserter(elements), size, [&n]() { return n++; });
             std::vector<std::size_t> indices;
             n = 0;
             std::generate_n(std::back_inserter(indices), size, [&n]() { return n++; });
             infra::IntrusiveBinarySearchTree<TestNode> tree;
             int current = 0;
             while (!indices.empty())
             {
                 current = (current + step) % indices.size();
                 tree.insert_in_tree(elements[indices[current]]);
                 EXPECT_TRUE(tree.invariant_holds());
                 indices.erase(indices.begin() + current);
             }
             while (!tree.empty())
             {
                 current = (current + step) % tree.size();
                 tree.remove_from_tree(*std::next(tree.begin(), current));
                 EXPECT_TRUE(tree.invariant_holds());
             }
         }
     }
 }