EMil: services::ConnectionLoopBack Class Reference
services::ConnectionLoopBack Class Reference
#include <ConnectionLoopBack.hpp>
Public Member Functions
ConnectionLoopBack ()
Connection & Server ()
Connection & Client ()
void Connect (infra::SharedPtr< services::ConnectionObserver > serverObserver, infra::SharedPtr< services::ConnectionObserver > clientObserver)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionLoopBack >
SharedPtr< ConnectionLoopBack > SharedFromThis ()
SharedPtr< const ConnectionLoopBack > SharedFromThis () const
WeakPtr< ConnectionLoopBack > WeakFromThis ()
WeakPtr< const ConnectionLoopBack > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionLoopBack > sharedPtr)
Private Attributes
ConnectionLoopBackPeer server
ConnectionLoopBackPeer client
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectionLoopBack >
using EnableSharedFromThisType = ConnectionLoopBack
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionLoopBack >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 68 of file ConnectionLoopBack.hpp.
Constructor & Destructor Documentation
ConnectionLoopBack()
services::ConnectionLoopBack::ConnectionLoopBack ()
Definition at line 106 of file ConnectionLoopBack.cpp.
         : server(client, *this)
         , client(server, *this)
     {}
Member Function Documentation
Client()
Connection & services::ConnectionLoopBack::Client ()
Definition at line 116 of file ConnectionLoopBack.cpp.
References client.
Referenced by Connect().
     {
         return client;
     }
Connect()
void services::ConnectionLoopBack::Connect (infra::SharedPtr< services::ConnectionObserver > serverObserver, infra::SharedPtr< services::ConnectionObserver > clientObserver)
Definition at line 121 of file ConnectionLoopBack.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), Client(), infra::Subject< ObserverType_, Helper >::GetObserver(), Server(), services::Connection::SetOwnership(), and infra::EnableSharedFromThis< ConnectionLoopBack >::SharedFromThis().
     {
         serverObserver->Attach(Server());
         Server().SetOwnership(SharedFromThis(), serverObserver);
         clientObserver->Attach(Client());
         Client().SetOwnership(SharedFromThis(), clientObserver);
         Client().GetObserver().Connected();
         Server().GetObserver().Connected();
     }
Server()
Connection & services::ConnectionLoopBack::Server ()
Definition at line 111 of file ConnectionLoopBack.cpp.
References server.
Referenced by Connect().
     {
         return server;
     }
Member Data Documentation
client
ConnectionLoopBackPeer services::ConnectionLoopBack::client private
Definition at line 81 of file ConnectionLoopBack.hpp.
Referenced by Client().
server
ConnectionLoopBackPeer services::ConnectionLoopBack::server private
Definition at line 80 of file ConnectionLoopBack.hpp.
Referenced by Server().
The documentation for this class was generated from the following files:
ConnectionLoopBack.hpp
ConnectionLoopBack.cpp