EMil: infra::QueueForOneReaderOneIrqWriter< T > Class Template Reference
infra::QueueForOneReaderOneIrqWriter< T > Class Template Reference
#include <QueueForOneReaderOneIrqWriter.hpp>
Public Types
template<std::size_t Size>
using WithStorage = infra::WithStorage< QueueForOneReaderOneIrqWriter< T >, std::array< T, Size+1 > >
Public Member Functions
QueueForOneReaderOneIrqWriter (const infra::MemoryRange< T > buffer, const infra::Function< void()> &onDataAvailable)
void AddFromInterrupt (T element)
void AddFromInterrupt (infra::MemoryRange< const T > data)
bool Empty () const
bool Full () const
T Get ()
infra::MemoryRange< const T > ContiguousRange (uint32_t offset=0) const
void Consume (uint32_t amount)
std::size_t Size () const
std::size_t EmptySize () const
T operator[] (size_t position) const
Private Member Functions
bool Full (const T *begin, const T *end) const
void NotifyDataAvailable ()
void DataAvailable ()
Private Attributes
const infra::MemoryRange< T > buffer
std::atomic< T * > contentsBegin
std::atomic< T * > contentsEnd
infra::Function< void()> onDataAvailable
std::atomic_bool notificationScheduled
Detailed Description
template<class T>
class infra::QueueForOneReaderOneIrqWriter< T >
Definition at line 15 of file QueueForOneReaderOneIrqWriter.hpp.
Member Typedef Documentation
WithStorage
template<class T> template<std::size_t Size> using infra::QueueForOneReaderOneIrqWriter< T >::WithStorage = infra::WithStorage<QueueForOneReaderOneIrqWriter<T>, std::array<T, Size + 1> >
Definition at line 19 of file QueueForOneReaderOneIrqWriter.hpp.
Constructor & Destructor Documentation
QueueForOneReaderOneIrqWriter()
template<class T> infra::QueueForOneReaderOneIrqWriter< T >::QueueForOneReaderOneIrqWriter (const infra::MemoryRange< T > buffer, const infra::Function< void()> & onDataAvailable)
Definition at line 53 of file QueueForOneReaderOneIrqWriter.hpp.
         : buffer(buffer)
         , contentsBegin(buffer.begin())
         , contentsEnd(buffer.begin())
         , onDataAvailable(onDataAvailable)
     {
         static_assert(std::is_trivial<T>::value, "Trivial type required");
         notificationScheduled = false;
     }
Member Function Documentation
AddFromInterrupt() [1/2]
template<class T> void infra::QueueForOneReaderOneIrqWriter< T >::AddFromInterrupt (T element)
Definition at line 64 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         assert(!Full());
         *contentsEnd = element;
         if (contentsEnd == buffer.end() - 1)
             contentsEnd = buffer.begin();
         else
             ++contentsEnd;
         NotifyDataAvailable();
     }
AddFromInterrupt() [2/2]
template<class T> void infra::QueueForOneReaderOneIrqWriter< T >::AddFromInterrupt (infra::MemoryRange< const T > data)
Definition at line 78 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         std::size_t copySize = std::min<std::size_t>(data.size(), buffer.end() - contentsEnd);
         T* begin = contentsBegin.load();
         if (!(begin <= contentsEnd.load() || begin > contentsEnd.load() + copySize))
             return;
         std::copy(data.begin(), data.begin() + copySize, contentsEnd.load());
         if (contentsEnd == buffer.end() - copySize)
             contentsEnd = buffer.begin();
         else
             contentsEnd += copySize;
         data.pop_front(copySize);
         assert(begin <= contentsEnd.load() || begin > contentsEnd.load() + data.size());
         std::copy(data.begin(), data.end(), contentsEnd.load());
         contentsEnd += data.size();
         NotifyDataAvailable();
     }
Consume()
template<class T > void infra::QueueForOneReaderOneIrqWriter< T >::Consume (uint32_t amount)
Definition at line 177 of file QueueForOneReaderOneIrqWriter.hpp.
Referenced by services::ConnectionSerial::DataReceived(), and services::ConnectionSerial::TryConstructHeader().
     {
         if (contentsBegin + amount >= buffer.end())
         {
             amount -= buffer.end() - contentsBegin;
             contentsBegin = buffer.begin();
         }
         contentsBegin += amount;
     }
ContiguousRange()
template<class T > infra::MemoryRange< const T > infra::QueueForOneReaderOneIrqWriter< T >::ContiguousRange (uint32_t offset = 0) const
Definition at line 157 of file QueueForOneReaderOneIrqWriter.hpp.
Referenced by services::ConnectionSerial::DataReceived().
     {
         const T* end = contentsEnd.load();
         T* begin = contentsBegin;
         if (begin + offset >= buffer.end())
         {
             offset -= buffer.end() - begin;
             begin = buffer.begin();
         }
         begin += offset;
         if (end < begin)
             return infra::MemoryRange<const T>(begin, buffer.end());
         else
             return infra::MemoryRange<const T>(begin, end);
     }
DataAvailable()
template<class T > void infra::QueueForOneReaderOneIrqWriter< T >::DataAvailable () private
Definition at line 216 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         notificationScheduled = false;
         onDataAvailable();
     }
Empty()
template<class T > bool infra::QueueForOneReaderOneIrqWriter< T >::Empty () const
Definition at line 102 of file QueueForOneReaderOneIrqWriter.hpp.
Referenced by services::ConnectionSerial::DataReceived(), services::Terminal::HandleInput(), and services::ConnectionSerial::TryConstructHeader().
     {
         return contentsBegin.load() == contentsEnd.load();
     }
EmptySize()
template<class T > std::size_t infra::QueueForOneReaderOneIrqWriter< T >::EmptySize () const
Definition at line 203 of file QueueForOneReaderOneIrqWriter.hpp.
Referenced by services::ConnectionSerial::ReceiveBufferSize().
     {
         return buffer.size() - 1;
     }
Full() [1/2]
template<class T > bool infra::QueueForOneReaderOneIrqWriter< T >::Full () const
Definition at line 108 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         const T* begin = contentsBegin.load();
         const T* end = contentsEnd.load();
         return Full(begin, end);
     }
Full() [2/2]
template<class T> bool infra::QueueForOneReaderOneIrqWriter< T >::Full (const T * begin, const T * end) const private
Definition at line 117 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         return (end == buffer.end() - 1 || begin == end + 1)
             && (end != buffer.end() - 1 || begin == buffer.begin());
     }
Get()
template<class T > T infra::QueueForOneReaderOneIrqWriter< T >::Get ()
Definition at line 124 of file QueueForOneReaderOneIrqWriter.hpp.
Referenced by services::Terminal::HandleInput().
     {
         assert(!Empty());
         T result = *contentsBegin;
         if (contentsBegin == buffer.end() - 1)
             contentsBegin = buffer.begin();
         else
             ++contentsBegin;
         return result;
     }
NotifyDataAvailable()
template<class T > void infra::QueueForOneReaderOneIrqWriter< T >::NotifyDataAvailable () private
Definition at line 209 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         if (!Empty() && !notificationScheduled.exchange(true))
             infra::EventDispatcher::Instance().Schedule([this]() { DataAvailable(); });
     }
operator[]()
template<class T > T infra::QueueForOneReaderOneIrqWriter< T >::operator[] (size_t position) const
Definition at line 138 of file QueueForOneReaderOneIrqWriter.hpp.
     {
         size_t size = Size();
         assert(size > 0);
         assert(position < size);
         T* begin = contentsBegin;
         if (begin + position >= buffer.end())
         {
             position -= buffer.end() - begin;
             begin = buffer.begin();
         }
         begin += position;
         return *begin;
     }
Size()
template<class T > std::size_t infra::QueueForOneReaderOneIrqWriter< T >::Size () const
Definition at line 189 of file QueueForOneReaderOneIrqWriter.hpp.
Referenced by services::ConnectionSerial::DataReceived().
     {
         const T* begin = contentsBegin.load();
         const T* end = contentsEnd.load();
         if (Full(begin, end))
             return EmptySize();
         else if (end >= begin)
             return end - begin;
         return (buffer.end() - begin) + (end - buffer.begin());
     }
Member Data Documentation
buffer
template<class T> const infra::MemoryRange<T> infra::QueueForOneReaderOneIrqWriter< T >::buffer private
Definition at line 42 of file QueueForOneReaderOneIrqWriter.hpp.
contentsBegin
template<class T> std::atomic<T*> infra::QueueForOneReaderOneIrqWriter< T >::contentsBegin private
Definition at line 43 of file QueueForOneReaderOneIrqWriter.hpp.
contentsEnd
template<class T> std::atomic<T*> infra::QueueForOneReaderOneIrqWriter< T >::contentsEnd private
Definition at line 44 of file QueueForOneReaderOneIrqWriter.hpp.
notificationScheduled
template<class T> std::atomic_bool infra::QueueForOneReaderOneIrqWriter< T >::notificationScheduled private
Definition at line 47 of file QueueForOneReaderOneIrqWriter.hpp.
onDataAvailable
template<class T> infra::Function<void()> infra::QueueForOneReaderOneIrqWriter< T >::onDataAvailable private
Definition at line 46 of file QueueForOneReaderOneIrqWriter.hpp.
The documentation for this class was generated from the following file:
QueueForOneReaderOneIrqWriter.hpp