EMil: infra::BoundedDeque< T > Class Template Reference
infra::BoundedDeque< T > Class Template Reference
#include <BoundedDeque.hpp>
Public Types
template<std::size_t Max>
using WithMaxSize = infra::WithStorage< BoundedDeque< T >, std::array< StaticStorage< T >, Max > >
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef detail::BoundedDequeIterator< BoundedDeque< T >, T > iterator
typedef detail::BoundedDequeIterator< const BoundedDeque< T >, const T > const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
BoundedDeque ()=default
BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage)
BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, size_type n, const value_type &value=value_type())
template<class InputIterator >
BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, InputIterator first, InputIterator last)
BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, const BoundedDeque &other)
BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, BoundedDeque &&other)
BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, std::initializer_list< T > initializerList)
BoundedDeque & operator= (const BoundedDeque &other)
BoundedDeque & operator= (BoundedDeque &&other)
BoundedDeque & operator= (std::initializer_list< T > initializerList)
void AssignFromStorage (const BoundedDeque &other)
void AssignFromStorage (BoundedDeque &&other)
~BoundedDeque ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
size_type size () const
size_type max_size () const
void resize (size_type n, const value_type &value=value_type())
bool empty () const
bool full () const
infra::MemoryRange< T > contiguous_range (const_iterator from)
infra::MemoryRange< const T > contiguous_range (const_iterator from) const
value_type & operator[] (size_type position)
const value_type & operator[] (size_type position) const
value_type & front ()
const value_type & front () const
value_type & back ()
const value_type & back () const
template<class InputIterator >
void assign (InputIterator first, const InputIterator &last)
void assign (size_type n, const value_type &value)
void assign (std::initializer_list< T > initializerList)
void push_front (const value_type &value)
void push_front (value_type &&value)
void pop_front ()
void push_back (const value_type &value)
void push_back (value_type &&value)
void pop_back ()
iterator insert (const const_iterator &position, const value_type &value)
iterator insert (const const_iterator &position, size_type n, const value_type &value)
template<class InputIterator >
iterator insert (const const_iterator &position, InputIterator first, const InputIterator &last)
iterator insert (const const_iterator &position, T &&val)
iterator insert (const const_iterator &position, std::initializer_list< T > initializerList)
iterator erase (const const_iterator &position)
iterator erase (const const_iterator &first, const const_iterator &last)
void swap (BoundedDeque &other)
void clear ()
template<class... Args>
iterator emplace (const const_iterator &position, Args &&... args)
template<class... Args>
void emplace_front (Args &&... args)
template<class... Args>
void emplace_back (Args &&... args)
bool operator== (const BoundedDeque &other) const
bool operator!= (const BoundedDeque &other) const
bool operator< (const BoundedDeque &other) const
bool operator<= (const BoundedDeque &other) const
bool operator> (const BoundedDeque &other) const
bool operator>= (const BoundedDeque &other) const
template<class RandomAccessIterator >
BoundedDeque< T >::iterator insert (const const_iterator &position, RandomAccessIterator first, const RandomAccessIterator &last)
Private Member Functions
size_type index (size_type i) const
void move_up (size_type position, size_type n)
Private Attributes
infra::MemoryRange< StaticStorage< T > > storage
size_type numAllocated = 0
size_type start = 0
Detailed Description
template<class T>
class infra::BoundedDeque< T >
Definition at line 23 of file BoundedDeque.hpp.
Member Typedef Documentation
const_iterator
template<class T> typedef detail::BoundedDequeIterator<const BoundedDeque<T>, const T> infra::BoundedDeque< T >::const_iterator
Definition at line 35 of file BoundedDeque.hpp.
const_pointer
template<class T> typedef const T* infra::BoundedDeque< T >::const_pointer
Definition at line 33 of file BoundedDeque.hpp.
const_reference
template<class T> typedef const T& infra::BoundedDeque< T >::const_reference
Definition at line 31 of file BoundedDeque.hpp.
const_reverse_iterator
template<class T> typedef std::reverse_iterator<const_iterator> infra::BoundedDeque< T >::const_reverse_iterator
Definition at line 37 of file BoundedDeque.hpp.
difference_type
template<class T> typedef std::iterator_traits<iterator>::difference_type infra::BoundedDeque< T >::difference_type
Definition at line 38 of file BoundedDeque.hpp.
iterator
template<class T> typedef detail::BoundedDequeIterator<BoundedDeque<T>, T> infra::BoundedDeque< T >::iterator
Definition at line 34 of file BoundedDeque.hpp.
pointer
template<class T> typedef T* infra::BoundedDeque< T >::pointer
Definition at line 32 of file BoundedDeque.hpp.
reference
template<class T> typedef T& infra::BoundedDeque< T >::reference
Definition at line 30 of file BoundedDeque.hpp.
reverse_iterator
template<class T> typedef std::reverse_iterator<iterator> infra::BoundedDeque< T >::reverse_iterator
Definition at line 36 of file BoundedDeque.hpp.
size_type
template<class T> typedef std::size_t infra::BoundedDeque< T >::size_type
Definition at line 39 of file BoundedDeque.hpp.
value_type
template<class T> typedef T infra::BoundedDeque< T >::value_type
Definition at line 29 of file BoundedDeque.hpp.
WithMaxSize
template<class T> template<std::size_t Max> using infra::BoundedDeque< T >::WithMaxSize = infra::WithStorage<BoundedDeque<T>, std::array<StaticStorage<T>, Max> >
Definition at line 27 of file BoundedDeque.hpp.
Constructor & Destructor Documentation
BoundedDeque() [1/7]
template<class T> infra::BoundedDeque< T >::BoundedDeque () default
BoundedDeque() [2/7]
template<class T> infra::BoundedDeque< T >::BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage) explicit
Definition at line 200 of file BoundedDeque.hpp.
         : storage(storage)
     {}
BoundedDeque() [3/7]
template<class T> infra::BoundedDeque< T >::BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, size_type n, const value_type & value = value_type())
Definition at line 205 of file BoundedDeque.hpp.
         : storage(storage)
     {
         resize(n, value);
     }
BoundedDeque() [4/7]
template<class T> template<class InputIterator > infra::BoundedDeque< T >::BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, InputIterator first, InputIterator last)
Definition at line 213 of file BoundedDeque.hpp.
         : storage(storage)
     {
         assign(first, last);
     }
BoundedDeque() [5/7]
template<class T> infra::BoundedDeque< T >::BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, const BoundedDeque< T > & other)
Definition at line 220 of file BoundedDeque.hpp.
         : storage(storage)
     {
         assign(other.begin(), other.end());
     }
BoundedDeque() [6/7]
template<class T> infra::BoundedDeque< T >::BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, BoundedDeque< T > && other)
Definition at line 227 of file BoundedDeque.hpp.
         : storage(storage)
         , numAllocated(other.numAllocated)
     {
         for (size_type i = 0; i != size(); ++i)
             storage[i].Construct(std::move(other[i]));
     }
BoundedDeque() [7/7]
template<class T> infra::BoundedDeque< T >::BoundedDeque (infra::MemoryRange< infra::StaticStorage< T >> storage, std::initializer_list< T > initializerList)
Definition at line 236 of file BoundedDeque.hpp.
         : storage(storage)
     {
         assign(initializerList.begin(), initializerList.end());
     }
~BoundedDeque()
template<class T > infra::BoundedDeque< T >::~BoundedDeque ()
Definition at line 285 of file BoundedDeque.hpp.
     {
         clear();
     }
Member Function Documentation
assign() [1/3]
template<class T > template<class InputIterator > void infra::BoundedDeque< T >::assign (InputIterator first, const InputIterator & last)
Definition at line 464 of file BoundedDeque.hpp.
     {
         clear();
         for (; first != last; ++first)
             push_back(*first);
     }
assign() [2/3]
template<class T > void infra::BoundedDeque< T >::assign (size_type n, const value_type & value)
Definition at line 473 of file BoundedDeque.hpp.
     {
         clear();
         for (size_type i = 0; i != n; ++i)
             push_back(value);
     }
assign() [3/3]
template<class T> void infra::BoundedDeque< T >::assign (std::initializer_list< T > initializerList)
Definition at line 482 of file BoundedDeque.hpp.
     {
         assign(initializerList.begin(), initializerList.end());
     }
AssignFromStorage() [1/2]
template<class T > void infra::BoundedDeque< T >::AssignFromStorage (const BoundedDeque< T > & other)
Definition at line 273 of file BoundedDeque.hpp.
     {
         *this = other;
     }
AssignFromStorage() [2/2]
template<class T > void infra::BoundedDeque< T >::AssignFromStorage (BoundedDeque< T > && other)
Definition at line 279 of file BoundedDeque.hpp.
     {
         *this = std::move(other);
     }
back() [1/2]
template<class T > BoundedDeque< T >::value_type & infra::BoundedDeque< T >::back ()
Definition at line 449 of file BoundedDeque.hpp.
     {
         really_assert(!empty());
         return *storage[index(numAllocated - 1)];
     }
back() [2/2]
template<class T > const BoundedDeque< T >::value_type & infra::BoundedDeque< T >::back () const
Definition at line 456 of file BoundedDeque.hpp.
     {
         really_assert(!empty());
         return *storage[index(numAllocated - 1)];
     }
begin() [1/2]
template<class T > BoundedDeque< T >::iterator infra::BoundedDeque< T >::begin ()
Definition at line 291 of file BoundedDeque.hpp.
Referenced by infra::BoundedDeque< decltype(buffer)>::BoundedDeque(), services::ConnectionMbedTls::DataReceived(), infra::BoundedDequeInputStreamReader::Extract(), infra::BoundedDequeInputStreamReader::ExtractContiguousRange(), services::ConnectionSerial::SerialConnectionStreamReader::ExtractContiguousRange(), infra::BoundedDeque< decltype(buffer)>::operator<(), infra::BoundedDeque< decltype(buffer)>::operator=(), infra::BoundedDeque< decltype(buffer)>::operator==(), services::ConnectionSerial::SerialConnectionStreamReader::PeekContiguousRange(), services::ConnectionBsd::Send(), services::ConnectionWin::Send(), and services::ConnectionMbedTls::TrySend().
     {
         return iterator(this, 0);
     }
begin() [2/2]
template<class T > BoundedDeque< T >::const_iterator infra::BoundedDeque< T >::begin () const
Definition at line 297 of file BoundedDeque.hpp.
     {
         return const_iterator(this, 0);
     }
cbegin()
template<class T > BoundedDeque< T >::const_iterator infra::BoundedDeque< T >::cbegin () const
Definition at line 339 of file BoundedDeque.hpp.
     {
         return begin();
     }
cend()
template<class T > BoundedDeque< T >::const_iterator infra::BoundedDeque< T >::cend () const
Definition at line 345 of file BoundedDeque.hpp.
     {
         return end();
     }
clear()
template<class T > void infra::BoundedDeque< T >::clear ()
Definition at line 630 of file BoundedDeque.hpp.
     {
         if (std::is_trivially_destructible<T>::value)
             numAllocated = 0;
         else
             while (!empty())
                 pop_back();
         start = 0;
     }
contiguous_range() [1/2]
template<class T > infra::MemoryRange< T > infra::BoundedDeque< T >::contiguous_range (const_iterator from)
Definition at line 397 of file BoundedDeque.hpp.
Referenced by services::ConnectionMbedTls::DataReceived(), infra::BoundedDequeInputStreamReader::Extract(), infra::BoundedDequeInputStreamReader::ExtractContiguousRange(), services::ConnectionSerial::SerialConnectionStreamReader::ExtractContiguousRange(), services::ConnectionSerial::SerialConnectionStreamReader::PeekContiguousRange(), services::ConnectionBsd::Send(), services::ConnectionWin::Send(), and services::ConnectionMbedTls::TrySend().
     {
         if (!empty())
         {
             std::size_t i = index(from.index);
             return infra::MemoryRange<T>(&*storage[i], std::min(&*storage[i] + numAllocated - from.index, &**storage.begin() + storage.size()));
         }
         else
             return infra::MemoryRange<T>();
     }
contiguous_range() [2/2]
template<class T > infra::MemoryRange< const T > infra::BoundedDeque< T >::contiguous_range (const_iterator from) const
Definition at line 409 of file BoundedDeque.hpp.
     {
         if (!empty())
         {
             std::size_t i = index(from.index);
             return infra::MemoryRange<const T>(&*storage[i], std::min(&*storage[i] + numAllocated - from.index, &**storage.begin() + storage.size()));
         }
         else
             return infra::MemoryRange<const T>();
     }
crbegin()
template<class T > BoundedDeque< T >::const_reverse_iterator infra::BoundedDeque< T >::crbegin () const
Definition at line 351 of file BoundedDeque.hpp.
     {
         return rbegin();
     }
crend()
template<class T > BoundedDeque< T >::const_reverse_iterator infra::BoundedDeque< T >::crend () const
Definition at line 357 of file BoundedDeque.hpp.
     {
         return rend();
     }
emplace()
template<class T > template<class... Args> BoundedDeque< T >::iterator infra::BoundedDeque< T >::emplace (const const_iterator & position, Args &&... args)
Definition at line 643 of file BoundedDeque.hpp.
     {
         really_assert(size() != max_size());
         size_type element_index = position - begin();
         move_up(element_index, 1);
         storage[index(element_index)].Construct(std::forward<Args>(args)...);
         return iterator(this, element_index);
     }
emplace_back()
template<class T > template<class... Args> void infra::BoundedDeque< T >::emplace_back (Args &&... args)
Definition at line 668 of file BoundedDeque.hpp.
     {
         really_assert(size() != max_size());
         storage[index(numAllocated)].Construct(std::forward<Args>(args)...);
         ++numAllocated;
     }
emplace_front()
template<class T > template<class... Args> void infra::BoundedDeque< T >::emplace_front (Args &&... args)
Definition at line 655 of file BoundedDeque.hpp.
     {
         really_assert(size() != max_size());
         if (start != 0)
             --start;
         else
             start = max_size() - 1;
         storage[index(0)].Construct(std::forward<Args>(args)...);
         ++numAllocated;
     }
empty()
template<class T > bool infra::BoundedDeque< T >::empty () const
Definition at line 385 of file BoundedDeque.hpp.
Referenced by services::Terminal::HistoryForward(), services::ConnectionBsd::Send(), services::ConnectionWin::Send(), services::ConnectionMbedTls::TrySend(), and services::ConnectionWin::UpdateEventFlags().
     {
         return numAllocated == 0;
     }
end() [1/2]
template<class T > BoundedDeque< T >::iterator infra::BoundedDeque< T >::end ()
Definition at line 303 of file BoundedDeque.hpp.
Referenced by infra::BoundedDeque< decltype(buffer)>::BoundedDeque(), infra::BoundedDeque< decltype(buffer)>::operator<(), infra::BoundedDeque< decltype(buffer)>::operator=(), services::ConnectionBsd::Receive(), and services::ConnectionWin::Receive().
     {
         return iterator(this, numAllocated);
     }
end() [2/2]
template<class T > BoundedDeque< T >::const_iterator infra::BoundedDeque< T >::end () const
Definition at line 309 of file BoundedDeque.hpp.
     {
         return const_iterator(this, numAllocated);
     }
erase() [1/2]
template<class T > BoundedDeque< T >::iterator infra::BoundedDeque< T >::erase (const const_iterator & position)
Definition at line 586 of file BoundedDeque.hpp.
Referenced by services::ConnectionBsd::Send(), services::ConnectionWin::Send(), and services::ConnectionMbedTls::TrySend().
     {
         return erase(position, position + 1);
     }
erase() [2/2]
template<class T > BoundedDeque< T >::iterator infra::BoundedDeque< T >::erase (const const_iterator & first, const const_iterator & last)
Definition at line 592 of file BoundedDeque.hpp.
     {
         size_type first_index = first - begin();
         size_type last_index = last - begin();
         for (; last_index != numAllocated; ++first_index, ++last_index)
             *storage[index(first_index)] = std::move(*storage[index(last_index)]);
         for (; first_index != last_index; ++first_index, --numAllocated)
             storage[index(first_index)].Destruct();
         return iterator(this, first - begin());
     }
front() [1/2]
template<class T > BoundedDeque< T >::value_type & infra::BoundedDeque< T >::front ()
Definition at line 435 of file BoundedDeque.hpp.
     {
         really_assert(!empty());
         return *storage[start];
     }
front() [2/2]
template<class T > const BoundedDeque< T >::value_type & infra::BoundedDeque< T >::front () const
Definition at line 442 of file BoundedDeque.hpp.
     {
         really_assert(!empty());
         return *storage[start];
     }
full()
template<class T > bool infra::BoundedDeque< T >::full () const
Definition at line 391 of file BoundedDeque.hpp.
Referenced by services::ConnectionMbedTls::DataReceived(), services::ConnectionBsd::Receive(), services::ConnectionWin::Receive(), services::Terminal::StoreHistory(), and services::ConnectionWin::UpdateEventFlags().
     {
         return numAllocated == max_size();
     }
index()
template<class T > BoundedDeque< T >::size_type infra::BoundedDeque< T >::index (size_type i) const private
Definition at line 713 of file BoundedDeque.hpp.
Referenced by infra::BoundedDeque< decltype(buffer)>::swap().
     {
         size_type index = start + elementIndex;
         if (index < max_size())
             return index;
         else
             return index - max_size();
     }
insert() [1/6]
template<class T > BoundedDeque< T >::iterator infra::BoundedDeque< T >::insert (const const_iterator & position, const value_type & value)
Definition at line 539 of file BoundedDeque.hpp.
Referenced by services::ConnectionBsd::Receive(), and services::ConnectionWin::Receive().
     {
         return insert(position, size_type(1), value);
     }
insert() [2/6]
template<class T > BoundedDeque< T >::iterator infra::BoundedDeque< T >::insert (const const_iterator & position, size_type n, const value_type & value)
Definition at line 545 of file BoundedDeque.hpp.
     {
         really_assert(size() + n <= max_size());
         size_type element_index = position - begin();
         move_up(element_index, n);
         iterator pos(this, position - cbegin());
         for (size_type i = 0, e = element_index; i != n; ++i, ++e)
             *storage[index(e)] = value;
         return iterator(this, element_index);
     }
insert() [3/6]
template<class T> template<class InputIterator > iterator infra::BoundedDeque< T >::insert (const const_iterator & position, InputIterator first, const InputIterator & last)
insert() [4/6]
template<class T> BoundedDeque< T >::iterator infra::BoundedDeque< T >::insert (const const_iterator & position, T && val)
Definition at line 574 of file BoundedDeque.hpp.
     {
         return emplace(position, std::move(val));
     }
insert() [5/6]
template<class T> BoundedDeque< T >::iterator infra::BoundedDeque< T >::insert (const const_iterator & position, std::initializer_list< T > initializerList)
Definition at line 580 of file BoundedDeque.hpp.
     {
         return insert(position, initializerList.begin(), initializerList.end());
     }
insert() [6/6]
template<class T> template<class RandomAccessIterator > BoundedDeque<T>::iterator infra::BoundedDeque< T >::insert (const const_iterator & position, RandomAccessIterator first, const RandomAccessIterator & last)
Definition at line 560 of file BoundedDeque.hpp.
     {
         size_type n = last - first;
         really_assert(size() + n <= max_size());
         size_type element_index = position - begin();
         move_up(element_index, n);
         for (; first != last; ++element_index, ++first)
             *storage[index(element_index)] = *first;
         return iterator(this, position - begin());
     }
max_size()
template<class T > BoundedDeque< T >::size_type infra::BoundedDeque< T >::max_size () const
Definition at line 369 of file BoundedDeque.hpp.
Referenced by services::ConnectionMbedTls::DataReceived(), services::ConnectionBsd::MaxSendStreamSize(), services::ConnectionWin::MaxSendStreamSize(), services::ConnectionMbedTls::MaxSendStreamSize(), services::ConnectionBsd::Receive(), services::ConnectionWin::Receive(), services::ConnectionBsd::TryAllocateSendStream(), services::ConnectionWin::TryAllocateSendStream(), and services::ConnectionMbedTls::TryAllocateSendStream().
     {
         return storage.size();
     }
move_up()
template<class T > void infra::BoundedDeque< T >::move_up (size_type position, size_type n) private
Definition at line 723 of file BoundedDeque.hpp.
     {
         size_type number_of_copies = numAllocated - position;
         size_type copy_position = numAllocated - 1 + n;
         for (; number_of_copies != 0 && copy_position >= numAllocated; --number_of_copies, --copy_position)
             storage[index(copy_position)].Construct(std::move(*storage[index(copy_position - n)]));
         for (; number_of_copies != 0; --number_of_copies, --copy_position)
             *storage[index(copy_position)] = std::move(*storage[index(copy_position - n)]);
         numAllocated += n;
     }
operator!=()
template<class T > bool infra::BoundedDeque< T >::operator!= (const BoundedDeque< T > & other) const
Definition at line 683 of file BoundedDeque.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T > bool infra::BoundedDeque< T >::operator< (const BoundedDeque< T > & other) const
Definition at line 689 of file BoundedDeque.hpp.
     {
         return std::lexicographical_compare(begin(), end(), other.begin(), other.end());
     }
operator<=()
template<class T > bool infra::BoundedDeque< T >::operator<= (const BoundedDeque< T > & other) const
Definition at line 695 of file BoundedDeque.hpp.
     {
         return !(other < *this);
     }
operator=() [1/3]
template<class T > BoundedDeque< T > & infra::BoundedDeque< T >::operator= (const BoundedDeque< T > & other)
Definition at line 243 of file BoundedDeque.hpp.
     {
         if (this != &other)
             assign(other.begin(), other.end());
         return *this;
     }
operator=() [2/3]
template<class T > BoundedDeque< T > & infra::BoundedDeque< T >::operator= (BoundedDeque< T > && other)
Definition at line 252 of file BoundedDeque.hpp.
     {
         clear();
         numAllocated = other.numAllocated;
         for (size_type i = 0; i != size(); ++i)
             storage[i].Construct(std::move(other[i]));
         return *this;
     }
operator=() [3/3]
template<class T> BoundedDeque< T > & infra::BoundedDeque< T >::operator= (std::initializer_list< T > initializerList)
Definition at line 265 of file BoundedDeque.hpp.
     {
         assign(initializerList.begin(), initializerList.end());
         return *this;
     }
operator==()
template<class T > bool infra::BoundedDeque< T >::operator== (const BoundedDeque< T > & other) const
Definition at line 677 of file BoundedDeque.hpp.
     {
         return size() == other.size() && std::equal(begin(), end(), other.begin());
     }
operator>()
template<class T > bool infra::BoundedDeque< T >::operator> (const BoundedDeque< T > & other) const
Definition at line 701 of file BoundedDeque.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T > bool infra::BoundedDeque< T >::operator>= (const BoundedDeque< T > & other) const
Definition at line 707 of file BoundedDeque.hpp.
     {
         return !(*this < other);
     }
operator[]() [1/2]
template<class T > BoundedDeque< T >::value_type & infra::BoundedDeque< T >::operator[] (size_type position)
Definition at line 421 of file BoundedDeque.hpp.
     {
         really_assert(position >= 0 && position < size());
         return *storage[index(position)];
     }
operator[]() [2/2]
template<class T > const BoundedDeque< T >::value_type & infra::BoundedDeque< T >::operator[] (size_type position) const
Definition at line 428 of file BoundedDeque.hpp.
     {
         really_assert(position >= 0 && position < size());
         return *storage[index(position)];
     }
pop_back()
template<class T > void infra::BoundedDeque< T >::pop_back ()
Definition at line 531 of file BoundedDeque.hpp.
     {
         really_assert(!empty());
         storage[index(numAllocated - 1)].Destruct();
         --numAllocated;
     }
pop_front()
template<class T > void infra::BoundedDeque< T >::pop_front ()
Definition at line 506 of file BoundedDeque.hpp.
Referenced by services::ConnectionSerial::SerialConnectionStreamReader::ConsumeExtracted(), and services::Terminal::StoreHistory().
     {
         really_assert(!empty());
         storage[start].Destruct();
         start = index(1);
         --numAllocated;
     }
push_back() [1/2]
template<class T > void infra::BoundedDeque< T >::push_back (const value_type & value)
Definition at line 515 of file BoundedDeque.hpp.
Referenced by services::Terminal::StoreHistory().
     {
         really_assert(!full());
         storage[index(numAllocated)].Construct(value);
         ++numAllocated;
     }
push_back() [2/2]
template<class T > void infra::BoundedDeque< T >::push_back (value_type && value)
Definition at line 523 of file BoundedDeque.hpp.
     {
         really_assert(!full());
         storage[index(numAllocated)].Construct(std::move(value));
         ++numAllocated;
     }
push_front() [1/2]
template<class T > void infra::BoundedDeque< T >::push_front (const value_type & value)
Definition at line 488 of file BoundedDeque.hpp.
     {
         really_assert(!full());
         start = index(max_size() - 1);
         storage[start].Construct(value);
         ++numAllocated;
     }
push_front() [2/2]
template<class T > void infra::BoundedDeque< T >::push_front (value_type && value)
Definition at line 497 of file BoundedDeque.hpp.
     {
         really_assert(!full());
         start = index(max_size() - 1);
         storage[start].Construct(std::move(value));
         ++numAllocated;
     }
rbegin() [1/2]
template<class T > BoundedDeque< T >::reverse_iterator infra::BoundedDeque< T >::rbegin ()
Definition at line 315 of file BoundedDeque.hpp.
     {
         return reverse_iterator(end());
     }
rbegin() [2/2]
template<class T > BoundedDeque< T >::const_reverse_iterator infra::BoundedDeque< T >::rbegin () const
Definition at line 321 of file BoundedDeque.hpp.
     {
         return const_reverse_iterator(end());
     }
rend() [1/2]
template<class T > BoundedDeque< T >::reverse_iterator infra::BoundedDeque< T >::rend ()
Definition at line 327 of file BoundedDeque.hpp.
     {
         return reverse_iterator(begin());
     }
rend() [2/2]
template<class T > BoundedDeque< T >::const_reverse_iterator infra::BoundedDeque< T >::rend () const
Definition at line 333 of file BoundedDeque.hpp.
     {
         return const_reverse_iterator(begin());
     }
resize()
template<class T > void infra::BoundedDeque< T >::resize (size_type n, const value_type & value = value_type())
Definition at line 375 of file BoundedDeque.hpp.
Referenced by services::ConnectionMbedTls::DataReceived().
     {
         while (n < size())
             pop_back();
         while (n > size())
             push_back(value);
     }
size()
template<class T > BoundedDeque< T >::size_type infra::BoundedDeque< T >::size () const
Definition at line 363 of file BoundedDeque.hpp.
Referenced by infra::BoundedDequeInputStreamReader::Available(), services::ConnectionSerial::SerialConnectionStreamReader::Available(), services::ConnectionMbedTls::DataReceived(), infra::BoundedDequeInputStreamReader::Empty(), infra::BoundedDequeInputStreamReader::Extract(), services::Terminal::HistoryForward(), infra::BoundedDeque< decltype(buffer)>::max_size(), infra::BoundedDeque< decltype(buffer)>::operator==(), services::ConnectionSerial::SerialConnectionStreamReader::PeekContiguousRange(), services::ConnectionBsd::Receive(), services::ConnectionWin::Receive(), services::Terminal::StoreHistory(), infra::BoundedDeque< decltype(buffer)>::swap(), services::ConnectionBsd::TryAllocateSendStream(), services::ConnectionWin::TryAllocateSendStream(), and services::ConnectionMbedTls::TryAllocateSendStream().
     {
         return numAllocated;
     }
swap()
template<class T > void infra::BoundedDeque< T >::swap (BoundedDeque< T > & other)
Definition at line 607 of file BoundedDeque.hpp.
Referenced by infra::swap().
     {
         using std::swap;
         for (size_type i = 0; i < size() && i < other.size(); ++i)
             swap(*storage[index(i)], *other.storage[other.index(i)]);
         for (size_type i = size(); i < other.size(); ++i)
         {
             storage[index(i)].Construct(std::move(*other.storage[other.index(i)]));
             other.storage[other.index(i)].Destruct();
         }
         for (size_type i = other.size(); i < size(); ++i)
         {
             other.storage[other.index(i)].Construct(std::move(*storage[index(i)]));
             storage[index(i)].Destruct();
         }
         std::swap(numAllocated, other.numAllocated);
     }
Member Data Documentation
numAllocated
template<class T> size_type infra::BoundedDeque< T >::numAllocated = 0 private
Definition at line 138 of file BoundedDeque.hpp.
Referenced by infra::BoundedDeque< decltype(buffer)>::swap().
start
template<class T> size_type infra::BoundedDeque< T >::start = 0 private
Definition at line 139 of file BoundedDeque.hpp.
storage
template<class T> infra::MemoryRange<StaticStorage<T> > infra::BoundedDeque< T >::storage private
Definition at line 137 of file BoundedDeque.hpp.
Referenced by infra::BoundedDeque< decltype(buffer)>::swap().
The documentation for this class was generated from the following file:
BoundedDeque.hpp