EMil: infra::Tokenizer Class Reference
infra::Tokenizer Class Reference
#include <Tokenizer.hpp>
Public Member Functions
Tokenizer (infra::BoundedConstString string, char separator)
infra::BoundedConstString Token (std::size_t tokenIndex) const
infra::BoundedConstString TokenAndRest (std::size_t tokenIndex) const
std::size_t Size () const
Private Member Functions
infra::BoundedConstString MakeToken (std::size_t start) const
std::size_t SkipTokens (std::size_t tokenIndex) const
std::size_t StartOfNextToken (std::size_t start) const
std::size_t SkipConsecutiveSeparators (std::size_t index) const
Private Attributes
infra::BoundedConstString string
char separator
Detailed Description
Definition at line 8 of file Tokenizer.hpp.
Constructor & Destructor Documentation
Tokenizer()
infra::Tokenizer::Tokenizer (infra::BoundedConstString string, char separator)
Definition at line 5 of file Tokenizer.cpp.
         : string(string)
         , separator(separator)
     {}
Member Function Documentation
MakeToken()
infra::BoundedConstString infra::Tokenizer::MakeToken (std::size_t start) const private
Definition at line 41 of file Tokenizer.cpp.
References separator, and infra::BoundedStringBase< T >::substr().
Referenced by Token().
     {
         if (start < string.size())
             return string.substr(start, string.find(separator, start) - start);
         else
             return infra::BoundedConstString();
     }
Size()
std::size_t infra::Tokenizer::Size () const
Definition at line 27 of file Tokenizer.cpp.
References infra::BoundedStringBase< const char >::npos, SkipConsecutiveSeparators(), and StartOfNextToken().
     {
         std::size_t result = 0;
         std::size_t start = SkipConsecutiveSeparators(0);
         while (start != infra::BoundedConstString::npos)
         {
             ++result;
             start = StartOfNextToken(start);
         }
         return result;
     }
SkipConsecutiveSeparators()
std::size_t infra::Tokenizer::SkipConsecutiveSeparators (std::size_t index) const private
Definition at line 64 of file Tokenizer.cpp.
References separator.
Referenced by Size(), SkipTokens(), and StartOfNextToken().
     {
         while (index < string.size() && string[index] == separator)
             ++index;
         return index;
     }
SkipTokens()
std::size_t infra::Tokenizer::SkipTokens (std::size_t tokenIndex) const private
Definition at line 49 of file Tokenizer.cpp.
References infra::BoundedStringBase< const char >::npos, SkipConsecutiveSeparators(), and StartOfNextToken().
Referenced by Token(), and TokenAndRest().
     {
         std::size_t start = SkipConsecutiveSeparators(0);
         while (tokenIndex-- != 0 && start != infra::BoundedConstString::npos)
             start = StartOfNextToken(start);
         return start;
     }
StartOfNextToken()
std::size_t infra::Tokenizer::StartOfNextToken (std::size_t start) const private
Definition at line 59 of file Tokenizer.cpp.
References separator, and SkipConsecutiveSeparators().
Referenced by Size(), and SkipTokens().
     {
         return SkipConsecutiveSeparators(string.find(separator, start));
     }
Token()
infra::BoundedConstString infra::Tokenizer::Token (std::size_t tokenIndex) const
Definition at line 10 of file Tokenizer.cpp.
References MakeToken(), and SkipTokens().
Referenced by services::HttpRequestParserImpl::FindPath(), services::HttpRequestParserImpl::FindVerb(), services::HttpClientImpl::HttpResponseParser::HeaderFromString(), and services::HttpClientImpl::HttpResponseParser::ParseStatusLine().
     {
         std::size_t start = SkipTokens(tokenIndex);
         return MakeToken(start);
     }
TokenAndRest()
infra::BoundedConstString infra::Tokenizer::TokenAndRest (std::size_t tokenIndex) const
Definition at line 17 of file Tokenizer.cpp.
References infra::detail::begin(), infra::BoundedStringBase< const char >::npos, and SkipTokens().
Referenced by services::HttpClientImpl::HttpResponseParser::HeaderFromString(), and application::TimeHttpPage::ServesRequest().
     {
         std::size_t start = SkipTokens(tokenIndex);
         if (start != infra::BoundedConstString::npos)
             return infra::BoundedConstString(string.begin() + start, string.size() - start);
         else
             return infra::BoundedConstString();
     }
Member Data Documentation
separator
char infra::Tokenizer::separator private
Definition at line 25 of file Tokenizer.hpp.
Referenced by MakeToken(), SkipConsecutiveSeparators(), and StartOfNextToken().
string
infra::BoundedConstString infra::Tokenizer::string private
Definition at line 24 of file Tokenizer.hpp.
The documentation for this class was generated from the following files:
Tokenizer.hpp
Tokenizer.cpp