EMil: infra::SavedMarkerStreamWriter Class Reference
infra::SavedMarkerStreamWriter Class Reference
#include <SavedMarkerStream.hpp>
Public Member Functions
SavedMarkerStreamWriter (OutputStream &stream, std::size_t marker)
~SavedMarkerStreamWriter ()
Public Member Functions inherited from infra::ByteOutputStreamWriter
ByteOutputStreamWriter (ByteRange range)
ByteRange Processed () const
ByteRange Remaining () const
void Reset ()
template<class T >
ReservedProxy< T > Reserve (StreamErrorPolicy &errorPolicy)
Private Attributes
OutputStream & stream
Additional Inherited Members
Public Types inherited from infra::ByteOutputStreamWriter
template<std::size_t Max>
using WithStorage = infra::WithStorage< ByteOutputStreamWriter, std::array< uint8_t, Max > >
Protected Member Functions inherited from infra::ByteOutputStreamWriter
virtual void Insert (ConstByteRange range, StreamErrorPolicy &errorPolicy) override
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 8 of file SavedMarkerStream.hpp.
Constructor & Destructor Documentation
SavedMarkerStreamWriter()
infra::SavedMarkerStreamWriter::SavedMarkerStreamWriter (OutputStream & stream, std::size_t marker)
Definition at line 5 of file SavedMarkerStream.cpp.
         : ByteOutputStreamWriter(stream.Writer().SaveState(marker))
         , stream(stream)
     {}
~SavedMarkerStreamWriter()
infra::SavedMarkerStreamWriter::~SavedMarkerStreamWriter ()
Definition at line 10 of file SavedMarkerStream.cpp.
References infra::ByteOutputStreamWriter::Remaining(), infra::StreamWriter::RestoreState(), stream, and infra::OutputStream::Writer().
     {
         stream.Writer().RestoreState(Remaining());
     }
Member Data Documentation
stream
OutputStream& infra::SavedMarkerStreamWriter::stream private
Definition at line 16 of file SavedMarkerStream.hpp.
Referenced by ~SavedMarkerStreamWriter().
The documentation for this class was generated from the following files:
SavedMarkerStream.hpp
SavedMarkerStream.cpp