EMil: infra::PolymorphicVariant< Base, T > Class Template Reference
infra::PolymorphicVariant< Base, T > Class Template Reference
#include <PolymorphicVariant.hpp>
Public Member Functions
PolymorphicVariant ()
PolymorphicVariant (const PolymorphicVariant &other)
template<class... T2>
PolymorphicVariant (const PolymorphicVariant< T2... > &other)
template<class U >
PolymorphicVariant (const U &v)
template<class U , class... Args>
PolymorphicVariant (InPlaceType< U >, Args &&... args)
PolymorphicVariant & operator= (const PolymorphicVariant &other)
template<class... T2>
PolymorphicVariant & operator= (const PolymorphicVariant< T2... > &other)
template<class U >
PolymorphicVariant & operator= (const U &v)
~PolymorphicVariant ()
template<class U , class... Args>
U & Emplace (Args &&... args)
const Base & Get () const
Base & Get ()
const Base & operator* () const
Base & operator* ()
const Base * operator-> () const
Base * operator-> ()
bool operator== (const PolymorphicVariant &other) const
bool operator!= (const PolymorphicVariant &other) const
bool operator< (const PolymorphicVariant &other) const
bool operator> (const PolymorphicVariant &other) const
bool operator<= (const PolymorphicVariant &other) const
bool operator>= (const PolymorphicVariant &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator== (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator!= (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator< (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator> (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator<= (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator>= (const U &other) const
template<class... T2>
PolymorphicVariant< Base, T... > & operator= (const PolymorphicVariant< T2... > &other)
template<class U>
PolymorphicVariant< Base, T... > & operator= (const U &v)
Static Public Attributes
static const std::size_t size = sizeof...(T)
Private Member Functions
std::size_t Which () const
template<std::size_t Index>
const TypeAtIndex< Index, T... >::Type & GetAtIndex () const
template<std::size_t Index>
TypeAtIndex< Index, T... >::Type & GetAtIndex ()
template<class U , class... Args>
U & ConstructInEmptyVariant (Args &&... args)
void Destruct ()
Private Attributes
std::size_t dataIndex = 0
StaticStorageForInheritanceTree< Base, T... > storage
Friends
template<std::size_t Index, class Visitor , class Variant , class Enable >
struct detail::ApplyVisitorHelper
template<std::size_t Index, class Visitor , class Variant , class Enable >
struct detail::ApplySameTypeVisitorHelper
template<class Base2 , class... T2>
struct detail::ConstructPolymorphicVisitor
template<class Visitor , class Variant >
Visitor::ResultType ApplySameTypeVisitor (Visitor &visitor, Variant &variant1, Variant &variant2)
Detailed Description
template<class Base, class... T>
class infra::PolymorphicVariant< Base, T >
Definition at line 10 of file PolymorphicVariant.hpp.
Constructor & Destructor Documentation
PolymorphicVariant() [1/5]
template<class Base , class... T> infra::PolymorphicVariant< Base, T >::PolymorphicVariant ()
Definition at line 99 of file PolymorphicVariant.hpp.
     {
         ConstructInEmptyVariant<typename Front<T...>::Type>();
     }
PolymorphicVariant() [2/5]
template<class Base , class... T> infra::PolymorphicVariant< Base, T >::PolymorphicVariant (const PolymorphicVariant< Base, T > & other)
Definition at line 105 of file PolymorphicVariant.hpp.
     {
         detail::ConstructPolymorphicVisitor<Base, T...> visitor(*this);
         ApplyVisitor(visitor, other);
     }
PolymorphicVariant() [3/5]
template<class Base , class... T> template<class... T2> infra::PolymorphicVariant< Base, T >::PolymorphicVariant (const PolymorphicVariant< T2... > & other) explicit
Definition at line 113 of file PolymorphicVariant.hpp.
     {
         detail::ConstructPolymorphicVisitor<Base, T...> visitor(*this);
         ApplyVisitor(visitor, other);
     }
PolymorphicVariant() [4/5]
template<class Base , class... T> template<class U> infra::PolymorphicVariant< Base, T >::PolymorphicVariant (const U & v) explicit
Definition at line 121 of file PolymorphicVariant.hpp.
     {
         ConstructInEmptyVariant<U>(v);
     }
PolymorphicVariant() [5/5]
template<class Base , class... T> template<class U, class... Args> infra::PolymorphicVariant< Base, T >::PolymorphicVariant (InPlaceType< U > , Args &&... args)
Definition at line 128 of file PolymorphicVariant.hpp.
     {
         ConstructInEmptyVariant<U>(std::forward<Args>(args)...);
     }
~PolymorphicVariant()
template<class Base , class... T> infra::PolymorphicVariant< Base, T >::~PolymorphicVariant ()
Definition at line 174 of file PolymorphicVariant.hpp.
     {
         Destruct();
     }
Member Function Documentation
ConstructInEmptyVariant()
template<class Base , class... T> template<class U , class... Args> U & infra::PolymorphicVariant< Base, T >::ConstructInEmptyVariant (Args &&... args) private
Definition at line 332 of file PolymorphicVariant.hpp.
     {
         dataIndex = IndexInTypeList<U, T...>::value;
         storage.template Construct<U>(std::forward<Args>(args)...);
         return reinterpret_cast<U&>(*storage);
     }
Destruct()
template<class Base , class... T> void infra::PolymorphicVariant< Base, T >::Destruct () private
Definition at line 340 of file PolymorphicVariant.hpp.
Referenced by infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::Destruct(), and infra::BoundedVector< infra::PolymorphicVariant< infra::JsonSubParser, infra::JsonSubObjectParser, infra::JsonSubArrayParser > >::erase().
     {
         storage.Destruct();
     }
Emplace()
template<class Base , class... T> template<class U , class... Args> U & infra::PolymorphicVariant< Base, T >::Emplace (Args &&... args)
Definition at line 167 of file PolymorphicVariant.hpp.
     {
         Destruct();
         return ConstructInEmptyVariant<U>(std::forward<Args>(args)...);
     }
Get() [1/2]
template<class Base , class... T> const Base & infra::PolymorphicVariant< Base, T >::Get () const
Definition at line 180 of file PolymorphicVariant.hpp.
     {
         return *storage;
     }
Get() [2/2]
template<class Base , class... T> Base & infra::PolymorphicVariant< Base, T >::Get ()
Definition at line 186 of file PolymorphicVariant.hpp.
     {
         return *storage;
     }
GetAtIndex() [1/2]
template<class Base , class... T> template<std::size_t Index> const TypeAtIndex< Index, T... >::Type & infra::PolymorphicVariant< Base, T >::GetAtIndex () const private
Definition at line 318 of file PolymorphicVariant.hpp.
     {
         return static_cast<const typename TypeAtIndex<Index, T...>::Type&>(Get());
     }
GetAtIndex() [2/2]
template<class Base , class... T> template<std::size_t Index> TypeAtIndex< Index, T... >::Type & infra::PolymorphicVariant< Base, T >::GetAtIndex () private
Definition at line 325 of file PolymorphicVariant.hpp.
     {
         return static_cast<typename TypeAtIndex<Index, T...>::Type&>(Get());
     }
operator!=() [1/2]
template<class Base , class... T> bool infra::PolymorphicVariant< Base, T >::operator!= (const PolymorphicVariant< Base, T > & other) const
Definition at line 226 of file PolymorphicVariant.hpp.
     {
         return !(*this == other);
     }
operator!=() [2/2]
template<class Base , class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::PolymorphicVariant< Base, T >::operator!= (const U & other) const
Definition at line 271 of file PolymorphicVariant.hpp.
     {
         return !(*this == other);                                                                                       //TICS !CON#007
     }
operator*() [1/2]
template<class Base , class... T> const Base & infra::PolymorphicVariant< Base, T >::operator* () const
Definition at line 192 of file PolymorphicVariant.hpp.
     {
         return *storage;
     }
operator*() [2/2]
template<class Base , class... T> Base & infra::PolymorphicVariant< Base, T >::operator* ()
Definition at line 198 of file PolymorphicVariant.hpp.
     {
         return *storage;
     }
operator->() [1/2]
template<class Base , class... T> const Base * infra::PolymorphicVariant< Base, T >::operator-> () const
Definition at line 204 of file PolymorphicVariant.hpp.
     {
         return &*storage;
     }
operator->() [2/2]
template<class Base , class... T> Base * infra::PolymorphicVariant< Base, T >::operator-> ()
Definition at line 210 of file PolymorphicVariant.hpp.
     {
         return &*storage;
     }
operator<() [1/2]
template<class Base , class... T> bool infra::PolymorphicVariant< Base, T >::operator< (const PolymorphicVariant< Base, T > & other) const
Definition at line 232 of file PolymorphicVariant.hpp.
     {
         if (Which() != other.Which())
             return Which() < other.Which();
         detail::LessThanVisitor visitor;
         return ApplySameTypeVisitor(visitor, *this, other);
     }
operator<() [2/2]
template<class Base , class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::PolymorphicVariant< Base, T >::operator< (const U & other) const
Definition at line 278 of file PolymorphicVariant.hpp.
     {
         if (Which() != IndexInTypeList<U, T...>::value)
             return Which() < IndexInTypeList<U, T...>::value;                                                           //TICS !CON#007
         return GetAtIndex<IndexInTypeList<U, T...>::value>() < other;                                                   //TICS !CON#007
     }
operator<=() [1/2]
template<class Base , class... T> bool infra::PolymorphicVariant< Base, T >::operator<= (const PolymorphicVariant< Base, T > & other) const
Definition at line 248 of file PolymorphicVariant.hpp.
     {
         return !(other < *this);
     }
operator<=() [2/2]
template<class Base , class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::PolymorphicVariant< Base, T >::operator<= (const U & other) const
Definition at line 298 of file PolymorphicVariant.hpp.
     {
         return !(*this > other);                                                                                        //TICS !CON#007
     }
operator=() [1/5]
template<class Base , class... T> PolymorphicVariant< Base, T... > & infra::PolymorphicVariant< Base, T >::operator= (const PolymorphicVariant< Base, T > & other)
Definition at line 134 of file PolymorphicVariant.hpp.
     {
         if (this != &other)
         {
             detail::CopyPolymorphicVisitor<Base, T...> visitor(*this);
             ApplyVisitor(visitor, other);
         }
         return *this;
     }
operator=() [2/5]
template<class Base, class... T> template<class... T2> PolymorphicVariant& infra::PolymorphicVariant< Base, T >::operator= (const PolymorphicVariant< T2... > & other)
operator=() [3/5]
template<class Base, class... T> template<class U > PolymorphicVariant& infra::PolymorphicVariant< Base, T >::operator= (const U & v)
operator=() [4/5]
template<class Base, class... T> template<class... T2> PolymorphicVariant<Base, T...>& infra::PolymorphicVariant< Base, T >::operator= (const PolymorphicVariant< T2... > & other)
Definition at line 147 of file PolymorphicVariant.hpp.
     {
         detail::CopyPolymorphicVisitor<Base, T...> visitor(*this);
         ApplyVisitor(visitor, other);
         return *this;
     }
operator=() [5/5]
template<class Base, class... T> template<class U> PolymorphicVariant<Base, T...>& infra::PolymorphicVariant< Base, T >::operator= (const U & v)
Definition at line 157 of file PolymorphicVariant.hpp.
     {
         Destruct();
         ConstructInEmptyVariant<U>(v);
         return *this;
     }
operator==() [1/2]
template<class Base , class... T> bool infra::PolymorphicVariant< Base, T >::operator== (const PolymorphicVariant< Base, T > & other) const
Definition at line 216 of file PolymorphicVariant.hpp.
     {
         if (Which() != other.Which())
             return false;
         detail::EqualVisitor visitor;
         return ApplySameTypeVisitor(visitor, *this, other);
     }
operator==() [2/2]
template<class Base , class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::PolymorphicVariant< Base, T >::operator== (const U & other) const
Definition at line 261 of file PolymorphicVariant.hpp.
     {
         if (Which() != IndexInTypeList<U, T...>::value)
             return false;                                                                                               //TICS !CON#007
         return GetAtIndex<IndexInTypeList<U, T...>::value>() == other;                                                  //TICS !CON#007
     }
operator>() [1/2]
template<class Base , class... T> bool infra::PolymorphicVariant< Base, T >::operator> (const PolymorphicVariant< Base, T > & other) const
Definition at line 242 of file PolymorphicVariant.hpp.
     {
         return other < *this;
     }
operator>() [2/2]
template<class Base , class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::PolymorphicVariant< Base, T >::operator> (const U & other) const
Definition at line 288 of file PolymorphicVariant.hpp.
     {
         if (Which() != IndexInTypeList<U, T...>::value)
             return Which() > IndexInTypeList<U, T...>::value;                                                           //TICS !CON#007
         return other < GetAtIndex<IndexInTypeList<U, T...>::value>();                                                   //TICS !CON#007
     }
operator>=() [1/2]
template<class Base , class... T> bool infra::PolymorphicVariant< Base, T >::operator>= (const PolymorphicVariant< Base, T > & other) const
Definition at line 254 of file PolymorphicVariant.hpp.
     {
         return !(*this < other);
     }
operator>=() [2/2]
template<class Base , class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::PolymorphicVariant< Base, T >::operator>= (const U & other) const
Definition at line 305 of file PolymorphicVariant.hpp.
     {
         return !(*this < other);                                                                                        //TICS !CON#007
     }
Which()
template<class Base , class... T> std::size_t infra::PolymorphicVariant< Base, T >::Which () const private
Definition at line 311 of file PolymorphicVariant.hpp.
Referenced by infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::operator<(), and infra::PolymorphicVariant< services::ConnectionSerial::State, services::ConnectionSerial::StateInitSizeRequest, services::ConnectionSerial::StateInitSizeResponseRequest, services::ConnectionSerial::StateInitSizeResponse, services::ConnectionSerial::StateConnectedIdle, services::ConnectionSerial::StateConnectedSendingContent, services::ConnectionSerial::StateSendingUpdate >::operator==().
     {
         return dataIndex;
     }
Friends And Related Function Documentation
ApplySameTypeVisitor
template<class Base, class... T> template<class Visitor , class Variant > Visitor::ResultType ApplySameTypeVisitor (Visitor & visitor, Variant & variant1, Variant & variant2) friend
Definition at line 368 of file Variant.hpp.
     {
         really_assert(variant1.Which() == variant2.Which());
         detail::ApplySameTypeVisitorHelper<0, Visitor, Variant> helper;
         return helper(visitor, variant1, variant2);                                                                     //TICS !CON#007
     }
detail::ApplySameTypeVisitorHelper
template<class Base, class... T> template<std::size_t Index, class Visitor , class Variant , class Enable > friend struct detail::ApplySameTypeVisitorHelper friend
Definition at line 67 of file PolymorphicVariant.hpp.
detail::ApplyVisitorHelper
template<class Base, class... T> template<std::size_t Index, class Visitor , class Variant , class Enable > friend struct detail::ApplyVisitorHelper friend
Definition at line 65 of file PolymorphicVariant.hpp.
detail::ConstructPolymorphicVisitor
template<class Base, class... T> template<class Base2 , class... T2> friend struct detail::ConstructPolymorphicVisitor friend
Definition at line 81 of file PolymorphicVariant.hpp.
Member Data Documentation
dataIndex
template<class Base, class... T> std::size_t infra::PolymorphicVariant< Base, T >::dataIndex = 0 private
Definition at line 88 of file PolymorphicVariant.hpp.
size
template<class Base, class... T> const std::size_t infra::PolymorphicVariant< Base, T >::size = sizeof...(T) static
Definition at line 13 of file PolymorphicVariant.hpp.
storage
template<class Base, class... T> StaticStorageForInheritanceTree<Base, T...> infra::PolymorphicVariant< Base, T >::storage private
Definition at line 89 of file PolymorphicVariant.hpp.
The documentation for this class was generated from the following file:
PolymorphicVariant.hpp