EMil: infra::JsonArrayVisitor Class Reference
infra::JsonArrayVisitor Class Reference
#include <JsonStreamingParser.hpp>
Public Member Functions
virtual void VisitString (infra::BoundedConstString value)
virtual void VisitNumber (int64_t value)
virtual void VisitBoolean (bool value)
virtual void VisitNull ()
virtual JsonObjectVisitor * VisitObject (JsonSubObjectParser &parser)
virtual JsonArrayVisitor * VisitArray (JsonSubArrayParser &parser)
virtual void Close () override
virtual void ParseError () override
virtual void SemanticError () override
virtual void StringOverflow () override
Protected Member Functions
JsonArrayVisitor ()=default
JsonArrayVisitor (const JsonArrayVisitor &other)=delete
JsonArrayVisitor & operator= (const JsonArrayVisitor &other)=delete
~JsonArrayVisitor ()=default
Protected Member Functions inherited from infra::JsonVisitor
JsonVisitor ()=default
JsonVisitor (const JsonVisitor &other)=delete
JsonVisitor & operator= (const JsonVisitor &other)=delete
~JsonVisitor ()=default
Detailed Description
Definition at line 54 of file JsonStreamingParser.hpp.
Constructor & Destructor Documentation
JsonArrayVisitor() [1/2]
infra::JsonArrayVisitor::JsonArrayVisitor () protected default
JsonArrayVisitor() [2/2]
infra::JsonArrayVisitor::JsonArrayVisitor (const JsonArrayVisitor & other) protected delete
~JsonArrayVisitor()
infra::JsonArrayVisitor::~JsonArrayVisitor () protected default
Member Function Documentation
Close()
void infra::JsonArrayVisitor::Close () override virtual
Implements infra::JsonVisitor.
Definition at line 63 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {}
operator=()
JsonArrayVisitor& infra::JsonArrayVisitor::operator= (const JsonArrayVisitor & other) protected delete
ParseError()
void infra::JsonArrayVisitor::ParseError () override virtual
Implements infra::JsonVisitor.
Definition at line 66 of file JsonStreamingParser.cpp.
     {}
SemanticError()
void infra::JsonArrayVisitor::SemanticError () override virtual
Implements infra::JsonVisitor.
Definition at line 69 of file JsonStreamingParser.cpp.
     {}
StringOverflow()
void infra::JsonArrayVisitor::StringOverflow () override virtual
Implements infra::JsonVisitor.
Definition at line 72 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {}
VisitArray()
JsonArrayVisitor * infra::JsonArrayVisitor::VisitArray (JsonSubArrayParser & parser) virtual
Definition at line 58 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {
         return nullptr;
     }
VisitBoolean()
void infra::JsonArrayVisitor::VisitBoolean (bool value) virtual
Definition at line 47 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {}
VisitNull()
void infra::JsonArrayVisitor::VisitNull () virtual
Definition at line 50 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {}
VisitNumber()
void infra::JsonArrayVisitor::VisitNumber (int64_t value) virtual
Definition at line 44 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {}
VisitObject()
JsonObjectVisitor * infra::JsonArrayVisitor::VisitObject (JsonSubObjectParser & parser) virtual
Definition at line 53 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {
         return nullptr;
     }
VisitString()
void infra::JsonArrayVisitor::VisitString (infra::BoundedConstString value) virtual
Definition at line 41 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubArrayParser::Feed().
     {}
The documentation for this class was generated from the following files:
JsonStreamingParser.hpp
JsonStreamingParser.cpp