EMil: HttpClientBasicTest Class Reference
HttpClientBasicTest Class Reference
Public Member Functions
HttpClientBasicTest ()
~HttpClientBasicTest ()
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< services::HttpClientMock > httpClient
testing::StrictMock< services::HttpClientConnectorMock > httpClientConnector
services::HttpClientObserverFactory * httpClientObserverFactory = nullptr
infra::Execute execute { [this]() { EXPECT_CALL(httpClientConnector, Connect(testing::_)).WillOnce(infra::SaveRef<0>(&httpClientObserverFactory)); } }
infra::BoundedString::WithStorage< 64 > url { "https://hostname/path" }
infra::Optional< testing::StrictMock< HttpClientBasicMock > > controller { infra::inPlace, url, 443, httpClientConnector }
testing::StrictMock< infra::MockCallback< void()> > onStopped
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 25 of file TestHttpClientBasic.cpp.
Constructor & Destructor Documentation
HttpClientBasicTest()
HttpClientBasicTest::HttpClientBasicTest () inline
Definition at line 30 of file TestHttpClientBasic.cpp.
References EXPECT_EQ(), services::HttpClientObserverFactory::Hostname(), httpClientObserverFactory, and services::HttpClientObserverFactory::Port().
     {
         EXPECT_EQ("hostname", httpClientObserverFactory->Hostname());
         EXPECT_EQ(443, httpClientObserverFactory->Port());
     }
~HttpClientBasicTest()
HttpClientBasicTest::~HttpClientBasicTest () inline
Definition at line 36 of file TestHttpClientBasic.cpp.
References httpClient.
     {
         httpClient.observer = nullptr;
     }
Member Data Documentation
controller
infra::Optional<testing::StrictMock<HttpClientBasicMock> > HttpClientBasicTest::controller { infra::inPlace, url, 443, httpClientConnector }
Definition at line 46 of file TestHttpClientBasic.cpp.
execute
infra::Execute HttpClientBasicTest::execute { [this]() { EXPECT_CALL(httpClientConnector, Connect(testing::_)).WillOnce(infra::SaveRef<0>(&httpClientObserverFactory)); } }
Definition at line 44 of file TestHttpClientBasic.cpp.
httpClient
testing::StrictMock<services::HttpClientMock> HttpClientBasicTest::httpClient
Definition at line 41 of file TestHttpClientBasic.cpp.
Referenced by ~HttpClientBasicTest().
httpClientConnector
testing::StrictMock<services::HttpClientConnectorMock> HttpClientBasicTest::httpClientConnector
Definition at line 42 of file TestHttpClientBasic.cpp.
httpClientObserverFactory
services::HttpClientObserverFactory* HttpClientBasicTest::httpClientObserverFactory = nullptr
Definition at line 43 of file TestHttpClientBasic.cpp.
Referenced by HttpClientBasicTest().
onStopped
testing::StrictMock<infra::MockCallback<void()> > HttpClientBasicTest::onStopped
Definition at line 47 of file TestHttpClientBasic.cpp.
url
infra::BoundedString::WithStorage<64> HttpClientBasicTest::url { "https://hostname/path" }
Definition at line 45 of file TestHttpClientBasic.cpp.
The documentation for this class was generated from the following file:
TestHttpClientBasic.cpp