EMil: application::TracingHttpClient Class Reference
application::TracingHttpClient Class Reference
Public Member Functions
TracingHttpClient (infra::BoundedString url, uint16_t port, services::HttpClientConnector &connector, services::Tracer &tracer)
Private Member Functions
virtual void Connected () override
virtual void StatusAvailable (services::HttpStatusCode statusCode) override
virtual void HeaderAvailable (services::HttpHeader header) override
virtual void BodyAvailable (infra::SharedPtr< infra::StreamReader > &&reader) override
virtual void Done ()
virtual void Error (bool intermittentFailure)
Private Member Functions inherited from services::HttpClientBasic
HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector &httpClientConnector)
HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector &httpClientConnector, infra::Duration timeoutDuration)
void Cancel (const infra::Function< void()> &onDone)
void Connect ()
void Connect (infra::BoundedString url)
void Close ()
void ContentError ()
infra::BoundedString Url () const
virtual infra::BoundedString Path () const
virtual services::HttpHeaders Headers () const
virtual void Established ()
virtual void ClosingConnection () override
virtual void BodyComplete () override
Private Attributes
services::Tracer & tracer
Detailed Description
Definition at line 46 of file https_client/MainWin.cpp.
Constructor & Destructor Documentation
TracingHttpClient()
application::TracingHttpClient::TracingHttpClient (infra::BoundedString url, uint16_t port, services::HttpClientConnector & connector, services::Tracer & tracer) inline
Definition at line 49 of file https_client/MainWin.cpp.
             : HttpClientBasic(url, port, connector)
             , tracer(tracer)
         {
         }
Member Function Documentation
BodyAvailable()
virtual void application::TracingHttpClient::BodyAvailable (infra::SharedPtr< infra::StreamReader > && reader) inline override private virtual
Implements services::HttpClientObserver.
Definition at line 73 of file https_client/MainWin.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), infra::InputStream::Empty(), infra::noFail, services::Tracer::Trace(), and tracer.
         {
             infra::DataInputStream::WithErrorPolicy stream(*reader, infra::noFail);
             while (!stream.Empty())
                 tracer.Trace() << infra::ByteRangeAsString(stream.ContiguousRange());
         }
Connected()
virtual void application::TracingHttpClient::Connected () inline override private virtual
Reimplemented from services::HttpClientObserver.
Definition at line 58 of file https_client/MainWin.cpp.
References services::HttpClientBasic::Headers(), and services::HttpClientBasic::Path().
         {
             HttpClientObserver::Subject().Get(Path(), Headers());
         }
Done()
virtual void application::TracingHttpClient::Done () inline private virtual
Implements services::HttpClientBasic.
Definition at line 81 of file https_client/MainWin.cpp.
References services::Tracer::Trace(), and tracer.
         {
             tracer.Trace() << "Done";
         }
Error()
virtual void application::TracingHttpClient::Error (bool intermittentFailure) inline private virtual
Implements services::HttpClientBasic.
Definition at line 86 of file https_client/MainWin.cpp.
References services::Tracer::Trace(), and tracer.
         {
             tracer.Trace() << "Error";
         }
HeaderAvailable()
virtual void application::TracingHttpClient::HeaderAvailable (services::HttpHeader header) inline override private virtual
Implements services::HttpClientObserver.
Definition at line 68 of file https_client/MainWin.cpp.
References services::Tracer::Trace(), and tracer.
         {
             tracer.Trace() << "Header: " << header;
         }
StatusAvailable()
virtual void application::TracingHttpClient::StatusAvailable (services::HttpStatusCode statusCode) inline override private virtual
Implements services::HttpClientObserver.
Definition at line 63 of file https_client/MainWin.cpp.
References services::Tracer::Trace(), and tracer.
         {
             tracer.Trace() << "Status: " << statusCode;
         }
Member Data Documentation
tracer
services::Tracer& application::TracingHttpClient::tracer private
Definition at line 92 of file https_client/MainWin.cpp.
Referenced by BodyAvailable(), Done(), Error(), HeaderAvailable(), and StatusAvailable().
The documentation for this class was generated from the following file:
https_client/MainWin.cpp