EMil: hal::I2cMasterRegisterAccess Class Reference
hal::I2cMasterRegisterAccess Class Reference
#include <I2cRegisterAccess.hpp>
Public Member Functions
I2cMasterRegisterAccess (I2cMaster &i2cMaster, I2cAddress address)
void ReadRegister (uint8_t dataRegister, infra::ByteRange data, const infra::Function< void()> &onDone)
void WriteRegister (uint8_t dataRegister, infra::ConstByteRange data, const infra::Function< void()> &onDone)
Private Attributes
I2cMaster & i2cMaster
I2cAddress address
uint8_t dataRegister = 0
infra::ByteRange readData
infra::ConstByteRange writeData
infra::Function< void()> onDone
Detailed Description
Definition at line 9 of file I2cRegisterAccess.hpp.
Constructor & Destructor Documentation
I2cMasterRegisterAccess()
hal::I2cMasterRegisterAccess::I2cMasterRegisterAccess (I2cMaster & i2cMaster, I2cAddress address)
Definition at line 5 of file I2cRegisterAccess.cpp.
         : i2cMaster(i2cMaster)
         , address(address)
     {}
Member Function Documentation
ReadRegister()
void hal::I2cMasterRegisterAccess::ReadRegister (uint8_t dataRegister, infra::ByteRange data, const infra::Function< void()> & onDone)
Definition at line 10 of file I2cRegisterAccess.cpp.
References address, infra::data, dataRegister, i2cMaster, infra::MakeByteRange(), onDone, readData, hal::I2cMaster::ReceiveData(), hal::repeatedStart, hal::I2cMaster::SendData(), and hal::stop.
     {
         this->dataRegister = dataRegister;
         this->readData = data;
         this->onDone = onDone;
         i2cMaster.SendData(address, infra::MakeByteRange(this->dataRegister), hal::Action::repeatedStart, [this](hal::Result, uint32_t numberOfBytesSent)
         {
             i2cMaster.ReceiveData(address, readData, hal::Action::stop, [this](hal::Result) { this->onDone(); });
         });
     }
WriteRegister()
void hal::I2cMasterRegisterAccess::WriteRegister (uint8_t dataRegister, infra::ConstByteRange data, const infra::Function< void()> & onDone)
Definition at line 22 of file I2cRegisterAccess.cpp.
References address, hal::continueSession, infra::data, dataRegister, i2cMaster, infra::MakeByteRange(), onDone, hal::I2cMaster::SendData(), hal::stop, and writeData.
     {
         this->dataRegister = dataRegister;
         this->writeData = data;
         this->onDone = onDone;
         i2cMaster.SendData(address, infra::MakeByteRange(this->dataRegister), hal::Action::continueSession, [this](hal::Result, uint32_t numberOfBytesSent)
         {
             i2cMaster.SendData(address, writeData, hal::Action::stop, [this](hal::Result, uint32_t numberOfBytesSent) { this->onDone(); });
         });
     }
Member Data Documentation
address
I2cAddress hal::I2cMasterRegisterAccess::address private
Definition at line 19 of file I2cRegisterAccess.hpp.
Referenced by ReadRegister(), and WriteRegister().
dataRegister
uint8_t hal::I2cMasterRegisterAccess::dataRegister = 0 private
Definition at line 21 of file I2cRegisterAccess.hpp.
Referenced by ReadRegister(), and WriteRegister().
i2cMaster
I2cMaster& hal::I2cMasterRegisterAccess::i2cMaster private
Definition at line 18 of file I2cRegisterAccess.hpp.
Referenced by ReadRegister(), and WriteRegister().
onDone
infra::Function<void()> hal::I2cMasterRegisterAccess::onDone private
Definition at line 24 of file I2cRegisterAccess.hpp.
Referenced by ReadRegister(), and WriteRegister().
readData
infra::ByteRange hal::I2cMasterRegisterAccess::readData private
Definition at line 22 of file I2cRegisterAccess.hpp.
Referenced by ReadRegister().
writeData
infra::ConstByteRange hal::I2cMasterRegisterAccess::writeData private
Definition at line 23 of file I2cRegisterAccess.hpp.
Referenced by WriteRegister().
The documentation for this class was generated from the following files:
I2cRegisterAccess.hpp
I2cRegisterAccess.cpp