EMil: infra::ProtoParser Class Reference
infra::ProtoParser Class Reference
#include <ProtoParser.hpp>
Public Types
using Field = std::pair< infra::Variant< uint32_t, uint64_t, ProtoLengthDelimited >, uint32_t >
Public Member Functions
ProtoParser (infra::DataInputStream inputStream)
bool Empty () const
uint64_t GetVarInt ()
uint32_t GetFixed32 ()
uint64_t GetFixed64 ()
Field GetField ()
Private Attributes
infra::LimitedStreamReader limitedReader
infra::DataInputStream input
Detailed Description
Definition at line 31 of file ProtoParser.hpp.
Member Typedef Documentation
Field
using infra::ProtoParser::Field = std::pair<infra::Variant<uint32_t, uint64_t, ProtoLengthDelimited>, uint32_t>
Definition at line 34 of file ProtoParser.hpp.
Constructor & Destructor Documentation
ProtoParser()
infra::ProtoParser::ProtoParser (infra::DataInputStream inputStream) explicit
Definition at line 44 of file ProtoParser.cpp.
         : limitedReader(inputStream.Reader(), inputStream.Available())
         , input(limitedReader, inputStream.ErrorPolicy())
     {}
Member Function Documentation
Empty()
bool infra::ProtoParser::Empty () const
Definition at line 49 of file ProtoParser.cpp.
References infra::InputStream::Empty(), and input.
     {
         return input.Empty();
     }
GetField()
ProtoParser::Field infra::ProtoParser::GetField ()
Definition at line 85 of file ProtoParser.cpp.
References infra::InputStream::Failed(), GetFixed32(), GetFixed64(), GetVarInt(), and input.
     {
         uint32_t x = static_cast<uint32_t>(GetVarInt());
         uint8_t type = x & 7;
         uint32_t fieldNumber = x >> 3;
         switch (type)
         {
             case 0:
                 return std::make_pair(GetVarInt(), fieldNumber);
             case 1:
                 return std::make_pair(GetFixed64(), fieldNumber);
             case 2:
                 return std::make_pair(ProtoLengthDelimited(input, static_cast<uint32_t>(GetVarInt())), fieldNumber);
             case 5:
                 return std::make_pair(GetFixed32(), fieldNumber);
             default:
                 if (!input.Failed())
                     std::abort();
                 // Todo: Report proper error
                 return std::make_pair(static_cast<uint32_t>(0), 0);
         }
     }
GetFixed32()
uint32_t infra::ProtoParser::GetFixed32 ()
Definition at line 71 of file ProtoParser.cpp.
References input.
Referenced by GetField().
     {
         uint32_t result = 0;
         input >> result;
         return result;
     }
GetFixed64()
uint64_t infra::ProtoParser::GetFixed64 ()
Definition at line 78 of file ProtoParser.cpp.
References input.
Referenced by GetField().
     {
         uint64_t result = 0;
         input >> result;
         return result;
     }
GetVarInt()
uint64_t infra::ProtoParser::GetVarInt ()
Definition at line 54 of file ProtoParser.cpp.
References infra::InputStream::Failed(), and input.
Referenced by GetField().
     {
         uint64_t result = 0;
         uint8_t byte = 0;
         uint8_t shift = 0;
         do
         {
             input >> byte;
             result += static_cast<uint64_t>(byte & 0x7f) << shift;                                                      //TICS !POR#006
             shift += 7;
         } while (!input.Failed() && (byte & 0x80) != 0);
         return result;
     }
Member Data Documentation
input
infra::DataInputStream infra::ProtoParser::input private
Definition at line 47 of file ProtoParser.hpp.
Referenced by Empty(), GetField(), GetFixed32(), GetFixed64(), and GetVarInt().
limitedReader
infra::LimitedStreamReader infra::ProtoParser::limitedReader private
Definition at line 46 of file ProtoParser.hpp.
The documentation for this class was generated from the following files:
ProtoParser.hpp
ProtoParser.cpp