EMil: application::UpgradePackBuilder Class Reference
application::UpgradePackBuilder Class Reference
#include <UpgradePackBuilder.hpp>
Classes
struct HeaderInfo
Public Member Functions
UpgradePackBuilder (const HeaderInfo &headerInfo, std::vector< std::unique_ptr< Input >> &&inputs, ImageSigner &signer)
std::vector< uint8_t > & UpgradePack ()
void WriteUpgradePack (const std::string &fileName, hal::FileSystem &fileSystem)
Private Member Functions
void CreateUpgradePack ()
void AddPrologueAndSignature ()
void AddEpilogue ()
void AddImages ()
void AssignZeroFilled (const std::string &data, infra::MemoryRange< char > destination) const
void CheckSignature ()
Private Attributes
HeaderInfo headerInfo
std::vector< std::unique_ptr< Input > > inputs
ImageSigner & signer
std::vector< uint8_t > upgradePack
Detailed Description
Definition at line 16 of file UpgradePackBuilder.hpp.
Constructor & Destructor Documentation
UpgradePackBuilder()
application::UpgradePackBuilder::UpgradePackBuilder (const HeaderInfo & headerInfo, std::vector< std::unique_ptr< Input >> && inputs, ImageSigner & signer)
Definition at line 8 of file UpgradePackBuilder.cpp.
References CreateUpgradePack().
         : headerInfo(headerInfo)
         , inputs(std::move(inputs))
         , signer(signer)
     {
         CreateUpgradePack();
     }
Member Function Documentation
AddEpilogue()
void application::UpgradePackBuilder::AddEpilogue () private
Definition at line 53 of file UpgradePackBuilder.cpp.
References AssignZeroFilled(), application::UpgradePackBuilder::HeaderInfo::componentName, application::UpgradePackHeaderEpilogue::componentName, application::UpgradePackBuilder::HeaderInfo::componentVersion, application::UpgradePackHeaderEpilogue::componentVersion, headerInfo, application::UpgradePackHeaderEpilogue::headerLength, application::UpgradePackHeaderEpilogue::headerVersion, inputs, application::UpgradePackHeaderEpilogue::numberOfImages, application::UpgradePackBuilder::HeaderInfo::productName, application::UpgradePackHeaderEpilogue::productName, application::UpgradePackBuilder::HeaderInfo::productVersion, application::UpgradePackHeaderEpilogue::productVersion, application::ImageSigner::SignatureLength(), signer, and upgradePack.
Referenced by CreateUpgradePack().
     {
         UpgradePackHeaderEpilogue epilogue = {};
         epilogue.headerVersion = 1;
         epilogue.headerLength = sizeof(UpgradePackHeaderPrologue) + signer.SignatureLength() + sizeof(UpgradePackHeaderEpilogue);
         epilogue.numberOfImages = inputs.size();
         AssignZeroFilled(headerInfo.productName, epilogue.productName);
         AssignZeroFilled(headerInfo.productVersion, epilogue.productVersion);
         AssignZeroFilled(headerInfo.componentName, epilogue.componentName);
         epilogue.componentVersion = headerInfo.componentVersion;
         upgradePack.assign(reinterpret_cast<const uint8_t*>(&epilogue), reinterpret_cast<const uint8_t*>(&epilogue + 1));
     }
AddImages()
void application::UpgradePackBuilder::AddImages () private
Definition at line 68 of file UpgradePackBuilder.cpp.
References inputs, and upgradePack.
Referenced by CreateUpgradePack().
     {
         for (const std::unique_ptr<Input>& input : inputs)
         {
             std::vector<uint8_t> image = input->Image();
             upgradePack.insert(upgradePack.end(), image.begin(), image.end());
         }
     }
AddPrologueAndSignature()
void application::UpgradePackBuilder::AddPrologueAndSignature () private
Definition at line 37 of file UpgradePackBuilder.cpp.
References application::UpgradePackHeaderPrologue::errorCode, application::ImageSigner::ImageSignature(), application::UpgradePackHeaderPrologue::magic, application::readyToDeploy, application::UpgradePackHeaderPrologue::signatureLength, application::ImageSigner::SignatureMethod(), application::UpgradePackHeaderPrologue::signatureMethod, application::UpgradePackHeaderPrologue::signedContentsLength, signer, application::UpgradePackHeaderPrologue::status, upgradePack, and application::upgradePackMagic.
Referenced by CreateUpgradePack().
     {
         std::vector<uint8_t> signature = signer.ImageSignature(upgradePack);
         UpgradePackHeaderPrologue prologue = {};
         prologue.status = UpgradePackStatus::readyToDeploy;
         prologue.magic = upgradePackMagic;
         prologue.errorCode = 0xffffffff;
         prologue.signedContentsLength = upgradePack.size();
         prologue.signatureMethod = signer.SignatureMethod();
         prologue.signatureLength = static_cast<uint16_t>(signature.size());
         upgradePack.insert(upgradePack.begin(), signature.begin(), signature.end());
         upgradePack.insert(upgradePack.begin(), reinterpret_cast<const uint8_t*>(&prologue), reinterpret_cast<const uint8_t*>(&prologue + 1));
     }
AssignZeroFilled()
void application::UpgradePackBuilder::AssignZeroFilled (const std::string & data, infra::MemoryRange< char > destination) const private
Definition at line 77 of file UpgradePackBuilder.cpp.
References infra::MemoryRange< T >::begin(), infra::data, and infra::MemoryRange< T >::size().
Referenced by AddEpilogue().
     {
         std::copy(data.begin(), data.begin() + std::min(data.size(), destination.size()), destination.begin());
     }
CheckSignature()
void application::UpgradePackBuilder::CheckSignature () private
Definition at line 82 of file UpgradePackBuilder.cpp.
References application::ImageSigner::CheckSignature(), application::ImageSigner::SignatureLength(), signer, and upgradePack.
Referenced by CreateUpgradePack().
     {
         std::vector<uint8_t> signature(upgradePack.begin() + sizeof(UpgradePackHeaderPrologue), upgradePack.begin() + sizeof(UpgradePackHeaderPrologue) + signer.SignatureLength());
         if (!signer.CheckSignature(signature, std::vector<uint8_t>(upgradePack.begin() + sizeof(UpgradePackHeaderPrologue) + signer.SignatureLength(), upgradePack.end())))
             throw SignatureDoesNotVerifyException();
     }
CreateUpgradePack()
void application::UpgradePackBuilder::CreateUpgradePack () private
Definition at line 28 of file UpgradePackBuilder.cpp.
References AddEpilogue(), AddImages(), AddPrologueAndSignature(), and CheckSignature().
Referenced by UpgradePackBuilder().
     {
         AddEpilogue();
         AddImages();
         AddPrologueAndSignature();
         CheckSignature();
     }
UpgradePack()
std::vector< uint8_t > & application::UpgradePackBuilder::UpgradePack ()
Definition at line 16 of file UpgradePackBuilder.cpp.
References upgradePack.
Referenced by application::ReferenceUpgradePackBuilderFacade::PostBuilder().
     {
         return upgradePack;
     }
WriteUpgradePack()
void application::UpgradePackBuilder::WriteUpgradePack (const std::string & fileName, hal::FileSystem & fileSystem)
Definition at line 21 of file UpgradePackBuilder.cpp.
References upgradePack, and hal::FileSystem::WriteBinaryFile().
Referenced by application::UpgradePackBuilderFacade::TryBuild().
     {
         assert(!upgradePack.empty());
         fileSystem.WriteBinaryFile(fileName, upgradePack);
     }
Member Data Documentation
headerInfo
HeaderInfo application::UpgradePackBuilder::headerInfo private
Definition at line 42 of file UpgradePackBuilder.hpp.
Referenced by AddEpilogue().
inputs
std::vector<std::unique_ptr<Input> > application::UpgradePackBuilder::inputs private
Definition at line 43 of file UpgradePackBuilder.hpp.
Referenced by AddEpilogue(), and AddImages().
signer
ImageSigner& application::UpgradePackBuilder::signer private
Definition at line 44 of file UpgradePackBuilder.hpp.
Referenced by AddEpilogue(), AddPrologueAndSignature(), and CheckSignature().
upgradePack
std::vector<uint8_t> application::UpgradePackBuilder::upgradePack private
Definition at line 45 of file UpgradePackBuilder.hpp.
Referenced by AddEpilogue(), AddImages(), AddPrologueAndSignature(), CheckSignature(), UpgradePack(), and WriteUpgradePack().
The documentation for this class was generated from the following files:
UpgradePackBuilder.hpp
UpgradePackBuilder.cpp