EMil: services::ConnectionStub::StreamWriterStub Class Reference
services::ConnectionStub::StreamWriterStub Class Reference
Public Member Functions
StreamWriterStub (ConnectionStub &connection, std::size_t size)
Public Member Functions inherited from infra::StreamWriter
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Private Member Functions
virtual void Insert (infra::ConstByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
Private Attributes
ConnectionStub & connection
std::size_t size
std::size_t offset = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 36 of file ConnectionStub.hpp.
Constructor & Destructor Documentation
StreamWriterStub()
services::ConnectionStub::StreamWriterStub::StreamWriterStub (ConnectionStub & connection, std::size_t size) explicit
Definition at line 62 of file ConnectionStub.cpp.
         : connection(connection)
         , size(size)
     {}
Member Function Documentation
Available()
std::size_t services::ConnectionStub::StreamWriterStub::Available () const override private virtual
Implements infra::StreamWriter.
Definition at line 74 of file ConnectionStub.cpp.
     {
         return size - offset;
     }
Insert()
void services::ConnectionStub::StreamWriterStub::Insert (infra::ConstByteRange range, infra::StreamErrorPolicy & errorPolicy) override private virtual
Implements infra::StreamWriter.
Definition at line 67 of file ConnectionStub.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         assert(range.size() + offset <= size);
         offset += range.size();
         connection.sentData.insert(connection.sentData.end(), range.begin(), range.end());
     }
Member Data Documentation
connection
ConnectionStub& services::ConnectionStub::StreamWriterStub::connection private
Definition at line 47 of file ConnectionStub.hpp.
offset
std::size_t services::ConnectionStub::StreamWriterStub::offset = 0 private
Definition at line 49 of file ConnectionStub.hpp.
size
std::size_t services::ConnectionStub::StreamWriterStub::size private
Definition at line 48 of file ConnectionStub.hpp.
The documentation for this class was generated from the following files:
ConnectionStub.hpp
ConnectionStub.cpp