EMil: infra::BoundedPriorityQueue< T, Max, Compare > Class Template Reference
infra::BoundedPriorityQueue< T, Max, Compare > Class Template Reference
#include <BoundedPriorityQueue.hpp>
Public Types
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef BoundedVector< T >::template WithMaxSize< Max >::iterator iterator
typedef BoundedVector< T >::template WithMaxSize< Max >::const_iterator const_iterator
typedef BoundedVector< T >::template WithMaxSize< Max >::reverse_iterator reverse_iterator
typedef BoundedVector< T >::template WithMaxSize< Max >::const_reverse_iterator const_reverse_iterator
Public Member Functions
BoundedPriorityQueue (const Compare &comp=Compare())
template<class InputIterator >
BoundedPriorityQueue (InputIterator first, InputIterator last, const Compare &comp=Compare())
BoundedPriorityQueue (const BoundedPriorityQueue &other)
BoundedPriorityQueue (BoundedPriorityQueue &&other)
BoundedPriorityQueue & operator= (const BoundedPriorityQueue &other)
BoundedPriorityQueue & operator= (BoundedPriorityQueue &&other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool empty () const
bool full () const
size_type size () const
reference top ()
const_reference top () const
const value_type & operator[] (size_type position) const
void push (const_reference value)
void push (value_type &&value)
void pop ()
void clear ()
void erase (iterator position)
template<class... Args>
void emplace (Args &&... args)
void swap (BoundedPriorityQueue &x)
Private Attributes
BoundedVector< value_type >::template WithMaxSize< Max > values
Compare compare
Detailed Description
template<class T, std::size_t Max, class Compare = std::less<T>>
class infra::BoundedPriorityQueue< T, Max, Compare >
Definition at line 12 of file BoundedPriorityQueue.hpp.
Member Typedef Documentation
const_iterator
template<class T, std::size_t Max, class Compare = std::less<T>> typedef BoundedVector<T>::template WithMaxSize<Max>::const_iterator infra::BoundedPriorityQueue< T, Max, Compare >::const_iterator
Definition at line 20 of file BoundedPriorityQueue.hpp.
const_reference
template<class T, std::size_t Max, class Compare = std::less<T>> typedef const T& infra::BoundedPriorityQueue< T, Max, Compare >::const_reference
Definition at line 17 of file BoundedPriorityQueue.hpp.
const_reverse_iterator
template<class T, std::size_t Max, class Compare = std::less<T>> typedef BoundedVector<T>::template WithMaxSize<Max>::const_reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::const_reverse_iterator
Definition at line 22 of file BoundedPriorityQueue.hpp.
iterator
template<class T, std::size_t Max, class Compare = std::less<T>> typedef BoundedVector<T>::template WithMaxSize<Max>::iterator infra::BoundedPriorityQueue< T, Max, Compare >::iterator
Definition at line 19 of file BoundedPriorityQueue.hpp.
reference
template<class T, std::size_t Max, class Compare = std::less<T>> typedef T& infra::BoundedPriorityQueue< T, Max, Compare >::reference
Definition at line 16 of file BoundedPriorityQueue.hpp.
reverse_iterator
template<class T, std::size_t Max, class Compare = std::less<T>> typedef BoundedVector<T>::template WithMaxSize<Max>::reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::reverse_iterator
Definition at line 21 of file BoundedPriorityQueue.hpp.
size_type
template<class T, std::size_t Max, class Compare = std::less<T>> typedef std::size_t infra::BoundedPriorityQueue< T, Max, Compare >::size_type
Definition at line 18 of file BoundedPriorityQueue.hpp.
value_type
template<class T, std::size_t Max, class Compare = std::less<T>> typedef T infra::BoundedPriorityQueue< T, Max, Compare >::value_type
Definition at line 15 of file BoundedPriorityQueue.hpp.
Constructor & Destructor Documentation
BoundedPriorityQueue() [1/4]
template<class T , std::size_t Max, class Compare> infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue (const Compare & comp = Compare()) explicit
Definition at line 123 of file BoundedPriorityQueue.hpp.
         : compare(comp)
     {}
BoundedPriorityQueue() [2/4]
template<class T , std::size_t Max, class Compare> template<class InputIterator > infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue (InputIterator first, InputIterator last, const Compare & comp = Compare())
Definition at line 129 of file BoundedPriorityQueue.hpp.
References infra::BoundedVector< T >::begin(), infra::BoundedPriorityQueue< T, Max, Compare >::compare, infra::BoundedVector< T >::end(), and infra::BoundedPriorityQueue< T, Max, Compare >::values.
         : values(first, last)
         , compare(comp)
     {
         std::make_heap(values.begin(), values.end(), compare);
     }
BoundedPriorityQueue() [3/4]
template<class T , std::size_t Max, class Compare> infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue (const BoundedPriorityQueue< T, Max, Compare > & other)
Definition at line 137 of file BoundedPriorityQueue.hpp.
         : values(other.values)
         , compare(other.compare)
     {}
BoundedPriorityQueue() [4/4]
template<class T , std::size_t Max, class Compare> infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue (BoundedPriorityQueue< T, Max, Compare > && other)
Definition at line 143 of file BoundedPriorityQueue.hpp.
         : values(std::move(other.values))
         , compare(std::move(other.compare))
     {}
Member Function Documentation
begin() [1/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::iterator infra::BoundedPriorityQueue< T, Max, Compare >::begin ()
Definition at line 167 of file BoundedPriorityQueue.hpp.
     {
         return values.begin();
     }
begin() [2/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_iterator infra::BoundedPriorityQueue< T, Max, Compare >::begin () const
Definition at line 173 of file BoundedPriorityQueue.hpp.
     {
         return values.begin();
     }
cbegin()
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_iterator infra::BoundedPriorityQueue< T, Max, Compare >::cbegin () const
Definition at line 215 of file BoundedPriorityQueue.hpp.
     {
         return values.cbegin();
     }
cend()
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_iterator infra::BoundedPriorityQueue< T, Max, Compare >::cend () const
Definition at line 221 of file BoundedPriorityQueue.hpp.
     {
         return values.cend();
     }
clear()
template<class T , std::size_t Max, class Compare > void infra::BoundedPriorityQueue< T, Max, Compare >::clear ()
Definition at line 296 of file BoundedPriorityQueue.hpp.
     {
         values.clear();
     }
crbegin()
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::crbegin () const
Definition at line 227 of file BoundedPriorityQueue.hpp.
     {
         return values.crbegin();
     }
crend()
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::crend () const
Definition at line 233 of file BoundedPriorityQueue.hpp.
     {
         return values.crend();
     }
emplace()
template<class T , std::size_t Max, class Compare > template<class... Args> void infra::BoundedPriorityQueue< T, Max, Compare >::emplace (Args &&... args)
Definition at line 310 of file BoundedPriorityQueue.hpp.
     {
         values.emplace_back(std::forward<Args>(args)...);
         std::push_heap(values.begin(), values.end(), compare);
     }
empty()
template<class T , std::size_t Max, class Compare > bool infra::BoundedPriorityQueue< T, Max, Compare >::empty () const
Definition at line 239 of file BoundedPriorityQueue.hpp.
     {
         return values.empty();
     }
end() [1/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::iterator infra::BoundedPriorityQueue< T, Max, Compare >::end ()
Definition at line 179 of file BoundedPriorityQueue.hpp.
     {
         return values.end();
     }
end() [2/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_iterator infra::BoundedPriorityQueue< T, Max, Compare >::end () const
Definition at line 185 of file BoundedPriorityQueue.hpp.
     {
         return values.end();
     }
erase()
template<class T , std::size_t Max, class Compare > void infra::BoundedPriorityQueue< T, Max, Compare >::erase (iterator position)
Definition at line 302 of file BoundedPriorityQueue.hpp.
References infra::erase_heap().
     {
         erase_heap(values.begin(), values.end(), position, compare);
         values.pop_back();
     }
full()
template<class T , std::size_t Max, class Compare > bool infra::BoundedPriorityQueue< T, Max, Compare >::full () const
Definition at line 245 of file BoundedPriorityQueue.hpp.
     {
         return values.full();
     }
operator=() [1/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare > & infra::BoundedPriorityQueue< T, Max, Compare >::operator= (const BoundedPriorityQueue< T, Max, Compare > & other)
Definition at line 149 of file BoundedPriorityQueue.hpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::compare, and infra::BoundedPriorityQueue< T, Max, Compare >::values.
     {
         values = other.values;
         compare = other.compare;
         return *this;
     }
operator=() [2/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare > & infra::BoundedPriorityQueue< T, Max, Compare >::operator= (BoundedPriorityQueue< T, Max, Compare > && other)
Definition at line 158 of file BoundedPriorityQueue.hpp.
     {
         values = std::move(other.values);
         compare = std::move(other.compare);
         return *this;
     }
operator[]()
template<class T , std::size_t Max, class Compare > const BoundedPriorityQueue< T, Max, Compare >::value_type & infra::BoundedPriorityQueue< T, Max, Compare >::operator[] (size_type position) const
Definition at line 269 of file BoundedPriorityQueue.hpp.
     {
         return values[position];
     }
pop()
template<class T , std::size_t Max, class Compare > void infra::BoundedPriorityQueue< T, Max, Compare >::pop ()
Definition at line 289 of file BoundedPriorityQueue.hpp.
     {
         std::pop_heap(values.begin(), values.end(), compare);
         values.pop_back();
     }
push() [1/2]
template<class T , std::size_t Max, class Compare > void infra::BoundedPriorityQueue< T, Max, Compare >::push (const_reference value)
Definition at line 275 of file BoundedPriorityQueue.hpp.
References value.
     {
         values.push_back(value);
         std::push_heap(values.begin(), values.end(), compare);
     }
push() [2/2]
template<class T , std::size_t Max, class Compare > void infra::BoundedPriorityQueue< T, Max, Compare >::push (value_type && value)
Definition at line 282 of file BoundedPriorityQueue.hpp.
References value.
     {
         values.push_back(std::move(value));
         std::push_heap(values.begin(), values.end(), compare);
     }
rbegin() [1/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::rbegin ()
Definition at line 191 of file BoundedPriorityQueue.hpp.
     {
         return values.rbegin();
     }
rbegin() [2/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::rbegin () const
Definition at line 197 of file BoundedPriorityQueue.hpp.
     {
         return values.rbegin();
     }
rend() [1/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::rend ()
Definition at line 203 of file BoundedPriorityQueue.hpp.
     {
         return values.rend();
     }
rend() [2/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_reverse_iterator infra::BoundedPriorityQueue< T, Max, Compare >::rend () const
Definition at line 209 of file BoundedPriorityQueue.hpp.
     {
         return values.rend();
     }
size()
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::size_type infra::BoundedPriorityQueue< T, Max, Compare >::size () const
Definition at line 251 of file BoundedPriorityQueue.hpp.
     {
         return values.size();
     }
swap()
template<class T , std::size_t Max, class Compare > void infra::BoundedPriorityQueue< T, Max, Compare >::swap (BoundedPriorityQueue< T, Max, Compare > & x)
Definition at line 317 of file BoundedPriorityQueue.hpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::compare, infra::swap(), and infra::BoundedPriorityQueue< T, Max, Compare >::values.
     {
         using std::swap;
         swap(values, other.values);
         swap(compare, other.compare);
     }
top() [1/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::reference infra::BoundedPriorityQueue< T, Max, Compare >::top ()
Definition at line 257 of file BoundedPriorityQueue.hpp.
     {
         return values.front();
     }
top() [2/2]
template<class T , std::size_t Max, class Compare > BoundedPriorityQueue< T, Max, Compare >::const_reference infra::BoundedPriorityQueue< T, Max, Compare >::top () const
Definition at line 263 of file BoundedPriorityQueue.hpp.
     {
         return values.front();
     }
Member Data Documentation
compare
template<class T, std::size_t Max, class Compare = std::less<T>> Compare infra::BoundedPriorityQueue< T, Max, Compare >::compare private
Definition at line 72 of file BoundedPriorityQueue.hpp.
Referenced by infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue(), infra::BoundedPriorityQueue< T, Max, Compare >::operator=(), and infra::BoundedPriorityQueue< T, Max, Compare >::swap().
values
template<class T, std::size_t Max, class Compare = std::less<T>> BoundedVector<value_type>::template WithMaxSize<Max> infra::BoundedPriorityQueue< T, Max, Compare >::values private
Definition at line 71 of file BoundedPriorityQueue.hpp.
Referenced by infra::BoundedPriorityQueue< T, Max, Compare >::BoundedPriorityQueue(), infra::BoundedPriorityQueue< T, Max, Compare >::operator=(), and infra::BoundedPriorityQueue< T, Max, Compare >::swap().
The documentation for this class was generated from the following file:
BoundedPriorityQueue.hpp