EMil: services::EventDispatcherWithNetwork Class Reference
services::EventDispatcherWithNetwork Class Reference
#include <EventDispatcherWithNetwork.hpp>
Public Member Functions
EventDispatcherWithNetwork ()
~EventDispatcherWithNetwork ()
void RegisterConnection (const infra::SharedPtr< ConnectionBsd > &connection)
void RegisterListener (ListenerBsd &listener)
void DeregisterListener (ListenerBsd &listener)
void DeregisterConnector (ConnectorBsd &connector)
void RegisterDatagram (const infra::SharedPtr< DatagramBsd > &datagram)
virtual infra::SharedPtr< void > Listen (uint16_t port, services::ServerConnectionObserverFactory &factory, IPVersions versions) override
virtual void Connect (ClientConnectionObserverFactory &factory) override
virtual void CancelConnect (ClientConnectionObserverFactory &factory) override
virtual infra::SharedPtr< DatagramExchange > Listen (DatagramExchangeObserver &observer, uint16_t port, IPVersions versions=IPVersions::both) override
virtual infra::SharedPtr< DatagramExchange > Listen (DatagramExchangeObserver &observer, IPVersions versions=IPVersions::both) override
virtual infra::SharedPtr< DatagramExchange > Connect (DatagramExchangeObserver &observer, UdpSocket remote) override
virtual infra::SharedPtr< DatagramExchange > Connect (DatagramExchangeObserver &observer, uint16_t localPort, UdpSocket remote) override
EventDispatcherWithNetwork ()
~EventDispatcherWithNetwork ()
void RegisterConnection (const infra::SharedPtr< ConnectionWin > &connection)
void RegisterListener (ListenerWin &listener)
void DeregisterListener (ListenerWin &listener)
void DeregisterConnector (ConnectorWin &connector)
void RegisterDatagram (const infra::SharedPtr< DatagramWin > &datagram)
virtual infra::SharedPtr< void > Listen (uint16_t port, services::ServerConnectionObserverFactory &factory, IPVersions versions) override
virtual void Connect (ClientConnectionObserverFactory &factory) override
virtual void CancelConnect (ClientConnectionObserverFactory &factory) override
virtual infra::SharedPtr< DatagramExchange > Listen (DatagramExchangeObserver &observer, uint16_t port, IPVersions versions=IPVersions::both) override
virtual infra::SharedPtr< DatagramExchange > Listen (DatagramExchangeObserver &observer, IPVersions versions=IPVersions::both) override
virtual infra::SharedPtr< DatagramExchange > Connect (DatagramExchangeObserver &observer, UdpSocket remote) override
virtual infra::SharedPtr< DatagramExchange > Connect (DatagramExchangeObserver &observer, uint16_t localPort, UdpSocket remote) override
Protected Member Functions
virtual void RequestExecution ()
virtual void Idle () override
virtual void RequestExecution ()
virtual void Idle () override
Protected Member Functions inherited from services::ConnectionFactory
ConnectionFactory ()=default
ConnectionFactory (const ConnectionFactory &other)=delete
ConnectionFactory & operator= (const ConnectionFactory &other)=delete
~ConnectionFactory ()=default
Protected Member Functions inherited from services::DatagramFactory
DatagramFactory ()=default
DatagramFactory (const DatagramFactory &other)=delete
DatagramFactory & operator= (const DatagramFactory &other)=delete
virtual ~DatagramFactory ()=default
Private Member Functions
void AddFileDescriptorToSet (int fileDescriptor, fd_set &set)
Private Attributes
std::list< infra::WeakPtr< ConnectionBsd > > connections
infra::IntrusiveList< ListenerBsd > listeners
std::list< ConnectorBsd > connectors
std::list< infra::WeakPtr< DatagramBsd > > datagrams
int numberOfFileDescriptors = 0
int wakeUpEvent [2] { 0 }
fd_set readFileDescriptors
fd_set writeFileDescriptors
fd_set exceptFileDescriptors
std::list< infra::WeakPtr< ConnectionWin > > connections
infra::IntrusiveList< ListenerWin > listeners
std::list< ConnectorWin > connectors
std::list< infra::WeakPtr< DatagramWin > > datagrams
WSAEVENT wakeUpEvent = WSACreateEvent()
Detailed Description
Definition at line 10 of file network_bsd/EventDispatcherWithNetwork.hpp.
Constructor & Destructor Documentation
EventDispatcherWithNetwork() [1/2]
services::EventDispatcherWithNetwork::EventDispatcherWithNetwork ()
Definition at line 17 of file network_bsd/EventDispatcherWithNetwork.cpp.
References wakeUpEvent.
     {
         if (pipe(wakeUpEvent) == -1)
             std::abort();
         SetNonBlocking(wakeUpEvent[0]);
         SetNonBlocking(wakeUpEvent[1]);
     }
~EventDispatcherWithNetwork() [1/2]
services::EventDispatcherWithNetwork::~EventDispatcherWithNetwork ()
Definition at line 26 of file network_bsd/EventDispatcherWithNetwork.cpp.
References wakeUpEvent.
     {
         close(wakeUpEvent[0]);
         close(wakeUpEvent[1]);
     }
EventDispatcherWithNetwork() [2/2]
services::EventDispatcherWithNetwork::EventDispatcherWithNetwork ()
~EventDispatcherWithNetwork() [2/2]
services::EventDispatcherWithNetwork::~EventDispatcherWithNetwork ()
Member Function Documentation
AddFileDescriptorToSet()
void services::EventDispatcherWithNetwork::AddFileDescriptorToSet (int fileDescriptor, fd_set & set) private
Definition at line 224 of file network_bsd/EventDispatcherWithNetwork.cpp.
References numberOfFileDescriptors.
Referenced by Idle().
     {
         FD_SET(fileDescriptor, &set);
         numberOfFileDescriptors = std::max(numberOfFileDescriptors, fileDescriptor);
     }
CancelConnect() [1/2]
virtual void services::EventDispatcherWithNetwork::CancelConnect (ClientConnectionObserverFactory & factory) override virtual
Implements services::ConnectionFactory.
CancelConnect() [2/2]
void services::EventDispatcherWithNetwork::CancelConnect (ClientConnectionObserverFactory & factory) override virtual
Implements services::ConnectionFactory.
Definition at line 76 of file network_bsd/EventDispatcherWithNetwork.cpp.
References connectors.
     {
         for (auto c = connectors.begin(); c != connectors.end(); ++c)
             if (&c->factory == &factory)
             {
                 connectors.erase(c);
                 return;
             }
         std::abort();
     }
Connect() [1/6]
virtual void services::EventDispatcherWithNetwork::Connect (ClientConnectionObserverFactory & factory) override virtual
Implements services::ConnectionFactory.
Connect() [2/6]
void services::EventDispatcherWithNetwork::Connect (ClientConnectionObserverFactory & factory) override virtual
Implements services::ConnectionFactory.
Definition at line 70 of file network_bsd/EventDispatcherWithNetwork.cpp.
References services::ClientConnectionObserverFactory::Address(), connectors, and infra::Variant< T >::Is().
     {
         assert(factory.Address().Is<IPv4Address>());
         connectors.emplace_back(*this, factory);
     }
Connect() [3/6]
virtual infra::SharedPtr<DatagramExchange> services::EventDispatcherWithNetwork::Connect (DatagramExchangeObserver & observer, UdpSocket remote) override virtual
Implements services::DatagramFactory.
Connect() [4/6]
infra::SharedPtr< DatagramExchange > services::EventDispatcherWithNetwork::Connect (DatagramExchangeObserver & observer, UdpSocket remote) override virtual
Implements services::DatagramFactory.
Definition at line 104 of file network_bsd/EventDispatcherWithNetwork.cpp.
References RegisterDatagram().
     {
         auto result = infra::MakeSharedOnHeap<DatagramBsd>(*this, remote, observer);
         RegisterDatagram(result);
         return result;
     }
Connect() [5/6]
virtual infra::SharedPtr<DatagramExchange> services::EventDispatcherWithNetwork::Connect (DatagramExchangeObserver & observer, uint16_t localPort, UdpSocket remote) override virtual
Implements services::DatagramFactory.
Connect() [6/6]
infra::SharedPtr< DatagramExchange > services::EventDispatcherWithNetwork::Connect (DatagramExchangeObserver & observer, uint16_t localPort, UdpSocket remote) override virtual
Implements services::DatagramFactory.
Definition at line 111 of file network_bsd/EventDispatcherWithNetwork.cpp.
References RegisterDatagram().
     {
         auto result = infra::MakeSharedOnHeap<DatagramBsd>(*this, localPort, remote, observer);
         RegisterDatagram(result);
         return result;
     }
DeregisterConnector() [1/2]
void services::EventDispatcherWithNetwork::DeregisterConnector (ConnectorWin & connector)
Definition at line 34 of file network_win/EventDispatcherWithNetwork.cpp.
References connectors.
     {
         for (auto c = connectors.begin(); c != connectors.end(); ++c)
             if (&*c == &connector)
             {
                 connectors.erase(c);
                 return;
             }
         std::abort();
     }
DeregisterConnector() [2/2]
void services::EventDispatcherWithNetwork::DeregisterConnector (ConnectorBsd & connector)
Definition at line 47 of file network_bsd/EventDispatcherWithNetwork.cpp.
References connectors.
Referenced by services::ConnectorBsd::Connected(), services::ConnectorWin::Connected(), services::ConnectorBsd::Failed(), and services::ConnectorWin::Failed().
     {
         for (auto c = connectors.begin(); c != connectors.end(); ++c)
             if (&*c == &connector)
             {
                 connectors.erase(c);
                 return;
             }
         std::abort();
     }
DeregisterListener() [1/2]
void services::EventDispatcherWithNetwork::DeregisterListener (ListenerWin & listener)
Definition at line 29 of file network_win/EventDispatcherWithNetwork.cpp.
References listeners.
     {
         listeners.erase(listener);
     }
DeregisterListener() [2/2]
void services::EventDispatcherWithNetwork::DeregisterListener (ListenerBsd & listener)
Definition at line 42 of file network_bsd/EventDispatcherWithNetwork.cpp.
References listeners.
Referenced by services::ListenerBsd::~ListenerBsd(), and services::ListenerWin::~ListenerWin().
     {
         listeners.erase(listener);
     }
Idle() [1/2]
virtual void services::EventDispatcherWithNetwork::Idle () override protected virtual
Idle() [2/2]
void services::EventDispatcherWithNetwork::Idle () override protected virtual
Definition at line 124 of file network_bsd/EventDispatcherWithNetwork.cpp.
References AddFileDescriptorToSet(), connections, connectors, datagrams, exceptFileDescriptors, listeners, infra::WeakPtr< T >::lock(), numberOfFileDescriptors, readFileDescriptors, wakeUpEvent, and writeFileDescriptors.
     {
         FD_ZERO(&readFileDescriptors);
         FD_ZERO(&writeFileDescriptors);
         FD_ZERO(&exceptFileDescriptors);
         AddFileDescriptorToSet(wakeUpEvent[0], readFileDescriptors);
         for (auto& listener : listeners)
             AddFileDescriptorToSet(listener.listenSocket, readFileDescriptors);
         for (auto& connector : connectors)
         {
             AddFileDescriptorToSet(connector.connectSocket, readFileDescriptors);
             AddFileDescriptorToSet(connector.connectSocket, exceptFileDescriptors);
         }
         for (auto& weakConnection : connections)
             if (infra::SharedPtr<ConnectionBsd> connection = weakConnection)
                 connection->TrySend();
         for (auto& weakConnection : connections)
         {
             if (infra::SharedPtr<ConnectionBsd> connection = weakConnection)
             {
                 AddFileDescriptorToSet(connection->socket, readFileDescriptors);
                 AddFileDescriptorToSet(connection->socket, writeFileDescriptors);
             }
         }
         for (auto& weakDatagram : datagrams)
             if (infra::SharedPtr<DatagramBsd> datagram = weakDatagram)
                 datagram->TrySend();
         for (auto& weakDatagram : datagrams)
         {
             if (infra::SharedPtr<DatagramBsd> datagram = weakDatagram)
             {
                 AddFileDescriptorToSet(datagram->socket, readFileDescriptors);
                 AddFileDescriptorToSet(datagram->socket, writeFileDescriptors);
             }
         }
         int result = 0;
         do
         {
             result = select(numberOfFileDescriptors + 1, &readFileDescriptors, &writeFileDescriptors, nullptr, nullptr);
         } while (result == -1 && errno == EINTR);
         if (result == -1)
             std::abort();
         while (true)
         {
             char dummy;
             if (read(wakeUpEvent[0], &dummy, 1) == -1)
                 if (errno == EAGAIN)
                     break;
                 else
                     std::abort();
         }
         for (auto& listener : listeners)
             if (FD_ISSET(listener.listenSocket, &readFileDescriptors))
                 listener.Accept();
         for (auto& connector : connectors)
         {
             if (FD_ISSET(connector.connectSocket, &readFileDescriptors))
                 connector.Connected();
             else if (FD_ISSET(connector.connectSocket, &exceptFileDescriptors))
                 connector.Failed();
         }
         for (auto& weakConnection : connections)
         {
             if (infra::SharedPtr<ConnectionBsd> connection = weakConnection)
             {
                 if (FD_ISSET(connection->socket, &readFileDescriptors))
                     connection->Receive();
                 if (FD_ISSET(connection->socket, &writeFileDescriptors))
                     connection->Send();
             }
         }
         for (auto& weakDatagram : datagrams)
         {
             if (infra::SharedPtr<DatagramBsd> datagram = weakDatagram)
             {
                 if (FD_ISSET(datagram->socket, &readFileDescriptors))
                     datagram->Receive();
                 if (FD_ISSET(datagram->socket, &writeFileDescriptors))
                     datagram->Send();
             }
         }
         connections.remove_if([](const infra::WeakPtr<ConnectionBsd>& connection) { return connection.lock() == nullptr; });
         datagrams.remove_if([](const infra::WeakPtr<DatagramBsd>& datagram) { return datagram.lock() == nullptr; });
     }
Listen() [1/6]
virtual infra::SharedPtr<void> services::EventDispatcherWithNetwork::Listen (uint16_t port, services::ServerConnectionObserverFactory & factory, IPVersions versions) override virtual
Implements services::ConnectionFactory.
Listen() [2/6]
infra::SharedPtr< void > services::EventDispatcherWithNetwork::Listen (uint16_t port, services::ServerConnectionObserverFactory & factory, IPVersions versions) override virtual
Implements services::ConnectionFactory.
Definition at line 64 of file network_bsd/EventDispatcherWithNetwork.cpp.
References services::ipv6.
     {
         assert(versions != IPVersions::ipv6);
         return infra::MakeSharedOnHeap<ListenerBsd>(*this, port, factory);
     }
Listen() [3/6]
virtual infra::SharedPtr<DatagramExchange> services::EventDispatcherWithNetwork::Listen (DatagramExchangeObserver & observer, uint16_t port, IPVersions versions = IPVersions::both) override virtual
Implements services::DatagramFactory.
Listen() [4/6]
infra::SharedPtr< DatagramExchange > services::EventDispatcherWithNetwork::Listen (DatagramExchangeObserver & observer, uint16_t port, IPVersions versions = IPVersions::both) override virtual
Implements services::DatagramFactory.
Definition at line 88 of file network_bsd/EventDispatcherWithNetwork.cpp.
References services::ipv6, and RegisterDatagram().
     {
         assert(versions != IPVersions::ipv6);
         auto result = infra::MakeSharedOnHeap<DatagramBsd>(*this, port, observer);
         RegisterDatagram(result);
         return result;
     }
Listen() [5/6]
virtual infra::SharedPtr<DatagramExchange> services::EventDispatcherWithNetwork::Listen (DatagramExchangeObserver & observer, IPVersions versions = IPVersions::both) override virtual
Implements services::DatagramFactory.
Listen() [6/6]
infra::SharedPtr< DatagramExchange > services::EventDispatcherWithNetwork::Listen (DatagramExchangeObserver & observer, IPVersions versions = IPVersions::both) override virtual
Implements services::DatagramFactory.
Definition at line 96 of file network_bsd/EventDispatcherWithNetwork.cpp.
References services::ipv6, and RegisterDatagram().
     {
         assert(versions != IPVersions::ipv6);
         auto result = infra::MakeSharedOnHeap<DatagramBsd>(*this, observer);
         RegisterDatagram(result);
         return result;
     }
RegisterConnection() [1/2]
void services::EventDispatcherWithNetwork::RegisterConnection (const infra::SharedPtr< ConnectionWin > & connection)
Definition at line 19 of file network_win/EventDispatcherWithNetwork.cpp.
References connections.
     {
         connections.push_back(connection);
     }
RegisterConnection() [2/2]
void services::EventDispatcherWithNetwork::RegisterConnection (const infra::SharedPtr< ConnectionBsd > & connection)
Definition at line 32 of file network_bsd/EventDispatcherWithNetwork.cpp.
References connections.
Referenced by services::ConnectionBsd::SetObserver(), and services::ConnectionWin::SetObserver().
     {
         connections.push_back(connection);
     }
RegisterDatagram() [1/2]
void services::EventDispatcherWithNetwork::RegisterDatagram (const infra::SharedPtr< DatagramWin > & datagram)
Definition at line 46 of file network_win/EventDispatcherWithNetwork.cpp.
References datagrams.
     {
         datagrams.push_back(datagram);
     }
RegisterDatagram() [2/2]
void services::EventDispatcherWithNetwork::RegisterDatagram (const infra::SharedPtr< DatagramBsd > & datagram)
Definition at line 59 of file network_bsd/EventDispatcherWithNetwork.cpp.
References datagrams.
Referenced by Connect(), and Listen().
     {
         datagrams.push_back(datagram);
     }
RegisterListener() [1/2]
void services::EventDispatcherWithNetwork::RegisterListener (ListenerWin & listener)
Definition at line 24 of file network_win/EventDispatcherWithNetwork.cpp.
References listeners.
     {
         listeners.push_back(listener);
     }
RegisterListener() [2/2]
void services::EventDispatcherWithNetwork::RegisterListener (ListenerBsd & listener)
Definition at line 37 of file network_bsd/EventDispatcherWithNetwork.cpp.
References listeners.
Referenced by services::ListenerBsd::ListenerBsd(), and services::ListenerWin::ListenerWin().
     {
         listeners.push_back(listener);
     }
RequestExecution() [1/2]
virtual void services::EventDispatcherWithNetwork::RequestExecution () protected virtual
RequestExecution() [2/2]
void services::EventDispatcherWithNetwork::RequestExecution () protected virtual
Definition at line 118 of file network_bsd/EventDispatcherWithNetwork.cpp.
References wakeUpEvent.
     {
         if (write(wakeUpEvent[1], "x", 1) == -1 && errno != EAGAIN)
             std::abort();
     }
Member Data Documentation
connections [1/2]
std::list<infra::WeakPtr<ConnectionWin> > services::EventDispatcherWithNetwork::connections private
Definition at line 41 of file network_win/EventDispatcherWithNetwork.hpp.
connections [2/2]
std::list<infra::WeakPtr<ConnectionBsd> > services::EventDispatcherWithNetwork::connections private
Definition at line 45 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by Idle(), and RegisterConnection().
connectors [1/2]
std::list<ConnectorWin> services::EventDispatcherWithNetwork::connectors private
Definition at line 43 of file network_win/EventDispatcherWithNetwork.hpp.
connectors [2/2]
std::list<ConnectorBsd> services::EventDispatcherWithNetwork::connectors private
Definition at line 47 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by CancelConnect(), Connect(), DeregisterConnector(), and Idle().
datagrams [1/2]
std::list<infra::WeakPtr<DatagramWin> > services::EventDispatcherWithNetwork::datagrams private
Definition at line 44 of file network_win/EventDispatcherWithNetwork.hpp.
datagrams [2/2]
std::list<infra::WeakPtr<DatagramBsd> > services::EventDispatcherWithNetwork::datagrams private
Definition at line 48 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by Idle(), and RegisterDatagram().
exceptFileDescriptors
fd_set services::EventDispatcherWithNetwork::exceptFileDescriptors private
Definition at line 53 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by Idle().
listeners [1/2]
infra::IntrusiveList<ListenerWin> services::EventDispatcherWithNetwork::listeners private
Definition at line 42 of file network_win/EventDispatcherWithNetwork.hpp.
listeners [2/2]
infra::IntrusiveList<ListenerBsd> services::EventDispatcherWithNetwork::listeners private
Definition at line 46 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by DeregisterListener(), Idle(), and RegisterListener().
numberOfFileDescriptors
int services::EventDispatcherWithNetwork::numberOfFileDescriptors = 0 private
Definition at line 49 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by AddFileDescriptorToSet(), and Idle().
readFileDescriptors
fd_set services::EventDispatcherWithNetwork::readFileDescriptors private
Definition at line 51 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by Idle().
wakeUpEvent [1/2]
WSAEVENT services::EventDispatcherWithNetwork::wakeUpEvent = WSACreateEvent() private
Definition at line 45 of file network_win/EventDispatcherWithNetwork.hpp.
wakeUpEvent [2/2]
int services::EventDispatcherWithNetwork::wakeUpEvent[2] { 0 } private
Definition at line 50 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by EventDispatcherWithNetwork(), Idle(), RequestExecution(), and ~EventDispatcherWithNetwork().
writeFileDescriptors
fd_set services::EventDispatcherWithNetwork::writeFileDescriptors private
Definition at line 52 of file network_bsd/EventDispatcherWithNetwork.hpp.
Referenced by Idle().
The documentation for this class was generated from the following files:
network_bsd/EventDispatcherWithNetwork.hpp
network_bsd/EventDispatcherWithNetwork.cpp