EMil: infra::JsonObjectVisitor Class Reference
infra::JsonObjectVisitor Class Reference
#include <JsonStreamingParser.hpp>
Public Member Functions
virtual void VisitString (infra::BoundedConstString tag, infra::BoundedConstString value)
virtual void VisitNumber (infra::BoundedConstString tag, int64_t value)
virtual void VisitBoolean (infra::BoundedConstString tag, bool value)
virtual void VisitNull (infra::BoundedConstString tag)
virtual JsonObjectVisitor * VisitObject (infra::BoundedConstString tag, JsonSubObjectParser &parser)
virtual JsonArrayVisitor * VisitArray (infra::BoundedConstString tag, JsonSubArrayParser &parser)
virtual void Close () override
virtual void ParseError () override
virtual void SemanticError () override
virtual void StringOverflow () override
Protected Member Functions
JsonObjectVisitor ()=default
JsonObjectVisitor (const JsonObjectVisitor &other)=delete
JsonObjectVisitor & operator= (const JsonObjectVisitor &other)=delete
~JsonObjectVisitor ()=default
Protected Member Functions inherited from infra::JsonVisitor
JsonVisitor ()=default
JsonVisitor (const JsonVisitor &other)=delete
JsonVisitor & operator= (const JsonVisitor &other)=delete
~JsonVisitor ()=default
Detailed Description
Definition at line 31 of file JsonStreamingParser.hpp.
Constructor & Destructor Documentation
JsonObjectVisitor() [1/2]
infra::JsonObjectVisitor::JsonObjectVisitor () protected default
JsonObjectVisitor() [2/2]
infra::JsonObjectVisitor::JsonObjectVisitor (const JsonObjectVisitor & other) protected delete
~JsonObjectVisitor()
infra::JsonObjectVisitor::~JsonObjectVisitor () protected default
Member Function Documentation
Close()
void infra::JsonObjectVisitor::Close () override virtual
Implements infra::JsonVisitor.
Definition at line 29 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {}
operator=()
JsonObjectVisitor& infra::JsonObjectVisitor::operator= (const JsonObjectVisitor & other) protected delete
ParseError()
void infra::JsonObjectVisitor::ParseError () override virtual
Implements infra::JsonVisitor.
Definition at line 32 of file JsonStreamingParser.cpp.
     {}
SemanticError()
void infra::JsonObjectVisitor::SemanticError () override virtual
Implements infra::JsonVisitor.
Definition at line 35 of file JsonStreamingParser.cpp.
     {}
StringOverflow()
void infra::JsonObjectVisitor::StringOverflow () override virtual
Implements infra::JsonVisitor.
Definition at line 38 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {}
VisitArray()
JsonArrayVisitor * infra::JsonObjectVisitor::VisitArray (infra::BoundedConstString tag, JsonSubArrayParser & parser) virtual
Definition at line 24 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {
         return nullptr;
     }
VisitBoolean()
void infra::JsonObjectVisitor::VisitBoolean (infra::BoundedConstString tag, bool value) virtual
Definition at line 13 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {}
VisitNull()
void infra::JsonObjectVisitor::VisitNull (infra::BoundedConstString tag) virtual
Definition at line 16 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {}
VisitNumber()
void infra::JsonObjectVisitor::VisitNumber (infra::BoundedConstString tag, int64_t value) virtual
Definition at line 10 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {}
VisitObject()
JsonObjectVisitor * infra::JsonObjectVisitor::VisitObject (infra::BoundedConstString tag, JsonSubObjectParser & parser) virtual
Definition at line 19 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {
         return nullptr;
     }
VisitString()
void infra::JsonObjectVisitor::VisitString (infra::BoundedConstString tag, infra::BoundedConstString value) virtual
Definition at line 7 of file JsonStreamingParser.cpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {}
The documentation for this class was generated from the following files:
JsonStreamingParser.hpp
JsonStreamingParser.cpp