EMil: infra::JsonObjectFormatter Class Reference
infra::JsonObjectFormatter Class Reference
#include <JsonFormatter.hpp>
Public Types
using WithStringStream = infra::WithStorage< JsonObjectFormatter, infra::StringOutputStream >
Public Member Functions
JsonObjectFormatter (infra::TextOutputStream &stream)
JsonObjectFormatter (const JsonObjectFormatter &other)=delete
JsonObjectFormatter (JsonObjectFormatter &&other)
JsonObjectFormatter & operator= (const JsonObjectFormatter &other)=delete
JsonObjectFormatter & operator= (JsonObjectFormatter &&other)
~JsonObjectFormatter ()
void Add (const char *tagName, bool tag)
void Add (JsonString tagName, bool tag)
void Add (const char *tagName, int32_t tag)
void Add (JsonString tagName, int32_t tag)
void Add (const char *tagName, uint32_t tag)
void Add (const char *tagName, int64_t tag)
void Add (const char *tagName, const char *tag)
void Add (const char *tagName, infra::BoundedConstString tag)
void Add (JsonString tagName, JsonString tag)
void Add (JsonString tagName, const JsonObject &tag)
void Add (JsonString tagName, const JsonArray &tag)
void Add (const infra::JsonKeyValue &keyValue)
void AddMilliFloat (const char *tagName, uint32_t intValue, uint32_t milliFractionalValue)
void AddSubObject (const char *tagName, infra::BoundedConstString json)
JsonObjectFormatter SubObject (infra::BoundedConstString tagName)
JsonArrayFormatter SubArray (infra::BoundedConstString tagName)
JsonStringStream AddString (const char *tagName)
bool Failed () const
Private Member Functions
void InsertSeparation ()
Private Attributes
infra::Optional< infra::TextOutputStream::WithErrorPolicy > stream
bool empty = true
Detailed Description
Definition at line 17 of file JsonFormatter.hpp.
Member Typedef Documentation
WithStringStream
using infra::JsonObjectFormatter::WithStringStream = infra::WithStorage<JsonObjectFormatter, infra::StringOutputStream>
Definition at line 20 of file JsonFormatter.hpp.
Constructor & Destructor Documentation
JsonObjectFormatter() [1/3]
infra::JsonObjectFormatter::JsonObjectFormatter (infra::TextOutputStream & stream) explicit
Definition at line 94 of file JsonFormatter.cpp.
         : stream(infra::inPlace, stream.Writer(), infra::noFail)
     {
         *this->stream << "{ ";
     }
JsonObjectFormatter() [2/3]
infra::JsonObjectFormatter::JsonObjectFormatter (const JsonObjectFormatter & other) delete
JsonObjectFormatter() [3/3]
infra::JsonObjectFormatter::JsonObjectFormatter (JsonObjectFormatter && other)
Definition at line 100 of file JsonFormatter.cpp.
References infra::none.
         : stream(other.stream)
     {
         other.stream = infra::none;
     }
~JsonObjectFormatter()
infra::JsonObjectFormatter::~JsonObjectFormatter ()
Definition at line 114 of file JsonFormatter.cpp.
References infra::none, and stream.
     {
         if (stream != infra::none)
             *stream << " }";
     }
Member Function Documentation
Add() [1/12]
void infra::JsonObjectFormatter::Add (const char * tagName, bool tag)
Definition at line 120 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
Referenced by application::TimeHttpPage::TimeResponse::WriteBody().
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)" << (tag ? "true" : "false");
     }
     void JsonObjectFormatter::Add(JsonString tagName, bool tag)
     {
         InsertSeparation();
         *stream << '"' << tagName.Raw() << R"(":)" << (tag ? "true" : "false");
     }
     void JsonObjectFormatter::Add(const char* tagName, int32_t tag)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)" << tag;
     }
     void JsonObjectFormatter::Add(JsonString tagName, int32_t tag)
     {
         InsertSeparation();
         *stream << '"' << tagName.Raw() << R"(":)" << tag;
     }
     void JsonObjectFormatter::Add(const char* tagName, uint32_t tag)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)" << tag;
     }
     void JsonObjectFormatter::Add(const char* tagName, int64_t tag)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)" << tag;
     }
     void JsonObjectFormatter::Add(const char* tagName, const char* tag)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":")";
         InsertEscapedTag(*stream, tag);
         *stream << '"';
     }
Add() [2/12]
void infra::JsonObjectFormatter::Add (JsonString tagName, bool tag)
Add() [3/12]
void infra::JsonObjectFormatter::Add (const char * tagName, int32_t tag)
Add() [4/12]
void infra::JsonObjectFormatter::Add (JsonString tagName, int32_t tag)
Add() [5/12]
void infra::JsonObjectFormatter::Add (const char * tagName, uint32_t tag)
Add() [6/12]
void infra::JsonObjectFormatter::Add (const char * tagName, int64_t tag)
Add() [7/12]
void infra::JsonObjectFormatter::Add (const char * tagName, const char * tag)
Add() [8/12]
void infra::JsonObjectFormatter::Add (const char * tagName, infra::BoundedConstString tag)
Definition at line 164 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":")";
         InsertEscapedTag(*stream, tag);
         *stream << '"';
     }
Add() [9/12]
void infra::JsonObjectFormatter::Add (JsonString tagName, JsonString tag)
Definition at line 172 of file JsonFormatter.cpp.
References InsertSeparation(), infra::JsonString::Raw(), and stream.
     {
         InsertSeparation();
         *stream << '"' << tagName.Raw() << R"(":")" << tag.Raw() << '"';
     }
Add() [10/12]
void infra::JsonObjectFormatter::Add (JsonString tagName, const JsonObject & tag)
Definition at line 178 of file JsonFormatter.cpp.
References InsertSeparation(), infra::JsonObject::ObjectString(), infra::JsonString::Raw(), and stream.
     {
         InsertSeparation();
         *stream << '"' << tagName.Raw() << R"(":)" << tag.ObjectString();
     }
     void JsonObjectFormatter::Add(JsonString tagName, const JsonArray& tag)
     {
         InsertSeparation();
         *stream << '"' << tagName.Raw() << R"(":)" << tag.ObjectString();
     }
     void JsonObjectFormatter::Add(const infra::JsonKeyValue& keyValue)
     {
         if (keyValue.value.Is<bool>())
             Add(keyValue.key, keyValue.value.Get<bool>());
         else if (keyValue.value.Is<int32_t>())
             Add(keyValue.key, keyValue.value.Get<int32_t>());
         else if (keyValue.value.Is<JsonString>())
             Add(keyValue.key, keyValue.value.Get<JsonString>());
         else if (keyValue.value.Is<JsonObject>())
             Add(keyValue.key, keyValue.value.Get<JsonObject>());
         else if (keyValue.value.Is<JsonArray>())
             Add(keyValue.key, keyValue.value.Get<JsonArray>());
         else
             std::abort();
     }
     void JsonObjectFormatter::AddMilliFloat(const char* tagName, uint32_t intValue, uint32_t milliFractionalValue)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)" << intValue << '.' << infra::Width(3, '0') << milliFractionalValue;
     }
     void JsonObjectFormatter::AddSubObject(const char* tagName, infra::BoundedConstString json)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)" << json;
     }
     JsonObjectFormatter JsonObjectFormatter::SubObject(infra::BoundedConstString tagName)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)";
         return JsonObjectFormatter(*stream);
     }
     JsonArrayFormatter JsonObjectFormatter::SubArray(infra::BoundedConstString tagName)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":)";
         return JsonArrayFormatter(*stream);
     }
     JsonStringStream JsonObjectFormatter::AddString(const char* tagName)
     {
         InsertSeparation();
         *stream << '"' << tagName << R"(":")";
         return JsonStringStream(*stream);
     }
Add() [11/12]
void infra::JsonObjectFormatter::Add (JsonString tagName, const JsonArray & tag)
Add() [12/12]
void infra::JsonObjectFormatter::Add (const infra::JsonKeyValue & keyValue)
AddMilliFloat()
void infra::JsonObjectFormatter::AddMilliFloat (const char * tagName, uint32_t intValue, uint32_t milliFractionalValue)
AddString()
JsonStringStream infra::JsonObjectFormatter::AddString (const char * tagName)
AddSubObject()
void infra::JsonObjectFormatter::AddSubObject (const char * tagName, infra::BoundedConstString json)
Failed()
bool infra::JsonObjectFormatter::Failed () const
Definition at line 242 of file JsonFormatter.cpp.
References infra::OutputStream::Failed(), and stream.
     {
         return stream->Failed();
     }
InsertSeparation()
void infra::JsonObjectFormatter::InsertSeparation () private
Definition at line 247 of file JsonFormatter.cpp.
References empty, and stream.
Referenced by Add().
     {
         if (!empty)
             *stream << ", ";
         empty = false;
     }
operator=() [1/2]
JsonObjectFormatter& infra::JsonObjectFormatter::operator= (const JsonObjectFormatter & other) delete
operator=() [2/2]
JsonObjectFormatter & infra::JsonObjectFormatter::operator= (JsonObjectFormatter && other)
Definition at line 106 of file JsonFormatter.cpp.
References infra::none, and stream.
     {
         stream = other.stream;
         other.stream = infra::none;
         return *this;
     }
SubArray()
JsonArrayFormatter infra::JsonObjectFormatter::SubArray (infra::BoundedConstString tagName)
SubObject()
JsonObjectFormatter infra::JsonObjectFormatter::SubObject (infra::BoundedConstString tagName)
Member Data Documentation
empty
bool infra::JsonObjectFormatter::empty = true private
Definition at line 54 of file JsonFormatter.hpp.
Referenced by InsertSeparation().
stream
infra::Optional<infra::TextOutputStream::WithErrorPolicy> infra::JsonObjectFormatter::stream private
Definition at line 53 of file JsonFormatter.hpp.
Referenced by Add(), Failed(), InsertSeparation(), operator=(), and ~JsonObjectFormatter().
The documentation for this class was generated from the following files:
JsonFormatter.hpp
JsonFormatter.cpp