EMil: services::SingleConnectionHttpServer< ConnectionCreationContext > Class Template Reference
services::SingleConnectionHttpServer< ConnectionCreationContext > Class Template Reference
#include <HttpServer.hpp>
Public Types
template<class Connection >
using WithFactoryFor = infra::WithStorage< SingleConnectionHttpServer, HttpServerConnectionObserverFactoryImpl< ConnectionCreationContext, Connection > >
Public Member Functions
SingleConnectionHttpServer (HttpServerConnectionObserverFactory< ConnectionCreationContext > &factory, ConnectionCreationContext &creationContext, ConnectionFactory &connectionFactory, uint16_t port)
~SingleConnectionHttpServer ()
virtual void Stop (const infra::Function< void()> &onDone)
virtual void ConnectionAccepted (infra::AutoResetFunction< void(infra::SharedPtr< ConnectionObserver > connectionObserver)> &&createdObserver, IPAddress address) override
Public Member Functions inherited from services::HttpPageServer
HttpPageServer ()=default
HttpPageServer (const HttpPageServer &other)=delete
HttpPageServer & operator= (const HttpPageServer &other)=delete
~HttpPageServer ()=default
virtual HttpPage * PageForRequest (const HttpRequestParser &request)
void AddPage (services::HttpPage &page)
Private Member Functions
void ObserverAllocatable ()
Private Attributes
HttpServerConnectionObserverFactory< ConnectionCreationContext > & factory
ConnectionCreationContext & creationContext
infra::SharedPtr< void > listener
infra::AutoResetFunction< void(infra::SharedPtr< ConnectionObserver > connectionObserver)> createdObserver
IPAddress address
infra::Function< void()> onStopped
Additional Inherited Members
Protected Member Functions inherited from services::ServerConnectionObserverFactory
ServerConnectionObserverFactory ()=default
ServerConnectionObserverFactory (const ServerConnectionObserverFactory &other)=delete
ServerConnectionObserverFactory & operator= (const ServerConnectionObserverFactory &other)=delete
~ServerConnectionObserverFactory ()=default
Detailed Description
template<class ConnectionCreationContext>
class services::SingleConnectionHttpServer< ConnectionCreationContext >
Definition at line 191 of file HttpServer.hpp.
Member Typedef Documentation
WithFactoryFor
template<class ConnectionCreationContext > template<class Connection > using services::SingleConnectionHttpServer< ConnectionCreationContext >::WithFactoryFor = infra::WithStorage<SingleConnectionHttpServer, HttpServerConnectionObserverFactoryImpl<ConnectionCreationContext, Connection> >
Definition at line 197 of file HttpServer.hpp.
Constructor & Destructor Documentation
SingleConnectionHttpServer()
template<class ConnectionCreationContext > services::SingleConnectionHttpServer< ConnectionCreationContext >::SingleConnectionHttpServer (HttpServerConnectionObserverFactory< ConnectionCreationContext > & factory, ConnectionCreationContext & creationContext, ConnectionFactory & connectionFactory, uint16_t port)
Definition at line 271 of file HttpServer.hpp.
References services::SingleConnectionHttpServer< ConnectionCreationContext >::factory, services::ConnectionFactory::Listen(), services::SingleConnectionHttpServer< ConnectionCreationContext >::listener, and services::SingleConnectionHttpServer< ConnectionCreationContext >::ObserverAllocatable().
         : factory(factory)
         , creationContext(creationContext)
     {
         factory.OnAllocatable([this]() { ObserverAllocatable(); });
         listener = connectionFactory.Listen(port, *this);
     }
~SingleConnectionHttpServer()
template<class ConnectionCreationContext > services::SingleConnectionHttpServer< ConnectionCreationContext >::~SingleConnectionHttpServer ()
Definition at line 280 of file HttpServer.hpp.
     {
         really_assert(factory.Allocatable());
     }
Member Function Documentation
ConnectionAccepted()
template<class ConnectionCreationContext > void services::SingleConnectionHttpServer< ConnectionCreationContext >::ConnectionAccepted (infra::AutoResetFunction< void(infra::SharedPtr< ConnectionObserver > connectionObserver)> && createdObserver, IPAddress address) override virtual
Implements services::ServerConnectionObserverFactory.
Definition at line 301 of file HttpServer.hpp.
     {
         this->address = address;
         this->createdObserver = std::move(createdObserver);
         if (factory.Allocatable())
             ObserverAllocatable();
         else if (factory.Allocated())
             factory.Get().CloseWhenIdle();
     }
ObserverAllocatable()
template<class ConnectionCreationContext > void services::SingleConnectionHttpServer< ConnectionCreationContext >::ObserverAllocatable () private
Definition at line 313 of file HttpServer.hpp.
Referenced by services::SingleConnectionHttpServer< ConnectionCreationContext >::SingleConnectionHttpServer().
     {
         if (createdObserver)
             createdObserver(factory.Emplace(creationContext));
     }
Stop()
template<class ConnectionCreationContext > void services::SingleConnectionHttpServer< ConnectionCreationContext >::Stop (const infra::Function< void()> & onDone) virtual
Definition at line 286 of file HttpServer.hpp.
     {
         onStopped = onDone;
         if (!factory.Allocatable())
         {
             factory.OnAllocatable([this]() { onStopped(); });
             if (factory.Allocated())
                 factory.Get().Close();
         }
         else
             onStopped();
     }
Member Data Documentation
address
template<class ConnectionCreationContext > IPAddress services::SingleConnectionHttpServer< ConnectionCreationContext >::address private
Definition at line 216 of file HttpServer.hpp.
createdObserver
template<class ConnectionCreationContext > infra::AutoResetFunction<void(infra::SharedPtr<ConnectionObserver> connectionObserver)> services::SingleConnectionHttpServer< ConnectionCreationContext >::createdObserver private
Definition at line 215 of file HttpServer.hpp.
creationContext
template<class ConnectionCreationContext > ConnectionCreationContext& services::SingleConnectionHttpServer< ConnectionCreationContext >::creationContext private
Definition at line 212 of file HttpServer.hpp.
factory
template<class ConnectionCreationContext > HttpServerConnectionObserverFactory<ConnectionCreationContext>& services::SingleConnectionHttpServer< ConnectionCreationContext >::factory private
Definition at line 211 of file HttpServer.hpp.
Referenced by services::SingleConnectionHttpServer< ConnectionCreationContext >::SingleConnectionHttpServer().
listener
template<class ConnectionCreationContext > infra::SharedPtr<void> services::SingleConnectionHttpServer< ConnectionCreationContext >::listener private
Definition at line 213 of file HttpServer.hpp.
Referenced by services::SingleConnectionHttpServer< ConnectionCreationContext >::SingleConnectionHttpServer().
onStopped
template<class ConnectionCreationContext > infra::Function<void()> services::SingleConnectionHttpServer< ConnectionCreationContext >::onStopped private
Definition at line 217 of file HttpServer.hpp.
The documentation for this class was generated from the following file:
HttpServer.hpp