EMil: TestTerminal.cpp File Reference
TestTerminal.cpp File Reference
Classes
class TerminalTest
class TerminalNavigationTest
class TerminalHistoryTest
Functions
TEST_F (TerminalTest, echo_printable_characters)
TEST_F (TerminalTest, echo_bell_for_nonprintable_characters)
TEST_F (TerminalTest, ignore_newline_character)
TEST_F (TerminalTest, echo_carriage_return_line_feed_and_prompt_on_carriage_return)
TEST_F (TerminalTest, ignore_unparsed_escaped_data)
TEST_F (TerminalTest, bell_on_invalid_escape_sequence)
TEST_F (TerminalTest, navigation_with_empty_buffer)
TEST_F (TerminalTest, clear_buffer_prints_prompt)
TEST_F (TerminalNavigationTest, move_cursor_home)
TEST_F (TerminalNavigationTest, move_cursor_home_escape)
TEST_F (TerminalNavigationTest, move_cursor_end)
TEST_F (TerminalNavigationTest, move_cursor_end_escape)
TEST_F (TerminalNavigationTest, move_cursor_left)
TEST_F (TerminalNavigationTest, move_cursor_left_escape)
TEST_F (TerminalNavigationTest, bell_on_move_past_beginning)
TEST_F (TerminalNavigationTest, move_cursor_right)
TEST_F (TerminalNavigationTest, move_cursor_right_escape)
TEST_F (TerminalNavigationTest, bell_on_move_past_end)
TEST_F (TerminalNavigationTest, remove_last_character_on_backspace)
TEST_F (TerminalNavigationTest, remove_first_character_on_backspace)
TEST_F (TerminalNavigationTest, remove_character_with_delete)
TEST_F (TerminalTest, move_backward_in_history_with_empty_history)
TEST_F (TerminalTest, move_forward_in_history_with_empty_history)
TEST_F (TerminalHistoryTest, move_backward_in_history)
TEST_F (TerminalHistoryTest, move_forward_past_end_prints_prompt)
Function Documentation
TEST_F() [1/25]
TEST_F (TerminalTest , echo_printable_characters)
Definition at line 67 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'A' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'Z' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '~' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ ' ', 'A', 'Z', '~' });
     ExecuteAllActions();
 }
TEST_F() [2/25]
TEST_F (TerminalTest , echo_bell_for_nonprintable_characters)
Definition at line 79 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 31, 128 });
     ExecuteAllActions();
 }
TEST_F() [3/25]
TEST_F (TerminalTest , ignore_newline_character)
Definition at line 89 of file TestTerminal.cpp.
 {
     communication.dataReceived(std::vector<uint8_t>{ '\n' });
     ExecuteAllActions();
 }
TEST_F() [4/25]
TEST_F (TerminalTest , echo_carriage_return_line_feed_and_prompt_on_carriage_return)
Definition at line 96 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r', '\n' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ '\r' });
     ExecuteAllActions();
 }
TEST_F() [5/25]
TEST_F (TerminalTest , ignore_unparsed_escaped_data)
Definition at line 106 of file TestTerminal.cpp.
 {
     communication.dataReceived(std::vector<uint8_t>{ 27, ';', '[', 'O', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' });
     ExecuteAllActions();
 }
TEST_F() [6/25]
TEST_F (TerminalTest , bell_on_invalid_escape_sequence)
Definition at line 113 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 27, 'Z' });
     ExecuteAllActions();
 }
TEST_F() [7/25]
TEST_F (TerminalTest , navigation_with_empty_buffer)
Definition at line 122 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 1, 1, 5, 5 });
     ExecuteAllActions();
 }
TEST_F() [8/25]
TEST_F (TerminalTest , clear_buffer_prints_prompt)
Definition at line 134 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 3 });
     ExecuteAllActions();
 }
TEST_F() [9/25]
TEST_F (TerminalNavigationTest , move_cursor_home)
Definition at line 144 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 1, 1 });
     ExecuteAllActions();
 }
TEST_F() [10/25]
TEST_F (TerminalNavigationTest , move_cursor_home_escape)
Definition at line 156 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 27, 'H' });
     ExecuteAllActions();
 }
TEST_F() [11/25]
TEST_F (TerminalNavigationTest , move_cursor_end)
Definition at line 166 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'a', 'b', 'c', 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 1, 5, 5 });
     ExecuteAllActions();
 }
TEST_F() [12/25]
TEST_F (TerminalNavigationTest , move_cursor_end_escape)
Definition at line 177 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'a', 'b', 'c', 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 1, 27, 'F' });
     ExecuteAllActions();
 }
TEST_F() [13/25]
TEST_F (TerminalNavigationTest , move_cursor_left)
Definition at line 188 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 2 });
     ExecuteAllActions();
 }
TEST_F() [14/25]
TEST_F (TerminalNavigationTest , move_cursor_left_escape)
Definition at line 197 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 27, 'D' });
     ExecuteAllActions();
 }
TEST_F() [15/25]
TEST_F (TerminalNavigationTest , bell_on_move_past_beginning)
Definition at line 206 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).Times(4).WillRepeatedly(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 2, 2, 2, 2, 2 });
     ExecuteAllActions();
 }
TEST_F() [16/25]
TEST_F (TerminalNavigationTest , move_cursor_right)
Definition at line 216 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 2, 6 });
     ExecuteAllActions();
 }
TEST_F() [17/25]
TEST_F (TerminalNavigationTest , move_cursor_right_escape)
Definition at line 226 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 2, 27, 'C' });
     ExecuteAllActions();
 }
TEST_F() [18/25]
TEST_F (TerminalNavigationTest , bell_on_move_past_end)
Definition at line 236 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 6 });
     ExecuteAllActions();
 }
TEST_F() [19/25]
TEST_F (TerminalNavigationTest , remove_last_character_on_backspace)
Definition at line 245 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ ' ', '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ '\b' });
     ExecuteAllActions();
 }
TEST_F() [20/25]
TEST_F (TerminalNavigationTest , remove_first_character_on_backspace)
Definition at line 255 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).Times(4).WillRepeatedly(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'b', 'c', 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ ' ', '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).Times(3).WillRepeatedly(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 2, 2, 2, '\b' });
     ExecuteAllActions();
 }
TEST_F() [21/25]
TEST_F (TerminalNavigationTest , remove_character_with_delete)
Definition at line 267 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).Times(3).WillRepeatedly(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'c', 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ ' ', '\b' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\b' })).Times(2).WillRepeatedly(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 2, 2, 2, 4 });
     ExecuteAllActions();
 }
TEST_F() [22/25]
TEST_F (TerminalTest , move_backward_in_history_with_empty_history)
Definition at line 279 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 14 });
     ExecuteAllActions();
 }
TEST_F() [23/25]
TEST_F (TerminalTest , move_forward_in_history_with_empty_history)
Definition at line 289 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 16 });
     ExecuteAllActions();
 }
TEST_F() [24/25]
TEST_F (TerminalHistoryTest , move_backward_in_history)
Definition at line 298 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'e', 'f', 'g' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ 'a', 'b', 'c', 'd' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\a' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 16, 16, 16 });
     ExecuteAllActions();
 }
TEST_F() [25/25]
TEST_F (TerminalHistoryTest , move_forward_past_end_prints_prompt)
Definition at line 315 of file TestTerminal.cpp.
References infra::Lambda().
 {
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '\r' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     EXPECT_CALL(communication, SendDataMock(std::vector<uint8_t>{ '>', ' ' })).WillOnce(infra::Lambda([this](std::vector<uint8_t>) { communication.actionOnCompletion(); }));
     communication.dataReceived(std::vector<uint8_t>{ 14, 14 });
     ExecuteAllActions();
 }