EMil: services::SignalLed Class Reference
services::SignalLed Class Reference
#include <SignalLed.hpp>
Public Member Functions
SignalLed (hal::GpioPin &led, uint32_t pattern, uint8_t length, infra::Duration duration)
SignalLed (hal::GpioPin &led, infra::Duration duration)
void Set (uint32_t pattern, uint8_t length)
Private Member Functions
void OnTimer ()
Private Attributes
hal::OutputPin led
uint32_t pattern = 0
uint8_t length = 0
infra::TimerRepeating timer
uint32_t index = 0
Detailed Description
Definition at line 9 of file SignalLed.hpp.
Constructor & Destructor Documentation
SignalLed() [1/2]
services::SignalLed::SignalLed (hal::GpioPin & led, uint32_t pattern, uint8_t length, infra::Duration duration)
Definition at line 5 of file SignalLed.cpp.
References OnTimer().
         : led(led)
         , timer(duration, [this]() { OnTimer(); })
     {
         Set(pattern, length);
     }
SignalLed() [2/2]
services::SignalLed::SignalLed (hal::GpioPin & led, infra::Duration duration)
Definition at line 12 of file SignalLed.cpp.
         : SignalLed(led, 0, 0, duration)
     {}
Member Function Documentation
OnTimer()
void services::SignalLed::OnTimer () private
Definition at line 25 of file SignalLed.cpp.
References index, led, length, pattern, and hal::OutputPin::Set().
Referenced by Set(), and SignalLed().
     {
         if (++index == length)
             index = 0;
         led.Set(((1 << index) & pattern) != 0);
     }
Set()
void services::SignalLed::Set (uint32_t pattern, uint8_t length)
Definition at line 16 of file SignalLed.cpp.
References index, length, OnTimer(), and pattern.
     {
         this->pattern = pattern;
         this->length = length;
         index = length - 1;
         OnTimer();
     }
Member Data Documentation
index
uint32_t services::SignalLed::index = 0 private
Definition at line 25 of file SignalLed.hpp.
Referenced by OnTimer(), and Set().
led
hal::OutputPin services::SignalLed::led private
Definition at line 21 of file SignalLed.hpp.
Referenced by OnTimer().
length
uint8_t services::SignalLed::length = 0 private
Definition at line 23 of file SignalLed.hpp.
Referenced by OnTimer(), and Set().
pattern
uint32_t services::SignalLed::pattern = 0 private
Definition at line 22 of file SignalLed.hpp.
Referenced by OnTimer(), and Set().
timer
infra::TimerRepeating services::SignalLed::timer private
Definition at line 24 of file SignalLed.hpp.
The documentation for this class was generated from the following files:
SignalLed.hpp
SignalLed.cpp