EMil: infra::Asn1Formatter Class Reference
infra::Asn1Formatter Class Reference
#include <Asn1Formatter.hpp>
Public Member Functions
Asn1Formatter (infra::DataOutputStream &stream)
void Add (uint8_t value)
void Add (uint32_t value)
void Add (int32_t value)
void AddSerial (infra::ConstByteRange serial)
void AddBigNumber (infra::ConstByteRange number)
void AddContextSpecific (uint8_t context, infra::ConstByteRange data)
void AddObjectId (infra::ConstByteRange oid)
void AddBitString (infra::ConstByteRange string)
void AddPrintableString (infra::ConstByteRange string)
void AddUtcTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
void AddGeneralizedTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
void AddTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
template<typename T >
void AddOptional (infra::Optional< T > value)
Asn1ContainerFormatter StartSequence ()
Asn1ContainerFormatter StartSet ()
Asn1ContainerFormatter StartContextSpecific (uint8_t context=0)
Asn1ContainerFormatter StartBitString ()
bool Failed () const
Protected Member Functions
infra::DataOutputStream & Stream ()
Private Types
enum Tag : uint8_t {
Integer = 0x02, BitString = 0x03, Null = 0x05, Oid = 0x06,
Sequence = 0x10, Set = 0x11, PrintableString = 0x13, UtcTime = 0x17,
GeneralizedTime = 0x18, Constructed = 0x20, ContextSpecific = 0x80
}
Private Member Functions
template<typename T >
void AddTagLengthValue (uint8_t tag, uint32_t length, T value)
void AddTagLength (uint8_t tag, uint32_t length)
Private Attributes
infra::DataOutputStream stream
Detailed Description
Definition at line 12 of file Asn1Formatter.hpp.
Member Enumeration Documentation
Tag
enum infra::Asn1Formatter::Tag : uint8_t private
Enumerator
Integer
BitString
Null
Oid
Sequence
Set
PrintableString
UtcTime
GeneralizedTime
Constructed
ContextSpecific
Definition at line 45 of file Asn1Formatter.hpp.
                  : uint8_t
         {
             Integer = 0x02,
             BitString = 0x03,
             Null = 0x05,
             Oid = 0x06,
             Sequence = 0x10,
             Set = 0x11,
             PrintableString = 0x13,
             UtcTime = 0x17,
             GeneralizedTime = 0x18,
             Constructed = 0x20,
             ContextSpecific = 0x80
         };
Constructor & Destructor Documentation
Asn1Formatter()
infra::Asn1Formatter::Asn1Formatter (infra::DataOutputStream & stream) explicit
Definition at line 18 of file Asn1Formatter.cpp.
         : stream(stream)
     {}
Member Function Documentation
Add() [1/3]
void infra::Asn1Formatter::Add (uint8_t value)
Definition at line 22 of file Asn1Formatter.cpp.
References AddTagLengthValue(), and value.
Referenced by Add(), and AddOptional().
     {
         AddTagLengthValue(Tag::Integer, sizeof(uint8_t), value);
     }
Add() [2/3]
void infra::Asn1Formatter::Add (uint32_t value)
Definition at line 27 of file Asn1Formatter.cpp.
References AddTagLengthValue(), and value.
     {
         value = (value << 16) | (value >> 16);
         value = ((value & 0x00ff00ff) << 8) | ((value & 0xff00ff00) >> 8);
         AddTagLengthValue(Tag::Integer, sizeof(uint32_t), value);
     }
Add() [3/3]
void infra::Asn1Formatter::Add (int32_t value)
Definition at line 35 of file Asn1Formatter.cpp.
References Add(), and value.
     {
         Add(static_cast<uint32_t>(value));
     }
AddBigNumber()
void infra::Asn1Formatter::AddBigNumber (infra::ConstByteRange number)
Definition at line 45 of file Asn1Formatter.cpp.
References AddTagLength(), infra::MemoryRange< T >::back(), infra::MemoryRange< T >::empty(), infra::MemoryRange< T >::pop_back(), infra::MemoryRange< T >::size(), and stream.
     {
         while (!number.empty() && number.back() == 0)
             number.pop_back();
         if (!number.empty() && (number.back() & 0x80) != 0)
         {
             AddTagLength(Tag::Integer, number.size() + 1);
             stream << static_cast<uint8_t>(0x00);
             for (int i = number.size() - 1; i >= 0; --i)
                 stream << number[i];
         }
         else
         {
             AddTagLength(Tag::Integer, number.size());
             for (int i = number.size() - 1; i >= 0; --i)
                 stream << number[i];
         }
     }
AddBitString()
void infra::Asn1Formatter::AddBitString (infra::ConstByteRange string)
Definition at line 77 of file Asn1Formatter.cpp.
References AddTagLength(), and stream.
     {
         AddTagLength(Tag::BitString, string.size() + 1);
         // Next byte indicates the bits of padding added to
         // the data when the length of the data in bits is
         // not a multiple of 8.
         stream << static_cast<uint8_t>(0x00);
         stream << string;
     }
AddContextSpecific()
void infra::Asn1Formatter::AddContextSpecific (uint8_t context, infra::ConstByteRange data)
Definition at line 67 of file Asn1Formatter.cpp.
References AddTagLengthValue(), and infra::data.
     {
         AddTagLengthValue(Tag::Constructed | Tag::ContextSpecific | context, data.size(), data);
     }
AddGeneralizedTime()
void infra::Asn1Formatter::AddGeneralizedTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
Definition at line 119 of file Asn1Formatter.cpp.
References AddTagLength(), stream, and infra::text.
Referenced by AddTime().
     {
         const uint8_t generalizedTimeSize = 15; // "YYYYMMDDhhmmssZ"
         AddTagLength(Tag::GeneralizedTime, generalizedTimeSize);
         stream << infra::text << infra::Width(4, '0') << year;
         stream << infra::text << infra::Width(2, '0') << month;
         stream << infra::text << infra::Width(2, '0') << day;
         stream << infra::text << infra::Width(2, '0') << hour;
         stream << infra::text << infra::Width(2, '0') << min;
         stream << infra::text << infra::Width(2, '0') << sec;
         stream << infra::text << 'Z';
     }
AddObjectId()
void infra::Asn1Formatter::AddObjectId (infra::ConstByteRange oid)
Definition at line 72 of file Asn1Formatter.cpp.
References AddTagLengthValue(), and infra::MemoryRange< T >::size().
Referenced by services::CertificatesMbedTls::X509AddAlgorithm(), and services::CertificatesMbedTls::X509AddName().
     {
         AddTagLengthValue(Tag::Oid, oid.size(), oid);
     }
AddOptional()
template<typename T > void infra::Asn1Formatter::AddOptional (infra::Optional< T > value)
Definition at line 70 of file Asn1Formatter.hpp.
References Add(), AddTagLength(), and value.
     {
         if (value)
             Add(*value);
         else
             AddTagLength(Tag::Null, 0);
     }
AddPrintableString()
void infra::Asn1Formatter::AddPrintableString (infra::ConstByteRange string)
Definition at line 88 of file Asn1Formatter.cpp.
References AddTagLengthValue().
     {
         AddTagLengthValue(Tag::PrintableString, string.size(), string);
     }
AddSerial()
void infra::Asn1Formatter::AddSerial (infra::ConstByteRange serial)
Definition at line 40 of file Asn1Formatter.cpp.
References AddTagLengthValue(), and infra::MemoryRange< T >::size().
     {
         AddTagLengthValue(Tag::Integer, serial.size(), serial);
     }
AddTagLength()
void infra::Asn1Formatter::AddTagLength (uint8_t tag, uint32_t length) private
Definition at line 177 of file Asn1Formatter.cpp.
References stream.
Referenced by AddBigNumber(), AddBitString(), AddGeneralizedTime(), AddOptional(), AddTagLengthValue(), and AddUtcTime().
     {
         stream << tag;
         AddLength(stream, length);
     }
AddTagLengthValue()
template<typename T > void infra::Asn1Formatter::AddTagLengthValue (uint8_t tag, uint32_t length, T value) private
Definition at line 79 of file Asn1Formatter.hpp.
References AddTagLength(), stream, and value.
Referenced by Add(), AddContextSpecific(), AddObjectId(), AddPrintableString(), and AddSerial().
     {
         AddTagLength(tag, length);
         stream << value;
     }
AddTime()
void infra::Asn1Formatter::AddTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
Definition at line 111 of file Asn1Formatter.cpp.
References AddGeneralizedTime(), and AddUtcTime().
Referenced by services::CertificatesMbedTls::X509AddTime().
     {
         if (year >= 1950 && year < 2050)
             AddUtcTime(year, month, day, hour, min, sec);
         else
             AddGeneralizedTime(year, month, day, hour, min, sec);
     }
AddUtcTime()
void infra::Asn1Formatter::AddUtcTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
Definition at line 93 of file Asn1Formatter.cpp.
References AddTagLength(), stream, and infra::text.
Referenced by AddTime().
     {
         assert(year >= 1950 && year < 2050);
         const uint8_t utcTimeSize = 13; // "YYMMDDhhmmssZ"
         AddTagLength(Tag::UtcTime, utcTimeSize);
         year -= (year >= 2000) ? 2000 : 1900;
         stream << infra::text << infra::Width(2, '0') << static_cast<uint8_t>(year);
         stream << infra::text << infra::Width(2, '0') << month;
         stream << infra::text << infra::Width(2, '0') << day;
         stream << infra::text << infra::Width(2, '0') << hour;
         stream << infra::text << infra::Width(2, '0') << min;
         stream << infra::text << infra::Width(2, '0') << sec;
         stream << infra::text << 'Z';
     }
Failed()
bool infra::Asn1Formatter::Failed () const
Definition at line 167 of file Asn1Formatter.cpp.
References infra::OutputStream::Failed(), and stream.
     {
         return stream.Failed();
     }
StartBitString()
Asn1ContainerFormatter infra::Asn1Formatter::StartBitString ()
Definition at line 154 of file Asn1Formatter.cpp.
References infra::OutputStream::SaveMarker(), and stream.
     {
         stream << static_cast<uint8_t>(Tag::BitString);
         auto marker = stream.SaveMarker();
         // Next byte indicates the bits of padding added to
         // the data when the length of the data in bits is
         // not a multiple of 8.
         stream << static_cast<uint8_t>(0x00);
         return Asn1ContainerFormatter(stream, marker);
     }
StartContextSpecific()
Asn1ContainerFormatter infra::Asn1Formatter::StartContextSpecific (uint8_t context = 0)
Definition at line 147 of file Asn1Formatter.cpp.
References infra::OutputStream::SaveMarker(), and stream.
     {
         stream << static_cast<uint8_t>(Tag::Constructed | Tag::ContextSpecific | context);
         return Asn1ContainerFormatter(stream, stream.SaveMarker());
     }
StartSequence()
Asn1ContainerFormatter infra::Asn1Formatter::StartSequence ()
Definition at line 133 of file Asn1Formatter.cpp.
References infra::OutputStream::SaveMarker(), and stream.
Referenced by services::CertificatesMbedTls::WriteOwnCertificate(), services::CertificatesMbedTls::WritePrivateKey(), services::CertificatesMbedTls::X509AddAlgorithm(), and services::CertificatesMbedTls::X509AddName().
     {
         stream << static_cast<uint8_t>(Tag::Constructed | Tag::Sequence);
         return Asn1ContainerFormatter(stream, stream.SaveMarker());
     }
StartSet()
Asn1ContainerFormatter infra::Asn1Formatter::StartSet ()
Definition at line 140 of file Asn1Formatter.cpp.
References infra::OutputStream::SaveMarker(), and stream.
Referenced by services::CertificatesMbedTls::X509AddName().
     {
         stream << static_cast<uint8_t>(Tag::Constructed | Tag::Set);
         return Asn1ContainerFormatter(stream, stream.SaveMarker());
     }
Stream()
infra::DataOutputStream & infra::Asn1Formatter::Stream () protected
Definition at line 172 of file Asn1Formatter.cpp.
References stream.
Referenced by infra::Asn1ContainerFormatter::~Asn1ContainerFormatter().
     {
         return stream;
     }
Member Data Documentation
stream
infra::DataOutputStream infra::Asn1Formatter::stream private
Definition at line 66 of file Asn1Formatter.hpp.
Referenced by AddBigNumber(), AddBitString(), AddGeneralizedTime(), AddTagLength(), AddTagLengthValue(), AddUtcTime(), Failed(), StartBitString(), StartContextSpecific(), StartSequence(), StartSet(), and Stream().
The documentation for this class was generated from the following files:
Asn1Formatter.hpp
Asn1Formatter.cpp