EMil: infra::JsonInputStreamReader Class Reference
infra::JsonInputStreamReader Class Reference
#include <JsonInputStream.hpp>
Public Member Functions
JsonInputStreamReader (JsonString string)
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy) override
virtual ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
Private Attributes
JsonString string
JsonStringIterator position
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 9 of file JsonInputStream.hpp.
Constructor & Destructor Documentation
JsonInputStreamReader()
infra::JsonInputStreamReader::JsonInputStreamReader (JsonString string) explicit
Definition at line 5 of file JsonInputStream.cpp.
         : string(string)
         , position(string.begin())
     {}
Member Function Documentation
Available()
std::size_t infra::JsonInputStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 48 of file JsonInputStream.cpp.
References infra::detail::end(), and position.
Referenced by Extract().
     {
         return std::distance(position, string.end());
     }
Empty()
bool infra::JsonInputStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 43 of file JsonInputStream.cpp.
References infra::JsonStringIterator::end, and position.
Referenced by Peek().
     {
         return position == string.end();
     }
Extract()
void infra::JsonInputStreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 10 of file JsonInputStream.cpp.
References Available(), infra::MemoryRange< T >::begin(), position, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         errorPolicy.ReportResult(Available() >= range.size());
         range.shrink_from_back_to(Available());
         auto newPosition = std::next(position, range.size());
         std::copy(position, newPosition, range.begin());
         position = newPosition;
     }
ExtractContiguousRange()
ConstByteRange infra::JsonInputStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 33 of file JsonInputStream.cpp.
     {
         std::abort(); // Not implemented
     }
Peek()
uint8_t infra::JsonInputStreamReader::Peek (StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 19 of file JsonInputStream.cpp.
References Empty(), and infra::StreamErrorPolicy::ReportResult().
     {
         if (Empty())
         {
             errorPolicy.ReportResult(false);
             return 0;
         }
         else
         {
             errorPolicy.ReportResult(true);
             return static_cast<uint8_t>(*position);
         }
     }
PeekContiguousRange()
ConstByteRange infra::JsonInputStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 38 of file JsonInputStream.cpp.
     {
         std::abort(); // Not implemented
     }
Member Data Documentation
position
JsonStringIterator infra::JsonInputStreamReader::position private
Definition at line 25 of file JsonInputStream.hpp.
Referenced by Available(), Empty(), and Extract().
string
JsonString infra::JsonInputStreamReader::string private
Definition at line 24 of file JsonInputStream.hpp.
The documentation for this class was generated from the following files:
JsonInputStream.hpp
JsonInputStream.cpp