EMil: hal::FlashHomogeneous Class Reference
hal::FlashHomogeneous Class Reference
#include <FlashHomogeneous.hpp>
Public Member Functions
FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone)=0
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone)=0
void EraseAll (infra::Function< void()> onDone)
Protected Member Functions
~FlashHomogeneous ()=default
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Private Attributes
uint32_t numberOfSectors
uint32_t sizeOfEachSector
Detailed Description
Definition at line 8 of file FlashHomogeneous.hpp.
Constructor & Destructor Documentation
FlashHomogeneous()
hal::FlashHomogeneous::FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
Definition at line 5 of file FlashHomogeneous.cpp.
         : numberOfSectors(numberOfSectors)
         , sizeOfEachSector(sizeOfEachSector)
     {}
~FlashHomogeneous()
hal::FlashHomogeneous::~FlashHomogeneous () protected default
Member Function Documentation
AddressOfSector()
uint32_t hal::FlashHomogeneous::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 25 of file FlashHomogeneous.cpp.
References sizeOfEachSector.
Referenced by services::FlashQuadSpiSingleSpeed::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseBlock(), services::FlashQuadSpiCypressFll::SendEraseHalfBlock(), services::FlashQuadSpiSingleSpeed::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSector(), services::FlashQuadSpiCypressFll::SendEraseSector(), services::FlashSpi::SendEraseSector(), services::FlashQuadSpiMicronN25q::SendEraseSubSector(), and services::FlashSpi::SendEraseSubSector().
     {
         return sectorIndex * sizeOfEachSector;
     }
NumberOfSectors()
uint32_t hal::FlashHomogeneous::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 10 of file FlashHomogeneous.cpp.
References numberOfSectors.
Referenced by services::FlashQuadSpiSingleSpeed::EraseSomeSectors(), services::FlashQuadSpiMicronN25q::EraseSomeSectors(), services::FlashQuadSpiCypressFll::EraseSomeSectors(), and services::FlashSpi::EraseSomeSectors().
     {
         return numberOfSectors;
     }
SectorOfAddress()
uint32_t hal::FlashHomogeneous::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 20 of file FlashHomogeneous.cpp.
References sizeOfEachSector.
     {
         return address / sizeOfEachSector;
     }
SizeOfSector()
uint32_t hal::FlashHomogeneous::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 15 of file FlashHomogeneous.cpp.
References sizeOfEachSector.
     {
         return sizeOfEachSector;
     }
Member Data Documentation
numberOfSectors
uint32_t hal::FlashHomogeneous::numberOfSectors private
Definition at line 25 of file FlashHomogeneous.hpp.
Referenced by NumberOfSectors().
sizeOfEachSector
uint32_t hal::FlashHomogeneous::sizeOfEachSector private
Definition at line 26 of file FlashHomogeneous.hpp.
Referenced by AddressOfSector(), SectorOfAddress(), and SizeOfSector().
The documentation for this class was generated from the following files:
FlashHomogeneous.hpp
FlashHomogeneous.cpp