EMil: services::LlmnrResponder Class Reference
services::LlmnrResponder Class Reference
#include <LlmnrResponder.hpp>
Classes
struct Answer
struct Footer
struct Header
Public Member Functions
LlmnrResponder (services::DatagramFactory &factory, services::Multicast &multicast, services::IPv4Info &ipv4Info, infra::BoundedConstString name)
~LlmnrResponder ()
virtual void DataReceived (infra::StreamReaderWithRewinding &reader, services::UdpSocket from) override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
Public Member Functions inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Static Public Attributes
static const services::IPv4Address llmnpMulticastAddress { 224, 0, 0, 252 }
static const uint16_t llmnpPort = 5355
Private Member Functions
bool PacketValid (const Header &header, const Footer &footer) const
Private Attributes
infra::SharedPtr< services::DatagramExchange > datagramExchange
services::Multicast & multicast
services::IPv4Info & ipv4Info
infra::BoundedConstString name
bool replying = false
infra::BigEndian< uint16_t > id
Additional Inherited Members
Public Types inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
using SubjectType = DatagramExchange
using SingleHelper = DatagramExchange
Protected Member Functions inherited from infra::SingleObserver< DatagramExchangeObserver, DatagramExchange >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Detailed Description
Definition at line 10 of file LlmnrResponder.hpp.
Constructor & Destructor Documentation
LlmnrResponder()
services::LlmnrResponder::LlmnrResponder (services::DatagramFactory & factory, services::Multicast & multicast, services::IPv4Info & ipv4Info, infra::BoundedConstString name)
Definition at line 36 of file LlmnrResponder.cpp.
References services::ipv4, services::Multicast::JoinMulticastGroup(), llmnpMulticastAddress, and multicast.
         : datagramExchange(factory.Listen(*this, llmnpPort, IPVersions::ipv4))
         , multicast(multicast)
         , ipv4Info(ipv4Info)
         , name(name)
     {
         multicast.JoinMulticastGroup(llmnpMulticastAddress);
     }
~LlmnrResponder()
services::LlmnrResponder::~LlmnrResponder ()
Definition at line 45 of file LlmnrResponder.cpp.
References services::Multicast::LeaveMulticastGroup(), llmnpMulticastAddress, and multicast.
     {
         multicast.LeaveMulticastGroup(llmnpMulticastAddress);
     }
Member Function Documentation
DataReceived()
void services::LlmnrResponder::DataReceived (infra::StreamReaderWithRewinding & reader, services::UdpSocket from) override virtual
Implements services::DatagramExchangeObserver.
Definition at line 50 of file LlmnrResponder.cpp.
References datagramExchange, infra::InputStream::Failed(), name, PacketValid(), replying, services::DatagramExchange::RequestSendStream(), and infra::softFail.
     {
         if (replying)
             return;
         infra::DataInputStream::WithErrorPolicy stream(reader, infra::softFail);
         Header header;
         stream >> header;
         LlmnrString<32> queriedName;
         stream >> queriedName;
         Footer footer;
         stream >> footer;
         if (stream.Failed())
             return;
         if (!PacketValid(header, footer))
             return;
         if (queriedName.value != name)
             return;
         replying = true;
         id = header.id;
         datagramExchange->RequestSendStream(sizeof(Header) + LlmnrStringSize(name) + sizeof(Footer) + sizeof(Answer), from);
     }
PacketValid()
bool services::LlmnrResponder::PacketValid (const Header & header, const Footer & footer) const private
Definition at line 91 of file LlmnrResponder.cpp.
References services::LlmnrResponder::Footer::class_, services::LlmnrResponder::Footer::classIn, services::LlmnrResponder::Header::flags, services::LlmnrResponder::Header::flagsQuery, services::LlmnrResponder::Header::questionsCount, services::LlmnrResponder::Footer::type, and services::LlmnrResponder::Footer::typeA.
Referenced by DataReceived().
     {
         return header.flags == Header::flagsQuery && header.questionsCount == static_cast<uint16_t>(1) && footer.type == Footer::typeA && footer.class_ == Footer::classIn;
     }
SendStreamAvailable()
void services::LlmnrResponder::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::DatagramExchangeObserver.
Definition at line 77 of file LlmnrResponder.cpp.
References services::LlmnrResponder::Footer::classIn, services::LlmnrResponder::Answer::defaultTtl, services::LlmnrResponder::Header::flagsResponse, services::IPv4Info::GetIPv4Address(), id, ipv4Info, infra::MakeByteRange(), name, services::LlmnrResponder::Answer::nameIsPointer, replying, infra::BoundedStringBase< T >::size(), infra::StringAsByteRange(), and services::LlmnrResponder::Footer::typeA.
     {
         replying = false;
         infra::DataOutputStream::WithErrorPolicy stream(*writer);
         Header header{ id, Header::flagsResponse, 1, 1 };
         stream << header;
         stream << static_cast<uint8_t>(name.size()) << infra::StringAsByteRange(name) << '\0';
         Footer footer;
         stream << footer;
         Answer answer{ Answer::nameIsPointer | sizeof(Header), Footer::typeA, Footer::classIn, 0, Answer::defaultTtl, sizeof(IPv4Address), ipv4Info.GetIPv4Address() };
         stream << infra::MakeByteRange(answer);
     }
Member Data Documentation
datagramExchange
infra::SharedPtr<services::DatagramExchange> services::LlmnrResponder::datagramExchange private
Definition at line 64 of file LlmnrResponder.hpp.
Referenced by DataReceived().
id
infra::BigEndian<uint16_t> services::LlmnrResponder::id private
Definition at line 69 of file LlmnrResponder.hpp.
Referenced by SendStreamAvailable().
ipv4Info
services::IPv4Info& services::LlmnrResponder::ipv4Info private
Definition at line 66 of file LlmnrResponder.hpp.
Referenced by SendStreamAvailable().
llmnpMulticastAddress
const services::IPv4Address services::LlmnrResponder::llmnpMulticastAddress { 224, 0, 0, 252 } static
Definition at line 14 of file LlmnrResponder.hpp.
Referenced by LlmnrResponder(), and ~LlmnrResponder().
llmnpPort
const uint16_t services::LlmnrResponder::llmnpPort = 5355 static
Definition at line 15 of file LlmnrResponder.hpp.
multicast
services::Multicast& services::LlmnrResponder::multicast private
Definition at line 65 of file LlmnrResponder.hpp.
Referenced by LlmnrResponder(), and ~LlmnrResponder().
name
infra::BoundedConstString services::LlmnrResponder::name private
Definition at line 67 of file LlmnrResponder.hpp.
Referenced by DataReceived(), and SendStreamAvailable().
replying
bool services::LlmnrResponder::replying = false private
Definition at line 68 of file LlmnrResponder.hpp.
Referenced by DataReceived(), and SendStreamAvailable().
The documentation for this class was generated from the following files:
LlmnrResponder.hpp
LlmnrResponder.cpp