EMil: infra::ClaimableResource Class Reference
infra::ClaimableResource Class Reference
#include <ClaimableResource.hpp>
Classes
class ClaimerBase
class ClaimerWithSize
Public Types
using Claimer = ClaimerWithSize< INFRA_DEFAULT_FUNCTION_EXTRA_SIZE >
Public Member Functions
ClaimableResource ()=default
ClaimableResource (const ClaimableResource &other)=delete
ClaimableResource & operator= (const ClaimableResource &other)=delete
~ClaimableResource ()
Private Member Functions
void ReEvaluateClaim ()
void AddClaim (ClaimerBase &claimer)
void RemoveClaim (ClaimerBase &claimer)
void EnqueueClaimer (ClaimerBase &claimer)
void DequeueClaimer (ClaimerBase &claimer)
Private Attributes
infra::IntrusiveList< ClaimerBase > pendingClaims
ClaimerBase * currentClaim = nullptr
Detailed Description
Definition at line 11 of file ClaimableResource.hpp.
Member Typedef Documentation
Claimer
using infra::ClaimableResource::Claimer = ClaimerWithSize<INFRA_DEFAULT_FUNCTION_EXTRA_SIZE>
Definition at line 21 of file ClaimableResource.hpp.
Constructor & Destructor Documentation
ClaimableResource() [1/2]
infra::ClaimableResource::ClaimableResource () default
ClaimableResource() [2/2]
infra::ClaimableResource::ClaimableResource (const ClaimableResource & other) delete
~ClaimableResource()
infra::ClaimableResource::~ClaimableResource ()
Definition at line 7 of file ClaimableResource.cpp.
References currentClaim, and pendingClaims.
     {
         assert(currentClaim == nullptr);
         assert(pendingClaims.empty());
     }
Member Function Documentation
AddClaim()
void infra::ClaimableResource::AddClaim (ClaimerBase & claimer) private
Definition at line 23 of file ClaimableResource.cpp.
References currentClaim, EnqueueClaimer(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), ReEvaluateClaim(), and infra::EventDispatcherWorker::Schedule().
     {
         EnqueueClaimer(claimer);
         if (currentClaim == nullptr)
             infra::EventDispatcher::Instance().Schedule([this]() { ReEvaluateClaim(); });
     }
DequeueClaimer()
void infra::ClaimableResource::DequeueClaimer (ClaimerBase & claimer) private
Definition at line 47 of file ClaimableResource.cpp.
References pendingClaims.
Referenced by RemoveClaim().
     {
         pendingClaims.erase(claimer);
     }
EnqueueClaimer()
void infra::ClaimableResource::EnqueueClaimer (ClaimerBase & claimer) private
Definition at line 42 of file ClaimableResource.cpp.
References pendingClaims.
Referenced by AddClaim().
     {
         pendingClaims.push_back(claimer);
     }
operator=()
ClaimableResource& infra::ClaimableResource::operator= (const ClaimableResource & other) delete
ReEvaluateClaim()
void infra::ClaimableResource::ReEvaluateClaim () private
Definition at line 13 of file ClaimableResource.cpp.
References infra::ClaimableResource::ClaimerBase::ClaimGranted(), currentClaim, and pendingClaims.
Referenced by AddClaim(), and RemoveClaim().
     {
         if (currentClaim == nullptr && !pendingClaims.empty())
         {
             currentClaim = &pendingClaims.front();
             pendingClaims.pop_front();
             currentClaim->ClaimGranted();
         }
     }
RemoveClaim()
void infra::ClaimableResource::RemoveClaim (ClaimerBase & claimer) private
Definition at line 31 of file ClaimableResource.cpp.
References currentClaim, DequeueClaimer(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), pendingClaims, ReEvaluateClaim(), and infra::EventDispatcherWorker::Schedule().
     {
         if (currentClaim == &claimer)
         {
             currentClaim = nullptr;
             infra::EventDispatcher::Instance().Schedule([this]() { ReEvaluateClaim(); });
         }
         else if (!pendingClaims.empty())
             DequeueClaimer(claimer);
     }
Member Data Documentation
currentClaim
ClaimerBase* infra::ClaimableResource::currentClaim = nullptr private
Definition at line 37 of file ClaimableResource.hpp.
Referenced by AddClaim(), ReEvaluateClaim(), RemoveClaim(), and ~ClaimableResource().
pendingClaims
infra::IntrusiveList<ClaimerBase> infra::ClaimableResource::pendingClaims private
Definition at line 36 of file ClaimableResource.hpp.
Referenced by DequeueClaimer(), EnqueueClaimer(), ReEvaluateClaim(), RemoveClaim(), and ~ClaimableResource().
The documentation for this class was generated from the following files:
ClaimableResource.hpp
ClaimableResource.cpp