EMil: infra::JsonArrayFormatter Class Reference
infra::JsonArrayFormatter Class Reference
#include <JsonFormatter.hpp>
Public Types
using WithStringStream = infra::WithStorage< JsonArrayFormatter, infra::StringOutputStream >
Public Member Functions
JsonArrayFormatter (infra::TextOutputStream &stream)
JsonArrayFormatter (const JsonArrayFormatter &other)=delete
JsonArrayFormatter (JsonArrayFormatter &&other)
JsonArrayFormatter & operator= (const JsonArrayFormatter &other)=delete
JsonArrayFormatter & operator= (JsonArrayFormatter &&other)
~JsonArrayFormatter ()
void Add (bool tag)
void Add (int32_t tag)
void Add (uint32_t tag)
void Add (int64_t tag)
void Add (const char *tag)
void Add (infra::BoundedConstString tag)
JsonObjectFormatter SubObject ()
JsonArrayFormatter SubArray ()
bool Failed () const
Private Member Functions
void InsertSeparation ()
Private Attributes
infra::Optional< infra::TextOutputStream::WithErrorPolicy > stream
bool empty = true
Detailed Description
Definition at line 57 of file JsonFormatter.hpp.
Member Typedef Documentation
WithStringStream
using infra::JsonArrayFormatter::WithStringStream = infra::WithStorage<JsonArrayFormatter, infra::StringOutputStream>
Definition at line 60 of file JsonFormatter.hpp.
Constructor & Destructor Documentation
JsonArrayFormatter() [1/3]
infra::JsonArrayFormatter::JsonArrayFormatter (infra::TextOutputStream & stream) explicit
Definition at line 255 of file JsonFormatter.cpp.
Referenced by SubArray().
         : stream(infra::inPlace, stream.Writer(), infra::noFail)
     {
         *this->stream << "[ ";
     }
JsonArrayFormatter() [2/3]
infra::JsonArrayFormatter::JsonArrayFormatter (const JsonArrayFormatter & other) delete
JsonArrayFormatter() [3/3]
infra::JsonArrayFormatter::JsonArrayFormatter (JsonArrayFormatter && other)
Definition at line 261 of file JsonFormatter.cpp.
References infra::none.
         : stream(other.stream)
     {
         other.stream = infra::none;
     }
~JsonArrayFormatter()
infra::JsonArrayFormatter::~JsonArrayFormatter ()
Definition at line 275 of file JsonFormatter.cpp.
References infra::none, and stream.
     {
         if (stream != infra::none)
             *stream << " ]";
     }
Member Function Documentation
Add() [1/6]
void infra::JsonArrayFormatter::Add (bool tag)
Definition at line 281 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << (tag ? "true" : "false");
     }
Add() [2/6]
void infra::JsonArrayFormatter::Add (int32_t tag)
Definition at line 287 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << tag;
     }
Add() [3/6]
void infra::JsonArrayFormatter::Add (uint32_t tag)
Definition at line 293 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << tag;
     }
Add() [4/6]
void infra::JsonArrayFormatter::Add (int64_t tag)
Definition at line 299 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << tag;
     }
Add() [5/6]
void infra::JsonArrayFormatter::Add (const char * tag)
Definition at line 305 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << '"';
         InsertEscapedTag(*stream, tag);
         *stream << '"';
     }
Add() [6/6]
void infra::JsonArrayFormatter::Add (infra::BoundedConstString tag)
Definition at line 313 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         *stream << '"';
         InsertEscapedTag(*stream, tag);
         *stream << '"';
     }
Failed()
bool infra::JsonArrayFormatter::Failed () const
Definition at line 335 of file JsonFormatter.cpp.
References infra::OutputStream::Failed(), and stream.
     {
         return stream->Failed();
     }
InsertSeparation()
void infra::JsonArrayFormatter::InsertSeparation () private
Definition at line 340 of file JsonFormatter.cpp.
References empty, and stream.
Referenced by Add(), SubArray(), and SubObject().
     {
         if (!empty)
             *stream << ", ";
         empty = false;
     }
operator=() [1/2]
JsonArrayFormatter& infra::JsonArrayFormatter::operator= (const JsonArrayFormatter & other) delete
operator=() [2/2]
JsonArrayFormatter & infra::JsonArrayFormatter::operator= (JsonArrayFormatter && other)
Definition at line 267 of file JsonFormatter.cpp.
References infra::none, and stream.
     {
         stream = other.stream;
         other.stream = infra::none;
         return *this;
     }
SubArray()
JsonArrayFormatter infra::JsonArrayFormatter::SubArray ()
Definition at line 328 of file JsonFormatter.cpp.
References InsertSeparation(), JsonArrayFormatter(), and stream.
     {
         InsertSeparation();
         return JsonArrayFormatter(*stream);
     }
SubObject()
JsonObjectFormatter infra::JsonArrayFormatter::SubObject ()
Definition at line 321 of file JsonFormatter.cpp.
References InsertSeparation(), and stream.
     {
         InsertSeparation();
         return JsonObjectFormatter(*stream);
     }
Member Data Documentation
empty
bool infra::JsonArrayFormatter::empty = true private
Definition at line 85 of file JsonFormatter.hpp.
Referenced by InsertSeparation().
stream
infra::Optional<infra::TextOutputStream::WithErrorPolicy> infra::JsonArrayFormatter::stream private
Definition at line 84 of file JsonFormatter.hpp.
Referenced by Add(), Failed(), InsertSeparation(), operator=(), SubArray(), SubObject(), and ~JsonArrayFormatter().
The documentation for this class was generated from the following files:
JsonFormatter.hpp
JsonFormatter.cpp