EMil: TestSpiMasterWithChipSelect.cpp File Reference
TestSpiMasterWithChipSelect.cpp File Reference
Classes
class SpiMasterWithChipSelectTest
Functions
TEST_F (SpiMasterWithChipSelectTest, ChipSelectStartsHigh)
TEST_F (SpiMasterWithChipSelectTest, on_StartSession_chip_select_is_activated)
TEST_F (SpiMasterWithChipSelectTest, on_EndSession_chip_select_is_deactivated)
TEST_F (SpiMasterWithChipSelectTest, additional_ChipSelectConfigurator_is_invoked)
TEST_F (SpiMasterWithChipSelectTest, SetCommunicationConfigurator_is_forwarded)
Function Documentation
TEST_F() [1/5]
TEST_F (SpiMasterWithChipSelectTest , ChipSelectStartsHigh)
Definition at line 24 of file TestSpiMasterWithChipSelect.cpp.
References EXPECT_TRUE().
 {
     EXPECT_TRUE(chipSelect.GetStubState());
 }
TEST_F() [2/5]
TEST_F (SpiMasterWithChipSelectTest , on_StartSession_chip_select_is_activated)
Definition at line 29 of file TestSpiMasterWithChipSelect.cpp.
References infra::emptyFunction, EXPECT_FALSE(), and hal::stop.
 {
     std::vector<uint8_t> buffer = { 0 };
     EXPECT_CALL(spiMock, SendAndReceiveMock(buffer, infra::MemoryRange<uint8_t>(buffer), hal::SpiAction::stop, testing::_));
     spi->StartSession();
     spi->SendAndReceive(buffer, buffer, hal::SpiAction::stop, infra::emptyFunction);
     EXPECT_FALSE(chipSelect.GetStubState());
 }
TEST_F() [3/5]
TEST_F (SpiMasterWithChipSelectTest , on_EndSession_chip_select_is_deactivated)
Definition at line 40 of file TestSpiMasterWithChipSelect.cpp.
References infra::emptyFunction, EXPECT_TRUE(), and hal::stop.
 {
     std::vector<uint8_t> buffer = { 0 };
     EXPECT_CALL(spiMock, SendAndReceiveMock(buffer, infra::MemoryRange<uint8_t>(buffer), hal::SpiAction::stop, testing::_));
     spi->StartSession();
     spi->SendAndReceive(buffer, buffer, hal::SpiAction::stop, infra::emptyFunction);
     spi->EndSession();
     EXPECT_TRUE(chipSelect.GetStubState());
 }
TEST_F() [4/5]
TEST_F (SpiMasterWithChipSelectTest , additional_ChipSelectConfigurator_is_invoked)
Definition at line 52 of file TestSpiMasterWithChipSelect.cpp.
References infra::emptyFunction, and hal::stop.
 {
     std::vector<uint8_t> buffer = { 0 };
     hal::ChipSelectConfiguratorMock chipSelectConfiguratorMock;
     spi->SetChipSelectConfigurator(chipSelectConfiguratorMock);
     EXPECT_CALL(spiMock, SendAndReceiveMock(buffer, infra::MemoryRange<uint8_t>(buffer), hal::SpiAction::stop, testing::_));
     EXPECT_CALL(chipSelectConfiguratorMock, StartSession());
     spi->StartSession();
     spi->SendAndReceive(buffer, buffer, hal::SpiAction::stop, infra::emptyFunction);
     EXPECT_CALL(chipSelectConfiguratorMock, EndSession());
     spi->EndSession();
 }
TEST_F() [5/5]
TEST_F (SpiMasterWithChipSelectTest , SetCommunicationConfigurator_is_forwarded)
Definition at line 67 of file TestSpiMasterWithChipSelect.cpp.
 {
     hal::CommunicationConfiguratorMock configurator;
     EXPECT_CALL(spiMock, SetCommunicationConfigurator(testing::Ref(configurator)));
     spi->SetCommunicationConfigurator(configurator);
     EXPECT_CALL(spiMock, ResetCommunicationConfigurator());
     spi->ResetCommunicationConfigurator();
 }