EMil: infra::ByteOutputStreamWriter Class Reference
infra::ByteOutputStreamWriter Class Reference
#include <ByteOutputStream.hpp>
Public Types
template<std::size_t Max>
using WithStorage = infra::WithStorage< ByteOutputStreamWriter, std::array< uint8_t, Max > >
Public Member Functions
ByteOutputStreamWriter (ByteRange range)
ByteRange Processed () const
ByteRange Remaining () const
void Reset ()
template<class T >
ReservedProxy< T > Reserve (StreamErrorPolicy &errorPolicy)
Protected Member Functions
virtual void Insert (ConstByteRange range, StreamErrorPolicy &errorPolicy) override
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Private Member Functions
std::size_t Available () const override
virtual std::size_t ConstructSaveMarker () const override
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const override
virtual infra::ByteRange SaveState (std::size_t marker) override
virtual void RestoreState (infra::ByteRange range) override
virtual infra::ByteRange Overwrite (std::size_t marker) override
Private Attributes
ByteRange streamRange
std::size_t offset = 0
Detailed Description
Definition at line 24 of file ByteOutputStream.hpp.
Member Typedef Documentation
WithStorage
template<std::size_t Max> using infra::ByteOutputStreamWriter::WithStorage = infra::WithStorage<ByteOutputStreamWriter, std::array<uint8_t, Max> >
Definition at line 29 of file ByteOutputStream.hpp.
Constructor & Destructor Documentation
ByteOutputStreamWriter()
infra::ByteOutputStreamWriter::ByteOutputStreamWriter (ByteRange range) explicit
Definition at line 5 of file ByteOutputStream.cpp.
         : streamRange(streamRange)
     {}
Member Function Documentation
Available()
std::size_t infra::ByteOutputStreamWriter::Available () const override private virtual
Implements infra::StreamWriter.
Definition at line 32 of file ByteOutputStream.cpp.
References offset, infra::MemoryRange< T >::size(), and streamRange.
     {
         return streamRange.size() - offset;
     }
ConstructSaveMarker()
std::size_t infra::ByteOutputStreamWriter::ConstructSaveMarker () const override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 37 of file ByteOutputStream.cpp.
References offset.
     {
         return offset;
     }
GetProcessedBytesSince()
std::size_t infra::ByteOutputStreamWriter::GetProcessedBytesSince (std::size_t marker) const override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 42 of file ByteOutputStream.cpp.
References offset.
     {
         return static_cast<std::size_t>(offset - marker);
     }
Insert()
void infra::ByteOutputStreamWriter::Insert (ConstByteRange range, StreamErrorPolicy & errorPolicy) override protected virtual
Implements infra::StreamWriter.
Definition at line 24 of file ByteOutputStream.cpp.
References infra::MemoryRange< T >::begin(), offset, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), infra::MemoryRange< T >::size(), and streamRange.
     {
         errorPolicy.ReportResult(dataRange.size() <= streamRange.size() - offset);
         dataRange.shrink_from_back_to(streamRange.size() - offset);
         std::copy(dataRange.begin(), dataRange.begin() + dataRange.size(), streamRange.begin() + offset);
         offset += dataRange.size();
     }
Overwrite()
infra::ByteRange infra::ByteOutputStreamWriter::Overwrite (std::size_t marker) override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 62 of file ByteOutputStream.cpp.
References infra::DiscardHead(), and streamRange.
     {
         return infra::DiscardHead(streamRange, marker);
     }
Processed()
ByteRange infra::ByteOutputStreamWriter::Processed () const
Definition at line 9 of file ByteOutputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MakeRange(), offset, and streamRange.
     {
         return MakeRange(streamRange.begin(), streamRange.begin() + offset);
     }
Remaining()
ByteRange infra::ByteOutputStreamWriter::Remaining () const
Definition at line 14 of file ByteOutputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), infra::MakeRange(), offset, and streamRange.
Referenced by infra::SavedMarkerStreamWriter::~SavedMarkerStreamWriter().
     {
         return MakeRange(streamRange.begin() + offset, streamRange.end());
     }
Reserve()
template<class T > ReservedProxy< T > infra::ByteOutputStreamWriter::Reserve (StreamErrorPolicy & errorPolicy)
Definition at line 73 of file ByteOutputStream.hpp.
References infra::MemoryRange< T >::begin(), offset, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), infra::MemoryRange< T >::size(), and streamRange.
     {
         ByteRange reservedRange(streamRange.begin() + offset, streamRange.begin() + offset + sizeof(T));
         std::size_t spaceLeft = streamRange.size() - offset;
         bool spaceOk = reservedRange.size() <= spaceLeft;
         errorPolicy.ReportResult(spaceOk);
         if (!spaceOk)
             reservedRange.shrink_from_back_to(spaceLeft);
         offset += reservedRange.size();
         return ReservedProxy<T>(reservedRange);
     }
Reset()
void infra::ByteOutputStreamWriter::Reset ()
Definition at line 19 of file ByteOutputStream.cpp.
References offset.
     {
         offset = 0;
     }
RestoreState()
void infra::ByteOutputStreamWriter::RestoreState (infra::ByteRange range) override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 56 of file ByteOutputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), offset, and streamRange.
     {
         std::copy(range.end(), streamRange.end(), range.begin());
         offset += std::distance(streamRange.begin() + offset, range.begin()) + std::distance(range.end(), streamRange.end());
     }
SaveState()
infra::ByteRange infra::ByteOutputStreamWriter::SaveState (std::size_t marker) override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 47 of file ByteOutputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), offset, and streamRange.
     {
         uint8_t* copyBegin = streamRange.begin() + marker;
         uint8_t* copyEnd = streamRange.begin() + offset;
         std::copy_backward(copyBegin, copyEnd, streamRange.end());
         return infra::ByteRange(copyBegin, streamRange.end() - std::distance(copyBegin, copyEnd));
     }
Member Data Documentation
offset
std::size_t infra::ByteOutputStreamWriter::offset = 0 private
Definition at line 55 of file ByteOutputStream.hpp.
Referenced by Available(), ConstructSaveMarker(), GetProcessedBytesSince(), Insert(), Processed(), Remaining(), Reserve(), Reset(), RestoreState(), and SaveState().
streamRange
ByteRange infra::ByteOutputStreamWriter::streamRange private
Definition at line 54 of file ByteOutputStream.hpp.
Referenced by Available(), Insert(), Overwrite(), Processed(), Remaining(), Reserve(), RestoreState(), and SaveState().
The documentation for this class was generated from the following files:
ByteOutputStream.hpp
ByteOutputStream.cpp