EMil: infra::MainClockReference Class Reference
infra::MainClockReference Class Reference
#include <LowPowerEventDispatcher.hpp>
Public Member Functions
MainClockReference ()
void Refere ()
void Release ()
bool IsReferenced () const
Private Attributes
std::atomic< uint32_t > numReferenced
Detailed Description
Definition at line 10 of file LowPowerEventDispatcher.hpp.
Constructor & Destructor Documentation
MainClockReference()
infra::MainClockReference::MainClockReference ()
Definition at line 5 of file LowPowerEventDispatcher.cpp.
         : numReferenced(0)
     {}
Member Function Documentation
IsReferenced()
bool infra::MainClockReference::IsReferenced () const
Definition at line 19 of file LowPowerEventDispatcher.cpp.
References numReferenced.
     {
         return numReferenced != 0;
     }
Refere()
void infra::MainClockReference::Refere ()
Definition at line 9 of file LowPowerEventDispatcher.cpp.
References numReferenced.
Referenced by hal::LowPowerSpiMaster::SendAndReceive(), and hal::LowPowerSerialCommunication::SendData().
     {
         ++numReferenced;
     }
Release()
void infra::MainClockReference::Release ()
Definition at line 14 of file LowPowerEventDispatcher.cpp.
References numReferenced.
Referenced by hal::LowPowerSpiMaster::SendAndReceive(), and hal::LowPowerSerialCommunication::SendData().
     {
         --numReferenced;
     }
Member Data Documentation
numReferenced
std::atomic<uint32_t> infra::MainClockReference::numReferenced private
Definition at line 20 of file LowPowerEventDispatcher.hpp.
Referenced by IsReferenced(), Refere(), and Release().
The documentation for this class was generated from the following files:
LowPowerEventDispatcher.hpp
LowPowerEventDispatcher.cpp