EMil: infra::Asn1SequenceIterator Class Reference
infra::Asn1SequenceIterator Class Reference
#include <Asn1.hpp>
Public Member Functions
Asn1SequenceIterator ()
Asn1SequenceIterator (infra::ConstByteRange range)
bool operator== (const Asn1SequenceIterator &other) const
bool operator!= (const Asn1SequenceIterator &other) const
Asn1Value & operator* ()
const Asn1Value & operator* () const
Asn1Value * operator-> ()
const Asn1Value * operator-> () const
Asn1SequenceIterator & operator++ ()
Asn1SequenceIterator operator++ (int)
Private Member Functions
Asn1Value MakeValue () const
Private Attributes
infra::ConstByteRange range
Asn1Value currentValue
Detailed Description
Definition at line 26 of file Asn1.hpp.
Constructor & Destructor Documentation
Asn1SequenceIterator() [1/2]
infra::Asn1SequenceIterator::Asn1SequenceIterator ()
Definition at line 25 of file Asn1.cpp.
         : currentValue(0, infra::ConstByteRange())
     {}
Asn1SequenceIterator() [2/2]
infra::Asn1SequenceIterator::Asn1SequenceIterator (infra::ConstByteRange range) explicit
Definition at line 29 of file Asn1.cpp.
         : range(range)
         , currentValue(MakeValue())
     {}
Member Function Documentation
MakeValue()
Asn1Value infra::Asn1SequenceIterator::MakeValue () const private
Definition at line 86 of file Asn1.cpp.
References infra::MemoryRange< T >::front(), infra::Head(), infra::MemoryRange< T >::pop_front(), and range.
Referenced by operator++().
     {
         infra::ConstByteRange range = this->range;
         uint8_t tag = range.front();
         range.pop_front();
         uint32_t length = range.front();
         range.pop_front();
         if (length == 0x81)
         {
             length = range.front();
             range.pop_front();
         }
         else if (length == 0x82)
         {
             length = range.front() << 8;
             range.pop_front();
             length += range.front();
             range.pop_front();
         }
         return Asn1Value(tag, infra::Head(range, length));
     }
operator!=()
bool infra::Asn1SequenceIterator::operator!= (const Asn1SequenceIterator & other) const
Definition at line 39 of file Asn1.cpp.
     {
         return !(*this == other);
     }
operator*() [1/2]
Asn1Value & infra::Asn1SequenceIterator::operator* ()
Definition at line 44 of file Asn1.cpp.
References currentValue.
     {
         return currentValue;
     }
operator*() [2/2]
const Asn1Value & infra::Asn1SequenceIterator::operator* () const
Definition at line 49 of file Asn1.cpp.
References currentValue.
     {
         return currentValue;
     }
operator++() [1/2]
Asn1SequenceIterator & infra::Asn1SequenceIterator::operator++ ()
Definition at line 64 of file Asn1.cpp.
References currentValue, infra::MemoryRange< T >::empty(), infra::MemoryRange< T >::end(), MakeValue(), infra::Asn1Value::range, and range.
     {
         if (!currentValue.range.empty())
         {
             range = infra::ConstByteRange(currentValue.range.end(), range.end());
             if (range.empty())
                 currentValue = Asn1Value(0, infra::ConstByteRange());
             else
                 currentValue = MakeValue();
         }
         return *this;
     }
operator++() [2/2]
Asn1SequenceIterator infra::Asn1SequenceIterator::operator++ (int)
Definition at line 79 of file Asn1.cpp.
     {
         Asn1SequenceIterator result(*this);
         ++*this;
         return result;
     }
operator->() [1/2]
Asn1Value * infra::Asn1SequenceIterator::operator-> ()
Definition at line 54 of file Asn1.cpp.
References currentValue.
     {
         return &currentValue;
     }
operator->() [2/2]
const Asn1Value * infra::Asn1SequenceIterator::operator-> () const
Definition at line 59 of file Asn1.cpp.
References currentValue.
     {
         return &currentValue;
     }
operator==()
bool infra::Asn1SequenceIterator::operator== (const Asn1SequenceIterator & other) const
Definition at line 34 of file Asn1.cpp.
References range.
     {
         return range == other.range;
     }
Member Data Documentation
currentValue
Asn1Value infra::Asn1SequenceIterator::currentValue private
Definition at line 49 of file Asn1.hpp.
Referenced by operator*(), operator++(), and operator->().
range
infra::ConstByteRange infra::Asn1SequenceIterator::range private
Definition at line 48 of file Asn1.hpp.
Referenced by MakeValue(), operator++(), and operator==().
The documentation for this class was generated from the following files:
Asn1.hpp
Asn1.cpp