EMil: TestFlashQuadSpiSingleSpeed.cpp File Reference
TestFlashQuadSpiSingleSpeed.cpp File Reference
Classes
class FlashQuadSpiSingleSpeedTest
Functions
TEST_F (FlashQuadSpiSingleSpeedTest, Construction)
TEST_F (FlashQuadSpiSingleSpeedTest, ReadData)
TEST_F (FlashQuadSpiSingleSpeedTest, ReadDataAtNonZeroAddress)
TEST_F (FlashQuadSpiSingleSpeedTest, WriteData)
TEST_F (FlashQuadSpiSingleSpeedTest, WriteDataFinishesOnFlagPoll)
TEST_F (FlashQuadSpiSingleSpeedTest, WriteDataAtNonZeroAddress)
TEST_F (FlashQuadSpiSingleSpeedTest, WhenPageBoundaryIsCrossedFirstPartIsWritten)
TEST_F (FlashQuadSpiSingleSpeedTest, WhenPageBoundaryIsCrossedSecondPartIsWritten)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseFirstSector)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseFirstSectorFinishesOnFlagPoll)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseSecondSector)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseMultipleErasesSubSector)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseMultipleErasesTwoSectors)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseMultipleErasesBlock)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseMultipleErasesSectorsAndBlock)
TEST_F (FlashQuadSpiSingleSpeedTest, EraseAllErasesChip)
Function Documentation
TEST_F() [1/16]
TEST_F (FlashQuadSpiSingleSpeedTest , Construction)
Definition at line 32 of file TestFlashQuadSpiSingleSpeed.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(4096, flash.NumberOfSectors());
     EXPECT_EQ(4096, flash.SizeOfSector(0));
 }
TEST_F() [2/16]
TEST_F (FlashQuadSpiSingleSpeedTest , ReadData)
Definition at line 38 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandReadData, EXPECT_EQ(), infra::MakeByteRange(), infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     std::array<uint8_t, 4> receiveData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiStub, ReceiveDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandReadData), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, hal::QuadSpi::Lines::SingleSpeed()))
         .WillOnce(testing::Return(infra::MakeByteRange(receiveData)));
     EXPECT_CALL(finished, callback());
     std::array<uint8_t, 4> buffer;
     flash.ReadBuffer(buffer, 0, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_EQ(receiveData, buffer);
 }
TEST_F() [3/16]
TEST_F (FlashQuadSpiSingleSpeedTest , ReadDataAtNonZeroAddress)
Definition at line 52 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandReadData, EXPECT_EQ(), infra::MakeByteRange(), infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     std::array<uint8_t, 4> receiveData = { 1, 2, 3, 4 };
     EXPECT_CALL(spiStub, ReceiveDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandReadData), hal::QuadSpi::AddressToVector(0x123456, 3), {}, 0 }, hal::QuadSpi::Lines::SingleSpeed()))
         .WillOnce(testing::Return(infra::MakeByteRange(receiveData)));
     EXPECT_CALL(finished, callback());
     std::array<uint8_t, 4> buffer;
     flash.ReadBuffer(buffer, 0 + 0x123456, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_EQ(receiveData, buffer);
 }
TEST_F() [4/16]
TEST_F (FlashQuadSpiSingleSpeedTest , WriteData)
Definition at line 66 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandPageProgram, infra::MakeByteRange(), infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     const std::array<uint8_t, 4> sendData = { 1, 2, 3, 4 };
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandPageProgram), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::MakeByteRange(sendData), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.WriteBuffer(sendData, 0, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [5/16]
TEST_F (FlashQuadSpiSingleSpeedTest , WriteDataFinishesOnFlagPoll)
Definition at line 77 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandPageProgram, infra::MakeByteRange(), infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     const std::array<uint8_t, 4> sendData = { 1, 2, 3, 4 };
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandPageProgram), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::MakeByteRange(sendData), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.WriteBuffer(sendData, 0, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_CALL(finished, callback());
     spiStub.onDone();
     ExecuteAllActions();
 }
TEST_F() [6/16]
TEST_F (FlashQuadSpiSingleSpeedTest , WriteDataAtNonZeroAddress)
Definition at line 92 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandPageProgram, infra::emptyFunction, infra::MakeByteRange(), infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     const std::array<uint8_t, 4> sendData = { 1, 2, 3, 4 };
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandPageProgram), hal::QuadSpi::AddressToVector(0x123456, 3), {}, 0 }, infra::MakeByteRange(sendData), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.WriteBuffer(sendData, 0 + 0x123456, infra::emptyFunction);
     ExecuteAllActions();
 }
TEST_F() [7/16]
TEST_F (FlashQuadSpiSingleSpeedTest , WhenPageBoundaryIsCrossedFirstPartIsWritten)
Definition at line 103 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandPageProgram, infra::emptyFunction, infra::MakeOptional(), infra::MakeRange(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     const std::array<uint8_t, 4> sendData = { 1, 2, 3, 4 };
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandPageProgram), hal::QuadSpi::AddressToVector(254, 3), {}, 0 }, infra::MakeRange(sendData.data(), sendData.data() + 2), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.WriteBuffer(sendData, 0 + 254, infra::emptyFunction);
     ExecuteAllActions();
 }
TEST_F() [8/16]
TEST_F (FlashQuadSpiSingleSpeedTest , WhenPageBoundaryIsCrossedSecondPartIsWritten)
Definition at line 114 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandPageProgram, infra::emptyFunction, infra::MakeOptional(), infra::MakeRange(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     testing::InSequence s;
     const std::array<uint8_t, 6> sendData = { 1, 2, 3, 4, 5, 6 };
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandPageProgram), hal::QuadSpi::AddressToVector(254, 3), {}, 0 }, infra::MakeRange(sendData.data(), sendData.data() + 2), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandPageProgram), hal::QuadSpi::AddressToVector(256, 3), {}, 0 }, infra::MakeRange(sendData.data() + 2, sendData.data() + 6), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.WriteBuffer(sendData, 0 + 254, infra::emptyFunction);
     spiStub.onDone();
     ExecuteAllActions();
 }
TEST_F() [9/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseFirstSector)
Definition at line 131 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseSector, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSector(0, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [10/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseFirstSectorFinishesOnFlagPoll)
Definition at line 141 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseSector, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSector(0, [this]() { finished.callback(); });
     ExecuteAllActions();
     EXPECT_CALL(finished, callback());
     spiStub.onDone();
     ExecuteAllActions();
 }
TEST_F() [11/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseSecondSector)
Definition at line 155 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseSector, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(4096, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSector(1, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [12/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseMultipleErasesSubSector)
Definition at line 165 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseSector, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSectors(0, 1, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [13/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseMultipleErasesTwoSectors)
Definition at line 175 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseSector, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     testing::InSequence s;
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(4096, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSectors(0, 2, [this]() { finished.callback(); });
     spiStub.onDone();
     ExecuteAllActions();
 }
TEST_F() [14/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseMultipleErasesBlock)
Definition at line 191 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseBlock, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseBlock), hal::QuadSpi::AddressToVector(0, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSectors(0, 16, [this]() { finished.callback(); });
     ExecuteAllActions();
 }
TEST_F() [15/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseMultipleErasesSectorsAndBlock)
Definition at line 201 of file TestFlashQuadSpiSingleSpeed.cpp.
References hal::QuadSpi::AddressToVector(), services::FlashQuadSpiSingleSpeed::commandEraseBlock, services::FlashQuadSpiSingleSpeed::commandEraseSector, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     testing::InSequence s;
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(61440, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseBlock), hal::QuadSpi::AddressToVector(65536, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseSector), hal::QuadSpi::AddressToVector(131072, 3), {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseSectors(15, 33, [this]() { finished.callback(); });
     spiStub.onDone();
     spiStub.onDone();
     ExecuteAllActions();
 }
TEST_F() [16/16]
TEST_F (FlashQuadSpiSingleSpeedTest , EraseAllErasesChip)
Definition at line 220 of file TestFlashQuadSpiSingleSpeed.cpp.
References services::FlashQuadSpiSingleSpeed::commandEraseChip, infra::MakeOptional(), and hal::QuadSpi::Lines::SingleSpeed().
 {
     EXPECT_ENABLE_WRITE();
     EXPECT_CALL(spiStub, SendDataMock(hal::QuadSpi::Header{ infra::MakeOptional(services::FlashQuadSpiSingleSpeed::commandEraseChip), {}, {}, 0 }, infra::ConstByteRange(), hal::QuadSpi::Lines::SingleSpeed()));
     EXPECT_POLL_WRITE_DONE();
     flash.EraseAll([this]() { finished.callback(); });
     ExecuteAllActions();
 }