EMil: services::ConnectionSerial::MessageHeader Class Reference
services::ConnectionSerial::MessageHeader Class Reference
Public Member Functions
MessageHeader ()
MessageHeader (MessageType type)
void AddByte (uint8_t byte)
void SetSize (size_t size)
bool IsFailed ()
bool IsDone ()
MessageType Type ()
size_t Size ()
infra::ConstByteRange Range ()
Static Public Member Functions
static bool IsHeaderByte (uint8_t byte)
static bool IsEscapeByte (uint8_t byte)
Static Public Attributes
static const size_t HeaderSize = 3
Private Member Functions
void SetContent (uint16_t content)
Private Attributes
std::array< uint8_t, HeaderSize > headerContent
bool isComplete = false
bool isFailed = false
uint8_t byteToSet = 0
Detailed Description
Definition at line 73 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
MessageHeader() [1/2]
services::ConnectionSerial::MessageHeader::MessageHeader ()
Definition at line 213 of file ConnectionSerial.cpp.
     {}
MessageHeader() [2/2]
services::ConnectionSerial::MessageHeader::MessageHeader (MessageType type)
Definition at line 216 of file ConnectionSerial.cpp.
References services::ConnectionSerial::SizeRequest.
     {
         headerContent[0] = static_cast<uint8_t>(type);
         if (type == MessageType::SizeRequest)
         {
             headerContent[1] = headerContent[2] = static_cast<uint8_t>(MessageType::SizeRequest);
             isComplete = true;
         }
     }
Member Function Documentation
AddByte()
void services::ConnectionSerial::MessageHeader::AddByte (uint8_t byte)
Definition at line 247 of file ConnectionSerial.cpp.
References services::ConnectionSerial::SizeRequest.
     {
         if (IsDone())
             return;
         switch (byteToSet)
         {
         case 0:
             if (!IsHeaderByte(byte))
                 isFailed = true;
             else
                 headerContent[0] = byte;
             break;
         case 1:
             if (Type() != MessageType::SizeRequest)
                 SetContent(static_cast<uint16_t>(byte << 8));
             else if (static_cast<MessageType>(byte) != MessageType::SizeRequest)
                 isFailed = true;
             break;
         case 2:
             if (Type() != MessageType::SizeRequest)
                 SetContent(static_cast<uint16_t>(byte + Size()));
             else if (static_cast<MessageType>(byte) != MessageType::SizeRequest)
                 isFailed = true;
             isComplete = true;
             break;
         }
         ++byteToSet;
     }
IsDone()
bool services::ConnectionSerial::MessageHeader::IsDone ()
Definition at line 237 of file ConnectionSerial.cpp.
     {
         return isComplete || isFailed;
     }
IsEscapeByte()
bool services::ConnectionSerial::MessageHeader::IsEscapeByte (uint8_t byte) static
Definition at line 302 of file ConnectionSerial.cpp.
References services::ConnectionSerial::Escape.
Referenced by services::ConnectionSerial::StateConnected::CopyEscapedContent(), and services::ConnectionSerial::StateConnected::IsEscapedByte().
     {
         return byte == static_cast<uint8_t>(MessageType::Escape);
     }
IsFailed()
bool services::ConnectionSerial::MessageHeader::IsFailed ()
Definition at line 242 of file ConnectionSerial.cpp.
     {
         return isFailed;
     }
IsHeaderByte()
bool services::ConnectionSerial::MessageHeader::IsHeaderByte (uint8_t byte) static
Definition at line 297 of file ConnectionSerial.cpp.
References services::ConnectionSerial::SizeRequest, and services::ConnectionSerial::SizeUpdate.
Referenced by services::ConnectionSerial::StateConnected::CopyEscapedContent(), and services::ConnectionSerial::StateConnected::IsEscapedByte().
     {
         return byte >= static_cast<uint8_t>(MessageType::SizeRequest) && byte <= static_cast<uint8_t>(MessageType::SizeUpdate);
     }
Range()
infra::ConstByteRange services::ConnectionSerial::MessageHeader::Range ()
Definition at line 292 of file ConnectionSerial.cpp.
References infra::MakeByteRange().
     {
         return infra::MakeByteRange(headerContent);
     }
SetContent()
void services::ConnectionSerial::MessageHeader::SetContent (uint16_t content) private
Definition at line 287 of file ConnectionSerial.cpp.
References infra::Copy(), infra::MakeByteRange(), infra::MakeRange(), and infra::Tail().
     {
         infra::Copy(infra::MakeByteRange(infra::BigEndian<uint16_t>(content)), infra::Tail(infra::MakeRange(headerContent), 2));
     }
SetSize()
void services::ConnectionSerial::MessageHeader::SetSize (size_t size)
Definition at line 281 of file ConnectionSerial.cpp.
     {
         SetContent(static_cast<uint16_t>(size));
         isComplete = true;
     }
Size()
size_t services::ConnectionSerial::MessageHeader::Size ()
Definition at line 231 of file ConnectionSerial.cpp.
References services::ConnectionSerial::SizeRequest.
     {
         assert(Type() != MessageType::SizeRequest);
         return static_cast<uint16_t>(headerContent[1]) << 8 | static_cast<uint16_t>(headerContent[2]);;
     }
Type()
ConnectionSerial::MessageType services::ConnectionSerial::MessageHeader::Type ()
Definition at line 226 of file ConnectionSerial.cpp.
     {
         return static_cast<MessageType>(headerContent[0]);
     }
Member Data Documentation
byteToSet
uint8_t services::ConnectionSerial::MessageHeader::byteToSet = 0 private
Definition at line 100 of file ConnectionSerial.hpp.
headerContent
std::array<uint8_t, HeaderSize> services::ConnectionSerial::MessageHeader::headerContent private
Definition at line 97 of file ConnectionSerial.hpp.
HeaderSize
const size_t services::ConnectionSerial::MessageHeader::HeaderSize = 3 static
Definition at line 91 of file ConnectionSerial.hpp.
Referenced by services::ConnectionSerial::StateConnected::ContentSizeToSend(), services::ConnectionSerial::StateConnectedSendingContent::SendContentWithSize(), services::ConnectionSerial::StateSendingUpdate::SendUpdate(), and services::ConnectionSerial::StateConnected::UpdatePossible().
isComplete
bool services::ConnectionSerial::MessageHeader::isComplete = false private
Definition at line 98 of file ConnectionSerial.hpp.
isFailed
bool services::ConnectionSerial::MessageHeader::isFailed = false private
Definition at line 99 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp