EMil: services::ConfigurationBlobImpl Class Reference
services::ConfigurationBlobImpl Class Reference
#include <ConfigurationStore.hpp>
Classes
struct Header
Public Types
template<std::size_t Size>
using WithStorage = infra::WithStorage< ConfigurationBlobImpl, std::array< uint8_t, Size+sizeof(Header)> >
Public Member Functions
ConfigurationBlobImpl (infra::ByteRange blob, hal::Flash &flash)
virtual infra::ByteRange CurrentBlob () override
virtual infra::ByteRange MaxBlob () override
virtual void Recover (const infra::Function< void(bool success)> &onRecovered) override
virtual void Write (uint32_t size, const infra::Function< void()> &onDone) override
virtual void Erase (const infra::Function< void()> &onDone) override
Private Member Functions
void RecoverCurrentSize ()
bool BlobIsValid () const
void PrepareBlobForWriting ()
Private Attributes
infra::ByteRange blob
hal::Flash & flash
uint32_t currentSize = 0
infra::AutoResetFunction< void(bool success)> onRecovered
Additional Inherited Members
Protected Member Functions inherited from services::ConfigurationBlob
ConfigurationBlob ()=default
ConfigurationBlob (const ConfigurationBlob &other)=delete
ConfigurationBlob & operator= (const ConfigurationBlob &other)=delete
~ConfigurationBlob ()=default
Detailed Description
Definition at line 30 of file ConfigurationStore.hpp.
Member Typedef Documentation
WithStorage
template<std::size_t Size> using services::ConfigurationBlobImpl::WithStorage = infra::WithStorage<ConfigurationBlobImpl, std::array<uint8_t, Size + sizeof(Header)> >
Definition at line 42 of file ConfigurationStore.hpp.
Constructor & Destructor Documentation
ConfigurationBlobImpl()
services::ConfigurationBlobImpl::ConfigurationBlobImpl (infra::ByteRange blob, hal::Flash & flash)
Definition at line 6 of file ConfigurationStore.cpp.
References blob, flash, infra::MemoryRange< T >::size(), and hal::Flash::TotalSize().
         : blob(blob)
         , flash(flash)
     {
         really_assert(blob.size() <= flash.TotalSize());
     }
Member Function Documentation
BlobIsValid()
bool services::ConfigurationBlobImpl::BlobIsValid () const private
Definition at line 58 of file ConfigurationStore.cpp.
References infra::MemoryRange< T >::begin(), blob, infra::Copy(), services::ConfigurationBlobImpl::Header::hash, infra::Head(), infra::MakeByteRange(), infra::MakeRange(), infra::MemoryRange< T >::size(), and services::ConfigurationBlobImpl::Header::size.
Referenced by Recover().
     {
         Header header;
         infra::Copy(infra::Head(blob, sizeof(header)), infra::MakeByteRange(header));
         if (header.size + sizeof(Header) > blob.size())
             return false;
         std::array<uint8_t, 32> messageHash;
         mbedtls_sha256(blob.begin() + sizeof(header.hash), std::min<std::size_t>(header.size + sizeof(header.size), blob.size() - sizeof(header.hash)), messageHash.data(), 0);  //TICS !INT#030
         return infra::Head(infra::MakeRange(messageHash), sizeof(header.hash)) == header.hash;
     }
CurrentBlob()
infra::ByteRange services::ConfigurationBlobImpl::CurrentBlob () override virtual
Implements services::ConfigurationBlob.
Definition at line 13 of file ConfigurationStore.cpp.
References blob, currentSize, infra::DiscardHead(), and infra::Head().
     {
         return infra::Head(infra::DiscardHead(blob, sizeof(Header)), currentSize);
     }
Erase()
void services::ConfigurationBlobImpl::Erase (const infra::Function< void()> & onDone) override virtual
Implements services::ConfigurationBlob.
Definition at line 38 of file ConfigurationStore.cpp.
References hal::Flash::EraseAll(), and flash.
     {
         flash.EraseAll(onDone);
     }
MaxBlob()
infra::ByteRange services::ConfigurationBlobImpl::MaxBlob () override virtual
Implements services::ConfigurationBlob.
Definition at line 18 of file ConfigurationStore.cpp.
References blob, and infra::DiscardHead().
     {
         return infra::DiscardHead(blob, sizeof(Header));
     }
PrepareBlobForWriting()
void services::ConfigurationBlobImpl::PrepareBlobForWriting () private
Definition at line 72 of file ConfigurationStore.cpp.
References infra::MemoryRange< T >::begin(), blob, infra::Copy(), currentSize, services::ConfigurationBlobImpl::Header::hash, infra::Head(), infra::MakeByteRange(), infra::MakeRange(), and services::ConfigurationBlobImpl::Header::size.
Referenced by Write().
     {
         Header header;
         header.size = currentSize;
         infra::Copy(infra::MakeByteRange(header), infra::Head(blob, sizeof(header)));
         std::array<uint8_t, 32> messageHash;
         mbedtls_sha256(blob.begin() + sizeof(header.hash), currentSize + sizeof(header.size), messageHash.data(), 0);  //TICS !INT#030
         infra::Copy(infra::Head(infra::MakeRange(messageHash), sizeof(header.hash)), infra::MakeRange(header.hash));
         infra::Copy(infra::MakeByteRange(header), infra::Head(blob, sizeof(header)));
     }
Recover()
void services::ConfigurationBlobImpl::Recover (const infra::Function< void(bool success)> & onRecovered) override virtual
Implements services::ConfigurationBlob.
Definition at line 23 of file ConfigurationStore.cpp.
References blob, BlobIsValid(), flash, onRecovered, hal::Flash::ReadBuffer(), and RecoverCurrentSize().
     {
         this->onRecovered = onRecovered;
         flash.ReadBuffer(blob, 0, [this]()
         {
             if (BlobIsValid())
             {
                 RecoverCurrentSize();
                 this->onRecovered(true);
             }
             else
                 this->onRecovered(false);
         });
     }
RecoverCurrentSize()
void services::ConfigurationBlobImpl::RecoverCurrentSize () private
Definition at line 50 of file ConfigurationStore.cpp.
References blob, infra::Copy(), currentSize, infra::Head(), infra::MakeByteRange(), and services::ConfigurationBlobImpl::Header::size.
Referenced by Recover().
     {
         Header header;
         infra::Copy(infra::Head(blob, sizeof(header)), infra::MakeByteRange(header));
         currentSize = header.size;
     }
Write()
void services::ConfigurationBlobImpl::Write (uint32_t size, const infra::Function< void()> & onDone) override virtual
Implements services::ConfigurationBlob.
Definition at line 43 of file ConfigurationStore.cpp.
References blob, currentSize, flash, PrepareBlobForWriting(), and hal::Flash::WriteBuffer().
     {
         currentSize = size;
         PrepareBlobForWriting();
         flash.WriteBuffer(blob, 0, onDone);
     }
Member Data Documentation
blob
infra::ByteRange services::ConfigurationBlobImpl::blob private
Definition at line 58 of file ConfigurationStore.hpp.
Referenced by BlobIsValid(), ConfigurationBlobImpl(), CurrentBlob(), MaxBlob(), PrepareBlobForWriting(), Recover(), RecoverCurrentSize(), and Write().
currentSize
uint32_t services::ConfigurationBlobImpl::currentSize = 0 private
Definition at line 60 of file ConfigurationStore.hpp.
Referenced by CurrentBlob(), PrepareBlobForWriting(), RecoverCurrentSize(), and Write().
flash
hal::Flash& services::ConfigurationBlobImpl::flash private
Definition at line 59 of file ConfigurationStore.hpp.
Referenced by ConfigurationBlobImpl(), Erase(), Recover(), and Write().
onRecovered
infra::AutoResetFunction<void(bool success)> services::ConfigurationBlobImpl::onRecovered private
Definition at line 61 of file ConfigurationStore.hpp.
Referenced by Recover().
The documentation for this class was generated from the following files:
ConfigurationStore.hpp
ConfigurationStore.cpp