EMil: services::TracingHttpClientImpl Class Reference
services::TracingHttpClientImpl Class Reference
#include <TracingHttpClientImpl.hpp>
Public Types
template<std::size_t MaxHeaderSize>
using WithMaxHeaderSize = infra::WithStorage< TracingHttpClientImpl, infra::BoundedString::WithStorage< MaxHeaderSize > >
Public Types inherited from services::HttpClientImpl
template<std::size_t MaxHeaderSize>
using WithMaxHeaderSize = infra::WithStorage< HttpClientImpl, infra::BoundedString::WithStorage< MaxHeaderSize > >
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Public Member Functions
TracingHttpClientImpl (infra::BoundedString &headerBuffer, infra::BoundedConstString hostname, Tracer &tracer)
virtual void WriteRequest (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
virtual void Connected () override
virtual void ClosingConnection () override
Public Member Functions inherited from services::HttpClientImpl
HttpClientImpl (infra::BoundedString &headerBuffer, infra::BoundedConstString hostname)
void AttachObserver (const infra::SharedPtr< HttpClientObserver > &observer)
virtual void Get (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Head (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Connect (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Options (infra::BoundedConstString requestTarget, HttpHeaders headers) override
virtual void Post (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers) override
virtual void Put (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers=noHeaders) override
virtual void Put (infra::BoundedConstString requestTarget, std::size_t contentSize, HttpHeaders headers=noHeaders) override
virtual void Patch (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers=noHeaders) override
virtual void Delete (infra::BoundedConstString requestTarget, infra::BoundedConstString content, HttpHeaders headers=noHeaders) override
virtual void AckReceived () override
virtual void Close () override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Member Functions inherited from infra::Subject< HttpClientObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Private Attributes
Tracer & tracer
Friends
class TracingHttpClientConnectorImpl
Additional Inherited Members
Protected Member Functions inherited from services::HttpClientImpl
virtual void StatusAvailable (HttpStatusCode code, infra::BoundedConstString statusLine)
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Protected Member Functions inherited from infra::Subject< HttpClientObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< HttpClientObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< HttpClientObserver, ObserverSubjectType > *observer)
Protected Attributes inherited from services::HttpClientImpl
infra::SharedPtr< HttpClientObserver > observer
infra::Optional< HttpRequestFormatter > request
infra::Optional< HttpResponseParser > response
Detailed Description
Definition at line 9 of file TracingHttpClientImpl.hpp.
Member Typedef Documentation
WithMaxHeaderSize
template<std::size_t MaxHeaderSize> using services::TracingHttpClientImpl::WithMaxHeaderSize = infra::WithStorage<TracingHttpClientImpl, infra::BoundedString::WithStorage<MaxHeaderSize> >
Definition at line 14 of file TracingHttpClientImpl.hpp.
Constructor & Destructor Documentation
TracingHttpClientImpl()
services::TracingHttpClientImpl::TracingHttpClientImpl (infra::BoundedString & headerBuffer, infra::BoundedConstString hostname, services::Tracer & tracer)
Definition at line 5 of file TracingHttpClientImpl.cpp.
         : HttpClientImpl(headerBuffer, hostname)
         , tracer(tracer)
     {}
Member Function Documentation
ClosingConnection()
void services::TracingHttpClientImpl::ClosingConnection () override virtual
Reimplemented from services::HttpClientImpl.
Definition at line 38 of file TracingHttpClientImpl.cpp.
References services::HttpClientImpl::ClosingConnection(), services::Tracer::Trace(), and tracer.
     {
         tracer.Trace() << "HttpClientImpl::ClosingConnection";
         HttpClientImpl::ClosingConnection();
     }
Connected()
void services::TracingHttpClientImpl::Connected () override virtual
Reimplemented from services::HttpClientImpl.
Definition at line 32 of file TracingHttpClientImpl.cpp.
References services::HttpClientImpl::Connected(), services::Tracer::Trace(), and tracer.
     {
         tracer.Trace() << "HttpClientImpl::Connected";
         HttpClientImpl::Connected();
     }
DataReceived()
void services::TracingHttpClientImpl::DataReceived () override virtual
Reimplemented from services::HttpClientImpl.
Definition at line 17 of file TracingHttpClientImpl.cpp.
References infra::ByteRangeAsString(), infra::InputStream::ContiguousRange(), services::HttpClientImpl::DataReceived(), infra::InputStream::Empty(), infra::endl, infra::SingleObserver< ConnectionObserver, Connection >::Subject(), services::Tracer::Trace(), and tracer.
     {
         tracer.Trace() << "HttpClientImpl::DataReceived; received response:" << infra::endl;
         auto reader = ConnectionObserver::Subject().ReceiveStream();
         infra::DataInputStream::WithErrorPolicy stream(*reader);
         while (!stream.Empty())
             tracer.Trace() << infra::ByteRangeAsString(stream.ContiguousRange());
         reader = nullptr;
         HttpClientImpl::DataReceived();
     }
WriteRequest()
void services::TracingHttpClientImpl::WriteRequest (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Reimplemented from services::HttpClientImpl.
Definition at line 10 of file TracingHttpClientImpl.cpp.
References infra::endl, services::HttpClientImpl::request, services::Tracer::Trace(), tracer, and services::HttpClientImpl::WriteRequest().
     {
         tracer.Trace() << "HttpClientImpl::WriteRequest; sending request:" << infra::endl;
         request->Write(tracer.Trace());
         HttpClientImpl::WriteRequest(std::move(writer));
     }
Friends And Related Function Documentation
TracingHttpClientConnectorImpl
friend class TracingHttpClientConnectorImpl friend
Definition at line 27 of file TracingHttpClientImpl.hpp.
Member Data Documentation
tracer
Tracer& services::TracingHttpClientImpl::tracer private
Definition at line 29 of file TracingHttpClientImpl.hpp.
Referenced by ClosingConnection(), Connected(), DataReceived(), and WriteRequest().
The documentation for this class was generated from the following files:
TracingHttpClientImpl.hpp
TracingHttpClientImpl.cpp