EMil: TestEventHandlerWithWeakPtr.cpp File Reference
TestEventHandlerWithWeakPtr.cpp File Reference
Classes
class EventDispatcherWithWeakPtrTest
Functions
TEST_F (EventDispatcherWithWeakPtrTest, TestSchedule)
TEST_F (EventDispatcherWithWeakPtrTest, TestScheduleTwice)
TEST_F (EventDispatcherWithWeakPtrTest, TestScheduleSharedPtr)
TEST_F (EventDispatcherWithWeakPtrTest, TestScheduleDestructedSharedPtr)
Function Documentation
TEST_F() [1/4]
TEST_F (EventDispatcherWithWeakPtrTest , TestSchedule)
Definition at line 13 of file TestEventHandlerWithWeakPtr.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), and infra::EventDispatcherWorker::Schedule().
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback());
     infra::EventDispatcher::Instance().Schedule([&callback, this]() { callback.callback(); });
     ExecuteAllActions();
 }
TEST_F() [2/4]
TEST_F (EventDispatcherWithWeakPtrTest , TestScheduleTwice)
Definition at line 22 of file TestEventHandlerWithWeakPtr.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), and infra::EventDispatcherWorker::Schedule().
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).Times(2);
     infra::EventDispatcher::Instance().Schedule([&callback, this]() { callback.callback(); });
     infra::EventDispatcher::Instance().Schedule([&callback, this]() { callback.callback(); });
     ExecuteAllActions();
 }
TEST_F() [3/4]
TEST_F (EventDispatcherWithWeakPtrTest , TestScheduleSharedPtr)
Definition at line 32 of file TestEventHandlerWithWeakPtr.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), and infra::EventDispatcherWithWeakPtrWorker::Schedule().
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback());
     infra::SharedObjectAllocatorFixedSize<int, void()>::WithStorage<2> allocator;
     infra::SharedPtr<int> object = allocator.Allocate();
     infra::EventDispatcherWithWeakPtr::Instance().Schedule([&callback, this](const infra::SharedPtr<int>& object) { callback.callback(); }, object);
     ExecuteAllActions();
 }
TEST_F() [4/4]
TEST_F (EventDispatcherWithWeakPtrTest , TestScheduleDestructedSharedPtr)
Definition at line 43 of file TestEventHandlerWithWeakPtr.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), and infra::EventDispatcherWithWeakPtrWorker::Schedule().
 {
     testing::StrictMock<infra::MockCallback<void()>> callback;
     infra::SharedObjectAllocatorFixedSize<int, void()>::WithStorage<2> allocator;
     infra::SharedPtr<int> object = allocator.Allocate();
     infra::EventDispatcherWithWeakPtr::Instance().Schedule([&callback, this](const infra::SharedPtr<int>& object) { callback.callback(); }, object);
     object = nullptr;
     ExecuteAllActions();
 }