EMil: infra::JsonSubObjectParser Class Reference
infra::JsonSubObjectParser Class Reference
#include <JsonStreamingParser.hpp>
Public Member Functions
JsonSubObjectParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char &subObjects, JsonObjectVisitor &visitor)
JsonSubObjectParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char &subObjects)
~JsonSubObjectParser ()
virtual void Feed (infra::MemoryRange< const char > &data) override
virtual JsonVisitor & Visitor () override
virtual void SetVisitor (JsonVisitor &visitor) override
void SemanticError ()
Public Member Functions inherited from infra::JsonSubParser
JsonSubParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char &subObjects)
JsonSubParser (const JsonSubParser &other)=delete
JsonSubParser & operator= (const JsonSubParser &other)=delete
virtual ~JsonSubParser ()
Private Types
enum State {
State::init, State::initialOpen, State::open, State::tagClosed,
State::valueExpected, State::closed, State::skipNestedObject, State::skipNestedArray,
State::parseError, State::semanticError
}
Private Attributes
JsonObjectVisitor * visitor
State state
uint32_t skipSubObjects = 0
bool * destructedIndication = nullptr
Additional Inherited Members
Protected Types inherited from infra::JsonSubParser
enum TokenState {
TokenState::open, TokenState::done, TokenState::stringOpen, TokenState::stringOpenAndEscaped,
TokenState::stringOverflowOpen, TokenState::unicodeValueOpen, TokenState::numberOpen, TokenState::numberFractionalOpen,
TokenState::numberExponentOpen, TokenState::identifierOpen
}
enum Token {
Token::error, Token::colon, Token::comma, Token::leftBrace,
Token::rightBrace, Token::leftBracket, Token::rightBracket, Token::string,
Token::stringOverflow, Token::number, Token::true_, Token::false_,
Token::null
}
Protected Member Functions inherited from infra::JsonSubParser
void FeedToken (infra::MemoryRange< const char > &data, bool saveValue)
void ReportParseError ()
void ReportSemanticError ()
infra::BoundedString CopyAndClear (infra::BoundedString &value) const
Protected Attributes inherited from infra::JsonSubParser
infra::BoundedString tagBuffer
infra::BoundedString valueBuffer
infra::BoundedVector< infra::PolymorphicVariant< JsonSubParser, JsonSubObjectParser, JsonSubArrayParser > > & subObjects
TokenState tokenState = TokenState::open
Token token = Token::error
int64_t tokenNumber
int8_t tokenSign
Detailed Description
Definition at line 151 of file JsonStreamingParser.hpp.
Member Enumeration Documentation
State
enum infra::JsonSubObjectParser::State strong private
Enumerator
init
initialOpen
open
tagClosed
valueExpected
closed
skipNestedObject
skipNestedArray
parseError
semanticError
Definition at line 166 of file JsonStreamingParser.hpp.
         {
             init,
             initialOpen,
             open,
             tagClosed,
             valueExpected,
             closed,
             skipNestedObject,
             skipNestedArray,
             parseError,
             semanticError
         };
Constructor & Destructor Documentation
JsonSubObjectParser() [1/2]
infra::JsonSubObjectParser::JsonSubObjectParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char & subObjects, JsonObjectVisitor & visitor)
Definition at line 336 of file JsonStreamingParser.cpp.
         : JsonSubParser(tagBuffer, valueBuffer, subObjects)
         , visitor(&visitor)
         , state(State::init)
     {}
JsonSubObjectParser() [2/2]
infra::JsonSubObjectParser::JsonSubObjectParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char & subObjects)
Definition at line 343 of file JsonStreamingParser.cpp.
References infra::BoundedStringBase< T >::clear().
         : JsonSubParser(tagBuffer, valueBuffer, subObjects)
         , state(State::initialOpen)
     {
         this->tagBuffer.clear();
     }
~JsonSubObjectParser()
infra::JsonSubObjectParser::~JsonSubObjectParser ()
Definition at line 351 of file JsonStreamingParser.cpp.
References destructedIndication.
     {
         if (destructedIndication != nullptr)
             *destructedIndication = true;
     }
Member Function Documentation
Feed()
void infra::JsonSubObjectParser::Feed (infra::MemoryRange< const char > & data) override virtual
Implements infra::JsonSubParser.
Definition at line 357 of file JsonStreamingParser.cpp.
References infra::BoundedStringBase< T >::assign(), infra::BoundedStringBase< T >::clear(), infra::JsonObjectVisitor::Close(), closed, infra::JsonSubParser::colon, infra::JsonSubParser::comma, infra::JsonSubParser::CopyAndClear(), infra::data, destructedIndication, infra::JsonSubParser::done, infra::JsonSubParser::false_, infra::JsonSubParser::FeedToken(), init, initialOpen, infra::JsonSubParser::leftBrace, infra::JsonSubParser::leftBracket, infra::BoundedStringBase< T >::max_size(), infra::JsonSubParser::null, infra::JsonSubParser::number, infra::JsonSubParser::open, open, parseError, infra::JsonSubParser::ReportParseError(), infra::JsonSubParser::ReportSemanticError(), infra::JsonSubParser::rightBrace, infra::JsonSubParser::rightBracket, semanticError, skipNestedArray, skipNestedObject, skipSubObjects, state, infra::JsonSubParser::string, infra::JsonObjectVisitor::StringOverflow(), infra::JsonSubParser::stringOverflow, infra::JsonSubParser::subObjects, infra::BoundedStringBase< T >::substr(), infra::JsonSubParser::tagBuffer, tagClosed, infra::JsonSubParser::token, infra::JsonSubParser::tokenNumber, infra::JsonSubParser::tokenSign, infra::JsonSubParser::tokenState, infra::JsonSubParser::true_, infra::JsonSubParser::valueBuffer, valueExpected, infra::JsonObjectVisitor::VisitArray(), infra::JsonObjectVisitor::VisitBoolean(), infra::JsonObjectVisitor::VisitNull(), infra::JsonObjectVisitor::VisitNumber(), infra::JsonObjectVisitor::VisitObject(), visitor, and infra::JsonObjectVisitor::VisitString().
     {
         bool destructed = false;
         destructedIndication = &destructed;
         infra::ExecuteOnDestruction::WithExtraSize<3 * sizeof(void*)> execute([this, &destructed, &data]()
         {
             if (!destructed)
                 destructedIndication = nullptr;
         });
         while (!destructed && !data.empty() && state != State::parseError && state != State::semanticError)
         {
             FeedToken(data, state != State::skipNestedObject && state != State::skipNestedArray);
             if (tokenState != TokenState::done)
                 break;
             if ((state == State::initialOpen || state == State::open) && (token == Token::string || token == Token::stringOverflow))
             {
                 state = State::tagClosed;
                 tagBuffer.assign(valueBuffer.substr(0, tagBuffer.max_size()));
             }
             else if (state == State::tagClosed && token == Token::colon)
                 state = State::valueExpected;
             else if (state == State::valueExpected && token == Token::string)
             {
                 state = State::closed;
                 visitor->VisitString(CopyAndClear(tagBuffer), valueBuffer);
             }
             else if (state == State::valueExpected && token == Token::stringOverflow)
             {
                 state = State::closed;
                 tagBuffer.clear();
                 visitor->StringOverflow();
             }
             else if (state == State::closed && token == Token::comma)
                 state = State::open;
             else if (state == State::init)
             {
                 if (token == Token::leftBrace)
                     state = State::initialOpen;
                 else
                     state = State::parseError;
             }
             else if (state == State::valueExpected && token == Token::leftBrace)
             {
                 tokenState = TokenState::open;
                 state = State::closed;
                 if (subObjects.full())
                     state = State::skipNestedObject;
                 else
                 {
                     subObjects.emplace_back(infra::InPlaceType<JsonSubObjectParser>(), tagBuffer, valueBuffer, reinterpret_cast<char&>(subObjects));
                     auto nestedVisitor = visitor->VisitObject(tagBuffer, static_cast<JsonSubObjectParser&>(*subObjects.back()));
                     if (destructed)
                         return;
                     if (nestedVisitor != nullptr)
                         subObjects.back()->SetVisitor(*nestedVisitor);
                     else
                     {
                         subObjects.pop_back();
                         state = State::skipNestedObject;
                     }
                 }
                 tagBuffer.clear();
                 return;
             }
             else if (state == State::valueExpected && token == Token::leftBracket)
             {
                 tokenState = TokenState::open;
                 state = State::closed;
                 if (subObjects.full())
                     state = State::skipNestedArray;
                 else
                 {
                     subObjects.emplace_back(infra::InPlaceType<JsonSubArrayParser>(), tagBuffer, valueBuffer, reinterpret_cast<char&>(subObjects));
                     auto nestedVisitor = visitor->VisitArray(tagBuffer, static_cast<JsonSubArrayParser&>(*subObjects.back()));
                     if (destructed)
                         return;
                     if (nestedVisitor != nullptr)
                         subObjects.back()->SetVisitor(*nestedVisitor);
                     else
                     {
                         subObjects.pop_back();
                         state = State::skipNestedArray;
                     }
                 }
                 tagBuffer.clear();
                 return;
             }
             else if (state == State::valueExpected && token == Token::number)
             {
                 state = State::closed;
                 visitor->VisitNumber(CopyAndClear(tagBuffer), tokenSign * tokenNumber);
             }
             else if (state == State::valueExpected && token == Token::false_)
             {
                 state = State::closed;
                 visitor->VisitBoolean(CopyAndClear(tagBuffer), false);
             }
             else if (state == State::valueExpected && token == Token::true_)
             {
                 state = State::closed;
                 visitor->VisitBoolean(CopyAndClear(tagBuffer), true);
             }
             else if (state == State::valueExpected && token == Token::null)
             {
                 state = State::closed;
                 visitor->VisitNull(CopyAndClear(tagBuffer));
             }
             else if ((state == State::initialOpen || state == State::closed) && token == Token::rightBrace)
             {
                 visitor->Close();
                 if (!destructed)
                     subObjects.pop_back();
                 return;
             }
             else if (state == State::skipNestedObject)
             {
                 if (token == Token::rightBrace)
                 {
                     if (skipSubObjects == 0)
                         state = State::closed;
                     else
                         --skipSubObjects;
                 }
                 else if (token == Token::leftBrace)
                     ++skipSubObjects;
             }
             else if (state == State::skipNestedArray)
             {
                 if (token == Token::rightBracket)
                 {
                     if (skipSubObjects == 0)
                         state = State::closed;
                     else
                         --skipSubObjects;
                 }
                 else if (token == Token::leftBracket)
                     ++skipSubObjects;
             }
             else
                 state = State::parseError;
             valueBuffer.clear();
             tokenState = TokenState::open;
         }
         if (state == State::parseError)
         {
             data.clear();
             ReportParseError();
         }
         if (state == State::semanticError)
         {
             data.clear();
             ReportSemanticError();
         }
     }
SemanticError()
void infra::JsonSubObjectParser::SemanticError ()
Definition at line 533 of file JsonStreamingParser.cpp.
References semanticError, and state.
     {
         state = State::semanticError;
     }
SetVisitor()
void infra::JsonSubObjectParser::SetVisitor (JsonVisitor & visitor) override virtual
Implements infra::JsonSubParser.
Definition at line 528 of file JsonStreamingParser.cpp.
References visitor.
     {
         this->visitor = static_cast<JsonObjectVisitor*>(&visitor);
     }
Visitor()
JsonVisitor & infra::JsonSubObjectParser::Visitor () override virtual
Implements infra::JsonSubParser.
Definition at line 523 of file JsonStreamingParser.cpp.
References visitor.
     {
         return *visitor;
     }
Member Data Documentation
destructedIndication
bool* infra::JsonSubObjectParser::destructedIndication = nullptr private
Definition at line 184 of file JsonStreamingParser.hpp.
Referenced by Feed(), and ~JsonSubObjectParser().
skipSubObjects
uint32_t infra::JsonSubObjectParser::skipSubObjects = 0 private
Definition at line 183 of file JsonStreamingParser.hpp.
Referenced by Feed().
state
State infra::JsonSubObjectParser::state private
Definition at line 182 of file JsonStreamingParser.hpp.
Referenced by Feed(), and SemanticError().
visitor
JsonObjectVisitor* infra::JsonSubObjectParser::visitor private
Definition at line 181 of file JsonStreamingParser.hpp.
Referenced by Feed(), SetVisitor(), and Visitor().
The documentation for this class was generated from the following files:
JsonStreamingParser.hpp
JsonStreamingParser.cpp