EMil: services::SynchronousFlashQuadSpi Class Reference
services::SynchronousFlashQuadSpi Class Reference
#include <SynchronousFlashQuadSpi.hpp>
Public Member Functions
SynchronousFlashQuadSpi (hal::SynchronousQuadSpi &quadSpi)
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex) override
Public Member Functions inherited from hal::SynchronousFlashHomogeneous
SynchronousFlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::SynchronousFlash
SynchronousFlash ()=default
SynchronousFlash (const SynchronousFlash &other)=delete
SynchronousFlash & operator= (const SynchronousFlash &other)=delete
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex)
void EraseAll ()
Static Public Attributes
static const uint32_t sizeSector = 65536
static const uint32_t sizeSubSector = 4096
static const uint32_t sizePage = 256
Private Member Functions
void WriteEnable ()
void PageProgram ()
void HoldWhileWriteInProgress ()
uint8_t ReadStatusRegister ()
Private Attributes
hal::SynchronousQuadSpi & quadSpi
infra::ConstByteRange buffer
uint32_t address = 0
Additional Inherited Members
Public Types inherited from hal::SynchronousFlash
using Range = std::pair< uint32_t, uint32_t >
Protected Member Functions inherited from hal::SynchronousFlashHomogeneous
~SynchronousFlashHomogeneous ()=default
Protected Member Functions inherited from hal::SynchronousFlash
~SynchronousFlash ()=default
Detailed Description
Definition at line 9 of file SynchronousFlashQuadSpi.hpp.
Constructor & Destructor Documentation
SynchronousFlashQuadSpi()
services::SynchronousFlashQuadSpi::SynchronousFlashQuadSpi (hal::SynchronousQuadSpi & quadSpi) explicit
Definition at line 5 of file SynchronousFlashQuadSpi.cpp.
References infra::MakeByteRange(), quadSpi, and hal::SynchronousQuadSpi::SendData().
         : hal::SynchronousFlashHomogeneous(4096, 4096)
         , quadSpi(quadSpi)
     {
         // Switch to single line speed
         const uint8_t commandWriteEnable = 0x06;
         static const hal::SynchronousQuadSpi::Header writeEnableHeader{ commandWriteEnable, std::numeric_limits<uint32_t>::max(), 0 };
         quadSpi.SendData(writeEnableHeader, infra::ByteRange());
         const uint8_t commandWriteEnhancedVolatileRegister = 0x61;
         static const hal::SynchronousQuadSpi::Header writeVolatileRegisterHeader{ commandWriteEnhancedVolatileRegister, std::numeric_limits<uint32_t>::max(), 0 };
         const uint8_t volatileRegisterForQuadSpeed = 0x5f;
         quadSpi.SendData(writeVolatileRegisterHeader, infra::MakeByteRange(volatileRegisterForQuadSpeed));
     }
Member Function Documentation
EraseSectors()
void services::SynchronousFlashQuadSpi::EraseSectors (uint32_t beginIndex, uint32_t endIndex) override virtual
Implements hal::SynchronousFlash.
Definition at line 41 of file SynchronousFlashQuadSpi.cpp.
     {}
HoldWhileWriteInProgress()
void services::SynchronousFlashQuadSpi::HoldWhileWriteInProgress () private
Definition at line 61 of file SynchronousFlashQuadSpi.cpp.
References ReadStatusRegister().
Referenced by WriteBuffer().
     {
         while ((ReadStatusRegister() & 1) == 1)
         {}
     }
PageProgram()
void services::SynchronousFlashQuadSpi::PageProgram () private
Definition at line 51 of file SynchronousFlashQuadSpi.cpp.
References address, hal::SynchronousFlash::AddressOffsetInSector(), buffer, infra::Head(), infra::MemoryRange< T >::pop_front(), quadSpi, hal::SynchronousQuadSpi::SendDataQuad(), infra::MemoryRange< T >::size(), and sizePage.
Referenced by WriteBuffer().
     {
         infra::ConstByteRange currentBuffer = infra::Head(buffer, sizePage - AddressOffsetInSector(address) % sizePage);
         buffer.pop_front(currentBuffer.size());
         const uint8_t commandPageProgram = 0x32;
         hal::SynchronousQuadSpi::Header pageProgramHeader{ commandPageProgram, address, 0 };
         quadSpi.SendDataQuad(pageProgramHeader, currentBuffer);
     }
ReadBuffer()
void services::SynchronousFlashQuadSpi::ReadBuffer (infra::ByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 33 of file SynchronousFlashQuadSpi.cpp.
References address, buffer, quadSpi, and hal::SynchronousQuadSpi::ReceiveDataQuad().
     {
         const uint8_t commandReadData = 0x0B;
         const hal::SynchronousQuadSpi::Header header{ commandReadData, address, 10 };
         quadSpi.ReceiveDataQuad(header, buffer);
     }
ReadStatusRegister()
uint8_t services::SynchronousFlashQuadSpi::ReadStatusRegister () private
Definition at line 67 of file SynchronousFlashQuadSpi.cpp.
References infra::MakeByteRange(), quadSpi, and hal::SynchronousQuadSpi::ReceiveDataQuad().
Referenced by HoldWhileWriteInProgress().
     {
         uint8_t result;
         const uint8_t commandReadStatusRegister = 0x05;
         static const hal::SynchronousQuadSpi::Header readStatusHeader{ commandReadStatusRegister, std::numeric_limits<uint32_t>::max(), 0 };
         quadSpi.ReceiveDataQuad(readStatusHeader, infra::MakeByteRange(result));
         return result;
     }
WriteBuffer()
void services::SynchronousFlashQuadSpi::WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 20 of file SynchronousFlashQuadSpi.cpp.
References address, buffer, infra::MemoryRange< T >::empty(), HoldWhileWriteInProgress(), PageProgram(), and WriteEnable().
     {
         buffer = buffer_;
         address = address_;
         while (!buffer.empty())
         {
             WriteEnable();
             PageProgram();
             HoldWhileWriteInProgress();
         }
     }
WriteEnable()
void services::SynchronousFlashQuadSpi::WriteEnable () private
Definition at line 44 of file SynchronousFlashQuadSpi.cpp.
References quadSpi, and hal::SynchronousQuadSpi::SendDataQuad().
Referenced by WriteBuffer().
     {
         const uint8_t commandWriteEnable = 0x06;
         static const hal::SynchronousQuadSpi::Header writeEnableHeader{ commandWriteEnable, std::numeric_limits<uint32_t>::max(), 0 };
         quadSpi.SendDataQuad(writeEnableHeader, infra::ByteRange());
     }
Member Data Documentation
address
uint32_t services::SynchronousFlashQuadSpi::address = 0 private
Definition at line 32 of file SynchronousFlashQuadSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), and WriteBuffer().
buffer
infra::ConstByteRange services::SynchronousFlashQuadSpi::buffer private
Definition at line 31 of file SynchronousFlashQuadSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), and WriteBuffer().
quadSpi
hal::SynchronousQuadSpi& services::SynchronousFlashQuadSpi::quadSpi private
Definition at line 30 of file SynchronousFlashQuadSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), ReadStatusRegister(), SynchronousFlashQuadSpi(), and WriteEnable().
sizePage
const uint32_t services::SynchronousFlashQuadSpi::sizePage = 256 static
Definition at line 15 of file SynchronousFlashQuadSpi.hpp.
Referenced by PageProgram().
sizeSector
const uint32_t services::SynchronousFlashQuadSpi::sizeSector = 65536 static
Definition at line 13 of file SynchronousFlashQuadSpi.hpp.
sizeSubSector
const uint32_t services::SynchronousFlashQuadSpi::sizeSubSector = 4096 static
Definition at line 14 of file SynchronousFlashQuadSpi.hpp.
The documentation for this class was generated from the following files:
SynchronousFlashQuadSpi.hpp
SynchronousFlashQuadSpi.cpp