EMil: hal::SynchronousSpi Class Reference
hal::SynchronousSpi Class Reference abstract
#include <SynchronousSpi.hpp>
Public Types
enum Action { continueSession, stop }
Public Member Functions
SynchronousSpi ()=default
SynchronousSpi (const SynchronousSpi &other)=delete
SynchronousSpi & operator= (const SynchronousSpi &other)=delete
void SendData (infra::ConstByteRange data, Action nextAction)
void ReceiveData (infra::ByteRange data, Action nextAction)
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, Action nextAction)=0
Protected Member Functions
~SynchronousSpi ()=default
Detailed Description
Definition at line 9 of file SynchronousSpi.hpp.
Member Enumeration Documentation
Action
enum hal::SynchronousSpi::Action
Enumerator
continueSession
stop
Definition at line 20 of file SynchronousSpi.hpp.
         {
             continueSession,
             stop
         };
Constructor & Destructor Documentation
SynchronousSpi() [1/2]
hal::SynchronousSpi::SynchronousSpi () default
SynchronousSpi() [2/2]
hal::SynchronousSpi::SynchronousSpi (const SynchronousSpi & other) delete
~SynchronousSpi()
hal::SynchronousSpi::~SynchronousSpi () protected default
Member Function Documentation
operator=()
SynchronousSpi& hal::SynchronousSpi::operator= (const SynchronousSpi & other) delete
ReceiveData()
void hal::SynchronousSpi::ReceiveData (infra::ByteRange data, Action nextAction)
Definition at line 10 of file SynchronousSpi.cpp.
References infra::data, and SendAndReceive().
Referenced by services::SynchronousFlashSpi::ReadBuffer(), and services::SynchronousFlashSpi::ReadStatusRegister().
     {
         SendAndReceive(infra::ConstByteRange(), data, nextAction);
     }
SendAndReceive()
virtual void hal::SynchronousSpi::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, Action nextAction) pure virtual
Implemented in services::SynchronousSpiMasterWithChipSelect.
Referenced by ReceiveData(), services::SynchronousSpiMasterWithChipSelect::SendAndReceive(), and SendData().
SendData()
void hal::SynchronousSpi::SendData (infra::ConstByteRange data, Action nextAction)
Definition at line 5 of file SynchronousSpi.cpp.
References infra::data, and SendAndReceive().
Referenced by services::SynchronousFlashSpi::PageProgram(), services::SynchronousFlashSpi::ReadBuffer(), services::SynchronousFlashSpi::ReadStatusRegister(), services::SynchronousFlashSpi::SendEraseBulk(), services::SynchronousFlashSpi::SendEraseSector(), services::SynchronousFlashSpi::SendEraseSubSector(), and services::SynchronousFlashSpi::WriteEnable().
     {
         SendAndReceive(data, infra::ByteRange(), nextAction);
     }
The documentation for this class was generated from the following files:
SynchronousSpi.hpp
SynchronousSpi.cpp