EMil: services::DnsResolver::HostnameParts Class Reference
services::DnsResolver::HostnameParts Class Reference abstract
Public Member Functions
virtual infra::BoundedConstString Current () const =0
virtual void ConsumeCurrent ()=0
virtual bool Empty () const =0
Protected Member Functions
HostnameParts ()=default
HostnameParts (const HostnameParts &other)=delete
HostnameParts & operator= (const HostnameParts &other)=delete
~HostnameParts ()=default
Detailed Description
Definition at line 88 of file DnsResolver.hpp.
Constructor & Destructor Documentation
HostnameParts() [1/2]
services::DnsResolver::HostnameParts::HostnameParts () protected default
HostnameParts() [2/2]
services::DnsResolver::HostnameParts::HostnameParts (const HostnameParts & other) protected delete
~HostnameParts()
services::DnsResolver::HostnameParts::~HostnameParts () protected default
Member Function Documentation
ConsumeCurrent()
virtual void services::DnsResolver::HostnameParts::ConsumeCurrent () pure virtual
Implemented in services::DnsResolver::HostnamePartsStream, and services::DnsResolver::HostnamePartsString.
Referenced by services::DnsResolver::ReplyParser::ReadAndMatchHostnameWithoutReference().
Current()
virtual infra::BoundedConstString services::DnsResolver::HostnameParts::Current () const pure virtual
Implemented in services::DnsResolver::HostnamePartsStream, and services::DnsResolver::HostnamePartsString.
Referenced by services::DnsResolver::ReplyParser::ReadAndMatchHostnamePart().
Empty()
virtual bool services::DnsResolver::HostnameParts::Empty () const pure virtual
Implemented in services::DnsResolver::HostnamePartsStream, and services::DnsResolver::HostnamePartsString.
Referenced by services::DnsResolver::ReplyParser::ReadAndMatchHostnamePart(), and services::DnsResolver::ReplyParser::ReadAndMatchHostnameWithoutReference().
operator=()
HostnameParts& services::DnsResolver::HostnameParts::operator= (const HostnameParts & other) protected delete
The documentation for this class was generated from the following file:
DnsResolver.hpp