EMil: services::SynchronousFlashSpi Class Reference
services::SynchronousFlashSpi Class Reference
#include <SynchronousFlashSpi.hpp>
Classes
struct InstructionAndAddress
Public Types
using Config = SynchronousFlashSpiConfig
Public Types inherited from hal::SynchronousFlash
using Range = std::pair< uint32_t, uint32_t >
Public Member Functions
SynchronousFlashSpi (hal::SynchronousSpi &spi, const Config &config=Config())
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex) override
Public Member Functions inherited from hal::SynchronousFlashHomogeneous
SynchronousFlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::SynchronousFlash
SynchronousFlash ()=default
SynchronousFlash (const SynchronousFlash &other)=delete
SynchronousFlash & operator= (const SynchronousFlash &other)=delete
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex)
void EraseAll ()
Static Public Attributes
static const uint8_t commandPageProgram = 0x02
static const uint8_t commandReadData = 0x03
static const uint8_t commandReadStatusRegister = 0x05
static const uint8_t commandWriteEnable = 0x06
static const uint8_t commandEraseSubSector = 0x20
static const uint8_t commandEraseSector = 0xd8
static const uint8_t commandEraseBulk = 0xc7
static const uint32_t sizeSector = 65536
static const uint32_t sizeSubSector = 4096
static const uint32_t sizePage = 256
static const uint8_t statusFlagWriteInProgress = 1
Private Member Functions
std::array< uint8_t, 3 > ConvertAddress (uint32_t address) const
void WriteEnable ()
void PageProgram ()
void EraseSomeSectors (uint32_t endIndex)
void SendEraseSubSector (uint32_t subSectorIndex)
void SendEraseSector (uint32_t subSectorIndex)
void SendEraseBulk ()
void HoldWhileWriteInProgress ()
uint8_t ReadStatusRegister ()
Private Attributes
hal::SynchronousSpi & spi
Config config
infra::ConstByteRange buffer
uint32_t address = 0
uint32_t sectorIndex = 0
struct services::SynchronousFlashSpi::InstructionAndAddress instructionAndAddress
Additional Inherited Members
Protected Member Functions inherited from hal::SynchronousFlashHomogeneous
~SynchronousFlashHomogeneous ()=default
Protected Member Functions inherited from hal::SynchronousFlash
~SynchronousFlash ()=default
Detailed Description
Definition at line 14 of file SynchronousFlashSpi.hpp.
Member Typedef Documentation
Config
using services::SynchronousFlashSpi::Config = SynchronousFlashSpiConfig
Definition at line 18 of file SynchronousFlashSpi.hpp.
Constructor & Destructor Documentation
SynchronousFlashSpi()
services::SynchronousFlashSpi::SynchronousFlashSpi (hal::SynchronousSpi & spi, const Config & config = Config())
Definition at line 13 of file SynchronousFlashSpi.cpp.
         : SynchronousFlashHomogeneous(config.numberOfSubSectors, sizeSubSector)
         , spi(spi)
         , config(config)
     {}
Member Function Documentation
ConvertAddress()
std::array< uint8_t, 3 > services::SynchronousFlashSpi::ConvertAddress (uint32_t address) const private
Definition at line 51 of file SynchronousFlashSpi.cpp.
References address.
Referenced by PageProgram(), ReadBuffer(), SendEraseSector(), and SendEraseSubSector().
     {
         uint32_t linearAddress = address;
         std::array<uint8_t, 3> result;
         result[0] = static_cast<uint8_t>(linearAddress >> 16);
         result[1] = static_cast<uint8_t>(linearAddress >> 8);
         result[2] = static_cast<uint8_t>(linearAddress);
         return result;
     }
EraseSectors()
void services::SynchronousFlashSpi::EraseSectors (uint32_t beginIndex, uint32_t endIndex) override virtual
Implements hal::SynchronousFlash.
Definition at line 40 of file SynchronousFlashSpi.cpp.
References EraseSomeSectors(), HoldWhileWriteInProgress(), sectorIndex, and WriteEnable().
     {
         sectorIndex = beginIndex;
         while (sectorIndex != endIndex)
         {
             WriteEnable();
             EraseSomeSectors(endIndex);
             HoldWhileWriteInProgress();
         }
     }
EraseSomeSectors()
void services::SynchronousFlashSpi::EraseSomeSectors (uint32_t endIndex) private
Definition at line 80 of file SynchronousFlashSpi.cpp.
References hal::SynchronousFlashHomogeneous::NumberOfSectors(), sectorIndex, SendEraseBulk(), SendEraseSector(), SendEraseSubSector(), sizeSector, and sizeSubSector.
Referenced by EraseSectors().
     {
         if (sectorIndex == 0 && endIndex == NumberOfSectors())
         {
             SendEraseBulk();
             sectorIndex += NumberOfSectors();
         }
         else if (sectorIndex % (sizeSector / sizeSubSector) == 0 && sectorIndex + sizeSector / sizeSubSector <= endIndex)
         {
             SendEraseSector(sectorIndex);
             sectorIndex += sizeSector / sizeSubSector;
         }
         else
         {
             SendEraseSubSector(sectorIndex);
             ++sectorIndex;
         }
     }
HoldWhileWriteInProgress()
void services::SynchronousFlashSpi::HoldWhileWriteInProgress () private
Definition at line 122 of file SynchronousFlashSpi.cpp.
References ReadStatusRegister().
Referenced by EraseSectors(), and WriteBuffer().
     {
         while ((ReadStatusRegister() & 1) == 1)
         {}
     }
PageProgram()
void services::SynchronousFlashSpi::PageProgram () private
Definition at line 67 of file SynchronousFlashSpi.cpp.
References address, services::SynchronousFlashSpi::InstructionAndAddress::address, hal::SynchronousFlash::AddressOffsetInSector(), buffer, commandPageProgram, hal::SynchronousSpi::continueSession, ConvertAddress(), infra::Head(), services::SynchronousFlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), infra::MemoryRange< T >::pop_front(), hal::SynchronousSpi::SendData(), infra::MemoryRange< T >::size(), sizePage, spi, and hal::SynchronousSpi::stop.
Referenced by WriteBuffer().
     {
         infra::ConstByteRange currentBuffer = infra::Head(buffer, sizePage - AddressOffsetInSector(address) % sizePage);
         buffer.pop_front(currentBuffer.size());
         instructionAndAddress.instruction = commandPageProgram;
         instructionAndAddress.address = ConvertAddress(address);
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SynchronousSpi::continueSession);
         spi.SendData(currentBuffer, hal::SynchronousSpi::stop);
         address += currentBuffer.size();
     }
ReadBuffer()
void services::SynchronousFlashSpi::ReadBuffer (infra::ByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 32 of file SynchronousFlashSpi.cpp.
References address, services::SynchronousFlashSpi::InstructionAndAddress::address, buffer, commandReadData, hal::SynchronousSpi::continueSession, ConvertAddress(), services::SynchronousFlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SynchronousSpi::ReceiveData(), hal::SynchronousSpi::SendData(), spi, and hal::SynchronousSpi::stop.
     {
         instructionAndAddress.instruction = commandReadData;
         instructionAndAddress.address = ConvertAddress(address);
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SynchronousSpi::continueSession);
         spi.ReceiveData(buffer, hal::SynchronousSpi::stop);
     }
ReadStatusRegister()
uint8_t services::SynchronousFlashSpi::ReadStatusRegister () private
Definition at line 128 of file SynchronousFlashSpi.cpp.
References commandReadStatusRegister, hal::SynchronousSpi::continueSession, infra::MakeByteRange(), hal::SynchronousSpi::ReceiveData(), hal::SynchronousSpi::SendData(), spi, and hal::SynchronousSpi::stop.
Referenced by HoldWhileWriteInProgress().
     {
         static const uint8_t instruction = commandReadStatusRegister;
         uint8_t statusRegister = 0;
         spi.SendData(infra::MakeByteRange(instruction), hal::SynchronousSpi::continueSession);
         spi.ReceiveData(infra::MakeByteRange(statusRegister), hal::SynchronousSpi::stop);
         return statusRegister;
     }
SendEraseBulk()
void services::SynchronousFlashSpi::SendEraseBulk () private
Definition at line 115 of file SynchronousFlashSpi.cpp.
References commandEraseBulk, services::SynchronousFlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SynchronousSpi::SendData(), spi, and hal::SynchronousSpi::stop.
Referenced by EraseSomeSectors().
     {
         instructionAndAddress.instruction = commandEraseBulk;
         spi.SendData(infra::MakeByteRange(instructionAndAddress.instruction), hal::SynchronousSpi::stop);
     }
SendEraseSector()
void services::SynchronousFlashSpi::SendEraseSector (uint32_t subSectorIndex) private
Definition at line 107 of file SynchronousFlashSpi.cpp.
References services::SynchronousFlashSpi::InstructionAndAddress::address, hal::SynchronousFlashHomogeneous::AddressOfSector(), commandEraseSector, ConvertAddress(), services::SynchronousFlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SynchronousSpi::SendData(), spi, and hal::SynchronousSpi::stop.
Referenced by EraseSomeSectors().
     {
         instructionAndAddress.instruction = commandEraseSector;
         instructionAndAddress.address = ConvertAddress(AddressOfSector(subSectorIndex));
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SynchronousSpi::stop);
     }
SendEraseSubSector()
void services::SynchronousFlashSpi::SendEraseSubSector (uint32_t subSectorIndex) private
Definition at line 99 of file SynchronousFlashSpi.cpp.
References services::SynchronousFlashSpi::InstructionAndAddress::address, hal::SynchronousFlashHomogeneous::AddressOfSector(), commandEraseSubSector, ConvertAddress(), services::SynchronousFlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SynchronousSpi::SendData(), spi, and hal::SynchronousSpi::stop.
Referenced by EraseSomeSectors().
     {
         instructionAndAddress.instruction = commandEraseSubSector;
         instructionAndAddress.address = ConvertAddress(AddressOfSector(subSectorIndex));
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SynchronousSpi::stop);
     }
WriteBuffer()
void services::SynchronousFlashSpi::WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 19 of file SynchronousFlashSpi.cpp.
References address, buffer, infra::MemoryRange< T >::empty(), HoldWhileWriteInProgress(), PageProgram(), and WriteEnable().
     {
         buffer = buffer_;
         address = address_;
         while (!buffer.empty())
         {
             WriteEnable();
             PageProgram();
             HoldWhileWriteInProgress();
         }
     }
WriteEnable()
void services::SynchronousFlashSpi::WriteEnable () private
Definition at line 61 of file SynchronousFlashSpi.cpp.
References commandWriteEnable, infra::MakeByteRange(), hal::SynchronousSpi::SendData(), spi, and hal::SynchronousSpi::stop.
Referenced by EraseSectors(), and WriteBuffer().
     {
         static const uint8_t command = commandWriteEnable;
         spi.SendData(infra::MakeByteRange(command), hal::SynchronousSpi::stop);
     }
Member Data Documentation
address
uint32_t services::SynchronousFlashSpi::address = 0 private
Definition at line 57 of file SynchronousFlashSpi.hpp.
Referenced by ConvertAddress(), PageProgram(), ReadBuffer(), and WriteBuffer().
buffer
infra::ConstByteRange services::SynchronousFlashSpi::buffer private
Definition at line 56 of file SynchronousFlashSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), and WriteBuffer().
commandEraseBulk
const uint8_t services::SynchronousFlashSpi::commandEraseBulk = 0xc7 static
Definition at line 26 of file SynchronousFlashSpi.hpp.
Referenced by SendEraseBulk().
commandEraseSector
const uint8_t services::SynchronousFlashSpi::commandEraseSector = 0xd8 static
Definition at line 25 of file SynchronousFlashSpi.hpp.
Referenced by SendEraseSector().
commandEraseSubSector
const uint8_t services::SynchronousFlashSpi::commandEraseSubSector = 0x20 static
Definition at line 24 of file SynchronousFlashSpi.hpp.
Referenced by SendEraseSubSector().
commandPageProgram
const uint8_t services::SynchronousFlashSpi::commandPageProgram = 0x02 static
Definition at line 20 of file SynchronousFlashSpi.hpp.
Referenced by PageProgram().
commandReadData
const uint8_t services::SynchronousFlashSpi::commandReadData = 0x03 static
Definition at line 21 of file SynchronousFlashSpi.hpp.
Referenced by ReadBuffer().
commandReadStatusRegister
const uint8_t services::SynchronousFlashSpi::commandReadStatusRegister = 0x05 static
Definition at line 22 of file SynchronousFlashSpi.hpp.
Referenced by ReadStatusRegister().
commandWriteEnable
const uint8_t services::SynchronousFlashSpi::commandWriteEnable = 0x06 static
Definition at line 23 of file SynchronousFlashSpi.hpp.
Referenced by WriteEnable().
config
Config services::SynchronousFlashSpi::config private
Definition at line 55 of file SynchronousFlashSpi.hpp.
instructionAndAddress
struct services::SynchronousFlashSpi::InstructionAndAddress services::SynchronousFlashSpi::instructionAndAddress private
Referenced by PageProgram(), ReadBuffer(), SendEraseBulk(), SendEraseSector(), and SendEraseSubSector().
sectorIndex
uint32_t services::SynchronousFlashSpi::sectorIndex = 0 private
Definition at line 58 of file SynchronousFlashSpi.hpp.
Referenced by EraseSectors(), and EraseSomeSectors().
sizePage
const uint32_t services::SynchronousFlashSpi::sizePage = 256 static
Definition at line 30 of file SynchronousFlashSpi.hpp.
Referenced by PageProgram().
sizeSector
const uint32_t services::SynchronousFlashSpi::sizeSector = 65536 static
Definition at line 28 of file SynchronousFlashSpi.hpp.
Referenced by EraseSomeSectors().
sizeSubSector
const uint32_t services::SynchronousFlashSpi::sizeSubSector = 4096 static
Definition at line 29 of file SynchronousFlashSpi.hpp.
Referenced by EraseSomeSectors().
spi
hal::SynchronousSpi& services::SynchronousFlashSpi::spi private
Definition at line 54 of file SynchronousFlashSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), ReadStatusRegister(), SendEraseBulk(), SendEraseSector(), SendEraseSubSector(), and WriteEnable().
statusFlagWriteInProgress
const uint8_t services::SynchronousFlashSpi::statusFlagWriteInProgress = 1 static
Definition at line 32 of file SynchronousFlashSpi.hpp.
The documentation for this class was generated from the following files:
SynchronousFlashSpi.hpp
SynchronousFlashSpi.cpp