EMil: services::ConnectionWin Class Reference
services::ConnectionWin Class Reference
#include <ConnectionWin.hpp>
Classes
class StreamReaderWin
class StreamWriterWin
Public Member Functions
ConnectionWin (EventDispatcherWithNetwork &network, SOCKET socket)
~ConnectionWin ()
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
IPv4Address Ipv4Address () const
void SetObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
void Receive ()
void Send ()
void TrySend ()
void UpdateEventFlags ()
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionWin >
SharedPtr< ConnectionWin > SharedFromThis ()
SharedPtr< const ConnectionWin > SharedFromThis () const
WeakPtr< ConnectionWin > WeakFromThis ()
WeakPtr< const ConnectionWin > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionWin > sharedPtr)
Private Member Functions
void TryAllocateSendStream ()
Private Attributes
EventDispatcherWithNetwork & network
SOCKET socket
WSAEVENT event = WSACreateEvent()
infra::BoundedDeque< uint8_t >::WithMaxSize< 2048 > receiveBuffer
infra::BoundedDeque< uint8_t >::WithMaxSize< 2048 > sendBuffer
infra::SharedOptional< StreamWriterWin > streamWriter
std::size_t requestedSendSize = 0
infra::SharedOptional< StreamReaderWin > streamReader
bool trySend = false
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectionWin >
using EnableSharedFromThisType = ConnectionWin
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionWin >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 18 of file ConnectionWin.hpp.
Constructor & Destructor Documentation
ConnectionWin()
services::ConnectionWin::ConnectionWin (EventDispatcherWithNetwork & network, SOCKET socket)
Definition at line 6 of file ConnectionWin.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), Receive(), infra::EventDispatcherWorker::Schedule(), and UpdateEventFlags().
         : network(network)
         , socket(socket)
     {
         UpdateEventFlags();
         infra::EventDispatcher::Instance().Schedule([this]() { Receive(); });
     }
~ConnectionWin()
services::ConnectionWin::~ConnectionWin ()
Definition at line 15 of file ConnectionWin.cpp.
References event, and socket.
     {
         if (socket != 0)
         {
             BOOL result = WSACloseEvent(event);
             assert(result == TRUE);
             result = closesocket(socket);
             if (result == SOCKET_ERROR)
             {
                 DWORD error = GetLastError();
                 std::abort();
             }
         }
     }
Member Function Documentation
AbortAndDestroy()
void services::ConnectionWin::AbortAndDestroy () override virtual
Implements services::Connection.
Definition at line 58 of file ConnectionWin.cpp.
References services::Connection::ResetOwnership(), and socket.
Referenced by CloseAndDestroy().
     {
         int result = closesocket(socket);
         assert(result != SOCKET_ERROR);
         socket = 0;
         ResetOwnership();
     }
AckReceived()
void services::ConnectionWin::AckReceived () override virtual
Implements services::Connection.
Definition at line 48 of file ConnectionWin.cpp.
References streamReader.
     {
         streamReader->ConsumeRead();
     }
CloseAndDestroy()
void services::ConnectionWin::CloseAndDestroy () override virtual
Implements services::Connection.
Definition at line 53 of file ConnectionWin.cpp.
References AbortAndDestroy().
     {
         AbortAndDestroy();
     }
Ipv4Address()
IPv4Address services::ConnectionWin::Ipv4Address () const
Definition at line 66 of file ConnectionWin.cpp.
References socket.
     {
         sockaddr_in address{};
         int addressLength = sizeof(address);
         getpeername(socket, reinterpret_cast<SOCKADDR*>(&address), &addressLength);
         return IPv4Address{
             static_cast<uint8_t>(address.sin_addr.s_addr >> 24),
             static_cast<uint8_t>(address.sin_addr.s_addr >> 16),
             static_cast<uint8_t>(address.sin_addr.s_addr >> 8),
             static_cast<uint8_t>(address.sin_addr.s_addr)
         };
     }
MaxSendStreamSize()
std::size_t services::ConnectionWin::MaxSendStreamSize () const override virtual
Implements services::Connection.
Definition at line 38 of file ConnectionWin.cpp.
References infra::BoundedDeque< T >::max_size(), and sendBuffer.
Referenced by RequestSendStream().
     {
         return sendBuffer.max_size();
     }
Receive()
void services::ConnectionWin::Receive ()
Definition at line 88 of file ConnectionWin.cpp.
References infra::BoundedDeque< T >::end(), infra::BoundedDeque< T >::full(), infra::BoundedDeque< T >::insert(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::BoundedDeque< T >::max_size(), receiveBuffer, services::Connection::ResetOwnership(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), infra::EnableSharedFromThis< ConnectionWin >::SharedFromThis(), infra::BoundedDeque< T >::size(), and socket.
Referenced by ConnectionWin().
     {
         while (!receiveBuffer.full())
         {
             std::array<uint8_t, 2048> buffer;
             int received = recv(socket, reinterpret_cast<char*>(buffer.data()), receiveBuffer.max_size() - receiveBuffer.size(), 0);
             if (received == SOCKET_ERROR)
             {
                 if (WSAGetLastError() != WSAEWOULDBLOCK)
                     ResetOwnership();
                 return;
             }
             else if (received != 0)
             {
                 receiveBuffer.insert(receiveBuffer.end(), buffer.data(), buffer.data() + received);
                 infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionWin>& object)
                 {
                     object->GetObserver().DataReceived();
                 }, SharedFromThis());
             }
             else
             {
                 ResetOwnership();
                 return;
             }
         }
     }
ReceiveStream()
infra::SharedPtr< infra::StreamReaderWithRewinding > services::ConnectionWin::ReceiveStream () override virtual
Implements services::Connection.
Definition at line 43 of file ConnectionWin.cpp.
References streamReader.
     {
         return streamReader.Emplace(*this);
     }
RequestSendStream()
void services::ConnectionWin::RequestSendStream (std::size_t sendSize) override virtual
Implements services::Connection.
Definition at line 30 of file ConnectionWin.cpp.
References MaxSendStreamSize(), requestedSendSize, and TryAllocateSendStream().
     {
         assert(requestedSendSize == 0);
         assert(sendSize != 0 && sendSize <= MaxSendStreamSize());
         requestedSendSize = sendSize;
         TryAllocateSendStream();
     }
Send()
void services::ConnectionWin::Send ()
Definition at line 117 of file ConnectionWin.cpp.
References infra::detail::begin(), infra::BoundedDeque< T >::begin(), infra::BoundedDeque< T >::contiguous_range(), infra::BoundedDeque< T >::empty(), infra::BoundedDeque< T >::erase(), requestedSendSize, services::Connection::ResetOwnership(), sendBuffer, socket, TryAllocateSendStream(), and UpdateEventFlags().
Referenced by TrySend().
     {
         int sent = 0;
         do
         {
             UpdateEventFlags();     // If there is something to send, update the flags before calling send, because FD_SEND is an edge-triggered event.
             sent = send(socket, reinterpret_cast<char*>(sendBuffer.contiguous_range(sendBuffer.begin()).begin())
                 , sendBuffer.contiguous_range(sendBuffer.begin()).size(), 0);
             if (sent == SOCKET_ERROR)
             {
                 if (WSAGetLastError() != WSAEWOULDBLOCK)
                     ResetOwnership();
                 return;
             }
             UpdateEventFlags();
             sendBuffer.erase(sendBuffer.begin(), sendBuffer.begin() + sent);
         } while (sent != 0 && !sendBuffer.empty());
         if (requestedSendSize != 0)
             TryAllocateSendStream();
     }
SetObserver()
void services::ConnectionWin::SetObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
Definition at line 80 of file ConnectionWin.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), services::ConnectionObserver::Connected(), network, services::EventDispatcherWithNetwork::RegisterConnection(), services::Connection::SetOwnership(), and infra::EnableSharedFromThis< ConnectionWin >::SharedFromThis().
     {
         connectionObserver->Attach(*this);
         SetOwnership(SharedFromThis(), connectionObserver);
         network.RegisterConnection(SharedFromThis());
         connectionObserver->Connected();
     }
TryAllocateSendStream()
void services::ConnectionWin::TryAllocateSendStream () private
Definition at line 158 of file ConnectionWin.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::BoundedDeque< T >::max_size(), requestedSendSize, infra::EventDispatcherWithWeakPtrWorker::Schedule(), sendBuffer, infra::EnableSharedFromThis< ConnectionWin >::SharedFromThis(), infra::BoundedDeque< T >::size(), and streamWriter.
Referenced by RequestSendStream(), and Send().
     {
         assert(streamWriter.Allocatable());
         if (sendBuffer.max_size() - sendBuffer.size() >= requestedSendSize)
         {
             auto size = requestedSendSize;
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([size](const infra::SharedPtr<ConnectionWin>& object)
             {
                 infra::SharedPtr<infra::StreamWriter> writer = object->streamWriter.Emplace(*object, size);
                 object->GetObserver().SendStreamAvailable(std::move(writer));
             }, SharedFromThis());
             requestedSendSize = 0;
         }
     }
TrySend()
void services::ConnectionWin::TrySend ()
Definition at line 143 of file ConnectionWin.cpp.
References Send(), and trySend.
     {
         if (trySend)
         {
             trySend = false;
             Send();
         }
     }
UpdateEventFlags()
void services::ConnectionWin::UpdateEventFlags ()
Definition at line 152 of file ConnectionWin.cpp.
References infra::BoundedDeque< T >::empty(), event, infra::BoundedDeque< T >::full(), receiveBuffer, sendBuffer, and socket.
Referenced by ConnectionWin(), and Send().
     {
         int result = WSAEventSelect(socket, event, (!receiveBuffer.full() ? FD_READ : 0) | (!sendBuffer.empty() ? FD_WRITE : 0) | FD_CLOSE);
         assert(result == 0);
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 70 of file ConnectionWin.hpp.
Member Data Documentation
event
WSAEVENT services::ConnectionWin::event = WSACreateEvent() private
Definition at line 74 of file ConnectionWin.hpp.
Referenced by UpdateEventFlags(), and ~ConnectionWin().
network
EventDispatcherWithNetwork& services::ConnectionWin::network private
Definition at line 72 of file ConnectionWin.hpp.
Referenced by SetObserver().
receiveBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<2048> services::ConnectionWin::receiveBuffer private
Definition at line 76 of file ConnectionWin.hpp.
Referenced by Receive(), and UpdateEventFlags().
requestedSendSize
std::size_t services::ConnectionWin::requestedSendSize = 0 private
Definition at line 80 of file ConnectionWin.hpp.
Referenced by RequestSendStream(), Send(), and TryAllocateSendStream().
sendBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<2048> services::ConnectionWin::sendBuffer private
Definition at line 77 of file ConnectionWin.hpp.
Referenced by MaxSendStreamSize(), Send(), TryAllocateSendStream(), and UpdateEventFlags().
socket
SOCKET services::ConnectionWin::socket private
Definition at line 73 of file ConnectionWin.hpp.
Referenced by AbortAndDestroy(), Ipv4Address(), Receive(), Send(), UpdateEventFlags(), and ~ConnectionWin().
streamReader
infra::SharedOptional<StreamReaderWin> services::ConnectionWin::streamReader private
Definition at line 81 of file ConnectionWin.hpp.
Referenced by AckReceived(), and ReceiveStream().
streamWriter
infra::SharedOptional<StreamWriterWin> services::ConnectionWin::streamWriter private
Definition at line 79 of file ConnectionWin.hpp.
Referenced by TryAllocateSendStream().
trySend
bool services::ConnectionWin::trySend = false private
Definition at line 82 of file ConnectionWin.hpp.
Referenced by TrySend().
The documentation for this class was generated from the following files:
ConnectionWin.hpp
ConnectionWin.cpp