EMil: services::TracingStreamReader Class Reference
services::TracingStreamReader Class Reference
#include <TracingInputStream.hpp>
Public Member Functions
TracingStreamReader (infra::StreamReader &reader, services::Tracer &tracer)
virtual void Extract (infra::ByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (infra::StreamErrorPolicy &errorPolicy) override
virtual infra::ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual infra::ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
Private Attributes
infra::StreamReader & reader
services::Tracer & tracer
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 9 of file TracingInputStream.hpp.
Constructor & Destructor Documentation
TracingStreamReader()
services::TracingStreamReader::TracingStreamReader (infra::StreamReader & reader, services::Tracer & tracer)
Definition at line 5 of file TracingInputStream.cpp.
         : reader(reader)
         , tracer(tracer)
     {}
Member Function Documentation
Available()
std::size_t services::TracingStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 40 of file TracingInputStream.cpp.
References infra::StreamReader::Available(), and reader.
     {
         return reader.Available();
     }
Empty()
bool services::TracingStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 35 of file TracingInputStream.cpp.
References infra::StreamReader::Empty(), and reader.
     {
         return reader.Empty();
     }
Extract()
void services::TracingStreamReader::Extract (infra::ByteRange range, infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 10 of file TracingInputStream.cpp.
References infra::AsHex(), infra::StreamReader::Extract(), reader, services::Tracer::Trace(), and tracer.
     {
         reader.Extract(range, errorPolicy);
         tracer.Trace() << "" << infra::AsHex(range);
     }
ExtractContiguousRange()
infra::ConstByteRange services::TracingStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 21 of file TracingInputStream.cpp.
References infra::AsHex(), infra::StreamReader::ExtractContiguousRange(), reader, services::Tracer::Trace(), and tracer.
     {
         infra::ConstByteRange result = reader.ExtractContiguousRange(max);
         tracer.Trace() << "" << infra::AsHex(result);
         return result;
     }
Peek()
uint8_t services::TracingStreamReader::Peek (infra::StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 16 of file TracingInputStream.cpp.
References infra::StreamReader::Peek(), and reader.
     {
         return reader.Peek(errorPolicy);
     }
PeekContiguousRange()
infra::ConstByteRange services::TracingStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 28 of file TracingInputStream.cpp.
References infra::AsHex().
     {
         infra::ConstByteRange result = reader.PeekContiguousRange(start);
         tracer.Trace() << "" << infra::AsHex(result);
         return result;
     }
Member Data Documentation
reader
infra::StreamReader& services::TracingStreamReader::reader private
Definition at line 24 of file TracingInputStream.hpp.
Referenced by Available(), Empty(), Extract(), ExtractContiguousRange(), and Peek().
tracer
services::Tracer& services::TracingStreamReader::tracer private
Definition at line 25 of file TracingInputStream.hpp.
Referenced by Extract(), and ExtractContiguousRange().
The documentation for this class was generated from the following files:
TracingInputStream.hpp
TracingInputStream.cpp