EMil: HttpClientTest Class Reference
HttpClientTest Class Reference
Public Member Functions
HttpClientTest ()
void Connect ()
Public Attributes
testing::StrictMock< services::ConnectionFactoryWithNameLookupMock > connectionFactory
testing::StrictMock< services::HttpClientObserverFactoryMock > factory
testing::StrictMock< services::HttpClientObserverFactoryMock > factory2
services::HttpClientConnectorImpl ::WithMaxHeaderSize< 50 > connector
testing::StrictMock< services::ConnectionStubWithAckReceivedMock > connection
infra::SharedPtr< services::Connection > connectionPtr
testing::StrictMock< services::HttpClientObserverMock > client
infra::SharedPtr< services::HttpClientObserver > clientPtr
Detailed Description
Definition at line 94 of file TestHttpClient.cpp.
Constructor & Destructor Documentation
HttpClientTest()
HttpClientTest::HttpClientTest () inline
Definition at line 99 of file TestHttpClient.cpp.
References Connect(), services::HttpClientConnectorImpl< HttpClient, Args >::Connect(), connectionFactory, connector, factory, and factory2.
         : connector(connectionFactory)
         , connectionPtr(infra::UnOwnedSharedPtr(connection))
         , clientPtr(infra::UnOwnedSharedPtr(client))
     {
         EXPECT_CALL(factory, Hostname()).WillRepeatedly(testing::Return("localhost"));
         EXPECT_CALL(factory, Port()).WillRepeatedly(testing::Return(80));
         EXPECT_CALL(factory2, Hostname()).WillRepeatedly(testing::Return("localhost"));
         EXPECT_CALL(factory2, Port()).WillRepeatedly(testing::Return(80));
         EXPECT_CALL(connectionFactory, Connect(testing::Ref(connector)));
         connector.Connect(factory);
     }
Member Function Documentation
Connect()
void HttpClientTest::Connect () inline
Definition at line 112 of file TestHttpClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), client, clientPtr, services::ConnectionObserver::Connected(), connection, services::HttpClientConnectorImpl< HttpClient, Args >::ConnectionEstablished(), connector, and factory.
Referenced by HttpClientTest().
     {
         EXPECT_CALL(factory, ConnectionEstablished(testing::_)).WillOnce(testing::Invoke([this](infra::AutoResetFunction<void(infra::SharedPtr<services::HttpClientObserver> client)>& createdClient)
         {
             EXPECT_CALL(client, Connected());
             createdClient(clientPtr);
         }));
         connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             connectionObserver->Attach(connection);
             connection.SetOwnership(nullptr, connectionObserver);
             connectionObserver->Connected();
         });
     }
Member Data Documentation
client
testing::StrictMock<services::HttpClientObserverMock> HttpClientTest::client
Definition at line 134 of file TestHttpClient.cpp.
Referenced by Connect().
clientPtr
infra::SharedPtr<services::HttpClientObserver> HttpClientTest::clientPtr
Definition at line 135 of file TestHttpClient.cpp.
Referenced by Connect().
connection
testing::StrictMock<services::ConnectionStubWithAckReceivedMock> HttpClientTest::connection
Definition at line 132 of file TestHttpClient.cpp.
Referenced by Connect().
connectionFactory
testing::StrictMock<services::ConnectionFactoryWithNameLookupMock> HttpClientTest::connectionFactory
Definition at line 128 of file TestHttpClient.cpp.
Referenced by HttpClientTest().
connectionPtr
infra::SharedPtr<services::Connection> HttpClientTest::connectionPtr
Definition at line 133 of file TestHttpClient.cpp.
connector
services::HttpClientConnectorImpl ::WithMaxHeaderSize<50> HttpClientTest::connector
Definition at line 131 of file TestHttpClient.cpp.
Referenced by Connect(), and HttpClientTest().
factory
testing::StrictMock<services::HttpClientObserverFactoryMock> HttpClientTest::factory
Definition at line 129 of file TestHttpClient.cpp.
Referenced by Connect(), and HttpClientTest().
factory2
testing::StrictMock<services::HttpClientObserverFactoryMock> HttpClientTest::factory2
Definition at line 130 of file TestHttpClient.cpp.
Referenced by HttpClientTest().
The documentation for this class was generated from the following file:
TestHttpClient.cpp