EMil: services::Tracer Class Reference
services::Tracer Class Reference
#include <Tracer.hpp>
Public Member Functions
Tracer (infra::TextOutputStream &stream)
Tracer (const Tracer &other)=delete
Tracer & operator= (const Tracer &other)=delete
virtual ~Tracer ()=default
infra::TextOutputStream Trace ()
infra::TextOutputStream Continue ()
Protected Member Functions
virtual void InsertHeader ()
Private Attributes
infra::TextOutputStream & stream
Detailed Description
Definition at line 8 of file Tracer.hpp.
Constructor & Destructor Documentation
Tracer() [1/2]
services::Tracer::Tracer (infra::TextOutputStream & stream) explicit
Definition at line 5 of file Tracer.cpp.
         : stream(stream)
     {}
Tracer() [2/2]
services::Tracer::Tracer (const Tracer & other) delete
~Tracer()
virtual services::Tracer::~Tracer () virtual default
Member Function Documentation
Continue()
infra::TextOutputStream services::Tracer::Continue ()
Definition at line 17 of file Tracer.cpp.
References stream.
Referenced by services::TracerWithDateTime::InsertHeader(), services::TracerWithTime::InsertHeader(), services::TracingConnectionMbedTls::LogFailure(), services::TracerAdapterPrintf::ParseFormat(), services::TracerAdapterPrintf::Print(), and Trace().
     {
         return stream;
     }
InsertHeader()
void services::Tracer::InsertHeader () protected virtual
Reimplemented in services::TracerWithDateTime, and services::TracerWithTime.
Definition at line 22 of file Tracer.cpp.
Referenced by Trace().
     {}
operator=()
Tracer& services::Tracer::operator= (const Tracer & other) delete
Trace()
infra::TextOutputStream services::Tracer::Trace ()
Definition at line 9 of file Tracer.cpp.
References Continue(), InsertHeader(), and stream.
Referenced by services::AllocatorTracingConnectionMbedTlsAdapter::Allocate(), services::AllocatorTracingConnectionMbedTlsAdapter::AllocatorTracingConnectionMbedTlsAdapter(), application::TracingHttpClient::BodyAvailable(), services::TracingHttpClientImpl::ClosingConnection(), services::TracingHttpClientImpl::Connected(), services::TracingHttpClientImpl::DataReceived(), application::TracingHttpClient::Done(), services::TracingFlash::EraseSectors(), application::TracingHttpClient::Error(), services::TracingStreamReader::Extract(), services::TracingStreamReader::ExtractContiguousRange(), application::TracingHttpClient::HeaderAvailable(), services::TracingConnectionMbedTls::LogFailure(), services::TracerAdapterPrintf::Print(), services::TracingFlash::ReadBuffer(), services::TracingStatusHttpClientImpl::StatusAvailable(), application::TracingHttpClient::StatusAvailable(), services::TracingConnectionMbedTls::TlsLog(), services::TracingConnectionFactoryMbedTls::TracingConnectionFactoryMbedTls(), services::TracingFlash::WriteBuffer(), and services::TracingHttpClientImpl::WriteRequest().
     {
         stream << "\r\n";
         InsertHeader();
         return Continue();
     }
Member Data Documentation
stream
infra::TextOutputStream& services::Tracer::stream private
Definition at line 23 of file Tracer.hpp.
Referenced by Continue(), and Trace().
The documentation for this class was generated from the following files:
Tracer.hpp
Tracer.cpp