EMil: services::ConnectionSerial::StateInitSizeResponseRequest Class Reference
services::ConnectionSerial::StateInitSizeResponseRequest Class Reference
Public Member Functions
StateInitSizeResponseRequest (ConnectionSerial &connection)
virtual void SizeRequestReceived () override
virtual void SizeResponseReceived (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::StateInit
StateInit (ConnectionSerial &connection)
virtual void EvaluatePendingSend () override
virtual void Reset () override
virtual void SizeResponseRequestReceived (size_t size) override
virtual size_t ContentReceived (infra::ConstByteRange receivedRange) override
virtual void SizeUpdateReceived (size_t size) override
virtual void AccumulateWindowUpdateSize (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::State
State (ConnectionSerial &connection)
virtual ~State ()=default
virtual void AckReceived ()
Private Member Functions
void SendWindowSizeResponseRequest ()
Private Attributes
MessageHeader windowSizeRespReqMsg = MessageHeader(MessageType::SizeResponseRequest)
Additional Inherited Members
Protected Attributes inherited from services::ConnectionSerial::StateInit
bool sendInProgress = false
bool resetAfterSend = false
bool responseRequestAfterSend = false
Protected Attributes inherited from services::ConnectionSerial::State
ConnectionSerial & connection
hal::SerialCommunication & serialCommunication
Detailed Description
Definition at line 168 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
StateInitSizeResponseRequest()
services::ConnectionSerial::StateInitSizeResponseRequest::StateInitSizeResponseRequest (ConnectionSerial & connection)
Definition at line 393 of file ConnectionSerial.cpp.
References SendWindowSizeResponseRequest().
         : StateInit(connection)
     {
         SendWindowSizeResponseRequest();
     }
Member Function Documentation
SendWindowSizeResponseRequest()
void services::ConnectionSerial::StateInitSizeResponseRequest::SendWindowSizeResponseRequest () private
Definition at line 399 of file ConnectionSerial.cpp.
References hal::SerialCommunication::SendData(), and services::ConnectionSerial::serialCommunication.
Referenced by StateInitSizeResponseRequest().
     {
         sendInProgress = true;
         windowSizeRespReqMsg.SetSize(connection.ReceiveBufferSize());
         serialCommunication.SendData(windowSizeRespReqMsg.Range(), [this]()
         {
             sendInProgress = false;
             if (responseRequestAfterSend)
                 connection.GoStateInitSizeResponseRequest();
         });
     }
SizeRequestReceived()
void services::ConnectionSerial::StateInitSizeResponseRequest::SizeRequestReceived () override virtual
Implements services::ConnectionSerial::State.
Definition at line 418 of file ConnectionSerial.cpp.
     {
         if (!sendInProgress)
             connection.GoStateInitSizeResponseRequest();
         else
             responseRequestAfterSend = true;
     }
SizeResponseReceived()
void services::ConnectionSerial::StateInitSizeResponseRequest::SizeResponseReceived (size_t size) override virtual
Reimplemented from services::ConnectionSerial::StateInit.
Definition at line 412 of file ConnectionSerial.cpp.
     {
         connection.peerBufferSize = size;
         connection.GoStateConnectedIdle();
     }
Member Data Documentation
windowSizeRespReqMsg
MessageHeader services::ConnectionSerial::StateInitSizeResponseRequest::windowSizeRespReqMsg = MessageHeader(MessageType::SizeResponseRequest) private
Definition at line 180 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp