EMil: infra::ClaimableResource::ClaimerBase Class Reference
infra::ClaimableResource::ClaimerBase Class Reference abstract
#include <ClaimableResource.hpp>
Public Member Functions
ClaimerBase (ClaimableResource &resource)
ClaimerBase (const ClaimerBase &other)=delete
ClaimerBase & operator= (const ClaimerBase &other)=delete
virtual void Release ()=0
bool IsClaimed () const
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Protected Member Functions
~ClaimerBase ()
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Private Member Functions
virtual void ClaimGranted ()=0
Private Attributes
ClaimableResource & resource
bool isGranted = false
bool isQueued = false
Friends
class ClaimableResource
Detailed Description
Definition at line 40 of file ClaimableResource.hpp.
Constructor & Destructor Documentation
ClaimerBase() [1/2]
infra::ClaimableResource::ClaimerBase::ClaimerBase (ClaimableResource & resource) explicit
Definition at line 52 of file ClaimableResource.cpp.
         : resource(resource)
     {}
ClaimerBase() [2/2]
infra::ClaimableResource::ClaimerBase::ClaimerBase (const ClaimerBase & other) delete
~ClaimerBase()
infra::ClaimableResource::ClaimerBase::~ClaimerBase () protected
Definition at line 56 of file ClaimableResource.cpp.
References Release().
     {
         if (isGranted)
             ClaimerBase::Release();
         if (isQueued)
             ClaimerBase::Release();
     }
Member Function Documentation
ClaimGranted()
virtual void infra::ClaimableResource::ClaimerBase::ClaimGranted () private pure virtual
Implemented in infra::ClaimableResource::ClaimerWithSize< ExtraSize >, infra::ClaimableResource::ClaimerWithSize< SERVICES_FLASH_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE >, infra::ClaimableResource::ClaimerWithSize< SERVICES_SPI_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE >, infra::ClaimableResource::ClaimerWithSize< SERVICES_I2C_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE >, and infra::ClaimableResource::ClaimerWithSize< SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE >.
Referenced by infra::ClaimableResource::ReEvaluateClaim().
IsClaimed()
bool infra::ClaimableResource::ClaimerBase::IsClaimed () const
Definition at line 74 of file ClaimableResource.cpp.
     {
         return isGranted;
     }
operator=()
ClaimerBase& infra::ClaimableResource::ClaimerBase::operator= (const ClaimerBase & other) delete
Release()
void infra::ClaimableResource::ClaimerBase::Release () pure virtual
Implemented in infra::ClaimableResource::ClaimerWithSize< ExtraSize >, infra::ClaimableResource::ClaimerWithSize< SERVICES_FLASH_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE >, infra::ClaimableResource::ClaimerWithSize< SERVICES_SPI_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE >, infra::ClaimableResource::ClaimerWithSize< SERVICES_I2C_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE >, and infra::ClaimableResource::ClaimerWithSize< SERVICES_CYCLIC_STORE_FUNCTION_EXTRA_SIZE >.
Definition at line 65 of file ClaimableResource.cpp.
Referenced by ~ClaimerBase().
     {
         if (!isGranted)
             isQueued = false;
         isGranted = false;
         resource.RemoveClaim(*this);
     }
Friends And Related Function Documentation
ClaimableResource
friend class ClaimableResource friend
Definition at line 56 of file ClaimableResource.hpp.
Member Data Documentation
isGranted
bool infra::ClaimableResource::ClaimerBase::isGranted = false private
Definition at line 62 of file ClaimableResource.hpp.
isQueued
bool infra::ClaimableResource::ClaimerBase::isQueued = false private
Definition at line 63 of file ClaimableResource.hpp.
resource
ClaimableResource& infra::ClaimableResource::ClaimerBase::resource private
Definition at line 61 of file ClaimableResource.hpp.
The documentation for this class was generated from the following files:
ClaimableResource.hpp
ClaimableResource.cpp