EMil: TestStaticStorage.cpp File Reference
TestStaticStorage.cpp File Reference
Functions
TEST (StaticStorageTest, TestConstruction)
TEST (StaticStorageTest, TestConstructionOfValue)
TEST (StaticStorageTest, TestInheritanceTree)
Function Documentation
TEST() [1/3]
TEST (StaticStorageTest , TestConstruction)
Definition at line 5 of file TestStaticStorage.cpp.
 {
     infra::StaticStorage<bool> s;
     (void)s;
 }
TEST() [2/3]
TEST (StaticStorageTest , TestConstructionOfValue)
Definition at line 11 of file TestStaticStorage.cpp.
References infra::StaticStorage< T >::Construct(), and EXPECT_TRUE().
 {
     infra::StaticStorage<bool> s;
     s.Construct(true);
     EXPECT_TRUE(*s);
 }
TEST() [3/3]
TEST (StaticStorageTest , TestInheritanceTree)
Definition at line 38 of file TestStaticStorage.cpp.
References infra::StaticStorageForPolymorphicObjects< T, ExtraSize, AlignAs >::Construct(), infra::StaticStorageForPolymorphicObjects< T, ExtraSize, AlignAs >::Destruct(), and EXPECT_EQ().
 {
     struct A
     {
         virtual ~A() = default;
     };
     struct B
         : A
     {};
     struct C
         : A
     {
         C(uint64_t aX)
             : x(aX)
         {}
         uint64_t x;
     };
     infra::StaticStorageForInheritanceTree<A, B> b;
     infra::StaticStorageForInheritanceTree<A, B, C> c;
     EXPECT_EQ(sizeof(b), 2 * sizeof(void*));
     EXPECT_EQ(sizeof(c), 4 * sizeof(void*) + sizeof(uint64_t));
     b.Construct<B>();
     c.Construct<C>(5);
     b.Destruct();
     c.Destruct();
 }