EMil: TestEventHandler.cpp File Reference
TestEventHandler.cpp File Reference
Classes
class EventDispatcherTest
Functions
TEST_F (EventDispatcherTest, TestConstruction)
TEST_F (EventDispatcherTest, TestSchedule)
TEST_F (EventDispatcherTest, TestScheduleTwice)
void helper1 ()
void helper2 ()
TEST_F (EventDispatcherTest, TestPerformance)
Variables
bool helper1turn = true
Function Documentation
helper1()
void helper1 ()
Definition at line 36 of file TestEventHandler.cpp.
References helper1turn.
Referenced by TEST_F().
 {
     really_assert(helper1turn);
     helper1turn = false;
 }
helper2()
void helper2 ()
Definition at line 42 of file TestEventHandler.cpp.
References helper1turn.
Referenced by TEST_F().
 {
     really_assert(!helper1turn);
     helper1turn = true;
 }
TEST_F() [1/4]
TEST_F (EventDispatcherTest , TestConstruction)
Definition at line 12 of file TestEventHandler.cpp.
 {}
TEST_F() [2/4]
TEST_F (EventDispatcherTest , TestSchedule)
Definition at line 15 of file TestEventHandler.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), and infra::EventDispatcherWorker::Schedule().
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback());
     infra::EventDispatcher::Instance().Schedule([&callback, this]() { callback.callback(); });
     ExecuteAllActions();
 }
TEST_F() [3/4]
TEST_F (EventDispatcherTest , TestScheduleTwice)
Definition at line 24 of file TestEventHandler.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), and infra::EventDispatcherWorker::Schedule().
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).Times(2);
     infra::EventDispatcher::Instance().Schedule([&callback, this]() { callback.callback(); });
     infra::EventDispatcher::Instance().Schedule([&callback, this]() { callback.callback(); });
     ExecuteAllActions();
 }
TEST_F() [4/4]
TEST_F (EventDispatcherTest , TestPerformance)
Definition at line 48 of file TestEventHandler.cpp.
References helper1(), helper2(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), and infra::EventDispatcherWorker::Schedule().
 {
     for (int j = 0; j != 10; ++j)
     {
         for (int i = 0; i != 20; ++i)
         {
             infra::EventDispatcher::Instance().Schedule([]() { helper1(); });
             infra::EventDispatcher::Instance().Schedule([]() { helper2(); });
         }
         ExecuteAllActions();
     }
 }
Variable Documentation
helper1turn
bool helper1turn = true
Definition at line 34 of file TestEventHandler.cpp.
Referenced by helper1(), and helper2().