EMil: services::SynchronousSpiMasterWithChipSelect Class Reference
services::SynchronousSpiMasterWithChipSelect Class Reference
#include <SynchronousSpiMasterWithChipSelect.hpp>
Public Member Functions
SynchronousSpiMasterWithChipSelect (hal::SynchronousSpi &spi, hal::GpioPin &chipSelect)
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, Action nextAction) override
Public Member Functions inherited from hal::SynchronousSpi
SynchronousSpi ()=default
SynchronousSpi (const SynchronousSpi &other)=delete
SynchronousSpi & operator= (const SynchronousSpi &other)=delete
void SendData (infra::ConstByteRange data, Action nextAction)
void ReceiveData (infra::ByteRange data, Action nextAction)
Private Attributes
hal::SynchronousSpi & spi
hal::OutputPin chipSelect
Additional Inherited Members
Public Types inherited from hal::SynchronousSpi
enum Action { continueSession, stop }
Protected Member Functions inherited from hal::SynchronousSpi
~SynchronousSpi ()=default
Detailed Description
Definition at line 9 of file SynchronousSpiMasterWithChipSelect.hpp.
Constructor & Destructor Documentation
SynchronousSpiMasterWithChipSelect()
services::SynchronousSpiMasterWithChipSelect::SynchronousSpiMasterWithChipSelect (hal::SynchronousSpi & spi, hal::GpioPin & chipSelect)
Definition at line 5 of file SynchronousSpiMasterWithChipSelect.cpp.
References chipSelect, and hal::OutputPin::Set().
         : spi(spi)
         , chipSelect(chipSelect)
     {
         chipSelect.Set(true);
     }
Member Function Documentation
SendAndReceive()
void services::SynchronousSpiMasterWithChipSelect::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, Action nextAction) override virtual
Implements hal::SynchronousSpi.
Definition at line 12 of file SynchronousSpiMasterWithChipSelect.cpp.
References chipSelect, hal::SynchronousSpi::SendAndReceive(), hal::OutputPin::Set(), spi, and hal::stop.
     {
         chipSelect.Set(false);
         spi.SendAndReceive(sendData, receiveData, nextAction);
         if (nextAction == Action::stop)
             chipSelect.Set(true);
     }
Member Data Documentation
chipSelect
hal::OutputPin services::SynchronousSpiMasterWithChipSelect::chipSelect private
Definition at line 19 of file SynchronousSpiMasterWithChipSelect.hpp.
Referenced by SendAndReceive(), and SynchronousSpiMasterWithChipSelect().
spi
hal::SynchronousSpi& services::SynchronousSpiMasterWithChipSelect::spi private
Definition at line 18 of file SynchronousSpiMasterWithChipSelect.hpp.
Referenced by SendAndReceive().
The documentation for this class was generated from the following files:
SynchronousSpiMasterWithChipSelect.hpp
SynchronousSpiMasterWithChipSelect.cpp