EMil: infra::JsonSubArrayParser Class Reference
infra::JsonSubArrayParser Class Reference
#include <JsonStreamingParser.hpp>
Public Types
enum State {
State::initialOpen, State::open, State::closed, State::skipNestedObject,
State::skipNestedArray, State::parseError, State::semanticError
}
Public Member Functions
JsonSubArrayParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char &subObjects)
~JsonSubArrayParser ()
virtual void Feed (infra::MemoryRange< const char > &data) override
virtual JsonVisitor & Visitor () override
virtual void SetVisitor (JsonVisitor &visitor) override
void SemanticError ()
Public Member Functions inherited from infra::JsonSubParser
JsonSubParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char &subObjects)
JsonSubParser (const JsonSubParser &other)=delete
JsonSubParser & operator= (const JsonSubParser &other)=delete
virtual ~JsonSubParser ()
Private Attributes
JsonArrayVisitor * visitor
State state = State::initialOpen
uint32_t skipSubObjects = 0
bool * destructedIndication = nullptr
Additional Inherited Members
Protected Types inherited from infra::JsonSubParser
enum TokenState {
TokenState::open, TokenState::done, TokenState::stringOpen, TokenState::stringOpenAndEscaped,
TokenState::stringOverflowOpen, TokenState::unicodeValueOpen, TokenState::numberOpen, TokenState::numberFractionalOpen,
TokenState::numberExponentOpen, TokenState::identifierOpen
}
enum Token {
Token::error, Token::colon, Token::comma, Token::leftBrace,
Token::rightBrace, Token::leftBracket, Token::rightBracket, Token::string,
Token::stringOverflow, Token::number, Token::true_, Token::false_,
Token::null
}
Protected Member Functions inherited from infra::JsonSubParser
void FeedToken (infra::MemoryRange< const char > &data, bool saveValue)
void ReportParseError ()
void ReportSemanticError ()
infra::BoundedString CopyAndClear (infra::BoundedString &value) const
Protected Attributes inherited from infra::JsonSubParser
infra::BoundedString tagBuffer
infra::BoundedString valueBuffer
infra::BoundedVector< infra::PolymorphicVariant< JsonSubParser, JsonSubObjectParser, JsonSubArrayParser > > & subObjects
TokenState tokenState = TokenState::open
Token token = Token::error
int64_t tokenNumber
int8_t tokenSign
Detailed Description
Definition at line 187 of file JsonStreamingParser.hpp.
Member Enumeration Documentation
State
enum infra::JsonSubArrayParser::State strong
Enumerator
initialOpen
open
closed
skipNestedObject
skipNestedArray
parseError
semanticError
Definition at line 200 of file JsonStreamingParser.hpp.
         {
             initialOpen,
             open,
             closed,
             skipNestedObject,
             skipNestedArray,
             parseError,
             semanticError
         };
Constructor & Destructor Documentation
JsonSubArrayParser()
infra::JsonSubArrayParser::JsonSubArrayParser (infra::BoundedString tagBuffer, infra::BoundedString valueBuffer, char & subObjects)
Definition at line 538 of file JsonStreamingParser.cpp.
         : JsonSubParser(tagBuffer, valueBuffer, subObjects)
     {}
~JsonSubArrayParser()
infra::JsonSubArrayParser::~JsonSubArrayParser ()
Definition at line 542 of file JsonStreamingParser.cpp.
References destructedIndication.
     {
         if (destructedIndication != nullptr)
             *destructedIndication = true;
     }
Member Function Documentation
Feed()
void infra::JsonSubArrayParser::Feed (infra::MemoryRange< const char > & data) override virtual
Implements infra::JsonSubParser.
Definition at line 548 of file JsonStreamingParser.cpp.
References infra::BoundedStringBase< T >::clear(), infra::JsonArrayVisitor::Close(), closed, infra::JsonSubParser::comma, infra::data, destructedIndication, infra::JsonSubParser::done, infra::JsonSubParser::false_, infra::JsonSubParser::FeedToken(), initialOpen, infra::JsonSubParser::leftBrace, infra::JsonSubParser::leftBracket, infra::JsonSubParser::null, infra::JsonSubParser::number, infra::JsonSubParser::open, open, parseError, infra::JsonSubParser::ReportParseError(), infra::JsonSubParser::ReportSemanticError(), infra::JsonSubParser::rightBrace, infra::JsonSubParser::rightBracket, semanticError, skipNestedArray, skipNestedObject, skipSubObjects, state, infra::JsonSubParser::string, infra::JsonArrayVisitor::StringOverflow(), infra::JsonSubParser::stringOverflow, infra::JsonSubParser::subObjects, infra::JsonSubParser::tagBuffer, infra::JsonSubParser::token, infra::JsonSubParser::tokenNumber, infra::JsonSubParser::tokenSign, infra::JsonSubParser::tokenState, infra::JsonSubParser::true_, infra::JsonSubParser::valueBuffer, infra::JsonArrayVisitor::VisitArray(), infra::JsonArrayVisitor::VisitBoolean(), infra::JsonArrayVisitor::VisitNull(), infra::JsonArrayVisitor::VisitNumber(), infra::JsonArrayVisitor::VisitObject(), visitor, and infra::JsonArrayVisitor::VisitString().
     {
         bool destructed = false;
         destructedIndication = &destructed;
         infra::ExecuteOnDestruction::WithExtraSize<3 * sizeof(void*)> execute([this, &destructed, &data]()
         {
             if (!destructed)
                 destructedIndication = nullptr;
         });
         while (!destructed && !data.empty() && state != State::parseError && state != State::semanticError)
         {
             FeedToken(data, state != State::skipNestedObject && state != State::skipNestedArray);
             if (tokenState != TokenState::done)
                 break;
             if ((state == State::initialOpen || state == State::open) && token == Token::string)
             {
                 state = State::closed;
                 visitor->VisitString(valueBuffer);
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::stringOverflow)
             {
                 state = State::closed;
                 visitor->StringOverflow();
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::false_)
             {
                 state = State::closed;
                 visitor->VisitBoolean(false);
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::true_)
             {
                 state = State::closed;
                 visitor->VisitBoolean(true);
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::null)
             {
                 state = State::closed;
                 visitor->VisitNull();
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::number)
             {
                 state = State::closed;
                 tagBuffer.clear();
                 visitor->VisitNumber(tokenSign * tokenNumber);
             }
             else if ((state == State::initialOpen || state == State::closed) && token == Token::rightBracket)
             {
                 state = State::closed;
                 visitor->Close();
                 if (!destructed)
                     subObjects.pop_back();
                 return;
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::leftBrace)
             {
                 tokenState = TokenState::open;
                 state = State::closed;
                 if (subObjects.full())
                     state = State::skipNestedObject;
                 else
                 {
                     subObjects.emplace_back(infra::InPlaceType<JsonSubObjectParser>(), tagBuffer, valueBuffer, reinterpret_cast<char&>(subObjects));
                     auto nestedVisitor = visitor->VisitObject(static_cast<JsonSubObjectParser&>(*subObjects.back()));
                     if (destructed)
                         return;
                     if (nestedVisitor != nullptr)
                         subObjects.back()->SetVisitor(*nestedVisitor);
                     else
                     {
                         subObjects.pop_back();
                         state = State::skipNestedObject;
                     }
                 }
                 return;
             }
             else if ((state == State::initialOpen || state == State::open) && token == Token::leftBracket)
             {
                 tokenState = TokenState::open;
                 state = State::closed;
                 if (subObjects.full())
                     state = State::skipNestedArray;
                 else
                 {
                     subObjects.emplace_back(infra::InPlaceType<JsonSubArrayParser>(), tagBuffer, valueBuffer, reinterpret_cast<char&>(subObjects));
                     auto nestedVisitor = visitor->VisitArray(static_cast<JsonSubArrayParser&>(*subObjects.back()));
                     if (destructed)
                         return;
                     if (nestedVisitor != nullptr)
                         subObjects.back()->SetVisitor(*nestedVisitor);
                     else
                     {
                         subObjects.pop_back();
                         state = State::skipNestedArray;
                     }
                 }
                 return;
             }
             else if (state == State::skipNestedObject)
             {
                 if (token == Token::rightBrace)
                 {
                     if (skipSubObjects == 0)
                         state = State::closed;
                     else
                         --skipSubObjects;
                 }
                 else if (token == Token::leftBrace)
                     ++skipSubObjects;
             }
             else if (state == State::skipNestedArray)
             {
                 if (token == Token::rightBracket)
                 {
                     if (skipSubObjects == 0)
                         state = State::closed;
                     else
                         --skipSubObjects;
                 }
                 else if (token == Token::leftBracket)
                     ++skipSubObjects;
             }
             else if (state == State::closed && token == Token::comma)
                 state = State::open;
             else
                 state = State::parseError;
             valueBuffer.clear();
             tokenState = TokenState::open;
         }
         if (state == State::parseError)
         {
             data.clear();
             ReportParseError();
         }
         if (state == State::semanticError)
         {
             data.clear();
             ReportSemanticError();
         }
     }
SemanticError()
void infra::JsonSubArrayParser::SemanticError ()
Definition at line 709 of file JsonStreamingParser.cpp.
References semanticError, and state.
     {
         state = State::semanticError;
     }
SetVisitor()
void infra::JsonSubArrayParser::SetVisitor (JsonVisitor & visitor) override virtual
Implements infra::JsonSubParser.
Definition at line 704 of file JsonStreamingParser.cpp.
References visitor.
     {
         this->visitor = static_cast<JsonArrayVisitor*>(&visitor);
     }
Visitor()
JsonVisitor & infra::JsonSubArrayParser::Visitor () override virtual
Implements infra::JsonSubParser.
Definition at line 699 of file JsonStreamingParser.cpp.
References visitor.
     {
         return *visitor;
     }
Member Data Documentation
destructedIndication
bool* infra::JsonSubArrayParser::destructedIndication = nullptr private
Definition at line 216 of file JsonStreamingParser.hpp.
Referenced by Feed(), and ~JsonSubArrayParser().
skipSubObjects
uint32_t infra::JsonSubArrayParser::skipSubObjects = 0 private
Definition at line 215 of file JsonStreamingParser.hpp.
Referenced by Feed().
state
State infra::JsonSubArrayParser::state = State::initialOpen private
Definition at line 214 of file JsonStreamingParser.hpp.
Referenced by Feed(), and SemanticError().
visitor
JsonArrayVisitor* infra::JsonSubArrayParser::visitor private
Definition at line 212 of file JsonStreamingParser.hpp.
Referenced by Feed(), SetVisitor(), and Visitor().
The documentation for this class was generated from the following files:
JsonStreamingParser.hpp
JsonStreamingParser.cpp