EMil: TestI2cRegisterAccess.cpp File Reference
TestI2cRegisterAccess.cpp File Reference
Classes
class I2cRegisterAccessTest
Functions
TEST_F (I2cRegisterAccessTest, TestReadRegister)
TEST_F (I2cRegisterAccessTest, TestWriteRegister)
Function Documentation
TEST_F() [1/2]
TEST_F (I2cRegisterAccessTest , TestReadRegister)
Definition at line 26 of file TestI2cRegisterAccess.cpp.
References data, EXPECT_EQ(), infra::MakeByteRange(), hal::repeatedStart, and hal::stop.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback());
     EXPECT_CALL(master, SendDataMock(slaveAddress, hal::Action::repeatedStart, std::vector<uint8_t>{ 3 }));
     EXPECT_CALL(master, ReceiveDataMock(slaveAddress, hal::Action::stop)).WillOnce(testing::Return(std::vector<uint8_t>{ 5, 6, 7 }));
     std::array<uint8_t, 3> data;
     registerAccess.ReadRegister(3, infra::MakeByteRange(data), [&callback]() { callback.callback(); });
     ExecuteAllActions();
     EXPECT_EQ((std::array<uint8_t, 3>{ 5, 6, 7 }), data);
 }
TEST_F() [2/2]
TEST_F (I2cRegisterAccessTest , TestWriteRegister)
Definition at line 41 of file TestI2cRegisterAccess.cpp.
References hal::continueSession, data, infra::MakeByteRange(), and hal::stop.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback());
     EXPECT_CALL(master, SendDataMock(slaveAddress, hal::Action::continueSession, std::vector<uint8_t>{ 3 }));
     EXPECT_CALL(master, SendDataMock(slaveAddress, hal::Action::stop, std::vector<uint8_t>{ 5, 6, 7 }));
     std::array<uint8_t, 3> data{ 5, 6, 7 };
     registerAccess.WriteRegister(3, infra::MakeByteRange(data), [&callback]() { callback.callback(); });
     ExecuteAllActions();
 }