EMil: hal::SynchronousFlashHomogeneous Class Reference
hal::SynchronousFlashHomogeneous Class Reference
#include <SynchronousFlashHomogeneous.hpp>
Public Member Functions
SynchronousFlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::SynchronousFlash
SynchronousFlash ()=default
SynchronousFlash (const SynchronousFlash &other)=delete
SynchronousFlash & operator= (const SynchronousFlash &other)=delete
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address)=0
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address)=0
void EraseSector (uint32_t sectorIndex)
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex)=0
void EraseAll ()
Protected Member Functions
~SynchronousFlashHomogeneous ()=default
Protected Member Functions inherited from hal::SynchronousFlash
~SynchronousFlash ()=default
Private Attributes
uint32_t numberOfSectors
uint32_t sizeOfEachSector
Additional Inherited Members
Public Types inherited from hal::SynchronousFlash
using Range = std::pair< uint32_t, uint32_t >
Detailed Description
Definition at line 8 of file SynchronousFlashHomogeneous.hpp.
Constructor & Destructor Documentation
SynchronousFlashHomogeneous()
hal::SynchronousFlashHomogeneous::SynchronousFlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
Definition at line 5 of file SynchronousFlashHomogeneous.cpp.
         : numberOfSectors(numberOfSectors)
         , sizeOfEachSector(sizeOfEachSector)
     {}
~SynchronousFlashHomogeneous()
hal::SynchronousFlashHomogeneous::~SynchronousFlashHomogeneous () protected default
Member Function Documentation
AddressOfSector()
uint32_t hal::SynchronousFlashHomogeneous::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::SynchronousFlash.
Definition at line 25 of file SynchronousFlashHomogeneous.cpp.
References sizeOfEachSector.
Referenced by services::SynchronousFlashSpi::SendEraseSector(), and services::SynchronousFlashSpi::SendEraseSubSector().
     {
         return sectorIndex * sizeOfEachSector;
     }
NumberOfSectors()
uint32_t hal::SynchronousFlashHomogeneous::NumberOfSectors () const override virtual
Implements hal::SynchronousFlash.
Definition at line 10 of file SynchronousFlashHomogeneous.cpp.
References numberOfSectors.
Referenced by services::SynchronousFlashSpi::EraseSomeSectors().
     {
         return numberOfSectors;
     }
SectorOfAddress()
uint32_t hal::SynchronousFlashHomogeneous::SectorOfAddress (uint32_t address) const override virtual
Implements hal::SynchronousFlash.
Definition at line 20 of file SynchronousFlashHomogeneous.cpp.
References sizeOfEachSector.
     {
         return address / sizeOfEachSector;
     }
SizeOfSector()
uint32_t hal::SynchronousFlashHomogeneous::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::SynchronousFlash.
Definition at line 15 of file SynchronousFlashHomogeneous.cpp.
References sizeOfEachSector.
     {
         return sizeOfEachSector;
     }
Member Data Documentation
numberOfSectors
uint32_t hal::SynchronousFlashHomogeneous::numberOfSectors private
Definition at line 25 of file SynchronousFlashHomogeneous.hpp.
Referenced by NumberOfSectors().
sizeOfEachSector
uint32_t hal::SynchronousFlashHomogeneous::sizeOfEachSector private
Definition at line 26 of file SynchronousFlashHomogeneous.hpp.
Referenced by AddressOfSector(), SectorOfAddress(), and SizeOfSector().
The documentation for this class was generated from the following files:
SynchronousFlashHomogeneous.hpp
SynchronousFlashHomogeneous.cpp