EMil: services::DebouncedButton Class Reference
services::DebouncedButton Class Reference
#include <DebouncedButton.hpp>
Public Member Functions
DebouncedButton (hal::GpioPin &buttonPin, infra::Function< void()> onPressed, infra::Function< void()> onReleased=infra::emptyFunction, infra::Duration debounceDuration=std::chrono::milliseconds(10))
~DebouncedButton ()
Private Member Functions
void ButtonChanged ()
void ButtonPressed ()
void ButtonReleased ()
void DebounceEnd () const
Private Attributes
hal::InputPin buttonPin
infra::Duration debounceDuration
bool previousButtonState
infra::TimerSingleShot debounceEnd
infra::Function< void()> onPressed
infra::Function< void()> onReleased
bool announcedPressed = false
Detailed Description
Definition at line 9 of file DebouncedButton.hpp.
Constructor & Destructor Documentation
DebouncedButton()
services::DebouncedButton::DebouncedButton (hal::GpioPin & buttonPin, infra::Function< void()> onPressed, infra::Function< void()> onReleased = infra::emptyFunction, infra::Duration debounceDuration = std::chrono::milliseconds(10))
Definition at line 5 of file DebouncedButton.cpp.
References hal::bothEdges, ButtonChanged(), and hal::GpioPin::EnableInterrupt().
         : buttonPin(buttonPin)
         , debounceDuration(debounceDuration)
         , previousButtonState(false)
         , onPressed(onPressed)
         , onReleased(onReleased)
     {
         this->buttonPin.EnableInterrupt([this]() { ButtonChanged(); }, hal::InterruptTrigger::bothEdges);
     }
~DebouncedButton()
services::DebouncedButton::~DebouncedButton ()
Definition at line 15 of file DebouncedButton.cpp.
References buttonPin, and hal::InputPin::DisableInterrupt().
     {
         buttonPin.DisableInterrupt();
     }
Member Function Documentation
ButtonChanged()
void services::DebouncedButton::ButtonChanged () private
Definition at line 20 of file DebouncedButton.cpp.
References buttonPin, ButtonPressed(), ButtonReleased(), hal::InputPin::Get(), and previousButtonState.
Referenced by DebouncedButton().
     {
         bool buttonState = buttonPin.Get();
         if (previousButtonState != buttonState)
         {
             if (buttonState)
                 ButtonPressed();
             else
                 ButtonReleased();
         }
         previousButtonState = buttonState;
     }
ButtonPressed()
void services::DebouncedButton::ButtonPressed () private
Definition at line 35 of file DebouncedButton.cpp.
References announcedPressed, infra::Timer::Armed(), debounceDuration, DebounceEnd(), debounceEnd, onPressed, and infra::TimerSingleShot::Start().
Referenced by ButtonChanged().
     {
         if (!debounceEnd.Armed())
         {
             debounceEnd.Start(debounceDuration, [this]() { DebounceEnd(); });
             announcedPressed = true;
             onPressed();
         }
     }
ButtonReleased()
void services::DebouncedButton::ButtonReleased () private
Definition at line 45 of file DebouncedButton.cpp.
References announcedPressed, infra::Timer::Armed(), debounceDuration, DebounceEnd(), debounceEnd, onReleased, and infra::TimerSingleShot::Start().
Referenced by ButtonChanged().
     {
         if (!debounceEnd.Armed())
         {
             debounceEnd.Start(debounceDuration, [this]() { DebounceEnd(); });
             announcedPressed = false;
             onReleased();
         }
     }
DebounceEnd()
void services::DebouncedButton::DebounceEnd () const private
Definition at line 55 of file DebouncedButton.cpp.
References announcedPressed, onPressed, onReleased, and previousButtonState.
Referenced by ButtonPressed(), and ButtonReleased().
     {
         if (announcedPressed && !previousButtonState)
             onReleased();
         else if (!announcedPressed && previousButtonState)
             onPressed();
     }
Member Data Documentation
announcedPressed
bool services::DebouncedButton::announcedPressed = false private
Definition at line 28 of file DebouncedButton.hpp.
Referenced by ButtonPressed(), ButtonReleased(), and DebounceEnd().
buttonPin
hal::InputPin services::DebouncedButton::buttonPin private
Definition at line 22 of file DebouncedButton.hpp.
Referenced by ButtonChanged(), and ~DebouncedButton().
debounceDuration
infra::Duration services::DebouncedButton::debounceDuration private
Definition at line 23 of file DebouncedButton.hpp.
Referenced by ButtonPressed(), and ButtonReleased().
debounceEnd
infra::TimerSingleShot services::DebouncedButton::debounceEnd private
Definition at line 25 of file DebouncedButton.hpp.
Referenced by ButtonPressed(), and ButtonReleased().
onPressed
infra::Function<void()> services::DebouncedButton::onPressed private
Definition at line 26 of file DebouncedButton.hpp.
Referenced by ButtonPressed(), and DebounceEnd().
onReleased
infra::Function<void()> services::DebouncedButton::onReleased private
Definition at line 27 of file DebouncedButton.hpp.
Referenced by ButtonReleased(), and DebounceEnd().
previousButtonState
bool services::DebouncedButton::previousButtonState private
Definition at line 24 of file DebouncedButton.hpp.
Referenced by ButtonChanged(), and DebounceEnd().
The documentation for this class was generated from the following files:
DebouncedButton.hpp
DebouncedButton.cpp