EMil: services::Connection Class Reference
services::Connection Class Reference abstract
#include <Connection.hpp>
Public Member Functions
virtual void RequestSendStream (std::size_t sendSize)=0
virtual std::size_t MaxSendStreamSize () const =0
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream ()=0
virtual void AckReceived ()=0
virtual void CloseAndDestroy ()=0
virtual void AbortAndDestroy ()=0
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Private Attributes
infra::SharedPtr< void > owner
infra::SharedPtr< ConnectionObserver > observer
Additional Inherited Members
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Detailed Description
Definition at line 31 of file Connection.hpp.
Member Function Documentation
AbortAndDestroy()
virtual void services::Connection::AbortAndDestroy () pure virtual
Implemented in services::ConnectionMbedTls, services::ConnectionSerial, services::ConnectionWin, and services::ConnectionBsd.
AckReceived()
virtual void services::Connection::AckReceived () pure virtual
Implemented in services::ConnectionMbedTls, services::ConnectionSerial, services::ConnectionWin, and services::ConnectionBsd.
CloseAndDestroy()
virtual void services::Connection::CloseAndDestroy () pure virtual
Implemented in services::ConnectionMbedTls, services::ConnectionSerial, services::ConnectionWin, and services::ConnectionBsd.
Referenced by services::HttpServerConnectionObserver::Close().
MaxSendStreamSize()
virtual std::size_t services::Connection::MaxSendStreamSize () const pure virtual
Implemented in services::ConnectionMbedTls, services::ConnectionSerial, services::ConnectionWin, and services::ConnectionBsd.
Observer()
infra::SharedPtr< ConnectionObserver > services::Connection::Observer () const
Definition at line 29 of file Connection.cpp.
References observer.
Referenced by services::HttpServerConnectionObserver::TakeOverConnection().
     {
         return observer;
     }
ReceiveStream()
virtual infra::SharedPtr<infra::StreamReaderWithRewinding> services::Connection::ReceiveStream () pure virtual
Implemented in services::ConnectionMbedTls, services::ConnectionSerial, services::ConnectionWin, and services::ConnectionBsd.
RequestSendStream()
virtual void services::Connection::RequestSendStream (std::size_t sendSize) pure virtual
Implemented in services::ConnectionMbedTls, services::ConnectionSerial, services::ConnectionWin, and services::ConnectionBsd.
ResetOwnership()
void services::Connection::ResetOwnership ()
Definition at line 16 of file Connection.cpp.
References observer, and owner.
Referenced by services::ConnectionBsd::AbortAndDestroy(), services::ConnectionWin::AbortAndDestroy(), services::ConnectionMbedTls::ClosingConnection(), services::ConnectionBsd::Receive(), services::ConnectionWin::Receive(), services::ConnectionBsd::Send(), services::ConnectionWin::Send(), and services::ConnectionMbedTls::~ConnectionMbedTls().
     {
         if (observer != nullptr)
         {
             // Someone may be keeping the observer alive, so give it the opportunity to close any open send/receive streams,
             // and detach it so that the owner is not observed anymore
             observer->ClosingConnection();
             observer->Detach();
         }
         observer = nullptr;
         owner = nullptr;
     }
SetOwnership()
void services::Connection::SetOwnership (const infra::SharedPtr< void > & owner, const infra::SharedPtr< ConnectionObserver > & observer)
Definition at line 10 of file Connection.cpp.
References observer, and owner.
Referenced by services::ConnectionMbedTls::CreatedObserver(), services::ConnectionBsd::SetObserver(), and services::ConnectionWin::SetObserver().
     {
         this->owner = owner;
         this->observer = observer;
     }
SwitchObserver()
void services::Connection::SwitchObserver (const infra::SharedPtr< ConnectionObserver > & newObserver)
Definition at line 5 of file Connection.cpp.
References observer.
Referenced by services::HttpServerConnectionObserver::TakeOverConnection().
     {
         this->observer = newObserver;
     }
Member Data Documentation
observer
infra::SharedPtr<ConnectionObserver> services::Connection::observer private
Definition at line 55 of file Connection.hpp.
Referenced by Observer(), ResetOwnership(), SetOwnership(), and SwitchObserver().
owner
infra::SharedPtr<void> services::Connection::owner private
Definition at line 54 of file Connection.hpp.
Referenced by ResetOwnership(), and SetOwnership().
The documentation for this class was generated from the following files:
Connection.hpp
Connection.cpp