EMil: services::ConnectionSerial::StateConnectedSendingContent Class Reference
services::ConnectionSerial::StateConnectedSendingContent Class Reference
Public Member Functions
StateConnectedSendingContent (ConnectionSerial &connection, size_t contentSize)
Public Member Functions inherited from services::ConnectionSerial::StateSending
StateSending (ConnectionSerial &connection)
virtual void EvaluatePendingSend () override
virtual void Reset () override
Public Member Functions inherited from services::ConnectionSerial::StateConnected
StateConnected (ConnectionSerial &connection)
virtual void AckReceived () override
virtual void SizeRequestReceived () override
virtual void SizeResponseRequestReceived (size_t size) override
virtual void SizeResponseReceived (size_t size) override
virtual size_t ContentReceived (infra::ConstByteRange receivedRange) override
virtual void SizeUpdateReceived (size_t size) override
virtual void AccumulateWindowUpdateSize (size_t size) override
Public Member Functions inherited from services::ConnectionSerial::State
State (ConnectionSerial &connection)
virtual ~State ()=default
Private Member Functions
void SendContentWithSize (size_t size)
void SendPartialContent (infra::ByteRange firstEscapeLessRange, size_t rawContentSize)
void SendEscapedContent ()
Private Attributes
MessageHeader contentMsgHeader = MessageHeader(MessageType::Content)
size_t partialContentSizeBeingSent = 0
std::array< uint8_t, 2 > escapedRange = {{ 0xf9, 0 }}
Additional Inherited Members
Protected Member Functions inherited from services::ConnectionSerial::StateSending
void GoIdle ()
Protected Member Functions inherited from services::ConnectionSerial::StateConnected
bool IsEscapedByte (uint8_t byte) const
Protected Attributes inherited from services::ConnectionSerial::StateSending
bool resetAfterSend = false
Protected Attributes inherited from services::ConnectionSerial::StateConnected
infra::ByteRange & sendBuffer
Protected Attributes inherited from services::ConnectionSerial::State
ConnectionSerial & connection
hal::SerialCommunication & serialCommunication
Detailed Description
Definition at line 263 of file ConnectionSerial.hpp.
Constructor & Destructor Documentation
StateConnectedSendingContent()
services::ConnectionSerial::StateConnectedSendingContent::StateConnectedSendingContent (ConnectionSerial & connection, size_t contentSize)
Definition at line 687 of file ConnectionSerial.cpp.
References SendContentWithSize().
         : StateSending(connection)
     {
         SendContentWithSize(contentSize);
     }
Member Function Documentation
SendContentWithSize()
void services::ConnectionSerial::StateConnectedSendingContent::SendContentWithSize (size_t size) private
Definition at line 490 of file ConnectionSerial.cpp.
References services::ConnectionSerial::MessageHeader::HeaderSize, hal::SerialCommunication::SendData(), and services::ConnectionSerial::serialCommunication.
Referenced by StateConnectedSendingContent().
     {
         connection.totalContentSizeToSend = size;
         contentMsgHeader.SetSize(size);
         connection.peerBufferSize -= size + MessageHeader::HeaderSize;
         serialCommunication.SendData(contentMsgHeader.Range(), [this]()
         {
             SendEscapedContent();
         });
     }
SendEscapedContent()
void services::ConnectionSerial::StateConnectedSendingContent::SendEscapedContent () private
Definition at line 502 of file ConnectionSerial.cpp.
References infra::MemoryRange< T >::front(), infra::Head(), services::ConnectionSerial::sendBuffer, and infra::MemoryRange< T >::size().
     {
         size_t firstEscapedByte = 0;
         while (firstEscapedByte < connection.totalContentSizeToSend && !IsEscapedByte(sendBuffer[firstEscapedByte]))
             firstEscapedByte++;
         if (firstEscapedByte == 0)
         {
             escapedRange[1] = sendBuffer.front();
             SendPartialContent(escapedRange, 1);
         }
         else
         {
             infra::ByteRange firstEscapeLessRange = infra::Head(sendBuffer, firstEscapedByte);
             SendPartialContent(firstEscapeLessRange, firstEscapeLessRange.size());
         }
     }
SendPartialContent()
void services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent (infra::ByteRange firstEscapeLessRange, size_t rawContentSize) private
Definition at line 520 of file ConnectionSerial.cpp.
References infra::MemoryRange< T >::empty(), services::ConnectionSerial::StateConnected::Reset(), services::ConnectionSerial::sendBuffer, hal::SerialCommunication::SendData(), services::ConnectionSerial::serialCommunication, infra::MemoryRange< T >::size(), and infra::Tail().
     {
         partialContentSizeBeingSent = range.size();
         serialCommunication.SendData(range, [this, rawContentSize]()
         {
             sendBuffer = infra::Tail(sendBuffer, sendBuffer.size() - rawContentSize);
             connection.totalContentSizeToSend -= partialContentSizeBeingSent;
             if (connection.totalContentSizeToSend == 0)
             {
                 if (sendBuffer.empty())
                     connection.SendStreamAllocatable();
                 if (!resetAfterSend)
                     GoIdle();
                 else
                     StateConnected::Reset();
             }
             else
                 SendEscapedContent();
         });
     }
Member Data Documentation
contentMsgHeader
MessageHeader services::ConnectionSerial::StateConnectedSendingContent::contentMsgHeader = MessageHeader(MessageType::Content) private
Definition at line 275 of file ConnectionSerial.hpp.
escapedRange
std::array<uint8_t, 2> services::ConnectionSerial::StateConnectedSendingContent::escapedRange = {{ 0xf9, 0 }} private
Definition at line 277 of file ConnectionSerial.hpp.
partialContentSizeBeingSent
size_t services::ConnectionSerial::StateConnectedSendingContent::partialContentSizeBeingSent = 0 private
Definition at line 276 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp