EMil: TestBoundedDeque.cpp File Reference
TestBoundedDeque.cpp File Reference
Functions
TEST (BoundedDequeTest, TestConstructedEmpty)
TEST (BoundedDequeTest, TestConstructionWith2Elements)
TEST (BoundedDequeTest, TestConstructionWithRange)
TEST (BoundedDequeTest, TestConstructionWithInitalizerList)
TEST (BoundedDequeTest, TestCopyConstruction)
TEST (BoundedDequeTest, TestCopyConstructionWrapped)
TEST (BoundedDequeTest, TestMoveConstruction)
TEST (BoundedDequeTest, TestMoveConstructionWrapped)
TEST (BoundedDequeTest, TestAssignment)
TEST (BoundedDequeTest, TestSelfAssignment)
TEST (BoundedDequeTest, TestAssignmentWrapped)
TEST (BoundedDequeTest, TestAssignmentInitializerList)
TEST (BoundedDequeTest, TestAssignmentInitializerListWrapped)
TEST (BoundedDequeTest, TestMove)
TEST (BoundedDequeTest, TestMoveWrapped)
TEST (BoundedDequeTest, TestBeginAndEnd)
TEST (BoundedDequeTest, TestBeginAndEndWrapped)
TEST (BoundedDequeTest, TestContiguousRange)
TEST (BoundedDequeTest, TestResizeBigger)
TEST (BoundedDequeTest, TestResizeSmaller)
TEST (BoundedDequeTest, TestFull)
TEST (BoundedDequeTest, TestFullWrapped)
TEST (BoundedDequeTest, TestFront)
TEST (BoundedDequeTest, TestFrontWrapped)
TEST (BoundedDequeTest, TestBack)
TEST (BoundedDequeTest, TestBackWrapped)
TEST (BoundedDequeTest, TestAssignRange)
TEST (BoundedDequeTest, TestAssignN)
TEST (BoundedDequeTest, TestAssignInitializerList)
TEST (BoundedDequeTest, TestPushFront)
TEST (BoundedDequeTest, TestPopFront)
TEST (BoundedDequeTest, TestPopWrapped)
TEST (BoundedDequeTest, TestPushBack)
TEST (BoundedDequeTest, TestPushBackWrapped)
TEST (BoundedDequeTest, TestPopBack)
TEST (BoundedDequeTest, TestPopBackWrapped)
TEST (BoundedDequeTest, TestInsertOneLvalueInTheMiddle)
TEST (BoundedDequeTest, TestInsertOneRvalueInTheMiddle)
TEST (BoundedDequeTest, TestInsertOneAtTheEnd)
TEST (BoundedDequeTest, TestInsertManyInTheMiddle)
TEST (BoundedDequeTest, TestInsertManyInTheMiddleWrapped)
TEST (BoundedDequeTest, TestInsertManyAtTheFront)
TEST (BoundedDequeTest, TestInsertRange)
TEST (BoundedDequeTest, TestInsertInitializerList)
TEST (BoundedDequeTest, TestInsertMove)
TEST (BoundedDequeTest, TestEraseOne)
TEST (BoundedDequeTest, TestEraseRange)
TEST (BoundedDequeTest, TestSwap)
TEST (BoundedDequeTest, TestSwapWrapped)
TEST (BoundedDequeTest, TestSwapDifferentSizes)
TEST (BoundedDequeTest, TestSwapDifferentSizesWrapped)
TEST (BoundedDequeTest, TestClear)
TEST (BoundedDequeTest, TestClearWithNonTrivialObject)
TEST (BoundedDequeTest, TestEmplace)
TEST (BoundedDequeTest, TestEmplaceWrapped)
TEST (BoundedDequeTest, IteratorCopyConstruct)
TEST (BoundedDequeTest, IteratorArrow)
TEST (BoundedDequeTest, IteratorRandomAccess)
TEST (BoundedDequeTest, IteratorPostInc)
TEST (BoundedDequeTest, IteratorPostDec)
TEST (BoundedDequeTest, TestEquals)
TEST (BoundedDequeTest, TestEqualsWrapped)
TEST (BoundedDequeTest, TestUnequals)
TEST (BoundedDequeTest, TestLessThan)
TEST (BoundedDequeTest, TestLessThanWrapped)
TEST (BoundedDequeTest, TestGreaterThan)
TEST (BoundedDequeTest, TestLessThanOrEqual)
TEST (BoundedDequeTest, TestGreaterThanOrEqual)
TEST (BoundedDequeTest, IteratorComparison)
Function Documentation
TEST() [1/69]
TEST (BoundedDequeTest , TestConstructedEmpty)
Definition at line 6 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque;
     EXPECT_TRUE(deque.empty());
     EXPECT_FALSE(deque.full());
     EXPECT_EQ(0, deque.size());
     EXPECT_EQ(5, deque.max_size());
 }
TEST() [2/69]
TEST (BoundedDequeTest , TestConstructionWith2Elements)
Definition at line 16 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     EXPECT_FALSE(deque.empty());
     EXPECT_FALSE(deque.full());
     EXPECT_EQ(2, deque.size());
     EXPECT_EQ(4, deque[0]);
     EXPECT_EQ(4, deque[1]);
 }
TEST() [3/69]
TEST (BoundedDequeTest , TestConstructionWithRange)
Definition at line 28 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(0, deque[0]);
     EXPECT_EQ(1, deque[1]);
     EXPECT_EQ(2, deque[2]);
 }
TEST() [4/69]
TEST (BoundedDequeTest , TestConstructionWithInitalizerList)
Definition at line 40 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque({ 0, 1, 2 });
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(0, deque[0]);
     EXPECT_EQ(1, deque[1]);
     EXPECT_EQ(2, deque[2]);
 }
TEST() [5/69]
TEST (BoundedDequeTest , TestCopyConstruction)
Definition at line 51 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> original(std::size_t(2), 4);
     infra::BoundedDeque<int>::WithMaxSize<5> copy(original);
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(4, copy[0]);
     EXPECT_EQ(4, copy[1]);
 }
TEST() [6/69]
TEST (BoundedDequeTest , TestCopyConstructionWrapped)
Definition at line 61 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> original(std::size_t(1), 4);
     original.push_front(3);
     infra::BoundedDeque<int>::WithMaxSize<5> copy(original);
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(3, copy[0]);
     EXPECT_EQ(4, copy[1]);
 }
TEST() [7/69]
TEST (BoundedDequeTest , TestMoveConstruction)
Definition at line 73 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_back(2);
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> copy(std::move(original));
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy[0].x);
 }
TEST() [8/69]
TEST (BoundedDequeTest , TestMoveConstructionWrapped)
Definition at line 83 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_back(2);
     original.emplace_front(1);
     original.emplace_front(3);
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> copy(std::move(original));
     EXPECT_EQ(3, copy.size());
     EXPECT_EQ(3, copy[0].x);
     EXPECT_EQ(1, copy[1].x);
     EXPECT_EQ(2, copy[2].x);
 }
TEST() [9/69]
TEST (BoundedDequeTest , TestAssignment)
Definition at line 97 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> original(std::size_t(2), 4);
     infra::BoundedDeque<int>::WithMaxSize<5> copy;
     copy = original;
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(4, copy[0]);
 }
TEST() [10/69]
TEST (BoundedDequeTest , TestSelfAssignment)
Definition at line 107 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> original(std::size_t(2), 4);
     original = original;
     EXPECT_EQ(2, original.size());
     EXPECT_EQ(4, original[0]);
 }
TEST() [11/69]
TEST (BoundedDequeTest , TestAssignmentWrapped)
Definition at line 116 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> original(std::size_t(1), 4);
     original.push_front(3);
     infra::BoundedDeque<int>::WithMaxSize<5> copy;
     copy = original;
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(3, copy[0]);
     EXPECT_EQ(4, copy[1]);
 }
TEST() [12/69]
TEST (BoundedDequeTest , TestAssignmentInitializerList)
Definition at line 128 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque({ 1, 2, 3 });
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(1, deque[0]);
     EXPECT_EQ(2, deque[1]);
 }
TEST() [13/69]
TEST (BoundedDequeTest , TestAssignmentInitializerListWrapped)
Definition at line 137 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), infra::BoundedDeque< T >::push_front(), and infra::BoundedDeque< T >::size().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> dequeStorage(std::size_t(1), 4);
     infra::BoundedDeque<int>& deque = dequeStorage;
     deque.push_front(3);
     deque = { 1, 2 };
     EXPECT_EQ(2, deque.size());
     EXPECT_EQ(1, deque[0]);
     EXPECT_EQ(2, deque[1]);
 }
TEST() [14/69]
TEST (BoundedDequeTest , TestMove)
Definition at line 149 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_back(2);
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> copy;
     copy = std::move(original);
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy[0].x);
 }
TEST() [15/69]
TEST (BoundedDequeTest , TestMoveWrapped)
Definition at line 160 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_back(2);
     original.emplace_front(1);
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> copy;
     copy = std::move(original);
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(1, copy[0].x);
     EXPECT_EQ(2, copy[1].x);
 }
TEST() [16/69]
TEST (BoundedDequeTest , TestBeginAndEnd)
Definition at line 173 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(deque.end(), deque.begin() + 3);
     EXPECT_EQ(deque.cbegin(), deque.begin());
     EXPECT_EQ(deque.cend(), deque.end());
     EXPECT_EQ(deque.rend(), deque.rbegin() + 3);
     EXPECT_EQ(0, *deque.begin());
     EXPECT_EQ(2, *deque.rbegin());
     EXPECT_EQ(2, *deque.crbegin());
     EXPECT_EQ(2, *(deque.end() - 1));
     EXPECT_EQ(0, *(deque.rend() - 1));
     EXPECT_EQ(0, *(deque.crend() - 1));
 }
TEST() [17/69]
TEST (BoundedDequeTest , TestBeginAndEndWrapped)
Definition at line 191 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     deque.push_front(-1);
     EXPECT_EQ(deque.end(), deque.begin() + 4);
     EXPECT_EQ(deque.cbegin(), deque.begin());
     EXPECT_EQ(deque.cend(), deque.end());
     EXPECT_EQ(deque.rend(), deque.rbegin() + 4);
     EXPECT_EQ(-1, *deque.begin());
     EXPECT_EQ(2, *deque.rbegin());
     EXPECT_EQ(2, *(deque.end() - 1));
     EXPECT_EQ(-1, *(deque.rend() - 1));
 }
TEST() [18/69]
TEST (BoundedDequeTest , TestContiguousRange)
Definition at line 208 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> emptyDeque;
     EXPECT_EQ(0, emptyDeque.contiguous_range(emptyDeque.begin()).size());
     EXPECT_EQ(0, static_cast<const infra::BoundedDeque<int>&>(emptyDeque).contiguous_range(emptyDeque.begin()).size());
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(3, deque.contiguous_range(deque.begin()).size());
     EXPECT_EQ(0, deque.contiguous_range(deque.begin()).front());
     deque.push_front(-1);
     deque.push_front(-2);
     EXPECT_EQ(2, static_cast<const infra::BoundedDeque<int>&>(deque).contiguous_range(deque.begin()).size());
     EXPECT_EQ(-2, static_cast<const infra::BoundedDeque<int>&>(deque).contiguous_range(deque.begin()).front());
     EXPECT_EQ(1, static_cast<const infra::BoundedDeque<int>&>(deque).contiguous_range(deque.begin() + 1).size());
     EXPECT_EQ(-1, static_cast<const infra::BoundedDeque<int>&>(deque).contiguous_range(deque.begin() + 1).front());
     EXPECT_EQ(3, static_cast<const infra::BoundedDeque<int>&>(deque).contiguous_range(deque.begin() + 2).size());
     EXPECT_EQ(0, static_cast<const infra::BoundedDeque<int>&>(deque).contiguous_range(deque.begin() + 2).front());
 }
TEST() [19/69]
TEST (BoundedDequeTest , TestResizeBigger)
Definition at line 231 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.resize(3, 5);
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(4, deque[0]);
     EXPECT_EQ(5, deque[2]);
 }
TEST() [20/69]
TEST (BoundedDequeTest , TestResizeSmaller)
Definition at line 241 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.resize(1, 5);
     EXPECT_EQ(1, deque.size());
     EXPECT_EQ(4, deque[0]);
 }
TEST() [21/69]
TEST (BoundedDequeTest , TestFull)
Definition at line 250 of file TestBoundedDeque.cpp.
References EXPECT_TRUE().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(5), 4);
     EXPECT_TRUE(deque.full());
 }
TEST() [22/69]
TEST (BoundedDequeTest , TestFullWrapped)
Definition at line 257 of file TestBoundedDeque.cpp.
References EXPECT_TRUE().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(5), 4);
     deque.pop_front();
     deque.push_back(1);
     EXPECT_TRUE(deque.full());
 }
TEST() [23/69]
TEST (BoundedDequeTest , TestFront)
Definition at line 266 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(0, deque.front());
     EXPECT_EQ(0, const_cast<const infra::BoundedDeque<int>::WithMaxSize<5>&>(deque).front());
 }
TEST() [24/69]
TEST (BoundedDequeTest , TestFrontWrapped)
Definition at line 275 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     deque.push_front(-1);
     EXPECT_EQ(-1, deque.front());
 }
TEST() [25/69]
TEST (BoundedDequeTest , TestBack)
Definition at line 284 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(2, deque.back());
     EXPECT_EQ(2, const_cast<const infra::BoundedDeque<int>::WithMaxSize<5>&>(deque).back());
 }
TEST() [26/69]
TEST (BoundedDequeTest , TestBackWrapped)
Definition at line 293 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<3> deque(range, range + 3);
     deque.pop_front();
     deque.push_back(5);
     EXPECT_EQ(5, deque.back());
 }
TEST() [27/69]
TEST (BoundedDequeTest , TestAssignRange)
Definition at line 303 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     int otherRange[2] = { 4, 5 };
     deque.assign(otherRange, otherRange + 2);
     EXPECT_EQ(2, deque.size());
     EXPECT_EQ(4, deque[0]);
     EXPECT_EQ(5, deque[1]);
 }
TEST() [28/69]
TEST (BoundedDequeTest , TestAssignN)
Definition at line 316 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     deque.assign(std::size_t(2), 4);
     EXPECT_EQ(2, deque.size());
     EXPECT_EQ(4, deque[0]);
     EXPECT_EQ(4, deque[1]);
 }
TEST() [29/69]
TEST (BoundedDequeTest , TestAssignInitializerList)
Definition at line 328 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque({ 0, 1, 2 });
     deque.push_front(-1);
     deque.assign({ 4, 5, 6 });
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(4, deque[0]);
     EXPECT_EQ(5, deque[1]);
     EXPECT_EQ(6, deque[2]);
 }
TEST() [30/69]
TEST (BoundedDequeTest , TestPushFront)
Definition at line 340 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.push_front(1);
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(1, deque[0]);
 }
TEST() [31/69]
TEST (BoundedDequeTest , TestPopFront)
Definition at line 349 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.pop_front();
     EXPECT_EQ(1, deque.size());
     EXPECT_EQ(4, deque[0]);
 }
TEST() [32/69]
TEST (BoundedDequeTest , TestPopWrapped)
Definition at line 358 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.push_front(1);
     deque.push_front(0);
     deque.pop_front();
     EXPECT_EQ(3, deque.size());
     EXPECT_EQ(1, deque[0]);
 }
TEST() [33/69]
TEST (BoundedDequeTest , TestPushBack)
Definition at line 370 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque;
     deque.push_back(2);
     deque.push_back(3);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque;
     expectedDeque.push_back(2);
     expectedDeque.push_back(3);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [34/69]
TEST (BoundedDequeTest , TestPushBackWrapped)
Definition at line 383 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque;
     for (auto i = 0; i < 5; ++i)
         deque.push_back(1);
     deque.pop_front();
     deque.pop_front();
     deque.pop_front();
     deque.pop_front();
     deque.push_back(2);
     deque.push_back(3);
     EXPECT_EQ(1, deque[0]);
     EXPECT_EQ(2, deque[1]);
     EXPECT_EQ(3, deque[2]);
 }
TEST() [35/69]
TEST (BoundedDequeTest , TestPopBack)
Definition at line 402 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.pop_back();
     EXPECT_EQ(1, deque.size());
     EXPECT_EQ(4, deque[0]);
 }
TEST() [36/69]
TEST (BoundedDequeTest , TestPopBackWrapped)
Definition at line 411 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(1), 4);
     deque.push_front(1);
     deque.pop_back();
     EXPECT_EQ(1, deque.size());
     EXPECT_EQ(1, deque[0]);
 }
TEST() [37/69]
TEST (BoundedDequeTest , TestInsertOneLvalueInTheMiddle)
Definition at line 422 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     int i = 5;
     EXPECT_EQ(5, *deque.insert(deque.begin() + 1, i));
     int expectedRange[4] = { 0, 5, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 4);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [38/69]
TEST (BoundedDequeTest , TestInsertOneRvalueInTheMiddle)
Definition at line 435 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(5, *deque.insert(deque.begin() + 1, 5));
     int expectedRange[4] = { 0, 5, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 4);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [39/69]
TEST (BoundedDequeTest , TestInsertOneAtTheEnd)
Definition at line 447 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(5, *deque.insert(deque.end(), 5));
     int expectedRange[4] = { 0, 1, 2, 5 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 4);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [40/69]
TEST (BoundedDequeTest , TestInsertManyInTheMiddle)
Definition at line 459 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(5, *deque.insert(deque.begin() + 2, std::size_t(2), 5));
     int expectedRange[5] = { 0, 1, 5, 5, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 5);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [41/69]
TEST (BoundedDequeTest , TestInsertManyInTheMiddleWrapped)
Definition at line 471 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque;
     deque.push_front(1);
     deque.push_front(0);
     deque.push_back(2);
     EXPECT_EQ(5, *deque.insert(deque.begin() + 1, std::size_t(2), 5));
     int expectedRange[5] = { 0, 5, 5, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 5);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [42/69]
TEST (BoundedDequeTest , TestInsertManyAtTheFront)
Definition at line 485 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(5, *deque.insert(deque.begin(), std::size_t(2), 5));
     int expectedRange[5] = { 5, 5, 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 5);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [43/69]
TEST (BoundedDequeTest , TestInsertRange)
Definition at line 497 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     int insertRange[2] = { 5, 6 };
     EXPECT_EQ(5, *deque.insert(deque.begin() + 2, insertRange, insertRange + 2));
     int expectedRange[5] = { 0, 1, 5, 6, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 5);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [44/69]
TEST (BoundedDequeTest , TestInsertInitializerList)
Definition at line 510 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     EXPECT_EQ(5, *deque.insert(deque.begin() + 2, { 5, 5 }));
     int expectedRange[5] = { 0, 1, 5, 5, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 5);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [45/69]
TEST (BoundedDequeTest , TestInsertMove)
Definition at line 522 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> deque;
     deque.emplace_back(0);
     deque.emplace_back(1);
     deque.emplace_back(2);
     EXPECT_EQ(5, deque.insert(deque.begin() + 1, infra::MoveConstructible(5))->x);
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> expectedDeque;
     expectedDeque.emplace_back(0);
     expectedDeque.emplace_back(5);
     expectedDeque.emplace_back(1);
     expectedDeque.emplace_back(2);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [46/69]
TEST (BoundedDequeTest , TestEraseOne)
Definition at line 539 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     deque.erase(deque.begin() + 1);
     int expectedRange[5] = { 0, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 2);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [47/69]
TEST (BoundedDequeTest , TestEraseRange)
Definition at line 551 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range, range + 3);
     deque.erase(deque.begin() + 1, deque.begin() + 3);
     int expectedRange[5] = { 0 };
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque(expectedRange, expectedRange + 1);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [48/69]
TEST (BoundedDequeTest , TestSwap)
Definition at line 563 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque2(range2, range2 + 3);
     swap(deque1, deque2);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque1(range2, range2 + 3);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque2(range1, range1 + 3);
     EXPECT_EQ(expectedDeque1, deque1);
     EXPECT_EQ(expectedDeque2, deque2);
 }
TEST() [49/69]
TEST (BoundedDequeTest , TestSwapWrapped)
Definition at line 578 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2 };
     int range2[3] = { 3, 4, 5 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     infra::BoundedDeque<int>::WithMaxSize<5> deque2;
     deque2.push_front(range2[0]);
     deque2.push_back(range2[1]);
     deque2.push_back(range2[2]);
     swap(deque1, deque2);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque1(range2, range2 + 3);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque2(range1, range1 + 3);
     EXPECT_EQ(expectedDeque1, deque1);
     EXPECT_EQ(expectedDeque2, deque2);
 }
TEST() [50/69]
TEST (BoundedDequeTest , TestSwapDifferentSizes)
Definition at line 596 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     int range2[2] = { 3, 4 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque2(range2, range2 + 2);
     swap(deque1, deque2);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque1(range2, range2 + 2);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque2(range1, range1 + 3);
     EXPECT_EQ(expectedDeque1, deque1);
     EXPECT_EQ(expectedDeque2, deque2);
 }
TEST() [51/69]
TEST (BoundedDequeTest , TestSwapDifferentSizesWrapped)
Definition at line 611 of file TestBoundedDeque.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[2] = { 0, 1 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 2);
     int range2[3] = { 2, 3, 4 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque2;
     deque2.push_front(range2[1]);
     deque2.push_front(range2[0]);
     deque2.push_back(range2[2]);
     swap(deque1, deque2);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque1(range2, range2 + 3);
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque2(range1, range1 + 2);
     EXPECT_EQ(expectedDeque1, deque1);
     EXPECT_EQ(expectedDeque2, deque2);
 }
TEST() [52/69]
TEST (BoundedDequeTest , TestClear)
Definition at line 629 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> deque(std::size_t(2), 4);
     deque.clear();
     infra::BoundedDeque<int>::WithMaxSize<5> expectedDeque;
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [53/69]
TEST (BoundedDequeTest , TestClearWithNonTrivialObject)
Definition at line 638 of file TestBoundedDeque.cpp.
References EXPECT_TRUE().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> deque;
     deque.emplace_back(4);
     deque.clear();
     EXPECT_TRUE(deque.empty());
 }
TEST() [54/69]
TEST (BoundedDequeTest , TestEmplace)
Definition at line 647 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> deque;
     deque.emplace_back(2);
     deque.emplace_back(3);
     deque.emplace(deque.begin() + 1, 4);
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> expectedDeque;
     expectedDeque.emplace_back(2);
     expectedDeque.emplace_back(4);
     expectedDeque.emplace_back(3);
     EXPECT_EQ(expectedDeque, deque);
 }
TEST() [55/69]
TEST (BoundedDequeTest , TestEmplaceWrapped)
Definition at line 662 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<infra::MoveConstructible>::WithMaxSize<5> deque;
     for (auto i = 0; i < 5; ++i)
         deque.emplace_back(1);
     deque.pop_front();
     deque.pop_front();
     deque.pop_front();
     deque.pop_front();
     deque.emplace_back(2);
     deque.emplace_back(3);
     deque.emplace(deque.begin() + 1, 4);
     EXPECT_EQ(infra::MoveConstructible(1), deque[0]);
     EXPECT_EQ(infra::MoveConstructible(4), deque[1]);
     EXPECT_EQ(infra::MoveConstructible(2), deque[2]);
     EXPECT_EQ(infra::MoveConstructible(3), deque[3]);
 }
TEST() [56/69]
TEST (BoundedDequeTest , IteratorCopyConstruct)
Definition at line 682 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedDeque<int>::iterator i(list.begin());
     EXPECT_EQ(4, *i);
 }
TEST() [57/69]
TEST (BoundedDequeTest , IteratorArrow)
Definition at line 690 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> list(std::size_t(1), 4);
     EXPECT_EQ(4, *(list.begin().operator->()));
 }
TEST() [58/69]
TEST (BoundedDequeTest , IteratorRandomAccess)
Definition at line 697 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedDeque<int>::iterator i(list.begin());
     EXPECT_EQ(4, i[0]);
 }
TEST() [59/69]
TEST (BoundedDequeTest , IteratorPostInc)
Definition at line 705 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedDeque<int>::iterator i(list.begin());
     EXPECT_EQ(4, *i++);
 }
TEST() [60/69]
TEST (BoundedDequeTest , IteratorPostDec)
Definition at line 713 of file TestBoundedDeque.cpp.
References EXPECT_EQ().
 {
     infra::BoundedDeque<int>::WithMaxSize<5> list(std::size_t(2), 4);
     infra::BoundedDeque<int>::iterator i(std::next(list.begin()));
     EXPECT_EQ(4, *i--);
     EXPECT_EQ(list.begin(), i);
 }
TEST() [61/69]
TEST (BoundedDequeTest , TestEquals)
Definition at line 722 of file TestBoundedDeque.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque2(range2, range2 + 3);
     int range3[2] = { 0, 1 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(deque1 == deque1);
     EXPECT_FALSE(deque1 == deque2);
     EXPECT_FALSE(deque1 == deque3);
     EXPECT_FALSE(deque3 == deque1);
 }
TEST() [62/69]
TEST (BoundedDequeTest , TestEqualsWrapped)
Definition at line 737 of file TestBoundedDeque.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     infra::BoundedDeque<int>::WithMaxSize<5> deque2;
     deque2.push_front(range1[0]);
     deque2.push_back(range1[1]);
     deque2.push_back(range1[2]);
     EXPECT_TRUE(deque1 == deque2);
 }
TEST() [63/69]
TEST (BoundedDequeTest , TestUnequals)
Definition at line 749 of file TestBoundedDeque.cpp.
References EXPECT_FALSE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     EXPECT_FALSE(deque1 != deque1);
 }
TEST() [64/69]
TEST (BoundedDequeTest , TestLessThan)
Definition at line 757 of file TestBoundedDeque.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     int range2[3] = { 0, 4, 5 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque2(range2, range2 + 3);
     int range3[2] = { 0, 1 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(deque1 < deque2);
     EXPECT_FALSE(deque1 < deque3);
     EXPECT_FALSE(deque1 < deque1);
 }
TEST() [65/69]
TEST (BoundedDequeTest , TestLessThanWrapped)
Definition at line 771 of file TestBoundedDeque.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     int range2[3] = { 0, 4, 5 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque2;
     deque2.push_front(0);
     deque2.push_back(4);
     deque2.push_back(5);
     int range3[2] = { 0, 1 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(deque1 < deque2);
     EXPECT_FALSE(deque1 < deque3);
     EXPECT_FALSE(deque1 < deque1);
 }
TEST() [66/69]
TEST (BoundedDequeTest , TestGreaterThan)
Definition at line 788 of file TestBoundedDeque.cpp.
References EXPECT_FALSE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     EXPECT_FALSE(deque1 > deque1);
 }
TEST() [67/69]
TEST (BoundedDequeTest , TestLessThanOrEqual)
Definition at line 796 of file TestBoundedDeque.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     EXPECT_TRUE(deque1 <= deque1);
 }
TEST() [68/69]
TEST (BoundedDequeTest , TestGreaterThanOrEqual)
Definition at line 804 of file TestBoundedDeque.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque1(range1, range1 + 3);
     EXPECT_TRUE(deque1 >= deque1);
 }
TEST() [69/69]
TEST (BoundedDequeTest , IteratorComparison)
Definition at line 812 of file TestBoundedDeque.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedDeque<int>::WithMaxSize<5> deque(range1, range1 + 3);
     EXPECT_TRUE(deque.begin() < deque.end());
     EXPECT_FALSE(deque.begin() > deque.end());
     EXPECT_TRUE(deque.begin() <= deque.end());
     EXPECT_FALSE(deque.begin() >= deque.end());
 }