EMil: services::ConnectionSerial Class Reference
services::ConnectionSerial Class Reference
#include <ConnectionSerial.hpp>
Classes
class MessageHeader
class SerialConnectionStreamReader
class State
class StateConnected
class StateConnectedIdle
class StateConnectedSendingContent
class StateInit
class StateInitSizeRequest
class StateInitSizeResponse
class StateInitSizeResponseRequest
class StateSending
class StateSendingUpdate
class StreamWriterWithCyclicBuffer
Public Types
template<std::size_t Max>
using WithStorage = infra::WithStorage< infra::WithStorage< infra::WithStorage< ConnectionSerial, std::array< uint8_t, Max > >, std::array< uint8_t, Max > >, infra::BoundedDeque< uint8_t >::WithMaxSize< Max > >
Public Member Functions
ConnectionSerial (infra::ByteRange sendBuffer, infra::ByteRange parseBuffer, infra::BoundedDeque< uint8_t > &receivedDataQueue, hal::SerialCommunication &serialCommunication, size_t minUpdateSize=MessageHeader::HeaderSize+1)
ConnectionSerial (const ConnectionSerial &other)=delete
ConnectionSerial & operator= (const ConnectionSerial &other)=delete
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Protected Attributes
size_t pendingSendStream = 0
Private Types
enum MessageType : uint8_t {
MessageType::Escape = 0xf9, MessageType::SizeRequest = 0xfa, MessageType::SizeResponse = 0xfb, MessageType::SizeResponseRequest = 0xfc,
MessageType::Content = 0xfd, MessageType::SizeUpdate = 0xfe
}
Private Member Functions
void TryProcessHeader ()
void TryConstructHeader ()
void ProcessHeader ()
void SendStreamFilled (infra::ByteRange data)
void DataReceived ()
void ResetConnection ()
void SendStreamAllocatable ()
void InitCompleted ()
void AllocatedSendStream ()
void NotifyObserverDataReceived ()
size_t ReceiveBufferSize () const
void GoStateInitSizeRequest ()
void GoStateInitSizeResponseRequest ()
void GoStateInitSizeResponse ()
void GoStateConnectedIdle ()
void GoStateConnectedSendingContent (size_t size)
void GoStateSendingUpdate ()
Private Attributes
size_t contentToReceive = 0
infra::Optional< MessageHeader > messageHeader
infra::BoundedDeque< uint8_t > & receivedDataQueue
infra::ByteRange sendBuffer
infra::ByteRange contentReadyForSend
infra::SharedOptional< StreamWriterWithCyclicBuffer > sendStream
hal::SerialCommunication & serialCommunication
infra::QueueForOneReaderOneIrqWriter< uint8_t > receiveQueue
infra::Optional< SerialConnectionStreamReader > receivedDataReader
infra::ClaimableResource serialCommunicationResource
infra::PolymorphicVariant< State, StateInitSizeRequest, StateInitSizeResponseRequest, StateInitSizeResponse, StateConnectedIdle, StateConnectedSendingContent, StateSendingUpdate > state
bool sendStreamAvailable = true
size_t minUpdateSize
bool observerNotified = false
size_t peerBufferSize
infra::Optional< size_t > accumulatedWindowSizeUpdate
bool updateInProgress = false
bool isEscapeSeen = false
size_t totalContentSizeToSend = 0
Additional Inherited Members
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Detailed Description
Definition at line 17 of file ConnectionSerial.hpp.
Member Typedef Documentation
WithStorage
template<std::size_t Max> using services::ConnectionSerial::WithStorage = infra::WithStorage<infra::WithStorage<infra::WithStorage<ConnectionSerial , std::array<uint8_t, Max> > , std::array<uint8_t, Max> > , infra::BoundedDeque<uint8_t>::WithMaxSize<Max> >
Definition at line 28 of file ConnectionSerial.hpp.
Member Enumeration Documentation
MessageType
enum services::ConnectionSerial::MessageType : uint8_t strong private
Enumerator
Escape
SizeRequest
SizeResponse
SizeResponseRequest
Content
SizeUpdate
Definition at line 63 of file ConnectionSerial.hpp.
                                : uint8_t
         {
             Escape = 0xf9, // f9-fe in data are escaped
             SizeRequest = 0xfa,
             SizeResponse = 0xfb,
             SizeResponseRequest = 0xfc,
             Content = 0xfd,
             SizeUpdate = 0xfe
         };
Constructor & Destructor Documentation
ConnectionSerial() [1/2]
services::ConnectionSerial::ConnectionSerial (infra::ByteRange sendBuffer, infra::ByteRange parseBuffer, infra::BoundedDeque< uint8_t > & receivedDataQueue, hal::SerialCommunication & serialCommunication, size_t minUpdateSize = MessageHeader::HeaderSize + 1)
Definition at line 7 of file ConnectionSerial.cpp.
References DataReceived().
         : serialCommunication(serialCommunication)
         , sendBuffer(sendBuffer)
         , receiveQueue(parseBuffer, [this]() { DataReceived(); })
         , receivedDataQueue(receivedDataQueue)
         , state(infra::InPlaceType<StateInitSizeRequest>(), *this)
         , minUpdateSize(std::max(minUpdateSize, MessageHeader::HeaderSize + 1))
     {
         assert(minUpdateSize <= receiveQueue.EmptySize() - MessageHeader::HeaderSize);
         serialCommunication.ReceiveData([this](infra::ConstByteRange data)
         {
             for (uint8_t byte : data)
                 if (!receiveQueue.Full())
                     receiveQueue.AddFromInterrupt(byte);
                 else
                     abort();
         });
     }
ConnectionSerial() [2/2]
services::ConnectionSerial::ConnectionSerial (const ConnectionSerial & other) delete
Member Function Documentation
AbortAndDestroy()
void services::ConnectionSerial::AbortAndDestroy () override virtual
Implements services::Connection.
Definition at line 85 of file ConnectionSerial.cpp.
     {
         std::abort();
     }
AckReceived()
void services::ConnectionSerial::AckReceived () override virtual
Implements services::Connection.
Definition at line 75 of file ConnectionSerial.cpp.
References state.
     {
         state->AckReceived();
     }
AllocatedSendStream()
void services::ConnectionSerial::AllocatedSendStream () private
Definition at line 27 of file ConnectionSerial.cpp.
References infra::Subject< ConnectionObserver >::GetObserver(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), pendingSendStream, infra::EventDispatcherWorker::Schedule(), sendBuffer, sendStream, and sendStreamAvailable.
Referenced by RequestSendStream(), and SendStreamAllocatable().
     {
         sendStreamAvailable = false;
         pendingSendStream = 0;
         infra::EventDispatcher::Instance().Schedule([this]()
         {
             infra::SharedPtr<StreamWriterWithCyclicBuffer> writer = sendStream.Emplace(sendBuffer, *this);
             this->GetObserver().SendStreamAvailable(std::move(writer));
         });
     }
CloseAndDestroy()
void services::ConnectionSerial::CloseAndDestroy () override virtual
Implements services::Connection.
Definition at line 80 of file ConnectionSerial.cpp.
     {
         std::abort();
     }
DataReceived()
void services::ConnectionSerial::DataReceived () private
Definition at line 103 of file ConnectionSerial.cpp.
References infra::QueueForOneReaderOneIrqWriter< T >::Consume(), contentToReceive, infra::QueueForOneReaderOneIrqWriter< T >::ContiguousRange(), infra::QueueForOneReaderOneIrqWriter< T >::Empty(), infra::Head(), receiveQueue, infra::QueueForOneReaderOneIrqWriter< T >::Size(), state, TryConstructHeader(), and TryProcessHeader().
Referenced by ConnectionSerial().
     {
         while (!receiveQueue.Empty())
         {
             if (contentToReceive > 0)
                 receiveQueue.Consume(state->ContentReceived(infra::Head(receiveQueue.ContiguousRange(), std::min(contentToReceive, receiveQueue.Size()))));
             else
             {
                 TryConstructHeader();
                 TryProcessHeader();
             }
             state->EvaluatePendingSend();
         }
     }
GoStateConnectedIdle()
void services::ConnectionSerial::GoStateConnectedIdle () private
Definition at line 198 of file ConnectionSerial.cpp.
References state.
Referenced by InitCompleted().
     {
         state.Emplace<StateConnectedIdle>(*this);
     }
GoStateConnectedSendingContent()
void services::ConnectionSerial::GoStateConnectedSendingContent (size_t size) private
Definition at line 203 of file ConnectionSerial.cpp.
References state.
     {
         state.Emplace<StateConnectedSendingContent>(*this, size);
     }
GoStateInitSizeRequest()
void services::ConnectionSerial::GoStateInitSizeRequest () private
Definition at line 183 of file ConnectionSerial.cpp.
References state.
Referenced by ResetConnection().
     {
         state.Emplace<StateInitSizeRequest>(*this);
     }
GoStateInitSizeResponse()
void services::ConnectionSerial::GoStateInitSizeResponse () private
Definition at line 193 of file ConnectionSerial.cpp.
References state.
     {
         state.Emplace<StateInitSizeResponse>(*this);
     }
GoStateInitSizeResponseRequest()
void services::ConnectionSerial::GoStateInitSizeResponseRequest () private
Definition at line 188 of file ConnectionSerial.cpp.
References state.
     {
         state.Emplace<StateInitSizeResponseRequest>(*this);
     }
GoStateSendingUpdate()
void services::ConnectionSerial::GoStateSendingUpdate () private
Definition at line 208 of file ConnectionSerial.cpp.
References state.
     {
         state.Emplace<StateSendingUpdate>(*this);
     }
InitCompleted()
void services::ConnectionSerial::InitCompleted () private
Definition at line 158 of file ConnectionSerial.cpp.
References GoStateConnectedIdle().
     {
         GoStateConnectedIdle();
     }
MaxSendStreamSize()
std::size_t services::ConnectionSerial::MaxSendStreamSize () const override virtual
Implements services::Connection.
Definition at line 63 of file ConnectionSerial.cpp.
References sendBuffer, and infra::MemoryRange< T >::size().
Referenced by RequestSendStream().
     {
         return sendBuffer.size();
     }
NotifyObserverDataReceived()
void services::ConnectionSerial::NotifyObserverDataReceived () private
Definition at line 39 of file ConnectionSerial.cpp.
References infra::Subject< ConnectionObserver >::GetObserver(), and observerNotified.
     {
         if (!observerNotified)
         {
             observerNotified = true;
             GetObserver().DataReceived();
         }
     }
operator=()
ConnectionSerial& services::ConnectionSerial::operator= (const ConnectionSerial & other) delete
ProcessHeader()
void services::ConnectionSerial::ProcessHeader () private
Definition at line 132 of file ConnectionSerial.cpp.
References Content, contentToReceive, messageHeader, SizeRequest, SizeResponse, SizeResponseRequest, SizeUpdate, and state.
Referenced by TryProcessHeader().
     {
         switch (messageHeader->Type())
         {
         case MessageType::SizeRequest:
             state->SizeRequestReceived();
             break;
         case MessageType::SizeResponseRequest:
             state->SizeResponseRequestReceived(messageHeader->Size());
             break;
         case MessageType::SizeResponse:
             state->SizeResponseReceived(messageHeader->Size());
             break;
         case MessageType::Content:
             contentToReceive = messageHeader->Size();
             break;
         case MessageType::SizeUpdate:
             state->SizeUpdateReceived(messageHeader->Size());
             break;
         }
     }
ReceiveBufferSize()
size_t services::ConnectionSerial::ReceiveBufferSize () const private
Definition at line 48 of file ConnectionSerial.cpp.
References infra::QueueForOneReaderOneIrqWriter< T >::EmptySize(), and receiveQueue.
     {
         return receiveQueue.EmptySize();
     }
ReceiveStream()
infra::SharedPtr< infra::StreamReaderWithRewinding > services::ConnectionSerial::ReceiveStream () override virtual
Implements services::Connection.
Definition at line 68 of file ConnectionSerial.cpp.
References observerNotified, receivedDataQueue, receivedDataReader, and infra::UnOwnedSharedPtr().
     {
         observerNotified = false;
         receivedDataReader.Emplace(receivedDataQueue);
         return infra::UnOwnedSharedPtr(*receivedDataReader);
     }
RequestSendStream()
void services::ConnectionSerial::RequestSendStream (std::size_t sendSize) override virtual
Implements services::Connection.
Definition at line 53 of file ConnectionSerial.cpp.
References AllocatedSendStream(), MaxSendStreamSize(), pendingSendStream, and sendStreamAvailable.
     {
         assert(sendSize <= MaxSendStreamSize());
         if (sendStreamAvailable)
             AllocatedSendStream();
         else
             pendingSendStream = sendSize;
     }
ResetConnection()
void services::ConnectionSerial::ResetConnection () private
Definition at line 163 of file ConnectionSerial.cpp.
References GoStateInitSizeRequest(), and sendStreamAvailable.
     {
         sendStreamAvailable = true;
         GoStateInitSizeRequest();
     }
SendStreamAllocatable()
void services::ConnectionSerial::SendStreamAllocatable () private
Definition at line 169 of file ConnectionSerial.cpp.
References AllocatedSendStream(), pendingSendStream, and sendStreamAvailable.
     {
         sendStreamAvailable = true;
         if (pendingSendStream != 0)
             AllocatedSendStream();
     }
SendStreamFilled()
void services::ConnectionSerial::SendStreamFilled (infra::ByteRange data) private
Definition at line 177 of file ConnectionSerial.cpp.
References contentReadyForSend, infra::data, infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::EventDispatcherWorker::Schedule(), and state.
     {
         contentReadyForSend = data;
         infra::EventDispatcher::Instance().Schedule([this](){ state->EvaluatePendingSend(); });
     }
TryConstructHeader()
void services::ConnectionSerial::TryConstructHeader () private
Definition at line 119 of file ConnectionSerial.cpp.
References infra::QueueForOneReaderOneIrqWriter< T >::Consume(), infra::QueueForOneReaderOneIrqWriter< T >::Empty(), messageHeader, infra::none, receiveQueue, and state.
Referenced by DataReceived().
     {
         if (messageHeader == infra::none)
             messageHeader.Emplace();
         while (!receiveQueue.Empty() && !messageHeader->IsDone())
         {
             messageHeader->AddByte(receiveQueue[0]);
             receiveQueue.Consume(1);
             state->AccumulateWindowUpdateSize(1);
         }
     }
TryProcessHeader()
void services::ConnectionSerial::TryProcessHeader () private
Definition at line 90 of file ConnectionSerial.cpp.
References messageHeader, infra::none, ProcessHeader(), and state.
Referenced by DataReceived().
     {
         if (!messageHeader->IsDone())
             return;
         if (messageHeader->IsFailed())
             state->Reset();
         else
             ProcessHeader();
         messageHeader = infra::none;
     }
Member Data Documentation
accumulatedWindowSizeUpdate
infra::Optional<size_t> services::ConnectionSerial::accumulatedWindowSizeUpdate private
Definition at line 331 of file ConnectionSerial.hpp.
contentReadyForSend
infra::ByteRange services::ConnectionSerial::contentReadyForSend private
Definition at line 319 of file ConnectionSerial.hpp.
Referenced by SendStreamFilled().
contentToReceive
size_t services::ConnectionSerial::contentToReceive = 0 private
Definition at line 103 of file ConnectionSerial.hpp.
Referenced by DataReceived(), and ProcessHeader().
isEscapeSeen
bool services::ConnectionSerial::isEscapeSeen = false private
Definition at line 333 of file ConnectionSerial.hpp.
messageHeader
infra::Optional<MessageHeader> services::ConnectionSerial::messageHeader private
Definition at line 104 of file ConnectionSerial.hpp.
Referenced by ProcessHeader(), TryConstructHeader(), and TryProcessHeader().
minUpdateSize
size_t services::ConnectionSerial::minUpdateSize private
Definition at line 327 of file ConnectionSerial.hpp.
observerNotified
bool services::ConnectionSerial::observerNotified = false private
Definition at line 328 of file ConnectionSerial.hpp.
Referenced by NotifyObserverDataReceived(), and ReceiveStream().
peerBufferSize
size_t services::ConnectionSerial::peerBufferSize private
Definition at line 330 of file ConnectionSerial.hpp.
Referenced by services::ConnectionSerial::StateConnected::SizeUpdateReceived().
pendingSendStream
size_t services::ConnectionSerial::pendingSendStream = 0 protected
Definition at line 314 of file ConnectionSerial.hpp.
Referenced by AllocatedSendStream(), RequestSendStream(), and SendStreamAllocatable().
receivedDataQueue
infra::BoundedDeque<uint8_t>& services::ConnectionSerial::receivedDataQueue private
Definition at line 317 of file ConnectionSerial.hpp.
Referenced by services::ConnectionSerial::SerialConnectionStreamReader::Available(), services::ConnectionSerial::SerialConnectionStreamReader::ConsumeExtracted(), services::ConnectionSerial::SerialConnectionStreamReader::ExtractContiguousRange(), services::ConnectionSerial::SerialConnectionStreamReader::Peek(), services::ConnectionSerial::SerialConnectionStreamReader::PeekContiguousRange(), and ReceiveStream().
receivedDataReader
infra::Optional<SerialConnectionStreamReader> services::ConnectionSerial::receivedDataReader private
Definition at line 323 of file ConnectionSerial.hpp.
Referenced by ReceiveStream().
receiveQueue
infra::QueueForOneReaderOneIrqWriter<uint8_t> services::ConnectionSerial::receiveQueue private
Definition at line 322 of file ConnectionSerial.hpp.
Referenced by DataReceived(), ReceiveBufferSize(), and TryConstructHeader().
sendBuffer
infra::ByteRange services::ConnectionSerial::sendBuffer private
Definition at line 318 of file ConnectionSerial.hpp.
Referenced by AllocatedSendStream(), services::ConnectionSerial::StateConnected::ContentSizeToSend(), MaxSendStreamSize(), services::ConnectionSerial::StateConnected::Reset(), services::ConnectionSerial::StateConnectedSendingContent::SendEscapedContent(), and services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent().
sendStream
infra::SharedOptional<StreamWriterWithCyclicBuffer> services::ConnectionSerial::sendStream private
Definition at line 320 of file ConnectionSerial.hpp.
Referenced by AllocatedSendStream().
sendStreamAvailable
bool services::ConnectionSerial::sendStreamAvailable = true private
Definition at line 326 of file ConnectionSerial.hpp.
Referenced by AllocatedSendStream(), RequestSendStream(), ResetConnection(), and SendStreamAllocatable().
serialCommunication
hal::SerialCommunication& services::ConnectionSerial::serialCommunication private
Definition at line 321 of file ConnectionSerial.hpp.
Referenced by services::ConnectionSerial::StateConnectedSendingContent::SendContentWithSize(), services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent(), services::ConnectionSerial::StateSendingUpdate::SendUpdate(), services::ConnectionSerial::StateInitSizeRequest::SendWindowSizeRequest(), services::ConnectionSerial::StateInitSizeResponse::SendWindowSizeResponse(), and services::ConnectionSerial::StateInitSizeResponseRequest::SendWindowSizeResponseRequest().
serialCommunicationResource
infra::ClaimableResource services::ConnectionSerial::serialCommunicationResource private
Definition at line 324 of file ConnectionSerial.hpp.
state
infra::PolymorphicVariant<State, StateInitSizeRequest, StateInitSizeResponseRequest, StateInitSizeResponse, StateConnectedIdle, StateConnectedSendingContent, StateSendingUpdate> services::ConnectionSerial::state private
Definition at line 325 of file ConnectionSerial.hpp.
Referenced by AckReceived(), DataReceived(), GoStateConnectedIdle(), GoStateConnectedSendingContent(), GoStateInitSizeRequest(), GoStateInitSizeResponse(), GoStateInitSizeResponseRequest(), GoStateSendingUpdate(), ProcessHeader(), SendStreamFilled(), TryConstructHeader(), and TryProcessHeader().
totalContentSizeToSend
size_t services::ConnectionSerial::totalContentSizeToSend = 0 private
Definition at line 334 of file ConnectionSerial.hpp.
updateInProgress
bool services::ConnectionSerial::updateInProgress = false private
Definition at line 332 of file ConnectionSerial.hpp.
The documentation for this class was generated from the following files:
ConnectionSerial.hpp
ConnectionSerial.cpp