EMil: services::TracingFlash Class Reference
services::TracingFlash Class Reference
#include <TracingFlash.hpp>
Public Member Functions
TracingFlash (hal::Flash &flash, services::Tracer &tracer)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Private Attributes
hal::Flash & flash
services::Tracer & tracer
infra::AutoResetFunction< void()> onDone
infra::ConstByteRange buffer
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 10 of file TracingFlash.hpp.
Constructor & Destructor Documentation
TracingFlash()
services::TracingFlash::TracingFlash (hal::Flash & flash, services::Tracer & tracer)
Definition at line 5 of file TracingFlash.cpp.
         : flash(flash)
         , tracer(tracer)
     {}
Member Function Documentation
AddressOfSector()
uint32_t services::TracingFlash::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 25 of file TracingFlash.cpp.
References hal::Flash::AddressOfSector(), and flash.
     {
         return flash.AddressOfSector(sectorIndex);
     }
EraseSectors()
void services::TracingFlash::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 47 of file TracingFlash.cpp.
References hal::Flash::EraseSectors(), flash, infra::hex, onDone, services::Tracer::Trace(), and tracer.
     {
         tracer.Trace() << "Flash EraseSectors 0x" << infra::hex << beginIndex << " to 0x" << infra::hex << endIndex;
         flash.EraseSectors(beginIndex, endIndex, onDone);
     }
NumberOfSectors()
uint32_t services::TracingFlash::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 10 of file TracingFlash.cpp.
References flash, and hal::Flash::NumberOfSectors().
     {
         return flash.NumberOfSectors();
     }
ReadBuffer()
void services::TracingFlash::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 36 of file TracingFlash.cpp.
References infra::AsHex(), buffer, flash, infra::hex, onDone, hal::Flash::ReadBuffer(), services::Tracer::Trace(), and tracer.
     {
         this->onDone = onDone;
         this->buffer = buffer;
         flash.ReadBuffer(buffer, address, [this, address]()
         {
             tracer.Trace() << "Flash ReadBuffer from 0x" << infra::hex << address << ": " << infra::AsHex(this->buffer);
             this->onDone();
         });
     }
SectorOfAddress()
uint32_t services::TracingFlash::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 20 of file TracingFlash.cpp.
References flash, and hal::Flash::SectorOfAddress().
     {
         return flash.SectorOfAddress(address);
     }
SizeOfSector()
uint32_t services::TracingFlash::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 15 of file TracingFlash.cpp.
References flash, and hal::Flash::SizeOfSector().
     {
         return flash.SizeOfSector(sectorIndex);
     }
WriteBuffer()
void services::TracingFlash::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 30 of file TracingFlash.cpp.
References infra::AsHex(), buffer, flash, infra::hex, onDone, services::Tracer::Trace(), tracer, and hal::Flash::WriteBuffer().
     {
         tracer.Trace() << "Flash WriteBuffer to 0x" << infra::hex << address << ": " << infra::AsHex(buffer);
         flash.WriteBuffer(buffer, address, onDone);
     }
Member Data Documentation
buffer
infra::ConstByteRange services::TracingFlash::buffer private
Definition at line 30 of file TracingFlash.hpp.
Referenced by ReadBuffer(), and WriteBuffer().
flash
hal::Flash& services::TracingFlash::flash private
Definition at line 26 of file TracingFlash.hpp.
Referenced by AddressOfSector(), EraseSectors(), NumberOfSectors(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), and WriteBuffer().
onDone
infra::AutoResetFunction<void()> services::TracingFlash::onDone private
Definition at line 29 of file TracingFlash.hpp.
Referenced by EraseSectors(), ReadBuffer(), and WriteBuffer().
tracer
services::Tracer& services::TracingFlash::tracer private
Definition at line 27 of file TracingFlash.hpp.
Referenced by EraseSectors(), ReadBuffer(), and WriteBuffer().
The documentation for this class was generated from the following files:
TracingFlash.hpp
TracingFlash.cpp