EMil: application::DecryptorAesTiny Class Reference
application::DecryptorAesTiny Class Reference
#include <DecryptorAesTiny.hpp>
Public Member Functions
DecryptorAesTiny (infra::ConstByteRange key)
virtual infra::ByteRange StateBuffer () override
virtual void Reset () override
virtual void DecryptPart (infra::ByteRange data) override
virtual bool DecryptAndAuthenticate (infra::ByteRange data) override
Static Public Attributes
static const std::size_t blockLength = 16
Private Member Functions
void IncreaseCounter ()
Private Attributes
size_t currentStreamBlockOffset = 0
std::array< uint8_t, blockLength > currentStreamBlock
std::array< uint8_t, blockLength > counter
Additional Inherited Members
Protected Member Functions inherited from application::Decryptor
~Decryptor ()=default
Detailed Description
Definition at line 8 of file DecryptorAesTiny.hpp.
Constructor & Destructor Documentation
DecryptorAesTiny()
application::DecryptorAesTiny::DecryptorAesTiny (infra::ConstByteRange key) explicit
Definition at line 10 of file DecryptorAesTiny.cpp.
References infra::MemoryRange< T >::begin(), counter, and currentStreamBlock.
         : currentStreamBlock()
         , counter()
     {
         AES128_ECB_encrypt(counter.data(), key.begin(), currentStreamBlock.data()); // Dummy encryption to trigger key expansion
     }
Member Function Documentation
DecryptAndAuthenticate()
bool application::DecryptorAesTiny::DecryptAndAuthenticate (infra::ByteRange data) override virtual
Implements application::Decryptor.
Definition at line 53 of file DecryptorAesTiny.cpp.
References infra::data, and DecryptPart().
     {
         DecryptPart(data);
         return true;
     }
DecryptPart()
void application::DecryptorAesTiny::DecryptPart (infra::ByteRange data) override virtual
Implements application::Decryptor.
Definition at line 27 of file DecryptorAesTiny.cpp.
References counter, currentStreamBlock, currentStreamBlockOffset, infra::data, and IncreaseCounter().
Referenced by DecryptAndAuthenticate().
     {
         while (!data.empty())
         {
             if (currentStreamBlockOffset == 0)
             {
                 AES128_ECB_encrypt(counter.data(), nullptr, currentStreamBlock.data());
                 IncreaseCounter();
             }
             data.front() ^= currentStreamBlock[currentStreamBlockOffset];
             data.pop_front();
             ++currentStreamBlockOffset;
             if (currentStreamBlockOffset == currentStreamBlock.size())
                 currentStreamBlockOffset = 0;
         }
     }
IncreaseCounter()
void application::DecryptorAesTiny::IncreaseCounter () private
Definition at line 46 of file DecryptorAesTiny.cpp.
References counter.
Referenced by DecryptPart().
     {
         for (std::size_t i = counter.size(); i != 0; --i)
             if (++counter[i - 1] != 0)
                 break;
     }
Reset()
void application::DecryptorAesTiny::Reset () override virtual
Implements application::Decryptor.
Definition at line 22 of file DecryptorAesTiny.cpp.
References currentStreamBlockOffset.
     {
         currentStreamBlockOffset = 0;
     }
StateBuffer()
infra::ByteRange application::DecryptorAesTiny::StateBuffer () override virtual
Implements application::Decryptor.
Definition at line 17 of file DecryptorAesTiny.cpp.
References counter, and infra::MakeByteRange().
     {
         return infra::MakeByteRange(counter);
     }
Member Data Documentation
blockLength
const std::size_t application::DecryptorAesTiny::blockLength = 16 static
Definition at line 12 of file DecryptorAesTiny.hpp.
counter
std::array<uint8_t, blockLength> application::DecryptorAesTiny::counter private
Definition at line 27 of file DecryptorAesTiny.hpp.
Referenced by DecryptorAesTiny(), DecryptPart(), IncreaseCounter(), and StateBuffer().
currentStreamBlock
std::array<uint8_t, blockLength> application::DecryptorAesTiny::currentStreamBlock private
Definition at line 26 of file DecryptorAesTiny.hpp.
Referenced by DecryptorAesTiny(), and DecryptPart().
currentStreamBlockOffset
size_t application::DecryptorAesTiny::currentStreamBlockOffset = 0 private
Definition at line 25 of file DecryptorAesTiny.hpp.
Referenced by DecryptPart(), and Reset().
The documentation for this class was generated from the following files:
DecryptorAesTiny.hpp
DecryptorAesTiny.cpp