EMil: TestConnectionSerial.cpp File Reference
TestConnectionSerial.cpp File Reference
Classes
class ConnectionSerialTest
class ConnectionSerialTestHeaderBytesTest
Functions
TEST_F (ConnectionSerialTest, MaxSendStreamSize)
TEST_F (ConnectionSerialTest, sends_request_for_window_size_after_construction_at_every_second)
TEST_F (ConnectionSerialTest, sends_request_for_window_size_after_construction_at_every_second2)
TEST_F (ConnectionSerialTest, stops_sending_window_size_request_after_receiving_window_size_response_request_and_sends_window_size_response)
TEST_F (ConnectionSerialTest, stops_sending_window_size_request_after_receiving_window_size_request_and_sends_window_size_response_request)
TEST_F (ConnectionSerialTest, stops_sending_window_size_request_after_receiving_window_size_request_and_sends_window_size_response_request2)
TEST_F (ConnectionSerialTest, window_response_request_received_while_sending_size_request)
TEST_F (ConnectionSerialTest, discards_scrap_bytes)
TEST_F (ConnectionSerialTest, handle_partially_received_header)
TEST_F (ConnectionSerialTest, size_request_received_while_sending_response_request_triggers_another_response_request_after_send)
TEST_F (ConnectionSerialTest, handle_wrapped_header)
TEST_F (ConnectionSerialTest, window_size_response_intercepted_by_window_size_request_resets_connection)
TEST_F (ConnectionSerialTest, RequestSendStream_before_initialization_grants_SendStreamAvailable_but_does_not_start_sending_if_initialization_is_not_complete)
TEST_F (ConnectionSerialTest, RequestSendStream_twice_before_initialization_grants_SendStreamAvailable_only_once)
TEST_F (ConnectionSerialTest, RequestSendStream_before_initialization_grants_SendStreamAvailable_but_does_not_start_sending_if_initialization_is_not_complete2)
TEST_F (ConnectionSerialTest, RequestSendStream_before_initialization_grants_SendStreamAvailable_and_starts_sending_after_initialization)
TEST_F (ConnectionSerialTest, RequestSendStream_before_initialization_grants_SendStreamAvailable_and_starts_sending_after_initialization2)
TEST_F (ConnectionSerialTest, RequestSendStream_after_initialization_grants_SendStreamAvailable_and_starts_sending_content)
TEST_F (ConnectionSerialTest, unexpected_request_after_initialization_blocks_send_and_resets)
TEST_F (ConnectionSerialTest, unexpected_response_request_after_initialization_blocks_send_and_resets)
TEST_F (ConnectionSerialTest, unexpected_response_after_initialization_blocks_send_and_resets)
TEST_F (ConnectionSerialTest, escape_header_and_escape_bytes_in_content)
TEST_F (ConnectionSerialTest, only_send_content_with_size_less_than_available_peer_space_minus_one_update_message_size)
TEST_F (ConnectionSerialTest, do_not_schedule_SendStreamAvailable_until_content_has_been_sent)
TEST_F (ConnectionSerialTest, notify_observer_when_content_message_received_only_if_observer_is_unaware)
TEST_F (ConnectionSerialTest, notify_observer_when_partial_content_message_received)
TEST_F (ConnectionSerialTest, notify_observer_when_content_message_received_part_by_part)
TEST_F (ConnectionSerialTest, extract_received_content_via_StreamReader_using_ExtractContiguousRange)
TEST_F (ConnectionSerialTest, extract_received_content_via_StreamReader_using_Extract)
TEST_F (ConnectionSerialTest, peek_received_content_via_StreamReader_using_PeekContiguousRange)
TEST_F (ConnectionSerialTest, peek_received_content_via_StreamReader_using_Peek)
TEST_F (ConnectionSerialTest, AckReceived_consumes_content_extracted_via_StreamReader)
TEST_F (ConnectionSerialTest, accumulate_size_updates_until_current_one_is_completed)
TEST_F (ConnectionSerialTest, size_updates_consumes_peer_buffer_space)
TEST_F (ConnectionSerialTest, dont_send_size_updates_less_than_default_minimum_size_of_4)
TEST_F (ConnectionSerialTest, dont_send_size_updates_less_than_configured_size)
TEST_F (ConnectionSerialTest, dont_send_size_updates_when_peer_buffer_is_completely_full)
TEST_F (ConnectionSerialTest, send_size_updates_for_consumed_headers)
TEST_F (ConnectionSerialTest, send_size_updates_for_consumed_headers2)
TEST_F (ConnectionSerialTest, escape_bytes_immediately_included_in_size_update)
TEST_F (ConnectionSerialTest, call_to_ReceiveStream_returns_stream_with_updated_messages)
TEST_F (ConnectionSerialTest, handle_wrapping_while_extracting_content_with_ExtractContiguousRange)
TEST_F (ConnectionSerialTest, handle_wrapping_while_extracting_content_with_Extract)
TEST_F (ConnectionSerialTest, handle_escaped_bytes_while_extracting_content)
TEST_F (ConnectionSerialTest, scrap_bytes_received_after_initialization_are_scrapped_and_connection_is_reset)
TEST_P (ConnectionSerialTestHeaderBytesTest, unescaped_header_bytes_received_midcontent_message_are_discarded_and_connection_state_is_reset1)
TEST_P (ConnectionSerialTestHeaderBytesTest, unescaped_header_bytes_received_midcontent_message_are_discarded_and_connection_state_is_reset2)
INSTANTIATE_TEST_CASE_P (HeaderBytes, ConnectionSerialTestHeaderBytesTest, testing::Values(0xfa, 0xfb, 0xfc, 0xfd, 0xfe))
TEST_F (ConnectionSerialTest, reset_connection_during_a_content_send)
Function Documentation
INSTANTIATE_TEST_CASE_P()
INSTANTIATE_TEST_CASE_P (HeaderBytes , ConnectionSerialTestHeaderBytesTest , testing::Values(0xfa, 0xfb, 0xfc, 0xfd, 0xfe))
TEST_F() [1/46]
TEST_F (ConnectionSerialTest , MaxSendStreamSize)
Definition at line 250 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), and services::ConnectionSerial::MaxSendStreamSize().
 {
     EXPECT_EQ(sizeof(sendBuffer), connection->MaxSendStreamSize());
 }
TEST_F() [2/46]
TEST_F (ConnectionSerialTest , sends_request_for_window_size_after_construction_at_every_second)
Definition at line 257 of file TestConnectionSerial.cpp.
 {
     ExpectWindowSizeRequest();
     ExecuteAllActions();
     ForwardTime(std::chrono::seconds(1));
     serialCommunication.actionOnCompletion();
     ExpectWindowSizeRequest();
     ForwardTime(std::chrono::seconds(1));
 }
TEST_F() [3/46]
TEST_F (ConnectionSerialTest , sends_request_for_window_size_after_construction_at_every_second2)
Definition at line 269 of file TestConnectionSerial.cpp.
 {
     WindowSizeResponseReceived();
     ExecuteAllActions();
     ExpectWindowSizeRequest();
     ForwardTime(std::chrono::seconds(1));
 }
TEST_F() [4/46]
TEST_F (ConnectionSerialTest , stops_sending_window_size_request_after_receiving_window_size_response_request_and_sends_window_size_response)
Definition at line 278 of file TestConnectionSerial.cpp.
 {
     WindowSizeResponseRequestReceived();
     ExpectAndCompleteWindowSizeResponse(ReceiveBufferSize());
     ForwardTime(std::chrono::seconds(1));
 }
TEST_F() [5/46]
TEST_F (ConnectionSerialTest , stops_sending_window_size_request_after_receiving_window_size_request_and_sends_window_size_response_request)
Definition at line 285 of file TestConnectionSerial.cpp.
 {
     ExpectWindowSizeRequest();
     ReconstructConnection();
     WindowSizeRequestReceived();
     ExecuteAllActions();
     ExpectWindowSizeResponseRequest(ReceiveBufferSize());
     serialCommunication.actionOnCompletion();
 }
TEST_F() [6/46]
TEST_F (ConnectionSerialTest , stops_sending_window_size_request_after_receiving_window_size_request_and_sends_window_size_response_request2)
Definition at line 297 of file TestConnectionSerial.cpp.
 {
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
     ForwardTime(std::chrono::seconds(1));
 }
TEST_F() [7/46]
TEST_F (ConnectionSerialTest , window_response_request_received_while_sending_size_request)
Definition at line 304 of file TestConnectionSerial.cpp.
 {
     ExpectWindowSizeRequest();
     ForwardTime(std::chrono::seconds(1));
     WindowSizeResponseRequestReceived();
     ExecuteAllActions();
     ExpectWindowSizeResponse(ReceiveBufferSize());
     serialCommunication.actionOnCompletion();
 }
TEST_F() [8/46]
TEST_F (ConnectionSerialTest , discards_scrap_bytes)
Definition at line 316 of file TestConnectionSerial.cpp.
 {
     serialCommunication.dataReceived(std::vector<uint8_t>{ 'a' });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 'b' });
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
 }
TEST_F() [9/46]
TEST_F (ConnectionSerialTest , handle_partially_received_header)
Definition at line 325 of file TestConnectionSerial.cpp.
 {
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfc });
     serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(2048 >> 8) });
     ExecuteAllActions();
     serialCommunication.dataReceived(std::vector<uint8_t>{ static_cast<uint8_t>(2048 & 0xff) });
     ExpectAndCompleteWindowSizeResponse(ReceiveBufferSize());
 }
TEST_F() [10/46]
TEST_F (ConnectionSerialTest , size_request_received_while_sending_response_request_triggers_another_response_request_after_send)
Definition at line 335 of file TestConnectionSerial.cpp.
 {
     WindowSizeRequestReceived();
     ExpectWindowSizeResponseRequest(ReceiveBufferSize());
     ExecuteAllActions();
     WindowSizeRequestReceived();
     ExecuteAllActions();
     ExpectWindowSizeResponseRequest(ReceiveBufferSize());
     serialCommunication.actionOnCompletion();
 }
TEST_F() [11/46]
TEST_F (ConnectionSerialTest , handle_wrapped_header)
Definition at line 348 of file TestConnectionSerial.cpp.
 {
     ReconstructConnectionWithReceiveBufferSize(8);
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
 }
TEST_F() [12/46]
TEST_F (ConnectionSerialTest , window_size_response_intercepted_by_window_size_request_resets_connection)
Definition at line 363 of file TestConnectionSerial.cpp.
 {
     WindowSizeResponseRequestReceived();
     ExpectWindowSizeResponse(ReceiveBufferSize());
     WindowSizeRequestReceived();
     ExecuteAllActions();
     ExpectWindowSizeResponseRequest(ReceiveBufferSize());
     serialCommunication.actionOnCompletion();
 }
TEST_F() [13/46]
TEST_F (ConnectionSerialTest , RequestSendStream_before_initialization_grants_SendStreamAvailable_but_does_not_start_sending_if_initialization_is_not_complete)
Definition at line 374 of file TestConnectionSerial.cpp.
 {
     GetAndWriteToSendStream({ '1', '2' });
     ExecuteAllActions();
 }
TEST_F() [14/46]
TEST_F (ConnectionSerialTest , RequestSendStream_twice_before_initialization_grants_SendStreamAvailable_only_once)
Definition at line 380 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::MaxSendStreamSize(), and services::ConnectionSerial::RequestSendStream().
 {
     GetAndWriteToSendStream({ '1', '2' });
     ExecuteAllActions();
     connection->RequestSendStream(connection->MaxSendStreamSize());
     ExecuteAllActions();
 }
TEST_F() [15/46]
TEST_F (ConnectionSerialTest , RequestSendStream_before_initialization_grants_SendStreamAvailable_but_does_not_start_sending_if_initialization_is_not_complete2)
Definition at line 389 of file TestConnectionSerial.cpp.
 {
     GetAndWriteToSendStream({ '1', '2' });
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
 }
TEST_F() [16/46]
TEST_F (ConnectionSerialTest , RequestSendStream_before_initialization_grants_SendStreamAvailable_and_starts_sending_after_initialization)
Definition at line 396 of file TestConnectionSerial.cpp.
 {
     GetAndWriteToSendStream({ '1', '2' });
     WindowSizeResponseRequestReceived();
     ExpectWindowSizeResponse(ReceiveBufferSize());
     ExecuteAllActions();
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '1', '2' });
     serialCommunication.actionOnCompletion();
 }
TEST_F() [17/46]
TEST_F (ConnectionSerialTest , RequestSendStream_before_initialization_grants_SendStreamAvailable_and_starts_sending_after_initialization2)
Definition at line 406 of file TestConnectionSerial.cpp.
 {
     GetAndWriteToSendStream({ '1', '2' });
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeResponseRequest(ReceiveBufferSize());
     WindowSizeResponseReceived();
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '1', '2' });
 }
TEST_F() [18/46]
TEST_F (ConnectionSerialTest , RequestSendStream_after_initialization_grants_SendStreamAvailable_and_starts_sending_content)
Definition at line 415 of file TestConnectionSerial.cpp.
 {
     Initialization();
     GetAndWriteToSendStream({ '1', '2' });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '1', '2' });
 }
TEST_F() [19/46]
TEST_F (ConnectionSerialTest , unexpected_request_after_initialization_blocks_send_and_resets)
Definition at line 423 of file TestConnectionSerial.cpp.
 {
     Initialization();
     GetAndWriteToSendStream({ '1', '2' });
     WindowSizeRequestReceived();
     ExpectAndCompleteWindowSizeRequest();
     Initialization();
     GetAndWriteToSendStream({ '2', '3' });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '2', '3' });
 }
TEST_F() [20/46]
TEST_F (ConnectionSerialTest , unexpected_response_request_after_initialization_blocks_send_and_resets)
Definition at line 435 of file TestConnectionSerial.cpp.
 {
     Initialization();
     WindowSizeResponseRequestReceived();
     ExpectAndCompleteWindowSizeRequest();
     ExecuteAllActions();
 }
TEST_F() [21/46]
TEST_F (ConnectionSerialTest , unexpected_response_after_initialization_blocks_send_and_resets)
Definition at line 444 of file TestConnectionSerial.cpp.
 {
     Initialization();
     WindowSizeResponseReceived();
     ExpectAndCompleteWindowSizeRequest();
     ExecuteAllActions();
 }
TEST_F() [22/46]
TEST_F (ConnectionSerialTest , escape_header_and_escape_bytes_in_content)
Definition at line 454 of file TestConnectionSerial.cpp.
 {
     Initialization();
     GetAndWriteToSendStream({ 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe });
     GetAndWriteToSendStream({ 0xf9, '1' });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ 0xf9, '1' });
     GetAndWriteToSendStream({ '1', 0xf9 });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '1', 0xf9 });
     GetAndWriteToSendStream({ 0xf9, '1', '2', '3', 0xf9 });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ 0xf9, '1', '2', '3', 0xf9 });
 }
TEST_F() [23/46]
TEST_F (ConnectionSerialTest , only_send_content_with_size_less_than_available_peer_space_minus_one_update_message_size)
Definition at line 471 of file TestConnectionSerial.cpp.
 {
     ReconstructConnectionWithMinUpdateSize(20);
     Initialization(10);
     // 'max content message size(4)' = 'peer space(10)' - 'update message size(3)' - 'content message header size(3)'
     GetAndWriteToSendStream({ '1', '2', '3', '4', '5', '6' });
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '1', '2', '3', '4' });
     WindowSizeUpdateReceived(4);
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '5' });
     WindowSizeUpdateReceived(3);
     ExecuteAllActions();
     WindowSizeUpdateReceived(1);
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '6' });
 }
TEST_F() [24/46]
TEST_F (ConnectionSerialTest , do_not_schedule_SendStreamAvailable_until_content_has_been_sent)
Definition at line 490 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::MaxSendStreamSize(), and services::ConnectionSerial::RequestSendStream().
 {
     Initialization(8);
     GetAndWriteToSendStream({ '1', '2', '3', '4' });
     ExpectSepearateContentHeaderAndContentMessages({ '1', '2' });
     ExecuteAllActions();
     connection->RequestSendStream(connection->MaxSendStreamSize());
     ExecuteAllActions();
     serialCommunication.actionOnCompletion();
     serialCommunication.actionOnCompletion();
     ExecuteAllActions();
     WindowSizeUpdateReceived(5);
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '3', '4' });
     ExpectSendStreamAvailable(std::vector<uint8_t>({ '5', '6' }));
     ExecuteAllActions();
     WindowSizeUpdateReceived(8);
     ExpectWindowSizeUpdateWithComplete(6);
     ExpectAndCompleteSepearateContentHeaderAndContentMessage({ '5', '6' });
 }
TEST_F() [25/46]
TEST_F (ConnectionSerialTest , notify_observer_when_content_message_received_only_if_observer_is_unaware)
Definition at line 516 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::ReceiveStream().
 {
     ReconstructConnectionWithMinUpdateSize(2000);
     Initialization();
     ContentMessageReceived({ '1', '2', '3' });
     EXPECT_CALL(observer, DataReceived());
     ExecuteAllActions();
     ContentMessageReceived({ '4', '5', '6' });
     ExecuteAllActions();
     connection->ReceiveStream();
     ContentMessageReceived({ '7', '8', '9' });
     EXPECT_CALL(observer, DataReceived());
     ExecuteAllActions();
 }
TEST_F() [26/46]
TEST_F (ConnectionSerialTest , notify_observer_when_partial_content_message_received)
Definition at line 534 of file TestConnectionSerial.cpp.
 {
     ReconstructConnectionWithMinUpdateSize(2000);
     Initialization();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfd });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 2 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ '1' });
     EXPECT_CALL(observer, DataReceived());
     ExecuteAllActions();
 }
TEST_F() [27/46]
TEST_F (ConnectionSerialTest , notify_observer_when_content_message_received_part_by_part)
Definition at line 548 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::ReceiveStream().
 {
     Initialization();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfd });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 2 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ '1' });
     EXPECT_CALL(observer, DataReceived());
     ExecuteAllActions();
     connection->ReceiveStream();
     serialCommunication.dataReceived(std::vector<uint8_t>{ '2' });
     EXPECT_CALL(observer, DataReceived());
     ExecuteAllActions();
 }
TEST_F() [28/46]
TEST_F (ConnectionSerialTest , extract_received_content_via_StreamReader_using_ExtractContiguousRange)
Definition at line 567 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), and services::ConnectionSerial::ReceiveStream().
 {
     ReconstructConnectionWithMinUpdateSize(2000);
     Initialization();
     ContentMessageReceived({ '1', });
     ContentMessageReceivedAndObserverNotified({ '2', '3' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     EXPECT_FALSE(reader->Empty());
     EXPECT_EQ(3, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({ '1', '2' }), reader->ExtractContiguousRange(2));
     EXPECT_EQ(1, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({ '3' }), reader->ExtractContiguousRange(2));
     EXPECT_EQ(0, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({}), reader->ExtractContiguousRange(1));
     EXPECT_TRUE(reader->Empty());
 }
TEST_F() [29/46]
TEST_F (ConnectionSerialTest , extract_received_content_via_StreamReader_using_Extract)
Definition at line 589 of file TestConnectionSerial.cpp.
References infra::Optional< T >::Emplace(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), infra::StreamErrorPolicy::Failed(), services::ConnectionSerial::ReceiveStream(), and infra::softFail.
 {
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     infra::Optional<infra::StreamErrorPolicy> error;
     std::vector<uint8_t> a;
     error.Emplace(infra::softFail);
     a.resize(5, 0);
     reader->Extract(infra::ByteRange(a), *error);
     EXPECT_TRUE(error->Failed());
     EXPECT_EQ(4, reader->Available());
     error.Emplace(infra::softFail);
     a.resize(1, 0);
     reader->Extract(infra::ByteRange(a), *error);
     EXPECT_EQ(std::vector<uint8_t>({ '1' }), a);
     EXPECT_FALSE(error->Failed());
     EXPECT_EQ(3, reader->Available());
     error.Emplace(infra::softFail);
     a.resize(3, 0);
     reader->Extract(infra::ByteRange(a), *error);
     EXPECT_EQ(std::vector<uint8_t>({ '2', '3', '4' }), a);
     EXPECT_FALSE(error->Failed());
     EXPECT_EQ(0, reader->Available());
 }
TEST_F() [30/46]
TEST_F (ConnectionSerialTest , peek_received_content_via_StreamReader_using_PeekContiguousRange)
Definition at line 619 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), and services::ConnectionSerial::ReceiveStream().
 {
     ReconstructConnectionWithMinUpdateSize(2000);
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     EXPECT_EQ(std::vector<uint8_t>({ '1', '2', '3', '4' }), reader->PeekContiguousRange(0));
     EXPECT_EQ(std::vector<uint8_t>({ '2', '3', '4' }), reader->PeekContiguousRange(1));
     EXPECT_EQ(std::vector<uint8_t>({}), reader->PeekContiguousRange(4));
     EXPECT_EQ(4, reader->Available());
     reader->ExtractContiguousRange(1);
     EXPECT_EQ(std::vector<uint8_t>({ '2', '3', '4' }), reader->PeekContiguousRange(0));
     EXPECT_EQ(3, reader->Available());
 }
TEST_F() [31/46]
TEST_F (ConnectionSerialTest , peek_received_content_via_StreamReader_using_Peek)
Definition at line 637 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), infra::StreamErrorPolicy::Failed(), services::ConnectionSerial::ReceiveStream(), and infra::softFail.
 {
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     infra::StreamErrorPolicy error(infra::softFail);
     EXPECT_EQ('1', reader->Peek(error));
     EXPECT_FALSE(error.Failed());
     reader->ExtractContiguousRange(1);
     EXPECT_EQ('2', reader->Peek(error));
     EXPECT_FALSE(error.Failed());
     reader->ExtractContiguousRange(2);
     reader->Peek(error);
     EXPECT_TRUE(error.Failed());
 }
TEST_F() [32/46]
TEST_F (ConnectionSerialTest , AckReceived_consumes_content_extracted_via_StreamReader)
Definition at line 659 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), and services::ConnectionSerial::ReceiveStream().
 {
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4', '5' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     EXPECT_EQ(std::vector<uint8_t>({ '1' }), reader->ExtractContiguousRange(1));
     AckReceivedAndExpectUpdate(4);
     reader = connection->ReceiveStream();
     EXPECT_EQ(4, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({ '2', '3', '4', '5' }), reader->ExtractContiguousRange(4));
     AckReceivedAndExpectUpdate(4);
 }
TEST_F() [33/46]
TEST_F (ConnectionSerialTest , accumulate_size_updates_until_current_one_is_completed)
Definition at line 674 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::AckReceived(), infra::StreamReader::ExtractContiguousRange(), and services::ConnectionSerial::ReceiveStream().
 {
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4', '5', '6', '7', '8', '9' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     ExpectWindowSizeUpdate(4);
     connection->AckReceived();
     ExecuteAllActions();
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(4);
     connection->AckReceived();
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(4);
     connection->AckReceived();
     ExpectWindowSizeUpdate(8);
     serialCommunication.actionOnCompletion();
     ExecuteAllActions();
 }
TEST_F() [34/46]
TEST_F (ConnectionSerialTest , size_updates_consumes_peer_buffer_space)
Definition at line 699 of file TestConnectionSerial.cpp.
References infra::StreamReader::ExtractContiguousRange(), and services::ConnectionSerial::ReceiveStream().
 {
     Initialization(7);
     ContentMessageReceivedAndObserverNotified({ '1' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     AckReceivedAndExpectUpdate(4);
     GetAndWriteToSendStream({ '1' });
     ExecuteAllActions();
 }
TEST_F() [35/46]
TEST_F (ConnectionSerialTest , dont_send_size_updates_less_than_default_minimum_size_of_4)
Definition at line 712 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::AckReceived(), infra::StreamReader::ExtractContiguousRange(), and services::ConnectionSerial::ReceiveStream().
 {
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4', '5' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     AckReceivedAndExpectUpdate(4);
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(3);
     connection->AckReceived();
     ExecuteAllActions();
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     ExpectWindowSizeUpdate(4);
     connection->AckReceived();
     ExecuteAllActions();
 }
TEST_F() [36/46]
TEST_F (ConnectionSerialTest , dont_send_size_updates_less_than_configured_size)
Definition at line 733 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::AckReceived(), infra::StreamReader::ExtractContiguousRange(), and services::ConnectionSerial::ReceiveStream().
 {
     ReconstructConnectionWithMinUpdateSize(5);
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     connection->AckReceived();
     ExecuteAllActions();
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     ExpectWindowSizeUpdate(5);
     connection->AckReceived();
     ExecuteAllActions();
 }
TEST_F() [37/46]
TEST_F (ConnectionSerialTest , dont_send_size_updates_when_peer_buffer_is_completely_full)
Definition at line 751 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::AckReceived(), infra::StreamReader::ExtractContiguousRange(), and services::ConnectionSerial::ReceiveStream().
 {
     Initialization(6);
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4', '5', '6', '7', '8', '9' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(1);
     AckReceivedAndExpectUpdate(4);
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(4);
     AckReceivedAndExpectUpdate(4);
     reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(4);
     connection->AckReceived();
     ExecuteAllActions();
     WindowSizeUpdateReceived(3);
     ExpectWindowSizeUpdate(7);
     ExecuteAllActions();
 }
TEST_F() [38/46]
TEST_F (ConnectionSerialTest , send_size_updates_for_consumed_headers)
Definition at line 774 of file TestConnectionSerial.cpp.
 {
     Initialization();
     ContentMessageReceived({ '1' });
     ContentMessageReceived({ '2' });
     ExpectWindowSizeUpdate(6);
     EXPECT_CALL(observer, DataReceived());
     ExecuteAllActions();
 }
TEST_F() [39/46]
TEST_F (ConnectionSerialTest , send_size_updates_for_consumed_headers2)
Definition at line 785 of file TestConnectionSerial.cpp.
 {
     Initialization();
     ExpectWindowSizeUpdate(6);
     WindowSizeUpdateReceived(0);
     WindowSizeUpdateReceived(0);
     ExecuteAllActions();
 }
TEST_F() [40/46]
TEST_F (ConnectionSerialTest , escape_bytes_immediately_included_in_size_update)
Definition at line 795 of file TestConnectionSerial.cpp.
 {
     Initialization();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfd });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 9 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     EXPECT_CALL(observer, DataReceived());
     ExpectAndCompleteUpdate(4);
     ExecuteAllActions();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfa });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     ExpectAndCompleteUpdate(4);
 }
TEST_F() [41/46]
TEST_F (ConnectionSerialTest , call_to_ReceiveStream_returns_stream_with_updated_messages)
Definition at line 820 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), and services::ConnectionSerial::ReceiveStream().
 {
     ReconstructConnectionWithMinUpdateSize(2000);
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     ContentMessageReceivedAndObserverNotified({ '2' });
     EXPECT_EQ(2, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({ '1', '2' }), reader->ExtractContiguousRange(2));
 }
TEST_F() [42/46]
TEST_F (ConnectionSerialTest , handle_wrapping_while_extracting_content_with_ExtractContiguousRange)
Definition at line 832 of file TestConnectionSerial.cpp.
References services::ConnectionSerial::AckReceived(), infra::Optional< T >::Emplace(), EXPECT_EQ(), and services::ConnectionSerial::ReceiveStream().
 {
     receiveBuffer.resize(10);
     receivedDataQueue.Emplace(infra::MemoryRange<infra::StaticStorage<uint8_t>>(&storage[0], &storage[10]));
     ExpectWindowSizeRequest([this]() { serialCommunication.actionOnCompletion(); });
     ReconstructConnection();
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4', '5' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     EXPECT_EQ(std::vector<uint8_t>({ '1', '2', '3', '4', '5' }), reader->ExtractContiguousRange(5));
     AckReceivedAndExpectUpdate(8);
     ContentMessageReceivedAndObserverNotified({ '7', '8', '9', 'a', 'b', 'c' });
     reader = connection->ReceiveStream();
     EXPECT_EQ(std::vector<uint8_t>({ '7', '8', '9', 'a', 'b' }), reader->PeekContiguousRange(0));
     EXPECT_EQ(std::vector<uint8_t>({ '7', '8', '9', 'a', 'b' }), reader->ExtractContiguousRange(6));
     AckReceivedAndExpectUpdate(8);
     reader = connection->ReceiveStream();
     EXPECT_EQ(std::vector<uint8_t>({ 'c' }), reader->ExtractContiguousRange(2));
     connection->AckReceived();
     ExecuteAllActions();
 }
TEST_F() [43/46]
TEST_F (ConnectionSerialTest , handle_wrapping_while_extracting_content_with_Extract)
Definition at line 860 of file TestConnectionSerial.cpp.
References infra::Optional< T >::Emplace(), EXPECT_EQ(), EXPECT_FALSE(), infra::StreamReader::Extract(), infra::StreamReader::ExtractContiguousRange(), infra::StreamErrorPolicy::Failed(), services::ConnectionSerial::ReceiveStream(), and infra::softFail.
 {
     ReconstructConnectionWithReceiveBufferSize(10);
     Initialization();
     ContentMessageReceivedAndObserverNotified({ '1', '2', '3', '4', '5' });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     reader->ExtractContiguousRange(5);
     AckReceivedAndExpectUpdate(8);
     ContentMessageReceivedAndObserverNotified({ '7', '8', '9', 'a', 'b', 'c' });
     std::vector<uint8_t> a;
     infra::Optional<infra::StreamErrorPolicy> error;
     error.Emplace(infra::softFail);
     a.resize(6, 0);
     reader = connection->ReceiveStream();
     reader->Extract(infra::ByteRange(a), *error);
     EXPECT_EQ(std::vector<uint8_t>({ '7', '8', '9', 'a', 'b', 'c' }), a);
     EXPECT_FALSE(error->Failed());
     EXPECT_EQ(0, reader->Available());
 }
TEST_F() [44/46]
TEST_F (ConnectionSerialTest , handle_escaped_bytes_while_extracting_content)
Definition at line 885 of file TestConnectionSerial.cpp.
References EXPECT_EQ(), and services::ConnectionSerial::ReceiveStream().
 {
     Initialization();
     ExpectWindowSizeUpdateWithComplete(9);
     ContentMessageReceivedAndObserverNotified({ 0xf9, 0xf9, 0xf9, 0xfa, 0xf9, 0xfb, 0xf9, 0xfc, 0xf9, 0xfd, 0xf9, 0xfe });
     infra::SharedPtr<infra::StreamReader> reader = connection->ReceiveStream();
     EXPECT_EQ(6, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({ 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe }), reader->ExtractContiguousRange(6));
     AckReceivedAndExpectUpdate(6);
     ExpectWindowSizeUpdateWithComplete(5);
     ContentMessageReceivedAndObserverNotified({ 0xf9, 0xf9, '1', '2', '3', '4', 0xf9, 0xfe });
     reader = connection->ReceiveStream();
     EXPECT_EQ(6, reader->Available());
     EXPECT_EQ(std::vector<uint8_t>({ 0xf9, '1', '2', '3', '4', 0xfe }), reader->ExtractContiguousRange(6));
 }
TEST_F() [45/46]
TEST_F (ConnectionSerialTest , scrap_bytes_received_after_initialization_are_scrapped_and_connection_is_reset)
Definition at line 903 of file TestConnectionSerial.cpp.
 {
     Initialization();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 'a' });
     ExpectAndCompleteWindowSizeRequest();
     Initialization();
 }
TEST_F() [46/46]
TEST_F (ConnectionSerialTest , reset_connection_during_a_content_send)
Definition at line 951 of file TestConnectionSerial.cpp.
 {
     Initialization();
     GetAndWriteToSendStream({ '1' });
     EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>({ 0xfd, static_cast<uint8_t>(1 >> 8), static_cast<uint8_t>(1) })))
         .WillOnce(testing::InvokeWithoutArgs([this]()
     {
         WindowSizeRequestReceived();
     }));
     EXPECT_CALL(serialCommunication, SendDataMock(std::vector<uint8_t>({ '1' })));
     ExecuteAllActions();
     serialCommunication.actionOnCompletion();
     ExpectWindowSizeRequest();
     serialCommunication.actionOnCompletion();
     ExecuteAllActions();
     serialCommunication.actionOnCompletion();
     Initialization();
 }
TEST_P() [1/2]
TEST_P (ConnectionSerialTestHeaderBytesTest , unescaped_header_bytes_received_midcontent_message_are_discarded_and_connection_state_is_reset1)
Definition at line 918 of file TestConnectionSerial.cpp.
 {
     Initialization();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfd });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ GetParam() });
     ExpectAndCompleteWindowSizeRequest();
 }
TEST_P() [2/2]
TEST_P (ConnectionSerialTestHeaderBytesTest , unescaped_header_bytes_received_midcontent_message_are_discarded_and_connection_state_is_reset2)
Definition at line 930 of file TestConnectionSerial.cpp.
 {
     Initialization();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xfd });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 5 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ '1' });
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     EXPECT_CALL(observer, DataReceived());
     ExpectAndCompleteUpdate(4);
     ExecuteAllActions();
     serialCommunication.dataReceived(std::vector<uint8_t>{ 0xf9 });
     serialCommunication.dataReceived(std::vector<uint8_t>{ GetParam() });
     ExpectAndCompleteWindowSizeRequest();
 }