EMil: SntpClientTest Class Reference
SntpClientTest Class Reference
Public Member Functions
SntpClientTest ()
void DataReceived (std::vector< uint8_t > &data)
void HeaderReceived (uint8_t header)
void KissOfDeathReceived (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< services::DatagramFactoryMock > factory
testing::StrictMock< services::DatagramExchangeMock > datagramExchange
infra::SharedPtr< services::DatagramExchangeMock > datagramExchangePtr
services::TimeWithLocalization timeWithLocalization
services::SntpClient sntpClient
testing::StrictMock< services::SntpResultObserverMock > sntpObserver
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 10 of file TestSntpClient.cpp.
Constructor & Destructor Documentation
SntpClientTest()
SntpClientTest::SntpClientTest () inline
Definition at line 15 of file TestSntpClient.cpp.
         : datagramExchangePtr(infra::UnOwnedSharedPtr(datagramExchange))
         , sntpClient(factory, timeWithLocalization)
         , sntpObserver(sntpClient)
     {}
Member Function Documentation
DataReceived()
void SntpClientTest::DataReceived (std::vector< uint8_t > & data) inline
Definition at line 21 of file TestSntpClient.cpp.
References data, services::SntpClient::DataReceived(), infra::MakeRange(), and sntpClient.
Referenced by HeaderReceived(), and KissOfDeathReceived().
     {
         infra::ByteInputStreamReader requestReader(infra::MakeRange(data));
         sntpClient.DataReceived(requestReader, services::Udpv4Socket{ { 1, 2, 3, 4 }, 123 });
     }
HeaderReceived()
void SntpClientTest::HeaderReceived (uint8_t header) inline
Definition at line 27 of file TestSntpClient.cpp.
References data, and DataReceived().
     {
         std::vector<uint8_t> data{ 0x00, 0x02, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00,
                                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                    0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
                                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                    0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00 };
         data.front() = header;
         DataReceived(data);
     }
KissOfDeathReceived()
void SntpClientTest::KissOfDeathReceived (uint8_t a, uint8_t b, uint8_t c, uint8_t d) inline
Definition at line 40 of file TestSntpClient.cpp.
References DataReceived(), services::SntpClient::SendStreamAvailable(), sntpClient, and infra::UnOwnedSharedPtr().
     {
         infra::ByteOutputStreamWriter::WithStorage<512> response;
         sntpClient.SendStreamAvailable(infra::UnOwnedSharedPtr(response));
         DataReceived(std::vector<uint8_t>{ 0x24, 0x00, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x00, 0x00, a,    b,    c,    d,
             0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
             0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
             0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00,
             0x83, 0xaa, 0x7e, 0x80, 0x00, 0x00, 0x00, 0x00 });
     }
Member Data Documentation
datagramExchange
testing::StrictMock<services::DatagramExchangeMock> SntpClientTest::datagramExchange
Definition at line 53 of file TestSntpClient.cpp.
datagramExchangePtr
infra::SharedPtr<services::DatagramExchangeMock> SntpClientTest::datagramExchangePtr
Definition at line 54 of file TestSntpClient.cpp.
factory
testing::StrictMock<services::DatagramFactoryMock> SntpClientTest::factory
Definition at line 52 of file TestSntpClient.cpp.
sntpClient
services::SntpClient SntpClientTest::sntpClient
Definition at line 56 of file TestSntpClient.cpp.
Referenced by DataReceived(), and KissOfDeathReceived().
sntpObserver
testing::StrictMock<services::SntpResultObserverMock> SntpClientTest::sntpObserver
Definition at line 57 of file TestSntpClient.cpp.
timeWithLocalization
services::TimeWithLocalization SntpClientTest::timeWithLocalization
Definition at line 55 of file TestSntpClient.cpp.
The documentation for this class was generated from the following file:
TestSntpClient.cpp