EMil: TestTimer.cpp File Reference
TestTimer.cpp File Reference
Classes
class TimerTest
Functions
TEST_F (TimerTest, SingleShotTimerTriggersOnceAfterDuration)
TEST_F (TimerTest, SingleShotTimerIsCancellable)
TEST_F (TimerTest, SingleShotTimerTakesResolutionIntoAccount)
TEST_F (TimerTest, TwoTimersTriggerInOrder)
TEST_F (TimerTest, RepeatingTimerTriggersRepeatedly)
TEST_F (TimerTest, RepeatingTimerTriggersImmediately)
TEST_F (TimerTest, RepeatingTimerTriggersRepeatedlyAfterReset)
TEST_F (TimerTest, RepeatingTimerTriggersImmediatelyAfterReset)
TEST_F (TimerTest, RepeatingTimerIsCancellable)
TEST_F (TimerTest, RepeatingTimerTakesResolutionIntoAccount)
TEST_F (TimerTest, TestTimerNotArmedAfterConstruction)
TEST_F (TimerTest, TestTimerArmed)
TEST_F (TimerTest, TestTimerNotArmedAfterTrigger)
TEST_F (TimerTest, TestTimerStaysArmedAfterRepeatedTrigger)
TEST_F (TimerTest, TestTimerCancel)
TEST_F (TimerTest, TestTimerIsNotArmedAfterCancel)
Function Documentation
TEST_F() [1/16]
TEST_F (TimerTest , SingleShotTimerTriggersOnceAfterDuration)
Definition at line 11 of file TestTimer.cpp.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     infra::TimerSingleShot timer(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(5));
 };
TEST_F() [2/16]
TEST_F (TimerTest , SingleShotTimerIsCancellable)
Definition at line 21 of file TestTimer.cpp.
References infra::Timer::Cancel().
 {
     infra::MockCallback<void(infra::TimePoint)> callback;
     infra::TimerSingleShot timer(std::chrono::seconds(1), [this, &callback]() { callback.callback(systemTimerService.Now()); });
     timer.Cancel();
     ForwardTime(std::chrono::seconds(5));
 };
TEST_F() [3/16]
TEST_F (TimerTest , SingleShotTimerTakesResolutionIntoAccount)
Definition at line 32 of file TestTimer.cpp.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(2)));
     systemTimerService.SetResolution(std::chrono::seconds(1));
     infra::TimerSingleShot timer(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(5));
 };
TEST_F() [4/16]
TEST_F (TimerTest , TwoTimersTriggerInOrder)
Definition at line 43 of file TestTimer.cpp.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(2)));
     infra::TimerSingleShot timer1(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     infra::TimerSingleShot timer2(std::chrono::seconds(2), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(5));
 };
TEST_F() [5/16]
TEST_F (TimerTest , RepeatingTimerTriggersRepeatedly)
Definition at line 55 of file TestTimer.cpp.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(2)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(3)));
     infra::TimerRepeating timer(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(3));
 };
TEST_F() [6/16]
TEST_F (TimerTest , RepeatingTimerTriggersImmediately)
Definition at line 67 of file TestTimer.cpp.
References infra::triggerImmediately.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(0)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     infra::TimerRepeating timer(std::chrono::seconds(1), [&callback]() { callback.callback(); }, infra::triggerImmediately);
     ForwardTime(std::chrono::seconds(1));
 }
TEST_F() [7/16]
TEST_F (TimerTest , RepeatingTimerTriggersRepeatedlyAfterReset)
Definition at line 78 of file TestTimer.cpp.
References infra::TimerRepeating::Start().
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(2)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(3)));
     infra::TimerRepeating timer;
     timer.Start(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(3));
 };
TEST_F() [8/16]
TEST_F (TimerTest , RepeatingTimerTriggersImmediatelyAfterReset)
Definition at line 91 of file TestTimer.cpp.
References infra::TimerRepeating::Start(), and infra::triggerImmediately.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(0)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     infra::TimerRepeating timer;
     timer.Start(std::chrono::seconds(1), [&callback]() { callback.callback(); }, infra::triggerImmediately);
     ForwardTime(std::chrono::seconds(1));
 }
TEST_F() [9/16]
TEST_F (TimerTest , RepeatingTimerIsCancellable)
Definition at line 103 of file TestTimer.cpp.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::seconds(1)));
     infra::TimerRepeating timer(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(1));
     timer.Cancel();
     ForwardTime(std::chrono::seconds(1));
 };
TEST_F() [10/16]
TEST_F (TimerTest , RepeatingTimerTakesResolutionIntoAccount)
Definition at line 115 of file TestTimer.cpp.
 {
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback()).With(After(std::chrono::milliseconds(1050)));
     EXPECT_CALL(callback, callback()).With(After(std::chrono::milliseconds(2050)));
     systemTimerService.SetResolution(std::chrono::milliseconds(50));
     infra::TimerRepeating timer(std::chrono::seconds(1), [&callback]() { callback.callback(); });
     ForwardTime(std::chrono::seconds(3));
 };
TEST_F() [11/16]
TEST_F (TimerTest , TestTimerNotArmedAfterConstruction)
Definition at line 127 of file TestTimer.cpp.
References infra::Timer::Armed(), and EXPECT_FALSE().
 {
     infra::TimerSingleShot timer;
     EXPECT_FALSE(timer.Armed());
 }
TEST_F() [12/16]
TEST_F (TimerTest , TestTimerArmed)
Definition at line 134 of file TestTimer.cpp.
References EXPECT_TRUE().
 {
     infra::TimerSingleShot timer(std::chrono::seconds(1), []() {});
     EXPECT_TRUE(timer.Armed());
 }
TEST_F() [13/16]
TEST_F (TimerTest , TestTimerNotArmedAfterTrigger)
Definition at line 141 of file TestTimer.cpp.
References EXPECT_FALSE().
 {
     infra::TimerSingleShot timer(std::chrono::seconds(1), []() {});
     ForwardTime(std::chrono::seconds(5));
     EXPECT_FALSE(timer.Armed());
 }
TEST_F() [14/16]
TEST_F (TimerTest , TestTimerStaysArmedAfterRepeatedTrigger)
Definition at line 149 of file TestTimer.cpp.
References EXPECT_TRUE().
 {
     infra::TimerRepeating timer(std::chrono::seconds(1), []() {});
     ForwardTime(std::chrono::seconds(5));
     EXPECT_TRUE(timer.Armed());
 }
TEST_F() [15/16]
TEST_F (TimerTest , TestTimerCancel)
Definition at line 157 of file TestTimer.cpp.
References infra::Timer::Cancel().
 {
     testing::StrictMock<infra::MockCallback<void()>> callback;
     infra::TimerSingleShot timer(std::chrono::seconds(1), [&callback]() { callback.callback();  });
     timer.Cancel();
     ForwardTime(std::chrono::seconds(5));
 }
TEST_F() [16/16]
TEST_F (TimerTest , TestTimerIsNotArmedAfterCancel)
Definition at line 167 of file TestTimer.cpp.
References infra::Timer::Cancel(), and EXPECT_FALSE().
 {
     infra::TimerSingleShot timer(std::chrono::seconds(1), []() {});
     timer.Cancel();
     EXPECT_FALSE(timer.Armed());
 }