EMil: services::HttpRequestFormatter Class Reference
services::HttpRequestFormatter Class Reference
#include <HttpClientImpl.hpp>
Public Member Functions
HttpRequestFormatter (HttpVerb verb, infra::BoundedConstString hostname, infra::BoundedConstString requestTarget, const HttpHeaders headers)
HttpRequestFormatter (HttpVerb verb, infra::BoundedConstString hostname, infra::BoundedConstString requestTarget, infra::BoundedConstString content, const HttpHeaders headers)
HttpRequestFormatter (HttpVerb verb, infra::BoundedConstString hostname, infra::BoundedConstString requestTarget, std::size_t contentSize, const HttpHeaders headers)
std::size_t Size () const
void Write (infra::TextOutputStream stream) const
Private Member Functions
void AddContentLength (std::size_t size)
std::size_t HeadersSize () const
Private Attributes
HttpVerb verb
infra::BoundedConstString requestTarget
infra::BoundedConstString content
infra::BoundedString::WithStorage< 8 > contentLength
infra::Optional< HttpHeader > contentLengthHeader
HttpHeader hostHeader
const HttpHeaders headers
Detailed Description
Definition at line 13 of file HttpClientImpl.hpp.
Constructor & Destructor Documentation
HttpRequestFormatter() [1/3]
services::HttpRequestFormatter::HttpRequestFormatter (HttpVerb verb, infra::BoundedConstString hostname, infra::BoundedConstString requestTarget, const HttpHeaders headers)
Definition at line 16 of file HttpClientImpl.cpp.
         : HttpRequestFormatter(verb, hostname, requestTarget, infra::BoundedConstString(), headers)
     {}
HttpRequestFormatter() [2/3]
services::HttpRequestFormatter::HttpRequestFormatter (HttpVerb verb, infra::BoundedConstString hostname, infra::BoundedConstString requestTarget, infra::BoundedConstString content, const HttpHeaders headers)
Definition at line 20 of file HttpClientImpl.cpp.
References AddContentLength(), content, infra::BoundedStringBase< T >::empty(), and infra::BoundedStringBase< T >::size().
         : verb(verb)
         , requestTarget(requestTarget)
         , content(content)
         , hostHeader("host", hostname)
         , headers(headers)
     {
         if (!content.empty())
             AddContentLength(content.size());
     }
HttpRequestFormatter() [3/3]
services::HttpRequestFormatter::HttpRequestFormatter (HttpVerb verb, infra::BoundedConstString hostname, infra::BoundedConstString requestTarget, std::size_t contentSize, const HttpHeaders headers)
Definition at line 31 of file HttpClientImpl.cpp.
References AddContentLength().
         : verb(verb)
         , requestTarget(requestTarget)
         , hostHeader("host", hostname)
         , headers(headers)
     {
         AddContentLength(contentSize);
     }
Member Function Documentation
AddContentLength()
void services::HttpRequestFormatter::AddContentLength (std::size_t size) private
Definition at line 61 of file HttpClientImpl.cpp.
References contentLength, and contentLengthHeader.
Referenced by HttpRequestFormatter().
     {
         infra::StringOutputStream contentLengthStream(contentLength);
         contentLengthStream << size;
         contentLengthHeader.Emplace("content-length", contentLength);
     }
HeadersSize()
std::size_t services::HttpRequestFormatter::HeadersSize () const private
Definition at line 68 of file HttpClientImpl.cpp.
References contentLengthHeader, headers, hostHeader, and services::HttpHeader::Size().
Referenced by Size().
     {
         std::size_t headerSize = 0;
         for (auto&& header : headers)
             headerSize += (header.Size() + crlf.size());
         if (contentLengthHeader)
             headerSize += contentLengthHeader->Size() + crlf.size();
         headerSize += hostHeader.Size() + crlf.size();
         return headerSize;
     }
Size()
std::size_t services::HttpRequestFormatter::Size () const
Definition at line 40 of file HttpClientImpl.cpp.
References content, HeadersSize(), services::HttpVerbToString(), requestTarget, infra::BoundedStringBase< T >::size(), and verb.
     {
         return HttpVerbToString(verb).size() + requestTarget.size() + httpVersion.size() + HeadersSize() + (2 * crlf.size()) + (2 * sp.size()) + content.size();
     }
Write()
void services::HttpRequestFormatter::Write (infra::TextOutputStream stream) const
Definition at line 45 of file HttpClientImpl.cpp.
References content, contentLengthHeader, headers, hostHeader, requestTarget, and verb.
     {
         stream << verb << sp << requestTarget << sp << httpVersion << crlf;
         for (auto&& header : headers)
             stream << header << crlf;
         stream << hostHeader << crlf;
         if (contentLengthHeader)
             stream << *contentLengthHeader << crlf;
         stream << crlf;
         stream << content;
     }
Member Data Documentation
content
infra::BoundedConstString services::HttpRequestFormatter::content private
Definition at line 30 of file HttpClientImpl.hpp.
Referenced by HttpRequestFormatter(), Size(), and Write().
contentLength
infra::BoundedString::WithStorage<8> services::HttpRequestFormatter::contentLength private
Definition at line 31 of file HttpClientImpl.hpp.
Referenced by AddContentLength().
contentLengthHeader
infra::Optional<HttpHeader> services::HttpRequestFormatter::contentLengthHeader private
Definition at line 32 of file HttpClientImpl.hpp.
Referenced by AddContentLength(), HeadersSize(), and Write().
headers
const HttpHeaders services::HttpRequestFormatter::headers private
Definition at line 34 of file HttpClientImpl.hpp.
Referenced by HeadersSize(), and Write().
hostHeader
HttpHeader services::HttpRequestFormatter::hostHeader private
Definition at line 33 of file HttpClientImpl.hpp.
Referenced by HeadersSize(), and Write().
requestTarget
infra::BoundedConstString services::HttpRequestFormatter::requestTarget private
Definition at line 29 of file HttpClientImpl.hpp.
Referenced by Size(), and Write().
verb
HttpVerb services::HttpRequestFormatter::verb private
Definition at line 28 of file HttpClientImpl.hpp.
Referenced by Size(), and Write().
The documentation for this class was generated from the following files:
HttpClientImpl.hpp
HttpClientImpl.cpp