EMil: services::ListenerBsd Class Reference
services::ListenerBsd Class Reference
#include <ConnectionBsd.hpp>
Public Member Functions
ListenerBsd (EventDispatcherWithNetwork &network, uint16_t port, services::ServerConnectionObserverFactory &factory)
~ListenerBsd ()
void Accept ()
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Private Attributes
EventDispatcherWithNetwork & network
services::ServerConnectionObserverFactory & factory
int listenSocket
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 84 of file ConnectionBsd.hpp.
Constructor & Destructor Documentation
ListenerBsd()
services::ListenerBsd::ListenerBsd (EventDispatcherWithNetwork & network, uint16_t port, services::ServerConnectionObserverFactory & factory)
Definition at line 194 of file ConnectionBsd.cpp.
References listenSocket, network, and services::EventDispatcherWithNetwork::RegisterListener().
         : network(network)
         , factory(factory)
     {
         listenSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
         assert(listenSocket != -1);
         sockaddr_in address = {};
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = htonl(INADDR_ANY);
         address.sin_port = htons(port);
         if (bind(listenSocket, reinterpret_cast<sockaddr*>(&address), sizeof(address)) == -1)
             std::abort();
         if (listen(listenSocket, 1) == -1)
             std::abort();
         SetNonBlocking(listenSocket);
         network.RegisterListener(*this);
     }
~ListenerBsd()
services::ListenerBsd::~ListenerBsd ()
Definition at line 215 of file ConnectionBsd.cpp.
References services::EventDispatcherWithNetwork::DeregisterListener(), and network.
     {
         network.DeregisterListener(*this);
     }
Member Function Documentation
Accept()
void services::ListenerBsd::Accept ()
Definition at line 220 of file ConnectionBsd.cpp.
References services::ServerConnectionObserverFactory::ConnectionAccepted(), factory, listenSocket, and network.
     {
         auto acceptedSocket = accept(listenSocket, NULL, NULL);
         assert(acceptedSocket != -1);
         infra::SharedPtr<ConnectionBsd> connection = infra::MakeSharedOnHeap<ConnectionBsd>(network, acceptedSocket);
         factory.ConnectionAccepted([connection](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             if (connectionObserver)
                 connection->SetObserver(connectionObserver);
         }, connection->Ipv4Address());
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 94 of file ConnectionBsd.hpp.
Member Data Documentation
factory
services::ServerConnectionObserverFactory& services::ListenerBsd::factory private
Definition at line 97 of file ConnectionBsd.hpp.
Referenced by Accept().
listenSocket
int services::ListenerBsd::listenSocket private
Definition at line 98 of file ConnectionBsd.hpp.
Referenced by Accept(), and ListenerBsd().
network
EventDispatcherWithNetwork& services::ListenerBsd::network private
Definition at line 96 of file ConnectionBsd.hpp.
Referenced by Accept(), ListenerBsd(), and ~ListenerBsd().
The documentation for this class was generated from the following files:
ConnectionBsd.hpp
ConnectionBsd.cpp