EMil: infra::LimitedStreamReader Class Reference
infra::LimitedStreamReader Class Reference
#include <LimitedInputStream.hpp>
Public Member Functions
LimitedStreamReader (StreamReader &input, uint32_t length)
LimitedStreamReader (const LimitedStreamReader &other)
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy) override
virtual ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
Private Attributes
StreamReader & input
uint32_t length
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 8 of file LimitedInputStream.hpp.
Constructor & Destructor Documentation
LimitedStreamReader() [1/2]
infra::LimitedStreamReader::LimitedStreamReader (StreamReader & input, uint32_t length)
Definition at line 5 of file LimitedInputStream.cpp.
         : input(input)
         , length(length)
     {}
LimitedStreamReader() [2/2]
infra::LimitedStreamReader::LimitedStreamReader (const LimitedStreamReader & other)
Definition at line 10 of file LimitedInputStream.cpp.
         : input(other.input)
         , length(other.length)
     {}
Member Function Documentation
Available()
std::size_t infra::LimitedStreamReader::Available () const override virtual
Implements infra::StreamReader.
Definition at line 50 of file LimitedInputStream.cpp.
References infra::StreamReader::Available(), input, and length.
     {
         return std::min<uint32_t>(length, input.Available());
     }
Empty()
bool infra::LimitedStreamReader::Empty () const override virtual
Implements infra::StreamReader.
Definition at line 45 of file LimitedInputStream.cpp.
References infra::StreamReader::Empty(), input, and length.
     {
         return length == 0 || input.Empty();
     }
Extract()
void infra::LimitedStreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 15 of file LimitedInputStream.cpp.
References infra::StreamReader::Extract(), input, length, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         errorPolicy.ReportResult(length >= range.size());
         range.shrink_from_back_to(length);
         length -= range.size();
         input.Extract(range, errorPolicy);
     }
ExtractContiguousRange()
ConstByteRange infra::LimitedStreamReader::ExtractContiguousRange (std::size_t max) override virtual
Implements infra::StreamReader.
Definition at line 33 of file LimitedInputStream.cpp.
References infra::StreamReader::ExtractContiguousRange(), input, length, and infra::MemoryRange< T >::size().
     {
         ConstByteRange result = input.ExtractContiguousRange(std::min<std::size_t>(length, max));
         length -= result.size();
         return result;
     }
Peek()
uint8_t infra::LimitedStreamReader::Peek (StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamReader.
Definition at line 23 of file LimitedInputStream.cpp.
References input, length, infra::StreamReader::Peek(), and infra::StreamErrorPolicy::ReportResult().
     {
         errorPolicy.ReportResult(length != 0);
         if (length != 0)
             return input.Peek(errorPolicy);
         else
             return 0;
     }
PeekContiguousRange()
ConstByteRange infra::LimitedStreamReader::PeekContiguousRange (std::size_t start) override virtual
Implements infra::StreamReader.
Definition at line 40 of file LimitedInputStream.cpp.
     {
         return input.PeekContiguousRange(start);
     }
Member Data Documentation
input
StreamReader& infra::LimitedStreamReader::input private
Definition at line 24 of file LimitedInputStream.hpp.
Referenced by Available(), Empty(), Extract(), ExtractContiguousRange(), and Peek().
length
uint32_t infra::LimitedStreamReader::length private
Definition at line 25 of file LimitedInputStream.hpp.
Referenced by Available(), Empty(), Extract(), ExtractContiguousRange(), and Peek().
The documentation for this class was generated from the following files:
LimitedInputStream.hpp
LimitedInputStream.cpp