EMil: infra::StreamReaderWithRewinding Class Reference
infra::StreamReaderWithRewinding Class Reference abstract
#include <InputStream.hpp>
Public Member Functions
virtual std::size_t ConstructSaveMarker () const =0
virtual void Rewind (std::size_t marker)=0
Public Member Functions inherited from infra::StreamReader
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy)=0
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy)=0
virtual ConstByteRange ExtractContiguousRange (std::size_t max)=0
virtual ConstByteRange PeekContiguousRange (std::size_t start)=0
virtual bool Empty () const =0
virtual std::size_t Available () const =0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 34 of file InputStream.hpp.
Member Function Documentation
ConstructSaveMarker()
virtual std::size_t infra::StreamReaderWithRewinding::ConstructSaveMarker () const pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::StdVectorInputStreamReader, and infra::StringInputStreamReader.
Referenced by services::HttpClientImpl::HttpResponseParser::ParseHeaders().
Rewind()
virtual void infra::StreamReaderWithRewinding::Rewind (std::size_t marker) pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::StdVectorInputStreamReader, and infra::StringInputStreamReader.
Referenced by services::HttpClientImpl::HttpResponseParser::ParseHeaders(), and services::HttpClientImpl::HttpResponseParser::ParseStatusLine().
The documentation for this class was generated from the following file:
InputStream.hpp