EMil: application::ImageUpgraderInternalFlash Class Reference
application::ImageUpgraderInternalFlash Class Reference
#include <ImageUpgraderInternalFlash.hpp>
Public Types
template<std::size_t Size>
using WithBlockSize = infra::WithStorage< ImageUpgraderInternalFlash, std::array< uint8_t, Size > >
Public Member Functions
ImageUpgraderInternalFlash (infra::ByteRange buffer, const char *targetName, Decryptor &decryptor, hal::SynchronousFlash &internalFlash, uint32_t destinationAddressOffset)
virtual uint32_t Upgrade (hal::SynchronousFlash &upgradePackFlash, uint32_t imageAddress, uint32_t imageSize, uint32_t destinationAddress) override
void SetFlash (hal::SynchronousFlash &flash)
Public Member Functions inherited from application::ImageUpgrader
ImageUpgrader (const char *targetName, Decryptor &decryptor)
ImageUpgrader (const ImageUpgrader &other)=delete
ImageUpgrader & operator= (const ImageUpgrader &other)=delete
const char * TargetName () const
Decryptor & ImageDecryptor ()
Private Attributes
infra::ByteRange buffer
hal::SynchronousFlash * internalFlash
uint32_t destinationAddressOffset
Additional Inherited Members
Protected Member Functions inherited from application::ImageUpgrader
~ImageUpgrader ()=default
Detailed Description
Definition at line 9 of file ImageUpgraderInternalFlash.hpp.
Member Typedef Documentation
WithBlockSize
template<std::size_t Size> using application::ImageUpgraderInternalFlash::WithBlockSize = infra::WithStorage<ImageUpgraderInternalFlash, std::array<uint8_t, Size> >
Definition at line 14 of file ImageUpgraderInternalFlash.hpp.
Constructor & Destructor Documentation
ImageUpgraderInternalFlash()
application::ImageUpgraderInternalFlash::ImageUpgraderInternalFlash (infra::ByteRange buffer, const char * targetName, Decryptor & decryptor, hal::SynchronousFlash & internalFlash, uint32_t destinationAddressOffset)
Definition at line 5 of file ImageUpgraderInternalFlash.cpp.
         : ImageUpgrader(targetName, decryptor)
         , buffer(buffer)
         , internalFlash(&internalFlash)
         , destinationAddressOffset(destinationAddressOffset)
     {}
Member Function Documentation
SetFlash()
void application::ImageUpgraderInternalFlash::SetFlash (hal::SynchronousFlash & flash)
Definition at line 34 of file ImageUpgraderInternalFlash.cpp.
References internalFlash.
     {
         internalFlash = &flash;
     }
Upgrade()
uint32_t application::ImageUpgraderInternalFlash::Upgrade (hal::SynchronousFlash & upgradePackFlash, uint32_t imageAddress, uint32_t imageSize, uint32_t destinationAddress) override virtual
Implements application::ImageUpgrader.
Definition at line 12 of file ImageUpgraderInternalFlash.cpp.
References buffer, application::Decryptor::DecryptPart(), destinationAddressOffset, hal::SynchronousFlash::EraseSectors(), infra::Head(), application::ImageUpgrader::ImageDecryptor(), internalFlash, hal::SynchronousFlash::ReadBuffer(), hal::SynchronousFlash::SectorOfAddress(), infra::MemoryRange< T >::size(), and hal::SynchronousFlash::WriteBuffer().
     {
         destinationAddress += destinationAddressOffset;
         internalFlash->EraseSectors(internalFlash->SectorOfAddress(destinationAddress), internalFlash->SectorOfAddress(destinationAddress + imageSize - 1) + 1);
         uint32_t imageAddressStart = imageAddress;
         while (imageAddress - imageAddressStart < imageSize)
         {
             infra::ByteRange bufferRange(infra::Head(buffer, imageSize - (imageAddress - imageAddressStart)));
             upgradePackFlash.ReadBuffer(bufferRange, imageAddress);
             imageAddress += bufferRange.size();
             ImageDecryptor().DecryptPart(bufferRange);
             internalFlash->WriteBuffer(bufferRange, destinationAddress);
             destinationAddress += bufferRange.size();
         }
         return 0;
     }
Member Data Documentation
buffer
infra::ByteRange application::ImageUpgraderInternalFlash::buffer private
Definition at line 23 of file ImageUpgraderInternalFlash.hpp.
Referenced by Upgrade().
destinationAddressOffset
uint32_t application::ImageUpgraderInternalFlash::destinationAddressOffset private
Definition at line 25 of file ImageUpgraderInternalFlash.hpp.
Referenced by Upgrade().
internalFlash
hal::SynchronousFlash* application::ImageUpgraderInternalFlash::internalFlash private
Definition at line 24 of file ImageUpgraderInternalFlash.hpp.
Referenced by SetFlash(), and Upgrade().
The documentation for this class was generated from the following files:
ImageUpgraderInternalFlash.hpp
ImageUpgraderInternalFlash.cpp