EMil: infra::detail::InvokerFunctions< Result(Args...), ExtraSize > Struct Template Reference
infra::detail::InvokerFunctions< Result(Args...), ExtraSize > Struct Template Reference
#include <Function.hpp>
Classes
struct VirtualMethodTable
Public Types
typedef InvokerFunctions< Result(Args...), ExtraSize > InvokerFunctionsType
typedef std::aligned_storage< ExtraSize, std::alignment_of< UTIL_FUNCTION_ALIGNMENT >::value >::type StorageType
Public Member Functions
template<class F >
const InvokerFunctions< Result(Args...), ExtraSize >::VirtualMethodTable * StaticVirtualMethodTable (typename std::enable_if< std::is_trivial< F >::value >::type *)
template<class F >
const InvokerFunctions< Result(Args...), ExtraSize >::VirtualMethodTable * StaticVirtualMethodTable (typename std::enable_if<!std::is_trivial< F >::value >::type *)
Static Public Member Functions
template<class F >
static Result StaticInvoke (const InvokerFunctionsType &invokerFunctions, Args... args)
template<class F >
static void StaticDestruct (InvokerFunctionsType &invokerFunctions)
template<class F >
static void StaticCopyConstruct (const InvokerFunctionsType &from, InvokerFunctionsType &to)
template<class F >
static const VirtualMethodTable * StaticVirtualMethodTable (typename std::enable_if< std::is_trivial< F >::value >::type *=0)
template<class F >
static const VirtualMethodTable * StaticVirtualMethodTable (typename std::enable_if<!std::is_trivial< F >::value >::type *=0)
template<class F >
static void Construct (InvokerFunctionsType &invokerFunctions, F &&f)
Public Attributes
const VirtualMethodTable * virtualMethodTable = nullptr
StorageType data
Detailed Description
template<std::size_t ExtraSize, class Result, class... Args>
struct infra::detail::InvokerFunctions< Result(Args...), ExtraSize >
Definition at line 53 of file Function.hpp.
Member Typedef Documentation
InvokerFunctionsType
template<std::size_t ExtraSize, class Result , class... Args> typedef InvokerFunctions<Result(Args...), ExtraSize> infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::InvokerFunctionsType
Definition at line 55 of file Function.hpp.
StorageType
template<std::size_t ExtraSize, class Result , class... Args> typedef std::aligned_storage<ExtraSize, std::alignment_of<UTIL_FUNCTION_ALIGNMENT>::value>::type infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StorageType
Definition at line 72 of file Function.hpp.
Member Function Documentation
Construct()
template<std::size_t ExtraSize, class Result , class... Args> template<class F > void infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::Construct (InvokerFunctionsType & invokerFunctions, F && f) static
Definition at line 273 of file Function.hpp.
References data, value, and virtualMethodTable.
         {
             static_assert(sizeof(F) <= ExtraSize, "Not enough static storage availabe for construction of derived type");
             static_assert(std::alignment_of<F>::value <= sizeof(UTIL_FUNCTION_ALIGNMENT), "Alignment of U is larger than alignment of this function");
             new (&invokerFunctions.data) F(std::forward<F>(f));                                                                                     //TICS !OAL#011
             std::memset(reinterpret_cast<char*>(&invokerFunctions.data) + sizeof(F), 0, ExtraSize - sizeof(F));                                     //TICS !COV_CPP_NO_EFFECT_13
             invokerFunctions.virtualMethodTable = StaticVirtualMethodTable<F>();
         }
StaticCopyConstruct()
template<std::size_t ExtraSize, class Result , class... Args> template<class F > void infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticCopyConstruct (const InvokerFunctionsType & from, InvokerFunctionsType & to) static
Definition at line 246 of file Function.hpp.
References data, and virtualMethodTable.
         {
             new (&to.data) F(reinterpret_cast<const F&>(from.data));                                                                                //TICS !OAL#011
             std::memset(reinterpret_cast<char*>(&to.data) + sizeof(F), 0, ExtraSize - sizeof(F));                                                   //TICS !COV_CPP_NO_EFFECT_13
             to.virtualMethodTable = StaticVirtualMethodTable<F>();
         }
StaticDestruct()
template<std::size_t ExtraSize, class Result , class... Args> template<class F > void infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticDestruct (InvokerFunctionsType & invokerFunctions) static
Definition at line 238 of file Function.hpp.
References data, and virtualMethodTable.
         {
             reinterpret_cast<F&>(invokerFunctions.data).~F();                                                                                       //TICS !CFL#024
             invokerFunctions.virtualMethodTable = nullptr;
         }
StaticInvoke()
template<std::size_t ExtraSize, class Result , class... Args> template<class F > Result infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticInvoke (const InvokerFunctionsType & invokerFunctions, Args... args) static
Definition at line 231 of file Function.hpp.
References data.
         {
             return (reinterpret_cast<const F&>(invokerFunctions.data))(args...);
         }
StaticVirtualMethodTable() [1/4]
template<std::size_t ExtraSize, class Result , class... Args> template<class F > static const VirtualMethodTable* infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticVirtualMethodTable (typename std::enable_if< std::is_trivial< F >::value >::type * = 0) static
StaticVirtualMethodTable() [2/4]
template<std::size_t ExtraSize, class Result , class... Args> template<class F > static const VirtualMethodTable* infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticVirtualMethodTable (typename std::enable_if<!std::is_trivial< F >::value >::type * = 0) static
StaticVirtualMethodTable() [3/4]
template<std::size_t ExtraSize, class Result , class... Args> template<class F > const InvokerFunctions<Result(Args...), ExtraSize>::VirtualMethodTable* infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticVirtualMethodTable (typename std::enable_if< std::is_trivial< F >::value >::type *)
Definition at line 256 of file Function.hpp.
         {
             static const VirtualMethodTable table = { &StaticInvoke<F>, nullptr, nullptr };
             return &table;
         }
StaticVirtualMethodTable() [4/4]
template<std::size_t ExtraSize, class Result , class... Args> template<class F > const InvokerFunctions<Result(Args...), ExtraSize>::VirtualMethodTable* infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::StaticVirtualMethodTable (typename std::enable_if<!std::is_trivial< F >::value >::type *)
Definition at line 265 of file Function.hpp.
         {
             static const VirtualMethodTable table = { &StaticInvoke<F>, &StaticDestruct<F>, &StaticCopyConstruct<F> };
             return &table;
         }
Member Data Documentation
data
template<std::size_t ExtraSize, class Result , class... Args> StorageType infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::data
Definition at line 73 of file Function.hpp.
Referenced by Construct(), StaticCopyConstruct(), StaticDestruct(), and StaticInvoke().
virtualMethodTable
template<std::size_t ExtraSize, class Result , class... Args> const VirtualMethodTable* infra::detail::InvokerFunctions< Result(Args...), ExtraSize >::virtualMethodTable = nullptr
Definition at line 70 of file Function.hpp.
Referenced by Construct(), infra::Function< Result(Args...), ExtraSize >::CopyConstruct(), infra::Function< Result(Args...), ExtraSize >::Destruct(), StaticCopyConstruct(), and StaticDestruct().
The documentation for this struct was generated from the following file:
Function.hpp