EMil: services::ClientConnectionObserverFactoryWithNameResolver Class Reference
services::ClientConnectionObserverFactoryWithNameResolver Class Reference abstract
#include <ConnectionFactoryWithNameResolver.hpp>
Public Types
enum ConnectFailReason { refused, connectionAllocationFailed, nameLookupFailed }
Public Member Functions
virtual infra::BoundedConstString Hostname () const =0
virtual uint16_t Port () const =0
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver)=0
virtual void ConnectionFailed (ConnectFailReason reason)=0
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Protected Member Functions
ClientConnectionObserverFactoryWithNameResolver ()=default
ClientConnectionObserverFactoryWithNameResolver (const ClientConnectionObserverFactoryWithNameResolver &other)=delete
ClientConnectionObserverFactoryWithNameResolver & operator= (const ClientConnectionObserverFactoryWithNameResolver &other)=delete
~ClientConnectionObserverFactoryWithNameResolver ()=default
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 10 of file ConnectionFactoryWithNameResolver.hpp.
Member Enumeration Documentation
ConnectFailReason
enum services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason
Enumerator
refused
connectionAllocationFailed
nameLookupFailed
Definition at line 20 of file ConnectionFactoryWithNameResolver.hpp.
         {
             refused,
             connectionAllocationFailed,
             nameLookupFailed
         };
Constructor & Destructor Documentation
ClientConnectionObserverFactoryWithNameResolver() [1/2]
services::ClientConnectionObserverFactoryWithNameResolver::ClientConnectionObserverFactoryWithNameResolver () protected default
ClientConnectionObserverFactoryWithNameResolver() [2/2]
services::ClientConnectionObserverFactoryWithNameResolver::ClientConnectionObserverFactoryWithNameResolver (const ClientConnectionObserverFactoryWithNameResolver & other) protected delete
~ClientConnectionObserverFactoryWithNameResolver()
services::ClientConnectionObserverFactoryWithNameResolver::~ClientConnectionObserverFactoryWithNameResolver () protected default
Member Function Documentation
ConnectionEstablished()
virtual void services::ClientConnectionObserverFactoryWithNameResolver::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver) pure virtual
Implemented in services::ConnectionFactoryWithNameResolverForTls, and services::HttpClientConnectorImpl< HttpClient, Args >.
Referenced by services::ConnectionFactoryWithNameResolverForTls::ConnectionEstablished().
ConnectionFailed()
virtual void services::ClientConnectionObserverFactoryWithNameResolver::ConnectionFailed (ConnectFailReason reason) pure virtual
Implemented in services::ConnectionFactoryWithNameResolverForTls, and services::HttpClientConnectorImpl< HttpClient, Args >.
Referenced by services::ConnectionFactoryWithNameResolverForTls::ConnectionFailed().
Hostname()
virtual infra::BoundedConstString services::ClientConnectionObserverFactoryWithNameResolver::Hostname () const pure virtual
Implemented in services::ConnectionFactoryWithNameResolverForTls, and services::HttpClientConnectorImpl< HttpClient, Args >.
Referenced by services::ConnectionFactoryWithNameResolverForTls::Hostname().
operator=()
ClientConnectionObserverFactoryWithNameResolver& services::ClientConnectionObserverFactoryWithNameResolver::operator= (const ClientConnectionObserverFactoryWithNameResolver & other) protected delete
Port()
virtual uint16_t services::ClientConnectionObserverFactoryWithNameResolver::Port () const pure virtual
Implemented in services::ConnectionFactoryWithNameResolverForTls, and services::HttpClientConnectorImpl< HttpClient, Args >.
Referenced by services::ConnectionFactoryWithNameResolverForTls::Port().
The documentation for this class was generated from the following file:
ConnectionFactoryWithNameResolver.hpp