EMil: infra::IntrusivePriorityQueue< T, Compare > Class Template Reference
infra::IntrusivePriorityQueue< T, Compare > Class Template Reference
#include <IntrusivePriorityQueue.hpp>
Public Types
typedef detail::IntrusivePriorityQueueNode< T > NodeType
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
Public Member Functions
IntrusivePriorityQueue (const Compare &comp=Compare())
template<class InputIterator >
IntrusivePriorityQueue (InputIterator first, InputIterator last, const Compare &comp=Compare())
IntrusivePriorityQueue (const IntrusivePriorityQueue &)=delete
IntrusivePriorityQueue (IntrusivePriorityQueue &&other)
IntrusivePriorityQueue & operator= (const IntrusivePriorityQueue &)=delete
IntrusivePriorityQueue & operator= (IntrusivePriorityQueue &&other)
bool empty () const
size_type size () const
T & top ()
const T & top () const
void push (const T &value)
void pop ()
void clear ()
void erase (const T &value)
void swap (IntrusivePriorityQueue &x)
Private Member Functions
void swapChildAndParentNodes (T &child, T &parent)
void insertAsLast (T &value)
T & lastNode () const
Private Attributes
T * topNode = nullptr
std::size_t numberOfElements = 0
Compare compare
Detailed Description
template<class T, class Compare = std::less<T>>
class infra::IntrusivePriorityQueue< T, Compare >
Definition at line 22 of file IntrusivePriorityQueue.hpp.
Member Typedef Documentation
const_reference
template<class T, class Compare = std::less<T>> typedef const T& infra::IntrusivePriorityQueue< T, Compare >::const_reference
Definition at line 29 of file IntrusivePriorityQueue.hpp.
NodeType
template<class T, class Compare = std::less<T>> typedef detail::IntrusivePriorityQueueNode<T> infra::IntrusivePriorityQueue< T, Compare >::NodeType
Definition at line 25 of file IntrusivePriorityQueue.hpp.
reference
template<class T, class Compare = std::less<T>> typedef T& infra::IntrusivePriorityQueue< T, Compare >::reference
Definition at line 28 of file IntrusivePriorityQueue.hpp.
size_type
template<class T, class Compare = std::less<T>> typedef std::size_t infra::IntrusivePriorityQueue< T, Compare >::size_type
Definition at line 30 of file IntrusivePriorityQueue.hpp.
value_type
template<class T, class Compare = std::less<T>> typedef T infra::IntrusivePriorityQueue< T, Compare >::value_type
Definition at line 27 of file IntrusivePriorityQueue.hpp.
Constructor & Destructor Documentation
IntrusivePriorityQueue() [1/4]
template<class T , class Compare> infra::IntrusivePriorityQueue< T, Compare >::IntrusivePriorityQueue (const Compare & comp = Compare()) explicit
Definition at line 92 of file IntrusivePriorityQueue.hpp.
         : compare(comp)
     {}
IntrusivePriorityQueue() [2/4]
template<class T , class Compare> template<class InputIterator > infra::IntrusivePriorityQueue< T, Compare >::IntrusivePriorityQueue (InputIterator first, InputIterator last, const Compare & comp = Compare())
Definition at line 98 of file IntrusivePriorityQueue.hpp.
References infra::IntrusivePriorityQueue< T, Compare >::push().
         : compare(comp)
     {
         for (; first != last; ++first)
             push(*first);
     }
IntrusivePriorityQueue() [3/4]
template<class T, class Compare = std::less<T>> infra::IntrusivePriorityQueue< T, Compare >::IntrusivePriorityQueue (const IntrusivePriorityQueue< T, Compare > &) delete
IntrusivePriorityQueue() [4/4]
template<class T , class Compare> infra::IntrusivePriorityQueue< T, Compare >::IntrusivePriorityQueue (IntrusivePriorityQueue< T, Compare > && other)
Definition at line 106 of file IntrusivePriorityQueue.hpp.
         : topNode(other.topNode)
         , numberOfElements(other.numberOfElements)
         , compare(std::move(other.compare))
     {
         other.topNode = nullptr;
         other.numberOfElements = 0;
     }
Member Function Documentation
clear()
template<class T , class Compare > void infra::IntrusivePriorityQueue< T, Compare >::clear ()
Definition at line 205 of file IntrusivePriorityQueue.hpp.
     {
         topNode = nullptr;
         numberOfElements = 0;
     }
empty()
template<class T , class Compare > bool infra::IntrusivePriorityQueue< T, Compare >::empty () const
Definition at line 128 of file IntrusivePriorityQueue.hpp.
     {
         return numberOfElements == 0;
     }
erase()
template<class T, class Compare > void infra::IntrusivePriorityQueue< T, Compare >::erase (const T & value)
Definition at line 212 of file IntrusivePriorityQueue.hpp.
     {
         T& erasingNode = const_cast<T&>(position);
         // First, move erasingNode all the way down in the tree, maintaining heap invariant except for erasingNode
         while (true)
         {
             T* shiftUpNode = nullptr;
             if (erasingNode.left && erasingNode.right)
             {
                 if (compare(*erasingNode.left, *erasingNode.right))
                     shiftUpNode = erasingNode.right;
                 else
                     shiftUpNode = erasingNode.left;
             }
             else if (erasingNode.left != nullptr)
                 shiftUpNode = erasingNode.left;
             else
                 shiftUpNode = erasingNode.right;
             if (shiftUpNode != nullptr)
                 swapChildAndParentNodes(*shiftUpNode, erasingNode);
             else
                 break;
         }
         // Then, replace erasingNode by lastNode
         T& last = lastNode();
         if (&last != &erasingNode)
         {
             assert(last.up);        // if last.up does not exist, then the tree holds only one element, and &last == &erasingNode
             assert(erasingNode.up); // if erasingNode.up does not exist, then the tree holds only one element, and &last == &erasingNode
             if (last.up->left == &last)
                 last.up->left = nullptr;
             else
                 last.up->right = nullptr;
             last.up = erasingNode.up;
             last.left = erasingNode.left;
             last.right = erasingNode.right;
             if (last.up->left == &erasingNode)
                 last.up->left = &last;
             else
                 last.up->right = &last;
             if (last.right != nullptr)
                 last.right->up = &last;
             if (last.left != nullptr)
                 last.left->up = &last;
             // Finally, move lastNode up in the tree, restoring the heap invariant
             while (true)
             {
                 if (last.up == nullptr)
                     break;
                 if (compare(last, *last.up))
                     break;
                 swapChildAndParentNodes(last, *last.up);
             }
         }
         else
         {
             if (!last.up)
                 topNode = nullptr;
             else
             {
                 if (last.up->left == &last)
                     last.up->left = nullptr;
                 else
                     last.up->right = nullptr;
             }
         }
         --numberOfElements;
     }
insertAsLast()
template<class T, class Compare > void infra::IntrusivePriorityQueue< T, Compare >::insertAsLast (T & value) private
Definition at line 300 of file IntrusivePriorityQueue.hpp.
References value.
     {
         value.right = nullptr;
         value.left = nullptr;
         if (!topNode)
         {
             ++numberOfElements;
             topNode = &value;
             value.up = nullptr;
         }
         else
         {
             ++numberOfElements;
             T* node = topNode;
             std::size_t direction = 1;
             while (direction <= numberOfElements)
                 direction <<= 1;
             direction >>= 2;
             while (direction != 1)
             {
                 if ((numberOfElements & direction) != 0)
                     node = node->right;
                 else
                     node = node->left;
                 direction >>= 1;
             }
             if ((numberOfElements & direction) != 0)
                 node->right = &value;
             else
                 node->left = &value;
             value.up = node;
         }
     }
lastNode()
template<class T , class Compare > T & infra::IntrusivePriorityQueue< T, Compare >::lastNode () const private
Definition at line 341 of file IntrusivePriorityQueue.hpp.
     {
         T* node = topNode;
         std::size_t direction = 1;
         while (direction <= numberOfElements)
             direction <<= 1;
         direction >>= 2;
         while (direction != 0)
         {
             if ((numberOfElements & direction) != 0)
                 node = node->right;
             else
                 node = node->left;
             direction >>= 1;
         }
         return *node;
     }
operator=() [1/2]
template<class T, class Compare = std::less<T>> IntrusivePriorityQueue& infra::IntrusivePriorityQueue< T, Compare >::operator= (const IntrusivePriorityQueue< T, Compare > &) delete
operator=() [2/2]
template<class T , class Compare > IntrusivePriorityQueue< T, Compare > & infra::IntrusivePriorityQueue< T, Compare >::operator= (IntrusivePriorityQueue< T, Compare > && other)
Definition at line 116 of file IntrusivePriorityQueue.hpp.
     {
         compare = std::move(other.compare);
         topNode = other.topNode;
         numberOfElements = other.numberOfElements;
         other.topNode = nullptr;
         other.numberOfElements = 0;
         return *this;
     }
pop()
template<class T , class Compare > void infra::IntrusivePriorityQueue< T, Compare >::pop ()
Definition at line 199 of file IntrusivePriorityQueue.hpp.
     {
         erase(*topNode);
     }
push()
template<class T, class Compare > void infra::IntrusivePriorityQueue< T, Compare >::push (const T & value)
Definition at line 189 of file IntrusivePriorityQueue.hpp.
References value.
Referenced by infra::IntrusivePriorityQueue< T, Compare >::IntrusivePriorityQueue().
     {
         T& node = const_cast<T&>(value);
         insertAsLast(node);
         while (node.up && compare(*node.up, node))
             swapChildAndParentNodes(node, *node.up);
     }
size()
template<class T , class Compare > IntrusivePriorityQueue< T, Compare >::size_type infra::IntrusivePriorityQueue< T, Compare >::size () const
Definition at line 134 of file IntrusivePriorityQueue.hpp.
     {
         return numberOfElements;
     }
swap()
template<class T , class Compare > void infra::IntrusivePriorityQueue< T, Compare >::swap (IntrusivePriorityQueue< T, Compare > & x)
Definition at line 292 of file IntrusivePriorityQueue.hpp.
References infra::IntrusivePriorityQueue< T, Compare >::numberOfElements, infra::swap(), and infra::IntrusivePriorityQueue< T, Compare >::topNode.
     {
         using std::swap;
         swap(topNode, other.topNode);
         swap(numberOfElements, other.numberOfElements);
     }
swapChildAndParentNodes()
template<class T, class Compare > void infra::IntrusivePriorityQueue< T, Compare >::swapChildAndParentNodes (T & child, T & parent) private
Definition at line 152 of file IntrusivePriorityQueue.hpp.
     {
         T* parentUp = parent.up;
         if (parentUp != nullptr)
         {
             if (parentUp->left == &parent)
                 parentUp->left = &child;
             else
                 parentUp->right = &child;
         }
         bool leftRotate = &child == parent.left;
         T* otherChild = leftRotate ? parent.right : parent.left;
         parent.left = child.left;
         parent.right = child.right;
         if (parent.left != nullptr)
             parent.left->up = &parent;
         if (parent.right != nullptr)
             parent.right->up = &parent;
         parent.up = &child;
         if (otherChild != nullptr)
             otherChild->up = &child;
         child.left = leftRotate ? &parent : otherChild;
         child.right = leftRotate ? otherChild : &parent;
         child.up = parentUp;
         if (topNode == &parent)
             topNode = &child;
     }
top() [1/2]
template<class T , class Compare > T & infra::IntrusivePriorityQueue< T, Compare >::top ()
Definition at line 140 of file IntrusivePriorityQueue.hpp.
     {
         return *topNode;
     }
top() [2/2]
template<class T , class Compare > const T & infra::IntrusivePriorityQueue< T, Compare >::top () const
Definition at line 146 of file IntrusivePriorityQueue.hpp.
     {
         return *topNode;
     }
Member Data Documentation
compare
template<class T, class Compare = std::less<T>> Compare infra::IntrusivePriorityQueue< T, Compare >::compare private
Definition at line 63 of file IntrusivePriorityQueue.hpp.
numberOfElements
template<class T, class Compare = std::less<T>> std::size_t infra::IntrusivePriorityQueue< T, Compare >::numberOfElements = 0 private
Definition at line 62 of file IntrusivePriorityQueue.hpp.
Referenced by infra::IntrusivePriorityQueue< T, Compare >::swap().
topNode
template<class T, class Compare = std::less<T>> T* infra::IntrusivePriorityQueue< T, Compare >::topNode = nullptr private
Definition at line 61 of file IntrusivePriorityQueue.hpp.
Referenced by infra::IntrusivePriorityQueue< T, Compare >::swap().
The documentation for this class was generated from the following file:
IntrusivePriorityQueue.hpp