EMil: hal::SynchronousFlashStub Class Reference
hal::SynchronousFlashStub Class Reference
#include <SynchronousFlashStub.hpp>
Public Member Functions
SynchronousFlashStub (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
void Clear ()
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex) override
Public Member Functions inherited from hal::SynchronousFlash
SynchronousFlash ()=default
SynchronousFlash (const SynchronousFlash &other)=delete
SynchronousFlash & operator= (const SynchronousFlash &other)=delete
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex)
void EraseAll ()
Public Attributes
std::vector< std::vector< uint8_t > > sectors
infra::Optional< uint8_t > stopAfterWriteSteps
Private Member Functions
void WriteBufferImpl (infra::ConstByteRange buffer, uint32_t address)
void ApplyBuffer (infra::ConstByteRange buffer, uint32_t address, uint32_t size)
void ReadBufferPart (infra::ByteRange &buffer, uint32_t &address)
Additional Inherited Members
Public Types inherited from hal::SynchronousFlash
using Range = std::pair< uint32_t, uint32_t >
Protected Member Functions inherited from hal::SynchronousFlash
~SynchronousFlash ()=default
Detailed Description
Definition at line 10 of file SynchronousFlashStub.hpp.
Constructor & Destructor Documentation
SynchronousFlashStub()
hal::SynchronousFlashStub::SynchronousFlashStub (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
Definition at line 6 of file SynchronousFlashStub.cpp.
         : sectors(numberOfSectors, std::vector<uint8_t>(sizeOfEachSector, 0xff))
     {}
Member Function Documentation
AddressOfSector()
uint32_t hal::SynchronousFlashStub::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::SynchronousFlash.
Definition at line 34 of file SynchronousFlashStub.cpp.
References sectors.
     {
         assert(sectorIndex <= sectors.size());
         uint32_t result = 0;
         for (uint32_t index = 0; index != sectorIndex; ++index)
             result += sectors[index].size();
         return result;
     }
ApplyBuffer()
void hal::SynchronousFlashStub::ApplyBuffer (infra::ConstByteRange buffer, uint32_t address, uint32_t size) private
Definition at line 82 of file SynchronousFlashStub.cpp.
References hal::SynchronousFlash::AddressOffsetInSector(), SectorOfAddress(), and sectors.
Referenced by WriteBufferImpl().
     {
         for (std::size_t i = 0; i != size; ++i)
             sectors[SectorOfAddress(address)][AddressOffsetInSector(address) + i] &= buffer[i];
     }
Clear()
void hal::SynchronousFlashStub::Clear ()
EraseSectors()
void hal::SynchronousFlashStub::EraseSectors (uint32_t beginIndex, uint32_t endIndex) override virtual
Implements hal::SynchronousFlash.
Definition at line 63 of file SynchronousFlashStub.cpp.
References infra::detail::begin(), infra::detail::end(), and sectors.
     {
         for (uint32_t sectorIndex = beginIndex; sectorIndex != endIndex; ++sectorIndex)
             std::fill(sectors[sectorIndex].begin(), sectors[sectorIndex].end(), 0xff);
     }
NumberOfSectors()
uint32_t hal::SynchronousFlashStub::NumberOfSectors () const override virtual
Implements hal::SynchronousFlash.
Definition at line 10 of file SynchronousFlashStub.cpp.
References sectors.
     {
         return sectors.size();
     }
ReadBuffer()
void hal::SynchronousFlashStub::ReadBuffer (infra::ByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 57 of file SynchronousFlashStub.cpp.
References infra::MemoryRange< T >::empty(), and ReadBufferPart().
     {
         while (!buffer.empty())
             ReadBufferPart(buffer, address);
     }
ReadBufferPart()
void hal::SynchronousFlashStub::ReadBufferPart (infra::ByteRange & buffer, uint32_t & address) private
Definition at line 88 of file SynchronousFlashStub.cpp.
References hal::SynchronousFlash::AddressOffsetInSector(), infra::detail::begin(), infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::pop_front(), SectorOfAddress(), sectors, infra::MemoryRange< T >::size(), SizeOfSector(), and hal::SynchronousFlash::StartOfNextSector().
Referenced by ReadBuffer().
     {
         std::size_t size = std::min<uint32_t>(buffer.size(), SizeOfSector(SectorOfAddress(address)) - AddressOffsetInSector(address));
         std::copy(sectors[SectorOfAddress(address)].begin() + AddressOffsetInSector(address), sectors[SectorOfAddress(address)].begin() + AddressOffsetInSector(address) + size, buffer.begin());
         buffer.pop_front(size);
         address = StartOfNextSector(address);
     }
SectorOfAddress()
uint32_t hal::SynchronousFlashStub::SectorOfAddress (uint32_t address) const override virtual
Implements hal::SynchronousFlash.
Definition at line 20 of file SynchronousFlashStub.cpp.
References sectors.
Referenced by ApplyBuffer(), ReadBufferPart(), and WriteBufferImpl().
     {
         for (std::size_t index = 0; index != sectors.size(); ++index)
         {
             if (address < sectors[index].size())
                 return index;
             address -= sectors[index].size();
         }
         assert(address == 0);
         return sectors.size();
     }
SizeOfSector()
uint32_t hal::SynchronousFlashStub::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::SynchronousFlash.
Definition at line 15 of file SynchronousFlashStub.cpp.
References sectors.
Referenced by ReadBufferPart(), and WriteBufferImpl().
     {
         return sectors[sectorIndex].size();
     }
WriteBuffer()
void hal::SynchronousFlashStub::WriteBuffer (infra::ConstByteRange buffer, uint32_t address) override virtual
Implements hal::SynchronousFlash.
Definition at line 46 of file SynchronousFlashStub.cpp.
References stopAfterWriteSteps, and WriteBufferImpl().
     {
         if (stopAfterWriteSteps)
             if (*stopAfterWriteSteps > 0)
                 --*stopAfterWriteSteps;
             else
                 return;
         WriteBufferImpl(buffer, address);
     }
WriteBufferImpl()
void hal::SynchronousFlashStub::WriteBufferImpl (infra::ConstByteRange buffer, uint32_t address) private
Definition at line 69 of file SynchronousFlashStub.cpp.
References hal::SynchronousFlash::AddressOffsetInSector(), ApplyBuffer(), infra::MemoryRange< T >::empty(), infra::MemoryRange< T >::pop_front(), SectorOfAddress(), infra::MemoryRange< T >::size(), SizeOfSector(), and hal::SynchronousFlash::StartOfNextSector().
Referenced by WriteBuffer().
     {
         while (!buffer.empty())
         {
             std::size_t size = std::min<uint32_t>(buffer.size(), SizeOfSector(SectorOfAddress(address)) - AddressOffsetInSector(address));
             ApplyBuffer(buffer, address, size);
             buffer.pop_front(size);
             address = StartOfNextSector(address);
         }
     }
Member Data Documentation
sectors
std::vector<std::vector<uint8_t> > hal::SynchronousFlashStub::sectors
Definition at line 34 of file SynchronousFlashStub.hpp.
Referenced by AddressOfSector(), ApplyBuffer(), EraseSectors(), NumberOfSectors(), ReadBufferPart(), SectorOfAddress(), and SizeOfSector().
stopAfterWriteSteps
infra::Optional<uint8_t> hal::SynchronousFlashStub::stopAfterWriteSteps
Definition at line 35 of file SynchronousFlashStub.hpp.
Referenced by WriteBuffer().
The documentation for this class was generated from the following files:
SynchronousFlashStub.hpp
SynchronousFlashStub.cpp