EMil: services::ConnectionStubWithAckReceivedMock Class Reference
services::ConnectionStubWithAckReceivedMock Class Reference
#include <ConnectionStub.hpp>
Public Member Functions
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
MOCK_METHOD0 (AckReceivedMock, void())
MOCK_METHOD0 (CloseAndDestroyMock, void())
MOCK_METHOD0 (AbortAndDestroyMock, void())
MOCK_CONST_METHOD0 (Ipv4Address, IPv4Address())
Public Member Functions inherited from services::ConnectionStub
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
MOCK_METHOD0 (CloseAndDestroyMock, void())
MOCK_METHOD0 (AbortAndDestroyMock, void())
MOCK_CONST_METHOD0 (Ipv4Address, IPv4Address())
void SimulateDataReceived (infra::ConstByteRange data)
std::string SentDataAsString () const
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionStub >
SharedPtr< ConnectionStub > SharedFromThis ()
SharedPtr< const ConnectionStub > SharedFromThis () const
WeakPtr< ConnectionStub > WeakFromThis ()
WeakPtr< const ConnectionStub > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionStub > sharedPtr)
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectionStub >
using EnableSharedFromThisType = ConnectionStub
Public Attributes inherited from services::ConnectionStub
std::vector< uint8_t > sentData
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionStub >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 72 of file ConnectionStub.hpp.
Member Function Documentation
AbortAndDestroy()
void services::ConnectionStubWithAckReceivedMock::AbortAndDestroy () override virtual
Reimplemented from services::ConnectionStub.
Definition at line 102 of file ConnectionStub.cpp.
References services::Connection::ResetOwnership().
     {
         AbortAndDestroyMock();
         ResetOwnership();
     }
AckReceived()
void services::ConnectionStubWithAckReceivedMock::AckReceived () override virtual
Reimplemented from services::ConnectionStub.
Definition at line 90 of file ConnectionStub.cpp.
References services::ConnectionStub::AckReceived().
     {
         AckReceivedMock();
         ConnectionStub::AckReceived();
     }
CloseAndDestroy()
void services::ConnectionStubWithAckReceivedMock::CloseAndDestroy () override virtual
Reimplemented from services::ConnectionStub.
Definition at line 96 of file ConnectionStub.cpp.
References services::Connection::ResetOwnership().
     {
         CloseAndDestroyMock();
         ResetOwnership();
     }
MOCK_CONST_METHOD0()
services::ConnectionStubWithAckReceivedMock::MOCK_CONST_METHOD0 (Ipv4Address , IPv4Address())
MOCK_METHOD0() [1/3]
services::ConnectionStubWithAckReceivedMock::MOCK_METHOD0 (AckReceivedMock , void())
MOCK_METHOD0() [2/3]
services::ConnectionStubWithAckReceivedMock::MOCK_METHOD0 (CloseAndDestroyMock , void())
MOCK_METHOD0() [3/3]
services::ConnectionStubWithAckReceivedMock::MOCK_METHOD0 (AbortAndDestroyMock , void())
The documentation for this class was generated from the following files:
ConnectionStub.hpp
ConnectionStub.cpp