EMil: infra::SystemStateManager Class Reference
infra::SystemStateManager Class Reference
#include <SystemStateManager.hpp>
Public Member Functions
SystemStateManager ()=default
SystemStateManager (const SystemStateManager &other)=delete
SystemStateManager & operator= (const SystemStateManager &other)=delete
void RunStates (infra::MemoryRange< const SystemStateBase > states)
Private Member Functions
void AddParticipant (SystemStateParticipant &participant)
void RemoveParticipant (SystemStateParticipant &participant)
void ReachedState (SystemStateParticipant &participant)
void GoToNextState ()
void InformAllParticipants ()
Private Attributes
infra::IntrusiveList< SystemStateParticipant > participantsInPreviousState
infra::IntrusiveList< SystemStateParticipant > participantsInCurrentState
infra::MemoryRange< const SystemStateBase > runningStates
const SystemStateBase * currentState = nullptr
Friends
class SystemStateParticipant
Detailed Description
Definition at line 53 of file SystemStateManager.hpp.
Constructor & Destructor Documentation
SystemStateManager() [1/2]
infra::SystemStateManager::SystemStateManager () default
SystemStateManager() [2/2]
infra::SystemStateManager::SystemStateManager (const SystemStateManager & other) delete
Member Function Documentation
AddParticipant()
void infra::SystemStateManager::AddParticipant (SystemStateParticipant & participant) private
Definition at line 44 of file SystemStateManager.cpp.
References participantsInCurrentState, and runningStates.
Referenced by infra::SystemStateParticipant::SystemStateParticipant().
     {
         assert(runningStates.empty());
         participantsInCurrentState.push_back(participant);
     }
GoToNextState()
void infra::SystemStateManager::GoToNextState () private
Definition at line 66 of file SystemStateManager.cpp.
References currentState, InformAllParticipants(), participantsInCurrentState, participantsInPreviousState, and runningStates.
Referenced by InformAllParticipants(), ReachedState(), and RunStates().
     {
         assert(participantsInPreviousState.empty());
         participantsInPreviousState = std::move(participantsInCurrentState);
         ++currentState;
         if (currentState != runningStates.end())
             InformAllParticipants();
     }
InformAllParticipants()
void infra::SystemStateManager::InformAllParticipants () private
Definition at line 76 of file SystemStateManager.cpp.
References currentState, GoToNextState(), and participantsInPreviousState.
Referenced by GoToNextState().
     {
         if (participantsInPreviousState.empty())
             GoToNextState();
         else
             for (SystemStateParticipant& participant: participantsInPreviousState)
                 participant.RequestState(*currentState);
     }
operator=()
SystemStateManager& infra::SystemStateManager::operator= (const SystemStateManager & other) delete
ReachedState()
void infra::SystemStateManager::ReachedState (SystemStateParticipant & participant) private
Definition at line 56 of file SystemStateManager.cpp.
References GoToNextState(), participantsInCurrentState, and participantsInPreviousState.
Referenced by infra::SystemStateParticipant::ReachedState().
     {
         assert(participantsInPreviousState.has_element(participant));
         participantsInPreviousState.erase(participant);
         participantsInCurrentState.push_back(participant);
         if (participantsInPreviousState.empty())
             GoToNextState();
     }
RemoveParticipant()
void infra::SystemStateManager::RemoveParticipant (SystemStateParticipant & participant) private
Definition at line 50 of file SystemStateManager.cpp.
References participantsInPreviousState.
Referenced by infra::SystemStateParticipant::~SystemStateParticipant().
     {
         assert(participantsInPreviousState.has_element(participant));
         participantsInPreviousState.erase(participant);
     }
RunStates()
void infra::SystemStateManager::RunStates (infra::MemoryRange< const SystemStateBase > states)
Definition at line 36 of file SystemStateManager.cpp.
References currentState, GoToNextState(), and runningStates.
     {
         assert(runningStates.empty() || currentState == std::prev(runningStates.end()));
         runningStates = states;
         currentState = std::prev(runningStates.begin());
         GoToNextState();
     }
Friends And Related Function Documentation
SystemStateParticipant
friend class SystemStateParticipant friend
Definition at line 63 of file SystemStateManager.hpp.
Member Data Documentation
currentState
const SystemStateBase* infra::SystemStateManager::currentState = nullptr private
Definition at line 78 of file SystemStateManager.hpp.
Referenced by GoToNextState(), InformAllParticipants(), and RunStates().
participantsInCurrentState
infra::IntrusiveList<SystemStateParticipant> infra::SystemStateManager::participantsInCurrentState private
Definition at line 75 of file SystemStateManager.hpp.
Referenced by AddParticipant(), GoToNextState(), and ReachedState().
participantsInPreviousState
infra::IntrusiveList<SystemStateParticipant> infra::SystemStateManager::participantsInPreviousState private
Definition at line 74 of file SystemStateManager.hpp.
Referenced by GoToNextState(), InformAllParticipants(), ReachedState(), and RemoveParticipant().
runningStates
infra::MemoryRange<const SystemStateBase> infra::SystemStateManager::runningStates private
Definition at line 77 of file SystemStateManager.hpp.
Referenced by AddParticipant(), GoToNextState(), and RunStates().
The documentation for this class was generated from the following files:
SystemStateManager.hpp
SystemStateManager.cpp