EMil: services::DatagramWin Class Reference
services::DatagramWin Class Reference
#include <DatagramWin.hpp>
Classes
class StreamWriterWin
Public Member Functions
DatagramWin (EventDispatcherWithNetwork &network, uint16_t port, DatagramExchangeObserver &observer)
DatagramWin (EventDispatcherWithNetwork &network, DatagramExchangeObserver &observer)
DatagramWin (EventDispatcherWithNetwork &network, UdpSocket remote, DatagramExchangeObserver &observer)
DatagramWin (EventDispatcherWithNetwork &network, uint16_t localPort, UdpSocket remote, DatagramExchangeObserver &observer)
~DatagramWin ()
virtual void RequestSendStream (std::size_t sendSize) override
virtual void RequestSendStream (std::size_t sendSize, UdpSocket to) override
void Receive ()
void Send ()
void TrySend ()
void UpdateEventFlags ()
Public Member Functions inherited from infra::Subject< DatagramExchangeObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::EnableSharedFromThis< DatagramWin >
SharedPtr< DatagramWin > SharedFromThis ()
SharedPtr< const DatagramWin > SharedFromThis () const
WeakPtr< DatagramWin > WeakFromThis ()
WeakPtr< const DatagramWin > WeakFromThis () const
void MakeShared (SharedPtr< DatagramWin > sharedPtr)
Private Member Functions
void InitSocket ()
void BindLocal (uint16_t port)
void BindRemote (UdpSocket remote)
void TryAllocateSendStream ()
Private Attributes
EventDispatcherWithNetwork & network
SOCKET socket = ::socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)
WSAEVENT event = WSACreateEvent()
infra::Optional< UdpSocket > connectedTo
infra::Optional< infra::BoundedVector< uint8_t >::WithMaxSize< 508 > > sendBuffer
infra::SharedOptional< StreamWriterWin > streamWriter
std::size_t requestedSendSize = 0
UdpSocket requestedTo
bool trySend = false
Friends
class EventDispatcherWithNetwork
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< DatagramWin >
using EnableSharedFromThisType = DatagramWin
Protected Member Functions inherited from infra::Subject< DatagramExchangeObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< DatagramExchangeObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< DatagramExchangeObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::EnableSharedFromThis< DatagramWin >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 18 of file DatagramWin.hpp.
Constructor & Destructor Documentation
DatagramWin() [1/4]
services::DatagramWin::DatagramWin (EventDispatcherWithNetwork & network, uint16_t port, DatagramExchangeObserver & observer)
Definition at line 7 of file DatagramWin.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(port);
     }
DatagramWin() [2/4]
services::DatagramWin::DatagramWin (EventDispatcherWithNetwork & network, DatagramExchangeObserver & observer)
Definition at line 15 of file DatagramWin.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(0);
     }
DatagramWin() [3/4]
services::DatagramWin::DatagramWin (EventDispatcherWithNetwork & network, UdpSocket remote, DatagramExchangeObserver & observer)
Definition at line 23 of file DatagramWin.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), BindRemote(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(0);
         BindRemote(remote);
     }
DatagramWin() [4/4]
services::DatagramWin::DatagramWin (EventDispatcherWithNetwork & network, uint16_t localPort, UdpSocket remote, DatagramExchangeObserver & observer)
Definition at line 32 of file DatagramWin.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), BindLocal(), BindRemote(), InitSocket(), and infra::Subject< DatagramExchangeObserver >::observer.
         : network(network)
     {
         observer.Attach(*this);
         InitSocket();
         BindLocal(localPort);
         BindRemote(remote);
     }
~DatagramWin()
services::DatagramWin::~DatagramWin ()
Definition at line 41 of file DatagramWin.cpp.
References event, infra::Subject< DatagramExchangeObserver >::GetObserver(), and socket.
     {
         GetObserver().Detach();
         BOOL result = WSACloseEvent(event);
         assert(result == TRUE);
         result = closesocket(socket);
         if (result == SOCKET_ERROR)
         {
             DWORD error = GetLastError();
             std::abort();
         }
     }
Member Function Documentation
BindLocal()
void services::DatagramWin::BindLocal (uint16_t port) private
Definition at line 146 of file DatagramWin.cpp.
References socket.
Referenced by DatagramWin().
     {
         sockaddr_in address{};
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = INADDR_ANY;
         address.sin_port = htons(port);
         auto result = bind(socket, reinterpret_cast<sockaddr*>(&address), sizeof(address));
         assert(result == 0);
     }
BindRemote()
void services::DatagramWin::BindRemote (UdpSocket remote) private
Definition at line 156 of file DatagramWin.cpp.
References services::connect, connectedTo, infra::Variant< T >::Get(), and socket.
Referenced by DatagramWin().
     {
         sockaddr_in address{};
         address.sin_family = AF_INET;
         address.sin_addr.s_net = remote.Get<Udpv4Socket>().first[0];
         address.sin_addr.s_host = remote.Get<Udpv4Socket>().first[1];
         address.sin_addr.s_lh = remote.Get<Udpv4Socket>().first[2];
         address.sin_addr.s_impno = remote.Get<Udpv4Socket>().first[3];
         address.sin_port = htons(remote.Get<Udpv4Socket>().second);
         auto result = connect(socket, reinterpret_cast<sockaddr*>(&address), sizeof(address));
         auto error = WSAGetLastError();
         assert(result == 0);
         connectedTo = remote;
     }
InitSocket()
void services::DatagramWin::InitSocket () private
Definition at line 133 of file DatagramWin.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), Receive(), infra::EventDispatcherWorker::Schedule(), socket, and UpdateEventFlags().
Referenced by DatagramWin().
     {
         assert(socket != INVALID_SOCKET);
         ULONG nonBlock = 1;
         if (ioctlsocket(socket, FIONBIO, &nonBlock) == SOCKET_ERROR)
             std::abort();
         UpdateEventFlags();
         infra::EventDispatcher::Instance().Schedule([this]() { Receive(); });
     }
Receive()
void services::DatagramWin::Receive ()
Definition at line 68 of file DatagramWin.cpp.
References infra::Subject< DatagramExchangeObserver >::GetObserver(), infra::MakeRange(), and socket.
Referenced by InitSocket().
     {
         infra::BoundedVector<uint8_t>::WithMaxSize<508> receiveBuffer;
         receiveBuffer.resize(receiveBuffer.max_size());
         sockaddr_in fromAddress{};
         int fromAddressSize = sizeof(fromAddress);
         auto received = recvfrom(socket, reinterpret_cast<char*>(receiveBuffer.data()), receiveBuffer.size(), 0, reinterpret_cast<sockaddr*>(&fromAddress), &fromAddressSize);
         if (received == SOCKET_ERROR)
         {
             auto error = WSAGetLastError();
             if (error != WSAEWOULDBLOCK && error != WSAEMSGSIZE)
                 std::abort();
             return;
         }
         else if (fromAddressSize == sizeof(fromAddress) && fromAddress.sin_family == AF_INET)
         {
             receiveBuffer.resize(received);
             infra::ByteInputStreamReader reader(infra::MakeRange(receiveBuffer));
             auto from = Udpv4Socket{ IPv4Address{ fromAddress.sin_addr.s_net, fromAddress.sin_addr.s_host, fromAddress.sin_addr.s_lh, fromAddress.sin_addr.s_impno }, fromAddress.sin_port };
             GetObserver().DataReceived(reader, from);
         }
     }
RequestSendStream() [1/2]
void services::DatagramWin::RequestSendStream (std::size_t sendSize) override virtual
Implements services::DatagramExchange.
Definition at line 55 of file DatagramWin.cpp.
References connectedTo.
     {
         RequestSendStream(sendSize, *connectedTo);
     }
RequestSendStream() [2/2]
void services::DatagramWin::RequestSendStream (std::size_t sendSize, UdpSocket to) override virtual
Implements services::DatagramExchange.
Definition at line 60 of file DatagramWin.cpp.
References requestedSendSize, requestedTo, streamWriter, and TryAllocateSendStream().
     {
         assert(streamWriter.Allocatable());
         requestedSendSize = sendSize;
         requestedTo = to;
         TryAllocateSendStream();
     }
Send()
void services::DatagramWin::Send ()
Definition at line 95 of file DatagramWin.cpp.
References infra::BoundedVector< T >::data(), infra::Variant< T >::Get(), infra::none, requestedTo, sendBuffer, infra::BoundedVector< T >::size(), socket, and UpdateEventFlags().
Referenced by TrySend().
     {
         UpdateEventFlags();     // If there is something to send, update the flags before calling send, because FD_SEND is an edge-triggered event.
         sockaddr_in address{};
         address.sin_family = AF_INET;
         address.sin_addr.s_net = requestedTo.Get<Udpv4Socket>().first[0];
         address.sin_addr.s_host = requestedTo.Get<Udpv4Socket>().first[1];
         address.sin_addr.s_lh = requestedTo.Get<Udpv4Socket>().first[2];
         address.sin_addr.s_impno = requestedTo.Get<Udpv4Socket>().first[3];
         address.sin_port = htons(requestedTo.Get<Udpv4Socket>().second);
         int sent = sendto(socket, reinterpret_cast<char*>(sendBuffer->data()), sendBuffer->size(), 0, reinterpret_cast<sockaddr*>(&address), sizeof(address));
         if (sent == SOCKET_ERROR)
         {
             if (WSAGetLastError() != WSAEWOULDBLOCK)
                 std::abort();
             return;
         }
         sendBuffer = infra::none;
         UpdateEventFlags();
     }
TryAllocateSendStream()
void services::DatagramWin::TryAllocateSendStream () private
Definition at line 172 of file DatagramWin.cpp.
References infra::Optional< T >::Emplace(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), requestedSendSize, infra::EventDispatcherWithWeakPtrWorker::Schedule(), sendBuffer, infra::EnableSharedFromThis< DatagramWin >::SharedFromThis(), and streamWriter.
Referenced by RequestSendStream().
     {
         assert(streamWriter.Allocatable());
         if (!sendBuffer)
         {
             sendBuffer.Emplace(requestedSendSize, 0);
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<DatagramWin>& object)
             {
                 infra::SharedPtr<infra::StreamWriter> writer = object->streamWriter.Emplace(*object);
                 object->GetObserver().SendStreamAvailable(std::move(writer));
             }, SharedFromThis());
         }
     }
TrySend()
void services::DatagramWin::TrySend ()
Definition at line 118 of file DatagramWin.cpp.
References Send(), and trySend.
     {
         if (trySend)
         {
             trySend = false;
             Send();
         }
     }
UpdateEventFlags()
void services::DatagramWin::UpdateEventFlags ()
Definition at line 127 of file DatagramWin.cpp.
References event, sendBuffer, and socket.
Referenced by InitSocket(), and Send().
     {
         int result = WSAEventSelect(socket, event, FD_READ | (sendBuffer ? FD_WRITE : 0));
         assert(result == 0);
     }
Friends And Related Function Documentation
EventDispatcherWithNetwork
friend class EventDispatcherWithNetwork friend
Definition at line 56 of file DatagramWin.hpp.
Member Data Documentation
connectedTo
infra::Optional<UdpSocket> services::DatagramWin::connectedTo private
Definition at line 61 of file DatagramWin.hpp.
Referenced by BindRemote(), and RequestSendStream().
event
WSAEVENT services::DatagramWin::event = WSACreateEvent() private
Definition at line 60 of file DatagramWin.hpp.
Referenced by UpdateEventFlags(), and ~DatagramWin().
network
EventDispatcherWithNetwork& services::DatagramWin::network private
Definition at line 58 of file DatagramWin.hpp.
requestedSendSize
std::size_t services::DatagramWin::requestedSendSize = 0 private
Definition at line 66 of file DatagramWin.hpp.
Referenced by RequestSendStream(), and TryAllocateSendStream().
requestedTo
UdpSocket services::DatagramWin::requestedTo private
Definition at line 67 of file DatagramWin.hpp.
Referenced by RequestSendStream(), and Send().
sendBuffer
infra::Optional<infra::BoundedVector<uint8_t>::WithMaxSize<508> > services::DatagramWin::sendBuffer private
Definition at line 63 of file DatagramWin.hpp.
Referenced by Send(), TryAllocateSendStream(), and UpdateEventFlags().
socket
SOCKET services::DatagramWin::socket = ::socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) private
Definition at line 59 of file DatagramWin.hpp.
Referenced by BindLocal(), BindRemote(), InitSocket(), Receive(), Send(), UpdateEventFlags(), and ~DatagramWin().
streamWriter
infra::SharedOptional<StreamWriterWin> services::DatagramWin::streamWriter private
Definition at line 65 of file DatagramWin.hpp.
Referenced by RequestSendStream(), and TryAllocateSendStream().
trySend
bool services::DatagramWin::trySend = false private
Definition at line 68 of file DatagramWin.hpp.
Referenced by TrySend().
The documentation for this class was generated from the following files:
DatagramWin.hpp
DatagramWin.cpp