EMil: services::FlashQuadSpiSingleSpeed Class Reference
services::FlashQuadSpiSingleSpeed Class Reference
#include <FlashQuadSpiSingleSpeed.hpp>
Public Member Functions
FlashQuadSpiSingleSpeed (hal::QuadSpi &spi, infra::Function< void()> onInitialized, uint32_t numberOfSectors=4096)
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
Public Member Functions inherited from services::FlashQuadSpi
FlashQuadSpi (hal::QuadSpi &spi, uint32_t numberOfSectors, uint8_t commandPageProgram)
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::FlashHomogeneous
FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Static Public Attributes
static const uint8_t commandPageProgram = 0x02
static const uint8_t commandReadData = 0x03
static const uint8_t commandReadStatusRegister = 0x05
static const uint8_t commandWriteEnable = 0x06
static const uint8_t commandEraseSector = 0x20
static const uint8_t commandEraseHalfBlock
static const uint8_t commandEraseBlock = 0xd8
static const uint8_t commandEraseChip = 0x60
static const uint8_t statusFlagWriteInProgress = 1
Static Public Attributes inherited from services::FlashQuadSpi
static const uint32_t sizeBlock = 65536
static const uint32_t sizeSector = 4096
static const uint32_t sizePage = 256
Protected Member Functions
virtual void PageProgram () override
Protected Member Functions inherited from services::FlashQuadSpi
void WriteBufferSequence ()
infra::BoundedVector< uint8_t >::WithMaxSize< 4 > ConvertAddress (uint32_t address) const
Protected Member Functions inherited from hal::FlashHomogeneous
~FlashHomogeneous ()=default
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Private Member Functions
virtual void WriteEnable () override
virtual void EraseSomeSectors (uint32_t endIndex) override
void SendEraseSector (uint32_t sectorIndex)
void SendEraseBlock (uint32_t sectorIndex)
void SendEraseChip ()
virtual void HoldWhileWriteInProgress () override
Private Attributes
infra::Function< void()> onInitialized
infra::TimerSingleShot initDelayTimer
Additional Inherited Members
Protected Attributes inherited from services::FlashQuadSpi
hal::QuadSpi & spi
infra::Sequencer sequencer
infra::AutoResetFunction< void()> onDone
infra::ConstByteRange buffer
uint32_t address = 0
uint32_t sectorIndex = 0
uint8_t commandPageProgram
Detailed Description
Definition at line 8 of file FlashQuadSpiSingleSpeed.hpp.
Constructor & Destructor Documentation
FlashQuadSpiSingleSpeed()
services::FlashQuadSpiSingleSpeed::FlashQuadSpiSingleSpeed (hal::QuadSpi & spi, infra::Function< void()> onInitialized, uint32_t numberOfSectors = 4096)
Definition at line 14 of file FlashQuadSpiSingleSpeed.cpp.
References onInitialized.
         : FlashQuadSpi(spi, numberOfSectors, commandPageProgram)
         , onInitialized(onInitialized)
         , initDelayTimer(std::chrono::milliseconds(100), [this]() { this->onInitialized(); })
     {}
Member Function Documentation
EraseSomeSectors()
void services::FlashQuadSpiSingleSpeed::EraseSomeSectors (uint32_t endIndex) override private virtual
Implements services::FlashQuadSpi.
Definition at line 44 of file FlashQuadSpiSingleSpeed.cpp.
References hal::FlashHomogeneous::NumberOfSectors(), services::FlashQuadSpi::sectorIndex, SendEraseBlock(), SendEraseChip(), SendEraseSector(), services::FlashQuadSpi::sizeBlock, and services::FlashQuadSpi::sizeSector.
     {
         if (sectorIndex == 0 && endIndex == NumberOfSectors())
         {
             SendEraseChip();
             sectorIndex += NumberOfSectors();
         }
         else if (sectorIndex % (sizeBlock / sizeSector) == 0 && sectorIndex + sizeBlock / sizeSector <= endIndex)
         {
             SendEraseBlock(sectorIndex);
             sectorIndex += sizeBlock / sizeSector;
         }
         else
         {
             SendEraseSector(sectorIndex);
             ++sectorIndex;
         }
     }
HoldWhileWriteInProgress()
void services::FlashQuadSpiSingleSpeed::HoldWhileWriteInProgress () override private virtual
Implements services::FlashQuadSpi.
Definition at line 81 of file FlashQuadSpiSingleSpeed.cpp.
References commandReadStatusRegister, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::PollStatus(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), services::FlashQuadSpi::spi, and statusFlagWriteInProgress.
     {
         static const hal::QuadSpi::Header pollWriteInProgressHeader{ infra::MakeOptional(commandReadStatusRegister), {}, {}, 0 };
         spi.PollStatus(pollWriteInProgressHeader, 1, 0, statusFlagWriteInProgress, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
PageProgram()
void services::FlashQuadSpiSingleSpeed::PageProgram () override protected virtual
Reimplemented from services::FlashQuadSpi.
Definition at line 27 of file FlashQuadSpiSingleSpeed.cpp.
References services::FlashQuadSpi::address, hal::Flash::AddressOffsetInSector(), services::FlashQuadSpi::buffer, commandPageProgram, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::Head(), infra::MakeOptional(), infra::MemoryRange< T >::pop_front(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), infra::MemoryRange< T >::size(), services::FlashQuadSpi::sizePage, and services::FlashQuadSpi::spi.
     {
         hal::QuadSpi::Header pageProgramHeader{ infra::MakeOptional(commandPageProgram), ConvertAddress(address),{}, 0 };
         infra::ConstByteRange currentBuffer = infra::Head(buffer, sizePage - AddressOffsetInSector(address) % sizePage);
         buffer.pop_front(currentBuffer.size());
         address += currentBuffer.size();
         spi.SendData(pageProgramHeader, currentBuffer, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
ReadBuffer()
void services::FlashQuadSpiSingleSpeed::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 20 of file FlashQuadSpiSingleSpeed.cpp.
References services::FlashQuadSpi::address, hal::QuadSpi::AddressToVector(), services::FlashQuadSpi::buffer, commandReadData, infra::MakeOptional(), services::FlashQuadSpi::onDone, hal::QuadSpi::ReceiveData(), hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
     {
         const hal::QuadSpi::Header header{ infra::MakeOptional(commandReadData), hal::QuadSpi::AddressToVector(address, 3), {}, 0 };
         spi.ReceiveData(header, buffer, hal::QuadSpi::Lines::SingleSpeed(), onDone);
     }
SendEraseBlock()
void services::FlashQuadSpiSingleSpeed::SendEraseBlock (uint32_t sectorIndex) private
Definition at line 69 of file FlashQuadSpiSingleSpeed.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseBlock, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), services::FlashQuadSpi::sectorIndex, hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseBlockHeader{ infra::MakeOptional(commandEraseBlock), ConvertAddress(AddressOfSector(sectorIndex)), {}, 0 };
         spi.SendData(eraseBlockHeader, {}, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseChip()
void services::FlashQuadSpiSingleSpeed::SendEraseChip () private
Definition at line 75 of file FlashQuadSpiSingleSpeed.cpp.
References commandEraseChip, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         static const hal::QuadSpi::Header eraseChipHeader{ infra::MakeOptional(commandEraseChip), {}, {}, 0 };
         spi.SendData(eraseChipHeader, {}, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
SendEraseSector()
void services::FlashQuadSpiSingleSpeed::SendEraseSector (uint32_t sectorIndex) private
Definition at line 63 of file FlashQuadSpiSingleSpeed.cpp.
References hal::FlashHomogeneous::AddressOfSector(), commandEraseSector, infra::Sequencer::Continue(), services::FlashQuadSpi::ConvertAddress(), infra::MakeOptional(), services::FlashQuadSpi::sectorIndex, hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
Referenced by EraseSomeSectors().
     {
         hal::QuadSpi::Header eraseSectorHeader{ infra::MakeOptional(commandEraseSector), ConvertAddress(AddressOfSector(sectorIndex)), {}, 0 };
         spi.SendData(eraseSectorHeader, {}, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
WriteEnable()
void services::FlashQuadSpiSingleSpeed::WriteEnable () override private virtual
Implements services::FlashQuadSpi.
Definition at line 38 of file FlashQuadSpiSingleSpeed.cpp.
References commandWriteEnable, infra::Sequencer::Continue(), infra::MakeOptional(), hal::QuadSpi::SendData(), services::FlashQuadSpi::sequencer, hal::QuadSpi::Lines::SingleSpeed(), and services::FlashQuadSpi::spi.
     {
         static const hal::QuadSpi::Header writeEnableHeader{ infra::MakeOptional(commandWriteEnable), {}, {}, 0 };
         spi.SendData(writeEnableHeader, {}, hal::QuadSpi::Lines::SingleSpeed(), [this]() { sequencer.Continue(); });
     }
Member Data Documentation
commandEraseBlock
const uint8_t services::FlashQuadSpiSingleSpeed::commandEraseBlock = 0xd8 static
Definition at line 18 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by SendEraseBlock().
commandEraseChip
const uint8_t services::FlashQuadSpiSingleSpeed::commandEraseChip = 0x60 static
Definition at line 19 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by SendEraseChip().
commandEraseHalfBlock
const uint8_t services::FlashQuadSpiSingleSpeed::commandEraseHalfBlock static
Definition at line 17 of file FlashQuadSpiSingleSpeed.hpp.
commandEraseSector
const uint8_t services::FlashQuadSpiSingleSpeed::commandEraseSector = 0x20 static
Definition at line 16 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by SendEraseSector().
commandPageProgram
const uint8_t services::FlashQuadSpiSingleSpeed::commandPageProgram = 0x02 static
Definition at line 12 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by PageProgram().
commandReadData
const uint8_t services::FlashQuadSpiSingleSpeed::commandReadData = 0x03 static
Definition at line 13 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by ReadBuffer().
commandReadStatusRegister
const uint8_t services::FlashQuadSpiSingleSpeed::commandReadStatusRegister = 0x05 static
Definition at line 14 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by HoldWhileWriteInProgress().
commandWriteEnable
const uint8_t services::FlashQuadSpiSingleSpeed::commandWriteEnable = 0x06 static
Definition at line 15 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by WriteEnable().
initDelayTimer
infra::TimerSingleShot services::FlashQuadSpiSingleSpeed::initDelayTimer private
Definition at line 41 of file FlashQuadSpiSingleSpeed.hpp.
onInitialized
infra::Function<void()> services::FlashQuadSpiSingleSpeed::onInitialized private
Definition at line 40 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by FlashQuadSpiSingleSpeed().
statusFlagWriteInProgress
const uint8_t services::FlashQuadSpiSingleSpeed::statusFlagWriteInProgress = 1 static
Definition at line 21 of file FlashQuadSpiSingleSpeed.hpp.
Referenced by HoldWhileWriteInProgress().
The documentation for this class was generated from the following files:
FlashQuadSpiSingleSpeed.hpp
FlashQuadSpiSingleSpeed.cpp