EMil: application::ImageEncryptorXtea Class Reference
application::ImageEncryptorXtea Class Reference
#include <ImageEncryptorXtea.hpp>
Public Member Functions
ImageEncryptorXtea (RandomNumberGenerator &randomNumberGenerator, infra::ConstByteRange key)
std::vector< uint8_t > Secure (const std::vector< uint8_t > &data) const
Static Public Attributes
static const std::size_t blockLength = 8
Private Member Functions
bool CheckDecryption (const std::vector< uint8_t > &original, const std::vector< uint8_t > &encrypted) const
Private Attributes
RandomNumberGenerator & randomNumberGenerator
infra::ConstByteRange key
Detailed Description
Definition at line 12 of file ImageEncryptorXtea.hpp.
Constructor & Destructor Documentation
ImageEncryptorXtea()
application::ImageEncryptorXtea::ImageEncryptorXtea (RandomNumberGenerator & randomNumberGenerator, infra::ConstByteRange key)
Definition at line 9 of file ImageEncryptorXtea.cpp.
         : randomNumberGenerator(randomNumberGenerator)
         , key(key)
     {}
Member Function Documentation
CheckDecryption()
bool application::ImageEncryptorXtea::CheckDecryption (const std::vector< uint8_t > & original, const std::vector< uint8_t > & encrypted) const private
Definition at line 38 of file ImageEncryptorXtea.cpp.
References infra::MemoryRange< T >::begin(), blockLength, and key.
Referenced by Secure().
     {
         std::vector<uint8_t> iv(encrypted.begin(), encrypted.begin() + blockLength);
         mbedtls_xtea_context ctx;
         mbedtls_xtea_init(&ctx);
         mbedtls_xtea_setup(&ctx, key.begin());                                                                                                          //TICS !INT#030
         if (encrypted.size() % blockLength != 0)
             return false;
         std::vector<uint8_t> decrypted(encrypted.size() - blockLength, 0);
         int ret = mbedtls_xtea_crypt_cbc(&ctx, MBEDTLS_XTEA_DECRYPT, decrypted.size(), iv.data(), encrypted.data() + blockLength, decrypted.data());    //TICS !INT#030
         return ret == 0 && mbedtls_xtea_self_test(0) == 0 && decrypted == original;
     }
Secure()
std::vector< uint8_t > application::ImageEncryptorXtea::Secure (const std::vector< uint8_t > & data) const
Definition at line 14 of file ImageEncryptorXtea.cpp.
References infra::MemoryRange< T >::begin(), blockLength, CheckDecryption(), infra::data, application::RandomNumberGenerator::Generate(), key, randomNumberGenerator, and infra::MemoryRange< T >::size().
Referenced by application::ImageSecurityXteaHmac::Secure().
     {
         std::vector<uint8_t> data = unalignedData;
         data.resize(data.size() + blockLength - (data.size() - 1 + blockLength) % blockLength - 1, 0);
         std::vector<uint8_t> iv = randomNumberGenerator.Generate(blockLength);
         mbedtls_xtea_context ctx;
         mbedtls_xtea_init(&ctx);
         assert(key.size() == 16);
         mbedtls_xtea_setup(&ctx, key.begin());                                                                                                          //TICS !INT#030
         std::vector<uint8_t> result = iv;
         result.resize(result.size() + data.size());
         int ret = mbedtls_xtea_crypt_cbc(&ctx, MBEDTLS_XTEA_ENCRYPT, data.size(), iv.data(), data.data(), result.data() + blockLength);                 //TICS !INT#030
         if (ret != 0)
             throw std::exception("XTEA encryption failed");
         if (!CheckDecryption(data, result))
             throw std::exception("XTEA decryption check failed");
         return result;
     }
Member Data Documentation
blockLength
const std::size_t application::ImageEncryptorXtea::blockLength = 8 static
Definition at line 15 of file ImageEncryptorXtea.hpp.
Referenced by CheckDecryption(), and Secure().
key
infra::ConstByteRange application::ImageEncryptorXtea::key private
Definition at line 25 of file ImageEncryptorXtea.hpp.
Referenced by CheckDecryption(), and Secure().
randomNumberGenerator
RandomNumberGenerator& application::ImageEncryptorXtea::randomNumberGenerator private
Definition at line 24 of file ImageEncryptorXtea.hpp.
Referenced by Secure().
The documentation for this class was generated from the following files:
ImageEncryptorXtea.hpp
ImageEncryptorXtea.cpp