EMil: TestSystemStateManager.cpp File Reference
TestSystemStateManager.cpp File Reference
Classes
class SystemStateTest
class TestParticipant
Functions
TEST_F (SystemStateTest, Construction)
TEST_F (SystemStateTest, RunSingleStateInEmptyManager)
TEST_F (SystemStateTest, RunSingleStateWithOneParticipant)
TEST_F (SystemStateTest, RunTwoStatesWithOneParticipant)
TEST_F (SystemStateTest, RunTwoStatesWithTwoParticipants)
Function Documentation
TEST_F() [1/5]
TEST_F (SystemStateTest , Construction)
Definition at line 33 of file TestSystemStateManager.cpp.
 {}
TEST_F() [2/5]
TEST_F (SystemStateTest , RunSingleStateInEmptyManager)
Definition at line 36 of file TestSystemStateManager.cpp.
 {
     static const std::array<infra::SystemStateBase, 1> singleStateSequence = { infra::StateInitializing() };
     manager.RunStates(singleStateSequence);
 }
TEST_F() [3/5]
TEST_F (SystemStateTest , RunSingleStateWithOneParticipant)
Definition at line 42 of file TestSystemStateManager.cpp.
References EXPECT_EQ(), infra::SystemStateParticipant::ReachedState(), and TestParticipant::requestedState.
 {
     TestParticipant participant(manager);
     static const std::array<infra::SystemStateBase, 1> singleStateSequence = { infra::StateInitializing() };
     manager.RunStates(singleStateSequence);
     EXPECT_EQ(infra::StateInitializing(), participant.requestedState);
     participant.ReachedState();
     ExecuteAllActions();
 }
TEST_F() [4/5]
TEST_F (SystemStateTest , RunTwoStatesWithOneParticipant)
Definition at line 54 of file TestSystemStateManager.cpp.
References EXPECT_EQ(), infra::SystemStateParticipant::ReachedState(), and TestParticipant::requestedState.
 {
     TestParticipant participant(manager);
     static const std::array<infra::SystemStateBase, 2> twoStateSequence = { infra::StateInitializing(), infra::StateRunning() };
     manager.RunStates(twoStateSequence);
     participant.ReachedState();
     ExecuteAllActions();
     EXPECT_EQ(infra::StateRunning(), participant.requestedState);
     participant.ReachedState();
     ExecuteAllActions();
 }
TEST_F() [5/5]
TEST_F (SystemStateTest , RunTwoStatesWithTwoParticipants)
Definition at line 69 of file TestSystemStateManager.cpp.
References EXPECT_EQ(), infra::SystemStateParticipant::ReachedState(), and TestParticipant::requestedState.
 {
     TestParticipant participant1(manager);
     TestParticipant participant2(manager);
     static const std::array<infra::SystemStateBase, 2> twoStateSequence = { infra::StateInitializing(), infra::StateRunning() };
     manager.RunStates(twoStateSequence);
     participant1.ReachedState();
     ExecuteAllActions();
     EXPECT_EQ(infra::StateInitializing(), participant1.requestedState);
     EXPECT_EQ(infra::StateInitializing(), participant2.requestedState);
     participant2.ReachedState();
     ExecuteAllActions();
     EXPECT_EQ(infra::StateRunning(), participant1.requestedState);
     EXPECT_EQ(infra::StateRunning(), participant2.requestedState);
     participant1.ReachedState();
     participant2.ReachedState();
     ExecuteAllActions();
 }