EMil: hal::LowPowerSerialCommunication Class Reference
hal::LowPowerSerialCommunication Class Reference
#include <LowPowerSerialCommunication.hpp>
Public Member Functions
LowPowerSerialCommunication (hal::SerialCommunication &serialCommunication, infra::MainClockReference &mainClockReference)
virtual void SendData (infra::ConstByteRange data, infra::Function< void()> actionOnCompletion) override
virtual void ReceiveData (infra::Function< void(infra::ConstByteRange data)> dataReceived) override
Private Attributes
infra::MainClockReference & mainClock
hal::SerialCommunication & serialCommunication
infra::AutoResetFunction< void()> actionOnCompletion
Additional Inherited Members
Protected Member Functions inherited from hal::SerialCommunication
SerialCommunication ()=default
~SerialCommunication ()=default
Detailed Description
Definition at line 10 of file LowPowerSerialCommunication.hpp.
Constructor & Destructor Documentation
LowPowerSerialCommunication()
hal::LowPowerSerialCommunication::LowPowerSerialCommunication (hal::SerialCommunication & serialCommunication, infra::MainClockReference & mainClockReference)
Definition at line 5 of file LowPowerSerialCommunication.cpp.
         : mainClock(mainClockReference)
         , serialCommunication(serialCommunication)
     {}
Member Function Documentation
ReceiveData()
void hal::LowPowerSerialCommunication::ReceiveData (infra::Function< void(infra::ConstByteRange data)> dataReceived) override virtual
Implements hal::SerialCommunication.
Definition at line 20 of file LowPowerSerialCommunication.cpp.
References hal::SerialCommunication::ReceiveData(), and serialCommunication.
     {
         serialCommunication.ReceiveData(dataReceived);
     }
SendData()
void hal::LowPowerSerialCommunication::SendData (infra::ConstByteRange data, infra::Function< void()> actionOnCompletion) override virtual
Implements hal::SerialCommunication.
Definition at line 10 of file LowPowerSerialCommunication.cpp.
References actionOnCompletion, mainClock, infra::MainClockReference::Refere(), infra::MainClockReference::Release(), hal::SerialCommunication::SendData(), and serialCommunication.
     {
         mainClock.Refere();
         this->actionOnCompletion = actionOnCompletion;
         serialCommunication.SendData(data, [this]() {
             this->actionOnCompletion();
             this->mainClock.Release();
         });
     }
Member Data Documentation
actionOnCompletion
infra::AutoResetFunction<void()> hal::LowPowerSerialCommunication::actionOnCompletion private
Definition at line 22 of file LowPowerSerialCommunication.hpp.
Referenced by SendData().
mainClock
infra::MainClockReference& hal::LowPowerSerialCommunication::mainClock private
Definition at line 20 of file LowPowerSerialCommunication.hpp.
Referenced by SendData().
serialCommunication
hal::SerialCommunication& hal::LowPowerSerialCommunication::serialCommunication private
Definition at line 21 of file LowPowerSerialCommunication.hpp.
Referenced by ReceiveData(), and SendData().
The documentation for this class was generated from the following files:
LowPowerSerialCommunication.hpp
LowPowerSerialCommunication.cpp