EMil: TestFlash.cpp File Reference
TestFlash.cpp File Reference
Classes
class FlashAddressTest
Functions
TEST_F (FlashAddressTest, StartAddress)
TEST_F (FlashAddressTest, AddressOfSector)
TEST_F (FlashAddressTest, StartOfSector)
TEST_F (FlashAddressTest, StartOfNextSector)
TEST_F (FlashAddressTest, StartOfNextSectorMidwayInASector)
TEST_F (FlashAddressTest, StartOfPreviousSector)
TEST_F (FlashAddressTest, StartOfPreviousSectorMidwayInASector)
Function Documentation
TEST_F() [1/7]
TEST_F (FlashAddressTest , StartAddress)
Definition at line 16 of file TestFlash.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     EXPECT_EQ(0, flash.SectorOfAddress(0));
     EXPECT_EQ(0, flash.AddressOffsetInSector(0));
     EXPECT_TRUE(flash.AtStartOfSector(0));
 }
TEST_F() [2/7]
TEST_F (FlashAddressTest , AddressOfSector)
Definition at line 23 of file TestFlash.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(7, flash.AddressOfSector(1));
 }
TEST_F() [3/7]
TEST_F (FlashAddressTest , StartOfSector)
Definition at line 28 of file TestFlash.cpp.
References EXPECT_EQ().
 {
     EXPECT_EQ(0, flash.StartOfSector(1));
 }
TEST_F() [4/7]
TEST_F (FlashAddressTest , StartOfNextSector)
Definition at line 33 of file TestFlash.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     EXPECT_EQ(7, flash.StartOfNextSector(0));
     EXPECT_TRUE(flash.AtStartOfSector(7));
 }
TEST_F() [5/7]
TEST_F (FlashAddressTest , StartOfNextSectorMidwayInASector)
Definition at line 39 of file TestFlash.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     EXPECT_EQ(7, flash.StartOfNextSector(1));
     EXPECT_TRUE(flash.AtStartOfSector(7));
 }
TEST_F() [6/7]
TEST_F (FlashAddressTest , StartOfPreviousSector)
Definition at line 45 of file TestFlash.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     EXPECT_EQ(0, flash.StartOfPreviousSector(7));
     EXPECT_TRUE(flash.AtStartOfSector(flash.StartOfPreviousSector(7)));
 }
TEST_F() [7/7]
TEST_F (FlashAddressTest , StartOfPreviousSectorMidwayInASector)
Definition at line 51 of file TestFlash.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     EXPECT_EQ(0, flash.StartOfPreviousSector(8));
     EXPECT_TRUE(flash.AtStartOfSector(flash.StartOfPreviousSector(8)));
 }