EMil: services::ConnectionMbedTls Class Reference
services::ConnectionMbedTls Class Reference
#include <ConnectionMbedTls.hpp>
Classes
struct ClientParameters
struct ParametersWorkaround
struct ServerParameters
class StreamReaderMbedTls
class StreamWriterMbedTls
Public Types
using Parameters = infra::Variant< ServerParameters, ClientParameters >
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Public Types inherited from infra::EnableSharedFromThis< ConnectionMbedTls >
using EnableSharedFromThisType = ConnectionMbedTls
Public Member Functions
ConnectionMbedTls (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver, CertificatesMbedTls &certificates, hal::SynchronousRandomDataGenerator &randomDataGenerator, const ParametersWorkaround &parameters)
ConnectionMbedTls (const ConnectionMbedTls &other)=delete
~ConnectionMbedTls ()
void CreatedObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
void SetHostname (infra::BoundedConstString hostname)
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
virtual void Connected () override
virtual void ClosingConnection () override
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
virtual void TlsInitFailure (int reason)
virtual void TlsReadFailure (int reason)
virtual void TlsWriteFailure (int reason)
virtual void TlsLog (int level, const char *file, int line, const char *message)
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionMbedTls >
SharedPtr< ConnectionMbedTls > SharedFromThis ()
SharedPtr< const ConnectionMbedTls > SharedFromThis () const
WeakPtr< ConnectionMbedTls > WeakFromThis ()
WeakPtr< const ConnectionMbedTls > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionMbedTls > sharedPtr)
Private Member Functions
void InitTls ()
void TryAllocateSendStream ()
void TryAllocateEncryptedSendStream ()
int SslSend (infra::ConstByteRange buffer)
int SslReceive (infra::ByteRange buffer)
void TrySend ()
void GenerateRandomData (infra::ByteRange data)
Static Private Member Functions
static int StaticSslSend (void *context, const unsigned char *buffer, std::size_t size)
static int StaticSslReceive (void *context, unsigned char *buffer, size_t size)
static int StaticGenerateRandomData (void *data, unsigned char *output, std::size_t size)
static void StaticDebugWrapper (void *context, int level, const char *file, int line, const char *message)
Private Attributes
infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> createdObserver
hal::SynchronousRandomDataGenerator & randomDataGenerator
bool server
mbedtls_ssl_session * clientSession = nullptr
mbedtls_ssl_context sslContext
mbedtls_ssl_config sslConfig
mbedtls_ctr_drbg_context ctr_drbg
infra::BoundedDeque< uint8_t >::WithMaxSize< 2048 > receiveBuffer
infra::BoundedDeque< uint8_t >::WithMaxSize< 2048 > sendBuffer
infra::SharedOptional< StreamWriterMbedTls > streamWriter
std::size_t requestedSendSize = 0
bool flushScheduled = false
infra::SharedOptional< StreamReaderMbedTls > receiveReader
infra::SharedPtr< infra::StreamWriter > encryptedSendWriter
std::size_t encryptedSendStreamSize = 0
bool initialHandshake = true
Additional Inherited Members
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionMbedTls >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 18 of file ConnectionMbedTls.hpp.
Member Typedef Documentation
Parameters
using services::ConnectionMbedTls::Parameters = infra::Variant<ServerParameters, ClientParameters>
Definition at line 35 of file ConnectionMbedTls.hpp.
Constructor & Destructor Documentation
ConnectionMbedTls() [1/2]
services::ConnectionMbedTls::ConnectionMbedTls (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver, CertificatesMbedTls & certificates, hal::SynchronousRandomDataGenerator & randomDataGenerator, const ParametersWorkaround & parameters)
Definition at line 7 of file ConnectionMbedTls.cpp.
References services::ConnectionMbedTls::ServerParameters::clientAuthenticationNeeded, services::CertificatesMbedTls::Config(), ctr_drbg, infra::Variant< T >::Get(), services::ConnectionMbedTls::ParametersWorkaround::parameters, server, services::ConnectionMbedTls::ServerParameters::serverCache, sslConfig, sslContext, StaticDebugWrapper(), and StaticGenerateRandomData().
         : createdObserver(std::move(createdObserver))
         , randomDataGenerator(randomDataGenerator)
         , server(parameters.parameters.Is<ServerParameters>())
         , clientSession(parameters.parameters.Is<ClientParameters>() ? &parameters.parameters.Get<ClientParameters>().clientSession : nullptr)
     {
         mbedtls_ssl_init(&sslContext);
         mbedtls_ssl_config_init(&sslConfig);
         mbedtls_ctr_drbg_init(&ctr_drbg);
         mbedtls_ssl_conf_dbg(&sslConfig, StaticDebugWrapper, this);
         int result;
         result = mbedtls_ctr_drbg_seed(&ctr_drbg, &ConnectionMbedTls::StaticGenerateRandomData, this, nullptr, 0);
         assert(result == 0);
         result = mbedtls_ssl_config_defaults(&sslConfig, server ? MBEDTLS_SSL_IS_SERVER : MBEDTLS_SSL_IS_CLIENT, MBEDTLS_SSL_TRANSPORT_STREAM, MBEDTLS_SSL_PRESET_DEFAULT);
         assert(result == 0);
         mbedtls_ssl_conf_rng(&sslConfig, mbedtls_ctr_drbg_random, &ctr_drbg);
         mbedtls_ssl_conf_authmode(&sslConfig, (server && !parameters.parameters.Get<ServerParameters>().clientAuthenticationNeeded) ? MBEDTLS_SSL_VERIFY_NONE : MBEDTLS_SSL_VERIFY_REQUIRED);
         certificates.Config(sslConfig);
         if (server)
             mbedtls_ssl_conf_session_cache(&sslConfig, &parameters.parameters.Get<ServerParameters>().serverCache, mbedtls_ssl_cache_get, mbedtls_ssl_cache_set);
         if (!server)
         {
             // mbedTLS can only talk with itself if the client enables ALPN. ALPN requires at least one protocol.
             static const char* protos[] = { "http/1.1", nullptr };
             mbedtls_ssl_conf_alpn_protocols(&sslConfig, protos);
         }
     }
ConnectionMbedTls() [2/2]
services::ConnectionMbedTls::ConnectionMbedTls (const ConnectionMbedTls & other) delete
~ConnectionMbedTls()
services::ConnectionMbedTls::~ConnectionMbedTls ()
Definition at line 63 of file ConnectionMbedTls.cpp.
References ctr_drbg, encryptedSendWriter, services::Connection::ResetOwnership(), sslConfig, and sslContext.
     {
         encryptedSendWriter = nullptr;
         mbedtls_ctr_drbg_free(&ctr_drbg);
         mbedtls_ssl_free(&sslContext);
         mbedtls_ssl_config_free(&sslConfig);
         ResetOwnership();
     }
Member Function Documentation
AbortAndDestroy()
void services::ConnectionMbedTls::AbortAndDestroy () override virtual
Implements services::Connection.
Definition at line 186 of file ConnectionMbedTls.cpp.
References encryptedSendWriter, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         encryptedSendWriter = nullptr;
         ConnectionObserver::Subject().AbortAndDestroy();
     }
AckReceived()
void services::ConnectionMbedTls::AckReceived () override virtual
Implements services::Connection.
Definition at line 175 of file ConnectionMbedTls.cpp.
References DataReceived(), and receiveReader.
     {
         receiveReader->ConsumeRead();
         DataReceived();
     }
CloseAndDestroy()
void services::ConnectionMbedTls::CloseAndDestroy () override virtual
Implements services::Connection.
Definition at line 181 of file ConnectionMbedTls.cpp.
References infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         ConnectionObserver::Subject().CloseAndDestroy();
     }
ClosingConnection()
void services::ConnectionMbedTls::ClosingConnection () override virtual
Reimplemented from services::ConnectionObserver.
Definition at line 151 of file ConnectionMbedTls.cpp.
References encryptedSendWriter, and services::Connection::ResetOwnership().
     {
         encryptedSendWriter = nullptr;
         ResetOwnership();
     }
Connected()
void services::ConnectionMbedTls::Connected () override virtual
Reimplemented from services::ConnectionObserver.
Definition at line 145 of file ConnectionMbedTls.cpp.
References infra::Subject< ConnectionObserver >::GetObserver(), and InitTls().
     {
         InitTls();
         GetObserver().Connected();
     }
CreatedObserver()
void services::ConnectionMbedTls::CreatedObserver (infra::SharedPtr< services::ConnectionObserver > connectionObserver)
Definition at line 74 of file ConnectionMbedTls.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), createdObserver, services::Connection::SetOwnership(), and infra::EnableSharedFromThis< ConnectionMbedTls >::SharedFromThis().
     {
         if (connectionObserver != nullptr)
         {
             connectionObserver->Attach(*this);
             SetOwnership(nullptr, connectionObserver);
             createdObserver(SharedFromThis());
         }
         else
             createdObserver(nullptr);
     }
DataReceived()
void services::ConnectionMbedTls::DataReceived () override virtual
Implements services::ConnectionObserver.
Definition at line 101 of file ConnectionMbedTls.cpp.
References infra::MemoryRange< T >::begin(), infra::BoundedDeque< T >::begin(), infra::BoundedDeque< T >::contiguous_range(), encryptedSendWriter, infra::BoundedDeque< T >::full(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::BoundedDeque< T >::max_size(), receiveBuffer, infra::BoundedDeque< T >::resize(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), infra::EnableSharedFromThis< ConnectionMbedTls >::SharedFromThis(), infra::MemoryRange< T >::size(), infra::BoundedDeque< T >::size(), sslContext, infra::SingleObserver< ConnectionObserver, Connection >::Subject(), and TlsReadFailure().
Referenced by AckReceived().
     {
         std::size_t startSize = receiveBuffer.size();
         while (!receiveBuffer.full())
         {
             std::size_t newBufferStart = receiveBuffer.size();
             receiveBuffer.resize(receiveBuffer.max_size());
             infra::ByteRange buffer = receiveBuffer.contiguous_range(receiveBuffer.begin() + newBufferStart);
             int result = mbedtls_ssl_read(&sslContext, reinterpret_cast<unsigned char*>(buffer.begin()), buffer.size());
             if (result == MBEDTLS_ERR_SSL_WANT_WRITE || result == MBEDTLS_ERR_SSL_WANT_READ)
             {
                 receiveBuffer.resize(newBufferStart);
                 break;
             }
             else if (result == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY)
             {
                 receiveBuffer.resize(newBufferStart);
                 break;
             }
             else if (result == MBEDTLS_ERR_SSL_BAD_INPUT_DATA)  // Precondition failure
             {
                 TlsReadFailure(result);
                 std::abort();
             }
             else if (result < 0)
             {
                 encryptedSendWriter = nullptr;
                 TlsReadFailure(result);
                 ConnectionObserver::Subject().AbortAndDestroy();
                 return;
             }
             else
                 receiveBuffer.resize(newBufferStart + static_cast<std::size_t>(result));
         }
         if (receiveBuffer.size() != startSize)
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionMbedTls>& object)
             {
                 object->GetObserver().DataReceived();
             }, SharedFromThis());
     }
GenerateRandomData()
void services::ConnectionMbedTls::GenerateRandomData (infra::ByteRange data) private
Definition at line 328 of file ConnectionMbedTls.cpp.
References infra::data, hal::SynchronousRandomDataGenerator::GenerateRandomData(), and randomDataGenerator.
Referenced by StaticGenerateRandomData().
     {
         randomDataGenerator.GenerateRandomData(data);
     }
InitTls()
void services::ConnectionMbedTls::InitTls () private
Definition at line 42 of file ConnectionMbedTls.cpp.
References clientSession, server, sslConfig, sslContext, StaticSslReceive(), StaticSslSend(), TlsInitFailure(), and TryAllocateEncryptedSendStream().
Referenced by Connected().
     {
         int result = mbedtls_ssl_setup(&sslContext, &sslConfig);
         if (result != 0)
             TlsInitFailure(result);
         really_assert(result == 0);
         if (!server)
         {
             if (clientSession->id_len != 0) // Workaround for what seems to be a problem in mbedTLS: When id_len = 0, then mbedTLS still thinks it can resume the session presented by the server
             {
                 result = mbedtls_ssl_set_session(&sslContext, clientSession);
                 assert(result == 0);
             }
         }
         mbedtls_ssl_set_bio(&sslContext, this, &ConnectionMbedTls::StaticSslSend, &ConnectionMbedTls::StaticSslReceive, nullptr);
         TryAllocateEncryptedSendStream();
     }
MaxSendStreamSize()
std::size_t services::ConnectionMbedTls::MaxSendStreamSize () const override virtual
Implements services::Connection.
Definition at line 165 of file ConnectionMbedTls.cpp.
References infra::BoundedDeque< T >::max_size(), and sendBuffer.
Referenced by RequestSendStream().
     {
         return sendBuffer.max_size();
     }
ReceiveStream()
infra::SharedPtr< infra::StreamReaderWithRewinding > services::ConnectionMbedTls::ReceiveStream () override virtual
Implements services::Connection.
Definition at line 170 of file ConnectionMbedTls.cpp.
References receiveReader.
     {
         return receiveReader.Emplace(*this);
     }
RequestSendStream()
void services::ConnectionMbedTls::RequestSendStream (std::size_t sendSize) override virtual
Implements services::Connection.
Definition at line 157 of file ConnectionMbedTls.cpp.
References MaxSendStreamSize(), requestedSendSize, and TryAllocateSendStream().
     {
         assert(requestedSendSize == 0);
         assert(sendSize != 0 && sendSize <= MaxSendStreamSize());
         requestedSendSize = sendSize;
         TryAllocateSendStream();
     }
SendStreamAvailable()
void services::ConnectionMbedTls::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::ConnectionObserver.
Definition at line 95 of file ConnectionMbedTls.cpp.
References encryptedSendWriter, and TrySend().
     {
         encryptedSendWriter = writer;
         TrySend();
     }
SetHostname()
void services::ConnectionMbedTls::SetHostname (infra::BoundedConstString hostname)
Definition at line 86 of file ConnectionMbedTls.cpp.
References sslContext.
     {
         infra::BoundedString::WithStorage<MBEDTLS_SSL_MAX_HOST_NAME_LEN + 1> terminatedHostname(hostname);
         terminatedHostname.push_back(0);
         int result = mbedtls_ssl_set_hostname(&sslContext, terminatedHostname.data());
         assert(result == 0);
     }
SslReceive()
int services::ConnectionMbedTls::SslReceive (infra::ByteRange buffer) private
Definition at line 261 of file ConnectionMbedTls.cpp.
References infra::MemoryRange< T >::begin(), infra::InputStream::ContiguousRange(), infra::MemoryRange< T >::empty(), infra::MemoryRange< T >::end(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), infra::EnableSharedFromThis< ConnectionMbedTls >::SharedFromThis(), infra::MemoryRange< T >::size(), and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by StaticSslReceive().
     {
         infra::SharedPtr<infra::StreamReader> reader = ConnectionObserver::Subject().ReceiveStream();
         infra::DataInputStream::WithErrorPolicy stream(*reader);
         infra::ConstByteRange streamBuffer = stream.ContiguousRange(buffer.size());
         std::copy(streamBuffer.begin(), streamBuffer.end(), buffer.begin());
         ConnectionObserver::Subject().AckReceived();
         if (!streamBuffer.empty())
         {
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionMbedTls>& object) { object->TrySend(); }, SharedFromThis());
             return streamBuffer.size();
         }
         else
             return MBEDTLS_ERR_SSL_WANT_READ;
     }
SslSend()
int services::ConnectionMbedTls::SslSend (infra::ConstByteRange buffer) private
Definition at line 235 of file ConnectionMbedTls.cpp.
References encryptedSendStreamSize, encryptedSendWriter, flushScheduled, infra::Head(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), infra::EnableSharedFromThis< ConnectionMbedTls >::SharedFromThis(), and infra::MemoryRange< T >::size().
Referenced by StaticSslSend().
     {
         if (encryptedSendWriter && encryptedSendStreamSize != 0)
         {
             buffer = infra::Head(buffer, encryptedSendStreamSize);
             encryptedSendStreamSize -= buffer.size();
             infra::DataOutputStream::WithErrorPolicy stream(*encryptedSendWriter);
             stream << buffer;
             if (!buffer.empty() && !flushScheduled)
             {
                 flushScheduled = true;
                 infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionMbedTls>& object)
                 {
                     object->flushScheduled = false;
                     object->encryptedSendWriter = nullptr;
                     object->TryAllocateEncryptedSendStream();
                 }, SharedFromThis());
             }
             return buffer.size();
         }
         else
             return MBEDTLS_ERR_SSL_WANT_WRITE;
     }
StaticDebugWrapper()
void services::ConnectionMbedTls::StaticDebugWrapper (void * context, int level, const char * file, int line, const char * message) static private
Definition at line 333 of file ConnectionMbedTls.cpp.
References TlsLog().
Referenced by ConnectionMbedTls().
     {
         reinterpret_cast<ConnectionMbedTls*>(context)->TlsLog(level, file, line, message);
     }
StaticGenerateRandomData()
int services::ConnectionMbedTls::StaticGenerateRandomData (void * data, unsigned char * output, std::size_t size) static private
Definition at line 322 of file ConnectionMbedTls.cpp.
References infra::data, and GenerateRandomData().
Referenced by ConnectionMbedTls().
     {
         reinterpret_cast<ConnectionMbedTls*>(data)->GenerateRandomData(infra::ByteRange(reinterpret_cast<uint8_t*>(output), reinterpret_cast<uint8_t*>(output) + size));
         return 0;
     }
StaticSslReceive()
int services::ConnectionMbedTls::StaticSslReceive (void * context, unsigned char * buffer, size_t size) static private
Definition at line 230 of file ConnectionMbedTls.cpp.
References SslReceive().
Referenced by InitTls().
     {
         return reinterpret_cast<ConnectionMbedTls*>(context)->SslReceive(infra::ByteRange(reinterpret_cast<uint8_t*>(buffer), reinterpret_cast<uint8_t*>(buffer) + size));
     }
StaticSslSend()
int services::ConnectionMbedTls::StaticSslSend (void * context, const unsigned char * buffer, std::size_t size) static private
Definition at line 225 of file ConnectionMbedTls.cpp.
References SslSend().
Referenced by InitTls().
     {
         return reinterpret_cast<ConnectionMbedTls*>(context)->SslSend(infra::ConstByteRange(reinterpret_cast<const uint8_t*>(buffer), reinterpret_cast<const uint8_t*>(buffer) + size));
     }
TlsInitFailure()
void services::ConnectionMbedTls::TlsInitFailure (int reason) virtual
Reimplemented in services::TracingConnectionMbedTls.
Definition at line 192 of file ConnectionMbedTls.cpp.
Referenced by InitTls().
     {}
TlsLog()
void services::ConnectionMbedTls::TlsLog (int level, const char * file, int line, const char * message) virtual
Reimplemented in services::TracingConnectionMbedTls.
Definition at line 201 of file ConnectionMbedTls.cpp.
Referenced by StaticDebugWrapper().
     {}
TlsReadFailure()
void services::ConnectionMbedTls::TlsReadFailure (int reason) virtual
Reimplemented in services::TracingConnectionMbedTls.
Definition at line 195 of file ConnectionMbedTls.cpp.
Referenced by DataReceived().
     {}
TlsWriteFailure()
void services::ConnectionMbedTls::TlsWriteFailure (int reason) virtual
Reimplemented in services::TracingConnectionMbedTls.
Definition at line 198 of file ConnectionMbedTls.cpp.
Referenced by TrySend().
     {}
TryAllocateEncryptedSendStream()
void services::ConnectionMbedTls::TryAllocateEncryptedSendStream () private
Definition at line 219 of file ConnectionMbedTls.cpp.
References encryptedSendStreamSize, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by InitTls().
     {
         encryptedSendStreamSize = ConnectionObserver::Subject().MaxSendStreamSize();
         ConnectionObserver::Subject().RequestSendStream(encryptedSendStreamSize);
     }
TryAllocateSendStream()
void services::ConnectionMbedTls::TryAllocateSendStream () private
Definition at line 204 of file ConnectionMbedTls.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), infra::BoundedDeque< T >::max_size(), requestedSendSize, infra::EventDispatcherWithWeakPtrWorker::Schedule(), sendBuffer, infra::EnableSharedFromThis< ConnectionMbedTls >::SharedFromThis(), infra::BoundedDeque< T >::size(), and streamWriter.
Referenced by RequestSendStream(), and TrySend().
     {
         assert(streamWriter.Allocatable());
         if (sendBuffer.max_size() - sendBuffer.size() >= requestedSendSize)
         {
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionMbedTls>& object)
             {
                 infra::SharedPtr<StreamWriterMbedTls> stream = object->streamWriter.Emplace(*object);
                 object->GetObserver().SendStreamAvailable(std::move(stream));
             }, SharedFromThis());
             requestedSendSize = 0;
         }
     }
TrySend()
void services::ConnectionMbedTls::TrySend () private
Definition at line 278 of file ConnectionMbedTls.cpp.
References infra::MemoryRange< T >::begin(), infra::BoundedDeque< T >::begin(), clientSession, infra::BoundedDeque< T >::contiguous_range(), infra::BoundedDeque< T >::empty(), encryptedSendWriter, infra::BoundedDeque< T >::erase(), initialHandshake, requestedSendSize, sendBuffer, server, infra::MemoryRange< T >::size(), sslContext, infra::SingleObserver< ConnectionObserver, Connection >::Subject(), TlsWriteFailure(), and TryAllocateSendStream().
Referenced by SendStreamAvailable().
     {
         while (initialHandshake || !sendBuffer.empty())
         {
             infra::ConstByteRange range = sendBuffer.contiguous_range(sendBuffer.begin());
             int result = initialHandshake
                 ? mbedtls_ssl_handshake(&sslContext)
                 : mbedtls_ssl_write(&sslContext, reinterpret_cast<const unsigned char*>(range.begin()), range.size());
             if (result == MBEDTLS_ERR_SSL_WANT_WRITE || result == MBEDTLS_ERR_SSL_WANT_READ)
                 return;
             else if (result == MBEDTLS_ERR_SSL_BAD_INPUT_DATA)  // Precondition failure
             {
                 TlsWriteFailure(result);
                 std::abort();
             }
             else if (result < 0)
             {
                 encryptedSendWriter = nullptr;
                 TlsWriteFailure(result);
                 ConnectionObserver::Subject().AbortAndDestroy();
                 return;
             }
             else if (initialHandshake)
             {
                 initialHandshake = false;
                 if (!server)
                 {
                     result = mbedtls_ssl_get_session(&sslContext, clientSession);
                     assert(result == 0);
                 }
             }
             else
             {
                 sendBuffer.erase(sendBuffer.begin(), sendBuffer.begin() + result);
                 if (static_cast<std::size_t>(result) < range.size())
                     break;
             }
         }
         if (requestedSendSize != 0)
             TryAllocateSendStream();
     }
Member Data Documentation
clientSession
mbedtls_ssl_session* services::ConnectionMbedTls::clientSession = nullptr private
Definition at line 116 of file ConnectionMbedTls.hpp.
Referenced by InitTls(), and TrySend().
createdObserver
infra::AutoResetFunction<void(infra::SharedPtr<services::ConnectionObserver> connectionObserver)> services::ConnectionMbedTls::createdObserver private
Definition at line 113 of file ConnectionMbedTls.hpp.
Referenced by CreatedObserver().
ctr_drbg
mbedtls_ctr_drbg_context services::ConnectionMbedTls::ctr_drbg private
Definition at line 119 of file ConnectionMbedTls.hpp.
Referenced by ConnectionMbedTls(), and ~ConnectionMbedTls().
encryptedSendStreamSize
std::size_t services::ConnectionMbedTls::encryptedSendStreamSize = 0 private
Definition at line 130 of file ConnectionMbedTls.hpp.
Referenced by SslSend(), and TryAllocateEncryptedSendStream().
encryptedSendWriter
infra::SharedPtr<infra::StreamWriter> services::ConnectionMbedTls::encryptedSendWriter private
Definition at line 129 of file ConnectionMbedTls.hpp.
Referenced by AbortAndDestroy(), ClosingConnection(), DataReceived(), SendStreamAvailable(), SslSend(), TrySend(), and ~ConnectionMbedTls().
flushScheduled
bool services::ConnectionMbedTls::flushScheduled = false private
Definition at line 126 of file ConnectionMbedTls.hpp.
Referenced by SslSend().
initialHandshake
bool services::ConnectionMbedTls::initialHandshake = true private
Definition at line 132 of file ConnectionMbedTls.hpp.
Referenced by TrySend().
randomDataGenerator
hal::SynchronousRandomDataGenerator& services::ConnectionMbedTls::randomDataGenerator private
Definition at line 114 of file ConnectionMbedTls.hpp.
Referenced by GenerateRandomData().
receiveBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<2048> services::ConnectionMbedTls::receiveBuffer private
Definition at line 121 of file ConnectionMbedTls.hpp.
Referenced by DataReceived().
receiveReader
infra::SharedOptional<StreamReaderMbedTls> services::ConnectionMbedTls::receiveReader private
Definition at line 127 of file ConnectionMbedTls.hpp.
Referenced by AckReceived(), and ReceiveStream().
requestedSendSize
std::size_t services::ConnectionMbedTls::requestedSendSize = 0 private
Definition at line 125 of file ConnectionMbedTls.hpp.
Referenced by RequestSendStream(), TryAllocateSendStream(), and TrySend().
sendBuffer
infra::BoundedDeque<uint8_t>::WithMaxSize<2048> services::ConnectionMbedTls::sendBuffer private
Definition at line 122 of file ConnectionMbedTls.hpp.
Referenced by MaxSendStreamSize(), TryAllocateSendStream(), and TrySend().
server
bool services::ConnectionMbedTls::server private
Definition at line 115 of file ConnectionMbedTls.hpp.
Referenced by ConnectionMbedTls(), InitTls(), and TrySend().
sslConfig
mbedtls_ssl_config services::ConnectionMbedTls::sslConfig private
Definition at line 118 of file ConnectionMbedTls.hpp.
Referenced by ConnectionMbedTls(), InitTls(), and ~ConnectionMbedTls().
sslContext
mbedtls_ssl_context services::ConnectionMbedTls::sslContext private
Definition at line 117 of file ConnectionMbedTls.hpp.
Referenced by ConnectionMbedTls(), DataReceived(), InitTls(), SetHostname(), TrySend(), and ~ConnectionMbedTls().
streamWriter
infra::SharedOptional<StreamWriterMbedTls> services::ConnectionMbedTls::streamWriter private
Definition at line 124 of file ConnectionMbedTls.hpp.
Referenced by TryAllocateSendStream().
The documentation for this class was generated from the following files:
ConnectionMbedTls.hpp
ConnectionMbedTls.cpp