EMil: TestHttpClientBasic.cpp File Reference
TestHttpClientBasic.cpp File Reference
Classes
class HttpClientBasicMock
class HttpClientBasicTest
Functions
TEST_F (HttpClientBasicTest, intermittent_error_is_reported_on_ConnectionFailed)
TEST_F (HttpClientBasicTest, Cancel_while_connecting_results_in_CancelConnect)
TEST_F (HttpClientBasicTest, Stop_while_connected_results_in_Close)
TEST_F (HttpClientBasicTest, Stop_while_connected_does_not_invoke_Done)
TEST_F (HttpClientBasicTest, second_Stop_while_connected_does_not_result_in_second_Close_but_adapts_callback)
TEST_F (HttpClientBasicTest, Stop_while_connected_stops_timeout_timer)
TEST_F (HttpClientBasicTest, Stop_while_almost_done)
TEST_F (HttpClientBasicTest, Stop_while_done)
TEST_F (HttpClientBasicTest, connection_times_out)
TEST_F (HttpClientBasicTest, timer_resets_after_BodyComplete)
TEST_F (HttpClientBasicTest, Stop_after_ClosingConnection)
Function Documentation
TEST_F() [1/11]
TEST_F (HttpClientBasicTest , intermittent_error_is_reported_on_ConnectionFailed)
Definition at line 50 of file TestHttpClientBasic.cpp.
 {
     EXPECT_CALL(*controller, Error(true));
     httpClientObserverFactory->ConnectionFailed(services::HttpClientObserverFactory::ConnectFailReason::nameLookupFailed);
 }
TEST_F() [2/11]
TEST_F (HttpClientBasicTest , Cancel_while_connecting_results_in_CancelConnect)
Definition at line 56 of file TestHttpClientBasic.cpp.
 {
     EXPECT_CALL(httpClientConnector, CancelConnect(testing::Ref(*httpClientObserverFactory)));
     EXPECT_CALL(onStopped, callback());
     controller->Cancel([this]() { onStopped.callback(); });
 }
TEST_F() [3/11]
TEST_F (HttpClientBasicTest , Stop_while_connected_results_in_Close)
Definition at line 63 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(httpClient, Close());
     controller->Cancel([this]() { onStopped.callback(); });
     EXPECT_CALL(onStopped, callback());
     httpClient.observer = nullptr;
     testing::Mock::VerifyAndClearExpectations(&onStopped);
 }
TEST_F() [4/11]
TEST_F (HttpClientBasicTest , Stop_while_connected_does_not_invoke_Done)
Definition at line 76 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected(), and infra::none.
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(httpClient, Close()).WillOnce(testing::Invoke([this]()
     {
         EXPECT_CALL(onStopped, callback());
         httpClient.observer = nullptr;
         controller = infra::none;
     }));
     controller->Cancel([this]() { onStopped.callback(); });
     testing::Mock::VerifyAndClearExpectations(&onStopped);
 }
TEST_F() [5/11]
TEST_F (HttpClientBasicTest , second_Stop_while_connected_does_not_result_in_second_Close_but_adapts_callback)
Definition at line 92 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(httpClient, Close());
     controller->Cancel([this]() { onStopped.callback(); });
     testing::StrictMock<infra::MockCallback<void()>> onStopped2;
     controller->Cancel([&onStopped2]() { onStopped2.callback(); });
     EXPECT_CALL(onStopped2, callback());
     httpClient.observer = nullptr;
     testing::Mock::VerifyAndClearExpectations(&onStopped2);
 }
TEST_F() [6/11]
TEST_F (HttpClientBasicTest , Stop_while_connected_stops_timeout_timer)
Definition at line 108 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(httpClient, Close());
     EXPECT_CALL(onStopped, callback());
     controller->Cancel([this]() { onStopped.callback(); });
     ForwardTime(std::chrono::minutes(2));
 }
TEST_F() [7/11]
TEST_F (HttpClientBasicTest , Stop_while_almost_done)
Definition at line 120 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->BodyComplete();
     controller->Cancel([this]() { onStopped.callback(); });
     EXPECT_CALL(onStopped, callback());
     httpClient.observer = nullptr;
     testing::Mock::VerifyAndClearExpectations(&onStopped);
 }
TEST_F() [8/11]
TEST_F (HttpClientBasicTest , Stop_while_done)
Definition at line 135 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(*controller, Done());
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->BodyComplete();
     httpClient.observer->ClosingConnection();
     httpClient.observer = nullptr;
     EXPECT_CALL(onStopped, callback());
     controller->Cancel([this]() { onStopped.callback(); });
     testing::Mock::VerifyAndClearExpectations(&onStopped);
 }
TEST_F() [9/11]
TEST_F (HttpClientBasicTest , connection_times_out)
Definition at line 151 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(*controller, Error(true));
     EXPECT_CALL(httpClient, Close());
     ForwardTime(std::chrono::minutes(1));
 }
TEST_F() [10/11]
TEST_F (HttpClientBasicTest , timer_resets_after_BodyComplete)
Definition at line 161 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(*controller, Done());
     EXPECT_CALL(httpClient, Close());
     httpClient.observer->BodyComplete();
     ForwardTime(std::chrono::minutes(1));
 }
TEST_F() [11/11]
TEST_F (HttpClientBasicTest , Stop_after_ClosingConnection)
Definition at line 173 of file TestHttpClientBasic.cpp.
References services::HttpClientObserver::Connected().
 {
     EXPECT_CALL(*controller, Established());
     httpClientObserverFactory->ConnectionEstablished([this](infra::SharedPtr<services::HttpClientObserver> client) { httpClient.AttachObserver(client); client->Connected(); });
     EXPECT_CALL(*controller, Error(true));
     httpClient.observer->ClosingConnection();
     httpClient.observer = nullptr;
     EXPECT_CALL(onStopped, callback());
     controller->Cancel([this]() { onStopped.callback(); });
     testing::Mock::VerifyAndClearExpectations(&onStopped);
 }