EMil: infra::BoundedStringBase< T > Class Template Reference
infra::BoundedStringBase< T > Class Template Reference
#include <BoundedString.hpp>
Public Types
using NonConstT = typename std::remove_const< T >::type
template<std::size_t Max>
using WithStorage = infra::WithStorage< BoundedStringBase, std::array< NonConstT, Max > >
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
using iterator = T *
using const_iterator = const T *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
BoundedStringBase ()
BoundedStringBase (MemoryRange< T > range)
BoundedStringBase (MemoryRange< NonConstT > range, size_type count)
BoundedStringBase (MemoryRange< NonConstT > range, size_type count, char ch)
BoundedStringBase (MemoryRange< NonConstT > range, const BoundedStringBase &other, size_type pos, size_type count=BoundedStringBase::npos)
BoundedStringBase (MemoryRange< NonConstT > range, const char *s, size_type count)
BoundedStringBase (MemoryRange< NonConstT > range, const char *s)
BoundedStringBase (MemoryRange< NonConstT > range, const std::string &s)
BoundedStringBase (T *s, size_type count)
BoundedStringBase (T *s)
BoundedStringBase (const std::string &s)
BoundedStringBase (std::string &s)
template<class InputIterator >
BoundedStringBase (MemoryRange< NonConstT > range, InputIterator first, InputIterator last)
BoundedStringBase (MemoryRange< NonConstT > range, std::initializer_list< char > initializerList)
template<class U >
BoundedStringBase (MemoryRange< NonConstT > range, const BoundedStringBase< U > &other)
BoundedStringBase (const BoundedStringBase &other)
template<class U >
BoundedStringBase (const BoundedStringBase< U > &other)
BoundedStringBase & operator= (const BoundedStringBase &other)
BoundedStringBase & operator= (const char *s)
BoundedStringBase & operator= (char ch)
BoundedStringBase & operator= (const std::string &s)
template<class U >
void AssignFromStorage (const BoundedStringBase< U > &other)
void AssignFromStorage (const char *s)
void AssignFromStorage (char ch)
void AssignFromStorage (const std::string &s)
BoundedStringBase & assign (size_type count, char ch)
template<class U >
BoundedStringBase & assign (const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase & assign (const BoundedStringBase< U > &other, size_type pos, size_type count)
BoundedStringBase & assign (const char *s, size_type count)
BoundedStringBase & assign (const char *s)
BoundedStringBase & assign (const std::string &s)
template<class InputIterator >
BoundedStringBase & assign (InputIterator first, InputIterator last)
reference operator[] (size_type pos)
const_reference operator[] (size_type pos) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
pointer data () const
iterator begin () const
const_iterator cbegin () const
iterator end () const
const_iterator cend () const
reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend () const
const_reverse_iterator crend () const
bool empty () const
bool full () const
size_type size () const
size_type max_size () const
void clear ()
BoundedStringBase & insert (size_type index, size_type count, char ch)
BoundedStringBase & insert (size_type index, const char *s)
BoundedStringBase & insert (size_type index, const char *s, size_type count)
BoundedStringBase & insert (size_type index, const BoundedStringBase &other)
BoundedStringBase & insert (size_type index, const BoundedStringBase &other, size_type index_str, size_type count)
BoundedStringBase & insert (size_type index, const std::string &other)
BoundedStringBase & insert (size_type index, const std::string &other, size_type index_str, size_type count)
iterator insert (const_iterator pos, char ch)
iterator insert (const_iterator pos, size_type count, char ch)
template<class InputIterator >
iterator insert (const_iterator i, InputIterator first, InputIterator last)
BoundedStringBase & erase (size_type index=0, size_type count=npos)
iterator erase (const_iterator position)
iterator erase (const_iterator first, const_iterator last)
void push_back (char ch)
void pop_back ()
BoundedStringBase & append (size_type count, char ch)
template<class U >
BoundedStringBase & append (const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase & append (const BoundedStringBase< U > &other, size_type pos, size_type count)
BoundedStringBase & append (const char *s, size_type count)
BoundedStringBase & append (const char *s)
BoundedStringBase & append (const std::string &s)
template<class InputIterator >
BoundedStringBase & append (InputIterator first, InputIterator last)
template<class U >
BoundedStringBase & operator+= (const BoundedStringBase< U > &other)
BoundedStringBase & operator+= (char ch)
BoundedStringBase & operator+= (const char *s)
BoundedStringBase & operator+= (const std::string &s)
int compare (const BoundedStringBase &other) const
int compare (size_type pos1, size_type count1, const BoundedStringBase &other) const
int compare (size_type pos1, size_type count1, const BoundedStringBase &other, size_type pos2, size_type count2) const
int compare (const char *s) const
int compare (size_type pos1, size_type count1, const char *s) const
int compare (size_type pos1, size_type count1, const char *s, size_type count2) const
int compare (const std::string &s) const
int compare (size_type pos1, size_type count1, const std::string &s) const
int compare (size_type pos1, size_type count1, const std::string &s, size_type count2) const
template<class U >
BoundedStringBase & replace (size_type pos, size_type count, const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase & replace (const_iterator first, const_iterator last, const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase & replace (size_type pos, size_type count, const BoundedStringBase< U > &other, size_type pos2, size_type count2)
template<class InputIterator >
BoundedStringBase & replace (const_iterator first, const_iterator last, InputIterator first2, InputIterator last2)
BoundedStringBase & replace (size_type pos, size_type count, const char *cstr, size_type count2)
BoundedStringBase & replace (const_iterator first, const_iterator last, const char *cstr, size_type count2)
BoundedStringBase & replace (size_type pos, size_type count, const char *cstr)
BoundedStringBase & replace (const_iterator first, const_iterator last, const char *cstr)
BoundedStringBase & replace (size_type pos, size_type count, const std::string &s, size_type count2)
BoundedStringBase & replace (const_iterator first, const_iterator last, const std::string &s, size_type count2)
BoundedStringBase & replace (size_type pos, size_type count, const std::string &s)
BoundedStringBase & replace (const_iterator first, const_iterator last, const std::string &s)
BoundedStringBase & replace (size_type pos, size_type count, size_type count2, char ch)
BoundedStringBase & replace (const_iterator first, const_iterator last, size_type count2, char ch)
BoundedStringBase substr (size_type pos=0, size_type count=npos)
BoundedStringBase< const T > substr (size_type pos=0, size_type count=npos) const
size_type copy (char *dest, size_type count, size_type pos=0)
void resize (size_type count)
void resize (size_type count, char ch)
void shrink (size_type count)
void swap (BoundedStringBase &other)
template<class U >
size_type find (const BoundedStringBase< U > &other, size_type pos=0) const
size_type find (const char *s, size_type pos, size_type count) const
size_type find (const char *s, size_type pos=0) const
size_type find (char ch, size_type pos=0) const
template<class U >
size_type rfind (const BoundedStringBase< U > &other, size_type pos=npos) const
size_type rfind (const char *s, size_type pos, size_type count) const
size_type rfind (const char *s, size_type pos=npos) const
size_type rfind (char ch, size_type pos=npos) const
template<class U >
size_type find_first_of (const BoundedStringBase< U > &other, size_type pos=0) const
size_type find_first_of (const char *s, size_type pos, size_type count) const
size_type find_first_of (const char *s, size_type pos=0) const
size_type find_first_of (char ch, size_type pos=0) const
template<class U >
size_type find_first_not_of (const BoundedStringBase< U > &other, size_type pos=0) const
size_type find_first_not_of (const char *s, size_type pos, size_type count) const
size_type find_first_not_of (const char *s, size_type pos=0) const
size_type find_first_not_of (char ch, size_type pos=0) const
template<class U >
size_type find_last_of (const BoundedStringBase< U > &other, size_type pos=npos) const
size_type find_last_of (const char *s, size_type pos, size_type count) const
size_type find_last_of (const char *s, size_type pos=npos) const
size_type find_last_of (char ch, size_type pos=npos) const
template<class U >
size_type find_last_not_of (const BoundedStringBase< U > &other, size_type pos=npos) const
size_type find_last_not_of (const char *s, size_type pos, size_type count) const
size_type find_last_not_of (const char *s, size_type pos=npos) const
size_type find_last_not_of (char ch, size_type pos=npos) const
template<class U >
BoundedStringBase< T > & assign (const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase< T > & assign (const BoundedStringBase< U > &other, size_type pos, size_type count)
template<class InputIterator >
BoundedStringBase< T > & assign (InputIterator first, InputIterator last)
template<class U >
BoundedStringBase< T > & append (const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase< T > & append (const BoundedStringBase< U > &other, size_type pos, size_type count)
template<class U >
BoundedStringBase< T > & operator+= (const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase< T > & replace (size_type pos, size_type count, const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase< T > & replace (const_iterator first, const_iterator last, const BoundedStringBase< U > &other)
template<class U >
BoundedStringBase< T > & replace (size_type pos, size_type count, const BoundedStringBase< U > &other, size_type pos2, size_type count2)
template<class InputIterator >
BoundedStringBase< T > & append (InputIterator first, InputIterator last)
template<class InputIterator >
BoundedStringBase< T > & replace (const_iterator first, const_iterator last, InputIterator first2, InputIterator last2)
Static Public Attributes
static const size_type npos = std::numeric_limits<size_type>::max()
Private Member Functions
void MoveUp (size_type start, size_type count)
void MoveDown (size_type start, size_type count)
int CompareImpl (const char *begin1, const char *end1, const char *begin2, const char *end2) const
void ReplaceImpl (char *begin1, size_type count1, const char *begin2, size_type count2)
void ReplaceImpl (char *begin1, size_type count1, char ch, size_type count2)
Static Private Member Functions
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, size_type count, char ch)
template<class U >
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, const BoundedStringBase< U > &other)
template<class U >
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, const BoundedStringBase< U > &other, size_type pos, size_type count)
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, const char *s, size_type count)
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, const char *s)
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, const std::string &s)
template<class InputIterator >
static void AssignToRange (MemoryRange< NonConstT > range, size_type &length, InputIterator first, InputIterator last)
Private Attributes
MemoryRange< T > range
size_type length = 0
Friends
template<class U >
class BoundedStringBase
Detailed Description
template<class T>
class infra::BoundedStringBase< T >
Definition at line 16 of file BoundedString.hpp.
Member Typedef Documentation
const_iterator
template<class T> using infra::BoundedStringBase< T >::const_iterator = const T*
Definition at line 38 of file BoundedString.hpp.
const_pointer
template<class T> using infra::BoundedStringBase< T >::const_pointer = const T*
Definition at line 36 of file BoundedString.hpp.
const_reference
template<class T> using infra::BoundedStringBase< T >::const_reference = const T&
Definition at line 34 of file BoundedString.hpp.
const_reverse_iterator
template<class T> using infra::BoundedStringBase< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 40 of file BoundedString.hpp.
difference_type
template<class T> using infra::BoundedStringBase< T >::difference_type = std::ptrdiff_t
Definition at line 32 of file BoundedString.hpp.
iterator
template<class T> using infra::BoundedStringBase< T >::iterator = T*
Definition at line 37 of file BoundedString.hpp.
NonConstT
template<class T> using infra::BoundedStringBase< T >::NonConstT = typename std::remove_const<T>::type
Definition at line 25 of file BoundedString.hpp.
pointer
template<class T> using infra::BoundedStringBase< T >::pointer = T*
Definition at line 35 of file BoundedString.hpp.
reference
template<class T> using infra::BoundedStringBase< T >::reference = T&
Definition at line 33 of file BoundedString.hpp.
reverse_iterator
template<class T> using infra::BoundedStringBase< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 39 of file BoundedString.hpp.
size_type
template<class T> using infra::BoundedStringBase< T >::size_type = std::size_t
Definition at line 31 of file BoundedString.hpp.
value_type
template<class T> using infra::BoundedStringBase< T >::value_type = T
Definition at line 30 of file BoundedString.hpp.
WithStorage
template<class T> template<std::size_t Max> using infra::BoundedStringBase< T >::WithStorage = infra::WithStorage<BoundedStringBase, std::array<NonConstT, Max> >
Definition at line 28 of file BoundedString.hpp.
Constructor & Destructor Documentation
BoundedStringBase() [1/17]
template<class T > infra::BoundedStringBase< T >::BoundedStringBase ()
Definition at line 362 of file BoundedString.hpp.
     {}
BoundedStringBase() [2/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< T > range) explicit
Definition at line 366 of file BoundedString.hpp.
         : range(range)
     {}
BoundedStringBase() [3/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, size_type count)
Definition at line 371 of file BoundedString.hpp.
         : range(range)
         , length(count)
     {}
BoundedStringBase() [4/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, size_type count, char ch)
Definition at line 377 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, count, ch);
     }
BoundedStringBase() [5/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, const BoundedStringBase< T > & other, size_type pos, size_type count = BoundedStringBase< T >::npos)
Definition at line 383 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, other, pos, count);
     }
BoundedStringBase() [6/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, const char * s, size_type count)
Definition at line 390 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, s, count);
     }
BoundedStringBase() [7/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, const char * s)
Definition at line 397 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, s);
     }
BoundedStringBase() [8/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, const std::string & s)
Definition at line 404 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, s);
     }
BoundedStringBase() [9/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (T * s, size_type count)
Definition at line 411 of file BoundedString.hpp.
         : range(s, s + count)
         , length(count)
     {}
BoundedStringBase() [10/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (T * s)
Definition at line 417 of file BoundedString.hpp.
         : range(s, s + std::strlen(s))
         , length(range.size())
     {}
BoundedStringBase() [11/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (const std::string & s)
Definition at line 423 of file BoundedString.hpp.
         : range(const_cast<char*>(s.data()), const_cast<char*>(s.data()) + s.size())
         , length(s.size())
     {}
BoundedStringBase() [12/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (std::string & s)
Definition at line 429 of file BoundedString.hpp.
         : range(const_cast<char*>(s.data()), const_cast<char*>(s.data()) + s.size())
         , length(s.size())
     {}
BoundedStringBase() [13/17]
template<class T > template<class InputIterator > infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, InputIterator first, InputIterator last)
Definition at line 1398 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, first, last);
     }
BoundedStringBase() [14/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, std::initializer_list< char > initializerList)
Definition at line 435 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, initializerList.begin(), initializerList.end());
     }
BoundedStringBase() [15/17]
template<class T > template<class U > infra::BoundedStringBase< T >::BoundedStringBase (MemoryRange< NonConstT > range, const BoundedStringBase< U > & other)
Definition at line 443 of file BoundedString.hpp.
         : range(range)
     {
         AssignToRange(range, length, other);
     }
BoundedStringBase() [16/17]
template<class T> infra::BoundedStringBase< T >::BoundedStringBase (const BoundedStringBase< T > & other)
Definition at line 450 of file BoundedString.hpp.
         : range(other.range)
         , length(other.length)
     {}
BoundedStringBase() [17/17]
template<class T > template<class U > infra::BoundedStringBase< T >::BoundedStringBase (const BoundedStringBase< U > & other)
Definition at line 1386 of file BoundedString.hpp.
         : range(other.range)
         , length(other.length)
     {
         T x = {};    // const char
         U y;    // char
         y = x;  // Test to see that this constructor is used for assigning a non-const string to a const string
         (void)y;
     }
Member Function Documentation
append() [1/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::append (size_type count, char ch)
Definition at line 809 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         for (; count > 0; --count, ++length)
             range[length] = ch;
         return *this;
     }
append() [2/10]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::append (const BoundedStringBase< U > & other)
append() [3/10]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::append (const BoundedStringBase< U > & other, size_type pos, size_type count)
append() [4/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::append (const char * s, size_type count)
Definition at line 841 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         for (const char* i = s; i != s + count; ++i, ++length)
             range[length] = *i;
         return *this;
     }
append() [5/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::append (const char * s)
Definition at line 851 of file BoundedString.hpp.
     {
         return append(s, std::strlen(s));
     }
append() [6/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::append (const std::string & s)
Definition at line 857 of file BoundedString.hpp.
     {
         return append(s.data(), s.size());
     }
append() [7/10]
template<class T> template<class InputIterator > BoundedStringBase& infra::BoundedStringBase< T >::append (InputIterator first, InputIterator last)
append() [8/10]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::append (const BoundedStringBase< U > & other)
Definition at line 820 of file BoundedString.hpp.
     {
         assert(length + other.size() <= max_size());
         for (const_iterator i = other.begin(); i != other.end(); ++i, ++length)
             range[length] = *i;
         return *this;
     }
append() [9/10]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::append (const BoundedStringBase< U > & other, size_type pos, size_type count)
Definition at line 831 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         for (const_iterator i = other.begin() + pos; i != other.begin() + pos + count; ++i, ++length)
             range[length] = *i;
         return *this;
     }
append() [10/10]
template<class T> template<class InputIterator > BoundedStringBase<T>& infra::BoundedStringBase< T >::append (InputIterator first, InputIterator last)
Definition at line 1419 of file BoundedString.hpp.
     {
         for (InputIterator i = first; i != last && length != max_size(); ++i, ++length)
             range[length] = *i;
         return *this;
     }
assign() [1/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::assign (size_type count, char ch)
Definition at line 507 of file BoundedString.hpp.
Referenced by infra::JsonSubObjectParser::Feed().
     {
         AssignToRange(range, length, count, ch);
         return *this;
     }
assign() [2/10]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::assign (const BoundedStringBase< U > & other)
assign() [3/10]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::assign (const BoundedStringBase< U > & other, size_type pos, size_type count)
assign() [4/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::assign (const char * s, size_type count)
Definition at line 533 of file BoundedString.hpp.
     {
         AssignToRange(range, length, s, count);
         return *this;
     }
assign() [5/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::assign (const char * s)
Definition at line 541 of file BoundedString.hpp.
     {
         AssignToRange(range, length, s);
         return *this;
     }
assign() [6/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::assign (const std::string & s)
Definition at line 549 of file BoundedString.hpp.
     {
         AssignToRange(range, length, s);
         return *this;
     }
assign() [7/10]
template<class T> template<class InputIterator > BoundedStringBase& infra::BoundedStringBase< T >::assign (InputIterator first, InputIterator last)
assign() [8/10]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::assign (const BoundedStringBase< U > & other)
Definition at line 516 of file BoundedString.hpp.
     {
         AssignToRange(range, length, other);
         return *this;
     }
assign() [9/10]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::assign (const BoundedStringBase< U > & other, size_type pos, size_type count)
Definition at line 525 of file BoundedString.hpp.
     {
         AssignToRange(range, length, other, pos, count);
         return *this;
     }
assign() [10/10]
template<class T> template<class InputIterator > BoundedStringBase<T>& infra::BoundedStringBase< T >::assign (InputIterator first, InputIterator last)
Definition at line 558 of file BoundedString.hpp.
     {
         AssignToRange(range, length, first, last);
         return *this;
     }
AssignFromStorage() [1/4]
template<class T > template<class U > void infra::BoundedStringBase< T >::AssignFromStorage (const BoundedStringBase< U > & other)
Definition at line 483 of file BoundedString.hpp.
     {
         assign(other);
     }
AssignFromStorage() [2/4]
template<class T > void infra::BoundedStringBase< T >::AssignFromStorage (const char * s)
Definition at line 489 of file BoundedString.hpp.
     {
         *this = s;
     }
AssignFromStorage() [3/4]
template<class T > void infra::BoundedStringBase< T >::AssignFromStorage (char ch)
Definition at line 495 of file BoundedString.hpp.
     {
         *this = ch;
     }
AssignFromStorage() [4/4]
template<class T > void infra::BoundedStringBase< T >::AssignFromStorage (const std::string & s)
Definition at line 501 of file BoundedString.hpp.
     {
         *this = s;
     }
AssignToRange() [1/7]
template<class T > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, size_type count, char ch) static private
Definition at line 1282 of file BoundedString.hpp.
     {
         assert(count <= range.size());
         length = count;
         std::fill(range.begin(), range.begin() + length, ch);
     }
AssignToRange() [2/7]
template<class T > template<class U > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, const BoundedStringBase< U > & other) static private
Definition at line 1291 of file BoundedString.hpp.
     {
         assert(other.size() <= range.size());
         length = other.length;
         std::copy(other.begin(), other.begin() + length, range.begin());
     }
AssignToRange() [3/7]
template<class T > template<class U > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, const BoundedStringBase< U > & other, size_type pos, size_type count) static private
Definition at line 1300 of file BoundedString.hpp.
     {
         count = std::min(count, other.size());
         assert(count <= range.size());
         length = count;
         std::copy(other.range.begin() + pos, other.range.begin() + pos + length, range.begin());
     }
AssignToRange() [4/7]
template<class T > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, const char * s, size_type count) static private
Definition at line 1309 of file BoundedString.hpp.
     {
         assert(count <= range.size());
         length = count;
         std::copy(s, s + length, range.begin());
     }
AssignToRange() [5/7]
template<class T > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, const char * s) static private
Definition at line 1317 of file BoundedString.hpp.
     {
         AssignToRange(range, length, s, std::strlen(s));
     }
AssignToRange() [6/7]
template<class T > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, const std::string & s) static private
Definition at line 1323 of file BoundedString.hpp.
     {
         AssignToRange(range, length, s.data(), s.size());
     }
AssignToRange() [7/7]
template<class T > template<class InputIterator > void infra::BoundedStringBase< T >::AssignToRange (infra::MemoryRange< NonConstT > range, size_type & length, InputIterator first, InputIterator last) static private
Definition at line 1330 of file BoundedString.hpp.
     {
         for (length = 0; length != range.size() && first != last; ++length, ++first)
             range[length] = *first;
     }
back() [1/2]
template<class T > T & infra::BoundedStringBase< T >::back ()
Definition at line 590 of file BoundedString.hpp.
     {
         return range[length - 1];
     }
back() [2/2]
template<class T > const T & infra::BoundedStringBase< T >::back () const
Definition at line 596 of file BoundedString.hpp.
     {
         return range[length - 1];
     }
begin()
template<class T > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::begin () const
Definition at line 608 of file BoundedString.hpp.
Referenced by infra::BoundedStringBase< char >::append(), infra::BoundedStringBase< char >::AssignToRange(), infra::JsonString::begin(), infra::BoundedStringBase< char >::cbegin(), infra::BoundedStringBase< char >::cend(), infra::BoundedStringBase< char >::compare(), infra::BoundedStringBase< char >::find(), infra::BoundedStringBase< char >::find_first_not_of(), infra::BoundedStringBase< char >::find_first_of(), infra::BoundedStringBase< char >::find_last_not_of(), infra::BoundedStringBase< char >::find_last_of(), services::NameResolverCache::Hash(), infra::BoundedStringBase< char >::insert(), services::NameLookupBsd::LookupIPv4(), services::NameLookupWin::LookupIPv4(), infra::MakeRange(), infra::operator+(), infra::JsonString::operator==(), infra::operator==(), infra::TextInputStream::operator>>(), services::HttpClientBasic::Path(), infra::BoundedStringBase< char >::replace(), and infra::BoundedStringBase< char >::rfind().
     {
         return range.begin();
     }
cbegin()
template<class T > BoundedStringBase< T >::const_iterator infra::BoundedStringBase< T >::cbegin () const
Definition at line 614 of file BoundedString.hpp.
     {
         return range.begin();
     }
cend()
template<class T > BoundedStringBase< T >::const_iterator infra::BoundedStringBase< T >::cend () const
Definition at line 626 of file BoundedString.hpp.
     {
         return range.begin() + length;
     }
clear()
template<class T > void infra::BoundedStringBase< T >::clear ()
Definition at line 680 of file BoundedString.hpp.
Referenced by infra::CleanJsonContents(), infra::JsonSubObjectParser::Feed(), infra::JsonSubArrayParser::Feed(), infra::JsonSubObjectParser::JsonSubObjectParser(), services::HttpServerConnectionObserver::PrepareForNextRequest(), services::HttpServerConnectionObserver::SendResponse(), infra::JsonString::ToString(), services::CertificatesMbedTls::WriteOwnCertificate(), and services::CertificatesMbedTls::WritePrivateKey().
     {
         length = 0;
     }
compare() [1/9]
template<class T > int infra::BoundedStringBase< T >::compare (const BoundedStringBase< T > & other) const
Definition at line 888 of file BoundedString.hpp.
     {
         return CompareImpl(begin(), end(), other.begin(), other.end());
     }
compare() [2/9]
template<class T > int infra::BoundedStringBase< T >::compare (size_type pos1, size_type count1, const BoundedStringBase< T > & other) const
Definition at line 894 of file BoundedString.hpp.
     {
         return CompareImpl(begin() + pos1, begin() + pos1 + count1, other.begin(), other.end());
     }
compare() [3/9]
template<class T > int infra::BoundedStringBase< T >::compare (size_type pos1, size_type count1, const BoundedStringBase< T > & other, size_type pos2, size_type count2) const
Definition at line 900 of file BoundedString.hpp.
     {
         return CompareImpl(begin() + pos1, begin() + pos1 + count1, other.begin() + pos2, other.begin() + pos2 + count2);
     }
compare() [4/9]
template<class T > int infra::BoundedStringBase< T >::compare (const char * s) const
Definition at line 906 of file BoundedString.hpp.
     {
         return CompareImpl(begin(), end(), s, s + std::strlen(s));
     }
compare() [5/9]
template<class T > int infra::BoundedStringBase< T >::compare (size_type pos1, size_type count1, const char * s) const
Definition at line 912 of file BoundedString.hpp.
     {
         return CompareImpl(begin() + pos1, begin() + pos1 + count1, s, s + std::strlen(s));
     }
compare() [6/9]
template<class T > int infra::BoundedStringBase< T >::compare (size_type pos1, size_type count1, const char * s, size_type count2) const
Definition at line 918 of file BoundedString.hpp.
     {
         return CompareImpl(begin() + pos1, begin() + pos1 + count1, s, s + count2);
     }
compare() [7/9]
template<class T > int infra::BoundedStringBase< T >::compare (const std::string & s) const
Definition at line 924 of file BoundedString.hpp.
     {
         return CompareImpl(begin(), end(), s.data(), s.data() + s.size());
     }
compare() [8/9]
template<class T > int infra::BoundedStringBase< T >::compare (size_type pos1, size_type count1, const std::string & s) const
Definition at line 930 of file BoundedString.hpp.
     {
         return CompareImpl(begin() + pos1, begin() + pos1 + count1, s.data(), s.data() + s.size());
     }
compare() [9/9]
template<class T > int infra::BoundedStringBase< T >::compare (size_type pos1, size_type count1, const std::string & s, size_type count2) const
Definition at line 936 of file BoundedString.hpp.
     {
         return CompareImpl(begin() + pos1, begin() + pos1 + count1, s.data(), s.data() + count2);
     }
CompareImpl()
template<class T > int infra::BoundedStringBase< T >::CompareImpl (const char * begin1, const char * end1, const char * begin2, const char * end2) const private
Definition at line 1351 of file BoundedString.hpp.
     {
         for (; begin1 != end1 && begin2 != end2; ++begin1, ++begin2)
             if (*begin1 != *begin2)
                 return *begin1 < *begin2 ? -1 : 1;
         if (begin1 != end1)
             return 1;
         if (begin2 != end2)
             return -1;
         return 0;
     }
copy()
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::copy (char * dest, size_type count, size_type pos = 0)
Definition at line 1052 of file BoundedString.hpp.
     {
         assert(pos + count <= length);
         std::copy(begin() + pos, begin() + pos + count, dest);
         return count;
     }
crbegin()
template<class T > BoundedStringBase< T >::const_reverse_iterator infra::BoundedStringBase< T >::crbegin () const
Definition at line 638 of file BoundedString.hpp.
     {
         return reverse_iterator(range.begin() + length);
     }
crend()
template<class T > BoundedStringBase< T >::const_reverse_iterator infra::BoundedStringBase< T >::crend () const
Definition at line 650 of file BoundedString.hpp.
     {
         return reverse_iterator(range.begin());
     }
data()
template<class T > T * infra::BoundedStringBase< T >::data () const
Definition at line 602 of file BoundedString.hpp.
Referenced by services::CertificatesMbedTls::AddCertificateAuthority(), services::CertificatesMbedTls::AddOwnCertificate(), and application::UpgradePackConfigParser::CheckMandatoryKeys().
     {
         return range.begin();
     }
empty()
template<class T > bool infra::BoundedStringBase< T >::empty () const
Definition at line 656 of file BoundedString.hpp.
Referenced by services::HttpRequestFormatter::HttpRequestFormatter(), infra::JsonEscapedStringSize(), services::DnsResolver::ActiveLookup::QuerySize(), and services::DnsResolver::ActiveLookup::WriteHostname().
     {
         return length == 0;
     }
end()
template<class T > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::end () const
Definition at line 620 of file BoundedString.hpp.
Referenced by infra::BoundedStringBase< char >::append(), infra::JsonString::begin(), infra::BoundedStringBase< char >::compare(), infra::JsonString::end(), infra::BoundedStringBase< char >::insert(), services::NameLookupBsd::LookupIPv4(), services::NameLookupWin::LookupIPv4(), infra::MakeRange(), infra::operator+(), infra::JsonString::operator==(), infra::operator==(), and infra::TextInputStream::operator>>().
     {
         return range.begin() + length;
     }
erase() [1/3]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::erase (size_type index = 0, size_type count = npos)
Definition at line 772 of file BoundedString.hpp.
     {
         count = std::min(count, length - index);
         MoveDown(index, count);
         return *this;
     }
erase() [2/3]
template<class T > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::erase (const_iterator position)
Definition at line 780 of file BoundedString.hpp.
     {
         MoveDown(position - begin(), 1);
         return begin() + (position - begin());
     }
erase() [3/3]
template<class T > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::erase (const_iterator first, const_iterator last)
Definition at line 787 of file BoundedString.hpp.
     {
         MoveDown(first - begin(), std::distance(first, last));
         return begin() + (first - begin());
     }
find() [1/4]
template<class T > template<class U > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find (const BoundedStringBase< U > & other, size_type pos = 0) const
Definition at line 1102 of file BoundedString.hpp.
Referenced by services::HttpRequestParserImpl::EnumerateHeaders(), services::HttpRequestParserImpl::Header(), services::HostFromUrl(), services::TimeWithLocalization::OffsetFromTimeString(), services::PathFromUrl(), services::Terminal::ProcessEscapeSequence(), services::DnsResolver::ActiveLookup::QuerySize(), services::SchemeFromUrl(), and services::DnsResolver::ActiveLookup::WriteHostname().
     {
         return find(other.begin(), pos, other.size());
     }
find() [2/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find (const char * s, size_type pos, size_type count) const
Definition at line 1108 of file BoundedString.hpp.
     {
         assert(pos <= length);
         for (const_iterator i = begin() + pos; i + count <= end(); ++i)
             if (CompareImpl(i, i + count, s, s + count) == 0)
                 return i - begin();
         return npos;
     }
find() [3/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find (const char * s, size_type pos = 0) const
Definition at line 1119 of file BoundedString.hpp.
     {
         return find(s, pos, std::strlen(s));
     }
find() [4/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find (char ch, size_type pos = 0) const
Definition at line 1125 of file BoundedString.hpp.
     {
         return find(&ch, pos, 1);
     }
find_first_not_of() [1/4]
template<class T > template<class U > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_not_of (const BoundedStringBase< U > & other, size_type pos = 0) const
Definition at line 1193 of file BoundedString.hpp.
     {
         return find_first_not_of(other.begin(), pos, other.size());
     }
find_first_not_of() [2/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_not_of (const char * s, size_type pos, size_type count) const
Definition at line 1199 of file BoundedString.hpp.
     {
         pos = std::min(pos, length);
         for (const_iterator i = begin() + pos; i != end(); ++i)
             if (std::find(s, s + count, *i) == s + count)
                 return i - begin();
         return npos;
     }
find_first_not_of() [3/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_not_of (const char * s, size_type pos = 0) const
Definition at line 1210 of file BoundedString.hpp.
     {
         return find_first_not_of(s, pos, std::strlen(s));
     }
find_first_not_of() [4/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_not_of (char ch, size_type pos = 0) const
Definition at line 1216 of file BoundedString.hpp.
     {
         return find_first_not_of(&ch, pos, 1);
     }
find_first_of() [1/4]
template<class T > template<class U > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_of (const BoundedStringBase< U > & other, size_type pos = 0) const
Definition at line 1163 of file BoundedString.hpp.
Referenced by services::TimeWithLocalization::OffsetFromTimeString(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), and services::HttpClientImpl::HttpResponseParser::ParseStatusLine().
     {
         return find_first_of(other.begin(), pos, other.size());
     }
find_first_of() [2/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_of (const char * s, size_type pos, size_type count) const
Definition at line 1169 of file BoundedString.hpp.
     {
         pos = std::min(pos, length);
         for (const_iterator i = begin() + pos; i != end(); ++i)
             if (std::find(s, s + count, *i) != s + count)
                 return i - begin();
         return npos;
     }
find_first_of() [3/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_of (const char * s, size_type pos = 0) const
Definition at line 1180 of file BoundedString.hpp.
     {
         return find_first_of(s, pos, std::strlen(s));
     }
find_first_of() [4/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_first_of (char ch, size_type pos = 0) const
Definition at line 1186 of file BoundedString.hpp.
     {
         return find_first_of(&ch, pos, 1);
     }
find_last_not_of() [1/4]
template<class T > template<class U > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_not_of (const BoundedStringBase< U > & other, size_type pos = npos) const
Definition at line 1253 of file BoundedString.hpp.
     {
         return find_last_not_of(other.begin(), pos, other.size());
     }
find_last_not_of() [2/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_not_of (const char * s, size_type pos, size_type count) const
Definition at line 1259 of file BoundedString.hpp.
     {
         pos = std::min(pos, length);
         for (const_iterator i = begin() + pos - 1; i >= begin(); --i)
             if (std::find(s, s + count, *i) == s + count)
                 return i - begin();
         return npos;
     }
find_last_not_of() [3/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_not_of (const char * s, size_type pos = npos) const
Definition at line 1270 of file BoundedString.hpp.
     {
         return find_last_not_of(s, pos, std::strlen(s));
     }
find_last_not_of() [4/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_not_of (char ch, size_type pos = npos) const
Definition at line 1276 of file BoundedString.hpp.
     {
         return find_last_not_of(&ch, pos, 1);
     }
find_last_of() [1/4]
template<class T > template<class U > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_of (const BoundedStringBase< U > & other, size_type pos = npos) const
Definition at line 1223 of file BoundedString.hpp.
Referenced by services::TracingConnectionMbedTls::TlsLog().
     {
         return find_last_of(other.begin(), pos, other.size());
     }
find_last_of() [2/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_of (const char * s, size_type pos, size_type count) const
Definition at line 1229 of file BoundedString.hpp.
     {
         pos = std::min(pos, length);
         for (const_iterator i = begin() + pos - 1; i >= begin(); --i)
             if (std::find(s, s + count, *i) != s + count)
                 return i - begin();
         return npos;
     }
find_last_of() [3/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_of (const char * s, size_type pos = npos) const
Definition at line 1240 of file BoundedString.hpp.
     {
         return find_last_of(s, pos, std::strlen(s));
     }
find_last_of() [4/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::find_last_of (char ch, size_type pos = npos) const
Definition at line 1246 of file BoundedString.hpp.
     {
         return find_last_of(&ch, pos, 1);
     }
front() [1/2]
template<class T > T & infra::BoundedStringBase< T >::front ()
Definition at line 578 of file BoundedString.hpp.
Referenced by infra::BoundedStringBase< char >::front().
     {
         return range.front();
     }
front() [2/2]
template<class T > const T & infra::BoundedStringBase< T >::front () const
Definition at line 584 of file BoundedString.hpp.
     {
         return range.front();
     }
full()
template<class T > bool infra::BoundedStringBase< T >::full () const
Definition at line 662 of file BoundedString.hpp.
Referenced by infra::JsonSubParser::AddToValueBuffer(), infra::JsonString::AppendTo(), infra::JsonSubParser::FeedToken(), and services::HttpClientImpl::HttpResponseParser::ParseHeaders().
     {
         return length == max_size();
     }
insert() [1/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, size_type count, char ch)
Definition at line 686 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         MoveUp(index, count);
         for (; count != 0; --count)
             range[index++] = ch;
         return *this;
     }
insert() [2/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, const char * s)
Definition at line 697 of file BoundedString.hpp.
     {
         return insert(index, s, std::strlen(s));
     }
insert() [3/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, const char * s, size_type count)
Definition at line 703 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         MoveUp(index, count);
         for (; count != 0; --count)
             range[index++] = *s++;
         return *this;
     }
insert() [4/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, const BoundedStringBase< T > & other)
Definition at line 714 of file BoundedString.hpp.
     {
         assert(length + other.size() <= max_size());
         MoveUp(index, other.size());
         for (const_iterator i = other.begin(); i != other.end(); ++i)
             range[index++] = *i;
         return *this;
     }
insert() [5/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, const BoundedStringBase< T > & other, size_type index_str, size_type count)
Definition at line 725 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         MoveUp(index, count);
         const_iterator i = other.begin() + index_str;
         for (; count != 0; --count)
             range[index++] = *i++;
         return *this;
     }
insert() [6/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, const std::string & other)
Definition at line 737 of file BoundedString.hpp.
     {
         return insert(index, other.data(), other.size());
     }
insert() [7/10]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::insert (size_type index, const std::string & other, size_type index_str, size_type count)
Definition at line 743 of file BoundedString.hpp.
     {
         return insert(index, other.data() + index_str, count);
     }
insert() [8/10]
template<class T > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::insert (const_iterator pos, char ch)
Definition at line 749 of file BoundedString.hpp.
     {
         assert(length != max_size());
         size_type index = pos - begin();
         MoveUp(index, 1);
         range[index++] = ch;
         return begin() + index;
     }
insert() [9/10]
template<class T > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::insert (const_iterator pos, size_type count, char ch)
Definition at line 760 of file BoundedString.hpp.
     {
         assert(length + count <= max_size());
         size_type index = pos - begin();
         MoveUp(index, count);
         for (; count != 0; --count)
             range[index++] = ch;
         return begin() + index;
     }
insert() [10/10]
template<class T > template<class InputIterator > BoundedStringBase< T >::iterator infra::BoundedStringBase< T >::insert (const_iterator i, InputIterator first, InputIterator last)
Definition at line 1406 of file BoundedString.hpp.
     {
         std::size_t additional = std::min(max_size() - length, static_cast<size_type>(std::distance(first, last)));
         size_type index = i - begin();
         MoveUp(index, additional);
         for (; additional != 0; --additional)
             range[index++] = *first++;
         return &range[index];
     }
max_size()
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::max_size () const
Definition at line 674 of file BoundedString.hpp.
Referenced by services::HttpServerConnectionObserver::DataReceived(), infra::JsonSubObjectParser::Feed(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpClientImpl::HttpResponseParser::ParseStatusLine(), and services::HttpClientBasic::Path().
     {
         return range.size();
     }
MoveDown()
template<class T > void infra::BoundedStringBase< T >::MoveDown (size_type start, size_type count) private
Definition at line 1344 of file BoundedString.hpp.
     {
         std::memmove(range.begin() + start, range.begin() + start + count, length - start - count);
         length -= count;
     }
MoveUp()
template<class T > void infra::BoundedStringBase< T >::MoveUp (size_type start, size_type count) private
Definition at line 1337 of file BoundedString.hpp.
     {
         std::memmove(range.begin() + start + count, range.begin() + start, length - start);
         length += count;
     }
operator+=() [1/5]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::operator+= (const BoundedStringBase< U > & other)
operator+=() [2/5]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator+= (char ch)
Definition at line 870 of file BoundedString.hpp.
     {
         return append(1, ch);
     }
operator+=() [3/5]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator+= (const char * s)
Definition at line 876 of file BoundedString.hpp.
     {
         return append(s);
     }
operator+=() [4/5]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator+= (const std::string & s)
Definition at line 882 of file BoundedString.hpp.
     {
         return append(s);
     }
operator+=() [5/5]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::operator+= (const BoundedStringBase< U > & other)
Definition at line 864 of file BoundedString.hpp.
     {
         return append(other);
     }
operator=() [1/4]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator= (const BoundedStringBase< T > & other)
Definition at line 456 of file BoundedString.hpp.
     {
         range = other.range;
         length = other.length;
         return *this;
     }
operator=() [2/4]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator= (const char * s)
Definition at line 464 of file BoundedString.hpp.
     {
         return assign(s);
     }
operator=() [3/4]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator= (char ch)
Definition at line 470 of file BoundedString.hpp.
     {
         return assign(1, ch);
     }
operator=() [4/4]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::operator= (const std::string & s)
Definition at line 476 of file BoundedString.hpp.
     {
         return assign(s);
     }
operator[]() [1/2]
template<class T > T & infra::BoundedStringBase< T >::operator[] (size_type pos)
Definition at line 566 of file BoundedString.hpp.
     {
         return range[pos];
     }
operator[]() [2/2]
template<class T > const T & infra::BoundedStringBase< T >::operator[] (size_type pos) const
Definition at line 572 of file BoundedString.hpp.
     {
         return range[pos];
     }
pop_back()
template<class T > void infra::BoundedStringBase< T >::pop_back ()
Definition at line 802 of file BoundedString.hpp.
     {
         assert(length > 0);
         --length;
     }
push_back()
template<class T > void infra::BoundedStringBase< T >::push_back (char ch)
Definition at line 794 of file BoundedString.hpp.
Referenced by infra::JsonString::AppendTo().
     {
         assert(length != max_size());
         range[length] = ch;
         ++length;
     }
rbegin()
template<class T > BoundedStringBase< T >::reverse_iterator infra::BoundedStringBase< T >::rbegin () const
Definition at line 632 of file BoundedString.hpp.
     {
         return reverse_iterator(range.begin() + length);
     }
rend()
template<class T > BoundedStringBase< T >::reverse_iterator infra::BoundedStringBase< T >::rend () const
Definition at line 644 of file BoundedString.hpp.
     {
         return reverse_iterator(range.begin());
     }
replace() [1/18]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const BoundedStringBase< U > & other)
replace() [2/18]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, const BoundedStringBase< U > & other)
replace() [3/18]
template<class T> template<class U > BoundedStringBase& infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const BoundedStringBase< U > & other, size_type pos2, size_type count2)
replace() [4/18]
template<class T> template<class InputIterator > BoundedStringBase& infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, InputIterator first2, InputIterator last2)
replace() [5/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const char * cstr, size_type count2)
Definition at line 966 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, cstr, count2);
         return *this;
     }
replace() [6/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, const char * cstr, size_type count2)
Definition at line 973 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + std::distance(cbegin(), first), std::distance(first, last), cstr, count2);
         return *this;
     }
replace() [7/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const char * cstr)
Definition at line 980 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, cstr, std::strlen(cstr));
         return *this;
     }
replace() [8/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, const char * cstr)
Definition at line 987 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + std::distance(cbegin(), first), std::distance(first, last), cstr, std::strlen(cstr));
         return *this;
     }
replace() [9/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const std::string & s, size_type count2)
Definition at line 994 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, s.data(), count2);
         return *this;
     }
replace() [10/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, const std::string & s, size_type count2)
Definition at line 1001 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + std::distance(cbegin(), first), std::distance(first, last), s.data(), count2);
         return *this;
     }
replace() [11/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const std::string & s)
Definition at line 1008 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, s.data(), s.size());
         return *this;
     }
replace() [12/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, const std::string & s)
Definition at line 1015 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + std::distance(cbegin(), first), std::distance(first, last), s.data(), s.size());
         return *this;
     }
replace() [13/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (size_type pos, size_type count, size_type count2, char ch)
Definition at line 1022 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, ch, count2);
         return *this;
     }
replace() [14/18]
template<class T > BoundedStringBase< T > & infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, size_type count2, char ch)
Definition at line 1029 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + std::distance(cbegin(), first), std::distance(first, last), ch, count2);
         return *this;
     }
replace() [15/18]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const BoundedStringBase< U > & other)
Definition at line 943 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, other.begin(), other.size());
         return *this;
     }
replace() [16/18]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, const BoundedStringBase< U > & other)
Definition at line 951 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + std::distance(cbegin(), first), std::distance(first, last), other.begin(), other.size());
         return *this;
     }
replace() [17/18]
template<class T> template<class U > BoundedStringBase<T>& infra::BoundedStringBase< T >::replace (size_type pos, size_type count, const BoundedStringBase< U > & other, size_type pos2, size_type count2)
Definition at line 959 of file BoundedString.hpp.
     {
         ReplaceImpl(begin() + pos, count, other.begin(), count2);
         return *this;
     }
replace() [18/18]
template<class T> template<class InputIterator > BoundedStringBase<T>& infra::BoundedStringBase< T >::replace (const_iterator first, const_iterator last, InputIterator first2, InputIterator last2)
Definition at line 1429 of file BoundedString.hpp.
     {
         size_type count = first - begin();
         difference_type count2 = std::distance(first2, last2);
         size_type replacementSize = count2 - std::max<difference_type>(length - count + count2 - max_size(), 0);
         ReplaceImpl(begin() + count, last - first, first2, replacementSize);
         return *this;
     }
ReplaceImpl() [1/2]
template<class T > void infra::BoundedStringBase< T >::ReplaceImpl (char * begin1, size_type count1, const char * begin2, size_type count2) private
Definition at line 1365 of file BoundedString.hpp.
     {
         assert(length - count1 + count2 <= max_size());
         std::memmove(begin1 + count2, begin1 + count1, length - count1 - (begin() - begin1));
         std::memmove(begin1, begin2, count2);
         length += count2 - count1;
     }
ReplaceImpl() [2/2]
template<class T > void infra::BoundedStringBase< T >::ReplaceImpl (char * begin1, size_type count1, char ch, size_type count2) private
Definition at line 1375 of file BoundedString.hpp.
     {
         assert(length - count1 + count2 <= max_size());
         std::memmove(begin1 + count2, begin1 + count1, length - count1 - (begin() - begin1));
         std::fill(begin1, begin1 + count2, ch);
         length += count2 - count1;
     }
resize() [1/2]
template<class T > void infra::BoundedStringBase< T >::resize (size_type count)
Definition at line 1060 of file BoundedString.hpp.
Referenced by services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpClientImpl::HttpResponseParser::ParseStatusLine(), and services::HttpServerConnectionObserver::ReceivedRequest().
     {
         resize(count, char());
     }
resize() [2/2]
template<class T > void infra::BoundedStringBase< T >::resize (size_type count, char ch)
Definition at line 1066 of file BoundedString.hpp.
     {
         assert(count <= max_size());
         if (count > length)
             std::fill(end(), begin() + count, ch);
         length = count;
     }
rfind() [1/4]
template<class T > template<class U > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::rfind (const BoundedStringBase< U > & other, size_type pos = npos) const
Definition at line 1132 of file BoundedString.hpp.
     {
         pos = std::min(pos, length);
         return rfind(other.begin(), pos, other.size());
     }
rfind() [2/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::rfind (const char * s, size_type pos, size_type count) const
Definition at line 1139 of file BoundedString.hpp.
     {
         pos = std::min(pos, length);
         for (const_iterator i = std::min(begin() + pos, end() - count); i >= begin(); --i)
             if (CompareImpl(i, i + count, s, s + count) == 0)
                 return i - begin();
         return npos;
     }
rfind() [3/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::rfind (const char * s, size_type pos = npos) const
Definition at line 1150 of file BoundedString.hpp.
     {
         return rfind(s, pos, std::strlen(s));
     }
rfind() [4/4]
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::rfind (char ch, size_type pos = npos) const
Definition at line 1156 of file BoundedString.hpp.
     {
         return rfind(&ch, pos, 1);
     }
shrink()
template<class T > void infra::BoundedStringBase< T >::shrink (size_type count)
Definition at line 1077 of file BoundedString.hpp.
     {
         if (count < length)
             length = count;
     }
size()
template<class T > BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::size () const
Definition at line 668 of file BoundedString.hpp.
Referenced by services::CertificatesMbedTls::AddCertificateAuthority(), services::CertificatesMbedTls::AddOwnCertificate(), infra::BoundedStringBase< char >::append(), infra::BoundedStringBase< char >::AssignToRange(), services::HttpRequestParserImpl::CheckContentsLength(), services::HttpServerConnectionObserver::DataReceived(), infra::BoundedStringBase< char >::find(), infra::BoundedStringBase< char >::find_first_not_of(), infra::BoundedStringBase< char >::find_first_of(), infra::BoundedStringBase< char >::find_last_not_of(), infra::BoundedStringBase< char >::find_last_of(), services::NameResolverCache::Hash(), services::HttpRequestFormatter::HttpRequestFormatter(), services::HttpStatusCodeFromString(), infra::BoundedStringBase< char >::insert(), infra::JsonEscapedStringSize(), infra::BoundedStringBase< char >::max_size(), services::MqttClientImpl::MqttFormatter::MessagePublish(), services::MqttClientImpl::MqttFormatter::MessageSizePublish(), services::TimeWithLocalization::OffsetFromTimeString(), infra::operator==(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpClientBasic::Path(), services::DnsResolver::ActiveLookup::QuerySize(), services::DnsResolver::ReplyParser::ReadAndMatchHostnamePart(), services::HttpServerConnectionObserver::ReceivedRequest(), infra::BoundedStringBase< char >::replace(), infra::BoundedStringBase< char >::rfind(), services::LlmnrResponder::SendStreamAvailable(), services::HttpRequestFormatter::Size(), services::HttpHeader::Size(), infra::JsonTokenizer::SkipWhitespace(), infra::BoundedStringBase< char >::swap(), infra::JsonTokenizer::Token(), infra::JsonTokenizer::TryCreateIdentifierToken(), infra::JsonTokenizer::TryCreateIntegerToken(), infra::JsonTokenizer::TryCreateStringToken(), and services::DnsResolver::ActiveLookup::WriteHostname().
     {
         return length;
     }
substr() [1/2]
template<class T > BoundedStringBase< T > infra::BoundedStringBase< T >::substr (size_type pos = 0, size_type count = npos)
Definition at line 1036 of file BoundedString.hpp.
Referenced by infra::JsonSubObjectParser::Feed(), services::HostFromUrl(), infra::Tokenizer::MakeToken(), services::TimeWithLocalization::OffsetFromTimeString(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpClientImpl::HttpResponseParser::ParseStatusLine(), services::PathFromUrl(), services::DnsResolver::ActiveLookup::QuerySize(), infra::JsonIterator::ReadArrayValue(), infra::JsonIterator::ReadObjectValue(), services::HttpServerConnectionObserver::ReceivedRequest(), services::SchemeFromUrl(), services::TracingConnectionMbedTls::TlsLog(), infra::JsonTokenizer::TryCreateIdentifierToken(), infra::JsonTokenizer::TryCreateIntegerToken(), infra::JsonTokenizer::TryCreateStringToken(), and services::DnsResolver::ActiveLookup::WriteHostname().
     {
         assert(pos <= length);
         count = std::min(count, length - pos);
         return BoundedStringBase<T>(begin() + pos, count);
     }
substr() [2/2]
template<class T > BoundedStringBase< const T > infra::BoundedStringBase< T >::substr (size_type pos = 0, size_type count = npos) const
Definition at line 1044 of file BoundedString.hpp.
     {
         assert(pos <= length);
         count = std::min(count, length - pos);
         return BoundedStringBase<const T>(begin() + pos, count);
     }
swap()
template<class T > void infra::BoundedStringBase< T >::swap (BoundedStringBase< T > & other)
Definition at line 1084 of file BoundedString.hpp.
Referenced by infra::swap().
     {
         using std::swap;
         for (size_type i = 0; i < size() && i < other.size(); ++i)
             swap(range[i], other.range[i]);
         for (size_type i = size(); i < other.size(); ++i)
             range[i] = other.range[i];
         for (size_type i = other.size(); i < size(); ++i)
             other.range[i] = range[i];
         std::swap(length, other.length);
     }
Friends And Related Function Documentation
BoundedStringBase
template<class T> template<class U > friend class BoundedStringBase friend
Definition at line 248 of file BoundedString.hpp.
Member Data Documentation
length
template<class T> size_type infra::BoundedStringBase< T >::length = 0 private
Definition at line 251 of file BoundedString.hpp.
Referenced by infra::BoundedStringBase< char >::AssignToRange(), infra::BoundedStringBase< char >::operator=(), and infra::BoundedStringBase< char >::swap().
npos
template<class T> const BoundedStringBase< T >::size_type infra::BoundedStringBase< T >::npos = std::numeric_limits<size_type>::max() static
Definition at line 43 of file BoundedString.hpp.
range
template<class T> MemoryRange<T> infra::BoundedStringBase< T >::range private
Definition at line 250 of file BoundedString.hpp.
Referenced by infra::BoundedStringBase< char >::AssignToRange(), infra::BoundedStringBase< char >::operator=(), and infra::BoundedStringBase< char >::swap().
The documentation for this class was generated from the following file:
BoundedString.hpp