EMil: infra::SystemStateParticipant Class Reference
infra::SystemStateParticipant Class Reference abstract
#include <SystemStateManager.hpp>
Public Member Functions
SystemStateParticipant (SystemStateManager &aSystemStateManager)
~SystemStateParticipant ()
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Protected Member Functions
virtual void RequestState (SystemStateBase state)=0
void ReachedState ()
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Private Attributes
SystemStateManager & systemStateManager
Friends
class SystemStateManager
Detailed Description
Definition at line 36 of file SystemStateManager.hpp.
Constructor & Destructor Documentation
SystemStateParticipant()
infra::SystemStateParticipant::SystemStateParticipant (SystemStateManager & aSystemStateManager) explicit
Definition at line 20 of file SystemStateManager.cpp.
References infra::SystemStateManager::AddParticipant(), and systemStateManager.
         : systemStateManager(aSystemStateManager)
     {
         systemStateManager.AddParticipant(*this);
     }
~SystemStateParticipant()
infra::SystemStateParticipant::~SystemStateParticipant ()
Definition at line 26 of file SystemStateManager.cpp.
References infra::SystemStateManager::RemoveParticipant(), and systemStateManager.
     {
         systemStateManager.RemoveParticipant(*this);
     }
Member Function Documentation
ReachedState()
void infra::SystemStateParticipant::ReachedState () protected
Definition at line 31 of file SystemStateManager.cpp.
References infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::SystemStateManager::ReachedState(), infra::EventDispatcherWorker::Schedule(), and systemStateManager.
     {
         infra::EventDispatcher::Instance().Schedule([this]() { systemStateManager.ReachedState(*this); });
     }
RequestState()
virtual void infra::SystemStateParticipant::RequestState (SystemStateBase state) protected pure virtual
Friends And Related Function Documentation
SystemStateManager
friend class SystemStateManager friend
Definition at line 44 of file SystemStateManager.hpp.
Member Data Documentation
systemStateManager
SystemStateManager& infra::SystemStateParticipant::systemStateManager private
Definition at line 50 of file SystemStateManager.hpp.
Referenced by ReachedState(), SystemStateParticipant(), and ~SystemStateParticipant().
The documentation for this class was generated from the following files:
SystemStateManager.hpp
SystemStateManager.cpp