EMil: hal::LowPowerSpiMaster Class Reference
hal::LowPowerSpiMaster Class Reference
#include <LowPowerSpiMaster.hpp>
Public Member Functions
LowPowerSpiMaster ()=delete
LowPowerSpiMaster (hal::SpiMaster &master, infra::MainClockReference &mainClockReference)
LowPowerSpiMaster (const LowPowerSpiMaster &other)=delete
LowPowerSpiMaster & operator= (const LowPowerSpiMaster &other)=delete
~LowPowerSpiMaster ()=default
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> &onDone) override
virtual void SetChipSelectConfigurator (ChipSelectConfigurator &configurator) override
virtual void SetCommunicationConfigurator (CommunicationConfigurator &configurator) override
virtual void ResetCommunicationConfigurator () override
Public Member Functions inherited from hal::SpiMaster
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
Private Attributes
infra::MainClockReference & mainClock
hal::SpiMaster & spiMaster
infra::AutoResetFunction< void()> onDone
Additional Inherited Members
Protected Member Functions inherited from hal::SpiMaster
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Detailed Description
Definition at line 10 of file LowPowerSpiMaster.hpp.
Constructor & Destructor Documentation
LowPowerSpiMaster() [1/3]
hal::LowPowerSpiMaster::LowPowerSpiMaster () delete
LowPowerSpiMaster() [2/3]
hal::LowPowerSpiMaster::LowPowerSpiMaster (hal::SpiMaster & master, infra::MainClockReference & mainClockReference)
Definition at line 5 of file LowPowerSpiMaster.cpp.
         : mainClock(mainClockReference)
         , spiMaster(master)
     {}
LowPowerSpiMaster() [3/3]
hal::LowPowerSpiMaster::LowPowerSpiMaster (const LowPowerSpiMaster & other) delete
~LowPowerSpiMaster()
hal::LowPowerSpiMaster::~LowPowerSpiMaster () default
Member Function Documentation
operator=()
LowPowerSpiMaster& hal::LowPowerSpiMaster::operator= (const LowPowerSpiMaster & other) delete
ResetCommunicationConfigurator()
void hal::LowPowerSpiMaster::ResetCommunicationConfigurator () override virtual
Implements hal::SpiMaster.
Definition at line 32 of file LowPowerSpiMaster.cpp.
References hal::SpiMaster::ResetCommunicationConfigurator(), and spiMaster.
     {
         spiMaster.ResetCommunicationConfigurator();
     }
SendAndReceive()
void hal::LowPowerSpiMaster::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> & onDone) override virtual
Implements hal::SpiMaster.
Definition at line 10 of file LowPowerSpiMaster.cpp.
References mainClock, onDone, infra::MainClockReference::Refere(), infra::MainClockReference::Release(), hal::SpiMaster::SendAndReceive(), and spiMaster.
     {
         mainClock.Refere();
         this->onDone = onDone;
         spiMaster.SendAndReceive(sendData, receiveData, nextAction, [this](){
             this->onDone();
             this->mainClock.Release();
         });
     }
SetChipSelectConfigurator()
void hal::LowPowerSpiMaster::SetChipSelectConfigurator (ChipSelectConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 22 of file LowPowerSpiMaster.cpp.
References hal::SpiMaster::SetChipSelectConfigurator(), and spiMaster.
     {
         spiMaster.SetChipSelectConfigurator(configurator);
     }
SetCommunicationConfigurator()
void hal::LowPowerSpiMaster::SetCommunicationConfigurator (CommunicationConfigurator & configurator) override virtual
Implements hal::SpiMaster.
Definition at line 27 of file LowPowerSpiMaster.cpp.
References hal::SpiMaster::SetCommunicationConfigurator(), and spiMaster.
     {
         spiMaster.SetCommunicationConfigurator(configurator);
     }
Member Data Documentation
mainClock
infra::MainClockReference& hal::LowPowerSpiMaster::mainClock private
Definition at line 28 of file LowPowerSpiMaster.hpp.
Referenced by SendAndReceive().
onDone
infra::AutoResetFunction<void()> hal::LowPowerSpiMaster::onDone private
Definition at line 30 of file LowPowerSpiMaster.hpp.
Referenced by SendAndReceive().
spiMaster
hal::SpiMaster& hal::LowPowerSpiMaster::spiMaster private
Definition at line 29 of file LowPowerSpiMaster.hpp.
Referenced by ResetCommunicationConfigurator(), SendAndReceive(), SetChipSelectConfigurator(), and SetCommunicationConfigurator().
The documentation for this class was generated from the following files:
LowPowerSpiMaster.hpp
LowPowerSpiMaster.cpp