EMil: services::ConnectionFactoryWithNameResolverForTls Class Reference
services::ConnectionFactoryWithNameResolverForTls Class Reference
#include <ConnectionMbedTls.hpp>
Public Member Functions
ConnectionFactoryWithNameResolverForTls (ConnectionFactoryWithNameResolver &connectionFactoryWithNameResolver)
virtual void Connect (ClientConnectionObserverFactoryWithNameResolver &factory) override
virtual void CancelConnect (ClientConnectionObserverFactoryWithNameResolver &factory) override
virtual infra::BoundedConstString Hostname () const override
virtual uint16_t Port () const override
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver) override
virtual void ConnectionFailed (ConnectFailReason reason) override
Public Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
Private Attributes
ConnectionFactoryWithNameResolver & connectionFactoryWithNameResolver
ClientConnectionObserverFactoryWithNameResolver * clientConnectionFactory = nullptr
Additional Inherited Members
Public Types inherited from services::ClientConnectionObserverFactoryWithNameResolver
enum ConnectFailReason { refused, connectionAllocationFailed, nameLookupFailed }
Protected Member Functions inherited from services::ConnectionFactoryWithNameResolver
ConnectionFactoryWithNameResolver ()=default
ConnectionFactoryWithNameResolver (const ConnectionFactoryWithNameResolver &other)=delete
ConnectionFactoryWithNameResolver & operator= (const ConnectionFactoryWithNameResolver &other)=delete
~ConnectionFactoryWithNameResolver ()=default
Protected Member Functions inherited from services::ClientConnectionObserverFactoryWithNameResolver
ClientConnectionObserverFactoryWithNameResolver ()=default
ClientConnectionObserverFactoryWithNameResolver (const ClientConnectionObserverFactoryWithNameResolver &other)=delete
ClientConnectionObserverFactoryWithNameResolver & operator= (const ClientConnectionObserverFactoryWithNameResolver &other)=delete
~ClientConnectionObserverFactoryWithNameResolver ()=default
Protected Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 227 of file ConnectionMbedTls.hpp.
Constructor & Destructor Documentation
ConnectionFactoryWithNameResolverForTls()
services::ConnectionFactoryWithNameResolverForTls::ConnectionFactoryWithNameResolverForTls (ConnectionFactoryWithNameResolver & connectionFactoryWithNameResolver)
Definition at line 532 of file ConnectionMbedTls.cpp.
         : connectionFactoryWithNameResolver(connectionFactoryWithNameResolver)
     {}
Member Function Documentation
CancelConnect()
void services::ConnectionFactoryWithNameResolverForTls::CancelConnect (ClientConnectionObserverFactoryWithNameResolver & factory) override virtual
Implements services::ConnectionFactoryWithNameResolver.
Definition at line 542 of file ConnectionMbedTls.cpp.
References services::ConnectionFactoryWithNameResolver::CancelConnect(), clientConnectionFactory, and connectionFactoryWithNameResolver.
     {
         clientConnectionFactory = &factory;
         connectionFactoryWithNameResolver.CancelConnect(*this);
     }
Connect()
void services::ConnectionFactoryWithNameResolverForTls::Connect (ClientConnectionObserverFactoryWithNameResolver & factory) override virtual
Implements services::ConnectionFactoryWithNameResolver.
Definition at line 536 of file ConnectionMbedTls.cpp.
References clientConnectionFactory, services::ConnectionFactoryWithNameResolver::Connect(), and connectionFactoryWithNameResolver.
     {
         clientConnectionFactory = &factory;
         connectionFactoryWithNameResolver.Connect(*this);
     }
ConnectionEstablished()
void services::ConnectionFactoryWithNameResolverForTls::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver) override virtual
Implements services::ClientConnectionObserverFactoryWithNameResolver.
Definition at line 560 of file ConnectionMbedTls.cpp.
References clientConnectionFactory, services::ClientConnectionObserverFactoryWithNameResolver::ConnectionEstablished(), Hostname(), and infra::SingleObserver< Descendant, SubjectType_ >::Subject().
     {
         assert(clientConnectionFactory != nullptr);
         clientConnectionFactory->ConnectionEstablished([this, &createdObserver](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             createdObserver(connectionObserver);
             static_cast<ConnectionMbedTls&>(connectionObserver->Subject()).SetHostname(Hostname());
         });
     }
ConnectionFailed()
void services::ConnectionFactoryWithNameResolverForTls::ConnectionFailed (ConnectFailReason reason) override virtual
Implements services::ClientConnectionObserverFactoryWithNameResolver.
Definition at line 570 of file ConnectionMbedTls.cpp.
References clientConnectionFactory, and services::ClientConnectionObserverFactoryWithNameResolver::ConnectionFailed().
     {
         assert(clientConnectionFactory != nullptr);
         return clientConnectionFactory->ConnectionFailed(reason);
     }
Hostname()
infra::BoundedConstString services::ConnectionFactoryWithNameResolverForTls::Hostname () const override virtual
Implements services::ClientConnectionObserverFactoryWithNameResolver.
Definition at line 548 of file ConnectionMbedTls.cpp.
References clientConnectionFactory, and services::ClientConnectionObserverFactoryWithNameResolver::Hostname().
Referenced by ConnectionEstablished().
     {
         assert(clientConnectionFactory != nullptr);
         return clientConnectionFactory->Hostname();
     }
Port()
uint16_t services::ConnectionFactoryWithNameResolverForTls::Port () const override virtual
Implements services::ClientConnectionObserverFactoryWithNameResolver.
Definition at line 554 of file ConnectionMbedTls.cpp.
References clientConnectionFactory, and services::ClientConnectionObserverFactoryWithNameResolver::Port().
     {
         assert(clientConnectionFactory != nullptr);
         return clientConnectionFactory->Port();
     }
Member Data Documentation
clientConnectionFactory
ClientConnectionObserverFactoryWithNameResolver* services::ConnectionFactoryWithNameResolverForTls::clientConnectionFactory = nullptr private
Definition at line 247 of file ConnectionMbedTls.hpp.
Referenced by CancelConnect(), Connect(), ConnectionEstablished(), ConnectionFailed(), Hostname(), and Port().
connectionFactoryWithNameResolver
ConnectionFactoryWithNameResolver& services::ConnectionFactoryWithNameResolverForTls::connectionFactoryWithNameResolver private
Definition at line 246 of file ConnectionMbedTls.hpp.
Referenced by CancelConnect(), and Connect().
The documentation for this class was generated from the following files:
ConnectionMbedTls.hpp
ConnectionMbedTls.cpp