EMil: TestIntrusiveSet.cpp File Reference
TestIntrusiveSet.cpp File Reference
Classes
class IntrusiveSetTest
Functions
TEST_F (IntrusiveSetTest, TestConstructedEmpty)
TEST_F (IntrusiveSetTest, TestConstructionWithRange)
TEST_F (IntrusiveSetTest, TestMoveConstruction)
TEST_F (IntrusiveSetTest, TestMoveAssignment)
TEST_F (IntrusiveSetTest, IterateAfterMoveAssignment)
TEST_F (IntrusiveSetTest, TestBeginAndEnd)
TEST_F (IntrusiveSetTest, TestFront)
TEST_F (IntrusiveSetTest, TestBack)
TEST_F (IntrusiveSetTest, TestNotHasElement)
TEST_F (IntrusiveSetTest, TestHasElement)
TEST_F (IntrusiveSetTest, TestNotHasElementForSameValue)
TEST_F (IntrusiveSetTest, TestAssignRange)
TEST_F (IntrusiveSetTest, TestAssignN)
TEST_F (IntrusiveSetTest, TestSwap)
TEST_F (IntrusiveSetTest, TestSwapDifferentSizes)
TEST_F (IntrusiveSetTest, TestClear)
TEST_F (IntrusiveSetTest, TestInsert)
TEST_F (IntrusiveSetTest, TestEraseSingleNode)
TEST_F (IntrusiveSetTest, TestEraseBlackWithRedReplacement)
TEST_F (IntrusiveSetTest, TestEraseBlackNonRootWithRedReplacement)
TEST_F (IntrusiveSetTest, TestEraseRedWithLeafReplacement)
TEST_F (IntrusiveSetTest, TestEraseRedWithBlackReplacement)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32ai)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32aiAndMoreRecolouring)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32aii)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32aiii)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32aiv)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32aivAndRecolouring)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32ciAnd32b)
TEST_F (IntrusiveSetTest, TestEraseBlackResultingIn32ciiAnd32b)
TEST_F (IntrusiveSetTest, TestEraseRootWithBlackLeavesAndRedGrandLeave)
TEST_F (IntrusiveSetTest, TestEraseFollowedByRecolouringLeaf)
TEST_F (IntrusiveSetTest, TestManyInsertionsAndDeletions)
TEST_F (IntrusiveSetTest, TestEquals)
TEST_F (IntrusiveSetTest, TestUnequals)
TEST_F (IntrusiveSetTest, TestLessThan)
TEST_F (IntrusiveSetTest, TestGreaterThan)
TEST_F (IntrusiveSetTest, TestLessThanOrEqual)
TEST_F (IntrusiveSetTest, TestGreaterThanOrEqual)
Function Documentation
TEST_F() [1/39]
TEST_F (IntrusiveSetTest , TestConstructedEmpty)
Definition at line 67 of file TestIntrusiveSet.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     infra::IntrusiveSet<SetInt> set;
     EXPECT_TRUE(set.empty());
     EXPECT_EQ(0, set.size());
     EXPECT_TRUE(set.invariant_holds());
 }
TEST_F() [2/39]
TEST_F (IntrusiveSetTest , TestConstructionWithRange)
Definition at line 76 of file TestIntrusiveSet.cpp.
References infra::detail::begin(), EXPECT_EQ(), and EXPECT_TRUE().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     EXPECT_EQ(3, set.size());
     EXPECT_EQ(SetInt(0), *set.begin());
     EXPECT_EQ(SetInt(1), *std::next(set.begin()));
     EXPECT_EQ(SetInt(2), *std::next(set.begin(), 2));
     EXPECT_TRUE(set.invariant_holds());
 }
TEST_F() [3/39]
TEST_F (IntrusiveSetTest , TestMoveConstruction)
Definition at line 89 of file TestIntrusiveSet.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::back(), infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::front(), infra::IntrusiveSet< T, Compare >::invariant_holds(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> original(range, range + 3);
     infra::IntrusiveSet<SetInt> copy(std::move(original));
     EXPECT_EQ(3, copy.size());
     EXPECT_EQ(SetInt(0), copy.front());
     EXPECT_EQ(SetInt(2), copy.back());
     EXPECT_TRUE(original.empty());
     EXPECT_TRUE(copy.invariant_holds());
 }
TEST_F() [4/39]
TEST_F (IntrusiveSetTest , TestMoveAssignment)
Definition at line 102 of file TestIntrusiveSet.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::back(), infra::IntrusiveBinarySearchTree< T, Compare >::empty(), EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::front(), infra::IntrusiveSet< T, Compare >::invariant_holds(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> original(range, range + 3);
     infra::IntrusiveSet<SetInt> copy;
     copy = std::move(original);
     EXPECT_EQ(3, copy.size());
     EXPECT_EQ(SetInt(0), copy.front());
     EXPECT_EQ(SetInt(2), copy.back());
     EXPECT_TRUE(original.empty());
     EXPECT_TRUE(copy.invariant_holds());
 }
TEST_F() [5/39]
TEST_F (IntrusiveSetTest , IterateAfterMoveAssignment)
Definition at line 116 of file TestIntrusiveSet.cpp.
References infra::MakeReverseRange().
 {
     SetInt range[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> original(range, range + 3);
     infra::IntrusiveSet<SetInt> copy;
     copy = std::move(original);
     for (SetInt& i: copy)
     {}
     for (SetInt& i: MakeReverseRange(copy))
     {}
 }
TEST_F() [6/39]
TEST_F (IntrusiveSetTest , TestBeginAndEnd)
Definition at line 130 of file TestIntrusiveSet.cpp.
References infra::detail::begin(), infra::detail::end(), and EXPECT_EQ().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     EXPECT_EQ(set.end(), std::next(set.begin(), 3));
     EXPECT_EQ(set.cbegin(), set.begin());
     EXPECT_EQ(set.cend(), set.end());
     EXPECT_EQ(SetInt(0), *set.begin());
 }
TEST_F() [7/39]
TEST_F (IntrusiveSetTest , TestFront)
Definition at line 142 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     EXPECT_EQ(SetInt(0), set.front());
 }
TEST_F() [8/39]
TEST_F (IntrusiveSetTest , TestBack)
Definition at line 150 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     EXPECT_EQ(SetInt(2), set.back());
 }
TEST_F() [9/39]
TEST_F (IntrusiveSetTest , TestNotHasElement)
Definition at line 158 of file TestIntrusiveSet.cpp.
References EXPECT_FALSE().
 {
     infra::IntrusiveSet<SetInt> set;
     SetInt x(3);
     EXPECT_FALSE(set.has_element(x));
 }
TEST_F() [10/39]
TEST_F (IntrusiveSetTest , TestHasElement)
Definition at line 166 of file TestIntrusiveSet.cpp.
References EXPECT_TRUE().
 {
     infra::IntrusiveSet<SetInt> set;
     SetInt x(3);
     set.insert(x);
     EXPECT_TRUE(set.has_element(x));
 }
TEST_F() [11/39]
TEST_F (IntrusiveSetTest , TestNotHasElementForSameValue)
Definition at line 175 of file TestIntrusiveSet.cpp.
References EXPECT_FALSE().
 {
     infra::IntrusiveSet<SetInt> set;
     SetInt x(3);
     SetInt y(3);
     set.insert(x);
     EXPECT_FALSE(set.has_element(y));
 }
TEST_F() [12/39]
TEST_F (IntrusiveSetTest , TestAssignRange)
Definition at line 185 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::assign(), infra::detail::begin(), EXPECT_EQ(), and EXPECT_TRUE().
 {
     SetInt range[3] = { 0, 1, 2};
     SetInt otherRange[2] = { 4, 5 };
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     set.assign(otherRange, otherRange + 2);
     EXPECT_EQ(2, set.size());
     EXPECT_EQ(SetInt(4), set.front());
     EXPECT_EQ(SetInt(5), *std::next(set.begin()));
     EXPECT_TRUE(set.invariant_holds());
 }
TEST_F() [13/39]
TEST_F (IntrusiveSetTest , TestAssignN)
Definition at line 199 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::assign(), EXPECT_EQ(), and EXPECT_TRUE().
 {
     SetInt range[3] = { 0, 1, 2 };
     SetInt range2[2] = { 3, 4 };
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     set.assign(range2, range2 + 2);
     EXPECT_EQ(2, set.size());
     EXPECT_EQ(SetInt(3), set.front());
     EXPECT_EQ(SetInt(4), set.back());
     EXPECT_TRUE(set.invariant_holds());
 }
TEST_F() [14/39]
TEST_F (IntrusiveSetTest , TestSwap)
Definition at line 213 of file TestIntrusiveSet.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveSet< T, Compare >::invariant_holds(), and infra::swap().
 {
     SetInt range1[3] = { 0, 1, 2};
     SetInt range2[3] = { 3, 4, 5 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     infra::IntrusiveSet<SetInt> set2(range2, range2 + 3);
     swap(set1, set2);
     SetInt expectedRange1[3] = { 0, 1, 2 };
     SetInt expectedRange2[3] = { 3, 4, 5 };
     infra::IntrusiveSet<SetInt> expectedSet1(expectedRange2, expectedRange2 + 3);
     infra::IntrusiveSet<SetInt> expectedSet2(expectedRange1, expectedRange1 + 3);
     EXPECT_EQ(expectedSet1, set1);
     EXPECT_EQ(expectedSet2, set2);
     EXPECT_TRUE(set1.invariant_holds());
     EXPECT_TRUE(set2.invariant_holds());
 }
TEST_F() [15/39]
TEST_F (IntrusiveSetTest , TestSwapDifferentSizes)
Definition at line 232 of file TestIntrusiveSet.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveSet< T, Compare >::invariant_holds(), and infra::swap().
 {
     SetInt range1[3] = { 0, 1, 2};
     SetInt range2[2] = { 3, 4 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     infra::IntrusiveSet<SetInt> set2(range2, range2 + 2);
     swap(set1, set2);
     SetInt expectedRange1[3] = { 0, 1, 2 };
     SetInt expectedRange2[2] = { 3, 4 };
     infra::IntrusiveSet<SetInt> expectedSet1(expectedRange2, expectedRange2 + 2);
     infra::IntrusiveSet<SetInt> expectedSet2(expectedRange1, expectedRange1 + 3);
     EXPECT_EQ(expectedSet1, set1);
     EXPECT_EQ(expectedSet2, set2);
     EXPECT_TRUE(set1.invariant_holds());
     EXPECT_TRUE(set2.invariant_holds());
 }
TEST_F() [16/39]
TEST_F (IntrusiveSetTest , TestClear)
Definition at line 251 of file TestIntrusiveSet.cpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::clear(), EXPECT_EQ(), and EXPECT_TRUE().
 {
     SetInt range[3] = { 0, 1, 2};
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     set.clear();
     EXPECT_EQ(0, set.size());
     EXPECT_TRUE(set.empty());
     infra::IntrusiveSet<SetInt> expectedSet;
     EXPECT_EQ(expectedSet, set);
     EXPECT_TRUE(set.invariant_holds());
 }
TEST_F() [17/39]
TEST_F (IntrusiveSetTest , TestInsert)
Definition at line 265 of file TestIntrusiveSet.cpp.
References EXPECT_EQ(), EXPECT_TRUE(), and infra::IntrusiveSet< T, Compare >::insert().
 {
     SetInt range[3] = { 0, 1, 2 };
     SetInt i1(3);
     infra::IntrusiveSet<SetInt> set(range, range + 3);
     set.insert(i1);
     EXPECT_EQ(4, set.size());
     EXPECT_EQ(i1, set.back());
     EXPECT_TRUE(set.invariant_holds());
 }
TEST_F() [18/39]
TEST_F (IntrusiveSetTest , TestEraseSingleNode)
Definition at line 277 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 1> range = { 1 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b1", Representation(set));
     set.erase(range[0]);
     EXPECT_EQ("", Representation(set));
 }
TEST_F() [19/39]
TEST_F (IntrusiveSetTest , TestEraseBlackWithRedReplacement)
Definition at line 287 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 2> range = { 2, 1 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b2(r1,)", Representation(set));
     set.erase(range[0]);
     EXPECT_EQ("b1", Representation(set));
 }
TEST_F() [20/39]
TEST_F (IntrusiveSetTest , TestEraseBlackNonRootWithRedReplacement)
Definition at line 297 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     SetInt range[4] = { 4, 3, 2, 1 };
     infra::IntrusiveSet<SetInt> set(range, range + 4);
     ASSERT_EQ("b3(b2(r1,),b4)", Representation(set));
     set.erase(range[2]);
     EXPECT_EQ("b3(b1,b4)", Representation(set));
 }
TEST_F() [21/39]
TEST_F (IntrusiveSetTest , TestEraseRedWithLeafReplacement)
Definition at line 307 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 2> range = { 2, 1 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b2(r1,)", Representation(set));
     set.erase(range[1]);
     EXPECT_EQ("b2", Representation(set));
 }
TEST_F() [22/39]
TEST_F (IntrusiveSetTest , TestEraseRedWithBlackReplacement)
Definition at line 317 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::erase(), and EXPECT_EQ().
 {
     std::array<SetInt, 6> range = { 3, 2, 1, 4, 5, 6 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     set.erase(range[5]);
     ASSERT_EQ("b2(b1,r4(b3,b5))", Representation(set));
     set.erase(range[3]);
     EXPECT_EQ("b2(b1,b5(r3,))", Representation(set));
 }
TEST_F() [23/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32ai)
Definition at line 328 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 5> range = { 4, 2, 5, 1, 3 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b4(b2(r1,r3),b5)", Representation(set));
     set.erase(range[2]);
     EXPECT_EQ("b2(b1,b4(r3,))", Representation(set));
 }
TEST_F() [24/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32aiAndMoreRecolouring)
Definition at line 338 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 7> range = { 5, 4, 6, 1, 0, 3, 2 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b5(r1(b0,b3(r2,r4)),b6)", Representation(set));
     set.erase(range[0]);
     EXPECT_EQ("b1(b0,r3(b2,b6(r4,)))", Representation(set));
 }
TEST_F() [25/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32aii)
Definition at line 348 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 4> range = { 3, 1, 4, 2 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b3(b1(,r2),b4)", Representation(set));
     set.erase(range[2]);
     EXPECT_EQ("b2(b1,b3)", Representation(set));
 }
TEST_F() [26/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32aiii)
Definition at line 358 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 4> range = { 3, 2, 4, 5 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b3(b2,b4(,r5))", Representation(set));
     set.erase(range[1]);
     EXPECT_EQ("b4(b3,b5)", Representation(set));
 }
TEST_F() [27/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32aiv)
Definition at line 368 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 5> range = { 3, 2, 5, 6, 4 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b3(b2,b5(r4,r6))", Representation(set));
     set.erase(range[1]);
     EXPECT_EQ("b4(b3,b5(,r6))", Representation(set));
 }
TEST_F() [28/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32aivAndRecolouring)
Definition at line 378 of file TestIntrusiveSet.cpp.
References EXPECT_EQ().
 {
     std::array<SetInt, 9> range = { 4, 0, 6, 3, 2, 5, 8, 1, 7 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     ASSERT_EQ("b4(r2(b0(,r1),b3),r6(b5,b8(r7,)))", Representation(set));
     set.erase(range[0]);
     EXPECT_EQ("b5(r2(b0(,r1),b3),r7(b6,b8))", Representation(set));
 }
TEST_F() [29/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32ciAnd32b)
Definition at line 388 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::erase(), and EXPECT_EQ().
 {
     std::array<SetInt, 6> range = { 4, 2, 5, 1, 3, 0 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     set.erase(range[5]);
     ASSERT_EQ("b4(r2(b1,b3),b5)", Representation(set));
     set.erase(range[2]);
     EXPECT_EQ("b2(b1,b4(r3,))", Representation(set));
 }
TEST_F() [30/39]
TEST_F (IntrusiveSetTest , TestEraseBlackResultingIn32ciiAnd32b)
Definition at line 399 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::erase(), and EXPECT_EQ().
 {
     std::array<SetInt, 12> range = { 10, 2, 13, 1, 4, 12, 15, 3, 5, 11, 16, 6 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     set.erase(range[11]);
     ASSERT_EQ("b10(b2(b1,r4(b3,b5)),b13(b12(r11,),b15(,r16)))", Representation(set));
     set.erase(range[1]);
     EXPECT_EQ("b10(b3(b1,b4(,r5)),b13(b12(r11,),b15(,r16)))", Representation(set));
 }
TEST_F() [31/39]
TEST_F (IntrusiveSetTest , TestEraseRootWithBlackLeavesAndRedGrandLeave)
Definition at line 410 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::erase(), and EXPECT_EQ().
 {
     std::array<SetInt, 5> range = { 0, 2, 1, 4, 3 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     set.erase(range[0]);
     ASSERT_EQ("b2(b1,b3(,r4))", Representation(set));
     set.erase(range[1]);
     EXPECT_EQ("b3(r1,r4)", Representation(set));
 }
TEST_F() [32/39]
TEST_F (IntrusiveSetTest , TestEraseFollowedByRecolouringLeaf)
Definition at line 421 of file TestIntrusiveSet.cpp.
References infra::IntrusiveSet< T, Compare >::erase(), and EXPECT_EQ().
 {
     std::array<SetInt, 12> range = { 5, 11, 6, 1, 9, 7, 4, 8, 0, 10, 3, 2 };
     infra::IntrusiveSet<SetInt> set(range.begin(), range.end());
     set.erase(range[0]);
     set.erase(range[1]);
     set.erase(range[2]);
     ASSERT_EQ("b7(b1(b0,r3(b2,b4)),b9(b8,b10))", Representation(set));
     set.erase(range[3]);
     EXPECT_EQ("b7(b2(b0,b3(,r4)),b9(b8,b10))", Representation(set));
 }
TEST_F() [33/39]
TEST_F (IntrusiveSetTest , TestManyInsertionsAndDeletions)
Definition at line 434 of file TestIntrusiveSet.cpp.
References infra::detail::begin(), EXPECT_TRUE(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
 {
     for (int size = 2; size != 40; ++size)
     {
         for (int step = 3; step != 7; ++step)
         {
             std::vector<SetInt> elements;
             int n = 0;
             std::generate_n(std::back_inserter(elements), size, [&n]() { return n++; });
             std::vector<std::size_t> indices;
             n = 0;
             std::generate_n(std::back_inserter(indices), size, [&n]() { return n++; });
             infra::IntrusiveSet<SetInt> set;
             int current = 0;
             while (!indices.empty())
             {
                 current = (current + step) % indices.size();
                 //std::cout << "insert size: " << size << ", step: " << step << ", set size: " << set.size() << ", insert: " << indices[current] << std::endl;
                 set.insert(elements[indices[current]]);
                 EXPECT_TRUE(set.invariant_holds());
                 indices.erase(indices.begin() + current);
             }
             while (!set.empty())
             {
                 current = (current + 2 * step) % set.size();
                 //std::cout << "erase size: " << size << ", step: " << step << ", set size: " << set.size() << ", erase: " << std::next(set.begin(), current)->value << std::endl;
                 set.erase(*std::next(set.begin(), current));
                 EXPECT_TRUE(set.invariant_holds());
             }
         }
     }
 }
TEST_F() [34/39]
TEST_F (IntrusiveSetTest , TestEquals)
Definition at line 469 of file TestIntrusiveSet.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     SetInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     SetInt range2[3] = { 3, 4, 5 };
     infra::IntrusiveSet<SetInt> set2(range2, range2 + 3);
     SetInt range3[2] = { 0, 1 };
     infra::IntrusiveSet<SetInt> deque3(range3, range3 + 2);
     EXPECT_TRUE(set1 == set1);
     EXPECT_FALSE(set1 == set2);
     EXPECT_FALSE(set1 == deque3);
     EXPECT_FALSE(deque3 == set1);
 }
TEST_F() [35/39]
TEST_F (IntrusiveSetTest , TestUnequals)
Definition at line 484 of file TestIntrusiveSet.cpp.
References EXPECT_FALSE().
 {
     SetInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     EXPECT_FALSE(set1 != set1);
 }
TEST_F() [36/39]
TEST_F (IntrusiveSetTest , TestLessThan)
Definition at line 492 of file TestIntrusiveSet.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     SetInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     SetInt range2[3] = { 0, 4, 5 };
     infra::IntrusiveSet<SetInt> set2(range2, range2 + 3);
     SetInt range3[2] = { 0, 1 };
     infra::IntrusiveSet<SetInt> deque3(range3, range3 + 2);
     EXPECT_TRUE(set1 < set2);
     EXPECT_FALSE(set1 < deque3);
     EXPECT_FALSE(set1 < set1);
 }
TEST_F() [37/39]
TEST_F (IntrusiveSetTest , TestGreaterThan)
Definition at line 506 of file TestIntrusiveSet.cpp.
References EXPECT_FALSE().
 {
     SetInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     EXPECT_FALSE(set1 > set1);
 }
TEST_F() [38/39]
TEST_F (IntrusiveSetTest , TestLessThanOrEqual)
Definition at line 514 of file TestIntrusiveSet.cpp.
References EXPECT_TRUE().
 {
     SetInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     EXPECT_TRUE(set1 <= set1);
 }
TEST_F() [39/39]
TEST_F (IntrusiveSetTest , TestGreaterThanOrEqual)
Definition at line 522 of file TestIntrusiveSet.cpp.
References EXPECT_TRUE().
 {
     SetInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveSet<SetInt> set1(range1, range1 + 3);
     EXPECT_TRUE(set1 >= set1);
 }