EMil: TestOutputStreamSwitch.cpp File Reference
TestOutputStreamSwitch.cpp File Reference
Functions
TEST (OutputStreamSwitchTest, StreamToTextStream)
TEST (OutputStreamSwitchTest, TextStreamToStream)
TEST (OutputStreamSwitchTest, StreamToTextStreamToStream)
TEST (OutputStreamSwitchTest, StreamFromBoundedString)
Function Documentation
TEST() [1/4]
TEST (OutputStreamSwitchTest , StreamToTextStream)
Definition at line 7 of file TestOutputStreamSwitch.cpp.
References EXPECT_EQ(), and infra::text.
 {
     infra::ByteOutputStream::WithStorage<2> stream;
     stream << infra::text << uint8_t(12);
     EXPECT_EQ((std::array<uint8_t, 2>{{ '1', '2' }}), stream.Writer().Processed());
 }
TEST() [2/4]
TEST (OutputStreamSwitchTest , TextStreamToStream)
Definition at line 15 of file TestOutputStreamSwitch.cpp.
References infra::data, EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<2> stream;
     stream << infra::data << uint8_t(012);
     EXPECT_EQ("\012", stream.Storage());
 }
TEST() [3/4]
TEST (OutputStreamSwitchTest , StreamToTextStreamToStream)
Definition at line 23 of file TestOutputStreamSwitch.cpp.
References infra::data, EXPECT_EQ(), and infra::text.
 {
     infra::ByteOutputStream::WithStorage<3> stream;
     stream << infra::text << uint8_t(12) << infra::data << uint8_t(12);
     EXPECT_EQ((std::array<uint8_t, 3>{{ '1', '2', 12 }}), stream.Writer().Processed());
 }
TEST() [4/4]
TEST (OutputStreamSwitchTest , StreamFromBoundedString)
Definition at line 31 of file TestOutputStreamSwitch.cpp.
References infra::data, and EXPECT_EQ().
 {
     infra::BoundedString::WithStorage<10> s = "abcd";
     infra::StringOutputStream stream(s);
     stream << uint8_t(12) << infra::data << uint8_t('a');
     EXPECT_EQ("abcd12a", s);
 }