EMil: services::TimeWithLocalization Class Reference
services::TimeWithLocalization Class Reference
#include <TimeWithLocalization.hpp>
Public Member Functions
TimeWithLocalization (uint32_t systemTimerServiceId=infra::systemTimerServiceId, uint32_t utcTimerServiceId=1, uint32_t localTimeWithoutDaylightSavingTimerServiceId=2, uint32_t localTimeTimerServiceId=3)
infra::DerivedTimerService & Utc ()
infra::DerivedTimerService & LocalWithoutDaylightSaving ()
infra::DerivedTimerService & Local ()
infra::Duration GetOffsetFromLocalToUtc () const
infra::Duration GetOffsetTimezone () const
infra::Duration GetOffsetDaylightSaving () const
Static Public Member Functions
static infra::Optional< infra::TimePoint > TimePointFromString (infra::BoundedConstString timePointString)
static infra::Optional< infra::Duration > DurationFromString (infra::BoundedConstString durationString)
static infra::Optional< infra::BoundedConstString > OffsetFromTimeString (infra::BoundedConstString timePointString)
static uint8_t TimePointToCalenderDay (infra::TimePoint timePoint)
static void TimePointToHourMinSec (infra::TimePoint timePoint, uint8_t &hours, uint8_t &min, uint8_t &sec)
static tm * GetTm (infra::TimePoint timePoint)
Static Public Attributes
static const std::size_t DateTimeSize = 19
static const std::size_t TimeOffsetSize = 6
Private Attributes
infra::DerivedTimerService utcTimerService
infra::DerivedTimerService localTimeWithoutDaylightSavingTimerService
infra::DerivedTimerService localTimeTimerService
Detailed Description
Definition at line 10 of file TimeWithLocalization.hpp.
Constructor & Destructor Documentation
TimeWithLocalization()
services::TimeWithLocalization::TimeWithLocalization (uint32_t systemTimerServiceId = infra::systemTimerServiceId, uint32_t utcTimerServiceId = 1, uint32_t localTimeWithoutDaylightSavingTimerServiceId = 2, uint32_t localTimeTimerServiceId = 3) explicit
Definition at line 10 of file TimeWithLocalization.cpp.
         : utcTimerService(utcTimerServiceId, infra::TimerServiceManager::Instance().GetTimerService(systemTimerServiceId))
         , localTimeWithoutDaylightSavingTimerService(localTimeWithoutDaylightSavingTimerServiceId, utcTimerService)
         , localTimeTimerService(localTimeTimerServiceId, localTimeWithoutDaylightSavingTimerService)
     {}
Member Function Documentation
DurationFromString()
infra::Optional< infra::Duration > services::TimeWithLocalization::DurationFromString (infra::BoundedConstString durationString) static
Definition at line 81 of file TimeWithLocalization.cpp.
References infra::InputStream::Failed(), infra::inPlace, infra::none, and infra::softFail.
     {
         char sign = {};
         char colon = {};
         int8_t hour = 0;
         int8_t minute = 0;
         infra::StringInputStream stream(durationString, infra::softFail);
         stream >> sign >> hour >> colon >> minute;
         if (stream.Failed() ||
             colon != ':' ||
             (sign != '-' && sign != '+'))
             return infra::none;
         if (sign == '-')
         {
             hour = -hour;
             minute = -minute;
         }
         return infra::Optional<infra::Duration>(infra::inPlace, std::chrono::hours(hour) + std::chrono::minutes(minute));
     }
GetOffsetDaylightSaving()
infra::Duration services::TimeWithLocalization::GetOffsetDaylightSaving () const
Definition at line 135 of file TimeWithLocalization.cpp.
References infra::DerivedTimerService::GetCurrentShift(), and localTimeTimerService.
     {
         return localTimeTimerService.GetCurrentShift();
     }
GetOffsetFromLocalToUtc()
infra::Duration services::TimeWithLocalization::GetOffsetFromLocalToUtc () const
Definition at line 130 of file TimeWithLocalization.cpp.
References infra::DerivedTimerService::GetCurrentShift(), localTimeTimerService, and localTimeWithoutDaylightSavingTimerService.
     {
         return localTimeWithoutDaylightSavingTimerService.GetCurrentShift() + localTimeTimerService.GetCurrentShift();
     }
GetOffsetTimezone()
infra::Duration services::TimeWithLocalization::GetOffsetTimezone () const
Definition at line 140 of file TimeWithLocalization.cpp.
References infra::DerivedTimerService::GetCurrentShift(), and localTimeWithoutDaylightSavingTimerService.
     {
         return localTimeWithoutDaylightSavingTimerService.GetCurrentShift();
     }
GetTm()
tm * services::TimeWithLocalization::GetTm (infra::TimePoint timePoint) static
Definition at line 31 of file TimeWithLocalization.cpp.
Referenced by operator<<(), TimePointToCalenderDay(), and TimePointToHourMinSec().
     {
         auto timeAsTimeType = std::chrono::system_clock::to_time_t(timePoint);
         auto timeAsGmTime = std::gmtime(&timeAsTimeType);
         assert(timeAsGmTime != nullptr);
         return timeAsGmTime;
     }
Local()
infra::DerivedTimerService & services::TimeWithLocalization::Local ()
Definition at line 26 of file TimeWithLocalization.cpp.
References localTimeTimerService.
     {
         return localTimeTimerService;
     }
LocalWithoutDaylightSaving()
infra::DerivedTimerService & services::TimeWithLocalization::LocalWithoutDaylightSaving ()
Definition at line 21 of file TimeWithLocalization.cpp.
References localTimeWithoutDaylightSavingTimerService.
     {
         return localTimeWithoutDaylightSavingTimerService;
     }
OffsetFromTimeString()
infra::Optional< infra::BoundedConstString > services::TimeWithLocalization::OffsetFromTimeString (infra::BoundedConstString timePointString) static
Definition at line 105 of file TimeWithLocalization.cpp.
References DateTimeSize, infra::BoundedStringBase< T >::find(), infra::BoundedStringBase< T >::find_first_of(), infra::inPlace, infra::none, infra::BoundedStringBase< char >::npos, infra::BoundedStringBase< T >::size(), and infra::BoundedStringBase< T >::substr().
     {
         if (timePointString.size() <= DateTimeSize)
             return infra::none;
         infra::BoundedConstString left = timePointString.substr(DateTimeSize);
         if (left.find_first_of('Z') != infra::BoundedString::npos && left.find_first_of('Z') == left.size() - 1)
             return infra::Optional<infra::BoundedConstString>(infra::inPlace, "+00:00");
         else if (left.find('+') != infra::BoundedString::npos)
             return infra::Optional<infra::BoundedConstString>(infra::inPlace, left.substr(left.find_first_of('+')));
         else if (left.find('-') != infra::BoundedString::npos)
             return infra::Optional<infra::BoundedConstString>(infra::inPlace, left.substr(left.find_first_of('-')));
         return infra::none;
     }
TimePointFromString()
infra::Optional< infra::TimePoint > services::TimeWithLocalization::TimePointFromString (infra::BoundedConstString timePointString) static
Definition at line 47 of file TimeWithLocalization.cpp.
References infra::InputStream::Failed(), infra::inPlace, infra::none, and infra::softFail.
     {
         uint16_t year = 0;
         uint8_t month = 0;
         uint8_t day = 0;
         uint8_t hour = 0;
         uint8_t minute = 0;
         uint8_t second = 0;
         char separator = {};
         infra::StringInputStream stream(timePointString, infra::softFail);
         stream >> year >> separator >> month >> separator >> day >> separator >> hour >> separator >> minute >> separator >> second;
         if (stream.Failed())
             return infra::none;
         struct std::tm tm = {};
         tm.tm_year = year - 1900;
         tm.tm_mon = month - 1;
         tm.tm_mday = day + 1;   // Adjust 1 day forward for tests that use times close to 1970
         tm.tm_hour = hour;
         tm.tm_min = minute;
         tm.tm_sec = second;
         time_t nullTime = 100000;
         std::tm* localUtcDiff = gmtime(&nullTime);
         assert(localUtcDiff != nullptr);
         std::time_t newTime = std::mktime(&tm) + nullTime - std::mktime(localUtcDiff);
         newTime -= 24 * 3600;   // Adjust 1 day backward for tests that use times close to 1970
         return infra::Optional<infra::TimePoint>(infra::inPlace, std::chrono::seconds(newTime));
     }
TimePointToCalenderDay()
uint8_t services::TimeWithLocalization::TimePointToCalenderDay (infra::TimePoint timePoint) static
Definition at line 122 of file TimeWithLocalization.cpp.
References GetTm().
     {
         auto timeAsGmTime = GetTm(timePoint);
         std::mktime(timeAsGmTime);
         return static_cast<uint8_t>(timeAsGmTime->tm_wday);
     }
TimePointToHourMinSec()
void services::TimeWithLocalization::TimePointToHourMinSec (infra::TimePoint timePoint, uint8_t & hours, uint8_t & min, uint8_t & sec) static
Definition at line 39 of file TimeWithLocalization.cpp.
References GetTm().
     {
         auto timeAsGmTime = GetTm(timePoint);
         hours = static_cast<uint8_t>(timeAsGmTime->tm_hour);
         min = static_cast<uint8_t>(timeAsGmTime->tm_min);
         sec = static_cast<uint8_t>(timeAsGmTime->tm_sec);
     }
Utc()
infra::DerivedTimerService & services::TimeWithLocalization::Utc ()
Definition at line 16 of file TimeWithLocalization.cpp.
References utcTimerService.
Referenced by services::SntpClient::NotifyOffsetAndDelay(), and services::SntpClient::SendStreamAvailable().
     {
         return utcTimerService;
     }
Member Data Documentation
DateTimeSize
const std::size_t services::TimeWithLocalization::DateTimeSize = 19 static
Definition at line 13 of file TimeWithLocalization.hpp.
Referenced by OffsetFromTimeString().
localTimeTimerService
infra::DerivedTimerService services::TimeWithLocalization::localTimeTimerService private
Definition at line 39 of file TimeWithLocalization.hpp.
Referenced by GetOffsetDaylightSaving(), GetOffsetFromLocalToUtc(), and Local().
localTimeWithoutDaylightSavingTimerService
infra::DerivedTimerService services::TimeWithLocalization::localTimeWithoutDaylightSavingTimerService private
Definition at line 38 of file TimeWithLocalization.hpp.
Referenced by GetOffsetFromLocalToUtc(), GetOffsetTimezone(), and LocalWithoutDaylightSaving().
TimeOffsetSize
const std::size_t services::TimeWithLocalization::TimeOffsetSize = 6 static
Definition at line 14 of file TimeWithLocalization.hpp.
utcTimerService
infra::DerivedTimerService services::TimeWithLocalization::utcTimerService private
Definition at line 37 of file TimeWithLocalization.hpp.
Referenced by Utc().
The documentation for this class was generated from the following files:
TimeWithLocalization.hpp
TimeWithLocalization.cpp