EMil: infra::TimerServiceManager Class Reference
infra::TimerServiceManager Class Reference
#include <TimerServiceManager.hpp>
Public Member Functions
void RegisterTimerService (TimerService &timerService)
void UnregisterTimerService (TimerService &timerService)
TimerService & GetTimerService (uint32_t id)
Private Attributes
infra::IntrusiveForwardList< TimerService > timerServices
Additional Inherited Members
Static Public Member Functions inherited from infra::InterfaceConnector< TimerServiceManager >
static TimerServiceManager & Instance ()
static bool InstanceSet ()
Protected Member Functions inherited from infra::InterfaceConnector< TimerServiceManager >
InterfaceConnector ()
InterfaceConnector (TimerServiceManager *instance)
InterfaceConnector (const InterfaceConnector &)=delete
~InterfaceConnector ()
InterfaceConnector & operator= (const InterfaceConnector &)=delete
Detailed Description
Definition at line 9 of file TimerServiceManager.hpp.
Member Function Documentation
GetTimerService()
TimerService & infra::TimerServiceManager::GetTimerService (uint32_t id)
Definition at line 21 of file TimerServiceManager.cpp.
References timerServices.
Referenced by infra::Now().
     {
         for (TimerService& timerService: timerServices)
             if (timerService.Id() == id)
                 return timerService;
         abort();    // No timer service with the given id found
     }
RegisterTimerService()
void infra::TimerServiceManager::RegisterTimerService (TimerService & timerService)
Definition at line 11 of file TimerServiceManager.cpp.
References timerServices.
Referenced by infra::TimerService::TimerService().
     {
         timerServices.push_front(timerService);
     }
UnregisterTimerService()
void infra::TimerServiceManager::UnregisterTimerService (TimerService & timerService)
Definition at line 16 of file TimerServiceManager.cpp.
References timerServices.
Referenced by infra::TimerService::~TimerService().
     {
         timerServices.erase_slow(timerService);
     }
Member Data Documentation
timerServices
infra::IntrusiveForwardList<TimerService> infra::TimerServiceManager::timerServices private
Definition at line 19 of file TimerServiceManager.hpp.
Referenced by GetTimerService(), RegisterTimerService(), and UnregisterTimerService().
The documentation for this class was generated from the following files:
TimerServiceManager.hpp
TimerServiceManager.cpp