EMil: infra::IntrusiveBinarySearchTree< T, Compare > Class Template Reference
infra::IntrusiveBinarySearchTree< T, Compare > Class Template Reference
#include <IntrusiveBinarySearchTree.hpp>
Public Types
typedef detail::IntrusiveBinarySearchTreeNode< T > NodeType
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef detail::IntrusiveBinarySearchTreeIterator< T, Compare > iterator
typedef detail::IntrusiveBinarySearchTreeIterator< const T, Compare > const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
IntrusiveBinarySearchTree (Compare compare=Compare())
IntrusiveBinarySearchTree (const IntrusiveBinarySearchTree &)=delete
IntrusiveBinarySearchTree (IntrusiveBinarySearchTree &&other)
IntrusiveBinarySearchTree & operator= (const IntrusiveBinarySearchTree &)=delete
IntrusiveBinarySearchTree & operator= (IntrusiveBinarySearchTree &&other)
~IntrusiveBinarySearchTree ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
size_type size () const
bool empty () const
iterator find (const_reference value)
const_iterator find (const_reference value) const
bool has_element (const_reference value) const
bool invariant_holds () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
reference root ()
const_reference root () const
void insert_in_tree (reference value)
std::tuple< T *, T *, T ** > remove_from_tree (reference value)
T * find_in_tree (const_reference value) const
T * sibling (const_reference node)
T *& parent_child_reference (reference node, const_reference child)
void right_rotate (reference top)
void left_rotate (reference top)
void clear ()
void swap (IntrusiveBinarySearchTree &other)
bool operator== (const IntrusiveBinarySearchTree &other) const
bool operator!= (const IntrusiveBinarySearchTree &other) const
bool operator< (const IntrusiveBinarySearchTree &other) const
bool operator<= (const IntrusiveBinarySearchTree &other) const
bool operator> (const IntrusiveBinarySearchTree &other) const
bool operator>= (const IntrusiveBinarySearchTree &other) const
Protected Member Functions
const T * RootNode () const
Private Member Functions
void erase_from_order (reference value)
Private Attributes
Compare compare
size_type numberOfNodes = 0
T * rootNode = nullptr
T * frontNode = nullptr
T * backNode = nullptr
Detailed Description
template<class T, class Compare>
class infra::IntrusiveBinarySearchTree< T, Compare >
Definition at line 15 of file IntrusiveBinarySearchTree.hpp.
Member Typedef Documentation
const_iterator
template<class T, class Compare> typedef detail::IntrusiveBinarySearchTreeIterator<const T, Compare> infra::IntrusiveBinarySearchTree< T, Compare >::const_iterator
Definition at line 53 of file IntrusiveBinarySearchTree.hpp.
const_pointer
template<class T, class Compare> typedef const T* infra::IntrusiveBinarySearchTree< T, Compare >::const_pointer
Definition at line 51 of file IntrusiveBinarySearchTree.hpp.
const_reference
template<class T, class Compare> typedef const T& infra::IntrusiveBinarySearchTree< T, Compare >::const_reference
Definition at line 49 of file IntrusiveBinarySearchTree.hpp.
const_reverse_iterator
template<class T, class Compare> typedef std::reverse_iterator<const_iterator> infra::IntrusiveBinarySearchTree< T, Compare >::const_reverse_iterator
Definition at line 55 of file IntrusiveBinarySearchTree.hpp.
difference_type
template<class T, class Compare> typedef std::iterator_traits<iterator>::difference_type infra::IntrusiveBinarySearchTree< T, Compare >::difference_type
Definition at line 56 of file IntrusiveBinarySearchTree.hpp.
iterator
template<class T, class Compare> typedef detail::IntrusiveBinarySearchTreeIterator<T, Compare> infra::IntrusiveBinarySearchTree< T, Compare >::iterator
Definition at line 52 of file IntrusiveBinarySearchTree.hpp.
NodeType
template<class T, class Compare> typedef detail::IntrusiveBinarySearchTreeNode<T> infra::IntrusiveBinarySearchTree< T, Compare >::NodeType
Definition at line 45 of file IntrusiveBinarySearchTree.hpp.
pointer
template<class T, class Compare> typedef T* infra::IntrusiveBinarySearchTree< T, Compare >::pointer
Definition at line 50 of file IntrusiveBinarySearchTree.hpp.
reference
template<class T, class Compare> typedef T& infra::IntrusiveBinarySearchTree< T, Compare >::reference
Definition at line 48 of file IntrusiveBinarySearchTree.hpp.
reverse_iterator
template<class T, class Compare> typedef std::reverse_iterator<iterator> infra::IntrusiveBinarySearchTree< T, Compare >::reverse_iterator
Definition at line 54 of file IntrusiveBinarySearchTree.hpp.
size_type
template<class T, class Compare> typedef std::size_t infra::IntrusiveBinarySearchTree< T, Compare >::size_type
Definition at line 57 of file IntrusiveBinarySearchTree.hpp.
value_type
template<class T, class Compare> typedef T infra::IntrusiveBinarySearchTree< T, Compare >::value_type
Definition at line 47 of file IntrusiveBinarySearchTree.hpp.
Constructor & Destructor Documentation
IntrusiveBinarySearchTree() [1/3]
template<class T , class Compare> infra::IntrusiveBinarySearchTree< T, Compare >::IntrusiveBinarySearchTree (Compare compare = Compare()) explicit
Definition at line 184 of file IntrusiveBinarySearchTree.hpp.
         : compare(compare)
     {}
IntrusiveBinarySearchTree() [2/3]
template<class T, class Compare> infra::IntrusiveBinarySearchTree< T, Compare >::IntrusiveBinarySearchTree (const IntrusiveBinarySearchTree< T, Compare > &) delete
IntrusiveBinarySearchTree() [3/3]
template<class T , class Compare> infra::IntrusiveBinarySearchTree< T, Compare >::IntrusiveBinarySearchTree (IntrusiveBinarySearchTree< T, Compare > && other)
Definition at line 189 of file IntrusiveBinarySearchTree.hpp.
     {
         *this = std::move(other);
     }
~IntrusiveBinarySearchTree()
template<class T , class Compare > infra::IntrusiveBinarySearchTree< T, Compare >::~IntrusiveBinarySearchTree ()
Definition at line 208 of file IntrusiveBinarySearchTree.hpp.
     {
         clear();
     }
Member Function Documentation
back() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::reference infra::IntrusiveBinarySearchTree< T, Compare >::back ()
Definition at line 492 of file IntrusiveBinarySearchTree.hpp.
     {
         return static_cast<reference>(*backNode);
     }
back() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reference infra::IntrusiveBinarySearchTree< T, Compare >::back () const
Definition at line 498 of file IntrusiveBinarySearchTree.hpp.
     {
         return static_cast<const_reference>(*backNode);
     }
begin() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::iterator infra::IntrusiveBinarySearchTree< T, Compare >::begin ()
Definition at line 214 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::operator<(), and infra::IntrusiveBinarySearchTree< T, Compare >::operator==().
     {
         return iterator(frontNode, *this);
     }
begin() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_iterator infra::IntrusiveBinarySearchTree< T, Compare >::begin () const
Definition at line 220 of file IntrusiveBinarySearchTree.hpp.
     {
         return const_iterator(frontNode, *this);
     }
cbegin()
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_iterator infra::IntrusiveBinarySearchTree< T, Compare >::cbegin () const
Definition at line 262 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::begin().
     {
         return begin();
     }
cend()
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_iterator infra::IntrusiveBinarySearchTree< T, Compare >::cend () const
Definition at line 268 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::end().
     {
         return end();
     }
clear()
template<class T , class Compare > void infra::IntrusiveBinarySearchTree< T, Compare >::clear ()
Definition at line 692 of file IntrusiveBinarySearchTree.hpp.
     {
         while (!empty())
             remove_from_tree(*rootNode);
     }
crbegin()
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reverse_iterator infra::IntrusiveBinarySearchTree< T, Compare >::crbegin () const
Definition at line 274 of file IntrusiveBinarySearchTree.hpp.
     {
         return rbegin();
     }
crend()
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reverse_iterator infra::IntrusiveBinarySearchTree< T, Compare >::crend () const
Definition at line 280 of file IntrusiveBinarySearchTree.hpp.
     {
         return rend();
     }
empty()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::empty () const
Definition at line 292 of file IntrusiveBinarySearchTree.hpp.
     {
         return numberOfNodes == 0;
     }
end() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::iterator infra::IntrusiveBinarySearchTree< T, Compare >::end ()
Definition at line 226 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::operator<().
     {
         return iterator(nullptr, *this);
     }
end() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_iterator infra::IntrusiveBinarySearchTree< T, Compare >::end () const
Definition at line 232 of file IntrusiveBinarySearchTree.hpp.
     {
         return const_iterator(nullptr, *this);
     }
erase_from_order()
template<class T , class Compare > void infra::IntrusiveBinarySearchTree< T, Compare >::erase_from_order (reference value) private
Definition at line 680 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         if (value.previousInOrder != nullptr)
             value.previousInOrder->nextInOrder = value.nextInOrder;
         if (value.nextInOrder != nullptr)
             value.nextInOrder->previousInOrder = value.previousInOrder;
         value.nextInOrder = nullptr;
         value.previousInOrder = nullptr;
     }
find() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::iterator infra::IntrusiveBinarySearchTree< T, Compare >::find (const_reference value)
Definition at line 298 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         return iterator(find_in_tree(value), *this);
     }
find() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_iterator infra::IntrusiveBinarySearchTree< T, Compare >::find (const_reference value) const
Definition at line 304 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         return const_iterator(find_in_tree(value), *this);
     }
find_in_tree()
template<class T , class Compare > T * infra::IntrusiveBinarySearchTree< T, Compare >::find_in_tree (const_reference value) const
Definition at line 316 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         T* node = rootNode;
         while (node != nullptr)
         {
             if (node == &value)
                 return node;
             if (compare(*node, value))
                 node = node->right;
             else
                 node = node->left;
         }
         return nullptr;
     }
front() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::reference infra::IntrusiveBinarySearchTree< T, Compare >::front ()
Definition at line 480 of file IntrusiveBinarySearchTree.hpp.
     {
         return static_cast<reference>(*frontNode);
     }
front() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reference infra::IntrusiveBinarySearchTree< T, Compare >::front () const
Definition at line 486 of file IntrusiveBinarySearchTree.hpp.
     {
         return static_cast<const_reference>(*frontNode);
     }
has_element()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::has_element (const_reference value) const
Definition at line 310 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         return find_in_tree(value) == &value;
     }
insert_in_tree()
template<class T , class Compare > void infra::IntrusiveBinarySearchTree< T, Compare >::insert_in_tree (reference value)
Definition at line 516 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         ++numberOfNodes;
         if (!rootNode)
         {
             rootNode = &value;
             frontNode = &value;
             backNode = &value;
         }
         else
         {
             T* current = rootNode;
             while (true)
             {
                 if (compare(value, *current))
                 {
                     if (current->left != nullptr)
                         current = current->left;
                     else
                     {
                         current->left = &value;
                         value.parent = current;
                         value.nextInOrder = current;
                         value.previousInOrder = current->previousInOrder;
                         current->previousInOrder = &value;
                         if (value.previousInOrder != nullptr)
                             value.previousInOrder->nextInOrder = &value;
                         else
                             frontNode = &value;
                         break;
                     }
                 }
                 else
                 {
                     if (current->right != nullptr)
                         current = current->right;
                     else
                     {
                         current->right = &value;
                         value.parent = current;
                         value.previousInOrder = current;
                         value.nextInOrder = current->nextInOrder;
                         current->nextInOrder = &value;
                         if (value.nextInOrder != nullptr)
                             value.nextInOrder->previousInOrder = &value;
                         else
                             backNode = &value;
                         break;
                     }
                 }
             }
         }
     }
invariant_holds()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds () const
Definition at line 390 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveSet< T, Compare >::invariant_holds().
     {
         std::size_t nodesDiscovered = 0;
         const T* node = frontNode;
         while (node != nullptr)
         {
             ++nodesDiscovered;
             // A node is the root node if and only if it has no parent
             if ((node->parent == nullptr) != (node == rootNode))
                 return false;
             if (node->parent != nullptr)
             {
                 if (node->parent->left == node)
                 {
                     if (!compare(*node, *node->parent))
                         return false;
                 }
                 else if (node->parent->right == node)
                 {
                     if (!compare(*node->parent, *node))
                         return false;
                 }
                 else
                     return false;
             }
             if (node->left != nullptr)
             {
                 if (node->left->parent != node)
                     return false;
                 if (!compare(*node->left, *node))
                     return false;
             }
             if (node->right != nullptr)
             {
                 if (node->right->parent != node)
                     return false;
                 if (!compare(*node, *node->right))
                     return false;
             }
             // Only the front node has no previousInOrder
             if ((node->previousInOrder == nullptr) != (node == frontNode))
                 return false;
             // Only the back node has no nextInOrder
             if ((node->nextInOrder == nullptr) != (node == backNode))
                 return false;
             const T* nextInOrder = node;
             if (nextInOrder->right != nullptr)
             {
                 nextInOrder = nextInOrder->right;
                 while (nextInOrder->left != nullptr)
                     nextInOrder = nextInOrder->left;
             }
             else
             {
                 while (nextInOrder->parent && nextInOrder->parent->right == nextInOrder)
                     nextInOrder = nextInOrder->parent;
                 if (nextInOrder->parent != nullptr)
                     nextInOrder = nextInOrder->parent;
                 else
                     nextInOrder = nullptr;
             }
             if (node->nextInOrder != nextInOrder)
                 return false;
             if (nextInOrder && nextInOrder->previousInOrder != node)
                 return false;
             if (!nextInOrder && node != backNode)
                 return false;
             node = nextInOrder;
         }
         if (nodesDiscovered != numberOfNodes)
             return false;
         return true;
     }
left_rotate()
template<class T , class Compare > void infra::IntrusiveBinarySearchTree< T, Compare >::left_rotate (reference top)
Definition at line 371 of file IntrusiveBinarySearchTree.hpp.
     {
         T* right = top.right;
         top.right = right->left;
         right->left = &top;
         right->parent = top.parent;
         top.parent = right;
         if (top.right != nullptr)
             top.right->parent = &top;
         if (right->parent != nullptr)
             parent_child_reference(*right->parent, top) = right;
         else
             rootNode = right;
     }
operator!=()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::operator!= (const IntrusiveBinarySearchTree< T, Compare > & other) const
Definition at line 716 of file IntrusiveBinarySearchTree.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::operator< (const IntrusiveBinarySearchTree< T, Compare > & other) const
Definition at line 722 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::begin(), infra::IntrusiveBinarySearchTree< T, Compare >::begin(), infra::detail::end(), and infra::IntrusiveBinarySearchTree< T, Compare >::end().
     {
         return std::lexicographical_compare(begin(), end(), other.begin(), other.end(), compare);
     }
operator<=()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::operator<= (const IntrusiveBinarySearchTree< T, Compare > & other) const
Definition at line 728 of file IntrusiveBinarySearchTree.hpp.
     {
         return !(other < *this);
     }
operator=() [1/2]
template<class T, class Compare> IntrusiveBinarySearchTree& infra::IntrusiveBinarySearchTree< T, Compare >::operator= (const IntrusiveBinarySearchTree< T, Compare > &) delete
operator=() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare > & infra::IntrusiveBinarySearchTree< T, Compare >::operator= (IntrusiveBinarySearchTree< T, Compare > && other)
Definition at line 195 of file IntrusiveBinarySearchTree.hpp.
References infra::swap().
     {
         clear();
         std::swap(numberOfNodes, other.numberOfNodes);
         std::swap(rootNode, other.rootNode);
         std::swap(frontNode, other.frontNode);
         std::swap(backNode, other.backNode);
         return *this;
     }
operator==()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::operator== (const IntrusiveBinarySearchTree< T, Compare > & other) const
Definition at line 709 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::begin(), infra::IntrusiveBinarySearchTree< T, Compare >::begin(), infra::detail::end(), and infra::IntrusiveBinarySearchTree< T, Compare >::size().
     {
         return size() == other.size()
             && std::equal(begin(), end(), other.begin());
     }
operator>()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::operator> (const IntrusiveBinarySearchTree< T, Compare > & other) const
Definition at line 734 of file IntrusiveBinarySearchTree.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T , class Compare > bool infra::IntrusiveBinarySearchTree< T, Compare >::operator>= (const IntrusiveBinarySearchTree< T, Compare > & other) const
Definition at line 740 of file IntrusiveBinarySearchTree.hpp.
     {
         return !(*this < other);
     }
parent_child_reference()
template<class T , class Compare > T *& infra::IntrusiveBinarySearchTree< T, Compare >::parent_child_reference (reference node, const_reference child)
Definition at line 343 of file IntrusiveBinarySearchTree.hpp.
     {
         if (parent.left == &child)
             return parent.left;
         else
             return parent.right;
     }
rbegin() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::reverse_iterator infra::IntrusiveBinarySearchTree< T, Compare >::rbegin ()
Definition at line 238 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::end().
     {
         return reverse_iterator(end());
     }
rbegin() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reverse_iterator infra::IntrusiveBinarySearchTree< T, Compare >::rbegin () const
Definition at line 244 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::end().
     {
         return const_reverse_iterator(end());
     }
remove_from_tree()
template<class T , class Compare > std::tuple< T *, T *, T ** > infra::IntrusiveBinarySearchTree< T, Compare >::remove_from_tree (reference value)
Definition at line 572 of file IntrusiveBinarySearchTree.hpp.
References value.
     {
         T* replacement = nullptr;
         T* oldReplacementParent = nullptr;
         T** oldReplacement = nullptr;
         if (!value.left && !value.right)
         {
             if (!value.parent)
             {
                 rootNode = nullptr;
                 frontNode = nullptr;
                 backNode = nullptr;
             }
             else
             {
                 oldReplacementParent = &value;
                 oldReplacement = &parent_child_reference(*value.parent, value);
                 if (value.parent->left == &value)
                 {
                     value.parent->left = nullptr;
                     if (&value == frontNode)
                         frontNode = value.parent;
                 }
                 else
                 {
                     value.parent->right = nullptr;
                     if (&value == backNode)
                         backNode = value.parent;
                 }
             }
         }
         else if (!value.left)
         {
             replacement = value.right;
             oldReplacementParent = replacement->parent;
             oldReplacement = &parent_child_reference(*replacement->parent, *replacement);
             value.right->parent = value.parent;
             if (!value.parent)
                 rootNode = value.right;
             else
                 parent_child_reference(*value.parent, value) = value.right;
             if (&value == frontNode)
                 frontNode = value.nextInOrder;
         }
         else if (!value.right)
         {
             replacement = value.left;
             oldReplacementParent = replacement->parent;
             oldReplacement = &parent_child_reference(*replacement->parent, *replacement);
             value.left->parent = value.parent;
             if (!value.parent)
                 rootNode = value.left;
             else
                 parent_child_reference(*value.parent, value) = value.left;
             if (&value == backNode)
                 backNode = value.previousInOrder;
         }
         else
         {
             replacement = value.nextInOrder;
             oldReplacementParent = replacement->parent;
             oldReplacement = &parent_child_reference(*replacement->parent, *replacement);
             if (replacement != value.right)
             {
                 if (replacement->right != nullptr)
                     replacement->right->parent = replacement->parent;
                 replacement->parent->left = replacement->right;
                 replacement->right = value.right;
                 replacement->right->parent = replacement;
             }
             replacement->parent = value.parent;
             replacement->left = value.left;
             replacement->left->parent = replacement;
             if (!replacement->parent)
                 rootNode = replacement;
             else
                 parent_child_reference(*replacement->parent, value) = replacement;
         }
         value.parent = nullptr;
         value.left = nullptr;
         value.right = nullptr;
         erase_from_order(value);
         --numberOfNodes;
         return std::make_tuple(replacement, oldReplacementParent, oldReplacement);
     }
rend() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::reverse_iterator infra::IntrusiveBinarySearchTree< T, Compare >::rend ()
Definition at line 250 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::begin().
     {
         return reverse_iterator(begin());
     }
rend() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reverse_iterator infra::IntrusiveBinarySearchTree< T, Compare >::rend () const
Definition at line 256 of file IntrusiveBinarySearchTree.hpp.
References infra::detail::begin().
     {
         return const_reverse_iterator(begin());
     }
right_rotate()
template<class T , class Compare > void infra::IntrusiveBinarySearchTree< T, Compare >::right_rotate (reference top)
Definition at line 352 of file IntrusiveBinarySearchTree.hpp.
     {
         T* left = top.left;
         top.left = left->right;
         left->right = &top;
         left->parent = top.parent;
         top.parent = left;
         if (top.left != nullptr)
             top.left->parent = &top;
         if (left->parent != nullptr)
             parent_child_reference(*left->parent, top) = left;
         else
             rootNode = left;
     }
root() [1/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::reference infra::IntrusiveBinarySearchTree< T, Compare >::root ()
Definition at line 504 of file IntrusiveBinarySearchTree.hpp.
     {
         return static_cast<reference>(*rootNode);
     }
root() [2/2]
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::const_reference infra::IntrusiveBinarySearchTree< T, Compare >::root () const
Definition at line 510 of file IntrusiveBinarySearchTree.hpp.
     {
         return static_cast<const_reference>(*rootNode);
     }
RootNode()
template<class T , class Compare > const T * infra::IntrusiveBinarySearchTree< T, Compare >::RootNode () const protected
Definition at line 674 of file IntrusiveBinarySearchTree.hpp.
     {
         return rootNode;
     }
sibling()
template<class T , class Compare > T * infra::IntrusiveBinarySearchTree< T, Compare >::sibling (const_reference node)
Definition at line 334 of file IntrusiveBinarySearchTree.hpp.
     {
         if (node.parent->left == &node)
             return node.parent->right;
         else
             return node.parent->left;
     }
size()
template<class T , class Compare > IntrusiveBinarySearchTree< T, Compare >::size_type infra::IntrusiveBinarySearchTree< T, Compare >::size () const
Definition at line 286 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::operator==().
     {
         return numberOfNodes;
     }
swap()
template<class T , class Compare > void infra::IntrusiveBinarySearchTree< T, Compare >::swap (IntrusiveBinarySearchTree< T, Compare > & other)
Definition at line 699 of file IntrusiveBinarySearchTree.hpp.
References infra::IntrusiveBinarySearchTree< T, Compare >::backNode, infra::IntrusiveBinarySearchTree< T, Compare >::compare, infra::IntrusiveBinarySearchTree< T, Compare >::frontNode, infra::IntrusiveBinarySearchTree< T, Compare >::numberOfNodes, infra::IntrusiveBinarySearchTree< T, Compare >::rootNode, and infra::swap().
Referenced by infra::IntrusiveSet< T, Compare >::swap(), and infra::swap().
     {
         std::swap(numberOfNodes, other.numberOfNodes);
         std::swap(rootNode, other.rootNode);
         std::swap(frontNode, other.frontNode);
         std::swap(backNode, other.backNode);
         std::swap(compare, other.compare);
     }
Member Data Documentation
backNode
template<class T, class Compare> T* infra::IntrusiveBinarySearchTree< T, Compare >::backNode = nullptr private
Definition at line 134 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::swap().
compare
template<class T, class Compare> Compare infra::IntrusiveBinarySearchTree< T, Compare >::compare private
Definition at line 130 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::swap().
frontNode
template<class T, class Compare> T* infra::IntrusiveBinarySearchTree< T, Compare >::frontNode = nullptr private
Definition at line 133 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::swap().
numberOfNodes
template<class T, class Compare> size_type infra::IntrusiveBinarySearchTree< T, Compare >::numberOfNodes = 0 private
Definition at line 131 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::swap().
rootNode
template<class T, class Compare> T* infra::IntrusiveBinarySearchTree< T, Compare >::rootNode = nullptr private
Definition at line 132 of file IntrusiveBinarySearchTree.hpp.
Referenced by infra::IntrusiveBinarySearchTree< T, Compare >::swap().
The documentation for this class was generated from the following file:
IntrusiveBinarySearchTree.hpp