EMil: infra::Variant< T > Class Template Reference
infra::Variant< T > Class Template Reference
#include <Variant.hpp>
Public Member Functions
Variant ()
Variant (const Variant &other)
template<class... T2>
Variant (const Variant< T2... > &other)
template<class U >
Variant (const U &v, typename std::enable_if< ExistsInTypeList< U, T... >::value >::type *=0)
template<class U , class... Args>
Variant (InPlaceType< U >, Args &&... args)
template<class... Args>
Variant (AtIndex, std::size_t index, Args &&... args)
Variant & operator= (const Variant &other)
template<class... T2>
Variant & operator= (const Variant< T2... > &other)
template<class U >
Variant & operator= (const U &v)
~Variant ()
template<class U , class... Args>
U & Emplace (Args &&... args)
template<class U >
const U & Get () const
template<class U >
U & Get ()
template<std::size_t Index>
const TypeAtIndex< Index, T... >::Type & GetAtIndex () const
template<std::size_t Index>
TypeAtIndex< Index, T... >::Type & GetAtIndex ()
std::size_t Which () const
template<class U >
bool Is () const
bool operator== (const Variant &other) const
bool operator!= (const Variant &other) const
bool operator< (const Variant &other) const
bool operator> (const Variant &other) const
bool operator<= (const Variant &other) const
bool operator>= (const Variant &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator== (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator!= (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator< (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator> (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator<= (const U &other) const
template<class U >
std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type operator>= (const U &other) const
template<class U , class... Args>
U & ConstructInEmptyVariant (Args &&... args)
template<class... Args>
void ConstructByIndexInEmptyVariant (std::size_t index, Args &&... args)
template<class... T2>
Variant< T... > & operator= (const Variant< T2... > &other)
template<class U>
Variant< T... > & operator= (const U &v)
Static Public Attributes
static const std::size_t size = sizeof...(T)
Private Member Functions
void Destruct ()
Private Attributes
std::size_t dataIndex = 0
std::aligned_storage< MaxSizeOfTypes< T... >::value, MaxAlignmentOfTypes< T... >::value >::type data
Friends
template<class... T2>
struct detail::ConstructVisitor
Detailed Description
template<class... T>
class infra::Variant< T >
Definition at line 14 of file Variant.hpp.
Constructor & Destructor Documentation
Variant() [1/6]
template<class... T> infra::Variant< T >::Variant ()
Definition at line 105 of file Variant.hpp.
     {
         ConstructInEmptyVariant<typename Front<T...>::Type>();
     }
Variant() [2/6]
template<class... T> infra::Variant< T >::Variant (const Variant< T > & other)
Definition at line 111 of file Variant.hpp.
     {
         detail::ConstructVisitor<T...> visitor(*this);
         ApplyVisitor(visitor, other);
     }
Variant() [3/6]
template<class... T> template<class... T2> infra::Variant< T >::Variant (const Variant< T2... > & other)
Definition at line 119 of file Variant.hpp.
     {
         detail::ConstructVisitor<T...> visitor(*this);
         ApplyVisitor(visitor, other);
     }
Variant() [4/6]
template<class... T> template<class U> infra::Variant< T >::Variant (const U & v, typename std::enable_if< ExistsInTypeList< U, T... >::value >::type * = 0)
Definition at line 127 of file Variant.hpp.
     {
         ConstructInEmptyVariant<U>(v);
     }
Variant() [5/6]
template<class... T> template<class U, class... Args> infra::Variant< T >::Variant (InPlaceType< U > , Args &&... args) explicit
Definition at line 134 of file Variant.hpp.
     {
         ConstructInEmptyVariant<U>(std::forward<Args>(args)...);
     }
Variant() [6/6]
template<class... T> template<class... Args> infra::Variant< T >::Variant (AtIndex , std::size_t index, Args &&... args)
Definition at line 141 of file Variant.hpp.
     {
         ConstructByIndexInEmptyVariant(index, std::forward<Args>(args)...);
     }
~Variant()
template<class... T> infra::Variant< T >::~Variant ()
Definition at line 187 of file Variant.hpp.
     {
         Destruct();
     }
Member Function Documentation
ConstructByIndexInEmptyVariant()
template<class... T> template<class... Args> void infra::Variant< T >::ConstructByIndexInEmptyVariant (std::size_t index, Args &&... args)
Definition at line 340 of file Variant.hpp.
     {
         dataIndex = index;
         detail::ConstructAtIndexHelper<T...>::Construct(*this, index, std::forward<Args>(args)...);
     }
ConstructInEmptyVariant()
template<class... T> template<class U , class... Args> U & infra::Variant< T >::ConstructInEmptyVariant (Args &&... args)
Definition at line 332 of file Variant.hpp.
     {
         dataIndex = IndexInTypeList<U, T...>::value;
         return *new(&data) U(std::forward<Args>(args)...);                                                                  //TICS !OAL#011: This is placement-new
     }
Destruct()
template<class... T> void infra::Variant< T >::Destruct () private
Definition at line 347 of file Variant.hpp.
     {
         detail::DestroyVisitor visitor;
         ApplyVisitor(visitor, *this);
     }
Emplace()
template<class... T> template<class U , class... Args> U & infra::Variant< T >::Emplace (Args &&... args)
Definition at line 180 of file Variant.hpp.
     {
         Destruct();
         return ConstructInEmptyVariant<U>(std::forward<Args>(args)...);
     }
Get() [1/2]
template<class... T> template<class U > const U & infra::Variant< T >::Get () const
Definition at line 194 of file Variant.hpp.
Referenced by services::DatagramBsd::BindRemote(), services::DatagramWin::BindRemote(), services::ConnectionMbedTls::ConnectionMbedTls(), services::ConnectorBsd::ConnectorBsd(), services::ConnectorWin::ConnectorWin(), infra::JsonIterator::ConvertValue(), services::GetAddress(), services::GetPort(), infra::JsonObject::GetValue(), services::MakeUdpSocket(), infra::operator<<(), services::DnsResolver::ReplyParser::ReadAnswerRecords(), infra::JsonIterator::ReadArrayValue(), infra::JsonObjectIterator::ReadKey(), infra::JsonObjectIterator::ReadKeyOrEnd(), infra::JsonIterator::ReadObjectValue(), infra::JsonIterator::SearchArrayEnd(), infra::JsonIterator::SearchObjectEnd(), services::DatagramWin::Send(), and services::DatagramBsd::Send().
     {
         really_assert((dataIndex == IndexInTypeList<U, T...>::value));
         return reinterpret_cast<const U&>(data);                                                                        //TICS !CON#007
     }
Get() [2/2]
template<class... T> template<class U > U & infra::Variant< T >::Get ()
Definition at line 202 of file Variant.hpp.
     {
         really_assert((dataIndex == IndexInTypeList<U, T...>::value));
         return reinterpret_cast<U&>(data);                                                                              //TICS !CON#007
     }
GetAtIndex() [1/2]
template<class... T> template<std::size_t Index> const TypeAtIndex< Index, T... >::Type & infra::Variant< T >::GetAtIndex () const
Definition at line 210 of file Variant.hpp.
     {
         return Get<typename TypeAtIndex<Index, T...>::Type>();                                                          //TICS !CON#007
     }
GetAtIndex() [2/2]
template<class... T> template<std::size_t Index> TypeAtIndex< Index, T... >::Type & infra::Variant< T >::GetAtIndex ()
Definition at line 217 of file Variant.hpp.
     {
         return Get<typename TypeAtIndex<Index, T...>::Type>();                                                          //TICS !CON#007
     }
Is()
template<class... T> template<class U > bool infra::Variant< T >::Is () const
Definition at line 230 of file Variant.hpp.
Referenced by infra::CleanJsonContents(), services::EventDispatcherWithNetwork::Connect(), infra::JsonIterator::ConvertValue(), services::GetAddress(), services::GetPort(), services::MakeUdpSocket(), infra::JsonArrayIterator::operator++(), infra::operator<<(), infra::JsonObjectIterator::ReadColon(), infra::JsonObjectIterator::ReadCommaOrObjectEnd(), infra::JsonObjectIterator::ReadKey(), infra::JsonObjectIterator::ReadKeyOrEnd(), infra::JsonObjectIterator::ReadObjectStart(), infra::JsonIterator::SearchArrayEnd(), and infra::JsonIterator::SearchObjectEnd().
     {
         return Which() == IndexInTypeList<U, T...>::value;                                                      //TICS !CON#007
     }
operator!=() [1/2]
template<class... T> bool infra::Variant< T >::operator!= (const Variant< T > & other) const
Definition at line 246 of file Variant.hpp.
     {
         return !(*this == other);                                                                               //TICS !CON#007
     }
operator!=() [2/2]
template<class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::Variant< T >::operator!= (const U & other) const
Definition at line 291 of file Variant.hpp.
     {
         return !(*this == other);
     }
operator<() [1/2]
template<class... T> bool infra::Variant< T >::operator< (const Variant< T > & other) const
Definition at line 252 of file Variant.hpp.
     {
         if (Which() != other.Which())
             return Which() < other.Which();
         detail::LessThanVisitor visitor;
         return ApplySameTypeVisitor(visitor, *this, other);
     }
operator<() [2/2]
template<class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::Variant< T >::operator< (const U & other) const
Definition at line 298 of file Variant.hpp.
     {
         if (Which() != IndexInTypeList<U, T...>::value)
             return Which() < IndexInTypeList<U, T...>::value;
         return GetAtIndex<IndexInTypeList<U, T...>::value>() < other;
     }
operator<=() [1/2]
template<class... T> bool infra::Variant< T >::operator<= (const Variant< T > & other) const
Definition at line 268 of file Variant.hpp.
     {
         return !(other < *this);
     }
operator<=() [2/2]
template<class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::Variant< T >::operator<= (const U & other) const
Definition at line 318 of file Variant.hpp.
     {
         return !(*this > other);
     }
operator=() [1/5]
template<class... T> Variant< T... > & infra::Variant< T >::operator= (const Variant< T > & other)
Definition at line 147 of file Variant.hpp.
     {
         if (this != &other)                                                                                         //TICS !CON#007
         {
             detail::CopyVisitor<T...> visitor(*this);
             ApplyVisitor(visitor, other);
         }
         return *this;
     }
operator=() [2/5]
template<class... T> template<class... T2> Variant& infra::Variant< T >::operator= (const Variant< T2... > & other)
operator=() [3/5]
template<class... T> template<class U > Variant& infra::Variant< T >::operator= (const U & v)
operator=() [4/5]
template<class... T> template<class... T2> Variant<T...>& infra::Variant< T >::operator= (const Variant< T2... > & other)
Definition at line 160 of file Variant.hpp.
     {
         detail::CopyVisitor<T...> visitor(*this);
         ApplyVisitor(visitor, other);
         return *this;
     }
operator=() [5/5]
template<class... T> template<class U> Variant<T...>& infra::Variant< T >::operator= (const U & v)
Definition at line 170 of file Variant.hpp.
     {
         Destruct();
         ConstructInEmptyVariant<U>(v);
         return *this;
     }
operator==() [1/2]
template<class... T> bool infra::Variant< T >::operator== (const Variant< T > & other) const
Definition at line 236 of file Variant.hpp.
     {
         if (Which() != other.Which())                                                                           //TICS !CON#007
             return false;
         detail::EqualVisitor visitor;
         return ApplySameTypeVisitor(visitor, *this, other);                                                     //TICS !CON#007
     }
operator==() [2/2]
template<class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::Variant< T >::operator== (const U & other) const
Definition at line 281 of file Variant.hpp.
     {
         if (Which() != IndexInTypeList<U, T...>::value)
             return false;
         return GetAtIndex<IndexInTypeList<U, T...>::value>() == other;
     }
operator>() [1/2]
template<class... T> bool infra::Variant< T >::operator> (const Variant< T > & other) const
Definition at line 262 of file Variant.hpp.
     {
         return other < *this;
     }
operator>() [2/2]
template<class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::Variant< T >::operator> (const U & other) const
Definition at line 308 of file Variant.hpp.
     {
         if (Which() != IndexInTypeList<U, T...>::value)
             return Which() > IndexInTypeList<U, T...>::value;
         return other < GetAtIndex<IndexInTypeList<U, T...>::value>();
     }
operator>=() [1/2]
template<class... T> bool infra::Variant< T >::operator>= (const Variant< T > & other) const
Definition at line 274 of file Variant.hpp.
     {
         return !(*this < other);
     }
operator>=() [2/2]
template<class... T> template<class U > std::enable_if< ExistsInTypeList< U, T... >::value, bool >::type infra::Variant< T >::operator>= (const U & other) const
Definition at line 325 of file Variant.hpp.
     {
         return !(*this < other);
     }
Which()
template<class... T> std::size_t infra::Variant< T >::Which () const
Definition at line 223 of file Variant.hpp.
Referenced by infra::ApplySameTypeVisitor(), infra::detail::ApplyVisitorHelper< Index, Visitor, Variant, Enable >::operator()(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >::operator()(), infra::detail::ApplySameTypeVisitorHelper< Index, Visitor, Variant, Enable >::operator()(), infra::Variant< services::IPv4Address, services::IPv6Address >::operator<(), infra::Variant< services::IPv4Address, services::IPv6Address >::operator==(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, Enable >::VisitSecond(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+1==Variant::size >::type >::VisitSecond(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+2==Variant::size >::type >::VisitSecond(), infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+3==Variant::size >::type >::VisitSecond(), and infra::detail::ApplyVisitorHelper2< Index, Visitor, Variant, typename std::enable_if< Index+4==Variant::size >::type >::VisitSecond().
     {
         return dataIndex;
     }
Friends And Related Function Documentation
detail::ConstructVisitor
template<class... T> template<class... T2> friend struct detail::ConstructVisitor friend
Definition at line 89 of file Variant.hpp.
Member Data Documentation
data
template<class... T> std::aligned_storage<MaxSizeOfTypes<T...>::value, MaxAlignmentOfTypes<T...>::value>::type infra::Variant< T >::data private
Definition at line 86 of file Variant.hpp.
dataIndex
template<class... T> std::size_t infra::Variant< T >::dataIndex = 0 private
Definition at line 85 of file Variant.hpp.
size
template<class... T> const std::size_t infra::Variant< T >::size = sizeof...(T) static
Definition at line 17 of file Variant.hpp.
The documentation for this class was generated from the following file:
Variant.hpp