EMil: services::HttpRequestParser Class Reference
services::HttpRequestParser Class Reference abstract
#include <HttpRequestParser.hpp>
Public Member Functions
virtual bool Complete () const =0
virtual bool Valid () const =0
virtual HttpVerb Verb () const =0
virtual const infra::Tokenizer & PathTokens () const =0
virtual infra::BoundedString Body ()=0
virtual infra::BoundedConstString Body () const =0
virtual infra::BoundedConstString Header (infra::BoundedConstString name) const =0
virtual void EnumerateHeaders (const infra::Function< void(infra::BoundedConstString name, infra::BoundedConstString value)> &enumerator) const =0
Protected Member Functions
HttpRequestParser ()=default
HttpRequestParser (const HttpRequestParser &other)=delete
HttpRequestParser & operator= (const HttpRequestParser &other)=delete
~HttpRequestParser ()=default
Detailed Description
Definition at line 11 of file HttpRequestParser.hpp.
Constructor & Destructor Documentation
HttpRequestParser() [1/2]
services::HttpRequestParser::HttpRequestParser () protected default
HttpRequestParser() [2/2]
services::HttpRequestParser::HttpRequestParser (const HttpRequestParser & other) protected delete
~HttpRequestParser()
services::HttpRequestParser::~HttpRequestParser () protected default
Member Function Documentation
Body() [1/2]
virtual infra::BoundedString services::HttpRequestParser::Body () pure virtual
Implemented in services::HttpRequestParserImpl.
Body() [2/2]
virtual infra::BoundedConstString services::HttpRequestParser::Body () const pure virtual
Implemented in services::HttpRequestParserImpl.
Complete()
virtual bool services::HttpRequestParser::Complete () const pure virtual
Implemented in services::HttpRequestParserImpl.
EnumerateHeaders()
virtual void services::HttpRequestParser::EnumerateHeaders (const infra::Function< void(infra::BoundedConstString name, infra::BoundedConstString value)> & enumerator) const pure virtual
Implemented in services::HttpRequestParserImpl.
Header()
virtual infra::BoundedConstString services::HttpRequestParser::Header (infra::BoundedConstString name) const pure virtual
Implemented in services::HttpRequestParserImpl.
Referenced by services::HttpServerConnectionObserver::Expect100().
operator=()
HttpRequestParser& services::HttpRequestParser::operator= (const HttpRequestParser & other) protected delete
PathTokens()
virtual const infra::Tokenizer& services::HttpRequestParser::PathTokens () const pure virtual
Implemented in services::HttpRequestParserImpl.
Referenced by services::HttpPageServer::PageForRequest().
Valid()
virtual bool services::HttpRequestParser::Valid () const pure virtual
Implemented in services::HttpRequestParserImpl.
Referenced by services::HttpServerConnectionObserver::TryHandleRequest().
Verb()
virtual HttpVerb services::HttpRequestParser::Verb () const pure virtual
Implemented in services::HttpRequestParserImpl.
The documentation for this class was generated from the following file:
HttpRequestParser.hpp