EMil: infra::detail::SharedPtrControl Class Reference
infra::detail::SharedPtrControl Class Reference
#include <SharedPtr.hpp>
Public Member Functions
SharedPtrControl (const void *object, SharedObjectDeleter *deleter)
SharedPtrControl (const SharedPtrControl &other)=delete
SharedPtrControl & operator= (const SharedPtrControl &other)=delete
void IncreaseSharedCount ()
void DecreaseSharedCount ()
void IncreaseWeakCount ()
void DecreaseWeakCount ()
bool Expired () const
bool UnReferenced () const
Private Attributes
uint16_t sharedPtrCount = 0
uint16_t weakPtrCount = 0
const void * object = nullptr
SharedObjectDeleter * deleter = nullptr
Detailed Description
Definition at line 34 of file SharedPtr.hpp.
Constructor & Destructor Documentation
SharedPtrControl() [1/2]
infra::detail::SharedPtrControl::SharedPtrControl (const void * object, SharedObjectDeleter * deleter)
Definition at line 9 of file SharedPtr.cpp.
             : object(object)
             , deleter(deleter)
         {}
SharedPtrControl() [2/2]
infra::detail::SharedPtrControl::SharedPtrControl (const SharedPtrControl & other) delete
Member Function Documentation
DecreaseSharedCount()
void infra::detail::SharedPtrControl::DecreaseSharedCount ()
Definition at line 20 of file SharedPtr.cpp.
References DecreaseWeakCount(), deleter, infra::SharedObjectDeleter::Destruct(), and sharedPtrCount.
Referenced by infra::SharedPtr< services::ConnectionObserver >::Reset().
         {
             assert(sharedPtrCount != 0);
             --sharedPtrCount;
             if (sharedPtrCount == 0)
                 deleter->Destruct(object);
             DecreaseWeakCount();
         }
DecreaseWeakCount()
void infra::detail::SharedPtrControl::DecreaseWeakCount ()
Definition at line 36 of file SharedPtr.cpp.
References infra::SharedObjectDeleter::Deallocate(), deleter, and weakPtrCount.
Referenced by DecreaseSharedCount().
         {
             assert(weakPtrCount != 0);
             --weakPtrCount;
             if (weakPtrCount == 0)
                 deleter->Deallocate(this);
         }
Expired()
bool infra::detail::SharedPtrControl::Expired () const
Definition at line 45 of file SharedPtr.cpp.
References sharedPtrCount.
Referenced by infra::SharedPtr< services::ConnectionObserver >::SharedPtr().
         {
             return sharedPtrCount == 0;
         }
IncreaseSharedCount()
void infra::detail::SharedPtrControl::IncreaseSharedCount ()
Definition at line 14 of file SharedPtr.cpp.
References IncreaseWeakCount(), and sharedPtrCount.
         {
             ++sharedPtrCount;
             IncreaseWeakCount();
         }
IncreaseWeakCount()
void infra::detail::SharedPtrControl::IncreaseWeakCount ()
Definition at line 31 of file SharedPtr.cpp.
References weakPtrCount.
Referenced by IncreaseSharedCount().
         {
             ++weakPtrCount;
         }
operator=()
SharedPtrControl& infra::detail::SharedPtrControl::operator= (const SharedPtrControl & other) delete
UnReferenced()
bool infra::detail::SharedPtrControl::UnReferenced () const
Definition at line 50 of file SharedPtr.cpp.
References weakPtrCount.
Referenced by infra::AccessedBySharedPtr::~AccessedBySharedPtr().
         {
             return weakPtrCount == 0;
         }
Member Data Documentation
deleter
SharedObjectDeleter* infra::detail::SharedPtrControl::deleter = nullptr private
Definition at line 53 of file SharedPtr.hpp.
Referenced by DecreaseSharedCount(), and DecreaseWeakCount().
object
const void* infra::detail::SharedPtrControl::object = nullptr private
Definition at line 52 of file SharedPtr.hpp.
sharedPtrCount
uint16_t infra::detail::SharedPtrControl::sharedPtrCount = 0 private
Definition at line 50 of file SharedPtr.hpp.
Referenced by DecreaseSharedCount(), Expired(), and IncreaseSharedCount().
weakPtrCount
uint16_t infra::detail::SharedPtrControl::weakPtrCount = 0 private
Definition at line 51 of file SharedPtr.hpp.
Referenced by DecreaseWeakCount(), IncreaseWeakCount(), and UnReferenced().
The documentation for this class was generated from the following files:
SharedPtr.hpp
SharedPtr.cpp