EMil: application::ImageSignerRsa Class Reference
application::ImageSignerRsa Class Reference
#include <ImageSignerRsa.hpp>
Public Member Functions
ImageSignerRsa (RandomNumberGenerator &randomNumberGenerator, const RsaPublicKey &publicKey, const RsaPrivateKey &privateKey)
virtual uint16_t SignatureMethod () const override
virtual uint16_t SignatureLength () const override
virtual std::vector< uint8_t > ImageSignature (const std::vector< uint8_t > &image) override
virtual bool CheckSignature (const std::vector< uint8_t > &signature, const std::vector< uint8_t > &image) override
Static Public Attributes
static const uint16_t signatureMethod = 1
static const size_t keyLength = 1024
Private Member Functions
void CalculateSha256 (const std::vector< uint8_t > &image)
void CalculateSignature (const std::vector< uint8_t > &image)
Static Private Member Functions
static int MyRandom (void *rng_state, unsigned char *output, size_t len)
Private Attributes
const RsaPublicKey & publicKey
const RsaPrivateKey & privateKey
std::string keyFileName
std::array< uint8_t, 32 > hash
std::array< uint8_t, keyLength/8 > signature
Static Private Attributes
static RandomNumberGenerator * randomNumberGenerator = nullptr
Additional Inherited Members
Protected Member Functions inherited from application::ImageSigner
~ImageSigner ()=default
Detailed Description
Definition at line 13 of file ImageSignerRsa.hpp.
Constructor & Destructor Documentation
ImageSignerRsa()
application::ImageSignerRsa::ImageSignerRsa (RandomNumberGenerator & randomNumberGenerator, const RsaPublicKey & publicKey, const RsaPrivateKey & privateKey)
Definition at line 11 of file ImageSignerRsa.cpp.
References randomNumberGenerator.
         : publicKey(publicKey)
         , privateKey(privateKey)
     {
         ImageSignerRsa::randomNumberGenerator = &randomNumberGenerator;
     }
Member Function Documentation
CalculateSha256()
void application::ImageSignerRsa::CalculateSha256 (const std::vector< uint8_t > & image) private
Definition at line 71 of file ImageSignerRsa.cpp.
References hash.
Referenced by CheckSignature(), and ImageSignature().
     {
         mbedtls_sha256_context ctx;
         mbedtls_sha256_init(&ctx);
         mbedtls_sha256_starts(&ctx, 0);
         mbedtls_sha256_update(&ctx, image.data(), image.size());
         mbedtls_sha256_finish(&ctx, hash.data());                                                                       //TICS !INT#030
         mbedtls_sha256_free(&ctx);
     }
CalculateSignature()
void application::ImageSignerRsa::CalculateSignature (const std::vector< uint8_t > & image) private
Definition at line 81 of file ImageSignerRsa.cpp.
References infra::MemoryRange< T >::begin(), RsaPrivateKey::D, RsaPrivateKey::DP, RsaPrivateKey::DQ, RsaPublicKey::E, hash, MyRandom(), RsaPublicKey::N, RsaPrivateKey::P, privateKey, publicKey, RsaPrivateKey::Q, RsaPrivateKey::QP, signature, and infra::MemoryRange< T >::size().
Referenced by ImageSignature().
     {
         int ret;
         mbedtls_rsa_context rsaCtx;
         mbedtls_rsa_init(&rsaCtx, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
         rsaCtx.len = publicKey.N.size();
         rsaCtx.N.s = 1;
         rsaCtx.N.n = publicKey.N.size() / 4;
         rsaCtx.N.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(publicKey.N.begin()));
         rsaCtx.E.s = 1;
         rsaCtx.E.n = publicKey.E.size() / 4;
         rsaCtx.E.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(publicKey.E.begin()));
         rsaCtx.D.s = 1;
         rsaCtx.D.n = privateKey.D.size() / 4;
         rsaCtx.D.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(privateKey.D.begin()));
         rsaCtx.P.s = 1;
         rsaCtx.P.n = privateKey.P.size() / 4;
         rsaCtx.P.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(privateKey.P.begin()));
         rsaCtx.Q.s = 1;
         rsaCtx.Q.n = privateKey.Q.size() / 4;
         rsaCtx.Q.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(privateKey.Q.begin()));
         rsaCtx.DP.s = 1;
         rsaCtx.DP.n = privateKey.DP.size() / 4;
         rsaCtx.DP.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(privateKey.DP.begin()));
         rsaCtx.DQ.s = 1;
         rsaCtx.DQ.n = privateKey.DQ.size() / 4;
         rsaCtx.DQ.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(privateKey.DQ.begin()));
         rsaCtx.QP.s = 1;
         rsaCtx.QP.n = privateKey.QP.size() / 4;
         rsaCtx.QP.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(privateKey.QP.begin()));
         mbedtls_rsa_set_padding(&rsaCtx, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
         if (rsaCtx.len != signature.size())
             throw std::exception("Key length wrong");
         ret = mbedtls_rsa_check_privkey(&rsaCtx);
         if (ret != 0)
             throw std::exception("Public key is invalid");
         ret = mbedtls_rsa_rsassa_pss_sign(&rsaCtx, MyRandom, NULL, MBEDTLS_RSA_PRIVATE, MBEDTLS_MD_SHA256, hash.size(), hash.data(), signature.data());
         if (ret != 0)
             throw std::exception("Failed to calculate signature");
         rsaCtx.N.p = nullptr;
         rsaCtx.E.p = nullptr;
         rsaCtx.D.p = nullptr;
         rsaCtx.P.p = nullptr;
         rsaCtx.Q.p = nullptr;
         rsaCtx.DP.p = nullptr;
         rsaCtx.DQ.p = nullptr;
         rsaCtx.QP.p = nullptr;
         mbedtls_rsa_free(&rsaCtx);
     }
CheckSignature()
bool application::ImageSignerRsa::CheckSignature (const std::vector< uint8_t > & signature, const std::vector< uint8_t > & image) override virtual
Implements application::ImageSigner.
Definition at line 36 of file ImageSignerRsa.cpp.
References infra::MemoryRange< T >::begin(), CalculateSha256(), RsaPublicKey::E, hash, RsaPublicKey::N, publicKey, signature, and infra::MemoryRange< T >::size().
     {
         std::copy(signature.begin(), signature.end(), this->signature.begin());
         CalculateSha256(image);
         mbedtls_rsa_context rsaCtx;
         mbedtls_rsa_init(&rsaCtx, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
         rsaCtx.len = publicKey.N.size();
         rsaCtx.N.s = 1;
         rsaCtx.N.n = publicKey.N.size();
         rsaCtx.N.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(publicKey.N.begin()));
         rsaCtx.E.s = 1;
         rsaCtx.E.n = publicKey.E.size();
         rsaCtx.E.p = reinterpret_cast<mbedtls_mpi_uint*>(const_cast<uint8_t*>(publicKey.E.begin()));
         mbedtls_rsa_set_padding(&rsaCtx, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
         if (mbedtls_rsa_check_pubkey(&rsaCtx) != 0)
             return false;
         bool success = mbedtls_rsa_rsassa_pss_verify(&rsaCtx, NULL, NULL, MBEDTLS_RSA_PUBLIC, MBEDTLS_MD_SHA256, hash.size(), hash.data(), signature.data()) == 0
             && mbedtls_rsa_self_test(0) == 0;
         rsaCtx.N.p = nullptr;
         rsaCtx.E.p = nullptr;
         rsaCtx.D.p = nullptr;
         rsaCtx.P.p = nullptr;
         rsaCtx.Q.p = nullptr;
         rsaCtx.DP.p = nullptr;
         rsaCtx.DQ.p = nullptr;
         rsaCtx.QP.p = nullptr;
         mbedtls_rsa_free(&rsaCtx);
         return success;
     }
ImageSignature()
std::vector< uint8_t > application::ImageSignerRsa::ImageSignature (const std::vector< uint8_t > & image) override virtual
Implements application::ImageSigner.
Definition at line 28 of file ImageSignerRsa.cpp.
References CalculateSha256(), CalculateSignature(), and signature.
     {
         CalculateSha256(image);
         CalculateSignature(image);
         return std::vector<uint8_t>(signature.begin(), signature.end());
     }
MyRandom()
int application::ImageSignerRsa::MyRandom (void * rng_state, unsigned char * output, size_t len) static private
Definition at line 136 of file ImageSignerRsa.cpp.
References infra::data, application::RandomNumberGenerator::Generate(), and randomNumberGenerator.
Referenced by CalculateSignature().
     {
         std::vector<uint8_t> data = randomNumberGenerator->Generate(len);
         std::copy(data.begin(), data.end(), output);
         return 0;
     }
SignatureLength()
uint16_t application::ImageSignerRsa::SignatureLength () const override virtual
Implements application::ImageSigner.
Definition at line 23 of file ImageSignerRsa.cpp.
References signature.
     {
         return static_cast<uint16_t>(signature.size());
     }
SignatureMethod()
uint16_t application::ImageSignerRsa::SignatureMethod () const override virtual
Implements application::ImageSigner.
Definition at line 18 of file ImageSignerRsa.cpp.
References signatureMethod.
     {
         return signatureMethod;
     }
Member Data Documentation
hash
std::array<uint8_t, 32> application::ImageSignerRsa::hash private
Definition at line 38 of file ImageSignerRsa.hpp.
Referenced by CalculateSha256(), CalculateSignature(), and CheckSignature().
keyFileName
std::string application::ImageSignerRsa::keyFileName private
Definition at line 37 of file ImageSignerRsa.hpp.
keyLength
const size_t application::ImageSignerRsa::keyLength = 1024 static
Definition at line 25 of file ImageSignerRsa.hpp.
privateKey
const RsaPrivateKey& application::ImageSignerRsa::privateKey private
Definition at line 35 of file ImageSignerRsa.hpp.
Referenced by CalculateSignature().
publicKey
const RsaPublicKey& application::ImageSignerRsa::publicKey private
Definition at line 34 of file ImageSignerRsa.hpp.
Referenced by CalculateSignature(), and CheckSignature().
randomNumberGenerator
RandomNumberGenerator * application::ImageSignerRsa::randomNumberGenerator = nullptr static private
Definition at line 36 of file ImageSignerRsa.hpp.
Referenced by ImageSignerRsa(), and MyRandom().
signature
std::array<uint8_t, keyLength / 8> application::ImageSignerRsa::signature private
Definition at line 39 of file ImageSignerRsa.hpp.
Referenced by CalculateSignature(), CheckSignature(), ImageSignature(), and SignatureLength().
signatureMethod
const uint16_t application::ImageSignerRsa::signatureMethod = 1 static
Definition at line 24 of file ImageSignerRsa.hpp.
Referenced by SignatureMethod().
The documentation for this class was generated from the following files:
ImageSignerRsa.hpp
ImageSignerRsa.cpp