EMil: infra::InputStream Class Reference
infra::InputStream Class Reference
#include <InputStream.hpp>
Public Member Functions
InputStream (StreamReader &reader, StreamErrorPolicy &errorPolicy)
bool Empty () const
std::size_t Available () const
ConstByteRange ContiguousRange (std::size_t max=std::numeric_limits< std::size_t >::max()) const
ConstByteRange PeekContiguousRange (std::size_t start=0) const
void Consume (std::size_t amount)
bool Failed () const
StreamReader & Reader () const
StreamErrorPolicy & ErrorPolicy () const
Protected Member Functions
~InputStream ()=default
Private Attributes
StreamReader & reader
StreamErrorPolicy & errorPolicy
Detailed Description
Definition at line 42 of file InputStream.hpp.
Constructor & Destructor Documentation
InputStream()
infra::InputStream::InputStream (StreamReader & reader, StreamErrorPolicy & errorPolicy)
Definition at line 6 of file InputStream.cpp.
         : reader(reader)
         , errorPolicy(errorPolicy)
     {}
~InputStream()
infra::InputStream::~InputStream () protected default
Member Function Documentation
Available()
std::size_t infra::InputStream::Available () const
Definition at line 16 of file InputStream.cpp.
References infra::StreamReader::Available(), and reader.
Referenced by services::HttpServerConnectionObserver::DataReceived(), infra::ProtoLengthDelimited::GetBytes(), infra::ProtoLengthDelimited::GetString(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpClientImpl::HttpResponseParser::ParseStatusLine(), and infra::ProtoLengthDelimited::ProtoLengthDelimited().
     {
         return reader.Available();
     }
Consume()
void infra::InputStream::Consume (std::size_t amount)
Definition at line 31 of file InputStream.cpp.
     {
         while (amount > 0)
         {
             auto reduced = reader.ExtractContiguousRange(amount).size();
             amount -= reduced;
             if (reduced == 0)
             {
                 errorPolicy.ReportResult(false);
                 return;
             }
         }
         errorPolicy.ReportResult(true);
     }
ContiguousRange()
ConstByteRange infra::InputStream::ContiguousRange (std::size_t max = std::numeric_limits<std::size_t>::max()) const
Definition at line 21 of file InputStream.cpp.
References infra::StreamReader::ExtractContiguousRange(), and reader.
Referenced by services::HttpClientJson::BodyAvailable(), application::TracingHttpClient::BodyAvailable(), services::TracingHttpClientImpl::DataReceived(), services::HttpServerConnectionObserver::ReceivedTooMuchData(), services::StreamEchoConnection::SendStreamAvailable(), infra::ProtoLengthDelimited::SkipEverything(), and services::ConnectionMbedTls::SslReceive().
     {
         return reader.ExtractContiguousRange(max);
     }
Empty()
bool infra::InputStream::Empty () const
Definition at line 11 of file InputStream.cpp.
References infra::StreamReader::Empty(), and reader.
Referenced by services::HttpClientJson::BodyAvailable(), application::TracingHttpClient::BodyAvailable(), services::TracingHttpClientImpl::DataReceived(), infra::ProtoParser::Empty(), application::BinaryObject::LineContents::LineContents(), infra::operator>>(), services::HttpClientImpl::HttpResponseParser::ParseHeaders(), services::HttpServerConnectionObserver::ReceivedTooMuchData(), and infra::ProtoLengthDelimited::SkipEverything().
     {
         return reader.Empty();
     }
ErrorPolicy()
StreamErrorPolicy & infra::InputStream::ErrorPolicy () const
Definition at line 57 of file InputStream.cpp.
References errorPolicy.
Referenced by infra::DataInputStream::operator>>(), infra::TextInputStream::operator>>(), infra::operator>>(), infra::ProtoLengthDelimited::ProtoLengthDelimited(), infra::TextInputStream::ReadAsDecimal(), infra::TextInputStream::ReadAsHex(), and infra::TextInputStream::SkipSpaces().
     {
         return errorPolicy;
     }
Failed()
bool infra::InputStream::Failed () const
Definition at line 47 of file InputStream.cpp.
References errorPolicy, and infra::StreamErrorPolicy::Failed().
Referenced by services::LlmnrResponder::DataReceived(), services::SntpClient::DataReceived(), services::MqttClientImpl::StateConnecting::DataReceived(), services::MqttClientImpl::StateConnected::DataReceived(), services::TimeWithLocalization::DurationFromString(), infra::ProtoParser::GetField(), infra::ProtoParser::GetVarInt(), application::BinaryObject::LineContents::LineContents(), and services::TimeWithLocalization::TimePointFromString().
     {
         return errorPolicy.Failed();
     }
PeekContiguousRange()
ConstByteRange infra::InputStream::PeekContiguousRange (std::size_t start = 0) const
Definition at line 26 of file InputStream.cpp.
References infra::StreamReader::PeekContiguousRange(), and reader.
     {
         return reader.PeekContiguousRange(start);
     }
Reader()
StreamReader & infra::InputStream::Reader () const
Definition at line 52 of file InputStream.cpp.
References reader.
Referenced by infra::DataInputStream::operator>>(), infra::TextInputStream::operator>>(), infra::TextInputStream::ReadAsDecimal(), infra::TextInputStream::ReadAsHex(), and infra::TextInputStream::SkipSpaces().
     {
         return reader;
     }
Member Data Documentation
errorPolicy
StreamErrorPolicy& infra::InputStream::errorPolicy private
Definition at line 63 of file InputStream.hpp.
Referenced by ErrorPolicy(), and Failed().
reader
StreamReader& infra::InputStream::reader private
Definition at line 62 of file InputStream.hpp.
Referenced by Available(), ContiguousRange(), Empty(), infra::TextInputStream::operator>>(), PeekContiguousRange(), and Reader().
The documentation for this class was generated from the following files:
InputStream.hpp
InputStream.cpp