EMil: infra::Timer Class Reference
infra::Timer Class Reference abstract
#include <Timer.hpp>
Public Member Functions
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
virtual const infra::Function< void()> & Action () const
virtual void ComputeNextTriggerTime ()=0
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Types
using UnalignedTimePoint = std::array< uint32_t, 2 >
Private Member Functions
void RegisterSelf ()
void UnregisterSelf (TimePoint oldTriggerTime)
void UpdateTriggerTime (TimePoint oldTriggerTime)
UnalignedTimePoint Convert (TimePoint point) const
TimePoint Convert (UnalignedTimePoint point) const
Private Attributes
TimerService & timerService
infra::Function< void()> action
UnalignedTimePoint nextTriggerTime = Convert(TimePoint())
Detailed Description
Definition at line 35 of file Timer.hpp.
Member Typedef Documentation
UnalignedTimePoint
using infra::Timer::UnalignedTimePoint = std::array<uint32_t, 2> private
Definition at line 63 of file Timer.hpp.
Constructor & Destructor Documentation
Timer() [1/2]
infra::Timer::Timer (uint32_t timerServiceId) explicit protected
Definition at line 12 of file Timer.cpp.
         : timerService(TimerServiceManager::Instance().GetTimerService(timerServiceId))
     {}
Timer() [2/2]
infra::Timer::Timer (const Timer &) protected delete
~Timer()
infra::Timer::~Timer () protected
Definition at line 16 of file Timer.cpp.
References Cancel().
     {
         Cancel();
     }
Member Function Documentation
Action()
const infra::Function< void()> & infra::Timer::Action () const virtual
Reimplemented in infra::TimerAlternating, and infra::TimerLimitedRepeatingWithClosingAction.
Definition at line 40 of file Timer.cpp.
References action.
Referenced by infra::TimerEvolving::ComputeNextTriggerTime(), and infra::TimerRepeating::ComputeNextTriggerTime().
     {
         return action;
     }
Armed()
bool infra::Timer::Armed () const
Definition at line 30 of file Timer.cpp.
References action.
Referenced by services::DebouncedButton::ButtonPressed(), services::RepeatingButton::ButtonPressed(), services::DebouncedButton::ButtonReleased(), and services::RepeatingButton::ButtonReleased().
     {
         return action != nullptr;
     }
Cancel()
void infra::Timer::Cancel ()
Definition at line 21 of file Timer.cpp.
References action, Convert(), nextTriggerTime, and UnregisterSelf().
Referenced by services::HttpClientBasic::BodyComplete(), services::RepeatingButton::ButtonReleased(), services::HttpClientBasic::Close(), infra::TimerLimitedRepeating::ComputeNextTriggerTime(), infra::TimerLimitedRepeatingWithClosingAction::ComputeNextTriggerTime(), infra::TimerSingleShot::ComputeNextTriggerTime(), services::RepeatingButton::DebounceEnd(), infra::TimerEvolving::Evolve(), infra::ScalableDerivedTimerService::NextTriggerChanged(), infra::DerivedTimerService::NextTriggerChanged(), services::HttpClientBasic::ReportError(), services::HttpServerConnectionObserver::RequestIsNowInProgress(), and ~Timer().
     {
         if (action)
             UnregisterSelf(Convert(nextTriggerTime));
         nextTriggerTime = Convert(TimePoint());
         action = nullptr;
     }
ComputeNextTriggerTime()
virtual void infra::Timer::ComputeNextTriggerTime () pure virtual
Implemented in infra::TimerRepeating, infra::TimerSingleShot, services::RepeatingButton::FireTimer, infra::TimerAlternating, infra::TimerLimitedRepeatingWithClosingAction, infra::TimerEvolving, and infra::TimerLimitedRepeating.
Convert() [1/2]
Timer::UnalignedTimePoint infra::Timer::Convert (TimePoint point) const private
Definition at line 60 of file Timer.cpp.
Referenced by Cancel(), NextTrigger(), and SetNextTriggerTime().
     {
         UnalignedTimePoint result;
         std::copy(reinterpret_cast<const uint32_t*>(&point), reinterpret_cast<const uint32_t*>(&point + 1), result.begin());
         return result;
     }
Convert() [2/2]
TimePoint infra::Timer::Convert (UnalignedTimePoint point) const private
Definition at line 67 of file Timer.cpp.
     {
         TimePoint result;
         std::copy(point.begin(), point.end(), reinterpret_cast<uint32_t*>(&result));
         return result;
     }
NextTrigger()
TimePoint infra::Timer::NextTrigger () const
Definition at line 35 of file Timer.cpp.
References Convert(), and nextTriggerTime.
Referenced by infra::TimerRepeating::ComputeNextTriggerTime(), and infra::TimerService::RegisterTimer().
     {
         return Convert(nextTriggerTime);
     }
Now()
TimePoint infra::Timer::Now () const protected
Definition at line 89 of file Timer.cpp.
References infra::TimerService::Now(), and timerService.
Referenced by infra::TimerLimitedRepeating::ComputeNextTriggerTime(), infra::TimerLimitedRepeatingWithClosingAction::ComputeNextTriggerTime(), infra::TimerRepeating::ComputeNextTriggerTime(), infra::TimerLimitedRepeating::Start(), infra::TimerEvolving::Start(), infra::TimerAlternating::Start(), infra::TimerLimitedRepeatingWithClosingAction::Start(), infra::TimerSingleShot::Start(), and infra::TimerRepeating::Start().
     {
         return timerService.Now();
     }
operator=()
Timer& infra::Timer::operator= (const Timer &) protected delete
RegisterSelf()
void infra::Timer::RegisterSelf () private
Definition at line 45 of file Timer.cpp.
References infra::TimerService::RegisterTimer(), and timerService.
Referenced by SetNextTriggerTime().
     {
         timerService.RegisterTimer(*this);
     }
Resolution()
Duration infra::Timer::Resolution () const protected
Definition at line 94 of file Timer.cpp.
References infra::TimerService::Resolution(), and timerService.
Referenced by infra::TimerLimitedRepeating::Start(), infra::TimerEvolving::Start(), infra::TimerAlternating::Start(), infra::TimerLimitedRepeatingWithClosingAction::Start(), infra::TimerSingleShot::Start(), and infra::TimerRepeating::Start().
     {
         return timerService.Resolution();
     }
SetNextTriggerTime()
void infra::Timer::SetNextTriggerTime (TimePoint time, const infra::Function< void()> & action) protected
Definition at line 74 of file Timer.cpp.
References action, Convert(), nextTriggerTime, RegisterSelf(), and UpdateTriggerTime().
Referenced by infra::TimerLimitedRepeating::ComputeNextTriggerTime(), infra::TimerLimitedRepeatingWithClosingAction::ComputeNextTriggerTime(), infra::TimerAlternating::ComputeNextTriggerTime(), infra::TimerRepeating::ComputeNextTriggerTime(), infra::TimerEvolving::Evolve(), infra::TimerSingleShot::Start(), and infra::TimerRepeating::Start().
     {
         assert(action);
         TimePoint oldTriggerTime = Convert(nextTriggerTime);
         nextTriggerTime = Convert(time);
         if (!this->action)
             RegisterSelf();
         else
             UpdateTriggerTime(oldTriggerTime);
         this->action = action;
     }
UnregisterSelf()
void infra::Timer::UnregisterSelf (TimePoint oldTriggerTime) private
Definition at line 50 of file Timer.cpp.
References timerService, and infra::TimerService::UnregisterTimer().
Referenced by Cancel().
     {
         timerService.UnregisterTimer(*this, oldTriggerTime);
     }
UpdateTriggerTime()
void infra::Timer::UpdateTriggerTime (TimePoint oldTriggerTime) private
Definition at line 55 of file Timer.cpp.
References timerService, and infra::TimerService::UpdateTriggerTime().
Referenced by SetNextTriggerTime().
     {
         timerService.UpdateTriggerTime(*this, oldTriggerTime);
     }
Member Data Documentation
action
infra::Function<void()> infra::Timer::action private
Definition at line 70 of file Timer.hpp.
Referenced by Action(), Armed(), Cancel(), infra::TimerEvolving::Evolve(), SetNextTriggerTime(), infra::TimerEvolving::Start(), infra::TimerSingleShot::Start(), infra::TimerRepeating::Start(), and infra::TimerEvolving::TimerEvolving().
nextTriggerTime
UnalignedTimePoint infra::Timer::nextTriggerTime = Convert(TimePoint()) private
Definition at line 71 of file Timer.hpp.
Referenced by Cancel(), NextTrigger(), and SetNextTriggerTime().
timerService
TimerService& infra::Timer::timerService private
Definition at line 69 of file Timer.hpp.
Referenced by Now(), RegisterSelf(), Resolution(), UnregisterSelf(), and UpdateTriggerTime().
The documentation for this class was generated from the following files:
Timer.hpp
Timer.cpp