EMil: TestTracer.cpp File Reference
TestTracer.cpp File Reference
Classes
class TracerTestImpl
Functions
TEST (TracerTest, trace_inserts_header)
TEST (TracerTest, trace_streams_text)
TEST (GlobalTracerTest, global_tracer_streams_text)
Function Documentation
TEST() [1/3]
TEST (TracerTest , trace_inserts_header)
Definition at line 17 of file TestTracer.cpp.
 {
     infra::StringOutputStream::WithStorage<32> stream;
     testing::StrictMock<TracerTestImpl> tracer(stream);
     EXPECT_CALL(tracer, InsertHeader());
     tracer.Trace();
 }
TEST() [2/3]
TEST (TracerTest , trace_streams_text)
Definition at line 26 of file TestTracer.cpp.
References EXPECT_EQ(), and infra::WithStorage< Base, StorageType >::Storage().
 {
     infra::StringOutputStream::WithStorage<32> stream;
     testing::StrictMock<TracerTestImpl> tracer(stream);
     EXPECT_CALL(tracer, InsertHeader());
     tracer.Trace() << "Text";
     EXPECT_EQ("\r\nText", stream.Storage());
 }
TEST() [3/3]
TEST (GlobalTracerTest , global_tracer_streams_text)
Definition at line 37 of file TestTracer.cpp.
References EXPECT_EQ(), services::GlobalTracer(), services::SetGlobalTracerInstance(), infra::WithStorage< Base, StorageType >::Storage(), and services::Tracer::Trace().
 {
     infra::StringOutputStream::WithStorage<32> stream;
     testing::StrictMock<TracerTestImpl> tracer(stream);
     services::SetGlobalTracerInstance(tracer);
     EXPECT_CALL(tracer, InsertHeader());
     services::GlobalTracer().Trace() << "Text";
     EXPECT_EQ("\r\nText", stream.Storage());
 }