EMil: TestIntrusiveList.cpp File Reference
TestIntrusiveList.cpp File Reference
Classes
struct ListInt
Functions
TEST (IntrusiveListTest, TestConstructedEmpty)
TEST (IntrusiveListTest, TestConstructionWithRange)
TEST (IntrusiveListTest, TestMoveConstruction)
TEST (IntrusiveListTest, TestMoveAssignment)
TEST (IntrusiveListTest, TestMoveAssignmentFromEmptyList)
TEST (IntrusiveListTest, IterateAfterMoveAssignment)
TEST (IntrusiveListTest, TestBeginAndEnd)
TEST (IntrusiveListTest, TestFront)
TEST (IntrusiveListTest, TestBack)
TEST (IntrusiveListTest, TestNotHasElement)
TEST (IntrusiveListTest, TestHasElement)
TEST (IntrusiveListTest, TestAssignRange)
TEST (IntrusiveListTest, TestAssignN)
TEST (IntrusiveListTest, TestPushFront)
TEST (IntrusiveListTest, TestPopFront)
TEST (IntrusiveListTest, TestPushBack)
TEST (IntrusiveListTest, TestPopBack)
TEST (IntrusiveListTest, TestSwap)
TEST (IntrusiveListTest, TestSwapDifferentSizes)
TEST (IntrusiveListTest, TestClear)
TEST (IntrusiveListTest, TestInsert)
TEST (IntrusiveListTest, TestErase)
TEST (IntrusiveListTest, TestDoubleErase)
TEST (IntrusiveListTest, TestEquals)
TEST (IntrusiveListTest, TestUnequals)
TEST (IntrusiveListTest, TestLessThan)
TEST (IntrusiveListTest, TestGreaterThan)
TEST (IntrusiveListTest, TestLessThanOrEqual)
TEST (IntrusiveListTest, TestGreaterThanOrEqual)
Function Documentation
TEST() [1/29]
TEST (IntrusiveListTest , TestConstructedEmpty)
Definition at line 26 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::IntrusiveList< T >::size().
 {
     infra::IntrusiveList<ListInt> list;
     EXPECT_TRUE(list.empty());
     EXPECT_EQ(0, list.size());
 }
TEST() [2/29]
TEST (IntrusiveListTest , TestConstructionWithRange)
Definition at line 34 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::begin(), EXPECT_EQ(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(ListInt(0), *list.begin());
     EXPECT_EQ(ListInt(1), *std::next(list.begin()));
     EXPECT_EQ(ListInt(2), *std::next(list.begin(), 2));
 }
TEST() [3/29]
TEST (IntrusiveListTest , TestMoveConstruction)
Definition at line 46 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::back(), infra::IntrusiveList< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveList< T >::front(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> original(range, range + 3);
     infra::IntrusiveList<ListInt> copy(std::move(original));
     EXPECT_EQ(3, copy.size());
     EXPECT_EQ(ListInt(0), copy.front());
     EXPECT_EQ(ListInt(2), copy.back());
     EXPECT_TRUE(original.empty());
 }
TEST() [4/29]
TEST (IntrusiveListTest , TestMoveAssignment)
Definition at line 58 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::back(), infra::IntrusiveList< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), infra::IntrusiveList< T >::front(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> original(range, range + 3);
     infra::IntrusiveList<ListInt> copy;
     copy = std::move(original);
     EXPECT_EQ(3, copy.size());
     EXPECT_EQ(ListInt(0), copy.front());
     EXPECT_EQ(ListInt(2), copy.back());
     EXPECT_TRUE(original.empty());
 }
TEST() [5/29]
TEST (IntrusiveListTest , TestMoveAssignmentFromEmptyList)
Definition at line 71 of file TestIntrusiveList.cpp.
References EXPECT_EQ(), and infra::IntrusiveList< T >::size().
 {
     infra::IntrusiveList<ListInt> original;
     infra::IntrusiveList<ListInt> copy;
     copy = std::move(original);
     EXPECT_EQ(0, copy.size());
 }
TEST() [6/29]
TEST (IntrusiveListTest , IterateAfterMoveAssignment)
Definition at line 80 of file TestIntrusiveList.cpp.
References infra::MakeReverseRange().
 {
     ListInt range[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> original(range, range + 3);
     infra::IntrusiveList<ListInt> copy;
     copy = std::move(original);
     for (ListInt& i: copy)
     {}
     for (ListInt& i: MakeReverseRange(copy))
     {}
 }
TEST() [7/29]
TEST (IntrusiveListTest , TestBeginAndEnd)
Definition at line 94 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::begin(), infra::IntrusiveList< T >::cbegin(), infra::IntrusiveList< T >::cend(), infra::IntrusiveList< T >::end(), and EXPECT_EQ().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     EXPECT_EQ(list.end(), std::next(list.begin(), 3));
     EXPECT_EQ(list.cbegin(), list.begin());
     EXPECT_EQ(list.cend(), list.end());
     EXPECT_EQ(ListInt(0), *list.begin());
 }
TEST() [8/29]
TEST (IntrusiveListTest , TestFront)
Definition at line 106 of file TestIntrusiveList.cpp.
References EXPECT_EQ(), and infra::IntrusiveList< T >::front().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     EXPECT_EQ(ListInt(0), list.front());
 }
TEST() [9/29]
TEST (IntrusiveListTest , TestBack)
Definition at line 114 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::back(), and EXPECT_EQ().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     EXPECT_EQ(ListInt(2), list.back());
 }
TEST() [10/29]
TEST (IntrusiveListTest , TestNotHasElement)
Definition at line 122 of file TestIntrusiveList.cpp.
References EXPECT_FALSE(), and infra::IntrusiveList< T >::has_element().
 {
     infra::IntrusiveList<ListInt> list;
     ListInt x(3);
     EXPECT_FALSE(list.has_element(x));
 }
TEST() [11/29]
TEST (IntrusiveListTest , TestHasElement)
Definition at line 130 of file TestIntrusiveList.cpp.
References EXPECT_TRUE(), infra::IntrusiveList< T >::has_element(), and infra::IntrusiveList< T >::push_back().
 {
     infra::IntrusiveList<ListInt> list;
     ListInt x(3);
     list.push_back(x);
     EXPECT_TRUE(list.has_element(x));
 }
TEST() [12/29]
TEST (IntrusiveListTest , TestAssignRange)
Definition at line 139 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::assign(), infra::IntrusiveList< T >::begin(), EXPECT_EQ(), infra::IntrusiveList< T >::front(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     ListInt otherRange[2] = { 4, 5 };
     list.assign(otherRange, otherRange + 2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(ListInt(4), list.front());
     EXPECT_EQ(ListInt(5), *std::next(list.begin()));
 }
TEST() [13/29]
TEST (IntrusiveListTest , TestAssignN)
Definition at line 152 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::assign(), infra::IntrusiveList< T >::back(), EXPECT_EQ(), infra::IntrusiveList< T >::front(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list(range, range + 3);
     ListInt range2[2] = { 3, 4 };
     list.assign(range2, range2 + 2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(ListInt(3), list.front());
     EXPECT_EQ(ListInt(4), list.back());
 }
TEST() [14/29]
TEST (IntrusiveListTest , TestPushFront)
Definition at line 165 of file TestIntrusiveList.cpp.
References EXPECT_EQ(), infra::IntrusiveList< T >::front(), infra::IntrusiveList< T >::push_front(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     ListInt i1(1);
     list.push_front(i1);
     EXPECT_EQ(4, list.size());
     EXPECT_EQ(i1, list.front());
 }
TEST() [15/29]
TEST (IntrusiveListTest , TestPopFront)
Definition at line 176 of file TestIntrusiveList.cpp.
References EXPECT_EQ(), infra::IntrusiveList< T >::front(), infra::IntrusiveList< T >::pop_front(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     list.pop_front();
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(ListInt(1), list.front());
 }
TEST() [16/29]
TEST (IntrusiveListTest , TestPushBack)
Definition at line 186 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::back(), EXPECT_EQ(), infra::IntrusiveList< T >::push_back(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     ListInt i1(1);
     list.push_back(i1);
     EXPECT_EQ(4, list.size());
     EXPECT_EQ(i1, list.back());
 }
TEST() [17/29]
TEST (IntrusiveListTest , TestPopBack)
Definition at line 197 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::back(), EXPECT_EQ(), infra::IntrusiveList< T >::pop_back(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     list.pop_back();
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(ListInt(1), list.back());
 }
TEST() [18/29]
TEST (IntrusiveListTest , TestSwap)
Definition at line 207 of file TestIntrusiveList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     ListInt range1[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     ListInt range2[3] = { 3, 4, 5};
     infra::IntrusiveList<ListInt> list2(range2, range2 + 3);
     swap(list1, list2);
     ListInt range1Copy[3] = { 0, 1, 2};
     ListInt range2Copy[3] = { 3, 4, 5};
     infra::IntrusiveList<ListInt> expectedList1(range2Copy, range2Copy + 3);
     infra::IntrusiveList<ListInt> expectedList2(range1Copy, range1Copy + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [19/29]
TEST (IntrusiveListTest , TestSwapDifferentSizes)
Definition at line 224 of file TestIntrusiveList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     ListInt range1[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     ListInt range2[2] = { 3, 4};
     infra::IntrusiveList<ListInt> list2(range2, range2 + 2);
     swap(list1, list2);
     ListInt range1Copy[3] = { 0, 1, 2};
     ListInt range2Copy[2] = { 3, 4};
     infra::IntrusiveList<ListInt> expectedList1(range2Copy, range2Copy + 2);
     infra::IntrusiveList<ListInt> expectedList2(range1Copy, range1Copy + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [20/29]
TEST (IntrusiveListTest , TestClear)
Definition at line 241 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::clear(), infra::IntrusiveList< T >::empty(), EXPECT_EQ(), EXPECT_TRUE(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     list.clear();
     EXPECT_EQ(0, list.size());
     EXPECT_TRUE(list.empty());
     infra::IntrusiveList<ListInt> expectedList;
     EXPECT_EQ(expectedList, list);
 }
TEST() [21/29]
TEST (IntrusiveListTest , TestInsert)
Definition at line 254 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::begin(), EXPECT_EQ(), infra::IntrusiveList< T >::insert(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     ListInt i2(2);
     list.insert(std::next(list.begin()), i2);
     EXPECT_EQ(4, list.size());
     EXPECT_EQ(ListInt(2), *std::next(list.begin()));
 }
TEST() [22/29]
TEST (IntrusiveListTest , TestErase)
Definition at line 265 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::begin(), infra::IntrusiveList< T >::erase(), EXPECT_EQ(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     list.erase(range[1]);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(ListInt(2), *std::next(list.begin()));
 }
TEST() [23/29]
TEST (IntrusiveListTest , TestDoubleErase)
Definition at line 275 of file TestIntrusiveList.cpp.
References infra::IntrusiveList< T >::begin(), infra::IntrusiveList< T >::erase(), EXPECT_EQ(), and infra::IntrusiveList< T >::size().
 {
     ListInt range[3] = { 0, 1, 2};
     infra::IntrusiveList<ListInt> list(range, range + 3);
     list.erase(range[1]);
     list.erase(range[1]);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(ListInt(2), *std::next(list.begin()));
 }
TEST() [24/29]
TEST (IntrusiveListTest , TestEquals)
Definition at line 286 of file TestIntrusiveList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     ListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     ListInt range2[3] = { 3, 4, 5 };
     infra::IntrusiveList<ListInt> list2(range2, range2 + 3);
     ListInt range3[2] = { 0, 1 };
     infra::IntrusiveList<ListInt> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 == list1);
     EXPECT_FALSE(list1 == list2);
     EXPECT_FALSE(list1 == deque3);
     EXPECT_FALSE(deque3 == list1);
 }
TEST() [25/29]
TEST (IntrusiveListTest , TestUnequals)
Definition at line 301 of file TestIntrusiveList.cpp.
References EXPECT_FALSE().
 {
     ListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 != list1);
 }
TEST() [26/29]
TEST (IntrusiveListTest , TestLessThan)
Definition at line 309 of file TestIntrusiveList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     ListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     ListInt range2[3] = { 0, 4, 5 };
     infra::IntrusiveList<ListInt> list2(range2, range2 + 3);
     ListInt range3[2] = { 0, 1 };
     infra::IntrusiveList<ListInt> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 < list2);
     EXPECT_FALSE(list1 < deque3);
     EXPECT_FALSE(list1 < list1);
 }
TEST() [27/29]
TEST (IntrusiveListTest , TestGreaterThan)
Definition at line 323 of file TestIntrusiveList.cpp.
References EXPECT_FALSE().
 {
     ListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 > list1);
 }
TEST() [28/29]
TEST (IntrusiveListTest , TestLessThanOrEqual)
Definition at line 331 of file TestIntrusiveList.cpp.
References EXPECT_TRUE().
 {
     ListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 <= list1);
 }
TEST() [29/29]
TEST (IntrusiveListTest , TestGreaterThanOrEqual)
Definition at line 339 of file TestIntrusiveList.cpp.
References EXPECT_TRUE().
 {
     ListInt range1[3] = { 0, 1, 2 };
     infra::IntrusiveList<ListInt> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 >= list1);
 }