EMil: application::ImageSigner Class Reference
application::ImageSigner Class Reference abstract
#include <ImageSigner.hpp>
Public Member Functions
virtual uint16_t SignatureMethod () const =0
virtual uint16_t SignatureLength () const =0
virtual std::vector< uint8_t > ImageSignature (const std::vector< uint8_t > &image)=0
virtual bool CheckSignature (const std::vector< uint8_t > &signature, const std::vector< uint8_t > &image)=0
Protected Member Functions
~ImageSigner ()=default
Detailed Description
Definition at line 9 of file ImageSigner.hpp.
Constructor & Destructor Documentation
~ImageSigner()
application::ImageSigner::~ImageSigner () protected default
Member Function Documentation
CheckSignature()
virtual bool application::ImageSigner::CheckSignature (const std::vector< uint8_t > & signature, const std::vector< uint8_t > & image) pure virtual
Implemented in application::ImageSignerEcDsa, and application::ImageSignerRsa.
Referenced by application::UpgradePackBuilder::CheckSignature().
ImageSignature()
virtual std::vector<uint8_t> application::ImageSigner::ImageSignature (const std::vector< uint8_t > & image) pure virtual
Implemented in application::ImageSignerEcDsa, and application::ImageSignerRsa.
Referenced by application::UpgradePackBuilder::AddPrologueAndSignature().
SignatureLength()
virtual uint16_t application::ImageSigner::SignatureLength () const pure virtual
Implemented in application::ImageSignerEcDsa, and application::ImageSignerRsa.
Referenced by application::UpgradePackBuilder::AddEpilogue(), application::UpgradePackBuilder::CheckSignature(), and application::ReferenceUpgradePackBuilderFacade::PostBuilder().
SignatureMethod()
virtual uint16_t application::ImageSigner::SignatureMethod () const pure virtual
Implemented in application::ImageSignerEcDsa, and application::ImageSignerRsa.
Referenced by application::UpgradePackBuilder::AddPrologueAndSignature().
The documentation for this class was generated from the following file:
ImageSigner.hpp