EMil: TestProtoFormatter.cpp File Reference
TestProtoFormatter.cpp File Reference
Functions
TEST (ProtoFormatterTest, PutVarInt_as_single_byte)
TEST (ProtoFormatterTest, PutVarInt_as_multiple_bytes)
TEST (ProtoFormatterTest, negative_int_encodes_as_10_bytes)
TEST (ProtoFormatterTest, negative_signed_int_encodes_as_1_byte)
TEST (ProtoFormatterTest, PutFixed32)
TEST (ProtoFormatterTest, PutFixed64)
TEST (ProtoFormatterTest, PutStringField)
TEST (ProtoFormatterTest, PutBytesField)
TEST (ProtoFormatterTest, PutSubObject)
Function Documentation
TEST() [1/9]
TEST (ProtoFormatterTest , PutVarInt_as_single_byte)
Definition at line 5 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutVarIntField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutVarIntField(2, 4);
     EXPECT_EQ((std::array<uint8_t, 2>{ 4 << 3, 2 }), stream.Writer().Processed());
 }
TEST() [2/9]
TEST (ProtoFormatterTest , PutVarInt_as_multiple_bytes)
Definition at line 14 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutVarIntField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutVarIntField(389, 4);
     EXPECT_EQ((std::array<uint8_t, 3>{ 4 << 3, 0x85, 3 }), stream.Writer().Processed());
 }
TEST() [3/9]
TEST (ProtoFormatterTest , negative_int_encodes_as_10_bytes)
Definition at line 23 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutVarIntField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutVarIntField(-1, 4);
     EXPECT_EQ((std::array<uint8_t, 11>{ 4 << 3, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 1 }), stream.Writer().Processed());
 }
TEST() [4/9]
TEST (ProtoFormatterTest , negative_signed_int_encodes_as_1_byte)
Definition at line 32 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutSignedVarIntField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutSignedVarIntField(-1, 4);
     EXPECT_EQ((std::array<uint8_t, 2>{ 4 << 3, 1 }), stream.Writer().Processed());
 }
TEST() [5/9]
TEST (ProtoFormatterTest , PutFixed32)
Definition at line 41 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutFixed32Field().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutFixed32Field(2, 4);
     EXPECT_EQ((std::array<uint8_t, 5>{ 4 << 3 | 5, 2, 0, 0, 0 }), stream.Writer().Processed());
 }
TEST() [6/9]
TEST (ProtoFormatterTest , PutFixed64)
Definition at line 50 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutFixed64Field().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutFixed64Field(2, 4);
     EXPECT_EQ((std::array<uint8_t, 9>{ 4 << 3 | 1, 2, 0, 0, 0, 0, 0, 0, 0 }), stream.Writer().Processed());
 }
TEST() [7/9]
TEST (ProtoFormatterTest , PutStringField)
Definition at line 59 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), and infra::ProtoFormatter::PutStringField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     formatter.PutStringField("a", 4);
     EXPECT_EQ((std::array<uint8_t, 3>{ 4 << 3 | 2, 1, 'a' }), stream.Writer().Processed());
 }
TEST() [8/9]
TEST (ProtoFormatterTest , PutBytesField)
Definition at line 68 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), infra::MakeRange(), and infra::ProtoFormatter::PutBytesField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     infra::BoundedVector<uint8_t>::WithMaxSize<10> bytes;
     bytes.push_back(5);
     formatter.PutBytesField(infra::MakeRange(bytes), 4);
     EXPECT_EQ((std::array<uint8_t, 3>{ 4 << 3 | 2, 1, 5 }), stream.Writer().Processed());
 }
TEST() [9/9]
TEST (ProtoFormatterTest , PutSubObject)
Definition at line 79 of file TestProtoFormatter.cpp.
References EXPECT_EQ(), infra::ProtoFormatter::LengthDelimitedFormatter(), and infra::ProtoFormatter::PutVarIntField().
 {
     infra::ByteOutputStream::WithStorage<20> stream;
     infra::ProtoFormatter formatter(stream);
     {
         infra::ProtoLengthDelimitedFormatter subObjectFormatter = formatter.LengthDelimitedFormatter(4);
         formatter.PutVarIntField(2, 4);
     }
     EXPECT_EQ((std::array<uint8_t, 4>{ 4 << 3 | 2, 2, 4 << 3, 2 }), stream.Writer().Processed());
 }