EMil: infra::IntrusiveList< T > Class Template Reference
infra::IntrusiveList< T > Class Template Reference
#include <IntrusiveList.hpp>
Public Types
typedef detail::IntrusiveListNode< T > NodeType
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef detail::IntrusiveListIterator< T > iterator
typedef detail::IntrusiveListIterator< const T > const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
IntrusiveList ()
template<class InputIterator >
IntrusiveList (InputIterator first, InputIterator last)
IntrusiveList (const IntrusiveList &)=delete
IntrusiveList (IntrusiveList &&other)
IntrusiveList & operator= (const IntrusiveList &)=delete
IntrusiveList & operator= (IntrusiveList &&other)
~IntrusiveList ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
size_type size () const
bool empty () const
bool has_element (const_reference value) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void push_front (const_reference value)
void push_back (const_reference value)
void pop_front ()
void pop_back ()
void insert (const_iterator position, const_reference value)
void erase (const_reference value)
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void swap (IntrusiveList &other)
void clear ()
bool operator== (const IntrusiveList &other) const
bool operator!= (const IntrusiveList &other) const
bool operator< (const IntrusiveList &other) const
bool operator<= (const IntrusiveList &other) const
bool operator> (const IntrusiveList &other) const
bool operator>= (const IntrusiveList &other) const
Private Attributes
size_type numberOfElements
NodeType * beginNode
NodeType endNode
Detailed Description
template<class T>
class infra::IntrusiveList< T >
Definition at line 12 of file IntrusiveList.hpp.
Member Typedef Documentation
const_iterator
template<class T> typedef detail::IntrusiveListIterator<const T> infra::IntrusiveList< T >::const_iterator
Definition at line 52 of file IntrusiveList.hpp.
const_pointer
template<class T> typedef const T* infra::IntrusiveList< T >::const_pointer
Definition at line 50 of file IntrusiveList.hpp.
const_reference
template<class T> typedef const T& infra::IntrusiveList< T >::const_reference
Definition at line 48 of file IntrusiveList.hpp.
const_reverse_iterator
template<class T> typedef std::reverse_iterator<const_iterator> infra::IntrusiveList< T >::const_reverse_iterator
Definition at line 54 of file IntrusiveList.hpp.
difference_type
template<class T> typedef std::iterator_traits<iterator>::difference_type infra::IntrusiveList< T >::difference_type
Definition at line 55 of file IntrusiveList.hpp.
iterator
template<class T> typedef detail::IntrusiveListIterator<T> infra::IntrusiveList< T >::iterator
Definition at line 51 of file IntrusiveList.hpp.
NodeType
template<class T> typedef detail::IntrusiveListNode<T> infra::IntrusiveList< T >::NodeType
Definition at line 44 of file IntrusiveList.hpp.
pointer
template<class T> typedef T* infra::IntrusiveList< T >::pointer
Definition at line 49 of file IntrusiveList.hpp.
reference
template<class T> typedef T& infra::IntrusiveList< T >::reference
Definition at line 47 of file IntrusiveList.hpp.
reverse_iterator
template<class T> typedef std::reverse_iterator<iterator> infra::IntrusiveList< T >::reverse_iterator
Definition at line 53 of file IntrusiveList.hpp.
size_type
template<class T> typedef std::size_t infra::IntrusiveList< T >::size_type
Definition at line 56 of file IntrusiveList.hpp.
value_type
template<class T> typedef T infra::IntrusiveList< T >::value_type
Definition at line 46 of file IntrusiveList.hpp.
Constructor & Destructor Documentation
IntrusiveList() [1/4]
template<class T > infra::IntrusiveList< T >::IntrusiveList ()
Definition at line 170 of file IntrusiveList.hpp.
         : numberOfElements(0)
         , beginNode(&endNode)
     {}
IntrusiveList() [2/4]
template<class T > template<class InputIterator > infra::IntrusiveList< T >::IntrusiveList (InputIterator first, InputIterator last)
Definition at line 177 of file IntrusiveList.hpp.
         : numberOfElements(0)
         , beginNode(&endNode)
     {
         assign(first, last);
     }
IntrusiveList() [3/4]
template<class T> infra::IntrusiveList< T >::IntrusiveList (const IntrusiveList< T > &) delete
IntrusiveList() [4/4]
template<class T > infra::IntrusiveList< T >::IntrusiveList (IntrusiveList< T > && other)
Definition at line 185 of file IntrusiveList.hpp.
         : numberOfElements(0)
         , beginNode(&endNode)
     {
         *this = std::move(other);
     }
~IntrusiveList()
template<class T > infra::IntrusiveList< T >::~IntrusiveList ()
Definition at line 210 of file IntrusiveList.hpp.
     {
         clear();
     }
Member Function Documentation
assign()
template<class T > template<class InputIterator > void infra::IntrusiveList< T >::assign (InputIterator first, InputIterator last)
Definition at line 417 of file IntrusiveList.hpp.
     {
         clear();
         for (; first != last; ++first)
             push_back(*first);
     }
back() [1/2]
template<class T > IntrusiveList< T >::reference infra::IntrusiveList< T >::back ()
Definition at line 322 of file IntrusiveList.hpp.
     {
         return static_cast<T&>(*endNode.previous);
     }
back() [2/2]
template<class T > IntrusiveList< T >::const_reference infra::IntrusiveList< T >::back () const
Definition at line 328 of file IntrusiveList.hpp.
     {
         return static_cast<T&>(*endNode.previous);
     }
begin() [1/2]
template<class T > IntrusiveList< T >::iterator infra::IntrusiveList< T >::begin ()
Definition at line 216 of file IntrusiveList.hpp.
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator<(), and infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator==().
     {
         return iterator(beginNode);
     }
begin() [2/2]
template<class T > IntrusiveList< T >::const_iterator infra::IntrusiveList< T >::begin () const
Definition at line 222 of file IntrusiveList.hpp.
     {
         return const_iterator(beginNode);
     }
cbegin()
template<class T > IntrusiveList< T >::const_iterator infra::IntrusiveList< T >::cbegin () const
Definition at line 264 of file IntrusiveList.hpp.
     {
         return begin();
     }
cend()
template<class T > IntrusiveList< T >::const_iterator infra::IntrusiveList< T >::cend () const
Definition at line 270 of file IntrusiveList.hpp.
     {
         return end();
     }
clear()
template<class T > void infra::IntrusiveList< T >::clear ()
Definition at line 444 of file IntrusiveList.hpp.
     {
         while (!empty())
             pop_front();
     }
crbegin()
template<class T > IntrusiveList< T >::const_reverse_iterator infra::IntrusiveList< T >::crbegin () const
Definition at line 276 of file IntrusiveList.hpp.
     {
         return rbegin();
     }
crend()
template<class T > IntrusiveList< T >::const_reverse_iterator infra::IntrusiveList< T >::crend () const
Definition at line 282 of file IntrusiveList.hpp.
     {
         return rend();
     }
empty()
template<class T > bool infra::IntrusiveList< T >::empty () const
Definition at line 294 of file IntrusiveList.hpp.
     {
         return numberOfElements == 0;
     }
end() [1/2]
template<class T > IntrusiveList< T >::iterator infra::IntrusiveList< T >::end ()
Definition at line 228 of file IntrusiveList.hpp.
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator<().
     {
         return iterator(&endNode);
     }
end() [2/2]
template<class T > IntrusiveList< T >::const_iterator infra::IntrusiveList< T >::end () const
Definition at line 234 of file IntrusiveList.hpp.
     {
         return const_iterator(&endNode);
     }
erase()
template<class T > void infra::IntrusiveList< T >::erase (const_reference value)
Definition at line 399 of file IntrusiveList.hpp.
     {
         NodeType& node = const_cast<reference>(value);
         if (node.previous != nullptr)
             node.previous->next = node.next;
         else if (beginNode != &node)
             return;
         else
             beginNode = node.next;
         node.next->previous = node.previous;
         node.previous = nullptr;
         node.next = nullptr;
         --numberOfElements;
     }
front() [1/2]
template<class T > IntrusiveList< T >::reference infra::IntrusiveList< T >::front ()
Definition at line 310 of file IntrusiveList.hpp.
     {
         return static_cast<T&>(*beginNode);
     }
front() [2/2]
template<class T > IntrusiveList< T >::const_reference infra::IntrusiveList< T >::front () const
Definition at line 316 of file IntrusiveList.hpp.
     {
         return static_cast<T&>(*beginNode);
     }
has_element()
template<class T > bool infra::IntrusiveList< T >::has_element (const_reference value) const
Definition at line 300 of file IntrusiveList.hpp.
     {
         for (const_reference item: *this)
             if (&item == &value)
                 return true;
         return false;
     }
insert()
template<class T > void infra::IntrusiveList< T >::insert (const_iterator position, const_reference value)
Definition at line 385 of file IntrusiveList.hpp.
     {
         NodeType& node = const_cast<reference>(value);
         node.previous = position.node->previous;
         node.next = const_cast<NodeType*>(position.node);
         const_cast<NodeType*>(position.node)->previous = &node;
         if (node.previous != nullptr)
             node.previous->next = &node;
         else
             beginNode = &node;
         ++numberOfElements;
     }
operator!=()
template<class T > bool infra::IntrusiveList< T >::operator!= (const IntrusiveList< T > & other) const
Definition at line 458 of file IntrusiveList.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T > bool infra::IntrusiveList< T >::operator< (const IntrusiveList< T > & other) const
Definition at line 464 of file IntrusiveList.hpp.
     {
         return std::lexicographical_compare(begin(), end(), other.begin(), other.end());
     }
operator<=()
template<class T > bool infra::IntrusiveList< T >::operator<= (const IntrusiveList< T > & other) const
Definition at line 470 of file IntrusiveList.hpp.
     {
         return !(other < *this);
     }
operator=() [1/2]
template<class T> IntrusiveList& infra::IntrusiveList< T >::operator= (const IntrusiveList< T > &) delete
operator=() [2/2]
template<class T > IntrusiveList< T > & infra::IntrusiveList< T >::operator= (IntrusiveList< T > && other)
Definition at line 193 of file IntrusiveList.hpp.
     {
         clear();
         numberOfElements = other.numberOfElements;
         if (other.beginNode != &other.endNode)
             beginNode = other.beginNode;
         endNode.previous = other.endNode.previous;
         if (endNode.previous != nullptr)
             endNode.previous->next = &endNode;
         other.beginNode = &other.endNode;
         other.endNode.previous = nullptr;
         other.numberOfElements = 0;
         return *this;
     }
operator==()
template<class T > bool infra::IntrusiveList< T >::operator== (const IntrusiveList< T > & other) const
Definition at line 451 of file IntrusiveList.hpp.
     {
         return size() == other.size()
             && std::equal(begin(), end(), other.begin());
     }
operator>()
template<class T > bool infra::IntrusiveList< T >::operator> (const IntrusiveList< T > & other) const
Definition at line 476 of file IntrusiveList.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T > bool infra::IntrusiveList< T >::operator>= (const IntrusiveList< T > & other) const
Definition at line 482 of file IntrusiveList.hpp.
     {
         return !(*this < other);
     }
pop_back()
template<class T > void infra::IntrusiveList< T >::pop_back ()
Definition at line 374 of file IntrusiveList.hpp.
     {
         NodeType* erasingNode = endNode.previous;
         endNode.previous = endNode.previous->previous;
         if (endNode.previous != nullptr)
             endNode.previous->next = &endNode;
         erasingNode->previous = nullptr;
         --numberOfElements;
     }
pop_front()
template<class T > void infra::IntrusiveList< T >::pop_front ()
Definition at line 364 of file IntrusiveList.hpp.
     {
         NodeType* erasingNode = beginNode;
         beginNode = beginNode->next;
         beginNode->previous = nullptr;
         erasingNode->next = nullptr;
         --numberOfElements;
     }
push_back()
template<class T > void infra::IntrusiveList< T >::push_back (const_reference value)
Definition at line 348 of file IntrusiveList.hpp.
     {
         NodeType& node = const_cast<reference>(value);
         node.next = &endNode;
         node.previous = endNode.previous;
         if (node.previous != nullptr)
             node.previous->next = &node;
         else
             beginNode = &node;
         endNode.previous = &node;
         ++numberOfElements;
     }
push_front()
template<class T > void infra::IntrusiveList< T >::push_front (const_reference value)
Definition at line 334 of file IntrusiveList.hpp.
     {
         NodeType& node = const_cast<reference>(value);
         node.next = beginNode;
         node.previous = nullptr;
         if (node.next != nullptr)
             node.next->previous = &node;
         beginNode = &node;
         ++numberOfElements;
     }
rbegin() [1/2]
template<class T > IntrusiveList< T >::reverse_iterator infra::IntrusiveList< T >::rbegin ()
Definition at line 240 of file IntrusiveList.hpp.
     {
         return reverse_iterator(end());
     }
rbegin() [2/2]
template<class T > IntrusiveList< T >::const_reverse_iterator infra::IntrusiveList< T >::rbegin () const
Definition at line 246 of file IntrusiveList.hpp.
     {
         return const_reverse_iterator(end());
     }
rend() [1/2]
template<class T > IntrusiveList< T >::reverse_iterator infra::IntrusiveList< T >::rend ()
Definition at line 252 of file IntrusiveList.hpp.
     {
         return reverse_iterator(begin());
     }
rend() [2/2]
template<class T > IntrusiveList< T >::const_reverse_iterator infra::IntrusiveList< T >::rend () const
Definition at line 258 of file IntrusiveList.hpp.
     {
         return const_reverse_iterator(begin());
     }
size()
template<class T > IntrusiveList< T >::size_type infra::IntrusiveList< T >::size () const
Definition at line 288 of file IntrusiveList.hpp.
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::operator==().
     {
         return numberOfElements;
     }
swap()
template<class T > void infra::IntrusiveList< T >::swap (IntrusiveList< T > & other)
Definition at line 425 of file IntrusiveList.hpp.
Referenced by infra::swap().
     {
         using std::swap;
         std::swap(endNode, other.endNode);
         std::swap(beginNode, other.beginNode);
         std::swap(numberOfElements, other.numberOfElements);
         if (endNode.previous != nullptr)
             endNode.previous->next = &endNode;
         else
             beginNode = &endNode;
         if (other.endNode.previous != nullptr)
             other.endNode.previous->next = &other.endNode;
         else
             other.beginNode = &other.endNode;
     }
Member Data Documentation
beginNode
template<class T> NodeType* infra::IntrusiveList< T >::beginNode private
Definition at line 122 of file IntrusiveList.hpp.
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::swap().
endNode
template<class T> NodeType infra::IntrusiveList< T >::endNode private
Definition at line 123 of file IntrusiveList.hpp.
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::swap().
numberOfElements
template<class T> size_type infra::IntrusiveList< T >::numberOfElements private
Definition at line 121 of file IntrusiveList.hpp.
Referenced by infra::IntrusiveList< infra::ClaimableResource::ClaimerBase >::swap().
The documentation for this class was generated from the following file:
IntrusiveList.hpp