EMil: services::FlashMultipleAccessMaster Class Reference
services::FlashMultipleAccessMaster Class Reference
#include <FlashMultipleAccess.hpp>
Public Member Functions
FlashMultipleAccessMaster (hal::Flash &master)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Public Member Functions inherited from infra::ClaimableResource
ClaimableResource ()=default
ClaimableResource (const ClaimableResource &other)=delete
ClaimableResource & operator= (const ClaimableResource &other)=delete
~ClaimableResource ()
Private Attributes
hal::Flash & master
Additional Inherited Members
Public Types inherited from infra::ClaimableResource
using Claimer = ClaimerWithSize< INFRA_DEFAULT_FUNCTION_EXTRA_SIZE >
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 14 of file FlashMultipleAccess.hpp.
Constructor & Destructor Documentation
FlashMultipleAccessMaster()
services::FlashMultipleAccessMaster::FlashMultipleAccessMaster (hal::Flash & master) explicit
Definition at line 5 of file FlashMultipleAccess.cpp.
         : master(master)
     {}
Member Function Documentation
AddressOfSector()
uint32_t services::FlashMultipleAccessMaster::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 24 of file FlashMultipleAccess.cpp.
References hal::Flash::AddressOfSector(), and master.
Referenced by services::FlashMultipleAccess::AddressOfSector().
     {
         return master.AddressOfSector(sectorIndex);
     }
EraseSectors()
void services::FlashMultipleAccessMaster::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 39 of file FlashMultipleAccess.cpp.
References hal::Flash::EraseSectors(), and master.
Referenced by services::FlashMultipleAccess::EraseSectors().
     {
         master.EraseSectors(beginIndex, endIndex, onDone);
     }
NumberOfSectors()
uint32_t services::FlashMultipleAccessMaster::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 9 of file FlashMultipleAccess.cpp.
References master, and hal::Flash::NumberOfSectors().
Referenced by services::FlashMultipleAccess::NumberOfSectors().
     {
         return master.NumberOfSectors();
     }
ReadBuffer()
void services::FlashMultipleAccessMaster::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 34 of file FlashMultipleAccess.cpp.
References master, and hal::Flash::ReadBuffer().
Referenced by services::FlashMultipleAccess::ReadBuffer().
     {
         master.ReadBuffer(buffer, address, onDone);
     }
SectorOfAddress()
uint32_t services::FlashMultipleAccessMaster::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 19 of file FlashMultipleAccess.cpp.
References master, and hal::Flash::SectorOfAddress().
Referenced by services::FlashMultipleAccess::SectorOfAddress().
     {
         return master.SectorOfAddress(address);
     }
SizeOfSector()
uint32_t services::FlashMultipleAccessMaster::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 14 of file FlashMultipleAccess.cpp.
References master, and hal::Flash::SizeOfSector().
Referenced by services::FlashMultipleAccess::SizeOfSector().
     {
         return master.SizeOfSector(sectorIndex);
     }
WriteBuffer()
void services::FlashMultipleAccessMaster::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 29 of file FlashMultipleAccess.cpp.
References master, and hal::Flash::WriteBuffer().
Referenced by services::FlashMultipleAccess::WriteBuffer().
     {
         master.WriteBuffer(buffer, address, onDone);
     }
Member Data Documentation
master
hal::Flash& services::FlashMultipleAccessMaster::master private
Definition at line 30 of file FlashMultipleAccess.hpp.
Referenced by AddressOfSector(), EraseSectors(), NumberOfSectors(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), and WriteBuffer().
The documentation for this class was generated from the following files:
FlashMultipleAccess.hpp
FlashMultipleAccess.cpp