EMil: infra::JsonIterator Class Reference
infra::JsonIterator Class Reference
#include <Json.hpp>
Protected Member Functions
JsonIterator (infra::BoundedConstString objectString)
infra::Optional< JsonValue > ConvertValue (JsonToken::Token token)
Protected Attributes
infra::BoundedConstString objectString
JsonTokenizer tokenizer
Private Member Functions
infra::Optional< JsonValue > ReadObjectValue (JsonToken::Token token)
infra::Optional< JsonValue > ReadArrayValue (JsonToken::Token token)
infra::Optional< JsonToken::RightBrace > SearchObjectEnd ()
infra::Optional< JsonToken::RightBracket > SearchArrayEnd ()
Detailed Description
Definition at line 316 of file Json.hpp.
Constructor & Destructor Documentation
JsonIterator()
infra::JsonIterator::JsonIterator (infra::BoundedConstString objectString) explicit protected
Definition at line 774 of file Json.cpp.
         : objectString(objectString)
         , tokenizer(objectString)
     {}
Member Function Documentation
ConvertValue()
infra::Optional< JsonValue > infra::JsonIterator::ConvertValue (JsonToken::Token token) protected
Definition at line 779 of file Json.cpp.
References infra::Variant< T >::Get(), infra::Variant< T >::Is(), infra::MakeOptional(), infra::none, ReadArrayValue(), ReadObjectValue(), infra::JsonToken::String::Value(), infra::JsonToken::Integer::Value(), and infra::JsonToken::Boolean::Value().
Referenced by infra::JsonObjectIterator::ReadValue(), and infra::JsonArrayIterator::ReadValue().
     {
         if (token.Is<JsonToken::String>())
             return infra::MakeOptional(JsonValue(token.Get<JsonToken::String>().Value()));
         else if (token.Is<JsonToken::Integer>())
             return infra::MakeOptional(JsonValue(token.Get<JsonToken::Integer>().Value()));
         else if (token.Is<JsonToken::Boolean>())
             return infra::MakeOptional(JsonValue(token.Get<JsonToken::Boolean>().Value()));
         else if (token.Is<JsonToken::LeftBrace>())
             return ReadObjectValue(token);
         else if (token.Is<JsonToken::LeftBracket>())
             return ReadArrayValue(token);
         else
             return infra::none;
     }
ReadArrayValue()
infra::Optional< JsonValue > infra::JsonIterator::ReadArrayValue (JsonToken::Token token) private
Definition at line 805 of file Json.cpp.
References infra::Variant< T >::Get(), infra::JsonToken::LeftBracket::Index(), infra::MakeOptional(), infra::none, objectString, SearchArrayEnd(), and infra::BoundedStringBase< T >::substr().
Referenced by ConvertValue().
     {
         infra::Optional<JsonToken::RightBracket> arrayEnd = SearchArrayEnd();
         if (arrayEnd)
             return infra::MakeOptional(JsonValue(JsonArray(objectString.substr(token.Get<JsonToken::LeftBracket>().Index(), arrayEnd->Index() + 1 - token.Get<JsonToken::LeftBracket>().Index()))));
         else
             return infra::none;
     }
ReadObjectValue()
infra::Optional< JsonValue > infra::JsonIterator::ReadObjectValue (JsonToken::Token token) private
Definition at line 795 of file Json.cpp.
References infra::Variant< T >::Get(), infra::JsonToken::LeftBrace::Index(), infra::MakeOptional(), infra::none, objectString, SearchObjectEnd(), and infra::BoundedStringBase< T >::substr().
Referenced by ConvertValue().
     {
         infra::Optional<JsonToken::RightBrace> objectEnd = SearchObjectEnd();
         if (objectEnd)
             return infra::MakeOptional(JsonValue(JsonObject(objectString.substr(token.Get<JsonToken::LeftBrace>().Index(), objectEnd->Index() + 1 - token.Get<JsonToken::LeftBrace>().Index()))));
         else
             return infra::none;
     }
SearchArrayEnd()
infra::Optional< JsonToken::RightBracket > infra::JsonIterator::SearchArrayEnd () private
Definition at line 835 of file Json.cpp.
References infra::Variant< T >::Get(), infra::Variant< T >::Is(), infra::MakeOptional(), infra::none, infra::JsonTokenizer::Token(), and tokenizer.
Referenced by ReadArrayValue().
     {
         std::size_t nested = 0;
         JsonToken::Token token = tokenizer.Token();
         while ((nested != 0 || !token.Is<JsonToken::RightBracket>()) && !token.Is<JsonToken::End>() && !token.Is<JsonToken::Error>())
         {
             if (token.Is<JsonToken::LeftBracket>())
                 --nested;
             if (token.Is<JsonToken::RightBracket>())
                 ++nested;
             token = tokenizer.Token();
         }
         if (token.Is<JsonToken::RightBracket>())
             return infra::MakeOptional(token.Get<JsonToken::RightBracket>());
         else
             return infra::none;
     }
SearchObjectEnd()
infra::Optional< JsonToken::RightBrace > infra::JsonIterator::SearchObjectEnd () private
Definition at line 815 of file Json.cpp.
References infra::Variant< T >::Get(), infra::Variant< T >::Is(), infra::MakeOptional(), infra::none, infra::JsonTokenizer::Token(), and tokenizer.
Referenced by ReadObjectValue().
     {
         std::size_t nested = 0;
         JsonToken::Token token = tokenizer.Token();
         while ((nested != 0 || !token.Is<JsonToken::RightBrace>()) && !token.Is<JsonToken::End>() && !token.Is<JsonToken::Error>())
         {
             if (token.Is<JsonToken::LeftBrace>())
                 --nested;
             if (token.Is<JsonToken::RightBrace>())
                 ++nested;
             token = tokenizer.Token();
         }
         if (token.Is<JsonToken::RightBrace>())
             return infra::MakeOptional(token.Get<JsonToken::RightBrace>());
         return
             infra::none;
     }
Member Data Documentation
objectString
infra::BoundedConstString infra::JsonIterator::objectString protected
Definition at line 330 of file Json.hpp.
Referenced by ReadArrayValue(), and ReadObjectValue().
tokenizer
JsonTokenizer infra::JsonIterator::tokenizer protected
Definition at line 331 of file Json.hpp.
Referenced by infra::JsonArrayIterator::operator++(), infra::JsonObjectIterator::operator==(), infra::JsonArrayIterator::operator==(), infra::JsonObjectIterator::ParseNextToken(), SearchArrayEnd(), and SearchObjectEnd().
The documentation for this class was generated from the following files:
Json.hpp
Json.cpp