EMil: hal::SpiMock Class Reference
hal::SpiMock Class Reference
#include <SpiMock.hpp>
Public Member Functions
virtual void SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> &onDone) override
MOCK_METHOD1 (SetChipSelectConfigurator, void(ChipSelectConfigurator &configurator))
MOCK_METHOD1 (SetCommunicationConfigurator, void(CommunicationConfigurator &configurator))
MOCK_METHOD0 (ResetCommunicationConfigurator, void())
MOCK_METHOD2 (SendDataMock, void(std::vector< uint8_t > dataSent, SpiAction nextAction))
MOCK_METHOD1 (ReceiveDataMock, std::vector< uint8_t >(SpiAction nextAction))
Public Member Functions inherited from hal::SpiMaster
void SendData (infra::ConstByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
void ReceiveData (infra::ByteRange data, SpiAction nextAction, const infra::Function< void()> &onDone)
virtual void SetChipSelectConfigurator (ChipSelectConfigurator &configurator)=0
virtual void SetCommunicationConfigurator (CommunicationConfigurator &configurator)=0
virtual void ResetCommunicationConfigurator ()=0
Additional Inherited Members
Protected Member Functions inherited from hal::SpiMaster
SpiMaster ()=default
SpiMaster (const SpiMaster &other)=delete
SpiMaster & operator= (const SpiMaster &other)=delete
~SpiMaster ()=default
Detailed Description
Definition at line 15 of file SpiMock.hpp.
Member Function Documentation
MOCK_METHOD0()
hal::SpiMock::MOCK_METHOD0 (ResetCommunicationConfigurator , void())
MOCK_METHOD1() [1/3]
hal::SpiMock::MOCK_METHOD1 (SetChipSelectConfigurator , void(ChipSelectConfigurator &configurator))
MOCK_METHOD1() [2/3]
hal::SpiMock::MOCK_METHOD1 (SetCommunicationConfigurator , void(CommunicationConfigurator &configurator))
MOCK_METHOD1() [3/3]
hal::SpiMock::MOCK_METHOD1 (ReceiveDataMock , std::vector< uint8_t > SpiAction nextAction)
MOCK_METHOD2()
hal::SpiMock::MOCK_METHOD2 (SendDataMock , void(std::vector< uint8_t > dataSent, SpiAction nextAction))
SendAndReceive()
void hal::SpiMock::SendAndReceive (infra::ConstByteRange sendData, infra::ByteRange receiveData, SpiAction nextAction, const infra::Function< void()> & onDone) override virtual
Implements hal::SpiMaster.
Definition at line 6 of file SpiMock.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::empty(), infra::MemoryRange< T >::end(), EXPECT_EQ(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::EventDispatcherWorker::Schedule(), and infra::MemoryRange< T >::size().
     {
         if (!sendData.empty())
             SendDataMock(std::vector<uint8_t>(sendData.begin(), sendData.end()), nextAction);
         if (!receiveData.empty())
         {
             std::vector<uint8_t> dataToBeReceived = ReceiveDataMock(nextAction);
             EXPECT_EQ(dataToBeReceived.size(), receiveData.size());                                                     //TICS !CFL#001
             std::copy(dataToBeReceived.begin(), dataToBeReceived.end(), receiveData.begin());
         }
         infra::EventDispatcher::Instance().Schedule(onDone);
     }
The documentation for this class was generated from the following files:
SpiMock.hpp
SpiMock.cpp