EMil: services::FlashSpi Class Reference
services::FlashSpi Class Reference
#include <FlashSpi.hpp>
Classes
struct InstructionAndAddress
Public Member Functions
FlashSpi (hal::SpiMaster &spi, uint32_t numberOfSubSectors=512)
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
virtual void ReadFlashId (infra::ByteRange buffer, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::FlashHomogeneous
FlashHomogeneous (uint32_t numberOfSectors, uint32_t sizeOfEachSector)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Static Public Attributes
static const uint8_t commandPageProgram = 0x02
static const uint8_t commandReadData = 0x03
static const uint8_t commandReadStatusRegister = 0x05
static const uint8_t commandWriteEnable = 0x06
static const uint8_t commandEraseSubSector = 0x20
static const uint8_t commandEraseSector = 0xd8
static const uint8_t commandEraseBulk = 0xc7
static const uint8_t commandReadId = 0x9f
static const uint32_t sizeSector = 65536
static const uint32_t sizeSubSector = 4096
static const uint32_t sizePage = 256
static const uint8_t statusFlagWriteInProgress = 1
Private Member Functions
std::array< uint8_t, 3 > ConvertAddress (uint32_t address) const
void WriteEnable ()
void PageProgram ()
void EraseSomeSectors (uint32_t endIndex)
void SendEraseSubSector (uint32_t subSectorIndex)
void SendEraseSector (uint32_t subSectorIndex)
void SendEraseBulk ()
void HoldWhileWriteInProgress ()
void ReadStatusRegister ()
Private Attributes
hal::SpiMaster & spi
uint32_t numberOfSubSectors = 0
infra::Sequencer sequencer
infra::TimerSingleShot delayTimer
infra::AutoResetFunction< void()> onDone
infra::ConstByteRange buffer
infra::ConstByteRange writeBuffer
infra::ByteRange readBuffer
uint32_t address = 0
uint32_t sectorIndex = 0
uint8_t statusRegister = 0
struct services::FlashSpi::InstructionAndAddress instructionAndAddress
Additional Inherited Members
Protected Member Functions inherited from hal::FlashHomogeneous
~FlashHomogeneous ()=default
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 13 of file FlashSpi.hpp.
Constructor & Destructor Documentation
FlashSpi()
services::FlashSpi::FlashSpi (hal::SpiMaster & spi, uint32_t numberOfSubSectors = 512) explicit
Definition at line 16 of file FlashSpi.cpp.
         : hal::FlashHomogeneous(numberOfSubSectors, sizeSubSector)
         , spi(spi)
     {}
Member Function Documentation
ConvertAddress()
std::array< uint8_t, 3 > services::FlashSpi::ConvertAddress (uint32_t address) const private
Definition at line 82 of file FlashSpi.cpp.
References address.
Referenced by PageProgram(), ReadBuffer(), SendEraseSector(), and SendEraseSubSector().
     {
         uint32_t linearAddress = address;
         std::array<uint8_t, 3> result;
         result[0] = static_cast<uint8_t>(linearAddress >> 16);
         result[1] = static_cast<uint8_t>(linearAddress >> 8);
         result[2] = static_cast<uint8_t>(linearAddress);
         return result;
     }
EraseSectors()
void services::FlashSpi::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 53 of file FlashSpi.cpp.
References infra::Sequencer::EndWhile(), EraseSomeSectors(), infra::Sequencer::Execute(), HoldWhileWriteInProgress(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::Sequencer::Load(), onDone, infra::EventDispatcherWorker::Schedule(), sectorIndex, sequencer, infra::Sequencer::Step(), infra::Sequencer::While(), and WriteEnable().
     {
         this->onDone = onDone;
         sectorIndex = beginIndex;
         sequencer.Load([this, endIndex]()
         {
             sequencer.While([this, endIndex]() { return sectorIndex != endIndex; });
                 sequencer.Step([this]() { WriteEnable(); });
                 sequencer.Step([this, endIndex]() { EraseSomeSectors(endIndex); });
                 HoldWhileWriteInProgress();
             sequencer.EndWhile();
             sequencer.Execute([this]() { infra::EventDispatcher::Instance().Schedule([this]() { this->onDone(); }); });
         });
     }
EraseSomeSectors()
void services::FlashSpi::EraseSomeSectors (uint32_t endIndex) private
Definition at line 121 of file FlashSpi.cpp.
References hal::FlashHomogeneous::NumberOfSectors(), sectorIndex, SendEraseBulk(), SendEraseSector(), SendEraseSubSector(), sizeSector, and sizeSubSector.
Referenced by EraseSectors().
     {
         if (sectorIndex == 0 && endIndex == NumberOfSectors())
         {
             SendEraseBulk();
             sectorIndex += NumberOfSectors();
         }
         else if (sectorIndex % (sizeSector / sizeSubSector) == 0 && sectorIndex + sizeSector / sizeSubSector <= endIndex)
         {
             SendEraseSector(sectorIndex);
             sectorIndex += sizeSector / sizeSubSector;
         }
         else
         {
             SendEraseSubSector(sectorIndex);
             ++sectorIndex;
         }
     }
HoldWhileWriteInProgress()
void services::FlashSpi::HoldWhileWriteInProgress () private
Definition at line 172 of file FlashSpi.cpp.
References infra::Sequencer::Continue(), delayTimer, infra::Sequencer::EndWhile(), ReadStatusRegister(), sequencer, infra::TimerSingleShot::Start(), statusRegister, infra::Sequencer::Step(), and infra::Sequencer::While().
Referenced by EraseSectors(), and WriteBuffer().
     {
         sequencer.Step([this]() { ReadStatusRegister(); });
         sequencer.While([this]() { return (statusRegister & 1) == 1; });
             sequencer.Step([this]() { delayTimer.Start(std::chrono::milliseconds(1), [this]() { sequencer.Continue(); }); });
             sequencer.Step([this]() { ReadStatusRegister(); });
         sequencer.EndWhile();
     }
PageProgram()
void services::FlashSpi::PageProgram () private
Definition at line 102 of file FlashSpi.cpp.
References address, services::FlashSpi::InstructionAndAddress::address, hal::Flash::AddressOffsetInSector(), buffer, commandPageProgram, infra::Sequencer::Continue(), hal::continueSession, ConvertAddress(), infra::Head(), services::FlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), infra::MemoryRange< T >::pop_front(), hal::SpiMaster::SendData(), sequencer, infra::MemoryRange< T >::size(), sizePage, spi, hal::stop, and writeBuffer.
Referenced by WriteBuffer().
     {
         writeBuffer = infra::Head(buffer, sizePage - AddressOffsetInSector(address) % sizePage);
         buffer.pop_front(writeBuffer.size());
         instructionAndAddress.instruction = commandPageProgram;
         instructionAndAddress.address = ConvertAddress(address);
         address += writeBuffer.size();
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SpiAction::continueSession, [this]()
         {
             spi.SendData(writeBuffer, hal::SpiAction::stop, [this]()
             {
                 sequencer.Continue();
             });
         });
     }
ReadBuffer()
void services::FlashSpi::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 37 of file FlashSpi.cpp.
References services::FlashSpi::InstructionAndAddress::address, buffer, commandReadData, hal::continueSession, ConvertAddress(), services::FlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), onDone, readBuffer, hal::SpiMaster::ReceiveData(), hal::SpiMaster::SendData(), spi, and hal::stop.
     {
         readBuffer = buffer;
         this->onDone = onDone;
         instructionAndAddress.instruction = commandReadData;
         instructionAndAddress.address = ConvertAddress(address);
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SpiAction::continueSession, [this]()
         {
             spi.ReceiveData(readBuffer, hal::SpiAction::stop, [this]()
             {
                 this->onDone();
             });
         });
     }
ReadFlashId()
void services::FlashSpi::ReadFlashId (infra::ByteRange buffer, infra::Function< void()> onDone) override virtual
Implements hal::FlashId.
Definition at line 68 of file FlashSpi.cpp.
References buffer, commandReadId, hal::continueSession, infra::MakeByteRange(), onDone, readBuffer, hal::SpiMaster::ReceiveData(), hal::SpiMaster::SendData(), spi, and hal::stop.
     {
         this->onDone = onDone;
         readBuffer = buffer;
         spi.SendData(infra::MakeByteRange(commandReadId), hal::SpiAction::continueSession, [this]()
         {
             spi.ReceiveData(readBuffer, hal::SpiAction::stop, [this]()
             {
                 this->onDone();
             });
         });
     }
ReadStatusRegister()
void services::FlashSpi::ReadStatusRegister () private
Definition at line 181 of file FlashSpi.cpp.
References commandReadStatusRegister, infra::Sequencer::Continue(), hal::continueSession, infra::MakeByteRange(), hal::SpiMaster::ReceiveData(), hal::SpiMaster::SendData(), sequencer, spi, statusRegister, and hal::stop.
Referenced by HoldWhileWriteInProgress().
     {
         static const uint8_t instruction = commandReadStatusRegister;
         spi.SendData(infra::MakeByteRange(instruction), hal::SpiAction::continueSession, [this]()
         {
             spi.ReceiveData(infra::MakeByteRange(statusRegister), hal::SpiAction::stop, [this]()
             {
                 sequencer.Continue();
             });
         });
     }
SendEraseBulk()
void services::FlashSpi::SendEraseBulk () private
Definition at line 162 of file FlashSpi.cpp.
References commandEraseBulk, services::FlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SpiMaster::SendData(), spi, and hal::stop.
Referenced by EraseSomeSectors().
     {
         instructionAndAddress.instruction = commandEraseBulk;
         spi.SendData(infra::MakeByteRange(instructionAndAddress.instruction), hal::SpiAction::stop, [this]()
         {
             sequencer.Continue();
         });
     }
SendEraseSector()
void services::FlashSpi::SendEraseSector (uint32_t subSectorIndex) private
Definition at line 151 of file FlashSpi.cpp.
References services::FlashSpi::InstructionAndAddress::address, hal::FlashHomogeneous::AddressOfSector(), commandEraseSector, infra::Sequencer::Continue(), ConvertAddress(), services::FlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SpiMaster::SendData(), sequencer, spi, and hal::stop.
Referenced by EraseSomeSectors().
     {
         instructionAndAddress.instruction = commandEraseSector;
         instructionAndAddress.address = ConvertAddress(AddressOfSector(subSectorIndex));
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SpiAction::stop, [this]()
         {
             sequencer.Continue();
         });
     }
SendEraseSubSector()
void services::FlashSpi::SendEraseSubSector (uint32_t subSectorIndex) private
Definition at line 140 of file FlashSpi.cpp.
References services::FlashSpi::InstructionAndAddress::address, hal::FlashHomogeneous::AddressOfSector(), commandEraseSubSector, infra::Sequencer::Continue(), ConvertAddress(), services::FlashSpi::InstructionAndAddress::instruction, instructionAndAddress, infra::MakeByteRange(), hal::SpiMaster::SendData(), sequencer, spi, and hal::stop.
Referenced by EraseSomeSectors().
     {
         instructionAndAddress.instruction = commandEraseSubSector;
         instructionAndAddress.address = ConvertAddress(AddressOfSector(subSectorIndex));
         spi.SendData(infra::MakeByteRange(instructionAndAddress), hal::SpiAction::stop, [this]()
         {
             sequencer.Continue();
         });
     }
WriteBuffer()
void services::FlashSpi::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 21 of file FlashSpi.cpp.
References address, buffer, infra::MemoryRange< T >::empty(), infra::Sequencer::EndWhile(), infra::Sequencer::Execute(), HoldWhileWriteInProgress(), infra::InterfaceConnector< EventDispatcherWorker >::Instance(), infra::Sequencer::Load(), onDone, PageProgram(), infra::EventDispatcherWorker::Schedule(), sequencer, infra::Sequencer::Step(), infra::Sequencer::While(), and WriteEnable().
     {
         this->onDone = onDone;
         this->buffer = buffer;
         this->address = address;
         sequencer.Load([this]()
         {
             sequencer.While([this]() { return !this->buffer.empty(); });
                 sequencer.Step([this]() { WriteEnable(); });
                 sequencer.Step([this]() { PageProgram(); });
                 HoldWhileWriteInProgress();
             sequencer.EndWhile();
             sequencer.Execute([this]() { infra::EventDispatcher::Instance().Schedule([this]() { this->onDone(); }); });
         });
     }
WriteEnable()
void services::FlashSpi::WriteEnable () private
Definition at line 92 of file FlashSpi.cpp.
References commandWriteEnable, infra::Sequencer::Continue(), infra::MakeByteRange(), hal::SpiMaster::SendData(), sequencer, spi, and hal::stop.
Referenced by EraseSectors(), and WriteBuffer().
     {
         static const uint8_t command = commandWriteEnable;
         spi.SendData(infra::MakeByteRange(command), hal::SpiAction::stop, [this]()
         {
             sequencer.Continue();
         });
     }
Member Data Documentation
address
uint32_t services::FlashSpi::address = 0 private
Definition at line 65 of file FlashSpi.hpp.
Referenced by ConvertAddress(), PageProgram(), and WriteBuffer().
buffer
infra::ConstByteRange services::FlashSpi::buffer private
Definition at line 62 of file FlashSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), ReadFlashId(), and WriteBuffer().
commandEraseBulk
const uint8_t services::FlashSpi::commandEraseBulk = 0xc7 static
Definition at line 24 of file FlashSpi.hpp.
Referenced by SendEraseBulk().
commandEraseSector
const uint8_t services::FlashSpi::commandEraseSector = 0xd8 static
Definition at line 23 of file FlashSpi.hpp.
Referenced by SendEraseSector().
commandEraseSubSector
const uint8_t services::FlashSpi::commandEraseSubSector = 0x20 static
Definition at line 22 of file FlashSpi.hpp.
Referenced by SendEraseSubSector().
commandPageProgram
const uint8_t services::FlashSpi::commandPageProgram = 0x02 static
Definition at line 18 of file FlashSpi.hpp.
Referenced by PageProgram().
commandReadData
const uint8_t services::FlashSpi::commandReadData = 0x03 static
Definition at line 19 of file FlashSpi.hpp.
Referenced by ReadBuffer().
commandReadId
const uint8_t services::FlashSpi::commandReadId = 0x9f static
Definition at line 25 of file FlashSpi.hpp.
Referenced by ReadFlashId().
commandReadStatusRegister
const uint8_t services::FlashSpi::commandReadStatusRegister = 0x05 static
Definition at line 20 of file FlashSpi.hpp.
Referenced by ReadStatusRegister().
commandWriteEnable
const uint8_t services::FlashSpi::commandWriteEnable = 0x06 static
Definition at line 21 of file FlashSpi.hpp.
Referenced by WriteEnable().
delayTimer
infra::TimerSingleShot services::FlashSpi::delayTimer private
Definition at line 60 of file FlashSpi.hpp.
Referenced by HoldWhileWriteInProgress().
instructionAndAddress
struct services::FlashSpi::InstructionAndAddress services::FlashSpi::instructionAndAddress private
Referenced by PageProgram(), ReadBuffer(), SendEraseBulk(), SendEraseSector(), and SendEraseSubSector().
numberOfSubSectors
uint32_t services::FlashSpi::numberOfSubSectors = 0 private
Definition at line 58 of file FlashSpi.hpp.
onDone
infra::AutoResetFunction<void()> services::FlashSpi::onDone private
Definition at line 61 of file FlashSpi.hpp.
Referenced by EraseSectors(), ReadBuffer(), ReadFlashId(), and WriteBuffer().
readBuffer
infra::ByteRange services::FlashSpi::readBuffer private
Definition at line 64 of file FlashSpi.hpp.
Referenced by ReadBuffer(), and ReadFlashId().
sectorIndex
uint32_t services::FlashSpi::sectorIndex = 0 private
Definition at line 66 of file FlashSpi.hpp.
Referenced by EraseSectors(), and EraseSomeSectors().
sequencer
infra::Sequencer services::FlashSpi::sequencer private
Definition at line 59 of file FlashSpi.hpp.
Referenced by EraseSectors(), HoldWhileWriteInProgress(), PageProgram(), ReadStatusRegister(), SendEraseSector(), SendEraseSubSector(), WriteBuffer(), and WriteEnable().
sizePage
const uint32_t services::FlashSpi::sizePage = 256 static
Definition at line 29 of file FlashSpi.hpp.
Referenced by PageProgram().
sizeSector
const uint32_t services::FlashSpi::sizeSector = 65536 static
Definition at line 27 of file FlashSpi.hpp.
Referenced by EraseSomeSectors().
sizeSubSector
const uint32_t services::FlashSpi::sizeSubSector = 4096 static
Definition at line 28 of file FlashSpi.hpp.
Referenced by EraseSomeSectors().
spi
hal::SpiMaster& services::FlashSpi::spi private
Definition at line 57 of file FlashSpi.hpp.
Referenced by PageProgram(), ReadBuffer(), ReadFlashId(), ReadStatusRegister(), SendEraseBulk(), SendEraseSector(), SendEraseSubSector(), and WriteEnable().
statusFlagWriteInProgress
const uint8_t services::FlashSpi::statusFlagWriteInProgress = 1 static
Definition at line 31 of file FlashSpi.hpp.
statusRegister
uint8_t services::FlashSpi::statusRegister = 0 private
Definition at line 67 of file FlashSpi.hpp.
Referenced by HoldWhileWriteInProgress(), and ReadStatusRegister().
writeBuffer
infra::ConstByteRange services::FlashSpi::writeBuffer private
Definition at line 63 of file FlashSpi.hpp.
Referenced by PageProgram().
The documentation for this class was generated from the following files:
FlashSpi.hpp
FlashSpi.cpp