EMil: services::ConnectionStub Class Reference
services::ConnectionStub Class Reference
#include <ConnectionStub.hpp>
Classes
class StreamReaderStub
class StreamWriterStub
Public Member Functions
virtual void RequestSendStream (std::size_t sendSize) override
virtual std::size_t MaxSendStreamSize () const override
virtual infra::SharedPtr< infra::StreamReaderWithRewinding > ReceiveStream () override
virtual void AckReceived () override
virtual void CloseAndDestroy () override
virtual void AbortAndDestroy () override
MOCK_METHOD0 (CloseAndDestroyMock, void())
MOCK_METHOD0 (AbortAndDestroyMock, void())
MOCK_CONST_METHOD0 (Ipv4Address, IPv4Address())
void SimulateDataReceived (infra::ConstByteRange data)
std::string SentDataAsString () const
Public Member Functions inherited from services::Connection
void SwitchObserver (const infra::SharedPtr< ConnectionObserver > &newObserver)
void SetOwnership (const infra::SharedPtr< void > &owner, const infra::SharedPtr< ConnectionObserver > &observer)
void ResetOwnership ()
infra::SharedPtr< ConnectionObserver > Observer () const
Public Member Functions inherited from infra::Subject< ConnectionObserver >
bool HasObserver () const
ObserverType & GetObserver () const
void NotifyObservers (F callback) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
void NotifyObservers (F callback, typename std::enable_if< std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *) const
bool NotifyObservers (F callback, typename std::enable_if<!std::is_same< typename std::result_of< F(ObserverType &)>::type, void >::value >::type *)
Public Member Functions inherited from infra::EnableSharedFromThis< ConnectionStub >
SharedPtr< ConnectionStub > SharedFromThis ()
SharedPtr< const ConnectionStub > SharedFromThis () const
WeakPtr< ConnectionStub > WeakFromThis ()
WeakPtr< const ConnectionStub > WeakFromThis () const
void MakeShared (SharedPtr< ConnectionStub > sharedPtr)
Public Attributes
std::vector< uint8_t > sentData
Private Attributes
infra::BoundedDeque< uint8_t >::WithMaxSize< 4096 > receivingData
infra::SharedOptional< StreamReaderStub > streamReader
infra::SharedOptional< StreamWriterStub > streamWriter
infra::SharedPtr< infra::StreamWriter > streamWriterPtr
Additional Inherited Members
Public Types inherited from infra::EnableSharedFromThis< ConnectionStub >
using EnableSharedFromThisType = ConnectionStub
Protected Member Functions inherited from infra::Subject< ConnectionObserver >
Subject ()=default
Subject (const Subject &)=delete
Subject & operator= (const Subject &)=delete
~Subject ()
virtual void RegisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
virtual void UnregisterObserver (SingleObserver< ConnectionObserver, ObserverSubjectType > *observer)
Protected Member Functions inherited from infra::EnableSharedFromThis< ConnectionStub >
~EnableSharedFromThis ()=default
Detailed Description
Definition at line 14 of file ConnectionStub.hpp.
Member Function Documentation
AbortAndDestroy()
void services::ConnectionStub::AbortAndDestroy () override virtual
Implements services::Connection.
Reimplemented in services::ConnectionStubWithAckReceivedMock.
Definition at line 41 of file ConnectionStub.cpp.
References services::Connection::ResetOwnership().
     {
         AbortAndDestroyMock();
         ResetOwnership();
     }
AckReceived()
void services::ConnectionStub::AckReceived () override virtual
Implements services::Connection.
Reimplemented in services::ConnectionStubWithAckReceivedMock.
Definition at line 29 of file ConnectionStub.cpp.
References streamReader.
Referenced by services::ConnectionStubWithAckReceivedMock::AckReceived().
     {
         if (streamReader)
             streamReader->ConsumeRead();
     }
CloseAndDestroy()
void services::ConnectionStub::CloseAndDestroy () override virtual
Implements services::Connection.
Reimplemented in services::ConnectionStubWithAckReceivedMock.
Definition at line 35 of file ConnectionStub.cpp.
References services::Connection::ResetOwnership().
     {
         CloseAndDestroyMock();
         ResetOwnership();
     }
MaxSendStreamSize()
std::size_t services::ConnectionStub::MaxSendStreamSize () const override virtual
Implements services::Connection.
Definition at line 18 of file ConnectionStub.cpp.
Referenced by RequestSendStream().
     {
         return 1024;
     }
MOCK_CONST_METHOD0()
services::ConnectionStub::MOCK_CONST_METHOD0 (Ipv4Address , IPv4Address())
MOCK_METHOD0() [1/2]
services::ConnectionStub::MOCK_METHOD0 (CloseAndDestroyMock , void())
MOCK_METHOD0() [2/2]
services::ConnectionStub::MOCK_METHOD0 (AbortAndDestroyMock , void())
ReceiveStream()
infra::SharedPtr< infra::StreamReaderWithRewinding > services::ConnectionStub::ReceiveStream () override virtual
Implements services::Connection.
Definition at line 23 of file ConnectionStub.cpp.
References streamReader.
     {
         assert(streamReader.Allocatable());
         return streamReader.Emplace(*this);
     }
RequestSendStream()
void services::ConnectionStub::RequestSendStream (std::size_t sendSize) override virtual
Implements services::Connection.
Definition at line 6 of file ConnectionStub.cpp.
References infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), MaxSendStreamSize(), infra::EventDispatcherWithWeakPtrWorker::Schedule(), infra::EnableSharedFromThis< ConnectionStub >::SharedFromThis(), streamWriter, and streamWriterPtr.
     {
         assert(streamWriter.Allocatable());
         assert(sendSize <= MaxSendStreamSize());
         streamWriterPtr = streamWriter.Emplace(*this, sendSize);
         infra::EventDispatcherWithWeakPtr::Instance().Schedule([](const infra::SharedPtr<ConnectionStub>& object)
         {
             infra::SharedPtr<infra::StreamWriter> stream = std::move(object->streamWriterPtr);
             object->GetObserver().SendStreamAvailable(std::move(stream));
         }, SharedFromThis());
     }
SentDataAsString()
std::string services::ConnectionStub::SentDataAsString () const
Definition at line 57 of file ConnectionStub.cpp.
References sentData.
     {
         return{ sentData.begin(), sentData.end() };
     }
SimulateDataReceived()
void services::ConnectionStub::SimulateDataReceived (infra::ConstByteRange data)
Definition at line 47 of file ConnectionStub.cpp.
References data, infra::BoundedDeque< T >::end(), infra::BoundedDeque< T >::insert(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), receivingData, infra::EventDispatcherWithWeakPtrWorker::Schedule(), and infra::EnableSharedFromThis< ConnectionStub >::SharedFromThis().
     {
         receivingData.insert(receivingData.end(), data.begin(), data.end());
         infra::EventDispatcherWithWeakPtr::Instance().Schedule([this](const infra::SharedPtr<ConnectionStub>& object)
         {
             if (object->HasObserver())
                 object->GetObserver().DataReceived();
         }, SharedFromThis());
     }
Member Data Documentation
receivingData
infra::BoundedDeque<uint8_t>::WithMaxSize<4096> services::ConnectionStub::receivingData private
Definition at line 65 of file ConnectionStub.hpp.
Referenced by SimulateDataReceived().
sentData
std::vector<uint8_t> services::ConnectionStub::sentData
Definition at line 32 of file ConnectionStub.hpp.
Referenced by SentDataAsString().
streamReader
infra::SharedOptional<StreamReaderStub> services::ConnectionStub::streamReader private
Definition at line 67 of file ConnectionStub.hpp.
Referenced by AckReceived(), and ReceiveStream().
streamWriter
infra::SharedOptional<StreamWriterStub> services::ConnectionStub::streamWriter private
Definition at line 68 of file ConnectionStub.hpp.
Referenced by RequestSendStream().
streamWriterPtr
infra::SharedPtr<infra::StreamWriter> services::ConnectionStub::streamWriterPtr private
Definition at line 69 of file ConnectionStub.hpp.
Referenced by RequestSendStream().
The documentation for this class was generated from the following files:
ConnectionStub.hpp
ConnectionStub.cpp