EMil: infra::StdStringInputStreamReader Class Reference
infra::StdStringInputStreamReader Class Reference
#include <StdStringInputStream.hpp>
Public Member Functions
StdStringInputStreamReader (const std::string &string)
Private Member Functions
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy) override
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy) override
virtual ConstByteRange ExtractContiguousRange (std::size_t max) override
virtual ConstByteRange PeekContiguousRange (std::size_t start) override
virtual bool Empty () const override
virtual std::size_t Available () const override
Private Attributes
uint32_t offset = 0
const std::string & string
Additional Inherited Members
Protected Member Functions inherited from infra::StreamReader
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 11 of file StdStringInputStream.hpp.
Constructor & Destructor Documentation
StdStringInputStreamReader()
infra::StdStringInputStreamReader::StdStringInputStreamReader (const std::string & string) explicit
Definition at line 5 of file StdStringInputStream.cpp.
         : string(string)
     {}
Member Function Documentation
Available()
std::size_t infra::StdStringInputStreamReader::Available () const override private virtual
Implements infra::StreamReader.
Definition at line 51 of file StdStringInputStream.cpp.
References offset.
     {
         return string.size() - offset;
     }
Empty()
bool infra::StdStringInputStreamReader::Empty () const override private virtual
Implements infra::StreamReader.
Definition at line 46 of file StdStringInputStream.cpp.
References offset.
     {
         return offset == string.size();
     }
Extract()
void infra::StdStringInputStreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) override private virtual
Implements infra::StreamReader.
Definition at line 9 of file StdStringInputStream.cpp.
References infra::detail::begin(), infra::MemoryRange< T >::begin(), offset, infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         errorPolicy.ReportResult(offset + range.size() <= string.size());
         range.shrink_from_back_to(string.size() - offset);
         std::copy(string.begin() + offset, string.begin() + offset + range.size(), range.begin());
         offset += range.size();
     }
ExtractContiguousRange()
ConstByteRange infra::StdStringInputStreamReader::ExtractContiguousRange (std::size_t max) override private virtual
Implements infra::StreamReader.
Definition at line 31 of file StdStringInputStream.cpp.
References infra::data, offset, infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         ConstByteRange result(reinterpret_cast<const uint8_t*>(string.data()) + offset, reinterpret_cast<const uint8_t*>(string.data()) + string.size());
         result.shrink_from_back_to(max);
         offset += result.size();
         return result;
     }
Peek()
uint8_t infra::StdStringInputStreamReader::Peek (StreamErrorPolicy & errorPolicy) override private virtual
Implements infra::StreamReader.
Definition at line 17 of file StdStringInputStream.cpp.
References offset, and infra::StreamErrorPolicy::ReportResult().
     {
         if (offset == string.size())
         {
             errorPolicy.ReportResult(false);
             return 0;
         }
         else
         {
             errorPolicy.ReportResult(true);
             return static_cast<uint8_t>(string.begin()[offset]);
         }
     }
PeekContiguousRange()
ConstByteRange infra::StdStringInputStreamReader::PeekContiguousRange (std::size_t start) override private virtual
Implements infra::StreamReader.
Definition at line 39 of file StdStringInputStream.cpp.
References infra::data, and offset.
     {
         ConstByteRange result(reinterpret_cast<const uint8_t*>(string.data()) + offset + start, reinterpret_cast<const uint8_t*>(string.size()));
         return result;
     }
Member Data Documentation
offset
uint32_t infra::StdStringInputStreamReader::offset = 0 private
Definition at line 26 of file StdStringInputStream.hpp.
Referenced by Available(), Empty(), Extract(), ExtractContiguousRange(), Peek(), and PeekContiguousRange().
string
const std::string& infra::StdStringInputStreamReader::string private
Definition at line 27 of file StdStringInputStream.hpp.
The documentation for this class was generated from the following files:
StdStringInputStream.hpp
StdStringInputStream.cpp