EMil: services::HttpServerConnectionObserver Class Reference
services::HttpServerConnectionObserver Class Reference
#include <HttpServer.hpp>
Public Types
template<::size_t BufferSize>
using WithBuffer = infra::WithStorage< HttpServerConnectionObserver, infra::BoundedString::WithStorage< BufferSize > >
Public Types inherited from infra::SingleObserver< ConnectionObserver, Connection >
using SubjectType = Connection
using SingleHelper = Connection
Public Member Functions
HttpServerConnectionObserver (infra::BoundedString &buffer, HttpPageServer &httpServer)
HttpServerConnectionObserver (const DefaultConnectionCreationContext &creationContext)
virtual void Connected () override
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer) override
virtual void DataReceived () override
virtual void ClosingConnection () override
void Close ()
void CloseWhenIdle ()
virtual void SendResponse (const HttpResponse &response) override
virtual void TakeOverConnection (ConnectionObserver &newObserver) override
Public Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Public Member Functions inherited from services::HttpPageServer
HttpPageServer ()=default
HttpPageServer (const HttpPageServer &other)=delete
HttpPageServer & operator= (const HttpPageServer &other)=delete
~HttpPageServer ()=default
void AddPage (services::HttpPage &page)
Protected Member Functions
virtual void SendingHttpResponse (infra::BoundedConstString response)
virtual void ReceivedHttpRequest (infra::BoundedConstString request)
virtual HttpPage * PageForRequest (const HttpRequestParser &request) override
Protected Member Functions inherited from infra::SingleObserver< ConnectionObserver, Connection >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
Protected Member Functions inherited from services::HttpServerConnection
HttpServerConnection ()=default
HttpServerConnection (const HttpServerConnection &other)=delete
HttpServerConnection & operator= (const HttpServerConnection &other)=delete
~HttpServerConnection ()=default
Protected Attributes
infra::SharedPtr< infra::StreamWriter > streamWriter
HttpPageServer & httpServer
Connection * connection = nullptr
bool send100Response = false
infra::BoundedString & buffer
bool closeWhenIdle = false
bool idle = false
bool requestInProgress = false
infra::TimerSingleShot initialIdle
Private Member Functions
void ReceivedTooMuchData (infra::TextInputStream &receiveStream)
void ReceivedRequest (infra::TextInputStream &receiveStream, std::size_t available)
void TryHandleRequest (HttpRequestParser &request)
void HandleRequest (HttpRequestParser &request)
void RequestIsNowInProgress ()
void ServePage (HttpRequestParser &request)
void RequestSendStream ()
void PrepareForNextRequest ()
bool Expect100 (HttpRequestParser &request) const
Detailed Description
Definition at line 100 of file HttpServer.hpp.
Member Typedef Documentation
WithBuffer
template<::size_t BufferSize> using services::HttpServerConnectionObserver::WithBuffer = infra::WithStorage<HttpServerConnectionObserver, infra::BoundedString::WithStorage<BufferSize> >
Definition at line 107 of file HttpServer.hpp.
Constructor & Destructor Documentation
HttpServerConnectionObserver() [1/2]
services::HttpServerConnectionObserver::HttpServerConnectionObserver (infra::BoundedString & buffer, HttpPageServer & httpServer)
Definition at line 87 of file HttpServer.cpp.
References Close(), closeWhenIdle, and idle.
         : buffer(buffer)
         , httpServer(httpServer)
         , initialIdle(std::chrono::seconds(1), [this]()
             {
                 idle = true;
                 if (closeWhenIdle)
                     Close();
             })
     {}
HttpServerConnectionObserver() [2/2]
services::HttpServerConnectionObserver::HttpServerConnectionObserver (const DefaultConnectionCreationContext & creationContext)
Definition at line 98 of file HttpServer.cpp.
         : HttpServerConnectionObserver(creationContext.buffer, creationContext.httpServer)
     {}
Member Function Documentation
Close()
void services::HttpServerConnectionObserver::Close ()
Definition at line 134 of file HttpServer.cpp.
References services::Connection::CloseAndDestroy(), and connection.
Referenced by CloseWhenIdle(), HttpServerConnectionObserver(), PrepareForNextRequest(), and TryHandleRequest().
     {
         // TakeOverConnection may have been invoked, which leads to Subject() not being available. However, TakeOverConnection may have been invoked by a page
         // which is about to upgrade to a web connection, but which is not yet upgraded since it is waiting for storage. In that case, if the HttpServer
         // must close down, then we still need to invoke CloseAndDestroy on the connection. Therefore, connection is used instead of Subject()
         connection->CloseAndDestroy();
     }
CloseWhenIdle()
void services::HttpServerConnectionObserver::CloseWhenIdle ()
Definition at line 142 of file HttpServer.cpp.
References Close(), closeWhenIdle, and idle.
     {
         closeWhenIdle = true;
         if (idle)
             Close();
     }
ClosingConnection()
void services::HttpServerConnectionObserver::ClosingConnection () override virtual
Reimplemented from services::ConnectionObserver.
Definition at line 129 of file HttpServer.cpp.
References streamWriter.
     {
         streamWriter = nullptr;
     }
Connected()
void services::HttpServerConnectionObserver::Connected () override virtual
Reimplemented from services::ConnectionObserver.
Definition at line 102 of file HttpServer.cpp.
References connection, RequestSendStream(), and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
     {
         connection = &Subject();
         RequestSendStream();
     }
DataReceived()
void services::HttpServerConnectionObserver::DataReceived () override virtual
Implements services::ConnectionObserver.
Definition at line 114 of file HttpServer.cpp.
References infra::InputStream::Available(), buffer, infra::BoundedStringBase< T >::max_size(), ReceivedRequest(), ReceivedTooMuchData(), infra::BoundedStringBase< T >::size(), streamWriter, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by SendStreamAvailable().
     {
         if (streamWriter == nullptr)
             return;
         infra::SharedPtr<infra::StreamReader> reader = Subject().ReceiveStream();
         infra::TextInputStream::WithErrorPolicy receiveStream(*reader);
         auto available = receiveStream.Available();
         if (available > buffer.max_size() - buffer.size())
             ReceivedTooMuchData(receiveStream);
         else if (available > 0)
             ReceivedRequest(receiveStream, available);
     }
Expect100()
bool services::HttpServerConnectionObserver::Expect100 (HttpRequestParser & request) const private
Definition at line 260 of file HttpServer.cpp.
References services::HttpRequestParser::Header().
Referenced by HandleRequest().
     {
         return request.Header("Expect") == "100-continue";
     }
HandleRequest()
void services::HttpServerConnectionObserver::HandleRequest (HttpRequestParser & request) private
Definition at line 216 of file HttpServer.cpp.
References Expect100(), RequestIsNowInProgress(), send100Response, and ServePage().
Referenced by TryHandleRequest().
     {
         RequestIsNowInProgress();
         send100Response |= Expect100(request);
         ServePage(request);
     }
PageForRequest()
HttpPage * services::HttpServerConnectionObserver::PageForRequest (const HttpRequestParser & request) override protected virtual
Reimplemented from services::HttpPageServer.
Definition at line 177 of file HttpServer.cpp.
References httpServer, and services::HttpPageServer::PageForRequest().
Referenced by ServePage().
     {
         auto page = HttpPageServer::PageForRequest(request);
         if (page != nullptr)
             return page;
         else
             return httpServer.PageForRequest(request);
     }
PrepareForNextRequest()
void services::HttpServerConnectionObserver::PrepareForNextRequest () private
Definition at line 248 of file HttpServer.cpp.
References buffer, infra::BoundedStringBase< T >::clear(), Close(), closeWhenIdle, idle, requestInProgress, RequestSendStream(), and send100Response.
Referenced by SendResponse().
     {
         RequestSendStream();
         idle = true;
         requestInProgress = false;
         send100Response = false;
         buffer.clear();
         if (closeWhenIdle)
             Close();
     }
ReceivedHttpRequest()
virtual void services::HttpServerConnectionObserver::ReceivedHttpRequest (infra::BoundedConstString request) inline protected virtual
Definition at line 127 of file HttpServer.hpp.
Referenced by RequestIsNowInProgress().
 {}
ReceivedRequest()
void services::HttpServerConnectionObserver::ReceivedRequest (infra::TextInputStream & receiveStream, std::size_t available) private
Definition at line 194 of file HttpServer.cpp.
References buffer, services::HttpRequestParserImpl::Complete(), infra::BoundedStringBase< T >::resize(), infra::BoundedStringBase< T >::size(), infra::SingleObserver< ConnectionObserver, Connection >::Subject(), infra::BoundedStringBase< T >::substr(), and TryHandleRequest().
Referenced by DataReceived().
     {
         buffer.resize(buffer.size() + available);
         auto justReceived = buffer.substr(buffer.size() - available);
         receiveStream >> justReceived;
         Subject().AckReceived();
         HttpRequestParserImpl parser(buffer);
         if (parser.Complete())
             TryHandleRequest(parser);
     }
ReceivedTooMuchData()
void services::HttpServerConnectionObserver::ReceivedTooMuchData (infra::TextInputStream & receiveStream) private
Definition at line 186 of file HttpServer.cpp.
References infra::InputStream::ContiguousRange(), infra::InputStream::Empty(), services::HttpResponseOutOfMemory::Instance(), SendResponse(), and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by DataReceived().
     {
         while (!receiveStream.Empty())
             receiveStream.ContiguousRange();
         Subject().AckReceived();
         SendResponse(HttpResponseOutOfMemory::Instance());
     }
RequestIsNowInProgress()
void services::HttpServerConnectionObserver::RequestIsNowInProgress () private
Definition at line 225 of file HttpServer.cpp.
References buffer, infra::Timer::Cancel(), idle, initialIdle, ReceivedHttpRequest(), and requestInProgress.
Referenced by HandleRequest().
     {
         idle = false;
         initialIdle.Cancel();
         requestInProgress = true;
         ReceivedHttpRequest(buffer);
     }
RequestSendStream()
void services::HttpServerConnectionObserver::RequestSendStream () private
Definition at line 242 of file HttpServer.cpp.
References streamWriter, and infra::SingleObserver< ConnectionObserver, Connection >::Subject().
Referenced by Connected(), and PrepareForNextRequest().
     {
         streamWriter = nullptr;
         Subject().RequestSendStream(Subject().MaxSendStreamSize());
     }
SendingHttpResponse()
virtual void services::HttpServerConnectionObserver::SendingHttpResponse (infra::BoundedConstString response) inline protected virtual
Definition at line 126 of file HttpServer.hpp.
Referenced by SendResponse().
 {}
SendResponse()
void services::HttpServerConnectionObserver::SendResponse (const HttpResponse & response) override virtual
Implements services::HttpServerConnection.
Definition at line 149 of file HttpServer.cpp.
References buffer, infra::BoundedStringBase< T >::clear(), PrepareForNextRequest(), send100Response, SendingHttpResponse(), streamWriter, and services::HttpResponse::WriteResponse().
Referenced by ReceivedTooMuchData(), ServePage(), and TryHandleRequest().
     {
         buffer.clear();
         infra::StringOutputStream responseStream(buffer);
         response.WriteResponse(responseStream);
         SendingHttpResponse(buffer);
         infra::TextOutputStream::WithErrorPolicy stream(*streamWriter);
         if (send100Response)
             stream << "HTTP/1.1 100 Continue\r\nContent-Length: 0\r\nContent-Type: application/json\r\nStrict-Transport-Security: max-age=31536000\r\n\r\n";
         stream << buffer;
         PrepareForNextRequest();
     }
SendStreamAvailable()
void services::HttpServerConnectionObserver::SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > && writer) override virtual
Implements services::ConnectionObserver.
Definition at line 108 of file HttpServer.cpp.
References DataReceived(), and streamWriter.
     {
         streamWriter = std::move(writer);
         DataReceived();
     }
ServePage()
void services::HttpServerConnectionObserver::ServePage (HttpRequestParser & request) private
Definition at line 233 of file HttpServer.cpp.
References services::HttpResponseNotFound::Instance(), PageForRequest(), and SendResponse().
Referenced by HandleRequest().
     {
         auto pageServer = PageForRequest(request);
         if (pageServer != nullptr)
             pageServer->RespondToRequest(request, *this);
         else
             SendResponse(HttpResponseNotFound::Instance());
     }
TakeOverConnection()
void services::HttpServerConnectionObserver::TakeOverConnection (ConnectionObserver & newObserver) override virtual
Implements services::HttpServerConnection.
Definition at line 166 of file HttpServer.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), connection, infra::SingleObserver< ConnectionObserver, Connection >::Detach(), infra::MakeContainedSharedObject(), services::Connection::Observer(), streamWriter, infra::SingleObserver< ConnectionObserver, Connection >::Subject(), and services::Connection::SwitchObserver().
     {
         streamWriter = nullptr;
         Subject().AckReceived();
         auto& connection = Subject();
         Detach();
         newObserver.Attach(connection);
         connection.SwitchObserver(infra::MakeContainedSharedObject(newObserver, connection.Observer()));
     }
TryHandleRequest()
void services::HttpServerConnectionObserver::TryHandleRequest (HttpRequestParser & request) private
Definition at line 206 of file HttpServer.cpp.
References Close(), HandleRequest(), services::HttpResponseBadRequest::Instance(), requestInProgress, SendResponse(), and services::HttpRequestParser::Valid().
Referenced by ReceivedRequest().
     {
         if (!request.Valid())
             SendResponse(HttpResponseBadRequest::Instance());
         else if (requestInProgress)
             Close();
         else
             HandleRequest(request);
     }
Member Data Documentation
buffer
infra::BoundedString& services::HttpServerConnectionObserver::buffer protected
Definition at line 148 of file HttpServer.hpp.
Referenced by DataReceived(), PrepareForNextRequest(), ReceivedRequest(), RequestIsNowInProgress(), and SendResponse().
closeWhenIdle
bool services::HttpServerConnectionObserver::closeWhenIdle = false protected
Definition at line 149 of file HttpServer.hpp.
Referenced by CloseWhenIdle(), HttpServerConnectionObserver(), and PrepareForNextRequest().
connection
Connection* services::HttpServerConnectionObserver::connection = nullptr protected
Definition at line 146 of file HttpServer.hpp.
Referenced by Close(), Connected(), and TakeOverConnection().
httpServer
HttpPageServer& services::HttpServerConnectionObserver::httpServer protected
Definition at line 145 of file HttpServer.hpp.
Referenced by PageForRequest().
idle
bool services::HttpServerConnectionObserver::idle = false protected
Definition at line 150 of file HttpServer.hpp.
Referenced by CloseWhenIdle(), HttpServerConnectionObserver(), PrepareForNextRequest(), and RequestIsNowInProgress().
initialIdle
infra::TimerSingleShot services::HttpServerConnectionObserver::initialIdle protected
Definition at line 152 of file HttpServer.hpp.
Referenced by RequestIsNowInProgress().
requestInProgress
bool services::HttpServerConnectionObserver::requestInProgress = false protected
Definition at line 151 of file HttpServer.hpp.
Referenced by PrepareForNextRequest(), RequestIsNowInProgress(), and TryHandleRequest().
send100Response
bool services::HttpServerConnectionObserver::send100Response = false protected
Definition at line 147 of file HttpServer.hpp.
Referenced by HandleRequest(), PrepareForNextRequest(), and SendResponse().
streamWriter
infra::SharedPtr<infra::StreamWriter> services::HttpServerConnectionObserver::streamWriter protected
Definition at line 142 of file HttpServer.hpp.
Referenced by ClosingConnection(), DataReceived(), RequestSendStream(), SendResponse(), SendStreamAvailable(), and TakeOverConnection().
The documentation for this class was generated from the following files:
HttpServer.hpp
HttpServer.cpp