EMil: services::HttpClientBasic Class Reference
services::HttpClientBasic Class Reference abstract
#include <HttpClientBasic.hpp>
Public Member Functions
HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector &httpClientConnector)
HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector &httpClientConnector, infra::Duration timeoutDuration)
void Cancel (const infra::Function< void()> &onDone)
Protected Member Functions
void Connect ()
void Connect (infra::BoundedString url)
void Close ()
void ContentError ()
infra::BoundedString Url () const
virtual infra::BoundedString Path () const
virtual services::HttpHeaders Headers () const
virtual void Established ()
virtual void Done ()=0
virtual void Error (bool intermittentFailure)=0
virtual void ClosingConnection () override
virtual void BodyComplete () override
Protected Member Functions inherited from services::HttpClientObserver
virtual void Connected ()
virtual void StatusAvailable (HttpStatusCode statusCode)=0
virtual void HeaderAvailable (HttpHeader header)=0
virtual void BodyAvailable (infra::SharedPtr< infra::StreamReader > &&reader)=0
virtual void SendStreamAvailable (infra::SharedPtr< infra::StreamWriter > &&writer)
Protected Member Functions inherited from infra::SingleObserver< HttpClientObserver, HttpClient >
SingleObserver (const SingleObserver &other)=delete
SingleObserver & operator= (const SingleObserver &other)=delete
~SingleObserver ()
SingleObserver ()=default
SingleObserver (SubjectType &subject)
SubjectType & Subject () const
bool Attached () const
void Attach (SubjectType &subject)
void Detach ()
Private Types
enum State { State::idle, State::connecting, State::connected, State::closing }
Private Types inherited from services::HttpClientObserverFactory
enum ConnectFailReason { refused, connectionAllocationFailed, nameLookupFailed }
Private Member Functions
virtual infra::BoundedConstString Hostname () const final
virtual uint16_t Port () const final
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::HttpClientObserver > client)> &&createdClientObserver) final
virtual void ConnectionFailed (ConnectFailReason reason) final
void Timeout ()
void Expire ()
void ReportError (bool intermittentFailure)
HttpClientObserverFactory ()=default
HttpClientObserverFactory (const HttpClientObserverFactory &other)=delete
HttpClientObserverFactory & operator= (const HttpClientObserverFactory &other)=delete
~HttpClientObserverFactory ()=default
Private Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
IntrusiveListNode ()
~IntrusiveListNode ()=default
Private Attributes
services::HttpClientConnector & httpClientConnector
infra::AccessedBySharedPtr sharedAccess
infra::BoundedString url
uint16_t port
infra::Duration timeoutDuration
infra::TimerSingleShot timeoutTimer
State state = State::idle
bool contentError = false
Detailed Description
Definition at line 9 of file HttpClientBasic.hpp.
Member Enumeration Documentation
State
enum services::HttpClientBasic::State strong private
Enumerator
idle
connecting
connected
closing
Definition at line 51 of file HttpClientBasic.hpp.
         {
             idle,
             connecting,
             connected,
             closing
         };
Constructor & Destructor Documentation
HttpClientBasic() [1/2]
services::HttpClientBasic::HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector & httpClientConnector)
Definition at line 5 of file HttpClientBasic.cpp.
         : HttpClientBasic(url, port, httpClientConnector, std::chrono::minutes(1))
     {}
HttpClientBasic() [2/2]
services::HttpClientBasic::HttpClientBasic (infra::BoundedString url, uint16_t port, services::HttpClientConnector & httpClientConnector, infra::Duration timeoutDuration)
Definition at line 9 of file HttpClientBasic.cpp.
References Expire().
         : httpClientConnector(httpClientConnector)
         , sharedAccess([this]() { Expire(); })
         , url(url)
         , port(port)
         , timeoutDuration(timeoutDuration)
     {
         Connect();
     }
Member Function Documentation
BodyComplete()
void services::HttpClientBasic::BodyComplete () override protected virtual
Implements services::HttpClientObserver.
Definition at line 97 of file HttpClientBasic.cpp.
References infra::Timer::Cancel(), Close(), and timeoutTimer.
     {
         timeoutTimer.Cancel();
         Close();
     }
Cancel()
void services::HttpClientBasic::Cancel (const infra::Function< void()> & onDone)
Definition at line 19 of file HttpClientBasic.cpp.
References services::HttpClientConnector::CancelConnect(), Close(), closing, connected, connecting, httpClientConnector, infra::AccessedBySharedPtr::SetAction(), sharedAccess, and state.
Referenced by services::HttpClientJson::Cancel().
     {
         if (state == State::connecting)
         {
             httpClientConnector.CancelConnect(*this);
             onDone();
         }
         else if (state == State::connected)
         {
             sharedAccess.SetAction(onDone);
             Close();
         }
         else if (state == State::closing)
             sharedAccess.SetAction(onDone);
         else
             onDone();
     }
Close()
void services::HttpClientBasic::Close () protected
Definition at line 50 of file HttpClientBasic.cpp.
References infra::SingleObserver< HttpClientObserver, HttpClient >::Attached(), infra::Timer::Cancel(), closing, connected, state, infra::SingleObserver< HttpClientObserver, HttpClient >::Subject(), and timeoutTimer.
Referenced by BodyComplete(), Cancel(), ContentError(), and Timeout().
     {
         assert(HttpClientObserver::Attached());
         assert(state == State::connected);
         state = State::closing;
         timeoutTimer.Cancel();
         HttpClientObserver::Subject().Close();
     }
ClosingConnection()
void services::HttpClientBasic::ClosingConnection () override protected virtual
Reimplemented from services::HttpClientObserver.
Reimplemented in services::HttpClientJson.
Definition at line 86 of file HttpClientBasic.cpp.
References closing, connected, infra::SingleObserver< HttpClientObserver, HttpClient >::Detach(), ReportError(), infra::AccessedBySharedPtr::SetAction(), sharedAccess, and state.
Referenced by services::HttpClientJson::ClosingConnection().
     {
         if (state == State::connected)
         {
             state = State::closing;
             sharedAccess.SetAction([this]() { ReportError(true); });
         }
         Detach();
     }
Connect() [1/2]
void services::HttpClientBasic::Connect () protected
Definition at line 37 of file HttpClientBasic.cpp.
References services::HttpClientConnector::Connect(), connecting, httpClientConnector, idle, and state.
Referenced by Connect().
     {
         assert(state == State::idle);
         state = State::connecting;
         httpClientConnector.Connect(*this);
     }
Connect() [2/2]
void services::HttpClientBasic::Connect (infra::BoundedString url) protected
Definition at line 44 of file HttpClientBasic.cpp.
References Connect(), and url.
     {
         this->url = url;
         Connect();
     }
ConnectionEstablished()
void services::HttpClientBasic::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::HttpClientObserver > client)> && createdClientObserver) final private virtual
Implements services::HttpClientObserverFactory.
Definition at line 113 of file HttpClientBasic.cpp.
References connected, Established(), infra::AccessedBySharedPtr::MakeShared(), sharedAccess, infra::TimerSingleShot::Start(), state, Timeout(), timeoutDuration, and timeoutTimer.
     {
         state = State::connected;
         timeoutTimer.Start(timeoutDuration, [this]() { Timeout(); });
         Established();
         createdClientObserver(sharedAccess.MakeShared(static_cast<services::HttpClientObserver&>(*this)));
     }
ConnectionFailed()
void services::HttpClientBasic::ConnectionFailed (ConnectFailReason reason) final private virtual
Implements services::HttpClientObserverFactory.
Definition at line 121 of file HttpClientBasic.cpp.
References ReportError().
     {
         ReportError(true);
     }
ContentError()
void services::HttpClientBasic::ContentError () protected
Definition at line 60 of file HttpClientBasic.cpp.
References Close(), and contentError.
Referenced by services::HttpClientJson::HeaderAvailable(), and services::HttpClientJson::StatusAvailable().
     {
         contentError = true;
         Close();
     }
Done()
virtual void services::HttpClientBasic::Done () protected pure virtual
Implemented in application::TracingHttpClient.
Referenced by Expire().
Error()
virtual void services::HttpClientBasic::Error (bool intermittentFailure) protected pure virtual
Implemented in application::TracingHttpClient.
Referenced by ReportError().
Established()
void services::HttpClientBasic::Established () protected virtual
Reimplemented in services::HttpClientJson.
Definition at line 83 of file HttpClientBasic.cpp.
Referenced by ConnectionEstablished().
     {}
Expire()
void services::HttpClientBasic::Expire () private
Definition at line 132 of file HttpClientBasic.cpp.
References contentError, Done(), idle, ReportError(), and state.
Referenced by HttpClientBasic().
     {
         if (contentError)
             ReportError(false);
         else
         {
             state = State::idle;
             Done();
         }
     }
Headers()
services::HttpHeaders services::HttpClientBasic::Headers () const protected virtual
Definition at line 78 of file HttpClientBasic.cpp.
References services::noHeaders.
Referenced by services::HttpClientJson::Connected(), and application::TracingHttpClient::Connected().
     {
         return services::noHeaders;
     }
Hostname()
infra::BoundedConstString services::HttpClientBasic::Hostname () const final private virtual
Implements services::HttpClientObserverFactory.
Definition at line 103 of file HttpClientBasic.cpp.
References services::HostFromUrl(), and url.
     {
         return services::HostFromUrl(url);
     }
Path()
infra::BoundedString services::HttpClientBasic::Path () const protected virtual
Definition at line 71 of file HttpClientBasic.cpp.
References infra::BoundedStringBase< T >::begin(), infra::MakeRange(), infra::BoundedStringBase< T >::max_size(), services::PathFromUrl(), infra::BoundedStringBase< T >::size(), and url.
Referenced by services::HttpClientJson::Connected(), and application::TracingHttpClient::Connected().
     {
         auto path = services::PathFromUrl(url);
         auto offset = path.empty() ? url.size() : path.begin() - url.begin();
         return infra::BoundedString(infra::MakeRange(url.begin() + offset, url.begin() + url.max_size() - offset), path.size());
     }
Port()
uint16_t services::HttpClientBasic::Port () const final private virtual
Implements services::HttpClientObserverFactory.
Definition at line 108 of file HttpClientBasic.cpp.
References port.
     {
         return port;
     }
ReportError()
void services::HttpClientBasic::ReportError (bool intermittentFailure) private
Definition at line 143 of file HttpClientBasic.cpp.
References infra::Timer::Cancel(), Error(), idle, state, and timeoutTimer.
Referenced by ClosingConnection(), ConnectionFailed(), Expire(), and Timeout().
     {
         state = State::idle;
         timeoutTimer.Cancel();
         Error(intermittentFailure);
     }
Timeout()
void services::HttpClientBasic::Timeout () private
Definition at line 126 of file HttpClientBasic.cpp.
References Close(), ReportError(), infra::AccessedBySharedPtr::SetAction(), and sharedAccess.
Referenced by ConnectionEstablished().
     {
         sharedAccess.SetAction([this]() { ReportError(true); });
         Close();
     }
Url()
infra::BoundedString services::HttpClientBasic::Url () const protected
Definition at line 66 of file HttpClientBasic.cpp.
References url.
     {
         return url;
     }
Member Data Documentation
contentError
bool services::HttpClientBasic::contentError = false private
Definition at line 68 of file HttpClientBasic.hpp.
Referenced by ContentError(), and Expire().
httpClientConnector
services::HttpClientConnector& services::HttpClientBasic::httpClientConnector private
Definition at line 60 of file HttpClientBasic.hpp.
Referenced by Cancel(), and Connect().
port
uint16_t services::HttpClientBasic::port private
Definition at line 63 of file HttpClientBasic.hpp.
Referenced by Port().
sharedAccess
infra::AccessedBySharedPtr services::HttpClientBasic::sharedAccess private
Definition at line 61 of file HttpClientBasic.hpp.
Referenced by Cancel(), ClosingConnection(), ConnectionEstablished(), and Timeout().
state
State services::HttpClientBasic::state = State::idle private
Definition at line 67 of file HttpClientBasic.hpp.
Referenced by Cancel(), Close(), ClosingConnection(), Connect(), ConnectionEstablished(), Expire(), and ReportError().
timeoutDuration
infra::Duration services::HttpClientBasic::timeoutDuration private
Definition at line 65 of file HttpClientBasic.hpp.
Referenced by ConnectionEstablished().
timeoutTimer
infra::TimerSingleShot services::HttpClientBasic::timeoutTimer private
Definition at line 66 of file HttpClientBasic.hpp.
Referenced by BodyComplete(), Close(), ConnectionEstablished(), and ReportError().
url
infra::BoundedString services::HttpClientBasic::url private
Definition at line 62 of file HttpClientBasic.hpp.
Referenced by Connect(), Hostname(), Path(), and Url().
The documentation for this class was generated from the following files:
HttpClientBasic.hpp
HttpClientBasic.cpp