EMil: TestInverseLogicPin.cpp File Reference
TestInverseLogicPin.cpp File Reference
Classes
class InverseLogicPinTest
Functions
TEST_F (InverseLogicPinTest, GpioPinGetValue)
TEST_F (InverseLogicPinTest, GpioPinTriggerOnChange)
TEST_F (InverseLogicPinTest, GpioPinSetValue)
TEST_F (InverseLogicPinTest, GpioPinGetOutputValue)
Function Documentation
TEST_F() [1/4]
TEST_F (InverseLogicPinTest , GpioPinGetValue)
Definition at line 21 of file TestInverseLogicPin.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and hal::InputPin::Get().
 {
     hal::InputPin pin(gpioPin);
     basePin.SetStubState(true);
     EXPECT_FALSE(pin.Get());
     basePin.SetStubState(false);
     EXPECT_TRUE(pin.Get());
 }
TEST_F() [2/4]
TEST_F (InverseLogicPinTest , GpioPinTriggerOnChange)
Definition at line 31 of file TestInverseLogicPin.cpp.
References hal::InputPin::EnableInterrupt(), and hal::fallingEdge.
 {
     hal::InputPin pin(gpioPin);
     infra::MockCallback<void()> callback;
     EXPECT_CALL(callback, callback());
     pin.EnableInterrupt([&callback]() { callback.callback(); }, hal::InterruptTrigger::fallingEdge);
     basePin.SetStubState(true);
 }
TEST_F() [3/4]
TEST_F (InverseLogicPinTest , GpioPinSetValue)
Definition at line 42 of file TestInverseLogicPin.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), and hal::OutputPin::Set().
 {
     hal::OutputPin pin(gpioPin);
     pin.Set(true);
     EXPECT_FALSE(basePin.GetStubState());
     pin.Set(false);
     EXPECT_TRUE(basePin.GetStubState());
 }
TEST_F() [4/4]
TEST_F (InverseLogicPinTest , GpioPinGetOutputValue)
Definition at line 52 of file TestInverseLogicPin.cpp.
References EXPECT_FALSE(), EXPECT_TRUE(), hal::OutputPin::GetOutputLatch(), and hal::OutputPin::Set().
 {
     hal::OutputPin pin(gpioPin);
     pin.Set(true);
     EXPECT_TRUE(pin.GetOutputLatch());
     pin.Set(false);
     EXPECT_FALSE(pin.GetOutputLatch());
 }