EMil: application::ImageEncryptorAes Class Reference
application::ImageEncryptorAes Class Reference
#include <ImageEncryptorAes.hpp>
Public Member Functions
ImageEncryptorAes (RandomNumberGenerator &randomNumberGenerator, infra::ConstByteRange key)
virtual uint32_t EncryptionAndMacMethod () const override
virtual std::vector< uint8_t > Secure (const std::vector< uint8_t > &data) const override
Public Member Functions inherited from application::ImageSecurity
ImageSecurity ()=default
ImageSecurity (const ImageSecurity &)=delete
ImageSecurity & operator= (const ImageSecurity &)=delete
Static Public Attributes
static const uint32_t encryptionAndMacMethod = 1
static const std::size_t blockLength = 16
Private Member Functions
bool CheckDecryption (const std::vector< uint8_t > &original, const std::vector< uint8_t > &encrypted) const
Private Attributes
RandomNumberGenerator & randomNumberGenerator
infra::ConstByteRange key
Additional Inherited Members
Protected Member Functions inherited from application::ImageSecurity
~ImageSecurity ()=default
Detailed Description
Definition at line 12 of file ImageEncryptorAes.hpp.
Constructor & Destructor Documentation
ImageEncryptorAes()
application::ImageEncryptorAes::ImageEncryptorAes (RandomNumberGenerator & randomNumberGenerator, infra::ConstByteRange key)
Definition at line 14 of file ImageEncryptorAes.cpp.
         : randomNumberGenerator(randomNumberGenerator)
         , key(key)
     {}
Member Function Documentation
CheckDecryption()
bool application::ImageEncryptorAes::CheckDecryption (const std::vector< uint8_t > & original, const std::vector< uint8_t > & encrypted) const private
Definition at line 47 of file ImageEncryptorAes.cpp.
References infra::MemoryRange< T >::begin(), blockLength, infra::data, and key.
Referenced by Secure().
     {
         std::vector<uint8_t> counter(encrypted.begin(), encrypted.begin() + blockLength);
         std::vector<uint8_t> currentStreamBlock(counter.size(), 0);
         std::size_t currentStreamBlockOffset = currentStreamBlock.size();
         std::vector<uint8_t> decrypted(encrypted.begin() + blockLength, encrypted.end());
         infra::ByteRange data(decrypted.data(), decrypted.data() + decrypted.size());
         while (!data.empty())
         {
             if (currentStreamBlockOffset == currentStreamBlock.size())
             {
                 AES128_ECB_encrypt(counter.data(), key.begin(), currentStreamBlock.data());
                 currentStreamBlockOffset = 0;
                 for (std::size_t i = counter.size(); i != 0; --i)
                     if (++counter[i - 1] != 0)
                         break;
             }
             data.front() ^= currentStreamBlock[currentStreamBlockOffset];
             data.pop_front();
             ++currentStreamBlockOffset;
         }
         return mbedtls_aes_self_test(0) == 0 && decrypted == original;
     }
EncryptionAndMacMethod()
uint32_t application::ImageEncryptorAes::EncryptionAndMacMethod () const override virtual
Implements application::ImageSecurity.
Definition at line 19 of file ImageEncryptorAes.cpp.
References encryptionAndMacMethod.
     {
         return encryptionAndMacMethod;
     }
Secure()
std::vector< uint8_t > application::ImageEncryptorAes::Secure (const std::vector< uint8_t > & data) const override virtual
Implements application::ImageSecurity.
Definition at line 24 of file ImageEncryptorAes.cpp.
References infra::MemoryRange< T >::begin(), blockLength, CheckDecryption(), infra::data, application::RandomNumberGenerator::Generate(), key, randomNumberGenerator, and infra::MemoryRange< T >::size().
     {
         std::vector<uint8_t> counter = randomNumberGenerator.Generate(blockLength);
         mbedtls_aes_context ctx;
         mbedtls_aes_init(&ctx);
         mbedtls_aes_setkey_enc(&ctx, key.begin(), key.size() * 8);
         std::vector<uint8_t> result = counter;
         result.resize(result.size() + data.size(), 0);
         size_t offset = 0;
         std::array<uint8_t, blockLength> stream_block = {};
         int ret = mbedtls_aes_crypt_ctr(&ctx, data.size(), &offset, counter.data(), stream_block.data(), data.data(), result.data() + blockLength);     //TICS !INT#030
         if (ret != 0)
             throw std::exception("AES encryption failed");
         if (!CheckDecryption(data, result))
             throw std::exception("AES decryption check failed");
         return result;
     }
Member Data Documentation
blockLength
const std::size_t application::ImageEncryptorAes::blockLength = 16 static
Definition at line 17 of file ImageEncryptorAes.hpp.
Referenced by CheckDecryption(), and Secure().
encryptionAndMacMethod
const uint32_t application::ImageEncryptorAes::encryptionAndMacMethod = 1 static
Definition at line 16 of file ImageEncryptorAes.hpp.
Referenced by EncryptionAndMacMethod().
key
infra::ConstByteRange application::ImageEncryptorAes::key private
Definition at line 28 of file ImageEncryptorAes.hpp.
Referenced by CheckDecryption(), and Secure().
randomNumberGenerator
RandomNumberGenerator& application::ImageEncryptorAes::randomNumberGenerator private
Definition at line 27 of file ImageEncryptorAes.hpp.
Referenced by Secure().
The documentation for this class was generated from the following files:
ImageEncryptorAes.hpp
ImageEncryptorAes.cpp