EMil: TestBoundedList.cpp File Reference
TestBoundedList.cpp File Reference
Classes
class BoundedListConstructionTest
class BoundedListConstructionTest::MonitoredConstructionInt
Functions
TEST (BoundedListTest, TestConstructedEmpty)
TEST (BoundedListTest, TestConstructionWith2Elements)
TEST (BoundedListTest, TestConstructionWithRange)
TEST (BoundedListTest, TestConstructionWithInitializerList)
TEST (BoundedListTest, TestCopyConstruction)
TEST (BoundedListTest, TestMoveConstruction)
TEST (BoundedListTest, TestAssignment)
TEST (BoundedListTest, TestSelfAssignment)
TEST (BoundedListTest, TestMove)
TEST (BoundedListTest, TestBeginAndEnd)
TEST (BoundedListTest, TestFull)
TEST (BoundedListTest, TestFront)
TEST (BoundedListTest, TestBack)
TEST (BoundedListTest, TestAssignRange)
TEST (BoundedListTest, TestAssignN)
TEST (BoundedListTest, TestMoveFromRange)
TEST (BoundedListTest, TestPushFront)
TEST (BoundedListTest, TestPushFrontRvalue)
TEST (BoundedListTest, TestEmplaceFront)
TEST (BoundedListTest, TestPopFront)
TEST (BoundedListTest, TestPushBack)
TEST (BoundedListTest, TestEmplaceBack)
TEST (BoundedListTest, TestPopBack)
TEST (BoundedListTest, TestSwap)
TEST (BoundedListTest, TestSwapDifferentSizes)
TEST (BoundedListTest, TestClear)
TEST (BoundedListTest, TestInsert)
TEST (BoundedListTest, TestInsertRvalue)
TEST (BoundedListTest, TestErase)
TEST (BoundedListTest, TestEraseAllAfter)
TEST (BoundedListTest, TestEraseAllAfterNothing)
TEST (BoundedListTest, TestRemove)
TEST_F (BoundedListConstructionTest, TestEraseDestruction)
TEST_F (BoundedListConstructionTest, TestEraseAllAfterDestruction)
TEST (BoundedListTest, IteratorCopyConstruct)
TEST (BoundedListTest, IteratorArrow)
TEST (BoundedListTest, IteratorPostInc)
TEST (BoundedListTest, TestEquals)
TEST (BoundedListTest, TestUnequals)
TEST (BoundedListTest, TestLessThan)
TEST (BoundedListTest, TestGreaterThan)
TEST (BoundedListTest, TestLessThanOrEqual)
TEST (BoundedListTest, TestGreaterThanOrEqual)
Function Documentation
TEST() [1/41]
TEST (BoundedListTest , TestConstructedEmpty)
Definition at line 7 of file TestBoundedList.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     infra::BoundedList<int>::WithMaxSize<5> list;
     EXPECT_TRUE(list.empty());
     EXPECT_FALSE(list.full());
     EXPECT_EQ(0, list.size());
     EXPECT_EQ(5, list.max_size());
 }
TEST() [2/41]
TEST (BoundedListTest , TestConstructionWith2Elements)
Definition at line 17 of file TestBoundedList.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     EXPECT_FALSE(list.empty());
     EXPECT_FALSE(list.full());
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(4, *list.begin());
     EXPECT_EQ(4, *std::next(list.begin()));
 }
TEST() [3/41]
TEST (BoundedListTest , TestConstructionWithRange)
Definition at line 29 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(0, *list.begin());
     EXPECT_EQ(1, *std::next(list.begin()));
     EXPECT_EQ(2, *std::next(list.begin(), 2));
 }
TEST() [4/41]
TEST (BoundedListTest , TestConstructionWithInitializerList)
Definition at line 41 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list({ 0, 1, 2 });
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(0, *list.begin());
     EXPECT_EQ(1, *std::next(list.begin()));
     EXPECT_EQ(2, *std::next(list.begin(), 2));
 }
TEST() [5/41]
TEST (BoundedListTest , TestCopyConstruction)
Definition at line 52 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> original(std::size_t(2), 4);
     infra::BoundedList<int>::WithMaxSize<5> copy(original);
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(4, copy.front());
 }
TEST() [6/41]
TEST (BoundedListTest , TestMoveConstruction)
Definition at line 61 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_front(2);
     infra::BoundedList<infra::MoveConstructible>::WithMaxSize<5> copy(std::move(original));
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy.front().x);
 }
TEST() [7/41]
TEST (BoundedListTest , TestAssignment)
Definition at line 71 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> original(std::size_t(2), 4);
     infra::BoundedList<int>::WithMaxSize<5> copy;
     copy = original;
     EXPECT_EQ(2, copy.size());
     EXPECT_EQ(4, copy.front());
 }
TEST() [8/41]
TEST (BoundedListTest , TestSelfAssignment)
Definition at line 81 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> original(std::size_t(2), 4);
     original = original;
     EXPECT_EQ(2, original.size());
     EXPECT_EQ(4, original.front());
 }
TEST() [9/41]
TEST (BoundedListTest , TestMove)
Definition at line 90 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_front(2);
     infra::BoundedList<infra::MoveConstructible>::WithMaxSize<5> copy;
     copy = std::move(original);
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy.front().x);
 }
TEST() [10/41]
TEST (BoundedListTest , TestBeginAndEnd)
Definition at line 101 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(list.end(), std::next(list.begin(), 3));
     EXPECT_EQ(list.cbegin(), list.begin());
     EXPECT_EQ(list.cend(), list.end());
     EXPECT_EQ(0, *list.begin());
 }
TEST() [11/41]
TEST (BoundedListTest , TestFull)
Definition at line 113 of file TestBoundedList.cpp.
References EXPECT_TRUE().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(5), 4);
     EXPECT_TRUE(list.full());
 }
TEST() [12/41]
TEST (BoundedListTest , TestFront)
Definition at line 120 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(0, list.front());
     EXPECT_EQ(0, static_cast<const infra::BoundedList<int>&>(list).front());
 }
TEST() [13/41]
TEST (BoundedListTest , TestBack)
Definition at line 129 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list(range, range + 3);
     EXPECT_EQ(2, list.back());
     EXPECT_EQ(2, static_cast<const infra::BoundedList<int>&>(list).back());
 }
TEST() [14/41]
TEST (BoundedListTest , TestAssignRange)
Definition at line 138 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list(range, range + 3);
     int otherRange[2] = { 4, 5 };
     list.assign(otherRange, otherRange + 2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(4, list.front());
     EXPECT_EQ(5, *std::next(list.begin()));
 }
TEST() [15/41]
TEST (BoundedListTest , TestAssignN)
Definition at line 151 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list(range, range + 3);
     list.assign(std::size_t(2), 4);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(4, list.front());
     EXPECT_EQ(4, *std::next(list.begin()));
 }
TEST() [16/41]
TEST (BoundedListTest , TestMoveFromRange)
Definition at line 163 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<infra::MoveConstructible>::WithMaxSize<5> original;
     original.emplace_front(2);
     infra::BoundedList<infra::MoveConstructible>::WithMaxSize<5> copy;
     copy.move_from_range(original.begin(), original.end());
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy.front().x);
 }
TEST() [17/41]
TEST (BoundedListTest , TestPushFront)
Definition at line 174 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list;
     int i(1);
     list.push_front(i);
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, list.front());
     ++i;
     list.push_front(i);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, list.front());
 }
TEST() [18/41]
TEST (BoundedListTest , TestPushFrontRvalue)
Definition at line 190 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list;
     list.push_front(1);
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, list.front());
     list.push_front(2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, list.front());
 }
TEST() [19/41]
TEST (BoundedListTest , TestEmplaceFront)
Definition at line 204 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list;
     list.emplace_front(1);
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, list.front());
     list.emplace_front(2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, list.front());
 }
TEST() [20/41]
TEST (BoundedListTest , TestPopFront)
Definition at line 218 of file TestBoundedList.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.pop_front();
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(4, list.front());
     list.pop_front();
     EXPECT_TRUE(list.empty());
 }
TEST() [21/41]
TEST (BoundedListTest , TestPushBack)
Definition at line 231 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.push_back(1);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(1, list.back());
 }
TEST() [22/41]
TEST (BoundedListTest , TestEmplaceBack)
Definition at line 240 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list;
     list.emplace_back(1);
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, list.back());
     list.emplace_back(2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, list.back());
 }
TEST() [23/41]
TEST (BoundedListTest , TestPopBack)
Definition at line 254 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.pop_front();
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(4, list.back());
 }
TEST() [24/41]
TEST (BoundedListTest , TestSwap)
Definition at line 263 of file TestBoundedList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5};
     infra::BoundedList<int>::WithMaxSize<5> list2(range2, range2 + 3);
     swap(list1, list2);
     infra::BoundedList<int>::WithMaxSize<5> expectedList1(range2, range2 + 3);
     infra::BoundedList<int>::WithMaxSize<5> expectedList2(range1, range1 + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [25/41]
TEST (BoundedListTest , TestSwapDifferentSizes)
Definition at line 278 of file TestBoundedList.cpp.
References EXPECT_EQ(), and infra::swap().
 {
     int range1[3] = { 0, 1, 2};
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[2] = { 3, 4};
     infra::BoundedList<int>::WithMaxSize<5> list2(range2, range2 + 2);
     swap(list1, list2);
     infra::BoundedList<int>::WithMaxSize<5> expectedList1(range2, range2 + 2);
     infra::BoundedList<int>::WithMaxSize<5> expectedList2(range1, range1 + 3);
     EXPECT_EQ(expectedList1, list1);
     EXPECT_EQ(expectedList2, list2);
 }
TEST() [26/41]
TEST (BoundedListTest , TestClear)
Definition at line 293 of file TestBoundedList.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(2), 4);
     list.clear();
     EXPECT_EQ(list.size(), 0);
     EXPECT_TRUE(list.empty());
     infra::BoundedList<int>::WithMaxSize<5> expectedList;
     EXPECT_EQ(expectedList, list);
 }
TEST() [27/41]
TEST (BoundedListTest , TestInsert)
Definition at line 305 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     int i(2);
     list.insert(list.begin(), i);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, list.front());
     ++i;
     list.insert(std::next(list.begin()), i);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(3, *std::next(list.begin()));
     ++i;
     list.insert(list.end(), i);
     EXPECT_EQ(4, list.size());
     EXPECT_EQ(4, list.back());
 }
TEST() [28/41]
TEST (BoundedListTest , TestInsertRvalue)
Definition at line 327 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     list.insert(list.begin(), 2);
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, list.front());
     list.insert(std::next(list.begin()), 3);
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(3, *std::next(list.begin()));
     list.insert(list.end(), 4);
     EXPECT_EQ(4, list.size());
     EXPECT_EQ(4, list.back());
 }
TEST() [29/41]
TEST (BoundedListTest , TestErase)
Definition at line 346 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(3), 4);
     list.erase(std::next(list.begin()));
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, std::distance(list.begin(), list.end()));
     list.erase(std::prev(list.end()));
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
     list.erase(list.begin());
     EXPECT_EQ(0, list.size());
     EXPECT_EQ(0, std::distance(list.begin(), list.end()));
 }
TEST() [30/41]
TEST (BoundedListTest , TestEraseAllAfter)
Definition at line 362 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(3), 4);
     list.erase_all_after(list.begin());
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
 }
TEST() [31/41]
TEST (BoundedListTest , TestEraseAllAfterNothing)
Definition at line 371 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     list.erase_all_after(list.begin());
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
 }
TEST() [32/41]
TEST (BoundedListTest , TestRemove)
Definition at line 380 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(3), 4);
     list.remove(*std::next(list.begin()));
     EXPECT_EQ(2, list.size());
     EXPECT_EQ(2, std::distance(list.begin(), list.end()));
     list.remove(list.back());
     EXPECT_EQ(1, list.size());
     EXPECT_EQ(1, std::distance(list.begin(), list.end()));
     list.remove(list.front());
     EXPECT_EQ(0, list.size());
     EXPECT_EQ(0, std::distance(list.begin(), list.end()));
 }
TEST() [33/41]
TEST (BoundedListTest , IteratorCopyConstruct)
Definition at line 443 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedList<int>::iterator i(list.begin());
     EXPECT_EQ(4, *i);
 }
TEST() [34/41]
TEST (BoundedListTest , IteratorArrow)
Definition at line 451 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     EXPECT_EQ(4, *(list.begin().operator->()));
 }
TEST() [35/41]
TEST (BoundedListTest , IteratorPostInc)
Definition at line 458 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<int>::WithMaxSize<5> list(std::size_t(1), 4);
     infra::BoundedList<int>::iterator i(list.begin());
     EXPECT_EQ(4, *i++);
 }
TEST() [36/41]
TEST (BoundedListTest , TestEquals)
Definition at line 466 of file TestBoundedList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5 };
     infra::BoundedList<int>::WithMaxSize<5> list2(range2, range2 + 3);
     int range3[2] = { 0, 1 };
     infra::BoundedList<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 == list1);
     EXPECT_FALSE(list1 == list2);
     EXPECT_FALSE(list1 == deque3);
     EXPECT_FALSE(deque3 == list1);
 }
TEST() [37/41]
TEST (BoundedListTest , TestUnequals)
Definition at line 481 of file TestBoundedList.cpp.
References EXPECT_FALSE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 != list1);
 }
TEST() [38/41]
TEST (BoundedListTest , TestLessThan)
Definition at line 489 of file TestBoundedList.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     int range2[3] = { 0, 4, 5 };
     infra::BoundedList<int>::WithMaxSize<5> list2(range2, range2 + 3);
     int range3[2] = { 0, 1 };
     infra::BoundedList<int>::WithMaxSize<5> deque3(range3, range3 + 2);
     EXPECT_TRUE(list1 < list2);
     EXPECT_FALSE(list1 < deque3);
     EXPECT_FALSE(list1 < list1);
 }
TEST() [39/41]
TEST (BoundedListTest , TestGreaterThan)
Definition at line 503 of file TestBoundedList.cpp.
References EXPECT_FALSE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_FALSE(list1 > list1);
 }
TEST() [40/41]
TEST (BoundedListTest , TestLessThanOrEqual)
Definition at line 511 of file TestBoundedList.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 <= list1);
 }
TEST() [41/41]
TEST (BoundedListTest , TestGreaterThanOrEqual)
Definition at line 519 of file TestBoundedList.cpp.
References EXPECT_TRUE().
 {
     int range1[3] = { 0, 1, 2 };
     infra::BoundedList<int>::WithMaxSize<5> list1(range1, range1 + 3);
     EXPECT_TRUE(list1 >= list1);
 }
TEST_F() [1/2]
TEST_F (BoundedListConstructionTest , TestEraseDestruction)
Definition at line 412 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     EXPECT_CALL(constructionMonitor, Construct(testing::_));
     infra::BoundedList<MonitoredConstructionInt>::WithMaxSize<1> monitoredList;
     monitoredList.emplace_front(constructionMonitor);
     EXPECT_EQ(1, monitoredList.size());
     EXPECT_CALL(constructionMonitor, Destruct(testing::_));
     monitoredList.erase(monitoredList.begin());
     EXPECT_EQ(0, monitoredList.size());
 }
TEST_F() [2/2]
TEST_F (BoundedListConstructionTest , TestEraseAllAfterDestruction)
Definition at line 425 of file TestBoundedList.cpp.
References EXPECT_EQ().
 {
     infra::BoundedList<MonitoredConstructionInt>::WithMaxSize<5> monitoredList;
     EXPECT_CALL(constructionMonitor, Construct(testing::_)).Times(3);
     monitoredList.emplace_front(constructionMonitor);
     monitoredList.emplace_front(constructionMonitor);
     monitoredList.emplace_front(constructionMonitor);
     EXPECT_EQ(3, monitoredList.size());
     EXPECT_CALL(constructionMonitor, Destruct(testing::_)).Times(2);
     monitoredList.erase_all_after(monitoredList.begin());
     EXPECT_EQ(1, monitoredList.size());
     EXPECT_CALL(constructionMonitor, Destruct(testing::_)).Times(1);
 }