EMil: TestHttpServer.cpp File Reference
TestHttpServer.cpp File Reference
Classes
class HttpServerTest
class HttpServerErrorTest
Functions
TEST_F (HttpServerTest, accept_connection)
TEST_F (HttpServerTest, accept_ipv6_connection)
TEST_F (HttpServerTest, wrong_start_url_results_in_error)
TEST_F (HttpServerTest, too_long_http_request_results_in_error)
TEST_F (HttpServerTest, unsupported_verb_results_in_error)
TEST_F (HttpServerTest, request_results_in_get)
TEST_F (HttpServerTest, double_request_results_in_closed_connection)
TEST_F (HttpServerTest, split_message_is_accepted)
TEST_F (HttpServerTest, send_100_response_when_expect_100_in_header)
TEST_F (HttpServerTest, second_connection_forces_idle_connection_to_close)
TEST_F (HttpServerTest, non_idle_connection_is_not_closed_by_second_connection)
TEST_F (HttpServerTest, choose_correct_url)
Function Documentation
TEST_F() [1/12]
TEST_F (HttpServerTest , accept_connection)
Definition at line 78 of file TestHttpServer.cpp.
References services::IPv4AddressLocalHost().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [2/12]
TEST_F (HttpServerTest , accept_ipv6_connection)
Definition at line 84 of file TestHttpServer.cpp.
References services::IPv6AddressLocalHost().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv6AddressLocalHost());
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [3/12]
TEST_F (HttpServerTest , wrong_start_url_results_in_error)
Definition at line 90 of file TestHttpServer.cpp.
References data, services::IPv4AddressLocalHost(), and infra::MakeStringByteRange().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     infra::ConstByteRange data = infra::MakeStringByteRange("PUT /path HTTP/1.1 \r\n\r\n {}");
     EXPECT_CALL(httpPage, ServesRequest(testing::_)).WillOnce(testing::Return(false));
     connection.SimulateDataReceived(data);
     ExecuteAllActions();
     CheckHttpResponse("404 Not Found", "{}");
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [4/12]
TEST_F (HttpServerTest , too_long_http_request_results_in_error)
Definition at line 103 of file TestHttpServer.cpp.
References data, services::IPv4AddressLocalHost(), and infra::MakeStringByteRange().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     infra::ConstByteRange data = infra::MakeStringByteRange("PUT /path/subpath/subpath/subpath/subpath/subpath/subpath/subpath HTTP/1.1 \r\n Content-Type: application/json \r\n Host: 192.168.0.98 \r\n Connection: Close \r\n\r\n { \"data\":\"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890\" }");
     connection.SimulateDataReceived(data);
     ExecuteAllActions();
     CheckHttpResponse("500 Internal Server Error", R"({ "error": "Out of memory" })");
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [5/12]
TEST_F (HttpServerTest , unsupported_verb_results_in_error)
Definition at line 115 of file TestHttpServer.cpp.
References data, services::IPv4AddressLocalHost(), and infra::MakeStringByteRange().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     infra::ConstByteRange data = infra::MakeStringByteRange("UPDATE /path HTTP/1.1 \r\n\r\n {}");
     connection.SimulateDataReceived(data);
     ExecuteAllActions();
     CheckHttpResponse("400 Bad request", "{}");
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [6/12]
TEST_F (HttpServerTest , request_results_in_get)
Definition at line 127 of file TestHttpServer.cpp.
References services::get, and services::IPv4AddressLocalHost().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     ExpectPageServerRequest(services::HttpVerb::get, "GET /path HTTP/1.1 \r\n\r\n");
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [7/12]
TEST_F (HttpServerTest , double_request_results_in_closed_connection)
Definition at line 135 of file TestHttpServer.cpp.
References data, services::get, services::IPv4AddressLocalHost(), and infra::MakeStringByteRange().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     ExpectPageServerRequest(services::HttpVerb::get, "GET /path HTTP/1.1 \r\n\r\n");
     EXPECT_CALL(connection, CloseAndDestroyMock());
     infra::ConstByteRange data = infra::MakeStringByteRange("GET /path HTTP/1.1 \r\n\r\n");
     connection.SimulateDataReceived(data);
     ExecuteAllActions();
     testing::Mock::VerifyAndClearExpectations(&connection);
 }
TEST_F() [8/12]
TEST_F (HttpServerTest , split_message_is_accepted)
Definition at line 148 of file TestHttpServer.cpp.
References services::get, services::IPv4AddressLocalHost(), and infra::MakeStringByteRange().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     std::string rest = R"({"other":"param"})";
     ExpectPageServerRequest(services::HttpVerb::get, std::string("GET /path") +
         " HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: 192.168.1.56\r\nContent-Length: " + std::to_string(rest.size()) + "\r\nContent-Type: application-json\r\n\r\n");
     connection.SimulateDataReceived(infra::MakeStringByteRange(rest));
     ExecuteAllActions();
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [9/12]
TEST_F (HttpServerTest , send_100_response_when_expect_100_in_header)
Definition at line 162 of file TestHttpServer.cpp.
References EXPECT_EQ(), services::get, and services::IPv4AddressLocalHost().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     ExpectPageServerRequest(services::HttpVerb::get, "GET /path HTTP/1.1 \r\nExpect: 100-continue\r\n\r\n");
     SendResponse("", "", "");
     ExecuteAllActions();
     std::string expectedResponseFirstPart = std::string("HTTP/1.1 ") + "100 Continue" + "\r\n" +
         "Content-Length: 0" + "\r\n" +
         "Content-Type: application/json\r\n" +
         "Strict-Transport-Security: max-age=31536000\r\n\r\n";
     std::vector<uint8_t> responseFirstPart = connection.sentData;
     responseFirstPart.erase(responseFirstPart.begin() + expectedResponseFirstPart.size(), responseFirstPart.end());
     connection.sentData.erase(connection.sentData.begin(), connection.sentData.begin() + expectedResponseFirstPart.size());
     EXPECT_EQ(std::vector<uint8_t>(expectedResponseFirstPart.begin(), expectedResponseFirstPart.end()), responseFirstPart);
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [10/12]
TEST_F (HttpServerTest , second_connection_forces_idle_connection_to_close)
Definition at line 184 of file TestHttpServer.cpp.
References services::IPv4AddressLocalHost().
 {
     testing::StrictMock<services::ConnectionMock> connectionFirst;
     EXPECT_CALL(connectionFirst, MaxSendStreamSize()).WillOnce(testing::Return(555));
     EXPECT_CALL(connectionFirst, RequestSendStream(555));
     connectionFactoryMock.NewConnection(connectionFirst, services::IPv4AddressLocalHost());
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     EXPECT_CALL(connectionFirst, CloseAndDestroy());
     ForwardTime(std::chrono::seconds(1));
     testing::Mock::VerifyAndClearExpectations(&connectionFirst);
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }
TEST_F() [11/12]
TEST_F (HttpServerTest , non_idle_connection_is_not_closed_by_second_connection)
Definition at line 200 of file TestHttpServer.cpp.
References services::get, services::IPv4AddressLocalHost(), and infra::UnOwnedSharedPtr().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     ExpectPageServerRequest(services::HttpVerb::get, "GET /path HTTP/1.1 \r\nExpect: 100-continue\r\n\r\n");
     testing::StrictMock<services::ConnectionStub> connectionSecond;
     infra::SharedPtr<services::ConnectionStub> connectionSecondPtr(infra::UnOwnedSharedPtr(connectionSecond));
     connectionFactoryMock.NewConnection(connectionSecond, services::IPv4AddressLocalHost());
     EXPECT_CALL(connection, CloseAndDestroyMock());
     SendResponse("", "", "");
 }
TEST_F() [12/12]
TEST_F (HttpServerTest , choose_correct_url)
Definition at line 214 of file TestHttpServer.cpp.
References services::get, and services::IPv4AddressLocalHost().
 {
     connectionFactoryMock.NewConnection(connection, services::IPv4AddressLocalHost());
     testing::StrictMock<services::HttpPageMock> secondHttpPage;
     httpServer.AddPage(secondHttpPage);
     EXPECT_CALL(secondHttpPage, ServesRequest(testing::_)).WillOnce(testing::Return(false));
     ExpectPageServerRequest(services::HttpVerb::get, "GET /path HTTP/1.1 \r\nExpect: 100-continue\r\n\r\n");
     EXPECT_CALL(connection, CloseAndDestroyMock());
 }