EMil: infra::StreamReader Class Reference
infra::StreamReader Class Reference abstract
#include <InputStream.hpp>
Public Member Functions
virtual void Extract (ByteRange range, StreamErrorPolicy &errorPolicy)=0
virtual uint8_t Peek (StreamErrorPolicy &errorPolicy)=0
virtual ConstByteRange ExtractContiguousRange (std::size_t max)=0
virtual ConstByteRange PeekContiguousRange (std::size_t start)=0
virtual bool Empty () const =0
virtual std::size_t Available () const =0
Protected Member Functions
StreamReader ()=default
StreamReader (const StreamReader &other)=delete
StreamReader & operator= (const StreamReader &other)=delete
~StreamReader ()=default
Detailed Description
Definition at line 16 of file InputStream.hpp.
Constructor & Destructor Documentation
StreamReader() [1/2]
infra::StreamReader::StreamReader () protected default
StreamReader() [2/2]
infra::StreamReader::StreamReader (const StreamReader & other) protected delete
~StreamReader()
infra::StreamReader::~StreamReader () protected default
Member Function Documentation
Available()
virtual std::size_t infra::StreamReader::Available () const pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::CountingStreamReader, infra::StdStringInputStreamReader, infra::StdVectorInputStreamReader, infra::StringInputStreamReader, infra::LimitedStreamReader, infra::JsonInputStreamReader, and services::TracingStreamReader.
Referenced by infra::LimitedStreamReader::Available(), services::TracingStreamReader::Available(), infra::CountingStreamReader::Available(), and infra::InputStream::Available().
Empty()
virtual bool infra::StreamReader::Empty () const pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::CountingStreamReader, infra::StdStringInputStreamReader, infra::StdVectorInputStreamReader, infra::StringInputStreamReader, infra::LimitedStreamReader, infra::JsonInputStreamReader, and services::TracingStreamReader.
Referenced by services::SntpClient::DataReceived(), services::TracingStreamReader::Empty(), infra::LimitedStreamReader::Empty(), infra::CountingStreamReader::Empty(), infra::InputStream::Empty(), infra::TextInputStream::ReadAsDecimal(), and infra::TextInputStream::ReadAsHex().
Extract()
virtual void infra::StreamReader::Extract (ByteRange range, StreamErrorPolicy & errorPolicy) pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::CountingStreamReader, infra::StdStringInputStreamReader, infra::StdVectorInputStreamReader, infra::StringInputStreamReader, infra::LimitedStreamReader, infra::JsonInputStreamReader, and services::TracingStreamReader.
Referenced by services::TracingStreamReader::Extract(), infra::LimitedStreamReader::Extract(), infra::CountingStreamReader::Extract(), infra::DataInputStream::operator>>(), infra::TextInputStream::operator>>(), infra::TextInputStream::ReadAsDecimal(), infra::TextInputStream::ReadAsHex(), and infra::TextInputStream::SkipSpaces().
ExtractContiguousRange()
virtual ConstByteRange infra::StreamReader::ExtractContiguousRange (std::size_t max) pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::CountingStreamReader, infra::StdStringInputStreamReader, infra::StdVectorInputStreamReader, infra::StringInputStreamReader, infra::LimitedStreamReader, infra::JsonInputStreamReader, and services::TracingStreamReader.
Referenced by infra::InputStream::ContiguousRange(), services::TracingStreamReader::ExtractContiguousRange(), infra::LimitedStreamReader::ExtractContiguousRange(), and infra::CountingStreamReader::ExtractContiguousRange().
operator=()
StreamReader& infra::StreamReader::operator= (const StreamReader & other) protected delete
Peek()
virtual uint8_t infra::StreamReader::Peek (StreamErrorPolicy & errorPolicy) pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::CountingStreamReader, infra::StdStringInputStreamReader, infra::StdVectorInputStreamReader, infra::StringInputStreamReader, infra::LimitedStreamReader, infra::JsonInputStreamReader, and services::TracingStreamReader.
Referenced by infra::TextInputStream::operator>>(), services::TracingStreamReader::Peek(), infra::LimitedStreamReader::Peek(), infra::CountingStreamReader::Peek(), infra::TextInputStream::ReadAsDecimal(), infra::TextInputStream::ReadAsHex(), and infra::TextInputStream::SkipSpaces().
PeekContiguousRange()
virtual ConstByteRange infra::StreamReader::PeekContiguousRange (std::size_t start) pure virtual
Implemented in services::ConnectionSerial::SerialConnectionStreamReader, infra::ByteInputStreamReader, infra::BoundedDequeInputStreamReader, infra::CountingStreamReader, infra::StdStringInputStreamReader, infra::StdVectorInputStreamReader, infra::StringInputStreamReader, infra::LimitedStreamReader, infra::JsonInputStreamReader, and services::TracingStreamReader.
Referenced by infra::CountingStreamReader::PeekContiguousRange(), and infra::InputStream::PeekContiguousRange().
The documentation for this class was generated from the following file:
InputStream.hpp