EMil: application::Decryptor Class Reference
application::Decryptor Class Reference abstract
#include <Decryptor.hpp>
Public Member Functions
virtual infra::ByteRange StateBuffer ()=0
virtual void Reset ()=0
virtual void DecryptPart (infra::ByteRange data)=0
virtual bool DecryptAndAuthenticate (infra::ByteRange data)=0
Protected Member Functions
~Decryptor ()=default
Detailed Description
Definition at line 8 of file Decryptor.hpp.
Constructor & Destructor Documentation
~Decryptor()
application::Decryptor::~Decryptor () protected default
Member Function Documentation
DecryptAndAuthenticate()
virtual bool application::Decryptor::DecryptAndAuthenticate (infra::ByteRange data) pure virtual
Implemented in application::DecryptorAesMbedTls, application::DecryptorXtea, application::DecryptorAesTiny, and application::DecryptorNone.
Referenced by application::SecondStageToRamLoader::TryLoadImage().
DecryptPart()
virtual void application::Decryptor::DecryptPart (infra::ByteRange data) pure virtual
Implemented in application::DecryptorAesMbedTls, application::DecryptorXtea, application::DecryptorAesTiny, and application::DecryptorNone.
Referenced by application::SecondStageToRamLoader::TryLoadImage(), and application::ImageUpgraderInternalFlash::Upgrade().
Reset()
virtual void application::Decryptor::Reset () pure virtual
Implemented in application::DecryptorAesMbedTls, application::DecryptorXtea, application::DecryptorAesTiny, and application::DecryptorNone.
Referenced by application::SecondStageToRamLoader::TryLoadImage().
StateBuffer()
virtual infra::ByteRange application::Decryptor::StateBuffer () pure virtual
Implemented in application::DecryptorAesMbedTls, application::DecryptorXtea, application::DecryptorAesTiny, and application::DecryptorNone.
Referenced by application::SecondStageToRamLoader::TryLoadImage().
The documentation for this class was generated from the following file:
Decryptor.hpp