EMil: infra::IntrusiveForwardList< T > Class Template Reference
infra::IntrusiveForwardList< T > Class Template Reference
#include <IntrusiveForwardList.hpp>
Public Types
typedef detail::IntrusiveForwardListNode< T > NodeType
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef detail::IntrusiveForwardListIterator< T > iterator
typedef detail::IntrusiveForwardListIterator< const T > const_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef std::size_t size_type
Public Member Functions
IntrusiveForwardList ()
template<class InputIterator >
IntrusiveForwardList (InputIterator first, InputIterator last)
IntrusiveForwardList (const IntrusiveForwardList &other)=delete
IntrusiveForwardList (IntrusiveForwardList &&other)
IntrusiveForwardList & operator= (const IntrusiveForwardList &other)=delete
IntrusiveForwardList & operator= (IntrusiveForwardList &&other)
~IntrusiveForwardList ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
bool empty () const
bool has_element (const_reference value) const
reference front ()
const_reference front () const
void push_front (const_reference value)
void pop_front ()
void insert_after (const_iterator position, const_reference value)
void erase_after (const_reference value)
void erase_slow (const_reference value)
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void swap (IntrusiveForwardList &other)
void clear ()
bool operator== (const IntrusiveForwardList &other) const
bool operator!= (const IntrusiveForwardList &other) const
bool operator< (const IntrusiveForwardList &other) const
bool operator<= (const IntrusiveForwardList &other) const
bool operator> (const IntrusiveForwardList &other) const
bool operator>= (const IntrusiveForwardList &other) const
Private Attributes
detail::IntrusiveForwardListNode< T > * beginNode
Detailed Description
template<class T>
class infra::IntrusiveForwardList< T >
Definition at line 21 of file IntrusiveForwardList.hpp.
Member Typedef Documentation
const_iterator
template<class T> typedef detail::IntrusiveForwardListIterator<const T> infra::IntrusiveForwardList< T >::const_iterator
Definition at line 32 of file IntrusiveForwardList.hpp.
const_pointer
template<class T> typedef const T* infra::IntrusiveForwardList< T >::const_pointer
Definition at line 30 of file IntrusiveForwardList.hpp.
const_reference
template<class T> typedef const T& infra::IntrusiveForwardList< T >::const_reference
Definition at line 28 of file IntrusiveForwardList.hpp.
difference_type
template<class T> typedef std::iterator_traits<iterator>::difference_type infra::IntrusiveForwardList< T >::difference_type
Definition at line 33 of file IntrusiveForwardList.hpp.
iterator
template<class T> typedef detail::IntrusiveForwardListIterator<T> infra::IntrusiveForwardList< T >::iterator
Definition at line 31 of file IntrusiveForwardList.hpp.
NodeType
template<class T> typedef detail::IntrusiveForwardListNode<T> infra::IntrusiveForwardList< T >::NodeType
Definition at line 24 of file IntrusiveForwardList.hpp.
pointer
template<class T> typedef T* infra::IntrusiveForwardList< T >::pointer
Definition at line 29 of file IntrusiveForwardList.hpp.
reference
template<class T> typedef T& infra::IntrusiveForwardList< T >::reference
Definition at line 27 of file IntrusiveForwardList.hpp.
size_type
template<class T> typedef std::size_t infra::IntrusiveForwardList< T >::size_type
Definition at line 34 of file IntrusiveForwardList.hpp.
value_type
template<class T> typedef T infra::IntrusiveForwardList< T >::value_type
Definition at line 26 of file IntrusiveForwardList.hpp.
Constructor & Destructor Documentation
IntrusiveForwardList() [1/4]
template<class T > infra::IntrusiveForwardList< T >::IntrusiveForwardList ()
Definition at line 160 of file IntrusiveForwardList.hpp.
         : beginNode(nullptr)
     {}
IntrusiveForwardList() [2/4]
template<class T > template<class InputIterator > infra::IntrusiveForwardList< T >::IntrusiveForwardList (InputIterator first, InputIterator last)
Definition at line 166 of file IntrusiveForwardList.hpp.
         : beginNode(nullptr)
     {
         assign(first, last);
     }
IntrusiveForwardList() [3/4]
template<class T> infra::IntrusiveForwardList< T >::IntrusiveForwardList (const IntrusiveForwardList< T > & other) delete
IntrusiveForwardList() [4/4]
template<class T > infra::IntrusiveForwardList< T >::IntrusiveForwardList (IntrusiveForwardList< T > && other)
Definition at line 173 of file IntrusiveForwardList.hpp.
         : beginNode(other.beginNode)
     {
         other.beginNode = nullptr;
     }
~IntrusiveForwardList()
template<class T > infra::IntrusiveForwardList< T >::~IntrusiveForwardList ()
Definition at line 189 of file IntrusiveForwardList.hpp.
     {}
Member Function Documentation
assign()
template<class T > template<class InputIterator > void infra::IntrusiveForwardList< T >::assign (InputIterator first, InputIterator last)
Definition at line 303 of file IntrusiveForwardList.hpp.
     {
         clear();
         iterator current;
         while (first != last)
         {
             if (empty())
             {
                 push_front(*first);
                 current = begin();
             }
             else
             {
                 insert_after(current, *first);
                 ++current;
             }
             ++first;
         }
     }
begin() [1/2]
template<class T > IntrusiveForwardList< T >::iterator infra::IntrusiveForwardList< T >::begin ()
Definition at line 193 of file IntrusiveForwardList.hpp.
Referenced by infra::IntrusiveForwardList< infra::Timer >::operator<().
     {
         return iterator(beginNode);
     }
begin() [2/2]
template<class T > IntrusiveForwardList< T >::const_iterator infra::IntrusiveForwardList< T >::begin () const
Definition at line 199 of file IntrusiveForwardList.hpp.
     {
         return const_iterator(beginNode);
     }
cbegin()
template<class T > IntrusiveForwardList< T >::const_iterator infra::IntrusiveForwardList< T >::cbegin () const
Definition at line 217 of file IntrusiveForwardList.hpp.
     {
         return begin();
     }
cend()
template<class T > IntrusiveForwardList< T >::const_iterator infra::IntrusiveForwardList< T >::cend () const
Definition at line 223 of file IntrusiveForwardList.hpp.
     {
         return end();
     }
clear()
template<class T > void infra::IntrusiveForwardList< T >::clear ()
Definition at line 331 of file IntrusiveForwardList.hpp.
     {
         beginNode = nullptr;
     }
empty()
template<class T > bool infra::IntrusiveForwardList< T >::empty () const
Definition at line 229 of file IntrusiveForwardList.hpp.
     {
         return beginNode == nullptr;
     }
end() [1/2]
template<class T > IntrusiveForwardList< T >::iterator infra::IntrusiveForwardList< T >::end ()
Definition at line 205 of file IntrusiveForwardList.hpp.
Referenced by infra::IntrusiveForwardList< infra::Timer >::operator<().
     {
         return iterator();
     }
end() [2/2]
template<class T > IntrusiveForwardList< T >::const_iterator infra::IntrusiveForwardList< T >::end () const
Definition at line 211 of file IntrusiveForwardList.hpp.
     {
         return const_iterator();
     }
erase_after()
template<class T > void infra::IntrusiveForwardList< T >::erase_after (const_reference value)
Definition at line 280 of file IntrusiveForwardList.hpp.
     {
         NodeType& node = const_cast<reference>(value);
         node.next = node.next->next;
     }
erase_slow()
template<class T > void infra::IntrusiveForwardList< T >::erase_slow (const_reference value)
Definition at line 287 of file IntrusiveForwardList.hpp.
     {
         iterator previous;
         for (iterator index = begin(); index != end(); previous = index++)
             if (&*index == &value)
             {
                 if (index != begin())
                     erase_after(*previous);
                 else
                     pop_front();
                 break;
             }
     }
front() [1/2]
template<class T > IntrusiveForwardList< T >::reference infra::IntrusiveForwardList< T >::front ()
Definition at line 245 of file IntrusiveForwardList.hpp.
     {
         return static_cast<T&>(*beginNode);
     }
front() [2/2]
template<class T > IntrusiveForwardList< T >::const_reference infra::IntrusiveForwardList< T >::front () const
Definition at line 251 of file IntrusiveForwardList.hpp.
     {
         return static_cast<T&>(*beginNode);
     }
has_element()
template<class T > bool infra::IntrusiveForwardList< T >::has_element (const_reference value) const
Definition at line 235 of file IntrusiveForwardList.hpp.
     {
         for (const_reference item : *this)
             if (&item == &value)
                 return true;
         return false;
     }
insert_after()
template<class T > void infra::IntrusiveForwardList< T >::insert_after (const_iterator position, const_reference value)
Definition at line 272 of file IntrusiveForwardList.hpp.
     {
         NodeType& node = const_cast<reference>(value);
         node.next = const_cast<NodeType*>(position.mNode)->next;
         const_cast<NodeType*>(position.mNode)->next = &node;
     }
operator!=()
template<class T > bool infra::IntrusiveForwardList< T >::operator!= (const IntrusiveForwardList< T > & other) const
Definition at line 355 of file IntrusiveForwardList.hpp.
     {
         return !(*this == other);
     }
operator<()
template<class T > bool infra::IntrusiveForwardList< T >::operator< (const IntrusiveForwardList< T > & other) const
Definition at line 361 of file IntrusiveForwardList.hpp.
     {
         return std::lexicographical_compare(begin(), end(), other.begin(), other.end());
     }
operator<=()
template<class T > bool infra::IntrusiveForwardList< T >::operator<= (const IntrusiveForwardList< T > & other) const
Definition at line 367 of file IntrusiveForwardList.hpp.
     {
         return !(other < *this);
     }
operator=() [1/2]
template<class T> IntrusiveForwardList& infra::IntrusiveForwardList< T >::operator= (const IntrusiveForwardList< T > & other) delete
operator=() [2/2]
template<class T > IntrusiveForwardList< T > & infra::IntrusiveForwardList< T >::operator= (IntrusiveForwardList< T > && other)
Definition at line 180 of file IntrusiveForwardList.hpp.
     {
         beginNode = other.beginNode;
         other.beginNode = nullptr;
         return *this;
     }
operator==()
template<class T > bool infra::IntrusiveForwardList< T >::operator== (const IntrusiveForwardList< T > & other) const
Definition at line 337 of file IntrusiveForwardList.hpp.
     {
         const NodeType* i = beginNode;
         const NodeType* j = other.beginNode;
         while (i != nullptr && j != nullptr)
         {
             if (*i != *j)
                 return false;
             i = i->next;
             j = j->next;
         }
         return i == j;
     }
operator>()
template<class T > bool infra::IntrusiveForwardList< T >::operator> (const IntrusiveForwardList< T > & other) const
Definition at line 373 of file IntrusiveForwardList.hpp.
     {
         return other < *this;
     }
operator>=()
template<class T > bool infra::IntrusiveForwardList< T >::operator>= (const IntrusiveForwardList< T > & other) const
Definition at line 379 of file IntrusiveForwardList.hpp.
     {
         return !(*this < other);
     }
pop_front()
template<class T > void infra::IntrusiveForwardList< T >::pop_front ()
Definition at line 266 of file IntrusiveForwardList.hpp.
     {
         beginNode = beginNode->next;
     }
push_front()
template<class T > void infra::IntrusiveForwardList< T >::push_front (const_reference value)
Definition at line 257 of file IntrusiveForwardList.hpp.
Referenced by services::HttpPageServer::AddPage().
     {
         NodeType& node = const_cast<reference>(value);
         node.next = beginNode;
         beginNode = &node;
     }
swap()
template<class T > void infra::IntrusiveForwardList< T >::swap (IntrusiveForwardList< T > & other)
Definition at line 325 of file IntrusiveForwardList.hpp.
Referenced by infra::swap().
     {
         std::swap(beginNode, other.beginNode);
     }
Member Data Documentation
beginNode
template<class T> detail::IntrusiveForwardListNode<T>* infra::IntrusiveForwardList< T >::beginNode private
Definition at line 87 of file IntrusiveForwardList.hpp.
Referenced by infra::IntrusiveForwardList< infra::Timer >::operator=(), infra::IntrusiveForwardList< infra::Timer >::operator==(), and infra::IntrusiveForwardList< infra::Timer >::swap().
The documentation for this class was generated from the following file:
IntrusiveForwardList.hpp