EMil: services::ConnectionLoopBackPeer::StreamWriterLoopBack Class Reference
services::ConnectionLoopBackPeer::StreamWriterLoopBack Class Reference
Public Member Functions
StreamWriterLoopBack (ConnectionLoopBackPeer &connection)
~StreamWriterLoopBack ()
Public Member Functions inherited from infra::StreamWriter
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Private Member Functions
virtual void Insert (infra::ConstByteRange range, infra::StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
Private Attributes
ConnectionLoopBackPeer & connection
std::size_t sent = 0
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 31 of file ConnectionLoopBack.hpp.
Constructor & Destructor Documentation
StreamWriterLoopBack()
services::ConnectionLoopBackPeer::StreamWriterLoopBack::StreamWriterLoopBack (ConnectionLoopBackPeer & connection) explicit
Definition at line 67 of file ConnectionLoopBack.cpp.
         : connection(connection)
     {}
~StreamWriterLoopBack()
services::ConnectionLoopBackPeer::StreamWriterLoopBack::~StreamWriterLoopBack ()
Definition at line 71 of file ConnectionLoopBack.cpp.
References infra::Subject< ObserverType_, Helper >::GetObserver(), infra::Subject< ObserverType_, Helper >::HasObserver(), infra::InterfaceConnector< EventDispatcherWithWeakPtrWorker >::Instance(), services::ConnectionLoopBackPeer::loopBack, services::ConnectionLoopBackPeer::peer, infra::EventDispatcherWithWeakPtrWorker::Schedule(), and infra::EnableSharedFromThis< T >::SharedFromThis().
     {
         if (sent != 0)
         {
             ConnectionLoopBackPeer& connection = this->connection;
             infra::EventDispatcherWithWeakPtr::Instance().Schedule([&connection](const infra::SharedPtr<ConnectionLoopBack>& loopBack)
             {
                 if (connection.peer.HasObserver())
                     connection.peer.GetObserver().DataReceived();
             }, connection.loopBack.SharedFromThis());
         }
     }
Member Function Documentation
Available()
std::size_t services::ConnectionLoopBackPeer::StreamWriterLoopBack::Available () const override private virtual
Implements infra::StreamWriter.
Definition at line 90 of file ConnectionLoopBack.cpp.
     {
         return connection.sendBuffer.size() - sent;
     }
Insert()
void services::ConnectionLoopBackPeer::StreamWriterLoopBack::Insert (infra::ConstByteRange range, infra::StreamErrorPolicy & errorPolicy) override private virtual
Implements infra::StreamWriter.
Definition at line 84 of file ConnectionLoopBack.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         connection.sendBuffer.insert(connection.sendBuffer.end(), range.begin(), range.end());
         sent += range.size();
     }
Member Data Documentation
connection
ConnectionLoopBackPeer& services::ConnectionLoopBackPeer::StreamWriterLoopBack::connection private
Definition at line 43 of file ConnectionLoopBack.hpp.
sent
std::size_t services::ConnectionLoopBackPeer::StreamWriterLoopBack::sent = 0 private
Definition at line 44 of file ConnectionLoopBack.hpp.
The documentation for this class was generated from the following files:
ConnectionLoopBack.hpp
ConnectionLoopBack.cpp