EMil: services::GpioPinInverted Class Reference
services::GpioPinInverted Class Reference
#include <GpioPinInverted.hpp>
Public Member Functions
GpioPinInverted (hal::GpioPin &pin)
virtual bool Get () const override
virtual void Set (bool value) override
virtual bool GetOutputLatch () const override
virtual void SetAsInput () override
virtual bool IsInput () const override
virtual void Config (hal::PinConfigType config) override
virtual void Config (hal::PinConfigType config, bool startOutputState) override
virtual void ResetConfig () override
virtual void EnableInterrupt (const infra::Function< void()> &action, hal::InterruptTrigger trigger) override
virtual void DisableInterrupt () override
Public Member Functions inherited from hal::GpioPin
GpioPin ()=default
GpioPin (const GpioPin &other)=delete
GpioPin & operator= (const GpioPin &other)=delete
Private Attributes
hal::GpioPin & pin
Additional Inherited Members
Protected Member Functions inherited from hal::GpioPin
~GpioPin ()=default
Detailed Description
Definition at line 9 of file GpioPinInverted.hpp.
Constructor & Destructor Documentation
GpioPinInverted()
services::GpioPinInverted::GpioPinInverted (hal::GpioPin & pin) explicit
Definition at line 5 of file GpioPinInverted.cpp.
         : pin(pin)
     {}
Member Function Documentation
Config() [1/2]
void services::GpioPinInverted::Config (hal::PinConfigType config) override virtual
Implements hal::GpioPin.
Definition at line 34 of file GpioPinInverted.cpp.
References hal::GpioPin::Config(), and pin.
     {
         pin.Config(config);
     }
Config() [2/2]
void services::GpioPinInverted::Config (hal::PinConfigType config, bool startOutputState) override virtual
Implements hal::GpioPin.
Definition at line 39 of file GpioPinInverted.cpp.
References hal::GpioPin::Config(), and pin.
     {
         pin.Config(config, !startOutputState);
     }
DisableInterrupt()
void services::GpioPinInverted::DisableInterrupt () override virtual
Implements hal::GpioPin.
Definition at line 57 of file GpioPinInverted.cpp.
References hal::GpioPin::DisableInterrupt(), and pin.
     {
         pin.DisableInterrupt();
     }
EnableInterrupt()
void services::GpioPinInverted::EnableInterrupt (const infra::Function< void()> & action, hal::InterruptTrigger trigger) override virtual
Implements hal::GpioPin.
Definition at line 49 of file GpioPinInverted.cpp.
References hal::bothEdges, hal::GpioPin::EnableInterrupt(), hal::fallingEdge, pin, and hal::risingEdge.
     {
         static const std::array<hal::InterruptTrigger, 3> inverse = { hal::InterruptTrigger::fallingEdge, hal::InterruptTrigger::risingEdge,
             hal::InterruptTrigger::bothEdges };
         assert(static_cast<uint8_t>(trigger) < inverse.size());
         pin.EnableInterrupt(action, inverse[static_cast<uint8_t>(trigger)]);
     }
Get()
bool services::GpioPinInverted::Get () const override virtual
Implements hal::GpioPin.
Definition at line 9 of file GpioPinInverted.cpp.
References hal::GpioPin::Get(), and pin.
     {
         return !pin.Get();
     }
GetOutputLatch()
bool services::GpioPinInverted::GetOutputLatch () const override virtual
Implements hal::GpioPin.
Definition at line 19 of file GpioPinInverted.cpp.
References hal::GpioPin::GetOutputLatch(), and pin.
     {
         return !pin.GetOutputLatch();
     }
IsInput()
bool services::GpioPinInverted::IsInput () const override virtual
Implements hal::GpioPin.
Definition at line 29 of file GpioPinInverted.cpp.
References hal::GpioPin::IsInput(), and pin.
     {
         return pin.IsInput();
     }
ResetConfig()
void services::GpioPinInverted::ResetConfig () override virtual
Implements hal::GpioPin.
Definition at line 44 of file GpioPinInverted.cpp.
References pin, and hal::GpioPin::ResetConfig().
     {
         pin.ResetConfig();
     }
Set()
void services::GpioPinInverted::Set (bool value) override virtual
Implements hal::GpioPin.
Definition at line 14 of file GpioPinInverted.cpp.
References pin, hal::GpioPin::Set(), and value.
     {
         pin.Set(!value);
     }
SetAsInput()
void services::GpioPinInverted::SetAsInput () override virtual
Implements hal::GpioPin.
Definition at line 24 of file GpioPinInverted.cpp.
References pin, and hal::GpioPin::SetAsInput().
     {
         pin.SetAsInput();
     }
Member Data Documentation
pin
hal::GpioPin& services::GpioPinInverted::pin private
Definition at line 27 of file GpioPinInverted.hpp.
Referenced by Config(), DisableInterrupt(), EnableInterrupt(), Get(), GetOutputLatch(), IsInput(), ResetConfig(), Set(), and SetAsInput().
The documentation for this class was generated from the following files:
GpioPinInverted.hpp
GpioPinInverted.cpp