EMil: hal::TimerServiceBsd Class Reference
hal::TimerServiceBsd Class Reference
#include <TimerServiceBsd.hpp>
Public Member Functions
TimerServiceBsd (uint32_t id=infra::systemTimerServiceId)
~TimerServiceBsd ()
virtual void NextTriggerChanged () override
virtual infra::TimePoint Now () const override
virtual infra::Duration Resolution () const override
Public Member Functions inherited from infra::TimerService
uint32_t Id () const
void RegisterTimer (Timer &timer)
void UnregisterTimer (Timer &timer, TimePoint oldTriggerTime)
void UpdateTriggerTime (Timer &timer, TimePoint oldTriggerTime)
void Progressed (TimePoint time)
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Private Member Functions
void WaitForTrigger ()
Private Attributes
std::condition_variable_any condition
std::recursive_mutex mutex
infra::TimePoint nextTrigger
bool quit = false
std::thread triggerThread
Additional Inherited Members
Protected Member Functions inherited from infra::TimerService
TimerService (uint32_t id)
TimerService (const TimerService &other)=delete
~TimerService ()
TimerService & operator= (const TimerService &other)=delete
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 11 of file TimerServiceBsd.hpp.
Constructor & Destructor Documentation
TimerServiceBsd()
hal::TimerServiceBsd::TimerServiceBsd (uint32_t id = infra::systemTimerServiceId)
Definition at line 7 of file TimerServiceBsd.cpp.
References WaitForTrigger().
         : TimerService(id)
         , triggerThread([this]() { WaitForTrigger(); })
     {
         nextTrigger = NextTrigger();
     }
~TimerServiceBsd()
hal::TimerServiceBsd::~TimerServiceBsd ()
Definition at line 14 of file TimerServiceBsd.cpp.
References condition, quit, and triggerThread.
     {
         quit = true;
         condition.notify_one();
         triggerThread.join();
     }
Member Function Documentation
NextTriggerChanged()
void hal::TimerServiceBsd::NextTriggerChanged () override virtual
Reimplemented from infra::TimerService.
Definition at line 21 of file TimerServiceBsd.cpp.
References condition, mutex, infra::TimerService::NextTrigger(), and nextTrigger.
Referenced by WaitForTrigger().
     {
         std::unique_lock<std::recursive_mutex> lock(mutex);
         nextTrigger = NextTrigger();
         condition.notify_one();
     }
Now()
infra::TimePoint hal::TimerServiceBsd::Now () const override virtual
Implements infra::TimerService.
Definition at line 28 of file TimerServiceBsd.cpp.
Referenced by WaitForTrigger().
     {
         return std::chrono::system_clock::now();
     }
Resolution()
infra::Duration hal::TimerServiceBsd::Resolution () const override virtual
Implements infra::TimerService.
Definition at line 33 of file TimerServiceBsd.cpp.
     {
         return std::chrono::duration<long long, std::chrono::system_clock::period>(1);
     }
WaitForTrigger()
void hal::TimerServiceBsd::WaitForTrigger () private
Definition at line 38 of file TimerServiceBsd.cpp.
References condition, infra::InterfaceConnector< EventDispatcherWorker >::Instance(), mutex, nextTrigger, NextTriggerChanged(), Now(), infra::TimerService::Progressed(), quit, and infra::EventDispatcherWorker::Schedule().
Referenced by TimerServiceBsd().
     {
         std::unique_lock<std::recursive_mutex> lock(mutex);
         while (!quit)
         {
             if (nextTrigger != infra::TimePoint::max())
                 condition.wait_until(lock, nextTrigger);
             else
                 condition.wait(lock);
             if (nextTrigger != infra::TimePoint::max() && nextTrigger <= Now())
             {
                 nextTrigger = infra::TimePoint::max();
                 infra::EventDispatcher::Instance().Schedule([this]()
                 {
                     std::unique_lock<std::recursive_mutex> lock(mutex);
                     Progressed(Now());
                     NextTriggerChanged();
                 });
             }
         }
     }
Member Data Documentation
condition
std::condition_variable_any hal::TimerServiceBsd::condition private
Definition at line 26 of file TimerServiceBsd.hpp.
Referenced by NextTriggerChanged(), WaitForTrigger(), and ~TimerServiceBsd().
mutex
std::recursive_mutex hal::TimerServiceBsd::mutex private
Definition at line 27 of file TimerServiceBsd.hpp.
Referenced by NextTriggerChanged(), and WaitForTrigger().
nextTrigger
infra::TimePoint hal::TimerServiceBsd::nextTrigger private
Definition at line 28 of file TimerServiceBsd.hpp.
Referenced by NextTriggerChanged(), and WaitForTrigger().
quit
bool hal::TimerServiceBsd::quit = false private
Definition at line 29 of file TimerServiceBsd.hpp.
Referenced by WaitForTrigger(), and ~TimerServiceBsd().
triggerThread
std::thread hal::TimerServiceBsd::triggerThread private
Definition at line 30 of file TimerServiceBsd.hpp.
Referenced by ~TimerServiceBsd().
The documentation for this class was generated from the following files:
TimerServiceBsd.hpp
TimerServiceBsd.cpp