EMil: hal::SynchronousFlash Class Reference
hal::SynchronousFlash Class Reference abstract
#include <SynchronousFlash.hpp>
Public Types
using Range = std::pair< uint32_t, uint32_t >
Public Member Functions
SynchronousFlash ()=default
SynchronousFlash (const SynchronousFlash &other)=delete
SynchronousFlash & operator= (const SynchronousFlash &other)=delete
virtual uint32_t NumberOfSectors () const =0
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const =0
uint32_t TotalSize () const
virtual uint32_t SectorOfAddress (uint32_t address) const =0
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const =0
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address)=0
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address)=0
void EraseSector (uint32_t sectorIndex)
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex)=0
void EraseAll ()
Protected Member Functions
~SynchronousFlash ()=default
Detailed Description
Definition at line 10 of file SynchronousFlash.hpp.
Member Typedef Documentation
Range
using hal::SynchronousFlash::Range = std::pair<uint32_t, uint32_t>
Definition at line 13 of file SynchronousFlash.hpp.
Constructor & Destructor Documentation
SynchronousFlash() [1/2]
hal::SynchronousFlash::SynchronousFlash () default
SynchronousFlash() [2/2]
hal::SynchronousFlash::SynchronousFlash (const SynchronousFlash & other) delete
~SynchronousFlash()
hal::SynchronousFlash::~SynchronousFlash () protected default
Member Function Documentation
AddressOffsetInSector()
uint32_t hal::SynchronousFlash::AddressOffsetInSector (uint32_t address) const
Definition at line 15 of file SynchronousFlash.cpp.
References StartOfSector().
Referenced by services::SynchronousFlashQuadSpi::PageProgram(), and services::SynchronousFlashSpi::PageProgram().
     {
         return address - StartOfSector(address);
     }
AddressOfSector()
virtual uint32_t hal::SynchronousFlash::AddressOfSector (uint32_t sectorIndex) const pure virtual
Implemented in hal::SynchronousFlashHomogeneous, and services::SynchronousFlashRegion.
Referenced by services::SynchronousFlashRegion::AddressOfSector(), StartOfNextSector(), StartOfNextSectorCyclical(), StartOfPreviousSector(), StartOfPreviousSectorCyclical(), StartOfSector(), and TotalSize().
AtStartOfSector()
bool hal::SynchronousFlash::AtStartOfSector (uint32_t address) const
Definition at line 46 of file SynchronousFlash.cpp.
References StartOfSector().
     {
         return StartOfSector(address) == address;
     }
EraseAll()
void hal::SynchronousFlash::EraseAll ()
Definition at line 56 of file SynchronousFlash.cpp.
References EraseSectors(), and NumberOfSectors().
     {
         EraseSectors(0, NumberOfSectors());
     }
EraseSector()
void hal::SynchronousFlash::EraseSector (uint32_t sectorIndex)
Definition at line 51 of file SynchronousFlash.cpp.
References EraseSectors().
     {
         EraseSectors(sectorIndex, sectorIndex + 1);
     }
EraseSectors()
virtual void hal::SynchronousFlash::EraseSectors (uint32_t beginIndex, uint32_t endIndex) pure virtual
Implemented in services::SynchronousFlashSpi, services::SynchronousFlashRegion, and services::SynchronousFlashQuadSpi.
Referenced by EraseAll(), EraseSector(), services::SynchronousFlashRegion::EraseSectors(), application::ImageUpgraderEraseSectors::Upgrade(), and application::ImageUpgraderInternalFlash::Upgrade().
NumberOfSectors()
virtual uint32_t hal::SynchronousFlash::NumberOfSectors () const pure virtual
Implemented in hal::SynchronousFlashHomogeneous, and services::SynchronousFlashRegion.
Referenced by EraseAll(), StartOfNextSectorCyclical(), StartOfPreviousSectorCyclical(), services::SynchronousFlashRegion::SynchronousFlashRegion(), and TotalSize().
operator=()
SynchronousFlash& hal::SynchronousFlash::operator= (const SynchronousFlash & other) delete
ReadBuffer()
virtual void hal::SynchronousFlash::ReadBuffer (infra::ByteRange buffer, uint32_t address) pure virtual
Implemented in services::SynchronousFlashSpi, services::SynchronousFlashRegion, and services::SynchronousFlashQuadSpi.
Referenced by application::PackUpgrader::HasImage(), application::PackUpgrader::IsImage(), application::VerifierEcDsa::IsValid(), application::VerifierRsa::IsValid(), application::SecondStageToRamLoader::Load(), services::SynchronousFlashRegion::ReadBuffer(), application::SecondStageToRamLoader::TryLoadImage(), application::PackUpgrader::TryUpgradeImage(), application::ImageUpgraderInternalFlash::Upgrade(), and application::PackUpgrader::UpgradeFromImages().
SectorOfAddress()
virtual uint32_t hal::SynchronousFlash::SectorOfAddress (uint32_t address) const pure virtual
Implemented in hal::SynchronousFlashHomogeneous, and services::SynchronousFlashRegion.
Referenced by services::SynchronousFlashRegion::SectorOfAddress(), StartOfNextSector(), StartOfNextSectorCyclical(), StartOfPreviousSector(), StartOfPreviousSectorCyclical(), StartOfSector(), and application::ImageUpgraderInternalFlash::Upgrade().
SizeOfSector()
virtual uint32_t hal::SynchronousFlash::SizeOfSector (uint32_t sectorIndex) const pure virtual
Implemented in hal::SynchronousFlashHomogeneous, and services::SynchronousFlashRegion.
Referenced by services::SynchronousFlashRegion::SizeOfSector(), and TotalSize().
StartOfNextSector()
uint32_t hal::SynchronousFlash::StartOfNextSector (uint32_t address) const
Definition at line 20 of file SynchronousFlash.cpp.
References AddressOfSector(), and SectorOfAddress().
     {
         return AddressOfSector(SectorOfAddress(address) + 1);
     }
StartOfNextSectorCyclical()
uint32_t hal::SynchronousFlash::StartOfNextSectorCyclical (uint32_t address) const
Definition at line 30 of file SynchronousFlash.cpp.
References AddressOfSector(), NumberOfSectors(), and SectorOfAddress().
     {
         uint32_t sectorIndex = SectorOfAddress(address) + 1;
         if (sectorIndex == NumberOfSectors())
             sectorIndex = 0;
         return AddressOfSector(sectorIndex);
     }
StartOfPreviousSector()
uint32_t hal::SynchronousFlash::StartOfPreviousSector (uint32_t address) const
Definition at line 25 of file SynchronousFlash.cpp.
References AddressOfSector(), and SectorOfAddress().
     {
         return AddressOfSector(SectorOfAddress(address) - 1);
     }
StartOfPreviousSectorCyclical()
uint32_t hal::SynchronousFlash::StartOfPreviousSectorCyclical (uint32_t address) const
Definition at line 38 of file SynchronousFlash.cpp.
References AddressOfSector(), NumberOfSectors(), and SectorOfAddress().
     {
         uint32_t sectorIndex = SectorOfAddress(address);
         if (sectorIndex == 0)
             sectorIndex = NumberOfSectors();
         return AddressOfSector(sectorIndex - 1);
     }
StartOfSector()
uint32_t hal::SynchronousFlash::StartOfSector (uint32_t address) const
Definition at line 10 of file SynchronousFlash.cpp.
References AddressOfSector(), and SectorOfAddress().
Referenced by AddressOffsetInSector(), and AtStartOfSector().
     {
         return AddressOfSector(SectorOfAddress(address));
     }
TotalSize()
uint32_t hal::SynchronousFlash::TotalSize () const
Definition at line 5 of file SynchronousFlash.cpp.
References AddressOfSector(), NumberOfSectors(), and SizeOfSector().
     {
         return AddressOfSector(NumberOfSectors() - 1) + SizeOfSector(NumberOfSectors() - 1);
     }
WriteBuffer()
virtual void hal::SynchronousFlash::WriteBuffer (infra::ConstByteRange buffer, uint32_t address) pure virtual
Implemented in services::SynchronousFlashSpi, services::SynchronousFlashRegion, and services::SynchronousFlashQuadSpi.
Referenced by application::PackUpgrader::MarkAsDeployed(), application::PackUpgrader::MarkAsDeployStarted(), application::SecondStageToRamLoader::MarkAsError(), application::PackUpgrader::MarkAsError(), application::ImageUpgraderInternalFlash::Upgrade(), and services::SynchronousFlashRegion::WriteBuffer().
The documentation for this class was generated from the following files:
SynchronousFlash.hpp
SynchronousFlash.cpp