EMil: TestSequencer.cpp File Reference
TestSequencer.cpp File Reference
Classes
class TestSequencer
Functions
TEST_F (TestSequencer, can_load_empty_sequence)
TEST_F (TestSequencer, executing_empty_sequence_results_in_Finished)
TEST_F (TestSequencer, executing_one_step_results_in_not_Finished)
TEST_F (TestSequencer, executing_Execute_results_in_Finished)
TEST_F (TestSequencer, two_steps_result_in_first_step_executed)
TEST_F (TestSequencer, after_continue_second_step_is_executed)
TEST_F (TestSequencer, nested_steps_are_executed_in_sequence)
TEST_F (TestSequencer, on_unsuccessful_condition_If_does_not_execute_statement)
TEST_F (TestSequencer, on_unsuccessful_condition_If_does_not_execute_multiple_statements)
TEST_F (TestSequencer, on_successful_condition_If_executes_statement)
TEST_F (TestSequencer, on_successful_condition_If_executes_multiple_statements)
TEST_F (TestSequencer, nested_If_does_not_release_If)
TEST_F (TestSequencer, on_unsuccessful_condition_IfElse_executes_Else_statement)
TEST_F (TestSequencer, on_successful_condition_IfElse_executes_If_statement)
TEST_F (TestSequencer, on_successful_second_condition_If_ElseIf_executes_ElseIf_statement)
TEST_F (TestSequencer, on_successful_second_condition_If_ElseIf_Else_executes_If_statement)
TEST_F (TestSequencer, on_successful_second_condition_If_ElseIf_Else_executes_ElseIf_statement)
TEST_F (TestSequencer, on_unsuccessful_second_condition_If_ElseIf_executes_Else_statement)
TEST_F (TestSequencer, on_successful_condition_IfElseIfElse_executes_If_statement)
TEST_F (TestSequencer, on_successful_condition_IfElseIfElse_executes_ElseIf_statement)
TEST_F (TestSequencer, on_successful_condition_IfElseIfElse_executes_ElseElse_statement)
TEST_F (TestSequencer, on_unsuccessful_condition_While_does_not_execute_statement)
TEST_F (TestSequencer, on_successful_condition_While_executes_statement_once)
TEST_F (TestSequencer, on_twice_successful_condition_While_executes_statement_twice)
TEST_F (TestSequencer, on_unsuccessful_condition_DoWhile_executes_statement_once)
TEST_F (TestSequencer, on_successful_condition_DoWhile_executes_statement_twice)
TEST_F (TestSequencer, ForEach_iterates_twice)
Function Documentation
TEST_F() [1/27]
TEST_F (TestSequencer , can_load_empty_sequence)
Definition at line 20 of file TestSequencer.cpp.
 {
     sequencer.Load([this]() { });
 }
TEST_F() [2/27]
TEST_F (TestSequencer , executing_empty_sequence_results_in_Finished)
Definition at line 25 of file TestSequencer.cpp.
References EXPECT_TRUE().
 {
     sequencer.Load([this]() { });
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [3/27]
TEST_F (TestSequencer , executing_one_step_results_in_not_Finished)
Definition at line 31 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, a());
     sequencer.Load([this]()
     {
         sequencer.Step([this]() { a(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [4/27]
TEST_F (TestSequencer , executing_Execute_results_in_Finished)
Definition at line 45 of file TestSequencer.cpp.
References EXPECT_TRUE().
 {
     EXPECT_CALL(*this, a());
     sequencer.Load([this]()
     {
         sequencer.Execute([this]() { a(); });
     });
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [5/27]
TEST_F (TestSequencer , two_steps_result_in_first_step_executed)
Definition at line 57 of file TestSequencer.cpp.
References EXPECT_FALSE().
 {
     EXPECT_CALL(*this, a());
     sequencer.Load([this]() {
         sequencer.Step([this]() { a(); });
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
 }
TEST_F() [6/27]
TEST_F (TestSequencer , after_continue_second_step_is_executed)
Definition at line 69 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, a());
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.Step([this]() { a(); });
         sequencer.Step([this]() { b(); });
     });
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [7/27]
TEST_F (TestSequencer , nested_steps_are_executed_in_sequence)
Definition at line 85 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, a());
     sequencer.Load([this]() {
         sequencer.Execute([this]()
         {
             sequencer.Step([this]() { a(); });
             sequencer.Step([this]() { b(); });
         });
     });
     EXPECT_FALSE(sequencer.Finished());
     testing::Mock::VerifyAndClearExpectations(this);
     EXPECT_CALL(*this, b());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     testing::Mock::VerifyAndClearExpectations(this);
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [8/27]
TEST_F (TestSequencer , on_unsuccessful_condition_If_does_not_execute_statement)
Definition at line 109 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.EndIf();
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [9/27]
TEST_F (TestSequencer , on_unsuccessful_condition_If_does_not_execute_multiple_statements)
Definition at line 126 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false));
     EXPECT_CALL(*this, c());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
             sequencer.Step([this]() { b(); });
         sequencer.EndIf();
         sequencer.Step([this]() { c(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [10/27]
TEST_F (TestSequencer , on_successful_condition_If_executes_statement)
Definition at line 144 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, a());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.EndIf();
         sequencer.Step([this]() { b(); });
     });
     EXPECT_CALL(*this, b());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [11/27]
TEST_F (TestSequencer , on_successful_condition_If_executes_multiple_statements)
Definition at line 164 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, a());
     EXPECT_CALL(*this, b());
     EXPECT_CALL(*this, c());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
             sequencer.Step([this]() { b(); });
         sequencer.EndIf();
         sequencer.Step([this]() { c(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [12/27]
TEST_F (TestSequencer , nested_If_does_not_release_If)
Definition at line 189 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.If([this](){ return condition(); });
             sequencer.EndIf();
         sequencer.EndIf();
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [13/27]
TEST_F (TestSequencer , on_unsuccessful_condition_IfElse_executes_Else_statement)
Definition at line 207 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.Else();
             sequencer.Step([this]() { b(); });
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [14/27]
TEST_F (TestSequencer , on_successful_condition_IfElse_executes_If_statement)
Definition at line 225 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, a());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.Else();
             sequencer.Step([this]() { b(); });
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [15/27]
TEST_F (TestSequencer , on_successful_second_condition_If_ElseIf_executes_ElseIf_statement)
Definition at line 243 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false)).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.ElseIf([this] { return condition(); });
             sequencer.Step([this]() { b(); });
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [16/27]
TEST_F (TestSequencer , on_successful_second_condition_If_ElseIf_Else_executes_If_statement)
Definition at line 261 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, a());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.ElseIf([this] { return condition(); });
             sequencer.Step([this]() { b(); });
         sequencer.Else();
             sequencer.Step([this]() { c(); });
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [17/27]
TEST_F (TestSequencer , on_successful_second_condition_If_ElseIf_Else_executes_ElseIf_statement)
Definition at line 281 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false)).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.ElseIf([this] { return condition(); });
             sequencer.Step([this]() { b(); });
         sequencer.Else();
             sequencer.Step([this]() { c(); });
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [18/27]
TEST_F (TestSequencer , on_unsuccessful_second_condition_If_ElseIf_executes_Else_statement)
Definition at line 301 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(false)).WillOnce(testing::Return(false));
     EXPECT_CALL(*this, c());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.ElseIf([this] { return condition(); });
             sequencer.Step([this]() { b(); });
         sequencer.Else();
             sequencer.Step([this]() { c(); });
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [19/27]
TEST_F (TestSequencer , on_successful_condition_IfElseIfElse_executes_If_statement)
Definition at line 321 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, a());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.Else();
             sequencer.If([this] { return condition(); });
                 sequencer.Step([this]() { b(); });
             sequencer.Else();
                 sequencer.Step([this]() { c(); });
             sequencer.EndIf();
        sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [20/27]
TEST_F (TestSequencer , on_successful_condition_IfElseIfElse_executes_ElseIf_statement)
Definition at line 343 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).Times(2).WillOnce(testing::Return(false)).WillOnce(testing::Return(true));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.Else();
             sequencer.If([this] { return condition(); });
                 sequencer.Step([this](){ b(); });
             sequencer.Else();
                 sequencer.Step([this]() { c(); });
             sequencer.EndIf();
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [21/27]
TEST_F (TestSequencer , on_successful_condition_IfElseIfElse_executes_ElseElse_statement)
Definition at line 365 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition()).Times(2).WillRepeatedly(testing::Return(false));
     EXPECT_CALL(*this, c());
     sequencer.Load([this]() {
         sequencer.If([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.Else();
             sequencer.If([this] { return condition(); });
                 sequencer.Step([this](){ b(); });
             sequencer.Else();
                 sequencer.Step([this]() { c(); });
             sequencer.EndIf();
         sequencer.EndIf();
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [22/27]
TEST_F (TestSequencer , on_unsuccessful_condition_While_does_not_execute_statement)
Definition at line 387 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition())
         .WillOnce(testing::Return(false));
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.While([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.EndWhile();
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [23/27]
TEST_F (TestSequencer , on_successful_condition_While_executes_statement_once)
Definition at line 405 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition())
         .WillOnce(testing::Return(true))
         .WillOnce(testing::Return(false));
     EXPECT_CALL(*this, a());
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.While([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.EndWhile();
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [24/27]
TEST_F (TestSequencer , on_twice_successful_condition_While_executes_statement_twice)
Definition at line 427 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition())
         .WillOnce(testing::Return(true))
         .WillOnce(testing::Return(true))
         .WillOnce(testing::Return(false));
     EXPECT_CALL(*this, a()).Times(2);
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.While([this] { return condition(); });
             sequencer.Step([this]() { a(); });
         sequencer.EndWhile();
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [25/27]
TEST_F (TestSequencer , on_unsuccessful_condition_DoWhile_executes_statement_once)
Definition at line 452 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition())
         .WillOnce(testing::Return(false));
     EXPECT_CALL(*this, a());
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.DoWhile();
             sequencer.Step([this]() { a(); });
         sequencer.EndDoWhile([this] { return condition(); });
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [26/27]
TEST_F (TestSequencer , on_successful_condition_DoWhile_executes_statement_twice)
Definition at line 473 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, condition())
         .WillOnce(testing::Return(true)).WillOnce(testing::Return(false));
     EXPECT_CALL(*this, a()).Times(2);
     EXPECT_CALL(*this, b());
     sequencer.Load([this]() {
         sequencer.DoWhile();
             sequencer.Step([this]() { a(); });
         sequencer.EndDoWhile([this] { return condition(); });
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }
TEST_F() [27/27]
TEST_F (TestSequencer , ForEach_iterates_twice)
Definition at line 496 of file TestSequencer.cpp.
References EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_CALL(*this, a()).Times(2);
     EXPECT_CALL(*this, b());
     uint32_t x;
     sequencer.Load([this, &x]() {
         sequencer.ForEach(x, 0, 2);
             sequencer.Step([this]() { a(); });
         sequencer.EndForEach(x);
         sequencer.Step([this]() { b(); });
     });
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_FALSE(sequencer.Finished());
     sequencer.Continue();
     EXPECT_TRUE(sequencer.Finished());
 }