EMil: application::RandomNumberGenerator Class Reference
application::RandomNumberGenerator Class Reference abstract
#include <RandomNumberGenerator.hpp>
Public Member Functions
virtual std::vector< uint8_t > Generate (std::size_t n)=0
Protected Member Functions
~RandomNumberGenerator ()=default
Detailed Description
Definition at line 10 of file RandomNumberGenerator.hpp.
Constructor & Destructor Documentation
~RandomNumberGenerator()
application::RandomNumberGenerator::~RandomNumberGenerator () protected default
Member Function Documentation
Generate()
virtual std::vector<uint8_t> application::RandomNumberGenerator::Generate (std::size_t n) pure virtual
Implemented in application::FixedRandomNumberGenerator, and application::SecureRandomNumberGenerator.
Referenced by application::MaterialGenerator::MaterialGenerator(), application::ImageSignerEcDsa::MyRandom(), application::ImageSignerRsa::MyRandom(), application::MaterialGenerator::RandomEntropy(), application::ImageEncryptorXtea::Secure(), application::ImageEncryptorAes::Secure(), and application::MaterialGenerator::UccRandom().
The documentation for this class was generated from the following file:
RandomNumberGenerator.hpp