EMil: TestCountingInputStream.cpp File Reference
TestCountingInputStream.cpp File Reference
Functions
TEST (CountingInputStreamTest, Extract)
TEST (CountingInputStreamTest, Extract_but_fails)
TEST (CountingInputStreamTest, Peek)
TEST (CountingInputStreamTest, ExtractContiguousRange)
TEST (CountingInputStreamTest, PeekContiguousRange)
TEST (CountingInputStreamTest, Available)
TEST (CountingInputStreamTest, Empty)
Function Documentation
TEST() [1/7]
TEST (CountingInputStreamTest , Extract)
Definition at line 5 of file TestCountingInputStream.cpp.
References data, EXPECT_EQ(), EXPECT_FALSE(), infra::CountingStreamReader::Extract(), infra::StreamErrorPolicy::Failed(), infra::MakeRange(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     infra::StreamErrorPolicy errorPolicy;
     std::array<uint8_t, 4> data;
     EXPECT_CALL(reader, Extract(infra::MakeRange(data), testing::_));
     countingReader.Extract(data, errorPolicy);
     EXPECT_EQ(4, countingReader.TotalRead());
     EXPECT_FALSE(errorPolicy.Failed());
 }
TEST() [2/7]
TEST (CountingInputStreamTest , Extract_but_fails)
Definition at line 19 of file TestCountingInputStream.cpp.
References data, EXPECT_EQ(), EXPECT_TRUE(), infra::CountingStreamReader::Extract(), infra::StreamErrorPolicy::Failed(), infra::MakeRange(), infra::noFail, infra::StreamErrorPolicy::ReportResult(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     infra::StreamErrorPolicy errorPolicy(infra::noFail);
     std::array<uint8_t, 4> data;
     EXPECT_CALL(reader, Extract(infra::MakeRange(data), testing::_)).WillOnce(testing::Invoke([](infra::ByteRange range, infra::StreamErrorPolicy& errorPolicy) { errorPolicy.ReportResult(false); }));
     countingReader.Extract(data, errorPolicy);
     EXPECT_EQ(0, countingReader.TotalRead());
     EXPECT_TRUE(errorPolicy.Failed());
 }
TEST() [3/7]
TEST (CountingInputStreamTest , Peek)
Definition at line 33 of file TestCountingInputStream.cpp.
References EXPECT_EQ(), infra::CountingStreamReader::Peek(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     infra::StreamErrorPolicy errorPolicy;
     EXPECT_CALL(reader, Peek(testing::Ref(errorPolicy))).WillOnce(testing::Return(4));
     EXPECT_EQ(4, countingReader.Peek(errorPolicy));
     EXPECT_EQ(0, countingReader.TotalRead());
 }
TEST() [4/7]
TEST (CountingInputStreamTest , ExtractContiguousRange)
Definition at line 45 of file TestCountingInputStream.cpp.
References data, EXPECT_EQ(), infra::CountingStreamReader::ExtractContiguousRange(), infra::MakeRange(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     std::array<uint8_t, 2> data;
     EXPECT_CALL(reader, ExtractContiguousRange(5)).WillOnce(testing::Return(infra::MakeRange(data)));
     EXPECT_EQ(infra::MakeRange(data), countingReader.ExtractContiguousRange(5));
     EXPECT_EQ(2, countingReader.TotalRead());
 }
TEST() [5/7]
TEST (CountingInputStreamTest , PeekContiguousRange)
Definition at line 57 of file TestCountingInputStream.cpp.
References data, EXPECT_EQ(), infra::MakeRange(), infra::CountingStreamReader::PeekContiguousRange(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     std::array<uint8_t, 2> data{{1, 2}};
     EXPECT_CALL(reader, PeekContiguousRange(7)).WillOnce(testing::Return(infra::MakeRange(data)));
     EXPECT_EQ(infra::MakeRange(data), countingReader.PeekContiguousRange(7));
     EXPECT_EQ(0, countingReader.TotalRead());
 }
TEST() [6/7]
TEST (CountingInputStreamTest , Available)
Definition at line 69 of file TestCountingInputStream.cpp.
References infra::CountingStreamReader::Available(), EXPECT_EQ(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     EXPECT_CALL(reader, Available()).WillOnce(testing::Return(4));
     EXPECT_EQ(4, countingReader.Available());
     EXPECT_EQ(0, countingReader.TotalRead());
 }
TEST() [7/7]
TEST (CountingInputStreamTest , Empty)
Definition at line 80 of file TestCountingInputStream.cpp.
References infra::CountingStreamReader::Empty(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), and infra::CountingStreamReader::TotalRead().
 {
     testing::StrictMock<infra::StreamReaderMock> reader;
     infra::CountingStreamReader countingReader(reader);
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(false));
     EXPECT_FALSE(countingReader.Empty());
     EXPECT_CALL(reader, Empty()).WillOnce(testing::Return(true));
     EXPECT_TRUE(countingReader.Empty());
     EXPECT_EQ(0, countingReader.TotalRead());
 }