EMil: services::I2cMultipleAccess Class Reference
services::I2cMultipleAccess Class Reference
#include <I2cMultipleAccess.hpp>
Public Member Functions
I2cMultipleAccess (I2cMultipleAccessMaster &master)
virtual void SendData (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction, infra::Function< void(hal::Result, uint32_t numberOfBytesSent)> onSent) override
virtual void ReceiveData (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction, infra::Function< void(hal::Result)> onReceived) override
Public Member Functions inherited from hal::I2cMaster
I2cMaster ()=default
I2cMaster (const I2cMaster &other)=delete
I2cMaster & operator= (const I2cMaster &other)=delete
Private Member Functions
void SendDataOnClaimed (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction)
void ReceiveDataOnClaimed (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction)
Private Attributes
I2cMultipleAccessMaster & master
infra::ClaimableResource::Claimer::WithSize< SERVICES_I2C_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE > claimer
infra::AutoResetFunction< void(hal::Result, uint32_t numberOfBytesSent)> onSent
infra::AutoResetFunction< void(hal::Result)> onReceived
Additional Inherited Members
Protected Member Functions inherited from hal::I2cMaster
~I2cMaster ()=default
Detailed Description
Definition at line 30 of file I2cMultipleAccess.hpp.
Constructor & Destructor Documentation
I2cMultipleAccess()
services::I2cMultipleAccess::I2cMultipleAccess (I2cMultipleAccessMaster & master) explicit
Definition at line 21 of file I2cMultipleAccess.cpp.
         : master(master)
         , claimer(master)
     {}
Member Function Documentation
ReceiveData()
void services::I2cMultipleAccess::ReceiveData (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction, infra::Function< void(hal::Result)> onReceived) override virtual
Implements hal::I2cMaster.
Definition at line 49 of file I2cMultipleAccess.cpp.
References claimer, infra::data, onReceived, and ReceiveDataOnClaimed().
     {
         this->onReceived = onReceived;
         if (!claimer.IsClaimed())
             claimer.Claim([this, address, data, nextAction, onReceived]()
             {
                 ReceiveDataOnClaimed(address, data, nextAction);
             });
         else
             ReceiveDataOnClaimed(address, data, nextAction);
     }
ReceiveDataOnClaimed()
void services::I2cMultipleAccess::ReceiveDataOnClaimed (hal::I2cAddress address, infra::ByteRange data, hal::Action nextAction) private
Definition at line 61 of file I2cMultipleAccess.cpp.
References claimer, infra::data, master, onReceived, services::I2cMultipleAccessMaster::ReceiveData(), and hal::stop.
Referenced by ReceiveData().
     {
         master.ReceiveData(address, data, nextAction, [this, nextAction](hal::Result result)
         {
             if (nextAction == hal::Action::stop)
                 claimer.Release();
             this->onReceived(result);
         });
     }
SendData()
void services::I2cMultipleAccess::SendData (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction, infra::Function< void(hal::Result, uint32_t numberOfBytesSent)> onSent) override virtual
Implements hal::I2cMaster.
Definition at line 26 of file I2cMultipleAccess.cpp.
References claimer, infra::data, onSent, and SendDataOnClaimed().
     {
         this->onSent = onSent;
         if (!claimer.IsClaimed())
             claimer.Claim([this, address, data, nextAction, onSent]()
             {
                 SendDataOnClaimed(address, data, nextAction);
             });
         else
             SendDataOnClaimed(address, data, nextAction);
     }
SendDataOnClaimed()
void services::I2cMultipleAccess::SendDataOnClaimed (hal::I2cAddress address, infra::ConstByteRange data, hal::Action nextAction) private
Definition at line 39 of file I2cMultipleAccess.cpp.
References claimer, infra::data, master, onSent, services::I2cMultipleAccessMaster::SendData(), and hal::stop.
Referenced by SendData().
     {
         master.SendData(address, data, nextAction, [this, nextAction](hal::Result result, uint32_t numberOfBytesSent)
         {
             if (nextAction == hal::Action::stop)
                 claimer.Release();
             this->onSent(result, numberOfBytesSent);
         });
     }
Member Data Documentation
claimer
infra::ClaimableResource::Claimer::WithSize<SERVICES_I2C_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE> services::I2cMultipleAccess::claimer private
Definition at line 47 of file I2cMultipleAccess.hpp.
Referenced by ReceiveData(), ReceiveDataOnClaimed(), SendData(), and SendDataOnClaimed().
master
I2cMultipleAccessMaster& services::I2cMultipleAccess::master private
Definition at line 46 of file I2cMultipleAccess.hpp.
Referenced by ReceiveDataOnClaimed(), and SendDataOnClaimed().
onReceived
infra::AutoResetFunction<void(hal::Result)> services::I2cMultipleAccess::onReceived private
Definition at line 49 of file I2cMultipleAccess.hpp.
Referenced by ReceiveData(), and ReceiveDataOnClaimed().
onSent
infra::AutoResetFunction<void(hal::Result, uint32_t numberOfBytesSent)> services::I2cMultipleAccess::onSent private
Definition at line 48 of file I2cMultipleAccess.hpp.
Referenced by SendData(), and SendDataOnClaimed().
The documentation for this class was generated from the following files:
I2cMultipleAccess.hpp
I2cMultipleAccess.cpp