EMil: infra::DerivedTimerService Class Reference
infra::DerivedTimerService Class Reference
#include <DerivedTimerService.hpp>
Public Member Functions
DerivedTimerService (uint32_t id, TimerService &baseTimerService)
virtual void NextTriggerChanged () override
virtual TimePoint Now () const override
virtual Duration Resolution () const override
void Shift (Duration shift)
Duration GetCurrentShift () const
Public Member Functions inherited from infra::TimerService
uint32_t Id () const
void RegisterTimer (Timer &timer)
void UnregisterTimer (Timer &timer, TimePoint oldTriggerTime)
void UpdateTriggerTime (Timer &timer, TimePoint oldTriggerTime)
void Progressed (TimePoint time)
TimePoint NextTrigger () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Private Attributes
TimerService & baseTimerService
TimerSingleShot timer
TimePoint nextTrigger
Duration shift = Duration()
Additional Inherited Members
Protected Member Functions inherited from infra::TimerService
TimerService (uint32_t id)
TimerService (const TimerService &other)=delete
~TimerService ()
TimerService & operator= (const TimerService &other)=delete
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Detailed Description
Definition at line 8 of file DerivedTimerService.hpp.
Constructor & Destructor Documentation
DerivedTimerService()
infra::DerivedTimerService::DerivedTimerService (uint32_t id, TimerService & baseTimerService)
Definition at line 5 of file DerivedTimerService.cpp.
         : TimerService(id)
         , baseTimerService(baseTimerService)
         , timer(baseTimerService.Id())
     {}
Member Function Documentation
GetCurrentShift()
Duration infra::DerivedTimerService::GetCurrentShift () const
Definition at line 37 of file DerivedTimerService.cpp.
References shift.
Referenced by services::TimeWithLocalization::GetOffsetDaylightSaving(), services::TimeWithLocalization::GetOffsetFromLocalToUtc(), and services::TimeWithLocalization::GetOffsetTimezone().
     {
         return shift;
     }
NextTriggerChanged()
void infra::DerivedTimerService::NextTriggerChanged () override virtual
Reimplemented from infra::TimerService.
Definition at line 11 of file DerivedTimerService.cpp.
References infra::Timer::Cancel(), nextTrigger, infra::TimerService::NextTrigger(), infra::TimerService::Progressed(), shift, infra::TimerSingleShot::Start(), and timer.
Referenced by Shift().
     {
         nextTrigger = NextTrigger() - shift;
         if (NextTrigger() != TimePoint::max())
             timer.Start(nextTrigger, [this]() { Progressed(nextTrigger + shift); });
         else
             timer.Cancel();
     }
Now()
TimePoint infra::DerivedTimerService::Now () const override virtual
Implements infra::TimerService.
Definition at line 21 of file DerivedTimerService.cpp.
References baseTimerService, infra::TimerService::Now(), and shift.
Referenced by services::SntpClient::NotifyOffsetAndDelay(), and services::SntpClient::SendStreamAvailable().
     {
         return baseTimerService.Now() + shift;
     }
Resolution()
Duration infra::DerivedTimerService::Resolution () const override virtual
Implements infra::TimerService.
Definition at line 26 of file DerivedTimerService.cpp.
References baseTimerService, and infra::TimerService::Resolution().
     {
         return baseTimerService.Resolution();
     }
Shift()
void infra::DerivedTimerService::Shift (Duration shift)
Definition at line 31 of file DerivedTimerService.cpp.
References NextTriggerChanged(), and shift.
     {
         this->shift = shift;
         NextTriggerChanged();
     }
Member Data Documentation
baseTimerService
TimerService& infra::DerivedTimerService::baseTimerService private
Definition at line 23 of file DerivedTimerService.hpp.
Referenced by Now(), and Resolution().
nextTrigger
TimePoint infra::DerivedTimerService::nextTrigger private
Definition at line 25 of file DerivedTimerService.hpp.
Referenced by NextTriggerChanged().
shift
Duration infra::DerivedTimerService::shift = Duration() private
Definition at line 27 of file DerivedTimerService.hpp.
Referenced by GetCurrentShift(), NextTriggerChanged(), Now(), and Shift().
timer
TimerSingleShot infra::DerivedTimerService::timer private
Definition at line 24 of file DerivedTimerService.hpp.
Referenced by NextTriggerChanged().
The documentation for this class was generated from the following files:
DerivedTimerService.hpp
DerivedTimerService.cpp