EMil: services::FlashMultipleAccess Class Reference
services::FlashMultipleAccess Class Reference
#include <FlashMultipleAccess.hpp>
Public Member Functions
FlashMultipleAccess (FlashMultipleAccessMaster &master)
virtual uint32_t NumberOfSectors () const override
virtual uint32_t SizeOfSector (uint32_t sectorIndex) const override
virtual uint32_t SectorOfAddress (uint32_t address) const override
virtual uint32_t AddressOfSector (uint32_t sectorIndex) const override
virtual void WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override
virtual void EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override
Public Member Functions inherited from hal::Flash
uint32_t TotalSize () const
uint32_t StartOfSector (uint32_t address) const
uint32_t AddressOffsetInSector (uint32_t address) const
uint32_t StartOfNextSector (uint32_t address) const
uint32_t StartOfPreviousSector (uint32_t address) const
uint32_t StartOfNextSectorCyclical (uint32_t address) const
uint32_t StartOfPreviousSectorCyclical (uint32_t address) const
bool AtStartOfSector (uint32_t address) const
void EraseSector (uint32_t sectorIndex, infra::Function< void()> onDone)
void EraseAll (infra::Function< void()> onDone)
Private Attributes
FlashMultipleAccessMaster & master
infra::ClaimableResource::Claimer::WithSize< SERVICES_FLASH_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE > claimer
infra::AutoResetFunction< void()> onDone
Additional Inherited Members
Protected Member Functions inherited from hal::Flash
Flash ()=default
Flash (const Flash &other)=delete
Flash & operator= (const Flash &other)=delete
~Flash ()=default
Detailed Description
Definition at line 33 of file FlashMultipleAccess.hpp.
Constructor & Destructor Documentation
FlashMultipleAccess()
services::FlashMultipleAccess::FlashMultipleAccess (FlashMultipleAccessMaster & master) explicit
Definition at line 44 of file FlashMultipleAccess.cpp.
         : master(master)
         , claimer(master)
     {}
Member Function Documentation
AddressOfSector()
uint32_t services::FlashMultipleAccess::AddressOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 64 of file FlashMultipleAccess.cpp.
References services::FlashMultipleAccessMaster::AddressOfSector(), and master.
     {
         return master.AddressOfSector(sectorIndex);
     }
EraseSectors()
void services::FlashMultipleAccess::EraseSectors (uint32_t beginIndex, uint32_t endIndex, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 81 of file FlashMultipleAccess.cpp.
References claimer, services::FlashMultipleAccessMaster::EraseSectors(), master, and onDone.
     {
         this->onDone = onDone;
         claimer.Claim([this, beginIndex, endIndex, onDone]() { master.EraseSectors(beginIndex, endIndex, [this]() { claimer.Release(); this->onDone(); }); });
     }
NumberOfSectors()
uint32_t services::FlashMultipleAccess::NumberOfSectors () const override virtual
Implements hal::Flash.
Definition at line 49 of file FlashMultipleAccess.cpp.
References master, and services::FlashMultipleAccessMaster::NumberOfSectors().
     {
         return master.NumberOfSectors();
     }
ReadBuffer()
void services::FlashMultipleAccess::ReadBuffer (infra::ByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 75 of file FlashMultipleAccess.cpp.
References claimer, master, onDone, and services::FlashMultipleAccessMaster::ReadBuffer().
     {
         this->onDone = onDone;
         claimer.Claim([this, buffer, address, onDone]() { master.ReadBuffer(buffer, address, [this]() { claimer.Release(); this->onDone(); }); });
     }
SectorOfAddress()
uint32_t services::FlashMultipleAccess::SectorOfAddress (uint32_t address) const override virtual
Implements hal::Flash.
Definition at line 59 of file FlashMultipleAccess.cpp.
References master, and services::FlashMultipleAccessMaster::SectorOfAddress().
     {
         return master.SectorOfAddress(address);
     }
SizeOfSector()
uint32_t services::FlashMultipleAccess::SizeOfSector (uint32_t sectorIndex) const override virtual
Implements hal::Flash.
Definition at line 54 of file FlashMultipleAccess.cpp.
References master, and services::FlashMultipleAccessMaster::SizeOfSector().
     {
         return master.SizeOfSector(sectorIndex);
     }
WriteBuffer()
void services::FlashMultipleAccess::WriteBuffer (infra::ConstByteRange buffer, uint32_t address, infra::Function< void()> onDone) override virtual
Implements hal::Flash.
Definition at line 69 of file FlashMultipleAccess.cpp.
References claimer, master, onDone, and services::FlashMultipleAccessMaster::WriteBuffer().
     {
         this->onDone = onDone;
         claimer.Claim([this, buffer, address, onDone]() { master.WriteBuffer(buffer, address, [this]() { claimer.Release(); this->onDone(); }); });
     }
Member Data Documentation
claimer
infra::ClaimableResource::Claimer::WithSize<SERVICES_FLASH_MULTIPLE_ACCESS_FUNCTION_EXTRA_SIZE> services::FlashMultipleAccess::claimer private
Definition at line 49 of file FlashMultipleAccess.hpp.
Referenced by EraseSectors(), ReadBuffer(), and WriteBuffer().
master
FlashMultipleAccessMaster& services::FlashMultipleAccess::master private
Definition at line 48 of file FlashMultipleAccess.hpp.
Referenced by AddressOfSector(), EraseSectors(), NumberOfSectors(), ReadBuffer(), SectorOfAddress(), SizeOfSector(), and WriteBuffer().
onDone
infra::AutoResetFunction<void()> services::FlashMultipleAccess::onDone private
Definition at line 50 of file FlashMultipleAccess.hpp.
Referenced by EraseSectors(), ReadBuffer(), and WriteBuffer().
The documentation for this class was generated from the following files:
FlashMultipleAccess.hpp
FlashMultipleAccess.cpp