EMil: HttpServerTest Class Reference
HttpServerTest Class Reference
Public Member Functions
HttpServerTest ()
~HttpServerTest ()
void ExpectPageServerRequest (services::HttpVerb verb, const std::string &request)
void SendResponse (infra::BoundedConstString status, infra::BoundedConstString contentType, infra::BoundedConstString body)
void CheckHttpResponse (const char *result, const char *body)
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< services::ConnectionStub > connection
infra::SharedPtr< services::ConnectionStub > connectionPtr
testing::StrictMock< services::ConnectionFactoryMock > connectionFactoryMock
infra::Execute execute
testing::StrictMock< services::HttpPageMock > httpPage
services::DefaultHttpServer::WithBuffer< 256 > httpServer
services::HttpServerConnection * httpConnection
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 11 of file TestHttpServer.cpp.
Constructor & Destructor Documentation
HttpServerTest()
HttpServerTest::HttpServerTest () inline
Definition at line 16 of file TestHttpServer.cpp.
References services::both, and connectionFactoryMock.
         : connectionPtr(infra::UnOwnedSharedPtr(connection))
         , execute([this]() { EXPECT_CALL(connectionFactoryMock, ListenMock(80, services::IPVersions::both)).WillOnce(testing::Return(nullptr)); })
         , httpServer(connectionFactoryMock, 80)
     {
         httpServer.AddPage(httpPage);
     }
~HttpServerTest()
HttpServerTest::~HttpServerTest () inline
Definition at line 24 of file TestHttpServer.cpp.
References infra::emptyFunction, and httpServer.
     {
         httpServer.Stop(infra::emptyFunction);
     }
Member Function Documentation
CheckHttpResponse()
void HttpServerTest::CheckHttpResponse (const char * result, const char * body) inline
Definition at line 52 of file TestHttpServer.cpp.
References connection, and EXPECT_EQ().
     {
         std::string response = std::string("HTTP/1.1 ") + result + "\r\n" +
             "Content-Length: " + std::to_string(std::strlen(body)) + "\r\n" +
             "Content-Type: application/json\r\n" +
             "\r\n" +
             body;
         EXPECT_EQ(std::vector<uint8_t>(response.begin(), response.end()), connection.sentData);
         connection.sentData.clear();
     }
ExpectPageServerRequest()
void HttpServerTest::ExpectPageServerRequest (services::HttpVerb verb, const std::string & request) inline
Definition at line 29 of file TestHttpServer.cpp.
References connection, data, EXPECT_EQ(), httpConnection, httpPage, infra::Lambda(), infra::MakeStringByteRange(), and services::HttpRequestParser::Verb().
     {
         EXPECT_CALL(httpPage, ServesRequest(testing::_)).WillOnce(testing::Return(true));
         EXPECT_CALL(httpPage, RespondToRequest(testing::_, testing::_)).WillOnce(infra::Lambda([this, verb](services::HttpRequestParser& parser, services::HttpServerConnection& connection)
         {
             EXPECT_EQ(verb, parser.Verb());
             httpConnection = &connection;
         }));
         infra::ConstByteRange data = infra::MakeStringByteRange(request);
         connection.SimulateDataReceived(data);
         ExecuteAllActions();
     }
SendResponse()
void HttpServerTest::SendResponse (infra::BoundedConstString status, infra::BoundedConstString contentType, infra::BoundedConstString body) inline
Definition at line 42 of file TestHttpServer.cpp.
References httpConnection, infra::Lambda(), and services::HttpServerConnection::SendResponse().
     {
         testing::StrictMock<services::HttpResponseMock> response(1024);
         EXPECT_CALL(response, ContentType()).WillOnce(testing::Return(contentType));
         EXPECT_CALL(response, AddHeaders(testing::_));
         EXPECT_CALL(response, WriteBody(testing::_)).WillOnce(infra::Lambda([body](infra::TextOutputStream& stream) { stream << body; }));
         EXPECT_CALL(response, Status()).WillOnce(testing::Return(status));
         httpConnection->SendResponse(response);
     }
Member Data Documentation
connection
testing::StrictMock<services::ConnectionStub> HttpServerTest::connection
Definition at line 64 of file TestHttpServer.cpp.
Referenced by CheckHttpResponse(), and ExpectPageServerRequest().
connectionFactoryMock
testing::StrictMock<services::ConnectionFactoryMock> HttpServerTest::connectionFactoryMock
Definition at line 66 of file TestHttpServer.cpp.
Referenced by HttpServerTest().
connectionPtr
infra::SharedPtr<services::ConnectionStub> HttpServerTest::connectionPtr
Definition at line 65 of file TestHttpServer.cpp.
execute
infra::Execute HttpServerTest::execute
Definition at line 67 of file TestHttpServer.cpp.
httpConnection
services::HttpServerConnection* HttpServerTest::httpConnection
Definition at line 70 of file TestHttpServer.cpp.
Referenced by ExpectPageServerRequest(), and SendResponse().
httpPage
testing::StrictMock<services::HttpPageMock> HttpServerTest::httpPage
Definition at line 68 of file TestHttpServer.cpp.
Referenced by ExpectPageServerRequest().
httpServer
services::DefaultHttpServer::WithBuffer<256> HttpServerTest::httpServer
Definition at line 69 of file TestHttpServer.cpp.
Referenced by ~HttpServerTest().
The documentation for this class was generated from the following file:
TestHttpServer.cpp