EMil: hal::SerialCommunication Class Reference
hal::SerialCommunication Class Reference abstract
#include <SerialCommunication.hpp>
Public Member Functions
virtual void SendData (infra::ConstByteRange data, infra::Function< void()> actionOnCompletion)=0
virtual void ReceiveData (infra::Function< void(infra::ConstByteRange data)> dataReceived)=0
Protected Member Functions
SerialCommunication ()=default
~SerialCommunication ()=default
Detailed Description
Definition at line 8 of file SerialCommunication.hpp.
Constructor & Destructor Documentation
SerialCommunication()
hal::SerialCommunication::SerialCommunication () protected default
~SerialCommunication()
hal::SerialCommunication::~SerialCommunication () protected default
Member Function Documentation
ReceiveData()
virtual void hal::SerialCommunication::ReceiveData (infra::Function< void(infra::ConstByteRange data)> dataReceived) pure virtual
Implemented in hal::LowPowerSerialCommunication.
Referenced by hal::LowPowerSerialCommunication::ReceiveData().
SendData()
virtual void hal::SerialCommunication::SendData (infra::ConstByteRange data, infra::Function< void()> actionOnCompletion) pure virtual
Implemented in hal::LowPowerSerialCommunication.
Referenced by services::Terminal::EraseCharacterUnderCursor(), services::Terminal::MoveCursorEnd(), services::Terminal::MoveCursorHome(), services::Terminal::MoveCursorLeft(), services::Terminal::MoveCursorRight(), services::Terminal::OverwriteBuffer(), services::Terminal::Print(), services::Terminal::SendBell(), services::ConnectionSerial::StateConnectedSendingContent::SendContentWithSize(), hal::LowPowerSerialCommunication::SendData(), services::Terminal::SendNonEscapeChar(), services::ConnectionSerial::StateConnectedSendingContent::SendPartialContent(), services::ConnectionSerial::StateSendingUpdate::SendUpdate(), services::ConnectionSerial::StateInitSizeRequest::SendWindowSizeRequest(), services::ConnectionSerial::StateInitSizeResponse::SendWindowSizeResponse(), services::ConnectionSerial::StateInitSizeResponseRequest::SendWindowSizeResponseRequest(), and services::StreamWriterOnSerialCommunication::TrySend().
The documentation for this class was generated from the following file:
SerialCommunication.hpp