EMil: services::ConnectionFactoryWithNameResolverStub Class Reference
services::ConnectionFactoryWithNameResolverStub Class Reference
#include <ConnectionFactoryWithNameResolverStub.hpp>
Public Member Functions
ConnectionFactoryWithNameResolverStub (services::ConnectionFactory &connectionFactory, services::IPAddress address)
virtual void Connect (services::ClientConnectionObserverFactoryWithNameResolver &factory) override
virtual void CancelConnect (services::ClientConnectionObserverFactoryWithNameResolver &factory) override
virtual services::IPAddress Address () const override
virtual uint16_t Port () const override
virtual void ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> &&createdObserver)
virtual void ConnectionFailed (ConnectFailReason reason)
Private Attributes
services::ConnectionFactory & connectionFactory
services::IPAddress address
services::ClientConnectionObserverFactoryWithNameResolver * client = nullptr
Additional Inherited Members
Protected Member Functions inherited from services::ConnectionFactoryWithNameResolver
ConnectionFactoryWithNameResolver ()=default
ConnectionFactoryWithNameResolver (const ConnectionFactoryWithNameResolver &other)=delete
ConnectionFactoryWithNameResolver & operator= (const ConnectionFactoryWithNameResolver &other)=delete
~ConnectionFactoryWithNameResolver ()=default
Private Types inherited from services::ClientConnectionObserverFactory
enum ConnectFailReason { refused, connectionAllocationFailed }
ClientConnectionObserverFactory ()=default
ClientConnectionObserverFactory (const ClientConnectionObserverFactory &other)=delete
ClientConnectionObserverFactory & operator= (const ClientConnectionObserverFactory &other)=delete
~ClientConnectionObserverFactory ()=default
Private Member Functions inherited from infra::detail::IntrusiveListNode< T >
IntrusiveListNode (const IntrusiveListNode &other)
IntrusiveListNode & operator= (const IntrusiveListNode &other)
IntrusiveListNode ()
~IntrusiveListNode ()=default
Detailed Description
Definition at line 8 of file ConnectionFactoryWithNameResolverStub.hpp.
Constructor & Destructor Documentation
ConnectionFactoryWithNameResolverStub()
services::ConnectionFactoryWithNameResolverStub::ConnectionFactoryWithNameResolverStub (services::ConnectionFactory & connectionFactory, services::IPAddress address)
Definition at line 5 of file ConnectionFactoryWithNameResolverStub.cpp.
         : connectionFactory(connectionFactory)
         , address(address)
     {}
Member Function Documentation
Address()
services::IPAddress services::ConnectionFactoryWithNameResolverStub::Address () const override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 21 of file ConnectionFactoryWithNameResolverStub.cpp.
References address.
     {
         return address;
     }
CancelConnect()
void services::ConnectionFactoryWithNameResolverStub::CancelConnect (services::ClientConnectionObserverFactoryWithNameResolver & factory) override virtual
Implements services::ConnectionFactoryWithNameResolver.
Definition at line 16 of file ConnectionFactoryWithNameResolverStub.cpp.
References services::ConnectionFactory::CancelConnect(), and connectionFactory.
     {
         connectionFactory.CancelConnect(*this);
     }
Connect()
void services::ConnectionFactoryWithNameResolverStub::Connect (services::ClientConnectionObserverFactoryWithNameResolver & factory) override virtual
Implements services::ConnectionFactoryWithNameResolver.
Definition at line 10 of file ConnectionFactoryWithNameResolverStub.cpp.
References client, services::ConnectionFactory::Connect(), and connectionFactory.
     {
         client = &factory;
         connectionFactory.Connect(*this);
     }
ConnectionEstablished()
void services::ConnectionFactoryWithNameResolverStub::ConnectionEstablished (infra::AutoResetFunction< void(infra::SharedPtr< services::ConnectionObserver > connectionObserver)> && createdObserver) virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 31 of file ConnectionFactoryWithNameResolverStub.cpp.
References client, and services::ClientConnectionObserverFactoryWithNameResolver::ConnectionEstablished().
     {
         client->ConnectionEstablished(std::move(createdObserver));
     }
ConnectionFailed()
void services::ConnectionFactoryWithNameResolverStub::ConnectionFailed (ConnectFailReason reason) virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 36 of file ConnectionFactoryWithNameResolverStub.cpp.
References client, and services::ClientConnectionObserverFactoryWithNameResolver::ConnectionFailed().
     {
         client->ConnectionFailed(reason == ConnectFailReason::connectionAllocationFailed ? services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::connectionAllocationFailed
             : services::ClientConnectionObserverFactoryWithNameResolver::ConnectFailReason::refused);
     }
Port()
uint16_t services::ConnectionFactoryWithNameResolverStub::Port () const override virtual
Implements services::ClientConnectionObserverFactory.
Definition at line 26 of file ConnectionFactoryWithNameResolverStub.cpp.
References client, and services::ClientConnectionObserverFactoryWithNameResolver::Port().
     {
         return client->Port();
     }
Member Data Documentation
address
services::IPAddress services::ConnectionFactoryWithNameResolverStub::address private
Definition at line 27 of file ConnectionFactoryWithNameResolverStub.hpp.
Referenced by Address().
client
services::ClientConnectionObserverFactoryWithNameResolver* services::ConnectionFactoryWithNameResolverStub::client = nullptr private
Definition at line 29 of file ConnectionFactoryWithNameResolverStub.hpp.
Referenced by Connect(), ConnectionEstablished(), ConnectionFailed(), and Port().
connectionFactory
services::ConnectionFactory& services::ConnectionFactoryWithNameResolverStub::connectionFactory private
Definition at line 26 of file ConnectionFactoryWithNameResolverStub.hpp.
Referenced by CancelConnect(), and Connect().
The documentation for this class was generated from the following files:
ConnectionFactoryWithNameResolverStub.hpp
ConnectionFactoryWithNameResolverStub.cpp