EMil: services::DnsResolver Class Reference
services::DnsResolver Class Reference
#include <DnsResolver.hpp>
Classes
class ActiveLookup
struct Answer
struct CName
struct DnsServers
class HostnameParts
class HostnamePartsStream
class HostnamePartsString
struct NoAnswer
struct QueryHeader
struct QuestionFooter
class ReplyParser
struct ResourceInner
Public Member Functions
DnsResolver (DatagramFactory &datagramFactory, const DnsServers &nameServers, hal::SynchronousRandomDataGenerator &randomDataGenerator)
virtual void Lookup (NameResolverResult &result) override
virtual void CancelLookup (NameResolverResult &result) override
Private Member Functions
void TryResolveNext ()
void Resolve (NameResolverResult &nameLookup)
void NameLookupSuccess (NameResolverResult &nameLookup, IPAddress address, infra::TimePoint validUntil)
void NameLookupFailed (NameResolverResult &nameLookup)
void NameLookupCancelled ()
void NameLookupDone (const infra::Function< void(), 3 *sizeof(void *)> &observerCallback)
Private Attributes
DatagramFactory & datagramFactory
hal::SynchronousRandomDataGenerator & randomDataGenerator
infra::MemoryRange< const IPAddress > nameServers
std::size_t currentNameServer = 0
infra::IntrusiveList< NameResolverResult > waiting
infra::Optional< ActiveLookup > activeLookup
Static Private Attributes
static const infra::Duration responseTimeout = std::chrono::seconds(5)
static const uint8_t maxAttempts = 3
static const uint8_t maxRecursions = 5
Additional Inherited Members
Protected Member Functions inherited from services::NameResolver
NameResolver ()=default
NameResolver (const NameResolver &other)=delete
NameResolver & operator= (const NameResolver &other)=delete
~NameResolver ()=default
Detailed Description
Definition at line 16 of file DnsResolver.hpp.
Constructor & Destructor Documentation
DnsResolver()
services::DnsResolver::DnsResolver (DatagramFactory & datagramFactory, const DnsServers & nameServers, hal::SynchronousRandomDataGenerator & randomDataGenerator)
Definition at line 10 of file DnsResolver.cpp.
         : datagramFactory(datagramFactory)
         , randomDataGenerator(randomDataGenerator)
         , nameServers(nameServers.nameServers)
     {
         assert(!this->nameServers.empty());
     }
Member Function Documentation
CancelLookup()
void services::DnsResolver::CancelLookup (NameResolverResult & result) override virtual
Implements services::NameResolver.
Definition at line 25 of file DnsResolver.cpp.
References activeLookup, NameLookupCancelled(), and waiting.
     {
         if (!activeLookup->IsResolving(result))
         {
             assert(waiting.has_element(result));
             waiting.erase(result);
         }
         else
             NameLookupCancelled();
     }
Lookup()
void services::DnsResolver::Lookup (NameResolverResult & result) override virtual
Implements services::NameResolver.
Definition at line 18 of file DnsResolver.cpp.
References TryResolveNext(), and waiting.
     {
         assert(!waiting.has_element(result));
         waiting.push_back(result);
         TryResolveNext();
     }
NameLookupCancelled()
void services::DnsResolver::NameLookupCancelled () private
Definition at line 63 of file DnsResolver.cpp.
References NameLookupDone().
Referenced by CancelLookup().
     {
         NameLookupDone([]() {});
     }
NameLookupDone()
void services::DnsResolver::NameLookupDone (const infra::Function< void(), 3 *sizeof(void *)> & observerCallback) private
Definition at line 68 of file DnsResolver.cpp.
References activeLookup, infra::none, and TryResolveNext().
Referenced by NameLookupCancelled(), NameLookupFailed(), and NameLookupSuccess().
     {
         activeLookup = infra::none;
         observerCallback();
         TryResolveNext();
     }
NameLookupFailed()
void services::DnsResolver::NameLookupFailed (NameResolverResult & nameLookup) private
Definition at line 58 of file DnsResolver.cpp.
References NameLookupDone(), and services::NameResolverResult::NameLookupFailed().
     {
         NameLookupDone([&nameLookup]() { nameLookup.NameLookupFailed(); });
     }
NameLookupSuccess()
void services::DnsResolver::NameLookupSuccess (NameResolverResult & nameLookup, IPAddress address, infra::TimePoint validUntil) private
Definition at line 53 of file DnsResolver.cpp.
References services::NameResolverResult::NameLookupDone(), and NameLookupDone().
     {
         NameLookupDone([&nameLookup, &address, &validUntil]() { nameLookup.NameLookupDone(address, validUntil); });
     }
Resolve()
void services::DnsResolver::Resolve (NameResolverResult & nameLookup) private
Definition at line 45 of file DnsResolver.cpp.
References activeLookup, currentNameServer, and nameServers.
Referenced by TryResolveNext().
     {
         activeLookup.Emplace(*this, nameLookup);
         ++currentNameServer;
         if (currentNameServer == nameServers.size())
             currentNameServer = 0;
     }
TryResolveNext()
void services::DnsResolver::TryResolveNext () private
Definition at line 36 of file DnsResolver.cpp.
References activeLookup, infra::none, Resolve(), and waiting.
Referenced by Lookup(), and NameLookupDone().
     {
         if (activeLookup == infra::none && !waiting.empty())
         {
             Resolve(waiting.front());
             waiting.pop_front();
         }
     }
Member Data Documentation
activeLookup
infra::Optional<ActiveLookup> services::DnsResolver::activeLookup private
Definition at line 226 of file DnsResolver.hpp.
Referenced by CancelLookup(), NameLookupDone(), Resolve(), and TryResolveNext().
currentNameServer
std::size_t services::DnsResolver::currentNameServer = 0 private
Definition at line 224 of file DnsResolver.hpp.
Referenced by services::DnsResolver::ReplyParser::AnswerIsForCurrentQuery(), services::DnsResolver::ActiveLookup::DnsUpdSocket(), Resolve(), services::DnsResolver::ActiveLookup::SelectNextNameServer(), and services::DnsResolver::ActiveLookup::TryNewNameServers().
datagramFactory
DatagramFactory& services::DnsResolver::datagramFactory private
Definition at line 221 of file DnsResolver.hpp.
maxAttempts
const uint8_t services::DnsResolver::maxAttempts = 3 static private
Definition at line 33 of file DnsResolver.hpp.
Referenced by services::DnsResolver::ActiveLookup::ResolveNextAttempt().
maxRecursions
const uint8_t services::DnsResolver::maxRecursions = 5 static private
Definition at line 34 of file DnsResolver.hpp.
Referenced by services::DnsResolver::ActiveLookup::ResolveRecursion().
nameServers
infra::MemoryRange<const IPAddress> services::DnsResolver::nameServers private
Definition at line 223 of file DnsResolver.hpp.
Referenced by Resolve(), services::DnsResolver::ActiveLookup::SelectNextNameServer(), and services::DnsResolver::ActiveLookup::TryNewNameServers().
randomDataGenerator
hal::SynchronousRandomDataGenerator& services::DnsResolver::randomDataGenerator private
Definition at line 222 of file DnsResolver.hpp.
responseTimeout
const infra::Duration services::DnsResolver::responseTimeout = std::chrono::seconds(5) static private
Definition at line 32 of file DnsResolver.hpp.
Referenced by services::DnsResolver::ActiveLookup::SendStreamAvailable().
waiting
infra::IntrusiveList<NameResolverResult> services::DnsResolver::waiting private
Definition at line 225 of file DnsResolver.hpp.
Referenced by CancelLookup(), Lookup(), and TryResolveNext().
The documentation for this class was generated from the following files:
DnsResolver.hpp
DnsResolver.cpp