EMil: hal::InputPin Class Reference
hal::InputPin Class Reference
#include <Gpio.hpp>
Public Member Functions
InputPin (GpioPin &pin)
InputPin (const InputPin &other)=delete
InputPin & operator= (const InputPin &other)=delete
~InputPin ()
bool Get () const
void EnableInterrupt (const infra::Function< void()> &action, InterruptTrigger trigger)
void DisableInterrupt ()
Private Attributes
GpioPin & pin
Detailed Description
Definition at line 51 of file Gpio.hpp.
Constructor & Destructor Documentation
InputPin() [1/2]
hal::InputPin::InputPin (GpioPin & pin) explicit
Definition at line 7 of file Gpio.cpp.
References hal::GpioPin::Config(), hal::input, and pin.
         : pin(pin)
     {
         pin.Config(PinConfigType::input);
     }
InputPin() [2/2]
hal::InputPin::InputPin (const InputPin & other) delete
~InputPin()
hal::InputPin::~InputPin ()
Definition at line 13 of file Gpio.cpp.
References pin, and hal::GpioPin::ResetConfig().
     {
         pin.ResetConfig();
     }
Member Function Documentation
DisableInterrupt()
void hal::InputPin::DisableInterrupt ()
Definition at line 28 of file Gpio.cpp.
References hal::GpioPin::DisableInterrupt(), and pin.
Referenced by services::DebouncedButton::~DebouncedButton().
     {
         pin.DisableInterrupt();
     }
EnableInterrupt()
void hal::InputPin::EnableInterrupt (const infra::Function< void()> & action, InterruptTrigger trigger)
Definition at line 23 of file Gpio.cpp.
References hal::GpioPin::EnableInterrupt(), and pin.
     {
         pin.EnableInterrupt(action, trigger);
     }
Get()
bool hal::InputPin::Get () const
Definition at line 18 of file Gpio.cpp.
References hal::GpioPin::Get(), and pin.
Referenced by services::DebouncedButton::ButtonChanged(), services::RepeatingButton::ButtonChanged(), and services::RepeatingButton::DebounceEnd().
     {
         return pin.Get();
     }
operator=()
InputPin& hal::InputPin::operator= (const InputPin & other) delete
Member Data Documentation
pin
GpioPin& hal::InputPin::pin private
Definition at line 65 of file Gpio.hpp.
Referenced by DisableInterrupt(), EnableInterrupt(), Get(), InputPin(), and ~InputPin().
The documentation for this class was generated from the following files:
Gpio.hpp
Gpio.cpp