EMil: TestBoundedPriorityQueue.cpp File Reference
TestBoundedPriorityQueue.cpp File Reference
Functions
TEST (BoundedPriorityQueueTest, TestConstructedEmpty)
TEST (BoundedPriorityQueueTest, TestConstructionWithRange)
TEST (BoundedPriorityQueueTest, TestCopyConstruction)
TEST (BoundedPriorityQueueTest, TestMoveConstruction)
TEST (BoundedPriorityQueueTest, TestAssignment)
TEST (BoundedPriorityQueueTest, TestMove)
TEST (BoundedPriorityQueueTest, TestPop)
TEST (BoundedPriorityQueueTest, TestErase)
TEST (BoundedPriorityQueueTest, TestErase2)
TEST (BoundedPriorityQueueTest, TestEraseLastElement)
TEST (BoundedPriorityQueueTest, TestBeginAndEnd)
TEST (BoundedPriorityQueueTest, TestFull)
TEST (BoundedPriorityQueueTest, TestSwap)
TEST (BoundedPriorityQueueTest, TestSwapDifferentSizes)
TEST (BoundedPriorityQueueTest, TestClear)
Function Documentation
TEST() [1/15]
TEST (BoundedPriorityQueueTest , TestConstructedEmpty)
Definition at line 5 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::empty(), EXPECT_EQ(), EXPECT_FALSE(), EXPECT_TRUE(), infra::BoundedPriorityQueue< T, Max, Compare >::full(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     infra::BoundedPriorityQueue<int, 5> queue;
     EXPECT_TRUE(queue.empty());
     EXPECT_FALSE(queue.full());
     EXPECT_EQ(0, queue.size());
 }
TEST() [2/15]
TEST (BoundedPriorityQueueTest , TestConstructionWithRange)
Definition at line 14 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::begin(), EXPECT_EQ(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedPriorityQueue<int, 5> queue(range, range + 3);
     EXPECT_EQ(3, queue.size());
     EXPECT_EQ(2, *queue.begin());
     EXPECT_EQ(1, *(queue.begin() + 1));
     EXPECT_EQ(0, *(queue.begin() + 2));
 }
TEST() [3/15]
TEST (BoundedPriorityQueueTest , TestCopyConstruction)
Definition at line 26 of file TestBoundedPriorityQueue.cpp.
References EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::push(), infra::BoundedPriorityQueue< T, Max, Compare >::size(), and infra::BoundedPriorityQueue< T, Max, Compare >::top().
 {
     infra::BoundedPriorityQueue<int, 5> original;
     original.push(4);
     infra::BoundedPriorityQueue<int, 5> copy(original);
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(4, copy.top());
 }
TEST() [4/15]
TEST (BoundedPriorityQueueTest , TestMoveConstruction)
Definition at line 36 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::emplace(), EXPECT_EQ(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     infra::BoundedPriorityQueue<infra::MoveConstructible, 5> original;
     original.emplace(2);
     infra::BoundedPriorityQueue<infra::MoveConstructible, 5> copy(std::move(original));
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy[0].x);
 }
TEST() [5/15]
TEST (BoundedPriorityQueueTest , TestAssignment)
Definition at line 46 of file TestBoundedPriorityQueue.cpp.
References EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::push(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     infra::BoundedPriorityQueue<int, 5> original;
     original.push(4);
     infra::BoundedPriorityQueue<int, 5> copy;
     copy = original;
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(4, copy[0]);
 }
TEST() [6/15]
TEST (BoundedPriorityQueueTest , TestMove)
Definition at line 57 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::emplace(), EXPECT_EQ(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     infra::BoundedPriorityQueue<infra::MoveConstructible, 5> original;
     original.emplace(2);
     infra::BoundedPriorityQueue<infra::MoveConstructible, 5> copy;
     copy = std::move(original);
     EXPECT_EQ(1, copy.size());
     EXPECT_EQ(2, copy[0].x);
 }
TEST() [7/15]
TEST (BoundedPriorityQueueTest , TestPop)
Definition at line 68 of file TestBoundedPriorityQueue.cpp.
References EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::pop(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedPriorityQueue<int, 5> queue(range, range + 3);
     queue.pop();
     EXPECT_EQ(2, queue.size());
     EXPECT_EQ(1, queue[0]);
     EXPECT_EQ(0, queue[1]);
 }
TEST() [8/15]
TEST (BoundedPriorityQueueTest , TestErase)
Definition at line 79 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::begin(), infra::BoundedPriorityQueue< T, Max, Compare >::erase(), EXPECT_EQ(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     int range[7] = { 0, 1, 2, 3, 4, 5, 6 };
     infra::BoundedPriorityQueue<int, 10> queue(range, range + 7);
     queue.erase(queue.begin() + 1);
     EXPECT_EQ(6, queue.size());
     EXPECT_EQ(6, queue[0]);
     EXPECT_EQ(3, queue[1]);
     EXPECT_EQ(5, queue[2]);
     EXPECT_EQ(2, queue[3]);
     EXPECT_EQ(1, queue[4]);
     EXPECT_EQ(0, queue[5]);
 }
TEST() [9/15]
TEST (BoundedPriorityQueueTest , TestErase2)
Definition at line 94 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::begin(), infra::BoundedPriorityQueue< T, Max, Compare >::erase(), EXPECT_EQ(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     int range[7] = { 0, 3, 2, 1, 4, 5, 6 };
     infra::BoundedPriorityQueue<int, 10> queue(range, range + 7);
     queue.erase(queue.begin() + 1);
     EXPECT_EQ(6, queue.size());
     EXPECT_EQ(6, queue[0]);
     EXPECT_EQ(3, queue[1]);
     EXPECT_EQ(5, queue[2]);
     EXPECT_EQ(1, queue[3]);
     EXPECT_EQ(2, queue[4]);
     EXPECT_EQ(0, queue[5]);
 }
TEST() [10/15]
TEST (BoundedPriorityQueueTest , TestEraseLastElement)
Definition at line 109 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::begin(), infra::BoundedPriorityQueue< T, Max, Compare >::erase(), EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::push(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     infra::BoundedPriorityQueue<int, 10> queue;
     queue.push(1);
     queue.erase(queue.begin());
     EXPECT_EQ(0, queue.size());
 }
TEST() [11/15]
TEST (BoundedPriorityQueueTest , TestBeginAndEnd)
Definition at line 118 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::begin(), infra::BoundedPriorityQueue< T, Max, Compare >::cbegin(), infra::BoundedPriorityQueue< T, Max, Compare >::cend(), infra::BoundedPriorityQueue< T, Max, Compare >::end(), EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::rbegin(), and infra::BoundedPriorityQueue< T, Max, Compare >::rend().
 {
     int range[3] = { 0, 1, 2};
     infra::BoundedPriorityQueue<int, 5> queue(range, range + 3);
     EXPECT_EQ(queue.end(), queue.begin() + 3);
     EXPECT_EQ(queue.cbegin(), queue.begin());
     EXPECT_EQ(queue.cend(), queue.end());
     EXPECT_EQ(queue.rend(), queue.rbegin() + 3);
     EXPECT_EQ(2, *queue.begin());
     EXPECT_EQ(0, *queue.rbegin());
 }
TEST() [12/15]
TEST (BoundedPriorityQueueTest , TestFull)
Definition at line 132 of file TestBoundedPriorityQueue.cpp.
References EXPECT_TRUE(), infra::BoundedPriorityQueue< T, Max, Compare >::full(), and infra::BoundedPriorityQueue< T, Max, Compare >::push().
 {
     infra::BoundedPriorityQueue<int, 1> queue;
     queue.push(5);
     EXPECT_TRUE(queue.full());
 }
TEST() [13/15]
TEST (BoundedPriorityQueueTest , TestSwap)
Definition at line 140 of file TestBoundedPriorityQueue.cpp.
References EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::size(), infra::swap(), and infra::BoundedPriorityQueue< T, Max, Compare >::top().
 {
     int range1[3] = { 0, 1, 2};
     infra::BoundedPriorityQueue<int, 5> queue1(range1, range1 + 3);
     int range2[3] = { 3, 4, 5};
     infra::BoundedPriorityQueue<int, 5> queue2(range2, range2 + 3);
     swap(queue1, queue2);
     EXPECT_EQ(3, queue1.size());
     EXPECT_EQ(5, queue1.top());
     EXPECT_EQ(3, queue2.size());
     EXPECT_EQ(2, queue2.top());
 }
TEST() [14/15]
TEST (BoundedPriorityQueueTest , TestSwapDifferentSizes)
Definition at line 155 of file TestBoundedPriorityQueue.cpp.
References EXPECT_EQ(), infra::BoundedPriorityQueue< T, Max, Compare >::size(), infra::swap(), and infra::BoundedPriorityQueue< T, Max, Compare >::top().
 {
     int range1[3] = { 0, 1, 2};
     infra::BoundedPriorityQueue<int, 5> queue1(range1, range1 + 3);
     int range2[2] = { 3, 4};
     infra::BoundedPriorityQueue<int, 5> queue2(range2, range2 + 2);
     swap(queue1, queue2);
     EXPECT_EQ(2, queue1.size());
     EXPECT_EQ(4, queue1.top());
     EXPECT_EQ(3, queue2.size());
     EXPECT_EQ(2, queue2.top());
 }
TEST() [15/15]
TEST (BoundedPriorityQueueTest , TestClear)
Definition at line 170 of file TestBoundedPriorityQueue.cpp.
References infra::BoundedPriorityQueue< T, Max, Compare >::clear(), infra::BoundedPriorityQueue< T, Max, Compare >::empty(), EXPECT_EQ(), EXPECT_TRUE(), infra::BoundedPriorityQueue< T, Max, Compare >::push(), and infra::BoundedPriorityQueue< T, Max, Compare >::size().
 {
     infra::BoundedPriorityQueue<int, 5> queue;
     queue.push(5);
     queue.clear();
     EXPECT_EQ(0, queue.size());
     EXPECT_TRUE(queue.empty());
 }