EMil: DnsResolverTest Class Reference
DnsResolverTest Class Reference
Public Member Functions
DnsResolverTest ()
auto && ExpectRequestSendStream (services::NameResolverResultMock &result, infra::BoundedConstString hostname, services::IPAddress dnsServer)
void ExpectAndRespondToRequestSendStream (services::NameResolverResultMock &result, infra::BoundedConstString hostname, services::IPAddress dnsServer)
void Lookup (services::NameResolverResultMock &result)
void GiveSendStream (services::NameResolverResultMock &result, infra::BoundedConstString hostname, services::IPAddress dnsServer)
void LookupAndGiveSendStream (services::NameResolverResultMock &result, infra::BoundedConstString hostname, services::IPAddress dnsServer)
void LookupIsRetried (services::NameResolverResultMock &result, infra::BoundedConstString hostname, services::IPAddress dnsServer)
std::vector< uint8_t > Concatenate (std::initializer_list< const std::vector< uint8_t >> vectors)
std::vector< uint8_t > ConvertDns (infra::BoundedConstString hostname)
std::vector< uint8_t > ConvertDns (services::IPv4Address address)
std::vector< uint8_t > MakeHeader (uint8_t answers, uint8_t authorativeNameServers=0, uint8_t additionRecords=0)
std::vector< uint8_t > MakeQuestion (infra::BoundedConstString hostname)
std::vector< uint8_t > MakeAnswerA (const std::vector< uint8_t > &name, services::IPv4Address answer)
std::vector< uint8_t > MakeAnswerCName (const std::vector< uint8_t > &name, infra::BoundedConstString answer)
std::vector< uint8_t > MakeAnswerNS (const std::vector< uint8_t > &name, infra::BoundedConstString answer)
std::vector< uint8_t > MakeReferenceAnswerA (services::IPv4Address address, uint8_t start=0x0c)
std::vector< uint8_t > MakeReferenceAnswerCName (infra::BoundedConstString answer, uint8_t start=0x0c)
std::vector< uint8_t > MakeReferenceAnswerNS (infra::BoundedConstString answer, uint8_t start=0x0c)
std::vector< uint8_t > MakeDnsResponse (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithUncompressedHost (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithCName (infra::BoundedConstString hostname, infra::BoundedConstString alias)
std::vector< uint8_t > MakeDnsResponseWithCNameAndAnswer (infra::BoundedConstString hostname, infra::BoundedConstString alias, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithCNameAndAnswerForDifferentHost (infra::BoundedConstString hostname, infra::BoundedConstString alias, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithCNameWithInnerReference (infra::BoundedConstString hostname, infra::BoundedConstString alias)
std::vector< uint8_t > MakeDnsResponseWithSecondCNameWithInnerReference (infra::BoundedConstString hostname, infra::BoundedConstString alias)
std::vector< uint8_t > MakeDnsResponseWithCNameWithReferenceInAnswer (infra::BoundedConstString hostname, infra::BoundedConstString alias)
std::vector< uint8_t > MakeDnsResponseWithNS (infra::BoundedConstString hostname, infra::BoundedConstString ns, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithNSTooShort (infra::BoundedConstString hostname, infra::BoundedConstString ns, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithAdditional (infra::BoundedConstString hostname, infra::BoundedConstString ns, services::IPv4Address address)
std::vector< uint8_t > MakeShortenedDnsResponse (infra::BoundedConstString hostname, services::IPv4Address address, uint32_t amountToShort)
std::vector< uint8_t > MakeDnsQuestion (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithSecondQuestion (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithDifferentId (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithDifferentType (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithDifferentClass (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithError (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithType2 (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithClass2 (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithIncorrectReference (infra::BoundedConstString hostname, services::IPv4Address address)
std::vector< uint8_t > MakeDnsResponseWithSecondAnswer (infra::BoundedConstString hostname, services::IPv4Address address)
void DataReceived (const std::vector< uint8_t > &response, services::UdpSocket from)
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
const services::IPv4Address dnsServer1 { 1, 2, 3, 4 }
const services::IPv4Address dnsServer2 { 2, 3, 4, 5 }
const services::IPv4Address hostAddress1 { 3, 4, 5, 6 }
const services::IPv4Address nsServer1 { 4, 5, 6, 7 }
testing::StrictMock< services::DatagramFactoryMock > datagramFactory
const std::array< services::IPAddress, 2 > dnsServers { dnsServer1, dnsServer2 }
testing::StrictMock< hal::SynchronousRandomDataGeneratorMock > randomDataGenerator
services::DnsResolver resolver { datagramFactory, { dnsServers }, randomDataGenerator }
testing::StrictMock< services::NameResolverResultMock > result1
testing::StrictMock< services::NameResolverResultMock > result2
testing::StrictMock< services::DatagramExchangeMock > datagram
services::DatagramExchangeObserver * datagramExchangeObserver = nullptr
testing::StrictMock< infra::StreamWriterMock > writer
infra::BoundedConstString currentHostname
infra::TimePoint expiration = infra::Now() + std::chrono::seconds(0x10000) + std::chrono::seconds(30)
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 13 of file TestDnsResolver.cpp.
Constructor & Destructor Documentation
DnsResolverTest()
DnsResolverTest::DnsResolverTest () inline
Definition at line 18 of file TestDnsResolver.cpp.
References infra::MemoryRange< T >::begin(), infra::MemoryRange< T >::end(), and randomDataGenerator.
     {
         EXPECT_CALL(randomDataGenerator, GenerateRandomData(testing::_)).WillRepeatedly(testing::Invoke([](infra::ByteRange result) { std::fill(result.begin(), result.end(), 9); }));
     }
Member Function Documentation
Concatenate()
std::vector<uint8_t> DnsResolverTest::Concatenate (std::initializer_list< const std::vector< uint8_t >> vectors) inline
Definition at line 75 of file TestDnsResolver.cpp.
Referenced by ConvertDns(), MakeAnswerA(), MakeAnswerCName(), MakeAnswerNS(), MakeDnsResponse(), MakeDnsResponseWithAdditional(), MakeDnsResponseWithCName(), MakeDnsResponseWithCNameAndAnswer(), MakeDnsResponseWithCNameWithInnerReference(), MakeDnsResponseWithCNameWithReferenceInAnswer(), MakeDnsResponseWithNS(), MakeDnsResponseWithSecondAnswer(), MakeDnsResponseWithSecondCNameWithInnerReference(), MakeDnsResponseWithUncompressedHost(), and MakeQuestion().
     {
         std::vector<uint8_t> result;
         for (auto& vector : vectors)
             result.insert(result.end(), vector.begin(), vector.end());
         return result;
     }
ConvertDns() [1/2]
std::vector<uint8_t> DnsResolverTest::ConvertDns (infra::BoundedConstString hostname) inline
Definition at line 85 of file TestDnsResolver.cpp.
References infra::BoundedStringBase< T >::begin(), Concatenate(), infra::BoundedStringBase< T >::end(), infra::Tokenizer::Size(), infra::BoundedStringBase< T >::size(), and infra::Tokenizer::Token().
Referenced by MakeAnswerA(), MakeAnswerCName(), MakeAnswerNS(), MakeDnsResponseWithAdditional(), MakeDnsResponseWithCNameWithInnerReference(), MakeDnsResponseWithCNameWithReferenceInAnswer(), MakeDnsResponseWithSecondAnswer(), MakeDnsResponseWithSecondCNameWithInnerReference(), MakeDnsResponseWithUncompressedHost(), and MakeQuestion().
     {
         std::vector<uint8_t> result;
         infra::Tokenizer tokenizer(hostname, '.');
         for (uint32_t i = 0; i != tokenizer.Size(); ++i)
             result = Concatenate({ result, std::vector<uint8_t>{ { static_cast<uint8_t>(tokenizer.Token(i).size()) } }, std::vector<uint8_t>(tokenizer.Token(i).begin(), tokenizer.Token(i).end()) });
         result.push_back(0);
         return result;
     }
ConvertDns() [2/2]
std::vector<uint8_t> DnsResolverTest::ConvertDns (services::IPv4Address address) inline
Definition at line 97 of file TestDnsResolver.cpp.
     {
         return std::vector<uint8_t>(address.begin(), address.end());
     }
DataReceived()
void DnsResolverTest::DataReceived (const std::vector< uint8_t > & response, services::UdpSocket from) inline
Definition at line 309 of file TestDnsResolver.cpp.
References datagramExchangeObserver, services::DatagramExchangeObserver::DataReceived(), and infra::inPlace.
     {
         infra::StdVectorInputStream::WithStorage stream(infra::inPlace, response);
         datagramExchangeObserver->DataReceived(stream.Reader(), from);
     }
ExpectAndRespondToRequestSendStream()
void DnsResolverTest::ExpectAndRespondToRequestSendStream (services::NameResolverResultMock & result, infra::BoundedConstString hostname, services::IPAddress dnsServer) inline
Definition at line 29 of file TestDnsResolver.cpp.
References datagramExchangeObserver, ExpectRequestSendStream(), services::DatagramExchangeObserver::SendStreamAvailable(), infra::Tokenizer::Size(), infra::BoundedStringBase< T >::size(), infra::Tokenizer::Token(), infra::UnOwnedSharedPtr(), and writer.
Referenced by GiveSendStream(), and LookupIsRetried().
     {
         ExpectRequestSendStream(result, hostname, dnsServer).WillOnce(testing::Invoke([this, &result, hostname](std::size_t sendSize, services::UdpSocket remote) {
             EXPECT_CALL(writer, Insert(infra::CheckByteRangeContents(std::vector<uint8_t>{ { 9, 9, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 } }), testing::_));
             infra::Tokenizer tokenizer(hostname, '.');
             for (uint32_t i = 0; i != tokenizer.Size(); ++i)
             {
                 EXPECT_CALL(writer, Insert(infra::CheckByteRangeContents(std::vector<uint8_t>{ { static_cast<uint8_t>(tokenizer.Token(i).size()) } }), testing::_));
                 EXPECT_CALL(writer, Insert(infra::CheckByteRangeContents(tokenizer.Token(i)), testing::_));
             }
             EXPECT_CALL(writer, Insert(infra::CheckByteRangeContents(std::vector<uint8_t>{ { 0 } }), testing::_));
             EXPECT_CALL(writer, Insert(infra::CheckByteRangeContents(std::vector<uint8_t>{ { 0, 1, 0, 1 } }), testing::_));
             datagramExchangeObserver->SendStreamAvailable(infra::UnOwnedSharedPtr(writer));
         }));
     }
ExpectRequestSendStream()
auto&& DnsResolverTest::ExpectRequestSendStream (services::NameResolverResultMock & result, infra::BoundedConstString hostname, services::IPAddress dnsServer) inline
Definition at line 23 of file TestDnsResolver.cpp.
References datagram, services::MakeUdpSocket(), and infra::BoundedStringBase< T >::size().
Referenced by ExpectAndRespondToRequestSendStream().
     {
         EXPECT_CALL(result, Hostname()).Times(testing::AnyNumber()).WillRepeatedly(testing::Return(hostname));
         return EXPECT_CALL(datagram, RequestSendStream(18 + hostname.size(), services::MakeUdpSocket(dnsServer, 53)));
     }
GiveSendStream()
void DnsResolverTest::GiveSendStream (services::NameResolverResultMock & result, infra::BoundedConstString hostname, services::IPAddress dnsServer) inline
Definition at line 52 of file TestDnsResolver.cpp.
References services::both, currentHostname, datagram, datagramExchangeObserver, datagramFactory, ExpectAndRespondToRequestSendStream(), and infra::UnOwnedSharedPtr().
Referenced by LookupAndGiveSendStream().
     {
         currentHostname = hostname;
         EXPECT_CALL(datagramFactory, Listen(testing::_, services::IPVersions::both)).WillOnce(testing::Invoke([this](services::DatagramExchangeObserver& observer, services::IPVersions versions)
         {
             datagramExchangeObserver = &observer;
             return infra::UnOwnedSharedPtr(datagram);
         }));
         ExpectAndRespondToRequestSendStream(result, hostname, dnsServer);
     }
Lookup()
void DnsResolverTest::Lookup (services::NameResolverResultMock & result) inline
Definition at line 47 of file TestDnsResolver.cpp.
References services::DnsResolver::Lookup(), and resolver.
Referenced by LookupAndGiveSendStream().
     {
         resolver.Lookup(result);
     }
LookupAndGiveSendStream()
void DnsResolverTest::LookupAndGiveSendStream (services::NameResolverResultMock & result, infra::BoundedConstString hostname, services::IPAddress dnsServer) inline
Definition at line 63 of file TestDnsResolver.cpp.
References GiveSendStream(), and Lookup().
     {
         GiveSendStream(result, hostname, dnsServer);
         Lookup(result);
     }
LookupIsRetried()
void DnsResolverTest::LookupIsRetried (services::NameResolverResultMock & result, infra::BoundedConstString hostname, services::IPAddress dnsServer) inline
Definition at line 69 of file TestDnsResolver.cpp.
References currentHostname, ExpectAndRespondToRequestSendStream(), and infra::ClockFixture::ForwardTime().
     {
         ExpectAndRespondToRequestSendStream(result, currentHostname, dnsServer);
         ForwardTime(std::chrono::seconds(5));
     }
MakeAnswerA()
std::vector<uint8_t> DnsResolverTest::MakeAnswerA (const std::vector< uint8_t > & name, services::IPv4Address answer) inline
Definition at line 113 of file TestDnsResolver.cpp.
References Concatenate(), and ConvertDns().
Referenced by MakeDnsResponseWithAdditional(), MakeDnsResponseWithUncompressedHost(), and MakeReferenceAnswerA().
     {
         std::vector<uint8_t> resourceInner{ { 0, 1, 0, 1, 0, 1, 0, 30, 0, 4 } };
         return Concatenate({ name, resourceInner, ConvertDns(answer) });
     }
MakeAnswerCName()
std::vector<uint8_t> DnsResolverTest::MakeAnswerCName (const std::vector< uint8_t > & name, infra::BoundedConstString answer) inline
Definition at line 119 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), and infra::BoundedStringBase< T >::size().
Referenced by MakeDnsResponseWithCNameWithInnerReference(), MakeDnsResponseWithSecondCNameWithInnerReference(), and MakeReferenceAnswerCName().
     {
         std::vector<uint8_t> resourceInner{ { 0, 5, 0, 1, 0, 1, 0, 30, 0, static_cast<uint8_t>(answer.size() + 2) } };
         return Concatenate({ name, resourceInner, ConvertDns(answer) });
     }
MakeAnswerNS()
std::vector<uint8_t> DnsResolverTest::MakeAnswerNS (const std::vector< uint8_t > & name, infra::BoundedConstString answer) inline
Definition at line 125 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), and infra::BoundedStringBase< T >::size().
Referenced by MakeReferenceAnswerNS().
     {
         std::vector<uint8_t> resourceInner{ { 0, 2, 0, 1, 0, 1, 0, 30, 0, static_cast<uint8_t>(answer.size() + 2) } };
         return Concatenate({ name, resourceInner, ConvertDns(answer) });
     }
MakeDnsQuestion()
std::vector<uint8_t> DnsResolverTest::MakeDnsQuestion (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 234 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[2] = 0;
         return result;
     }
MakeDnsResponse()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponse (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 149 of file TestDnsResolver.cpp.
References Concatenate(), MakeHeader(), MakeQuestion(), and MakeReferenceAnswerA().
Referenced by MakeDnsQuestion(), MakeDnsResponseWithClass2(), MakeDnsResponseWithDifferentClass(), MakeDnsResponseWithDifferentId(), MakeDnsResponseWithDifferentType(), MakeDnsResponseWithError(), MakeDnsResponseWithIncorrectReference(), MakeDnsResponseWithSecondQuestion(), MakeDnsResponseWithType2(), and MakeShortenedDnsResponse().
     {
         return Concatenate({ MakeHeader(1), MakeQuestion(hostname), MakeReferenceAnswerA(address) });
     }
MakeDnsResponseWithAdditional()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithAdditional (infra::BoundedConstString hostname, infra::BoundedConstString ns, services::IPv4Address address) inline
Definition at line 222 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), MakeAnswerA(), MakeHeader(), and MakeQuestion().
     {
         return Concatenate({ MakeHeader(0, 0, 1), MakeQuestion(hostname), MakeAnswerA(ConvertDns(ns), address) });
     }
MakeDnsResponseWithClass2()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithClass2 (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 283 of file TestDnsResolver.cpp.
References MakeDnsResponse().
Referenced by MakeDnsResponseWithSecondAnswer().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[35] = 2;
         return result;
     }
MakeDnsResponseWithCName()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithCName (infra::BoundedConstString hostname, infra::BoundedConstString alias) inline
Definition at line 159 of file TestDnsResolver.cpp.
References Concatenate(), MakeHeader(), MakeQuestion(), and MakeReferenceAnswerCName().
     {
         return Concatenate({ MakeHeader(1), MakeQuestion(hostname), MakeReferenceAnswerCName(alias) });
     }
MakeDnsResponseWithCNameAndAnswer()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithCNameAndAnswer (infra::BoundedConstString hostname, infra::BoundedConstString alias, services::IPv4Address address) inline
Definition at line 164 of file TestDnsResolver.cpp.
References Concatenate(), MakeHeader(), MakeQuestion(), MakeReferenceAnswerA(), and MakeReferenceAnswerCName().
Referenced by MakeDnsResponseWithCNameAndAnswerForDifferentHost().
     {
         return Concatenate({ MakeHeader(2), MakeQuestion(hostname), MakeReferenceAnswerCName(alias), MakeReferenceAnswerA(address, 42) });
     }
MakeDnsResponseWithCNameAndAnswerForDifferentHost()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithCNameAndAnswerForDifferentHost (infra::BoundedConstString hostname, infra::BoundedConstString alias, services::IPv4Address address) inline
Definition at line 169 of file TestDnsResolver.cpp.
References MakeDnsResponseWithCNameAndAnswer().
     {
         auto result = MakeDnsResponseWithCNameAndAnswer(hostname, alias, address);
         result[54] = 0x0c;
         return result;
     }
MakeDnsResponseWithCNameWithInnerReference()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithCNameWithInnerReference (infra::BoundedConstString hostname, infra::BoundedConstString alias) inline
Definition at line 178 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), infra::BoundedStringBase< T >::find(), MakeAnswerCName(), MakeHeader(), MakeQuestion(), and infra::BoundedStringBase< T >::substr().
     {
         std::vector<uint8_t>  nameStart(ConvertDns(hostname.substr(0, hostname.find('.'))));
         nameStart.pop_back();
         std::vector<uint8_t> nameWithInnerReference(Concatenate({ nameStart, { 0xc0, 21 } }));
         return Concatenate({ MakeHeader(1), MakeQuestion(hostname), MakeAnswerCName(nameWithInnerReference, alias) });
     }
MakeDnsResponseWithCNameWithReferenceInAnswer()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithCNameWithReferenceInAnswer (infra::BoundedConstString hostname, infra::BoundedConstString alias) inline
Definition at line 194 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), MakeHeader(), MakeQuestion(), infra::BoundedStringBase< T >::rfind(), and infra::BoundedStringBase< T >::size().
     {
         std::vector<uint8_t> header(MakeHeader(1));
         std::vector<uint8_t> question(MakeQuestion(hostname));
         std::vector<uint8_t> nameReference{ { 0xc0, 0x0c } };
         std::vector<uint8_t> resourceInner{ { 0, 5, 0, 1, 0, 1, 0, 30, 0, static_cast<uint8_t>(alias.size() + 2) } };
         resourceInner.back() -= static_cast<uint8_t>(alias.size() - alias.rfind('.') - 1);
         std::vector<uint8_t> aliasData(ConvertDns(alias));
         aliasData.erase(aliasData.begin() + alias.rfind('.') + 1, aliasData.end());
         aliasData.push_back(0xc0);
         aliasData.push_back(static_cast<uint8_t>(13 + hostname.rfind('.')));
         return Concatenate({ header, question, nameReference, resourceInner, aliasData });
     }
MakeDnsResponseWithDifferentClass()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithDifferentClass (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 262 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[29] = 5;
         return result;
     }
MakeDnsResponseWithDifferentId()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithDifferentId (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 248 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[0] = 5;
         return result;
     }
MakeDnsResponseWithDifferentType()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithDifferentType (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 255 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[27] = 5;
         return result;
     }
MakeDnsResponseWithError()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithError (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 269 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[3] = 1;
         return result;
     }
MakeDnsResponseWithIncorrectReference()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithIncorrectReference (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 290 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[17] = 2;
         return result;
     }
MakeDnsResponseWithNS()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithNS (infra::BoundedConstString hostname, infra::BoundedConstString ns, services::IPv4Address address) inline
Definition at line 210 of file TestDnsResolver.cpp.
References Concatenate(), MakeHeader(), MakeQuestion(), MakeReferenceAnswerA(), and MakeReferenceAnswerNS().
Referenced by MakeDnsResponseWithNSTooShort().
     {
         return Concatenate({ MakeHeader(0, 1, 1), MakeQuestion(hostname), MakeReferenceAnswerNS(ns), MakeReferenceAnswerA(address, 42) });
     }
MakeDnsResponseWithNSTooShort()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithNSTooShort (infra::BoundedConstString hostname, infra::BoundedConstString ns, services::IPv4Address address) inline
Definition at line 215 of file TestDnsResolver.cpp.
References MakeDnsResponseWithNS().
     {
         auto result = MakeDnsResponseWithNS(hostname, ns, address);
         result.pop_back();
         return result;
     }
MakeDnsResponseWithSecondAnswer()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithSecondAnswer (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 297 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), and MakeDnsResponseWithClass2().
     {
         auto result = MakeDnsResponseWithClass2(hostname, address);
         result[7] = 2;  // 2 answers
         std::vector<uint8_t> nameReference{ { 0xc0, 0x0c } };
         std::vector<uint8_t> resourceInner{ { 0, 1, 0, 1, 0, 1, 0, 30, 0, 4 } };
         return Concatenate({ result, nameReference, resourceInner, ConvertDns(address) });
     }
MakeDnsResponseWithSecondCNameWithInnerReference()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithSecondCNameWithInnerReference (infra::BoundedConstString hostname, infra::BoundedConstString alias) inline
Definition at line 186 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), MakeAnswerCName(), MakeHeader(), MakeQuestion(), and MakeReferenceAnswerCName().
     {
         std::vector<uint8_t>  nameStart(ConvertDns("other"));
         nameStart.pop_back();
         std::vector<uint8_t> nameWithInnerReference(Concatenate({ nameStart, { 0xc0, 21 } }));
         return Concatenate({ MakeHeader(2), MakeQuestion(hostname), MakeAnswerCName(nameWithInnerReference, alias), MakeReferenceAnswerCName(alias) });
     }
MakeDnsResponseWithSecondQuestion()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithSecondQuestion (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 241 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[5] = 2;
         return result;
     }
MakeDnsResponseWithType2()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithType2 (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 276 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result[33] = 2;
         return result;
     }
MakeDnsResponseWithUncompressedHost()
std::vector<uint8_t> DnsResolverTest::MakeDnsResponseWithUncompressedHost (infra::BoundedConstString hostname, services::IPv4Address address) inline
Definition at line 154 of file TestDnsResolver.cpp.
References Concatenate(), ConvertDns(), MakeAnswerA(), MakeHeader(), and MakeQuestion().
     {
         return Concatenate({ MakeHeader(1), MakeQuestion(hostname), MakeAnswerA(ConvertDns(hostname), address) });
     }
MakeHeader()
std::vector<uint8_t> DnsResolverTest::MakeHeader (uint8_t answers, uint8_t authorativeNameServers = 0, uint8_t additionRecords = 0) inline
Definition at line 102 of file TestDnsResolver.cpp.
Referenced by MakeDnsResponse(), MakeDnsResponseWithAdditional(), MakeDnsResponseWithCName(), MakeDnsResponseWithCNameAndAnswer(), MakeDnsResponseWithCNameWithInnerReference(), MakeDnsResponseWithCNameWithReferenceInAnswer(), MakeDnsResponseWithNS(), MakeDnsResponseWithSecondCNameWithInnerReference(), and MakeDnsResponseWithUncompressedHost().
     {
         return std::vector<uint8_t>{ { 9, 9, 0x80, 0, 0, 1, 0, answers, 0, authorativeNameServers, 0, additionRecords } };
     }
MakeQuestion()
std::vector<uint8_t> DnsResolverTest::MakeQuestion (infra::BoundedConstString hostname) inline
Definition at line 107 of file TestDnsResolver.cpp.
References Concatenate(), and ConvertDns().
Referenced by MakeDnsResponse(), MakeDnsResponseWithAdditional(), MakeDnsResponseWithCName(), MakeDnsResponseWithCNameAndAnswer(), MakeDnsResponseWithCNameWithInnerReference(), MakeDnsResponseWithCNameWithReferenceInAnswer(), MakeDnsResponseWithNS(), MakeDnsResponseWithSecondCNameWithInnerReference(), and MakeDnsResponseWithUncompressedHost().
     {
         std::vector<uint8_t> footer{ { 0, 1, 0, 1 } };
         return Concatenate({ ConvertDns(hostname), footer });
     }
MakeReferenceAnswerA()
std::vector<uint8_t> DnsResolverTest::MakeReferenceAnswerA (services::IPv4Address address, uint8_t start = 0x0c) inline
Definition at line 131 of file TestDnsResolver.cpp.
References MakeAnswerA().
Referenced by MakeDnsResponse(), MakeDnsResponseWithCNameAndAnswer(), and MakeDnsResponseWithNS().
     {
         std::vector<uint8_t> nameReference{ { 0xc0, start } };
         return MakeAnswerA(nameReference, address);
     }
MakeReferenceAnswerCName()
std::vector<uint8_t> DnsResolverTest::MakeReferenceAnswerCName (infra::BoundedConstString answer, uint8_t start = 0x0c) inline
Definition at line 137 of file TestDnsResolver.cpp.
References MakeAnswerCName().
Referenced by MakeDnsResponseWithCName(), MakeDnsResponseWithCNameAndAnswer(), and MakeDnsResponseWithSecondCNameWithInnerReference().
     {
         std::vector<uint8_t> nameReference{ { 0xc0, start } };
         return MakeAnswerCName(nameReference, answer);
     }
MakeReferenceAnswerNS()
std::vector<uint8_t> DnsResolverTest::MakeReferenceAnswerNS (infra::BoundedConstString answer, uint8_t start = 0x0c) inline
Definition at line 143 of file TestDnsResolver.cpp.
References MakeAnswerNS().
Referenced by MakeDnsResponseWithNS().
     {
         std::vector<uint8_t> nameReference{ { 0xc0, start } };
         return MakeAnswerNS(nameReference, answer);
     }
MakeShortenedDnsResponse()
std::vector<uint8_t> DnsResolverTest::MakeShortenedDnsResponse (infra::BoundedConstString hostname, services::IPv4Address address, uint32_t amountToShort) inline
Definition at line 227 of file TestDnsResolver.cpp.
References MakeDnsResponse().
     {
         auto result = MakeDnsResponse(hostname, address);
         result.erase(result.end() - amountToShort, result.end());
         return result;
     }
Member Data Documentation
currentHostname
infra::BoundedConstString DnsResolverTest::currentHostname
Definition at line 329 of file TestDnsResolver.cpp.
Referenced by GiveSendStream(), and LookupIsRetried().
datagram
testing::StrictMock<services::DatagramExchangeMock> DnsResolverTest::datagram
Definition at line 326 of file TestDnsResolver.cpp.
Referenced by ExpectRequestSendStream(), and GiveSendStream().
datagramExchangeObserver
services::DatagramExchangeObserver* DnsResolverTest::datagramExchangeObserver = nullptr
Definition at line 327 of file TestDnsResolver.cpp.
Referenced by DataReceived(), ExpectAndRespondToRequestSendStream(), and GiveSendStream().
datagramFactory
testing::StrictMock<services::DatagramFactoryMock> DnsResolverTest::datagramFactory
Definition at line 320 of file TestDnsResolver.cpp.
Referenced by GiveSendStream().
dnsServer1
const services::IPv4Address DnsResolverTest::dnsServer1 { 1, 2, 3, 4 }
Definition at line 315 of file TestDnsResolver.cpp.
dnsServer2
const services::IPv4Address DnsResolverTest::dnsServer2 { 2, 3, 4, 5 }
Definition at line 316 of file TestDnsResolver.cpp.
dnsServers
const std::array<services::IPAddress, 2> DnsResolverTest::dnsServers { dnsServer1, dnsServer2 }
Definition at line 321 of file TestDnsResolver.cpp.
expiration
infra::TimePoint DnsResolverTest::expiration = infra::Now() + std::chrono::seconds(0x10000) + std::chrono::seconds(30)
Definition at line 330 of file TestDnsResolver.cpp.
hostAddress1
const services::IPv4Address DnsResolverTest::hostAddress1 { 3, 4, 5, 6 }
Definition at line 317 of file TestDnsResolver.cpp.
nsServer1
const services::IPv4Address DnsResolverTest::nsServer1 { 4, 5, 6, 7 }
Definition at line 318 of file TestDnsResolver.cpp.
randomDataGenerator
testing::StrictMock<hal::SynchronousRandomDataGeneratorMock> DnsResolverTest::randomDataGenerator
Definition at line 322 of file TestDnsResolver.cpp.
Referenced by DnsResolverTest().
resolver
services::DnsResolver DnsResolverTest::resolver { datagramFactory, { dnsServers }, randomDataGenerator }
Definition at line 323 of file TestDnsResolver.cpp.
Referenced by Lookup().
result1
testing::StrictMock<services::NameResolverResultMock> DnsResolverTest::result1
Definition at line 324 of file TestDnsResolver.cpp.
result2
testing::StrictMock<services::NameResolverResultMock> DnsResolverTest::result2
Definition at line 325 of file TestDnsResolver.cpp.
writer
testing::StrictMock<infra::StreamWriterMock> DnsResolverTest::writer
Definition at line 328 of file TestDnsResolver.cpp.
Referenced by ExpectAndRespondToRequestSendStream().
The documentation for this class was generated from the following file:
TestDnsResolver.cpp