EMil: infra::StringOutputStreamWriter Class Reference
infra::StringOutputStreamWriter Class Reference
#include <StringOutputStream.hpp>
Public Member Functions
StringOutputStreamWriter (BoundedString &string)
template<class T >
ReservedProxy< T > Reserve (StreamErrorPolicy &errorPolicy)
Private Member Functions
virtual void Insert (ConstByteRange range, StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
virtual std::size_t ConstructSaveMarker () const override
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const override
virtual infra::ByteRange SaveState (std::size_t marker) override
virtual void RestoreState (infra::ByteRange range) override
virtual infra::ByteRange Overwrite (std::size_t marker) override
Private Attributes
BoundedString & string
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 11 of file StringOutputStream.hpp.
Constructor & Destructor Documentation
StringOutputStreamWriter()
infra::StringOutputStreamWriter::StringOutputStreamWriter (BoundedString & string) explicit
Definition at line 5 of file StringOutputStream.cpp.
         : string(string)
     {}
Member Function Documentation
Available()
std::size_t infra::StringOutputStreamWriter::Available () const override private virtual
Implements infra::StreamWriter.
Definition at line 19 of file StringOutputStream.cpp.
Referenced by Insert().
     {
         return string.max_size() - string.size();
     }
ConstructSaveMarker()
std::size_t infra::StringOutputStreamWriter::ConstructSaveMarker () const override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 24 of file StringOutputStream.cpp.
     {
         return string.size();
     }
GetProcessedBytesSince()
std::size_t infra::StringOutputStreamWriter::GetProcessedBytesSince (std::size_t marker) const override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 29 of file StringOutputStream.cpp.
     {
         return string.size() - marker;
     }
Insert()
void infra::StringOutputStreamWriter::Insert (ConstByteRange range, StreamErrorPolicy & errorPolicy) override private virtual
Implements infra::StreamWriter.
Definition at line 9 of file StringOutputStream.cpp.
References Available(), infra::MemoryRange< T >::begin(), infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         std::size_t spaceLeft = Available();
         bool spaceOk = range.size() <= spaceLeft;
         errorPolicy.ReportResult(spaceOk);
         if (!spaceOk)
             range.shrink_from_back_to(spaceLeft);
         string.append(reinterpret_cast<const char*>(range.begin()), range.size());
     }
Overwrite()
infra::ByteRange infra::StringOutputStreamWriter::Overwrite (std::size_t marker) override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 50 of file StringOutputStream.cpp.
References infra::DiscardHead(), infra::MakeRange(), and infra::ReinterpretCastByteRange().
     {
         return infra::DiscardHead(infra::ReinterpretCastByteRange(infra::MakeRange(string)), marker);
     }
Reserve()
template<class T > ReservedProxy< T > infra::StringOutputStreamWriter::Reserve (StreamErrorPolicy & errorPolicy)
Definition at line 49 of file StringOutputStream.hpp.
References infra::detail::end(), infra::ReinterpretCastByteRange(), infra::StreamErrorPolicy::ReportResult(), infra::MemoryRange< T >::shrink_from_back_to(), and infra::MemoryRange< T >::size().
     {
         ByteRange range(ReinterpretCastByteRange(MemoryRange<char>(string.end(), string.end() + sizeof(T))));
         std::size_t spaceLeft = string.max_size() - string.size();
         bool spaceOk = range.size() <= spaceLeft;
         errorPolicy.ReportResult(spaceOk);
         if (!spaceOk)
             range.shrink_from_back_to(spaceLeft);
         string.append(range.size(), 0);
         return ReservedProxy<T>(range);
     }
RestoreState()
void infra::StringOutputStreamWriter::RestoreState (infra::ByteRange range) override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 44 of file StringOutputStream.cpp.
References infra::MemoryRange< T >::begin(), infra::detail::end(), infra::MemoryRange< T >::end(), and infra::MemoryRange< T >::size().
     {
         std::copy(reinterpret_cast<char*>(range.end()), string.end(), reinterpret_cast<char*>(range.begin()));
         string.resize(string.size() - range.size());
     }
SaveState()
infra::ByteRange infra::StringOutputStreamWriter::SaveState (std::size_t marker) override private virtual
Reimplemented from infra::StreamWriter.
Definition at line 34 of file StringOutputStream.cpp.
References infra::MemoryRange< T >::begin(), and infra::detail::end().
     {
         char* copyBegin = string.begin() + marker;
         char* copyEnd = string.end();
         string.resize(string.max_size());
         std::copy_backward(copyBegin, copyEnd, string.end());
         return infra::ByteRange(reinterpret_cast<uint8_t*>(copyBegin), reinterpret_cast<uint8_t*>(string.end() - std::distance(copyBegin, copyEnd)));
     }
Member Data Documentation
string
BoundedString& infra::StringOutputStreamWriter::string private
Definition at line 31 of file StringOutputStream.hpp.
The documentation for this class was generated from the following files:
StringOutputStream.hpp
StringOutputStream.cpp