EMil: infra::StreamWriter Class Reference
infra::StreamWriter Class Reference abstract
#include <OutputStream.hpp>
Public Member Functions
virtual void Insert (ConstByteRange range, StreamErrorPolicy &errorPolicy)=0
virtual std::size_t Available () const =0
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Protected Member Functions
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 15 of file OutputStream.hpp.
Constructor & Destructor Documentation
StreamWriter() [1/2]
infra::StreamWriter::StreamWriter () protected default
StreamWriter() [2/2]
infra::StreamWriter::StreamWriter (const StreamWriter &) protected delete
~StreamWriter()
infra::StreamWriter::~StreamWriter () protected default
Member Function Documentation
Available()
virtual std::size_t infra::StreamWriter::Available () const pure virtual
Implemented in services::ConnectionMbedTls::StreamWriterMbedTls, infra::ByteOutputStreamWriter, infra::StreamWriterDummy, infra::StringOutputStreamWriter, infra::IoOutputStreamWriter, services::StreamWriterOnSerialCommunication, infra::StdStringOutputStreamWriter, infra::LimitedStreamWriter, services::StreamWriterOnSynchronousSerialCommunication, and infra::StreamWriterPrintF.
Referenced by infra::LimitedStreamWriter::Available(), infra::OutputStream::Available(), and services::HttpClientImpl::ForwardStream().
ConstructSaveMarker()
std::size_t infra::StreamWriter::ConstructSaveMarker () const virtual
Reimplemented in infra::ByteOutputStreamWriter, and infra::StringOutputStreamWriter.
Definition at line 7 of file OutputStream.cpp.
Referenced by infra::OutputStream::SaveMarker().
     {
         std::abort();
     }
GetProcessedBytesSince()
std::size_t infra::StreamWriter::GetProcessedBytesSince (std::size_t marker) const virtual
Reimplemented in infra::ByteOutputStreamWriter, and infra::StringOutputStreamWriter.
Definition at line 12 of file OutputStream.cpp.
Referenced by infra::OutputStream::ProcessedBytesSince().
     {
         std::abort();
     }
Insert()
virtual void infra::StreamWriter::Insert (ConstByteRange range, StreamErrorPolicy & errorPolicy) pure virtual
Implemented in services::ConnectionMbedTls::StreamWriterMbedTls, infra::ByteOutputStreamWriter, infra::StreamWriterDummy, infra::StringOutputStreamWriter, infra::IoOutputStreamWriter, services::StreamWriterOnSerialCommunication, infra::StdStringOutputStreamWriter, infra::LimitedStreamWriter, services::StreamWriterOnSynchronousSerialCommunication, and infra::StreamWriterPrintF.
Referenced by infra::TextOutputStream::FormatArgs(), infra::LimitedStreamWriter::Insert(), infra::DataOutputStream::operator<<(), infra::TextOutputStream::operator<<(), infra::TextOutputStream::OutputAsBinary(), infra::TextOutputStream::OutputAsDecimal(), infra::TextOutputStream::OutputAsHexadecimal(), and infra::TextOutputStream::OutputOptionalPadding().
operator=()
StreamWriter& infra::StreamWriter::operator= (const StreamWriter &) protected delete
Overwrite()
ByteRange infra::StreamWriter::Overwrite (std::size_t marker) virtual
Reimplemented in infra::ByteOutputStreamWriter, and infra::StringOutputStreamWriter.
Definition at line 27 of file OutputStream.cpp.
     {
         std::abort();
     }
RestoreState()
void infra::StreamWriter::RestoreState (infra::ByteRange range) virtual
Reimplemented in infra::ByteOutputStreamWriter, and infra::StringOutputStreamWriter.
Definition at line 22 of file OutputStream.cpp.
Referenced by infra::SavedMarkerStreamWriter::~SavedMarkerStreamWriter().
     {
         std::abort();
     }
SaveState()
ByteRange infra::StreamWriter::SaveState (std::size_t marker) virtual
Reimplemented in infra::ByteOutputStreamWriter, and infra::StringOutputStreamWriter.
Definition at line 17 of file OutputStream.cpp.
     {
         std::abort();
     }
The documentation for this class was generated from the following files:
OutputStream.hpp
OutputStream.cpp