EMil: MqttClientTest Class Reference
MqttClientTest Class Reference
Public Member Functions
MqttClientTest ()
void Connect ()
Public Member Functions inherited from infra::ClockFixture
ClockFixture (uint32_t timerSericeId=systemTimerServiceId)
ClockFixture (const ClockFixture &)=delete
ClockFixture & operator= (const ClockFixture &)=delete
~ClockFixture ()
void ForwardTime (Duration time)
TimeMatcherHelper After (infra::Duration duration) const
Public Attributes
testing::StrictMock< services::ConnectionFactoryMock > connectionFactory
testing::StrictMock< services::MqttClientObserverFactoryMock > factory
services::MqttClientConnectorImpl connector
testing::StrictMock< services::ConnectionStub > connection
infra::SharedPtr< services::Connection > connectionPtr
testing::StrictMock< services::MqttClientObserverMock > client
infra::SharedPtr< services::MqttClientObserver > clientPtr
Public Attributes inherited from infra::ClockFixture
PerfectTimerService systemTimerService
Additional Inherited Members
Static Public Member Functions inherited from infra::ClockFixture
static std::string TimeToString (TimePoint time)
Detailed Description
Definition at line 9 of file TestMqttClient.cpp.
Constructor & Destructor Documentation
MqttClientTest()
MqttClientTest::MqttClientTest () inline
Definition at line 14 of file TestMqttClient.cpp.
         : connector("clientId", "username", "password", services::IPv4Address{ 127, 0, 0, 1 }, 1234, connectionFactory)
         , connectionPtr(infra::UnOwnedSharedPtr(connection))
         , clientPtr(infra::UnOwnedSharedPtr(client))
     {
         EXPECT_CALL(connectionFactory, Connect(testing::Ref(connector)));
         connector.Connect(factory);
     }
Member Function Documentation
Connect()
void MqttClientTest::Connect () inline
Definition at line 23 of file TestMqttClient.cpp.
References infra::SingleObserver< Descendant, SubjectType_ >::Attach(), client, clientPtr, services::ConnectionObserver::Connected(), connection, services::MqttClientConnectorImpl::ConnectionEstablished(), connector, factory, and infra::Lambda().
     {
         connector.ConnectionEstablished([this](infra::SharedPtr<services::ConnectionObserver> connectionObserver)
         {
             connectionObserver->Attach(connection);
             connection.SetOwnership(nullptr, connectionObserver);
             connectionObserver->Connected();
         });
         ExecuteAllActions();
         EXPECT_CALL(factory, ConnectionEstablished(testing::_)).WillOnce(infra::Lambda([this](infra::AutoResetFunction<void(infra::SharedPtr<services::MqttClientObserver> client)>& createdClient)
         {
             EXPECT_CALL(client, Connected());
             createdClient(clientPtr);
         }));
         connection.SimulateDataReceived(std::vector<uint8_t>{ 0x20, 0x00, 0x00, 0x00 });
         ExecuteAllActions();
         connection.sentData.clear();
     }
Member Data Documentation
client
testing::StrictMock<services::MqttClientObserverMock> MqttClientTest::client
Definition at line 50 of file TestMqttClient.cpp.
Referenced by Connect().
clientPtr
infra::SharedPtr<services::MqttClientObserver> MqttClientTest::clientPtr
Definition at line 51 of file TestMqttClient.cpp.
Referenced by Connect().
connection
testing::StrictMock<services::ConnectionStub> MqttClientTest::connection
Definition at line 48 of file TestMqttClient.cpp.
Referenced by Connect().
connectionFactory
testing::StrictMock<services::ConnectionFactoryMock> MqttClientTest::connectionFactory
Definition at line 45 of file TestMqttClient.cpp.
connectionPtr
infra::SharedPtr<services::Connection> MqttClientTest::connectionPtr
Definition at line 49 of file TestMqttClient.cpp.
connector
services::MqttClientConnectorImpl MqttClientTest::connector
Definition at line 47 of file TestMqttClient.cpp.
Referenced by Connect().
factory
testing::StrictMock<services::MqttClientObserverFactoryMock> MqttClientTest::factory
Definition at line 46 of file TestMqttClient.cpp.
Referenced by Connect().
The documentation for this class was generated from the following file:
TestMqttClient.cpp