EMil: infra::TimerRepeating Class Reference
infra::TimerRepeating Class Reference
#include <Timer.hpp>
Public Member Functions
TimerRepeating (uint32_t timerServiceId=systemTimerServiceId)
TimerRepeating (Duration duration, const infra::Function< void()> &action, uint32_t timerServiceId=systemTimerServiceId)
TimerRepeating (Duration duration, const infra::Function< void()> &action, TriggerImmediately, uint32_t timerServiceId=systemTimerServiceId)
void Start (Duration duration, const infra::Function< void()> &action)
void Start (Duration duration, const infra::Function< void()> &action, TriggerImmediately)
Public Member Functions inherited from infra::Timer
void Cancel ()
bool Armed () const
TimePoint NextTrigger () const
virtual const infra::Function< void()> & Action () const
Public Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
bool operator== (const IntrusiveForwardListNode< T > &other) const
bool operator!= (const IntrusiveForwardListNode< T > &other) const
Protected Member Functions
virtual void ComputeNextTriggerTime () override
Protected Member Functions inherited from infra::Timer
Timer (uint32_t timerServiceId)
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
~Timer ()
TimePoint Now () const
Duration Resolution () const
void SetNextTriggerTime (TimePoint time, const infra::Function< void()> &action)
Protected Member Functions inherited from infra::detail::IntrusiveForwardListNode< T >
IntrusiveForwardListNode ()
IntrusiveForwardListNode (const IntrusiveForwardListNode &other)
IntrusiveForwardListNode & operator= (const IntrusiveForwardListNode &other)
~IntrusiveForwardListNode ()=default
Private Member Functions
void SetDuration (Duration duration)
Private Attributes
Duration triggerPeriod = Duration()
Detailed Description
Definition at line 88 of file Timer.hpp.
Constructor & Destructor Documentation
TimerRepeating() [1/3]
infra::TimerRepeating::TimerRepeating (uint32_t timerServiceId = systemTimerServiceId) explicit
Definition at line 124 of file Timer.cpp.
         : Timer(timerServiceId)
     {}
TimerRepeating() [2/3]
infra::TimerRepeating::TimerRepeating (Duration duration, const infra::Function< void()> & action, uint32_t timerServiceId = systemTimerServiceId)
Definition at line 128 of file Timer.cpp.
References Start().
         : Timer(timerServiceId)
     {
         Start(duration, aAction);
     }
TimerRepeating() [3/3]
infra::TimerRepeating::TimerRepeating (Duration duration, const infra::Function< void()> & action, TriggerImmediately , uint32_t timerServiceId = systemTimerServiceId)
Definition at line 134 of file Timer.cpp.
References Start(), and infra::triggerImmediately.
         : Timer(timerServiceId)
     {
         Start(duration, aAction, triggerImmediately);
     }
Member Function Documentation
ComputeNextTriggerTime()
void infra::TimerRepeating::ComputeNextTriggerTime () override protected virtual
Implements infra::Timer.
Definition at line 152 of file Timer.cpp.
References infra::Timer::Action(), infra::Timer::NextTrigger(), infra::Timer::Now(), infra::Timer::SetNextTriggerTime(), and triggerPeriod.
Referenced by SetDuration().
     {
         TimePoint now = std::max(Now(), NextTrigger());
         Duration diff = (now - NextTrigger()) % triggerPeriod;
         SetNextTriggerTime(now - diff + triggerPeriod, Action());
     }
SetDuration()
void infra::TimerRepeating::SetDuration (Duration duration) private
Definition at line 160 of file Timer.cpp.
References ComputeNextTriggerTime(), and triggerPeriod.
Referenced by Start().
     {
         triggerPeriod = duration;
         ComputeNextTriggerTime();
     }
Start() [1/2]
void infra::TimerRepeating::Start (Duration duration, const infra::Function< void()> & action)
Definition at line 140 of file Timer.cpp.
References infra::Timer::action, infra::Timer::Now(), infra::Timer::Resolution(), SetDuration(), and infra::Timer::SetNextTriggerTime().
Referenced by Start(), and TimerRepeating().
     {
         SetNextTriggerTime(Now() + Resolution(), action);  // Initialize NextTrigger() for ComputeNextTriggerTime
         SetDuration(duration);
     }
Start() [2/2]
void infra::TimerRepeating::Start (Duration duration, const infra::Function< void()> & action, TriggerImmediately)
Definition at line 146 of file Timer.cpp.
References infra::Timer::action, and Start().
     {
         Start(duration, action);
         action();
     }
Member Data Documentation
triggerPeriod
Duration infra::TimerRepeating::triggerPeriod = Duration() private
Definition at line 106 of file Timer.hpp.
Referenced by ComputeNextTriggerTime(), and SetDuration().
The documentation for this class was generated from the following files:
Timer.hpp
Timer.cpp