EMil: infra::StreamWriterPrintF Class Reference
infra::StreamWriterPrintF Class Reference
#include <StreamWriterPrintF.hpp>
Public Member Functions
virtual void Insert (ConstByteRange range, StreamErrorPolicy &errorPolicy) override
virtual std::size_t Available () const override
Public Member Functions inherited from infra::StreamWriter
virtual std::size_t ConstructSaveMarker () const
virtual std::size_t GetProcessedBytesSince (std::size_t marker) const
virtual infra::ByteRange SaveState (std::size_t marker)
virtual void RestoreState (infra::ByteRange range)
virtual infra::ByteRange Overwrite (std::size_t marker)
Additional Inherited Members
Protected Member Functions inherited from infra::StreamWriter
StreamWriter ()=default
StreamWriter (const StreamWriter &)=delete
StreamWriter & operator= (const StreamWriter &)=delete
~StreamWriter ()=default
Detailed Description
Definition at line 8 of file StreamWriterPrintF.hpp.
Member Function Documentation
Available()
std::size_t infra::StreamWriterPrintF::Available () const override virtual
Implements infra::StreamWriter.
Definition at line 22 of file StreamWriterPrintF.cpp.
     {
         return std::numeric_limits<size_t>::max();
     }
Insert()
void infra::StreamWriterPrintF::Insert (ConstByteRange range, StreamErrorPolicy & errorPolicy) override virtual
Implements infra::StreamWriter.
Definition at line 6 of file StreamWriterPrintF.cpp.
References infra::Copy(), infra::MemoryRange< T >::empty(), infra::Head(), infra::MemoryRange< T >::pop_front(), and infra::MemoryRange< T >::size().
     {
         std::array<uint8_t, 128> printBuffer;
         while (!range.empty())
         {
             auto from = infra::Head(range, printBuffer.size() - 1);
             auto to = infra::Head(infra::ByteRange(printBuffer), from.size());
             infra::Copy(from, to);
             range.pop_front(from.size());
             printBuffer[to.size()] = 0;
             printf("%s", printBuffer.data());
         }
     }
The documentation for this class was generated from the following files:
StreamWriterPrintF.hpp
StreamWriterPrintF.cpp