EMil: TestCyclicBuffer.cpp File Reference
TestCyclicBuffer.cpp File Reference
Classes
class CyclicBufferTest
Functions
TEST_F (CyclicBufferTest, CreateEmpty)
TEST_F (CyclicBufferTest, PushOne)
TEST_F (CyclicBufferTest, PushRange)
TEST_F (CyclicBufferTest, PushEmptyRange)
TEST_F (CyclicBufferTest, PushFull)
TEST_F (CyclicBufferTest, Pop)
TEST_F (CyclicBufferTest, PopNothing)
TEST_F (CyclicBufferTest, PushBeyondEnd)
TEST_F (CyclicBufferTest, PushFullBeyondEnd)
TEST_F (CyclicBufferTest, PopUntilEnd)
TEST_F (CyclicBufferTest, PopBeyondEnd)
Function Documentation
TEST_F() [1/11]
TEST_F (CyclicBufferTest , CreateEmpty)
Definition at line 11 of file TestCyclicBuffer.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     EXPECT_TRUE(buffer.Empty());
     EXPECT_FALSE(buffer.Full());
     EXPECT_EQ(0, buffer.Size());
     EXPECT_EQ(4, buffer.Available());
 }
TEST_F() [2/11]
TEST_F (CyclicBufferTest , PushOne)
Definition at line 19 of file TestCyclicBuffer.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     buffer.Push(5);
     EXPECT_FALSE(buffer.Empty());
     EXPECT_FALSE(buffer.Full());
     EXPECT_EQ(1, buffer.Size());
     EXPECT_EQ(3, buffer.Available());
     EXPECT_EQ(std::vector<uint8_t>{ 5 }, buffer.ContiguousRange());
 }
TEST_F() [3/11]
TEST_F (CyclicBufferTest , PushRange)
Definition at line 29 of file TestCyclicBuffer.cpp.
References EXPECT_EQ(), and EXPECT_FALSE().
 {
     buffer.Push(std::vector<uint8_t>{ 3, 7 });
     EXPECT_FALSE(buffer.Empty());
     EXPECT_FALSE(buffer.Full());
     EXPECT_EQ((std::vector<uint8_t>{ 3, 7 }), buffer.ContiguousRange());
 }
TEST_F() [4/11]
TEST_F (CyclicBufferTest , PushEmptyRange)
Definition at line 38 of file TestCyclicBuffer.cpp.
References EXPECT_EQ(), EXPECT_FALSE(), and EXPECT_TRUE().
 {
     buffer.Push(std::vector<uint8_t>{ });
     EXPECT_TRUE(buffer.Empty());
     EXPECT_FALSE(buffer.Full());
     EXPECT_EQ((std::vector<uint8_t>{ }), buffer.ContiguousRange());
 }
TEST_F() [5/11]
TEST_F (CyclicBufferTest , PushFull)
Definition at line 47 of file TestCyclicBuffer.cpp.
References EXPECT_EQ(), and EXPECT_TRUE().
 {
     buffer.Push(std::vector<uint8_t>{ 2, 3, 7, 11 });
     EXPECT_TRUE(buffer.Full());
     EXPECT_EQ((std::vector<uint8_t>{ 2, 3, 7, 11 }), buffer.ContiguousRange());
     infra::CyclicBuffer<uint8_t>::WithStorage<4> buffer2;
     buffer2.Push(std::vector<uint8_t>{ 2, 3, 7 });
     buffer2.Push(11);
     EXPECT_TRUE(buffer2.Full());
     EXPECT_EQ((std::vector<uint8_t>{ 2, 3, 7, 11 }), buffer2.ContiguousRange());
 }
TEST_F() [6/11]
TEST_F (CyclicBufferTest , Pop)
Definition at line 62 of file TestCyclicBuffer.cpp.
References EXPECT_TRUE().
 {
     buffer.Push(5);
     buffer.Pop(1);
     EXPECT_TRUE(buffer.Empty());
 }
TEST_F() [7/11]
TEST_F (CyclicBufferTest , PopNothing)
Definition at line 70 of file TestCyclicBuffer.cpp.
References EXPECT_FALSE().
 {
     buffer.Push(5);
     buffer.Pop(0);
     EXPECT_FALSE(buffer.Empty());
 }
TEST_F() [8/11]
TEST_F (CyclicBufferTest , PushBeyondEnd)
Definition at line 78 of file TestCyclicBuffer.cpp.
References EXPECT_EQ().
 {
     buffer.Push(std::vector<uint8_t>{ 3, 7, 9 });
     buffer.Pop(2);
     buffer.Push(std::vector<uint8_t>{ 2, 3 });
     EXPECT_EQ((std::vector<uint8_t>{ 9, 2 }), buffer.ContiguousRange());
     EXPECT_EQ(3, buffer.Size());
     EXPECT_EQ(1, buffer.Available());
 }
TEST_F() [9/11]
TEST_F (CyclicBufferTest , PushFullBeyondEnd)
Definition at line 89 of file TestCyclicBuffer.cpp.
References EXPECT_EQ().
 {
     buffer.Push(std::vector<uint8_t>{ 3, 2 });
     buffer.Pop(1);
     buffer.Push(std::vector<uint8_t>{ 5, 7, 9 });
     EXPECT_EQ((std::vector<uint8_t>{ 2, 5, 7 }), buffer.ContiguousRange());
     EXPECT_EQ(4, buffer.Size());
     EXPECT_EQ(0, buffer.Available());
 }
TEST_F() [10/11]
TEST_F (CyclicBufferTest , PopUntilEnd)
Definition at line 100 of file TestCyclicBuffer.cpp.
References EXPECT_EQ().
 {
     buffer.Push(std::vector<uint8_t>{ 3, 5, 9 });
     buffer.Pop(2);
     buffer.Push(std::vector<uint8_t>{ 2, 3, 7 });
     buffer.Pop(2);
     EXPECT_EQ((std::vector<uint8_t>{ 3, 7 }), buffer.ContiguousRange());
 }
TEST_F() [11/11]
TEST_F (CyclicBufferTest , PopBeyondEnd)
Definition at line 110 of file TestCyclicBuffer.cpp.
References EXPECT_EQ().
 {
     buffer.Push(std::vector<uint8_t>{ 3, 5, 9 });
     buffer.Pop(2);
     buffer.Push(std::vector<uint8_t>{ 2, 3, 7 });
     buffer.Pop(3);
     EXPECT_EQ((std::vector<uint8_t>{ 7 }), buffer.ContiguousRange());
 }