EMil: IntrusiveBinarySearchTreeTest Class Reference
IntrusiveBinarySearchTreeTest Class Reference
Public Member Functions
~IntrusiveBinarySearchTreeTest ()
std::string Representation (const infra::IntrusiveBinarySearchTree< TestNode > &tree)
void AddRepresentation (const TestNode &node, std::ostream &os)
Public Attributes
TestNode node0 = 0
TestNode node1 = 1
TestNode node2 = 2
TestNode node3 = 3
TestNode node4 = 4
TestNode node5 = 5
infra::IntrusiveBinarySearchTree< TestNode > tree
Detailed Description
Definition at line 33 of file TestIntrusiveBinarySearchTree.cpp.
Constructor & Destructor Documentation
~IntrusiveBinarySearchTreeTest()
IntrusiveBinarySearchTreeTest::~IntrusiveBinarySearchTreeTest () inline
Definition at line 37 of file TestIntrusiveBinarySearchTree.cpp.
References EXPECT_TRUE(), infra::IntrusiveBinarySearchTree< T, Compare >::invariant_holds(), and tree.
     {
         EXPECT_TRUE(tree.invariant_holds());
     }
Member Function Documentation
AddRepresentation()
void IntrusiveBinarySearchTreeTest::AddRepresentation (const TestNode & node, std::ostream & os) inline
Definition at line 52 of file TestIntrusiveBinarySearchTree.cpp.
Referenced by Representation().
     {
         os << node.value;
         if (node.left || node.right)
         {
             os << "(";
             if (node.left)
                 AddRepresentation(*node.left, os);
             os << ",";
             if (node.right)
                 AddRepresentation(*node.right, os);
             os << ")";
         }
     }
Representation()
std::string IntrusiveBinarySearchTreeTest::Representation (const infra::IntrusiveBinarySearchTree< TestNode > & tree) inline
Definition at line 42 of file TestIntrusiveBinarySearchTree.cpp.
References AddRepresentation(), infra::IntrusiveBinarySearchTree< T, Compare >::empty(), infra::IntrusiveBinarySearchTree< T, Compare >::root(), and tree.
     {
         std::ostringstream os;
         if (!tree.empty())
             AddRepresentation(tree.root(), os);
         return os.str();
     }
Member Data Documentation
node0
TestNode IntrusiveBinarySearchTreeTest::node0 = 0
Definition at line 69 of file TestIntrusiveBinarySearchTree.cpp.
node1
TestNode IntrusiveBinarySearchTreeTest::node1 = 1
Definition at line 70 of file TestIntrusiveBinarySearchTree.cpp.
node2
TestNode IntrusiveBinarySearchTreeTest::node2 = 2
Definition at line 71 of file TestIntrusiveBinarySearchTree.cpp.
node3
TestNode IntrusiveBinarySearchTreeTest::node3 = 3
Definition at line 72 of file TestIntrusiveBinarySearchTree.cpp.
node4
TestNode IntrusiveBinarySearchTreeTest::node4 = 4
Definition at line 73 of file TestIntrusiveBinarySearchTree.cpp.
node5
TestNode IntrusiveBinarySearchTreeTest::node5 = 5
Definition at line 74 of file TestIntrusiveBinarySearchTree.cpp.
tree
infra::IntrusiveBinarySearchTree<TestNode> IntrusiveBinarySearchTreeTest::tree
Definition at line 76 of file TestIntrusiveBinarySearchTree.cpp.
Referenced by Representation(), and ~IntrusiveBinarySearchTreeTest().
The documentation for this class was generated from the following file:
TestIntrusiveBinarySearchTree.cpp