EMil: services::ConnectionLoopBackListener Class Reference
services::ConnectionLoopBackListener Class Reference
#include <ConnectionLoopBack.hpp>
Public Member Functions
ConnectionLoopBackListener (uint16_t port, ConnectionLoopBackFactory &loopBackFactory, ServerConnectionObserverFactory &connectionObserverFactory)
~ConnectionLoopBackListener ()
void Accept (ClientConnectionObserverFactory &clientObserverFactory)
Private Attributes
uint16_t port
ConnectionLoopBackFactory & loopBackFactory
ServerConnectionObserverFactory & connectionObserverFactory
Detailed Description
Definition at line 84 of file ConnectionLoopBack.hpp.
Constructor & Destructor Documentation
ConnectionLoopBackListener()
services::ConnectionLoopBackListener::ConnectionLoopBackListener (uint16_t port, ConnectionLoopBackFactory & loopBackFactory, ServerConnectionObserverFactory & connectionObserverFactory)
Definition at line 131 of file ConnectionLoopBack.cpp.
References loopBackFactory, port, and services::ConnectionLoopBackFactory::RegisterListener().
         : port(port)
         , loopBackFactory(loopBackFactory)
         , connectionObserverFactory(connectionObserverFactory)
     {
         loopBackFactory.RegisterListener(port, this);
     }
~ConnectionLoopBackListener()
services::ConnectionLoopBackListener::~ConnectionLoopBackListener ()
Definition at line 139 of file ConnectionLoopBack.cpp.
References loopBackFactory, port, and services::ConnectionLoopBackFactory::UnregisterListener().
     {
         loopBackFactory.UnregisterListener(port);
     }
Member Function Documentation
Accept()
void services::ConnectionLoopBackListener::Accept (ClientConnectionObserverFactory & clientObserverFactory)
Definition at line 161 of file ConnectionLoopBack.cpp.
References services::ServerConnectionObserverFactory::ConnectionAccepted(), connectionObserverFactory, and services::IPv4AddressLocalHost().
     {
         struct Info
         {
             infra::SharedPtr<ConnectionLoopBack> connection;
             ClientConnectionObserverFactory& clientObserverFactory;
             infra::SharedPtr<services::ConnectionObserver> serverObserver;
         };
         Info info{ infra::MakeSharedOnHeap<ConnectionLoopBack>(), clientObserverFactory };
         connectionObserverFactory.ConnectionAccepted([&info](infra::SharedPtr<services::ConnectionObserver> serverObserver)
         {
             if (serverObserver)
             {
                 info.serverObserver = serverObserver;
                 info.clientObserverFactory.ConnectionEstablished([&info](infra::SharedPtr<services::ConnectionObserver> clientObserver)
                 {
                     if (clientObserver)
                         info.connection->Connect(info.serverObserver, clientObserver);
                 });
             }
             else
                 info.clientObserverFactory.ConnectionFailed(services::ClientConnectionObserverFactory::ConnectFailReason::connectionAllocationFailed);
         }, services::IPv4AddressLocalHost());
     }
Member Data Documentation
connectionObserverFactory
ServerConnectionObserverFactory& services::ConnectionLoopBackListener::connectionObserverFactory private
Definition at line 95 of file ConnectionLoopBack.hpp.
Referenced by Accept().
loopBackFactory
ConnectionLoopBackFactory& services::ConnectionLoopBackListener::loopBackFactory private
Definition at line 94 of file ConnectionLoopBack.hpp.
Referenced by ConnectionLoopBackListener(), and ~ConnectionLoopBackListener().
port
uint16_t services::ConnectionLoopBackListener::port private
Definition at line 93 of file ConnectionLoopBack.hpp.
Referenced by ConnectionLoopBackListener(), and ~ConnectionLoopBackListener().
The documentation for this class was generated from the following files:
ConnectionLoopBack.hpp
ConnectionLoopBack.cpp